### ISSUE TITLE
[Request] Prevent bot from walking

### ISSUE THREAD

**Issue by ilhamazdi** [Ar1i/PokemonGo-Bot#1]
Sometimes there are  3-4 Pokestops near each other that lured 24/7 non-stop.
I wonder if the bot can stay at some coordinate and only swipes those pokestops ? or maybe can set the walk radius from center position we've set before

**Comment by Ar1i** [comment]
Will take a look later at it, need to fix some Errors first. Thanks for the Request!

**Comment by ilhamazdi** [comment]
#
