### ISSUE TITLE
PTC account red error

### ISSUE THREAD

**Issue by Anomy1337** [Ar1i/PokemonGo-Bot#10]
[20:37:11] Unhandled exception: System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\Kilian\Desktop\Configs\LastCoords.txt" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bei System.IO.File.WriteAllText(String path, String contents)
   bei PokemonGo.RocketAPI.Client.SaveLatLng(Double lat, Double lng) in C:\Users\Kilian\Desktop\PokemonGO Accs\Google\XXX\PokemonGo.RocketAPI\Client.cs:Zeile 100.
   bei PokemonGo.RocketAPI.Client.SetCoordinates(Double lat, Double lng, Double altitude) in C:\Users\Kilian\Desktop\PokemonGO Accs\Google\XXX\PokemonGo.RocketAPI\Client.cs:Zeile 94.
   bei PokemonGo.RocketAPI.Client..ctor(ISettings settings) in C:\Users\Kilian\Desktop\PokemonGO Accs\Google\XXX\PokemonGo.RocketAPI\Client.cs:Zeile 50.
   bei PokemonGo.RocketAPI.Logic.Logic..ctor(ISettings clientSettings) in C:\Users\Kilian\Desktop\PokemonGO Accs\AScoundrelhd2@gmail.com\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 33.
   bei PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\Kilian\Desktop\PokemonGO Accs\Google\XXX\PokemonGo.RocketAPI.Console\Program.cs:Zeile 17.

total unregelmäßig manchmal auch direkt am start.. taucht aber immer wieder bei versch accs auf

**Comment by Ar1i** [comment]
Der Prozess kann nicht auf die Datei "C:\Users\Kilian\Desktop\Configs\LastCoords.txt" zugreifen, da sie von einem anderen Prozess verwendet wird.

- Steht doch schon da :p Öffnet irgendwas anderes die Datei?

**Comment by Anomy1337** [comment]
natürlich hab ichs mir selber durchgelesen aber tuts eben nicht
hab sogar die ganze ordnergliederung gemacht es kann keine datei von zwei bots genutzt werden

**Comment by Ar1i** [comment]
Okay, haue gleich nen Update raus welches es fixen sollte.

**Comment by Ar1i** [comment]
Sollte nun gehen, einmal testen
