### ISSUE TITLE
PROFILE INFO

### ISSUE THREAD

**Issue by darklordor** [Ar1i/PokemonGo-Bot#1000]
Well, your bot is incredible good, but i want to ask you if you can add anoter aplication to only make your profile information: what i mean is that i have a "good" account and i don't want to do any bot on it, but i like the ideo of having the profile info avaliable without having to put the bot. I think that all the comunity will apreciate it because it doesn't have any repercusion in teh game, is just a info doc.

i don't know if i have to ask that in the issues page, but i didn't found anything else to write you.
PD: i don't speak english a lot so if i haven't explained myself very good, please tell me

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
