### ISSUE TITLE
FAKE GPS

### ISSUE THREAD

**Issue by darklordor** [Ar1i/PokemonGo-Bot#1002]
Your bot is incredible, but i think that the GPS fact can be improved. When you star the bot you can add where do you want to go, but when i run it, my character goes there walking. So if i am in Manhattan and i want to go to China i have to wait 9999999999999999999 seconds to start working

**Comment by ShutUpPvP** [comment]
u can just teleport

**Comment by darklordor** [comment]
i have just read the "start walking form default place" thing
