### ISSUE TITLE
Time left until LEVEL UP

### ISSUE THREAD

**Issue by deezmasterballz** [Ar1i/PokemonGo-Bot#1003]
it would be nice to see real-time how much time is left until you reach the next level like in necrobot showing it next to stardust count.

**Comment by ShutUpPvP** [comment]
Dont think thats needed, since its pretty much random anyway, and u have the %until u lvl up.
Which is all u need i think.
Just my personal meaning.

**Comment by darklordor** [comment]
+1

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
