### ISSUE TITLE
What dos it means IV A-D-S ??

### ISSUE THREAD

**Issue by filoh** [Ar1i/PokemonGo-Bot#1005]

**Comment by darklordor** [comment]
iv is like your pokemon trainment, i don't know how to explain but if your pokemon have 31 iv in attack, him attack will be better tahn the samen pokemon wit the same attack but thiferent iv

A= atack
D=Defense
S=Stamina

**Comment by UltraVLT** [comment]
Attack, Defense, Stamina 15/15/15 is 100% IV

**Comment by JustPlaysDE** [comment]
^
