### ISSUE TITLE
Location Webpage

### ISSUE THREAD

**Issue by Provokan** [Ar1i/PokemonGo-Bot#1007]
Hallo, 

ich habe mir mal die mühe gemacht und einige gute Locations, die ich auch überprüft habe
in einer Liste verfasst. Es ist denke ich, vom Vorteil diese für andere User zu integrieren,
oder die im Bot via APi einzubinden, so dass man durch einen klick die richtige Location
direkt hat. 

Die Liste wird täglich aktualisiert und neue Standorte eingebunden.

poke.game-junkies.de

**Comment by UltraVLT** [comment]
Eine sehr schöne Arbeit.Es wäre nett wenn du diese Liste bei https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ postest,damit es Ar1i leichter hat.

**Comment by Provokan** [comment]
Habe den Thread Ersteller, Raddat. bereits eine Nachricht dort hinterlassen mit dem verweiß auf diese seite (:

**Comment by JustPlaysDE** [comment]
^
