### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Burrito159** [Ar1i/PokemonGo-Bot#101]
Hey, I open this up with VS 15, and I click on "Start" and I get this error:

http://image.prntscr.com/image/e89d1ab49b01449398b10c12078406da.png

**Comment by SlDracon** [comment]
Set PokemonGo.RocketAPI.Console as Startup Project.

**Comment by Burrito159** [comment]
@SlDracon Like this?

http://prntscr.com/bypl1w

If so, it still gives me that error

**Comment by Burrito159** [comment]
Nevermind, I got it!

**Comment by SlDracon** [comment]
![image](https://cloud.githubusercontent.com/assets/7977620/17222665/c5e88c16-54f9-11e6-992e-17a932a44fd1.png)

**Comment by SlDracon** [comment]
ok.

**Comment by Burrito159** [comment]
@SlDracon Thank you though, almost immediately after I posted that, I figured it out.. Lol
