### ISSUE TITLE
*QUESTION* Help for translation

### ISSUE THREAD

**Issue by LemonAdd** [Ar1i/PokemonGo-Bot#1010]
Hi !
I love your work and I want to know if you need help for translations. I can help you for french stuffs ^^.
See you again !

**Comment by jief78** [comment]
hello i want to help to but i cant find the pokemon list translation.

**Comment by xJustx** [comment]
You can't translate the pokemon names.
If you want to translate the others stuff, you can take a .json file in the Translations-folder, translate it and do a pull request.
