### ISSUE TITLE
Tranfer and Evovle Bug!

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#1012]
I let the bot running for a few hours and the inventor was full so i decided to tansefer some Pokémons. I guess because the inventory wasnt refreshed i got this error.
![unbenanntdasd](https://cloud.githubusercontent.com/assets/20752818/17344196/94736f82-5901-11e6-9f1c-d0cf60d35472.PNG)

Kinda the same thing happen when u try to evolve a Pokemon.

         Maybe its because the Pokemon i try to do something with isn't there anymore.

**Comment by UltraVLT** [comment]
First reload the GUI,then manually transfer and evolve

**Comment by jordanpillefernandez** [comment]
You have to reaload before or check reload every 60s
