### ISSUE TITLE
Catch pokemon when the pokestop is disabled (for 5m)

### ISSUE THREAD

**Issue by Akikazuu** [Ar1i/PokemonGo-Bot#1013]
![sans titre](https://cloud.githubusercontent.com/assets/15688823/17344124/5d1e9480-5901-11e6-94df-7996f7994967.png)

Hi, i m french , i love ur hack (im in a IT school ^^) .

Look the picture, i want to stay in the middle of this 3 pokestops to catch all the pokemon spowned when the pokestop is disabled (in this spot lure is h24/d7) for the basically 5 minuts 

The hack found the pokestop buyt when he take it , he dont want catch teh pokemon and say "we cant find pokestop ..."

Do u understand me ? thx mate ! 

setting bot : (location in the middle of this)
                    set radius at 50meter (i calculate on radius maps)
                    10km/h

**Comment by FAymYs19** [comment]
yeah that would be a nice feature too.

**Comment by Akikazuu** [comment]
I think make an option : walk to the pokestop visited ( for camp a 3-4-5 or more pokestop for farm the place who lure are)

**Comment by CowMadness** [comment]
hey, excuse moi mais ma question est hors contexte.. J'aimerais savoir comment tu as fait pour avoir ton jeu sur ecran. (Comme à gauche de ton screenshot) 
On dirait que tu joue sur ton telephone mais directement sur l'ordi.
Peux-tu m'expliquer?

**Comment by Akikazuu** [comment]
@CowMadness : il suffit de télécharger nox (il y a des tuto sur YouTube)

**Comment by CowMadness** [comment]
Est-ce qu'il y a un même type d'application mais pour un Iphone?

**Comment by Akikazuu** [comment]
Oui le jeu tout simplement, nox cest pour Windows .

**Comment by FAymYs19** [comment]
I think u can trick the bot when u set the speed to "0" and the range to like "100"

**Comment by FrancYescO** [comment]
i think @FAymYs19 is right, bot is ever checking for pokemons also if no pokestop usable found

**Comment by Akikazuu** [comment]
@FrancYescO @FAymYs19 Dont work !

**Comment by FAymYs19** [comment]
worth a try ^^

**Comment by Akikazuu** [comment]
@FAymYs19 I try , and dont work rly good, but if include the option in the hack, the hack become rly better !
