### ISSUE TITLE
bug console/pokemonlist?

### ISSUE THREAD

**Issue by emilie253** [Ar1i/PokemonGo-Bot#1014]
Hello, in my console, i read : eevee captured (41 pc---93%) but nothing in my pokemon list (only one eevee 47--97 %).

I dont transfer pokemin with IV> 90% , so he is dont transfer.

can you explain me?
ty

**Comment by UltraVLT** [comment]
Reload button

**Comment by emilie253** [comment]
yes, i know ^^ but after 10 reload, nothing.

**Comment by FrancYescO** [comment]
and how many evee have can you see in the list? probably you have seen wront when catched.

**Comment by emilie253** [comment]
4 eevee (3 with my option) and 1 because >90%.
No wront, i travel in my console and it's 41pc-93%

**Comment by FrancYescO** [comment]
how many cp the 3 left ? are you using latest build?
