### ISSUE TITLE
EncounterNotInRange

### ISSUE THREAD

**Issue by Chompdron** [Ar1i/PokemonGo-Bot#1015]
I can't use the bot because when it tries to catch a Pokemon it shows "EncounterNotInRange" and the Pokestops don't work.

https://gyazo.com/8345fb62a751be5d4c2523a341832737

**Comment by UltraVLT** [comment]
I'd say you are softbanned,wait 'till he detects and clears it first.

**Comment by JustPlaysDE** [comment]
What is your speed in the location settings?

**Comment by Chompdron** [comment]
i'm having this problem since 4 days.
My speed is 10km/h

**Comment by Tochez** [comment]
try changing the location

**Comment by FAymYs19** [comment]
maybe go for something like 200 km/h
im useing it with no problems

**Comment by Chompdron** [comment]
Neither worked, even with other account

**Comment by rihanboo** [comment]
see if https://github.com/Ar1i/PokemonGo-Bot/issues/849 works for you
