### ISSUE TITLE
request  hit of each attack

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#1017]
Is possible to put in the list the hit of each attack (and  count number of special attack) ?
For example 
28;Sandslash;;649/724;"39,00";MudShotFast (6);RockTomb (50/ 3) .....

to know what drop with similar perfection percentaje

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
