### ISSUE TITLE
soft ban?

### ISSUE THREAD

**Issue by lucasxvieira** [Ar1i/PokemonGo-Bot#1018]
Detected a Softban????

why did i get soft banned, in the first place??
i thought this program don't get you banned

**Comment by UltraVLT** [comment]
When you bot in obvious locations like new york and/or use no proxy for other countries,you do get softbanned,but it's okay since the programm can unban you.So don't worry and happy botting :)

**Comment by xJustx** [comment]
If you change your location you will get softbanned.
But the bot has a special 1337 softunban method ;) 
So run the bot und he will unban you automatically
