### ISSUE TITLE
Help: have this error code, dont know why

### ISSUE THREAD

**Issue by shibby1889** [Ar1i/PokemonGo-Bot#102]
![capture](https://cloud.githubusercontent.com/assets/20709248/17223685/8e2e0496-54b2-11e6-9804-0fe83748f94c.PNG)

**Comment by istatro3428** [comment]
Im having the same problem, any fix?

**Comment by shibby1889** [comment]
none yet, haven't been able to figure it out

**Comment by istatro3428** [comment]
anyone else having this problem or know how to fix it

**Comment by shibby1889** [comment]
still haven't figured it out

**Comment by Ar1i** [comment]
server are laggy or down.
