### ISSUE TITLE
Reported that guy who steals your code as unsafe

### ISSUE THREAD

**Issue by yazeed** [Ar1i/PokemonGo-Bot#1020]
https://www.dropbox.com/s/jj4yecmbdus0os2/Screenshot%202016-08-03%2000.52.17.png?dl=0

**Comment by FAymYs19** [comment]
![unspecified](https://cloud.githubusercontent.com/assets/20752818/17346923/5377eace-590d-11e6-8350-c0621cc9f52f.png)

**Comment by danielalvenstrand** [comment]
Now we just need the bot to DDoS the site ;) joking...
