### ISSUE TITLE
Pokémon List reloads if "Reload every xx s" is check even if other action is in play.

### ISSUE THREAD

**Issue by danielalvenstrand** [Ar1i/PokemonGo-Bot#1022]
Hi,

I would like the pokémon list feature to _not_ reload when I've pressed Evole, PowerUp, Full-PowerUp or Transfer, even if the "Reload every xx s" is checked. This freezes the application if the two actions collide or the other action will be canceled. Maybe make it wait until it's done?

**Comment by danielalvenstrand** [comment]
Now we just need the bot to DDoS the site ;) joking

**Comment by FAymYs19** [comment]
@danielalvenstrand DDoS xD

**Comment by danielalvenstrand** [comment]
@FAymYs19 sorry I commented on the wrong Issue! Haha...

**Comment by xJustx** [comment]
It's not possible to not reload the list if you pressed one of the buttons. Sorry!

**Comment by danielalvenstrand** [comment]
@xJustx well, the problem was that it automatically was reloaded _even if_ another action is in play. So the list _does_ reload even if I've pressed the other buttons, as long as the "Reload every" checkbox is checked.
