### ISSUE TITLE
Errors Errors and MORE Errors .....

### ISSUE THREAD

**Issue by CP02A** [Ar1i/PokemonGo-Bot#1023]
I get this error:
http://www.hastebin.com/wiyativifa.tex

**Comment by xJustx** [comment]
Wait some minutes and try it again please

**Comment by CP02A** [comment]
It works now

**Comment by CP02A** [comment]
My pc went to sleep and then when I woke it up I saw this

**Comment by CP02A** [comment]
How is this closed?

**Comment by CP02A** [comment]
O well
