### ISSUE TITLE
Error reloading Pokemon list?

### ISSUE THREAD

**Issue by mathiaas** [Ar1i/PokemonGo-Bot#1026]
http://i.imgur.com/8CMfLTp.png

I can't use the bot as it just shows "Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing".

**Comment by rlmrso** [comment]
Create new folder place latest update in a new clean folder ! worked for me.

**Comment by mathiaas** [comment]
@rlmrso Tried that, didn't help. :/
