### ISSUE TITLE
Romanian translation JSON file

### ISSUE THREAD

**Issue by BeReLaxed** [Ar1i/PokemonGo-Bot#1028]
[Romanian.zip](https://github.com/Ar1i/PokemonGo-Bot/files/398313/Romanian.zip)

**Comment by xJustx** [comment]
Please do a pull request

**Comment by BeReLaxed** [comment]
I'll do it this morning. Actually it's 3.55

Il 03/Ago/2016 03:52, "xJustx" <notifications@github.com> ha scritto:
