### ISSUE TITLE
Google sign in problem (Help please)

### ISSUE THREAD

**Issue by sufficey** [Ar1i/PokemonGo-Bot#1029]
This has been happening for 2 days: http://prntscr.com/c0qugr
I've been patient, re-trying it every few hours, using the newest version, still doesn't work. Any ideas?

**Comment by mathiaas** [comment]
Same thing here.

**Comment by elenex23** [comment]
You may want to find the tutorial video and just retry from scratch. If you know your telegram bot is okay due to experience you maybe able to skip that portion.

**Comment by xJustx** [comment]
#856
