### ISSUE TITLE
Can we Gym Battle with the Bot?

### ISSUE THREAD

**Issue by JunoBotboy** [Ar1i/PokemonGo-Bot#1031]
Gym Battle may raise the suspicion of another player thats actually @ the Gym point o that player thinks he fighting a player while the player used "[Phantom Force](http://bulbapedia.bulbagarden.net/wiki/Phantom_Force_(move))"

That's a little pokeJoke for you today. Enjoy it.

**Comment by elenex23** [comment]
No you cannot.

**Comment by xJustx** [comment]
Currently you can't.
