### ISSUE TITLE
Nullreferenceexception movenext()

### ISSUE THREAD

**Issue by amuessig** [Ar1i/PokemonGo-Bot#1033]
Hi,

an error encounters quite frequently, see screenshot: http://prnt.sc/c0vaho

Thanks

**Comment by FrancYescO** [comment]
server issue.

**Comment by Smux** [comment]
I also have this error since 30 minutes ago...
so this is really a server issue?

**Comment by elenex23** [comment]
It normally fixes itself. If not restarting the bot should fix.

**Comment by xJustx** [comment]
^
