### ISSUE TITLE
Google code problem

### ISSUE THREAD

**Issue by Koopler123** [Ar1i/PokemonGo-Bot#104]
So I've been looking around and it seems like people fixed the google problem...but when I input my e-mail and password for the new update, it launches gmail but nothing shows up and says this:

The setting you are looking for is not available for your account.

Any clue how to fix this?

**Comment by RealKayos** [comment]
Same I cant find a fix.

**Comment by RealKayos** [comment]
Was working fine yesterday

**Comment by RealKayos** [comment]
Mine is working now I think I found a fix..
I changed my password to my gmail then tried doing it again and it worked

**Comment by Koopler123** [comment]
What do you mean by changed your password to your gmail?

**Comment by RealKayos** [comment]
Go to your gmail and change the password then start up the pokemon go bot and just try it again with the new password worked for me

**Comment by RealKayos** [comment]
work??

**Comment by Koopler123** [comment]
Nope didn't work for me, the google webpage just doesn't show the option to generate an app password... Thanks though.

**Comment by Ar1i** [comment]
Load newest Version.
