### ISSUE TITLE
How about add egg list

### ISSUE THREAD

**Issue by winsonlcy** [Ar1i/PokemonGo-Bot#1045]
i find the egg qty in latest version, how about add egg list for hatch egg?
btw good bot

**Comment by OGcpalm** [comment]
suggestions go on the likeminded thread, he also made a comment about this saying after they get the new API

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
