### ISSUE TITLE
Softban Removal

### ISSUE THREAD

**Issue by willmlocke** [Ar1i/PokemonGo-Bot#1051]
Hey! Love the program! Works like a charm!!! But they soft ban removal system could use a little tweaking. Im no too worried because I can just use the soft ban removal trick already in the game. But could definitely use some work! Thanks!

**Comment by CP02A** [comment]
What is the problem with it? It works... And what exactly needs tweaking?

**Comment by willmlocke** [comment]
I closed the program to go cap some gyms and it seemed to have not removed my soft ban. It may have been a previous 12 hour ban (location spoofing) but that happened 3 days ago. I'll keep you posted. I don't have the ban any more and I'll be running the program all night. I'll post anymore updates in the morning (or if I decide to get on later tonight)

**Comment by willmlocke** [comment]
Just logged on and had an active soft ban. The only thing that would've caused it is the program

**Comment by CP02A** [comment]
I think they knew that you teleported thats why you got soft banned when you went on your phone

**Comment by willmlocke** [comment]
Shouldn't all users of the program be getting soft banned in that case? Not to down talk the program just trying to provide constructive criticism

**Comment by immoempe** [comment]
willmlocke, if your account (in the bot) are a bit distant from your real location, and you opened the app in your phone (or viceversa), or if you changed the location too fast, you will get a softban

**Comment by willmlocke** [comment]
That really helps! Could you explain how to change my location?

**Comment by immoempe** [comment]
You can check the location of your account in the pokemon gui clicking the map icon, or checking the file LastCoord.txt (located in Configs file). Softbans due to this condition (travelling too quick inside the same city) finishes in some minutes

**Comment by willmlocke** [comment]
Any recommended distance max from where I am at?

**Comment by immoempe** [comment]
I use 3000 - 5000m, but I wait some minutes if I need to open the app in my phone

**Comment by willmlocke** [comment]
Thank you so much for the support!

**Comment by xJustx** [comment]
^
