### ISSUE TITLE
[SUGGESTION] Default localisation

### ISSUE THREAD

**Issue by Meowrouane** [Ar1i/PokemonGo-Bot#1059]
deleting default localisation and forcing the user to set one at the first install would be nice
softbanned for the second time now
and the 1337 methode is not working :/

**Comment by pokerave** [comment]
#1057 you can do this. :) delete the lastcoords in the config folder.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
