### ISSUE TITLE
[NO ISSUE] pokecrot.com - Removal of domain + bot

### ISSUE THREAD

**Issue by zunox** [Ar1i/PokemonGo-Bot#1060]
Alright so i appreciate what you do for everyone here. So ill post some information and see if it helps.

![screen shot 2016-08-03 at 12 53 50 am](https://cloud.githubusercontent.com/assets/11843564/17354287/324f87a0-5915-11e6-9107-6c57f22e2376.png)

They hide behind cloudflare but nothing is a secret. They seem to be the same people that run vip-spuc3ngine.co* since they are using their DNS. 

![screen shot 2016-08-03 at 12 59 06 am](https://cloud.githubusercontent.com/assets/11843564/17354327/85c28f5e-5915-11e6-8d83-c0abddbdd089.png)

But vip-spuc3ngine.co* seems to move around a lot as you can see the DNS changes. 

The owner of the site is:

https://www.facebook.com/NewMessa.Harianto?fref=nf

Look at all his post. :) So i went ahead and spammed OVH since his VPS is located with them in Canada. Ill keep trying new things oh and his email is messaharianto@icloud.com

**Comment by Logxn** [comment]
[http://image.prntscr.com/image/a1b5663e1bc441d9a2862f1d5ca105bb.png](image)

**Comment by zunox** [comment]
Image doesnt load.

**Comment by DeltaCore** [comment]
Am i the only one how can't reach the pokecrot site anymore :P ?
Even the google dns gave me timeouts when i wanted to nslookup pokecrot ?

**Comment by DeltaCore** [comment]
Update: when i use nslookup from my server it still gives me an IP, but i think 99% are using the google dns, my server has aperently an old DNS-Cache:
![unbenannt](https://cloud.githubusercontent.com/assets/5575913/17367584/d07acfe0-5990-11e6-8712-99f401a935c7.PNG)

**Comment by zunox** [comment]
The site is down. Maybe when i talked to OVH helped lol i told them i was gonna sue them lol

**Comment by Logxn** [comment]
They contacted me they'd take down the site.

RiP fear logxn.
