### ISSUE TITLE
RazzBerries not counting down on single Pokémon

### ISSUE THREAD

**Issue by danielalvenstrand** [Ar1i/PokemonGo-Bot#1063]
Hi,

I found an issue where the number of RazzBerries does not show the lowered amount (if used) when catching a pokémon. Only _after_ the pokémon is caught and the berries are used on another pokémon, the correct amount will be displayed:

![image](https://cloud.githubusercontent.com/assets/14288758/17356653/f0d94006-5958-11e6-843a-b6707a2276f5.png)

So it actually uses the berries (as seen when catching CP 299 Raticate) but it doesn't show when catching the CP 228 Raticate.

**Comment by FrancYescO** [comment]
I already noticed that...was waiting for some PR to fix
