### ISSUE TITLE
Admin Permission

### ISSUE THREAD

**Issue by jmpb032** [Ar1i/PokemonGo-Bot#1064]
how do u remove the admin permission thing like u mentioned in here?
https://github.com/Ar1i/PokemonGo-Bot/issues/985

because i currently dont have the admin rights on my parents computer

**Comment by erucquoy** [comment]
Same problem :/

**Comment by Logxn** [comment]
Locate file "app.manifest" in visual studio.

Edit this line: 
'<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />'

to
'<requestedExecutionLevel level="asInvoker" uiAccess="false" />'

If shit doesnt work correctly its your own fault

**Comment by stormlolz** [comment]
If its possible to have two exe in next build, one with admin and the other for us...
thank you

**Comment by jmpb032** [comment]
We do not have Visual Studio

And downloading it needs Admin Permissions.
so i still cant change it,,

**Comment by stormlolz** [comment]
cannot find a c# compiler portable..

**Comment by stormlolz** [comment]
Okay with last build... thx a lot

#close

**Comment by xJustx** [comment]
^
