### ISSUE TITLE
faster way to remove softban

### ISSUE THREAD

**Issue by whirlpool7381** [Ar1i/PokemonGo-Bot#1068]
I want to post exact coordinates to catch a rare pokemon but i am always softbanned at first and can't get it.. is there a way to remove the softban at first or to wait somehow until i get to the specific pokemon

**Comment by whirlpool7381** [comment]
i'm pretty sure there is a file that i can edit that detects softban after 6(ithink) errors and i can fix it from there to 2 for example, can anyone tell me which file is that and what currency should i switch

**Comment by Logxn** [comment]
You need to set up sniper correctly, otherwise you will always get banned.
You need to have the same location in the sniper config as you had in your bot.
And dont let them run both at the same time.

**Comment by whirlpool7381** [comment]
how do i set up the "sniper" im not sure what that is?

**Comment by Logxn** [comment]
Oh I now understand,
you cant just set "exact" locations. You will get softbanned either way.
Even with manual unban button

**Comment by whirlpool7381** [comment]
im fine with being banned for a while but it usually takes too long to get me unbanned and i miss the rare that i want
