### ISSUE TITLE
Please add new language : Bahasa

### ISSUE THREAD

**Issue by hatrednuow** [Ar1i/PokemonGo-Bot#1069]
{
"accountType":"Piih Akun:",
"username":"Nama Pengguna:",
"password":"Sandi:",
"locationSettings":"Pengaturan Lokasi",
"speed":"Kecepatan.:",
"moveRadius":"Radius:",
"meters":"Meter",
"startFromDefaultLocation":"Mulai dari lokasi awal",
"botSettings":"Pengaturan Bot",
"autoTransferDoublePokemon":"Otomatis Transfer Pokemon yang berganda",
"maxDupPokemon":"Maks. Pokemon berganda",
"maxCPtransfer":"Max. CP untuk transer:",
"maxIVtransfer":"Max. IV untuk transer:",
"telegramSettings":"Setting Telegram",
"infoline1":"Bot ini akan selamanya gratis, jika berbayar, minta kembali uang anda!",
"infoline2":"Bot dengan nama 'Pokecrot' adalah versi bajakan dari Bot ini.",
"maxPokeballs":"Pokeball Maks:",
"maxGreatballs":"Superball Maks:",
"maxUltraballs":"Ultraball Maks:",
"maxMasterballs":"Masterball Maks:",
"maxRevives":"Revive Maks:",
"maxTopRevives":"Top Revive Maks:",
"maxPotions":"Max. Tränke:",
"maxSuperpotions":"Superpotion Maks:",
"maxHyperpotions":"Hyperpotion Maks:",
"maxToppotions":"Top Potion Maks:",
"maxRazzberrys":"Razzberrys Maks:",
"totalCount":"Total:",
"pokemonNotToTransfer":"Pokemon - Yang tidak di Transfer",
"selectAll":"Pilih Semua",
"pokemonNotToCatch":"Pokemons - yang tidak ditangkap",
"pokemonNotToEvolve":"Pokemons - yang akan di Evolusi",
"saveConfig":"Simpan Pengaturan / Jalankan Bot",
"otherSettings":"Pengaturan Lainnya",
"useLuckyeggAtEvolve":"Pakai Lucky Egg untuk Evolusi",
"germanPokemonNames":"Pokemon dengan Nama Jerman",
"useIncese":"Gunakan Incense tiap 30 menit",
"evolvePokemonIfEnoughCandy":"Evolusi Pokemon jika Candy Tercukupi",
"enablePokemonListGUI":"Tampilkan List GUI Pokemon",
"keepPokemonWhichCanBeEvolved":"Simpan Pokemon yang dapat di Evolusi"
}

**Comment by fourcom** [comment]
jangan dibisnisin dan bikin malu doang bro kaya pokecrot.com hahaha

**Comment by xquiaz** [comment]
gak usah biarin aja bahasa inggris, dari pada banyak bocah sok sok an pake bot.

** for dev, skip this issue hahaha.

**Comment by hatrednuow** [comment]
he?? yang bisnisin siapa?

**Comment by xJustx** [comment]
Please do a pull request - thank you!
