### ISSUE TITLE
Error Loading Pokemon List : Out of memory

### ISSUE THREAD

**Issue by AndreLuminosity** [Ar1i/PokemonGo-Bot#1070]
I use the latest 1.0.6.0 build, and I encountered this issue... is there anyone having the same issue?

How can I fix this?

Thanks before
![capture](https://cloud.githubusercontent.com/assets/20811479/17358559/cd511828-598c-11e6-8e5b-b0651ecba781.JPG)

**Comment by Logxn** [comment]
You cant, its the pokelist server.

@Ar1i

**Comment by HaydarOzturk** [comment]
Actually I don't think that it's the server. People who download from other sources are encounters this problem as I can tell. I helped few of them and when they download from original source it was resolved. Try to download latest version

**Comment by Dexter13425** [comment]
I have the same issue with the latest version and I dowloaded from original source

**Comment by VinCySrOw** [comment]
Same here, memory issue when reloading pokemon list, even with the newest version (03.08.17.10).

**Comment by goOFYy** [comment]
i'm having the same issue any solution ?
