### ISSUE TITLE
can help for French Translate & French Pokemon List

### ISSUE THREAD

**Issue by keustii** [Ar1i/PokemonGo-Bot#1071]
I think all are in the tittle. :)

one more thing:
i try to change the GerName Into, but it look doesn't why ? 
\PokemonGo.RocketAPI.Logic\Utils\StringUtils.cs

Thx.

**Comment by IceQ1337** [comment]
There is a frensh translation already. Only the GUI itself gets translated currently.
If we add more translation features in the future, you can contact us again.

**Comment by keustii** [comment]
thx Ice. 
really reactive, very nice. <3
