### ISSUE TITLE
hi bot is not transfering pokemon by itself 

### ISSUE THREAD

**Issue by sammode** [Ar1i/PokemonGo-Bot#1072]
hi bot is not transfering pokemon by itself .

**Comment by thepeople03** [comment]
im also having trouble on the bot not transferring all pokemons i want, it inly transfers 3 of the same pokemons? help please

**Comment by IceQ1337** [comment]
Uncheck "Keep Pokemos Which Can Be Evolved"

**Comment by sammode** [comment]
i mean the low cp pokemon like cp10
