### ISSUE TITLE
I heard About how to Move Without Softban ... This Is It..

### ISSUE THREAD

**Issue by fourmansyah** [Ar1i/PokemonGo-Bot#1073]
sorry About this But i just want to Help everybody in Here... And I make This Video :D 
I did not mean to but Its Works kwowkwk :smile:
And this is the link : 
https://www.youtube.com/embed/5Fzk3sRKh7o
#1068

**Comment by Logxn** [comment]
This song hurts my ears.

**Comment by fourmansyah** [comment]
@Logxn Sorry ... kwokwokw :D Just Turn Off the Songs ...

**Comment by fourmansyah** [comment]
But If u Move City Or country Permanent,  Just Us Fake GPS spoofer ... And U Move Location Dont Use The Map From emulator But User Map From Fake Gps Spoofer....

**Comment by xJustx** [comment]
not an issue
