### ISSUE TITLE
Multi column sort

### ISSUE THREAD

**Issue by hightechpresha** [Ar1i/PokemonGo-Bot#1074]
Sehr nett wäre wenn man die Pokemon Liste nach CP und IV sortieren könnte.

Einen Ansatz findet man hier: http://www.codeproject.com/Articles/18440/DataGridView-Multi-column-Sort

**Comment by UltraVLT** [comment]
Vorschläge hier posten: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Danke :)

**Comment by xJustx** [comment]
^
