### ISSUE TITLE
Language Highlighting

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#1076]
Klickst du auf die GB Flagge wird Deutschland mit schwarzem Balken gehighlighted
Klickst du auf DE dann Spanien
Spanien => Brasilien
Brasilien => Döner
Döner => Vodka
Vodka => Baguette
Baguette => Tee

Eigentlich müsste das gehighlighted werden, was gerade aktiv ist.

**Comment by subix** [comment]
Dafür sollst du wahrscheinlich eine Pullrequest öffnen da das ja nur eine schönheitsanpassung ist

**Comment by Logxn** [comment]
Ar1i weiß , dass ich keine Ahnung von Pullrequests hab :D 
Bin kein Githubnerd ^^
