### ISSUE TITLE
Telegram doesnt work (You have no power here)

### ISSUE THREAD

**Issue by SimonSCLT** [Ar1i/PokemonGo-Bot#1079]
Hello,
I can't use Telegram in ur bot, however the settings are good:
![image](https://cloud.githubusercontent.com/assets/17403445/17361126/1794af76-596f-11e6-8b26-0e51f086b989.png)

Have you got a answer?

Thanks

**Comment by Provokan** [comment]
its work :) u make it wrong. I use this from beginning-

**Comment by SimonSCLT** [comment]
Look carefully at my screenshot, there is a line with the command that I sent with Telegram, so communication is good between the two programs no?

**Comment by ThmsD** [comment]
You have to set your Telegram name in the gui!

**Comment by Provokan** [comment]
Set you Telegram Name, which u kontakt the bot !

I Provokan send a Commad to Provo91_bot and my Results is the Stats of the cmd

**Comment by Ar1i** [comment]
^this, you dont have a telegram nickname
