### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by TehVipRz** [Ar1i/PokemonGo-Bot#108]
Hello Operator,

Please can you explain to me what exactly the telegram is?
And how I can get it to work.

I want to be able to port it so that I can display the COMMAND LINE interface FROM MY WEBSITE, to show me how my bot is doing on my RDP.

Thank you.

**Comment by maekzi** [comment]
Hey TehVipRz,

[Telegram](https://telegram.org/) is a Messaging Client like Whatsapp.

So when you set it up and download the Client on your Phone or the Win Client you can get information about how the bot is doing sent to you via this service.

To set it up you simply:

1. Download Telegram and set it up with your Phone number
2. Search for BotFather in Telegram and start a conversation
3. type `/newbot` and follow instructions in giving your bot a name and a username
4. Take the given API Key and paste it into the Bot along with your Telegram username
5. Start the Pokebot and search for your Telegram bot on Telegram like you did with BotFather and simply write him a msg.

**Comment by TehVipRz** [comment]
Hello,

Thanks for the reply.

I've tried that, just said I did not hear you? And says I sent a request in the console and doesn't give me any updates :(

Thanks.

Sent from my iPhone

On Jul 28, 2016, at 11:03 PM, maekz! <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey TehVipRz,

Telegram<https://telegram.org/> is a Messaging Client like Whatsapp.

So when you set it up and download the Client on your Phone or the Win Client you can get information about how the bot is doing sent to you via this service.

To set it up you simply:

  1.  Download Telegram and set it up with your Phone number
  2.  Search for BotFather in Telegram and start a conversation
  3.  type /newbot and follow instructions in giving your bot a name and a username
  4.  Take the given API Key and paste it into the Bot along with your Telegram username
  5.  Start the Pokebot and search for your Telegram bot on Telegram like you did with BotFather and simply write him a msg.

-

**Comment by XxAirWalker26xX** [comment]
Same thing hopefully someone can help us
