### ISSUE TITLE
Error reloading Pokemon list : Mémoire insuffisante

### ISSUE THREAD

**Issue by Dexter13425** [Ar1i/PokemonGo-Bot#1080]
Hi since this morning I have an error on the bot 

http://image.noelshack.com/fichiers/2016/31/1470218028-capture.png

I don't know why because my  RAM is not full and I've never got this error before.

**Comment by pokerave** [comment]
Try to upgrade to new version

#1070 
#957

**Comment by Dexter13425** [comment]
This is a new version !
