### ISSUE TITLE
- Bug Pokemon List - 

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#1083]
If I choose:

**Auto transfer double Pokemon and**
**Max duplicate Pokemon 1**
**[Keep Pokemon which can be evolved = unchecked]**

I still have many many **Zubat** and **Eevee** for example!
So my inventory is full after some hours.

Any idea?

**Comment by stickmick12** [comment]
mee to -_-

**Comment by HuDiNi27** [comment]
You have them checked on the do not transfer list?

**Comment by lailaps** [comment]
No, nothing like Zubat or Eevee. They are almost worthless.

**Comment by lailaps** [comment]
If I would choose **do not catch** Magikarp for example, would I still get the XP for the Pokemon?

**Comment by pokerave** [comment]
Check the CP with your CP XXX to be transferred and IV  to % IV to be transferred.

**Comment by alperemre** [comment]
same problem I have many magikarp #987
