### ISSUE TITLE
"The Process cannot access the File"

### ISSUE THREAD

**Issue by cirnolp** [Ar1i/PokemonGo-Bot#1084]
Yup. It's like the title. The bot can't access the file "LastCoords.txt".
I already deleted the file so the Bot can create a new one, but even without the file present, the bot throws the exception to my face.

Link to the detailed error:
http://pastebin.com/tc2UW9pv

(After " We got the API Url .....", the bot freezes.)

**Comment by Ar1i** [comment]
restart pc, or stop any other bot running in the same directory

**Comment by cirnolp** [comment]
Already did the stuff above, if I access the file with other tools I can modify and save without any problems.
