### ISSUE TITLE
Norwegian language json file

### ISSUE THREAD

**Issue by roflnoob** [Ar1i/PokemonGo-Bot#1085]
Didn't know where to post this so I'm sorry if I'm causing any inconvenience by putting it here :s

Anyhow, here is the json.
https://dl.dropboxusercontent.com/u/32506436/PokeBotNOjson/no.json

**Comment by OSDemirci** [comment]
Hello, It is better to fork the project, add your translation to your fork and create a pull request from [Pull Requests Page](https://github.com/Ar1i/PokemonGo-Bot/pulls)

**Comment by xJustx** [comment]
^
