### ISSUE TITLE
Add Pokemon Numbers in Pokemon list window

### ISSUE THREAD

**Issue by Firestart3r** [Ar1i/PokemonGo-Bot#1087]
So the pokemon list can be sorted by pokemon number

**Comment by UltraVLT** [comment]
You mean by pokedex? Isn't really needed at all in my opinion Oo

**Comment by Firestart3r** [comment]
It woud be nice to have **B**ellsprout next to **W**eepinbell and **E**evee next to **V**aporeon and so on. it would make things easier for those who just want to automate walking not all the decisions

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
