### ISSUE TITLE
Ar1i new update idee

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#1089]
Put the egg for pokemons in and it msut be say all 60 sek etc... how mutch km left etc?

**Comment by stickmick12** [comment]
also der soll die ausbütung etc anzeigen

**Comment by UltraVLT** [comment]
Die Idee gibts schon oft.Poste die Idee auf https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/  wenn du möchtest :s
