### ISSUE TITLE
[Problem] Error when starting with restart script

### ISSUE THREAD

**Issue by magiccube007** [Ar1i/PokemonGo-Bot#109]
If i start with the restart script i get this error: http://prnt.sc/byrnhs
What am i doing wrong or is it a glitch?

**Comment by shibby1889** [comment]
looks like you might have messed up your loggin info

**Comment by magiccube007** [comment]
if i start it with out the script and just hit save it works fine

**Comment by SpoderPig** [comment]
i had this, you have inputted a wrong password for your account

**Comment by magiccube007** [comment]
i checked it again and it is correct ... and as i said before when i sart it without the script or without -nogui  it works just fine

**Comment by kuan098760** [comment]
that is weird...I have the exact same issue....I did put my account info correctly. Could it be that the servers are down now?

**Comment by djdomrep** [comment]
your authentication information is wrong. retype your acc and password

**Comment by kuan098760** [comment]
plop.....i just remember that i had caps lock on!!!!!!!!!!!!!!

**Comment by e0xe** [comment]
![affichage de la tache](https://cloud.githubusercontent.com/assets/20713996/17233509/b4895770-5530-11e6-9eca-df50ca3431fa.jpg)
and this in 4 bot I dont understand *W*

**Comment by e0xe** [comment]
![bcreuso level 17 - 1615 20000 8 stardust 37400 exphour 1423 exp pokemonhour 7 pokemon s](https://cloud.githubusercontent.com/assets/20713996/17233540/f549b674-5530-11e6-9703-1f782c4717c0.jpg)
for better resolution

**Comment by djdomrep** [comment]
did you update?
