### ISSUE TITLE
Making a Route ?!?

### ISSUE THREAD

**Issue by Jam1ePistol** [Ar1i/PokemonGo-Bot#1090]
Hello there , i am sorry for the noob question in advance :) I wanted to know if it is possible to make a route for example around the sea or close to the river line for catching magicarps without the bot going towards other directions >

**Comment by UltraVLT** [comment]
It isn't possible yet.But you could suggest it at https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ .

**Comment by Jam1ePistol** [comment]
thanx alot for the fast reply ! :) Another question , since i havent opened the account on a mobile before using the bot am i going to have any issue ? I never changed from my city thought etc

**Comment by zunox** [comment]
You will be fine. Worse case scenario you get a soft ban and that you can remove in minutes.

**Comment by UltraVLT** [comment]
You can set your gps off and login without worrying about a softban.

**Comment by Jam1ePistol** [comment]
Since you are all so kind , might as well ask smth final :P in a week i am going on vacation ! will i have a problem with my phone since i ll change from London to a whole different country ?

**Comment by Tochez** [comment]
@Jam1ePistol no u wont have a problem. Try not to log in right after the flight tho. Give it some time because u might get softbanned.

**Comment by Jam1ePistol** [comment]
Million $ Question : Evolve a Dragonair with IV's 15-9-11 to a Dragonite or wait for another 25 candy and evolve a Dratini with 15-15-15 xD ?

**Comment by xJustx** [comment]
^
