### ISSUE TITLE
Request: Min IV to evolve.

### ISSUE THREAD

**Issue by justchil** [Ar1i/PokemonGo-Bot#1091]
Sorry if this is covered i'm on a laggy vnc connection.

I'm not evolving things like eevee's so that I can manually transfer anything <95% IV.

Would it be possible to add a Min IV to evolve by chance?

Cheers!

**Comment by justchil** [comment]
Latest update evolved all the pokemon NOT on my list to evolve.

if "Evolve pokemons if enough candy" is not checked does it still evolve those in the list?

**Comment by BimbasVG** [comment]
We need this!

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
