### ISSUE TITLE
I checked the site you claimed to steal your bot. It would be possible to take down the site + copied bot... But it's dangerous. The website is made with a website creator-site (like wix.com)... So they would trace the guy who took down "their" website and its only a matter of time until they would find the culprits and he will have to pay a big fine. Its a big risk... You should probably accept it...

### ISSUE THREAD

**Issue by unknownhelp** [Ar1i/PokemonGo-Bot#1092]

**Comment by FrancYescO** [comment]
Pokecrot suspended.

**Comment by Ar1i** [comment]
Thank you for your precious information regarding to domain Pokecrot.com. Please be informed that we have suspended the said domain.

Thank you for your cooperation.


Best Regards,
Arsini Suryantinah
ResellerCamp Support Team


Just a matter of time. But thanks!

**Comment by akbaryahya** [comment]
pokecrot still work if using vpn sg

**Comment by Ar1i** [comment]
it just need some time already told! :)
