### ISSUE TITLE
error since update

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1093]
![screenshot_1](https://cloud.githubusercontent.com/assets/20731094/17366637/def454f6-59a9-11e6-8c59-cbb96e07f51a.jpg)

getting this eror after everyy pokestop visited

**Comment by Ar1i** [comment]
Will take a look.. try to update to the newest fixes/pushes please

**Comment by sunit1998** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20731094/17366963/8e210ebe-59ab-11e6-9f1a-a23451b29ec6.jpg)

now this error too

**Comment by amaslkw** [comment]
in addition to that,  it showed my pokemon inventory full while its not.

**Comment by sunit1998** [comment]
i m still getting the same error with updated files

**Comment by sunit1998** [comment]
thnx a lot Ar1i its fixed after this update
i guess i will get all my pokemon back in 1 or 2 days.
i will donate again once i get cash
