### ISSUE TITLE
Usage Of Language ComboBox Instead Of Buttons

### ISSUE THREAD

**Issue by OSDemirci** [Ar1i/PokemonGo-Bot#1096]
With the increasing number of languages, I think it would be better to use a combobox for languages instead of buttons. With this way languages can be added automatically by downloading language json files with flag images.  Using  a format like Flag - Language Name in the combobox(Dropdown list) like below.

[![](http://www.codeproject.com/KB/combobox/ImageComboBox_CSharp/Fig1.png)](http://www.codeproject.com/Articles/106467/How-to-Display-Images-in-ComboBox-in-Minutes)

Also same system may be put on to the pokemon list menu. Checking default user language and selecting proper language may get better user experience. For this usage of localized resource files may be much more suited and migration to such system or hybrid of it where resx file created on compile time from json files may give its benefits.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
