### ISSUE TITLE
wtf this freaking update ruined my game

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1097]
this new update which u put on today just fucked my game up and transferred all the pokem on who had less than 2000 cp and i m now fucking broke on pokemon please fix this asap or i want the donated money back

**Comment by UltraVLT** [comment]
Screen of your settings?

**Comment by sunit1998** [comment]
all set to trnfer duplicate pokemon but that just tranferred all pokemons below 2000 cp

**Comment by Ar1i** [comment]
you never paid for anything. this is not nice from you and not fair lol, never said you should use unstable version. Stable Version is under Last Builds.

**Comment by sunit1998** [comment]
i paid u 3 days ago please check again i tranferred 10$

**Comment by sunit1998** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20731094/17368239/cbca1396-59b0-11e6-874e-3b68a5ed154d.jpg)

**Comment by Ar1i** [comment]
transferred all the pokem on who had less than 2000 cp and

Then put MAX Cp to Tranfser down?

**Comment by Ar1i** [comment]
Yeah thanks for the donation, but this is a donation not a buyed software man! keep that in mind please

**Comment by sunit1998** [comment]
since past 3 days i got no problem with these settings just now after the latest update

**Comment by Ar1i** [comment]
Yeah it will remove every pokemon which got under 2000 cp and under 90% IV

**Comment by sunit1998** [comment]
ok just leave it, it worked fine before todays update please revert back i m getting too much errors in this one

**Comment by OSDemirci** [comment]
Did you compile the source code or have you downloaded from builds section?

**Comment by sunit1998** [comment]
i download the whole zip file with all files in it and yes i compiled it

**Comment by Ar1i** [comment]
Use the Build Only when you want to be safe. And yeah no problem

**Comment by sunit1998** [comment]
ok sure now the world is spinning around me still too high blood pressure and thanks

**Comment by Ar1i** [comment]
np, thanks for the donation again!

**Comment by sunit1998** [comment]
i will close the issue now just look into my other issue
