### ISSUE TITLE
Is server down?

### ISSUE THREAD

**Issue by duyphuc1610** [Ar1i/PokemonGo-Bot#1098]
I can't open the auto bot at moment

**Comment by durnevo** [comment]
It seems the bot connects to a cloudflare ip before it even runs.

**Comment by OSDemirci** [comment]
@Ar1i , your website seems to be down. Therefore it cannot fetch languages.

**Comment by duyphuc1610** [comment]
that's sad :(

**Comment by Ar1i** [comment]
Yeah, will put an update which doesnt need my server anymore :p!
