### ISSUE TITLE
 Exception: System.IO.IOException: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

### ISSUE THREAD

**Issue by Wendelstein** [Ar1i/PokemonGo-Bot#11]
[20:41:48] We caught a Krabby (Krabby) with CP 455 using a ITEM_POKE_BALL
[20:41:58] Exception: System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Debug\Configs\LastCoords.txt" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bei System.IO.File.WriteAllText(String path, String contents)
   bei PokemonGo.RocketAPI.Client.SaveLatLng(Double lat, Double lng) in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI\Client.cs:Zeile 100.
   bei PokemonGo.RocketAPI.Client.SetCoordinates(Double lat, Double lng, Double altitude) in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI\Client.cs:Zeile 94.
   bei PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__28.MoveNext() in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI\Client.cs:Zeile 136.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Navigation.cs:Zeile 77.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 245.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__8.MoveNext() in C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 143.
[20:41:58] Starting again.. But waiting 10 Seconds..

**Comment by Anomy1337** [comment]
+1 gleiches problem bei google accounts

**Comment by Wendelstein** [comment]
Anomy1337 , ich benutze ein Google Account ...

**Comment by Anomy1337** [comment]
hast du nicht dazugeschrieben deswegen hab ichs getan.

**Comment by Wendelstein** [comment]
spielt das eine Rolle ? wohl eher nicht, sieht für mich nach lokalem Problem aus

**Comment by Ar1i** [comment]
Der Prozess kann nicht auf die Datei "C:\Users\freit\Desktop\Neuer Ordner\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Debug\Configs\LastCoords.txt" zugreifen, da sie von einem anderen Prozess verwendet wird.

Mehere Bots in nutzung? Dann die Bots in verschiedene Ordner kopieren bitte.

**Comment by Wendelstein** [comment]
nein ich habe nur einen 
und auch einen Ordner

**Comment by Ar1i** [comment]
Uhmmmm, habe da so ne Vermutung woran das liegen könnte.. werde gleich mal nen Update raushauen.

**Comment by Ar1i** [comment]
Probiert mal aus ob es jetzt geht.
