### ISSUE TITLE
Getlanguages API

### ISSUE THREAD

**Issue by CruSherFL** [Ar1i/PokemonGo-Bot#1100]
Hey Ar1i, thanks for the awesome bot! 
Since your language update, it seems like your website is offline? Maybe you can add a failsafe if your website is offline? Or I'll give you an example in the evening via git. 
GUI.cs @ line87 where it breaks

**Comment by OSDemirci** [comment]
#1098 Said that it will change.

**Comment by OSDemirci** [comment]
#1098

**Comment by Ar1i** [comment]
already in newest update

**Comment by Ar1i** [comment]
added
