### ISSUE TITLE
Errors since last two updates! Cannot start anymore

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#1101]
![screenshot_1](https://cloud.githubusercontent.com/assets/20720517/17368876/cebd3594-594a-11e6-95fb-5ea5ba5ddde1.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20720517/17368877/cebdbcc6-594a-11e6-9dfd-b06dac33cc47.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/20720517/17368875/cebcd0c2-594a-11e6-840b-95d3a100b625.png)

**Comment by OSDemirci** [comment]
#1102 #1099 #1100 #1098

**Comment by Ar1i** [comment]
try to download newest update?

**Comment by Ar1i** [comment]
fixed
