### ISSUE TITLE
Latest Build - 03.08 16.18.zip

### ISSUE THREAD

**Issue by ObsessedHacker** [Ar1i/PokemonGo-Bot#1103]
![](http://i.imgur.com/H0hzd1z.png)

**Comment by Ar1i** [comment]
will look at it 1sec

**Comment by UltraVLT** [comment]
Same somtimes,but works later on :S

**Comment by ObsessedHacker** [comment]
@Ar1i 

![](http://i.imgur.com/IFaWjca.png)


![](http://i.imgur.com/Lq1jMf6.png)

**Comment by stormlolz** [comment]
same problem

**Comment by Ar1i** [comment]
^already fixing..

**Comment by Ar1i** [comment]
@stormlolz @ObsessedHacker please test the newest version!

**Comment by ObsessedHacker** [comment]
@Ar1i The red text on the latest picture I gave you here is still on the bot but yeah everything fixed.

**Comment by zzzz9999** [comment]
Where is the last PokemonGo-Bot-master.zip?
For download only yesterday's version (02.08)

**Comment by stormlolz** [comment]
![azddazazdazazdazd9](https://cloud.githubusercontent.com/assets/20703341/17369528/ff84c0d6-5998-11e6-9702-d45dd9170374.PNG)

its ok

**Comment by ObsessedHacker** [comment]
@Ar1i Yep FIXED Now downloaded FIX3.
Close this issue!

**Comment by zzzz9999** [comment]
found it!

**Comment by Ar1i** [comment]
@stormlolz for the memory issue i will take a look.. but idk why that happens atm
