### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by HaydarOzturk** [Ar1i/PokemonGo-Bot#1104]
It found trojan on the last building...

**Comment by UltraVLT** [comment]
nope,false report

**Comment by OSDemirci** [comment]
Can you share the antivirus /w version and virus report?

**Comment by UltraVLT** [comment]
if vt shows 0 virus,your antivirus is pretty useless.https://www.virustotal.com/de/file/0e07254112423e33b11b3cd18af03146c9806c4b066a40919d8634282931b7ff/analysis/

**Comment by HaydarOzturk** [comment]
https://s32.postimg.org/5uh9tzphx/vir_s.jpg

**Comment by Ar1i** [comment]
Its cause i dont edit the GUID, and the Virus Scanner is giving fale positives out. Uploading new Version with some more fixes..

**Comment by HaydarOzturk** [comment]
I did but it still gives the same error @Ar1i
