### ISSUE TITLE
pokemon name

### ISSUE THREAD

**Issue by amaslkw** [Ar1i/PokemonGo-Bot#1105]
I am sorry but did someone request arranging the pokemon names in alphabetical order?

to me it seems arranging in order of the pokedex number would be more convenient.

just a thought. depends on majority. thanks guys for the work

**Comment by gise88** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/949
https://github.com/Ar1i/PokemonGo-Bot/issues/1056

**Comment by xJustx** [comment]
^
