### ISSUE TITLE
[Request] visit PokeStop but not activating it

### ISSUE THREAD

**Issue by n0o0ne** [Ar1i/PokemonGo-Bot#1108]
Visit PokeStops but not activating them!

Don't know if it is possible. But i think it's a good feature for people who don't want raise thier lvl and just want to search for rare Pokemon or just want to get km for thier eggs. 
And two options to set a minimum for Pokeballs in your pocket to reanable Pokestop activating and a maximum for the number of Pokeballs to disable the Pokestop aktivating again.

I hope you understand my intention^^

**Comment by delta-dude** [comment]
Agreed, that's actually a thing. Like some might want to collect all pokemons, but level them up themselves, manually. Is that possible?

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
