### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by SpoderPig** [Ar1i/PokemonGo-Bot#111]
I click the github tab to download but how do apply the update, the file downloads as a .zip then what do  I do?

**Comment by djdomrep** [comment]
you should download the exe if you don't know how to compile the source code.

**Comment by djdomrep** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
download the rar file and unpack it into a folder.
the github download zip button is just downloading the source code.

**Comment by SpoderPig** [comment]
thankyou

**Comment by SpoderPig** [comment]
ive unpacked the link you told me to download, then what do i do ?

**Comment by Ar1i** [comment]
Open the fcking exe. Closing this, its not a Support Forum
