### ISSUE TITLE
Auto transfer not working (?)

### ISSUE THREAD

**Issue by ranggirahman** [Ar1i/PokemonGo-Bot#1112]
I use auto transfer when double pokemon is 2 and max cp is 1700, lV 90%. but sometimes my pokemon have is 3 ~ 6. thank you :)

Update : i read other issues thread on this git have same problem, i wish bug can be fixed soon

**Comment by OhhPian** [comment]
same with me!

**Comment by FAymYs19** [comment]
I let the bot running in Central Park and an one hour latter i got a full inventory of Elekteks

**Comment by Tochez** [comment]
it is sorta like a bug. I think it has to do with evolving.
It catches alot of pidgy for me. But at the same time. All i do is evolve them so i get exp

**Comment by Abbasoo** [comment]
@ranggirahman @OhhPian @FAymYs19 @Tochez un-check "Keep Pokemons which can be evolved"

**Comment by ranggirahman** [comment]
@Abbasoo sure i uncheck that option but bug still exist
