### ISSUE TITLE
Stuck on black windows console, when starting PokemonGo.RocketAPI.Console.exe

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#1113]
When start .exe windows console opens, but it freezes.
Any idea?
AV is turned off....

Thanks

![bot1](https://cloud.githubusercontent.com/assets/20780971/17369994/57b4e184-5992-11e6-8901-ab911865ba3d.png)

**Comment by Bikkstar123HD** [comment]
same here

**Comment by Rolzy2** [comment]
idem

**Comment by DonBot12** [comment]
Please close your issue and just add onto #1114. It has detailed information about the error.

**Comment by Ar1i** [comment]
Test it with the newest Version now please @Bikkstar123HD @Rolzy2 @DonBot12 @zzzz9999

**Comment by zzzz9999** [comment]
As per DonBot12 suggestion this issue will be close.
(Duplicate of #1114)
