### ISSUE TITLE
Reward requesting

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#1115]
The bot doesn't request level-up rewards, neither the trophies.

**Comment by UltraVLT** [comment]
When you log into the app at your phone or NoxPlayer,you get the annotation of the level ups.Then just start the bot again.

**Comment by FAymYs19** [comment]
I know, but if the server sees that that u got enough xp for two level but not request the rewards, it could think you are botting.

**Comment by UltraVLT** [comment]
I started a fresh account in new york 1 week ago,logged in first when it was lvl 26,still no ban :S)

**Comment by LvGPoke** [comment]
If you gather 600 000 XP per day they dont think you are botting, but if you receive no rewards they do ?

**Comment by FAymYs19** [comment]
xD im just sayin

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
