### ISSUE TITLE
Stop using all my razz berries!

### ISSUE THREAD

**Issue by NextOG** [Ar1i/PokemonGo-Bot#1117]
Can you make a setting so that it will only use razz berries on certain Pokemon we select it keeps using them on pidgeys :/

**Comment by AgentBallermann** [comment]
Great Idea!
In addition to that the border when berries are used should be customizable... No berries for 400 CP But for 600+CP

**Comment by globsch** [comment]
you cant change the probability.Value yourself.
Login.cs line 545
`if (probability.HasValue && probability.Value < 0.35)`
just increase the value to use less.
or something like 
`if (probability.HasValue && probability.Value < 0.35 && encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp < 600)`
(untested)

**Comment by xJustx** [comment]
^
