### ISSUE TITLE
JsonReaderExpception Error when loading bot?

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#1118]
![screenshot_1](https://cloud.githubusercontent.com/assets/20720517/17370553/50b7e278-5951-11e6-8db9-2d26f50db02d.png)

**Comment by steezespot** [comment]
1. Use a debug build configuration or disable the debug option 'Enable Just My Code'. 
2. Check the 'Symbols' settings under debugging options.'PokemonGo.RocketAPI.Console.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Console.vshost.exe): Loaded 'C:\Users\Administrator\Desktop\Pokemon go\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Release\Pokemon Go Rocket API.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Console.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Console.vshost.exe): Loaded 'C:\Users\Administrator\Desktop\Pokemon go\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Release\PokemonGo.RocketAPI.Logic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Console.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Console.vshost.exe): Loaded 'C:\Users\Administrator\Desktop\Pokemon go\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Release\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Console.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Console.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x12d0 has exited with code 0 (0x0).
The thread 0x3088 has exited with code 0 (0x0).
The thread 0x1780 has exited with code 0 (0x0).
The thread 0x2d40 has exited with code 0 (0x0).
The program '[8472] PokemonGo.RocketAPI.Console.vshost.exe' has exited with code 0 (0x0).

**Comment by roberrrt-s** [comment]
Download the latest version. ( 1960a4c7823ac21f2d28e3443663c803c5e307cc )

**Comment by steezespot** [comment]
thanks

**Comment by clmnt02** [comment]
still got error unhandled exception :(
