### ISSUE TITLE
Pokemon list alfabetic -> # number

### ISSUE THREAD

**Issue by godlex999** [Ar1i/PokemonGo-Bot#1119]
Is it possible to make the pokemon lists (trasfer/catch/evolve) back on pokemonnumber and not sorted alfabetic?

**Comment by madeinyashiro** [comment]
Or at leat give user the option to switch between alphabetic or # lists

**Comment by gise88** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1105
https://github.com/Ar1i/PokemonGo-Bot/pull/949
https://github.com/Ar1i/PokemonGo-Bot/issues/1056
