### ISSUE TITLE
help: anyone know how to fix this

### ISSUE THREAD

**Issue by shibby1889** [Ar1i/PokemonGo-Bot#112]
![capture](https://cloud.githubusercontent.com/assets/20709248/17228612/8ecddb86-54c8-11e6-84c9-ec96008db6c4.PNG)
Ive tried 2 different accounts and this happens on both

**Comment by TMaddox** [comment]
same problem here, but only one account.
it is definitely accountbased, the account with the problem doesnt work with other bots either, but my other accounts work quite well

**Comment by djdomrep** [comment]
whats de difference between the account that isn't working and the ones that are working?

**Comment by shibby1889** [comment]
yeah because i just created a new one and it wouldnt work

**Comment by Ar1i** [comment]
Server is lagging. Wtf guys how many thinks you want to open. Read on the Forum.
