### ISSUE TITLE
Add ID Column to pokemon list GUI

### ISSUE THREAD

**Issue by some1563** [Ar1i/PokemonGo-Bot#1120]
Hi,
Can you add a column with pokemon ID in pokemon GUI?.
With this feature, i can sort caught pokemon by ID, like pokedex

Thanks for working

**Comment by Tochez** [comment]
please use the thread: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

Answer : Might be good but then again it takes 5 seconds in ur life to search it up :D.

**Comment by some1563** [comment]
I seached, but here on Github! :D

**Comment by xJustx** [comment]
^
