### ISSUE TITLE
Still not fixed

### ISSUE THREAD

**Issue by Timmiller109** [Ar1i/PokemonGo-Bot#1121]
![screenshot_1](https://cloud.githubusercontent.com/assets/20779663/17371500/b684f6b8-5965-11e6-80df-a4697e218141.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20779663/17371502/b78a08be-5965-11e6-88ff-410b62d91d64.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/20779663/17371503/b899e418-5965-11e6-8d0c-4b18fc744783.png)

**Comment by Tochez** [comment]
you tried redownloading it again?

**Comment by sunit1998** [comment]
redownload the files and restart pc and try again worked for me

**Comment by Timmiller109** [comment]
i did

**Comment by januszhej** [comment]
same for me, it was working like 2 hours ago, weird

**Comment by Timmiller109** [comment]
ok deleted the entire folder, restarted my computer, and re dowloaded everything and now it seems to be working. thank you guys!
