### ISSUE TITLE
[SUGGESTION] Multi Account Feature

### ISSUE THREAD

**Issue by AgentBallermann** [Ar1i/PokemonGo-Bot#1122]
Simply a feature to start the bot multiple times with different accounts easier. Atm i have like 6 :P Bot copies in seperat folders to manage this. I think the optimal way to do this would be a function (in form of a button) to ADD accounts to a DB or so so you can then select the accounts from a dropdownmenu.
Maybe a additional button to start all acounts at the same time.

**Comment by ranggirahman** [comment]
Great idea ..

**Comment by gise88** [comment]
You can copy the build directory and use this method for use multiple account.. 

However: https://github.com/Ar1i/PokemonGo-Bot/issues/231

**Comment by Timmiller109** [comment]
I understand the not wanting to help account sellers but some people, as in myself have multiple accounts. Im currently running my account, my girlfriends account, my mother in laws account, my best friends account, and all 3 of my neices and nephews accounts all at once. its not much of a hassle to log in to each one but it would be nice to have a feature to do it all without having to start a new bot every time.

**Comment by AgentBallermann** [comment]
Exactly :D 
The GUI we see now could be the main Launcher and the Save Button sould  iopen a new Console window instead of closing the GUI

**Comment by gise88** [comment]
Yes, I know.. But you can simply solve by doing a copy of the build directory many times.. 
What you are asking for is a lot of work and it is going to help only a few people! I am not the project manager but if you want this try to do a PR..

**Comment by AgentBallermann** [comment]
You mean like this ? 
http://puu.sh/qozms/27a736cc0c.png 
I already done that BUT its also a lot of work to update this okay a little bit ...
And to realize it it wouldnt be such a big deal. probably less than an Hour of work more likely half an hour.

**Comment by gummyruler** [comment]
We already have profiles saved on configs. So that might be possible to use it as a reference point and we'll just have to click it to login using the GUI. How does that sound?

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
