### ISSUE TITLE
Telegram /information Catch activates Pokestop

### ISSUE THREAD

**Issue by deulos** [Ar1i/PokemonGo-Bot#1124]
Like described in title, when I try to activate the catch notification with the command /information Catch I get the alert to Pokestop and I receive the pokestops notifications instead of the pokemon catches.

Thank you and terrific work!!

**Comment by esc1duy** [comment]
how to use Telegram?

**Comment by deulos** [comment]
in telegram install botfather, create a bot in botfather, and configure the pokemongobot with the token and your telegram nickname

**Comment by esc1duy** [comment]
yes i have configure above, but i try command in telegram is main out picture as link. "https://cdn.discordapp.com/attachments/209328668458090496/210567892444512257/Screenshot_2016-08-04-08-16-54.jpg"

**Comment by xuninho** [comment]
Put your nickname in the box. Only.

**Comment by deulos** [comment]
look at your telegram profile and set a nickname if you dont have, then put that nickname in the bot
