### ISSUE TITLE
Evolve + PowerUp Everything

### ISSUE THREAD

**Issue by AgentBallermann** [Ar1i/PokemonGo-Bot#1125]
Two new Buttons in the pokemon list which powerups(to the Maximum) / evolves as much pokemon as you can started from high IV .
In case you dont want to let the bot do that automaticly and neighter klick on each single pokemon you want to upgrade.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
