### ISSUE TITLE
auto incubate

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1126]
auto incubate not working Ar1i are u still implementing this new thing?

**Comment by Ar1i** [comment]
still implementing was just a merge, he will work later at it

**Comment by sunit1998** [comment]
i m getting error so i asked
i reverted back to old version
i got nearly 50 zip files all archives of ur bots

**Comment by Ar1i** [comment]
@sunit1998 use newest version

**Comment by sunit1998** [comment]
but its giving me errors and not working properly right now
once the egg is incubated i will use latest version i still got 10km egg on my hatching
