### ISSUE TITLE
An Auto-update ?

### ISSUE THREAD

**Issue by Zalatis** [Ar1i/PokemonGo-Bot#1128]
Hello, is it possible to add an auto-update feature on the bot ?

Thanks for the answer , You make a very great Job !

**Comment by AgentBallermann** [comment]
I was about to post this Idea too.
Maybe a new Build Release with an Auto Updater so we dont have to open VS every time ;)

**Comment by ShutUpPvP** [comment]
Had the same idea today at work, but were faster! xD

**Comment by arisaurusrex** [comment]
Would appreciate an auto-updater..

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
