### ISSUE TITLE
Suggestions for next update(less pokestops more pokemon catches

### ISSUE THREAD

**Issue by myronownage** [Ar1i/PokemonGo-Bot#113]
Somehow and i heard from other people. The bot doesnt catch all the pokemon nearby.. It gets more pokestops then actually pokemons. I get like 1 pokemon catch every 40sec? sometimes even a minute.

And its only catching pidgeys/ratta's while i enabled it to catch all pokemons. I only get  a different pokemon every 10min. While there plenty arround.

Just some suggestions! I respect your hard work!

**Comment by Ar1i** [comment]
Uhm, their is already a check every step for a pokemon
