### ISSUE TITLE
Using PokeSnipers

### ISSUE THREAD

**Issue by lovakosh** [Ar1i/PokemonGo-Bot#1134]
Hi,
Is there a way to snipe pokemons with the bot like in coordinates from PokeSnipers or Pokespawns?
If there is a way can you explain how to use it?
Thanks.

**Comment by UltraVLT** [comment]
You could use pokesniper2 extern and when you are done and need to farm balls you can start the bot again. That's the only way atm

**Comment by xJustx** [comment]
^
