### ISSUE TITLE
(NOT an issue: Pokemon Density Site)

### ISSUE THREAD

**Issue by gummyruler** [Ar1i/PokemonGo-Bot#1135]
This is not an issue but I would like to post this pokemon density site here. I've tried it out and it's pretty accurate. 

https://skiplagged.com/pokemon/

(p.s I want to post it here since it kinda gave me a hard time to find this. hope it helps.)

**Comment by UltraVLT** [comment]
Already in use since pokevision is down,check at telegram /stats

**Comment by Versake** [comment]
@gummyruler where do u find charmander btw?
