### ISSUE TITLE
PokeBall

### ISSUE THREAD

**Issue by TheBlazerLP** [Ar1i/PokemonGo-Bot#1136]
The Bot doesnt use my Pokeballs but my GreatBalls

**Comment by AgentBallermann** [comment]
Thats because they are above any border ... or does the bot uses Greatballs for 10CP mons even if you have normal ones ?!
A customizable amount of CP / IV or pokemon needed to use special Items wuld be cool!!!

**Comment by ShutUpPvP** [comment]
Probably justa  full inventory, u probably cant get pokeballs.
MY bot is using pokeballs so its something with ur inventory

**Comment by xJustx** [comment]
^
