### ISSUE TITLE
Pokevision alternative!

### ISSUE THREAD

**Issue by DevEagle15** [Ar1i/PokemonGo-Bot#1137]
Hey man! I would like you to check out this page: https://github.com/AHAAAAAAA/PokemonGo-Map/
It's a python based server that shows pokemon locations around a certain area in a given radius. If you could implement the script into your bot, it might help many people who would like to catch specific pokemons.

**Comment by ranggirahman** [comment]
it works to open map on browser like pokevision ?

**Comment by zunox** [comment]
Yes but is internal meaning for you. Unless you release it public. Not sure it could handle the people though.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
