### ISSUE TITLE
x% perfect Pokemon behalten trotz max 2 pro Exemplar - dann lieber das mit mehr CP zum Prof schicken aber das mit mehr potenzial behalten

### ISSUE THREAD

**Issue by Fackma** [Ar1i/PokemonGo-Bot#114]
gibt es eine Möglichkeit alle > (X% perfect)en Pokemon zu behalten und dann trotz ggfs. geringeren WP, bei der Einstellung, dass er von je einem Pokemon 2 Exemplare behalten soll, das mit der höheren WP zum Prof schickt?
Gern auch im Code.

VG
Fackma

**Comment by djdomrep** [comment]
aktuell ist dies nicht möglich. ob es von den entwicklern vorgesehen ist weiss ich nicht. gut wäre es jedenfalls.

**Comment by Ar1i** [comment]
#143
