### ISSUE TITLE
Can this be converted to a website?

### ISSUE THREAD

**Issue by zunox** [Ar1i/PokemonGo-Bot#1141]
So basically a person visits a URL and they can set the same settings and run it online?

**Comment by 12348766754** [comment]
So the cost (systems) is for the developer?
Won't work for freeware.

**Comment by zunox** [comment]
No i mean make the software into a website.

**Comment by TMaddox** [comment]
who pays the server for the website then ?? ;)

**Comment by zunox** [comment]
I would if we had the proper script that can be ran.

**Comment by asfo** [comment]
Yes it could but it will sucks so much or costs too much for a good site...because the site will require something for real-time like Pusher or for free Ratchet but it requires a good server.

Sorry for my bad english :(
