### ISSUE TITLE
[SUGGESTION] Add a "self decided" amount of candy you would like to spend on a pokemon

### ISSUE THREAD

**Issue by arisaurusrex** [Ar1i/PokemonGo-Bot#1143]
Instead of manually pressing the "Powerup" button many times, add a feature where the user can decide how many candy to invest, instead of using all the candy.

**Comment by UltraVLT** [comment]
It varies from level on how much you need for the power-ups.By this manually powerupping,it's easier for you to control it.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
