### ISSUE TITLE
Only keep +IV 100 Pokemons

### ISSUE THREAD

**Issue by QustomiZed** [Ar1i/PokemonGo-Bot#1145]
How can i set my bot that it only keeps IV 100 pokemons no matter the CP ?

**Comment by vibenji** [comment]
Set CP to 9999 and IV to 100.

**Comment by jief78** [comment]
not tested yest but i think if you put 100 to iv and 999999 to cp

**Comment by xJustx** [comment]
^

**Comment by QustomiZed** [comment]
And if i set max. duplicate pokemons 0? do i keep my double 100 IV pokemons?

**Comment by jief78** [comment]
i think yes
