### ISSUE TITLE
What is this <IV A-D-S?

### ISSUE THREAD

**Issue by januszhej** [Ar1i/PokemonGo-Bot#1147]
title

**Comment by Vadmins** [comment]
Are the stats of your pokemon. A = attack, D = defence, S = stamina. The IV is the perfection of the three stats on a 0/15 rate

**Comment by januszhej** [comment]
can A-D-S change after power uping pokemon?

**Comment by FrancYescO** [comment]
No.

**Comment by Vadmins** [comment]
I'm not 100% sure but IV's (so at the same time A-D-S) are permanently set on a Pokemon

**Comment by januszhej** [comment]
right, thank you
