### ISSUE TITLE
[Suggestion] Old layout for Player Stats

### ISSUE THREAD

**Issue by Vadmins** [Ar1i/PokemonGo-Bot#1148]
Hi guys, you made an amazing work here! I just want to suggest to go back on the old layout for the light blue Player Stats because the new one is too confusing and diffiult to read. Thank you very much guys!! Again you really did a great work here!

P.S. I also saw that there is no italian translation yet.. if needed just let me know, send me a txt file with the english one and I'll translate it!

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
