### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by OhhPian** [Ar1i/PokemonGo-Bot#1149]
Has anyone encounter this problem ? im at Sydney right now.

![prob](https://cloud.githubusercontent.com/assets/17487706/17374685/5d2de3ba-59e0-11e6-9807-58a634ea0892.PNG)

**Comment by OhhPian** [comment]
it always repeat same thing T_T

**Comment by zunox** [comment]
Yea but still works. I normally restart the program.

**Comment by OhhPian** [comment]
When starting it popup this. already restart 5 times but no works :(

![prob1](https://cloud.githubusercontent.com/assets/17487706/17374827/f7b3b13a-59e0-11e6-8c8b-22a85812527c.PNG)

**Comment by jief78** [comment]
when it show this i delete the coord in the file Configs/LastCoords.txt
and it start with a ban but unban quickly

**Comment by OhhPian** [comment]
@jief78  Do u mean by PokemonGo.RocketAPI.Console/bin/Debug/Configs/LastCoords.txt ?

**Comment by gummyruler** [comment]
@OhhPian Yes delete that file and try again.

**Comment by OhhPian** [comment]
it still happening T_T 
i wonder why.. i already delete the LastCoords and then bin folder. But still the same.

**Comment by jief78** [comment]
don't you use the builded version?
because in mine the configs folder is in the same folder as the console.exe

**Comment by OhhPian** [comment]
I use the other one, but i will try use the build version.

**Comment by immoempe** [comment]
OhhPian: first picture: servers problem, second picture: Delete the LastCoords.txt (you can find it inside Builds Only/Configs route)

**Comment by OhhPian** [comment]
@immoempe i see. thats clear the mystery. 
@jief78  i use the build version and it works fine. 

Thanks guys ^^
