### ISSUE TITLE
Trojaner?! evtl. False positive 

### ISSUE THREAD

**Issue by TrolluXe** [Ar1i/PokemonGo-Bot#1150]
Hab das neuste Update runtergeladen und auf einmal ging WinDefender an und hat gesagt es wäre ein Trojaner in der Datei enthalten.

**Comment by vibenji** [comment]
Ist sicher nur ein False positive. Liegt glaube ich daran dass die .exe mit Enigma gepackt wird, bin mir da aber nicht 100% sicher.

**Comment by xJustx** [comment]
^
