### ISSUE TITLE
Encounternotinrange

### ISSUE THREAD

**Issue by gabrimen** [Ar1i/PokemonGo-Bot#1151]
I've seen in this forum that this error is because a softbanning by niantic, but if i open my account in another bot like application it runs without problems, is there any other way that i recive this message? i'm with the new version but seems to repeat in older versions, what do i check i think this is the better bot app but since yesterday i cant catch a pokemon because of this error, plase help me

**Comment by jief78** [comment]
make sure not to have 2 bot opened with the same account simultaneously or the app on your phone opened 
i had this error because of that previously

**Comment by gabrimen** [comment]
I let it rest about 6 hours and still the error in this app, i opened another bot app and started ok...
