### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by frktml** [Ar1i/PokemonGo-Bot#1153]
hi @Ar1i  a few pokemons not transfer.

especially

nidoran female. ratata. weedle and pidgey

![adsiz](https://cloud.githubusercontent.com/assets/20819225/17375555/2934be9c-59ba-11e6-9ab9-6257443e4bdc.jpg)
can u fix this ?

**Comment by jief78** [comment]
verify they aren't checked in the not to transfer list

**Comment by frktml** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/20819225/17375703/d4a00282-59ba-11e6-81fb-a855b83f6a3c.jpg)
as you see...

**Comment by BEKKNQV** [comment]
Uncheck "keep pokemon which can be evolved"

**Comment by frktml** [comment]
oh thanks bro :)

**Comment by BEKKNQV** [comment]
Please close the issue if it isn't one anymore ;)
