### ISSUE TITLE
Live inventory

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#1154]
Is there a way to see my inventory live? 
Like how many pokebals/berries etc

**Comment by jief78** [comment]
just connect to the app on your phone after deactivating GPS

**Comment by 12348766754** [comment]
Does the app not use IP? @jief78

**Comment by Jam1ePistol** [comment]
can you be online from bot and from phone at same time :O ?

**Comment by jief78** [comment]
yes but only if you deactivate gps on phone so you can't do many things.

**Comment by xJustx** [comment]
^
