### ISSUE TITLE
Change name of pokemons

### ISSUE THREAD

**Issue by fakirpic** [Ar1i/PokemonGo-Bot#1155]
hi i want to evolve eevee but need to change name can you add such function?

**Comment by jief78** [comment]
you can connect to your phone BUT ONLY AFTER DEACTIVATING GPS
and do it their

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
