### ISSUE TITLE
Keep all 100% IV Pokemons 

### ISSUE THREAD

**Issue by BimbasVG** [Ar1i/PokemonGo-Bot#1156]
We need button -> Don't transfer all 100% IV Pokemons or Prior IV over CP.

Thanks.

**Comment by Sinan102** [comment]
You can do it right now and it is working

**Comment by BimbasVG** [comment]
Its not working, we need prior IV over CP. Its keep only highest CP pokemon, IV don't work.

**Comment by gummyruler** [comment]
there's a default 90% IV keep right now. Anthing above 90%IV will be kept. It's already there you just have to look a little. 

Lowering the IV cap would help a lot a good 80IV will catch just about everything though.

**Comment by BimbasVG** [comment]
Its keep only highest CP pokemon, transfer everything else...

**Comment by globsch** [comment]
can't be your settings must be wrong!

**Comment by NextOG** [comment]
It is a setting just look for it... https://gyazo.com/27b51783a6f479bdc0bc22ab3152bfe6

**Comment by xJustx** [comment]
^
