### ISSUE TITLE
Eggs hatching

### ISSUE THREAD

**Issue by Sinan102** [Ar1i/PokemonGo-Bot#1158]
There are other bots that can hatch eggs and they are using "RocketAPI" like you. So i thought that api may updated but you may fail to notice about it. Can you consider adding to bot ? 

Thanks for you attention

**Comment by OGcpalm** [comment]
his already working on it, but suggestions go on highminded.

**Comment by gummyruler** [comment]
He's already making a framework for it. idk maybe 2 days from now he will be able to complete it.
