### ISSUE TITLE
Error: Reloading pokemonList!

### ISSUE THREAD

**Issue by benz1996** [Ar1i/PokemonGo-Bot#1159]
What should i do?? I keep getting Error: Reloading pokemonlist... I tried old version and the new update aswell neither of them works...

**Comment by benz1996** [comment]
Please help...

**Comment by TheAntonio422** [comment]
Same issue here!!!!Please fix it

**Comment by FoolYah** [comment]
I now cant even start it anymore

**Comment by TheAntonio422** [comment]
Try to desactivate pokemon GUI. Temporary fix, but worked for me , i tried
