### ISSUE TITLE
Build Download - Virus Detected

### ISSUE THREAD

**Issue by GHANT** [Ar1i/PokemonGo-Bot#1160]
Someone figure out what is happening. Windows 10 encounters the virus after the fact. Now it's not allowing me to download it.

**Comment by UltraVLT** [comment]
Defender or which software?

**Comment by iOwner** [comment]
Most likely defender

**Comment by UltraVLT** [comment]
Then easily just deactivate that useless thing ._.

**Comment by Logxn** [comment]
Defender = shit.
Always was always will be.

**Comment by CreativiTimothy** [comment]
Disable antivirus. Kaspersky says there's no virus, but you can go to virustotal.com if you're unsure

**Comment by sunit1998** [comment]
if u are done with the issue please close this issue

**Comment by xJustx** [comment]
It's a false positive.
