### ISSUE TITLE
The domain pokecrot.com is still up... could i somehow contact you maybe there is a way to get itr down completely. would also be an honor to help you

### ISSUE THREAD

**Issue by unknownhelp** [Ar1i/PokemonGo-Bot#1163]

**Comment by Logxn** [comment]
No its down.
But he has a new domain already.
If you have a booter or something you could swiftly add me on steam :b http://steamcommunity.com/id/logxnhumble/

**Comment by unknownhelp** [comment]
do you speak german too?

**Comment by unknownhelp** [comment]
gonna add you

**Comment by cicklow** [comment]
Name: Messa Harianto
Organization: Messa Harianto
Address: 149 weste ave 	map
City: jacksonville 	
State: NC
Country: US United States 	
Phone: +1.9019150023

more domains: http://domainbigdata.com/email/vipspuc3ngine@yahoo.com
