### ISSUE TITLE
Cant Start.

### ISSUE THREAD

**Issue by FoolYah** [Ar1i/PokemonGo-Bot#1165]
The Bot wont star for me.

**Comment by CreativiTimothy** [comment]
I'm on Windows 10 it starts half the time, sometimes saying Net Framework error. All you need to is re-extract it again, restart your computer if necessary, and try again. At least, that's what worked for me.

**Comment by FoolYah** [comment]
I've Windows 7, I can open it but it wont show me the bot, I have the newest Microsoft .NET Framework, and restart doesnt helped. Downloaded it again but it just wont start. @CreativiTimothy

**Comment by FoolYah** [comment]
@CreativiTimothy

**Comment by xJustx** [comment]
any screeenshots?

**Comment by sidd1993** [comment]
Extract it and make it RUN as Administrator.... try this... it worked for me..
