### ISSUE TITLE
Bot accidentally transferred 96% IV Squirtle when I set the MAX IV to 95%

### ISSUE THREAD

**Issue by CreativiTimothy** [Ar1i/PokemonGo-Bot#1166]
Here's a screenshot: http://prnt.sc/c1833q
In the settings, I set it the max IV to 95%: http://prntscr.com/c184dw

I assumed that it would transfer all Pokemon except Pokemon between 95%-100% IV. However, it seemed tro transfer all Pokemon regardless. I did set the transfer max duplicate Pokemon to 1, but I thought the Max IV setting would override it. Otherwise, it would be a non-functional setting.

I think this is a bug. Could you please fix it? Thank you!

I have build number 03.08 17.10

**Comment by sunit1998** [comment]
u set the cp tranfer high so it transfered the squirtle too

**Comment by CreativiTimothy** [comment]
The squirtle is only 136CP. I set it at 4000CP transfer so that it would transfer all Pokemon below 4000CP. The Max IV setting is supposed to override that and keep the 95-100% IV Pokemon. Otherwise, it's a useless function that makes no difference if the button was removed. Do you know what I'm saying?

**Comment by globsch** [comment]
I improved the check!
https://github.com/Ar1i/PokemonGo-Bot/pull/1172
But I don't think the old was wrong.

**Comment by gummyruler** [comment]
*Cringe* I can't even get a decent 50% IV squirtle.

**Comment by Requal** [comment]
What does IV stand for anyway I still dont know and googled everywhere

**Comment by Vicellus** [comment]
I assume you set the bot to automatically transfer duplicates? It was replaced with the same IV & lower CP. You need to set the bot to allow duplicates.

IV is individual value. http://pokemon.wikia.com/wiki/Individual_Values

**Comment by CreativiTimothy** [comment]
@Vicellus Yes. But if I set it to allow duplicates, even just 2, my Pokemon storage will max out. Also, I'm pretty sure it's intended that the do not transfer Max IV should override all other settings. For example, on Necrobot, it says, "This setting will make sure that Pokemon in these IV ranges will NEVER be transferred under any circumstances". It wouldn't make sense for the setting to not override other settings. Again, if it didn't, it would be a pointless setting
