### ISSUE TITLE
WTf is this |HELP|

### ISSUE THREAD

**Issue by darklordor** [Ar1i/PokemonGo-Bot#1167]
![c0248db86eb14f7ebc02155f2303ffae](https://cloud.githubusercontent.com/assets/20802047/17378453/503a8e0a-59be-11e6-9a73-8b51aab03b59.png)

**Comment by immoempe** [comment]
It seems a server error

**Comment by DokiTeeX** [comment]
Yes me too

**Comment by sunit1998** [comment]
download the latest zip file i got this error too ji jusr downloaded the new file and now works smoothly for me

**Comment by TheAntonio422** [comment]
what file??

**Comment by TheAntonio422** [comment]
Same issue!!

**Comment by darklordor** [comment]
i have the most recent file

**Comment by gummyruler** [comment]
Server is out that's what it means.

**Comment by danielalvenstrand** [comment]
Whenever I get this I just restart the bot and it starts working in a couple of seconds. :+1:

**Comment by xJustx** [comment]
^
