### ISSUE TITLE
 Anyone familiar with this "System.NotImplementedException"?

### ISSUE THREAD

**Issue by JackTheTripper** [Ar1i/PokemonGo-Bot#1168]
![system notimplementedexception](https://cloud.githubusercontent.com/assets/20823086/17378625/e5e3072a-59be-11e6-976c-f3d5869876ce.JPG)

got this since half an hour i guess
it is the most recent not compiled version (with VS)

**Comment by sunit1998** [comment]
everyone is getting this error just download the new file and use that one it works smoothly i had the same error

**Comment by JackTheTripper** [comment]
thank you, 
though I had to use the build version which doesn't contain the hatching-eggs-feature
I'll try compiling again later

**Comment by monoxacc** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/page-286#post-497882

**Comment by setoy** [comment]
That was a mistake made by me, I fixed it in my PR 15 hours ago (~ 03.08.2016 17:00). This error is not present in the latest build version although this one doesn't have the egg-hatching feature.

The source after the date stated above works flawlessly **with** hatching.
