### ISSUE TITLE
WTF I CANT CATCH POKEMONS

### ISSUE THREAD

**Issue by dirdamantas** [Ar1i/PokemonGo-Bot#1169]
![untitled](https://cloud.githubusercontent.com/assets/20823288/17378719/c3840a40-59c7-11e6-9e83-5fd9525bd0aa.jpg)I JUST CANT CATCH POKEMON, WHEN I PLAY ON PHONE I CANT CATCH EATHER, ITS CATCHINK POKEMONS ERROR OR SOMETHING

**Comment by CreativiTimothy** [comment]
You've been soft-banned. Don't set the moving speed too high.

**Comment by dirdamantas** [comment]
what moving speed you recomend?

**Comment by FoolYah** [comment]
did u changed the location? with me it only happens when i change the location

**Comment by dirdamantas** [comment]
i am from lithuania and i did location to germany munich

**Comment by FoolYah** [comment]
Try it with standard Location. (New Central Park - New York I guess) (I live near Munich lol)

**Comment by dirdamantas** [comment]
Ok i will try it, thx

**Comment by gummyruler** [comment]
move speed max should be 100 even with that speed I get soft banned sometimes. And it seems like you jumped so far away. You have to delete your "lastcoords" file in the config folder before you jump from state to state.

**Comment by dirdamantas** [comment]
where i can found config folder? @gummyruler

**Comment by xJustx** [comment]
^
