### ISSUE TITLE
Redundant Informations

### ISSUE THREAD

**Issue by NoticeMeSenpaiPLS** [Ar1i/PokemonGo-Bot#1170]
Is it possible the implement an option to select which information the bot prints out.

I mean i rly dont want to know every time the bot gots near a pokestop or clearing the pokestop^^
For me it would be enough to know which pokemon the bot catched and the player stats :D

Would be nice to implement such an option^^

**Comment by FoolYah** [comment]
i dont think so

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
