### ISSUE TITLE
Cant open

### ISSUE THREAD

**Issue by FoolYah** [Ar1i/PokemonGo-Bot#1171]
I cant open the bot. Tried re starting and converted it again, didnt worked

**Comment by untesty** [comment]
Same problem here. :(

**Comment by FoolYah** [comment]
@untesty since when?

**Comment by globsch** [comment]
just use the last exe build or remove all StartIncubation() at the Logic.cs
the future is under development.

**Comment by FoolYah** [comment]
Now the older Version works for me lol @globsch @untesty

**Comment by FoolYah** [comment]
Now i can open everything again. this is strange ._.

**Comment by xJustx** [comment]
^
