### ISSUE TITLE
pokemon list gui sort by catch-date

### ISSUE THREAD

**Issue by KaV0** [Ar1i/PokemonGo-Bot#1174]
would be cool to sort the pokemon also by catch date.

btw catch date seems to be wrong. catches for today it says 04.08.2017 (but it is 03.08.2016)
time seems to be correct. cet+-0

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
