### ISSUE TITLE
[FEATURE REQUEST & Question] Improved GUI

### ISSUE THREAD

**Issue by inZaneX** [Ar1i/PokemonGo-Bot#1177]
Hey guys,

today i made a GUI in Photoshop and want know what you think about it.
If you like it i will realize it for the Bot.

http://i.imgur.com/kpIQwC9.png

Hope you like it.
best wishes

**Comment by Qurus1** [comment]
Wow. great look

**Comment by Qurus1** [comment]
But you should hide your e-mail!!

**Comment by inZaneX** [comment]
its not my email :P. in germany this is a fake mail.

**Comment by cpblack** [comment]
Looks awesome but I think it would be better if the player stats were not displayed in the logs but rather in its own panel

**Comment by danig105** [comment]
Look awesome!

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
