### ISSUE TITLE
suddenly lots of softbans detected

### ISSUE THREAD

**Issue by KaV0** [Ar1i/PokemonGo-Bot#1179]
since now, the bots say that a softban is detected several times. they can unban themselves, but nevertheless, never had this problem before.
others have the same problem?
changed nothing. 20kmh speed.

**Comment by zzzz9999** [comment]
same here 10kmh

![bot2](https://cloud.githubusercontent.com/assets/20780971/17380045/0408e1b8-59bd-11e6-85c0-47dfbf712a21.png)

**Comment by BimbasVG** [comment]
http://ispokemongodownornot.com/

**Comment by xhalfbakedguy** [comment]
do you use a proxy or no?

**Comment by Logger26** [comment]
Probably cuz the server was down

**Comment by PloxFire** [comment]
I set it to 50kmh and i only get softbanned once a day, when i go on my phone or nox im still softbanned with all the pokemon i got before and after the softban happened and did the unsoft ban trick and i was fine :P

**Comment by KaV0** [comment]
yes it was a short time before the servers went down. i think that was the problem and will close this.
if happens again, will post again.
