### ISSUE TITLE
Detetcetd softban ...

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#1181]
What is this?!
Then unban?!  How to avoid?

![bot2](https://cloud.githubusercontent.com/assets/20780971/17380034/eec1baa0-59bc-11e6-90ed-931ddcc826e5.png)

**Comment by gnzl0o** [comment]
there is a method to "unsoft ban" by doing a pokestop 40 times in a row or so, also there is another detail but i dont remember rn

**Comment by gnzl0o** [comment]
i'll recomend to change the speed of the bot to 25-30

**Comment by zzzz9999** [comment]
why not 10? its slower ...

**Comment by BimbasVG** [comment]
http://ispokemongodownornot.com/

**Comment by xJustx** [comment]
You will get a softban if you change your location. But the bot will unban you easily.
