### ISSUE TITLE
is the bot working for y'all?

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#1182]

**Comment by Tochez** [comment]
nope

**Comment by BimbasVG** [comment]
Stop working for me...

**Comment by RipstiE** [comment]
Stopped working for me too...

**Comment by CreativiTimothy** [comment]
Servers are offline right now I think. I can't log in with my regular iPhone

**Comment by PokemonGoer** [comment]
It's down atm

**Comment by novincobra** [comment]
login in phone work, server bot down maybe

**Comment by cktisaac** [comment]
maybe server problem

**Comment by Tochez** [comment]
yea servers are offline 
![capture](https://cloud.githubusercontent.com/assets/20713623/17380223/1bc1200a-5994-11e6-82ff-afe1ab250455.PNG)

**Comment by evrine** [comment]
servers down probably

**Comment by KaV0** [comment]
its not the poke servers. smartphone pokego works

**Comment by BimbasVG** [comment]
http://ispokemongodownornot.com/

**Comment by gnzl0o** [comment]
same here pokemon in the phone totally works

**Comment by AriahVitae** [comment]
If u are alrealy log in ur phone its ok, but the bot need to log, and its the problem actually

**Comment by Tochez** [comment]
yes the servers are working. Bots arent because they have to log in which they cannot bc its unavailable.

**Comment by AriahVitae** [comment]
I think the do an update or something just wait

**Comment by lailaps** [comment]
Maybe they changed API?

**Comment by AriahVitae** [comment]
Login up try it

**Comment by cktisaac** [comment]
cant find pokestore

**Comment by Ar1i** [comment]
#1185
