### ISSUE TITLE
Even More Issue

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#1183]
![capture](https://cloud.githubusercontent.com/assets/20713623/17380169/d7884f30-5993-11e6-8bf8-158b6c024aba.PNG)

**Comment by cktisaac** [comment]
same here, are we getting banned?

**Comment by ElectricTaco** [comment]
The servers are down / experiencing issues.

**Comment by CreativiTimothy** [comment]
^

**Comment by ge1stbtch** [comment]
You should read the error messages before complaining lol

**Comment by TheAntonio422** [comment]
Nope, just server problems

**Comment by cktisaac** [comment]
phone's log in working well

**Comment by TheAntonio422** [comment]
yes on my pone it woks too, not here for some reason.

**Comment by abdellahaski** [comment]
try to disconnect and reconnect from your phone and you'll get the error

**Comment by LvGPoke** [comment]
seems like other PokeBots arent working aswell...

**Comment by BimbasVG** [comment]
http://ispokemongodownornot.com/

**Comment by Tochez** [comment]
![capture](https://cloud.githubusercontent.com/assets/20713623/17380309/93999864-5994-11e6-8180-6953e8ff91af.PNG)

**Comment by abdellahaski** [comment]
guys instead of opening a new issue check the servers status first here : [http://ispokemongodownornot.com/](http://ispokemongodownornot.com/)
