### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by i-am-nobody-1** [Ar1i/PokemonGo-Bot#1184]
some errors due to which i am unable to farm :/ please fix this and thanks for your help
![error](https://cloud.githubusercontent.com/assets/20818032/17380230/c3c1e626-598b-11e6-9f01-902b2c7570f9.png)

**Comment by BimbasVG** [comment]
http://ispokemongodownornot.com/

**Comment by LvGPoke** [comment]
Maybe Niantic took server down to implement the new pokémons :D

**Comment by itzjaydon** [comment]
why do i doubt that haha

**Comment by LvGPoke** [comment]
It would be better than banning us

**Comment by Ar1i** [comment]
#1185
