### ISSUE TITLE
PTC Log In Is Currently Offline

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#1185]
![capture](https://cloud.githubusercontent.com/assets/20713623/17380382/e2a65fbe-5994-11e6-8b20-deaaae6808c8.PNG)

**Comment by Qurus1** [comment]
Poodlecorp?

**Comment by itzjaydon** [comment]
im getting the error too

**Comment by sixmoonth** [comment]
but i can online when open from phone

**Comment by Qurus1** [comment]
me too.

**Comment by TouchTheSkies** [comment]
Getting the same error x.x

**Comment by Tochez** [comment]
SERVER IS CURRENTLY OFFLINE

**Comment by emilie253** [comment]
me too, but not with my phone.

**Comment by Tochez** [comment]
THE REASON WHY IT WORKS ON YOUR PHONE IS BECAUSE ITS LOGGED IN ALREADY

**Comment by LvGPoke** [comment]
How can you be logged in at your phone and pc the same time ?

**Comment by Jam1ePistol** [comment]
''Unable to authenticate try again later'' thats what phone says

**Comment by PokemonGoer** [comment]
reset your phone and it won't work

**Comment by Tochez** [comment]
@Jam1ePistol its becuase you tried to relog in but logging in is currently offline @PokemonGoer

**Comment by Jam1ePistol** [comment]
but if i log with google it logs completly fine

**Comment by sixmoonth** [comment]
when switch account it is on

**Comment by Jam1ePistol** [comment]
Google accounts got up and working just PTC ones are down :)

**Comment by Tochez** [comment]
@Jam1ePistol Its because google accounts work

**Comment by Tochez** [comment]
@Jam1ePistol dam u stole it before i said it XD

**Comment by itzjaydon** [comment]
back up now

**Comment by Tochez** [comment]
Ptc works @itzjaydon

**Comment by Tochez** [comment]
?

**Comment by itzjaydon** [comment]
for me it is yeah

**Comment by itzjaydon** [comment]
but an error is occurring (no pokestops nearby)

**Comment by AmbientLights** [comment]
I think they took down the api

**Comment by Jam1ePistol** [comment]
what that does mean ambient ?

**Comment by Tochez** [comment]
@Ar1i Please Fix

**Comment by AmbientLights** [comment]
was getting the no pokestops error for a while and it just stopped working all together. it says error loading pokemon list wrong uri or something and pokelocate completely stopped working

**Comment by itzjaydon** [comment]
going back to bignox till fixed

**Comment by AmbientLights** [comment]
but I can log in on the phone fine

**Comment by immoempe** [comment]
Just wait some minutes, servers are unstable yet

**Comment by Tochez** [comment]
@AmbientLight we will just have to wait. and if it doesnt fix by itself. Ar1i will fix it soon enough

**Comment by itzjaydon** [comment]
@Tochez  yeah probably on it already

**Comment by Ar1i** [comment]
Calm your titties guys, its the Server!

**Comment by Tochez** [comment]
@Ar1i Okie Dokie :D

**Comment by itzjaydon** [comment]
@Ar1i  hahahah

**Comment by itzjaydon** [comment]
@Ar1i great work by the way works like a charm normally

**Comment by Jam1ePistol** [comment]
If anybody manages to get on from PTC please say smth ! thanx

**Comment by Jam1ePistol** [comment]
I bet my dick this is happening because they try to get it working in Brazil......

**Comment by cktisaac** [comment]
@Jam1ePistol hype olympic

**Comment by immoempe** [comment]
Is working, but no pokestops yet, I will wait for servers lol

**Comment by Tymoc** [comment]
Same here... =)

**Comment by Midnlght** [comment]
Patience my children (':

**Comment by Tymoc** [comment]
LOL... actually have to "play" the game now... LMFAO!

**Comment by Jam1ePistol** [comment]
Some people say it is up some say not , i can log in on phone but nothing rly works
