### ISSUE TITLE
Pokemon Transfer Suggestion REALLY IMPORTANT FEATURE

### ISSUE THREAD

**Issue by smilehlolz** [Ar1i/PokemonGo-Bot#1186]
Hello, first of all thanks for the bot, it works nicely and it's been pretty handy.

After a few days using it I noticed it needs some fixes regarding pokemon transfer specially because the information is not very clear:

Max CP to transfer
Max IV to transfer

What are these exacly? I don't think it meets the criteria properly. If I am playing and farming I want to select the criteria like so:

Transfer Pokemon bellow _XXXX_ CP
or
Transfer Pokemon bellow _XXXX_ IV

That means I just want to keep Pokemon which are at least 1.500 CP and 95%+ IV. If you set one to 0 only one criteria will work. I want to keep every pokemo higher than 1500 CP and 0 for IV means the bot should ignore the IVs in this case.

That' the way it should work in my opinion. Hopefully you can make it work

**Comment by ge1stbtch** [comment]
> What are these exacly?

Every Pokémon with a CP count lower than X **OR** a IV percentage lower than Y gets transfered.
Meeting both criterias results in a transfer as well.

What I might add to your suggestion:

Add a list of Pokémon which should always be transfered. You catch them for XP but they get tranfered afterwards. The reason for my suggestion is that I'm getting Pokémon count problems because I always have like 50 rattata, pidgey etc.. I want to keep Pokémon that can be evolved but I don't want to keep these.

**Comment by cpblack** [comment]
The system works fine you just don't know how to use it

**Comment by immoempe** [comment]
I think the filters works fine, if you wanna keep only for CP, then set IV to 100, because if you put 0, you are giving the order to keep all pokemon = or > 0 IV

**Comment by gummyruler** [comment]
You know setting it to 1500CP cap and 100% IV would fix all your problems right?

**Comment by smilehlolz** [comment]
@gummyruler Then If I catch a lower CP than 1500 with IV 100% the pokemon will get transfered, which is not good.

**Comment by smilehlolz** [comment]
@cpblack The system is just not working. It just doesnt transfer any pokemon. At least for me

**Comment by cpblack** [comment]
The servers are down right now o.o

**Comment by smilehlolz** [comment]
@cpblack I know they're down, wasn't talking about right now

**Comment by cpblack** [comment]
You probably have keep pokemon which can evolve enabled t.t

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
