### ISSUE TITLE
Error instead of pokemon's images 

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#1189]
This is the problem. is Anyone aware of it ?
or knows how to fix ?
![image](https://cloud.githubusercontent.com/assets/14841132/17380937/82f53d80-5997-11e6-9978-b1195a280251.png)

**Comment by itzjaydon** [comment]
the servers are unstable just be patient

**Comment by Ar1i** [comment]
My servers are getting ddosd, thats why it happens.. cant do anything about it atm

**Comment by itzjaydon** [comment]
@Ar1i  damn wish this was working

**Comment by Tochez** [comment]
**Just Wait**

**Comment by LvGPoke** [comment]
Who would Ddos you ? You are god ! :*

**Comment by Midnlght** [comment]
why would you ddos a god

**Comment by cktisaac** [comment]
maybe the thieves ??

**Comment by zzzz9999** [comment]
DDOS? 
SoB's!

@Ar1i all the best!

**Comment by arjunvegda** [comment]
Why would anyone DDOS you ? You are amazing person. Wish there was a solution to prevent these kind of attacks and let the fucking world live peacefully !!!!

**Comment by Ar1i** [comment]
Mad ppl ddosing me :p

**Comment by cpblack** [comment]
@Ar1i Do you think there are multiple attacks happening?

**Comment by Ar1i** [comment]
Yeah, but i cant put on cloudflare to prevent layer7 attacks cause the bot which want information cant download it too then @cpblack

**Comment by 13XxM1CHA3lxX37** [comment]
I bet that's that Pokecrot fucktard

**Comment by cpblack** [comment]
What if you made it so that the client uses throwaway accounts to manually sweep the area and keep a map of all traveled area and find the pokemon so that there would be no server needed

**Comment by puturaya** [comment]
same here problem

**Comment by Ar1i** [comment]
#1196 read there please :)!

**Comment by Ar1i** [comment]
@cpblack that has to do with pokemon servers not mine

**Comment by JWPapi** [comment]
Can we donate to get better servers?
