### ISSUE TITLE
"BadAuthentication" Error. (On NEW setup)

### ISSUE THREAD

**Issue by FrozGR** [Ar1i/PokemonGo-Bot#119]
I am trying to setup the bot's latest version, on a fresh new folder, and it bugs .. hard.
The error i  get is this one:

![image](https://cloud.githubusercontent.com/assets/12578906/17230491/1400ae9e-5525-11e6-83cd-428cf68dbe2d.png)

**Comment by Schuhsack** [comment]
ur not the only one here... just wait for the commuity. ill hope they will fix it.

**Comment by djdomrep** [comment]
Guys it's not a bug. the servers are laggy like mentioned in the last 10 issue reports.
please don't create any new issue reports.

**Comment by InvisibleTouch** [comment]
google server are laggy... stop the bot and wait

**Comment by MarvinSCR** [comment]
i have the same problem now -.-

**Comment by MarvinSCR** [comment]
google account and PTC account same problem...

**Comment by Ar1i** [comment]
Wait for the Servers to come up again. Bad Auth could be false Account Data. And @MarvinSCR stop fucking spamming. Already told you.

**Comment by MarvinSCR** [comment]
sry

**Comment by uNNfair** [comment]
Hey, I´m new. Is there an instruction how to update?

**Comment by Phantisy1234** [comment]
My old error changed to this one

**Comment by XxAirWalker26xX** [comment]
Same
I used to have a diff error. Hopefully he fixes this soon as this doesnt seem to be pokemon go server related as i have pidgey farm bot running with 1k accounts fine

**Comment by Ar1i** [comment]
fixed.
