### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cpblack** [Ar1i/PokemonGo-Bot#1190]
I was wondering if you could add an egg feature, it would also be nice if you could set the minimum KM distance for both the finite and infinite incubators. Also could you add renaming and toggling favorite status? I don't know if the program does this already but it might be less suspicious to Niantic if the program was set to use the roads instead of flying over buildings
Also I just remembered another potential feature, I think it would be could if you could log in to multiple throwaway accounts and use them to sweep the area for pokemon then your main account could go directly to the pokemon for much faster catching

**Comment by cpblack** [comment]
Also I just remembered another potential feature, I think it would be could if you could log in to multiple throwaway accounts and use them to sweep the area for pokemon then your main account could go directly to the pokemon for much faster catching

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
