### ISSUE TITLE
Not able to find pokestops

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#1191]
![image](https://cloud.githubusercontent.com/assets/14841132/17381063/2cae50c8-5998-11e6-887e-848fd21b9a03.png)

It gives me this error.

I am aware that the location i have chosen has more than 100 poke stops and was working fine until this morning. Seems like either pokemon go servers are down or something is wrong with the bot.

**Comment by pokegoload** [comment]
same

**Comment by berk1n** [comment]
Ar1i 's servers are getting ddosed just wait

**Comment by Sonyc88** [comment]
same and thanks 4 info :)

**Comment by adman9031** [comment]
can someone update here when we are good again?

**Comment by CastleFan1983** [comment]
thx for the info

**Comment by 13XxM1CHA3lxX37** [comment]
> @Ar1i 's servers are getting ddosed just wait

Source @berk1n ?

**Comment by Dliang2k** [comment]
with my iphone, i can play without any problem. i think, game server has changed something. We can just wait

**Comment by berk1n** [comment]
@13XxM1CHA3IxX37 https://github.com/Ar1i/PokemonGo-Bot/issues/1189

**Comment by AnixOpz** [comment]
Niantic has changed the way the MapObjects are named.

**Comment by LvGPoke** [comment]
Source?

**Comment by Ar1i** [comment]
#1196 read there please :)!

**Comment by ebargan1** [comment]
[url=http://hizliresim.com/z48Yp4][img]http://i.hizliresim.com/z48Yp4.jpg[/img][/url]
