### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1192]
i can login now but i cant find any pokestop nearby i can login through my phone though but error throught bot can u fix it Ar1i

**Comment by pokegoload** [comment]
same

**Comment by berk1n** [comment]
Ar1i 's servers are getting ddosed just wait

**Comment by sunit1998** [comment]
oh ok

**Comment by lordzxil** [comment]
LOL who is ddosing?

**Comment by sunit1998** [comment]
probably niantic

**Comment by samueleycw** [comment]
we need Cloudfare

**Comment by Tymoc** [comment]
And for the programming impaired... what is ddosing ???

**Comment by madeinyashiro** [comment]
Juste use Google...

https://en.wikipedia.org/wiki/Denial-of-service_attack

**Comment by BotriXMX** [comment]
I dont think that Ar1i 's servers are getting ddosed cause every bot got this issue

**Comment by Sintonic** [comment]
starting many requests to one server in a short time period.

**Comment by GHANT** [comment]
FFS...

**Comment by GHANT** [comment]
I'm level 33. I wanted to get to 34 today...

**Comment by LvGPoke** [comment]
Me too :(

**Comment by Shikkaku** [comment]
then i rly think this is niantic doings, just before the server went down and now no bots are working

**Comment by adman9031** [comment]
yeah i think so too

**Comment by Sintonic** [comment]
Niantic fixed the bot.

**Comment by adman9031** [comment]
is that confirmed?

**Comment by LvGPoke** [comment]
How do you know?

**Comment by CastleFan1983** [comment]
atleast bluestacks with fake gps is still working

**Comment by LvGPoke** [comment]
True ... but without Pokevision it sucks....

**Comment by Sintonic** [comment]
Yes it do work but the systems are based on different systems.

**Comment by Ar1i** [comment]
NOT MY SERVERS! PokemonGo Servers are laggy, my servers are only for images & languages

**Comment by GHANT** [comment]
Getting error pokemon icons. It wont even load.
