### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by NovaAfterComa** [Ar1i/PokemonGo-Bot#1193]
Hi, why it isn't possible to use Italian translation even if it's in the files (All the flags are shown except for the Italian one)
![1](https://cloud.githubusercontent.com/assets/20824494/17381479/660ebf2c-59cc-11e6-9da4-b9018aa58c49.PNG)
![2](https://cloud.githubusercontent.com/assets/20824494/17381478/66068794-59cc-11e6-986f-3ad7aabada22.PNG)

**Comment by nickzheng998** [comment]
could you also add the chinese ?

**Comment by IceQ1337** [comment]
We already got a italian translation. It is not implemented yet.
@nickzheng998 We can if you translate it for us.

**Comment by RaphaelYLG** [comment]
@IceQ1337 I can translate all of them to Chinese for you.

**Comment by nickzheng998** [comment]
Thank you

**Comment by BackZ** [comment]
i can translate all of them to French for you.

**Comment by dialgalex59** [comment]
It've already been translated in french ^^

**Comment by BackZ** [comment]
Missing the name of pokemon, bug accents.

**Comment by dialgalex59** [comment]
For the name idk but for the bug i made a new json file in an old issue, but if you can translate all of the soft, it would be great :)

**Comment by BackZ** [comment]
ok I'll wait for the next update . and I translate.

**Comment by IceQ1337** [comment]
Everything which can be translated is translated.
The translations are currently only for the Main GUI.
The Pokemon List GUI and Pokemon Names and Stuff are not in the translation system yet.
We have other stuff to work on.

**Comment by BackZ** [comment]
"Use LuckyEgg if not running"
"General" "items" "set location" "account info"
and all of accent bug.

**Comment by nickzheng998** [comment]
Thanks lot. Do not worried about it at this point.

**Comment by BackZ** [comment]
I just want to help. 
I am French and the translation is not correct syntax.

thank you again for your work.

**Comment by IceQ1337** [comment]
@BackZ We have other stuff to work on.
To see that Issues and Pull-Request only contain translations and shit is really annoying.
People just want their name on the credits list i added a few days ago.

If there is enough time and space to add a new language or change things, we will do that.

**Comment by BackZ** [comment]
Ok, I understand. but I do not care to be in a list of credit. I just wanted to help . good luck for the future

**Comment by nickzheng998** [comment]
http://www.hk01.com/%E5%A5%BD%E7%94%9F%E6%B4%BB/33438/Pokemon-GO%E6%94%BB%E7%95%A5-%E7%8F%8D%E8%B2%B4%E5%AF%B5%E7%89%A9%E5%9C%96%E6%96%87%E5%88%97%E8%A1%A8-%E4%B8%AD%E8%8B%B1%E6%96%87%E8%AD%AF%E5%90%8D%E4%B8%80%E8%A6%BD
A  list chinese and english for 150 pokemon list

**Comment by IceQ1337** [comment]
@BackZ Don't get me wrong, we are happy to add people to the credits for their contribution.
It's just, since we first released a translation, everyone wants to be part of it.
We appreciate help from everyone, because this is most-likely a community-project.
I just needed to make sure that translations got lower-priority as other things :D

**Comment by nickzheng998** [comment]
i just try to help. if do not have time, do not do add it on this time.

**Comment by nickzheng998** [comment]
https://www.pokeradar.io/#

this is scanner.  It is not run with the Api. I hope that it may work for our problem. 

I wish

**Comment by IceQ1337** [comment]
@nickzheng998 It does. And no, it doesn`t help us.
@Ar1i will probably update the bot tomorrow.
