### ISSUE TITLE
The clone is dead

### ISSUE THREAD

**Issue by Albeoris** [Ar1i/PokemonGo-Bot#1194]
> 
    So there is a guy, which copys 1:1 my source and puts it online.
    Help me to get his Site + copied Bot removed.
    His site is: https://www.pokecrot.com/
    Until that is done, i only publish builds. No Source.

Done.

**Comment by Ar1i** [comment]
Yeah domain got taken down!

**Comment by tanpaulus0605** [comment]
why they are proud to make a clone of your bot ?

**Comment by Grieche** [comment]
@Ar1i fix your servers pls

**Comment by Ar1i** [comment]
cause they are stupid, he maked money with the bot lmao but closing this. @Grieche cant do shit if they get ddos´d
