### ISSUE TITLE
*READ* Pokemon Servers laggy/down

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#1196]
The Pokemon Servers in some Regions with the Map are not UP atm. so it cant get any Pokestops. Try it again later. If you cant see sprites in the Pokemon List, its cause my servers are getting ddos´d.

**Comment by cpblack** [comment]
@Ar1i Maybe you should make it in console say the servers are down and to not post a bug report

**Comment by CastleFan1983** [comment]
pokemongo servers aren´t down, i can still play with my phone

**Comment by lailaps** [comment]
Maybe done by this kid from Jakarta?!

**Comment by Ar1i** [comment]
@CastleFan1983 but it has to do with pokemon servers, nothing with the bot

**Comment by Ar1i** [comment]
@CastleFan1983 i can login with the bot but it doesnt find any pokestops, cause servers are laggy af

**Comment by AnixOpz** [comment]
Niantic has updated map objects, this is the reason you are getting the message "No usable Pokestops in your area". All bot's will have to be updated so that they have the correct info and that they can work again! -MobBot developer

**Comment by AnixOpz** [comment]
I have another bot with the same errors so nothing to do with the servers x)

**Comment by GHANT** [comment]
Why are they getting ddossed? Wtf would anyone have to gain from pokemon go..

**Comment by Markogeta** [comment]
Thanks for the answer,
I can leave my computer with program on or it needed to restart the bot when the problem will be solved?

**Comment by P529** [comment]
Not pokemon go is being ddosed the server of Ar1i are getting ddosed thats why there are no pokemon sprites showing

**Comment by CCminus** [comment]
> I have another bot with the same errors so nothing to do with the servers x)
It can still be the servers......

**Comment by AnixOpz** [comment]
How can it be the servers? I can log in from my phone and still play

**Comment by Ar1i** [comment]
@P529 exactly.

@AnixOpz can you use pokestops?

@Markogeta just let the bot run should fix himself

**Comment by LvGPoke** [comment]
Anyone knows how long that takes ? Just asking if I can go to sleep :D

**Comment by AnixOpz** [comment]
The only thing i can't to is use pokestops Ar1i

**Comment by P529** [comment]
My bot cant find any pokestops i think what @AnixOpz said might be true with the updated pokestops

**Comment by Mrtkcmz** [comment]
I think they updated Pokemon GO API

**Comment by tanpaulus0605** [comment]
you're all wearing these BOT for free
should not be too many protests

**Comment by 12348766754** [comment]
@Mrtkcmz they did

But since this is freeware, and the bot is just great, we should give the developer time to fix this issue / check if there is an error with the API.

**Comment by Conorh779** [comment]
Ar1i the API was  updated and apparently only botters could be online while they were updated so what i heard is they logged everyone who was online when they shouldt and a perm ban wave is coming. Also the bot is unreal its by far the best!

**Comment by Conorh779** [comment]
Meant to donate but couldn't, expect $50 soon

**Comment by Ar1i** [comment]
@Mrtkcmz @LvGPoke @AnixOpz - Thanks for the post Anix, 
@Conorh779 any proof? 

So as i said, has nothing to do with the Bot. Just wait.

**Comment by AnixOpz** [comment]
Thanks for the great work Ar1i and all the team behind this great project

**Comment by CCminus** [comment]
@Conorh779 I can confirm that. App got updatet and even android emulators like bluestacks wont work either (device is not compatible anymore)

**Comment by AnixOpz** [comment]
I don't think the api has been updated

**Comment by CastleFan1983** [comment]
if i would get a perma ban i will stop playing, i have no great citys nearby and just 8 pokestops at my whole village, i have no other chance than using bots, otherwise it would take me years to reach lvl 40

**Comment by TouchTheSkies** [comment]
But there were no updates for it the app in the App Store/Play store. I wasn't aware they could update it without the players knowledge.

**Comment by Nedovik** [comment]
@CCminus Nox works just fine =) farming Jyms right now =)

**Comment by CastleFan1983** [comment]
@CCminus bluestacks still works, just google for the pokemongo apk

**Comment by pokerave** [comment]
Bluestacks sucks.. lol. i have one better and faster. :+1:

**Comment by CCminus** [comment]
@CastleFan1983 @Nedovik @TouchTheSkies already then, sorry for the false alarm guy

**Comment by 12348766754** [comment]
Kinda off topic, but since this topic is high populated -> is there a way to battle a gym while being home?

**Comment by Qurus1** [comment]
Have found that on the web!!
![cpwe5z4](https://cloud.githubusercontent.com/assets/20823864/17382069/20ef50ca-599d-11e6-9733-bbec40cf0763.jpg)

**Comment by Adeffsmith** [comment]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/568584-pokemon-go-api-change-reason-not-working-bots-maps.html

"POKEMON GO API CHANGE - Reason for not working bots maps
Hey, I'm a Pokemon map developer and also I'm into botting.

Just wanted to told you all that Niantic changed the API in the latest update.

What that means?

That it is impossible to run ANY of the bots or a maps.

Just because now any non-updated connection (you know that mobile app was updated a few hours ago) is not getting any pokestops or pokemon.

You can do NOTHING so don't spam the forum. Just wait for the update but it'll take some time, some of the bot could be updated TOMORROW as a EARLIEST date, most likely 2-3 days.

This as a basic info, if you want to know more detailed info let me know in posts.

Cheers!"

From http://www.ownedcore.com/

**Comment by 12348766754** [comment]
@Qurus1 that's old. Saw that one tomorrow already.

**Comment by AnixOpz** [comment]
It seems that major changes were made to the way clients communicate with the API. - MobBot developer

**Comment by pokerave** [comment]
@12348766754 its just 20 mins ago
![20mins](https://cloud.githubusercontent.com/assets/20603254/17382182/4499a1fc-59d8-11e6-9635-80e9e66c8ab6.jpg)

**Comment by Ar1i** [comment]
#1202 closing this here. I am trying to Update the stuff.
