### ISSUE TITLE
bot macht probleme

### ISSUE THREAD

**Issue by waldiludi** [Ar1i/PokemonGo-Bot#1198]
[22:54:29] Exception: System.NotImplementedException: Die Methode oder der Vorgang ist nicht implementiert.
   bei PokemonGo.RocketAPI.Client.<Incubate>d__50.MoveNext() in C:\Users\waldh\Desktop\poké\PokemonGo.RocketAPI\Client.cs:Zeile 565.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<StartIncubation>d__20.MoveNext() in C:\Users\waldh\Desktop\poké\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 672.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__11.MoveNext() in C:\Users\waldh\Desktop\poké\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 145.
[22:54:29] Starting again.. But waiting 10 Seconds..

schreibt er und macht nichts... vorhin hat alles noch geklappt. Ist neuste version. Schreibt hin und wieder die Accinformationen und dann immer wieder das. Danke im vorraus

**Comment by pokerave** [comment]
#1196 please read

**Comment by madeinyashiro** [comment]
Read https://github.com/Ar1i/PokemonGo-Bot/issues/1196

**Comment by Ar1i** [comment]
^

**Comment by monoxacc** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/page-286#post-497882
