### ISSUE TITLE
[Problem] RocketAPI

### ISSUE THREAD

**Issue by Phantisy1234** [Ar1i/PokemonGo-Bot#120]
This pops up every time, after I hit "Save Configuration"
![29a25bb40b6474b2402d75ddbfe0f181](https://cloud.githubusercontent.com/assets/20712556/17230588/d958fc90-54d1-11e6-9a7c-93a8f1c12b0b.png)

**Comment by SpoderPig** [comment]
same here :/

**Comment by InvisibleTouch** [comment]
Google server have the problem at the moment.... Stop bot and wait...

**Comment by SpoderPig** [comment]
i was thinking that, but i just want to "catch em all" xD
thanks anyway :)

**Comment by Ar1i** [comment]
Please read before you open. #119

**Comment by MarvinSCR** [comment]
and PTC Server ??

**Comment by MarvinSCR** [comment]
PTC Server is Online but i cant connected same error..

**Comment by Schuhsack** [comment]
Man pls.. can someone mute that Marvin? 💃 🐰
