### ISSUE TITLE
ETA on egg hatcher?

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#1200]
I seen you comment on working on it or something along those lines any idea when it will be ready? it's extremely useful

**Comment by Abbasoo** [comment]
@Ar1i ETA ?

**Comment by Ar1i** [comment]
first of all fixing the bot so it works again

**Comment by pokerave** [comment]
getting the bot running is priority i thinks. no use if egg hatching working but bot is not. :dancers:

**Comment by rayito45** [comment]
do not listen,  Finish it as you believe appropriate, I prefer a 100 upgrade than 5 per hour

**Comment by setoy** [comment]
Finished it with my latest PR.

**Comment by xJihadx** [comment]
Want a egg hatcher? Download bluestacks, install pokemon go and hold down one of the w,s,a,d keys and walk around the city.

**Comment by xJustx** [comment]
^
