### ISSUE TITLE
Max Radius Issue

### ISSUE THREAD

**Issue by ruili23** [Ar1i/PokemonGo-Bot#1204]
![daw](https://cloud.githubusercontent.com/assets/20819009/17382289/b4a4a4c2-5a02-11e6-93ea-503db337aec2.png)

i got this problem when applying bot, i try all the radius, but it always said that. need some suggestions. thank you

**Comment by Ar1i** [comment]
#1202

**Comment by pokerave** [comment]
Delete LastCoords in config folder.. but bot not working atm.
