### ISSUE TITLE
frage

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#1207]
wenn ich in das verzeichnis
PokemonGo.RocketAPI.Console\bin\Release
gehe kann ich da eier ausbrüten ankreuzen und mit dem normalen Build nicht?
Und wie kann ich mehrere account mit Visual studios benutzten? also mit den verzeichnis
PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\bin\Release

**Comment by Rhukz** [comment]
das geht noch nicht, er ist gerade dabei den bot zu fixen weil die API umgestellt wurde von Niantic, das hat gerade priorität, und nicht eier ausbrüten... ^^ 

starte doch einfach mehrfach die anwendung ;)

**Comment by Ar1i** [comment]
#1202
