### ISSUE TITLE
Hey guys i need a bit help ***pics included***

### ISSUE THREAD

**Issue by NuttPlaysHG** [Ar1i/PokemonGo-Bot#1209]
Hey ya'll i'm getting this problem
![screen shot 2016-08-03 at 22 24 34 2](https://cloud.githubusercontent.com/assets/20825401/17382826/cb198494-59ca-11e6-91a4-48542ef31b18.png)
![screen shot 2016-08-03 at 22 24 31 2](https://cloud.githubusercontent.com/assets/20825401/17382829/cc9572ce-59ca-11e6-9651-137c14044152.png)

**Comment by Ar1i** [comment]
#1202
