### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by MarvinSCR** [Ar1i/PokemonGo-Bot#121]
![jjj](https://cloud.githubusercontent.com/assets/20703104/17230760/5d4a800e-551e-11e6-99fb-ede81620e6f1.PNG)

**Comment by Ar1i** [comment]
Kannst ignorieren, und man sieht deinen Usernamen. Just saying!

**Comment by InvisibleTouch** [comment]
same here :/
google server problem...
stop bot and wait
