### ISSUE TITLE
Recent changes on pokemon go server does that the bot can't read the data map

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#1210]
Several programers people are saying on forums that now only can read data map every 10 seconds from the server.
If you try now the bot and put walk 5 and radios 10.000 you can see that there aren't pokestops neither pokemons nearby.

**Comment by Ar1i** [comment]
i am only reading it 1x time for the pokestops then looping for it. so this cant be true

**Comment by sunit1998** [comment]
there is api change so the bot dont notice the pokemons and pokestops please wait for sometime Ar1i is trying to make a solution

**Comment by Xelwon** [comment]
Ahh, ohh, bad news then :'( .  
Ok.
