### ISSUE TITLE
Error, cant find any pokestops in a range of 5000m and more.

### ISSUE THREAD

**Issue by Tavorib** [Ar1i/PokemonGo-Bot#1212]
Hey ar1i,
i was playing on the older version of your bot and suddenly it stops work .
i had an error while launching the exe file, that saying microsoft.net framework,
i downloaded your latest updated files of the bot, and that error disappeared.
now im troubleing with another problem.
its keep saying cant find pokestops in a range of 5000m, Probably server unstable or youve visted them all.
it keep saying that dosent matter where i put my player on the map, and also says 'starting again, but waiting 10 sec' . 
Please, Can you help me ? 
Thanks.

**Comment by IceQ1337** [comment]
Probably a server issue. Got the same problem^^

**Comment by gummyruler** [comment]
Game is empty and they changed the API. So yea bot is currently not working.

**Comment by eigur** [comment]
#1202

**Comment by Tavorib** [comment]
did it will work soon or they block the bot ?

**Comment by Danian66** [comment]
You might want to do some readings on other similar issues (forum threads).

**Comment by Ar1i** [comment]
#1202
