### ISSUE TITLE
Pokemon Go Problem

### ISSUE THREAD

**Issue by mhrrmarat** [Ar1i/PokemonGo-Bot#1215]
![20160804_012835](https://cloud.githubusercontent.com/assets/20826043/17384306/da18d008-59e3-11e6-87a9-9cac66b88955.jpg)

**Comment by eigur** [comment]
#1202

**Comment by eigur** [comment]
just read stop spamming problems

**Comment by k0b000m** [comment]
this isnt what mine says? :P it only happens with updated version

**Comment by k0b000m** [comment]
not spamming problems either. dont know if its something with my computer or the program

**Comment by pokerave** [comment]
@k0b000m you are using a POKECROT BOT.. lol WTH??
