### ISSUE TITLE
Paar Sicherheitsupdate 

### ISSUE THREAD

**Issue by Provokan** [Ar1i/PokemonGo-Bot#1217]
moin,

ich habe mal ein wenig wegen der api geschaut 
und habe etwas sehr interessantes gefunden, ich denke dass diese Eigenschaft doch dem Bot sicherer macht wenn nicht jeder Ball direkt 100% gewinnt sondern auch die Master Bälle benutzt werden, das ganze findest du unter https://github.com/Grover-c13/PokeGOAPI-Java/commit/626145894534c4e85213eaac4116a5be519b104a

**Comment by Ar1i** [comment]
wird bereits
