### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by Imqtpie** [Ar1i/PokemonGo-Bot#1218]
![screenshot_27](https://cloud.githubusercontent.com/assets/20826505/17384896/6678c198-59df-11e6-9fb7-2d71d240c82c.png)

Its says this but idk why I tryed entering the game and it all works fine, and I use this spot lots of times before and it worked.

**Comment by Sintonic** [comment]
Close. Learn to read.

**Comment by Imqtpie** [comment]
"We can't find any PokeStops, which are unused! Probably Server unstable, or you visited them all. Retrying..," It says that but it's the center of Tokyo how could it not have any.
