### ISSUE TITLE
Verstehe gerade nix mehr....

### ISSUE THREAD

**Issue by L3v1X** [Ar1i/PokemonGo-Bot#1221]
Also ich weiß nicht ob wer Deutsch kann und mir helfen könnte aber ich probiere es mal...
Also er findet keine Pokestops mehr [wird bei mir so angezeigt] und ich lese mich gerade hier durch und habe gesehen das was mit der api nicht stimmt oder sie geändert wurde.... was ist jetzt die Api ?
Lg LeviX

**Comment by OfficialMorise** [comment]
Das ist jetzt zu kompliziert zum erklären, ich denke bis Morgen müsste das gefixt sein. Also einfach abwarten. :)

Als Alternative könntest du ja NOX benutzen.

**Comment by Ar1i** [comment]
^

**Comment by L3v1X** [comment]
achso ok danke ^^ und viel glück ! :D
