### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by nandinharec** [Ar1i/PokemonGo-Bot#1222]
[20:18:28] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   em PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) na C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:linha 34
   em PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() na C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:linha 129
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() na C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:linha 53
[20:18:28] Trying to Restart.
[20:18:28] Restarting in 10 Seconds.
[20:18:30] Error reloading Pokemon list: BadAuthentication

**Comment by Tochez** [comment]
**Can u read before posting** Thanks

**Comment by Ar1i** [comment]
^
