### ISSUE TITLE
[Translations] Italian & Romanian

### ISSUE THREAD

**Issue by IceQ1337** [Ar1i/PokemonGo-Bot#1224]
PRs of new languages are almost useless and spamming the PRs-List.
I've saved flag images, credits and translation files for italian and romanian translations from an old PR.
You can edit those as you want and if there is enough time to add more translations, we will add them.

[it+ro.zip](https://github.com/Ar1i/PokemonGo-Bot/files/400512/it.ro.zip)

**Comment by xJustx** [comment]
Thank you but do a Pull request for this.

**Comment by IceQ1337** [comment]
@xJustx Hab Ar1i bescheid gegeben. Hatte mit ihm darüber selbst geschrieben. Aber dauernd diese Translation PRs nerven, vor allem weil es wichtigeres gibt. Da kann man sich einige Konflikte ersparen.

Brauchte nur nen Platz um die Dateien aus meinem alten PR zu sichern.

**Comment by xJustx** [comment]
Ich leite ihm das weiter.
