### ISSUE TITLE
Cant get Pokestops 

### ISSUE THREAD

**Issue by skalomenia** [Ar1i/PokemonGo-Bot#1225]
Hello,
it been much than 6 hours, my bot doenst detect any pokestops and it shows 
![image](https://cloud.githubusercontent.com/assets/20742321/17385437/9caca7ca-59da-11e6-9bd7-a8921c41740b.png)

**Comment by GrungeGut** [comment]
#1202

**Comment by LikeAFisch** [comment]
tomorrow it's fixed!

**Comment by plowzey** [comment]
Updates have been done to the APIs & the in-game MAPS, therefore bots will be down & will not work for a while. If you try to run the bot, you will recieve "No usable Pokestops in your area"For now, you will receive errors while running the bot & no bot will work. You are not banned, do not worry. There is an estimated ETA of 24-48 hours on the bot fixes or update(s)

**Comment by xJustx** [comment]
^
