### ISSUE TITLE
Go to Pokestop takes hours

### ISSUE THREAD

**Issue by NiowGo** [Ar1i/PokemonGo-Bot#1227]
Bonsoir,
Le bot trouve un pokestop mais il doit prend un maximum de temps, pour y aller.
Good evening,
The bot is a pokestop but it must take much time to go.
![capture](https://cloud.githubusercontent.com/assets/20826867/17385694/a1439456-59e4-11e6-8df9-03f2922d1fee.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20826867/17385693/a1374eee-59e4-11e6-8c7f-4b7b0267ce8b.PNG)
419900/60= 6998,33..min
6998    /60= 116,6388888888889 Heure - Hour

**Comment by Fhajad** [comment]
#1202

**Comment by 13XxM1CHA3lxX37** [comment]
Delete LastCoords.txt

**Comment by CP02A** [comment]
It doesnt work

**Comment by CP02A** [comment]
The Niantic API Changed

**Comment by CP02A** [comment]
it is getting fixed right now

**Comment by xJustx** [comment]
^ #1202
