### ISSUE TITLE
Stops Not in range 

### ISSUE THREAD

**Issue by GunplayVII** [Ar1i/PokemonGo-Bot#1228]
Poke stops not in range idk if niantic server problem or the .Bot :D just a heads up <3

**Comment by CP02A** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1202

**Comment by CP02A** [comment]
Information is there

**Comment by Tochez** [comment]
@GunplayVII  CLose Plz

**Comment by CP02A** [comment]
cant... I wish I could

**Comment by xJustx** [comment]
^
