### ISSUE TITLE
[German] Erklärungen & Hilfestellungen

### ISSUE THREAD

**Issue by Fruschel** [Ar1i/PokemonGo-Bot#1229]
Hallo.

Ich wende mich speziell an die Entwickler / Mitwirkende des Bots, denn mich würde persönlich als Hobby-Programmierer interessieren, wie man bei so etwas vorgeht - woher bekommt man die API, wie baut man diese in ein Programm ein, weil bis auf ein paar Abschnitte im Quellcode ist mir der Rest Spanisch.

Außerdem:
Wenn ich das Projekt in Visual Studio debugge, funktioniert nichts, der Bot startet nicht? Wieso?

---
Tut mir Leid übrigens dass ich dafür ein Thread in "Issues" erstellt habe, benutze Github nicht so oft und wusste deshalb nicht wie ich z.B. den Nutzer "Ar1i" anschreiben sollte.

MfG,
Fru. :)

P.S.: Ihr macht, aber das hört ihr sicherlich in letzter Zeit sehr oft, eine hervorragende Arbeit, alle Achtung, und lasst euch nicht aus dem Ruder treiben durch die momentane Problematik, stay cool. :)

**Comment by CP02A** [comment]
Es ist geschrieben in C#

**Comment by Fruschel** [comment]
Das habe ich auch mitbekommen. Aber dennoch beantwortet es nicht meine Frage, ob es irgendeine Möglichkeit gäbe, mit dir, oder irgendjemand anderen der daran mitentwickelt, Kontakt aufzubauen, vielleicht mal über'm TeamSpeak quatscht. Schadet ja keinem. :)

**Comment by IceQ1337** [comment]
Der Bot funktioniert zurzeit nicht. Steht mitlerweile aber auch oft genug irgendwo.
GitHub hat kein PM System.

Die API bekommst du vom "Hersteller" selbst, siehe Google, wo du sie einfach laden kannst, oder du findest sie im Quellcode einer Anwendung.

Wie du eine API einbindest etc. findest du in zahlreichen Tutorials im Internet.
Meine Empfehlung ist ein Handbuch.
Ich kann "The C Programming Language" von Brian W. Kernighan und Dennis M.Ritchie empfehlen.
Davon die "Second Edition". Das Buch ist allerdings in Englisch verfasst, aber leicht verständlich.

**Comment by Fruschel** [comment]
Hallo IceQ1337, Englisch ist für mich kein gewaltiges Problem.
Habe mein "Problem" (wenn man es Problem nennen kann) auf Deutsch verfasst, weil ich mir schon denken konnte, dass ihr auch Deutsch seid. :)

**Comment by Fruschel** [comment]
Ich hoffe ich raube euch nicht gewaltige Zeit mit meinem Thread, während ihr den anderen Github-Mitgliedern erklärt was momentan nicht läuft. :)

**Comment by Fruschel** [comment]
Ach, und im Bezug auf das Buch:
Danke für die Empfehlung, notfalls komme ich auf das Buch zurück, doch ich finde, dass bei mir die Lernkurve wesentlich höher ist, wenn ich mit einer Person quatsche die Ahnung von ihrem Fach hat, kann ich schlecht beschreiben, finde es aber wesentlich angenehmer. :)

**Comment by IceQ1337** [comment]
Nein, wir sind da relativ einfach gestrickt. Ich greife @Ar1i ja auch nur leicht unter die Arme.
Wenn die Leute zu doof sind sich zu informieren können wir da immerhin nichts für.
Oben steht der Link zum Projekt, da kann sich jeder den Thread bei High-Minded durchlesen.

**Comment by IceQ1337** [comment]
Das Problem dabei ist, eine Person erklärt dir nicht das, was du wissen musst.
Dafür müsstest du Kurse belegen.
Das Buch ist insofern gut, da es alles erklärt, aber von Anfang an Übungsaufgaben eingebaut sind.
Sprich es behandelt ein Thema und lässt dich das gelernte direkt selbst anwenden.

**Comment by IceQ1337** [comment]
Ich glaube nicht, dass es eine Person gibt, die dir die Basics und alles weitere mündlich einfach so erklärt, dass würde ausserdem viel zu lange dauern^^

**Comment by Fruschel** [comment]
Ich will nicht sagen dass ich der gewaltige Profi im Programmieren bin, aber ich glaube du schätzt mich völlig falsch ein.

Basics, Grundwissen & Logik ist für mich kein Problem - nur mal so nebenbei: mit Basics meine ich halt die Basics für den "normalen" Hobby-Programmierer. :D
Aber wenn ich dann an den richtig coolen Stuff ranmöchte, sei es nur das Auslesen von einfachen Adressen bzw. das Arbeiten mit Multi-Lvl-Pointern bei WoW etc., da kriege ich schon einen Hals - ich mache vermeindlich alles richtig, aber dann scheinbar wiederum nicht.

Deshalb würde mich mal so brennend interessieren, wie ihr an den Pokemon Go Bot rangegangen seid, was hat euch animiert?

**Comment by IceQ1337** [comment]
Auf die Frage kann ich leider nicht antworten.
Der Bot-Ursprung liegt bei anderen Entwicklern. Habe den Bot dort seit Tag 1 verfolgt.
@Ar1i hat nur eine deutlich verbesserte Version entwickelt und seit dem contribute ich hier.
Melde dich bei ihm via PM auf High-Minded.net, vielleicht erzählt er dir was. (Name: Radat.)

**Comment by Fruschel** [comment]
Okay. Nice. 

Das war bis jetzt eigentlich alles. :-)

Sachma, zockst du CS:GO? :D

**Comment by IceQ1337** [comment]
Warum?

**Comment by Fruschel** [comment]
Ja um zu zocken, eine Runde Matchmaking, da du Ar1i kennst, und ich sein Steam-Profil gecheckt habe und er auch CS:GO zockt, nehme ich mal an, dass du es auch spielst. :D

**Comment by IceQ1337** [comment]
Ar1i und Ich haben eigentlich nichts miteinander zu tun. Ich greife ihm lediglich unter die Arme^^
Ich bin allerdings seit gut 30 Stunden wach und werde jetzt erstmal schlafen gehen...
Morgen können wir gerne eine Runde spielen^^

**Comment by Fruschel** [comment]
Unter was für'n Namen findet man dich :)

**Comment by IceQ1337** [comment]
IceQ?!

**Comment by Fruschel** [comment]
Bei über 100 Millionen Steam-Nutzern tümmeln sich so einige IceQ's zusammen, ein Link wäre nicht schlecht. :D

**Comment by Fruschel** [comment]
http://steamcommunity.com/jacktheinsider

Ich glaube damit fahren wir beide besser. ;'P

**Comment by Fruschel** [comment]
Aber die Falle ruft auch langsam bei mir. Wünsche dir eine gute Nacht. Hoffentlich zocken wir morgen. :D

**Comment by djdomrep** [comment]
Pointer usw. sind hier nicht gefragt da man keine Daten aus der Memory lesen muss.
Die API ist eine Schnittstelle um zwischen Server und Client zu kommunizieren.
Freie Entwickler versuchen auf diese API zuzugreifen um so Informationen über das Spiel abzufragen dabei verwenden sie die gleichen Zugriffsmethoden wie das Spiel.
Daraus entstehen können Webseiten oder Programme wie dieser Bot hier.

**Comment by Fruschel** [comment]
Also hat im Prinzip jede App, von Facebook, Instagram bishin zu Pokemon Go irgendwo eine API liegen.
Und woher weiß der Experte von Programmierer, wo er danach suchen muss, also nach der API? Packete sniffen?

Und mal so nebenbei gesagt:
Sprich es ist schon leicht blamabel für Niantic so einen Fehler zu machen, oder konnten die dafür auch nichts?

**Comment by djdomrep** [comment]
Ja, jedoch hat z.B. Facebook eine offene API. Packete Sniffen hauptsächlich würd ich meinen.
Was für einen Fehler meinst du?

**Comment by IceQ1337** [comment]
@Fruschel Ich füge dich später hinzu.
@djdomrep Ich denke er meint, die API öffentlich zugänglich zu machen.

Es geht allerdings auch nicht anders, man mann sie zwar etwas verschleiern so wie sie es jetzt machen, aber irgendwoher muss der Spielclient wissen was er tut und da ist dann natürlich die API über RE zugänglich. Das ist also kein Fehler seitens Niantic in dem Sinne.

**Comment by AlpaEZPZ** [comment]
"Ach, und im Bezug auf das Buch:
Danke für die Empfehlung, notfalls komme ich auf das Buch zurück, doch ich finde, dass bei mir die Lernkurve wesentlich höher ist, wenn ich mit einer Person quatsche die Ahnung von ihrem Fach hat, kann ich schlecht beschreiben, finde es aber wesentlich angenehmer. :)"

Wenn ich sowas schon lese... hauptsache nicht selber mal ein Buch oder Tutorial lesen.
Dir ist schon klar das programmierer sich ihr wissen ebenfalls hart erarbeiten mussten.
Fühl dich nicht angegriffen, aber das klingt einfach eher nach faulheit. Mir ist schon klar warum du lieber mit einem Programmierer im TS reden willst, man erhofft sich davon schneller an genau die Informationen zu kommen an denen man selber interessiert ist.
Komisch, wenn es um IT- Fragen geht denken die meisten immer es sei völlig legitim kostenlos um hilfe zu bitten.

**Comment by Fruschel** [comment]
AlpaEZPZ, ich habe weiter unten geschrieben dass ich die Basics etc. alle kann.
Aber ich kenne kein Buch was mir erklärt, wie man auf eine API zugreift, Verbindung zum Server aufbaut und eigentlich den ganzen lustigen Kram.

In den ganzen Büchern wird mir lediglich gezeigt wie ich ein Programm letztendlich schreibe, dass mir automatisch das Netto vom Brutto ausrechnet (oder ich habe mich mit den falschen Büchern beschäftigt). :)

**Comment by d4nlo3008** [comment]
@Ar1i versteht deutsch? Ist sogar vielleicht Deutscher? Das würde einiges hier leichter machen :D

**Comment by Ar1i** [comment]
Ja wieso?

**Comment by d4nlo3008** [comment]
@Ar1i naja ich dachte die ganze Zeit, dass du kein deutsch verstehst oder sogar selbst Deutscher bist ;) dann kann ich zukünftige Anfragen, Hinweise etc. ja auch in deutsch verfassen. Bessere und einfachere Problembeschreibung. Zeit wird gespart.

**Comment by IceQ1337** [comment]
@d4nlo3008 Hättest du mal den High Minded Thread besucht wüsstest du das ;)

**Comment by djdomrep** [comment]
@Fruschel Public API's haben eine Dokumentation. Bei den anderen ist es vom Hersteller nicht erwünscht dass diese verwendet wird. Da es sich hier bereits um hacking handelt liegt da vielleicht der Grund dass es wenig oder keine Bücher darüber gibt.
Hier ein Tutorial um API's rauszufinden per MITM (Man in the middle) https://www.toptal.com/back-end/reverse-engineering-the-private-api-hacking-your-couch

**Comment by NidiKea** [comment]
Da es derzeit so viel zu lesen  gibt und ich englische Fachbegriffe nicht gut kenne was PC angeht mal hier ne Frage. Gibt es derzeit permanente Bans für die User von Bots? Soll sowas kommen? Ist das das Problem? Also dass das irgendwann mal gestoppt wird und umgangen werden muss, war irgendwie klar. Also wird nach einer Lösung gesucht oder wird es keine geben? Ich bin nur jemand, der zufällig aus diesen Bot gestossen ist und sonst kaum was mit sowas zu tun hat. Das ist das, was ich bisher meine verstanden zu haben. Also es ist kein Gemecker nur eine Verständnisfrage. Also sollte der Bot wieder online gehen, ist es dann dennoch immer ne Gefahr, dass man gesperrt wird richtig? Ist ja nicht gewollt.
