### ISSUE TITLE
Bulbasaur Nest?

### ISSUE THREAD

**Issue by iBjorntjuh** [Ar1i/PokemonGo-Bot#1231]
After the Error, Who Knows location of Bulbasaur nest?

**Comment by Fhajad** [comment]
This is for issues on PokemonGo-Bot, not to talk about tips for the game.

**Comment by IceQ1337** [comment]
@Fhajad already said it, but also, nests a migrating so there is no bulbasaur nest anymore.

**Comment by iBjorntjuh** [comment]
I'm so sorry. Don't know that's only for issue's

**Comment by IceQ1337** [comment]
No Problem.

/Closed
