### ISSUE TITLE
ERROR MICROSOFT VISUAL STUDIO

### ISSUE THREAD

**Issue by viplavip15** [Ar1i/PokemonGo-Bot#1232]
A project with an Output Type of Class Library cannot be started directly.
In order to debug this project, add an executable project tho this solution wihch references the library project. Set the executable project as the startup project.

**Comment by IceQ1337** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
English Tutorial: https://www.youtube.com/watch?v=mW5KsA75lt8

Remember the bot does not work at the moment.

**Comment by churchill12** [comment]
Right mouse click on PokemonGo.RocketAPI.Console and then set as startup project.
Then build it and it will work.

**Comment by IceQ1337** [comment]
@churchill12 It won't, because the bot is not working at the moment :P

**Comment by xJustx** [comment]
^

**Comment by viplavip15** [comment]
TKS ALL. WORKING BUT NOT FOUND POKE STOP :(

**Comment by IceQ1337** [comment]
#1202

**Comment by xJustx** [comment]
^

**Comment by xJustx** [comment]
^
