### ISSUE TITLE
The bot can not find Pokestops in "x" radius 

### ISSUE THREAD

**Issue by MVDNESS** [Ar1i/PokemonGo-Bot#1237]
Is the bot not working anymore?
Cause my bot can't find any pokestops and so he can't catch pokemons.

**Comment by IceQ1337** [comment]
#1202

**Comment by MVDNESS** [comment]
thanks

**Comment by rlmrso** [comment]
Niantic has now began to obfuscate the API answers. This means that we will need to update the POGOProtos and implement the new hash b1f2bf509a025b7cd76e1c484e2a24411c50f0612. 

Reverse Engineering an App with SSL Pinning is hard to do, thanks to git user rastapasta & cstrachan88 we able to bypass these security measures.

Niantic took a big step to block Bots. But we are sure this is bypassable. 

Sorry for the inconvienience.

**Comment by bigdog3626** [comment]
#1235

**Comment by xJustx** [comment]
^
