### ISSUE TITLE
pokemon go bloquer 

### ISSUE THREAD

**Issue by lucky59300** [Ar1i/PokemonGo-Bot#1238]
bloquer ici ![capture](https://cloud.githubusercontent.com/assets/20828137/17387251/2f483ea2-59f2-11e6-888f-35267d3bb847.PNG)

**Comment by HaydarOzturk** [comment]
Read this ( #1202 ) one and close up your issue...

**Comment by IceQ1337** [comment]
Change coordinates.
And then...  #1202
