### ISSUE TITLE
"We can't find any PokeStops in a range of 5000m!"

### ISSUE THREAD

**Issue by kayoriceball** [Ar1i/PokemonGo-Bot#1239]
Started doing this today, I know for a fact this place has hundreds of stops.

**Comment by idkwateva** [comment]
you must be BANNED!!! Go create new account

https://github.com/Ar1i/PokemonGo-Bot/issues/1202

**Comment by GunplayVII** [comment]
Not banned if you read previous comments (issues) Ar1i is working on it it happens

**Comment by rlmrso** [comment]
Niantic has now began to obfuscate the API answers. This means that we will need to update the POGOProtos and implement the new hash b1f2bf509a025b7cd76e1c484e2a24411c50f0612. 

Reverse Engineering an App with SSL Pinning is hard to do, thanks to git user rastapasta & cstrachan88 we able to bypass these security measures.

Niantic took a big step to block Bots. But we are sure this is bypassable. 

Sorry for the inconvienience.

**Comment by bigdog3626** [comment]
look at #1235

**Comment by ElectricTaco** [comment]
How about ya'll OPs read other posts? wtf.... It's been like this for hours. Ar1i is graciously working on it. CTFO.

**Comment by xJustx** [comment]
^ #1202

**Comment by KazWave** [comment]
Thanks rlmrso 

Write comment when it's update please :)

**Comment by farisyusry** [comment]
how to update the hash key? is it i can update my own? or just wait for new release?
