### ISSUE TITLE
Pokefast ( COPY!) 

### ISSUE THREAD

**Issue by max783** [Ar1i/PokemonGo-Bot#1240]
New copy called POKEFAST. just saying. Have a nice day

**Comment by Tochez** [comment]
@max783 thanks you

**Comment by xJustx** [comment]
domain?

**Comment by arjunvegda** [comment]
@xJustx Was unable to find domain... But found this post https://iosgods.com/topic/32928-pokemon-go-bot-pokefast-v1-v2/

**Comment by max783** [comment]
Exactly. found the post too.

**Comment by xJustx** [comment]
I will forward this to Ar1i, thank you.
