### ISSUE TITLE
This problem happened after release update 0.31.0 Pokemon GO.

### ISSUE THREAD

**Issue by Utopik** [Ar1i/PokemonGo-Bot#1242]
Problem on picture. Everybody have this problem.

![adszziz](https://cloud.githubusercontent.com/assets/20828530/17388280/e49fbf6c-5a03-11e6-89f1-83877ca35f74.jpg)

**Comment by ijuchia** [comment]
i have some problem

**Comment by motemo77** [comment]
#1202

**Comment by dodogtg** [comment]
cannot found any pokestop.

**Comment by jorgewilliams** [comment]
Cannot fouund any pokestop  D:

**Comment by dodogtg** [comment]
may be related updates from pokemon go on iTunes store
