### ISSUE TITLE
Ban Hammer

### ISSUE THREAD

**Issue by cicklow** [Ar1i/PokemonGo-Bot#1243]
Niantic has begun to ban many of the users who have a high rate of pokestops obtained..
https://pokeadvisor.com/ -> Community -> PokeStops

All banned!
![1](https://cloud.githubusercontent.com/assets/933689/17388848/3e3ffbec-59d5-11e6-8084-9dc9d18a0609.png)

The bot has to be handled differently, do not go getting all pokestops there, but go collecting pokemon and when you need it objects open pokestops

**Comment by IceQ1337** [comment]
Is Pokeadvisor.com associated with Niantic? If not there is no problem and these users just got tagged as cheater on this website. I dont know for sure, but since you have to login to get your account entered to the list i think its not related to it.

**Comment by dodogtg** [comment]
No team and have level 32...wowwww!

**Comment by idkwateva** [comment]
that no team probably just catch pokemon and never entered gym

**Comment by Hahahaha0** [comment]
wow in 3 days or less they got level 30+

**Comment by Nomad52** [comment]
First of all, this website does not track all players, only the ones that decide to sign up on this website, and it also has nothing to do with Niantic. Second these guys aren't getting banned, I don't see where or how you're even getting that. They're being labeled as a cheater on this website.

**Comment by Ar4isteR** [comment]
Like im lvv 29 in 3 days still not banned tho

**Comment by Jam1ePistol** [comment]
Is there any way to see pokemon levels outside of the bot ?

**Comment by Tochez** [comment]
That is a 3rd party thing. It doesn't associate with Niantic guys. They arent banned. There just suspicious.

**Comment by immoempe** [comment]
https://www.reddit.com/r/PokeAdvisor/comments/4vj3jx/what_is_pokeadvisor/

PokeAdvisor has nothing related with Niantic, stop spreading hoaxes please... (Or maybe this post is only a joke?)

**Comment by Midnlght** [comment]
I suggest if you logged your info on that you delete it, even though 3rd party websites have nothing to do with the game

**Comment by pokerave** [comment]
Well actually the pokeadvisior is getting their data from Pokemon Go server which is niantech, meaning if they are detected cheater in their stats there niantech already knows they cheat. HOW EVER, we have a few people here that check those site (including me), **My self is not detected as a cheater, but there are some here that are detected as a cheater but can still play.**

**Comment by Biscuit090** [comment]
Yeah I think once you login to pokeadvisor and continue to use the bot afterwards, it detects cheating on the account. Unless of course, you delete your credentials from their database. (My account is still clean but I haven't used the bot since logging in so this theory has yet to be really tested..)

**Comment by audota000** [comment]
how could they get lvl30+ within 3 days? im using bot it is like about 20000exp/h, but this is not even near their speed....

**Comment by Biscuit090** [comment]
That rate of leveling seems about right, I left the bot on for at least 3 days straight and I reached level 28.

**Comment by Ar1i** [comment]
This has nothing to do with Niantic.
