### ISSUE TITLE
Error in app

### ISSUE THREAD

**Issue by scottyv3** [Ar1i/PokemonGo-Bot#1244]
So ive been using this for the last few days, and worked perfectly fine. now there isnt anything wrong with the bot, but whjen i enter pokemon go on my phone, it wont let me catch pokemon, spin pokestops, or do gyms. ive tried on multiple phones but still no result. seems to be a profile thing. any way to fix?

**Comment by Asdrubalgp** [comment]
just wait until tomorrow without using the bot

**Comment by IceQ1337** [comment]
Probably Soft-Banned

**Comment by dodogtg** [comment]
Banned detect. :dancer:

**Comment by xJustx** [comment]
^
