### ISSUE TITLE
Cant find anythings Please help

### ISSUE THREAD

**Issue by kit9377** [Ar1i/PokemonGo-Bot#1246]
![default](https://cloud.githubusercontent.com/assets/20830526/17390392/45180076-5a3f-11e6-91c5-12f2a9ce1100.png)

**Comment by jamc02** [comment]
dude, were all having that problem. Let arli fix it just be patient...

**Comment by kit9377** [comment]
Before this have the sentence (Youre outside of the defined Max Walking Radius.Walking back)

**Comment by dodogtg** [comment]
#1202 <- chill dude an keep donate :dancer:

**Comment by jamc02** [comment]
just be patient, ARLI WILL FIX THE PROBLE BY TOMORROW>>>>>>

**Comment by Midnlght** [comment]
Does no one take the time to read whats going on lol
