### ISSUE TITLE
Lure attraction, and question

### ISSUE THREAD

**Issue by Slickkiller** [Ar1i/PokemonGo-Bot#1249]
I was wondering if the bot was working and does it pick up lures/ pokemon at lures while running? Is new build updated? Thank you for all your hard work, a real time saver.

**Comment by Tochez** [comment]
@Slickkiller  Currently the bot is still down. But for your first question. Yes, it picks up pokemon at lures.

**Comment by gummyruler** [comment]
Works for both.

**Comment by xJustx** [comment]
^
