### ISSUE TITLE
we cant find any pokestops in a range of.....

### ISSUE THREAD

**Issue by Allyck** [Ar1i/PokemonGo-Bot#1250]
please,what happen?
![adsfghj](https://cloud.githubusercontent.com/assets/20831881/17391624/330746f2-5a4a-11e6-99a8-fd57c2e9f0b8.png)

**Comment by peoplearmy** [comment]
please read through the other issues before posting a new one.  THis issue has been identified and is being worked on.

[#1202](https://github.com/Ar1i/PokemonGo-Bot/issues/1202)

**Comment by xJustx** [comment]
^
