### ISSUE TITLE
ERROR: NO POKESTOPS in the range!!

### ISSUE THREAD

**Issue by Tanish2409** [Ar1i/PokemonGo-Bot#1251]
Suddenly i am getting an error that there are no pokestops in the range however big it is. And also it doesnt detect any nearby pokemons. Its been 12hoours and I am constantly getting this error.

![untitled](https://cloud.githubusercontent.com/assets/20831818/17391727/12b06b5e-5a36-11e6-9fad-d98c0677420d.png)

**Comment by peoplearmy** [comment]
Please read through other posted issues before creating a new one.

[https://github.com/Ar1i/PokemonGo-Bot/issues/1202](url)

**Comment by motemo77** [comment]
“Never underestimate the power of stupid people in large groups.”

**Comment by xJustx** [comment]
^
