### ISSUE TITLE
Whats The Deal With It Now Works Fine Until Today...

### ISSUE THREAD

**Issue by gatekeeper1122** [Ar1i/PokemonGo-Bot#1252]
Whats the deal with this it started doing this today now worked fine for last 6 days until now ive tried over 6 accounts even 1 new one same issue
![kmnjhgf](https://cloud.githubusercontent.com/assets/16184353/17391612/cc7b29dc-59d4-11e6-9cb1-8cc1ba4edc9a.png)

**Comment by Pseudoxanthoma** [comment]
Same here.

**Comment by Allyck** [comment]
yes me too...

**Comment by Tanish2409** [comment]
looks lyk everyone facing the same issue!!

**Comment by handyipit** [comment]
me too :(

**Comment by Biscuit090** [comment]
#1202

**Comment by Biscuit090** [comment]
Please read it. PLEASE

**Comment by TNLzItalic** [comment]
Same here.

**Comment by Allyck** [comment]
yeah,where dev.
please fast fix them... :(

**Comment by motemo77** [comment]
he fix it at his own time... don't rush him... he do it for free... he doesn't deserve being rushed like this... be patience, people!

**Comment by pokerave** [comment]
as biscuit said read #1202
and its FREE so dont complain or make your own. :facepunch:

**Comment by xJustx** [comment]
^ #1202
