### ISSUE TITLE
"We cant find any pokestops in a range of 5000m"

### ISSUE THREAD

**Issue by TNLzItalic** [Ar1i/PokemonGo-Bot#1253]
This new update has caused this for me and im only sending the bot to the city which has tons of stops :( how do i fix this issue?

**Comment by SneaxRight** [comment]
same problem

**Comment by Biscuit090** [comment]
#1202

**Comment by peoplearmy** [comment]
Please read through other posted issues before creating a new one:

[https://github.com/Ar1i/PokemonGo-Bot/issues/1202]#1202

**Comment by Biscuit090** [comment]
This issue has been addressed already multiple times click here: #1202

**Comment by xJustx** [comment]
^
