### ISSUE TITLE
IV Gui

### ISSUE THREAD

**Issue by fredylie** [Ar1i/PokemonGo-Bot#1254]
Can i ask to separate the iv gui with the catch and get pokestop bot.

**Comment by pokerave** [comment]
i think their priority as of the moment is to get the bot up and running. :laughing:

**Comment by mchterence** [comment]
That ture!

**Comment by Xelwon** [comment]
I have a question for this ask.
IV values given for the bot are the real values in game or are calculated by the cp, hp and dust (Like doing all IV calculators)

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
