### ISSUE TITLE
Use at your own risk (must read!!)

### ISSUE THREAD

**Issue by lucasxvieira** [Ar1i/PokemonGo-Bot#1257]
Niantic is banning people permanent now, so use hacks at your own risk..

https://www.youtube.com/watch?v=ZlNg4s-KcVA

it can be fake, but it can also be real. There is always a risk..

**Comment by immoempe** [comment]
Seems fake...

**Comment by madeinyashiro** [comment]
Look so fake, it's awesome how people can believe this ...

**Comment by Exkonvict** [comment]
Fake Period.

**Comment by pokerave** [comment]
thats the guy from london that photoshoped that

**Comment by Biscuit090** [comment]
Yup absolutely fake. You know why? Because how does it make sense that only ONE person got permanently banned? Shouldn't there have been a huge WAVE of bans instead? If there really was a wave of bans, it would have spread much quicker than this fake story has.

**Comment by shahroozal** [comment]
It's definitely fake
