### ISSUE TITLE
Option to not spin pokestop?

### ISSUE THREAD

**Issue by Aiwoma** [Ar1i/PokemonGo-Bot#1259]
Hi Guys understand that currently the bot is down and many thx to the devs working to fix it.

I have been using the bot for a couple of days with great results, was wondering if there is an option to only catch pokemon and not spin the pokestops?

**Comment by dodogtg** [comment]
good idea...

**Comment by Aiwoma** [comment]
the inventory fills up over 100 pokeballs in minutes

**Comment by andihirawan** [comment]
@Aiwoma actually better using if, spin pokestops if the ball become 0.

**Comment by Aiwoma** [comment]
@andihirawan yea man only spin pokestop if pokeball becomes 0. that was the account dont have obvious bot record with 20 thousand pokestop visited.

**Comment by tr1via1** [comment]
If you want this feature for the main purpose of your **inventory filling up with normal pokeballs**, then just simply set a "limit" to your "Items" configuration:
Example:
Max Pokeballs = 20

Therefore, if you already have 20 Normal Pokeballs - the bot will automatically "Recycle" any extra's you collect.

This can be done for all items that Ar1i (owner) has made available on GUI.

**Comment by Aiwoma** [comment]
@tr1via1 yo thx for your tip. But I was hoping to turn off the spin pokestop so that my account doesn't register with unrealistic amount of pokestop visited.

**Comment by tr1via1** [comment]
@Aiwoma In that case, I think it would be a cool feature to have. 
I have not seen the source, but I suppose something as simple as this can be added:

item_x = 0       //  user can set this value
spin_pokestop = false   // default
if (item_x = y) spin_pokestop = true

My area has a lot of pokestops, so I just set my bot speed to 5kph (realistic walking speed). This makes the amount of pokestop spins I accumulate to have a more realistic value.

**Comment by thepeople03** [comment]
has the bot been updated yet?
