### ISSUE TITLE
Howmany Items to cap

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#126]
I don't really get the point in capping how many items you should have, I do cap either way, but Is there any reason to actually cap what items to collect and what to recycle, or am i wasting all my shiz.

**Comment by XxAirWalker26xX** [comment]
better to cap off lower tier items like normal potions and pokeballs and keep higher tier items like max potions and revives so that when u play u can use them.

**Comment by plowzey** [comment]
But there's no point or does your inventory max out - I haven't actually loaded the game on my phone, i'm just farming accounts.

**Comment by XxAirWalker26xX** [comment]
Yes theres a cap of 250 at the start without any upgrades

**Comment by plowzey** [comment]
Ohh rightt ok thanks man.
