### ISSUE TITLE
No poke-stops in range & Error reloading Pokemon list: Out of memory

### ISSUE THREAD

**Issue by rongsteven** [Ar1i/PokemonGo-Bot#1260]
I've also set my coordinates to Hyde Park, Sydney.
I'm on the latest version: 17.10
![capture](https://cloud.githubusercontent.com/assets/20813780/17393095/c081a2a6-5a64-11e6-9aa4-811cc65224a4.PNG)

**Comment by shahroozal** [comment]
Yes everyone has that problem

**Comment by 0x92** [comment]
Be patient and wait nobody can use the bot at the moment

**Comment by Biscuit090** [comment]
#1202 Omg please read this before posting the same issue that everyone else has been posting for the past 24 hours straight. pleeeaseeee

**Comment by rongsteven** [comment]
my bad, guess im actually gonna have to play pokemon go

**Comment by 0x92** [comment]
@rongsteven get nox player

**Comment by dodogtg** [comment]
ZZZZZZZZZZZzzzzzzzzzzzzzzzz...............

**Comment by WhoBotWhoBad** [comment]
@Biscuit090 I feel you bro. I think their kids and lazy to read lol

**Comment by bautschi44** [comment]
come a update?

**Comment by Biscuit090** [comment]
Just come back later when the devs and the owner are back online. Right now, they're probably still resting. Patience cannot be stressed enough dude.

**Comment by bautschi44** [comment]
Time is Money,and i dont have Money xDD

**Comment by 0x92** [comment]
@bautschi44 Just chill

**Comment by bautschi44** [comment]
yes sorry

**Comment by xJustx** [comment]
^ #1202
