### ISSUE TITLE
Just A Quick Question.

### ISSUE THREAD

**Issue by Bender57** [Ar1i/PokemonGo-Bot#1261]
I read through a lot of the issues and I couldn't find a similar question to what I want to ask, so I made this. Whenever I try to catch a Pokemon without the Bot, after one or two shakes, it just runs away. Apparently, I've been told that if I wait a while without using the Bot or logging into my Account, I should be able to catch Pokemon. Is this true? I just want to be sure, as I've only been using the Bot for two days.

**Comment by 0x92** [comment]
Youre softbanned

**Comment by xJustx** [comment]
^

**Comment by DemonBytes** [comment]
Yup. Go to a pokestop. Enter it, flip, leave. Repeat that 40 times and youre unbanned

**Comment by Bender57** [comment]
Jesus Christ, everyone answers fast. Well, thank you, I'll try that.
