### ISSUE TITLE
I dont know how to update :/

### ISSUE THREAD

**Issue by mrsnowsn** [Ar1i/PokemonGo-Bot#1262]
I dont understand how do you update to the latest version? I copy every file from the new stuff to my bot map. But the bot still says. *Do you want to update to our new version?* Can someone help me? :)

**Comment by keustii** [comment]
into folder "Builds Only", u hav to unzip le zip  "Latest Build - 03.08 17.10.zip",
but the bot dont work ATM

**Comment by DemonBytes** [comment]
Extract the rar file in builds only folder and start the console.exe

**Comment by mrsnowsn** [comment]
I thought i did that yesterday but i tried now again and it worked, Thank you so much boys. :dart:
