### ISSUE TITLE
 Bot does not work?

### ISSUE THREAD

**Issue by DALTON64** [Ar1i/PokemonGo-Bot#1266]
**** 
we cant find any PokeStops in a range of 5000m!
We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying...
****

about 12 hours, I get the same error .

Does anyone have information?

**Comment by Biscuit090** [comment]
#1202

**Comment by PloxFire** [comment]
PokemonGo updated their API recently, this is happening for everyone atm and the bot creators are working on it as we speak :P

**Comment by brunomassa** [comment]
we need to wait for fix :P
