### ISSUE TITLE
* ETA * Update

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#1267]
So, currently i looked more into it. I already know which thing i need to update, but the problem is getting the data which should be in. Trying that today, i hope i get it working today. Thanks for your awesome support guys!

**Comment by OGcpalm** [comment]
thank you for your awesome work

**Comment by yashmhatre** [comment]
thank you for your awesome work @Ar1i

**Comment by Tonyjaain** [comment]
You can do it ;D

**Comment by Biscuit090** [comment]
Awesome! Thanks so much for this amazing work.

**Comment by bunnymuny** [comment]
we really appreciate your work ar1i, take your time mate.

**Comment by casanovas** [comment]
take ur time mate!! we'll be waiting for ur update on the bot!! btw thankyou for ur hardwork!!

**Comment by GundBear** [comment]
Love your work, you are awesome!!

**Comment by 0x92** [comment]
![1449699321690](https://cloud.githubusercontent.com/assets/6593435/17396034/a290da38-5a31-11e6-818b-578bb06d9ffe.jpg)

@Ar1i  You while reading the open issues =D

**Comment by JWPapi** [comment]
maybe this helps you:

**Comment by JWPapi** [comment]
https://docs.google.com/document/d/1gVySwQySdwpT96GzFT9Tq0icDiLuyW1WcOcEjVfsUu4/preview

**Comment by L3v1X** [comment]
Lass dir Zeit Ar1i ! :D und viel Glück :) <3

**Comment by Ar1i** [comment]
@JWPapi already saw, but thanks

**Comment by wreckoning** [comment]
@Ar1i 

Keep up the awesome work man! Take your time.. Just want to let you know that your work is greatly appreciated :)

**Comment by bunnymuny** [comment]
well guys to help Ar1i we could make a small donation to show him a bit of support, what d you think?

**Comment by zzzz9999** [comment]
@Ar1i you're the BOSS!
Thanks

**Comment by akrw1000** [comment]
Thanks @Ar1i  you're the MAN!

**Comment by dodogtg** [comment]
donate

**Comment by Ar1i** [comment]
#1274 closing this here

**Comment by sylva91** [comment]
thank you very much :+1:

**Comment by codman96** [comment]
keep up the good work @Ar1i

**Comment by Filip1232334** [comment]
thank you for your awesome work @Ar1i

**Comment by NevilleNg** [comment]
Awesome! Thanks so much for this amazing work... take your time

**Comment by fnodnarb** [comment]
http://pastebin.com/upXpS6D9

http://www.i4u.com/2016/08/114046/niantic-breaks-pokemon-go-apis-and-all-bots-and-trackers-based-apis
 
Will this help at all? Someone has already cracked the code but won't share it because of a cease and desist letter.

**Comment by KamoiChikubi** [comment]
Nice work dude. Good luck with fixing this issue <3
