### ISSUE TITLE
Option to transfer Pokemon within/under a certain CP value?

### ISSUE THREAD

**Issue by burnSMACKER** [Ar1i/PokemonGo-Bot#1269]
Sometimes my Pokemon Inventory gets full and the bot does not properly transfer the duplicates, so I am suggesting that an option be added where any Pokemon under or within a set of CP values be automatically transferred; and because Magikarp can be quite valuable but have a CP in the one hundreds, I suggest also adding an option to exclude chosen Pokemon from being automatically transferred unless it is below a set value.

**Comment by Biscuit090** [comment]
..... r u srs?

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
