### ISSUE TITLE
Wird man jetzt gebannt?

### ISSUE THREAD

**Issue by L3v1X** [Ar1i/PokemonGo-Bot#1273]
Wird man jetzt durch benutzen des Bots gebannt ? will meinen Spielstand net verlieren :C

**Comment by Sander523i** [comment]
in English plz

**Comment by Sintonic** [comment]
Nein chill. Wenn doch kannst das jetzt eh nicht mehr ändern.

**Comment by xJustx** [comment]
nope

**Comment by L3v1X** [comment]
Jup

**Comment by L3v1X** [comment]
wäre halt trotzdem doof ...
