### ISSUE TITLE
Offering Dev-Support

### ISSUE THREAD

**Issue by yvesniessen** [Ar1i/PokemonGo-Bot#1277]
Hey,

würde euch gerne meinen Dev-Support anbieten.
Bin professioneller C# .NET Entwickler, wir entwickeln täglich API Anwendungen.

Wäre super wenn Ihr mir eine Möglichkeit gebt euch zu kontaktieren.

Danke und Gruß.

**Comment by 0x92** [comment]
Schick Ar1i einfach ne Nachricht in Skype oario1998

**Comment by Ar1i** [comment]
^
