### ISSUE TITLE
Help for poke go bot 

### ISSUE THREAD

**Issue by luc113035** [Ar1i/PokemonGo-Bot#1278]
hi i dont know how but i cant use my pokemon bot  he says not pokestops founding so i dont know how to fix and if it gets a update how i can use it cuz i am just using the lastest build and all other stuff i delet cuz i dont know waht i can do wiht that all conigs i wish i can get help ty

**Comment by xJustx** [comment]
#1202

**Comment by iBjorntjuh** [comment]
Can Ppl read?

**Comment by LvGPoke** [comment]
No
