### ISSUE TITLE
notification via telegram when you catch a pokemon with more than X cp

### ISSUE THREAD

**Issue by phipsy** [Ar1i/PokemonGo-Bot#128]
we already have the /information toggle that is imo useless. maybe you can add something there to notify me when i catch something above a specific cp. like for example the cp threshold for not sending it away.

**Comment by XxAirWalker26xX** [comment]
How do u get the telegram bot to work all i get is I dont hear at you!

**Comment by Ar1i** [comment]
You need to Enter your Nickname @XxAirWalker26xX then he anwsers you

**Comment by phipsy** [comment]
there is a video in the original thread in that forum. i don't speak german but i tried to do the same as the guy in that video and it worked.

**Comment by XxAirWalker26xX** [comment]
I tried putting in my Name in for the telegram thing but still the same thing?

**Comment by djdomrep** [comment]
you need to have a username in telegram and add that username in the bot config

**Comment by XxAirWalker26xX** [comment]
Sorry im an idiot, my telegram account when i made it didnt ask me to put a username so i manually did it thank u tho btw that would be a great idea adding in more functionality with telegram
