### ISSUE TITLE
when get the pokemon go bot fixxed

### ISSUE THREAD

**Issue by luc113035** [Ar1i/PokemonGo-Bot#1280]
and can u maybe make that the bot catchs firs t the rare pokemongs liek snorlaxo then others ?

**Comment by TheSmartly** [comment]
Why would you need that? If the bot found those, it will try to catch them anyways. No matter in what order. I do not see the sense of that :D

**Comment by AlpaEZPZ** [comment]
i do not see the the sense of this thread...

**Comment by xJustx** [comment]
We hope the bot get fixxed soon!
And this is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by luc113035** [comment]
it would be cool if the bot farms just faster like ra1ndr0pz bot he farmed 200k xp in one hour thats a bot but i think the bot becomes then more dangers for perma ban
