### ISSUE TITLE
[Kopierschutz] z.B. Pokekrot

### ISSUE THREAD

**Issue by TMaddox** [Ar1i/PokemonGo-Bot#1281]
Es is zwar gegen alles was man beim Programmieren eigentlich so lernt, aber der Vietnamese der den Bot immer kopiert kann bestimmt nicht Deutsch.

Vielleicht könnte man darüber nachdenken ob man einfach alles (Variablen, Kommentare, Methoden,..) auf Deutsch schreibt, so wie ich das mitbekommen hab sind ohnehin die meisten Contibutors aus Deutschland. (Das Forum Highminded auch)

Ich denke wenn man das gleichzeitig mit einer Codeumstrukturierung durchführt, würde das das ständige kopieren unterbinden.

@Ar1i

**Comment by xJustx** [comment]
Wird nichts bringen - der wird schon weiter kopieren.

**Comment by Ar1i** [comment]
Das bringt viel zu viel verwirrung..
