### ISSUE TITLE
Unterschied IV und CP

### ISSUE THREAD

**Issue by jk6046** [Ar1i/PokemonGo-Bot#1284]
Ich weiß, dass das nicht hierhin gehört, aber was genau ist IV und was bedeutet CP?

**Comment by 0x92** [comment]
IV ist quasi die Anzeige des Potenzials der Stats 100%  im späteren Verlauf. CP die aktuelle" Level" Anzeige -

**Comment by AlpaEZPZ** [comment]
Wenn du in der Lage bist google zu benutzen sollte dir relativ schnell klar sein wie die werte zueinander stehen.
