### ISSUE TITLE
Nox und so...

### ISSUE THREAD

**Issue by L3v1X** [Ar1i/PokemonGo-Bot#1286]
Solange der Bot nicht Funktioniert wollte ich mit einem android emulator pokemon go spielen. Da wäre Nox doch es geht nicht weil Pokemon go auf der android version nicht verfügbar ist ( seit dem neusten update ). Gibt es eine neue Nox version oder einen anderen emulator der es unterstützt ?
Lg Levi

**Comment by bunnymuny** [comment]
they are working to solve the issue #1274

**Comment by motemo77** [comment]
http://en.bignox.com/pokemongo 
is this what are you looking for, mate?

**Comment by AlpaEZPZ** [comment]
Ganz einfach, ich hatte genau das selbe problem,
Ich hab mir auf Chip einfach die aktuelle "pokemon go apk" runtergeladen und diese dann einfach über nox gestartet.

Über die nox seite würde ich die apk nicht runterladen, der durchsatz ist einfach viel zu gering.

MfG Alpa

**Comment by L3v1X** [comment]
Ahh danke ! :D
