### ISSUE TITLE
- READ THIS Before ASKING why BOT NOT WORKING -

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1291]
.. I BET you are reading this now to find out why the bot is not working

READ THIS #1274

**Comment by lejoueuronline** [comment]
What happens exactly the bot does not work? thank you

**Comment by pokerave** [comment]
Niantech updated the API used to read the Objects on the map. like the pokemon and the pokestop and the gyms. now the DEV of the bots need to reverse engineer the APP to get the API to work.

**Comment by lejoueuronline** [comment]
ah okay, do you think the Bot will be updated soon? Thanks

**Comment by HaydarOzturk** [comment]
Best thread ever :D

**Comment by kurban85** [comment]
what is the problem and what to do?
![nvnbgocd13o](https://cloud.githubusercontent.com/assets/20836549/17398910/ef1e47d0-5a47-11e6-992a-7fd26e330b0f.jpg)

**Comment by Shikkaku** [comment]
^ did you even read the first post?

**Comment by Correexx** [comment]
@kurban85 this walked out radius is from the Last Record textfile in your dictonary but the bot had also issues cause of the new API :)

**Comment by kurban85** [comment]
and what to do?

**Comment by AlpaEZPZ** [comment]
format C:

**Comment by 0x92** [comment]
do not shitpost in github go to 4chan

**Comment by Correexx** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/ ---> then open english or german spoiler to fix any issues without not founding pokestops thats an issue but he is fixing it :)

**Comment by ozncglyn** [comment]
@Ar1i hatte schon geschrieben, weiß nur nicht ob es an kam!

Ich bin aus Deutschland und bin auch Entwickler.
C# und VB.Net.

Falls du Hilfe benötigst, sag Bescheid

**Comment by lailaps** [comment]
**Ar1i** has to wait just like everyone else, until some genius will release a workaround on Reddit.
After that he can implement it into his bot!

So just be patience guys!

Once they found a fix everyone with a bit skill in C# can implement it into his Pokemon GO bot!

**Comment by KazWave** [comment]
Thanks

**Comment by Bosskiller1711** [comment]
wann geht der bot wieder ? When will work the bot again ? wie lange brauchen die ca. ?

**Comment by lailaps** [comment]
lol

**Comment by lailaps** [comment]
Follow on Reddit!

https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

04/08/2016 - 02:07 GMT+1 : It's becoming more evident that this is a non-trivial change, and will take much longer than planned to get reverse engineered again.

**Comment by pokerave** [comment]
READ This Please #1306
