### ISSUE TITLE
j'ai un bug sur le bot (we cant find any pokestops in a range of 5000m)

### ISSUE THREAD

**Issue by Xeroxs** [Ar1i/PokemonGo-Bot#1292]
bonjour comme je l'ai dis j'ai un bug sur bot quand je l'ouvre.
Et c'est pas la peine de me dire si j'ai supprimer le dossier lastcoords et que j'ai changer de localisation, je l'ai fait 100 fois est sa marche toujours pas.
voila une photo.
![image](https://cloud.githubusercontent.com/assets/20836902/17399413/33b4e9ea-5a42-11e6-9fe9-f170a97a66c1.png)
Aider moi STP

**Comment by AlpaEZPZ** [comment]
learn to read...

**Comment by motemo77** [comment]
gardez le calme et manger votre baguette

**Comment by xJustx** [comment]
#1274

**Comment by Waiiim** [comment]
Normal, niantic a fait une mise à jour pour bloquer les bot, donc le fondateur essaye de contourner et d'enculer Niantic =)

**Comment by Lentsha** [comment]
C'est à peu près la 142ème fois que ce problème fait l'objet d'un sujet dans ce forum depuis hier soir. Avant de poster, il faut lire les autres sujets. Les doublons ne servent à rien!

Pour ta réponse, il va te falloir attendre une mise à jour du bot pour contourner une mesure prise par Niantic hier soir contre les bots. Le développeur principal a estimé une mise à jour dans la journée, ou demain. Patience!

**Comment by lejoueuronline** [comment]
J'espère qu'il arriverait à bypass les mesures prises part Niantic 🤔😌
