### ISSUE TITLE
Error reloading pokemon list: badauthentication

### ISSUE THREAD

**Issue by BloodHearts** [Ar1i/PokemonGo-Bot#1293]
Hey I am trying to use the bot for the first time but I am getting an error ( check the attached screenshot)
Does anyone know how to fix this error?
![error](https://cloud.githubusercontent.com/assets/20837874/17399906/386b8536-5a45-11e6-964e-395aa91515e2.png)

**Comment by amuessig** [comment]
Username and/or password are wrong?

**Comment by Shikkaku** [comment]
#1274 pls read before post///

**Comment by LvGPoke** [comment]
It has nothing to do with the post... His password and email are wrong... had the same problem

**Comment by Shikkaku** [comment]
but still the bot isnt working

**Comment by LvGPoke** [comment]
True... but still not his problem atm.

**Comment by Shikkaku** [comment]
well, even if his pw and email are right he cant use it

**Comment by Riot0815** [comment]
Shikkaku. But nontheless your comment do and did not help, but probably will help sometimes :)

**Comment by Correexx** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/ ---> open spoiler english or German to fix it if this doesint work i dont know :)

**Comment by Correexx** [comment]
maybe u checked in with google but use a PTC Acount? or u picked your username for the google acc?

**Comment by RavenZero** [comment]
Possible problems which cause it:
- you use google, but you registered with ptc
- your login data is wrong
- you never normaly logged into your account, so there is no charakter name, gender etc choosen (not sure what the bot does when that happens)

**Comment by Correexx** [comment]
@RavenZero if theres no character he wouldnt say BadAuthentification cause he cant read any "Account datas"

**Comment by BloodHearts** [comment]
Guys it was indeed a simple wrong password
Sometimes errors are the simplest problems lol
Right now the bot transfered all pokemons but it isn't catching any, how do I fix this problem? ( see attached screenshot again :P)
![probleem](https://cloud.githubusercontent.com/assets/20837874/17400330/80e10078-5a47-11e6-9f91-b3b81cffde45.png)

**Comment by Correexx** [comment]
First read one of the first comments was: "#1274 pls read before post..." or "but still the bot isnt working" Niantic changed his API so the Bot doesnt work until they patch it so just wait as we do :)

**Comment by BloodHearts** [comment]
ah I see I will just wait then I thought only the pokestopts didn't work but I get it now thanks for all the quick support

**Comment by Correexx** [comment]
No problem hope u enjoi this nice bot :D "i didnt used it befor too xD" -- i thought hey download it and test it but it doesnt worked xD"

**Comment by Timmiller109** [comment]
BTW, @Correexx for PTC you use your trainer club user name. Not your in game character name.

**Comment by Correexx** [comment]
@Timmiller109 Yeah thx u updatet my comment :)

**Comment by czokalapik** [comment]
@RavenZero if he never logged in normally, bot will run using prefix of user e-mail, but after logging in to the game for the first time after bot ran on it there will be tutorial, option to change character mail, gender, looks, and even starter pokemon (which, after being caught will have CP raised to player's level even if it says only 10 CP when catching it).
