### ISSUE TITLE
No Pokestop

### ISSUE THREAD

**Issue by DiTechRacer** [Ar1i/PokemonGo-Bot#1295]
Since 12 hours I get the message that no Pokestops near are. But there are many..
Where is the problem? Same Problem with two bots..

![unbenannt](https://cloud.githubusercontent.com/assets/14916371/17400332/83660348-5a47-11e6-9f4b-c0da187fe678.png)

**Comment by xJustx** [comment]
#1274

**Comment by DiTechRacer** [comment]
Thx!
