### ISSUE TITLE
Cant load pokestops

### ISSUE THREAD

**Issue by P0tat0killer** [Ar1i/PokemonGo-Bot#1296]
![b619fd80fd664d769e0e2a4e0e87bb89](https://cloud.githubusercontent.com/assets/9396465/17400442/3266b22a-5a48-11e6-97f5-5db56c7196c2.png)

**Comment by bunnymuny** [comment]
please read #1274 thx

**Comment by xJustx** [comment]
^

**Comment by Correexx** [comment]
OMG guys do u rly think u are the only one if all worked good? maybe i mean maybe read any other threads with name like "First Read then ask Bot not working" or "Bot doesnt Work" or anything like that guys rly pls

**Comment by valver** [comment]
hello feel the same, what would be the solution

**Comment by xJustx** [comment]
#1274

**Comment by valver** [comment]
I been using all week and yesterday I get that

**Comment by xJustx** [comment]
Look to this: #1274

**Comment by valver** [comment]
I do not understand what you mean sorry

**Comment by valver** [comment]
could be a banishment by niantic, thanks for the attention and I am sorry for my Spanish vocabulary
