### ISSUE TITLE
"Can't find any pokestop in a range of 5000m!"

### ISSUE THREAD

**Issue by itomex** [Ar1i/PokemonGo-Bot#1298]
Hello, i got this problem since yersterday !! 

I thought it would be fixed today, but it still happend... I can't farm on this account anymore... 

Does anyone know what i should do please ? 

Thank you very much for your feedback !

**Comment by xJustx** [comment]
#1274

**Comment by itomex** [comment]
My bad, im new here lol i just saw that it happends for everyone !!
