### ISSUE TITLE
[GER] Keine pokéstops

### ISSUE THREAD

**Issue by d4nlo3008** [Ar1i/PokemonGo-Bot#1299]
Heyho,

da ich mitbekommen habe, dass hier einige diese Sprache verstehen/sprechen sende ich die Anfrage mal auf deutsch:

Bekomme leider die Nachricht, dass alle pokéstops im Radius von 5km bereits benutzt sind. Der Bot geht dann immer wieder zur "default location" zurück und gibt diese Fehlermeldung im loop wieder an. 

"[14:02:44] We cant find any PokeStops in a range of 5000m!
[14:02:45] We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying.."

Liegt dieses Problem auch an der veränderten API von Niantic? Sprich, gehört es auch zu den Problemen, die hier öfters in den letzten Anfragen erwähnt wurden?

Beste Grüße

**Comment by Ar1i** [comment]
ja gehört es

**Comment by d4nlo3008** [comment]
und selbst der Chef selbst versteht deutsch :D nice! Danke für die Antwort :)
