### ISSUE TITLE
[German] FEHLER HILFE! Pokestop!

### ISSUE THREAD

**Issue by Cenkyavuz** [Ar1i/PokemonGo-Bot#1300]
![unbenannt](https://cloud.githubusercontent.com/assets/20838708/17401343/67ea8ade-5a4d-11e6-94c1-d55ebc3c70aa.PNG)
Ich habe dieses Problem schon die ganze zeit hat jemand eine Ahnung woran das liegen könnte?
Danke im voraus.

**Comment by Abbasoo** [comment]
#1274

**Comment by Correexx** [comment]
Oke du bist dann jetzt der 6te dem ich es in ca 10 min sage: Niantic hat die Server Gepatch und aufgrund dessen hat sich die API geändert die dafür zuständig is das der Bot weiß wo pokemon und pokestops sind und da man diese grad versucht herauszufinden kann der Bot leider nicht für dich Cheaten :)

**Comment by Cenkyavuz** [comment]
Okay danke dir :D @Correexx
