### ISSUE TITLE
is bot rdy

### ISSUE THREAD

**Issue by luc113035** [Ar1i/PokemonGo-Bot#1301]
is it ? and if its rdy how i can fix it
or waht i need to do if its ready or how i can see how its ready

**Comment by darkoroty** [comment]
The creators are looking for ways to fix it , wait a 4-5h and I hope there will be a new update

**Comment by AKBlizzard** [comment]
Well, 4-5 hours is a random estimate, honestly there isn't an eta on the time the bot will be back up, also not sure how often Ar1i is working on it, we don't get constant updates. You can't help unless you can code.

**Comment by Ninjaku** [comment]
#1274

**Comment by luispereira** [comment]
There will take a while while people are still figuring out what really had changed on Niantic API, you can follow the progress here, until then just hope and wait https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by pokerave** [comment]
READ This Please #1306
