### ISSUE TITLE
PokeStops

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#1302]
Hello Ar1i,

We all know you are aware of the PokeStops error for the past 24 hours and how it is impossible to use your bot, but could you give us a ball park estimate on how much more time it is going to take to fix that error you said you have found? Also, on how much longer until you release the next version of your bot, by the way, it truly is an amazing bot. I have seen that you have updated 2 of the packages 3 hours ago, but they didn't seem to fix anything.

**Comment by Mainfrezzer** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1274

**Comment by Ar1i** [comment]
Never said they will fix anything, its just a thing for the update which is needed. Probably its done tomrrow, if we are lucky today.
