### ISSUE TITLE
Pokemon Go Bot not working

### ISSUE THREAD

**Issue by BlertonD** [Ar1i/PokemonGo-Bot#1303]
I downloaded this pokemon go bot and it didnt work it just shows me that:

[15:06:42] Error reloading Pokemon list: BadAuthentication
[15:06:42] Error: Pokemon Go Rocket API
[15:06:42] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   bei PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, S
ring password) in C:\Users\messa\OneDrive\Documents\GitHub\FinalVersionPokecrot
PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:Zeile 34.
   bei PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\m
ssa\OneDrive\Documents\GitHub\FinalVersionPokecrot\PokemonGo.RocketAPI\Client.c
:Zeile 129.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausg
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerN
tification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\me
sa\OneDrive\Documents\GitHub\FinalVersionPokecrot\PokemonGo.RocketAPI.Logic\Log
c.cs:Zeile 53.

**Comment by keustii** [comment]
ATM all pokemon GO bot are DOWN.

**Comment by scimo2** [comment]
#1274 for more news

**Comment by AKBlizzard** [comment]
@BlertonD At this moment in time Ar1i's bot isn't available for use. He is working to fix it.

**Comment by NaveTK** [comment]
@BlertonD you entered the wrong username/password... but even if you get it to login, the bot is currently not working due to niantics API changes 18 hours ago...
