### ISSUE TITLE
Wieso geht der pokemon go bot nicht mehr

### ISSUE THREAD

**Issue by BlertonD** [Ar1i/PokemonGo-Bot#1304]
wenn ich versuche den bot zu benutzen dann kommt da so ein fenster bevor es sich öffnet und da steht dann: 

[15:06:42] Error reloading Pokemon list: BadAuthentication
[15:06:42] Error: Pokemon Go Rocket API
[15:06:42] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   bei PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, S
ring password) in C:\Users\messa\OneDrive\Documents\GitHub\FinalVersionPokecrot
PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:Zeile 34.
   bei PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\m
ssa\OneDrive\Documents\GitHub\FinalVersionPokecrot\PokemonGo.RocketAPI\Client.c
:Zeile 129.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausg
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerN
tification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\me
sa\OneDrive\Documents\GitHub\FinalVersionPokecrot\PokemonGo.RocketAPI.Logic\Log
c.cs:Zeile 53.

drin hoffe irgendwer kann mich aufklären.

**Comment by scimo2** [comment]
#1274 for more news

**Comment by Correexx** [comment]
Its so nice that all guys just Post #1274 for answers thats not the question @scimo2 Gosh if u want to be serius just read omg @BlertonD maybe wrong Password or did u loged in with your Ptc in a google acc or with your google acc in a ptc? and to prevent it: The bot have a bug u cant find pokestops but now u the problem will be solved today or tommorow :) if u want it in german ask :)

**Comment by L3v1X** [comment]
alles durchlesen

**Comment by bautschi44** [comment]
gibts nun ein update?wurde sicher 100x gefragt nur ich kann kein englisch wie erfahre ich am besten wann und ob der bot wieder läuft?
lg

**Comment by L3v1X** [comment]
Ar1i also der Owner arbeitret gerade am update

**Comment by bautschi44** [comment]
ok cool danke

**Comment by ValeLeo** [comment]
Ein wenig Englisch lernen wird ja aber wohl drin sein. 

Könntest du den Thread für die Übersicht bitte schließen ? Deine Antwort hast du ja inzwischen :)
