### ISSUE TITLE
Progress & Notification

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#1307]
Hello Ar1i,

Do you have a twitter, or another platform on which you can post the progress of your bot? You have hundreds of people wanting to know information. Instead of just saying it could be done today or tomorrow do you have a better ETA? Do you have a way we could help fund you, like paypal, you should post your email so we can all donate to help.

**Comment by pokerave** [comment]
READ This Please #1306

**Comment by xJustx** [comment]
^
