### ISSUE TITLE
We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying.

### ISSUE THREAD

**Issue by spectrek1453** [Ar1i/PokemonGo-Bot#1310]
We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying.

**Comment by Ricky87654** [comment]
#1291

**Comment by Timmiller109** [comment]
seriously please read other issues before posting

**Comment by setoy** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1274
https://github.com/Ar1i/PokemonGo-Bot/issues/1291
https://github.com/Ar1i/PokemonGo-Bot/issues/1301
https://github.com/Ar1i/PokemonGo-Bot/issues/1307
https://github.com/Ar1i/PokemonGo-Bot/issues/1306
