### ISSUE TITLE
Need help with your softban?

### ISSUE THREAD

**Issue by ToX1cHyDrA** [Ar1i/PokemonGo-Bot#1317]
Hey, i recently watched a video where you can get unbanned if you have a softban for teleporting. If you just stopped using the bot and you want to go out with your friends and play some pokemon you will be banned, but there is a fast way to get unbanned. 
1: Find a Pokestop
2: Spin the pokestop(nothing will happen)
3: Press the X at the bottom
4: Repeat step 2 & 3 40 times or until you are unbanned
I know it sounds dumb but for some reason it works, when you get the reward for the pokestop you will be unbanned.

**Comment by Mamutebr** [comment]
its works fine

**Comment by IceQ1337** [comment]
The bot is unbanning the account itself. And this is not an issue!
Go to https://high-minded.net/
