### ISSUE TITLE
Ideas for the bot  - READ PLEASE ? :)

### ISSUE THREAD

**Issue by rayito45** [Ar1i/PokemonGo-Bot#1318]
I would like to be included in your bot pokesniper, is so easy capture pokemons with this program, with the registerurl.bat only wait for the pokemon in  http://pokesnipers.com/  and click snipe for to redirect the program, or just the option to capture Pokemon in certain coordinates automatically.

Like would not be bad to add a more human behavior, only goes of pokerada in pokeparada , 
it would be good that sometimes diverted either surrounding the pokestop or random routes and not just in a straight line ( I guess that's ).

could just be a way in which only walk randomly in certain areas capturing pokemons

the same could be kept on the map with the help of users or automatically catch the Pokemon that , to manually dial a tour and so could capture certain pokemones particularly in an area

not much as can program or if all this, I bring my ideas alone
and above all thank you very much ar1i , if you can not 'm happy with what you've accomplished

by google traductor :"v

**Comment by IceQ1337** [comment]
You came too late.
And post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
