### ISSUE TITLE
Not an issue, but just sharing a pokestop farming gpx file, while we wait for Ar1i's great work =]

### ISSUE THREAD

**Issue by mydonny1986** [Ar1i/PokemonGo-Bot#1320]
Anyone would like to have pokestop farming gpx file while we wait for Ar1i's great work?
Australia Melbourne City 150+ pokestops in 10 mins, I'm no coder, but just putting the pokestop gps locations together. Change the file type to gpx and good to go XD, let me know how it go.
[pokestopfarm txt.txt](https://github.com/Ar1i/PokemonGo-Bot/files/401948/pokestopfarm.txt.txt)

Sorry if I'm posing this at a wrong place, don't know where to share =P

**Comment by LvGPoke** [comment]
Thx man! What is the XP/H? 
I still don't know how to implement gpx files :/

**Comment by Sander523i** [comment]
what do I need to run the files

**Comment by mydonny1986** [comment]
Well I never calculate the xp/h, mainly use it for getting items before I start botting, 
So if everything goes perfectly, 
50xp x 150shops x 5.5times/hr = 41.25k/hr
If you use eggs then 82.5k/hr
But you have do do it manully tho XD

**Comment by Sander523i** [comment]
Donny how do I run the file

**Comment by sylva91** [comment]
how to run it (or use it) ?

**Comment by mydonny1986** [comment]
Just like how you spoof gps locations...
Watch this guy's tutorial
https://www.youtube.com/watch?v=rhbSeg6xg_s
Well you need a Mac and Xcode tho..=.=

**Comment by Sander523i** [comment]
ow oke im running windows 10

**Comment by ToX1cHyDrA** [comment]
What s a gpx file?

**Comment by LvGPoke** [comment]
I think its a file that saves a route on google maps... but I'm not 100% sure if thats true ... maybe we have a captain here

**Comment by mydonny1986** [comment]
Yes location files, route file, not only google maps, also other applications as well
Watch this, its the same type of file he used to simulate walking
https://www.youtube.com/watch?v=9vqOWCNuZD4

**Comment by punkoussa** [comment]
i'm no expert but i found a method of my own to get max xp 60k-40k xp and max pokémon ( no luky eggs) 
- i use -33.8669305,151.2092733 sydney location (2xx pokestops)
- speed 180km/h and the most important thing set the radius at (1100 meters ) so you don't get banned 
i have tested this method on all my account none was banned it's  the fasts way to fast xp that i have found

**Comment by mydonny1986** [comment]
@punkoussa ha I see, 180km/h wouldnt that be too fast? I am gonna try that in Melbourne when the bot is up.. So basically if the radius is smaller, it won't go out of the radius right?

**Comment by punkoussa** [comment]
..

**Comment by punkoussa** [comment]
exactly , as long as you keep the radius small you'r ok , i'v discovered this while spoofing the gps in nox , traveling instantly in small distances is safe
