### ISSUE TITLE
Just a quick question.... 

### ISSUE THREAD

**Issue by PloxFire** [Ar1i/PokemonGo-Bot#1322]
I know whats going on with the bot and they're updating etc, but when he says "Well only release the executable" does that mean we can download it it and it will be the same and fixed? Or if he releses this "Executable" will it still be offline/Broke?

**Comment by Millenniunn** [comment]
it doesnt affect anything for you...   it only means he wont publish his source code so other people like pokecrot cannot steal ar1i's code and rebuild their own program.

**Comment by NaveTK** [comment]
For a normal user like you or me it won't make any difference, we'll still be able to run the newest versions of the bot and everything is going to work like it should... it's just that he won't release the source code anylonger. That means nobody can take his source code, change the name and donation button of the bot and release it as their own like some people were doing it

**Comment by PloxFire** [comment]
Oh nice, cheers
