### ISSUE TITLE
What is this problem?

### ISSUE THREAD

**Issue by azlath** [Ar1i/PokemonGo-Bot#1323]
[http://es.tinypic.com/r/24b26oi/9] URL IMAGE

**Comment by UltraVLT** [comment]
ffs read the issue section.The bot isn't working atm.

**Comment by pokemongowwtr** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1306

**Comment by xJustx** [comment]
^

**Comment by bunnymuny** [comment]
#1274
