### ISSUE TITLE
Just a small problem

### ISSUE THREAD

**Issue by fairytailss** [Ar1i/PokemonGo-Bot#1324]
.-. I know we have unban in the bot, but the bot take so long to realized that an account has been softbanned, can you guy upgrade it? . Sorry for my bad English

**Comment by 0ny** [comment]
Yeah that's a problem for me too if i want to get some rare pokemons. Maybe add that the first what the bot do is unban? 
-----------------------------
Ja das Problem habe ich auch  wenn ich bestimmte pokemons fangen möchte. Vielleicht könnte man den bot so einstellen, dass er als erstes unbant

Thanks (Sorry for bad english)
