### ISSUE TITLE
Error coming "We Can't find any pokestop in a range of 5000m " even there is  a pokestop in that range

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#1327]
An error coming"We Can't find any pokestop in a range of 5000m " even i decrease the range still the same error coming .Please help

**Comment by setoy** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1306

**Comment by PokePro21** [comment]
So it will fix till tomorrow?

**Comment by mydonny1986** [comment]
Guys please read before you post anything..
[https://github.com/Ar1i/PokemonGo-Bot/issues/1306](url)

**Comment by mydonny1986** [comment]
Just chill out and let the developer do their work and donate..=]

**Comment by bapoek** [comment]
I've been using the latest bot, but the problem is still the same.
like this capture :

![bot](https://cloud.githubusercontent.com/assets/20962751/17578893/fcf35474-5fb8-11e6-805b-6fd86a31d29b.jpg)

is there any latest updates.
