### ISSUE TITLE
Just catching Pokemon

### ISSUE THREAD

**Issue by Baris1990** [Ar1i/PokemonGo-Bot#1328]
I'm pretty sure some people don't need those pokestops. Isn't it possible to let the bot go around and only catch Pokemon?

**Comment by hendek95** [comment]
Zaten bizim milletin aklı böyle şeylere çalışır ama takdir ettim mantıklı. :D

**Comment by sseduppp718** [comment]
stop posting shit dude we are waiting for important update....if you just want to get popular go home..../(^_^)/

**Comment by NaveTK** [comment]
Even though the current problem we're facing is often referred to as the "_No PokeStops Problem_", it doesn't mean that it's **only** unable to find pokestops. In fact it doesn't recieve the position of **any** map object at all, that includes PokeStops, Gyms and of course also Pokemon. So no, we cannot make the bot go around catching Pokemon before this problem has been solved. Everything you could normally acces through the world map on the original Pokemon Go app does not work for the bot right now. It's only capable of managing Items and Pokemon you already own.
