### ISSUE TITLE
No near pokestops [READ ME IMPORTANT ISSUE]

### ISSUE THREAD

**Issue by BradleyFlorence** [Ar1i/PokemonGo-Bot#1329]
<img width="848" alt="capture" src="https://cloud.githubusercontent.com/assets/11214309/17410338/34197a0a-5a41-11e6-9dcb-c0c39f6e4eb8.PNG">
As you can see from the image the Pokebot does not allow the capturing of pokemon because it keeps retrying to find Pokestops but keep repeating the same error message and does not even bother to try and catch any pokemon.

**Comment by epiclololol** [comment]
xD

**Comment by pokerave** [comment]
if you want the whole story
READ the Following.

#1291 - Read This
#1274 - then This
#1306 - This is the End

Before posting new thread.

**Comment by Rhaego110** [comment]
this makes me kind of ..angry? please just READ before posting the same stuff again and again

**Comment by xJustx** [comment]
^
