### ISSUE TITLE
[Request] Implement the eggs incubator

### ISSUE THREAD

**Issue by Jukera** [Ar1i/PokemonGo-Bot#133]
Heyho!
Is it possible to implement the eggs incubator? 
The bot should be use the eggs automatically.

**Comment by plowzey** [comment]
I wish this was a implemented good idea

**Comment by stormlolz** [comment]
Yes good idea, eggs are so important

**Comment by 13XxM1CHA3lxX37** [comment]
Cosign.
You can also do it manually by turning location services off, but that would be much better

**Comment by ReactiioN1337** [comment]
Guys take a look at the pokomon-go protobufs. Maybe there is a protobuffer for this, dunno. You could check it, implement it and create a pull request instead of an issue(because this is not an issue).
