### ISSUE TITLE
Not an issue just a question while there is some down time

### ISSUE THREAD

**Issue by swtrpeter** [Ar1i/PokemonGo-Bot#1330]
I have been using a different bot and I was wondering if i download this version is it pretty easy to install and get working? What are the requirements ? I looked in the wiki etc. but couldnt find any installation guides. Any help would be appreciated.

**Comment by emilie253** [comment]
you download, you open and.... work :) But dont work for the time being , need fix ;)

**Comment by pokerave** [comment]
Just wait for the new one, before asking this question again., might get new features never know.

**Comment by swtrpeter** [comment]
@pokerave  Thanks ! Sounds easy enough to me.

**Comment by mydonny1986** [comment]
Quite easy, can use it out from the box...it opens up a UI for you to fill in some settings, like location you wanna start from, what items you wanna keep, select the pokemons you would like to evolve/transfer/keep etc

**Comment by swtrpeter** [comment]
@mydonny1986 yeah sounds like what I have been using. Just seems like a better community and more updates when things change. Is there a gui you can access from outside of a network ?

**Comment by mydonny1986** [comment]
@swtrpeter yes, you can see all your pokemons and their exact IVs and percentage, can also manually power up/evolve/transfer them, and can also see how many candy you have.
And their move set as well.

**Comment by swtrpeter** [comment]
@mydonny1986 Awesome ! Look forward to the fix ! Thanks everybody for the fast response !

**Comment by gnzl0o** [comment]
we all are :)
