### ISSUE TITLE
Just curious on the status of the new update?

### ISSUE THREAD

**Issue by Timmiller109** [Ar1i/PokemonGo-Bot#1331]
Do we have any kind of timeframe on when you might be ready to roll out a new update for the bot? Awesome work and thank you so much for your effort for all of us.

**Comment by pokerave** [comment]
![tomorrow](https://cloud.githubusercontent.com/assets/20603254/17410873/47ad3330-5a7e-11e6-9716-7c62263709c1.jpg)

**Comment by mydonny1986** [comment]
Chill man, I believe they are all working as hard as they can

**Comment by Timmiller109** [comment]
I wasnt trying to be pushy. Was simply curious.

**Comment by mydonny1986** [comment]
@Timmiller109 Yeah I know we all curious, its 3am here...im waiting hahaha

**Comment by Timmiller109** [comment]
Lol I hear ya. My concern is less about the bot itself and the ramifications of having botted. It seems Niantic is starting to drop the ban hammer on people.
