### ISSUE TITLE
do i have to update???

### ISSUE THREAD

**Issue by gorgis112** [Ar1i/PokemonGo-Bot#1332]
i was just wondering if i have to update the bot when the problem is solved and it works again??? cuz now im on the latest version.

**Comment by pokerave** [comment]
I think you have to because that latest you have wont be the latest when they update. right? or am i missing something?

**Comment by ColdF0rest** [comment]
Yeah,they will publish a new version which you have to download

**Comment by gorgis112** [comment]
@ColdF0rest ok thx

**Comment by BrutalBirdie** [comment]
#1274

**Comment by xJustx** [comment]
^
