### ISSUE TITLE
How I start???

### ISSUE THREAD

**Issue by Matheusnovo** [Ar1i/PokemonGo-Bot#1333]
I downloaded but I don't know start

**Comment by pokerave** [comment]
You start by waiting and reading the issues 

if you want the whole story
READ the Following.

#1291 - Read This
#1274 - then This
#1306 - This is the End

BTW Bot not working atm.

**Comment by datguypanix** [comment]
@Matheusnovo 

1. Download it as .zip
2. Unpack it somewhere
3. Open the "Builds only" folder and unpack that I another folder on your desktop
4. Start "PokemonGo.RocketAPI.Console.exe" and put your details
5. Happy botting.

The bot isn't working atm. Niantic changed the API
