### ISSUE TITLE
How to download the Bot

### ISSUE THREAD

**Issue by ankhmok** [Ar1i/PokemonGo-Bot#1335]
I was using the last vision 3.8.0.0 and I download it from the other link and I found out here maybe the source of the Bot, I just want to know where can I download it? From CORE>Builds only?

Btw after reading your post and try my Bot I know it's doesn't work now, just strive

**Comment by kelops** [comment]
https://twitter.com/Ar1iDev

**Comment by ankhmok** [comment]
You mean the following link? Thankyou and forgive my poor English 

https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by pepeyon** [comment]
Yes. If you want the bot compile, just need to download the "Builds only" [Link](https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only)

**Comment by ankhmok** [comment]
Thankyou for u guys helping

**Comment by xJustx** [comment]
^
