### ISSUE TITLE
Error no pokestops within 5000 km

### ISSUE THREAD

**Issue by RuseolliModzYT** [Ar1i/PokemonGo-Bot#1336]
Good morning, puts me there pokestops, but exactly where I put it there as 100 pokestops, and I get as if there are none within 5000km help !!

**Comment by pokerave** [comment]
if you want the whole story
READ the Following.

#1291 - Read This
#1274 - then This
#1306 - This is the End

Before posting new thread.

**Comment by RuseolliModzYT** [comment]
A I understand, I hope they fix it soon, thanks for everything

**Comment by xJustx** [comment]
^
