### ISSUE TITLE
Wie lange kann das ungefähr noch dauern? 

### ISSUE THREAD

**Issue by Cenkyavuz** [Ar1i/PokemonGo-Bot#1337]
Wollte nur mal fragen wie lange das noch dauern kann bis der bot wieder funktioniert ?

**Comment by jk6046** [comment]
Gibt keine genaue Zeit. Es soll morgen im laufe des Tages rauskommen

**Comment by Cenkyavuz** [comment]
Okay danke :D

**Comment by jk6046** [comment]
Gerne

**Comment by xJustx** [comment]
1337!!!
