### ISSUE TITLE
https://twitter.com/OfficialPokeBot

### ISSUE THREAD

**Issue by DonMoritz** [Ar1i/PokemonGo-Bot#1340]
Hey Ar1i,
just wanted to make shure if this guy is just taking advantage of the situation or if the money people send to 

"PokeBot ‏@OfficialPokeBot  16 Min.Vor 16 Minuten
Donate to the @OfficialPokeBot at: Paul.Kodiakj@gmail.com on PayPal. Product is free, donations are appreciated."

is actually reaching the right guys :)

Greetings

**Comment by pokerave** [comment]
AS you can see
![as you can see](https://cloud.githubusercontent.com/assets/20603254/17414155/01fed19a-5a8d-11e6-9bd8-e378224b585b.jpg)

**Comment by DonMoritz** [comment]
Well im not familiar with twitter so my guess was everyone can write that. 
Thanks anyways :)

**Comment by Ar1i** [comment]
Everyone can write that, but already spoked with him :)!
