### ISSUE TITLE
How to fix Pokestop problem

### ISSUE THREAD

**Issue by Ninamyers** [Ar1i/PokemonGo-Bot#1343]
Alternative to Bot
1) Open Nox, Bluestacks, or your favorite emulator
2) Launch Pokemon Go via apk file
3) Spin pokestop with mouse

A bot is a bot.

Thx Ar1i and all devs for your work.

**Comment by KamoiChikubi** [comment]
What did I just read?

**Comment by KnewNothing** [comment]
Did someone just call me a bot?

**Comment by Biscuit090** [comment]
This doesn't achieve the rate of pokestop looting that the bot does. Especially if you have a low-end computer like a laptop or just a shit PC overall. (He means downloading an emulator to play pokemon go while faking your GPS location).

**Comment by HeIIoWorld** [comment]
That's not a fix - it's an alternative

**Comment by Revoss** [comment]
what drugs are you on

**Comment by ade182** [comment]
Are you sleepwalkers ?

**Comment by kakksa** [comment]
hahahhaha

**Comment by mrlinxx** [comment]
at that moment ninamyers knew she fked up. lol

**Comment by CreativiTimothy** [comment]
Correction:

Title: Alternative to Bot
1) Open Nox, Bluestacks, or your favorite emulator
2) Launch Pokemon Go via apk file
3) Spin pokestop with mouse

A bot is a bot.

Thx Ar1i and all devs for *your* work.

Or maybe just not post anything at all

**Comment by idkwateva** [comment]
Did you know the meaning of "fix"?

**Comment by motemo77** [comment]
all i know is vicks... vaporub...

**Comment by stormlolz** [comment]
Anyone have a portable emulator ? thx

or install without admin rights

**Comment by 0x92** [comment]
stop smoking weed
![50f97bf8afa96f5c9100004c](https://cloud.githubusercontent.com/assets/6593435/17431658/5b714e38-5afb-11e6-917f-581122f6c9f6.jpg)
