### ISSUE TITLE
WHEN IS BOT RDY

### ISSUE THREAD

**Issue by luc113035** [Ar1i/PokemonGo-Bot#1345]
WHENNNNNN

**Comment by KnewNothing** [comment]
Stop being ungrateful... if you want to see how much time doing something like this takes then go take a cs course and learn otherwise wait patiently

**Comment by CreativiTimothy** [comment]
when you learn how to code

**Comment by Jeybo53** [comment]
if we dont have this guys we will never have it so be cool

**Comment by oXNARXo** [comment]
calm down ! it's FREE so just w8 him !

**Comment by McLovin1337** [comment]
Probably tomorrow , Ar1i is sleeping https://twitter.com/Ar1iDev

**Comment by FAymYs19** [comment]
... close

**Comment by QustomiZed** [comment]
Wauw! We dont pay for it and ppl are so anoying and disrespectfu.

**Comment by ValeLeo** [comment]
Luc, close the issue please.
