### ISSUE TITLE
Stop Asking About Bot

### ISSUE THREAD

**Issue by GhostSamurai** [Ar1i/PokemonGo-Bot#1346]
While bot is being worked on those who cant wait much longer and have android check out
http://repo.xposed.info/module/com.axndx.prithvee.pokemongocontrols
Or http://en.bignox.com/ in the mean time

**Comment by Safti54** [comment]
is there en emulator for ios to ?

**Comment by GhostSamurai** [comment]
Yes

**Comment by GhostSamurai** [comment]
For iOS visit http://iosem.us

**Comment by Safti54** [comment]
Yes but i wannna play it on my pc not on my device

Am Freitag, 5. August 2016 schrieb GhostSamurai :

**Comment by GhostSamurai** [comment]
So download nox

**Comment by LvGPoke** [comment]
@GhostSamurai  it says that I have no connection to app.box.com when I try to download the pokemon app from iosem.us app on my iphone... you know what the problem is ?

**Comment by jivie2006** [comment]
can you give me more information on this matter, i live in the middle of nowhere oklahoma. i want to be able to catch a few from home. how do these work?

**Comment by LvGPoke** [comment]
I read that this link http://iosem.us isnt working anymore... but nox is still working... just search in youtube for instructions... it's very easy

**Comment by GhostSamurai** [comment]
@LvGPoke it does work I use it on my iPhone. Its just some times its down try again later

**Comment by GhostSamurai** [comment]
Follow this if you want nox @jivie2006
