### ISSUE TITLE
How long will this Take??

### ISSUE THREAD

**Issue by TheDjCS** [Ar1i/PokemonGo-Bot#1348]
All I want to know is this. How long does everyone think this will take to get the bot fixed. Not to force a rush or anything I just want to get a general idead

**Comment by GhostSamurai** [comment]
Its been answered read the other comments

**Comment by jivie2006** [comment]
lol go read

**Comment by motemo77** [comment]
it will be fixed when it fixed... in the meantime, please go outside, socialise with other... or not... i'm not your mother...

**Comment by LvGPoke** [comment]
There are developers 40 h awake to fix this problem... so be patient and wait until they give info... i think they have bigger problems to deal with than responding to these kind of questions.
