### ISSUE TITLE
Map works again

### ISSUE THREAD

**Issue by Ted0504** [Ar1i/PokemonGo-Bot#1349]
Hey guys check the skiplagged pokemon maps, it seems the map works now. Does it mean they already solved the API problems?

**Comment by Ted0504** [comment]
forget it

**Comment by mrlinxx** [comment]
GoRadar is better. 👌🏼

**Comment by Correexx** [comment]
y if u follow the other comments then u will check they got the api at 8pm its just time to implement it to the bots code :)
