### ISSUE TITLE
Hope this helps.

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#1350]
I got my hand on the fix (The emulator) for the changes in the certification shit.

http://pastebin.com/SYbmYjf8

Enjoy.

**Comment by GhostSamurai** [comment]
Nice!

**Comment by plowzey** [comment]
Thanks.

**Comment by GhostSamurai** [comment]
@Ar1i

**Comment by plowzey** [comment]
@Ar1i

**Comment by katchim** [comment]
can you post  your folder in this thread?

now your  bot is runnin?

**Comment by Tochez** [comment]
@Ar1i

**Comment by dearanson** [comment]
Excuse me. How to use it? i am new sorry

**Comment by fredylie** [comment]
Hope this help. 
https://skiplagged.com/pokemon/#-33.879,151.211,19

**Comment by NidiKea** [comment]
hm ich weiss nicht, wohin ich das kopieren soll bzw. wo das rein muss kann mir das jemand möglichst einfach erklären? Sorry

**Comment by darkoroty** [comment]
How i install? Im new

**Comment by FeloPlays** [comment]
Same... Don't know what to do with it?

**Comment by pokerave** [comment]
its for the developer to use. anyway they say they have a new issue now. this was solve yesterday.

**Comment by Ar1i** [comment]
Thanks!
