### ISSUE TITLE
GOOD NEWS!!!

### ISSUE THREAD

**Issue by jivie2006** [Ar1i/PokemonGo-Bot#1351]
I just saved a ton on my car insurance....

**Comment by motemo77** [comment]
Dude... you just made my day!

**Comment by mezo91** [comment]
i signed up just to tell you how much i'm happy for you.

**Comment by jivie2006** [comment]
thank you. nice to have an extra $6.42 every month.

**Comment by mezo91** [comment]
tell me more about it.

**Comment by Tochez** [comment]
XD

**Comment by CreativiTimothy** [comment]
...

**Comment by fakybaby** [comment]
congratulations!

**Comment by Biscuit090** [comment]
What the fuck is this topic even here for? Go spread your cancer somewhere else.

**Comment by kevcussick** [comment]
nice one did u get a free lvl40 account with the insurance or a 10000 cp dragonite?

**Comment by Ar1i** [comment]
Nice!
