### ISSUE TITLE
@Ar1i how far are u finished ? :)

### ISSUE THREAD

**Issue by Safti54** [Ar1i/PokemonGo-Bot#1353]
just to know if i can go to sleep or na ^^

**Comment by Safti54** [comment]
just to know if i can go to sleep or na ^^

**Comment by OGcpalm** [comment]
he is sleeping

**Comment by Safti54** [comment]
oh, well then good night to u all :)

**Comment by motemo77** [comment]
FFS, people.... let him do his magic uninterrupted.... how would you like being rushed? no good, eh?

**Comment by ToX1cHyDrA** [comment]
The more comments u leave the more time he ll spend reading them and the longer it ll take him to finish it so just stop it and let him work. Put yourself in his place, he is doing this for free and u guys expect him to do so fucking much, just be patient, he will finish it eventually

**Comment by Tochez** [comment]
^ close thread plz

**Comment by sseduppp718** [comment]
This post like shit ... you know why? ... Everyone is waiting for the new version to be released but you screw up

**Comment by spena1024** [comment]
idiots
