### ISSUE TITLE
@Ar1i watch this when possible

### ISSUE THREAD

**Issue by IDonated** [Ar1i/PokemonGo-Bot#1358]
This thread on pokemon go devs reddit;
https://github.com/pkmngodev/Unknown6
The github for unknown 6:
https://github.com/pkmngodev/Unknown6
The wiki for unknown 6:
https://github.com/pkmngodev/Unknown6/wiki

hope that helps

**Comment by yashmhatre** [comment]
@Ar1i CHECK IT OUT

**Comment by xavor92** [comment]
Read at #1306, he links to the reddit guys (which made these gits), so there is a high chance he already watches.
The devs of most apps using the api (and therefore most bots) are pretty nicely linked, the API is a big community project.

**Comment by Bannz** [comment]
@Ar1i Cmon We count on you man..!! if i could help .. i'll do but i know pretty bout script..

**Comment by Ar1i** [comment]
Already saw thanks!
