### ISSUE TITLE
is this a ban? 

### ISSUE THREAD

**Issue by ferobeatz** [Ar1i/PokemonGo-Bot#1363]
Hey guys, i was using the bot until the ati update. 

now if I log into my account which i used with the bot. i cant see anything. im just in the game but there is no pokestops no gyms and no pokemons. 

have anyone the same problem? or anyone know how to fix this bs. 

PS: i have a jailbroken ios device. also a tweak called "pokepatch" its to bypass pokemon go jailbreak detaction.

**Comment by Biscuit090** [comment]
Probably. Either the game hasnt loaded up yet or yeah, youve been soft banned

**Comment by J3azzo** [comment]
Update your apk ..... This is for Bot News not for mimimi

**Comment by dodogtg** [comment]
get new account..LOL
