### ISSUE TITLE
I heard in issue "Hope this helps" how to fix

### ISSUE THREAD

**Issue by darkoroty** [Ar1i/PokemonGo-Bot#1364]
I read that issue and ..How i install this? Im new, sorry

**Comment by gummyruler** [comment]
ATM there's no bot, it's been patched go back tomorrow see if the builds folder has been updated. If it has, then go ahead and download it, unzip it and run the .exe.

**Comment by darkoroty** [comment]
Here is 9:22 am xD , i cant wait but the work of Ar1i is beautiful
