### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Ekz0r** [Ar1i/PokemonGo-Bot#1365]
/edit alles gut

Gruß

**Comment by TrippyCat** [comment]
Kannst du kein Englisch? Hier steht überall das er Nicht mehr Funktioniert aus dem einfachen Grund das die Pokemon API worüber es lief gänzlich vom spiel entfernt wurde. Das Niantecs Lösung für den Bot.
Geh raus und Spiel normal, ich bezweifle ein wenig das der Bot nochmal funktionieren wird da aktuell die Schnittstelle fehlt.

**Comment by TrippyCat** [comment]
http://www.chip.de/news/Pokemon-Go-Geht-Niantic-endlich-gegen-Cheater-vor_97847383.html
Laden aber lächerlicher Weise die Geklaute Version auf ihrer Seite hoch

**Comment by Ekz0r** [comment]
Habs erst danach gelesen sorry
