### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by verybadboy85** [Ar1i/PokemonGo-Bot#1367]
Hallo ich würde gern wissen ob
1. Könnte man den Bot über einen Pfad laufen lassen können. Zb über eine kml Datei.
2. Würde er die Pokémons auf seinen Weg erkennen?

Ich frage nur weil ich sowas in der Art über bluestacks ausprobiert habe und ich mir daraus ein Klick bot machen wollte. Aber es wäre natürlich nicht so hammer wie der weil es zu ungenau die Bälle wirft. Ich hoffe ich halte euch nicht auf. Peace

**Comment by TheSmartly** [comment]
Machbar ist es. Es ist nur die Frage, ob es sinnvoll ist und ob Ar1i das machen will. Ausserdem wurde das schon öfters requested. Aber cool wäre es, wobei man glaube ich neben kml auch gpx tracks nutzen sollte :)

**Comment by verybadboy85** [comment]
Ah ok das habe ich wohl nicht gesehen das es schon gefragt wurde. Wäre halt eine Alternative zu unknown6. Und klar die Arbeit die dahinter steckt muss jemand machen. Wenn ich es könnte würde ich gern helfen.

**Comment by jk6046** [comment]
Was genau ist bzw. bedeutet unknown6 in Pokemon GO?
