### ISSUE TITLE
The github of Unknown6

### ISSUE THREAD

**Issue by darkoroty** [Ar1i/PokemonGo-Bot#1368]
https://github.com/pkmngodev/Unknown6  thatds is the fix?

**Comment by bunnymuny** [comment]
almost but still missing :)

**Comment by darkoroty** [comment]
Thats a good news no?

**Comment by bunnymuny** [comment]
Yes of course. There isn`t a ETA yet but if not today, this weekend will be fixed

PS: Follow the link to stay tuned https://discordapp.com/channels/210748996736516096/210748996736516096

**Comment by GhostSamurai** [comment]
https://discord.gg/XsXuRJY

**Comment by Ar1i** [comment]
^https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
