### ISSUE TITLE
Add proxy settings for connection

### ISSUE THREAD

**Issue by bachirassi** [Ar1i/PokemonGo-Bot#1370]
![untitled](https://cloud.githubusercontent.com/assets/14182409/17431677/d5aba7f4-5b03-11e6-89f5-16dc21307233.png)

**Comment by Filip1232334** [comment]
what is that?

**Comment by QustomiZed** [comment]
VPN server

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by bachirassi** [comment]
Sorry about that (I just couldn't run the bot while im using a cnx with proxy and thought to tell u about it)
Thanks a lot for you awesome work!
Seriously what ur doing here is humongous!
