### ISSUE TITLE
Since its "Basically working" i have some Request/idea

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1373]
Just some request and Idea for the future. or now :smile: 

1. Please add minimize to tray option for hiding ;):P
2. Does the bot catch pokemon from pokestop with lures? if no please add.
3. Add a function to just stay in one place(not walk around), spin the pokestop in the area and catch pokemon there. i have an area with 4 pokestop with almost 12hrs of lures i want to stay there and use incense.
4. A GUI to hatch eggs
5. a button to return the Close GUI(pokemon)

**Comment by sefalette** [comment]
3) i think you can to this with set "Move Radius" to 100-200 or something

**Comment by levalbe** [comment]
or radius 0 ?

**Comment by sefalette** [comment]
yes that's right if you set radius to 0 you cant walk

**Comment by PippoAe** [comment]
> Does the bot catch pokemon from pokestop with lures? if no please add.
I guess yes, since when my bot walks to spots that I know are lured my pokemon/h rises.

> Add a function to just stay in one place(not walk around), spin the pokestop in the area and catch pokemon there. i have an area with 4 pokestop with almost 12hrs of lures i want to stay there and use incense.
I tried this with a radius of 30 meters and a very slow walk speed, but sometimes the bots starts to reboot because he thinks that there are "no active pokestops near, servers may be down".
I'd love this function too.

> A GUI to hatch eggs
AFAIK egg-hatching is in the works.

**Comment by HaKKeBeilHaRRy** [comment]
nice to have are to change things after start the bot (pokemon not to catch, max cp to transfer and so on)

**Comment by xuban** [comment]
3- Set radius 100 meters and walk in 2km. If u get all pokestops, u will get a "no active poketops near" and the bot go to first set location.

**Comment by pokerave** [comment]
If you set the radius to 0, then the 4pokestop will be looted you need 5mins to cool down, before it loots again or it will just loop to no usable pokestop in radius, then walk back to original position which you are in because its set to 0 (infinite loop until 5mins cool down)

so its better for the bot to NOT actually walk, have a 5 mins cool down before trying the pokestop again, catch the pokemon there because of the lures and the incense.

**Comment by Waiiim** [comment]
"AFAIK egg-hatching is on work" 
Will it replace the hatched egg with another in the incubator? or will it just make it hatch

**Comment by xJustx** [comment]
Thank you for this but post your suggestions please here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ Thank you!
