### ISSUE TITLE
Status and Updates

### ISSUE THREAD

**Issue by GhostSamurai** [Ar1i/PokemonGo-Bot#1374]
Stay up to date at: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

04/08/2016 - 00:49 GMT+1 : Logic and proto behind seem to have changed MapRequest, we're investigating. 04/08/2016 - 01:37 GMT+1 : Proto files have not changed and new hashes etc. did not have any effect so far. Our best guess currently is that the requests are cryptographically signed somehow, but we don't know anything for sure yet.
04/08/2016 - 02:07 GMT+1 : It's becoming more evident that this is a non-trivial change, and will take much longer than planned to get reverse engineered again.
04/08/2016 - 08:08 GMT+1 : Everyone is currently working on debugging and attempting to trace where unknown6 is being generated. What we know so far can summed-up here: https://docs.google.com/document/d/1gVySwQySdwpT96GzFT9Tq0icDiLuyW1WcOcEjVfsUu4
04/08/2016 - 15:06 GMT+1 : We can now confirm that Unknown6 is related to the API Changes. However, we're conducting further analysis."
04/08/2016 - 21:13 GMT+1 : We know most of the payload that goes into the "unknown6" hash, still working on the encryption/signature algorithm itself.
04/08/2016 - 23:43 GMT+1 : May have figured out encyption, investigation continues.
05/08/2016 - 03:30 GMT+1 : We have a Github page and wiki: https://github.com/pkmngodev/Unknown6 && https://github.com/pkmngodev/Unknown6/wiki

**Comment by pokerave** [comment]
Stay upto date with the developer HERE https://twitter.com/Ar1iDev

**Comment by JunoBotboy** [comment]
AHHH A GHOST

**Comment by Logxn** [comment]
or you follow me :^) https://twitter.com/loganpunkt

#shamelesadverstising

**Comment by Ar1i** [comment]
^this :p
