### ISSUE TITLE
Best location with most pokestops?

### ISSUE THREAD

**Issue by Kranios** [Ar1i/PokemonGo-Bot#1375]
Hi I was just woundering where the best location is with the most pokestops?

**Comment by pokerave** [comment]
New York

**Comment by mase2015** [comment]
New York, Central Park :-) yup...

**Comment by Kranios** [comment]
so basically the default location? Thanks for the answear guys :)

**Comment by Logxn** [comment]
Las Vegas baby

**Comment by Teneryo** [comment]
And what is the zone with most rare pokemon ?

**Comment by Kranios** [comment]
Yeah should you go for pokestops or the place with the rarest pokemons btw?

**Comment by JCortexs** [comment]
Santa Monica near the pier theres like 30 pokestops lure all the time 24/7

**Comment by waldiludi** [comment]
i think at santa monica pier are a few rare pokemons :D

**Comment by Teneryo** [comment]
In Paris i've tried and i works good for me i catched 2 over 2000 pc in a row

**Comment by JCortexs** [comment]
Santa Monica , Sidney, New york , El retiro Spain :P:P

**Comment by Kranios** [comment]
okey then i guess i wil try out santa monica first and see how that goes :), can you have two accounts active at the same time with the bot?

**Comment by Teneryo** [comment]
yes i was using 4 bot at the same time

**Comment by Kranios** [comment]
ohh okey great then I can try all four locations :D really thanks guys for all the quick answears :)

**Comment by JanamSamjhaKaro** [comment]
can we use 4 bots at the same time? running on the same account i mean??

**Comment by Teneryo** [comment]
no on the same account it's really strange it's like nothing happen

**Comment by kakksa** [comment]
just copy the folder, delete the text file in config, so and start just in difrent places

**Comment by waldiludi** [comment]
bot is still not working right?

**Comment by xuban** [comment]
Teneryo i think if you "fly" between several locations... niantic f*ck you.
I recommend you simule a real playing.

**Comment by velfisadri** [comment]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/564806-nice-locations-farm-pokemon-bots-lets-share.html

yoyogi park is best exp/h for me :)

**Comment by mase2015** [comment]
@xuban that's i do too :-) it's fair.

4 bots at the same time... what for? selling? that is fucked up.

have you seen the serverload since niantic fucked the api up for all bots etc.?
it's less than half.

**Comment by Teneryo** [comment]
i know right xuban

**Comment by PokePro21** [comment]
anyone knows dratini nest or charminder nest ?

**Comment by Teneryo** [comment]
4 bots at the same time just for troll my friends and they was like " you download the game yesterday and your have already 4 account over lvl 25 wtf "

**Comment by xuban** [comment]
Fuck github, deleted my comment.

We here (north of spain), farm xp and catch in 43.3152733,-1.9004924 and 43.3193456,-1.9773019. 50-70 stops near 1,5km and a lot of type pokemon.

**Comment by shahroozal** [comment]
@Teneryo well almost anybody knows about the hacks and bots by now so you're just telling them that you cheated.

**Comment by Teneryo** [comment]
in france hack are not so much known because no french ytber have made a video how to cheat on pokemon go

**Comment by smtburc** [comment]
Santa Monica is my favorite

**Comment by liufeibupt** [comment]
If you only consider the density of Pokestops, I would suggest Tokyo. However, there are not much Lure as in SF or NY.

**Comment by Teneryo** [comment]
-33.867038 , 151.20919 Sydney,Australia
260 Pokestops | 80K EXP/H | 290 P/H
Walking Speed 300 KM/H

**Comment by xuban** [comment]
300km/h lol.

I almost always set 8km/h walking and 50km/h driving.

**Comment by xJustx** [comment]
I think you got a answer :p

**Comment by Teneryo** [comment]
i know this walking speed is abused but it is more efficient to reach pokestop
