### ISSUE TITLE
Location for water pokemons

### ISSUE THREAD

**Issue by lidorbt** [Ar1i/PokemonGo-Bot#1377]
Hello guys, I need a good location for water pokemons . 
I saw that many people use/recommend Australia but does anyone have a good location?
Thanks a lot !
(By the way , does the game work for you right now? )

**Comment by PloxFire** [comment]
Neer water.....

**Comment by PloxFire** [comment]
Near*

**Comment by liufeibupt** [comment]
SF

**Comment by jief78** [comment]
@lidorbt disneyland tokyo in japan is a realy good place as of sidney

**Comment by Filip1232334** [comment]
Santa monica pier

**Comment by xJustx** [comment]
^
