### ISSUE TITLE
Question about Squirtle, Charmander, Bulbasaur

### ISSUE THREAD

**Issue by XxSHADOWxWOLFxX** [Ar1i/PokemonGo-Bot#1379]
It is possible to find this pokemons with a higher IV score than 66%.
All these pokemons have 0 attack points. 
i caught 100s of every type, but no one with more than 66% and every time 0 attack.
Is this a bug?

**Comment by kakksa** [comment]
Yes is porrible, i did fint a Bulbasaur with 89%, and i evolved he once to ivnosaur, and he is now like 1300... He will be a 2000-2200 venosaur, but i got one with 2450 venosaur, i did find a wild Blastoise with just 280 cp, 0 15 10 :/

**Comment by IceQ1337** [comment]
This is not the right place to ask questions.
Go to the High Minded Thread please.

**Comment by 0x92** [comment]
You seem to be a really bad luck brian peson. i catched several 100% pokemon but since i did not like them and i cant exchange them i sent them away to a refugee camp

**Comment by dodogtg** [comment]
*delete plz

**Comment by Zykhatslover** [comment]
my blastoise has hydro pump (or w/e is the name of his best attack) and is 96% :-3

**Comment by FoolYah** [comment]
Is bot working again?

Am 05.08.2016 13:54 schrieb "Zykhatslover" <notifications@github.com>:

**Comment by GhostSamurai** [comment]
Stop talking here about nonsense either join the discord server at https://discord.gg/XsXuRJY or the thread on highminded
