### ISSUE TITLE
Fight Gyms - Auto Bot local Gyms

### ISSUE THREAD

**Issue by REDiiiX** [Ar1i/PokemonGo-Bot#138]
Fight Gyms - Auto Bot local Gyms
thanx

and 

Can you add to collect ultra ball not use them

**Comment by Ar1i** [comment]
I dont want to put local Gyms in. Cause its fucking unfair.

**Comment by REDiiiX** [comment]
no problem can you add a feature to collect ultra balls and not to use them and even great balls
