### ISSUE TITLE
Just a Question about the best config.

### ISSUE THREAD

**Issue by PureSkill** [Ar1i/PokemonGo-Bot#1380]
So, basically what is the best config to level up faster ?

Ty ;)

**Comment by UltraVLT** [comment]
Mine is central park with about 50 km/h,keeping the evolvable pkmns to a limit and when there are about 90 I use a lucky egg :)

**Comment by wrobe06117** [comment]
yoyogi park japan with 50 km/ph for me

**Comment by PureSkill** [comment]
@UltraVLT @wrobe06117 And what xp/h do u earn ?

**Comment by UltraVLT** [comment]
441k xp/h with lucky egg,without it's about 90k~110k

**Comment by 0x92** [comment]
350 km/h Central Park 15 000 meters range

**Comment by PureSkill** [comment]
Thank you all ! :+1:  :)
