### ISSUE TITLE
Please help !

### ISSUE THREAD

**Issue by Intera54140** [Ar1i/PokemonGo-Bot#1382]
No find pokestop in range of 500000 !!!

**Comment by pokerave** [comment]
yes even 9999999 read..

**Comment by TrippyCat** [comment]
Learn to Read, THE BOT IS NOT WORKING

**Comment by arzz90** [comment]
Just Wait :smile:

**Comment by Affenasmo** [comment]
No bot is working at this time cause Niantec somehow removed API locations of pokestops etc etc.

**Comment by pokerave** [comment]
use this working map. change LAT and LONG in address if need your own location
https://maps.pokemongo.id/?lat=42.34962&lng=-71.076428

**Comment by dragon2011** [comment]
Same as pokevision https://skiplagged.com/pokemon/#40.778,-73.964,15 , stills works for me, if it helps you

**Comment by xJustx** [comment]
#1274
