### ISSUE TITLE
THE WAIT IS OVER!!!

### ISSUE THREAD

**Issue by jivie2006** [Ar1i/PokemonGo-Bot#1384]
I just got my UPS package!!

**Comment by shahroozal** [comment]
You sir, are an a$$hole :D

**Comment by 0x92** [comment]
![lammasu___shedu_by_glowinfreak-d5j1tz4](https://cloud.githubusercontent.com/assets/6593435/17436396/f8a83b88-5b16-11e6-9f3f-ebadf568cfab.jpg)

**Comment by Mahnium** [comment]
^^

**Comment by ezreal666** [comment]
joke??

**Comment by nietmarvin** [comment]
LOL

**Comment by ezreal666** [comment]
??$

**Comment by IceQ1337** [comment]
Don't spam the Github Project... WTF?!

**Comment by Astifleure** [comment]
https://twitter.com/RedditPokeGoDev --> Uknown6 craked !!!!

**Comment by fenlyn** [comment]
what the fuck :3 password 23.59
