### ISSUE TITLE
Pokémon Go owners are threatening to sue developers over third-party hacks

### ISSUE THREAD

**Issue by NevilleNg** [Ar1i/PokemonGo-Bot#1386]
http://www.theverge.com/2016/8/4/12380210/pokemon-go-niantic-maps-hacks-api-lawsuit

**Comment by GhostSamurai** [comment]
Doesnt look good :/

**Comment by Abbasoo** [comment]
This is encouraging. :-1:

**Comment by GhostSamurai** [comment]
![ee5c5ffc-5a7f-11e6-8e86-1fd6d9838138](https://cloud.githubusercontent.com/assets/6166953/17436786/b056df62-5ae7-11e6-9ab5-06559163bc88.jpg)

**Comment by NevilleNg** [comment]
https://www.reddit.com/r/pokemongodev/comments/4v6k62/the_pok%C3%A9mon_company_international_inc_moving/

**Comment by drakerznight** [comment]
Looks like the Dragonite Awake =D

**Comment by Waiiim** [comment]
Ah ffs

**Comment by Ar1i** [comment]
Shit happens, if they contact me i will take the bot offline, else i wont take it down.

**Comment by Astifleure** [comment]
https://twitter.com/RedditPokeGoDev --> Uknown6 craked !!!!
