### ISSUE TITLE
[German] Gibt es überhaupt ein Bot der grade funktioniert? 

### ISSUE THREAD

**Issue by Cenkyavuz** [Ar1i/PokemonGo-Bot#1388]
Ein Freund von mir hat momentan nämlich ein bot der funktioniert aber er möchte es mir nicht verraten von wem es ist :/ Gibt es noch ein anderes das funktioniert?

**Comment by shahroozal** [comment]
Nein

**Comment by drakerznight** [comment]
Siehe #1376

**Comment by Cenkyavuz** [comment]
Mir ist schon klar was er in #1376 geschrieben hat, aber wollte nur mal fragen das was mein freund mir gesagt hat "Sein Bot Funktioniert" ob das möglich ist oder er einfach lügt?

**Comment by kalcheat** [comment]
Dein "Freund" ist wohl ein Laberkopp.

**Comment by drakerznight** [comment]
Ja, es vielleicht seine Arbeit einen Punkt erreicht, der möglicherweise einen neuen Bot machen, die aber laufen kann, bis jetzt keine offene API, die wir Bot machen verwenden können, um öffentlich.

jedoch sehen #1386

**Comment by Cenkyavuz** [comment]
Okay Danke für alles Infos
