### ISSUE TITLE
Pokestops werden nicht angenommen

### ISSUE THREAD

**Issue by KyBlack** [Ar1i/PokemonGo-Bot#1389]
Hi Leute ich habe den Fehler, das er bei mir keine Pokestops findet egal wie Groß ich den Radius einstelle
und in dem Park wo es "Letzte Woche" Funktioniert hat sind ca. 12-14 Pokestops

Hier das Bild http://abload.de/image.php?img=asdasdabmsih.jpg

wäre für Hilfe sehr Dankbar.

**Comment by TheSmartly** [comment]
Lies!

**Comment by KyBlack** [comment]
no, lies wtf`? look at the Pic
