### ISSUE TITLE
[Request/Suggestion] Updater und andere sachen

### ISSUE THREAD

**Issue by niikooartz** [Ar1i/PokemonGo-Bot#139]
Update Abfrage mit einer messagebox Ja und Nein option wenn man nein klickt geht der/die/das GUI auf und wenn man ja klickt dann beendet sich der Bot und öffnet die Seite :)

```
if (Program.getNewestVersion() > Assembly.GetExecutingAssembly().GetName().Version)
            {
                DialogResult dialogResult = MessageBox.Show("There is an Update on Github. do you want to open it ?", "Newest Version: " + Program.getNewestVersion(), MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    Process.Start("https://github.com/Ar1i/PokemonGo-Bot");
                }
                else if (dialogResult == DialogResult.No)
                {
                    //nothing   
                }
            }
```

Ansonsten eventuell diese übersicht einpaar optionen hinzufügen http://prntscr.com/byv0pi
wie zum beispiel: PokeBälle: (anzahl), SuperBälle (anzahl) usw.. und das aber dann vom GUI aus konfigurierbar :)

unter Other Settings eventuell eine Evolve at (anzahl) Pokemon. dann fängt er bei sagen wir mal 100 entwickelbaren pokemon das entwickeln an und schmeißt ein EI ein wenn diese option angehackt ist :)

Ansonsten muss ich sagen ich bin mehr als Zufrieden mit dem BOT + ich respektiere was da für eine arbeit dahinter steckt :D kenne mich selbst mit C# aus ^^ ist nicht immer einfach :D

ich mache immer wieder videos wenn ein großes update kommt und hoffe das ist okay :D und hatte mir überlegt eventuell einen video Updatelog zu machen :D also nach jedem update zeige ich kurz was geupdatet wurde :D

habe inzwischen knappe 18k klicks auf einem vid und 16k klicks auf dem ersten xD

**Comment by Ar1i** [comment]
Schick mal nen Link von dem Video/Channel bitte und das mit der MessageBox is ne Gute Idee baue ich ein.

**Comment by niikooartz** [comment]
https://www.youtube.com/c/saudracheartz :D

**Comment by Ar1i** [comment]
Das mit dem Adfly Link is aber schon bissl uncool ^^

**Comment by niikooartz** [comment]
naja is aber ein wenig cash nebenbei :D 

hab ja drunter den normalen github link gepackt :D

**Comment by Ar1i** [comment]
Trotzdem ziemlich uncool ehrlich gesagt. Und leite den Link einfach auf die Exe Builds Only. Oder use am besten direct Links, da das Projekt Freeware is und nichts womit man Geld machen sollte ^^

**Comment by niikooartz** [comment]
jetzt kann man auswählen ob man mit ads oder ohne macht :D 

http://prntscr.com/byv8da

**Comment by niikooartz** [comment]
was mir grad noch einfällt wäre ne anzeige in den stats die auftählt wv pokemon von den max slots die man hat gerade besitzt und evtl das gleiche mit items :D das währe noch sick :3

**Comment by niikooartz** [comment]
ich hoffe ich nerve nicht xD

aber ungefähr iwie so :D ich bekomme nur errors daher kann ichs nicht testen -_-

```

            Logger.ColoredConsoleWrite(ConsoleColor.Cyan, "Items: " + _inventory.GetItems + "/" + _inventory.getMaxItemslots);
            Logger.ColoredConsoleWrite(ConsoleColor.Cyan, "Pokemon total: " + _inventory.GetPokemons + "/" + _inventory.getMaxPokemonSlots);
```
