### ISSUE TITLE
Testo???? kanst du mich bitte mir den link schicken zu discord

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#1391]

**Comment by LvGPoke** [comment]
https://discord.gg/DzYNN
Bitte schliessen

**Comment by stickmick12** [comment]
bist du testo??? ich war in einer anderen gruppe

**Comment by LvGPoke** [comment]
Also dich würd ich auch nicht mehr in die Gruppe zurück holen ... Anstand und Rechtschreibung sind bei dir verloren gegangen oder nie aufgetaucht ...

**Comment by stickmick12** [comment]
jaa aber es ist sehr wichtig ich suche die andere gruppe wo testo und co2 drine waren

**Comment by Mahnium** [comment]
English?!

**Comment by frestlyer** [comment]
I don't get it either

**Comment by Deenaiy** [comment]
He's searching for some guys

**Comment by supermario007** [comment]
He can try Tinder or grindr ;-)

**Comment by pcmore** [comment]
Tu mir bitte einen gefallen und lösche einfach dein Konto auf Github. Du hast 11 Fälle für dumme Fragen in schlechtester Grammatik geöffnet und scheinst die Plattform in keinster Weise zu verstehen.

**Comment by pcmore** [comment]
@stickmick12 Tu mir bitte einen gefallen und lösche einfach dein Konto auf Github. Du hast 11 Fälle für dumme Fragen in schlechtester Grammatik geöffnet und scheinst die Plattform in keinster Weise zu verstehen.
