### ISSUE TITLE
Cant find any PokeStops

### ISSUE THREAD

**Issue by godlex999** [Ar1i/PokemonGo-Bot#1393]
I have since yesterday this error: 
We cant find any PokeStops in a range of 5000m!
We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying..

I don't think it is a ban, because it is since yesterday.
Is there someting down why it wont work? 
(i use the most recent version)

**Comment by x33c** [comment]
are you serious..?

**Comment by ruvelro** [comment]
LOL

**Comment by Kranios** [comment]
time to wake up bro

**Comment by Waiiim** [comment]
You didn't read anything since yester f**cking day did you

**Comment by Waiiim** [comment]
Niantic did update
us sad, bot not working
Developpers are trying to get pass that update
Us hope, us wait

You understand?

**Comment by xMiracle** [comment]
All bots are usable at the moment.

**Comment by xMiracle** [comment]
All bots are not working at the moment.

**Comment by godlex999** [comment]
Ah ok! Yeah I red nothing about it. Now i see it ....
Tnx

**Comment by TouchTheSkies** [comment]
Guys, stop getting pissy because some people actually HAVEN'T been on here to read about the issues. Direct them to where it's explained NICELY. No need to act like a dick just because someone doesn't sit on here 24/7 waiting for updates.

**Comment by DargQ** [comment]
@Waiiim That made my laugh fking hard. LOL

**Comment by Zaei** [comment]
Pretty sure there are like 5+ posts that says "Read THIS"

**Comment by canbabacan** [comment]
Pretty sure there are like 5+ posts that says "Read THIS"

**Comment by Requal** [comment]
You should be banned for blindy posting without reading first lol

**Comment by TouchTheSkies** [comment]
3 posts actually, so if they need to learn to read, you should learn to count ^^ And a lot of posts are in broken english, so maybe they'd want one a little easier to understand instead of just having assholes scream at them for asking a question.

**Comment by Waiiim** [comment]
Asking a question who has been the hot topic for the last 2 days and that the answer of that same question is pretty much in every "issue" Even if the titled says something else, someone surely asked the question in it

**Comment by hbchang** [comment]
Try to ask "Niantic", They will answer your question.

**Comment by hbchang** [comment]
You have time to post the question. But you don't have time to review the previous posts. it is funny.

**Comment by NaveTK** [comment]
Btw. since your question has been answered you can close this Issue yourself now, no need to wait for a mod to do so.
