### ISSUE TITLE
What if .... 

### ISSUE THREAD

**Issue by Wutrhad** [Ar1i/PokemonGo-Bot#1394]
If Niantic changed the API, blocking all unofficial parts of Pokemon GO, how can the Bluestacks' Pokemon GO still work ? why don't you try to check how the Pokemon GO APK of Bluestaks work ?

Please, if i said a bullshit, don't flame me cause i don't know much about those things, just explaned my idea.

**Comment by Archimondee** [comment]
bluestack working with android platform, not API Pokemon GO

**Comment by NaveTK** [comment]
Bluestacks is an emulator using the official PokemonGo app like you'd use on your phone

**Comment by CastleFan1983** [comment]
and on bluestacks you are using an fake gps app

**Comment by Wutrhad** [comment]
Well but, how can be official if it gives you the option of moving around with WASD ?

**Comment by CastleFan1983** [comment]
the pokemon app is official but the root and fake gps are not

**Comment by NaveTK** [comment]
The moving thourgh WASD is a third party plugin that simply changes your gps coordinates, it's not a part of the App, that's also the reason the inputs are laggy and ignore the direction you're facing

**Comment by Wutrhad** [comment]
Ok, after that answer I can close thread
