### ISSUE TITLE
Can this get fixed today?

### ISSUE THREAD

**Issue by Filip1232334** [Ar1i/PokemonGo-Bot#1397]

**Comment by NaveTK** [comment]
Nobody knows. Please read the other Issues marked with *READ* or check out the reddit livethread https://www.reddit.com/live/xdkgkncepvcq and official reddit post https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/ to see the current status of this project.

**Comment by Requal** [comment]
Stop complaining...
Go outside and play the game as intended

**Comment by Affenasmo** [comment]
or just use bluestacks as anybody else
