### ISSUE TITLE
[Request] Don't collect the Pokestops

### ISSUE THREAD

**Issue by bamoas** [Ar1i/PokemonGo-Bot#14]
Hey, i wondered if it's possible, that the Bot ignores all Pokestops and just searches for Pokemons in a certain Area which you might have to specify before starting the bot. 

For exmaple i choose the coordinates of the Central Park with an Radius of about 2 km where the bot catch all the Pokemon he can find. 

Would be glad if i get an answer :)

**Comment by chrisoro** [comment]
Yup, in my opinion a great addition.

Just let him walk and catch stuff!

**Comment by chrisoro** [comment]
I took a look at the code myself (I am a dev myself but just have an android phone right now).

From what I can see in this small amount of time:
Logic.cs #303
var fortSearch = await _client.SearchFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

Basically make this optional

**Comment by bamoas** [comment]
Im waiting for an option for that. 
What should i do exactly with this Line above ?

**Comment by chrisoro** [comment]
Well what you could do is comment line 303 till 309 and insert the quote below.
It won't search the pokestop anymore but instead will give you a log message that it skipped. It also increases the wait after reaching the pokestop to 1s-5s(random).
Just a quick hack but as I said, I am not at home and cannot integrate a setting for it.

>
Logger.ColoredConsoleWrite(ConsoleColor.Cyan, $"Skipped touching fort", LogLevel.Info);
await RandomHelper.RandomDelay(1000, 5000);

**Comment by bamoas** [comment]
I'll try out later and tell you if it worked. 

PS : In my version, which i  downloaded yesterday here from github, it's Line 297-305 in Logic.cs

**Comment by Naaw88** [comment]
I also need a option not to get the pokestops, and only go for pokemons i want.
