### ISSUE TITLE
[Suggestion] How to fix people from using this as a forum.

### ISSUE THREAD

**Issue by zunox** [Ar1i/PokemonGo-Bot#1400]
I been on reddit for some time and here reading articles and progress. This section has been miss used quite a bit. This is meant for issues with the program and not so much talking. A while back i purchased a domain. Over the past week i have been working to improve it. I added a forum.  Would the staff want to make their own thread or section so people can talk and not open up issues when its just general chat?

Anyways if interested everything is fresh. http://pokemongohelp.net 

Let me know if its something you guys would be interested in.

Cheers!

**Comment by IceQ1337** [comment]
Our Forum is linked on the front page of this github repository....

**Comment by i-am-nobody-1** [comment]
I don't want to open an issue and waste time of dev to close it but, i just want to give heads up to people who are using emulator. My friend was using emulator with gps hack as everyone know. It worked for him yesterday after update. Later today after some time he got banned. I don't know if its normal soft ban or permanent ban. But, just a heads up for people using emulator/gps hack. The snapshot is below.
![emulator](https://cloud.githubusercontent.com/assets/20818032/17445715/b5dff012-5b0b-11e6-89ea-d50a5ad82612.jpg)

**Comment by shahroozal** [comment]
@i-am-nobody-1 ouch :\

**Comment by i-am-nobody-1** [comment]
I'm afraid to open mine. Haven't opened it since niantic update. I'm still lvl 11 and no pokemon near me and have to walk so many miles for one pokestop
