### ISSUE TITLE
Add a way to disable PokeStops.

### ISSUE THREAD

**Issue by lordzxil** [Ar1i/PokemonGo-Bot#1401]
I know it's not working right now but all I want to do is catch Pidgeys, Ratatas, and Weedles. No, I am not trolling, I just want to catch about 10,000 of them. I was wondering if it'd be possible to disable PokeStops?

**Comment by shahroozal** [comment]
why don't you just prevent other pokemons from being caught by selecting them in the pokemon list in the second tab?

**Comment by wrobe06117** [comment]
i think he wants to catch all those but still catch other pokemons, maybe he just wants hes bot to move around catching pokemon and not move from 1 poke stop to another

**Comment by matts829** [comment]
@lordzxil Its more than just pokestops not working. There is a deeper issue that is creating the pokestop error message thats being worked on. If it were just problems with the pokestops you would be able to catch pokemon and just not be able to get pokestops. I hope that answered your question

**Comment by lordzxil** [comment]
No, haha. I want it to move around catching all the pokemon but not spin the pokestops (unless I need pokeballs, then I will enable them). The purpose is the in the achievement page if you level with pokestops, it shows that you visited an impossible amount whereas catching that many shitty pokemon to level is the legit way to level right now. Gives you the illusion of not having used a bot. I mean like, traveled 20km, but visited 10k pokestops? That is hilarious. Also, I still have a lvl 23 main with similar pokemon as bot-I just want this one so that I can be on another team in case of some legendary event bullshit.

**Comment by pokerave** [comment]
there is now way that there is 10k pokestop in a 20Km radius. lol, im assuming its a joke. anyway, your problem will be that the inventory is only 350(default) asuming you only have pokeball(ultra,great, even master) you can only throw 350 times WITHOUT missing.

**Comment by lordzxil** [comment]
Ok, mine says 100km traveled with 8263 pokestops. There is no way I did this. Either way, I just want a way for it to disable collecting Pokestops but still visit them. Once I'm out of balls, I can reenable for a bit (I have 750 item storage). I just want to level my main without too many pokestops and catching all the rares because I like to do that myself-just dont like the grind-especially since it has an impact on gameplay.

**Comment by Waiiim** [comment]
If you disable Pokestop, and you're wish is to only capture pokemons
Then Niantic's will see that you have 100% accuracy and the bot sends a special code to the server that only bot's send, so they will notice that you cheat and get banned :+1:

**Comment by Wrexist** [comment]
You will not have any pokemon balls left then.

**Comment by 13XxM1CHA3lxX37** [comment]
You can do this with Pokesniper

**Comment by 1nf0** [comment]
Yes, it's more than pokestops. You can make your char travel by setting location to a far target, but you won't find anything.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
