### ISSUE TITLE
Is the bot still not working? 

### ISSUE THREAD

**Issue by itsbangie** [Ar1i/PokemonGo-Bot#1404]
Just wondering

**Comment by xuban** [comment]
Repeat this question hundreds of times has made it work. It is a miracle!

**Comment by Shikkaku** [comment]
if you just read at the first site (<>Code) then you know that the bot isnt working

**Comment by Requal** [comment]
You impatient kids shouldn't be allowed on the internet...
You kids don't read, just post your questions blindly when the answer is shown in CAPITAL and font 40 size...
