### ISSUE TITLE
Wheeeen?

### ISSUE THREAD

**Issue by darkorotyyt** [Ar1i/PokemonGo-Bot#1405]
The work of Ar1i is impresionante but wheen? :'(

**Comment by xuban** [comment]
Now, all thanks to you!

**Comment by itzjaydon** [comment]
@xuban what you on about "now"

**Comment by xuban** [comment]
He asks when I say that now. All thanks to your question, without it would not have been possible.

**Comment by Shikkaku** [comment]
pls just stop asking... i think Ar1i will post it if the bot is working

**Comment by bautschi44** [comment]
All work hard to fix it i give my Respekt all❤️

**Comment by Requal** [comment]
What the hell is impresionante?
Can you kids stop creating posts that has nothing to do with the developement!?
This ain't a forum!

**Comment by Logxn** [comment]
It needs time! Chillax

**Comment by Ar1i** [comment]
^
