### ISSUE TITLE
I know the bot is not working, but... 

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#1407]
Only for get near pokestops, right? 
Can the bot be used for bulk evolve, for example? 
Or definitely is no good to use? 
Thanks

**Comment by Biscuit090** [comment]
If the bot is OFFLINE, take a wild guess at what you can do with it at the moment.

**Comment by FAymYs19** [comment]
You can still evolve and transfer Pokemon. The bot just wont run around and catch anything.

**Comment by Requal** [comment]
All these posts...
Have you tried before asking here?
Try it!
If it doesn't work then it doesn't work!!!

**Comment by zzzz9999** [comment]
See @Biscuit090,  you think you are smart, cool, replying that way? 
Grow up!

**Comment by NaveTK** [comment]
Things the bot can still do:
-Auto/Manually transfer Pokemon
-Auto/Manually evolve Pokemon
-Auto Item management

Things the Bot cannot do at the moment:
-Find/Use PokeStops
-Find/Catch Pokemon

Everything that does not require the bot to walk around is still possible

**Comment by zzzz9999** [comment]
Thanks NaveTK
