### ISSUE TITLE
source code ok

### ISSUE THREAD

**Issue by leolas123** [Ar1i/PokemonGo-Bot#1408]
Reddit Pokemongo Dev @RedditPokeGoDev
Unknown6 has finally been cracked! Source code in node.js, python and java @ https://www.sendspace.com/file/wtaqj0  
Password is: LolHowTheFKuGUYSdOIT845

**Comment by PoopThrower** [comment]
Can someone confirm this works and is safe?

**Comment by Mainfrezzer** [comment]
thats bullshit, its a folder with insults

**Comment by Qluz** [comment]
https://www.reddit.com/live/xdkgkncepvcq/

**Comment by bushidoku** [comment]
So, bot will never get ubdate ?

**Comment by Sander523i** [comment]
can someone please close this issue

**Comment by kakksa** [comment]
kick that dude out
