### ISSUE TITLE
Unknown6 has finally been cracked! 

### ISSUE THREAD

**Issue by rlmrso** [Ar1i/PokemonGo-Bot#1410]
@Ar1i Source code in node.js, python and java
 
https://www.sendspace.com/file/wtaqj0 /  Password is: LolHowTheFKuGUYSdOIT845

https://twitter.com/RedditPokeGoDev

its over niantic..

**Comment by Waiiim** [comment]
It's a troll...

**Comment by Correexx** [comment]
lols that BOX IN YOUR FACE xD Comment

**Comment by darkoroty** [comment]
no is a troll, read this https://twitter.com/RedditPokeGoDev, but how i install?

**Comment by dodogtg** [comment]
Zonk!

**Comment by willmlocke** [comment]
If this was real it wouldn't be here. Im almost certain Ar1i would be one of the first people to know if U6 was discovered

**Comment by TouchTheSkies** [comment]
You trolls are more annoying than Niantic.

**Comment by pokerave** [comment]
![pokemongodev](https://cloud.githubusercontent.com/assets/20603254/17452312/daa34f32-5b76-11e6-882b-51b933d8d99a.jpg)
