### ISSUE TITLE
who's missing the bot right "up" here

### ISSUE THREAD

**Issue by biiouii** [Ar1i/PokemonGo-Bot#1411]

**Comment by stickmick12** [comment]
i

**Comment by Biscuit090** [comment]
...w-what?

**Comment by darkoroty** [comment]
when is the bot online?

**Comment by jivie2006** [comment]
@darkoroty the bot will be online when it comes online...

**Comment by Waiiim** [comment]
The bot is back up =)

**Comment by PloxFire** [comment]
@Waiiim no its not stop lying

**Comment by dstN** [comment]
what the f.. is wrong with you? this is not a forum. get your facts what "github" is and stop commenting shit here. it doesn't help. just LEAVE.

**Comment by Cenkyavuz** [comment]
The bot Comes never online

**Comment by yashmhatre** [comment]
up

**Comment by kakksa** [comment]
When should the kids go sleep, so he can work... All this questions all the time, the team are working on it kids, it will come, just give them some time
