### ISSUE TITLE
Ar1i

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#1414]
kannst du mich wieder in die Gruppe einladen von discord wo #update war und nur ein Chat da wo Testo war co2 und so will da wieder rein habe ccleaner benutzt und habe jetzt irgendwie alles verloren;/

**Comment by biiouii** [comment]
where

**Comment by stickmick12** [comment]
i was in a discord groupe how are was only 2 hashtag chats with Testo, co2 etc my #number was 9990 but i dont know how i can go in

**Comment by Leak1337** [comment]
krasses deutsch

**Comment by saimoond** [comment]
@stickmick12 Du scheinst wohl vollkommen beschränkt zu sein. Ich wünsche dir eine gute Besserung.

**Comment by saimoond** [comment]
So dämlich ist doch keiner
