### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by biiouii** [Ar1i/PokemonGo-Bot#1416]

**Comment by canbabacan** [comment]
FACEPALM

**Comment by biiouii** [comment]
???

**Comment by Grieche** [comment]
#1291

**Comment by 13XxM1CHA3lxX37** [comment]
Here you go: http://lmgtfy.com/?q=how+to+delete+my+github+account

**Comment by drakerznight** [comment]
See #1386 #1376

**Comment by Sander523i** [comment]
this proves my lawnmower theory

**Comment by Sander523i** [comment]
https://seanhamptoncole.wordpress.com/2012/11/15/how-to-stop-being-stupid-in-10-easy-steps/
