### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Vxphal** [Ar1i/PokemonGo-Bot#1417]
How To solution? please Ar11. "we cant find any pokestop, which are unsed! probably server unstable, are you visited them all."

**Comment by drpenguinMD** [comment]
Read the README at the main page, bro. There aren't any bots working.

**Comment by Waiiim** [comment]
Run before everyone insultes you
QUICK!

**Comment by jmo93** [comment]
You realy can't read the other issues? Facepalm

**Comment by 13XxM1CHA3lxX37** [comment]
Here you go http://lmgtfy.com/?q=how+to+delete+my+github+account

**Comment by fucky0u** [comment]
fuck you

**Comment by drakerznight** [comment]
@Vxphal Where are you IDIOT, I'll hit your head cuz I hate ppl like u

**Comment by Vxphal** [comment]
sorry friend I just know this site, so sorry everyone

**Comment by drakerznight** [comment]
See #1376 and #1386 if you insist to ask the question again!
