### ISSUE TITLE
Even if the bot gets Updated

### ISSUE THREAD

**Issue by Waiiim** [Ar1i/PokemonGo-Bot#1419]
"We would like to repeat that the API-cracking community does not support bots. We are here to crack the API, thats it.  _**That said we would like to confirm that Niantic can detect any MITM apps, these are apps that somehow modify data sent to the server. For example an app that ensures a perfect pokeballthrow. If you used an app like that Niantic could know.**_"

**Comment by moops44** [comment]
If you used an app like that Niantic # **_could_** know."

**Comment by moops44** [comment]
pls stop spam the **ISSUES** with that kind of crap 
we all can read in twitter/reddit/discord/github and other sites whats going on and the whole steps that happens
@Ar1i  kannst du nicht irgendwie issues und request sperren bis es alles wieder funktioniert bzw je funktionieren wird ^^

**Comment by Waiiim** [comment]
Tbh it's an issue that Ar1i can fixe =)

**Comment by OGcpalm** [comment]
there is lots of work arounds

**Comment by Waiiim** [comment]
Still worried that we all get f*cked because of that one plugin of perfect pokeball throws

**Comment by Hahahaha0** [comment]
cool down...

**Comment by drakerznight** [comment]
We can modify it so it can be more "Humanly", Give your support to the API and Bot Dev =D

**Comment by Ar1i** [comment]
Has nothing really to do with the bot
