### ISSUE TITLE
Bored, App is not working

### ISSUE THREAD

**Issue by riautama77** [Ar1i/PokemonGo-Bot#1424]
So Bored, while waiting...........

**Comment by ranggirahman** [comment]
sekolah yang bener dek

**Comment by Bannz** [comment]
if u wont to bored.. make it by urself! fcker!

**Comment by whitemouse14** [comment]
@ranggirahman r u indonesian? Or perhaps you are the owner of pokecrots.com who steal bot from this site.

**Comment by ranggirahman** [comment]
@whitemouse14 What did you learn manners from school ?

**Comment by whitemouse14** [comment]
Dude,
Learn some english first then leave a better comment here.
Lol you made my day.
Go to your friend pokecrot.com instead of coming here

**Comment by ranggirahman** [comment]
Sorry im stupid in english but im know what kind people like you is stupid like my ass. Im just bot user not stealer like pokecrot.

**Comment by whitemouse14** [comment]
Since youre indonesian,
May i ask you this,
What excatly crots means????
I wonder why he named it like that 😂😂

**Comment by ranggirahman** [comment]
Crots meaning jerk*ff in indonesia.
But i dont understand why he created name like that.

**Comment by shahroozal** [comment]
@ranggirahman I wonder why you keep answering instead of the one who created the thread.
