### ISSUE TITLE
For Everyone READ THIS BEFORE TAKE ACTION

### ISSUE THREAD

**Issue by fenlyn** [Ar1i/PokemonGo-Bot#1428]
For Your safety ID/EMAIL..
Please DONT GIVE ANY ID+PASSWORD TO THE UNKNOWN WEBSITE...
LIKE : 
" Pokeadvisor.com "
Please be smart..its for u safety ID later..
Officialy Niantic NEVER ASK ur Password for any reason..

**Comment by drakerznight** [comment]
PokeAdvisor Only needs Google Authentication to Authorize access for Pokemon Go Profile read. Logically, there's no harmful behavior because you log in to Google Account directly in Google Web Portal. However, its true to not give your account ID to unknown site that provide direct log in.

**Comment by fenlyn** [comment]
aaaa sorry i dont want take a risk for unknown website...
who created that website,and for what....
i just wanna be a smart player before take a action

**Comment by FoolYah** [comment]
Is the bot working again?

Am 06.08.2016 09:53 schrieb "fenlyn" <notifications@github.com>:

**Comment by fenlyn** [comment]
nope,bot still not working.

**Comment by FoolYah** [comment]
Ah thank you.

Am 06.08.2016 09:56 schrieb "fenlyn" <notifications@github.com>:

**Comment by drakerznight** [comment]
@fenlyn If you want to become a smart player, be sure to use your high logic to analyze every thing from the gameplay mechanic down into server behavior. You can't easily judge by saying that simple thing even true. If you want to learn _you must sacrifice something to gain some knowledge_

@FoolYah Yeah you fool! Create GitHub account to only see a new version bot. GitHub is available for Open Source Software (OSS), not for cheating stuff! If you want bot, let them trying for crack something in API

**ANY BAN OR SOMETHING THAT CAN DAMAGE YOUR GAME PROFILE IS AT YOUR RESPONSIBILITY AND THE SOFTWARE PROVIDED BY ANY OPEN SOURCE SOFTWARE IS GIVEN AS-IS WITHOUT ANY WARRANTY**

**Comment by FoolYah** [comment]
Shut up you little asshole. I am checking the news on my tablet,  so I cant
read everything. Who cares that i use cheats?  So care about yourself and
don't Comment others. Geez i am not so stupid and hanging 24/7 on the
PC/Internet

Am 06.08.2016 10:04 schrieb "drakerznight" <notifications@github.com>:
