### ISSUE TITLE
Where can I check the news ?

### ISSUE THREAD

**Issue by itomex** [Ar1i/PokemonGo-Bot#1429]
Here is my question, i'd like to know where i could check the news concerning the app problem (API etc...)

Just to be informed in time when the new update comes out ! I dont want to miss anything aha 

Thank you guys, and thank you Ar1i for your work !

iTO

**Comment by dstN** [comment]
if you read the issues here and main issue from Ar1i you would know that. 

can you guys please stop opening issues which are no ISSUES?! this is not a FAQ Forum or something, this is GITHUB.

**Comment by itomex** [comment]
Okay , my very bad im closing it now !

**Comment by drakerznight** [comment]
@dstN you're right however @itomex is the issue itself

**Comment by itomex** [comment]
AHahahahahahaah nice one @drakerznight

**Comment by kickz** [comment]
Please follow twitter: https://twitter.com/Ar1iDev

All of informations about bot is there.

**Comment by NaveTK** [comment]
https://www.reddit.com/live/xdkgkncepvcq check the reddit livethread for the fastest updates on the current situation
