### ISSUE TITLE
Request perfect filter

### ISSUE THREAD

**Issue by FelipeMallmann** [Ar1i/PokemonGo-Bot#143]
Please add perfection filter to block great pokemons with low cp to be transfered

**Comment by andrekkn** [comment]
You mean IV Filter, right? +1

**Comment by Ar1i** [comment]
So, it should not transfer if the IV (%) is like over 90? or how should i understand that?

**Comment by andrekkn** [comment]
Yes, and we should be able to edit the percentage to higher or lower :D Thanks for the support!

**Comment by 13XxM1CHA3lxX37** [comment]
@Ar1i I think he's referring to this: https://pokeassistant.com/main/ivcalculator
So you maybe get a Pokémon that is low CP, but got awesome stats
-> with your nice bot you get stardust and candies en masse
-> you could "upgrade" that Pokémon so that you got a perfect Pokémon on a high level

**Comment by FelipeMallmann** [comment]
yeah, but not just block transfer, it should transfer the lowest one with less then x % perfect if duplicated pokemons. 
If you just cancel transfer we will get full off pokemons

**Comment by Ar1i** [comment]
Hmm @FelipeMallmann for that i need a better calculation. Cause, what is with the CP? Is it still counting right? So example: i got 1 pokemon with 99% perfect but only 10cp, when i got a pokemon with 2000cp and 60% perfect.. you know?

**Comment by andrekkn** [comment]
@Ar1i You should keep the perfect pokemons+ the duplicates the user wants. Just ignore the perfect pokemons when transfering. Just check if there are duplicates to transfer if the number of not perfect pokemons is above the limit the user wants(the actual duplicates max option)

**Comment by FelipeMallmann** [comment]
example: I checked to keep 3 duplicates pokemons, to not transfer pokemon cp over 999 and to keep pokemons with perfection over 90%.  But if this pokemon i kept with perfection over 90% is the lowest cp pokemon, when i get the 4th duplicate pokemon, it'll try to delete the perfect one and will start a loop..
Trying to delete and blocking, trying to delete and blocking..

**Comment by Ar1i** [comment]
Too much math for me at this time, will try to do it tomorrow.

**Comment by FelipeMallmann** [comment]
Just cancel transfer from pokemon over x% perfection and ignore him in the  lowest cp transfer check,
please

**Comment by Ar1i** [comment]
Yeah thats already in

**Comment by FelipeMallmann** [comment]
alright! Thanks!!

**Comment by mantoniolli** [comment]
thanks! youre the best

**Comment by andrekkn** [comment]
amazing!

**Comment by andrekkn** [comment]
@Ar1i can you make it so when we catch a good Perfection pokemon, you print in a txt which pokemon and what is the CP, so we dont need to go 1 by 1 of our pokemons to check their IV? Obviously, if it is easy for you

**Comment by Ar1i** [comment]
doing a complete list of the pokemons, which you can open in excel orso

**Comment by FelipeMallmann** [comment]
@Ar1i can you update Builds Only for the excel list?

**Comment by Leoguy77** [comment]
@Ar1i maybe you let the bot rename the pokemon to "pokemonname_(iv) when the pokemon is at a value above a configurable value. Ive seen this at an onther bot and it was great.
