### ISSUE TITLE
This website is working if anyone of you want to try it

### ISSUE THREAD

**Issue by JanamSamjhaKaro** [Ar1i/PokemonGo-Bot#1432]
https://skiplagged.com/catch-that/#37.803,-122.318,11

**Comment by dstN** [comment]
for you as well: This is not a forum. this is a github ISSUE-board.

**Comment by d0ct0r87** [comment]
it kinda sucks, yesterday i used that site and it had all the artwork, got off work took a nap woke up now its just outlines/shadows of them. kinda like a rainbow where's waldo.

**Comment by Grieche** [comment]
not working

**Comment by Experte9** [comment]
It dont works,for Germany...
