### ISSUE TITLE
For those of of you using iPhones and miss the bot terribly!

### ISSUE THREAD

**Issue by adman9031** [Ar1i/PokemonGo-Bot#1435]
This is a tutorial to install a tweaked version of the Pokemon go app with a joystick. This for those of you who haven't jail broken your iPhone but would still like some of those features. http://youtu.be/duIS-s3iU98

**Comment by Leak1337** [comment]
Or play direct nox lmao

**Comment by deezmasterballz** [comment]
or just do it from your phone because who wants to sit at a computer all day...

**Comment by adman9031** [comment]
Personally I'm jail broken soo I like that I can play with tweaks anywhere instead of having to use a computer. Also nearby Pokemon automatically show on the right hand side, so all I have to do is tap on them and I walk right to them.
