### ISSUE TITLE
An estimate for when available the bot?

### ISSUE THREAD

**Issue by angel315** [Ar1i/PokemonGo-Bot#1436]
to this day, and tomorrow may be some link alert for when the bot

**Comment by Cuirithir** [comment]
Please don't ask these sort of questions. Be patient and give the devs the time to work everything out. Furthermore, information about the API's status can easily be found, creating a new Issue for this really isn't necessary.

**Comment by angel315** [comment]
okey, I can give the link

**Comment by Xeroxs** [comment]
your new link ??

**Comment by angel315** [comment]
the link where this news bot

**Comment by Xeroxs** [comment]
thou or not ??

**Comment by angel315** [comment]
who pass a link to the hack

**Comment by angel315** [comment]
publish the news link

**Comment by Xeroxs** [comment]
when you talk about the connection is loose or bot ?

**Comment by angel315** [comment]
what?

**Comment by Xeroxs** [comment]
You said if you could link the meter but what link you speak

**Comment by angel315** [comment]
que si sabes alguna novedad de hack, o un link

**Comment by angel315** [comment]
It was just that

**Comment by Xeroxs** [comment]
ok

**Comment by angel315** [comment]
link?

**Comment by Xeroxs** [comment]
not yet

**Comment by angel315** [comment]
y sabes alguna informacion the bot?

**Comment by Xeroxs** [comment]
https://www.reddit.com/live/xdkgkncepvcq/ pasando que lo relacione y habla https://twitter.com/LujiTV bot y la novedad
