### ISSUE TITLE
Bots Will Be Working Shortly

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#1438]
I know this isnt a issue but its a announcement. Bots are shortly going to start to work.
My prefrences:
Dont use your main account in the begining of bots who knows what might happen
Dont put setting too hight
Have Fun
More:
If Ar1i PokemonGo-Bot doesnt work.
Use Necrobot.io
![capture](https://cloud.githubusercontent.com/assets/20713623/17459604/2c45fc18-5c0d-11e6-8cb4-f25190a75027.PNG)

**Comment by pokerave** [comment]
![key](https://cloud.githubusercontent.com/assets/20603254/17459625/e08bb7e0-5c48-11e6-94c2-8757cac02a27.jpg)

**Comment by McLovin1337** [comment]
Ye , actually we're almost done; still working on it. Shoutout to all admins & debuggers great job :)

**Comment by pokerave** [comment]
Monster lol 44hrs? get rest dude.. you all deserve it.

**Comment by pokerave** [comment]
![one](https://cloud.githubusercontent.com/assets/20603254/17459711/cec88110-5c4c-11e6-9190-44bd855a97d0.jpg)

**Comment by pokerave** [comment]
![2](https://cloud.githubusercontent.com/assets/20603254/17459731/ca0c4b2e-5c4d-11e6-8545-511924b7f076.jpg)

**Comment by peoplearmy** [comment]
Ar1i let me know if you need help with converting the python code to csharp. I shoud have some time in a bit.
