### ISSUE TITLE
Not AN Issue. Just celebrating.  THANK YOU to all the DEVs

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1439]
![redit](https://cloud.githubusercontent.com/assets/20603254/17459638/5d31ca64-5c49-11e6-8b65-a13edc22e680.jpg)

**Comment by Biscuit090** [comment]
Ayy the devs are almost done? I actually don't mind that this post isn't an issue, keep up the good work guys! Woohoo!

**Comment by pokerave** [comment]
![7b7a30d0-820d-47e3-9400-0086857849e0](https://cloud.githubusercontent.com/assets/20603254/17459689/93bad0a6-5c4b-11e6-9892-3381708b4600.jpg)

**Comment by chickeflonoah** [comment]
Hey guys, I just signed in here some minutes ago but i read all the issues 
I just have a question. Dont u think that Niantic is gonna publish a new patch, when u finish the new bot? I will hope not, but I think so.. Sorry for my bad english, I'm german

**Comment by Kuzmarin** [comment]
http://prntscr.com/c2iu1s its here

**Comment by pokerave** [comment]
![one](https://cloud.githubusercontent.com/assets/20603254/17459708/b52d61bc-5c4c-11e6-8fbe-4bcc3c1b84a9.jpg)

**Comment by pokerave** [comment]
![2](https://cloud.githubusercontent.com/assets/20603254/17459728/ab467a48-5c4d-11e6-89df-4f144553550f.jpg)
