### ISSUE TITLE
Softban unbanner not working properly

### ISSUE THREAD

**Issue by Knedex777** [Ar1i/PokemonGo-Bot#144]
The softunbanner is not working ! :D
Just got softbanned (all pokemons go away & no xp from pokestop) and the bot isn't detecting that i'm softbanned ! I've waited few more pokestops (like 3-4) and it's still not detecting that i'm softbanned and pokemons keep going away :)
![sans titre](https://cloud.githubusercontent.com/assets/20714882/17234726/bf459b32-553b-11e6-8f66-1db1a245b435.png)

**Comment by Ar1i** [comment]
It should detect after 6 times not getting xp from pokestops. will add it to pokemon too tho! so it will work faster.

**Comment by Ar1i** [comment]
Try with newest version

**Comment by Knedex777** [comment]
Thanks ! i'll try :)

**Comment by Knedex777** [comment]
It's working ! But the new stats that you just added are buggy (see pic)
![sszeadezdezdezdezdezd](https://cloud.githubusercontent.com/assets/20714882/17234952/72bed9ca-553d-11e6-834e-3e807c7bba62.png)
