### ISSUE TITLE
Bot Update Soon

### ISSUE THREAD

**Issue by McLovin1337** [Ar1i/PokemonGo-Bot#1440]
Announcment ; Everything is updated , read more here-> https://github.com/keyphact/pgoapi and here https://www.reddit.com/live/xdkgkncepvcq.

Thanks for everyone who helped us gettin this done. Im going to sleep now , have a good night fam. <3

**Comment by pokerave** [comment]
![one](https://cloud.githubusercontent.com/assets/20603254/17459710/c0ea4f88-5c4c-11e6-858d-6aa48fab0a98.jpg)

**Comment by McLovin1337** [comment]
Im not talkin about the bot @pokerave , we updated the API and we know now what unknown 22 is.

**Comment by chickeflonoah** [comment]
And when is the bot published?

**Comment by Emmi911** [comment]
@chickenflonoah when they find time to fix it... Be patience and happy that this is freeware

**Comment by pokerave** [comment]
![2](https://cloud.githubusercontent.com/assets/20603254/17459726/9e364900-5c4d-11e6-87dc-9f3d9c46e2c0.jpg)

**Comment by chickeflonoah** [comment]
Oh yes I really appreciate that, but I thought this was the bot

**Comment by chickeflonoah** [comment]
Ahh ok thanks @pokerave

**Comment by Safti54** [comment]
yeah but many people los patient couse last update was 3 days ago i hope it comes soon.
pls tell us when u probably realese the bot like its gona be in 1 day or 4 days pls giv us an update over the hole bot so the people know ok its comeing in 3 or 4 days so we know something about the the great progress u have made guys

**Comment by Biscuit090** [comment]
All they have to do is convert the files from Python to the program they're planning to release the update on, just wait until tomorrow. The new bot update will be released within the next day or two.

**Comment by Waiiim** [comment]
Ar1i and Logan decided to "fuck" sleep and pass their whole night and the translation of python to their programm, so it's gonna come or later on today or tomorow

**Comment by MrProblematic** [comment]
I'm from Rio and im more excited about this release then the olympic games!
#Ar1i my hero!
