### ISSUE TITLE
Soo tomorrow is the day?

### ISSUE THREAD

**Issue by darkorotyyt** [Ar1i/PokemonGo-Bot#1441]
Ar1i and Logan decide to sleep but hes work are impresionante. Tomorrow is the day? Tomorrow bots online?

**Comment by BradleyFlorence** [comment]
Yep!

**Comment by Pyroman2300** [comment]
Should be, but then again it will get here when it gets here. Only time will tell.

**Comment by Biscuit090** [comment]
Yeah, I'm no Ar1i but it's being released everywhere not just on GitHub so it's definitely coming out tomorrow, if not check out Necrobot.io

**Comment by Logxn** [comment]
Okay guys, to clear some things up.
Yes we are going to go to sleep now, but I cant assure, that the bot will be online tomorrow.

**Comment by xJustx** [comment]
^
