### ISSUE TITLE
not urgent request *putting a pokemon sniping option*

### ISSUE THREAD

**Issue by wrobe06117** [Ar1i/PokemonGo-Bot#1444]
ok i know the title is confusing so heres an explanation, is it posible to put a setting where the bot will snipe pokemons that we want using a 3rd party program or something like that to look for nests and the bot will roam around the nest capturing the wanted pokemon i know theres already a bot like that so maybe you could add the option in your bot? so basically the option will make the bot run from 1 pokemon specific nest to another instead of poke stops

so im going to link the video of the bot with the pokemon sniper for reference,

https://www.youtube.com/watch?v=Wkb_D79LmrA

**Comment by Affenasmo** [comment]
just set the walking distance only 200 m

**Comment by Logxn** [comment]
This is not for requests.
This is issues only

#Closed

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by wrobe06117** [comment]
@xJustx  where can i post? cos the thread you left wont allow me to reply to it

**Comment by xJustx** [comment]
Sorry, I will reopen this.

**Comment by wrobe06117** [comment]
@xJustx  tnx hope the dev can add this option cos i want to stock up on dragonairs but using bluestacks or nox to jump from 1 dragonair nest from 1 another is tiring ^^

**Comment by xJustx** [comment]
Thank you for your suggestion. But there are a lot of wishes.

**Comment by TheShade1337** [comment]
@wrobe06117 Just for your help. The way I farm specific pokemon

http://pkmngotrading.com/wiki/Nests

Thats a site where you have locations of different poke-nests just copy and paste the latitude and longitude and make that to your location where you want to go. 

the only thing you have to do now is to set the range and your MPH/KMH.


For dratinis there is no special spawn atm, but Ive got a Magikarp/Karpador spwan where I caught most of my Dratinis.


Latitude: 37,808966

Longitude: -122,410153 

I hope I could help you... :)

Ich hoffe ich konnte dir helfen... :)

**Comment by wrobe06117** [comment]
@TheShade1337  thanks ill use it when bot is up ^^

**Comment by TheShade1337** [comment]
@wrobe06117 No problem but be patcient its a lot of waiting and hoping to get whats you want espescially dratinis but its the best way to manage nests at the time.
