### ISSUE TITLE
*NOT ISSUE* News || The Reddit FINISHED the API !

### ISSUE THREAD

**Issue by Abbasoo** [Ar1i/PokemonGo-Bot#1447]
![untitled](https://cloud.githubusercontent.com/assets/20796710/17460227/65d7b3b0-5c65-11e6-9fd2-af3ca7fcf213.jpg)

Api || https://github.com/keyphact/pgoapi

**Comment by Biscuit090** [comment]
we know.. it was announced a while ago

**Comment by fulsker** [comment]
People never read the older posts.
Nice enthusiasm though

**Comment by Leak1337** [comment]
captain obvious

**Comment by xJustx** [comment]
^

**Comment by Georgiexoh** [comment]
Sorry im a noob at this, what does this mean exactly?
