### ISSUE TITLE
Error with bot

### ISSUE THREAD

**Issue by WalkingResurrector** [Ar1i/PokemonGo-Bot#1448]
Keep getting *no pokestop in range* error ;~; is the bot still not working? because I thought I heard it was. Thanks!

**Comment by DrakeandJosh** [comment]
it'll work when Ar1i next updates it

**Comment by Midnlght** [comment]
there still in the process of updating it, shouldn't be too long now @WalkingResurrector

**Comment by WalkingResurrector** [comment]
Alright Thank you!!! @Midnlght and @DrakeandJosh

**Comment by xJustx** [comment]
^
