### ISSUE TITLE
A way to manage Poke-nests with the Poke-Bot. (Close if its not an issue)

### ISSUE THREAD

**Issue by TheShade1337** [Ar1i/PokemonGo-Bot#1449]
ENG:

I dont know if its an issue or not, but for people who wants to farm special Pokemon, there is a site where you can see many different Pokemon-nests and spots where the poke-nests are located. 

Link: http://pkmngotrading.com/wiki/Nests

to use that with your bot, you can copy and paste the latitude and longitude from your chosen pokemon nests.
After that make that to your location where you want to go with your bot.
After that set the speed and range. (Mostlikly/Range: 5000Km/Speed: 15-50KmH/Mph)
So youre ready to go! :)

GER:

Ich habe keine Ahnung ob das ein Fehler oder Problem ist, korrigiert mich wenn ich falsch liege...

Für Leute die ein Problem damit haben, mit dem Bot spezielle Pokemon-Nester aufzusuchen oder zu fangen, gebe ich euch jetzt hier eine Methode wie ich dies momentan mache.

Es gibt eine Seite wo die meisten Pokemon-Nester mit Längen und Breitengrad aufgelistet sind.

Link: http://pkmngotrading.com/wiki/Nests

Möchtet ihr zu einem Speziellen Nest kopiert einfach die Längen und Breitengrad angaben und fügt sie zu eurem neuen Standort hinzu. Meistens sind dies Nester wo auch Poke-stops existieren also dürften keine Probleme entstehen.
Habt ihr euren neuen Standort angepasst, so müsst ihr nur noch eure KM und euer Tempo anpassen.

Ich hoffe es war etwas hilfreich und sollte es hier nicht reinpassen dann tut es mir leid

LG 

TheShade :)))

**Comment by Tochez** [comment]
Thanks for the info @TheShade1337

**Comment by TheShade1337** [comment]
@Tochez No problem :)

**Comment by Georgiexoh** [comment]
I am unsure, wont your bot just go to the next pokestop and eventually move out o the pokemon nests range?

Isn't it better to make it around 200m range or something?

Please correct if im wrong

**Comment by Midnlght** [comment]
Thanks for this information mate :)

**Comment by TheShade1337** [comment]
there are many different ways, sure you can but not every poke-nest is that small there are sometimes nest which are very large. you can see the location on your map is it in a park or smth you can put your range down for example 1Km but if there are many buildings you can put it to 5km or 4km of course. It worked for me, but how you are doing it is in your hand :)

you have to try what fits best for you :)

I hope this could help you :)

**Comment by Georgiexoh** [comment]
Thank you my friend

**Comment by TheShade1337** [comment]
@Georgiexoh @Midnlght no problem :)

**Comment by IDonated** [comment]
The majority of this nest has changed with the last updated, the dratini's nest are all gone for example. There's a reddit thread that explains how nests changed, for example, magmar next changed to elektabuzz nests.

**Comment by TheShade1337** [comment]
@IDonated yeah youre right b ut they updated the site right after the update there was an explenation which nest changed but they removed it and updated the most nest in the list 
you can also see if the nest are confirmed not confirmed or the best nest what you can get :)

**Comment by Biscuit090** [comment]
Any idea if these items that will likely be featured in the next update have any effect on the nests?
![pokefarmer2](https://cloud.githubusercontent.com/assets/20826708/17461420/b6027c96-5c40-11e6-971f-cf35e052f477.PNG)
