### ISSUE TITLE
New Stats shown are glitched

### ISSUE THREAD

**Issue by Knedex777** [Ar1i/PokemonGo-Bot#145]
The new stats you've just added are not showing properly ! (see pic)
![556545454](https://cloud.githubusercontent.com/assets/20714882/17234999/099a0216-553e-11e6-9c73-c1f4a8c8cd85.png)

**Comment by Ar1i** [comment]
wuppppsss adding a fix

**Comment by Ar1i** [comment]
Try it now please.

**Comment by Knedex777** [comment]
Yes it's now working, thanks for your work !!! :D

**Comment by Ar1i** [comment]
Good!
