### ISSUE TITLE
please check this coding

### ISSUE THREAD

**Issue by x1aolung** [Ar1i/PokemonGo-Bot#1454]
https://github.com/keyphact/pgoapi

**Comment by Inforcer25** [comment]
We know the API has been updated. He is updating the bot now. Just wait. Holy shit you guys are like 5 year olds wanting ice cream.

**Comment by Biscuit090** [comment]
Is this an issue? If you're trying to show this to Ar1i I assure you that he's seen it lol

**Comment by dragon2011** [comment]
@x1aolung  why dont you read @Ar1i twitter feed then you wont need to post unnecessary crap, reading takes less time than posting
