### ISSUE TITLE
Ar1i is Love, Ar1i is Life

### ISSUE THREAD

**Issue by GHANT** [Ar1i/PokemonGo-Bot#1458]
I was only 22 years old I loved Ar1i so much, I had all the code and builds
I pray to Ar1i every night before bed thanking him for the build update I've been given.
Ar1i is love I say, Ar1i is life
My dad overhears me and calls me a faggot
I knew he was just jealous of my devotion for Ar1i
I called him a cunt
He slaps me and sends me to go to sleep
Im crying now, and my face hurts
I lay in bed and its really cold
A warmth is moving towards me.
I feel something touch me
Its Ar1i
I am so happy
He whispers in to ear "this is my code"
He grabs me with his powerful monkey hands and puts me on my hands and knees
I'm ready
I spread my ass cheeks for Ar1i
He takes so long to update his code
It hurts so much but I do it for Ar1i
I can feel my butt tearing as my eyes start to water
I push against his force
I want to please Ar1i
He roars a mighty roar as he fills my butt with his love
My dad walks in
Ar1i looks him straight in the eye and says "Alrighty then, donate to my paypal"
Ar1i leaves through my window
Ar1i is love, Ar1i is life

**Comment by DargQ** [comment]
Really nice how much time it took for you? :D

**Comment by Georgiexoh** [comment]
LMFAO wow wee

**Comment by Xeroxs** [comment]
lolllllllllllllllllllllllllllllllllllllllllllllllll

**Comment by The-Real-IMMG** [comment]
Lol you just copied Shrek is love, Shrek is life :D

**Comment by pikaiskawai** [comment]
FFS that's sick af ( coppied also )

**Comment by Logxn** [comment]
Hello? 
Where is "Logan is love, Logan is live" q.q

**Comment by Mrtkcmz** [comment]
@Logxn 
I was only 22 years old I loved Logan so much, I had all the code and builds
I pray to Logan every night before bed thanking him for the build update I've been given.
Logan is love I say, Logan is life
My dad overhears me and calls me a faggot
I knew he was just jealous of my devotion for Logan
I called him a cunt
He slaps me and sends me to go to sleep
Im crying now, and my face hurts
I lay in bed and its really cold
A warmth is moving towards me.
I feel something touch me
Its Logan
I am so happy
He whispers in to ear "this is my code"
He grabs me with his powerful monkey hands and puts me on my hands and knees
I'm ready
I spread my ass cheeks for Logan
He takes so long to update his code
It hurts so much but I do it for Logan
I can feel my butt tearing as my eyes start to water
I push against his force
I want to please Logan
He roars a mighty roar as he fills my butt with his love
My dad walks in
Logan looks him straight in the eye and says "Alrighty then, donate to my paypal"
Logan leaves through my window
Logan is love, Logan is life

**Comment by Logxn** [comment]
<3
