### ISSUE TITLE
Issues solved, Reddit

### ISSUE THREAD

**Issue by Experte9** [Ar1i/PokemonGo-Bot#1459]
Reddit say its Done: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
https://github.com/keyphact/pgoapi

**Comment by DargQ** [comment]
Someone has already working bot its paid and its sh*t :D

**Comment by Madrocker85** [comment]
We know, it was announced about 12 hours ago.

**Comment by Rummskull** [comment]
And there is already a pull request for FeroxApi from neoz :)
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/125

**Comment by Filip1232334** [comment]
when we can use bot?

**Comment by pokerave** [comment]
![update](https://cloud.githubusercontent.com/assets/20603254/17462163/d5f35fae-5cac-11e6-873b-8de5070861ee.jpg)
