### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by StephenSocksTv** [Ar1i/PokemonGo-Bot#146]
I click on builds only. Then the only one there its like a zip file. Then I click download. And it downloads into word perfect and its all really weird coding. Please help

**Comment by Ar1i** [comment]
Just download it? You should be able to Download something.

**Comment by StephenSocksTv** [comment]
is there anyway you could email me the download? Stephensockstv@gmail.com

**Comment by StephenSocksTv** [comment]
like the folder

**Comment by djdomrep** [comment]
install winrar and open the downloaded file with winrar. unpack it to a folder
