### ISSUE TITLE
when we can use bot?

### ISSUE THREAD

**Issue by Filip1232334** [Ar1i/PokemonGo-Bot#1460]

**Comment by Rhaego110** [comment]
can you just please READ his tweets

**Comment by Filip1232334** [comment]
i dont have tweater sry
what he says

**Comment by pokerave** [comment]
![update](https://cloud.githubusercontent.com/assets/20603254/17462161/c508f208-5cac-11e6-81dd-2cb91ecc6447.jpg)

**Comment by Filip1232334** [comment]
oke tnx

**Comment by Rhaego110** [comment]
you dont need twitter to read this

**Comment by sixmoonth** [comment]
im already using necrobot, its work but no gui
https://github.com/NECROBOTIO/NecroBot/releases

**Comment by pokerave** [comment]
we are waiting for this one @sixmoonth

**Comment by AnusRandalus** [comment]
Right After u Start 2 use ur brain.

**Comment by Filip1232334** [comment]
sixmoonth how to start that bot

**Comment by christopherbees** [comment]
we will wait for ar1i, he is the best

**Comment by lailaps** [comment]
@Filip1232334 Use files in config folder. Working great since 40 mins.

**Comment by OfficialMT22** [comment]
necrobot isnt worth my time

**Comment by lailaps** [comment]
It's working perfectly for me for 20 accounts, all over level 33 and all with >50,000 xp/h.
So yeah, it's worth my time.
First I just want to level up and later I catch the rarest Pokemon with sniper.

**Comment by OfficialMT22** [comment]
the fact that you have 20 accounts is depressing

**Comment by EmperorChez** [comment]
@lailaps wanna share your config? mine isn't working :/
