### ISSUE TITLE
WE'VE DONE IT - POKEMON BOT FIXED

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#1465]
http://image.prntscr.com/image/ed7760db358c4d64852e7e0c231874b6.png

**Comment by kalcheat** [comment]
AWESOME GUYS!!!

**Comment by benz1996** [comment]
You guys are the best!!!!

**Comment by Aiwoma** [comment]
YAYAYA

**Comment by biiouii** [comment]
really nigga

**Comment by Aiwoma** [comment]
is it up for download, i was using the shitty pokefarm omg

**Comment by zzzz9999** [comment]
Yeahhh

**Comment by emilie253** [comment]
we need download new version or we can to use last??

**Comment by TheShade1337** [comment]
GZ

Gute Arbeit 

Good work :p

**Comment by AriahVitae** [comment]
U did an awesome works, all redditdev and botdev, good job.

**Comment by ONOBARY** [comment]
Awesome works for team

**Comment by emilie253** [comment]
where is new version plz?

**Comment by OfficialMT22** [comment]
be respectful and wait for it

**Comment by Midnlght** [comment]
Thank you guys for all the time you have put into this !

**Comment by lakezz** [comment]
link?

**Comment by dragobite** [comment]
My body is ready, danke schön Jung ich war schon am verzwiefeln mit diesem Pokefarm Schrott

**Comment by januszhej** [comment]
AYEEEEEEEEEEE

**Comment by xavifm97** [comment]
OMFG!

**Comment by BimbasVG** [comment]
AWESOME!!! THANKS!!!!

**Comment by CastleFan1983** [comment]
there is one thing i want to say, you guys are fucking amazing

**Comment by The-Real-IMMG** [comment]
Good work guys :)

**Comment by motemo77** [comment]
You guys are great

**Comment by lovakosh** [comment]
You are the best. Well done!!!

**Comment by KToast21** [comment]
I have a Error 
![capture image](https://cloud.githubusercontent.com/assets/20845939/17462650/194fbcbe-5cb4-11e6-8770-ee50d5c7ab2d.png)

**Comment by whitemouse14** [comment]
finally, the wait is over..
thanks a lot dude,

**Comment by iridiumkills** [comment]
That doesn't show anything lol, I ran it while the bot was broken and I still got all that data

**Comment by AnusRandalus** [comment]
Thumbs up.

**Comment by The-Real-IMMG** [comment]
Why is it transfering all my pokemon? I've set it to keep 1 duplicate and its transferring everyone!

**Comment by iridiumkills** [comment]
@The-Real-IMMG 
Did The same to me, i was just like "wtf, trooooooollll" and then I stopped it lol

**Comment by The-Real-IMMG** [comment]
yeh iv exited then reopened and it still done it. I had charmeleon with 87 candies and its transfered him :(

**Comment by iridiumkills** [comment]
Yea dude, I lost some pretty high cp Pokémon during that, but thankfully not my best
 https://cloud.githubusercontent.com/assets/20603254/17462714/c40af132-5cbe-11e6-899c-94c3d93d65db.png

**Comment by iridiumkills** [comment]
I can officially confim that its been fixed
