### ISSUE TITLE
BOT DONT START

### ISSUE THREAD

**Issue by Daniel140** [Ar1i/PokemonGo-Bot#1466]
The Bot dont start ;(

**Comment by xJustx** [comment]
any screenshots?

**Comment by sposha25** [comment]
never had a shot of the first bot so i've been following the updated version. could someone put me through the steps of running the new bot?:)

**Comment by Daniel140** [comment]
the bot dont start ? from What you want a Scrrenshot ?

**Comment by KToast21** [comment]
![capture image](https://cloud.githubusercontent.com/assets/20845939/17462646/e783ead4-5cb3-11e6-9422-1a78bd0014ef.png)

**Comment by Ayold** [comment]
Bei mir steht klassenbibliothek kann nicht direkt gestartet werden.

**Comment by 13XxM1CHA3lxX37** [comment]
Nimm das fertige Build, mache uU eine AV Ausnahme und starte als Admin

**Comment by Midnlght** [comment]
hmmm, seem to be having the same issue, clicking start bot and nothing happens

**Comment by Mrtkcmz** [comment]
my bot is working perfectly

**Comment by fak3333333** [comment]
I get the same problem

**Comment by Ayold** [comment]
Danke :-)

**Comment by Midnlght** [comment]
I Just restarted my computer, and it works fine now (;

**Comment by Ayold** [comment]
Aber wo ist das fertige Build?

**Comment by fak3333333** [comment]
Does anyone know how to fix this? Sorry, I don't understand german :(

**Comment by Ayold** [comment]
Kommt immer das mit der Bibliothek...

**Comment by sajko** [comment]
![xx](https://cloud.githubusercontent.com/assets/7016410/17462684/6b9df4da-5cb5-11e6-83fc-cb745dccacd4.jpg)

**Comment by xJustx** [comment]
@Daniel140 Is it working now? Do you have the newest version?
