### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by benz1996** [Ar1i/PokemonGo-Bot#1467]
Thank you for ur job and time spend! but atm i still have same problem and yes i did download updated version

**Comment by Logxn** [comment]
Please provide us with detailed information about your problem. :)

**Comment by shahroozal** [comment]
Its working perfectly for me

**Comment by sposha25** [comment]
@Logxn  never had a shot of the first bot so i've been following the updated version. could someone put me through the steps of running the new bot?:)

**Comment by OfficialMT22** [comment]
Its transferring all my pokemon even my best cp. All settings are on default

**Comment by shahroozal** [comment]
> Its transferring all my pokemon even my best cp. All settings are on default
ouch! I just noticed that!

**Comment by benz1996** [comment]
Nvm i found i out,i was just being a cunt. Great work!

**Comment by czokalapik** [comment]
Same here, transferring all but the ones above set IV and CP, so it's ignoring "max number of duplicates"

**Comment by benz1996** [comment]
Oh its transferring all pokemons :( just lost a bunch meh

**Comment by amaslkw** [comment]
Same here, transferring all but the ones above set IV and CP x2
