### ISSUE TITLE
Pokemon catchrate bug.

### ISSUE THREAD

**Issue by darren1998s** [Ar1i/PokemonGo-Bot#1469]
I know youre supposed to miss but 
http://puu.sh/qsQLK/ad28c6420a.png 

Pretty sure this is a bug 

Is this due to the new way you guys are re-writing the catching mechanism?

**Comment by EmperorChez** [comment]
most likely a soft ban.

**Comment by Mrtkcmz** [comment]
I think It is soft ban too.

**Comment by b3shoy** [comment]
Soft Ban.

**Comment by darren1998s** [comment]
Not a soft ban. Just loaded it on my device and it works.

**Comment by EmperorChez** [comment]
I dont know then @darren1998s . My bot is working fine right now.

**Comment by sayanils** [comment]
i have the same problem pokestops and so are working but i didnt catch 1 pokemon

**Comment by Mindiocoss** [comment]
Same problem here. It wouldnt actually catch the pokemon unless I through a razzberry first.

**Comment by darren1998s** [comment]
Ok my issue is fixed by a fresh install of the latest build. My guess is that there is still some old interactions with the old files present in the old folder.

**Comment by EmperorChez** [comment]
@darren1998s problem solved. please close then :)
