### ISSUE TITLE
Can't find IV filter and It just transfer my 100% perfect Magikarp 

### ISSUE THREAD

**Issue by HumphreyBao** [Ar1i/PokemonGo-Bot#147]
![788119866297842310](https://cloud.githubusercontent.com/assets/20715304/17235268/bd215202-550d-11e6-8b0d-2700cf60e281.jpg)

**Comment by Ar1i** [comment]
RIP. Its in the Gui m8

**Comment by sufficey** [comment]
I've never felt this bad for somebody in my life.

**Comment by kuan098760** [comment]
^agree..... dam son!!!! my condolences
