### ISSUE TITLE
Bot has major issue - Transfers (ALL) Pokemon

### ISSUE THREAD

**Issue by OfficialMT22** [Ar1i/PokemonGo-Bot#1470]
Its transferring all my pokemon even my best cp. All settings are on default

**Comment by Logxn** [comment]
PLEASE DO STOP ALL BOTS

**Comment by xJustx** [comment]
We know the problem. Sorry!
Ar1i and Logxn are working on it!

**Comment by OfficialMT22** [comment]
Lost alot of my best, but its ok glad you guys are working on it

**Comment by MarTiniiii** [comment]
Just disable transfer and you can farm =)
Great work btw.

**Comment by xJustx** [comment]
It's fixed now. Please download the newest version!
