### ISSUE TITLE
Alle Pokemons werden transferiert 

### ISSUE THREAD

**Issue by jk6046** [Ar1i/PokemonGo-Bot#1471]
Ich habe in den Einstellungen angeben, dass es maximal 2 Duplikate geben soll. Der Bot hat jetzt einfach jedes (!) meiner Pokemon "gelöscht"!

**Comment by orlyorly** [comment]
bei mir gottseidank nicht, er hat zwar echt viel weggeschickt, aber die über 1000WP hat er behalten wie er sollte

**Comment by xJustx** [comment]
It's fixed now. Please download the newest version!
