### ISSUE TITLE
Transfered all of my pokemon

### ISSUE THREAD

**Issue by RoxasFiesta** [Ar1i/PokemonGo-Bot#1472]
So i started the bot and it simply log in like the basic stuff and then it started to transfer all of my pokemon no matter which cp or IV

**Comment by xJustx** [comment]
We know the problem. Please stop your Bot. Sorry!
Ar1i and Logxn are working on it!

**Comment by RoxasFiesta** [comment]
RIp 2k lapras xD

**Comment by RoxasFiesta** [comment]
its cool its a bot smt like this would happen anyway someday better now then later =b

**Comment by Guiillee191** [comment]
if you put the option auto transfer out it's working fine, and u can wait until it's fixed

**Comment by itsforscience** [comment]
Yupp, that happened. Lol. 

Oh well user beware. Regardless - thank you so much for your hard work. I wouldnt have gotten those pokemon anyways if it weren't for you.

**Comment by xJustx** [comment]
It's fixed now. Please download the newest version!
