### ISSUE TITLE
Disable transfering pokemon

### ISSUE THREAD

**Issue by xJustx** [Ar1i/PokemonGo-Bot#1473]
Currently the bot is transfering all your pokemon if you enabled to transfer pokemon.
Ar1i and Logxn are working on it! Sorry!

**Comment by kalcheat** [comment]
Mine does not

**Comment by MarTiniiii** [comment]
You can just disable transfer.
Working great for me.

**Comment by globsch** [comment]
no problem here

**Comment by delokalizator** [comment]
transfers seems to be a problem, but other parts work quite properly

**Comment by LemuelKL** [comment]
It is kinda hilarious.

**Comment by NidiKea** [comment]
AAAAAAH der hat  mir alle Pokemon verkauft so ein Sh.....

**Comment by olsig** [comment]
How come when I click the "Console" the previous version worked but this one says "The parameter is incorrect"? Is there a password to input into the cert file?
