### ISSUE TITLE
What about the Softban Unban Method?

### ISSUE THREAD

**Issue by TheShade1337** [Ar1i/PokemonGo-Bot#1476]
Is the Special 1337 Unban method working fine? cause as far as i know travling from Germany to New york results in a soft ban. But as soon i teleported from Germany to California there were no signs of Softban at all. Im a lil bit confused ^^

**Comment by NaaTiiVee** [comment]
If you ever get a Softban, simply go in your Pokemon Go App, go to the nearest Pokestop. Press it(Go in it) then spin it. Go out. <- repeat this 40x

**Comment by xJustx** [comment]
It's working fine currently. If not, please open a new issue.
