### ISSUE TITLE
Config ?

### ISSUE THREAD

**Issue by niikooartz** [Ar1i/PokemonGo-Bot#148]
hab grad den GUI auf gemacht und es ist keine config mehr geladen :o ohwohl die configs im ordner sind ^^

http://prntscr.com/byvol4

alles leer :c

**Comment by Ar1i** [comment]
Erstell einen Configs Ordner und pack dort deine jetzigen Configs rein, wenn er diese Laden soll.

**Comment by niikooartz** [comment]
perfekt danke :3
