### ISSUE TITLE
WARNING STOP BOT ( POKEMON TRANSFER ERROR)

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1480]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462691/f67bd128-5cbd-11e6-8197-ba0606cccf23.png)

**Comment by ruubs11** [comment]
i can confirm! i lost all my pokemon *crying out loud* haha

**Comment by Kranios** [comment]
all mine is already gone but it doesnt matter i had like 600cp pokemons so i don't really care this is not my original account. But i am happy that the bot is working so i will continue using it. Big love to all that made this happend <333333

**Comment by Wi1dHunt** [comment]
hufftt.... luckily i choose to patient and wait for victim :+1:

**Comment by xJustx** [comment]
Please disable transfering pokemon.
Ar1i and Logxn are working on it!

**Comment by Midnlght** [comment]
Worked completely fine for me just as always, but just to be safe ill stop it. thanks for the heads up!

**Comment by Wi1dHunt** [comment]
@xJustx then if we disable transfer pokemon it will work well?

**Comment by AriahVitae** [comment]
http://hpics.li/d369993

Work 100% like this... Just disabled all transfer.

**Comment by xJustx** [comment]
@Wi1dHunt Yep. If it's fixed you can re-enable it.
