### ISSUE TITLE
I dont know how to make this update//plshelp

### ISSUE THREAD

**Issue by bokepall** [Ar1i/PokemonGo-Bot#1481]
I know I'm pathetic but I really dont have any idea how I make this update work? My friend gave me the last build so I didnt have to download it by myself. Can somebody tell me simply how I make it work :s. Or if I just remove the bot and download it again will it do the same and how I do it

**Comment by sayanils** [comment]
download again

**Comment by velfisadri** [comment]
download and click on console thats it

**Comment by eNNj0y** [comment]
where can i find the newest download ?

**Comment by olsig** [comment]
When I click console, it says the parameter is incorrect?

**Comment by darren1998s** [comment]
@olsig which parameter. Check your login details again
