### ISSUE TITLE
Download..

### ISSUE THREAD

**Issue by eNNj0y** [Ar1i/PokemonGo-Bot#1482]
Hallo, bin neu hier..
Verstehe nicht ganz wo ich den Bot hier downloaden kann & wie ihn dann starte.. Habe mir den "Master-zip" runtergeladen aber da ist ja keine "Anwendung" dabei, die den Bot startet oder bin ich blöd? ^^

& dann noch die Frage, funktioniert der Bot jetzt oder nicht ? 
Lese ja fast nur noch, dass er nicht funktioniert..

Mit freundlichen Grüßen

eNNj0y! :)

**Comment by xJustx** [comment]
Du musst dir "Builds Only" herunterladen.
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
