### ISSUE TITLE
Bot geht bei mir nicht

### ISSUE THREAD

**Issue by dave13364** [Ar1i/PokemonGo-Bot#1483]
hab den bot gestartet aber er findet einfach nix

**Comment by Leak1337** [comment]
Tolle Fehlermeldung !

**Comment by xJustx** [comment]
Ändere mal deine Location zu einem anderen Ort.

**Comment by dave13364** [comment]
er sagt mir das er keine pokestops findet und auch keine pokemon?

**Comment by dave13364** [comment]
hab den bot neu runtergeladen dann ging er wieder danke

**Comment by xJustx** [comment]
perfekt!
