### ISSUE TITLE
It's transfering everything 

### ISSUE THREAD

**Issue by RogelioEV** [Ar1i/PokemonGo-Bot#1484]
Testing in a new acount, the bot catches a pokemon and inmediatly transfers. Doesn't care about the max duplicate pokemons

**Comment by xJustx** [comment]
We know the problem. Please disable transfering pokemon. Sorry!
Ar1i and Logxn are working on it!

**Comment by ruubs11** [comment]
i can confirm, i did run the bot, went to the toilet, came back, all my pokemon are gone haha

**Comment by pikaiskawai** [comment]
its a new api lets wait for them to fix the bugs :+1:

**Comment by RogelioEV** [comment]
Yeah, I'm not angry or something, just testing to informs. Thanks @xJustx, take your time :)

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462712/af21cffc-5cbe-11e6-98c8-974b3d0e1208.png)

**Comment by xJustx** [comment]
Yeah..  you don't have to stop your bots. If you disable transfering pokemon, all is working fine ^^
