### ISSUE TITLE
Don't captcha pokemons !! Only pokestop

### ISSUE THREAD

**Issue by pedromaia1234** [Ar1i/PokemonGo-Bot#1485]
Only pokestop's , why don't captcha pokemons?

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462694/2bb81d7e-5cbe-11e6-8fa1-ab4325cb6769.png)

**Comment by b3shoy** [comment]
#1469 
Do a clean Installation, it worked with others AFAIK.

**Comment by xJustx** [comment]
^
