### ISSUE TITLE
Cannot find pokestops

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#1487]
![screenshot_1](https://cloud.githubusercontent.com/assets/20720517/17462707/b32d64fc-5c6a-11e6-857f-1799ae4b44f5.png)

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462717/d3988682-5cbe-11e6-8a27-c5dc3557852e.png)

**Comment by SpecialOOps** [comment]
Stop with that @pokerave that's not the same bug !

**Comment by radoyx** [comment]
same problem here :/ how can i fix that?
