### ISSUE TITLE
PGO Api Found!

### ISSUE THREAD

**Issue by iridiumkills** [Ar1i/PokemonGo-Bot#1488]

**Comment by iridiumkills** [comment]
But bot is still broken :(

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462714/c40af132-5cbe-11e6-899c-94c3d93d65db.png)

**Comment by iridiumkills** [comment]
I noticed that after running it momentarily, anyways, since there's still the source code for an earlier version, we could probably just edit that and change the APIs

**Comment by in5an1ty** [comment]
yes. bugs, it transfered my dragonair :(

**Comment by xJustx** [comment]
It's fixed! Please download the newest version and it will work fine.
Sorry for the problems!
