### ISSUE TITLE
POKEMON ARE GONE

### ISSUE THREAD

**Issue by LLorDPaulus** [Ar1i/PokemonGo-Bot#1489]
I started the bot.... and it transfered all my pokemon....

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462721/fa962ca8-5cbe-11e6-835c-bc13b7e0f508.png)

**Comment by xJustx** [comment]
We know the problem. Please disable transfering pokemon. Sorry!
Ar1i and Logxn are working on it!
