### ISSUE TITLE
[REQUEST] Show XP gained

### ISSUE THREAD

**Issue by Knedex777** [Ar1i/PokemonGo-Bot#149]
Hey, i would love to know if it's possible to see how many xp we gained, for exemple:

[XX:XX:XX] We caught a Eevee with CP 436 (48% perfect) using a ITEM_POKE_BALL (XP Gained: +210XP)
[XX:XX:XX] Transfer Eevee with 436 CP (48 % perfect) (Best: 652 CP) (XP Gained: +00XP)
And same for an evolution :D

**Comment by Ar1i** [comment]
evolution is already showing. adding if we caught a pokemon
