### ISSUE TITLE
Total Item Display 

### ISSUE THREAD

**Issue by Ncktoriouz** [Ar1i/PokemonGo-Bot#1490]
Bot is only showing a max of 298/600 items. I do have Upgraded storage and not lost items as far as I know, only the value shown is not the value that's is actually there.

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462734/5f59a5d4-5cbf-11e6-83ff-6dde26c64555.png)

**Comment by b3shoy** [comment]
Maybe you can open the game and double check on everything, if it's not the case; stop the Bot for now.

**Comment by Ncktoriouz** [comment]
I know the common problem thanks pokerave, I already disabled poketransfer item recycle is runnng fine,  Like I said this issue has been checked I have 590 Items on the phone, Im only saying the Display value in the script / prompt is not correct :) but thx again

**Comment by b3shoy** [comment]
@Ncktoriouz Oh, my bad, I didn't understand it like that, welcome anyways :smile:

**Comment by Ncktoriouz** [comment]
Oh never a problem, I already lost my pokemon a week ago since first use lol. just trying to add up
