### ISSUE TITLE
FAIL ?

### ISSUE THREAD

**Issue by eNNj0y** [Ar1i/PokemonGo-Bot#1491]
Habe den Bot gestartet..
& er hat einfach ALLE meine Pokemons transferiert..

Was ist da jetzt los ?

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462735/672f6be0-5cbf-11e6-9da0-0ed036421cea.png)

**Comment by xJustx** [comment]
Es ist nun gefixxt. Tut mir leid!
Lade dir einfach die neuste Version herunter und alles sollte wieder funktionieren!

===========

It's fixed! Please download the newest version and it will work fine.
Sorry for the problems!

**Comment by AnusRandalus** [comment]
Isn bug, sind weg weil in der Setup Check box transfer aktiviert war

**Comment by jmo93** [comment]
bei mir kommt die Fehlermeldung: failed to evolve... er versucht zu entwickeln obwohl zu wenig bon bons

**Comment by xJustx** [comment]
@jmo93 Macht bitte kurz ein neues issue, sonst kommen wir durcheinander. Danke!
