### ISSUE TITLE
Why is this error occurring for me?

### ISSUE THREAD

**Issue by Sjnez** [Ar1i/PokemonGo-Bot#1495]
Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462767/2fbdb40e-5cc0-11e6-912e-e94d295e71dc.png)

**Comment by b3shoy** [comment]
Try downloading the latest build, updated 9 minutes ago.

**Comment by xJustx** [comment]
@pokerave It's okay. It's working again. Please don't post this anymore!
