### ISSUE TITLE
All pokemon catches still 420xp, which doesn't match this patch, would this be an issue?

### ISSUE THREAD

**Issue by mydonny1986** [Ar1i/PokemonGo-Bot#1500]
Would this be an issue? Its max to 220 in this patch..unless you get the bonus xp every time which is not possible..

**Comment by Minzaa** [comment]
For me it's 210xp every catch, which is still a problem because only curve ball bonus is still present? so max xp per catch without lucky egg is 110, this is very suspicious?

**Comment by Minzaa** [comment]
@Ar1i 
Btw thanks for much for the hardwork! However i think this is fairly important in making the automation realistic and undetectable, please have a look when you're free
