### ISSUE TITLE
Error reloading Pokemon list : BadAuthentication

### ISSUE THREAD

**Issue by NiowGo** [Ar1i/PokemonGo-Bot#1501]
![bad](https://cloud.githubusercontent.com/assets/20826867/17462797/59ffff86-5cb8-11e6-9f2c-6007ca30a48d.PNG)

**Comment by pokerave** [comment]
bad auth wrong password anyway...

![damn](https://cloud.githubusercontent.com/assets/20603254/17462800/cc9c744a-5cc0-11e6-81bc-931afb7c166b.png)

**Comment by Logxn** [comment]
Show fullscreen please

**Comment by Logxn** [comment]
This is fixed already

**Comment by NiowGo** [comment]
Error Me, excuse me ^^, I think I have good exclaims password

**Comment by NiowGo** [comment]
Thanks You
