### ISSUE TITLE
Dont know if its everyone or just me.

### ISSUE THREAD

**Issue by Inforcer25** [Ar1i/PokemonGo-Bot#1502]
If you guys can just say if it finds pokestops for you pls do so. I still get the same error when the API was updated. It cant find any pokestops. Is it just me?

**Comment by zygis278** [comment]
Same

**Comment by DevilBlyat** [comment]
I didn't take the last build because it contains some errors. I took the one just before.

**Comment by Inforcer25** [comment]
Im closing just because it seems like its not only me. I got my answere thx
