### ISSUE TITLE
Wer versteht den Fehler ?..

### ISSUE THREAD

**Issue by eNNj0y** [Ar1i/PokemonGo-Bot#1504]
![unbenannt](https://cloud.githubusercontent.com/assets/20887831/17462798/5a4a6b70-5cb8-11e6-995b-db4dfcd4a29a.jpg)

Was ist da los ?
Warte jetzt schon etwas.. habe ihn auch schon mehrmals neugestartet.. Daten sind korrekt..

**Comment by dadaxd** [comment]
bei mir findet er keine pokestops...kp -_-
