### ISSUE TITLE
Why do all encountered pokemons gets away from me?

### ISSUE THREAD

**Issue by iilkercetinn** [Ar1i/PokemonGo-Bot#1505]
When my bot encounters pokemon, this pokemon always gets away from me.

https://s8.postimg.org/wn8mpmjz9/qeqwe_Ads_z.png

How could I fix this?

**Comment by zygis278** [comment]
softban?

**Comment by iilkercetinn** [comment]
I was unbanned. You can see it half of the pic.

**Comment by royhubb** [comment]
it says "probably unbanned you", so it could be you still got the softban

**Comment by FleischPe1tsche** [comment]
have the same problem , I farm in England and today I was not otherwise online on cell phone

**Comment by TheDavenger** [comment]
Same issue here

**Comment by TheShade1337** [comment]
i dont have that issue so far, after the system unbanned me i can farm pokestops and catch pokemon but i dunno if i can catch them on my mobile... :S

**Comment by sanruan2206** [comment]
Same here, can't catch any pokemon, i'm not softbanned

**Comment by nabi11** [comment]
@iilkercetinn you are softbanned. look you dont farm the pokéstop ^^
