### ISSUE TITLE
FIX -> ERROR REOLADING POKEMON LIST: out of memory

### ISSUE THREAD

**Issue by johnykkk** [Ar1i/PokemonGo-Bot#1506]
ERROR RELOADING POKEMON LIST: out of memory 
and this not transfert pokemon :/
WHAT can i do!
thanks for help

**Comment by Logxn** [comment]
Nothing, just ignore it :b

**Comment by johnykkk** [comment]
but this is error! bot isnt trasfering pokemon

**Comment by butcha** [comment]
I am seeing the same error on a PTC account that has bought extra space for pokémons,
dunno if that can be a why.
A google login with no extra space does not get the error.

**Comment by johnykkk** [comment]
FIX problem thnks! (i downloaded again (updated))
