### ISSUE TITLE
Transfering

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#1508]
There is a bug, that is still even after your hot fix, transferring all pokemon, even after configuration.

**Comment by Ar1i** [comment]
Uhm you using the newest version?

**Comment by Ar1i** [comment]
Cause you are the only one atm

**Comment by TheShade1337** [comment]
^^

**Comment by BEKKNQV** [comment]
Everything ok with newest version, you should update.

**Comment by xJustx** [comment]
@AKBlizzard Is it working now fine?
