### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by Knedex777** [Ar1i/PokemonGo-Bot#151]
When we visit a pokestop, it doesn't show if we got eggs :/ (see pic)
![noeggs](https://cloud.githubusercontent.com/assets/20714882/17235683/57a675f2-5543-11e6-8a33-b23b7259f6ee.png)

**Comment by Ar1i** [comment]
You probably didnt got any egg :( Its not a bug, but i will edit that message.

**Comment by Knedex777** [comment]
Ow okay, i never find eggs xD

**Comment by Ar1i** [comment]
Try it please, just pushed Update. And make a screen of the next one please!

**Comment by Knedex777** [comment]
It shows an "/" 
![neweggs](https://cloud.githubusercontent.com/assets/20714882/17235863/ab7ecfca-5544-11e6-9ba8-cc94f90b0c2d.png)

**Comment by Ar1i** [comment]
Good, so it works! Thank you!

**Comment by Knedex777** [comment]
No, thanks to YOU ! ahah :D
Wouldn't be easier to the user to put "0" instead of "/" ?
