### ISSUE TITLE
Viele rote Error-Nachrichten

### ISSUE THREAD

**Issue by PackChoi** [Ar1i/PokemonGo-Bot#1512]
![screenshot_1](https://cloud.githubusercontent.com/assets/20888138/17462814/c952f71c-5cb8-11e6-90f4-63002f1519b1.png)

Ist das bekannt?

**Comment by phoeniXX1337** [comment]
Hab ich auch :(

**Comment by xJustx** [comment]
Sollte am falschen Passwort liegen. Überprüft das bitte nochmal!

**Comment by phoeniXX1337** [comment]
Hab es Überprüft, sogar mehr fach.. kein Erfolg :/

**Comment by PackChoi** [comment]
Vielleicht wurde der Acc gebannt?
