### ISSUE TITLE
error while startin

### ISSUE THREAD

**Issue by phoeniXX1337** [Ar1i/PokemonGo-Bot#1513]
When i Start the Bot the following error comes:

Error reloading Pokemon list: Eine ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.LoginFailedException" Wurde ausgelöst.

pls hellp

**Comment by SpecialOOps** [comment]
Wrong password perhaps.

**Comment by phoeniXX1337** [comment]
Did Everything right lol :/
