### ISSUE TITLE
Wrong information/ fail to catch many pokémon

### ISSUE THREAD

**Issue by nabi11** [Ar1i/PokemonGo-Bot#1516]
So in first my account was lvl 30 and the information display i'm lvl 1 on a PTC account and second the bot fail to catch many pokémon and using pokéball but i don't have any pokéball in my bag. Here a screen for you
![ss 2016-08-07 at 03 59 38](https://cloud.githubusercontent.com/assets/20888144/17462823/f3aab57c-5cb8-11e6-9640-282a26c3507d.png)

**Comment by nabi11** [comment]
no, look i can get the pokéstop and some pokémon

**Comment by TheDavenger** [comment]
I've got the same issue

**Comment by royhubb** [comment]
Weird, it is doing fine for me..

**Comment by DrHPain** [comment]
Just don,t throw away the simple pokeballs. Seems that the bot can only catch with pokeballs and not with hyper or superballs. works for me.

**Comment by Kaimera** [comment]
Yesterday it worked fine, this morning i got this problem too, cannot catch any pokemon, they all got away but i still receive items and EXP from pokestops, anyone can take a look at this issue? Thanks
