### ISSUE TITLE
Inventory Full?

### ISSUE THREAD

**Issue by TouchTheSkies** [Ar1i/PokemonGo-Bot#1518]
Can't get anymore items from Pokestop spins, and I've never had to expand my inventory before with the bot so..is this an error or should I just go ahead and expand my inventory to fix it?

**Comment by b3shoy** [comment]
Configure your Inventory in the second tab, specify a number for each item that yow wanna keep.

**Comment by johnykkk** [comment]
same problem
ERROR REOLADING POKEMON LIST: out of memory and not trasfer

**Comment by TouchTheSkies** [comment]
I have configured it, but it still gives me the same error and won't collect anymore items when I'm positive my inventory is not full at all.

**Comment by johnykkk** [comment]
the fix problem! download again my friend is updated

**Comment by testo4life** [comment]
same here showing 380/350 items constantly !

**Comment by TouchTheSkies** [comment]
I'm already on the latest version., so that's not the issue either >.<

**Comment by b3shoy** [comment]
@Ar1i

**Comment by TouchTheSkies** [comment]
Still getting the same thing every time. Always says 'InventoryFull?'
