### ISSUE TITLE
Request notify rare pokemon / high iv

### ISSUE THREAD

**Issue by FelipeMallmann** [Ar1i/PokemonGo-Bot#152]
Could you do, when we get a high pokemon iv or rare pokemon, create a file log and write the pokemon infos?

I would help us a lot, because if we do not watch the screen we cant see what pokemons we got.

Thanks!

**Comment by Ar1i** [comment]
Their is a list which rebuilds at every restart, for excel.

**Comment by FelipeMallmann** [comment]
Thank you!
