### ISSUE TITLE
Pokemon Go Nest

### ISSUE THREAD

**Issue by YakuzaR** [Ar1i/PokemonGo-Bot#1520]
Not really a issue, but do u know any good Nests or do your know a Website, that Show all of them?

Kennt ihr eine Website, die die Pokemon Nester zeigt oder kennt ihr einige? 

btw i mean the Nests after the  Change..

**Comment by xJustx** [comment]
Sorry - kann ich hier gerade nicht offen lassen.

**Comment by BigManTyrone** [comment]
charmander nest in park in milaan
