### ISSUE TITLE
no catch

### ISSUE THREAD

**Issue by Freeze33980** [Ar1i/PokemonGo-Bot#1525]
all pokemon not catch 
![sans titre 22](https://cloud.githubusercontent.com/assets/20841222/17462844/8c5a3662-5cb9-11e6-9f03-d736b610eff5.png)

**Comment by xJustx** [comment]
Can you make again a screenshot? I can see like nothing - sorry.

**Comment by EmperorChez** [comment]
@Ar1i  Having the same problem after update.

**Comment by Minzaa** [comment]
For me it's the opposite, im catching every pokemon i encounter, this is very unrealistic?

**Comment by Freeze33980** [comment]
![sans titre 22](https://cloud.githubusercontent.com/assets/20841222/17462865/09f019a2-5cba-11e6-86e2-ac966cadd8b4.png)

**Comment by Freeze33980** [comment]
you can zoom the screen for read

**Comment by Minzaa** [comment]
Also is the probability the probability of successful catch?
eg. Encountered Weedle CP 218  IV 20% Probability 31%

**Comment by Scanda85** [comment]
Here the same... i don't catch any pokemon
