### ISSUE TITLE
soft ban?

### ISSUE THREAD

**Issue by ankhmok** [Ar1i/PokemonGo-Bot#1526]
![pokemonbot](https://cloud.githubusercontent.com/assets/20844068/17462835/8bd3570a-5ceb-11e6-935b-cf23cf3e10b2.png)

first of all thankyou for this amazing Bot on the other hand am i got soft ban? all the pokemon got away

**Comment by ankhmok** [comment]
sorry for my poor english, i come from Hong Kong so that bot will show a little bit chinese.

**Comment by Freeze33980** [comment]
no pokestop give you xp ^^ not soft ban

**Comment by ankhmok** [comment]
just bad luck? so poor

**Comment by xJustx** [comment]
@ankhmok Please try to delete your LastCords-File and change your location and try it again.

**Comment by ankhmok** [comment]
try it now, thankyou again

**Comment by EmperorChez** [comment]
@xJustx where is the LastCords-File located at?

**Comment by ankhmok** [comment]
finding, also want to know where it is

**Comment by xJustx** [comment]
@EmperorChez You can locate the lastCords-File in the "Configs"-Folder.

**Comment by sharaoki** [comment]
I had this issue, but fixed it by changing the number of maximum pokeballs to >0 (I made it 30). It seems the program is trying to throw pokeballs even when you don't have any...

**Comment by ankhmok** [comment]
![pokemonbot2](https://cloud.githubusercontent.com/assets/20844068/17462882/d2588064-5cec-11e6-9350-d25b3e5e8356.png)

sorry cant find, im so fool.../_\...

**Comment by EmperorChez** [comment]
^ that might be the reason tbh.

**Comment by ankhmok** [comment]
@sharaoki  thankyou reset it now

**Comment by FleischPe1tsche** [comment]
"I had this issue, but fixed it by changing the number of maximum pokeballs to >0 (I made it 30). It seems the program is trying to throw pokeballs even when you don't have any..."

thank you thats was the problem

**Comment by Logxn** [comment]
Also it could be, that your speed is simply to high.
Try changing it to 50km/h or smth like that

**Comment by ankhmok** [comment]
![pokemonbot3](https://cloud.githubusercontent.com/assets/20844068/17462903/dde3d7d4-5ced-11e6-9fd6-2bdff9696106.png)

here is my setting, i think im just deeply bad luck lol

**Comment by EmperorChez** [comment]
@ankhmok have pokeballs from 0 to 50. that will fix it.
