### ISSUE TITLE
Auto Incubate and PTC problems

### ISSUE THREAD

**Issue by Kurix777** [Ar1i/PokemonGo-Bot#1527]
Hello Guys,

The Bot doesn't Auto Incubate ( in the GUI it's checked )

and only on my PTC Accounts i get much errors in Logic.cs 124
and there
![image](https://cloud.githubusercontent.com/assets/20888180/17462852/b5dd9f2e-5cb9-11e6-8e6e-55256bbce61b.png)

on my Google Account it all works Fine

**Comment by Ar1i** [comment]
Auto Incubate is atm not active.

**Comment by Kurix777** [comment]
And i get to much Player Stats Update all 10-15 seconds is that normal ??
