### ISSUE TITLE
"Can't find any pokestop in a range of 8000 meters" ..

### ISSUE THREAD

**Issue by Xemory** [Ar1i/PokemonGo-Bot#1528]
The problem is on the title ;)
Thanks in advance

**Comment by royhubb** [comment]
Have you downloaded the newest version of the bot?
Then this problem should be solved

**Comment by xJustx** [comment]
Do you have the newest version?

**Comment by Xemory** [comment]
Yes, I have the newest version ;)
Th bot worked just few minutes ..

**Comment by xJustx** [comment]
Please delete your "LastCords"-File in your "Configs" Folder, change your location and try it again.

**Comment by Xemory** [comment]
it works ! Thank you for your help
