### ISSUE TITLE
[Question] Incubators

### ISSUE THREAD

**Issue by CruSherFL** [Ar1i/PokemonGo-Bot#1529]
What exactly is "use basic incubators"? 
If selected, the bot will only use the unlimited incubators, if deselected, the bot uses all incubators it has?

**Comment by Minzaa** [comment]
I believe logically this is the case

**Comment by Praxthisnovcht** [comment]
Yes, if he lies he uses only the incubator by default if you uncheck it will use all available incubator

**Comment by downspath** [comment]
some people dont speak that good english, @Minzaa

**Comment by CruSherFL** [comment]
For me all Incubators are kinda 'basic' - maybe in the future you'll get a 'better' Incubator where you i.e. need 50% of the distance to walk. :)
I just want to be 100% be sure, because I don't know if I still have to log in to the game on my phone to manually place the incubators.
Do I get a telegram for incubated eggs?

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
