### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NezaelHD** [Ar1i/PokemonGo-Bot#1530]
there is a bug who write me this 

Exception: System.InvalidOperationException: La séquence ne contient aucun élément correspondant.
   à System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 58
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__13.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 175
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__16.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 336
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 125
Sorry it's in french
Thanks

**Comment by pokegoplayer** [comment]
Maybe becuase you set it to low amount like 10 or 20 pokeballs

**Comment by evrine** [comment]
same me, double error now ziele 111 and 125, last time was ziele 110

**Comment by Ar1i** [comment]
can you provide your config?

**Comment by NezaelHD** [comment]
Windows 10 x64
Nvidia GTX 960 PNY
SSD Transcend 128go
1to Seagate barracuda
8go ram
