### ISSUE TITLE
Can't open more than 2 bots from the same exe

### ISSUE THREAD

**Issue by Melancolie** [Ar1i/PokemonGo-Bot#1533]
I just started to multibot from the same exe. Is this a bug or does it support only 2 accounts at a time?

**Comment by iilkercetinn** [comment]
copy your latest build file somewhere else. then open different exes from these files.

**Comment by xJustx** [comment]
^

**Comment by Yummster** [comment]
I use separate folders for each bot, that way you can have configs tailored to each bot.
