### ISSUE TITLE
[Question] Which is your Default Location. 

### ISSUE THREAD

**Issue by cristianst** [Ar1i/PokemonGo-Bot#1535]
Hi guys! Just out of curiosity: since the bots starts catching pokemon for you automatically.. IMO the Starting Point is pretty important., because if you start in a village you will probably find less and "poor" pokemon..

My question for you is : Which one is your "default location"( starting point.). A big city? A lake? A place where u find rare pokemons?

**Comment by whitemouse14** [comment]
dude,
try Santa Monica, that's my starting point :)

**Comment by cristianst** [comment]
@xJustx why u close it ? ive seen a couple of questions and they are not closed.

**Comment by xJustx** [comment]
Sorry but it's not a issue. Currently we can't need it here.
