### ISSUE TITLE
Ask about arc bar below CP number

### ISSUE THREAD

**Issue by bertojk** [Ar1i/PokemonGo-Bot#1536]
I don't know how important is IV but imho, arc bar below CP is important. I think it can be showed since I am manually transfer with considering the CP than IV (although I know a little bit IV is like the quality of pokemon). Maybe you can add an equation to calculate the maximum CP from current CP and length of white arc bar. So if you can, please change CP which show only current_CP with current_CP/max_limit_CP. Thanks

**Comment by mydonny1986** [comment]
high IV means high CP(well when you level it up, it will have higher cp then low IV pokemons even their arc bar showing at the same place), the arc bar is only the indication between your player level and pokemon level.

**Comment by bertojk** [comment]
So you mean when I upgrade my pokemon then automatically pokemon IV is decreasing?

**Comment by mydonny1986** [comment]
no, IV never changes, so for example if you have two charmander, one with 90% IV and the other with 20% , when they are at the same level ( arc bar at the same place), 90% would have higher CP then the 20%. so the arc bar can only show you how times left you can power up you pokemon, bit not how good your pokemon is, only IV will
