### ISSUE TITLE
GNU GPL3.0

### ISSUE THREAD

**Issue by StevasaurousREX** [Ar1i/PokemonGo-Bot#1537]
You are using Rocket API which is GNU GPL 3.0
https://www.gnu.org/licenses/gpl-3.0.en.html

`To protect your rights, we need to prevent others from denying you these rights or asking you to surrender the rights. Therefore, you have certain responsibilities if you distribute copies of the software, or if you modify it: responsibilities to respect the freedom of others.

For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.`

Put something similar in a comment to make sure its seen posting here. Ill give you 30 minutes till I report this repo to Github and let them handle your copy write infringement.

**Comment by Ar1i** [comment]
You want to know why we dont provide it? Cause of this: https://www.pokecrot.com/ he is stealing and pushing it out without source too.. soo without source he cant do shit.

**Comment by Logxn** [comment]
Also we are providing credits, and anyone can follow the link to the RocketAPI and can view the code for themselfes ;)

**Comment by StevasaurousREX** [comment]
Not how GNU GPL 3.0 works. Ill go ahead and report it now.

**Comment by Ar1i** [comment]
Then do it, idk whats your problem is. Probably your the pokecrot guy. lmao
