### ISSUE TITLE
Error loading my pokemon list

### ISSUE THREAD

**Issue by ReapeX** [Ar1i/PokemonGo-Bot#1538]
hey guys, big fan of your work and been using the bot for a while now.
I got some kind of problem now tho. I'm using the same settings as before but it tells me theres an error loading my pokemon list. Please tell me what I'm doing wrong ^^

**Comment by Aiwoma** [comment]
error reloading pokemon list: out of memory

**Comment by whitemouse14** [comment]
yes me too,
yes bot keep saying -->  error loading pokemon list: needs browser

**Comment by testo4life** [comment]
use clean install dont copy old folder should work !

**Comment by whitemouse14** [comment]
@testo4life please do me a favor to show me.the detail of yr instruction
Appreciate for your great understanding dude
