### ISSUE TITLE
[Request] List of pokemon in real time

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#154]
Is it possible to add the ability to view all the pokemon that we have real-time in a list or array?

This will avoid closing the application to go check on her phone ..

Ex ;

Name / cp / %iv

Thank you

**Comment by Ar1i** [comment]
Sounds like a great idea, but how do you want to show it exactly?

**Comment by mantoniolli** [comment]
with the same program for phone but only with the list, or with telegram, we send a message and receive the list

**Comment by stormlolz** [comment]
I havent the exact solution but :

I think like that 

Updating a DB in each caught pokemon .

An independent executable reads the database and displayed when the user requests ?

**Comment by andrekkn** [comment]
Or make it so it send the list by message every hour or so
