### ISSUE TITLE
problem with location between 2 pokéstops

### ISSUE THREAD

**Issue by sylva91** [Ar1i/PokemonGo-Bot#1542]
Hi,
I have, let's say 2 pokéstops at positions X and Y that have no more than 1.4Km distance beween them.
When i put the robot near one of the positions with a  move radius of 5000 meters, it only sees the one near it. when i put it in the middle, it doesn't see any.

what's the proper method to use ?

**Comment by downspath** [comment]
The bot cant see that far, it just says he can move 5000m from your set coordinates away
