### ISSUE TITLE
Razz Berry (display) Small issue

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1544]
![print](https://cloud.githubusercontent.com/assets/20603254/17462915/4049e42e-5cc4-11e6-923f-2f05d8e6cf46.png)

**Comment by downspath** [comment]
it only refreshes the razz berry after battle

**Comment by CruSherFL** [comment]
Good thing I hit F5 before posting =) 
![image](https://cloud.githubusercontent.com/assets/12624399/17462928/12f13d22-5cbc-11e6-8126-3983e1927ef0.png)

**Comment by gemgio** [comment]
+1

**Comment by danielalvenstrand** [comment]
Easy fix, just do result.count.toString() on the json object, will probably come in next patch.
