### ISSUE TITLE
Bot Won't start correctly

### ISSUE THREAD

**Issue by noah8915** [Ar1i/PokemonGo-Bot#1545]
![wow](https://cloud.githubusercontent.com/assets/20888259/17462918/9b5d6d12-5c89-11e6-9446-da7378286ecf.PNG)

**Comment by xJustx** [comment]
Please check your password and try it again,

**Comment by pokerave** [comment]
you have the new version? mine works great

**Comment by arjunvegda** [comment]
@noah8915 And also you need to wait for 15 minutes if you are using trainer account.
![image](https://cloud.githubusercontent.com/assets/14841132/17462950/54ff85f2-5c8a-11e6-809d-b4dc40f44a43.png)

**Comment by noah8915** [comment]
I downloaded the latest version, checked my password and made sure that my account wasn't disabled and it's still not working.

**Comment by arjunvegda** [comment]
Same issue with me.
