### ISSUE TITLE
Poketstop with Lure

### ISSUE THREAD

**Issue by wannaD1E** [Ar1i/PokemonGo-Bot#1548]
![2016-08-07_17-26-39](https://cloud.githubusercontent.com/assets/20835223/17462927/6d45e676-5cc4-11e6-99c6-0a4ad2c65fb4.png)
Dont see pokemon around Poketstop with Lure

![2016-08-07_17-24-15](https://cloud.githubusercontent.com/assets/20835223/17462932/92c68932-5cc4-11e6-9dc3-043c5f369e91.png)

**Comment by sunit1998** [comment]
actually the bot works only with incensce and not with lure

**Comment by Ar1i** [comment]
adding that with the lure

**Comment by wannaD1E** [comment]
thx

**Comment by ronnyouxia** [comment]
how to add with lure btw?

**Comment by PippoAe** [comment]
as soon as this is implemented the pokemon/h will skyrocket :O
