### ISSUE TITLE
I don't know if I am on the latest update? I am still stuck at 'No Pokestop within...."

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#1549]
I am pretty sure I extracted into the right files, just like i have before, but it still does not work.

Can someone direct me to the original download and i'll just download that + extract newest update again?

Thanks

**Comment by mydonny1986** [comment]
which one did you download?
did you download with the green button zip file?

**Comment by sunit1998** [comment]
just use the build and dont open the microsoft visual file

**Comment by mydonny1986** [comment]
go to build only ..
you shold get this file: Latest Build - 07.08 15.48.rar

**Comment by sunit1998** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20731094/17462968/3701894c-5cda-11e6-9624-66d12fb01b14.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/20731094/17462969/372a8da6-5cda-11e6-9d45-1c88bd573481.jpg)

**Comment by pokerave** [comment]
https://codeload.github.com/Ar1i/PokemonGo-Bot/zip/master

**Comment by gise88** [comment]
well.. the latest build is 1.0.7.1..

**Comment by mydonny1986** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2007.08%2015.48.rar

**Comment by ronnyouxia** [comment]
how to add lure to find pokemon?

**Comment by bluezerodany** [comment]
does it work? with that file?

**Comment by steezespot** [comment]
thanks mydonny1986

**Comment by bluezerodany** [comment]
Yeah thank you very much
