### ISSUE TITLE
Request - Turkish Translation for GUI and Text

### ISSUE THREAD

**Issue by HaydarOzturk** [Ar1i/PokemonGo-Bot#155]
I noticed a lot of people in Turkey are using your program and we appreciate it very very much. I want to translate the program in Turkish so people could understand without explanation. If  you accept my offer that would be great, If you won't accept it I want to thank you so much for this amazing work!

**Comment by Ar1i** [comment]
Uhm, i will do in some days a language file. Which you can use to Translate then! So we can Support muliply languages!

**Comment by HaydarOzturk** [comment]
I would be glad to do that. Just let me know and I'll be there to help :)

**Comment by stormlolz** [comment]
Yeah need some traduction ! 
Thank you
