### ISSUE TITLE
Where

### ISSUE THREAD

**Issue by kakksa** [Ar1i/PokemonGo-Bot#1554]
Where is the location.cfg now? Cant find it to delete so i can go to china etc

**Comment by Logxn** [comment]
The folder where your console.exe is => Configs => "lastCoords.txt"

**Comment by kakksa** [comment]
Me and friend not have man, i know used to be in configs but it is not there

**Comment by kakksa** [comment]
![image](https://cloud.githubusercontent.com/assets/20825908/17463039/497d7e6c-5cbe-11e6-9a99-4258a6788077.png)

**Comment by kakksa** [comment]
![image](https://cloud.githubusercontent.com/assets/20825908/17463040/545c97dc-5cbe-11e6-962f-940ce6d3ad74.png)
