### ISSUE TITLE
.rar file for download problem??

### ISSUE THREAD

**Issue by lucafry1** [Ar1i/PokemonGo-Bot#1555]
Hello, sorry i am very uneducated with technology and all but when i go to download the bot in the builds only section it is a .rar file and i cant open the bot, cant anyone help? sorry.

**Comment by gise88** [comment]
http://www.7-zip.org/download.html

**Comment by lucafry1** [comment]
wait what do i do once i have 7 zip

**Comment by pokerave** [comment]
unzip the build folder in the main directory run the app

**Comment by gise88** [comment]
7zip can unrar too..

**Comment by mydonny1986** [comment]
use 7zip to extract the file to a folder
