### ISSUE TITLE
NOT ISSUE, A QUESTION!

### ISSUE THREAD

**Issue by gabmanzano** [Ar1i/PokemonGo-Bot#1556]
Guys, how does Snipper works? it gets ban when you go to different places and catch the pokemon?

**Comment by sunit1998** [comment]
just jump to other place click on pokemon and return to ur original place and catch the pokemon u wont be banned that way

**Comment by Logxn** [comment]
No.
It goes in to the encounter screen,
teleports back to your normal location,
catches it.
Tada no ban
