### ISSUE TITLE
Not transferring properly?

### ISSUE THREAD

**Issue by shahroozal** [Ar1i/PokemonGo-Bot#1557]
So after the fix, I setup the bot like so:

![untitled](https://cloud.githubusercontent.com/assets/20831147/17463002/6da117d2-5cbd-11e6-9d72-a595187069e0.png)

But the problem is that now it barely transfer the pokemon and I keep having multiple duplicates:

![untitled1](https://cloud.githubusercontent.com/assets/20831147/17463013/aa83b2cc-5cbd-11e6-97b2-0f111188bbbf.png)

Am I doing something wrong or is it a bug?

**Comment by pokerave** [comment]
uncheck keep evolvable pokemon.

**Comment by Logxn** [comment]
^

**Comment by shahroozal** [comment]
@pokerave thanks :)
