### ISSUE TITLE
[Request] List of localisations

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#156]
You can add the ability to select from a predefined location list?
On the forum you add a list , why not add it to the program?

Thank you

Edit : MAJ of list
(edit the list on the forum, thank to bananajoe)

**# 

- Deutshland :

**

Düsseldorf Girardetbrücke​

Berlin Old Town Spandau : 52,53702300 , 13,20301100​

Aachen : 50.776309, 6.083505 (4Stops)​

Hamburg : 53.5588061, 10.057689399999958 (4 Stops)​

Dortmund : 51.552381, 7.309696​

Koblenz : 50.363425, 7.605247​

Düsseldorf Schloss Benrath : 51.161206, 6.870546 (Magmar)​

Essen Steele : 51.448197, 7.075814​

Serengeti Park (Hodenhagen) : 52.751040, 9.617021 (Kicklee)​

Duisburg : 51.432737, 6.769041 (Bisasam, Shiggy, sogar 1x Turtok)​

Berlin : 52.54553867687206,13.385488986968994 (Bisasam)​

Botanischer Garten, Minden :52.289727 8.907234 ( Hypno, Slimer, Rosana, Schiggiy, Seemon, Kingler, Nidoran (M), Enton, Sterndu, Abra, Quapsel, Nidoran (W), Nebulak, Seeper, Karpador, Tentacha, Paras, Mauzi, Flegmon, Knofensa, Traumato, Smogon, uvm.)​

München Westpark 1-4 Pikatchu(s): 48.1227197,11.5252951

**# 

- Australia

**

Sydney, Australia : -33.859048, 151.213182​
Lilydale, Melbourne : -37.7651298, 145.3509665 (Dratini)​
Brimbank Park, Melbourne : -37.727411806375,144.83374804258 (Kangama)​
Canberra : -35.2899395,149.1305726 (Dratini)​

# **

- United States

**

Boston, MA : 42.343636, -71.08485​
1010 Valley Street, Seattle, WA 98109, USA​
New York Central Park : 40.764871, -73.972722​
Myrtle Beach : 33.714451, -78.877194​
Long Beach : 33.760757, -118.19507​
1313 Disneyland Dr Anaheim, CA 92802​
Long Beach, Cali : 33.761059 -118.196184​
Seattle WA : 47.626680, -122.335884 (sollten Dratinis kommen)​
Memorial Pkwy Minneapolis, MN : 45.030221 -93.319307 (Taubsi, Evoli, Zubat etc.)​
Austin Texas : 30.264215,-97.754544 (Viele Glumandas)​
Hermann Park Houston, Texas : 29.715695,-95.391055 (Ponitas)​
Sun Diego, Cali : 32.712615129552525,-117.1588683128357 (Fukanos)​
Atlanta : 33.976613749641665,-84.57535337540321 (Bisasams)​
Sacramento, USA : 38.554206, -121.238508 (Dratinis)​
890 Beach St, San Francisco, CA 94109 : 37.806398, -122.423551​
Los Angeles : 33.94303952672716,-118.1863260269165 (Sichlor)​
Santa Monica Pier : 34.00939407500961, -118.4973281621933​

**_

- Holland

_**

Bezembrug 157​
Den Helder : 52.936191, 4.726726 (Pantimos)​
Amsterdam : 52.374026242 , 4.8896870380004 (Karpador)​

**# 

- United Kingdom

**

Solihul Brueton park : 52.406730, -1.765572​

**# 

- Italia

**

Piazza Sempione, Milano, Italien : 45.47210, 9.17722 (Sehr viele Glumandas)​

# **

- Japan

**

Shinjuku Gyoen National Park, Tokyo, Japan : 35.684895044528794, 139.70996975898743 (Pikachus)​
Koganei Park, Japan : 35.716205279972726,139.52101830480387​
Setagaya Park, Tokyo, Japan : 35.64173421813652,139.68279361724854 (Dratini)​

# **

- Norwegen

**

Norwegen, Oslo : 59.926453, 10.703065 (Shiggys)​

**# 

- Turkey

**

Sultan Ahmet Camii Latitude: 41.00541 | Longitude: 28.976814

**# 

- France

**

Lyon-Parc de la tête d'or
lat : 45.77889169140457
long : 4.8537468910217285
alt : 176,215682983398
moove radius : 1000m

**Comment by HaydarOzturk** [comment]
Additionally for Istanbul;
Sultan Ahmet Camii Latitude: 41.00541 | Longitude: 28.976814

**Comment by niikooartz** [comment]
München Westpark 1-4 Pikatchu(s): 48.1227197,11.5252951

**Comment by stormlolz** [comment]
I will edit the post later and add all localisation posted here, Thank you

**Comment by stormlolz** [comment]
updated, add :
Turkey/Sultan Ahmet Camii Latitude
Deutshland/München Westpark
France/Lyon Parc de la tête d'or
