### ISSUE TITLE
Important BUG

### ISSUE THREAD

**Issue by ranggirahman** [Ar1i/PokemonGo-Bot#1562]
Update :
- Razzberry display wrong format like this "Thrown ItemRazzBerry. Remaining: { "itemId": "ITEM_RAZZ_BERRY", "coun"
- Wrong items display on my phone is 323, but on bot is 374

**Comment by pokerave** [comment]
you are soft ban.

**Comment by ranggirahman** [comment]
@pokerave but im get exp, why u can say it soft banned ?

**Comment by pokerave** [comment]
because mine works great.

![perfect](https://cloud.githubusercontent.com/assets/20603254/17463077/64b40f44-5cc7-11e6-8b76-31437d290a11.png)

**Comment by ronnyouxia** [comment]
how to catch pokemon at luring pokestop?

**Comment by ranggirahman** [comment]
@pokerave : can u send me a screenshoot from bot setting windows

**Comment by TouchTheSkies** [comment]
I sort of have the same issue. I can catch Pokemon, but get no items at stops, just EXP. It also hasn't said I've been softbanned like it would before so...?...

**Comment by Whoopass** [comment]
You dont get Items when your bag is full. You only get the EXP.

**Comment by tbeng** [comment]
You most likely dont have any pokeballs left and your is full. You can fix that by adjusting the item count in the Items tab and force it to recycle some items to get new pokeballs at the next pokestop.
