### ISSUE TITLE
Exeption at RocketAPI

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#1564]
![execptions](https://cloud.githubusercontent.com/assets/20603254/17463048/da194958-5cc6-11e6-9143-71c6b38516ea.png)

**Comment by emilie253** [comment]
same, even after redownload

**Comment by cristianst** [comment]
same here! but after the exception the bot keeps working normally.

**Comment by pokerave** [comment]
@cristianst yes same here works normally after that.
