### ISSUE TITLE
LastCords

### ISSUE THREAD

**Issue by kakksa** [Ar1i/PokemonGo-Bot#1565]
![image](https://cloud.githubusercontent.com/assets/20825908/17463054/966e1a42-5cbe-11e6-95d0-405f6b5c6985.png)

**Comment by kakksa** [comment]
![image](https://cloud.githubusercontent.com/assets/20825908/17463058/9fa947d0-5cbe-11e6-9853-2946a531579e.png)

**Comment by kakksa** [comment]
Can not find it :/

**Comment by pokerave** [comment]
its in the config folder, config.txt

**Comment by kakksa** [comment]
Okei so just remove the cord then save :) Thanks

**Comment by kakksa** [comment]
But dident work, hm what i am doing wrong, i deleted the cord, and moved to LA, and nothing will happen
