### ISSUE TITLE
Virus???

### ISSUE THREAD

**Issue by InvisibleTouch** [Ar1i/PokemonGo-Bot#1567]
Backdoor.Win32.Extreme......???

<blockquote class="imgur-embed-pub" lang="en" data-id="gla6cKg"><a href="//imgur.com/gla6cKg">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Whoopass** [comment]
Dont use it when u dont trust the Dev's ;)

**Comment by pokerave** [comment]
its there because of the pokecrot guy (maybe its you) lol just kidding.

**Comment by AKBlizzard** [comment]
What does it mean?

**Comment by InvisibleTouch** [comment]
It was only a question and a Inforemark... I trust the devs.... It also can be that the dev hav it on his PC....
It runs on my PC already....  Thats about trusting...
So it can had something to do with the changes where made....

**Comment by Dhannyjsb** [comment]
false positive
