### ISSUE TITLE
Items & Telegram infos

### ISSUE THREAD

**Issue by niikooartz** [Ar1i/PokemonGo-Bot#157]
es werden dauerhaft nur 13 items angezeigt :D da das ja die items sind die vorhanden sind ^^ aber nicht die items die in pokemon oben angezeigt werden :D 

http://prntscr.com/byw4vg

in pokemon selbst habe ich aktuell: 391/450
der bot zeigt nur 13/450 an :D 

__________________________________________________

bei den Telegram infos wenn man die abholt dann wäre das evtl auch noch cool wenn er da ausgibt wv items/pokemon er gerade im inv hat :D 

+ Telegram bug gefunden ^^
wenn man /informations sendet dann aktiviert er die informationen dauerhaft ^^ aber disabled sie nicht :D 

bin dann mal pennen :3
mach weiter so ! gute arbeit ! :+1:

**Comment by TheDarkClaw** [comment]
@niikooartz Hi ,
kannst du mir Erklären wie man den Telegram api token bekommt kenne mich da gar nicht aus.

danke schon mal im voraus,
Luca <(°.^)>
