### ISSUE TITLE
Vielen Dank an die Leute, die sich die Mühe machen alle Fehler zu beheben, Tank you 

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#1570]
Danke, dass ihr Euch die Mühe gebt, damit wir alle wieder unsere Pokémons durch den Bot jagen können.  Es war sicher kein leichter Weg.
Thank you to the people who fixed the bugs. I think that it was not as easy as ist seems. Now we can level our Pokémons higher again. :-)

**Comment by xJustx** [comment]
Danke! Ich werde das an Ar1i und Logxn weitergeben. Bei jedem einzelnen User kann ich mich jetzt natürlich nicht bedanken, der hier auch fleißig hilft :p

======

Thank you! I will forward that to Ar1i and Logxn.

**Comment by NidiKea** [comment]
Sogar den Soft Ban hat der Bot bei mir raus gemacht. Super ! Ja natürlich auch danke an die User :-)
