### ISSUE TITLE
The big Question

### ISSUE THREAD

**Issue by Jam1ePistol** [Ar1i/PokemonGo-Bot#1571]
Did something dramatically change from previous bot version to this one , that makes every person who uses it potential Victim of a ban or is it the same as it was before ?

**Comment by Kongolan** [comment]
Bans are most likely happening, yes.

**Comment by AKBlizzard** [comment]
#1561

**Comment by Jam1ePistol** [comment]
What i am asking is , do we have the same chances to get banned as before the huge update or after they did all those changes now , there is something inside the whole history that makes us 100% vulnerable

**Comment by pokerave** [comment]
well if i'm using my alternative account for a while to see what will happen in a few days.

**Comment by Jam1ePistol** [comment]
Because as it is obviously known and understood , boting has a risk to be found but what i am asking now is did that risk go up with some implementation they did or its the same as before >?

**Comment by cristianst** [comment]
Which is for u guys the recommended speed and radius?

**Comment by Kongolan** [comment]
Chances became higher to get banned, since the API is not 100% fixed and might just emulate the right decryption. They will sure just flag your account and ban them later on in a huge ban wave.
