### ISSUE TITLE
Unable to login in

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#1573]
With Google account 
![image](https://cloud.githubusercontent.com/assets/14841132/17463134/d0069ca6-5c8d-11e6-851c-866c375ee347.png)

With PTC account

![image](https://cloud.githubusercontent.com/assets/14841132/17463142/ed8cf6da-5c8d-11e6-8153-72454d8d0767.png)

Using latest pokemonGo-Bot version.

**Comment by ONOBARY** [comment]
Wrong pasword mybe

**Comment by royhubb** [comment]
Had the same thing, not a wrong password...

**Comment by arjunvegda** [comment]
@ONOBARY I am able to login in with same credentials on google. But PTC disabled my account for 15 mins.

![image](https://cloud.githubusercontent.com/assets/14841132/17463188/df60f984-5c8e-11e6-9417-189d6ff92336.png)

**Comment by 007sg** [comment]
do you use another bot? maybe it's still working..
try change password

**Comment by arjunvegda** [comment]
@007sg Dont know if any other bot has been updated to work. Any suggestions would be appreciated.

**Comment by arjunvegda** [comment]
Pokemon seems to be dealing with heavy traffic 

![image](https://cloud.githubusercontent.com/assets/14841132/17463458/ea0ac7b6-5c93-11e6-9ee3-62cf948f3a87.png)
