### ISSUE TITLE
pokestop, lure and incense

### ISSUE THREAD

**Issue by ronnyouxia** [Ar1i/PokemonGo-Bot#1575]
is it true that we can only find pokemon just normal and use incense only?

how bout pokestop with lure?

can we see the pokemon with bot in term pokemon + lure?

**Comment by wannaD1E** [comment]
Read themes already have such a topic is the answer.

**Comment by wannaD1E** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1548

**Comment by ronnyouxia** [comment]
sorry i just dont get when ar1i say adding with lure..
is it still in project or we can add it to setting manually?

**Comment by wannaD1E** [comment]
as I understand that it is a project. and while we can't collect lure

**Comment by ronnyouxia** [comment]
ok then i'm sorry for misperception..

thx dude..
