### ISSUE TITLE
Not load pokemon list why?

### ISSUE THREAD

**Issue by blade90** [Ar1i/PokemonGo-Bot#1577]
![immagine error](https://cloud.githubusercontent.com/assets/20888636/17463177/e85515a2-5cc0-11e6-8406-e2d9a553702f.jpg)

**Comment by Dhannyjsb** [comment]
please read your console carefully :)

**Comment by pokerave** [comment]
bad authentication, wrong password

**Comment by arjunvegda** [comment]
Because you have not logged in.  I have the same issue.
#1573
