### ISSUE TITLE
Still showing 'Inventory Full?'

### ISSUE THREAD

**Issue by TouchTheSkies** [Ar1i/PokemonGo-Bot#1578]
Still shows this. Just getting EXP from Pokestops, no items at all. I have the latest download, so that's not the issue.
![image](https://cloud.githubusercontent.com/assets/20759766/17463190/e6a97162-5c8e-11e6-9803-a57ec2bc09a3.jpeg)
![image](https://cloud.githubusercontent.com/assets/20759766/17463191/e6bf5b12-5c8e-11e6-8f96-4c9bed7cba6a.jpeg)

**Comment by 007sg** [comment]
your bag is FULL, change your setting on the tab ITEMS

**Comment by pokerave** [comment]
his items is saying 192/350.. i have not encounter this problem check with the Devs.. but they are resting now i think after 40hrs no sleep

**Comment by TouchTheSkies** [comment]
My bag ISN'T full though. And usually the bot would still continue to get items anyway, so I'm not sure what's up.
