### ISSUE TITLE
Bug login ptc

### ISSUE THREAD

**Issue by KLIBREFR** [Ar1i/PokemonGo-Bot#1580]
Please Help
![8fbd1dbf911d7df9f9759d54f48cbd88](https://cloud.githubusercontent.com/assets/11018569/17463197/41081a46-5cc1-11e6-9027-9658c615b190.png)
![8967e58c1bb1cc868713fcc013a0fc3e](https://cloud.githubusercontent.com/assets/11018569/17463198/410dc676-5cc1-11e6-8ebd-7902da7a5591.png)

**Comment by arjunvegda** [comment]
I have the same error here #1573

**Comment by KLIBREFR** [comment]
@arjunvegda Google login work but not PTC
