### ISSUE TITLE
not unbanning my account

### ISSUE THREAD

**Issue by tenboherce** [Ar1i/PokemonGo-Bot#1581]
all pokemons run away , no error that i'm softbanned, but clearly i am, but he won't unban himself :/

**Comment by MariusSolaat** [comment]
Just let it stand for a couple of hours (about 4-5) and it'll fix itself.
Or you could look up and try the QuickSpin unban tool. But I don't know if it's updated to the new API though.

**Comment by tenboherce** [comment]
ok ty , this can get closed then :)
