### ISSUE TITLE
Transfer Pokemon

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#1582]
I set keep 3 duplicate pokemon and tick transfer doble pokemon but it sends all pokemon away

**Comment by pokerave** [comment]
you have latest download?

**Comment by MythosOfGaming** [comment]
i have this one https://github.com/Ar1i/PokemonGo-Bot/tree/old-source

**Comment by mydonny1986** [comment]
use this:
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2007.08%2015.48.rar

**Comment by MythosOfGaming** [comment]
Ok thanks it works :+1: :D
