### ISSUE TITLE
**Feature Request - Perfect Thows Configurable

### ISSUE THREAD

**Issue by tr1via1** [Ar1i/PokemonGo-Bot#1583]
Hi,

Request (please):
- feature where user can configure perfect throws.

Example:
- if CP >= 999 (perfect_throw = true)
- if IV >= 90 (perfect_throw = true)
- if Probability <= 50 (perfect_throw = true)
else throw = random    //nice or great

Reason: I'm assuming Niantic stores "player throws" data. If so, this feature would help make a user's throw data more "realistic".
TL;TR: for the paranoid

Thanks

**Comment by jmo93** [comment]
Good idea.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
