### ISSUE TITLE
Auto Incubate

### ISSUE THREAD

**Issue by yonatan-nugraha** [Ar1i/PokemonGo-Bot#1584]
I am just wondering whether "basic incubators" include both permanent incubator (orange color) and limited incubator (blue color), cos I would like to just use my permanent incubator and keep the limited one. Thank you :)

**Comment by wannaD1E** [comment]
There is also a checkbox which the incubators to use. If you want to use only an endless incubator, put a tick. Yet setting some eggs to add, but I think the project will.

**Comment by pokerave** [comment]
They will work on it. they need rest after 40+hrs of no sleep

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
