### ISSUE TITLE
Auto incubate doesn't work

### ISSUE THREAD

**Issue by Verbalkint89** [Ar1i/PokemonGo-Bot#1586]
Auto incubate doesn't work... pls fix it : )
p.s. good job to all

**Comment by pokerave** [comment]
They will work on it. they need rest after 40+hrs of no sleep

**Comment by Kranios** [comment]
was just going to post the same issue but I will let them get some sleep for now :P I am putting my eggs manually for now on.

**Comment by Verbalkint89** [comment]
ok : ) take tour time boys...and again good job : )

**Comment by gummyruler** [comment]
IT works fine for me? what seems to be the problem?
