### ISSUE TITLE
Question... Has anyone been soft or hard banned yet?

### ISSUE THREAD

**Issue by Tymoc** [Ar1i/PokemonGo-Bot#1587]
Just curious to see if anyone has been banned yet... i'm using an alternate account with default settings... and so far so good.  =)

**Comment by gummyruler** [comment]
@Tymoc It's a risk we all have to take. We're a`ll probably going to get banned soon anyway.

**Comment by Tymoc** [comment]
Hope not... this tool is awesome!!!

**Comment by VitoDEV** [comment]
Yes i has been banned, but the bot tried a method and i'm not banned anymore now, xD The bot have 1372method to unban ;)

**Comment by Tymoc** [comment]
SWEEEET!

**Comment by pokerave** [comment]
i havnt been ban

**Comment by Madrocker85** [comment]
nope I've not been banned at all yet, with sensible settings you should be relatively safe atm.

**Comment by Tymoc** [comment]
How long have you been on the program?

**Comment by Tymoc** [comment]
so ... set speed to less than 50kph?

**Comment by mydonny1986** [comment]
im on like 150kph lol

**Comment by Tymoc** [comment]
LMFAO!  XD

**Comment by Madrocker85** [comment]
been running this new build for about 2 hours with good results, but have been using Ar1i's bot for about 1 1/2 weeks with zero problems. I have my speed set to 19kph

**Comment by jmo93** [comment]
Why so fast? I have set 14 kph

**Comment by gemgio** [comment]
i'm going @ 300 km/h, no hard neither soft ban.

**Comment by Tymoc** [comment]
WOW!

**Comment by Madrocker85** [comment]
you'll miss loads of potential pokemon catches at those speeds!

**Comment by jmo93** [comment]
What is the best speed  for farming but also for incubating the eggs?

**Comment by Tymoc** [comment]
Have mine set at 21... o.O

**Comment by Madrocker85** [comment]
> acer2k commented a minute ago
For eggs use max at 10mph or 15 km/h

Slowed mine down to 14kph now.

**Comment by Tymoc** [comment]
Thanks Guys!!

**Comment by VitoDEV** [comment]
![image](https://cloud.githubusercontent.com/assets/6379116/17463460/a02572d2-5cb5-11e6-95ca-a989eabb39a0.png)

**Comment by Tymoc** [comment]
@VitoDEV what settings do you have running?

**Comment by VitoDEV** [comment]
@Tymoc 50Kmph, and like evolve and transfer and other things.

**Comment by Tymoc** [comment]
thanks

**Comment by gemgio** [comment]
well, i'm not sure on what u rally miss at high speed, cause before every pokestop it slows down, so u have 40 meters to find pokemons. plus, if there are some lures, when u come near to stops pokemons just spawn. anyway, it works quite fine for me, no need to change it

**Comment by Bannz** [comment]
sorry for oot. anyone have a good lat and long? I'm done with central park NY.. just nidoran F I caught!

**Comment by VitoDEV** [comment]
@Bannz Hahahahha, me too, i'm in L.A now join me xD

**Comment by velfisadri** [comment]
what speed is best for exp/h? im using 200 km/h - 50.000 exp/h in yoyogi park tokyo, what do u recommend for best exp/h

**Comment by gummyruler** [comment]
People you can set it to as high as 2000, but you get soft banned if it travels on great distances. If the pokestops are close to each other you can set it to the speed of light.

**Comment by Bannz** [comment]
@VitoDEV location sir.. and what the safe speed limit?? worry for banned

**Comment by xJustx** [comment]
^
