### ISSUE TITLE
No last coordinates

### ISSUE THREAD

**Issue by jmo93** [Ar1i/PokemonGo-Bot#1588]
Since the update there is no file lastcoords. 
Every botstart i have to put my coordinates new.

**Comment by pokerave** [comment]
last coordinates is in config folder, config.txt

**Comment by jmo93** [comment]
Ok thanks. But still i have to enter, every time i start the bot, my coordinates.

**Comment by itsawd** [comment]
last coord is created when you launch the bot firstly

**Comment by sylva91** [comment]
i have a similar problem : my new coordinates are always set as the last coordinates
