### ISSUE TITLE
Rewrite of French translate 

### ISSUE THREAD

**Issue by BlackHatching** [Ar1i/PokemonGo-Bot#1589]
Can u just take 1 minutes to edit french.json
And replace all ["é", "è"] , to "e"
Also "à" in "a" please
Because there are all replace in "?" this is not esthetic ;)

**Comment by BrusXYZ** [comment]
Tiens, je l'ai modifié.

**Comment by Gunjha** [comment]
What file do i need to edit to correct this bug ?
when i save france.json i don't see any difference

**Comment by BrusXYZ** [comment]
What version do you have ?

**Comment by xJustx** [comment]
If you edited something pls do a pull request. Thank you!
