### ISSUE TITLE
Pokemon List out of memory

### ISSUE THREAD

**Issue by Nygmarius** [Ar1i/PokemonGo-Bot#1590]
[12:12:55] Error reloading Pokemon list: Out of memory.

its happening every 5 seconds...

Still between error and error im able to catch and transfer just seems a wierd bug i cant fix in any way.

Any idea?

**Comment by chom00** [comment]
i get the same issue. i think this happens when we have upgraded pokemon storage. I'm just waiting till they fix this. You can close the pokemon list for now i guess.
