### ISSUE TITLE
not catching any pokemons at all

### ISSUE THREAD

**Issue by BloodHearts** [Ar1i/PokemonGo-Bot#1593]
Hey I am not catching any pokemons at all it will slow down for the pokemon but it doesn't catch it.. and I have enough pokeballs..
Does anyone know why? ( check attached screenshot)
![x](https://cloud.githubusercontent.com/assets/20837874/17463300/fc507888-5cc2-11e6-9953-c6b771356ded.png)

**Comment by itsawd** [comment]
delete "LastCoord" and change you location

**Comment by BloodHearts** [comment]
marion808 I tried that and it did not work I will try your solution now itsawd

**Comment by itsawd** [comment]
try to change continent by the way

**Comment by ankhmok** [comment]
Same issue as well and I can't find "lastcoord" file

**Comment by ankhmok** [comment]
Same issue as well and I can't find "lastcoord" file

**Comment by BloodHearts** [comment]
I can't find lastcoord for some reason

**Comment by itsawd** [comment]
In the folder Config wht do u see?

**Comment by BloodHearts** [comment]
I just changed the location without deleting anything and it is working fine now thanks for all the quick support
