### ISSUE TITLE
No items from pokestops. "Inventory full?"

### ISSUE THREAD

**Issue by RomanRooks** [Ar1i/PokemonGo-Bot#1594]
![default](https://cloud.githubusercontent.com/assets/20888923/17463262/d25d2672-5cca-11e6-92b1-89a8a908194f.JPG)
![1](https://cloud.githubusercontent.com/assets/20888923/17463263/d25f0d7a-5cca-11e6-877d-6f6bf6806fd4.JPG)
![2](https://cloud.githubusercontent.com/assets/20888923/17463261/d259fccc-5cca-11e6-83d5-bdd57841d626.JPG)

I've got some place in inventory, but bot still send "inventory full". 

Thanks for great bot and support!

**Comment by itsawd** [comment]
965 items is too big

**Comment by rainkeel** [comment]
your inventory full 350item, you setting bot total count 965 ITEM

**Comment by RomanRooks** [comment]
Look at the first screen.
"Items: 234/350"
I've got only 234/350 in the inventory.

**Comment by dragon2011** [comment]
@RomanRooks  change your settings so that your inventory count is 340 or 345, and not 965. bot reads 965, you dont have 965 space, your settings wrongs

**Comment by RomanRooks** [comment]
Changed settings to that ones, and it worked!
![default](https://cloud.githubusercontent.com/assets/20888923/17463778/658fe492-5cd6-11e6-8673-a78c7659d6aa.JPG)
