### ISSUE TITLE
NOT ISSUE Just a thanks to Ar1i

### ISSUE THREAD

**Issue by dragon2011** [Ar1i/PokemonGo-Bot#1595]
Thanks Ar1i, it works perfectly as before on my first use after API fix, also many people are getting soft banned for 4 hours because they forgot to set their location to where they last were.

Thanks again mate

**Comment by Rolzy2** [comment]
Completely agreed, thank you Ari and all people who worked on it, you rule!

**Comment by zyf911** [comment]
+1 here, thanks to Ar1i~~~the new update works like a charm, so great, I saw the hatch function was added too...

**Comment by xJustx** [comment]
Thank you! I will forward that to Ar1i.

**Comment by Logxn** [comment]
Also no problem =) -Logan

**Comment by Logxn** [comment]
I will tell Logan :^)
