### ISSUE TITLE
Great Ball and Master ball aren't working!

### ISSUE THREAD

**Issue by MegaVortex** [Ar1i/PokemonGo-Bot#1596]
Thr only item you can cathch pokemon with is a pokeball.  Great Ball and Master ball aren't working!

**Comment by itsawd** [comment]
have u an error or something like that ?

**Comment by dragon2011** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20613381/17463394/8b44465e-5cc4-11e6-821f-8c30d18e69e9.jpg)

greatballs seems to work fine

**Comment by MegaVortex** [comment]
My settings for pokeballs are: pokeball - 0, greatball - 5, ultraball - 100 and everytime I set pokeball=0 all the pokemons are running away with an error "run away while using ItemPokeBall". Error disappearing just when I set pokeball=10.

**Comment by dragon2011** [comment]
@MegaVortex  the bot is set to use pokeball on pokemon 0-499cp, greatball 500-999cp, ultraball 1000cp+, you must have pokeballs, you can NOT set pokeballs to 0

**Comment by MegaVortex** [comment]
Now I see, fells like an idiot. Thanks, dragon2011, I appreciate your comment!

**Comment by adhitaattack** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20889535/17463748/cadf53f0-5c81-11e6-8e93-164dd085d656.png)
always got away plese help me

**Comment by surfacing1976** [comment]
i have the same problem than u adhitaattack

**Comment by dragon2011** [comment]
@adhitaattack you are soft banned for 4 hours because you changed location that is to far away, you can download the new version to try and unban yourself or wait 4 hours, never make big jumps with location or you will get a soft ban

**Comment by adhitaattack** [comment]
this is new version man 17.58
plis help me
