### ISSUE TITLE
Bot SettingS For High Level Trainers

### ISSUE THREAD

**Issue by MOE4HACKS** [Ar1i/PokemonGo-Bot#1597]
I have my alt account lvl 22 with a tons of 1500+ evolved pokemons, So what is the best settings for max cp & IV to transfer , also im filtering all the top evolutions from getting transfered, i dont want to start the bot and loose all my gd pokemons b4 i get any help about the best settings.

THX

**Comment by itsawd** [comment]
https://gyazo.com/106a2bc9ac6f29da60c16b2fd6edc68e For lvl 32 is correct

**Comment by sunit1998** [comment]
set the cp to 1400 and iv to 85%

**Comment by MOE4HACKS** [comment]
Thx Guyz :)

**Comment by MOE4HACKS** [comment]
@itsawd  can u pls give me a print screen for your filters , guess it wll help.

**Comment by Madrocker85** [comment]
I'm at lvl30 with cp @ 1200 and IV @ 90%

**Comment by sunit1998** [comment]
i m level 34 with 2000 cp and 90% iv

**Comment by 13XxM1CHA3lxX37** [comment]
Level 34, 34, 34, 35, 35, 36, 36, 36

best setting so far:

max dupes: 1
max. CP to transfer: 2000
max. IV to transfer: 90
