### ISSUE TITLE
JUST THANKS

### ISSUE THREAD

**Issue by chickeflonoah** [Ar1i/PokemonGo-Bot#1598]
I just wanted to say THANKS to the developers. They worked on the bot almost 24/7 and they finally did it. They dont even sell the bot, its for free so I will donate some money for them. Be thankful for that guys! ♥

**Comment by gRullo** [comment]
Quote @chickeflonoah , Amazing job, thanks to everyone !

**Comment by Logxn** [comment]
21 minutes ago, I did not recieve a donation yet. ......... jk :p 

No seriously, no problem =) We had our fun

**Comment by FinFis** [comment]
love the dedication! you guys and ur brains :+1:

**Comment by chickeflonoah** [comment]
Give me some time bro @Logxn 
Im on work now :D

**Comment by owned85** [comment]
Thanks a lot for your work @Logxn  and @Ar1i ... Made a little dotation for your work :)
