### ISSUE TITLE
GPSOAuthSharp & Error reloading Pokemon list: Object reference not set to an instance of object

### ISSUE THREAD

**Issue by john-hardesky** [Ar1i/PokemonGo-Bot#1599]
![pgbot2](https://cloud.githubusercontent.com/assets/20889066/17463328/8663b008-5cc3-11e6-847c-3fa7fe3463e5.png)

![pgbot](https://cloud.githubusercontent.com/assets/20889066/17463317/522e6986-5cc3-11e6-84a9-62641c270f15.png)

Information:
Account type: Google
Bot settings: Default and personal yield same error
Bot version: 1.0.7.6

**Comment by sunit1998** [comment]
check if u have entered right id and password

**Comment by itsawd** [comment]
exactly the problem is your id n pass

**Comment by john-hardesky** [comment]
Yeah, the authentication information is accurate. The problem has nothing to do with my username and password.
I tried it with 2 different accounts.

**Comment by krush26** [comment]
i am also getting this error i changed my pass and tried and am still getting this

**Comment by itsawd** [comment]
lol im searching

**Comment by john-hardesky** [comment]
Problem solved in version 1.0.7.2

Thanks

**Comment by candas974** [comment]
How to fix it????
