### ISSUE TITLE
my items not getting deleted

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1600]
i got like 150 pokeballs but i have set pokeballs to 50 they arent getting deleted please solve this or give me a solution for it

**Comment by itsawd** [comment]
leave us your config screenshot

**Comment by sunit1998** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20731094/17463428/b8867c22-5ce2-11e6-96cf-edad38ccb9c9.jpg)

**Comment by arjunvegda** [comment]
Same issue

![image](https://cloud.githubusercontent.com/assets/14841132/17463498/d63a80e0-5c94-11e6-9efe-d86d58c75af0.png)
