### ISSUE TITLE
not transferring certain pokemon

### ISSUE THREAD

**Issue by lucafry1** [Ar1i/PokemonGo-Bot#1601]
Ive begun to notice that it doesnt transfer any of my male nidorans or machomps, geodudes and a few others i think. They are under my max iv and cp, and my max duplicate is 1. Anyone got the same problem?

**Comment by lucafry1** [comment]
Much respect and thanks to ar1i and friends though for putting in so much hard work.

**Comment by itsawd** [comment]
Please leave us a screen of your config...

**Comment by arjunvegda** [comment]
Same problem.. Here are my configs.

![image](https://cloud.githubusercontent.com/assets/14841132/17463463/1f2664d2-5c94-11e6-94dd-78da9b7b4cfb.png)

![image](https://cloud.githubusercontent.com/assets/14841132/17463464/2e2d62c8-5c94-11e6-8fc2-b397cbffb201.png)

**Comment by bassemmixez** [comment]
when i mark on Auto transfer double pokemons  and max dublicate 02  , it remove all pokemon without keeping any of them , 

if i removed the mark from auto transfer  it keep all pokemons without removing

**Comment by gummyruler** [comment]
Check and uncheck the boxes maybe that'l fix it. Some config files might be messed up during the transfer.

**Comment by pokerave** [comment]
download new version.

**Comment by Pyroman2300** [comment]
Still not working for me, put max IV at 95% and max cp at 2000, transferred a gyarados with a 97% IV and 2224 cp...
