### ISSUE TITLE
NeedsBrowser

### ISSUE THREAD

**Issue by sti000en** [Ar1i/PokemonGo-Bot#1603]
Hi there
this problem occurs only with one account from me.. my other gmail accounts are working.
anyone an idea?
![bildschirmfoto 2016-08-07 um 17 34 17](https://cloud.githubusercontent.com/assets/20889251/17463435/9a885f0a-5cc5-11e6-94a4-0bb93e0b280a.png)

**Comment by erickrisnarinjaya** [comment]
turn off the 2 step verification from your google account setting.

**Comment by sti000en** [comment]
ok thank you i'll try that 👍

**Comment by sti000en** [comment]
hmm didn't turned that on, still doesn't working :/

**Comment by erickrisnarinjaya** [comment]
but it worked in mine.

**Comment by BlackHatching** [comment]
download the new version of the build and tell us

**Comment by gummyruler** [comment]
@sti000en  That means you're account restricted for 15mns. Recheck the characters you have entered.

**Comment by sti000en** [comment]
yes i did enter the password wrong on the first try and on the second attempt, this text appeared. Maybe thats the problem right?
thank you so much for the help!

**Comment by 13XxM1CHA3lxX37** [comment]
Try to create an app password

**Comment by sti000en** [comment]
@13XxM1CHA3lxX37 isn't that only needed when 2-step verification is turned on?

**Comment by sti000en** [comment]
still doesn't working, even after waiting. app password doesn't work either, 'cause 2step verification isn't turned on.

**Comment by Inforcer25** [comment]
Login here and create a password for the app https://security.google.com/settings/security/apppasswords

**Comment by sti000en** [comment]
![](http://i.imgur.com/RHPlGuJ.jpg)
