### ISSUE TITLE
[feature request] enhance pokemon list

### ISSUE THREAD

**Issue by czokalapik** [Ar1i/PokemonGo-Bot#1604]
First of all: thank you all for your all hard work! 

I'm constantly checking my list to leave best pokemons, but there are few things lacking.
IV helps alot, but i have few suggestions, that could help to see "more":

- reference http://www.eurogamer.net/articles/2016-08-02-pokemon-go-moves-movesets-move-list-and-highest-dps-attacks and add 1-3 stars rating to strong attack (or add it's DPS values)
- add number of bars strong attack have
- also referencing above link add 1-2 stars rating to basic attack (or add it's DPS values)
- add option to "mark as favourite" to quick actions on pokemon list
- in general settings add option "don't transfer or evolve favourite pokemons.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
