### ISSUE TITLE
Not an issue, just a question about getting banned.

### ISSUE THREAD

**Issue by Sora1724** [Ar1i/PokemonGo-Bot#1606]
Is it safe to use my main account lvl 23, spent some money on it?
He's in my city, walking 10 kmh. 
I'm a little bit afraid of getting banned xD

Also thanks to everybody who worked on the bot!

**Comment by itsawd** [comment]
You can but with bot's tool probably you have risks to be banned (1%)

**Comment by sunit1998** [comment]
u wont get banned on 10kmph speed u can go upto 25 kmph without getting banned i use 500 kmph and dont get banned

**Comment by Sora1724** [comment]
Thanks ^^ I think 10kmh is pretty good, cause the eggs will hatch too :)

**Comment by xJustx** [comment]
Don't use your main account. It's not 100% safe.
