### ISSUE TITLE
transferring problem 

### ISSUE THREAD

**Issue by bassemmixez** [Ar1i/PokemonGo-Bot#1609]
thanks boss for your efforts
i have one problem
when i mark on Auto transfer double pokemons and max dublicate 02 , it remove all pokemon without keeping any of them ,

if i removed the mark from auto transfer it keep all pokemons without removing

**Comment by xJustx** [comment]
It's fixed now. Please download the newest version!

**Comment by PokePro21** [comment]
so disable the auto transfer and transfer it your self ! until the update comes
 :)

**Comment by xJustx** [comment]
@PokePro21 It's fixed. You don't need to disable that...

**Comment by bassemmixez** [comment]
but not said need to download the newest version

**Comment by bassemmixez** [comment]
where the new link

**Comment by xJustx** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
