### ISSUE TITLE
ISSUE: The specified module could not be found

### ISSUE THREAD

**Issue by Dangery1** [Ar1i/PokemonGo-Bot#1610]
![pkmngoissue](https://cloud.githubusercontent.com/assets/20889399/17463500/292ff92e-5cc7-11e6-9746-1e6e9cc1e32f.JPG)
Does anybody else has this issue? Or any idea how to fix it?
Tried various settings now, getting the same thing every single time with more than one account (Gmail and PTC)
Thanks in advance

**Comment by itsawd** [comment]
Place Encrypt.dll at the root of the build
https://t.co/GxEaBFaXj6 (link)

**Comment by Dangery1** [comment]
Thx mate, I close this
