### ISSUE TITLE
Does not catch pokemon

### ISSUE THREAD

**Issue by zenith4957** [Ar1i/PokemonGo-Bot#1614]
![report](https://cloud.githubusercontent.com/assets/20888868/17463472/5f008e20-5c94-11e6-86a6-72bb1ea44266.jpg)
pokestop works fine. It is not soft ban.
all the pokemon got away and encounter the same pokemon(same CP, same IV, same %) again about 5 times, even I am moving.
I tried re-download, move the location, just wait, reboot the computer but nothing works.

**Comment by Logxn** [comment]
Set normal Pokeballs to 10
