### ISSUE TITLE
Pokesnipers benutzten

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#1619]
Wie kann man Pokesnipers benutzten? 
Man wird ja immer gebannt wegem dem Teleport und gibts da tricks nicht gebannt zu werden?

**Comment by Thomongo** [comment]
Du musst deine richtige Position angeben dann wirst du nicht gebannt  https://www.youtube.com/watch?v=KK02oNW8Oz0 schau mal dort vorbei er erklärt es

**Comment by Logxn** [comment]
Nein
