### ISSUE TITLE
Debugging nicht starten

### ISSUE THREAD

**Issue by Zwenkek** [Ar1i/PokemonGo-Bot#162]
Ich bekomme immer die meldung das Das Debugging nicht staten kann. da das Debugziel nicht vorhanden ist. "Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0006	Metadatendatei "C:\Users\user1\Desktop\Kmo\Zwente NEW\PokemonGo-Bot-master (1)\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\bin\Debug\PokemonGo.RocketAPI.Logic.dll" wurde nicht gefunden.	PokemonGo.RocketAPI.Console	C:\Users\user1\Desktop\Kmo\Zwente NEW\PokemonGo-Bot-master (1)\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\CSC	1	Aktiv
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Warnung	CS1998	In dieser Async-Methode fehlen die "await"-Operatoren, weshalb sie synchron ausgeführt wird. Sie sollten die Verwendung des "await"-Operators oder von "await Task.Run(...)" in Betracht ziehen, um auf nicht blockierende API-Aufrufe zu warten bzw. CPU-gebundene Aufgaben auf einem Hintergrundthread auszuführen.	PokemonGo.RocketAPI	C:\Users\user1\Desktop\Kmo\Zwente NEW\PokemonGo-Bot-master (1)\PokemonGo-Bot-master\PokemonGo.RocketAPI\Client.cs	125	Aktiv
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Warnung	CS0219	Die Variable "R" ist zugewiesen, ihr Wert wird aber nie verwendet.	PokemonGo.RocketAPI.Logic	C:\Users\user1\Desktop\Kmo\Zwente NEW\PokemonGo-Bot-master (1)\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Utils\GeoUtils.cs	41	Aktiv

Ich weiß nicht weiter

**Comment by par0noid** [comment]
Bei mir das selbe

**Comment by Zwenkek** [comment]
I just get my self the .EXE and the Exe works

**Comment by Ar1i** [comment]
fixed in newest update
