### ISSUE TITLE
Auto Brüten

### ISSUE THREAD

**Issue by TrippyCat** [Ar1i/PokemonGo-Bot#1620]
Moin
Kann es sein das es noch nicht funktioniert? Ei Brütet der Bot, aber packt kein neues rein. Kann auch sein das ich die Einstellung falsch gewählt hab, aber ich geh davon aus das der Basic Incubator der unendlich nutzbare ist.

**Comment by marion808** [comment]
funktioniert noch nicht richtig!

**Comment by BlackHatching** [comment]
Speak ENGLISH please !

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
