### ISSUE TITLE
Not transfering

### ISSUE THREAD

**Issue by BrandonHCD** [Ar1i/PokemonGo-Bot#1623]
Hi, i have selected auto transfer double Pokemon and max duplicate is 1, max CP to transfere is 1400 and max IV is 85. But somehow it doesnt transfer any pokemon, not even a 10CP Caterpie...

**Comment by Logxn** [comment]
Do you have "keepPokemonsThatCanEvolve" checked?

**Comment by BrandonHCD** [comment]
Yes i did. What a stupid mistake... Besten Dank :P

**Comment by Praxthisnovcht** [comment]
it may be just the
![capture](https://cloud.githubusercontent.com/assets/9677000/17464097/59944084-5c8b-11e6-8076-a469c4024a40.PNG)
