### ISSUE TITLE
got this issue every 30mins

### ISSUE THREAD

**Issue by audota000** [Ar1i/PokemonGo-Bot#1629]
First, thanks for ur work.
i got this issue on both of my accounts right after the first 30mins. tried twice, 30mins again. any help?
after the first 30mins when it happens, it repeatly comes.
![error](https://cloud.githubusercontent.com/assets/20767527/17463728/d7bd4e36-5d0f-11e6-9afe-d35e81a875d2.png)

**Comment by emilie253** [comment]
same

**Comment by PokePro21** [comment]
yes for me also but it catches the pokemons for me

**Comment by audota000** [comment]
yes, otherthing works fine.

**Comment by bassemmixez** [comment]
same
