### ISSUE TITLE
[Request] Import/Export configuration 

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#163]
With update we loose our configuration of bot

**Comment by stormlolz** [comment]
Error.. Cannot edit on my mobile phone.. 

Possibility to export/impprt our configuration or profiles to save ?

**Comment by Ar1i** [comment]
Uhm just Copy the Config Folder!

**Comment by stormlolz** [comment]
Yes i'm unbrain this morning..
