### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Vamp1G** [Ar1i/PokemonGo-Bot#1630]
Beim öffnen der .exe erscheint diese fehlermeldung 

auf das angegebene gerät bzw. den pfad oder die datei kann nicht zugegriffen werden.
etc etc 

windows 10 64x

**Comment by PippoAe** [comment]
Klick mit der rechten Maustaste auf die .exe und wähle "Als Administrator ausführen".

**Comment by Vamp1G** [comment]
Hat nichts gebracht, es lag an Gdata (antivir prog). einfach alles ausschalten dann klappt es
