### ISSUE TITLE
Works like a charm, heres tutorial

### ISSUE THREAD

**Issue by itzjaydon** [Ar1i/PokemonGo-Bot#1632]
hers Ar1i`s tutorial and yes its the older version but its the same way you welcome :) https://www.youtube.com/watch?v=mW5KsA75lt8

**Comment by itzjaydon** [comment]
https://www.youtube.com/watch?v=mW5KsA75lt8

**Comment by dragonuts330** [comment]
Ggreat good post maybe help people who are having issues and clear the board a little. Its working great for me on x5 clients atm.. Domination incoming 💃

**Comment by itzjaydon** [comment]
@dragonuts330 thanksthats what im aiming for and hahaha domination is defiantly incoming
