### ISSUE TITLE
Possibility of a "no farm" mode, just for deleting items and Pokemon?

### ISSUE THREAD

**Issue by Ritzii** [Ar1i/PokemonGo-Bot#1634]
While the bot was down, I had started to use it while playing through Nox to auto delete items while I walked etc and to check the IVs and mass transfer Pokes that I had caught. The updated version seems to cause conflict though and nothing will appear on Nox until I close it down.

I realise this is a weird issue and I could load it once in a while to delete/transfer, but the access to never having to sort my inventory out and check my IVs in such an easy and simplistic way is amazing.

Thank you and thank you for this amazing project. :)

**Comment by P529** [comment]
+1
