### ISSUE TITLE
Force Unban Failed

### ISSUE THREAD

**Issue by marcop888** [Ar1i/PokemonGo-Bot#1638]
Force Unban Failed.. Still cannot catch Pokemon. Please fix it Ar1i.. u're da best

**Comment by Ar1i** [comment]
Need more informations about that, or i cant do shit. Screen Log?

**Comment by Praxthisnovcht** [comment]
it works for me: D
![capture](https://cloud.githubusercontent.com/assets/9677000/17464085/170a82a0-5c8b-11e6-94e2-a8a2d0fd5d59.PNG)
