### ISSUE TITLE
is it me or its catching a pokemon / min

### ISSUE THREAD

**Issue by kuan098760** [Ar1i/PokemonGo-Bot#164]
is it possible to get the program to catch all the pokemon within a radius? I mean there are like 20 pokemons in 1 location within 10 feet and the bot is like 1 pokemon / min. Is it because i set the moving radius to 1000 meters? or it has something to do with just the bot going through its programs? I remember i used another one before that was catching crazy amounts of pokemons before. Im not saying that yours is rubbish, I totally appreciate the fact that i can get to use a FREE bot! Thanks for your contribution to the community, hats off to you.

I also noticed that the bot is more towards taking pokestops than catching the pokemon. just my 0.2 cents

**Comment by StephenSocksTv** [comment]
The same thing is happening to me. I would like to catch pokemon faster too!

**Comment by kxngrocafella** [comment]
Yep I agree. It seems to be prioritizing stops over catching pokemon.

Also, I just went to a location where there are Dratini all over the place (10+ in the area) so I set the radius to 5000 meters, but it just won't catch them. Anyone know why?

**Comment by stormlolz** [comment]
What the speed to configurate for maximize the catch of pokemon?

**Comment by kuan098760** [comment]
i dont know...but im pretty sure that the bot is more towards pokestops... i would like the frequency to be more about catching pokemons then transfer then pokestop

ex;

catch pokemon  2 seconds CD
catch pokemon  
transfer pokemon lower %    IV low CP
poke stop 
transfer item

* repeat

**Comment by Zwenkek** [comment]
I agree! also it seems to Catch more Low Cp pokemon than High.. but maybe it is just me...

**Comment by Joesilvpb4** [comment]
Zwenkek, I too am experiencing low cp catching and the application is very pokestop based.  I unsure as to why though.

**Comment by Ar1i** [comment]
I needed to Change something yesterday. Thats why it doesnt hunt that much Pokemon's. Today there will be an update which should fix that.

**Comment by Ar1i** [comment]
Fixed in newest Update. Thanks @baeckstrom
