### ISSUE TITLE
Get this error every so often

### ISSUE THREAD

**Issue by D3VASTATlON** [Ar1i/PokemonGo-Bot#1640]
the error does not seem to stop the bot longer than 10 seconds.

![pokemongo error](https://cloud.githubusercontent.com/assets/20890128/17463823/4302bd5c-5c9d-11e6-8238-f64c238bca1b.png)

**Comment by sunit1998** [comment]
redownload the latest bot and try again

**Comment by Ar1i** [comment]
already fixing that

**Comment by CreatorSky** [comment]
@Ar1i did you fix that ?

**Comment by Ar1i** [comment]
yeah should be fixed in newest update.
