### ISSUE TITLE
Doubt about Config for exp/location(Don´t know if its an issue)

### ISSUE THREAD

**Issue by PureSkill** [Ar1i/PokemonGo-Bot#1642]
Some people say they earn like 200k xp per hour, is it legit ? 

If it is, what the config/location ?

**Comment by Bikkstar123HD** [comment]
yeah i wanna know the same level 32 here i only get 40-50k hardly  and again its an issue thread dont post for requests thanks

**Comment by royhubb** [comment]
Yeah you can, when u powerlevel using lucky eggs, you can get 200k exp per hour.
But then you gotta have a lot of evolvable pokemon lol

**Comment by sunit1998** [comment]
wow i just get 30k exp per hour

**Comment by sunsiskos** [comment]
Where do you guys farm at ?

**Comment by PureSkill** [comment]
@sunsiskos  Farming on Tokyo right now, 60kxp/h, but not 200 ^^

**Comment by velfisadri** [comment]
im at yoyogi park tokyo too, 50k exp/h. what is your speed?
