### ISSUE TITLE
[Request] Will you upload the source any time soon?

### ISSUE THREAD

**Issue by Kongolan** [Ar1i/PokemonGo-Bot#1644]
Hello there,

beside of all the spamy issues here, my question is if you will upload the source again in future? 

I used to inject my own methods into the source for my personal use, to speed things up and have better pokemon filter and such. 

Currently you only give away the .exe, which literally has no use for any developer, just for the kid-botters, who love drag&drop...

Kind Regards,
- Kongolan

**Comment by pokerave** [comment]
pokecrot lol

**Comment by Bikkstar123HD** [comment]
he wont be realeasing source anytime soon so better not ask hahah @pokerave  u know what i mean *wink* *wink*

**Comment by marion808** [comment]
dont steel bot! make your own bot and code

**Comment by Kongolan** [comment]
@marion808 I already used the old source and injected my own methods there. Just today he put the source offline. Most likely, because he had such an early API fix. But i'm asking, if he will upload it in 2-3 days or something.

**Comment by Bikkstar123HD** [comment]
nope he wont

**Comment by immoempe** [comment]
I hope he don't upload the source, with the exe is enough

**Comment by Ar1i** [comment]
Atm i wont publish it. But some users which helped me, getting access to the private repo
