### ISSUE TITLE
Incubation

### ISSUE THREAD

**Issue by Bowny** [Ar1i/PokemonGo-Bot#1645]
auto- Incubation doesn't work for me

**Comment by pokerave** [comment]
they are working on it. they need a little rest  after all the work they did.
![rest](https://cloud.githubusercontent.com/assets/20603254/17463869/e73f91d8-5cd9-11e6-80fe-7a6799637ceb.png)

**Comment by Bikkstar123HD** [comment]
they obviously deserve some rest

**Comment by Sora1724** [comment]
yep they did xD
