### ISSUE TITLE
Can you add a fast level bot?

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#1646]
I have seen a bot which is called  spegli and it gives you 200k XP per hour.
Unfortunately that bot is not updated.
Can you also add this featrue or can you tell me a free bot which can do that?

**Comment by Bikkstar123HD** [comment]
this is not a search engine its an issue thread so u better search yourself and close this issue thanks

**Comment by pokerave** [comment]
I think theres a bot called EasyToGetBAN try that one. lol

**Comment by fourmansyah** [comment]
if u want got many XP just make it 1000/8000...
but if u god banned, dont Ask me Why :laughing:

**Comment by xxhamsterxx** [comment]
@fourmansyah How?

**Comment by P529** [comment]
Just bump up your speed to 1000Km/H and your radius to 8000Km

**Comment by xxhamsterxx** [comment]
@P529 Is this how the other bóts work?
