### ISSUE TITLE
Download Error !

### ISSUE THREAD

**Issue by Luxor1945** [Ar1i/PokemonGo-Bot#1647]
Ich kann nicht den bot downloaden. ist es nur bei mir? danke

**Comment by pokerave** [comment]
https://github.com/Ar1i/PokemonGo-Bot/archive/master.zip

**Comment by Luxor1945** [comment]
Auch Error :(

**Comment by pokerave** [comment]
Try using VPN maybe location is block

**Comment by Luxor1945** [comment]
I use VPN and i have Download Error

**Comment by supermario007** [comment]
I got the same error. I downloaded the file and instead of trying to doubleclick the .rar file i opened 7-zip, browsed to the download folder and added the file. And in 7-zip i extracted the file to a location. That works for me

**Comment by Ar1i** [comment]
^
