### ISSUE TITLE
Catching Issue on Highlevel Charakter (around 30)

### ISSUE THREAD

**Issue by Baelmung** [Ar1i/PokemonGo-Bot#1648]
Hey there Ar1i
first thanks for reupping the bot with updated API but i found a lil problem on the new version running for 3 hours now with the update 40 minutes ago on 10 accounts and found a pretty annoying error. Bot seems to not correctly using Ultraballs Greatballs and so on i know i have at least 150 ultraballs in my account and i set the bot to recycle all pokeballs and just keep 10 great balls now i let it run and it caught a whopping 0 pokemon in almost 3 hours on all 10 accounts. Seems like it always tries to use pokeballs cause after i reset it to keep 10 pokeballs too it works with some pokemon the rate is just kinda garbage like using a normal pokeball ona pidgeoto 1000´+ CP so pherhaps there is a mistake in the usage of higher balls or even a possibility to get a lil capture setting for like CP based ball usage cause atm its nice to farm items at pokestops with it but i miss the caught pokemon kinda compared to before the damn API change.
Sorry for my bad english i*m not a native its just something i realized after these few hours and yes i completely deleted the old files downloaded set up from 0 and let it run its running perfectly just the capture issue.
Thanks in advantage.

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17463902/983a8664-5cda-11e6-96dc-fd5f1b08b75a.png)
