### ISSUE TITLE
immer soft ban ......

### ISSUE THREAD

**Issue by sHaXx69** [Ar1i/PokemonGo-Bot#1649]
jede 2 min ein softban wieso = was kann ich ich machen das ich kein softban mehr bekomme hatte ich noch nie

**Comment by fourmansyah** [comment]
english please .. may be i can help u ?

**Comment by xxhamsterxx** [comment]
Ich hab nach einem levelbotgefragtundkeine hilfreiche antwort bekommen

**Comment by PoDaMo** [comment]
Und dabei hast du deine Satzzeichen verloren?

**Comment by zzzz9999** [comment]
Can you guys write EN please? 
Thanks

**Comment by marion808** [comment]
habt ihr probleme? schreibt auf english macht screenshots oder der gleichen! und wartet mal ab,
der man arbeitet tag und nacht daran um alles ins laufen zu bringen und ihr mekert nur. 
abwarten und tee trinken.

**Comment by pokerave** [comment]
#1572 - need screenshot

**Comment by SkillsPayBills** [comment]
@sHaXx69 
Versuchen Sie, die km/h senken

**Comment by P529** [comment]
@sHaXx69 Versuch doch mal deine Geschwindigkeit runterzustellen

**Comment by Logxn** [comment]
Wenn du da mit 900 km/h wie Marty McFly da durchsaust ist klar, dass du gebannt wirst

**Comment by sHaXx69** [comment]
EVERY 2 min a softban why = what I can I do that I get no more softban I had never my km / h is 30

**Comment by SkillsPayBills** [comment]
idk i think there should be an auto unban

**Comment by SkillsPayBills** [comment]
that would be amazing

**Comment by yossarianmw** [comment]
There is forum that i forgot where is..
It said there is limit speed..
Its around 10 to near 20.
The best safe play is 10km/h.
So isn't 30km/h is too fast tp get banned ?

**Comment by yossarianmw** [comment]
*to
