### ISSUE TITLE
Error  Out of Memory

### ISSUE THREAD

**Issue by NWExKraken** [Ar1i/PokemonGo-Bot#1650]
? any idea it does it after everything

**Comment by pokerave** [comment]
#1572 - need screenshot

**Comment by xlmnt** [comment]
bitdefender virüs detectec pokemongo.rocketAPI.console.exe.!!!!

**Comment by NWExKraken** [comment]
https://gyazo.com/0be1a475219951aa677580772c512895

**Comment by anindvd** [comment]
Also got the same problem. I have 18 GB free HDD space and 4 GB RAM http://puu.sh/qt1yi/08c8062347.png

**Comment by akangnduz** [comment]
try delete "sprites" folder

**Comment by teatalay** [comment]
Sprite deleting works!

**Comment by anindvd** [comment]
Works flawlessly. Thanks <3
