### ISSUE TITLE
Pokeball

### ISSUE THREAD

**Issue by CastleFan1983** [Ar1i/PokemonGo-Bot#1651]
It seems that the bot only uses the normal pokeball and not the great and ultra ball

**Comment by fourmansyah** [comment]
pokeball set cp pokemon 0-499 its using item pokeball...

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464037/9cec19f4-5cdd-11e6-8d74-17abc4264fa6.png)

**Comment by CastleFan1983** [comment]
would be nice if there were an option to change it

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
