### ISSUE TITLE
Last Build 

### ISSUE THREAD

**Issue by Praxthisnovcht** [Ar1i/PokemonGo-Bot#1652]
I get an error like this after the last update
![capture](https://cloud.githubusercontent.com/assets/9677000/17463986/b1aa9802-5c88-11e6-976e-38fae62ad975.PNG)

**Comment by marion808** [comment]
thats no error, it shows the gps data!

**Comment by xlmnt** [comment]
bitdefender virüs detectec pokemongo.rocketAPI.console.exe.!!!!
