### ISSUE TITLE
Can you add a fast level bot?

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#1654]
Can you add a fast level bot? #1646

I have seen a bot which is called spegli and it gives you 200k XP per hour.
Unfortunately that bot is not updated.
Can you also add this featrue or can you tell me a free bot which can do that?

**Comment by marion808** [comment]
dont spam!!!!!!!!!!

**Comment by fourmansyah** [comment]
if u want got many XP just make it 1000/8000...
but if u god banned, dont Ask me Why :laughing:

**Comment by Ar1i** [comment]
^
