### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Vamp1G** [Ar1i/PokemonGo-Bot#1655]
![screenshot_12](https://cloud.githubusercontent.com/assets/20889950/17464022/c11936ee-5cd4-11e6-939c-7b74f491b4df.png)

**Comment by marion808** [comment]
thats no error, just the gps data ignor it

**Comment by Vamp1G** [comment]
So i can still run the bot?

**Comment by Praxthisnovcht** [comment]
Fixed in the latest version

**Comment by marion808** [comment]
yes, redownload last version

**Comment by aljahmi92** [comment]
WHERE CAN I DOWNLOAD THE NEWEST VERSION?

**Comment by aljahmi92** [comment]
??
