### ISSUE TITLE
Virus alert on last build

### ISSUE THREAD

**Issue by xdemoor** [Ar1i/PokemonGo-Bot#1656]
Gen:Variant:Strictor.111418

Wtf ?

**Comment by downspath** [comment]
he will close this soon
last post about it (5 min ago) got closed to...

**Comment by pokerave** [comment]
because nobody reads anymore

**Comment by downspath** [comment]
but why did it recognise a virus? what kind of virus?

**Comment by Ar1i** [comment]
Its cause of the packer or because i didnt changed guid the last builds. Trying to get this false positve away. Gimme some minutes.

**Comment by downspath** [comment]
Gen:Variant.Strictor is a polymorphic virus that will infect executable files in order to spread itself on computers and network environment. Upon installation, this virus will establish a network connection so that remote attacker may gain control on the infected computer. Gen:Variant.Strictor can also steal sensitive data such as user name, password, and relevant information.

**Comment by downspath** [comment]
your computer is infected maybe? now you spread it :,D

**Comment by Ar1i** [comment]
no it isnt, just false positive

**Comment by SkillsPayBills** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/20889679/17464049/adcd7836-5d18-11e6-9ca0-302be00deadc.png)
nothing lol

**Comment by Logxn** [comment]
Bla bla bullshit.
We would never infect other computers neither would we try to harm anyone.

If you are in fear, we infected you then run an antivirus and please dont use our bot anymore.

**Comment by Bannz** [comment]
@Logxn nice respone

**Comment by pokerave** [comment]
maybe you did not wash your hands when you touch your PC and Mouse thats why the virus transferred. lol

**Comment by Ar1i** [comment]
Its false positve. Just dont use it anymore, if you dont trust us. Its from the packer, and i cant do shit about it.

**Comment by downspath** [comment]
i dont even have a antivirus programm :,D

**Comment by xdemoor** [comment]
@SkillsPayBills Bitdefender for me.

@Logxn 

Do I insult you because I asked why the files raised an alert with my AV ?!
I inform you, that's all ! If it's a false positive, it's okay. But don't be so agressive because someone (me) report a virus alert on a cheating bot and asked for an answer.

If I download and launch all cheating programs I found on internet with no AV and by trusting creators saying "We never put a virus in our app", my computer will not live long.

So.. I inform you, so you can remove that false positive if you can. That's all.
