### ISSUE TITLE
Inventory Calculate bug

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#1657]
I think its a bug. I was getting inventory full but the item count was 372. 
After that item count remains from 371-372

![image](https://cloud.githubusercontent.com/assets/14841132/17464053/798eb47e-5ca3-11e6-9445-8c33ea37a789.png)

my inventory settings looks like this 

![image](https://cloud.githubusercontent.com/assets/14841132/17464057/8b78bebe-5ca3-11e6-9a7d-46c07986c59d.png)

**Comment by Praxthisnovcht** [comment]
already, putting your total to 400.
Objects have their proper place.
you will not have more than 40 Pokeball on you if you let 40

**Comment by Ar1i** [comment]
^this

**Comment by arjunvegda** [comment]
@Praxthisnovcht Ohh yes. I know that. I forgot. Sorry.
