### ISSUE TITLE
new bot errors

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#1658]
![adsiz](https://cloud.githubusercontent.com/assets/19182149/17464066/807c2dbc-5cde-11e6-84ce-8c41f9998664.png)

**Comment by CritSin** [comment]
PLease help me every time giving google apis error why?

**Comment by Ar1i** [comment]
Download newest version

**Comment by Praxthisnovcht** [comment]
already fixed , please update

**Comment by CritSin** [comment]
ok thx
