### ISSUE TITLE
Time until lvl up

### ISSUE THREAD

**Issue by AmaliaWinter** [Ar1i/PokemonGo-Bot#1659]
Hey Folks,

short and simple question, is there any way to see which time is needed for a lvl up?
estimated time for lvl up or something like that?

ty for help :)

**Comment by DougDimmadomeOfDimmsdaleGymmadome** [comment]
Current amount of exp left to level up/xp per hour = Hours left until level up. No way to see it on the bot.

**Comment by xJustx** [comment]
^
