### ISSUE TITLE
link broken?

### ISSUE THREAD

**Issue by jivie2006** [Ar1i/PokemonGo-Bot#1661]
so i have previously been running the bot, i have watched the video several times with his how to, however when i fallow step by step i do not receive any files just the 4mb Latest Build - 07.08 19.25.rar. i cant do anything with this file. no unzip option and no program to open. i cant find what all i need to replace in the old folder to make this file work, and does not come with any supporting files. if i delete all old folders and builds, is there a direct link to replace all and start over?

**Comment by Luxor1945** [comment]
Same Problem. + problem with download
