### ISSUE TITLE
[Feature Request] Add Radius to Map Overview

### ISSUE THREAD

**Issue by godleydemon** [Ar1i/PokemonGo-Bot#1662]
We can set the radius within either the config or in the gui client, but I would like to be able to see the default location and the radius according to my set radius as like a circle or shaded area on the map. Because right now at 5k meters, the bot seems to be walking a great deal further away than I'd like. So It'd be nice to be able to see and tweak that radius to where I'd like the bot to stay in.

Awesome bot btw, really awesome. Been running it for a little while now and haven't really found to many flaws with anything.

**Comment by LMDR2016** [comment]
If you open the map locator while it is running you can view the "travel pattern" adjust your speed/distance accordingly, I am sure features to this particular function will happen at a later date. As of right now there are other bugs/issues taking precedence to fix. Also lets not push the fact the devs have been working very hard and non stop for the last few days :)

**Comment by godleydemon** [comment]
lol, yeah I know, it's just a suggestions once alot of the bugs get out of the way. :)
