### ISSUE TITLE
Simple Ask ? [quantity items]

### ISSUE THREAD

**Issue by fourmansyah** [Ar1i/PokemonGo-Bot#1663]
how much the maximum quantity of items ?
400 ???

**Comment by BigManTyrone** [comment]
350 btw not a isue

**Comment by arjunvegda** [comment]
depends on how much you have on your pokemon go account. its usually 350 if you did not upgrade it.

**Comment by fourmansyah** [comment]
thanks .. because many people ask for this, many people got items Bug ...

**Comment by arjunvegda** [comment]
checkout this issue @fourmansyah #1657
