### ISSUE TITLE
Is it possible to use it on Mac?

### ISSUE THREAD

**Issue by LaMut** [Ar1i/PokemonGo-Bot#1664]
Just want to know that ^^

Thx <3

**Comment by Greenryder** [comment]
Yes, it is. Install Windows on it.

**Comment by arjunvegda** [comment]
I have installed windows on it. And its working like charm.

**Comment by LaMut** [comment]
Hum, never did that :(
dont know how it works :$

**Comment by LaMut** [comment]
Is it possible to install windows on a small partition of my Mac without formate everything?

**Comment by BigManTyrone** [comment]
make a virtual machine with windows on it just google vmware

**Comment by arjunvegda** [comment]
@LaMut let me know if you need my help.

**Comment by LaMut** [comment]
@arjunvegda OK i'll try this one : 
http://www.cultofmac.com/307503/run-windows-10-mac-free/
What do u think about it?

**Comment by arjunvegda** [comment]
@LaMut Yeah. Follow this tutorial

https://www.youtube.com/watch?v=-TCgmY3kkC4

**Comment by LaMut** [comment]
OK ill try to understand my english not that good :p 

I'm eating and ill try it ;)

**Comment by xJustx** [comment]
^
