### ISSUE TITLE
Telegram /information fail

### ISSUE THREAD

**Issue by phil-veoo** [Ar1i/PokemonGo-Bot#1665]
/information failt ein wenig, wenn man evolve eingibt kommt trotzdem nur pokestop, ebenso mit levelup

sprich es ist irgendwie nur möglich /information für pokestops anzumachen
![ss 2016-08-07 at 07 55 41](https://cloud.githubusercontent.com/assets/15851349/17464194/feebd2d4-5cd8-11e6-834b-eaf7d3242930.jpg)

**Comment by OhhPian** [comment]
what is this ?

**Comment by mrd66** [comment]
@OhhPian Telegram API, you can get your current status etc with sending message to a bot that you created

**Comment by OhhPian** [comment]
@mrd66 how to use the telegram api ? what i need to insert at API Token and Name ?

**Comment by phil-veoo** [comment]
well there is a tutorial at the startpost on hm

**Comment by OhhPian** [comment]
@phil-veoo i never open the HM lol xD btw is it 1 telegram number for 1 account ? or can more than 1 account ?

**Comment by OhhPian** [comment]
okey thanks ^^
