### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by OhhPian** [Ar1i/PokemonGo-Bot#1666]
Is this bug or what ? The bot does prio most IV pokemon but the display seems like give wrong information, like the CP still remain the same, but the IV follows the % from the recent transfer pokemon.

![bug](https://cloud.githubusercontent.com/assets/17487706/17464186/0e625814-5d0b-11e6-816e-9970416a939d.PNG)

**Comment by phil-veoo** [comment]
the iv and cp in brackets are the stats of your best pokemon of that sort.
all is fine how it is! :)

**Comment by OhhPian** [comment]
@phil-veoo yes. but look at the bulbasaur. The highest IV should be 65%, but somehow it drop to 24% then 23%. It might be not a big deal since not effect my pokemon, but i just report this bug. Thats all :)

**Comment by phil-veoo** [comment]
looks like you have enabled that Bulbasaur should be transfered auto.

**Comment by OhhPian** [comment]
idk how to say this maybe this somekind of miscalculation info. not because of auto transfer

**Comment by eliteknight** [comment]
Its no bug!
In your options you have set keep all Pokemon over 999 cp? and 90+% IV
Your best Pokemon is 137, and no other is 90+%.
So he auto transfer the Pokemon with "best" CP with 65%...is less than 90 and is not retained!

**Comment by OhhPian** [comment]
@eliteknight This is my setting. 

![bug1](https://cloud.githubusercontent.com/assets/17487706/17464360/2dbe19a6-5d0f-11e6-96c4-6f586a6a5583.PNG)

**Comment by eliteknight** [comment]
its works correct.
No Pokemon is over 1500 CP and no one over 95%.
So he keep only the Pokemon with most CP.
By your Bulbasaur is it with 146CP and all other are auto transfer.
The IV drop down because it transferred the 65% IV Pokemon and after this the 24% IV Pokemon.
But he keep the 146CP Pokemon.

**Comment by pokerave** [comment]
download the latest version
