### ISSUE TITLE
BUG - LastCoords.txt is not read at start

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#1669]
To avoid softban, I used to edit lastcoords.txt to a known position before launching the bot.
Then I could set location as the destination, with a speed of 25 km/h ... and it was fine.
Now the location we set from the GUI is the the start point ... not the destination.

Thanks

**Comment by xJustx** [comment]
The LastCoords.txt was deleted. You can't use this anymore
