### ISSUE TITLE
No issue: but a tipp to hide that you used a bot.

### ISSUE THREAD

**Issue by downspath** [Ar1i/PokemonGo-Bot#1671]
Somebody asked how to decrease the "pokestops visited" and increase "pokemon caught", just make your char slower (about 5 to 10 kmh) now you encounter more pokemon.

I know the bot will have les exph but it would be obvious anyway if you level up 3 level a day righ? :D

**Comment by lailaps** [comment]
You can't hide, because it's connection via API sending fake requests. ;)
Atm. everybody is using the same device on IOS.

**Comment by downspath** [comment]
edit: i meant : hide it in your archievements

**Comment by xJustx** [comment]
No issue - I have to close it, sry
