### ISSUE TITLE
Error JSON

### ISSUE THREAD

**Issue by Emmi911** [Ar1i/PokemonGo-Bot#1673]
http://fs5.directupload.net/images/160807/6lvqw83f.jpg

**Comment by k0bra1** [comment]
Same here....

**Comment by Ar1i** [comment]
taking a look

**Comment by CritSin** [comment]
same here

**Comment by downspath** [comment]
me to suddenly

**Comment by downspath** [comment]
all 3 bots i have running got it at about the same time
i closed them

**Comment by lailaps** [comment]
What did you changed in last update @Ar1i?
I am still using the version before and have >70.000 xp/h on accounts >level 33.

**Comment by CreatorSky** [comment]
@lailaps which version are you using ?

**Comment by k0bra1** [comment]
@lailaps Wtf how are ur settings.... maximum i get 50.000 xp/h

5000m circle
50 km/h

**Comment by SkillsPayBills** [comment]
@Ar1i is it possible to have an automatic force unban?

**Comment by downspath** [comment]
it has an automatic force unban, it just needs time to recognise @Ar1i

**Comment by SkillsPayBills** [comment]
oh ok

**Comment by Emmi911** [comment]
@Ar1i Also bevor dein 'security' update raus kam lief der bot noch einwandfrei ohne error.

**Comment by NidiKea** [comment]
hier auch , same here whats the matter, also was ist los?
Ja genau vor dem Update war alles super

**Comment by NidiKea** [comment]
![image](https://cloud.githubusercontent.com/assets/20837963/17464351/a4e76092-5cdc-11e6-953e-e48cec14cedd.png)

**Comment by NidiKea** [comment]
Kann es ein Windows 10 Problem sein? Ich nutze Windows 10 und er 7, bei ihm geht es bei mir nicht

**Comment by k0bra1** [comment]
Hab das selbe Problem, mir ist aufgefallen das ganz oben steht "System.ArgumentNullException: Der Wert darf nicht null sein. Allerding hab ich null Plan was das bedeutet.

-> Benutze Windows 7 und es funktioniert auch nicht.

**Comment by Ar1i** [comment]
try and give me a anwser if it works

**Comment by NidiKea** [comment]
oh nichts ist ok hier 
![image](https://cloud.githubusercontent.com/assets/20837963/17464388/5ac60184-5cdd-11e6-9e2f-6c2f6182c58a.png)

**Comment by untesty** [comment]
It's working. Great job mate!

**Comment by markyudan5** [comment]
looks good  for me now

**Comment by Ar1i** [comment]
@NidiKea komm.. da steht BadAuthentication = Falscher Login. Daten wahrscheinlich falsch...

**Comment by Ar1i** [comment]
Okay good, closing this then.

**Comment by NidiKea** [comment]
Ja, auch gemerkt...man sollte auch nicht seine GMX Email angeben. Sorry, hab ich schon gelöscht den Kommentar. Es klappt wunderbar danke für die schnelle Hilfe

**Comment by lailaps** [comment]
@k0bra1
49 km/h 5000m
Running on OVH dedicated server
