### ISSUE TITLE
Dauernd nur noch weisse Schrift wieso das

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#1677]
Ich habe auf einmal mitten beim Lauf nur noch weisse Schrift...dann wieder 10 Sekunden warten dann wieder das:
![image](https://cloud.githubusercontent.com/assets/20837963/17464287/89616aee-5cdb-11e6-848d-42434349ad18.png)
was bedeutet das denn?

**Comment by k0bra1** [comment]
#1673 Wird hier gerade diskutiert, laut Ar1i schaut er sich es gerade an.

**Comment by NidiKea** [comment]
ok sorry aber bei den ganzen Posts weiss ich gar nicht wo es um was geht

**Comment by NidiKea** [comment]
Ich nutze Windows 10 und es geht nicht mehr, mein Partner Windows 7 und es geht. Also eventuell ist es ein Windows 10 Problem?
