### ISSUE TITLE
Pokemon Nest

### ISSUE THREAD

**Issue by YakuzaR** [Ar1i/PokemonGo-Bot#1678]
Does anyone know a few Nests with Location/coord ? 
Or do you know a Website who Shows it??

Hat jmd ne Ahnung, wo sich aktuell die Nester befinden??
Oder kennt ihr ne Seite, die mir das zeigt?

Greetz xP

**Comment by k0bra1** [comment]
-> Nicht 100% safe, allerdings hab ich gesagt bekommen das man vieles in Santa Monica bekommen soll.
Meist Elektek.... etc, hab es allerdings nicht selbst probiert.

**Comment by Sora1724** [comment]
I know a Charmander nest in Cologne Germany. Check Aachener Weihe/Innerer Grüngürtel

**Comment by YakuzaR** [comment]
Danke,  ich werde mal Ausschau halten. (y) 💃

**Comment by BigManTyrone** [comment]
milaan italy charmander nest in the park

**Comment by Kahjo** [comment]
Charmander: 40.7467367607185 , 40.7467367607185 (Flushing Meadows Corona Park)

**Comment by YakuzaR** [comment]
u got maybe a few coord for me? langitude and longitude?

**Comment by SkillsPayBills** [comment]
use the default location that has some good pokemon

**Comment by LMDR2016** [comment]
http://pkmngotrading.com/wiki/Nests - verified and working for me, hope this help you in your search.

**Comment by YakuzaR** [comment]
Thx!
