### ISSUE TITLE
Keine LastCords mehr im config Ordner

### ISSUE THREAD

**Issue by BadassTK** [Ar1i/PokemonGo-Bot#1679]
Sooo , so viel ich gemerkt habe speichert er keine letzten Koordinaten mehr,
meine frage ist werden die jetzt von selber gelöscht (weil nach neustart des bots ist die Lokalisierung wieder auf New York Central Park).
im Config Ordner ist noch ein Confog.txt dort stehen halt meine Daten drin bzw. auch Koordinaten 
soll man die jetzt da raus löschen oder werden die Koordinaten automatisch selber gelöscht??

 Vielen Dank im vorraus

**Comment by LMDR2016** [comment]
http://pkmngotrading.com/wiki/Nests - have verified a few near me that are actually still up and running well. 

Hope this helps in your search.

**Comment by LMDR2016** [comment]
Es wäre ratsam, die "letzte weiß coords " aus der confige Datei zu löschen, bevor die App zu vermeiden Sie softbans verwenden.

**Comment by xJustx** [comment]
lastcords wurden entfernt
