### ISSUE TITLE
Errors, after latest update

### ISSUE THREAD

**Issue by Kahjo** [Ar1i/PokemonGo-Bot#1681]
Sup. Getting these errors after the latest update. Fix pls :-1: 
https://pbs.twimg.com/media/CpRpukMWgAAKiWR.jpg

**Comment by Ar1i** [comment]
already opened, read.

**Comment by xlmnt** [comment]
pls scan file because bitdefender saying. virüs detectec!!!. gen:Variant.Strictor.111418
