### ISSUE TITLE
file can not be transferred

### ISSUE THREAD

**Issue by Blooddrek** [Ar1i/PokemonGo-Bot#1683]
when I downloaded the file, there is no problem
when I want to transfer the console file is not transferred, even if I can and I run the application it disappears

**Comment by Kibrisli** [comment]
![image](https://cloud.githubusercontent.com/assets/20828201/17464380/833a9c58-5ce5-11e6-92ae-60605e26a300.png)
Help pls.. i updated the new one that u updated Ar1i and that happend, any suggstions ?

**Comment by Ar1i** [comment]
@Kibrisli #1673 .....

**Comment by Ar1i** [comment]
Try another browser.

**Comment by Kibrisli** [comment]
Sry, downloading new one, Thank you Ar1i :)
