### ISSUE TITLE
No Poke-stops within 5000M

### ISSUE THREAD

**Issue by jmaines2** [Ar1i/PokemonGo-Bot#1684]
I'm still not collecting from any Poke-stops. It seems that they can be located; but all show none in range/none unused:
![image](https://cloud.githubusercontent.com/assets/15603277/17464352/9fcd632e-5c99-11e6-8362-d378a2aa3100.png)

**Comment by Ar1i** [comment]
Use the Build Version, and make sure your location is right.

**Comment by jmaines2** [comment]
Thanks! I used the Build Version ( Latest Build - 07.08 21.04 ) but it
seems to be just the location I've selected on the map. Some of the western
states in the U.S. still show the error. It must be something with the
Google map API. I'll just watch for updates.
