### ISSUE TITLE
Items not correct

### ISSUE THREAD

**Issue by Jacowork** [Ar1i/PokemonGo-Bot#1686]
When I empty my items on my phone and close the app.
I go to the bot and run it, but the number of items stays at it's max.
It doesn't update to the correct amount.

Is this an issue or just me?
Thx for the great work guys.

**Comment by Ar1i** [comment]
Its cause of caching, need some time then it should be updated.

**Comment by gahget** [comment]
This is not working for me, what can be the problem? Always restarting.

**Comment by gahget** [comment]
Ten minutes ago it was working.What is the problem? Api chanced again?
