### ISSUE TITLE
"Error reloading Pokemon List: NeedsBrowser" what it mean?!/ was bedeutet das?!  HELP

### ISSUE THREAD

**Issue by ShaaiLo** [Ar1i/PokemonGo-Bot#1687]
![unbenannt](https://cloud.githubusercontent.com/assets/20891139/17464353/c35b2c34-5cdc-11e6-8f78-53b0f4ee93c6.png)

"Error reloading Pokemon List: NeedsBrowser" 

Did anyone knnow how to fix this ?!
weiß einer wie man das fixen kann?!

**Comment by Ar1i** [comment]
Create a password here, and use it instead of your normal one. https://security.google.com/settings/security/apppasswords

**Comment by ShaaiLo** [comment]
i did but the error is still there.
