### ISSUE TITLE
can´t find any pokestops

### ISSUE THREAD

**Issue by Hazuke1337** [Ar1i/PokemonGo-Bot#1689]
it can´t find any pokestops nearby: http://scr.hu/0qr65/bdyl3
 
and yes i have the new Build : http://scr.hu/0qr65/qljcs

**Comment by Ar1i** [comment]
Its not the latest, change your location

**Comment by Hazuke1337** [comment]
god damn i´m a fcking idiot sorry bro but also thanks for all u did for the bot and for us :+1:

**Comment by lucas2107** [comment]
Working for me ^^
