### ISSUE TITLE
Auto Incubating not working please fix

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#1690]
i tested it it doesnt work.It does not auto incubate,so we have to sign back on and do it ourselfs and let it hatch please fix this ar1i.Its not working im 100% sure

**Comment by LMDR2016** [comment]
Devs are looking in to this issue, will be updated soon. be patient.

**Comment by beasttry** [comment]
im more than patient i just wanted to make sure they knew about this issure lmdr2016
