### ISSUE TITLE
Reduce RAM?

### ISSUE THREAD

**Issue by Psycherl** [Ar1i/PokemonGo-Bot#1693]
Engl:
The bot needs alot of RAM. It seems that the RAM used/bot is stacking, so at any time RAM will be at 100%. If you got many instances running, the used RAM is going insane.

DE:
Der Bot benötigt eine Menge RAM. Umso länger er läuft, desto mehr RAM pro Bot-Instanz wird benötigt. Der RAM-Wert pro Bot erhöht sich also stetig. Wenn man mehrere Bots am laufen hat, so erreicht der Arbeitsspeicher früher oder später 100%. Gibt es eine Möglichkeit das zu unterbinden?

**Comment by lucas2107** [comment]
Hi, the bot is using 32Mo of ram for me. I'm running it as administrator, maybe it can help you?

**Comment by Ar1i** [comment]
http://i.imgur.com/dVtGP14.png 40mb - probably your fault

**Comment by Psycherl** [comment]
Watch it, it increases

**Comment by ScriptingNik** [comment]
This is only a problem with Multi instances

**Comment by ScriptingNik** [comment]
Single instances keep around 29-32Mb

**Comment by Krypton00** [comment]
I have about 20 Instances every Instance needs 20-25 mb

**Comment by PlsTarget** [comment]
http://image.prntscr.com/image/5872e2485465438f850c1eeb26b87371.png

**Comment by 13XxM1CHA3lxX37** [comment]
![2016-08-07 21 21 48](https://cloud.githubusercontent.com/assets/20713070/17464679/201038b8-5ce5-11e6-8ee2-123b383e3f13.png)

**Comment by Psycherl** [comment]
....i guess i have to uprade my v-server-RAM then :-D

**Comment by asfo** [comment]
If you have "Reload every X seconds", then, disable it or change it...that happened to me if i had "60" in "X". I don't know why but it wasted like 25gb of RAM :p then I change X to 300 and now is fine.

**Comment by Psycherl** [comment]
found another solution:
create ".vbs" with "FreeMem = Space(500000000)" and run that in task-scheduler every 10 minutes. This clears 500MB of RAM all 10 Minutes.

**Comment by asfo** [comment]
Just don't enable the "reload every X seconds" or change the X to a big number, this is the RAM after 3 hours with "Reload every 300 seconds"
![captura](https://cloud.githubusercontent.com/assets/829964/17466121/a804f262-5ccd-11e6-8255-d378b63b2aa7.PNG)
