### ISSUE TITLE
Can't open "PokemonGo.RocketAPI.Console.exe" 

### ISSUE THREAD

**Issue by BluCone** [Ar1i/PokemonGo-Bot#1694]
I'm trying to open this PokemonGo.RocketAPI.Console.exe but its not working, nothing happeneds. Pls help, im using 7ZIP, should i use winrar?

**Comment by lucas2107** [comment]
Hi,

Create a folder and extract all the archive in and try to run it as administrator

**Comment by Zuldar** [comment]
for me it's say : files infectd by variant strictor 111418. 

same issue
