### ISSUE TITLE
Unbanning method

### ISSUE THREAD

**Issue by madeinyashiro** [Ar1i/PokemonGo-Bot#1695]
Hi,

Since i've started to use the new bot (20.02) it can't unban my account and I miss all catch

Is there a solution ? Force Unban won't work

**Comment by Hazuke1337** [comment]
i dont even find force unban xD

**Comment by xiannny** [comment]
just miss catch or cant farm either ??

**Comment by madeinyashiro** [comment]
Miss catch all time

**Comment by cristianst** [comment]
Open a poke stop and spin it .
Do this several times until you get the items. That method works always for me

**Comment by madeinyashiro** [comment]
It works for me, but the bot still wont work

**Comment by xJustx** [comment]
Click the unban button in the pokemonlist

**Comment by Mancuz** [comment]
"force unban" button , not work

**Comment by draga123** [comment]
Is your pokeball set to 0? If so set it to 10 and you should be able to catch Pokemon again.

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464607/4a5fa256-5ceb-11e6-92ff-73633ce31786.png)

**Comment by madeinyashiro** [comment]
Ohh.. I feel so stupid. Thanks Its fixed
