### ISSUE TITLE
Cant Catch pokemon

### ISSUE THREAD

**Issue by xiannny** [Ar1i/PokemonGo-Bot#1696]
Im I the only one around here, who can farm Pokestops (Probably not softbanned) but still cant catch anything ?? 
Everything just got away. (In the bot)
Pokemon Per hour =0
Running it for like an hour now.

**Comment by thecoldblooded** [comment]
I have the same issue!

**Comment by draga123** [comment]
I just posted about this....

Solution: Is your Pokeball set to 0? If so set it to 10, and it should work.

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464603/38e2e9de-5ceb-11e6-866f-004f1d973eba.png)

**Comment by xiannny** [comment]
thanks guys

**Comment by Drakoo2** [comment]
i got pokeballs set to more than 10 but still doesnt work please help me
