### ISSUE TITLE
All Pokemon run away (But gaining items from Pokestops)

### ISSUE THREAD

**Issue by draga123** [Ar1i/PokemonGo-Bot#1697]
Hi,

For some reason any Pokemon i try to catch runs away? Even though im not soft banned because im still gaining items from poke-stops.... Ive also set my item bag to 0 pokeballs and instead use great balls/ ultra balls, but according to the GUI, its using pokeballs?

I have tried to delete and re-download as well.

Any suggestions?

![example](https://cloud.githubusercontent.com/assets/20891312/17464434/e94b8746-5d21-11e6-9527-dfed15f17769.png)

**Comment by rainkeel** [comment]
you softbanned

**Comment by draga123** [comment]
I can't be soft banned if im still gaining items from Poke-Stops...

**Comment by xiannny** [comment]
same problem here.

**Comment by lucas2107** [comment]
Hi, have you tried to slow down ? i'm at 14km/h and it's working fine.

**Comment by jmo93** [comment]
Do you set normal pokeball to 0?

**Comment by draga123** [comment]
Yes Pokeballs are set to 0

Ive also checked my journal, and usually it says if a Pokemon has run away, but the journal shows none of the Pokemon the GUI is claiming have run away. Example: The Zubut with CP 125 should be in the journal but its not there, nor is any of the other Pokemon that have claimed to run away.

**Comment by jmo93** [comment]
Thats the mistake. Set it to 10 .

**Comment by draga123** [comment]
There for i think it might have something to do with throwing Pokeballs which aren't in the inventory itself? As you can see Pokeballs were recycled at 4:35.21 (there for going by my settings there should be 0 pokeballs left) But then the bot is still claiming that its throwing Pokeballs to catch the pokemon... rather than throwing Great balls/Ultra Balls...

I just changed the settings and put 10 pokeballs, Pokemon are now being caught.... 

So the only thing you can use to catch pokemon is Pokeballs? Not Great/Ultra balls?

**Comment by VNRG** [comment]
its a bug i guess, because in the old version, the bot has used great/ultra ball if there was no pokeball left
