### ISSUE TITLE
Can't run multiple bots at the same time? (Different accounts)

### ISSUE THREAD

**Issue by sandor111** [Ar1i/PokemonGo-Bot#1698]
Can't run multiple bots at the same time? (Different accounts)

**Comment by xiannny** [comment]
tryed different folder ??

**Comment by sandor111** [comment]
Yes

**Comment by DargQ** [comment]
Im runing 3 Bots at the same time.

**Comment by sandor111** [comment]
oh

**Comment by sandor111** [comment]
I will try again with the updated version

**Comment by xiannny** [comment]
well. it woks fine with me, exept i cant even catch a  fucking weedle with 10 cp .....

**Comment by DargQ** [comment]
All in the same folder and everything.

**Comment by xiannny** [comment]
folder in different location ?
try different partition

**Comment by sandor111** [comment]
I get this error http://imgur.com/ZMqmhXi

**Comment by pokerave** [comment]
TRY THIS 
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464505/0928910a-5ce9-11e6-9795-e0543b4c31fe.png)

**Comment by sandor111** [comment]
What?

**Comment by sandor111** [comment]
I didn't change any settings

**Comment by sandor111** [comment]
The error is:

**Comment by sandor111** [comment]
Export player infos and all pokemons to CSV not possible. File seems to be in use!

**Comment by sandor111** [comment]
http://imgur.com/LL2AH93

**Comment by sandor111** [comment]
I am running 2 bots

**Comment by sandor111** [comment]
In 2 different files

**Comment by pokerave** [comment]
2 different file folders? try restarting ur pc the csv file seems lock

**Comment by sandor111** [comment]
ok

**Comment by Krypton00** [comment]
I run 20 Bots without one error.
