### ISSUE TITLE
Rauch, Glückseier über Telegram aktvieren

### ISSUE THREAD

**Issue by Dmnation** [Ar1i/PokemonGo-Bot#17]
/smoke oder /egg zur Aktivierung von Rauch bzw. eines Glücks-Ei's.
Eventuell mit einem Integer versehen => /smoke 4 <= besagt, das er 4x Rauch nachzünden soll, wenn die halbe Stunde rum ist, bzw /smoke 99 als Angabe, damit er so lange Rauch an macht, wie man noch welchen hat. Umgekehrt auch für das Glücks-Ei sinnig :)

**Comment by bamoas** [comment]
Ich weiß zwar nicht wie es geht, aber bin voll deiner meinung, sehr gute idee. Wollte auch gestern rauch an machen, aber über Handy ohne GPS klappt es leider iwie net.

**Comment by Dmnation** [comment]
Genau das ist es!
Habe meistens wenn mein Account am botten ist natürlich das GPS aus um Eier zu aktivieren.
Rauch und Glücks-Eier gehen leider nur, wenn man das GPS an hat und glaube Telegram ist eine gute Option, das ganze zu bewerkstelligen.

Alles in allem ist der Coder auch einfach top, so schnell neue Updates und Features ist schon Wahnsinn.
