### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by torani** [Ar1i/PokemonGo-Bot#1700]
![360 16180929536994](https://cloud.githubusercontent.com/assets/20891215/17464418/c2197784-5d10-11e6-8530-0306ac74abbe.png)
 
Encounter Pokemon fled but Pokestops can be farmed. How to resolve this?

**Comment by arricie** [comment]
set basic pokeball to 50 and be calm..

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464610/5d432d52-5ceb-11e6-948c-2971b6a83e1c.png)
