### ISSUE TITLE
Bugs.

### ISSUE THREAD

**Issue by SkillsPayBills** [Ar1i/PokemonGo-Bot#1701]
![screenshot_3](https://cloud.githubusercontent.com/assets/20889679/17464446/1ce08ff2-5d22-11e6-8ba8-5b25afa0b0b3.png)
Pokemon on the pokemon list keep flashing (Error reloading Pokemon list: Out of memory)
![screenshot_1](https://cloud.githubusercontent.com/assets/20889679/17464453/5b7f861e-5d22-11e6-9fd4-34f281bd3707.png)
^ This bug still exists

**Comment by marcop888** [comment]
yeah me too
