### ISSUE TITLE
ERROR PLS HELP

### ISSUE THREAD

**Issue by ShaaiLo** [Ar1i/PokemonGo-Bot#1702]
![unbenannt](https://cloud.githubusercontent.com/assets/20891139/17464454/5824ed8a-5cdf-11e6-81fc-c077d712300d.png)

"Error reloading Pokemon List: NeedsBrowser"

Did anyone knnow how to fix this ?!
weiß einer wie man das fixen kann?!

**Comment by lucas2107** [comment]
Hi, have you extracted all the archive and running the console as administrator?

**Comment by ShaaiLo** [comment]
yes i did

**Comment by marcop888** [comment]
10 mnts fine and then that's happen

**Comment by Ar1i** [comment]
https://security.google.com/settings/security/apppasswords
Create a password there, and use it instead of your normal one

**Comment by ShaaiLo** [comment]
Ar1i  did it already but didnt work for me

**Comment by acelya** [comment]
same error every 5 minutes and i cant create a password at https://security.google.com/settings/security/apppasswords
