### ISSUE TITLE
[feature suggestion] per hour counter

### ISSUE THREAD

**Issue by computer101dude** [Ar1i/PokemonGo-Bot#1703]
I think it would be useful to add a counter that shows EXP per hour, star dust per hour and pokemon caught per hour, it could update it self at will in the console  and would give us ideas on where better farming spots are. I can understand if there are more pressing issues to deal with or if this isn't even something that you think necessary. - cj

**Comment by LMDR2016** [comment]
it does have a stats counter though? ..... look at your top action bar on the scrolling stats page? ... 
![stats counter](https://cloud.githubusercontent.com/assets/20846055/17464464/063aee3c-5ca5-11e6-8617-c18dd99a3172.PNG)

**Comment by LvGPoke** [comment]
Yeah -... if you have the pokemon per hour you have the stardust per hour aswell ... 
(pokemon/hour)*100

**Comment by computer101dude** [comment]
I did not notice that before

**Comment by OfficialMT22** [comment]
looked better before cause everything was wordwrap. Now its kinda clustered together

**Comment by AmaliaWinter** [comment]
Wait... am i blind? Where exactly do i have to look for these information i have only:
[20:48:52] -----------------------[PLAYER STATS UPDATE]-----------------------
[20:48:52] Level/EXP: 23 115.158/125.000 (92,13%) EXP to Level up: 9842
[20:48:52] PokeStops visited: 2488 KM Walked: 106,091
[20:48:53] Pokemon: 194 + 9 Eggs /250 (0 Evolvable)
[20:48:53] Items: 428/450 Stardust: 11.804
No xp/h :/ etc.

**Comment by computer101dude** [comment]
it's at the top of the console

**Comment by AmaliaWinter** [comment]
Ah ty :) i'm really blind

**Comment by pokerave** [comment]
yup
![tut1](https://cloud.githubusercontent.com/assets/20603254/17464518/874d947c-5ce9-11e6-8b40-3846e363d48b.png)

**Comment by computer101dude** [comment]
I was the one who started this, I am the blind one here XD

**Comment by computer101dude** [comment]
also pokerave central park NY is giving me and my friend 100k+ xp per hour I See your getting 30k+

**Comment by xJustx** [comment]
^
