### ISSUE TITLE
Can't open "PokemonGo.RocketAPI.Console.exe" 

### ISSUE THREAD

**Issue by BluCone** [Ar1i/PokemonGo-Bot#1704]
I'm trying to open this PokemonGo.RocketAPI.Console.exe but its not working, nothing happeneds. Pls help, im using 7ZIP, should i use winrar? If I extract it to a folder the "PokemonGo.RocketAPI.Console.exe" is gone. It doesnt exist anymore than :/ pls help

**Comment by OfficialMT22** [comment]
if it doesnt extract with all the other files, sounds like a antivirus thing on your pc

**Comment by eliteknight** [comment]
antivir tool?

**Comment by computer101dude** [comment]
download the latest build, extract the contents into a folder and find the console application, it should have a pokeball next to it and you double click to run. if that doesn't work then run as admin, if that doesn't work it's your PC

**Comment by BluCone** [comment]
I closed the antivirus

**Comment by eliteknight** [comment]
loading the new package and looking in there

**Comment by pokerave** [comment]
extract all files not only the exe.

**Comment by BluCone** [comment]
its working ^^

**Comment by xJustx** [comment]
^
