### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by hxps** [Ar1i/PokemonGo-Bot#1705]
The new API is not flag-proof(at least not like the older one) and everyone that is using the updated bot with new API is supposedly playing through the same IOS phone, which is, basically like handing our corrupted accounts to niantic. Don't get me wrong though, I appreciate all the efforts for bringing back the bot, we are all happy and thankful but I understand it is the new API we have right now. My question is, is there would be any updates in the near future that can secure our accounts a little bit more? And if my ignorance is just too much, then please, explain us how your bot will not get us flagged because everyone knows there's a ban hammer comming, like it happened in ingress.

**Comment by downspath** [comment]
hxps, does it mean we are all sending the same iphone ip to niantic? omg

**Comment by hxps** [comment]
https://m.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?utm_source=mweb_redirect&compact=true 

With the new API we're all playing through an IOS user.

**Comment by hxps** [comment]
@Ar1i
