### ISSUE TITLE
Some Pokemon will do be transfered

### ISSUE THREAD

**Issue by PlsTarget** [Ar1i/PokemonGo-Bot#1706]
Some Pokemons will not be transfered. I have Max. dubblicate on 2 but have more than 2:

NidoranFemale
Pidgey
Rattata
Exeggcute
Weedle

**Comment by OfficialMT22** [comment]
manual transfer then it should correct itself

**Comment by pokerave** [comment]
uncheck "keep evolbable pokemon"

**Comment by xJustx** [comment]
^
