### ISSUE TITLE
Restarting all the time...

### ISSUE THREAD

**Issue by hydroenergy18** [Ar1i/PokemonGo-Bot#1708]
It restarting all the time and nothing happens...

**Comment by pokerave** [comment]
Screen Shot.

**Comment by hydroenergy18** [comment]
![bot](https://cloud.githubusercontent.com/assets/20891432/17464509/b62e8eb2-5ce0-11e6-8bca-edf737b0db6e.PNG)

**Comment by Ar1i** [comment]
using newest version?

**Comment by willdanzabir** [comment]
yes

**Comment by hydroenergy18** [comment]
i downloaded today :D

**Comment by willdanzabir** [comment]
same me too

**Comment by Ar1i** [comment]
Try the normal version, if normal not work try the other one
