### ISSUE TITLE
Exception: System.argumentnullexception: value cannot be null

### ISSUE THREAD

**Issue by BlakeNightgale** [Ar1i/PokemonGo-Bot#1709]
![image](https://cloud.githubusercontent.com/assets/20830278/17464475/3161717e-5ce8-11e6-968d-4e322c82bd2b.png)

any suggestions ? :c

EDIT: Updating to 07.08 20.25 fixes this issue, will edit this further if problems reoccurs.

**Comment by kalcheat** [comment]
got the same

**Comment by swtrpeter** [comment]
+1

**Comment by SkillsPayBills** [comment]
Only thing we can do I wait

**Comment by pokerave** [comment]
does it continue afterwards?

**Comment by Ar1i** [comment]
dont know why that happens atm, rolling back an update..

**Comment by untesty** [comment]
Do you guys have the latest version? Because I had this before and now I'm just fine

**Comment by eliteknight** [comment]
continue afterwards? i think...or no?

**Comment by Ar1i** [comment]
what version do you guys use? newest?

**Comment by M31860** [comment]
@Ar1i
Yes the newest.

**Comment by jmo93** [comment]
Newest version , same problem

**Comment by Ar1i** [comment]
Uploading a fix version, if normal version is not working for you guy

**Comment by uchitake84** [comment]
Guys please update to 07.08 20.25 version,this work fine for me

**Comment by jmo93** [comment]
ok thanks

**Comment by BlakeNightgale** [comment]
I'm using the newest version, today after updating was working fine and now it started to happen. and it keep cycling for ever.

**Comment by swtrpeter** [comment]
Using the latest and that fixed my issue

**Comment by LMDR2016** [comment]
I get that error then it restarts after 10 seconds, ? happen randomly

**Comment by M31860** [comment]
@LMDR2016 
unpack the fix archive

**Comment by BlakeNightgale** [comment]
@Ar1i I think it's a problem related to using the map icon
![image](https://cloud.githubusercontent.com/assets/20830278/17464626/07c643c2-5cec-11e6-9462-06cde83939ab.png)

**Comment by Ushushu** [comment]
Fix not work for me. Still got the same error. I can see altitude not work, can be a clue ?

**Comment by Ar1i** [comment]
@Ushushu exactly error?

**Comment by Ushushu** [comment]
Got the grey error about "null" but that work alone now. :)
