### ISSUE TITLE
Still can´t find any Pokestops

### ISSUE THREAD

**Issue by Hazuke1337** [Ar1i/PokemonGo-Bot#1710]
Same problem but could it be that i have a Softban? what would it say when i have a soft-ban?

**Comment by pokerave** [comment]
you wont get XP from pokestop and cant catch pokemon, if you cant see pokestop transfer to another state and try that.

**Comment by Hazuke1337** [comment]
k thanks
i try. don´t close the issue Ar1i

**Comment by Hazuke1337** [comment]
nope nothing happend it only says that there is no pokestop 5000m nearby

**Comment by Ar1i** [comment]
switch location should fix that
