### ISSUE TITLE
Can't use bot outside from Central Park.

### ISSUE THREAD

**Issue by ShujiYagami** [Ar1i/PokemonGo-Bot#1712]
I want to use my city to farm, using one of the "nest" but in this new version and old version never let me do it.

The other account I have is working with the SAME configuration except for the location. So wich could be the problem?

![123](https://cloud.githubusercontent.com/assets/20828891/17464494/ac185bfa-5ca5-11e6-9ad4-066dc6aa9d9d.PNG)

**Comment by pokerave** [comment]
Change the default location in the config folder, config.txt file

**Comment by Ar1i** [comment]
cause servers are down there probably

**Comment by ShujiYagami** [comment]
Change config.txt file and enter to the account on my phone. Servers are Up :(
