### ISSUE TITLE
Error Reloading pokemon list: -----------------------

### ISSUE THREAD

**Issue by Vessi15** [Ar1i/PokemonGo-Bot#1714]
![untitled](https://cloud.githubusercontent.com/assets/20891488/17464516/0aebdec8-5ce1-11e6-81db-48ae69c90b10.png)

**Comment by pokerave** [comment]
you have the latest version?

**Comment by Vessi15** [comment]
Yep..

**Comment by bluezerodany** [comment]
its because you put the wrong email or password

**Comment by Vessi15** [comment]
Nope, I didn't. It's PTC tho. But I didnt put in anything wrong

**Comment by alchem9st** [comment]
I'm also facing this with google account, anyone ?

**Comment by miguellm86** [comment]
same to me and  when i disable the pokemon GUI i obtain  the next error 
![image](https://cloud.githubusercontent.com/assets/20747838/17464791/9ad7e4bc-5cac-11e6-8477-02df6059e1ae.png)

**Comment by levalbe** [comment]
same error for me too

**Comment by Vessi15** [comment]
Anyone know whats wrong?
