### ISSUE TITLE
Displays wrong IV

### ISSUE THREAD

**Issue by VNRG** [Ar1i/PokemonGo-Bot#1715]
http://puu.sh/qt5vk/dde1216834.png

System says that it has 98% (15-15-7)
but it is wrong, the actual value is 82%

would be nice if that get fixed soon, otherwise the bot might transfer some pokemon for some ppl, which they didnt want

**Comment by pokerave** [comment]
i thinks theres a computation for that, with HP, CP

**Comment by VNRG** [comment]
i know and it is wrong, because in the old version, it got displayed as 82% which is correct and i have calculated with this page https://pokeassistant.com/main/ivcalculator again:

name: chansey
cp: 459
Stardust: 3500
HP:331

->IV 82.2%

**Comment by arjunvegda** [comment]
#1660
