### ISSUE TITLE
[Minor Defect] Leveling Up text.

### ISSUE THREAD

**Issue by b3shoy** [Ar1i/PokemonGo-Bot#1716]
When i got leveled up, the level up text is appearing after each an every stats update.
![capture](https://cloud.githubusercontent.com/assets/20810298/17464537/8c70ead8-5ce1-11e6-8b4a-595344f05c83.PNG)

Guys, You are really Stupendous! :pray:

**Comment by xJustx** [comment]
Try to restart your bot please.

**Comment by Ar1i** [comment]
fixed in an update, got the error thanks for reporting

**Comment by Krypton00** [comment]
what should that mean? more random?

**Comment by arjunvegda** [comment]
@Ar1i 
Its still there (I am using latest version)


![image](https://cloud.githubusercontent.com/assets/14841132/17465656/0fcab00a-5ccc-11e6-9b49-6c20d6c8fa5f.png)

**Comment by luchitobw** [comment]
not catch pokemons! :S

**Comment by zerroc** [comment]
Intendet not catching anything? allready forced an unban

![poke](https://cloud.githubusercontent.com/assets/20893980/17466034/f5cba2b0-5d05-11e6-9592-2807b55501d9.png)

**Comment by bluecito** [comment]
Dont work again https://postimg.org/image/nrzff2rtd/

**Comment by jimboozx** [comment]
yeah, not work again
we cant find any pokestop

**Comment by bluecito** [comment]
![sin titulo - copia](https://cloud.githubusercontent.com/assets/20894080/17466110/e09ed93c-5d07-11e6-8687-c8b3113c4c58.jpg)

**Comment by bluecito** [comment]
![dfdfdf](https://cloud.githubusercontent.com/assets/20894080/17466115/14c16cc0-5d08-11e6-97ce-e4064ab2c2dc.jpg)

This happends,

**Comment by bluecito** [comment]
if I find I pokestops but  falls every 2 Minutes

**Comment by arjunvegda** [comment]
@bluecito Your issue does not relate to the issue you have commented on.

**Comment by rezaadityaap** [comment]
anybody know where is Dratini's Nest ?

**Comment by arjunvegda** [comment]
@rezaadityaap #1748

**Comment by xJustx** [comment]
reopend

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.
