### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jekzi** [Ar1i/PokemonGo-Bot#1717]
![error](https://cloud.githubusercontent.com/assets/20826254/17464606/6f1a2408-5c97-11e6-912c-ce20a3c58102.png)

This keeps popping up and it wont start up properly.

Plz Help

**Comment by OhhPian** [comment]
@Jekzi update the bot

**Comment by Jekzi** [comment]
yeah i just found out he uploaded another version.

**Comment by Guiillee191** [comment]
the same error here and it's the updated version wich has been working all the afternoon :/

**Comment by sirkinglolguy** [comment]
Yes this happend to me with updated version
