### ISSUE TITLE
Not catching pokemons ...its show got away pokemon

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#1718]
![1poke](https://cloud.githubusercontent.com/assets/20843400/17464618/d72e3976-5d00-11e6-84ac-c9af0e31af10.png)
its showing again and again but its collecting pokestops not any pokemon

**Comment by DargQ** [comment]
Soft ban.

**Comment by draga123** [comment]
Set pokeball to 10. (Can't have Pokeball set to 0)

**Comment by PokePro21** [comment]
already set it still :(

**Comment by xiannny** [comment]
move slower. 
set moving pace to 10 kmh solved it for me

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464670/3f967532-5ced-11e6-989c-11de88234eba.png)
