### ISSUE TITLE
[Missing] Standart settings (V. 1.0.2.4)

### ISSUE THREAD

**Issue by Shad86** [Ar1i/PokemonGo-Bot#172]
Since this version the whole settings are blank.

https://puu.sh/qiqwq/6a5f11a396.PNG

Dont know if its really a "bug"

regards

**Comment by Ar1i** [comment]
Its the Exe build or?

**Comment by myronownage** [comment]
Its the build, Just copy it from the old version. Not that hard. I re-typed everything and the build is working

**Comment by Shad86** [comment]
sure i dont say its hard its just that i report something what is different from before, where i think it shouldn't be like that ;)

thats in fact waht an issue thread is for, i think some people here have to learn that ;)

And its the newest one as on top says v. 1.0.2.4,... So yes

**Comment by Ar1i** [comment]
Fixed in Source already
