### ISSUE TITLE
what should i do ?

### ISSUE THREAD

**Issue by milamberfb** [Ar1i/PokemonGo-Bot#1721]
22:12:17] PokemonGo.RocketAPI.Exceptions.LoginFailedException: 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' türünde özel durum oluşturuldu.
   konum: PokemonGo.RocketAPI.Login.PtcLogin.ExtracktTicketFromResponse(HttpResponseMessage loginResp) C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs içinde: satır 46
   konum: PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__7.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs içinde: satır 85
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   konum: PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__3.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs içinde: satır 35
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   konum: PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs içinde: satır 43
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   konum: PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs içinde: satır 62

**Comment by arjunvegda** [comment]
Updating the bot should fix it.

**Comment by milamberfb** [comment]
its the newst one. im using bot with my google acc but cant use it with my poke trainer acc..

**Comment by pokerave** [comment]
wrong password maybe? or you have not activated it in the email

**Comment by arjunvegda** [comment]
Poke trainer seems to be down or not functionable. Same problem for me. here - #1573
