### ISSUE TITLE
Exception: System.ArgumentNullException: Value cannot be null ERROR

### ISSUE THREAD

**Issue by ShinHere** [Ar1i/PokemonGo-Bot#1723]
![image](https://cloud.githubusercontent.com/assets/20825292/17464664/6d3ebc96-5cb2-11e6-9556-c4c4ff7ed4ad.png)

**Comment by Ar1i** [comment]
use newest version

**Comment by ShinHere** [comment]
![image](https://cloud.githubusercontent.com/assets/20825292/17464671/9d018bf2-5cb2-11e6-9b8f-4c95f272d015.png)

Is there anything I don't know or something? I think I have the newest one.. @Ar1i

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only

And yeah your version is old

**Comment by ShinHere** [comment]
Thank you very much! Sorry for wasting your time. I will close this thread I guess.
