### ISSUE TITLE
how can i do the telegram option ?

### ISSUE THREAD

**Issue by oXNARXo** [Ar1i/PokemonGo-Bot#1724]
i did an API from here
https://my.telegram.org/apps

and now i have 

App api_id:

App api_hash:

App title:

Short name:

Test configuration:
Production configuration:
Public keys:

--------------

and the pokemon bot has : 
API token
Name

so what to put there to make it work ?

**Comment by PlsTarget** [comment]
https://www.youtube.com/watch?v=FO-M9cTARGU

**Comment by PlsTarget** [comment]
https://www.youtube.com/watch?v=FO-M9cTARGU its in german but i hope it will helps u

**Comment by oXNARXo** [comment]
i did same as him (like the video with out the sound cuz it's german)
but i got lost at 4:19

he did changed the totorial bot to old bot that he has

mine has only ( /start ) and i if i do it
it tells me with a meme photo : You have no power here



so ????

**Comment by GundBear** [comment]
1. make sure the telegram bot has started.
2. go the the setting on Telegram, set a username for your telegram account.
3. copy and paste the API token when you create the telegram bot in the PokemonGo-Bot
4. then type in the user name you just set in the telegram in PokemonGo-Bot.   run the bot again.
