### ISSUE TITLE
Doesn't collect items at Pokéstops.

### ISSUE THREAD

**Issue by Sora1724** [Ar1i/PokemonGo-Bot#1725]
I get the 50XP from every Pokéstop, but it says "Items: Nothing <Inventory Full?>, but everytime it shows me the Player Stats Update, it tells me "Items: 299/600".
So either the Player Stats Update is bugged or collecting Pokéstops^^

**Comment by pokerave** [comment]
check item setting

**Comment by GHANT** [comment]
it does for me.

**Comment by sylva91** [comment]
it does for me too

**Comment by Zapper2k3** [comment]
checked my settings, and it also dosent put the collected items to my inventory. maybe found 3 pokeballs ( my set limet isent reached). and the iventory dosent count up or put then to my inventory.
