### ISSUE TITLE
Can't run two Bots

### ISSUE THREAD

**Issue by Grieche** [Ar1i/PokemonGo-Bot#1726]
http://www2.pic-upload.de/img/31403580/Screenshot_1.png

**Comment by PlsTarget** [comment]
u have 2 bots in 2 different folders?

**Comment by pokerave** [comment]
make copy of the whole folder not just the exe file

**Comment by Grieche** [comment]
Yes

**Comment by Grieche** [comment]
I did.

**Comment by Teneryo** [comment]
3 bot perfectly working 4 me

**Comment by Grieche** [comment]
Ok i got it. The Accounts just be need to activate from the email.

**Comment by Grieche** [comment]
why this errors? http://www2.pic-upload.de/img/31403670/Screenshot_1.png

**Comment by PlsTarget** [comment]
update the bot

**Comment by Grieche** [comment]
still

**Comment by oXNARXo** [comment]
can u use 2 bots for same account so it level up faster?

**Comment by Grieche** [comment]
no
