### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by RunMan1** [Ar1i/PokemonGo-Bot#1728]
When I download the latest build it downloads it to note pad.... if i click it, I just see all the code and stuff. How do I download the file again like I use to.

**Comment by pokerave** [comment]
https://github.com/Ar1i/PokemonGo-Bot/archive/master.zip

**Comment by 13XxM1CHA3lxX37** [comment]
That not everybody has the same values and the bot does not get detected that fast

**Comment by RunMan1** [comment]
I downloaded the master.zip and it is still the notepad version..

**Comment by pokerave** [comment]
there is no unzip the file unzip the build run the exe file

**Comment by GHANT** [comment]
This shouldn't be an issue... just click the .rar and download...

**Comment by john-hardesky** [comment]
@pokerave Download [Latest Build](https://github.com/Ar1i/PokemonGo-Bot/raw/master/Builds%20Only/Latest%20Build%20-%2007.08%2021.04.rar)
Open the .rar file with WinRAR or 7Zip and extract it.
