### ISSUE TITLE
PokemonGo.ROcketApI.Console.exe is missing

### ISSUE THREAD

**Issue by myronownage** [Ar1i/PokemonGo-Bot#173]
Im getting this error , tried everything. :(  Redownloaded everthing still getting this error.
I used console as Startupfile

[IMG]http://i68.tinypic.com/6iwmfl.png[/IMG]

And the builds are not stable after updates yesterday i got 150+ pokemon catches a hour now arround 100

**Comment by baeckstrom** [comment]
There were a compilation error that has been fixed with commit 2bcac5dda1e181b55475b681c4af0bc2c7363e51 do a new pull and it should compile.

**Comment by Ar1i** [comment]
Fixed in newest Update.
