### ISSUE TITLE
egg incubator

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#1730]
how can i use automatical

**Comment by pokerave** [comment]
they are fixing it

**Comment by Jacowork** [comment]
Will they add it like Necrobot has it?
![capture](https://cloud.githubusercontent.com/assets/5517110/17465098/4d196be6-5cee-11e6-86ba-7ffafd0cf60b.PNG)
Would make this app the BEST........!!!!!!!
