### ISSUE TITLE
download 

### ISSUE THREAD

**Issue by gorgis112** [Ar1i/PokemonGo-Bot#1733]
whenever i download the latest version and click on it sends me to micrsoft edge som1 help pls.

**Comment by john-hardesky** [comment]
#1728

When you download the .rar file open it with WinRAR or 7Zip.
Your default application for handling .rar files is not set correctly.

**Comment by pokerave** [comment]
Right Click Open with unzip or winrar

**Comment by gorgis112** [comment]
@john-hardesky i dont winrar or 7zip
