### ISSUE TITLE
Exception: Invalid Response (Information)

### ISSUE THREAD

**Issue by RedDelfin** [Ar1i/PokemonGo-Bot#1735]
Build: 20.25
After 1 Hour I got this massage: 
![bug 1](https://cloud.githubusercontent.com/assets/20891877/17464732/6c9679bc-5ce6-11e6-99d9-bd6e6a8c9aa8.jpg)
![bug 2](https://cloud.githubusercontent.com/assets/20891877/17464731/6c95fd66-5ce6-11e6-8ba9-95829ad49cd8.jpg)

But after this it reconnected and works fine. 
Thank you for your great work.

Habe euch zwein eine kleine Spende überwiesen danke euch :)

PS: Why do I get Failed to evolve .... EvolvePokemonOutProto.Result Was FailedInsufficentResources ?

**Comment by joelx3** [comment]
Hab ich auch habe auch schon nen Issue geschrieben.. Solange es geht ist es doch egal.. Vielleicht hilft es ihnen trotzdem :) Die machen schon sehr gute Arbeit habe gerade auch mal meine 25€ gespendet :)

**Comment by RedDelfin** [comment]
Gut gemacht, dass das mindeste was wir machen können. 
Here some more Text: 
![bug 3](https://cloud.githubusercontent.com/assets/20891877/17464927/e4763dc0-5ce9-11e6-9a2f-17ae7ae5ceb3.jpg)
![bug -5](https://cloud.githubusercontent.com/assets/20891877/17464926/e474f23a-5ce9-11e6-826d-bad00ca2292c.jpg)
![bug4](https://cloud.githubusercontent.com/assets/20891877/17464929/e479c1ca-5ce9-11e6-8c89-18d9b376be0c.jpg)
![bug6](https://cloud.githubusercontent.com/assets/20891877/17464928/e47799c2-5ce9-11e6-8249-d327344c4a39.jpg)

PS is there an tutorial for the incubator and the eggs? What dose use standart incubator mean die (limitless) or use everey kind of incubator ?

**Comment by audota000** [comment]
same here.
