### ISSUE TITLE
 2 bots auf 1 account 

### ISSUE THREAD

**Issue by OneRating** [Ar1i/PokemonGo-Bot#1736]
Kann ich 2 bots auf 1 account gleichzeitig laufen lassen auf 2 verschiedenen Ordnern ? Das quasi der eine bot in New york farmt und der andere in Tokyo ?

**Comment by CrushLP** [comment]
testen ^^

**Comment by downspath** [comment]
bitte ergebnis posten: zb ob die exp x2 oder nur x1.5 sind danke :D

**Comment by NidiKea** [comment]
Das wäre auch für mich interessant. Wobei der grad schon wieder ganz viel weisse Schrift hat...

**Comment by CrushLP** [comment]
nur ein kleiner crash, 10 sek warten, bot läuft danach weiter

**Comment by sHaXx69** [comment]
thanks for the quick answer how can I adjust that he is not only a pokemon transfer equal to all lows cp??

**Comment by OneRating** [comment]
Nope , hat fürn paar sek geklappt dannach ein softbann..

**Comment by NidiKea** [comment]
Hast du 1 Account auf 2 Bots laufen lassen oder 2 verschiedene?

**Comment by OneRating** [comment]
1 account auf 2 bots war mein versuch ;D hat aber nicht geklappt.

**Comment by downspath** [comment]
warscheinlich weil dein char nicht in 2 länder gleichzeitig sein kann

probier zb beide in NY (neuer acc zum testen)

**Comment by OneRating** [comment]
ah gute idee :D

**Comment by CrushLP** [comment]
benutz entbann button

**Comment by OneRating** [comment]
habe ich ja aber is ja blöd wen du jede 30 den entbann button drücken musst

**Comment by CrushLP** [comment]
und dann versuch beide z.b central park, 1 ganz oben der andere ganz unten

**Comment by downspath** [comment]
und mach das er sich höchstends 500m von den coords weckbewegen kann

**Comment by downspath** [comment]
oder weniger
es gibt da genug pokestops

**Comment by CrushLP** [comment]
lasse meinen grad mit 100km/h dort durch rennen mit 5000m abstand vom start, aller 3 sekunden 2 stops xD

**Comment by CrushLP** [comment]
seit 20 Minuten schon, noch kein bann

**Comment by downspath** [comment]
ich probiers mit 1 acc 2 bots und max abstand vom startpunkt 500m

**Comment by OneRating** [comment]
Crush , machst du es mit 1 acc oder 1 acc mit 2 bots ?

**Comment by CrushLP** [comment]
1 acc 2 bots, 1 bot ganz unten am park, 2 bot ganz oben am park, läuft easyyyyyyyyy

**Comment by OneRating** [comment]
bei mir nicht ;/

**Comment by CrushLP** [comment]
wurde zwar gesoftbanned, aber nun nach entbann laufen beide komplett durch, fangen und sammeln ohne ende

**Comment by downspath** [comment]
wow ich habs jetzt 10 mal neu gestarted jetzt funktionierts einfach alle bälle auf 0 stellen dann fängt er keine pokemon mehr und ist richtig schnell 120.000 exph und mehr oO 1 acc 2 bots der is schon fast lvl 10 :,D

**Comment by downspath** [comment]
0 bälle desswegen weil sonst immer error komt mit pokemon already encounterd

**Comment by OneRating** [comment]
Wie ? welche einstellungen hast du benutzt ?

**Comment by CrushLP** [comment]
bin mit beide zusammengerechnet 205.472 exp/h

**Comment by OneRating** [comment]
erzählt mal alle eure einstellungen :o

**Comment by eliteknight** [comment]
Die werden eh alle Accounts bannen, welche über lvl 30 sind, ist eh keiner im reallife...ist nur ne frage der zeit^^

**Comment by downspath** [comment]
2500m vom spawn max entfernt, bei den items alle bälle auf 0 stellen, geschwindigkeit auf 120 (ganz normal in ny :,D) und rest is egal weil eh keine pokemon gefangen werden

**Comment by downspath** [comment]
ich mach den bot nur weil ich einen char in allen continenten hab ich werde später alle auf meinen main tauschen (mein main is ohne bots und hat lvl 27)

**Comment by CrushLP** [comment]
@eliteknight  da liegst du ein wenig Falsch, da es ein Youtuber level 36 bereits gibt, der das game suchtet wie bekloppt, und für youtube auch alles dokumentiert

**Comment by eliteknight** [comment]
wurde ausgerechnet, dass man bei 8-12h am Tag mit dem speed welchen der Spieler hat, welcher alle Pokemon besitzt 548 Jahre brauch bis lvl 40...blöd nur das die ersten schon lvl40 sind....weil sie eben nicht selber spielen.

**Comment by NidiKea** [comment]
wie tauscht man die denn? Das kommt später richtig?
Also wie soll man dann dieses Spiel bis Level 40 bringen ? Also im real Live???

**Comment by OneRating** [comment]
Und 1 acc auf 2 bots klappt iwie nicht bekomme fast keine ep und fast nurn bann :D

**Comment by eliteknight** [comment]
gar nicht, ausser sie ändern die XP

**Comment by NidiKea** [comment]
wenn ihr nur lauft und keine Pokemon dabei fangt, wozu lauft ihr dann? 
Und was ist das denn für ein Spiel, wo man nicht zu Ende kommt bei den Leveln also ich denke natürlich wollen sie es auf Jahre ziehen und es möglichst immer wieder mit Neuerungen füttern und neuen Pokémons und Events usw... aber ich befürchte auch, irgendwann bekommen alle einen Permanenten Ban....also ich werde nur bis Lv 30 spielen und dann einfach im Real Live aus Spass weiterhin

**Comment by OneRating** [comment]
@CrushLP @downspath  könnt ihr mal nen screen schiken wo eure beiden acc gleichzeitig laufen ? :+1:

**Comment by eliteknight** [comment]
Ob es nur mit laufen schneller geht sei mal dahin gestellt.
Sie machen es letztlich, weil sie Pokemon mit hohem lvl wollen, und die hängen vom Trainerlvl ab.

Dabei entgehen dir aber massig Essenzen und Punkte bei der Methode.

**Comment by NidiKea** [comment]
Mein Problem ist, wenn ich schnell laufe, findet er schneller Pokemon, aber er verkauft keine und dann ist es schnell voll wenn man nicht daneben sitzt und selber verkauft

**Comment by OneRating** [comment]
Ja aber besonders viele Pokemons , will ich auch mein 2 acc nicht . sondern nur ein hohes lvl erreichen ,

**Comment by eliteknight** [comment]
Du kannst doch einstellen wie viele Duplikate er behält.

**Comment by NidiKea** [comment]
ja eigentlich schon, aber er verkauft keine, hatte grad 25 Zubats

**Comment by eliteknight** [comment]
musst die CP und IV % so hoch setzen, das er keinen behalten kann.
Und Pokemon behalten für Entwicklen ausstellen

**Comment by NidiKea** [comment]
ok danke ich versuche es

**Comment by downspath** [comment]
du verwechselst jahre mit tage ich hab bereits ücer 1 mil xp auf mein legit acc, und für lvl 40 braucht man 20 mil also if find lvl 40 erreichen ist nicht schwer

**Comment by downspath** [comment]
@eliteknight check deine info nochmal mit den 584 jahren ;)
