### ISSUE TITLE
Dont catch pokemon

### ISSUE THREAD

**Issue by tuignoras** [Ar1i/PokemonGo-Bot#1737]
please my bot dont catch pokemon just farm pokestops, envolver pokemon and transfer, i set the speed to 10km

**Comment by iilkercetinn** [comment]
it seems softban. click force unban button on pokemon list screen.

**Comment by tuignoras** [comment]
it isnt , just dont see pokemons on the screen 
![image](https://cloud.githubusercontent.com/assets/20891983/17464797/024b6cd6-5cdf-11e6-9ad0-f36ad325f6ad.png)

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17464802/f0d5dd90-5cef-11e6-8efe-e246878d9799.png)

**Comment by tuignoras** [comment]
![image](https://cloud.githubusercontent.com/assets/20891983/17464808/5cdbe680-5cdf-11e6-83e1-d7abec4dac93.png)

**Comment by PokePro21** [comment]
dont keep 500+

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17464832/bc1a0d4a-5d05-11e6-971b-754269a2fc0d.png)

**Comment by PokePro21** [comment]
that error comes because all pokeballs over

**Comment by tuignoras** [comment]
still not working 
![image](https://cloud.githubusercontent.com/assets/20891983/17464865/6105e2d2-5ce0-11e6-9d6f-f6202b07aaee.png)
![image](https://cloud.githubusercontent.com/assets/20891983/17464867/6ca7ca9c-5ce0-11e6-94f3-a6a24d2e762a.png)

**Comment by tuignoras** [comment]
it seems that pokemons are not detected
