### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Neikon** [Ar1i/PokemonGo-Bot#1738]
![captura de pantalla 7](https://cloud.githubusercontent.com/assets/1765319/17464785/12f49cc6-5ce7-11e6-943a-03f2560910a6.png)

The last build is detected like a virus

**Comment by downspath** [comment]
no virus only pakage error

**Comment by pokerave** [comment]
False positive.

**Comment by joelx3** [comment]
because he is packing it.

**Comment by 1nf0** [comment]
Same for me. Just ignored.

**Comment by pokerave** [comment]
wash your hands.,.. :laughing:

**Comment by 44Ercan44** [comment]
just beware of downloading infected
