### ISSUE TITLE
bot not starting?

### ISSUE THREAD

**Issue by maggi499** [Ar1i/PokemonGo-Bot#1739]
this is all that happens then i try to start the bot.
am i doing something wrong or? :)

![bot](https://cloud.githubusercontent.com/assets/20892012/17464796/5d9c719a-5ce7-11e6-9ba3-a1932bf1df9a.PNG)

**Comment by pokerave** [comment]
show screen setting

**Comment by 1nf0** [comment]
Do you have a healthy connection? May your antivirus or firewall block it?

**Comment by maggi499** [comment]
i have a 40/10 connection. run as admin. but i could try not sandboxing it?
screen settings?

**Comment by maggi499** [comment]
FIXED! just had to run it out of my sandbox ^^
