### ISSUE TITLE
Error: Pokemon GO Rocket API

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#174]
[10:57:48] Starting Execute on login server: Google
[10:57:48] Error: Pokemon Go Rocket API
[10:57:48] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   bij PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:regel 34
   bij PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:regel 128
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:regel 50

---- also: 
The whole bot is not installed at "C:\Users\Ari\Desktop\PokemonGo Bot"
My name aint Ari and it's not even installed on the C:\

**Comment by Ar1i** [comment]
[10:57:48] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication

That is cause, i didnt removed the Debug thing. Shouldnt be a Problem tho. Its your Account Data which is wrong.
