### ISSUE TITLE
Can start bot

### ISSUE THREAD

**Issue by LordBigPapa** [Ar1i/PokemonGo-Bot#1740]
![bot](https://cloud.githubusercontent.com/assets/20892027/17464801/85f54b58-5ce7-11e6-9822-178a334df711.png)

I can't open the bot anymore. I am using the right file so anyone knows what the problem could be?

**Comment by pokerave** [comment]
thats the XML.. look for the APPLICATION

**Comment by LordBigPapa** [comment]
@pokerave sorry my bad. Was trying to edit the picture. But you where faster :)

@joelx3 will try that. In previous versions my firewall and defender gave no problems

**Comment by LordBigPapa** [comment]
This time the virusscanner deleted it indeed. Works now as old.

Thank you all guys.
