### ISSUE TITLE
/

### ISSUE THREAD

**Issue by sufficey** [Ar1i/PokemonGo-Bot#1741]
/

**Comment by pokerave** [comment]
ask POKECROT

**Comment by downspath** [comment]
lol suddenly people ask for the source, i bet you are from pokecrot

**Comment by downspath** [comment]
https://www.youtube.com/watch?v=CrPulYDwlCA look at the program, it is just a redesigned version, and they sell it for money, that is the reason

**Comment by xcrumpy** [comment]
if you want the source than translate it from python yourself. Our developers have ran on no sleep for 24+ hours to get the source made for us so deal with it.

**Comment by sufficey** [comment]
I didn't know about pokecrot, lol
