### ISSUE TITLE
Every pokemon escape 

### ISSUE THREAD

**Issue by SteffLn** [Ar1i/PokemonGo-Bot#1742]
Like the title, every pokèmon escape, bot can't capture anyone

**Comment by joelx3** [comment]
https://cloud.githubusercontent.com/assets/20603254/17464802/f0d5dd90-5cef-11e6-8efe-e246878d9799.png

**Comment by 1nf0** [comment]
You might be soft banned. Do you gain xp or stuff from pokestops?

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17464856/e81c2090-5d05-11e6-83c9-97de8d8ec997.png)

**Comment by PokePro21** [comment]
its coming because 0 pokeballs

**Comment by PokePro21** [comment]
keep this setting

**Comment by john-hardesky** [comment]
Before reporting an issue check if it already exists: #1737

**Comment by SteffLn** [comment]
Thx guys, sorry but i'm new on this website ^^'

**Comment by SteffLn** [comment]
Checked, it still doesn't work
