### ISSUE TITLE
best speed to run bot and get fast xp? and not get banned 

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#1743]
how many km/h do you put?

**Comment by CrushLP** [comment]
using 100km/h in New York for 20 mins now, not banned, fast as shit

**Comment by oXNARXo** [comment]
i think the default 100% not bannable

**Comment by joelx3** [comment]
im using 50-70km/h and its fine

**Comment by Sora1724** [comment]
Jup, running two bots, both on 50 km/h and it works fine

**Comment by spotterd** [comment]
I use 400km/h, havent gotten softbanned.

**Comment by pokerave** [comment]
im playing the safest @25km/h. lol

**Comment by asfo** [comment]
This is not a forum guys, stop asking things here.

**Comment by joelx3** [comment]
true dat

**Comment by arjunvegda** [comment]
#1748

**Comment by mahdouch25** [comment]
30km/h i think is safe lol
