### ISSUE TITLE
no pokestops in range

### ISSUE THREAD

**Issue by icewick** [Ar1i/PokemonGo-Bot#1745]
Sorry for posting ... but i downloaded the newest version 1.0.6.5 dont changed the settings and there wont be any pokestops found.

i changed the position
i changed the account.
i changed move speed and range

i realy dont get it ... what im doing wrong?

**Comment by joelx3** [comment]
delete everything.. check if your account is banned..

DELETE all bot folders redownload and turn of firewall and all antivirus you have

**Comment by oXNARXo** [comment]
there is update ^

**Comment by pokerave** [comment]
move to a new state.. ex from NY to CA

**Comment by icewick** [comment]
im sorry guys! ....


thx oXNARXo 


i allways compilled the old version
