### ISSUE TITLE
Telegram bug

### ISSUE THREAD

**Issue by SxS46** [Ar1i/PokemonGo-Bot#1747]
Hello!
If I have notification enabled and another user sends a message to the bot it answers "you have no power here" and after that starts sending informations to that other user instead of me, if I write back to the bot then everything goes back to normal.

**Comment by DargQ** [comment]
You opened something wrong same happened to me.

**Comment by DargQ** [comment]
Its your issue not the bot :D

**Comment by DargQ** [comment]
Try to open the bot from the liink botfather gives you.

**Comment by SxS46** [comment]
Telegram works perfect with my account (except /information catch that enables pokestop info), the issue is when another telegram user write to my bot then this happens: 
![photo_2016-08-07_22-09-25](https://cloud.githubusercontent.com/assets/20704913/17465011/a3343022-5ceb-11e6-9631-7567415f0adc.jpg)

**Comment by StianNorway** [comment]
How does this telegram work? Any video?
