### ISSUE TITLE
Sickest Magikarp iv seen

### ISSUE THREAD

**Issue by BlackHatching** [Ar1i/PokemonGo-Bot#1749]
![sick](https://cloud.githubusercontent.com/assets/20826911/17464943/4fc50ee4-5cea-11e6-80e4-6ac14726e0ea.png)
Crap

**Comment by DargQ** [comment]
I dont know how to help you with this issue :D

**Comment by john-hardesky** [comment]
See #1748

**Comment by DargQ** [comment]
Only German people use it ;(

**Comment by BlackHatching** [comment]
I help people on issues usually. Just for this i want to see i people have a better Magikarp to show me ;)

**Comment by DargQ** [comment]
Before someone close this issue what lvl are you? :D

**Comment by BlackHatching** [comment]
32 now :)

**Comment by DargQ** [comment]
Same My best pokemon is 2600+ Cp yours?

**Comment by The-Real-IMMG** [comment]
Max power up magikarp before evolution and you might get 3000+ gyarados

**Comment by DargQ** [comment]
Does it help if you power up before evolution and after?

**Comment by BlackHatching** [comment]
Nope Real

**Comment by BlackHatching** [comment]
Best CP gyarados is 26xx

**Comment by immoempe** [comment]
I had a Magikarp with 100% IV, evolved already

**Comment by BlackHatching** [comment]
show meh ur screenshot thats more fun :p

**Comment by john-hardesky** [comment]
Not a bot related issue. 
Use any Pokemon Go related forum for discussions like this.

**Comment by DargQ** [comment]
Oky BlackHatching close this issue lets not waste Ar1i time reading this and making John angry.

**Comment by BlackHatching** [comment]
chill out john... To answer u Dargq my best is drago 3017 78%
