### ISSUE TITLE
New Exception - Argumentnullexeption

### ISSUE THREAD

**Issue by usercolo** [Ar1i/PokemonGo-Bot#1750]
![captura](https://cloud.githubusercontent.com/assets/937655/17464945/55536aa4-5cea-11e6-946e-db2c1a673379.PNG)

**Comment by joelx3** [comment]
It hapens for me every 60 minutes or so.. its not that bad

**Comment by v1mp** [comment]
Why is this happening...I can't get back in to get it to work..

**Comment by yozaliefian** [comment]
having the same problem. and it happens everytime it started over. 
did all of you use google login data ?

**Comment by v1mp** [comment]
Yes, used google login.

**Comment by FvG90** [comment]
I have the same problem here  and yeah i'm using google login

**Comment by usercolo** [comment]
I'm using google login too

**Comment by usercolo** [comment]
I install the last versión of the bot (Latest Build - 07.08 21.04) and works

**Comment by yozaliefian** [comment]
might be the problem with the google token. ^ this should be our emergency fix.
lets try it for now until our lord and saviour fix this issue rofl. 
btw, thanks colo
