### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Guiillee191** [Ar1i/PokemonGo-Bot#1751]
![sin titulo](https://cloud.githubusercontent.com/assets/20887789/17464947/5c8059b8-5cea-11e6-97ef-a826c86c9f20.png)

I'm getting this error again and again. Help pls. And yes, it is the updated version

**Comment by v1mp** [comment]
Yes, I'm getting the same error message.

**Comment by Hazuke1337** [comment]
It´s not a Error Massage it´s like a "refresh"
