### ISSUE TITLE
IT DOESNT TRANSFER ANY POKEMON

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#1754]
![2016-08-07 22_02_08-greenshot](https://cloud.githubusercontent.com/assets/20840606/17464974/de5c252a-5cea-11e6-868b-044f038d31cb.png)
![2016-08-07 22_02_24-greenshot](https://cloud.githubusercontent.com/assets/20840606/17464975/e1024930-5cea-11e6-9f40-fb91c84daaa6.png)
![Uploading 2016-08-07 22_02_31-Greenshot.png…]()

**Comment by MythosOfGaming** [comment]
It doesnt transfer pokemon

**Comment by MythosOfGaming** [comment]
PLEASE HELP IT DOESNT TRANSFER ANY POKEMON

**Comment by pokerave** [comment]
un check "keep pokemon which can be evolve"

**Comment by MythosOfGaming** [comment]
it dont works too but i wait if someone has a solution pls comment
