### ISSUE TITLE
für die blöden ....

### ISSUE THREAD

**Issue by Titus1987** [Ar1i/PokemonGo-Bot#1756]
Hey Leute ich bekomme den bot gerade garnicht zum laufen weil es keine komplette Datei Sammlung ist ....wenn ich die alten einfach ersetzte bekomme ich den fehler das er die console nicht laden kann ? Kann mir irgendwer helfen? 

Grüsse

**Comment by LvGPoke** [comment]
Lösch einfach alles und lad es nochmal runter ... Sollte eigentlich alles flüssig und ohne Probleme funktionieren ...

**Comment by Titus1987** [comment]
ich hab das Problem das ich garnicht alles bekomme ich hab hier den last build die readme und die console als ordner mehr nicht exe etc fehlt ja

**Comment by john-hardesky** [comment]
Extract the Last Build .rar file with WinRAR or 7Zip

**Comment by LvGPoke** [comment]
Also ich erklär mal wie ich es gemacht habe:
1.Alles runterladen
2. Alles extrahieren in einen Ordner auf dem Desktop
3.Datei im Order "Builds only" extrahieren in einen !neuen! Order auf dem Desktop
4. Die .exe Datei im 2. Ordner öffnen
5. fertig

**Comment by Titus1987** [comment]
funktioniert bei mir auch Dankeschön ich versuch nur gern dahinter zu kommen damit ich beim 2ten mal keine blöden fragen mehr stellen muss !
