### ISSUE TITLE
Bot Fails To Catch Pokemon. Not Softbanned. w/ Screenshot

### ISSUE THREAD

**Issue by DougDimmadomeOfDimmsdaleGymmadome** [Ar1i/PokemonGo-Bot#1757]
So the bot fails to catch pokemon. I'm confirmed that i'm not soft banned via Bluestacks, also, Pokestops works fine on the bot. After it fails to catch the pokemon and disengages, it finds that pokemon, tries to catch and fail again. Screenshot should explain it better than i can. Notice the cp's of the pokemon that got away. 

![wtf](https://cloud.githubusercontent.com/assets/20888981/17465006/eb0ad948-5cf3-11e6-87cf-7f789f9d9cc2.png)

**Comment by DougDimmadomeOfDimmsdaleGymmadome** [comment]
M pokeboll settings are all 200. Trying again with 10.

**Comment by DougDimmadomeOfDimmsdaleGymmadome** [comment]
Nope didn't work.

**Comment by john-hardesky** [comment]
Before reporting an issue check if it already exists: #1737 #1742

**Comment by DougDimmadomeOfDimmsdaleGymmadome** [comment]
My issue is not the same. My bot try to catch pokemon but it fails and pokemon gets away, after it gets away bot finds it again and fails again.

**Comment by phhp10** [comment]
Same issue for me.

**Comment by john-hardesky** [comment]
As I said check #1742
To be explicit read [this comment.](https://github.com/Ar1i/PokemonGo-Bot/issues/1742#issuecomment-238103943 )

**Comment by DougDimmadomeOfDimmsdaleGymmadome** [comment]
As i said, none of my pokeball settings were 0. Can you be more spesific and explain yourself?

**Comment by eliteknight** [comment]
Force Unban

**Comment by phhp10** [comment]
@DougDimmadomeOfDimmsdaleGymmadome , Try lowering the speed for a while, until you can catch pokemeon again. I had the same issue (at 50 km/h). I lowered the speed at 10km/h and now I catch every pokemon. Maybe it is not linked but it worked for me.
