### ISSUE TITLE
How can we see our eggs hatching? If hatching?

### ISSUE THREAD

**Issue by vascobrissos14** [Ar1i/PokemonGo-Bot#1758]
Hello Ar1i! Loving your job so far, but how can we select, hatch and see our eggs? I never know if they are hatching and it the one I want to be hatched was the chosen one. I think it's a nice feature to add like the pokemon "inventory". 

Thank you!

**Comment by DargQ** [comment]
Go on your phone with you gps disabled and check :)

**Comment by vascobrissos14** [comment]
It would be awesome if we could that on the BOT, but your idea works, just not very handy xD

**Comment by emilie253** [comment]
if we can see that on the bot (with our level...) it will be perfect :)

**Comment by vascobrissos14** [comment]
Ikr! That would be awesome but the bot is alredy awesome as it is :D

**Comment by emilie253** [comment]
yes, except for egg :p

**Comment by vascobrissos14** [comment]
Ar1i has to make it, Im just here to give the idea to him :D

**Comment by Sora1724** [comment]
Yea great idea, we need something that shows us what we got from the eggs

**Comment by vascobrissos14** [comment]
What we got and what we have, to know if it is a 2 5 or 10KM

**Comment by vascobrissos14** [comment]
A list of the items would be also good, but the eggs are more important :+1:
