### ISSUE TITLE
Keine Pokestops

### ISSUE THREAD

**Issue by Tyanieee** [Ar1i/PokemonGo-Bot#1759]
Bin grad heimgekommen, natürlich gefreut, das ihr so gute Arbeit geleistet habt, Daumen hoch!
Aber ich hab mir das neue Build gezogen und natürlich in den richtigen order gepackt, nur wenn ich starte wie gewohnt, kommt die selbe Fehler Meldung wie davor, das er keine Pokestops in der Umgebung findet und wieder zur Default Location zurück läuft. 
Entweder bin ich grad hängen geblieben, oder ich checks grad nicht was ich falsch gemacht hab.
kann mir grad wer weiterhelfen bitte ?

**Comment by eliteknight** [comment]
neue stadt gehen...
