### ISSUE TITLE
Add in auto un ban.....

### ISSUE THREAD

**Issue by PloxFire** [Ar1i/PokemonGo-Bot#1760]
Im upset that auto unsoft ban was removed, now i can't go off at night without being softbanned and it being unbanned soon after....

**Comment by asfo** [comment]
Just click the "Force unban". This is not a forum, is for bug reports.

**Comment by BlackHatching** [comment]
open your eyes guys....

**Comment by cristianst** [comment]
I see no "force unban" option.

**Comment by BlackHatching** [comment]
Look at the "Pokemon List"..

**Comment by cristianst** [comment]
![image](https://cloud.githubusercontent.com/assets/11995461/17465122/22276b62-5cef-11e6-96c9-397471a4a931.png)

Nothing. OR im blind :D

**Comment by eliteknight** [comment]
Pokemon-List....

**Comment by PloxFire** [comment]
I know there a force unban what im trying to say is i would like to go off to bed without getting banned and not being able to unban myself because im asleep....

**Comment by PloxFire** [comment]
I can force unban if im asleep can i know... which is why the auto un ban was sych a good feature because you could goto work or goto bed without having to click a button every few hours.....

**Comment by cristianst** [comment]
Oh ok got it ! @eliteknight

**Comment by eliteknight** [comment]
I think this feature come back.
That's work automatically.
