### ISSUE TITLE
ERROR: "Value cannot be zero"

### ISSUE THREAD

**Issue by mi2kk3el** [Ar1i/PokemonGo-Bot#1761]
Randomly started to get this error, after running the bot for a few hours. No idea what to do or what caused it.
Screenshot: https://gyazo.com/a8e8694f3ec499c5cea4730b1bb76425

**Comment by asfo** [comment]
Update it.

**Comment by mi2kk3el** [comment]
I've updated it, still the same issue.

**Comment by krwlng** [comment]
Same error to mine app.

**Comment by asfo** [comment]
Did you delete your older version? ...I had the same error but I update it and its fixed. Try to move to another place ...

**Comment by SentESp** [comment]
I got the same error... and i allways delete all files except the iteam config

**Comment by mi2kk3el** [comment]
Seems like moving the folder to another place and deleting the older version worked. Thanks @asfo :+1:
