### ISSUE TITLE
what does exactly mean "start from default location" ? 

### ISSUE THREAD

**Issue by cristianst** [Ar1i/PokemonGo-Bot#1763]
After you set the location in the map. There is a checkbox "start from default location". 
What does it exactly mean? If Ive already set the location in the map. Which is the default location? 
I want to start from the location I set in the map.

**Comment by BlackHatching** [comment]
You setup your default location 1st and you ll spawn at this point

**Comment by cristianst** [comment]
@BlackHatching thanks for ur fast answer.. but what happens if i dont check "start from default location" even after I set up my location with the map?

**Comment by eliteknight** [comment]
default is what you selectet in the options.

**Comment by john-hardesky** [comment]
See #1748

But to answer your question
If you check start from default location it will start from there but if you uncheck it will start anywhere within the radius from the default location.

**Comment by Tr1n0va** [comment]
But it seems, that the bot After every restart starts in New York, and not like the Order Version at the Last User Position where it was closed....

**Comment by john-hardesky** [comment]
I'm using the [Latest Build](https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only) and it works for me, no location reset.
