### ISSUE TITLE
need gui look like this

### ISSUE THREAD

**Issue by mhmimoeb** [Ar1i/PokemonGo-Bot#1764]
combine window

http://imgur.com/a/ItXLT

please open source to fork. thank you

**Comment by plowzey** [comment]
That'd be so good

**Comment by pokerave** [comment]
this ones better ![gui1](https://cloud.githubusercontent.com/assets/20603254/17465386/4568c292-5cfe-11e6-8f49-cc5f0ca9fb9f.png)
