### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by iOwner** [Ar1i/PokemonGo-Bot#1765]
Is it safe to bot again? Also is it safe to bot for extended periods of time?

**Comment by john-hardesky** [comment]
See #1748

Using bots is never safe

**Comment by iOwner** [comment]
I know that, what i mean is, is it stable for me to be leaving on without it stumbling and turning off...

**Comment by john-hardesky** [comment]
Stabel-ish 
There are some quirks here and there but if nothing happens in the first 30 min you should be fine.

**Comment by iOwner** [comment]
Awesome, last one, is the unbanning after teleporting working?

**Comment by pokerave** [comment]
unban 1337 worked for me.
