### ISSUE TITLE
I can't start bot, .exe file doesn't start running

### ISSUE THREAD

**Issue by dayburak** [Ar1i/PokemonGo-Bot#1766]
Can't run .exe file

**Comment by Seabasssssss** [comment]
same here! need help!

**Comment by john-hardesky** [comment]
Ambiguous description.
Give us more details and screen-shots.

**Comment by dayburak** [comment]
There's nothing to be screenshotted, PokemonGo.RocketAPI.Console.vshost.exe doesn't start running

**Comment by Seabasssssss** [comment]
when we click on PokemonGo.RocketAPI.Console.vshost.exe it does not open

**Comment by ourty** [comment]
This is what happens when i start the console .exe
![image](https://cloud.githubusercontent.com/assets/7776268/17465176/5dceb0e8-5cbe-11e6-8433-e5f6ba999822.png)

This is what happens when i start it as an admin
![image](https://cloud.githubusercontent.com/assets/7776268/17465179/68a0b73c-5cbe-11e6-9813-85bbb80f2e8f.png)

**Comment by Kirisuna10** [comment]
I think you are clicking the wrong thing.... Should say PokemonGo.RocketAPI.Console

**Comment by john-hardesky** [comment]
See #1748

Use PokemonGo.RocketAPI.Console.exe

**Comment by john-hardesky** [comment]
Delete old bot, download [Latest Build](https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2007.08%2021.04.rar) and extract the .rar file with WinRAR or 7Zip and then launch PokemonGo.RocketAPI.Console.exe

**Comment by Seabasssssss** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/20892613/17465215/5e58d8ee-5ca6-11e6-8d5f-b01ab8cf3b97.png)


i dont it

**Comment by dayburak** [comment]
yea i don't have that exe file either

**Comment by Seabasssssss** [comment]
It was working fine then all of a sudden it stopped and didn't run anymore.

**Comment by miguellm86** [comment]
Probably your antivirus delete the file, mine did

**Comment by Seabasssssss** [comment]
ive turned off my windows defender and still nothing

**Comment by Seabasssssss** [comment]
so how do i turn off all of my antivirus?

**Comment by Seabasssssss** [comment]
@miguellm86

**Comment by miguellm86** [comment]
i dont use windows defender but search for whitelist or something like that...
i hope this can ehlp you
https://www.reddit.com/r/Windows10/comments/34x6a2/howto_manually_disable_windows_defender/

**Comment by Seabasssssss** [comment]
im trying again @miguellm86
