### ISSUE TITLE
Using Application

### ISSUE THREAD

**Issue by Seabasssssss** [Ar1i/PokemonGo-Bot#1767]
When i click on the application "PokemonGo.RocketAPI.Console.vshost.exe" a little loading symbol comes up then goes away. how can i fix?

**Comment by john-hardesky** [comment]
See #1748

Doesn't need fixing, use PokemonGo.RocketAPI.Console.exe

**Comment by smedicejr** [comment]
Why "PokemonGo.RocketAPI.Console.exe" disapper when I try to execute it?

**Comment by Seabasssssss** [comment]
i dont even see that one you said as a option @john-hardesky

**Comment by john-hardesky** [comment]
Delete old bot, download [Latest Build](https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2007.08%2021.04.rar) and extract the .rar file with WinRAR or 7Zip and then launch PokemonGo.RocketAPI.Console.exe

**Comment by Notnianticspy** [comment]
Seabasssssss..........make sure your antivirus isn't trying to block the application from running.

**Comment by Seabasssssss** [comment]
i still cant find "PokemonGo.RocketAPI.Console.exe" all i see is "PokemonGo.RocketAPI.Console.vshost.exe"

**Comment by Seabasssssss** [comment]
And my windows defender is off

**Comment by Notnianticspy** [comment]
mine is located about three files up from that file.  "PokemonGo.RocketAPI.Console". it's an application file

**Comment by Seabasssssss** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/20892613/17465296/54eab622-5ca8-11e6-9e69-9c598023bc65.png)


See

**Comment by Seabasssssss** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/20892613/17465307/7dcfa796-5ca8-11e6-8ba8-f1d2f4d2d466.png)

Updated Screenshot

**Comment by Notnianticspy** [comment]
it looks like you downloaded the latest build but windows defender might have already removed the file when you tried to open it the first time. you can either go and try and unquarentine the file or reinstall the build with all antivirus disabled

**Comment by Notnianticspy** [comment]
webroot tried to quarantine the file when i opened it.
