### ISSUE TITLE
Bot does catch pokemon..

### ISSUE THREAD

**Issue by FlyHaxHD** [Ar1i/PokemonGo-Bot#1768]
I see all these issues with bot not catching pokemon. Im running 2 accounts and the bot is working great. Catching pokemon and pokestops.
![capture](https://cloud.githubusercontent.com/assets/20892244/17465136/4fcf7140-5ca4-11e6-8474-031147e94820.JPG)

**Comment by phhp10** [comment]
Lucky you :)
