### ISSUE TITLE
IT DOESNT TRANSFER ANY POKEMON

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#1769]

**Comment by MythosOfGaming** [comment]
![2016-08-07 22_02_08-greenshot](https://cloud.githubusercontent.com/assets/20840606/17465149/370c75e4-5cf0-11e6-9d15-5f478b9e0c9b.png)
![Uploading 2016-08-07 22_02_24-Greenshot.png…]()
![Uploading 2016-08-07 22_02_31-Greenshot.png…]()

**Comment by MythosOfGaming** [comment]
![2016-08-07 22_02_24-greenshot](https://cloud.githubusercontent.com/assets/20840606/17465156/4fe59f5a-5cf0-11e6-9cee-8431a2208ddd.png)

**Comment by MythosOfGaming** [comment]
![2016-08-07 22_02_31-greenshot](https://cloud.githubusercontent.com/assets/20840606/17465157/5bb97072-5cf0-11e6-9bc1-d4d0a04a66db.png)

**Comment by arjunvegda** [comment]
Because your maximum IV to transfer says 0.

**Comment by MythosOfGaming** [comment]
Thanks !
