### ISSUE TITLE
Cant Get Unbanned + Error reloading pokemon list

### ISSUE THREAD

**Issue by Drakoo2** [Ar1i/PokemonGo-Bot#1770]
Hello guys now all my pokemons is running away and when i press force unban it says in the next pokestop and it doesnt do anything and all pokemons now are running and i got the latest version Please help me

**Comment by phhp10** [comment]
Same issue for me. It seems we are constantly sofbanned :(

**Comment by Ritzii** [comment]
The way it unbans is repeatedly opening, spinning and closing the pokestop, (takes longer depending on the distance you travelled between the last stop and the ban). 
Login through Nox or something and you can do it manually, just slow the speed of the bot down to 35-40 after to be safe. :)

**Comment by FlyHaxHD** [comment]
If it doesnt catch pokemon but you collect Exp from Pokestops It doesnt mean your ban. Its an issue fro people rn.

**Comment by phhp10** [comment]
> Its an issue fro people rn. @FlyHaxHD  What do you mean ?

**Comment by pokerave** [comment]
![pokesetting](https://cloud.githubusercontent.com/assets/20603254/17465352/a6b0acbe-5cfd-11e6-8c58-092d2433b2b7.png)
