### ISSUE TITLE
Transfer Logic

### ISSUE THREAD

**Issue by cristianst** [Ar1i/PokemonGo-Bot#1772]
Imagine you have 5 Dratinis - between lvl 400 and 500. 

And you start the bot with the following options : 

Repeated Pokemon : 3
MAX CP to transfer : 999
MAX IV 90%..

I expect the algorithm to be smart enough and keep the 3 Dratinis with the highest CP, because after transfering from bottom to top (CP)  at the 4th Dratini , the bot should stop transfering Pokemon because there are now just 3 repeated pokemon. 

But no.. The bot deletes them all. 

![image](https://cloud.githubusercontent.com/assets/11995461/17465175/a4e077c8-5cf0-11e6-9b38-127c86dff186.png)

**Comment by cristianst** [comment]
I hope my explanation was clear enough. :)

**Comment by FlyHaxHD** [comment]
It keeps the best 3 dratinis you have. If you have 7 of em and 4 are around 400 it will delete all of em but the 3 highest CP ones.

**Comment by eliteknight** [comment]
its works correct.
No Pokemon is over 999 CP and no one over 90%.
So he keeps only the Pokemon with most CP.
If your Dratini he keeps this with 580CP and all over 90+% IV and all other are auto transfer.
The best CP and IV Pokemon does not have to be the same!

**Comment by LucasK94** [comment]
i never find any dratinis lol

**Comment by xhalfbakedguy** [comment]
52.5180064794906, 13.3994740247726
thats in berlin there are 2/3 dratinis every hour or so

**Comment by cristianst** [comment]
In London I found 100 Dratinis :D

**Comment by cristianst** [comment]
If you wanna catch specific rare pokemon I recommend nox + pokemon go and GoRadar for iOS

**Comment by Ritzii** [comment]
Go to the Pokemon tab and check Dratini in the "Pokemon not to transfer" list, same goes for any others you want to check through yourself.

--Royal Botanic Gardens in Sydney, NSW (where the bot actually starts you), is amazing for Dratini and it's supported by Skiplagged. The only problem is they spawn quite spread out along the edges of the water, so the bot doesn't pick many of them up, you'd have to use Nox or something but I farmed 3-4x 95%+ Dragonites there in a day or two, picked up a few Snorlax/Lapras and Aerodactyl too ^^

**Comment by cristianst** [comment]
Where can I pick a Snorlax & Lapras T_T
