### ISSUE TITLE
Got the level up reward from you level up.

### ISSUE THREAD

**Issue by FreeHux** [Ar1i/PokemonGo-Bot#1773]
getting this on every Player Status Update, even if i did not level up :)

**Comment by Ar1i** [comment]
Update :)

**Comment by FreeHux** [comment]
using the latest build :D

**Comment by lucas2107** [comment]
Fixed in the lastest update ^^ Working for me :+1:

**Comment by FreeHux** [comment]
after i hit a level up.. i allways get it :/
