### ISSUE TITLE
it keeps doing it over and over ?????

### ISSUE THREAD

**Issue by cheese313** [Ar1i/PokemonGo-Bot#1774]
![capture](https://cloud.githubusercontent.com/assets/20838570/17465208/6655130a-5cbf-11e6-9d53-3e0a4b0771d0.PNG)

**Comment by xhalfbakedguy** [comment]
compare it to the phone app crashing. my guess is no response from the server. happens every hour or so for me

**Comment by FlyHaxHD** [comment]
Its normal. Its actually good. Its just like a refresh.
