### ISSUE TITLE
Bot doesn't transfer pokemons

### ISSUE THREAD

**Issue by Azmich** [Ar1i/PokemonGo-Bot#1775]
My bot doesnt transefer pokemons so after 2-3 hours it says : Can't catch pokemon because inventory is full. So i manually transfer my pokemons. Is there any solution?

BTW: Thanks for the hard work i really appriciate that ^_^

**Comment by arjunvegda** [comment]
#1609

**Comment by Praxthisnovcht** [comment]
![capture](https://cloud.githubusercontent.com/assets/9677000/17465252/5293c842-5ca7-11e6-9f49-e35cd942ec11.PNG)

**Comment by Azmich** [comment]
Thank you so much for solution ^_^
