### ISSUE TITLE
Sorry Third time...

### ISSUE THREAD

**Issue by Hazuke1337** [Ar1i/PokemonGo-Bot#1778]
i switched the location i download the bot a secound time and it says "there is no pokestop in a radius of... meters". god damn Ar1i don´t say always that i need to switch the location xD

**Comment by eliteknight** [comment]
change town

**Comment by Hazuke1337** [comment]
bro i just changed from New York to LA xD

**Comment by arjunvegda** [comment]
Try this location.

And make sure your bot is updated to the latest version.
Lat = 37.797788

Lon = -122.40077
