### ISSUE TITLE
open account on phone

### ISSUE THREAD

**Issue by jivie2006** [Ar1i/PokemonGo-Bot#1779]
can i open poke go from phone if i turn off gps while the bot is running?

**Comment by Hazuke1337** [comment]
try it xD

**Comment by cheese313** [comment]
ya you can

**Comment by jivie2006** [comment]
im not worried about ban factor just curious what the bot will do if i get on to buy incubators

**Comment by Hamouda55** [comment]
YEAH YEAH U CAN DO IT I MAKE AND EVOLVVEEEEEEEEEEEEE 

Happy Hunting
Sorry for being CRAAAAAAAAAAAAZY++

**Comment by Ritzii** [comment]
I think so long as you don't use anything on your phone when you login, you should be fine. I've done it several times to check the Gym where I live and put a new egg in the incubators and nothing has happened. You could just close the bot, buy the incubators and restart if you are worried.
