### ISSUE TITLE
[Request] Sort the Pokemons in "Pokemon List" by number of pokemons

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#178]
How about giving the user to sort the pokemons in pokelist by number.
So that they can easy transfer 9 of 10 pidgeys

**Comment by globsch** [comment]
`        private async Task PrintPokemon()
        {
           
                var PokemonCount = await _inventory.GetPokemonCount();

                foreach (var Pokemon in PokemonCount.GroupBy(p => p.PokemonId).OrderByDescending(x => x.Count()).Where(x => x.Count() > 0))
                {
                Logger.ColoredConsoleWrite(ConsoleColor.Yellow, $"Got {StringUtils.getPokemonNameByLanguage(_clientSettings, Pokemon.Key)} # {Pokemon.Count()}", LogLevel.Info);

                await RandomHelper.RandomDelay(500, 700);
                    
                }
        }
`

add this to the Logic.cs and call it with:
`await PrintPokemon()`
