### ISSUE TITLE
Anyone know how to fix this?

### ISSUE THREAD

**Issue by Pyroman2300** [Ar1i/PokemonGo-Bot#1781]
http://i65.tinypic.com/25hznf5.jpg
Having a problem and idk what to do to fix it.

**Comment by xhalfbakedguy** [comment]
uhm wait 10 seconds??

**Comment by Pyroman2300** [comment]
My friend said its been like that for a while.

**Comment by suckerpunish** [comment]
yeah @Pyroman2300 am gonna try the newest version if am gonna face the same problem or not

**Comment by arjunvegda** [comment]
Update the bot. Maybe it would solve it.

**Comment by Pyroman2300** [comment]
Alright, I have to newest version and I don't get this, but my friend does. He has the latest version.

**Comment by arjunvegda** [comment]
I would delete whole folder and download again and try.
Also please check the existing issues before posting
#1751 , #1717

**Comment by Pyroman2300** [comment]
K just asking buddy.
