### ISSUE TITLE
Can't catch

### ISSUE THREAD

**Issue by solodolo59** [Ar1i/PokemonGo-Bot#1782]
Always This message "... got away while using itempokeball"

**Comment by BluCone** [comment]
You are softbanned, takes 3-4 hours till unban

**Comment by frktml** [comment]
soft ban use force unban button..

**Comment by Pyroman2300** [comment]
You are probably softbanned, use the Force-unban feature of just wait. The bot at one point auto-detected the bans and fixed them.

**Comment by john-hardesky** [comment]
See: #1737 #1742

**Comment by solodolo59** [comment]
Thanks
