### ISSUE TITLE
not sure what this is

### ISSUE THREAD

**Issue by jivie2006** [Ar1i/PokemonGo-Bot#1786]
![image](https://cloud.githubusercontent.com/assets/20846886/17465478/961dec4e-5cbd-11e6-8b4a-b13a8d4ae078.png)

was working great for about an hour, then this started. no changes made or altered, moving bot at default 50. also tried my daughters account and no luck

**Comment by BlackHatching** [comment]
Seems like the config file is corrupted

**Comment by BlackHatching** [comment]
Try to delete the folder, configure it again and change the location too

**Comment by jivie2006** [comment]
![image](https://cloud.githubusercontent.com/assets/20846886/17465623/2cef9a38-5cc2-11e6-880b-d5a095fd53b3.png)
i did a reset and this is what i got this time, hit a couple stops and then started to do it again

**Comment by pokerave** [comment]
try uncheck hatch eggs
