### ISSUE TITLE
player stats update

### ISSUE THREAD

**Issue by crazyandy3** [Ar1i/PokemonGo-Bot#1787]
please cen we have the old payerstats updater  the new one is litel bugy and hard to read  and its all messy :(

**Comment by BlackHatching** [comment]
What do you mean ?

**Comment by crazyandy3** [comment]
https://i.imgsafe.org/7aef761926.png
 the  old  playerstat updater wos   perfect  i dont know why he change it   i cant even see my curent lvl or enything alse its hard to read :(
