### ISSUE TITLE
not deleting all double pokemons

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#1789]
the bot won't duplicate pokemons even if all conditions are met(Sometimes I catch 6 pokemmon in one location then when he shows my stats(light blue) he only deletes 1 then the next time he show the stats he deletes another one but when the bot is on a roll he gets backed up causing me to have 10 geodudes and 10 pîdgeys....and eventually I run out of space.

**Comment by BlackHatching** [comment]
Config screen?

**Comment by Ritzii** [comment]
Do you have it set to keep Pokemon that can be evolved, but not set to auto evolve the ones it's keeping?

**Comment by suljo94** [comment]
@Ritzii yes I did. it is probably that issie but can't that be fixed by checking (max duplicates and then removing 1

**Comment by 13XxM1CHA3lxX37** [comment]
Check Pokemon list if their IV isn't >90%

**Comment by nekudah** [comment]
Close bot, delete all content on Config folder, run again the bot  as Administrator and on "General" tab uncheck Keep Pokemons Which can be evolved and on "Pokemon" tab check "Auto transfer" and put how many copies of each pokemons you want to keep, I recommend 2 for farming

**Comment by suljo94** [comment]
@nekudah I did that just now but Iset it to 1
