### ISSUE TITLE
1337 unban method no longer works

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#1790]
all 4 of my accounts just got banned at the same time, tried the force unban button nothing happened, also changed location so the bot would auto try it and it said "probably unbanned you" but still softban

**Comment by john-hardesky** [comment]
Don't double report issue.
Close #1784

**Comment by arjunvegda** [comment]
@john-hardesky 1770

**Comment by arjunvegda** [comment]
#1695

**Comment by OGcpalm** [comment]
I'm not getting exp or catching pokemon

**Comment by acelya** [comment]
use the "Force Unban" function it still works..

**Comment by pokerave** [comment]
unban still works.. maybe you are using one account with 2 bots? or open 1 account with 2 device.

also check your pokeball if configured correctly

**Comment by OGcpalm** [comment]
just deleted and redownloaded seems to be working now
