### ISSUE TITLE
Issue. Bot doesn't work

### ISSUE THREAD

**Issue by giordanojr** [Ar1i/PokemonGo-Bot#1793]
How do i fix this? bot doesn't work 
![screenshot_1](https://cloud.githubusercontent.com/assets/20893195/17465575/23d58c5a-5cd1-11e6-91e7-a80e92cd4234.png)

**Comment by Praxthisnovcht** [comment]
screnn ?

**Comment by Jekzi** [comment]
download the new update

**Comment by wellrccity** [comment]
aqui deu tbm mas voltou ao normal dps de reiniciar o pc

**Comment by nekudah** [comment]
Run PokemonGo.RocketAPI.Console as Administrator
