### ISSUE TITLE
210XP for each catch?

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#1795]
Not using magic egg and each repeated catch:
[23:29:34] Caught Clefairy CP 77 IV 34% using ItemPokeBall got 210 XP.

**Comment by immoempe** [comment]
yes that's right

**Comment by zzzz9999** [comment]
but in game is 100 / 110 XP
Or bot is using any trick to curve ball or something?

**Comment by Gengar09** [comment]
catch pokemon 100 xp + excellent throm 100 xp + curveball 10 xp

**Comment by zzzz9999** [comment]
Thanks for reply.
Closing issue....
