### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#1796]
![error](https://cloud.githubusercontent.com/assets/20752818/17465722/068a5d90-5d00-11e6-82ac-f9f6a4179c6e.png)

I got this Error.

**Comment by zzzz9999** [comment]
Then bot "restarts" and continue his work, right?

**Comment by KappaLord123** [comment]
this happend to me after a hour or so, it did this then said it would "restart" but it would just keep popping the error after it "restarted"...

**Comment by jefferygroseclose** [comment]
Bump

**Comment by BlackHatching** [comment]
try another version of build to see wht happens
If that worked so copy Config to the new build

**Comment by FAymYs19** [comment]
yeah i know its not a big deal. its restating 10 sec later and it works fine.
i just thought that it maybe could be usefull for Ar1i maybe. :D

**Comment by audota000** [comment]
same here, it might be a bug that need to be fixed.
