### ISSUE TITLE
[Request] recycling items

### ISSUE THREAD

**Issue by petpetpetvm** [Ar1i/PokemonGo-Bot#1798]
because most of the time, i put a lot of ultraball and none pokeball in setting (of course)...
and the bot always recycle pokeball really early (even there are like 200+ free spot) and come out I don't have so little balls that not enough for using.
Is there anyway that you can fix the bot to recycle items when there is like 50 or less spots ?
thank you and awesome bot

**Comment by BlackHatching** [comment]
it takes at least 2s to recycle pokeballs don't worry
If you have 200+spots  put 30 pokeballs

**Comment by petpetpetvm** [comment]
i have 1000 spot and put 20 pokeball, 600 ultraball, about 1hr later, i turned off the bot and walked around and the balls is out really fast
