### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by Gamer82** [Ar1i/PokemonGo-Bot#180]
Brauche hilfe,
er macht ein STop dann kommt der fehler und immer im wechsel.
Woran kann es liegt ???

Danke im vorraus

[11:39:23] Distance to target location: 62,99 meters. Will take -283,47 seconds!
[11:39:24] Exception: System.ArgumentOutOfRangeException: Der Wert muss entweder -1 (dies gibt einen unendlichen Timeout an), 0 oder eine positive ganze Zahl sein.
Parametername: millisecondsDelay
   bei System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay)
   bei PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() in C:\Spiele\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Navigation.cs:Zeile 100.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__14.MoveNext() in C:\Spiele\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 268.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__9.MoveNext() in C:\Spiele\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 136.
[11:39:24] Starting again.. But waiting 10 Seconds..
[11:39:34] We got the API Url: pgorelease.nianticlabs.com/plfe/569
[11:39:36] Export Player Infos and all Pokemon to "\Export\PokemonList.csv"

**Comment by Ar1i** [comment]
Its fixed now
