### ISSUE TITLE
Softban on all accounts same time... lol

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#1801]
Someone else too?

**Comment by cktisaac** [comment]
same

**Comment by kazzaluis** [comment]
same

**Comment by dragonuts330** [comment]
was likewise, was curious. it seems it throws one up every once and while.

**Comment by lamweixing** [comment]
same can't find pokestops

**Comment by money1989** [comment]
same here

**Comment by Safti54** [comment]
same

**Comment by downspath** [comment]
same
i logged in with my phone: cant find any pocestops

**Comment by micreu** [comment]
same

**Comment by lailaps** [comment]
You guys are all in New York too?

**Comment by adman9031** [comment]
yeah i retried after maybe ten minutes and everything started off okay but no more that two minutes later the same thing occured

**Comment by downspath** [comment]
banwave?

**Comment by NagaCS** [comment]
^ Possible

**Comment by micreu** [comment]
R.I.P

**Comment by justchil** [comment]
ditto D:

**Comment by adman9031** [comment]
the account isnt banned i tried logging on my phone and everything worked fine

**Comment by micreu** [comment]
Api update again?

**Comment by lailaps** [comment]
Maybe server problems in New York.

**Comment by justchil** [comment]
I am using a local city < 10 miles away.  This is strange.  I am not using NY area.

**Comment by xcrumpy** [comment]
I swear if they updated api again.

**Comment by downspath** [comment]
i am in austria and cant find any pokestops on my phone

**Comment by lailaps** [comment]
No Pokestops or softban, no single account active atm.

**Comment by evrine** [comment]
Hong Kong, Tokyo can't find any pokestops API again? :D

**Comment by downspath** [comment]
no update in appstore... hmm

**Comment by Safti54** [comment]
ohhhh i hope they didnt update API  again man -.-

**Comment by adman9031** [comment]
and the servers never went down either like the last time they updated the api

**Comment by NagaCS** [comment]
@downspath they didnt update the game via appstore, it was implemented server side

**Comment by evrine** [comment]
Guys check status, any1 have link?

**Comment by xcrumpy** [comment]
pokeadvisor isnt showing a ban

**Comment by BlackHatching** [comment]
Try to delete your default coordinates in the Config.txt and then change your Location i recommend to change continent

**Comment by BrandonHCD** [comment]
idk if this means anything http://www.mmoserverstatus.com/pokemon_go

**Comment by evrine** [comment]
Poke Club Login791ms

**Comment by downspath** [comment]
very high ping
i thing it is a serversided problem

**Comment by Hardbas** [comment]
Well, I live in Colombia and everything is normal.

**Comment by xcrumpy** [comment]
so do we think its just the US servers

**Comment by lamweixing** [comment]
@Hardbas where are your bots at?

**Comment by downspath** [comment]
hardbas your pokestops work?

**Comment by micreu** [comment]
also germany / netherlands and ASIA

**Comment by Hardbas** [comment]
Yeah!... everything is working for me

**Comment by alexhart123** [comment]
It happened to me with all my ptc and google accounts around the same time this post was made.

**Comment by evrine** [comment]
BTW guys, what settings location do you have to get more than 100k xp per hour?

**Comment by lailaps** [comment]
Seems to be just server problems.

**Comment by BlackHatching** [comment]
Check with a VPN guys

**Comment by downspath** [comment]
austria does not work, i wont change country they test you

**Comment by Souluzumaki** [comment]
mine is working (Maryland)

**Comment by micreu** [comment]
tokio, disneyland @evrine

**Comment by downspath** [comment]
use the standart settings and evolve and stuff witn about 100 kmh

**Comment by evrine** [comment]
@micreu I tried, and just 70k per hour

**Comment by cktisaac** [comment]
i think they changed the API again?

**Comment by downspath** [comment]
the app works again

**Comment by micreu** [comment]
@evrine well, im using luckyEgg all the time

**Comment by Safti54** [comment]
it works in zurich switzerland but it dosent take any Pokestop like it wont spin the pokestop

**Comment by BrandonHCD** [comment]
so what is the best speed? 100 kmh?

**Comment by Safti54** [comment]
mine is always on 60 km/h

**Comment by evrine** [comment]
@micreu whats ur move radius and speed?

**Comment by downspath** [comment]
everything is normal again

**Comment by Safti54** [comment]
in a range of 10 km

**Comment by xBudSpencer** [comment]
same here iam in SF peer 39

**Comment by downspath** [comment]
bot works

**Comment by micreu** [comment]
@evrine 59 km/h and 5000 metres

**Comment by lailaps** [comment]
Some accounts start working again, without doing anything.

**Comment by Souluzumaki** [comment]
maybe alot of users teleported?

**Comment by cktisaac** [comment]
this pokemon go server

**Comment by phoeniXX1337** [comment]
it says something with the pokemon list lol

**Comment by christopherbees** [comment]
probably server problems

**Comment by downspath** [comment]
thats is why the server has a uptime off 99,7%

**Comment by micreu** [comment]
prc login doesnt work anymore....

**Comment by bramvanbeek** [comment]
1 had 5 bots on my pc and all got a softban, logged in on ptc account did not work... my dad logged in and it worked for him....

everything seems to work again.. 
 still no clue what is was..

**Comment by phoeniXX1337** [comment]
Farmed XP: 50, Items: Nothing (Inventory Full?) what does that mean lol

**Comment by evrine** [comment]
I think servers are down, I cant log

**Comment by phoeniXX1337** [comment]
it farmed 4 times pokestops and then the error again

**Comment by downspath** [comment]
phoeni it means your inventory is full

**Comment by phoeniXX1337** [comment]
i thought the bot is recycling the items

**Comment by bramvanbeek** [comment]
whahah yea mine to phoeni

**Comment by downspath** [comment]
you have space for 350 items, dont forget you have eggs and stuff too

**Comment by downspath** [comment]
so: full

**Comment by micreu** [comment]
working again on ptc

google acc still down

**Comment by phoeniXX1337** [comment]
446/350 items hahaha

**Comment by bramvanbeek** [comment]
everything works at my place ptc & google  ( Netherlands)

**Comment by downspath** [comment]
http://ispokemongodownornot.com/

**Comment by downspath** [comment]
droped to 99.0 lol

**Comment by phoeniXX1337** [comment]
everytime when its workin it goes on 2 pokestops and then the error accured again

**Comment by xcrumpy** [comment]
Tons of errors now

**Comment by BlackHatching** [comment]
i verified i think its an API change

**Comment by xuban** [comment]
In Europe (Spain) same problem.

**Comment by xcrumpy** [comment]
why niantic

**Comment by phoeniXX1337** [comment]
so rip botting again?

**Comment by phoeniXX1337** [comment]
its working again lol

**Comment by evrine** [comment]
wotking guys, try relog

**Comment by phoeniXX1337** [comment]
and rip again ._.

**Comment by downspath** [comment]
mine works noemal

**Comment by Midnlght** [comment]
well shit lol

**Comment by Biscuit090** [comment]
It's working for me, there should be a button that says "Force unban" on the pokemon list window.

**Comment by phoeniXX1337** [comment]
i think its just bugging out right now

**Comment by alexhart123** [comment]
Mine still don't work. This looks like server problems.

**Comment by Safti54** [comment]
well i got two acc working perfectly but the third is full of errors

**Comment by bramvanbeek** [comment]
mine runs fine just running 1 acc right now.. gonna wait a few minutes

**Comment by downspath** [comment]
just a short downtime it runns notmal on ptc , checking google

**Comment by alexhart123** [comment]
Stop scaremongering with all the banwave and api change rhetoric.

**Comment by Souluzumaki** [comment]
mine works normal too

**Comment by BlackHatching** [comment]
so

**Comment by phoeniXX1337** [comment]
i want to go to sleep :( but i want to bot over the night :dash:

**Comment by Hardbas** [comment]
Mine still working normally!
 I live in Colombia

**Comment by cktisaac** [comment]
works normal now

**Comment by Biscuit090** [comment]
then leave it on, it'll fix itself

**Comment by Midnlght** [comment]
mine works fine , from CA,

**Comment by phoeniXX1337** [comment]
kay  hope so.. good night everyone :v:

**Comment by Biscuit090** [comment]
Yeah, it's working fine now. No problems anymore.

**Comment by phoeniXX1337** [comment]
still bugging, from germany..

**Comment by bramvanbeek** [comment]
Netherlands up and runnign

**Comment by alexhart123** [comment]
Servers are shitting themselves. Just wait a little while, it'll fix itself.

**Comment by downspath** [comment]
[01:24:46] Error reloading Pokemon list: Die Sequenz enthält kein übereinstimmendes Element.
[01:24:48] Error reloading Pokemon list: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

this error ocours if i try to run a 2nd ptc acc

**Comment by NaveTK** [comment]
buggy for me still (germany)

**Comment by lailaps** [comment]
Yep, me too!

**Comment by BlackHatching** [comment]
That's a server bug i conclude

**Comment by alexhart123** [comment]
Down for me in Chicago.

**Comment by Biscuit090** [comment]
Okay so German servers are currently experiencing issues

**Comment by downspath** [comment]
only with a 2nd acc

**Comment by xBudSpencer** [comment]
i have this problem with one acc ... germany

**Comment by evrine** [comment]
Guys put there your locations, settings speed and radius + xp per hour. Let's find the best place and settings for our bot.

Tokyo Disneyland : 35.633511709084274, 139.87992525100708 - 100km/h , 5000m - 70-80 k xp

**Comment by Safti54** [comment]
in switzerland u can run up to two acc the third one is a mess ^^ tons of errors ^^

**Comment by Hardbas** [comment]
where is the best place for our bots guys?

**Comment by Waiiim** [comment]
You know guys, it's not by raming yourself in that the servers are gonna get better....

**Comment by Safti54** [comment]
new york central park 40k xp/h

**Comment by evrine** [comment]
Tokyo Disneyland  around 70k/h

**Comment by downspath** [comment]
i think the server has problems

**Comment by evrine** [comment]
in necrobot I saw 200-350k xp/h in Tokyo

**Comment by Safti54** [comment]
yeah thats my thoughts to

**Comment by Souluzumaki** [comment]
anyone knows a good dratini farming spot?

**Comment by Safti54** [comment]
ohh shit really ? :D

**Comment by xcrumpy** [comment]
2/4 of my accounts are working wtf

**Comment by WhiteyTheKillah** [comment]
Can someone else confirm that tokyo disneyland farming rate?

**Comment by phoeniXX1337** [comment]
its just bugging...
im trying tokyo disneyland right now

**Comment by evrine** [comment]
Our bot is slow but I really like it :P Hope Ar1i will make something that we can gain 200k / h

**Comment by cirnolp** [comment]
Stay on topic please, this is not a forum to discuss about farming spots.  #1748

**Comment by downspath** [comment]
slow but steady bots are the best

**Comment by Waiiim** [comment]
35.633511709084274, 139.87992525100708 is in the middle of the ocean for me :x:

**Comment by downspath** [comment]
i am currently online with my nohack acc at my phone: the server has big problems

**Comment by xcrumpy** [comment]
Sill only able to run 2 accounts

**Comment by bramvanbeek** [comment]
try new york manhattan park....

**Comment by lailaps** [comment]
@Waiiim Nope, that's near Tokyo Disneyland.

**Comment by downspath** [comment]
turn off list gui, it works now for me

**Comment by xuban** [comment]
Logically farm more the faster you go. Stop comparing, this is not a forum.

**Comment by downspath** [comment]
od still the white error

**Comment by downspath** [comment]
[01:45:32] Exception: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PokemonGo.RocketAPI.Rpc.Inventory.<getInventoryCount>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:Zeile 87.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 186.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 356.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 129.

who knows what this means?

**Comment by alexhart123** [comment]
http://downdetector.com/status/pokemon-go/map/

**Comment by NaveTK** [comment]
@alexhart123 no wonder i have trouble logging in from germany :D it's all red

**Comment by downspath** [comment]
all 4 bots are running normal and without error since 3 min (only 1 white error when i started them ^last post (what does it mean?)

**Comment by downspath** [comment]
just got softbaned on 3 of them...
