### ISSUE TITLE
not working suddenly

### ISSUE THREAD

**Issue by jmo93** [Ar1i/PokemonGo-Bot#1804]
![screenshot 21](https://cloud.githubusercontent.com/assets/20781018/17466027/da46536e-5d05-11e6-8a21-8f0d77edebe5.png)

**Comment by BlubbPaule** [comment]
Same for me. Suddenly nothing is working anymore.

**Comment by draga123** [comment]
Same issue.

**Comment by pedromaia1234** [comment]
same

**Comment by BlubbPaule** [comment]
The first thing it said was "File seems to be already in use"
After that it keeps repeating that what you see in the screenshot .

**Comment by 13XxM1CHA3lxX37** [comment]
Same thing here. But ironically some instances are working.
App is also fine

**Comment by alexhart123** [comment]
http://downdetector.com/status/pokemon-go/map/

**Comment by jmo93** [comment]
Ok
