### ISSUE TITLE
Getting errors since an hour ago

### ISSUE THREAD

**Issue by CastleFan1983** [Ar1i/PokemonGo-Bot#1805]
![error](https://cloud.githubusercontent.com/assets/20824641/17466030/e74e549e-5d05-11e6-8fe8-de01ec397c0e.jpg)

**Comment by draga123** [comment]
Yeh, got the same issue.

**Comment by smedicejr** [comment]
Are you using Google accounts? Getting the same error.

**Comment by NaaTiiVee** [comment]
Servers are offline..

**Comment by NaaTiiVee** [comment]
http://downdetector.com/status/pokemon-go

**Comment by CastleFan1983** [comment]
servers aren´t offline, bot still works with version 1.0.7.0

**Comment by MOE4HACKS** [comment]
http://cmmcd.com/PokemonGo/   servers offline

**Comment by CastleFan1983** [comment]
im still online with my bot so the severs cant be down :)

**Comment by smedicejr** [comment]
PTC acc is working fine

**Comment by MOE4HACKS** [comment]
close your bot and run it again

**Comment by CastleFan1983** [comment]
closed my bot, started again and im still catching pokemon, so the servers aren´t down here

**Comment by MOE4HACKS** [comment]
Maybe it depends on locations?

**Comment by CastleFan1983** [comment]
seems so
