### ISSUE TITLE
Getting this error every 10 seconds.

### ISSUE THREAD

**Issue by xxKevinSniperxx** [Ar1i/PokemonGo-Bot#1807]
http://i.imgur.com/FOa4sO2.png

**Comment by zzzz9999** [comment]
same here ...

**Comment by Alushi99** [comment]
Yeah it stopped working

**Comment by itzjaydon** [comment]
yeah i got this so i reinstalled the bot and now it works

**Comment by gorgis112** [comment]
same

**Comment by CliveCockster** [comment]
Same here... 5 Accounts in 1 Time Softban but

**Comment by BlackHatching** [comment]
Test now thats working

**Comment by zzzz9999** [comment]
what do you mean "reinstall" bot?

**Comment by itzjaydon** [comment]
delete the whole bot and download it again

**Comment by corydoraswhite** [comment]
Only got it my Google Accounts. PTC account still running fine.

**Comment by xxKevinSniperxx** [comment]
its working now, try reinstalling the bot

**Comment by itzjaydon** [comment]
@xxKevinSniperxx  thats what i did

**Comment by xxKevinSniperxx** [comment]
ok nevermind, the issue is still alive

**Comment by pedromaia1234** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by xxKevinSniperxx** [comment]
ok, i have come to the conclusion that the servers are unstable at the moment, the bot may or may not work at the moment

**Comment by DaniOurGamer** [comment]
`[01:26:05] Starting again in 10 seconds...
[01:26:16] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[01:26:16] Exception: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:línea 276
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:línea 174
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   en PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:línea 115`

**Comment by Safti54** [comment]
export player infos and pokemon to csv not possible what does that mean ?
