### ISSUE TITLE
GPS BUG

### ISSUE THREAD

**Issue by apollo2244** [Ar1i/PokemonGo-Bot#1808]
Hello dear Community and Developpers,

I wanted to report a bug about the GPS of your Skript. If I choose the coordinates of Luxemburg City, the altitude coordinates are set to 0 which make the bot unfunctional. In the last version, he accepted the coordinates and set the right altitude.
Here is a little screenshot of the Issue the bot gave me.
![errorlog](https://cloud.githubusercontent.com/assets/20893988/17466049/50e27d72-5d06-11e6-8a8c-e55016a50307.PNG)

Thanks for your help,

Apollo2244

**Comment by itzjaydon** [comment]
hey i got this too so what i did is delete the whole thing then re download works like a charm once again

**Comment by Alushi99** [comment]
Did it work?

**Comment by BlackHatching** [comment]
Fixed, thats a server bug

**Comment by Alushi99** [comment]
Mines still broken

**Comment by BlackHatching** [comment]
Thats working 1 times/5

**Comment by apollo2244** [comment]
@Alushi99 Reinstalling didn't work

@BlackHatching it works very rare

**Comment by Alushi99** [comment]
How did you guys get it to evolve mons automatically?

**Comment by BlackHatching** [comment]
works nw

**Comment by dominik1122** [comment]
works

**Comment by Alushi99** [comment]
What are your guys' coordinates and xp/hr

**Comment by apollo2244** [comment]
Still doesn't work for me....

**Comment by Alushi99** [comment]
Im getting soft banned

**Comment by apollo2244** [comment]
@BlackHatching @dominik1122 How? It is still not working for me

**Comment by apollo2244** [comment]
Here is the real Problem![0altitude](https://cloud.githubusercontent.com/assets/20893988/17466202/a0076576-5d0a-11e6-885e-b44badc3adda.PNG)
