### ISSUE TITLE
Is it just my computer or the file has problem?

### ISSUE THREAD

**Issue by redforres** [Ar1i/PokemonGo-Bot#1811]
![capture0](https://cloud.githubusercontent.com/assets/20889994/17466064/61bb4cf0-5cd4-11e6-8ded-d86caadddc8b.JPG)

It's a fresh download this morning, and it triggers the virus scanner when I tried to move the contents to another folder.....

Anyone else has the same issue?

**Comment by dreyan1** [comment]
my avast also finds a virus in the new file. hmm?

**Comment by redforres** [comment]
And I just tested. if I move other executable,  the anti-virus will not complain.. it does only on this file..
