### ISSUE TITLE
Whats is this ?

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#1812]
![image](https://cloud.githubusercontent.com/assets/1984839/17466087/7a742f44-5ccc-11e6-9fed-ebe7d19e5f03.png)

**Comment by pedromaia1234** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by kazzaluis** [comment]
is for the down server???

**Comment by shaoware** [comment]
I've the same pb

**Comment by kazzaluis** [comment]
well ty i will wait

**Comment by Zunzel** [comment]
now it works again --> server bug

**Comment by xcrumpy** [comment]
if its still not working delete you players excel file in the configs

**Comment by kazzaluis** [comment]
nop still the same and when i check te GUI Pokemon list appear this

![image](https://cloud.githubusercontent.com/assets/1984839/17466113/4fff6660-5ccd-11e6-8cb6-f5ac94f4e4fc.png)

**Comment by shaoware** [comment]
Working while 5min of wating on the console

**Comment by christopherbees** [comment]
same problem here

**Comment by swtrpeter** [comment]
Same Here
![error](https://cloud.githubusercontent.com/assets/20620293/17466117/8c854230-5ccd-11e6-8844-225350481499.PNG)

**Comment by Anonymous131** [comment]
If I use the other Rar "debugg" file, Kaspersky spyed an Malware.

**Comment by shaoware** [comment]
Not working sry

**Comment by moops44** [comment]
ppl just wait, a run 4 bots, 2 of them works
and on my main acc @ android phone i have server problem 
after many many  restarts in console it work

**Comment by kazzaluis** [comment]
![image](https://cloud.githubusercontent.com/assets/1984839/17466147/4f0743da-5cce-11e6-9a5f-c7aaa750f4f1.png)

**Comment by moops44** [comment]
![affee](https://cloud.githubusercontent.com/assets/20789896/17466152/3f9d7c4e-5d09-11e6-9e68-f5a960983e46.PNG)

**Comment by kazzaluis** [comment]
but how i can it works?

**Comment by asfo** [comment]
Just restart the bot, you run out of memory RAM ...
Don't reload pokemon list every 5 secs, if you do that, you waste more and more and more RAM. Just do it every 5 mins or more.

Or restart the bot, try updating it also and don't use the same folder because for some reason some people are having issues updating it on the same folder.

**Comment by moops44** [comment]
16gb ram is enough for bot bro ;)
@kazzaluis this is because the servers are unstable !
[http://www.mmoserverstatus.com/pokemon_go](url)

**Comment by Criispey** [comment]
It works for me now

**Comment by kazzaluis** [comment]
i have a workstation with 16 ram

i put refresh every 60,000 milsecs

**Comment by moops44** [comment]
it works a while then get down 
UNSTABLE SERVERS! close this " issue" thread pls 
@Ar1i
