### ISSUE TITLE
[NO ISSUE] Walking Speed?

### ISSUE THREAD

**Issue by Delogab** [Ar1i/PokemonGo-Bot#1813]
I´m just curious if it matters how fast i "walk" with the bot. I reduced the speed to 20km/h so it seems more "normal". Since the wrong API request is the main problem with being detected, does it even matter if i walk normally or super fast?

**Comment by DaniOurGamer** [comment]
I think that doesn´t matter because the bot auto adjust the speed when finds pokestops

**Comment by asfo** [comment]
This is not a forum, please report any bugs only :)...if you need help, try asking in reddit.
