### ISSUE TITLE
Cannot open more than 1 bot?

### ISSUE THREAD

**Issue by Biscuit090** [Ar1i/PokemonGo-Bot#1816]
![pkmn](https://cloud.githubusercontent.com/assets/20826708/17466118/cadce788-5cbc-11e6-8d41-fdbd4b5648a3.PNG)

This appears on every bot other than the first one I opened. Each bot opened is used for a different account.

**Comment by kazzaluis** [comment]
do you have the bots in diferent folder?
i don't have problem to open more than 1 bot but now server is offline

**Comment by asfo** [comment]
Or try with VM

**Comment by CreativiTimothy** [comment]
I have the same problem. I was able to open multiple bots. I'm not sure what happened but when I came back home from the beach, this started happening

**Comment by Biscuit090** [comment]
When it's not giving this grey text all the time it's just skipping over pokestops and heading to the next ones available.

**Comment by Safti54** [comment]
mine cant find any pokestops again -.-

**Comment by Biscuit090** [comment]
The bot works for me, it's just that I am unable to open more than one account at a time without it failing.

**Comment by xxKevinSniperxx** [comment]
yeah, idk why one of them works but not the other http://i.imgur.com/3iGzuoB.png

**Comment by HuDiNi27** [comment]
Yes. This seems to be the case for me. As soon as there is multiple bots open the errors start.

**Comment by Biscuit090** [comment]
Yeah I'm just not gonna risk it and only open one account for now

**Comment by xxKevinSniperxx** [comment]
it seems to be working now
