### ISSUE TITLE
Anybody else having this error ?

### ISSUE THREAD

**Issue by swtrpeter** [Ar1i/PokemonGo-Bot#1819]
Having this error at start and then everytime bot tries to catch.

![error](https://cloud.githubusercontent.com/assets/20620293/17466140/3a97e42c-5cce-11e6-9662-02f03cf2e453.PNG)

**Comment by RealShun** [comment]
yes dont know how i fix that

**Comment by Criispey** [comment]
yes sir

**Comment by Biscuit090** [comment]
I just closed the window and restarted it and it worked fine

**Comment by swtrpeter** [comment]
I have tried everything from restarting the process to restarting the server.

**Comment by swtrpeter** [comment]
Restarted and seemed to fix it for now. Must have been due to a server issue.
