### ISSUE TITLE
error reloading pokemon list 

### ISSUE THREAD

**Issue by tenboherce** [Ar1i/PokemonGo-Bot#1820]
well i got the error reloading pokemon list and some other errors every 10seconds loads of lines why can this be ?

**Comment by kazzaluis** [comment]
![image](https://cloud.githubusercontent.com/assets/1984839/17466148/560aeeb6-5cce-11e6-9916-e7f949865d51.png)

**Comment by tenboherce** [comment]
it's empty for me

**Comment by Biscuit090** [comment]
It's still loading your pokemon list lol just wait

**Comment by kazzaluis** [comment]
![image](https://cloud.githubusercontent.com/assets/1984839/17466153/9aceb8d4-5cce-11e6-91ae-04ef899f08d8.png)
 this error for loading pokemon list

**Comment by kazzaluis** [comment]
Insufficient memory

Object reference not set to an instance of object

**Comment by Biscuit090** [comment]
"Memoria insuficiente" is Spanish for "Insufficient memory" so... that means your pokemon storage is ful

**Comment by tenboherce** [comment]
![error](https://cloud.githubusercontent.com/assets/20837933/17466156/650007cc-5d09-11e6-849f-4143c0bf55c9.png)

this is my error

**Comment by kazzaluis** [comment]
i have more space in my pokemon storage, i have 500 slots

**Comment by Biscuit090** [comment]
"loginfailedexception" probably a wrong password?

**Comment by mrflux** [comment]
@kazzaluis bro quick question where do you farm to have those dragonites.

**Comment by kazzaluis** [comment]
@mrflux Santa monica

**Comment by mrflux** [comment]
@kazzaluis ok thanks bro

**Comment by Rannilas** [comment]
I am also getting "Object reference not set to an instance of object".  Trying to attach a screen cap but I'm getting "something went really wrong, and we can't process that file." from github.

**Comment by Rannilas** [comment]
![error reloading pokemon list](https://cloud.githubusercontent.com/assets/20826782/17466239/2f247fa0-5cd9-11e6-8d77-d7a1462237f6.jpg)

**Comment by tenboherce** [comment]
i did right password no idea whats happening

**Comment by Anonymous131** [comment]
i got " System.InvalidOperations :/

It switches about working, catch pokemons, but bring the same message. all few seconds

**Comment by slitherin** [comment]
I'm getting something really similar to @Rannilas but mine's a bit longer.

![error](https://cloud.githubusercontent.com/assets/20894502/17466336/8a735bc2-5cc2-11e6-9c4f-0a75fd50cd5e.jpg)

**Comment by fikrirmd** [comment]
i had the same problem, but after i uncheck the "Enable Pokemon list GUI", its solved.
but i cant see my pokemon list anymore.

![fdbfdbfd](https://cloud.githubusercontent.com/assets/20740665/17466400/b0b0241a-5d39-11e6-8693-ed2a5d962192.jpg)
