### ISSUE TITLE
This is a little bit odd

### ISSUE THREAD

**Issue by aquilinachu** [Ar1i/PokemonGo-Bot#1821]
So I got 4 accounts currently farming on bot. 2 Gmail and 2 PTC

I get that there are some problems right now, but this is before those problems. Gmail ones are not working atm. PTC's work. But the problem is;

First PTC account can go to pokestops and get items&exp but every single pokemon runs away.
Second PTC account can do everything but it gives an error message every 2 minutes (the one everyone posts right now).

Please do not post server status as a comment, this has been like this since the release of the new bot.

**Comment by xJihadx** [comment]
softban?
