### ISSUE TITLE
Strait up freezing

### ISSUE THREAD

**Issue by iridiumkills** [Ar1i/PokemonGo-Bot#1822]
The console seems to just freeze, no error, no "not responding", it'll just have the timestamp from the last thing that happened. It's happened to  me multiple times now today

**Comment by CliveCockster** [comment]
Press Enter and Fix it ^^ same by me ^^

**Comment by zzzz9999** [comment]
if you right click console (DOS console) it might get freeze.

**Comment by iridiumkills** [comment]
Yea I noticed that right clicking freezes it a few days ago, but it wasn't even that, I'll run it, and then hours later I'll check and then it'll be frozen
