### ISSUE TITLE
Soft ban?

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#1823]
Been running bot a few mins and every pokemon is getting away.. Bot isn,t trying to unban me. 
Any suggestion or anything I should know?

**Comment by Biscuit090** [comment]
There should be a button on the Pokémon list window that says "Force Unban". It should unban you at the next pokestop.

**Comment by Praxthisnovcht** [comment]
make sure to pick one and start pokestop yellow highlighter
![force unban](https://cloud.githubusercontent.com/assets/9677000/17466170/72d1d98e-5cbe-11e6-86bd-c8ad22842360.PNG)

**Comment by CowMadness** [comment]
What you mean pick one?
 I did force unban a few times already and still not catching any pokemon.

**Comment by solodolo59** [comment]
Same, force unban does''tu work
