### ISSUE TITLE
Pokemon not Tranfer

### ISSUE THREAD

**Issue by kilakuma** [Ar1i/PokemonGo-Bot#1824]
I run bot 1-2 hr. bot is normal 
but now bot not tranfer pokemon

**Comment by Biscuit090** [comment]
Then restart it.

**Comment by Praxthisnovcht** [comment]
trying to withdraw and it should work but configure pokemons not transfer
![evolution](https://cloud.githubusercontent.com/assets/9677000/17466194/0c857266-5cbf-11e6-8a9d-6478a14ac7e9.PNG)

**Comment by kilakuma** [comment]
@Biscuit090 @Praxthisnovcht i try re-program it doesn't work then i re-extract file program is run normoly :)

*
![untitled2](https://cloud.githubusercontent.com/assets/8610752/17466296/fab67ed6-5d36-11e6-915d-c79155e81002.png)
