### ISSUE TITLE
Where are the best Location ?/Wo sind die besten Locations ?

### ISSUE THREAD

**Issue by Bosskiller1711** [Ar1i/PokemonGo-Bot#1825]
Brauche dringend eine Location Wo man richtig gute Pokémon's finden kann, so wie Raichu , Diesen riesen Drachen , Relaxo oder so , gibt bitte die Breite und Länge Daten

**Comment by moops44** [comment]
ist zwar kein issue aber naja nächstes mal 
www.gidf.de versuchen  !!!

die wirst du nicht direkt finden bzw ein nest
aber hier ne seite mit daten http://pokesnipers.com/
