### ISSUE TITLE
Cannot find 'LastCoords

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#1826]

**Comment by steezespot** [comment]
Cannot find last coords file anymore? Is it not in the latest download?

**Comment by Praxthisnovcht** [comment]
looks in this file
![lastcord](https://cloud.githubusercontent.com/assets/9677000/17466218/8d5c2ac4-5cbf-11e6-8ce7-aabba61f02a0.PNG)

**Comment by misakiw** [comment]
hi steezespot, 

Same as you, I did not find the LastCoords file anymore in the recent build. The file Praxthisnovcht highlighted is dated in the past (3/8). That should be the old file kept in the same folder??
