### ISSUE TITLE
Soft ban.

### ISSUE THREAD

**Issue by Manugc1** [Ar1i/PokemonGo-Bot#1828]
I just get banned but the bot cant unban me. What can i do?
![screenshot_1](https://cloud.githubusercontent.com/assets/20894332/17466215/0896d2d6-5ce1-11e6-8678-df097052b6bc.png)

**Comment by CliveCockster** [comment]
Ur unbanned dude 

Probatly Unbanned now...

**Comment by beasttry** [comment]
did you get unbanned right after?

**Comment by Praxthisnovcht** [comment]
you no ban .you capture pokemon

**Comment by draga123** [comment]
Your pokeballs is set to 0. Change that to 10 (Pokeballs cannot be set to 0, because the bot uses them)

**Comment by Ritzii** [comment]
You just got unlucky and some Pokes fled.
  
20:51:45 - you caught Nidoran = not banned.
20:52:07 - you looted a Pokestop = not banned.
20:52:15 - you caught a Gastly = not banned.

20:51:18 - the bot unbanned you here, you did all the rest after, so, you were unbanned :))

**Comment by Manugc1** [comment]
Im trying now, but i only catch 1 pokemon of 10. Do you know whats happening?

**Comment by Manugc1** [comment]
Thanks!
