### ISSUE TITLE
No Pokéstops

### ISSUE THREAD

**Issue by Dextiz** [Ar1i/PokemonGo-Bot#1830]
running multiple bots and none can find pokéstops. Tried new ip's and brand new accounts. Nothing works. 
![0d3031e3ad3b65edc183ca837124be07](https://cloud.githubusercontent.com/assets/20881248/17466248/b498a6d4-5d0b-11e6-8e28-af2156cc779d.png)

**Comment by eden764** [comment]
same :(

**Comment by Dextiz** [comment]
Fixed,

**Comment by MaikelxD** [comment]
servers are offline

**Comment by MaikelxD** [comment]
http://www.mmoserverstatus.com/pokemon_go
