### ISSUE TITLE
Soft ban won't go away.. any help?

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#1831]
First of all, been using bot for a few mins and still not catching any pokemon but I'm farming exp and items off pokestops.. 

Also, my item count is wrong.. [19:58:14] Items: 385/350 - I don't even have that many item, I checked on my phone. (Same location as bot)

I tried clicking on ''Force Unban'' but nothing happened..

Any idea please?

**Comment by downspath** [comment]
2 options: you have no pokeballs or you have ser pokeballs in setings to 0

**Comment by downspath** [comment]
i think 2nd one

**Comment by CowMadness** [comment]
well, I have Ultraballs a bunch, and yeah I set pokeballs to 0, should i set to something else?

**Comment by VitoDEV** [comment]
@CowMadness You can't catch pokemons without PokeBalls, set them to 50.

**Comment by CowMadness** [comment]
But I have Ultraballs?

**Comment by downspath** [comment]
0to 499 cp pokemons are ony catched with pokeballs

**Comment by CowMadness** [comment]
ahhh.. Didn't know that. Should I set 50 to greatballs too?

**Comment by downspath** [comment]
you run away from pokemon if you dont have the correct balls to catch them

**Comment by Ritzii** [comment]
Bot is preset to use certain balls depending on the CP of the Pokemon you encounter, so you need to let it hold at least 10 at all times.

**Comment by downspath** [comment]
yes

**Comment by CowMadness** [comment]
Okay, what about my items now? It says : [20:04:57] Items: 388/350
but I don't have that many.

**Comment by Ritzii** [comment]
Have you levelled up a bunch with bot since starting? You get given a lot of stuff at lower levels which can easily take you way over the cap.

**Comment by CowMadness** [comment]
Well, I have it on my phone and I play with it, during day time and bot at night. «That's why I know I don't have that mamy items. Which is weird.
