### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by Waiiim** [Ar1i/PokemonGo-Bot#1832]
I downloaded the last version but once on my computer it wants me to open it with internet explorer, who then opens and directly close at the next second, can someone tell me what to open it with ? :cake:

**Comment by downspath** [comment]
are you shure you klicked on the correct file in the folder?

**Comment by downspath** [comment]
https://github.com/Ar1i/PokemonGo-Bot/raw/master/Builds%20Only/Latest%20Build%20-%2007.08%2021.04.rar

**Comment by Waiiim** [comment]
"Latest Build - 07.08 21.04.rar"

**Comment by downspath** [comment]
you have to unpack the .rar file...
