### ISSUE TITLE
where to download new version 1.0.7.6  HELP

### ISSUE THREAD

**Issue by yourbrother010** [Ar1i/PokemonGo-Bot#1833]
is here someone how know where i can download the newest version 1.0.7.6? 
because i now have the 1.0.6.5 version

**Comment by gulss** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only

**Comment by yourbrother010** [comment]
yea and whats next whits one do i need to download (FILE?)

**Comment by yourbrother010** [comment]
and if i downloaded it in whits folder do i need to copy paste it ?
