### ISSUE TITLE
How much speed without softban

### ISSUE THREAD

**Issue by gulss** [Ar1i/PokemonGo-Bot#1835]
With how much speed can i go without getting a softban? and do i catch more pokemon based on speed?

**Comment by Dextiz** [comment]
120 should be fine :)

**Comment by Dextiz** [comment]
You get more pokéstops, which is more xp

**Comment by downspath** [comment]
less speed = more pokemons i have 16 km/h and 25-40k exp/h

**Comment by downspath** [comment]
depends on pokemon spawns and how close pokestops are
