### ISSUE TITLE
RIP Pokebot

### ISSUE THREAD

**Issue by Biscuit090** [Ar1i/PokemonGo-Bot#1836]
![pkmn2](https://cloud.githubusercontent.com/assets/20826708/17466320/1f3a5b30-5cc2-11e6-9e62-0dae2be594c9.PNG)

**Comment by Dextiz** [comment]
Servers are offline.
/close

**Comment by cicklow** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/933689/17466329/e32bd142-5ce3-11e6-9d93-afce5c64f793.jpg)

not in ARG!

**Comment by Biscuit090** [comment]
@Dextiz 
![servers](https://cloud.githubusercontent.com/assets/20826708/17466332/66c4779c-5cc2-11e6-865c-c0d6607cb99c.PNG)

**Comment by downspath** [comment]
biscuit: it depend on the country your char is

**Comment by Dextiz** [comment]
@Biscuit090 
![67e6b64987dcfcdee4968383b5431133](https://cloud.githubusercontent.com/assets/20881248/17466338/0d241110-5d0e-11e6-94dc-7e1e46583a1d.png)
