### ISSUE TITLE
[Read] Servers Offline

### ISSUE THREAD

**Issue by xcrumpy** [Ar1i/PokemonGo-Bot#1837]
Servers are offline for now. Pokestops will not be found.
![image](https://cloud.githubusercontent.com/assets/20798076/17466344/00700a28-5cdc-11e6-84a0-8a22877f0fa8.png)

**Comment by Dextiz** [comment]
Servers off, had same problems
 /close

**Comment by evrine** [comment]
Same for me guys :(

**Comment by zackbond** [comment]
Server down...

**Comment by cheese313** [comment]
me to

**Comment by downspath** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by evrine** [comment]
http://ispokemongodownornot.com/    here looks good lel

**Comment by Biscuit090** [comment]
I keep getting that same error that everyone got after the API was changed...

**Comment by gummyruler** [comment]
Figured just as much I'm surprised no one panic spam posted. The white error is still ongoing though.

**Comment by eden764** [comment]
Guys should i keep my bots ok ?
they are not doing anything at the moment but. do you think when the servers will be up again the bots will work again ?

**Comment by xcrumpy** [comment]
Yes @eden764, the bot should work once server issues are solved.

**Comment by eden764** [comment]
@xcrumpy kk thanks :D

**Comment by Biscuit090** [comment]
There are no server issues dude the servers are up and running...

**Comment by Pixie00** [comment]
#1848
