### ISSUE TITLE
Bug on my item list.

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#1838]
Bot says I have 388 items on 350..
[20:04:57] Items: 388/350
but the thing is, I checked on my phone and I don't even have close to 300 items. I'm like at 260ish.
Anything wrong with my bot or anything I forgot to manually fix?
But, I am still getting item off the Pokestops and still Recycling some items and picking new ones.

**Comment by downspath** [comment]
check your item settings in the bot

**Comment by CowMadness** [comment]
And what exactly should I check?

**Comment by arjunvegda** [comment]
@CowMadness post the screenshot of your items config

**Comment by CowMadness** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/20785729/17466387/346c96c4-5cdd-11e6-8306-0fbd10ca9634.png)

**Comment by arjunvegda** [comment]
@CowMadness Your item list is good. Maybe those are the level up awards. Not sure Wait for @Ar1i  to confirm. I have the similar problem too. But it's good right the more items we can store without extending the storage.

**Comment by akangnduz** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20890824/17470210/b84ad1a4-5d64-11e6-8542-2da29023ac3d.png)
same here
