### ISSUE TITLE
Komme nicht rein

### ISSUE THREAD

**Issue by CINEXHD** [Ar1i/PokemonGo-Bot#1842]
Komme nicht rein weiß einer was los ist

**Comment by Ahmett5** [comment]
YES BEBEK

**Comment by aquilinachu** [comment]
Sen ne diyosun lan değişik

**Comment by Safti54** [comment]
Bei mir funzt es gut mit 8 laufenden acc :)

**Comment by CINEXHD** [comment]
Geht bei mir auch wieder :)
