### ISSUE TITLE
#Ask for IV score information

### ISSUE THREAD

**Issue by puturaya** [Ar1i/PokemonGo-Bot#1843]
I find difference in IV Score information on application Pokemon Go-Bot and website pokeadvisor.com. This makes user confused where the right to information IV Score.

**Comment by xcrumpy** [comment]
Yes this is a bug #1777

**Comment by puturaya** [comment]
new bug guys?

**Comment by HuDiNi27** [comment]
From what I can gather. When it shows Best pokemon it show's the highest CP and highest IV seperately. It could be the same pokemon or 2 different pokemon.
