### ISSUE TITLE
TP to another countries

### ISSUE THREAD

**Issue by Manugc1** [Ar1i/PokemonGo-Bot#1844]
Now im in New York, how many time should i wait to "jump" to Argentina?

**Comment by Ahmett5** [comment]
2 HOURS TO 24 IT DEPENDS ON KM

**Comment by Dextiz** [comment]
To skip softban, wait as long as a planeflight would take

**Comment by xcrumpy** [comment]
Use at your own risk, its up to you.

**Comment by Baelmung** [comment]
depending on where in argentinia 10-12 hours buenos aires is 11 hours to be safe

**Comment by sealtx** [comment]
you mean in the prog?

**Comment by Hardbas** [comment]
Guys!.. Do you know a place where I can catch Magikarps?

**Comment by Manugc1** [comment]
Santa Mónica pier or Sidney

**Comment by Manugc1** [comment]
Santa Mónica pier or Sidney
