### ISSUE TITLE
error reloading pokemon list bad authentication on cmd

### ISSUE THREAD

**Issue by hazman87** [Ar1i/PokemonGo-Bot#1846]
![untitled 5](https://cloud.githubusercontent.com/assets/20870986/17466494/efa058f2-5d43-11e6-8b20-b10ce755faa3.png)
![untitled](https://cloud.githubusercontent.com/assets/20870986/17466496/efa0c2e2-5d43-11e6-8930-b2a90e3d9ef9.png)
![untitled 2](https://cloud.githubusercontent.com/assets/20870986/17466495/efa05fd2-5d43-11e6-93c3-ea027ffd39d8.png)
![untitled 3](https://cloud.githubusercontent.com/assets/20870986/17466497/efa180e2-5d43-11e6-9f2f-c7038223df79.png)
![untitled 4](https://cloud.githubusercontent.com/assets/20870986/17466498/efa248ec-5d43-11e6-855e-3c87eb91428a.png)

**Comment by hazman87** [comment]
why like this ya on cmd?

**Comment by bbaotx** [comment]
I had the same problem before, check for your password

**Comment by hazman87** [comment]
password ok already, but still same.. im using 2 different gmail of my pokemon... still same.. use different internet from wifi and cellphone hotspot too..
