### ISSUE TITLE
softbans

### ISSUE THREAD

**Issue by MaikelxD** [Ar1i/PokemonGo-Bot#1847]
everytime when the bots start working again it says im softbanned.

when its unbanned it works for 10 mins and it gets softbanned again..
any idea what causes this?

**Comment by Hardbas** [comment]
Maybe you should try with Quickspin for your Softbans

**Comment by evrine** [comment]
Now all my accounts got soft bans :o

**Comment by blablablachn** [comment]
same

**Comment by SaschaS7** [comment]
how do you unbann yourself? please help
