### ISSUE TITLE
Detection ratio: 10 / 54  Latest Build - 07.08 21.04.rar 

### ISSUE THREAD

**Issue by Pixie00** [Ar1i/PokemonGo-Bot#1848]
SHA256:	caeb17dbcae5988f9efa65b3c1a6e11f35a0b41484aacba23af964bb852eb837
File name:	Latest Build - 07.08 21.04.rar
Detection ratio:	10 / 54
Analysis date:	2016-08-08 00:40:28 UTC ( 0 minutes ago )

https://www.virustotal.com/en/file/caeb17dbcae5988f9efa65b3c1a6e11f35a0b41484aacba23af964bb852eb837/analysis/1470616828/

**Comment by xcrumpy** [comment]
False detection because its compressed

**Comment by xcrumpy** [comment]
#1738

**Comment by Pixie00** [comment]
That's a weird reason...! And it's very sensitive :)

**Comment by Pixie00** [comment]
will wait for the next update to resold that problem tho

**Comment by Ar1i** [comment]
Nothing will solve that cause of the Packer. Sorry.
