### ISSUE TITLE
[Bug] Bot Freezing

### ISSUE THREAD

**Issue by Whoopass** [Ar1i/PokemonGo-Bot#185]
I got the problem that somewhat the bot just freeze and stop doing anything. I put a screenshot below and atm its still in the same state.
![ok](https://cloud.githubusercontent.com/assets/20700835/17245705/f71b037a-5587-11e6-87a8-bc0dc6845ce5.png)

**Comment by Ar1i** [comment]
Try to restart, and open a new one if it happens again.

**Comment by Logxn** [comment]
Press enter once.

**Comment by Ar1i** [comment]
Or that, probably you marked something. Thanks @Logxn

**Comment by Whoopass** [comment]
Thanks will try it if it happens again. Happend now twice i just restarted the Bot.
Is there a way to fix this? Like in the Version before the bot could run like 24/7 without Issues.
Anyway good work tho!

**Comment by Logxn** [comment]
Mine seems to run perfectly.
You could redownload the zip and rebuild it.

I cant seem any other explanation then you accidently marking something

**Comment by Whoopass** [comment]
Will try that. Maybe it helps atleast i hope so. 
Will let you know if that happens again after i redownloaded it.

**Comment by Whoopass** [comment]
Happend again. In 2 instances of the Bot nearly at the same Time.

**Comment by Ar1i** [comment]
Go to the Window and try to press enter or space orso.

**Comment by Whoopass** [comment]
Yeah then i need to restart the bot. Found that someone got the same issue maybe i wrote it wrong. The window actually not freezing its like after that action the bot stops and is not going to do anything after that. Happens after an amount of time even if he catched a pokemon or walking to a pokestop.

**Comment by gise88** [comment]
Same here! Sometimes the bot stops after catching a pk.. Don't know why but the old version did not do that.. :sob:

**Comment by Extracritical** [comment]
Bot freezing 20-30 min. again again and again... :-1: 
Please fixed this issues. maybe 5 min. auto restart bot?

**Comment by Ar1i** [comment]
Its fixed now
