### ISSUE TITLE
can't catch pokemon but can get exp from pokestops?

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#1855]
anyone know how to fix this last time I deleted and redownloaded and it started working now it not working when I do that

**Comment by immoempe** [comment]
check that your pokeballs are not equal to 0

**Comment by OGcpalm** [comment]
it's set to 50

**Comment by evrine** [comment]
got the same problem :D farming pokestops, but every pokemon got away :o

**Comment by OGcpalm** [comment]
1 of my account is working but the other isn't and they are both in same place, Stockholm sweden

**Comment by stylized810** [comment]
I'm having a similar issue but I'm  getting the....
 We can't find any PokeStops in a range of 5000m!
 We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

**Comment by iyanricardo** [comment]
i have same issue , can not get or catch pokemon
but get xp from pokestop

**Comment by victorpiva** [comment]
Try to change ur walk speed to < 30

**Comment by OGcpalm** [comment]
nope nothing works

**Comment by OGcpalm** [comment]
anyone please help?
