### ISSUE TITLE
Says 241 pokemon but have 250?

### ISSUE THREAD

**Issue by fLxOG** [Ar1i/PokemonGo-Bot#1857]
In the bot it says i have 241 bot but when I log in to the game it shows 250? I think this is the reason for 
"Error reloading Pokemon list: Out of memory." Not sure doe.

**Comment by lailaps** [comment]
Known bug!

**Comment by Tracynew** [comment]
lol.. that's egg dude...

you have 241 pokemon with 9 egg = 250..

**Comment by fLxOG** [comment]
does that have anything to do with me getting the error "Error reloading Pokemon list: Out of memory." ?

**Comment by victorpiva** [comment]
@fLxOG , no

**Comment by fLxOG** [comment]
@victorpiva  do you know the fix it that? :c

**Comment by victorpiva** [comment]
Unfortunately not :( Victor Piva Renault GrossiEngenheiro de Telecomunicações.(85) 9 8133-3508 

    Em Domingo, 7 de Agosto de 2016 22:45, fLxOG <notifications@github.com> escreveu:
 

 @victorpiva do you know the fix it that? :c—
