### ISSUE TITLE
[Feature Request] Proxy setting or auto reconnection to bypass IP Softban

### ISSUE THREAD

**Issue by Dliang2k** [Ar1i/PokemonGo-Bot#1858]
Can you please add a proxy setting feature or auto reconnection to bypass IP Softban?
This is my test result:
4 accounts, 50km/h = IP Softban after 10 min
4 accounts 30km/h = IP Softban after 10 min
4 accounts 10km/h = IP Softban after 10 min
2 accounts 30km/h = ok, no Ban
2 accounts 50km/h = ok, no Ban
i think, we can not send to many request per IP, otherwise we will get a IP Softban

Thnkas

**Comment by OGcpalm** [comment]
is this the cause of farming pokestops but can't catch pokemon?

**Comment by Dliang2k** [comment]
This is the cause, if you can not find any pokestops. You just need to restart your router to get a new ip

**Comment by blablablachn** [comment]
3 accounts 40-50km/h ok no ban

**Comment by blablablachn** [comment]
7 accounts 40-50km/h IP soft ban after 5 min

**Comment by Dliang2k** [comment]
maybe 3-4 accounts is the maximum

**Comment by blablablachn** [comment]
@Dliang2k im not tested with 4 account but 3 account working like charm. more then 30min now

**Comment by dragonuts330** [comment]
I use 5 and have ban problem constant now, force unban no success. can log in manually on ios and unban by spinning or via nox. but the program will not unban itself. I cannot even use a single account without it being soft ban flag.

**Comment by blablablachn** [comment]
@dragonuts330 wait like 10min for unban and try with max 3 account when workin

**Comment by elenex23** [comment]
the 3 account is working well for me over 10 mins now.

**Comment by downspath** [comment]
running only 1 acc works perfectly

**Comment by CreativiTimothy** [comment]
Yeah, it seems like Niantic is cracking down on multiple accounts. I can only get 2 accounts working for 30 minutes. 3 accounts works for the first 10 minutes, but then it starts getting soft-banned. I really would like a proxy feature!
