### ISSUE TITLE
Egg Hatching No info

### ISSUE THREAD

**Issue by 666triv** [Ar1i/PokemonGo-Bot#1861]
When ticking the option to use the incubator, the regular stats update does not show current egg info i.e. Incubator 1 3.89km to go? Is this possible! BTW this is my favourite bot been using since day 1

**Comment by beasttry** [comment]
great idea!

**Comment by gummyruler** [comment]
I think we don't need more display on the bot though. I personally want them to make the bot cleaner. Like only show what you caught and what ran away that's just about all I care about.
