### ISSUE TITLE
Dratini spawn spots

### ISSUE THREAD

**Issue by Austin333** [Ar1i/PokemonGo-Bot#1863]
Please help me I can't find dratini anywhere. Only pokemon I need right now. Anyone have luck with finding them? Please share location

**Comment by peoplearmy** [comment]
This is not an issue with the bot please keep requests specific to not issues.

**Comment by CliveCockster** [comment]
#1748

**Comment by Austin333** [comment]
Sorry for posting a non related issue. Plus i Can't find any info on that link.

**Comment by Austin333** [comment]
Is there any way to ask all users here to see if someone actually has a good location that works right now?

**Comment by elenex23** [comment]
no. use reddit or google for this please. pokesnipers.com may help

**Comment by oXNARXo** [comment]
you can find it here:
http://lmgtfy.com/?q=pokemon+go+Dratini+nest
