### ISSUE TITLE
Instant Softban

### ISSUE THREAD

**Issue by haxpure** [Ar1i/PokemonGo-Bot#1867]
After starting the bot it only takes a few second's to get banned. 
I don't know why but it's pretty annoying...

**Comment by elenex23** [comment]
Instantly softban is a little strange. Try renewing your ip and dont run more then 3 bots at a time. Double check all your settings including location.

**Comment by haxpure** [comment]
Thanks for the answer, i tried to restart my router & only used 1 acc with Force Unban and it's working.. strange.
