### ISSUE TITLE
Bot not working again?

### ISSUE THREAD

**Issue by WhoBotWhoBad** [Ar1i/PokemonGo-Bot#1868]
I got this in all of my running bot

http://i.imgur.com/il5cn7a.jpg

Is bot not working again?

**Comment by stylized810** [comment]
Im getting the same thing . i reset my computer and it worked but then went back to the issue

**Comment by WhoBotWhoBad** [comment]
Hmmm... It seems Niantec is detecting same IP? I have 9 bot running in same IP and it generate that kind of error. Now I open my VPN and everything working back again.
