### ISSUE TITLE
still cannot find pokestop

### ISSUE THREAD

**Issue by artasakha** [Ar1i/PokemonGo-Bot#1869]
![image](https://cloud.githubusercontent.com/assets/20830371/17467534/6403e420-5d49-11e6-817f-8070a1df8f76.png)

**Comment by haxpure** [comment]
How many account's do you have running? Try to start max 3 Account's at the time and restart your router before.. worked for me

**Comment by artasakha** [comment]
just 1 account running. ill restart my router and try

**Comment by artasakha** [comment]
it works, thanks man.

now i have another issue, my acc got baned too fast and the unbanned method didnt work
