### ISSUE TITLE
Warning.

### ISSUE THREAD

**Issue by FlyHaxHD** [Ar1i/PokemonGo-Bot#1872]
Warning to people running the bot with more than 2 accounts. You will get banned. I just banned all 3 accounts at the same time for the second time, But when I only run 2 or one it goes forever no problem.

**Comment by oXNARXo** [comment]
i'm running 4 accounts and there is no problem yet

**Comment by adman9031** [comment]
i think i have to agree with this, has been happening to me now i think its ip related wondering if there will eventually be a work around

**Comment by centoxe** [comment]
how do you even run multiple? do you duplicate the bot folder?

**Comment by WhoBotWhoBad** [comment]
I have 9 bot running. All experience same errors and yes I experience soft ban too. But all working fine again when I open my VPN

**Comment by haxpure** [comment]
I got banned while running 4 account's. After a router restart it worked fine.

**Comment by DHBios** [comment]
I think the problems it with managing your locationn or your speed or other things, not because you run 2 / 3 / 4 accounts at the same time

**Comment by adman9031** [comment]
my speed is only 59

**Comment by ONOBARY** [comment]
![desert](https://cloud.githubusercontent.com/assets/20884771/17467612/49ca13a8-5d4a-11e6-8791-c322255da3e1.jpg)

**Comment by WhoBotWhoBad** [comment]
Maybe we should change our speed to 5?

**Comment by haxpure** [comment]
My bot's are running with 70 so...

**Comment by centoxe** [comment]
How do you run multiple bots?

**Comment by haxpure** [comment]
Just copy the folder :+1:

**Comment by adman9031** [comment]
@centoxe you dont even have to do that just click on the .exe again

**Comment by centoxe** [comment]
thanks :D

**Comment by haxpure** [comment]
I have different settings for the bots

**Comment by centoxe** [comment]
Can anyone send me their config that you think can be the "fastest xp config"?

**Comment by downspath** [comment]
https://www.twitch.tv/appleandcakes he runns 5 at the same time? no softbans for him?

**Comment by CliveCockster** [comment]
@downspath this is not the Ar1i Bot ^^ but Ar1i is better then the other bot ^^

**Comment by gummyruler** [comment]
Bot speed at 400 here I don't get softban.

**Comment by justchil** [comment]
It looks like you are correct.  I have been testing for a few hours.

Using my home pc and a vps in a dc.

5,4,3 accounts each = soft bans.

I'm trying two now.  I only have 10 accounts... so it looks like a schedule to run them 2x at a time for so many hours and rotate out... or virtual machines using VPN's.
