### ISSUE TITLE
Auto Eggs Hatching is not working

### ISSUE THREAD

**Issue by oXNARXo** [Ar1i/PokemonGo-Bot#1873]
the new future ,Auto Eggs Hatching is not working

**Comment by DHBios** [comment]
Really,.? I think the auto incubator feature is working fine, but there isn't any information being provided into your console yet.. just wait for arli to fix it :)

Anw, reallyy appreciate arli for the good works!
Going to donate sooner or later haha

**Comment by Ted0504** [comment]
it is not working

**Comment by oXNARXo** [comment]
when i enter the game with my phone i don't see any egg that has the "Hatching thing them"
so i guess yea it's not working
