### ISSUE TITLE
Pokemon Go Softban 

### ISSUE THREAD

**Issue by SaschaS7** [Ar1i/PokemonGo-Bot#1874]
The bot told me I got softbanned and should try the unbann 1337... what does that mean and how can I unbann myself? please help asap

**Comment by JeCelle** [comment]
Click the "Force unban" button in the GUI.

**Comment by SaschaS7** [comment]
wow Im so dumb I legit cant find it could you explain where its found? thanks

**Comment by SaschaS7** [comment]
ah got it still thanks

**Comment by OhhPian** [comment]
force unban not working

**Comment by menaze818** [comment]
@SaschaS7 Where did you find force unban ? i can't find it

**Comment by suabahasa** [comment]
@menaze818 you can see it on Pokemon list GUI

**Comment by menaze818** [comment]
@suabahasa Literally don't see it

**Comment by suabahasa** [comment]
1. you must enable the pokemon list gui http://puu.sh/qtyCr.png
2. the "force unban" button it top of "transfer" button http://puu.sh/qtyEb.png

**Comment by menaze818** [comment]
@suabahasa oh nvm i see it i was using different version thank you !

**Comment by menaze818** [comment]
@suabahasa asppreciate the help, have a good day
