### ISSUE TITLE
SOFTBANS EVERYWHERE

### ISSUE THREAD

**Issue by Biscuit090** [Ar1i/PokemonGo-Bot#1875]
Changing your IP is the only way to rid of softbans now or you can use a VPN. No clue if I have to reset my router every time I start the bother or if the 3 account limit per IP is true but I will post back with results in a bit...

**Comment by oXNARXo** [comment]
i have 4 accounts with same ip,, kinda ur problem

**Comment by ONOBARY** [comment]
![desert](https://cloud.githubusercontent.com/assets/20884771/17467695/43c19d7c-5d4b-11e6-903c-7bb81259bfdb.jpg) 44 minute no issue

**Comment by DHBios** [comment]
Changing the IP (Restarting the Connection or Restarting the router) still didn't works for me.

**Comment by NagaCS** [comment]
Seems like Niantic is doing it by being able to see how many request the same IP had, one bot is no issue at least not yet

**Comment by chenbobowu** [comment]
I am now running 2 Google accounts and 3 PTC accounts. It works fine at the moment. 

When I tried to open the fourth PTC accounts, all my account got softban.

So, I guess they limit 3 Google accounts and 3 PTC accounts in one IP or something?

**Comment by DHBios** [comment]
So the problem solving to solve this problem is providing an IP Changer app for every console running? (If it's possible)

**Comment by downspath** [comment]
@nagaCS this sounds realistic

**Comment by NagaCS** [comment]
It could also be Bot sided, this is the only bot i use for Pokemon go, but from what I've seen people aren't having issues yet with others.

**Comment by MarTiniiii** [comment]
No Softban here

**Comment by DHBios** [comment]
How many console that you run currently MarTini..?

**Comment by MarTiniiii** [comment]
@DHBios 1

**Comment by NagaCS** [comment]
I'm running 2 on the same IP and havent experienced an issue

**Comment by Sw3rv3** [comment]
running both necro and this one once I hit three it softbans all three accts.  The new way it softbans you can't fix with pokespin because it makes it where nothing spawns.
