### ISSUE TITLE
not able to catch pokemon after reloading bot

### ISSUE THREAD

**Issue by davegoskate** [Ar1i/PokemonGo-Bot#1877]
I downloaded the new update ran it fine for a couple hours ran out of room for pokemon since transfer is also broken i logged on m phone but accidentally opened it while my gps spoofer app was off so it soft banned me for 10 mins ran the bot again and it collects items from poke stops but every pokemon it encounters it runs away.
![capture](https://cloud.githubusercontent.com/assets/20896118/17467947/1bbdbdb0-5cf1-11e6-8534-1f5085f1c02f.PNG)

**Comment by peptidoglikan** [comment]
+1

**Comment by Animehq** [comment]
+1

**Comment by alexhart123** [comment]
you running multiple bots?

**Comment by Animehq** [comment]
nop simple

**Comment by DHBios** [comment]
obviously because of the sudden jump you got softbanned

**Comment by davegoskate** [comment]
*update* figured out it was just the settings as my pokeballs were set to 0 and it was working fine with 2 bots i had running and i always made sure to spawn back in the same location but that was the problem for me.

**Comment by DHBios** [comment]
Good for you :)

**Comment by Animehq** [comment]
no softban DHBios

**Comment by peptidoglikan** [comment]
i think being added a button to pokelist for unbanning softban would be great. we can manually remove softban.

**Comment by Animehq** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/15330553/17468182/83998f0c-5d25-11e6-9d5a-46cb33044db2.png)

**Comment by peptidoglikan** [comment]
Animehq +1

**Comment by Animehq** [comment]
ok just Fix if other Outputs errors.rar don't work , but Latest Build - 07.08 21.04.rar work fine

**Comment by Juniels** [comment]
some problem with me to.. try to use latest buld dan fix other output. and it same happen

**Comment by Luuqi** [comment]
Guess it is caused by that you have no normal pokeballs and bot tries to use them and fail to catch pokemon, at least it worked for me. Make some room for normal pokeballs in your items and you should be fine.
