### ISSUE TITLE
Transferring not working right.

### ISSUE THREAD

**Issue by Nomad52** [Ar1i/PokemonGo-Bot#1879]
The pokemon go bot gets the pokemon inventory get full for some reason, even though It's supposed to be transferring all the duplicates.

**Comment by peptidoglikan** [comment]
+1 yes i was gonna write about this issue :)

**Comment by davegoskate** [comment]
bug ar1i is in process of fixing

**Comment by CreativiTimothy** [comment]
Works for me fine. It just sometimes transfers my 96IV Squirtle, so that's the bug. Make sure duplicate pokemon is set at 1 or something and set MAX CP to like 5000 and IV 90 or 95%

**Comment by davegoskate** [comment]
i rather wait than lose my best iv pokemon..

**Comment by Nomad52** [comment]
@CreativiTimothy 
Guess what

It was set at 1.
