### ISSUE TITLE
Error reloading pokemon list: Out of memory

### ISSUE THREAD

**Issue by tweetthehens** [Ar1i/PokemonGo-Bot#1880]
is it my computer issue? did i miss any files?

**Comment by davegoskate** [comment]
its a bug ar1i is fixing it soon meantime you have to do it manually

**Comment by CurlzM8** [comment]
How do you do it manually

**Comment by davegoskate** [comment]
when it opens the Pokemon list right click the Pokemon with the lowest iv and transfer.

**Comment by CurlzM8** [comment]
Ok I'll try now thanks

**Comment by CurlzM8** [comment]
I can't scroll down
