### ISSUE TITLE
How i can use Greatball?

### ISSUE THREAD

**Issue by Maxpowder** [Ar1i/PokemonGo-Bot#1881]
Hey how i can use Greatball or greater?

A lot of pokemons flee, i can use only normal pokeball why?

**Comment by downspath** [comment]
it uses it automatic, it depends on cp 0 to 499 cp is regular pokebal

**Comment by Maxpowder** [comment]
how can I set the?

**Comment by ankhmok** [comment]
also want o know, pokemon alway got away for some reason(not soft ban)
