### ISSUE TITLE
Auto Incubator - fix

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#1884]
I think that auto incubator doesnt work.

Each of eggs i must manual activate and add to incubator.

**Comment by Minzaa** [comment]
yes i think Ar1i has mentioned before the incubator function is not actually working yet

**Comment by CreativiTimothy** [comment]
Yeah, it doesn't incubate anything.

**Comment by hades19850** [comment]
how can config auto tranfer by cp ?
