### ISSUE TITLE
Build #07.08 21.04 Transfer error (selecting pokemon to transfer)

### ISSUE THREAD

**Issue by pangestucn** [Ar1i/PokemonGo-Bot#1886]
![transferring error](https://cloud.githubusercontent.com/assets/20897033/17469088/7b168b88-5d60-11e6-902a-dc5b8c67249c.jpg)

Lets say when I have 18 CP magikarp with 80% IV and then the bot captured a magikarp with better IV. The bot transfers the magikarp with better IV instead the other one. It seems that the bot confused the CP and the IV when transferring.

When I had 6 voltrobs, the bot kept transferring my voltrob one by one because it confused the IV till 0 voltrob left. Even though I have already set my minimum pokemon copy to 1.

I wish I screencaptured it so I can post it here.

Sorry for my bad english. 

EDIT: I already attach it. As we can see, the bot confuse my 64% IV eevee to 69% so it transferred the recently caught eevee with the better IV instead. It only happened when the bot manage to catch a pokemon with better IV, if it catch pokemon with lesser IV, the bot can read the IV of the pre-owned pokemon correctly.

**Comment by davegoskate** [comment]
try and get a screen cap of it and post

**Comment by pangestucn** [comment]
I already got the screencap and edit my first post

**Comment by immoempe** [comment]
I don't know, but maybe is comparing both eevees and taking the best of both (CP of one and IV of the other) and showing it as the best option to keep (sounds like a problem in the code)

**Comment by pangestucn** [comment]
I dont think so.

Since in the module it stated that the pre-owned eevee IV is 69% (matching the newly caught IV), but in reality the pre-owned eevee IV is 64%
