### ISSUE TITLE
Can't find pokestops. 

### ISSUE THREAD

**Issue by ineedtostudy** [Ar1i/PokemonGo-Bot#1887]
![capture](https://cloud.githubusercontent.com/assets/20897325/17469138/b747803c-5ceb-11e6-972b-3e4bb8628c06.PNG)

**Comment by MaikelxD** [comment]
servers probably unstable again : http://www.mmoserverstatus.com/pokemon_go

**Comment by dzocrusher05** [comment]
ur IP got banned , just change the ip and then its okay

**Comment by MaikelxD** [comment]
@dzocrusher05 no he is not, the UK & USA servers were unstable.

should work again.

**Comment by ineedtostudy** [comment]
yeah works. thanks!

**Comment by CreativiTimothy** [comment]
Soft-banned IP

**Comment by CuteKittyyy** [comment]
how many bots can we place per ip address?
