### ISSUE TITLE
cant find any pokestops in a range of 5000

### ISSUE THREAD

**Issue by i-am-nobody-1** [Ar1i/PokemonGo-Bot#1888]
Hi, i am using latest update for today and it was working fine until few minutes back. I keep getting this error. I don't know why. I let it open so that it will unban if it is softbanned. But, no matter how many hours, i keep getting same error. Can someone please help me regarding this. 

Thanks for your help 
![1](https://cloud.githubusercontent.com/assets/20818032/17469182/e027d91c-5cf4-11e6-8012-c568acf096ae.png)

**Comment by MaikelxD** [comment]
Pokemon GO Servers are unstable, try to relaunch the bot.
worked for me.

**Comment by i-am-nobody-1** [comment]
Thanks mate!!

**Comment by i-am-nobody-1** [comment]
how do i close this issue?

**Comment by i-am-nobody-1** [comment]
never mind found it, thanks for help
