### ISSUE TITLE
i found best way to fix softban / no pokestop 

### ISSUE THREAD

**Issue by dzocrusher05** [Ar1i/PokemonGo-Bot#1890]
i got the prob like softban / no pokestop just change u IP , u can use VPN like HSS(hotspot shield)
its work 100% on me 

i hope ar1i read this issue and include IP changer to the BOT , cuz this is the best way to fix this issue

**Comment by dzocrusher05** [comment]
sry for my bad english

**Comment by MaikelxD** [comment]
Just don't run more than 3 bots and you will be fine.. lol

**Comment by dzocrusher05** [comment]
wew ill try that
