### ISSUE TITLE
 fix for broken pokemon transfer bug

### ISSUE THREAD

**Issue by davegoskate** [Ar1i/PokemonGo-Bot#1892]
i set my max transfer to 999 and the max iv to 75% with only 2 duplicates to catch for each pokemon try it out and let me know if it fixes the issue

**Comment by NagaCS** [comment]
I have yet to see a single transferring issue and my max transfer is 2400 and the IV max is set to 95% with only 2 duplicates, BUT. If the duplicates have an IV of over 95% it auto keeps them

**Comment by davegoskate** [comment]
the only problem was is if you set it lower than 999 max transfer and 50% iv or lower it breaks the transfer and it doesn't work

**Comment by NagaCS** [comment]
@davegoskate ahhh, okay.

**Comment by mariobros33** [comment]
So what the perfect setup to auto-transfer.

**Comment by davegoskate** [comment]
im still about level 22 so i left it at  999 max transfer and 75% iv with only 2 doubles each and its working again flawlessly @mariobros33

**Comment by AiVo7z** [comment]
I have to admit it works for me, but only for a couple hours, then the bot starts to leave more and more pokemons in my inventory. I can't send 'em back manuelly either. If I restart the bot it works - but not always. Im using "simplegui bot" for that now. The bot doesn't work right now for botting, but works well for sending back Pokémons. 
But even with this error, the bot's great ar1i did a great Job to fix that bot fast.
