### ISSUE TITLE
Niantic sends WARNING E-MAILS before banning accounts?

### ISSUE THREAD

**Issue by Biscuit090** [Ar1i/PokemonGo-Bot#1894]
https://www.reddit.com/r/Ingress/comments/23y48m/bans_bans_bans/

For those of you concerned about being PERMA-BANNED in the future...:

"These bans are coming through in waves, with an automated warning email to begin with, and then a permanent ban if you persist in using the illegitimate client beyond the initial warning.

Originally they would do one or two banwaves a week but they are now doing three or four and it's killing the bots faster than they can be of any real use."

**Comment by Biscuit090** [comment]
So apparently if you stop using the bot after a warning email is sent, you can still have your account? At least, this was the case for Niantic's last game "Ingress".

**Comment by CreativiTimothy** [comment]
Thank you for the announcement! I haven't gotten any emails yet thank god

**Comment by justchil** [comment]
submitted 2 years ago....

**Comment by Biscuit090** [comment]
@CreativiTimothy I don't think they'll be sending any emails out just yet, not until trading is implemented.

**Comment by Biscuit090** [comment]
While Ingress is an old game now, I think they're going to keep their style of banning people quite similar. Don't expect a permanent ban without a warning notice.
