### ISSUE TITLE
Suggestion: Add option to select which unevolved Pokemon to keep

### ISSUE THREAD

**Issue by CreativiTimothy** [Ar1i/PokemonGo-Bot#1895]
The option "Keep pokemon which can be evolved" keeps every single Pokemon that can evolve. I would like an option to select which exact Pokemon to keep, instead of all of them. For example, I want to select Pidgey, Weedle, Caterpie, and Rattata, while transferring the rest according to what I set in duplicates. Otherwise, my Pokemon storage gets filled up really quickly. If you don't understand my suggestion, feel free to ask for clarificaiton. Thank you again for you hard work!!

**Comment by justchil** [comment]
I posted on the thread after mentioning something similar.

Min IV to evolve option -- This keeps me from having low IV pokemon evolved. Would help so much.  Posting in the thread I was told to just gets buried with german posts so...

**Comment by tryndamerewu** [comment]
i really like this options  right now i select not to cath rata pidey weedle caterpie  to save some space but lose some exp
