### ISSUE TITLE
Error reloading Pokemon list: out of memory

### ISSUE THREAD

**Issue by CurlzM8** [Ar1i/PokemonGo-Bot#1896]
How can you fix this?
I can't interact with the list at all and everything just runs away

**Comment by davegoskate** [comment]
make sure your pokeballs arent set to 0 or any other item at least put 1 for items you cant get yet and dont set your max transfer lower than 999 and 75% iv everything should work again after that.

**Comment by CurlzM8** [comment]
Still isn't working :/

**Comment by CurlzM8** [comment]
I'll redown load hopefully it fixes something

**Comment by coolbuddy26** [comment]
yeah just keep some pokeballs if 0 u cant catch any Pokemons!.
Ty for the help :+1:

**Comment by CurlzM8** [comment]
Reinstalled it its working now thanks guys

**Comment by davegoskate** [comment]
@CurlzM8 no problem :P

**Comment by akangnduz** [comment]
if this issue happen again...try delete sprites folder then start again
