### ISSUE TITLE
Help-me 

### ISSUE THREAD

**Issue by questioner01** [Ar1i/PokemonGo-Bot#1897]
what is this error?
![capturar](https://cloud.githubusercontent.com/assets/20895864/17469825/577c4bac-5d0d-11e6-97c4-019ba6c37877.PNG)

**Comment by CurlzM8** [comment]
Wrong password maybe ?

**Comment by CurlzM8** [comment]
I think I got a similar error when I did wrong pw

**Comment by tryndamerewu** [comment]
wrong pasword

**Comment by questioner01** [comment]
tks guys
