### ISSUE TITLE
[Request] Bot über telegram aktivieren und deaktivieren

### ISSUE THREAD

**Issue by magiccube007** [Ar1i/PokemonGo-Bot#19]
Angenommen man hat den bot am laufen während man unterwegs ist mit Freunden die sehen auf ihrem Radar ein seltenes Pokemon und man will dieses fangen, geht des ja zur Zeit nicht da man den bot aus der Entfernung ja nicht stoppen kann. Jetzt wäre ein Befehl über Telegram ganz praktisch z.B. /pause um den Bot kurz zu pausieren so, dass man sich in den eigenen Account schnell einloggen kann das Pokemon fangen und den bot durch z.B. /start wieder starten kann.

**Comment by Ar1i** [comment]
Wird nicht gehen, da es Softbans gibt.
