### ISSUE TITLE
How to download [Im dumb] 

### ISSUE THREAD

**Issue by 1337Panther** [Ar1i/PokemonGo-Bot#1900]
I got the bot like 12 days, deleted it and now im to dumb to download it.
Please help me. :/

**Comment by AiVo7z** [comment]
Download, unzip, start the .exe and that's it?

**Comment by 1337Panther** [comment]
I cant find any .exe file

**Comment by PokemonGoer** [comment]
1) https://github.com/Ar1i
2) PokemonGo-Bot
3) Builds Only
4)Latest Build.rar file
5)click download

**Comment by Zykhatslover** [comment]
https://github.com/Ar1i/PokemonGo-Bot

On the upper right corner there is a "clone or download" button.  Just hit the "download" button, unzip the latestbuild.rar, then find the "PokemonGo.RocketAPI.Console" file in it and run it :-)
