### ISSUE TITLE
always get softban

### ISSUE THREAD

**Issue by cheecko** [Ar1i/PokemonGo-Bot#1901]
how fast i need to move? i use 50 km/h distance 500, but every 1 minute i get softban. sorry fot bad English

**Comment by ankhmok** [comment]
did u get any EXP from pokeshops?

**Comment by cheecko** [comment]
i get it, but i need 20-30 second to unbanned and 30 doing it properly and then i get soft banned again.

**Comment by justchil** [comment]
How many bots are your running?

**Comment by cheecko** [comment]
5 bot, 1 google and 3 ptc

**Comment by KoiPanda** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1907

Dont run more than 2 bots...
