### ISSUE TITLE
Problem finding pokestops

### ISSUE THREAD

**Issue by Buddhasama** [Ar1i/PokemonGo-Bot#1902]
Ever since last night I keep having this issue, the bot works for a bit then on all accounts I start getting that . I am not sure if there is a problem with the servers or the bot .

![capture](https://cloud.githubusercontent.com/assets/20898364/17470184/ff919d12-5d42-11e6-95d7-27b5506ce57f.PNG)

**Comment by akangnduz** [comment]
yeah sometime me too...but try to change location it will fix

**Comment by Ar1i** [comment]
Change location, servers are down there probably
