### ISSUE TITLE
Alle Pokemons weg?

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#1903]
Ich hatte grad meinen Acoount, den ich wirklich fast selber im Urlaub bis 26 hoch gebracht habe im Bot und habe nur 1 Pokemon gelöscht. Auf einmal ist nur noch 1 Pokemon da? Kriegt man die wieder?? Oh man das ist so ärgerlich da ich die wirklich alle gefangen habe mit hin und her laufen und allem :-((((

**Comment by Provokan** [comment]
Nein, weil du übernimmst die Haftung selber für die Einstellungen deines Bots.

**Comment by Ar1i** [comment]
Dann sind deine Settings falsch

**Comment by NidiKea** [comment]
Er hat sie ja alle gelöscht als ich selber 1 gelöscht habe bei dem Fenster
wo sie stehen.  Habe einen Zubat gelöscht und dann stand da auch er hat 1
Pokemok erfolgreich gelöscht . 2 Minuten später stand da 150 von 150
gelöscht und alle weg

Am 08.08.2016 08:17 schrieb "Ar1i" <notifications@github.com>:

**Comment by NidiKea** [comment]
Aber ich werde es überleben aber ärgert einen schon sehr.  Naja danke aber
für die schnellen Antworten immer

Am 08.08.2016 08:35 schrieb "Nadine Nimizz" <nidimausi@gmail.com>:
