### ISSUE TITLE
Eier und Rauch in die Item Liste aufnehmen

### ISSUE THREAD

**Issue by Provokan** [Ar1i/PokemonGo-Bot#1905]
Hallo Ari,

ist es möglich den Rauch sowie dirgendwie Glückseier in die Item LISTE mit aufzunehmen, nach jedem Level update, schmeißt er diese ungewollt weg, was leider sehr schade ist.

**Comment by Ar1i** [comment]
Er schmeißt die nicht weg, er benutzt die wenn du die Optionen aktiviert hast

**Comment by Provokan** [comment]
Kann man alle Glückseier auf einmal verwenden? Hatte durch das erreichen von Level 30, drei glükseier und 3 Rauchwolken, ich denke er kann immer nur 1 Pro Item benutzen, und die anderen hat er nach der Konsole weggeschmissen
