### ISSUE TITLE
[NOTICE]  Limit running to 2 bots/accounts per IP or Soft Ban / No pokestops. [NOTICE] 

### ISSUE THREAD

**Issue by justchil** [Ar1i/PokemonGo-Bot#1907]
If you run more than TWO bots on the same IP you're going to get SOFT BANNED.

I have tested this along with other folks.  If you need to run more you may want to look into other solutions such as VM + VPN (per 2 accounts).  If you have a better method please feel free to share.

Thank you.

**Comment by ineedtostudy** [comment]
Really? I'm running 3 bots and it's working fine. 1 google, 2 PTC

**Comment by JeCelle** [comment]
I also run 3 bots at the same time. They're all google accounts. I tried adding another one, but I got a softban so I figured that the limit must be 3 per IP.

**Comment by CuteKittyyy** [comment]
im getting soft banned off 2 accs. i can only use one only. :(

**Comment by elenex23** [comment]
I run 1 Google and 2 ptc well

**Comment by Tracynew** [comment]
i run 8 bot..

with normal walking 30kmh and in my region still fine.. i think you set your speed and your location..

**Comment by anjarokz** [comment]
1 IP for 2 Account google only and infinity Ptc. I just try and try and now know that
