### ISSUE TITLE
Google 2-Factor Authenticator causes trouble with my android device

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#1908]
Hi, 
i'm using Pokemon with my Google Account. During the bot is running on different places all over the world, i got a problem with my authenication of my android device. So i have to relogin with my google account on my mobile device, because of a "account change".

For the bot i use a "single password".

Do you have the same problem or is this a bug/problem?

**Comment by Ar1i** [comment]
Thats normal and is not an issue, its cause of google
