### ISSUE TITLE
SoftBanning and PokeStop

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#1909]
Currently, It shows the PokeStops but it doesn't hit them, it just says coming up on one, then goes to the next and nothing is collected. Also, it is no longer catching pokemon, and it keeps trying to undo softbans on all accounts even though it hasn't jumped location.

**Comment by JeCelle** [comment]
That happened to me earlier when I tried running 4 bots at the same time. I got IP softbanned, so I had to release/renew to get a new IP. Have you been running more than 3 bots at a time?
