### ISSUE TITLE
[Request] My Ideas

### ISSUE THREAD

**Issue by TheSmartly** [Ar1i/PokemonGo-Bot#191]
These are my ideas that may improve the bot. I will edit this if I find sth. that could be cool.

## **Pokemon Bot Client:**
   ·Manual incense and luck egg use (via command.     or GUI)
   ·Auto-Hatcher(Puts egg in incubator)
   ·Walk to Location (Auto walks to a Location)

## **Telegram Bot:**
   ·Restart the Bot
   ·Sell all doubles (My bot often forgets to do this)
   ·Manual incense lucky egg use
   · /top_iv xx shows the top pokemon by sorted by iv
   ·Modify speed and radius of the bot
   ·Include/Exclude Pokemon from catching and evolving
   ·All stats in Telegram (number of pokemon, items etc.)

--EDIT--
## **Pokemon Bot Client:**
  ·Walk custom routes (maybe via gpx tracks or patrol points the user can set)
  ·Mute specific outputs (To keep the console clean, the oppertunity to mute for exampe the "We are within 35 meters of the target. Speeding down to ~10 km/h to not pass the target." and all that stuff)

--EDIT2--
## **Pokemon Bot Client (Pokemon List)**
   ·Lock Pokemon (Lock a Pokemon. The bot will not perform any actions on this Pokemon. Via a Button at this Rightclick menue)
   

I know some of these are doubles, but I wanted my list to be complete.

@Ar1i  I really like your bot, it is working very well. Thanks for the great work. I hope you will keep developing it.

**Comment by cinek19** [comment]
Great ideas!

**Comment by 666triv** [comment]
+1

**Comment by plowzey** [comment]
+1
