### ISSUE TITLE
Artemis Trojanisches Pferd

### ISSUE THREAD

**Issue by barashnukor** [Ar1i/PokemonGo-Bot#1912]
Hallo, 

mein Mcafee schlägt dauernd mit der Meldung an, dass Artemis Trojanisches Pferd in dem Download Paket drinnen wäre, und löscht mir alles.

Schon bekannt?
Mfg
Stefan

**Comment by Ar1i** [comment]
Lad dir gleich die neuste Version, ist ein false positive.
