### ISSUE TITLE
10Zubat, 8 Beetle, 12 pidgey, Program don't transfer these pokemon.

### ISSUE THREAD

**Issue by sirface92** [Ar1i/PokemonGo-Bot#1913]
these 3 kinds of pokemons are problem. Program don't transfer these pokemons.

**Comment by Ar1i** [comment]
Your settings are wrong.

**Comment by hades19850** [comment]
how can setting, can you show image config

**Comment by PippoAe** [comment]
You probably ticked the option "don't transfer evolveable pokemons".

**Comment by sirface92** [comment]
Sorry my bad, l saw other option new. Thanks for everything

8 Ağu 2016 09:48 tarihinde "PippoAe" <notifications@github.com> yazdı:
