### ISSUE TITLE
Read.

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#1916]
We cant handle all that issues, where like 80% is bullshit. So deleted all of them.

If your posting a issue, make sure its an issue AND NOT A SUGGESTION. Make sure that no one already posted that issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by sargathus** [comment]
u are awesome dude!

**Comment by ranggirahman** [comment]
thanks i love your work buddy :+1:

**Comment by PippoAe** [comment]
Awesome work Ar1i, grosses Dankeschön!
Can you make this post sticky?

**Comment by Hahahaha0** [comment]
Thank you ar1i! love you...

**Comment by MuRainbow** [comment]
The bot always say The Pokemon got away while using itempokeball?

**Comment by DubbinDanny** [comment]
Hi sir, awesome work, have you got a link to the new download? thanks dude

**Comment by dragonuts330** [comment]
Bot is soft banned after 10m of operation regardless of how many clients I'm attempting to use. Has been that way since 8/7 7:15pm EST.

**Comment by DubbinDanny** [comment]
does the new bot not evolve pokemon? as my pokedex is just getting fuller

**Comment by DubbinDanny** [comment]
How do you get the new bot to evolve and trasfer pokemon? I'm just getting stacks and stacks of the same pokemon?

**Comment by PokeShopOrg** [comment]
always getting issue with finding pokestop in area i am, nomather what location i give in always this problem, and i know for sure it are good locations can this be fixed?

and why can we only run 3 instances? i want to run more and not getting softbanned 

pls let me know

**Comment by eLDeMe** [comment]
@SkyWalkerMc  +1

**Comment by pumpersi** [comment]
why  the bot still using the  normal pokeballs and all  pokemon escape :-( ?? i set it up in items options  keep 0 item pokebal keep 0 great ball and keep only 150  ultraball and  still  cant catch the pokemons why some one help me pls

**Comment by Mixone-FinallyHere** [comment]
it is a softban probably or your level is high (catch becomes harder) also you might have set a low catch probability giving various fails and leading to the pokemon fleeing

**Comment by eLDeMe** [comment]
@pumpersi bot uses greatball when poke is over 500cp, you should have always normal pokeballs it's a bug and they are working on it.

@Mixone-FinallyHere No softban, he just need normal pokeballs

**Comment by Mixone-FinallyHere** [comment]
@Ar1i maybe disconnect issues and open a channel on the slack or dosbiscus (the chat thingy I always forget the name) and if the issue is really an issue then a "issue moderator" can make an issue in the repo (so rather than eliminating issues altogether set up a write acces to them maybe? )

**Comment by Mixone-FinallyHere** [comment]
@eLDeMe oh right I forgot about that, I changed the bit of code on my fork last night cos I only had greatballs and ultraballs so that it would use any ball except for masterball

**Comment by pumpersi** [comment]
@eLDeMe thank you very much its was true what did you said :-) u was good  guys to :-)

**Comment by PokeShopOrg** [comment]
@ar1i why can we only run 3 instances?
