### ISSUE TITLE
POkemon catching bug

### ISSUE THREAD

**Issue by kazekiki** [Ar1i/PokemonGo-Bot#1918]
![pokemon](https://cloud.githubusercontent.com/assets/20899253/17471335/a056a010-5d6d-11e6-8746-2b180371e615.jpg)
I run 2 bot (1 PTC + 1 GG) , the PTC account catching is normal but GG is not, it still can get XP from pokemonstop

**Comment by Ar1i** [comment]
Its catching normal too? Some pokemons go away thats normal

**Comment by ozdenor** [comment]
this was answered yesterday. you have to have all type of pokeball. Do not set zero none of them.
