### ISSUE TITLE
*issue* error reloading pokemon list: out of memory for the past 30mins now

### ISSUE THREAD

**Issue by wrobe06117** [Ar1i/PokemonGo-Bot#1920]
![untitled](https://cloud.githubusercontent.com/assets/20858496/17471345/0d16588c-5d76-11e6-8db0-52bb72920c23.png)

**Comment by wrobe06117** [comment]
wanted to use the full power up from the gui but well this error

**Comment by akangnduz** [comment]
delete sprites folder

**Comment by wrobe06117** [comment]
@akangnduz  lemme try tnx

**Comment by wrobe06117** [comment]
@akangnduz  the error in the logs disapear after deleting the sprites folder but the gui is still unclickable so i restart the bot but the error came back in the logs

**Comment by wrobe06117** [comment]
@akangnduz nvm its ok now what i did is delete the items inside the folder then click the unban in the GUI now its working so im closing this
