### ISSUE TITLE
POkemon catching bug

### ISSUE THREAD

**Issue by kazekiki** [Ar1i/PokemonGo-Bot#1922]
I ran 2 bot and got catching pokemon bug with 1 account!

![pokemon](https://cloud.githubusercontent.com/assets/20899253/17471374/e209a03e-5d6d-11e6-824e-a32a75614da8.jpg)

**Comment by Ar1i** [comment]
there is no bug.

**Comment by iDemoxios** [comment]
Don't write 0 in simple pokéball ! /!\
