### ISSUE TITLE
every single pokemon gets away 

### ISSUE THREAD

**Issue by Kranios** [Ar1i/PokemonGo-Bot#1923]
So i keep encountering pokemons but every single one gets away. I gets xp from pokestops so its not a soft ban.

**Comment by kazekiki** [comment]
same issue

**Comment by iDemoxios** [comment]
Don't make 0 in simple pokeball !!

**Comment by Kranios** [comment]
i will try that thanks for the help

**Comment by Kranios** [comment]
it is working thanks for the help
