### ISSUE TITLE
Autoincubation not workig

### ISSUE THREAD

**Issue by PippoAe** [Ar1i/PokemonGo-Bot#1924]
The autoincubation feature is not working,.

**Comment by Lentsha** [comment]
Yes Ar1i has said that incubation is not activated in the bot, in a previous posted issue. You should wait until the option is working fine and is released

**Comment by b3shoy** [comment]
Yes, because it's not working right now.
Please close this issue until further notice.

**Comment by Logxn** [comment]
We are working on it :)

**Comment by xJustx** [comment]
#346
