### ISSUE TITLE
We can't find any PokeStops in a range

### ISSUE THREAD

**Issue by crack00r** [Ar1i/PokemonGo-Bot#1926]
Latest Build - 08.08 08.14

```
[08:45:40] Walking back to default location.
[08:45:40] Distance to target location: 0,04 meters. Will take 0 seconds!
[08:45:41] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[08:45:42] Starting again in 10 seconds...
[08:45:53] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[08:45:55] -----------------------[PLAYER STATS UPDATE]-----------------------
[08:45:55] Level/EXP: 29 305.225/350.000 (87,21%) EXP to Level up: 44775
[08:45:55] PokeStops visited: 6891 KM Walked: 89,7533
[08:45:55] Pokemon: 97 + 9 Eggs /250 (0 Evolvable)
[08:45:56] Items: 318/350 Stardust: 203.230
[08:45:58] We can't find any PokeStops in a range of 20000m!
[08:45:58] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..
[08:45:59] Walking back to default location.
[08:45:59] Distance to target location: 18,16 meters. Will take 0,87 seconds!
[08:45:59] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[08:46:01] Starting again in 10 seconds...
```

**Comment by Ar1i** [comment]
change location

**Comment by 1337Panther** [comment]
Same error :/

**Comment by lelele666** [comment]
thx but i tried that a couple of times, atm trying central park but no succes
![image](https://cloud.githubusercontent.com/assets/20819250/17471615/e2975582-5d45-11e6-8507-0cadee71627a.png)

**Comment by Hahahaha0** [comment]
it work for me, i change my location to -37.7651298, 145.3509665

**Comment by lelele666** [comment]
i will try that location

**Comment by Lentsha** [comment]
I can confirm that, having tried different locations within Paris where the pokestops should be en masse!

**Comment by Scantraxzu** [comment]
Currently I think you can't multibot.

I tried using 2 Ar1i bots at the same time and after a while both got soft banned. I rebooted my internet router and tried to use 1 Ar1i bot and another bot from the internet and its still working

**Comment by 1337Panther** [comment]
Im multiboting too :D but i cant reset internet, :( what should I do

**Comment by lelele666** [comment]
i tried hahahaha0 location and no succes, i know i am getting soft banned for hopping around the world.
i geuss soft bans changed? cause prev it would still find all the pokestops and force to unban me.

and i only use 1 account, never worked for me after you guys cracked the code

**Comment by 1337Panther** [comment]
Yeah one of my Accounts got unbanned, i guess they have 15-30 minute softbanns now

**Comment by Hahahaha0** [comment]
uhmm... maybe there is problem with your connection @lelele666

**Comment by crack00r** [comment]
So, what is it now, multibot ban, ore just connection problems, ore maybe bad location?

**Comment by Hahahaha0** [comment]
haven't tried to multibot, lemme try now

**Comment by Scantraxzu** [comment]
If you have a way to change your IP (router reboot), wait a couple minutes and then yry to run ONLY 1 bot at a time and see if it still cause you any trouble.

**Comment by crack00r** [comment]
i cant, i´m at cable, allways same ip

**Comment by milanstiano** [comment]
Try to change position nearly, if you in position lat and long blablabla try to change the last number

**Comment by crack00r** [comment]
i see now on other but, 
you have to reset ip, and start bots with 1 min between.. else you got ip ban

**Comment by Scantraxzu** [comment]
I changed my ip once and still got softbanned after a couple minutes. I did it again but this time with only 1 Ar1i bot and another bot and until now (4/5hours) they are still working without any softban or errors.

**Comment by Hahahaha0** [comment]
2 bots still working normally

**Comment by lelele666** [comment]
no matter what location i try i get this
![image](https://cloud.githubusercontent.com/assets/20819250/17472072/eb7f99cc-5d48-11e6-853e-448bad428c1d.png)
tried resetting router, used 6 diff locations i know off are good and have plenty pokestops.
any suggestions?

**Comment by Hahahaha0** [comment]
i got that issue when i have low internet connection, i don't know if that will apply to you...

**Comment by Scantraxzu** [comment]
@lelele666 are u running multiple bots?

**Comment by lelele666** [comment]
no i only run 1 bot

**Comment by hades2795** [comment]
Anyone can give me latest file?

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.

**Comment by hades2795** [comment]
I have still problem #1966
