### ISSUE TITLE
Item number is wrong.

### ISSUE THREAD

**Issue by ozdenor** [Ar1i/PokemonGo-Bot#1928]
Firstly, Thanks for this great job Ar1i. Really appreciated.

I do not know it is a bug or not. When I check the item number from the app, it is 350/350 (full). As you can see in the bot screen it is 460/350, 459/350.

![capture](https://cloud.githubusercontent.com/assets/20899336/17471497/618f6b3e-5d4d-11e6-95f5-2a644e4e0c95.PNG)

If this can be fixed, I will be very glad. Thanks again for your all effort.

Sorry for my bad English.

Have a great day.

**Comment by HeIIoWorld** [comment]
If you level up you recieve Items that ignore the maximum of the inventory so you can have more than the max. amount of items

**Comment by MatkeMatke** [comment]
same issue here, sorta, it's 515/800 for me, while i have over 700 items in my inventory, it does not update when it loots or recycles either, just stays at 515/800.

**Comment by ranggirahman** [comment]
same here, and my razberry counter error too

**Comment by Souadka** [comment]
same here mate , it showing 380/350 but in game only 137/350

**Comment by testo4life** [comment]
any update on this ? i cant get any berrys because of that !

**Comment by ozdenor** [comment]
I have re-arrange the total count of items. Sum of them is 350 so that I have approximately same amount of items in my inventory.

Potion: 0
Super Potion: 0
Hyper Potion: 35
Max Potion: 65
Revive: 25
Max Revive: 25
Lucky Egg: 6
Incense: 7
Pokeball: 15
Great Pokeball: 25
Ultra Pokeball: 100
Lure: 9
Razz Berry: 38

**Comment by testo4life** [comment]
i just loged in got in total 200 Items but bot is showing 431/350 if thats not a bug i dont know :D

**Comment by ozdenor** [comment]
Yeap, it is really strange.

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.

**Comment by ozdenor** [comment]
thank you  so much
