### ISSUE TITLE
What is Max IV to transfer?

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#1929]
Can some one tell me What is Max IV to transfer? and I want  to set Auto transfer but i dont want to transfer 500+ CP pokemon . Can some one send me there settings ?

**Comment by JeCelle** [comment]
#1916

**Comment by Lentsha** [comment]
IV mean Individual Value and like the name says, is individual to each pokemon. It's the IV that explains why to Magicarps may have different CP and HP. IVs are from 0% to 100%, the higher IV, the better. 

Max IV to tranfer is there to prevent the bot from tranfering high IV pokemons. 85%-90% seems to be a good value, it will keep the top stats pokemons.
