### ISSUE TITLE
[Request] Show the Radius on the map and PokeVision

### ISSUE THREAD

**Issue by TMaddox** [Ar1i/PokemonGo-Bot#193]
Hey i think it would be pretty cool if you would add:
- Set the Radius on the Map (i know a few spots on the map where good pokemons spawn f.e. Snorlax and Electrocute) and i want to make sure they are in the radius (now i do this with google maps, but takes time)
- Add a tab in the Pokemon live GUI with pokevision to figure out good spawnspots (and if you are very cool, let the bot figure it out, like statistically)

I pretty like the Ideas from #191 

Thank for this work
I really like your bot, you´re awesome :+1:

**Comment by justchil** [comment]
This would be very useful and thanks too for your work!
