### ISSUE TITLE
Start Location

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#1931]
The bot always starts in new york.

the older one dosnt. it starts where it was clossed, or walked to the new set place.

**Comment by pokerave** [comment]
update the bot, you can also change the default location in the config folder, config.txt

**Comment by Tr1n0va** [comment]
i dit, but nothing works.... its always starts in new york... no matter what i do....

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.
