### ISSUE TITLE
Detected softban many times

### ISSUE THREAD

**Issue by Gin520** [Ar1i/PokemonGo-Bot#1933]
I didn't suddenly popup at a far location, only chosen a location within the same city and set to to 80km walk within 3000m radius. 

It detected softban after walking for some hours in the morning, it auto tried to unban for me, didn't work. So I tried the new feature force unban, it worked. 
I set back to the same area again, it walks around for me just fine and caught pokemon, but after a while, it started detecting softban again, and the force unban doesn't seem to work.

And if I let the program continue running, it will then start to show messages like "We can't find any pokestops in a range of 2000m!"

**Comment by Xcutioner** [comment]
It an error wich came with the latest update. Its going to be fixed.

**Comment by Ar1i** [comment]
how many bots do you run?

**Comment by rainkeel** [comment]
no run bots 3+ client

**Comment by theazncross** [comment]
Ar1i there's peoples saying that they run over 30 accounts without ban how true is that? because I'm running 4 and I get soft ban

**Comment by rainkeel** [comment]
arli build Proxy in you bot pls

**Comment by Ar1i** [comment]
idk personally i am only botting 1, and @rainkeel probably later

**Comment by theazncross** [comment]
btw where is the force unban thing? xD

**Comment by Ar1i** [comment]
its not working with an ip ban probably

**Comment by Yummster** [comment]
maybe try dialling your speed down to 50 km/h, I use that with three bots and don't ever get soft bans

**Comment by rainkeel** [comment]
change vpn for unbanned IP ban

**Comment by theazncross** [comment]
I have no idea about that "force unban" feature lol; So dumb here.

**Comment by Gin520** [comment]
@Ar1i I'm using 1 bot only 
first softban happened when I was at home. (i closed the bot before I go to office)
2nd softban and the ones after are when I'm at office.

**Comment by 1337Panther** [comment]
New Softban [IP] type, you now get Ip bans for 15-30 minutes.

**Comment by theazncross** [comment]
btw if i get the "no pokestop in a range of 500m" mean that I am ip banned for half an hour right?

**Comment by untesty** [comment]
Why can't we run more than 3 bots at the same time? Did niantic change something?

**Comment by rainkeel** [comment]
@theazncross  you ip banned, no run 3 bots ++

**Comment by sargathus** [comment]
mine works okay. i dont get any soft ban

**Comment by pokerave** [comment]
I run 4 bots.. its ok. different folder, different account, im working in saudi arabia so my IP should be ban but its not.

**Comment by Yummster** [comment]
@untesty more than likely Niantic trying to stop the people mass producing accounts to sell and reduce server load

**Comment by rainkeel** [comment]
Seagame use bot for sell account LOL

**Comment by gummyruler** [comment]
OK I found a semi solution to the problem. Those who run bots cannot run 2+ bots at the same time. And you cannot put the same bots at the same locale (E.G 2 bots at Grand central ). Also separate your folders when you run your bots. Ideally 1 account should have a folder of its own.

**Comment by Gin520** [comment]
thanks for the replies, it's unbanned now, so i guess it needed 15-30 minutes for unbanning.
I going to set it back to 50km, and hopefully it won't ban me again.

**Comment by TrainerNr1** [comment]
IP ban is bullshit!!!

My smartphone with "legal" account is in same router like my PC with bots. On smartphone everything works fine, but bots get banned.

GERMAN:
So ein Blödsinn mit dem IP Ban. Mein Handy mit "legalem" Account ist im gleichen Router (gleiche IP) angemeldet wie mein PC mit den Bots. Dann müsste ja auch der Account auf dem Smartphone geblockt sein, ist er aber nicht!

**Comment by pokerave** [comment]
@TrainerNr1 IP is different WITH EACH DEVICE ( your phone have diff IP even if its connected to same router) but if you run multiple bots (SAME PC - SAME IP) but yeah IP ban sounds like bull

**Comment by TrainerNr1** [comment]
@pokerave lol??? If my PC and my mobile are logged into the same router, both have same IP! Sure!!!

**Comment by Yummster** [comment]
devices have different internal ip addresses on the router but the same ip gateway address that the router uses to connect to the Niantic servers.

**Comment by AiVo7z** [comment]
I always run 3 bots same time. default config of botspeed etc. and ive never gotten a softban not then or now (means neither old nor new api). So saying more than 2 bots result in softban is wrong. I dont jump location and iam at a crowded popular place.

**Comment by AiVo7z** [comment]
And sure. Diffrent devices have different ip adresses IN YOUR -LOCAL - NETWORK but ofc all the same external ip. Except you paid for having more than one (Companies etc).

**Comment by mastercoyin** [comment]
Hai i wanna help but i cant speak english too much

Just open firtst bot and give break until 5 minutes then open the second bot

**Comment by jembatanpatah** [comment]
I bot 6 run ++. Working good. My english is bat. But i want to share . im change my ip at japan because i bot there. I’m using hotspot shield pro for change ip country. Semoga bermanfaat :D

**Comment by Ar1i** [comment]
Just make a little delay if you open more then 1 bot between opening.
