### ISSUE TITLE
error- "reloading pokemon list: out of memory"

### ISSUE THREAD

**Issue by jtchase** [Ar1i/PokemonGo-Bot#1934]
edit: ontop of the heading (just an inconvenient error). I'm only getting 2,200 xp/h and 5 pokemon/h.. i believe the unban method is failing as all encountered pokemon are getting away. I may be IP banned or something

**Comment by pokerave** [comment]
are you running multiple bots with same account? or opening account in different apps?

**Comment by pokerave** [comment]
check you pokeball setting, do not set pokeball to 0.

**Comment by jtchase** [comment]
i set pokeball to 0 and great/ultra up.. oops might be it

**Comment by gummyruler** [comment]
Just close the GUI if keeps doing it.

**Comment by akangnduz** [comment]
i always delete my sprites folder if this issue comes

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.
