### ISSUE TITLE
Bot unable to catch Pokemon with GreatBall or UltraBall

### ISSUE THREAD

**Issue by Lentsha** [Ar1i/PokemonGo-Bot#1935]
I have set my settings to only keep Pokeballs and RazzBerrys. When catching Pokemons with Pokeballs, the bot works fine.

But somehow, the bot tries to use GreatBalls to catch stronger Pokemons (with the Max. GreatBalls set to 0!) and GreatBalls thrown fail to catch Pokemon 100%.

Same issue with UltraBalls.

**Comment by Ar1i** [comment]
just dont set it to 0, idk why its bad when the bot autochoose the pokeballs

**Comment by Lentsha** [comment]
ok, I tried your advice, and it worked just fine! Thanks a lot!

**Comment by gummyruler** [comment]
I think it's a genius idea to make sure you use pokeball with higher capture rate. Just leave it at that. Pokemon CP600 above are uncatchable by normal pokeballs.
