### ISSUE TITLE
READ!! BEFORE COMPLAIN ABOUT THE ISSUE NO POKESTOPS IN RANGE

### ISSUE THREAD

**Issue by 1337Panther** [Ar1i/PokemonGo-Bot#1936]
Hello everyone, Niantic got a new way to softban your Accounts if you are Multiboting to fast.

The new type of softban is an Ip ban for time (15-30 minutes) 

Tip for multiboting: Always open 1 bot in 3 minutes. ;) Good Luck and thanks to Ar1i for fixing everyting

**Comment by pokerave** [comment]
im running 4 bots since last night its ok. im working in saudi arabia(not release POGO)

**Comment by 1337Panther** [comment]
@pokerave Yeah i updated my comment, if you are not opening the bots to fast ( 2 bots in 3 minutes ) it should work fine

**Comment by Biscuit090** [comment]
Yeah, the maximum allowed number of bots right now is 3 (at least for me). I received an IP ban on my main account and it lasted over 6 hours+ so I don't think these bans are going to be as short any more.

**Comment by jmpb032** [comment]
i create 3 different folders for 3 accounts. will i get ip banned for that

**Comment by b3shoy** [comment]
@jmpb032 you will probably will, if you don't obey the rules of human-like botting. :hand:

**Comment by 1337Panther** [comment]
Multiboting for 3 Accounts works fine i think its the max per ip

**Comment by milanstiano** [comment]
@1337Panther it's really work bro? So, if i only one bot, can i softban ip?

**Comment by milanstiano** [comment]
I used multibot with my friend on one line networking. So, if i botting, and then my friend can open the bot after 3 minutes?

**Comment by milanstiano** [comment]
still working? @1337Panther @pokerave

**Comment by downspath** [comment]
i am using 2 bots and wayted 5 men beteen starting running since 3 hours without a problem
