### ISSUE TITLE
Transfer Bug and Pokestop Bug

### ISSUE THREAD

**Issue by HansKrywaa** [Ar1i/PokemonGo-Bot#1937]
Morgen Ar1i,

ich schreib einfach auf Deutsch, ist ja einfacher :D 
Also ich bin auf Version 1.0.7.7, wenn ich den Bot starte, habe ich am Anfang den Transfer Bug, wie bei Version 1.0.7.0. Dannach kommt der "Pokestop not found" Error.

Ich hoffe das hilft dir irgendwie weiter :D

**Comment by pokerave** [comment]
update to latest version

**Comment by HansKrywaa** [comment]
1.0.7.7 is latest Version i think

**Comment by Ar1i** [comment]
switch location #1902
