### ISSUE TITLE
Bot stops after X amount of time

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#194]
Hi there.

It's the second time today that the bot stops after he caught a pokemon.
After that, no errors nor updates. Coulnd't find any problem.
Do you know how to fix this issue?

Thanks for making such great bot though!

**Comment by Ar1i** [comment]
You marked something orso? Cause your the only one where it happens

**Comment by faiver** [comment]
the same happens to me. :(

**Comment by Ar1i** [comment]
try to edit the HttpClientExtensions.cs replace:
`while (response.Payload.Count == 0) // WE WANT A FUCKING ANWSER POKEMON
            {
                await RandomHelper.RandomDelay(150, 300);
                response = await PostProto<TRequest>(client, url, request);
            }`
with:
`      if (response.Payload.Count == 0) // WE WANT A FUCKING ANWSER POKEMON
            {
                throw new InvalidResponseException;
            }`
Tell me if it fixes, it should probably output a Exception then.

**Comment by midoom** [comment]
[13:44:43] Exception: System.ArgumentOutOfRangeException: La valeur doit être -1 (ce qui signifie un délai infini), 0 ou un entier positif.
Nom du paramètre : millisecondsDelay
   à System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay)
   à PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Navigation.cs:ligne 97
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__14.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 268
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__9.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 136
[13:44:43] Starting again.. But waiting 10 Seconds..

**Comment by MarvinSCR** [comment]
try to edit the HttpClientExtensions.cs replace:
while (response.Payload.Count == 0) // WE WANT A FUCKING ANWSER POKEMON { await RandomHelper.RandomDelay(150, 300); response = await PostProto<TRequest>(client, url, request); }
with:
if (response.Payload.Count == 0) // WE WANT A FUCKING ANWSER POKEMON { throw new InvalidResponseException; }
Tell me if it fixes, it should probably output a Exception then.

**Comment by Logxn** [comment]
@midoom 
Redownload the newest version.
Its fixed now

**Comment by Ar1i** [comment]
Its fixed now
