### ISSUE TITLE
transfering problems 

### ISSUE THREAD

**Issue by sargathus** [Ar1i/PokemonGo-Bot#1940]
i was not going to open this topic but i think i have to say that.

bot works great thanks for good work but bot don't transfer most of the pokemons i disabled that keep pokemon which can evolve but its still not transfering and my pokemon invertory gettin full in like 30 minutes. 

pls fix that.

 max cp is 550
max %75
still not trasnfering under 550cp im keep doing it manually

**Comment by pokerave** [comment]
uncheck "keep pokemons which can be evolve"

**Comment by sargathus** [comment]
@pokerave its disabled already.its not check.its uncheck? did u really read what i wrote?

**Comment by alebotvvs** [comment]
i'm having this problm too! the bot only transfer pokemons at the start,... how i should set my configurations @Ar1i

**Comment by PokePro21** [comment]
same problem with me also its not tansferring later @Ar1i @Logxn

**Comment by PokePro21** [comment]
it transfer some pokemons but very rarely not all which we are selected after catching them later @Ar1i @Logxn

**Comment by sargathus** [comment]
this is only problem right now other than that works perferct

**Comment by milanstiano** [comment]
indeed..

**Comment by xRealMaks** [comment]
Can you give an update? Is this still a bug in the newest version?
