### ISSUE TITLE
lastcoords.txt missing / not generated

### ISSUE THREAD

**Issue by zorndyke** [Ar1i/PokemonGo-Bot#1941]
Last version before api fix, the bot generate lastcoords.txt in configs folder, in order app closed or restarted we just continue from last coordinate. The walking behavior look natural, because we're not jumping after 2km away from starting position.
but the new bot always restarting from determined location in config.txt causing jumping from few km in a second and resulting softbanned.

**Comment by pokerave** [comment]
in config folder, config.txt

**Comment by Ar1i** [comment]
adding that later again
