### ISSUE TITLE
GUI ERROR patch: 08.08 08.14

### ISSUE THREAD

**Issue by gummyruler** [Ar1i/PokemonGo-Bot#1942]
![oh yis](https://cloud.githubusercontent.com/assets/20757587/17472440/215b3f60-5d08-11e6-9951-ad1f25a1e39f.png)

**Comment by Yummster** [comment]
I wouldn't advertise your username on the pic

**Comment by gummyruler** [comment]
thanks bud

**Comment by pokerave** [comment]
delete sprite folder

**Comment by Ar1i** [comment]
http://i.ar1i.xyz/e3igzM6D.rar  download this rar, and put the folder sprites in your main directory of the bot

**Comment by gummyruler** [comment]
Done it's working well now thanks.

**Comment by b3shoy** [comment]
@gummyruler then close the issue :smile:

**Comment by gummyruler** [comment]
how?
