### ISSUE TITLE
Idea of new features

### ISSUE THREAD

**Issue by arond1** [Ar1i/PokemonGo-Bot#1947]
First thank you for your amazing work second I want to teel you some idea about new features :+
1) a button on the GUI to use a lucky egg.
2) make your GUI standalone because it's usefull to manage our pokemons
3) Add a table with one line by item and give the possibility to us to delete it
4) Finally and very important make the recycling of item after every pokestop because in high level a lot of pokemon got away because bot try to use simple pokeball ;-(

P¨S : Sorry if I make some mistake i'm french if you need help to translate I can help you.

**Comment by gummyruler** [comment]
Issues only friend.

**Comment by b3shoy** [comment]
#1916

**Comment by b3shoy** [comment]
Please close, this is for issues only man!

**Comment by arond1** [comment]
Ok sorry new on github
