### ISSUE TITLE
Account retrying

### ISSUE THREAD

**Issue by harryjsc97** [Ar1i/PokemonGo-Bot#1948]
I am using the correct credentials and have wiated 15 minutes. I can log in using the app.

please help

**Comment by HBraga** [comment]
same here... any thoughts ?

**Comment by HBraga** [comment]
ok just understood... tranfer the current files to the old pokemon go extraction and it works...
jus replace those two folders with these ones..

**Comment by harryjsc97** [comment]
Sorry, i dont quite understand

**Comment by harryjsc97** [comment]
have tried this and still does not work

**Comment by harryjsc97** [comment]
@pokerave how did u fix

**Comment by lucas2107** [comment]
Hi, if you don't have the lastest version update. And check your firewall.

**Comment by harryjsc97** [comment]
firewall was the issue. thank you

**Comment by xJustx** [comment]
^
