### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by DeeDeePac187** [Ar1i/PokemonGo-Bot#1949]
Hello,

I've a problem with **System.InvalidOperationException** .

After this, the bot restart the connexion.

Thanks for your future response

<div class="container">

> [09:51:15] Exception: System.InvalidOperationException: La séquence ne contient aucun élément correspondant.
>    à System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
>    à PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 60
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    à PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 180
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    à PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 362
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    à PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 129
`

**Comment by VitoDEV** [comment]
Essaye de supprimer le bot, puis le réinstaller, et essaye un nouvel emplacement par défaut.
Try to delete the bot, and reinstall it, and try to change your defaut location.

**Comment by DeeDeePac187** [comment]
Ok thx I try it. thx for translete

**Comment by Ar1i** [comment]
fixed in newest version
