### ISSUE TITLE
Problem with pokeball

### ISSUE THREAD

**Issue by arond1** [Ar1i/PokemonGo-Bot#1951]
Bot is suppose to delete pokeball but i don"t do it see : 
![capture](https://cloud.githubusercontent.com/assets/20900500/17473475/f5d049aa-5d50-11e6-85a0-1092d1547626.PNG)
I have this configuration : 
![capture2](https://cloud.githubusercontent.com/assets/20900500/17473503/14d3d254-5d51-11e6-813c-85c894414545.PNG)

**Comment by zzzz9999** [comment]
What is wrong? 
I see 1 pokeball recycled

**Comment by arond1** [comment]
Yes and see the next line i try to catch pokemon with pokeball

**Comment by arond1** [comment]
jsute after the deleting

**Comment by zzzz9999** [comment]
Ok I see. 
Probably a bug. 
Let's wait to other explanation, or confirmation that is a bug.

**Comment by ozdenor** [comment]
[#1930](https://github.com/Ar1i/PokemonGo-Bot/issues/1930)

**Comment by zzzz9999** [comment]
Quote :
Okay. So I need to have atleast one normal pokeball for it to caugh. This fixed the problem with me. Simply have some normal balls in your inventory.

**Comment by zzzz9999** [comment]
Then close issue please

**Comment by Kranios** [comment]
don't set pokeballs 0

**Comment by arond1** [comment]
ok thanks i close
