### ISSUE TITLE
Different IV numbers

### ISSUE THREAD

**Issue by vasyarun** [Ar1i/PokemonGo-Bot#1953]
Hello,

did you change the formula of IV calculation in the last version?

For some of my pokemons the IVs got significantly decreased for some increased. Are these numbers correct?

**Comment by HBraga** [comment]
Ar1i it would be nice it there was an option to catch pokemon only iff above XX% in IV..
so who ever wants to just catch high iv pokemon does so...

**Comment by arjunvegda** [comment]
I already created issue yesterday about this and I am on latest version but still the same thing..

![image](https://cloud.githubusercontent.com/assets/14841132/17478856/9f9274c8-5d3c-11e6-9e05-b7e61dc2f679.png)

**Comment by gitovahere** [comment]
@HBraga you could filter for mainly just IV when you put the CP very high (I put 9999 for CP). In that way when CP is out of reach it will assess the IV, where I keep 90% or more. If you keep 2 pokemon at all time w/ transferring the lower, it will keep 2 pokemon of any IV until it catching 90% or more than it will get rid of the lowest IV and so on. 

I had to downgrade to the previous version of bot as I found the latest didn't do the job even when it caught higher IV.
