### ISSUE TITLE
Ar1i Da verkauft einer Deinen Bot bei Ebay!

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#1954]
@Ar1i 

http://www.ebay.de/itm/FIX-UPDATE-FIX-SELTENE-POKEMONS-FANGEN-Automatisch-pokemon-go-BESTER-BOT-/201640620621?hash=item2ef2b7b24d:g:0xsAAOSw-itXp3Z9

2 hat er schon verkauft!

---------------

Lieferumfang:
Sobald das Geld bei mir eingegangen ist bekommt ihr ein Link vom Programm vom Entwickler und eine detaillierte Anleitung zur Installation und Bedienung per Mail von mir.
Dann nur noch einloggen und ihr könnt mit dem leveln beginnen!
Ihr braucht ein Windows Rechner um das Programm zu starten.

Besonderheit:
Bei diesem Programm könnt ihr sogar den Ort angeben, wo es für euch Pokemon fangen soll.

Die Koordinaten für den Central Park in New York (höchste Pokemondichte weltweit) lege ich kostenlos dazu!

Man brauch ein PC (Windows) um die Software zu nutzen.

---------------

Die Koordinaten legt er noch bei, was für ein Idiot!

**Comment by TrainerNr1** [comment]
Ihm scheint sein ebay-Account nicht wirklich wichtig zu sein.

**Comment by lailaps** [comment]
Schon very dreist!

**Comment by AmaliaWinter** [comment]
Verklag ihn ;) Urheberrechtsverletzung :P

**Comment by PoDaMo** [comment]
Naja er verkauft ja nicht direkt den Bot sondern wie er in der Beschreibung beschrieben hat zahlt man für die Zeit die er investiert hat um den Bot zu finden. 

Trozdem dreist es für den preis anzubieten

**Comment by acelya** [comment]
Einen kostenlosen bot für geld weiterzuverkaufen... hmm ich würde mir das nicht gefallen lassen :P

**Comment by AmaliaWinter** [comment]
Die Zeit die ihr gebraucht hat den Bot zu finden? Guter Witz. Ich hab einmal gegooglet.

**Comment by RavenZero** [comment]
Wie er sich mit "
Ihr bietet hier auf meine Recherche, eine Anleitung und ein Link wo ihr das Programm laden könnt, welches für euch automatisch levelt und Pokemon fängt."
rausreden will...
traurig

**Comment by PoDaMo** [comment]
Ihr bietet hier auf meine Recherche, eine Anleitung und ein Link wo ihr das Programm laden könnt, welches für euch automatisch levelt und Pokemon fängt.

Steht doch da! Wer lesen kann....

Ist trozdem frech und der entwickler sollte sich mal bei ihm melden

**Comment by BrutalBirdie** [comment]
http://puu.sh/qtLPT/831685a821.png 10/10 rekt

**Comment by AmaliaWinter** [comment]
War halt so ein typisches Mindcraft/CS Kiddie das dachte es kann andere Leute mit nicht eigener Arbeit leicht das Geld aus der Tasche ziehen dachte mir schon das er bei dem Copyright Hinweis einknickt.

**Comment by AmaliaWinter** [comment]
Der nächste Lappen....
http://www.ebay.de/itm/FIX-Update-Seltene-Pokemon-Fangen-Automatisch-50k-Exp-Stunde/222212472513?_trksid=p2047675.c100011.m1850&_trkparms=aid%3D222007%26algo%3DSIC.MBE%26ao%3D1%26asc%3D35393%26meid%3Def4d8b5dbc0e45f5970dcf5f5bd24272%26pid%3D100011%26rk%3D2%26rkt%3D10%26sd%3D201640620621

**Comment by AmaliaWinter** [comment]
R.I.P


"Dieses Angebot wurde vom Verkäufer beendet, da es einen Fehler enthielt.
Details zu  FIX Update - Seltene Pokémon Fangen Automatisch 50k Exp /Stunde Originalangebot aufrufen
FIX-Update-Seltene-Pokemon-Fangen-Automatisch-50k-Exp-Stunde
Item Ended
Artikelzustand:
Neu
Beendet:
08. Aug. 2016 12:00:55 MESZ
Preis:
EUR 15,99
Versand:
Kostenlose Abholung
Artikelstandort:
Berlin, Deutschland
Verkäufer:
gigoloimkimono (1 )
| Andere Artikel des Verkäufers"

**Comment by AmaliaWinter** [comment]
Bedenkt man den Standort bei beiden verkäufen fällt einem auf das beide aus Berlin sind... der Kerl der vorhin meinte er nimmt ihn wohl besser raus hat einfach auf nem neuen Account die Anzeige nochmal erstellt.... Ich meine wie dämlich kann man denn bitte sein...

**Comment by lailaps** [comment]
@AmaliaWinter

Haha, ja...
War fast identischer Wortlaut.

**Comment by Ar1i** [comment]
shit happens, hoffentlich zeigen ihn die käufer dafür an
