### ISSUE TITLE
How can I edit "Player Stats Update"?

### ISSUE THREAD

**Issue by proyugi** [Ar1i/PokemonGo-Bot#1955]
The information about Player Stats Update is very quickly. 

How can i make it slow down to reduce the time for catching pokemon?

**Comment by BrutalBirdie** [comment]
Start GUI Bottom Left Live-Stats Delay 5000.

**Comment by proyugi** [comment]
i see, thank you BrutaBirdie.

May i ask what is the maximum Live-Stats Delay i can write?

**Comment by proyugi** [comment]
I change 5000 to 50000. But it seems nothing happened.

**Comment by proyugi** [comment]
#1916

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
