### ISSUE TITLE
Pokemon List: Sort by Number

### ISSUE THREAD

**Issue by Montrazul** [Ar1i/PokemonGo-Bot#1956]
I would love to have an option to sort the Pokemon List by number. 
You support many sorts: Name, CP, IV, LVL, etc. but when i want to 
decide which pokemon to power up or to envolve i would prefer
sort by number so that i can see immediately which pokemons 
i already have evolved and how strong they are.

**Comment by elffish** [comment]
I am about to make a same post and I saw yours. :) 
Sorting by pokedex number is extremely helpful for evolving.

**Comment by JeCelle** [comment]
#1916

**Comment by Lentsha** [comment]
This is not the right place for your question. If you can read, this page is for Issues. You should only post subjects concerning bugs or the bot not working well.

**Comment by Montrazul** [comment]
The bot is not working well because it has no sort by number option ;)

**Comment by JeCelle** [comment]
What kind of logic is that? The bot is not working well? seriously? You said so yourself "I would love to have an OPTION to sort the Pokemon List by number. " sheesh

**Comment by Montrazul** [comment]
Calm your titties young girl lol

**Comment by b3shoy** [comment]
Close this issue.

**Comment by Montrazul** [comment]
I will never ever do that!!!!!!
