### ISSUE TITLE
Bot cant catch pokemons

### ISSUE THREAD

**Issue by bozkurt123** [Ar1i/PokemonGo-Bot#1957]
![adsiz](https://cloud.githubusercontent.com/assets/20901472/17474190/6c5285be-5d5d-11e6-8ca1-818ce29f5cc0.png)
Bot cant catch pokemons since now i opened it 5 hours ago, it works perfectly untill now. can u tell me what did i do wrong. 
Thanx for the bot. Its Great ...

# **SOLVED : DONT Set the NORMAL POKEBALL to 0**

**Comment by supermario007** [comment]
Probably soft banned. Hit the button Force Unban.

**Comment by Jlozde** [comment]
I have exact same problem with latest build.

**Comment by Montrazul** [comment]
Yes. It is a softban. Hit the force unban button!

**Comment by madeinyashiro** [comment]
Dont' set default pokeballs to 0

**Comment by bozkurt123** [comment]
i dont collect normal pokeball
is it that
i tried unban its not a problem

**Comment by bozkurt123** [comment]
im collecting mega ball and highers

**Comment by akangnduz** [comment]
thats why you cant catch any pokemon...set pokeball >20 dont 0

**Comment by bozkurt123** [comment]
okay ill try

**Comment by Jlozde** [comment]
Yeap. that solved my problem. now it is running.

**Comment by bozkurt123** [comment]
me 2, thanks for the quick help ... im grateful
Çok Teşekkürler...

**Comment by Kidnub** [comment]
my acocunt is softbanned or  idont know cause balls i have XD i even dont get items from the pokeshops so i  think it is softbanned or banned ...

**Comment by bozkurt123** [comment]
might be your inventory full ?

**Comment by b3shoy** [comment]
close this issue please.
