### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HaydarOzturk** [Ar1i/PokemonGo-Bot#1958]
Can you add a new feature as calculation button for all the process the bot have? I would try to explain with an example that what we want :)

We want to be able to see how much hour this program worked,
We want to see how much exp is earned in this progress,
We want to see how many pokemon it catched at this progress,

thanks for everything you big man!

**Comment by JeCelle** [comment]
#1916

**Comment by Montrazul** [comment]
JeCelle's job is to read every request and to post "#1916" under each post. He gets one whole bowl of rice each day for his awesome work.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
