### ISSUE TITLE
[Bug] Pidgey evolve failed

### ISSUE THREAD

**Issue by CruSherFL** [Ar1i/PokemonGo-Bot#1959]
The bot tries to evolve pidgeys from time to time and I'll get this error. 
In the settings, I have selcted Pidgey to auto evolve. 
![image](https://cloud.githubusercontent.com/assets/12624399/17474401/f941283e-5d55-11e6-9d30-fc76f4321a75.png)

**Comment by Montrazul** [comment]
"InsufficientResources" you dont have enough candies to evolve it ;)

**Comment by Dennos11** [comment]
Zubat evolve failed too


![fail](https://cloud.githubusercontent.com/assets/20901921/17474853/6224595a-5d58-11e6-864c-0f7d7cc230e5.JPG)

**Comment by CruSherFL** [comment]
@Montrazul  I don't evolve it. The bot does it automatically.

**Comment by CruSherFL** [comment]
Since 1.0.8.1 also Rattata appears trying to evolve fails.
![image](https://cloud.githubusercontent.com/assets/12624399/17494017/1b88179c-5db3-11e6-895c-288950df3fab.png)
