### ISSUE TITLE
Catch By IV %

### ISSUE THREAD

**Issue by HBraga** [Ar1i/PokemonGo-Bot#1961]
Ar1i it would be nice if there was an option to catch pokemon only if above XX% in IV..
So whom ever wants to just catch high iv pokemon, does so...
is this possible ?

**Comment by bozkurt123** [comment]
whats the IV % :)

**Comment by HBraga** [comment]
what are iv´s ?
it is basicly the total amount of perfection on a pokemon...
the better the % in IV the more powerfull it will be when fully evolved.

**Comment by bozkurt123** [comment]
ohh thank you :)

**Comment by Montrazul** [comment]
What? Where is @JeCelle with his "#1916"? Work harder or you wont get a bowl of rice today!

**Comment by HBraga** [comment]
so when you get to a certain level you only whould like to catch high IV pokemon for "secure evolving" and no spending stardust on pokemon that wont be so strong has others...
even if you have a high Cp pokemon, if it as low IV% it wont be as powerfull as a high IV% pokemon..

**Comment by bozkurt123** [comment]
i have 2 evee 
1- 549 CP %97 IV
2- 700 cp  %95 IV
Whats ur suggestion ?

**Comment by Montrazul** [comment]
lol.... of course the 700cp... guys.... IV is not THAT important. If you have an eve with 1000cp at 0% and another eve with 1000cp at 100% the 100% eve is only 10% stronger than the 0% eve.....

**Comment by bozkurt123** [comment]
Thank you mate now i understand totaly :D

**Comment by Lentsha** [comment]
Well IV DOES matter, if you want to optimize your team!

**Comment by bozkurt123** [comment]
we all agree

**Comment by pokerave** [comment]
hahhaha IV because when you full the IV is HIGHER than CP

**Comment by HBraga** [comment]
In my opinion i would keep them both!
Every thing above 90% Iv is a must keep and evolve IF  its not bellow 500 cp.. 
And we are talking about EVE it evolves into 3 diferent categories!!! vaporeon jolteon and flareon!
keep them both and when you have the stardust and seeds train them both and evolve hem both!
for high lvl players everything below 90%IV is eventually garbage above that if its above 500Cp base form its worth while to invest and train and evolve... 
But its just my opinion...

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
