### ISSUE TITLE
How to get more XP/hr?

### ISSUE THREAD

**Issue by Lukilele** [Ar1i/PokemonGo-Bot#1962]
Just want to ask, if someone here has a good trick on how to make more than 13k xp / hr. Cause all I do is max 12k xp / Hr.

**Comment by ozdenor** [comment]
you can increase your speed or you can use lucky egg. If you want to use your lucky egg, collect lots of pokemon to evolve. For example, I have collected 1200 pidgey candy. Then, startted luck egg. In 25 munites, I gained more than 100k xp. you can try this method.

**Comment by Montrazul** [comment]
What? Where is @JeCelle with his "#1916"? Work harder or you wont get a bowl of rice today!

**Comment by ineedtostudy** [comment]
Increase radius and speed. Also I'd suggest popping a lucky egg and choosing a better starting location. The default seems to be fine.

**Comment by proyugi** [comment]
Lat: -33.8688197
Long: 151.2092955
At this place, we can get about 20k xp / hr. But i am finding more. Hope anyone can help!

**Comment by Montrazul** [comment]
Be careful with fast leveling. I set my bot to 5 km/h only because the chance of a ban is smaller when you dont level up like speedy goncales.

**Comment by lucas2107** [comment]
In the center of Paris, at 16km/h i've 27k xp /h and 78 pokemons /h :+1:

**Comment by ineedtostudy** [comment]
Where I start, I get 80k/hr

**Comment by Lukilele** [comment]
Why is every pokemon running away? :O

**Comment by 0x92** [comment]
@Lukilele softban

**Comment by ozdenor** [comment]
**Do not set none of your pokeballs to zero.**

**Comment by Lukilele** [comment]
How do I get rid of the softban? just click Force Unban?

**Comment by aerladis** [comment]
lat 59.3256984
long 18.0718788

stockholm city center 45-50k exp/h

**Comment by k0bra1** [comment]
The Force Unban dont work at mine... ?

**Comment by neo66659** [comment]
lat 22,2856615660287
long 114,150202274323
Hong Kong
Currently i'm running at ~70kXP/h with ~200pk/h without any boost (encens or eggs). Walk speed : 300km/h ; area 5000m.  Soft ban happened once or twice per hour.

**Comment by AmaliaWinter** [comment]
I do not recommend more than 20 km/h for multiple reasons... like hatching eggs, getting softbanned, become on a black list (more likly if you going for aircraft speed like 300 km/h) use safe setting if you care about your account in the future. for me i get 37k xp/h in central park newyork with 19 km/h enough to farm accurate and good speed to hatch eggs because below 20km/h you hatch your eggs. and it seems like you're driving slowly in your car or Bicycling.

Greetings

**Comment by EmperorChez** [comment]
@neo66659 What's some good pokemons you getting?

**Comment by EmperorChez** [comment]
Yoyogi Park, Japan.
35.672963
139.698338

Speed: 300-500km/h
Radius: 2000km

40-70k exp/h
150-200 pkmn/h

**Comment by laxawana** [comment]
MANHATTAN

**Comment by cagdasinnal** [comment]
I prefer sydney/australia for 250 ps for 5k range. My tiny man hits stops like mario :)

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
