### ISSUE TITLE
Please add level limit

### ISSUE THREAD

**Issue by skillize** [Ar1i/PokemonGo-Bot#1965]
So lately you decided to release only debugged version, but now i cant implement level limit
(it was if level same as a textbox text where i putted like 25, for doing only 5 levels daily then it stops ) 
so the idea its put a textbox when u can choose the level that bot needs to arrive and then it stops, if you can please :-)

**Comment by Raiderman1105** [comment]
this was nice (y)

**Comment by Montrazul** [comment]
What? Where is @JeCelle with his "#1916"? Work harder or you wont get a bowl of rice today!

**Comment by skillize** [comment]
Whoops im sorry :c

**Comment by Ar1i** [comment]
Nah useless, you can stop it easily by yourself tho!

**Comment by skillize** [comment]
Yep but in the middle of night? :c
