### ISSUE TITLE
"Account requires action" on phone when running a bot

### ISSUE THREAD

**Issue by czokalapik** [Ar1i/PokemonGo-Bot#1967]
Since new bot came out i'm seeing "Account requires action" constantly on my phone, BlueStacks, Nox etc. When i click it, there is some info about changes made on account, so it requires authentication.

Since today morning i haven't used bot (at least 8 hours) and there was no notification, and when half an hour ago I started using bot again notifications were back.

I have app password created for bot (2-step auth in google) and bot itself is running without a problem.

Can this be caused by bot?

**Comment by pokerave** [comment]
No you did not activate it in you email

**Comment by Thijscream** [comment]
i also have the same problem. get it several times / day. not sure what;s causing this problem. but with 1 tablet, 1 phone it;s realy annoying to relogin every time.
seems bot related. never had it before i used the bot.

**Comment by czokalapik** [comment]
@pokerave, i don't have to activate anything in my email. when i created app password for bot i only got email confirming this, no activation required.

**Comment by Baelmung** [comment]
When you use the same mail as your phone google account the phone registers a login on a new source like another maschine and wants a verifycation to prevent that your account gets hacked and wants you to verify to tell them that you are still in possesion of your account its just a protection message for you and google. Have that all the time cause i use the same google account on 3 phones and if you log into the bot its kinda logging into a new machine so well thats probably causing the login verifycation request. 
hope i could help and hope i understood and answered the right thing my english is not the best

**Comment by czokalapik** [comment]
@Baelmung  up till now i was using phone, bluestacks, nox with same account and 3-4 apps with passwords generated for them. Never got such notification.

I know when i log on new device google is sending me SMS with code or asking me to generate app password etc, but it never  signed me out of my phone or even Bluestacks/Nox.

That's why i think it might be bot-related problem.

**Comment by Baelmung** [comment]
You used bluestacks and Nox with the password and it probably uses this extra authentification correct the bot maybe not programmed for it as you see ar1i is concentrating on getting the bot running correctly in the bot features first. so kinda like i wanted to explain it is right .... ugh my english. In other words probably the bot is not using the extra authentification like my second devices (cause i dont care for the message ) well and many with the pw authentification have it like "Thijscream" said or friends of mine 
my english really is bad that i cant even explain this sorry *bows*

**Comment by Ar1i** [comment]
https://security.google.com/settings/security/apppasswords <- create a password there and use it
