### ISSUE TITLE
What is This

### ISSUE THREAD

**Issue by xkvN** [Ar1i/PokemonGo-Bot#1968]
What is this it comes Permanently
http://prntscr.com/c30134

**Comment by pokerave** [comment]
THAT IS SPAM.. noob

**Comment by EmperorChez** [comment]
@xkvN I do believe it's just the bot restarting back to its original position.

**Comment by b3shoy** [comment]
Normal behavior for a long usage or server lag/issue, please close issue

**Comment by Ar1i** [comment]
https://security.google.com/settings/security/apppasswords

**Comment by Ar1i** [comment]
wups meant should be fixed in newest update if not reopen
