### ISSUE TITLE
Error Reloading Pokemon List

### ISSUE THREAD

**Issue by Drakoo2** [Ar1i/PokemonGo-Bot#1970]
it always gave me Error Reloading Pokemon List and the list doesnt work for me anyone know how can i fix it?

**Comment by hamris2** [comment]
Same problem for me.
![problem](https://cloud.githubusercontent.com/assets/20902516/17475804/1bf918bc-5d5d-11e6-8b68-5f453992204e.JPG)

**Comment by Drakoo2** [comment]
But i catch pokemons and pokestops anyway but my list doesnt work i use my list to transfer etc

**Comment by akangnduz** [comment]
post  your screenshoot drakoo
hamris maybe wrong pasword or because thats its ptc account you should veryfy your email,check email if already 2 day ...sry bad english

**Comment by Drakoo2** [comment]
its not wrong password because i catch pokemons and i opened my account on my mobile and all pokemons i caught them

**Comment by Drakoo2** [comment]
![bandicam 2016-08-08 13-00-25-812](https://cloud.githubusercontent.com/assets/20892678/17476622/3908f702-5d61-11e6-89c4-ca1d5fdedc77.jpg)

**Comment by b3shoy** [comment]
@Drakoo2 I won't say your username to public :smile:

**Comment by b3shoy** [comment]
Try closing bot, clearing some system cache an close unused applications, and restart the bot, it should be fixed i think.

**Comment by Drakoo2** [comment]
Sorry What? i cant understand you

**Comment by b3shoy** [comment]
screenshot is displaying ur username! not so cool.

**Comment by Drakoo2** [comment]
Oh Fck i forgot about it  is the comment deleted :D?

**Comment by Drakoo2** [comment]
![bandicam 2016-08-08 13-20-12-406](https://cloud.githubusercontent.com/assets/20892678/17476889/904cab7a-5d62-11e6-832d-ec04b7a5aee8.jpg)

**Comment by b3shoy** [comment]
@Drakoo2 yes, please do as i told you and try, if it succeeded close the issue

**Comment by akangnduz** [comment]
try delete sprites folder  for issue out of memory

**Comment by Drakoo2** [comment]
@akangnduz Thank You very much it worked for me

**Comment by b3shoy** [comment]
close the issue please

**Comment by KoreanTopLane** [comment]
Where cani find the sprites folder You talked about?
