### ISSUE TITLE
Ability to control razz berry usage?

### ISSUE THREAD

**Issue by KiraxGH** [Ar1i/PokemonGo-Bot#1971]
The bot seems to love feeding razz berrys to most pokemon I come across, as long as their cp is above a few hundred. This means I quickly burn through my supplies and I'd like to be able to chose a min cp for razz berry usage.

Thank you, no worries if this isn't possible since I realise this is a free bot and I'm grateful for the hard work that's been done here.

**Comment by AmaliaWinter** [comment]
Ähm just to mention... the bot using razzberrys very often and still i don't run out of razzberrys always on 75 which is more than enough in my oppinion.

Greetings

**Comment by fikrirmd** [comment]
hope there's an option to use razz berrys and ultra ball. because mine use more than 30 razz berry in 2 hours.

**Comment by Yumeeh** [comment]
@AmaliaWinter you probably live in an area where there are plenty of pokestops, when i put bots in a rural area i find just as many pokemon (although not as rare pokemon as in crowded area's) but not nearly as many pokestops, and they seem to run out on my  bot account ( i only use my bot account to test i'm never gonna use my main that would ruin the fun. ) But anyways @KiraxGH this is not an issue, so u shouldn't post it here.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
