### ISSUE TITLE
i cant open the rar because ther is a Virus in the PokemonGo.RocketAPI.Console.exe

### ISSUE THREAD

**Issue by Khorajuste** [Ar1i/PokemonGo-Bot#1974]
i download the last version and my problem is in the title :/
someone help me ?

**Comment by Souadka** [comment]
stop the inti-virus mate and open it !

**Comment by 1337Panther** [comment]
Did the same ;) its safe dont worry

**Comment by U2EZNeko** [comment]
As said before.

-deactivate your anti virus
-unpack it
-add an excepion to the path where the .exe is located (if possible)
-turn anti virus back on, should now run with no problem.


The code it open-source, at least it used to be/some parts are. There's no virus in it.

**Comment by Khorajuste** [comment]
ok it work thx :D

**Comment by cagdasinnal** [comment]
Dont use wooden antiviruses mate

**Comment by zzzz9999** [comment]
Then close issue please @Khorajuste

**Comment by Khorajuste** [comment]
i use bit defender :/

**Comment by b3shoy** [comment]
Close the issue, Please!
