### ISSUE TITLE
Some Runtime Errors

### ISSUE THREAD

**Issue by G4UKL3R** [Ar1i/PokemonGo-Bot#1977]
Hi,
not sure if this is important
![bug123](https://cloud.githubusercontent.com/assets/20825294/17476274/734ab498-5d5f-11e6-8810-a66386eb779b.jpg)

**Comment by Kidnub** [comment]
same i have all 30min .. i hope a hole pc reboot fix it if not seems like a code error ;(

**Comment by 1337Panther** [comment]
Yeah maybe reboot your system, mine is working fine for 5 hours now.

**Comment by G4UKL3R** [comment]
Reboot doesn´t help. 
Bot works fine but still get this error messages.

**Comment by testo4life** [comment]
now and then u will get those ignore them bot works !

**Comment by Ar1i** [comment]
Should be fixed in newest update, if not open a new issue.
