### ISSUE TITLE
[Bug] SystemOutOfRange Exception (Negative Distance)

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#198]
[13:53:24] Exception: System.ArgumentOutOfRangeException: Der Wert muss entweder -1 (dies gibt einen unendlichen Timeout an), 0 oder eine positive ganze Zahl sein.
Parametername: millisecondsDelay
   bei System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay)
   bei PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() in C:\Users\nrgne\Desktop\Pokebot\PokemonGo-Bot-master\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Navigation.cs:Zeile 100.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__14.MoveNext() in C:\Users\nrgne\Desktop\Pokebot\PokemonGo-Bot-master\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 268.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__9.MoveNext() in C:\Users\nrgne\Desktop\Pokebot\PokemonGo-Bot-master\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 136.

Die negative Distanz vorher: [13:53:23] Distance to target location: 106,93 meters. Will take -137,48 seconds!

Schon 9x in einem Run

**Comment by Ar1i** [comment]
Fixed in newset Commit probably. Try it. If it happens again, open a new Issue.
