### ISSUE TITLE
Rename or choose the evolution of eevee

### ISSUE THREAD

**Issue by magicarl** [Ar1i/PokemonGo-Bot#1980]

**Comment by CruSherFL** [comment]
You can only have on Eevee with the same name.. and for those 3 names it may be better to just log in and do it?

**Comment by HBraga** [comment]
the renaming process is ridiculously a myth...
and no bot can control the final evolution of a pokemon... being stats skills final form or anything...
stop asking for the impossible and filling the request/tread list...

**Comment by testo4life** [comment]
renaming is NOT a myth it only works once for each evulotion after that its just random.

**Comment by gummyruler** [comment]
@testo4life  It works 100/100 for me. It's just you have to make sure there are no other eevees undergoing the process. like a duplicate "rainer" or you name the eevee "rainer" and the other "pyro." You can do this, but it would be useless.

**Comment by Ar1i** [comment]
Already talked about it, it wont work 100% so its pretty useless, just do it yourself!
