### ISSUE TITLE
Pokedex Completion Stat

### ISSUE THREAD

**Issue by madeinyashiro** [Ar1i/PokemonGo-Bot#1982]
Hi !

Would it be posible to add to player's stats the completion of the Pokédex ? Now that I have more than 120 Pokemon, it would be easier to know when I catch a new one !

Thanks

**Comment by b3shoy** [comment]
--> #1916 
Close this please.

**Comment by Logxn** [comment]
you mean like so? 
![screenshot_19](https://cloud.githubusercontent.com/assets/20424274/17477709/047308a6-5d67-11e6-9e68-56cb7c5f5b6c.png)

**Comment by sunit1998** [comment]
i got 143 right now just need machamp and kabutops to complete my collection
