### ISSUE TITLE
Pokemon servers really unstable atm or pokestop problem back?

### ISSUE THREAD

**Issue by Baelmung** [Ar1i/PokemonGo-Bot#1983]
I have the problem that i start the bot and after 4-5 minutes i get either softbanned or "no pokestops found in a radius of 5000/8000/12000 metres (depending on setting)" doesnt matter if 16km/h 28km/h or 50 km/h speed is set (simulating bike/car in city/ and city train)
especially getting this issue fast when i use multiple instances of the bot before api change let 14 instances run (lot of friends of mine with no suitable pc or stable connection while i had a server thats running 24/7 anyway) and now when the 7. instance starts it breaks every instance at once kinda and suddenly softban or no pokestops.

so cause i am not technical to this extent and dunno the botcode not sure if issue or problem with my own settings

**Comment by b3shoy** [comment]
You can't have more than 3 simultaneous instances of the bot working on the same PC IP, otherwise you will get softbanned, maybe IP banned too because of the flags.

**Comment by jmo93** [comment]
Niantic  is banning more than 4 instances bcause same ip. Try only 3,4 instances

**Comment by Baelmung** [comment]
so there was a change good to know thank you so i need to virtualize the server and try to go over an proxy with the additional instances? would that be posible?

**Comment by b3shoy** [comment]
You can try that, on your own responsibility #1938

**Comment by b3shoy** [comment]
and please close this issue.
