### ISSUE TITLE
Isn't transferring many pokemon, allowing inventory to fill

### ISSUE THREAD

**Issue by Nomad52** [Ar1i/PokemonGo-Bot#1990]
Apparently for some pokemon like Tentacool and sparrow, it won't auto transfer them and lets them fill up the inventory. There are more than I listed, hopefully you should be able to see the issue and find all the pokemans effected by this.

**Comment by downspath** [comment]
screenshot of your settings pls,

**Comment by Nomad52** [comment]
Max duplicate pokemon 1 
Max CP to transfer 999
Max .IV to transfer 90%
Checked auto transfer

Pokemon not to transfer 
Venusaur
Charizard
Blastoise
Snorlax
Every rare pokemon not even in the game yet
Dragonair
And Dragonite. 
Pokemon not to catch blank
Pokemon to Evolve blank

**Comment by Dextiz** [comment]
You want to change pokémons to evolve tho... pretty sure you have "keep pokémon which can be evolved" ON
Evolve all but, dratini, dragonair, bulb, squirt, charm, charmeloeon, ivy and war.
Should fix your problem. And enable the GUI for pokémons to easily transfer shit pokémon

**Comment by Ar1i** [comment]
#1940
