### ISSUE TITLE
Bot stoped.

### ISSUE THREAD

**Issue by Osobuke** [Ar1i/PokemonGo-Bot#1992]
I have just downloaded the last version (Latest Build - 08.08 08.14), and when it connects, nothing happens.
![image](https://cloud.githubusercontent.com/assets/20903973/17477966/c8350482-5d68-11e6-90f7-3ee3254d47da.png)

**Comment by Dextiz** [comment]
here's no errors or anything, you still have this issue? If not please
/close issue
