### ISSUE TITLE
inventory full bug? sorry if im re-posting this..

### ISSUE THREAD

**Issue by mydonny1986** [Ar1i/PokemonGo-Bot#1995]
can catch pokemon, get visit pokestop and get xp, but couldnt loot most of the time..
says item: nothing. 80% of the time..
<img width="412" alt="inventory full" src="https://cloud.githubusercontent.com/assets/20655187/17478137/10984baa-5dad-11e6-8602-5d0b5f0a5fcc.png">

**Comment by TMaddox** [comment]
same her but only visualisation bug here, collects items and so on only displays f.e. 438/350

**Comment by mydonny1986** [comment]
sorry my inventory is actually full haha..gonna close this.. =P
