### ISSUE TITLE
Lure Catching ?

### ISSUE THREAD

**Issue by 1337Panther** [Ar1i/PokemonGo-Bot#1997]
Does the bot also catch the pokemons from the lures ? Because im not sure.

**Comment by tryndamerewu** [comment]
not yet  1 day ago he say he will look in to that

**Comment by DargQ** [comment]
I really want the bot not to farm pokestops just go around really populater areas with lot of lures.

**Comment by SpectraOne** [comment]
Please realize this function.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
