### ISSUE TITLE
where can i find the latest exe ore program to run the bot 

### ISSUE THREAD

**Issue by yourbrother010** [Ar1i/PokemonGo-Bot#1998]
i only find the RAR files but not the program it self to start the bot up

**Comment by Tiziako** [comment]
Just Unrar and start the exe 

(this is not a forum )

**Comment by obzc** [comment]
PokemonGo.RocketAPI.Console.exe

**Comment by 1337Panther** [comment]
@yourbrother010 

-unrar the file
-start PokemonGo.RocketAPI.Console.exe 
(Your Antivir Program could have deleted it, i got the problem before

**Comment by Toukiinou** [comment]
I've not this file too...
