### ISSUE TITLE
every few secounds a ban

### ISSUE THREAD

**Issue by LikeAFisch** [Ar1i/PokemonGo-Bot#1999]
http://prntscr.com/c31bdf
i start the bot and after 5min all of my bots has been banned.
he cant unbanned!
Not allone or with "Force Unban".

**Comment by fikrirmd** [comment]
try a different IP, and the force unban. it works for me.
good luck!

**Comment by LikeAFisch** [comment]
http://prntscr.com/c31ce5

**Comment by 1337Panther** [comment]
You are running to many bots, my limit is 3 ! But I heard some people can only run 1 bot at the time

**Comment by LikeAFisch** [comment]
i  have 8 xD

**Comment by 1337Panther** [comment]
You can maximum run 3 bots ! Close issue pls

**Comment by justchil** [comment]
3 google account instances = ban for me.  Tested on 3x different VPS/IP's.  I can run 2x google 1x PTC though.

**Comment by idkwateva** [comment]
run only 2 bots... if you still got banned run only 1... don't force it...
