### ISSUE TITLE
[Problem] Not all Pokemons are transfered.

### ISSUE THREAD

**Issue by Dmnation** [Ar1i/PokemonGo-Bot#2]
I only want to hold 2 Pokemons from each, so i change the Skip-Value to (2).
But i've got 5-6 Pinsirs in my storage, they dont transfered to Eich.

**Comment by Ph1l77** [comment]
have the same problem 
only appears for pinsirs for me

**Comment by Ar1i** [comment]
Uhm Probably CP over 999?

**Comment by Dmnation** [comment]
Yep, its over 1000.. that seems to be the problem.

And also the favorites wont transfered to Eich. Seems like the bot is holding the favorites. Is this right?

**Comment by Ph1l77** [comment]
line 386 in the logic.cs is right?

**Comment by Ar1i** [comment]
Yeah, thats the Problem. I will push an Update. Then you can edit in Settings, that he holds Pokemons with more then > ? CP.

**Comment by Ar1i** [comment]
Update up. Please test it. If it´s working, i will close this here.

**Comment by Dmnation** [comment]
Tested it, it works :)

**Comment by Ph1l77** [comment]
http://x-up.ws/i/4ba25c3c4773.png
dank dir

**Comment by Ar1i** [comment]
Thanks.
