### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by JackSbirrow** [Ar1i/PokemonGo-Bot#2000]
I have this error with all the bots!

When I try to log with Google i get this: http://puu.sh/qtQYp/05a6644249.png (In english: Object reference not set to an instance of an object.)

If I try with PTC i get this: http://puu.sh/qtR7S/8e467d69a2.png
and continue here: http://puu.sh/qtR9w/820d50103e.png

Any solution? What do these error mean?

**Comment by Dextiz** [comment]
You still have this problem?
Try to download the newest version and redo it. should fix it

**Comment by JackSbirrow** [comment]
I have this problem since the 0.7.2 and in every version i have this problem, even 0.7.6
When I try to log with PTC in every bot it says there is an error with mscorlib.dll, (look the first screen i put on this issue) and if I try with Google there is an error about istance and object, I can't use any bot...

**Comment by arjunvegda** [comment]
Delete whole folder and download a new one. And configure it from fresh.

**Comment by gummyruler** [comment]
Could be that you were banned for entering the wrong password. Try logging in your account from nox or your phone.

**Comment by JackSbirrow** [comment]
I tried with both account in my phone and still unbanned

**Comment by JackSbirrow** [comment]
In my other computer all the bots work, in this one not even one of them...

**Comment by arjunvegda** [comment]
@JackSbirrow  Get a VPN

**Comment by JackSbirrow** [comment]
Why do I need a VPN? It's a problem about files in my computer because in my other one all the bots work
