### ISSUE TITLE
Not catching pokemon!

### ISSUE THREAD

**Issue by henrywww255** [Ar1i/PokemonGo-Bot#2001]
They always get away, giving the message "X got away" this always happens, like if the character were softbanned, but even after force unbanning or receiving the "1337 anti ban" it continues to not capture pokemos, everything else is fine, but sadly i lost 4 lucky eggs in the process.

**Comment by 1337Panther** [comment]
@henrywww255 the 1337 unban doesnt work at the moment because we got a new type of softban (time ip bans)

**Comment by YakuzaR** [comment]
dont catching pokemons for me too, but dont got softbanned

**Comment by henrywww255** [comment]
It is now working, i simply don't know why, are you a magician? it literally started working the second you replied! it is now capturing them, thank you! (i guess?)

**Comment by YakuzaR** [comment]
@henrywww255  u restarted it or just simply run the bot?

**Comment by henrywww255** [comment]
It literally started working! http://imgur.com/a/Y3xrK

**Comment by b3shoy** [comment]
make sure guys that you have >20 pokeballs and total items <330.

**Comment by yossarianmw** [comment]
if u can receive XP or items from pokestop, thats definitely not banned.
but because from newest update pokemon go *0.31.0* its hard to catch pokemon, the got away..
niantic already mention they will fix it in upcoming update.

**Comment by b3shoy** [comment]
@yossarianmw No, read my comment above.

**Comment by yossarianmw** [comment]
hm.. when it got away, i stop the bot and check, i still have 15 pokeballs

**Comment by b3shoy** [comment]
be in the safe side and make bot have more than 20 pokeballs, and all items under 330
