### ISSUE TITLE
How the new update is installed?

### ISSUE THREAD

**Issue by RuseolliModzYT** [Ar1i/PokemonGo-Bot#2002]
A question like the new update is installed? It is missing many files and folders before had more, and my only show me 2

**Comment by izzaeroth** [comment]
i just downloaded it, and mine showed the usual stuff. did you try and re-download it?

**Comment by b3shoy** [comment]
copy your config and sprites folders, and place them inside the new extracted bot folder.

**Comment by Dextiz** [comment]
He removed other stuff from this download, rocketAPI, RocketConfig.
Should still work just fine for you. download the newest version and just unpack it in the folder. 
ez

**Comment by RuseolliModzYT** [comment]
Thank you all
