### ISSUE TITLE
Unhandled exception has ocurred !

### ISSUE THREAD

**Issue by insaneinet** [Ar1i/PokemonGo-Bot#2003]
Well since the bot didnt work it keeps giving me this message, i updated every file since the last 2 updates u made and keeps giving me the message. I dont know what to do!
https://gyazo.com/4aaad33c2ce414e6a2e759c77287f339

**Comment by VitoDEV** [comment]
Redownload your MICROSOFT .Net Framework, and try again, and repair the old one.
Or delete the old one, and install the new one..
And make sure to update all your drivers.

**Comment by U2EZNeko** [comment]
@insaneinet looks like your Dotnet framwork is broken or not propperly installed.

Windows updates usually downloads those so either let Windows check for updates or download the .Net framework here:
https://www.microsoft.com/en-us/download/details.aspx?id=30653


this may not be the version you need, maybe it is. You're gonna have to find that out yourself i cannot tell from the ss you posted
