### ISSUE TITLE
/ not issue ! / if you run more than 3 instances u get soft banned

### ISSUE THREAD

**Issue by 07AF** [Ar1i/PokemonGo-Bot#2005]
what does it mean in german ?

**Comment by U2EZNeko** [comment]
Wenn du mehr als 3 bots am laufen hast gibts nen softbann @07AF

**Comment by SebiWolze** [comment]
Wenn du den Bot mehr als 3x startest über eine IP werden deine Bots mit einem Softbann belegt, Niantic hat da ne neue Sperre drin.

**Comment by 07AF** [comment]
achso :D konnte man das früher oder wie ?

**Comment by Raiderman1105** [comment]
Ja konnte man leider

**Comment by Logxn** [comment]
^
