### ISSUE TITLE
Reoccuring bug after failing to catch a Pokemon

### ISSUE THREAD

**Issue by U2EZNeko** [Ar1i/PokemonGo-Bot#2006]
Hey there!

Not sure if it's been posted before, I saw a similar bug report  a few minutes ago but that didnt seem to be the exact same.

Basically, sometimes when a Pokemon flee's, the bot will still see it, click on it and try to catch it.

Ofc this doesn't work because it fled just a minute ago, the bot is trying to catch a ghost, basically.

https://imgur.com/a/aVdpl

Here's what I mean. The Pidgey in the picture has 20CP, everytime.

The bot manages to feed it berries every now and then, causing me to lose most/all of them. 

Hope you can help, I'll delete the thread if this is a repost.

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17478698/437487ea-5d8b-11e6-99bb-e3c854723ad9.png)

**Comment by PokePro21** [comment]
just because of 0 pokeballs dont keep total count more than 330+

**Comment by Logxn** [comment]
Dont keep any pokeballs 0

**Comment by U2EZNeko** [comment]
Doesn't seem o be the problem, buddy.. I'm 1 underneath my max in total. 

Thought about that aswell

**Comment by U2EZNeko** [comment]
Update: 

The bot is about 500m away from the initial monster spawn location and it still sees it. Quite sure something is broken.

**Comment by Koimii** [comment]
@U2EZNeko i have exactly the same problem

**Comment by U2EZNeko** [comment]
@Koimii @Logxn was right, as soon as you have 0 PokeBalls it will glitch.. -> The bot tries to catch the pokemon with none existend balls or rather it will not check for Super/hyperballs.


Fix: Keep Pokeballs at 20 or some.. I had it at 5 and the glitch started after the bot wasted those 5 without getting more.
