### ISSUE TITLE
Automatisch Verschicken

### ISSUE THREAD

**Issue by CINEXHD** [Ar1i/PokemonGo-Bot#2007]
Kann ich die doppelten pokemons irgendwie automatisch verschicken

**Comment by Logxn** [comment]
Guckst du unter Pokemons, ganz unten.

**Comment by U2EZNeko** [comment]
![bruh](https://cloud.githubusercontent.com/assets/20902663/17478637/9352f206-5d6d-11e6-94d8-699a01c84f08.PNG)

**Comment by CINEXHD** [comment]
Danke :+1:
