### ISSUE TITLE
max lvl pokemon can still be power up one more time in the bot. bug?

### ISSUE THREAD

**Issue by mydonny1986** [Ar1i/PokemonGo-Bot#2008]
on my phone it shows trainer level too low to power up.
but in the bot you can actually power up one more time.
im on lvl33 at moment, max pokemon level should be lvl 34.5

here's screen shot before i power up Arcanine(34.5), already powered up Dragonite(35) and Vaporeon(35)..
<img width="341" alt="before" src="https://cloud.githubusercontent.com/assets/20655187/17478583/4fea591c-5db0-11e6-99dd-7b8df9d84409.png">
here is after i power up Arcanine
<img width="340" alt="after" src="https://cloud.githubusercontent.com/assets/20655187/17478589/5a5db77c-5db0-11e6-9ea5-f6742f80b545.png">

i couldnt power up any of them in the game, max level at 34.5, but bot max level at 35

**Comment by Logxn** [comment]
Thats not an issue, thats tricking the app +1

**Comment by mydonny1986** [comment]
thanks
