### ISSUE TITLE
eggs & auto incubators

### ISSUE THREAD

**Issue by Shoier** [Ar1i/PokemonGo-Bot#2011]
if someone from team can answer for this req. Are you improve bot to auto incubating eggs ?

**Comment by 1337Panther** [comment]
Man, you need to read, you can turn on the feautrue use auto incubators, but you have to turn the walking speed to 20 or lower ... to auto incubate

**Comment by U2EZNeko** [comment]
@1337Panther the option is enabled by default, even lol



@Shoier you can enable/disable hatching and you can also tell it to use only the unlimited one.

**Comment by Logxn** [comment]
You all need to read:
Auto Incubating does not work at the moment.
Simply set your speed to 8km/h MAX to hatch
