### ISSUE TITLE
ok after i opened 6 bots they are going to lost pokeshop

### ISSUE THREAD

**Issue by melody09341** [Ar1i/PokemonGo-Bot#2012]
i used vpn it still can't find any pokeshops and pokemons  also i used the force unban it's still not working

**Comment by Kidnub** [comment]
to many bots??? [ref info]( https://github.com/Ar1i/PokemonGo-Bot/issues/2005)

**Comment by 1337Panther** [comment]
Its not an fault of the creators that the force unban doesnt work @ the moment.
You got to many bots open, i understand that you use vpn but i would max use 3.
New type of softban is time softban (IP) so you cant play for a some minutes

**Comment by 1337Panther** [comment]
Please /close (no issue)

**Comment by melody09341** [comment]
i am thinking caz i set the locat @ USA so i got banned  after that i reset locat at japan it can works😂😂
