### ISSUE TITLE
Certificate password?

### ISSUE THREAD

**Issue by ahmetkazan37** [Ar1i/PokemonGo-Bot#2013]
I cant open PokemonGo.RocketAPI.Console.exe. is this because i need a password for installing the certificate?

**Comment by Logxn** [comment]
What?

**Comment by Logxn** [comment]
Why cant you open the program? any errors? nothing happening?

**Comment by 1337Panther** [comment]
There is no password neede, make sure you install it from the right source.

**Comment by ahmetkazan37** [comment]
I have a cert,pfx in the package :) After just starting the program i get this message: Windows cannot acces the specified device,path or file. You may not have the appropriate permissions to access the item.

It worked with the older versions and i am the admin of this device :) it is a little strange.

**Comment by lfaveur** [comment]
make a screen please :)

**Comment by ahmetkazan37** [comment]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/10278314/17479096/a8459b84-5d70-11e6-9c01-497db9444010.png)

![image](https://cloud.githubusercontent.com/assets/10278314/17479113/c4f17618-5d70-11e6-9877-0480a62ff796.png)

**Comment by ahmetkazan37** [comment]
With the older versions there was no Certificate. I downloaded the .rar file from https://github.com/Ar1i/PokemonGo-Bot

**Comment by izzaeroth** [comment]
run as admin? or change the location of where it was saved?

**Comment by ahmetkazan37** [comment]
Nothing helps. I disabled my antivirus programs but still notiing.

**Comment by U2EZNeko** [comment]
@ahmetkazan37 "antivirus programs"... You have multiple installed...?


You shouldn't have to install anything at all... I'm running my bots from a USB stick on a PC where I don't have Admin rights...

**Comment by ahmetkazan37** [comment]
hmm. oke thank you. I will try it with an USB to.

**Comment by ahmetkazan37** [comment]
USB not working either. I will try it after a few hours again with my other laptop. 
For now lets close the issue.
