### ISSUE TITLE
How to increase XP per Hour?

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2015]
![bot1](https://cloud.githubusercontent.com/assets/20780971/17479031/e84776ac-5d67-11e6-8e3a-0122106c4909.png)

Only 19 432 xp/h...
How to increase? Set a higher speed? (currently 12km/h to avoid bans)

**Comment by shaoware** [comment]
I don't know but i want to know (:

**Comment by 1337Panther** [comment]
Please /close its not an issue, get another location set speed to 50 km/h i recommend central park

**Comment by shaoware** [comment]
san francisco = 260 pokestops near

**Comment by BlackHatching** [comment]
150kmh ; lucky eggs ; sydney,central park, san francisco

**Comment by zzzz9999** [comment]
Im in Sydney.
NY only next few days :P 
Closing ...

**Comment by shaoware** [comment]
150kmh wtf ? working ?

**Comment by BlackHatching** [comment]
i tested 1000kmh thats working too yh
