### ISSUE TITLE
now no pokestops?

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#2016]
was in the same location for past 5 hours now there no pokestop here when there was 212? changed location 3 times to other spots I have used all with 150+ pokestops saying no pokestops anywhere

**Comment by b3shoy** [comment]
do you have the latest version?

**Comment by OGcpalm** [comment]
yes sir

**Comment by OGcpalm** [comment]
fixed it strangest bug I have ever seen put your item count to add up to exactly 355 and it will say no pokestops near > 355 works didn't try under

**Comment by b3shoy** [comment]
yes, the max should be >330 items.

**Comment by Kidnub** [comment]
softban? or to high range of the radius?

**Comment by OGcpalm** [comment]
@Kidnub nope was in same spot for past 5 years didn't change anything

**Comment by b3shoy** [comment]
if sooftban, bot will detect pokestops anyways

**Comment by OGcpalm** [comment]
its not a softban what are you guys talking about, when your softbanned it doesn't say "no pokestops"

**Comment by b3shoy** [comment]
please close it if it's solved

**Comment by DemonBytes** [comment]
got the same issue. doesnt work properly. yesterday evening all was good. during night and today, doesnt work at all. maybe it's the servers... dunno..

**Comment by Buddhasama** [comment]
Now if you have more than 3 bots running on the same ip you will get ip softban and it will say no pokestops found.

**Comment by b3shoy** [comment]
@OGcpalm please close
