### ISSUE TITLE
Information for IV bot

### ISSUE THREAD

**Issue by k-chen59** [Ar1i/PokemonGo-Bot#2018]
Hi, please someone can explain me the best IV ? 
For example "(Best: 572 CP, IV 92%)" 
Because the bot transfers the pokemons with more than 90 IV while in the option, the max to tranfer is 90%.

**Comment by xuninho** [comment]
This is the pokemon that in pokedex.

**Comment by b3shoy** [comment]
It transfers one kind of Pokemon, and tells you that your best one is "(Best: ... CP, ... IV)".
Nothing to worry about, just informative message for your best Pokemon in this type.

**Comment by b3shoy** [comment]
close this please

**Comment by k-chen59** [comment]
Oh okay thank you so much I close this post
