### ISSUE TITLE
ALL pokemon got away

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#2019]
![capture](https://cloud.githubusercontent.com/assets/20703341/17479337/5b14871a-5d72-11e6-99f2-056c11573397.PNG)

All pokemon got away...

**Comment by U2EZNeko** [comment]
It's  bcause you're out of Pokeballs.


Had the same problem


Simply set max Pokeballs to like 20+ and keep the maximum Item number under 350

Should fix it, let me know.

**Comment by stormlolz** [comment]
Thank you bro

**Comment by stormlolz** [comment]
So the bot attempt to use pokeball all time ? even if I have no pokeball?

**Comment by madeinyashiro** [comment]
Only for pkmn with CP between 0-499

**Comment by stormlolz** [comment]
Hum ok thank you

**Comment by U2EZNeko** [comment]
@stormlolz might be what @madeinyashiro said. 

To be honest idk where the error is. Pretty sure the bot will try to use a pokeball even if it isnt there.

**Comment by stormlolz** [comment]
I have no pokeball on my account, only great and ultraball

It would force the bot use higher pokeball if we do not have that in relation to the CP of pokemon

Or an option to ignore the pokemon (not encounter it) if we do not have ball in relation to the CP of pokemon

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17483234/dbf577ba-5da2-11e6-840d-16dc6173a08a.png)

**Comment by stormlolz** [comment]
But it's illogic to keep maximum pokeball and 0 ultra ball, it's best to keep the best ball no ? even if we use it on low CP pokemon !
