### ISSUE TITLE
FYI: Experiencing "Exceptions" error sometimes

### ISSUE THREAD

**Issue by cyb0rg01** [Ar1i/PokemonGo-Bot#2020]
Sometimes I am experiencing an "Exceptions" error, but the bot keeps running. It is just for your info.

![pokemon_go_bot_error](https://cloud.githubusercontent.com/assets/20904908/17479445/e52ccf02-5d72-11e6-8430-c89c476964ff.jpg)

**Comment by 1337Panther** [comment]
Maybe reboot your device, doesnt look like an issue from the bot

**Comment by b3shoy** [comment]
exceptions happen, unless they are fatal or issue-stoppers, please don't create a new issue.

**Comment by wally1980** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/20905265/17479605/63d97a10-5d6b-11e6-866a-8c3a5e04b556.png)
i been having same thing since update and it refuses to run im at a loss ! gonna see if i can try another way to see if its my account as i had no issues before the big changes

**Comment by b3shoy** [comment]
@wally1980 make sure that you are doing cleen installation for the latest version,
take your config and sprites folders and place them in a newly extracted bot folder.

**Comment by U2EZNeko** [comment]
@wally1980 I've had that happen before.. My very questionable fix is rebooting your machine or trying to open the bot again with admin rights..

Either one usually does the trick for me.

**Comment by Ar1i** [comment]
@wally1980 download newest version
@cyb0rg01 i already fixed that, uploading it later
