### ISSUE TITLE
Rename and Favourite your Pokemon

### ISSUE THREAD

**Issue by gshock91** [Ar1i/PokemonGo-Bot#2021]
it should be very handy to rename and favorite your pokemon.
your GUI for pokemon is by far the best.

thanku guys for al the hard work!

**Comment by 1337Panther** [comment]
Please /close its not an issue 

If you want any things to be implented ask over there
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by U2EZNeko** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/ 


Not a forum, buddy. Recommendations go to the website above. 
Close this please.


Hope the Mods are fine with me asking you to do so.

**Comment by gshock91** [comment]
sorry guys! my german is not so good ill try there
