### ISSUE TITLE
Can't get any Pokémon

### ISSUE THREAD

**Issue by StefanVIIXI** [Ar1i/PokemonGo-Bot#2022]
I can farm all Pokestops but i can't get any Pokémon?

Every single Pokémon get away. But Pokestops are working?

What is this

**Comment by stormlolz** [comment]
You have probably no pokeballs..

**Comment by acelya** [comment]
you should keep 10-20 normal pokeballs because it wont use any greatballs for low cp pokemon.

**Comment by U2EZNeko** [comment]
#2006

**Comment by testo4life** [comment]
cant u guys READ first before posting ! 100x same issue  no one reads always new topic. Lazy ppls out there !
