### ISSUE TITLE
No evolve don't work

### ISSUE THREAD

**Issue by Lexobama** [Ar1i/PokemonGo-Bot#2023]
Even if all the Pokémon not evolve are checked, they evolve still automatically. Normal ?

sorry for my bad english

**Comment by testo4life** [comment]
check your setting " Enable pokemon when enough candy " should be active !Disable it !

**Comment by mexyn** [comment]
Are u sure you correctly set the checkmarks? I cant look right now, but as far as i do remember the interface, you check the pokemons you WANT TO evolve. So in your case, there should be no checkmark set. Works for me.

**Comment by Lexobama** [comment]
I check all the pokemon not evolve. The third checklist in "Pokemon". Or am, the French translation was bad and I got screwed.

**Comment by BEKKNQV** [comment]
Third checklist is "Pokemon to evolve", uncheck all if you don't want to evolve any of your pokemon.

**Comment by Lexobama** [comment]
Okay. So if I check a Pokemon is to make it evolve? Or not to evolve it?

**Comment by BEKKNQV** [comment]
If you check the pokemon in the list, it is making the evolve.

**Comment by Lexobama** [comment]
Okay! Thanks. The French translation was beautiful and very bad.
