### ISSUE TITLE
Error reloading Pokemon list?

### ISSUE THREAD

**Issue by infinite10** [Ar1i/PokemonGo-Bot#2026]
Yesterday the .exe worked perfectly. Now I started the new .exe (updated version) and I get these nonstop errors, how is this possible and how can I fix this?
Help would be much appreciated
(1 attachment)

![screenshot1](https://cloud.githubusercontent.com/assets/20906240/17480973/e0f97b94-5d7a-11e6-8d51-4f30c144dc41.png)

**Comment by LetMeKnowYourName** [comment]
Have you tried deleting your \Configs folder? Restart the bot and re-configure your settings. It's running just fine over here.

**Comment by feraso25** [comment]
Here this error happning only with poke accounts, using google accounts work fine.  :(

**Comment by feraso25** [comment]
![error](https://cloud.githubusercontent.com/assets/20906625/17481868/7c942b88-5d55-11e6-8786-b21d2129b852.png)

**Comment by infinite10** [comment]
I got the exact same thing.
Btw, I use a Google account so that shoudn't be it right?
I really hope for a solution to this

**Comment by feraso25** [comment]
Yes shoundnt be for google accounts, here in my computer ggogle accounts work fine, only Poke accounts didint work.

**Comment by infinite10** [comment]
I tried 4 different google accounts, even different IP's, did not work at all.
Also deleted config file, nothing seems to help, why oh why

**Comment by feraso25** [comment]
This error continue?
For me back to happening, now with Google and Poke accounts.
:(

**Comment by feraso25** [comment]
![error](https://cloud.githubusercontent.com/assets/20906625/17500100/dbf67182-5da8-11e6-84a6-0041058cd3e5.png)

**Comment by ankhmok** [comment]
i have the same issues

**Comment by AguilaHub** [comment]
Same here

**Comment by AguilaHub** [comment]
It does exactly look like the error earlier but the fixes dont work -,-

**Comment by ankhmok** [comment]
i did download tthe bot again and it wouldnt work

**Comment by xRealMaks** [comment]
Should be fixed in the newest version.
