### ISSUE TITLE
Hatching not working?

### ISSUE THREAD

**Issue by idkwateva** [Ar1i/PokemonGo-Bot#2027]
I have on the report 9 eggs... but it's never hatched...
Any idea why?

**Comment by b3shoy** [comment]
Hatching is not implemented completely, wait til it's officially released, and close the issue please

**Comment by PippoAe** [comment]
This big is already postet multiple times.
They're working on it.

**Comment by testo4life** [comment]
eggs are hatching but there is No notification for that. When they did or not. if u have 5 km eggs. Incubate them through mobile let the bot run 6 km and it wil hatch automatically !
