### ISSUE TITLE
Pokemon transfer Question

### ISSUE THREAD

**Issue by Lukilele** [Ar1i/PokemonGo-Bot#2028]
Is there a way to let the bot transfer all Pokemons under 750cp, even tho all the Pidgeys and Weedles and all that. Cause the only thing I see is, that you can type in the Box where it says "Max. duplicate Pokemons" just the number 1, but i want to have 0 Pidgeys. What I want is that the bot transfers EVERYTHING under 750cp.

**Comment by b3shoy** [comment]
There is a transfer list, select what you want to transfer in it.
and this is a question not an issue, please close.

**Comment by Buddhasama** [comment]
It is an issue since you select the bot to transfer everything under 750 but it doesn't transfer them.

**Comment by gummyruler** [comment]
SEt it to 750CP max duplicate 0.

**Comment by Lukilele** [comment]
@gummyruler ok well thanks mate, i just tried this before but it just give me a red box, now it's working don't know why, but how ever, thanks for the info and help tho :)

/closed
