### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Chris20000** [Ar1i/PokemonGo-Bot#2029]
I´m very lucky the bot works again, but i have a question: In most cases of found pokemon, it says: "encountered -name-" and not "caught -name-". What does this mean and can I do anything?

**Comment by b3shoy** [comment]
does it say encountered only, check the line after it for the caught statement.

**Comment by Chris20000** [comment]
Thanks, I got it, but which meaning does the encountered line have then?

**Comment by b3shoy** [comment]
it means that the bot detected this pokemon in sight and going to catch it.
Please close//
