### ISSUE TITLE
Chose ITEM_GREAT_BALL over ITEM POKE_BALL

### ISSUE THREAD

**Issue by yoyos** [Ar1i/PokemonGo-Bot#203]
I would prefer using GREAT BALL Over POKE BALL for a certain pokemon level

I'm doing a lot of misses with pokeballs with 300CP pokemons and I have 200 GREAT BALL and 150 ULTRA BALL in my bags ...

Is it possible to have settings for that ? 

Thanks ! :)

**Comment by IceQ1337** [comment]
The Bot always uses the best choice of pokeballs. He does it by itself.
If you get stuck with a lot of pokeballs, try change the amount to delete/hold in the settings UI.

**Comment by madhoy** [comment]
no answer for setting?

**Comment by Ar1i** [comment]
Just set the normal Pokeball to zero, so he dont own any. But the Bot is auto choosing the best one.

**Comment by yoyos** [comment]
It would have been great to chose using a GREAT BALL for certains IV's ...

POKEBALL is already at 0 in my settings but it keeps getting them from pokestops and only recycles them too late it already caught some pokemons with them.
