### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by dadaxd** [Ar1i/PokemonGo-Bot#2033]
![12](https://cloud.githubusercontent.com/assets/20825003/17482237/1a21e0a4-5d81-11e6-9b89-6554cfd690cc.png)
hat jmd eine loesung?

er ladet auch keine Pokemonliste...

**Comment by money1989** [comment]
löschen
und neu entpacken
dann gehts wieder

**Comment by dadaxd** [comment]
probiere,danke

**Comment by 1337Panther** [comment]
Wenn dies das Problem löst bitte closen ;)

**Comment by dadaxd** [comment]
![adsdsd](https://cloud.githubusercontent.com/assets/20825003/17482452/1daaf67e-5d82-11e6-89fb-1f95d6545483.png)
es lief ohne probleme... wollte den bot für paar std ausmachen und nun geht er nicht mehr
habe pc neugestartet, neu instaliert

**Comment by dadaxd** [comment]
jmd ne loesung?

**Comment by DirtyAssign** [comment]
Die Fehlermeldung sagt, dass etwas fehlt.
Vielleicht hast du nicht alle Files in einen neuen Ordner kopiert?
Oder dein Viren-Programm hat etwas in Quarantäne gesetzt?

**Comment by dadaxd** [comment]
![sadsadasdasd](https://cloud.githubusercontent.com/assets/20825003/17483180/59ae2210-5d85-11e6-984f-6e494a92c7ae.png)


ok ich mach mal folgendes, virenprogramm aus und lade es neu runter

**Comment by dadaxd** [comment]
problem immernoch, könnte es ein softbann sein, während ich vllt offline war und ich evtl die zeit nun abwarten muss?

**Comment by Ar1i** [comment]
Lade dir das neuste Microsoft Framework runter
