### ISSUE TITLE
Prioritise IV over CP

### ISSUE THREAD

**Issue by jief78** [Ar1i/PokemonGo-Bot#2036]
hello @Ar1i  thank you very much for your bot i'm found of it
But i just got a 59% IV charmander 
and the bot transferred it because i had one with more cp but much less iv
is it possible to add an option to prioritise IV over CP
i think it's an important thing IMHO
thank you.

**Comment by b3shoy** [comment]
You can post this here:
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

Please Close, this is for issues only.

**Comment by jief78** [comment]
ok thanks closed

**Comment by jief78** [comment]
@Ar1i 
Are you sure this is not an issue because in my mind it really is.
throwing away hard to find pokemons seams to be an issue, isn't it?

**Comment by b3shoy** [comment]
Technically, it's not an issue, because you decide the CP and IV you want to  transfer.
Game-wise, It maybe better to have an option for prioritizing CP over IV (which is now applied in transfer for IVs less than the desired) or vice-versa.

**Comment by jief78** [comment]
> Technically, it's not an issue, because you decide the CP and IV you want to transfer.


yes but it's different than what my problem is, because none of them hint my min IV and cp but throwing away a higher iv pokemon versus an higher cp is technically a problem.
as is the bot is simply throwing better pokemon and keeping weaker

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
