### ISSUE TITLE
Transfer Down ?

### ISSUE THREAD

**Issue by sHaXx69** [Ar1i/PokemonGo-Bot#2037]
one can help me my bot does not transfer more still 250 pokemons fully :(

**Comment by seehuily** [comment]
me too, I used default setting, and ended up collecting many low level pokemons below:
Weedle
Rattata
Poliwag
Pidgey
Pidgeotto
Nidoran F
Caterpie

**Comment by sHaXx69** [comment]
the bot will send no more pokemons away why

**Comment by ppphhh** [comment]
Check Setting "Keep Pokemond which can be evolved. Should be unchecked otherwise it keeps them all.

**Comment by Deepbluen** [comment]
Same problem here...

**Comment by ppphhh** [comment]
No this is not an error. It's a misunderstud feature. It keeps the Pokemon which can be evolved. Just uncheck it an it works the way you exspect.

**Comment by sHaXx69** [comment]
thy guys <3 knows her a good bot space? farming tool?
