### ISSUE TITLE
[Not Issue But Question] Open Pokemon Go on GPS Off

### ISSUE THREAD

**Issue by WhoBotWhoBad** [Ar1i/PokemonGo-Bot#2038]
My friends ask me to bot their account. Their account is in the different country like US. So is it safe to let them check their account when they want but to make sure their GPS os offline?

Like my friend is in Indonesia but their bot is in the US. Check their account with offline GPS

SAFE?

**Comment by jief78** [comment]
yes it's safe you can close this

**Comment by xJustx** [comment]
^
