### ISSUE TITLE
Set Location: Altitude never changes. Has influence on GPS?

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2039]
On previous bot versions, Altitude was changing at same time of Lat/Long.
On this version Altitude keeps always the same, don't change.
Does it affect GPS? Why is not changing anymore?
Thanks

**Comment by Ar1i** [comment]
Uhm Altidude should change your using newest version?

**Comment by stormlolz** [comment]
i'm using last version and altitude is = 0 in GUI when we change lat and long

**Comment by zzzz9999** [comment]
Yes @Ar1i I'm using "Latest Build - 08.08 08.14".
When moving map, Lat/Long changes, but Alitude no.
Thanks

**Comment by ppphhh** [comment]
have also this issue with version 08.08 08.14. Sometimes it works, sometimes not.

**Comment by Ar1i** [comment]
It will auto solve that problem if its 0 in gui, so there is no problem! It changes 100%!
