### ISSUE TITLE
problem finding pokestops

### ISSUE THREAD

**Issue by FelipeMallmann** [Ar1i/PokemonGo-Bot#204]
we cant find any pokestops in a range of x m!

**Comment by IceQ1337** [comment]
Does he travel to pokestops anyway?
Got this problem a few versions before, but it worked fine.

**Comment by Joxiii** [comment]
For me too also on my real Device all no Pokestops Lol :D

**Comment by FelipeMallmann** [comment]
he is trying to travel to default location, but is already in it..
I'm using version 29.07 - 14.28

**Comment by Logxn** [comment]
I had this too.
Just change your location to idk. Mexico City.
That worked for me. (I actually did not try settings it back to central park...)

**Comment by FelipeMallmann** [comment]
I just waited and now he found pokestops again

**Comment by Ar1i** [comment]
Its cause the Server are laggy.
