### ISSUE TITLE
List of real issues

### ISSUE THREAD

**Issue by Niubbo** [Ar1i/PokemonGo-Bot#2040]
i found these problems

1) IV doesent match between interfaces prompt say a number and GUI say another one **.:Seems fixed:.**

2) incubator bot doesnt work

3) items number on terminal doesent match the real
now he write 287/350 and he dont take nothing but exp from pokestop, if i log in throgh the app i see items are fully capped

4) "failed to evolve pokemon" i assume there is no candy, so the game should check before the candy avalaibility

5) last coords start doesnt work

6) *this is not a programming issue, but user issue*
    should be nice have the option to change the system id, for not be banned

i think the first 3 points should have an high priority to be fixed

i wanna say a huge thanks to dev, because he is doing an awesome job

**Comment by Niubbo** [comment]
list updated

**Comment by xRealMaks** [comment]
Thanks for your work. Sorry for the time you waited.
1) Fixed
2) See #1924
6) SystemID is random, as far as i know
I will forward it. :+1:
