### ISSUE TITLE
extreme change in gps didn't get me soft banned

### ISSUE THREAD

**Issue by sylva91** [Ar1i/PokemonGo-Bot#2042]
i changed my location within 2 hours between : New york - Paris - Sydney. I farmed over 20k XP and this morning i rechecked by connecting at Paris and it was still OK.

I find that weird since it's suppose to ban such users, any explanations ?

**Comment by BlackHatching** [comment]
Because the bot unbans you

**Comment by sylva91** [comment]
I mean, isn't the PGO gps system configured to detect those OBVIOUS cheating methods ?  like someone being in new york at 10am then being in paris at 10:30 am

**Comment by pikaiskawai** [comment]
FFS this is not a forum

**Comment by xJustx** [comment]
not an issue?
