### ISSUE TITLE
Can I set a way the bot should walk ?

### ISSUE THREAD

**Issue by Wastl1** [Ar1i/PokemonGo-Bot#2045]
Sorry if im wrong here with this but i dont know where else i should ask.
Is it Possible to set tracks for the bot ? like i set him a own way to go wich doesn´t only let him go from Pokestop to Pokestop.
And I would have another Qestion may be dump to ask but what does the Telegram setting do ? 
[Api token / Name ] and should they get set or doesn´t it matter ?

**Comment by jivie2006** [comment]
also wondering this. would love to be able to set a long path that the bot don't deviate more than 200m from. like set points and it works from point to point, for example to walk down santa monica beach hitting poke stops but don't go to far inland.

**Comment by Wastl1** [comment]
That is exatly what i mean.

**Comment by xhalfbakedguy** [comment]
set your location in the water and create a radius that only covers the pokestops you want it to. i used google maps and my imagination

**Comment by xhalfbakedguy** [comment]
http://imgur.com/uTbgXx3
like this

**Comment by jivie2006** [comment]
i have done this in a lake to work around the edge i just wish i could fallow several miles of beach

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
