### ISSUE TITLE
not transferring a certain pokemon

### ISSUE THREAD

**Issue by amaslkw** [Ar1i/PokemonGo-Bot#2046]
im quite sure the settings are correct coz they are working for all other pokemons.
but the bot is not transferring zubat only. all of them are kept , even those lower than the max cp or max iv%. 

anyone hav similar issue? or shd i just check zubat to avoid this problem?

**Comment by cyb0rg01** [comment]
Did you unchecked the box "Keep Pokemon if evolvable"?
