### ISSUE TITLE
Solved: pokemon caught/pokestops visited

### ISSUE THREAD

**Issue by downspath** [Ar1i/PokemonGo-Bot#2048]
Because of the new api the map only refreshes every 10 sek, people who use bots encounter even less pokemons if they are to fast

**Comment by ronnyouxia** [comment]
so you mean set speed below 10?

**Comment by gummyruler** [comment]
@downspath I set my speed to 120. Every stop gives me 2 - 4 catchable pokemon. After the loop is done it goes back to that idk what the problem is. More speed = more exp.

**Comment by burnSMACKER** [comment]
I would recommend setting it to 50km/h. If you guys want to hatch eggs it has to be 18km/h or below.

**Comment by ronnyouxia** [comment]
speed upper 10 not banned?

**Comment by hades2795** [comment]
i cant find pokestop and i cant change location plss help or u can give me full file bot sorry my english so bad
