### ISSUE TITLE
Everyone Pokémon is getting away?

### ISSUE THREAD

**Issue by Damantium** [Ar1i/PokemonGo-Bot#2049]
Every Pokémon I encounter gets away, even the CP12 Pidgeys. Everything else is working fine, and no my Pokémon inventory isn't full.

**Comment by akangnduz** [comment]
setting your pokeball >10

**Comment by Damantium** [comment]
What do you mean? I have pokéballs D:?

**Comment by Damantium** [comment]
https://gyazo.com/6758b36980f3b163095f99258180a8f5

**Comment by akangnduz** [comment]
screenshot setting item please

**Comment by Damantium** [comment]
https://gyazo.com/435007c58d875f7e74a8dca1d7339db3

**Comment by Defwang** [comment]
Happening to me too lots of pokemon r escaping. I changed location but it still hapens. I can farm pokestop though.

**Comment by Damantium** [comment]
Yeah Pokéstops are farming fine, just every Pokémon I encounter gets away.

**Comment by Defwang** [comment]
I've stopped the bot for 1 hour and it still happens.

**Comment by filoh** [comment]
same here, farm ok, pokemon getting away.

**Comment by Wastl1** [comment]
I have the same Problem. Every single one of them runs away

**Comment by dcg121288** [comment]
i have the same problem

if you setting Max normal Pokeballs to 0
try set Max normal Pokeballs to 50
i dont not why, but work for me

**Comment by Defwang** [comment]
I think it has to do with greatballs

**Comment by dcg121288** [comment]
@Damantium if your issuse is solved please close it

we need to help to @Ar1i

**Comment by Defwang** [comment]
I confirm set ur max pokeball to 50 it does work!

**Comment by filoh** [comment]
Here no, set max pokeball to 50 but many pokemons keep getting away, not every pokemon, but most of them are getting away.

**Comment by Damantium** [comment]
Nope setting to 50 hasn't helped everything still getting away

**Comment by KappaLord123** [comment]
Dumb question, are you softbanned? Just a thought!

**Comment by filoh** [comment]
Now it looks like the issue kind got away, most of pokemon are catching, rarely it runs away.

**Comment by dcg121288** [comment]
try to set slow move speed, maybe 20, and tell us

**Comment by Damantium** [comment]
my move speed is 5 anyway, nut it seems to have gone away on it's own. Strange eh! Thanks anyway guys, closing issue.
