### ISSUE TITLE
210XP...too perfect each catch

### ISSUE THREAD

**Issue by bullettt** [Ar1i/PokemonGo-Bot#2050]
Please if  possible randomise the catch perfection to great throw, excellent and some with curve or none curve ball. It seems too perfect the catch and might raise red flag should they filter through in future months. Thanks for your GREAT work!

**Comment by zzzz9999** [comment]
+1 Agree

**Comment by AgentBallermann** [comment]
Yep ...

**Comment by xhalfbakedguy** [comment]
especially now since you cant even get the bonus expierience over the newest version of the app

**Comment by zzzz9999** [comment]
@Ar1i please consider this: a kind of random throw catch:
30% perfect 
70% normal
Less XP but less suspicious too.

**Comment by burnSMACKER** [comment]
Maybe even let us set custom percentage rates
