### ISSUE TITLE
Not transferring!

### ISSUE THREAD

**Issue by silentassassonwp** [Ar1i/PokemonGo-Bot#2051]
My api wont transfer Pokemon. Yes i have keep if evolvable unchecked. Any ideas? thanks

**Comment by cyb0rg01** [comment]
Are you using the latest version? - Whats your transfer settings (CP and IV)? - Any screenshot to provide?

**Comment by akangnduz** [comment]
check auto transfer n max duplicate 1 or 2

**Comment by silentassassonwp** [comment]
ok i will post screenshots
![2](https://cloud.githubusercontent.com/assets/20892433/17486081/813cdff6-5d5d-11e6-9fe2-59aeae208b3d.png)
![pokemon](https://cloud.githubusercontent.com/assets/20892433/17486084/82eb9c7a-5d5d-11e6-94e3-992f59a2072d.png)
![pokemon](https://cloud.githubusercontent.com/assets/20892433/17486086/85896840-5d5d-11e6-9d2d-68b76b8fb6c6.png)

**Comment by akangnduz** [comment]
max duplicate 3 so if u catch more than 4 same pokemon it will transfer

**Comment by hozzerford** [comment]
Had to create an account to add to this. What I've found is that duplicate pokemon do not get transferred if the lowest rated pokemon has an IV rating of over 90. Let's say I have 3 Pidgeys all at 500 CP and I catch another at 50 CP but its IV rating is 90. It will not get transferred and niether will the others.

**Comment by silentassassonwp** [comment]
mmm ok thanks guys

**Comment by arjunvegda** [comment]
Same is with me. I am currently manually transferring pokemons. It transfers some pokemon for me but it just ignores rest of them.

This is how my config looks like
![image](https://cloud.githubusercontent.com/assets/14841132/17486377/935b818c-5d5e-11e6-9816-6c29cabd84c7.png)


and see how many drowzees I have

![image](https://cloud.githubusercontent.com/assets/14841132/17486403/ad843b08-5d5e-11e6-9368-43346664758e.png)

**Comment by hozzerford** [comment]
@arjunvegda can you sort by IV and post screenshots? I'm pretty sure if your weakest Pokemon has an IV of 90+ the program will not transfer any duplicates.

**Comment by akangnduz** [comment]
your IV 75%  any pokemon above 74% not count as duplicate below 74% count as duplicate max 3 then will transfer auto sry bad english

**Comment by hozzerford** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20909156/17486696/b2c386c0-5d89-11e6-956e-9a87e67743a7.png)
I do not have many duplicate pokemon. However, all my duplicates (that have IVs less than 90 and CP less than 1500) do not get transferred if there is a pokemon of a lower CP but an IV over 90. 

Theorectically I could have 50 Pidgeys of CP 400 and none of them would be transferred because there is a PIdgey with CP 20 that has an IV rating of 95. 

There should be a fix soon and an addon could maybe include an option to ignore CP values and just focus on IV.

**Comment by arjunvegda** [comment]
@hozzerford  There you go.. I got your point :D maybe thats the reason
![image](https://cloud.githubusercontent.com/assets/14841132/17487517/2b101b9c-5d63-11e6-95bc-2c98b6beba85.png)

**Comment by Ar1i** [comment]
#1940

**Comment by PokePro21** [comment]
@arjunvegda which location you are using so much drowzee :"3

**Comment by arjunvegda** [comment]
@PokePro21 That was too short

here is a long list of it

![image](https://cloud.githubusercontent.com/assets/14841132/17488139/f9c62646-5d65-11e6-9431-34c837706394.png)


and still add 25 more drowzees which i was unable to fit in the screen.
