### ISSUE TITLE
bot keeps crashing while its open

### ISSUE THREAD

**Issue by GoldenLucas** [Ar1i/PokemonGo-Bot#2055]

**Comment by GoldenLucas** [comment]
when i open the bot and start doing all the settings it will just crash for some reason. even if i get the bot running itll crash after a minute or so

**Comment by Raiderman1105** [comment]
with a grey long text?

**Comment by GoldenLucas** [comment]
yes and then it just closes

**Comment by Raiderman1105** [comment]
ive same problem i open 3 windows and 2/3 windows at same time gets the grey text and restart message then 2 other windows gets the message and this in a loop

**Comment by Ar1i** [comment]
Update should fix. If not open a new one.
