### ISSUE TITLE
Er findet keine Pokestops und ich kann auch nicht den Softban löschen

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#2056]
Ich habe auf einmal wieder das Problem, dass er keine Pokestops findet. Und es scheint ein Softban zu sein und den kann er so nicht lösen weil er ja keine Stop findet. Auch auf dem Handy zeigt er keine Pokestops an

**Comment by NidiKea** [comment]
Kann man da was machen?

**Comment by Raiderman1105** [comment]
Auf dem handy auch nicht o.o? Locker HardBann :dash:

**Comment by NidiKea** [comment]
Alle Accounts ....also habe die anderen beiden auch ausprobiert im Bot als der nicht ging und bei allen ist das so. Kann ich was tun?

**Comment by NidiKea** [comment]
Weil ohne Pokestops kann der nichts tun

**Comment by NidiKea** [comment]
Wir nutzen mehrere PCs in einem Haushalt, kann das auch daran liegen?

**Comment by Raiderman1105** [comment]
Laufen auf jedem PC bots?

**Comment by NidiKea** [comment]
ähm auf 2 en --meine Söhne machen sowas ja noch nicht, die haben den Pc auch selten mal an . Aber wir hatten jeder 2 laufen schäm (wollten es mal ausprobieren) ...war wohl etwas übermutig-hab auch nicht an die IP gedacht, ist ja dieselbe.

**Comment by Kidnub** [comment]
starte den unban einmal dann gehe zum nächsten pokestop ... dann schalte den bot aus ... starte den bot neu und als tip sobald du mehr als 3 bots laufen hast hast du auto softban .. daher nie mehr als 2 laufen lassen und ich kann nur sagen das der anti softban super arbeitet XD

**Comment by NidiKea** [comment]
Ja, er macht den Ban am nächsten Pokestop weg, aber er sagt ja er kann keine Stops finden im Umkreis in rot

**Comment by Raiderman1105** [comment]
Habe mir 2 Windows Server gemietet und kann so 6 bzw 9 Bots betreiben

**Comment by NidiKea** [comment]
Auch im Spiel ist alles ohne Pokémons oder Stops ohoh

**Comment by Kidnub** [comment]
hardban dann XD;( nicht schön

**Comment by NidiKea** [comment]
Ja wir spielen nur zum Spass, also 1 Bot ist eigentlich schon klasse genug...aber nun geht nix mehr, was mache ich da?

**Comment by Kidnub** [comment]
oder erstell mal nur einen neuen bot und teste dann den account nochmal ka sonst ist es permban kann sein habe noch nie einen bot nach dem botten angemacht .. daher kann ich dazu nix sagen ... ;(

**Comment by 1337Panther** [comment]
Wie oft noch maximal 3 Bots per IP !!!!

**Comment by 1337Panther** [comment]
IP bann da kannste noch 100 Accounts erstellen und es wird net funktionieren

**Comment by money1989** [comment]
ja 3 bots pro ip
hab das ne stunde lang getestet
ab dem 4ten wird nach 2minuten gesoftbannt

**Comment by Kidnub** [comment]
panther machmal ein snoralax XD und ja da hast du recht wenn die ip gebannt ist dann braucht er ne neue ip das bei vodavone nicht easy ist XD

**Comment by NidiKea** [comment]
Ja, hatten ja per PC 2 Bots, haben da nicht dran gedacht...aber ich kann nun wieder Stops im Spiel sehen nur nicht im Bot, der schreibt immer noch rote Zeilen mit keine Pokestops in 10000 m gefunden

**Comment by Raiderman1105** [comment]
2 bots pro PC wäre mit einem VPN oder Proxy möglich :)

**Comment by Kidnub** [comment]
hmm geht bei mir ohne proxy darf nur nicht die gleiche location sein XD 2bot np XD

**Comment by Raiderman1105** [comment]
gibts es tools mit denen Man einzelnen Prozessen einen Proxy zuweisen kann ?

**Comment by NidiKea** [comment]
soo nun geht es endlich wieder...also kann einer 2 nutzen und einer nut 1nen  ..wir waren nicht bei der gleichen Location

**Comment by Raiderman1105** [comment]
> hmm geht bei mir ohne proxy darf nur nicht die gleiche location sein XD 2bot np XD
dann wäre niantic schön blöd gleiche ip 2 standorte .. seems legit

**Comment by FoolYah** [comment]
Also bei mir funktioniert alles

Am 08.08.2016 18:27 schrieb "Raiderman1105" <notifications@github.com>:

**Comment by neocrypton** [comment]
@raiderman
Schon mal an virtuelle Maschinen gedacht?  Da kannst du bestimmt jeder vm nen Proxy zuweisen.

Wollt ihr anderen Mir sagen das ihr euch 3 mal mit dem bot im selben Account einloggt?

**Comment by eliteknight** [comment]
neue stadt benutzen...mit vielen pokestops...
