### ISSUE TITLE
[Feature Suggestion] Confirmation Box

### ISSUE THREAD

**Issue by cristianst** [Ar1i/PokemonGo-Bot#2058]
It would be nice a Confirmation Box after clicking "Transfer" in the Pokemon List, 
I just clicked the button by mistake and one pokemon is gone. 

Maybe a confirmation box for all the buttons that make something to the pokemon. And inform the user that the action cant be undone.  Just like in the real app.

**Comment by Waiiim** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ 
Dude, there, not here for suggestions

**Comment by arjunvegda** [comment]
#1916

**Comment by xJustx** [comment]
^
