### ISSUE TITLE
[HELP] How can I teleport from USA to Austria without getting a ban ?

### ISSUE THREAD

**Issue by 1337Panther** [Ar1i/PokemonGo-Bot#2059]
How can I teleport from USA to Austria without getting a ban ?

**Comment by hozzerford** [comment]
You can't. Have you tried doing it then hitting the 'Foce Unban' button? It makes sense that you should get a ban though. 

You can do it safely if you wait a couple of hours before teleporting back and forth.

This is not a bot issue though.
