### ISSUE TITLE
Not transferring duplicates. (known cause)

### ISSUE THREAD

**Issue by hozzerford** [Ar1i/PokemonGo-Bot#2060]
![untitled](https://cloud.githubusercontent.com/assets/20909156/17487363/69966f32-5d8c-11e6-9663-3c62552f3802.png)

For every duplicate that is not being transferred I have found the following:

A pokemon with a CP value under the 'Max. CP to transfer' will not be transferred if there is a pokemon with a smaller CP value which also has an IV rating equal to or above the 'Max. IV to transfer' (usually 90).

Pictures above - Red value pokemon will not be transferred due to black value pokemon.

**Comment by rickepk** [comment]
its ok. look you config. max duplicate 2. if cp biger.

**Comment by Emmi911** [comment]
For me, with the same settings it also saves like 30 ratatas and 20 pidgeys too..

**Comment by Ritzii** [comment]
This is likely due to the fact you have checked the box to "save Pokemon that can evolve", but not specifically told the bot to evolve that Pokemon, so it saves 1 for each 25 candy that you have, so you can evolve later. This is what happens for me, anyway.

**Comment by hozzerford** [comment]
@Ritzii Unfortunately it still doesn't solve the probelm, for me anyway. The duplicate Pokemon do not get transferred.

**Comment by BradleyFlorence** [comment]
Same issue here, the button that says "Auto Transfer Double Pokémon" is not at all working correctly

**Comment by tiny1980** [comment]
I agree with @Ritzii on this.

It looks like it is saving it for now until you have 4 more candies.

Try manually clearing a few (not drowzee's), make sure drowzee is set To Evolve, and see if it evolves them, and then it should transfer the Hypno it creates (if under 90% IV).

**Comment by eliteknight** [comment]
@rickepk  have right

**Comment by hozzerford** [comment]
@tiny1980 I get what you're saying but the point is I don't want the low IV Pokemon to be evolved. I want them transferred before they are even able to evolve so that I don't waste candies.

**Comment by hozzerford** [comment]
@tiny1980 Also, it didn't work because the new Hypno was a higher CP than the lowest one which had a 90+ IV rating.

**Comment by xRealMaks** [comment]
Uncheck "Keep Pokemons which can be evolved"
