### ISSUE TITLE
Everytime use a normal Pokeball

### ISSUE THREAD

**Issue by dcg121288** [Ar1i/PokemonGo-Bot#2062]
have or not have a normal pokeball, everytime get a message is using a ItemPokeball

**Comment by Waiiim** [comment]
Except if you have a good CP pokemon and then uses a GreatBall

**Comment by hozzerford** [comment]
Are you sure the bot is not collecting normals pokeballs from the stops and then using them for pokemon? 
Try setting the 'Max. Pokeballs' number to 0

**Comment by dcg121288** [comment]
yea, i set pokeballs to 0
when i do it, get a lot of "pokemon got away using ItemPokeball" but i dont know why beacause supposedly i dont have normal pokeball

and then i set pokeballs to 50 and not more "pokemon got away"

**Comment by PippoAe** [comment]
Set normal pokeballs to atleast 20.
The bot uses normal pokeballs for all pokemons under 499CP but doesn't check if you actually have pokeballs left wich results in "the pokemon got away" message.
