### ISSUE TITLE
[ Feature Suggestion ] Additionial Waypoint route.

### ISSUE THREAD

**Issue by Affenasmo** [Ar1i/PokemonGo-Bot#2063]
Dont know why...but all the pokes i get a fucking rats or the flying fucking rats...all day Long.

If i play manually via Bluestack app player...ill get Dratinis etc etc.

Maybe it is posible to add an option to mark specific locations, like a route out of Waypoints.

Thanks in advance and very nice work this weekend Ar1i

**Comment by hozzerford** [comment]
Not an issue. Please close.

Use: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Affenasmo** [comment]
...shit.....you are right mate.....my fault
