### ISSUE TITLE
Almost all Pokemon got away

### ISSUE THREAD

**Issue by thepapabear** [Ar1i/PokemonGo-Bot#2066]
Even when it says probability 100% it still gets away and it always uses a pokeball even if i set it to 0
![pokemon bot issue](https://cloud.githubusercontent.com/assets/20909888/17488274/36360c1c-5dcb-11e6-926a-a50d3b3b8ea3.jpg)

**Comment by momo0206** [comment]
log into your acc on the mobile and delte your pokeballs, the but use the remaining pokeballs in your bag

**Comment by Azantys** [comment]
Try login from your device and then start the bot again

**Comment by dcg121288** [comment]
i have the same problem

try set Max normal Pokeballs to 50
i dont not why, but work for me

**Comment by thepapabear** [comment]
I already tried deleting the pokeballs but it still happens

i'll try your method where i set to 50 in a while

**Comment by cyb0rg01** [comment]
There is a change to the catching algorithm. Low CP Pokemons are getting caught with normal Pokeballs, higher CP Pokemons are getting caught with Superballs and above 1000 CP the bot uses Ultraballs to catch.

**Comment by sunit1998** [comment]
there r no superballs in the game

**Comment by dcg121288** [comment]
@thepapabear do you solved the problem?

**Comment by cyb0rg01** [comment]
Yeah, I know. Just misstyped ... have a little lack of sleep. I mean "Greatballs" instead of "Superballs". I guess, "Superball" is the German translation for it. ;P

**Comment by thepapabear** [comment]
I think I figured it out why it always got away.
Since I deleted all my regular pokemon ball and set it to 0, so the bot recycles the pokemon ball immediately but when it finds low cp pokemon, it is programed to use a pokemon ball but since I don't have any, the pokemon gets away. I realized this when it only catches pokemon when it uses great ball or ultra balls.

**Comment by Azantys** [comment]
Sunit1998; yes they are in game, they're the same as greatballs in other translations (like spanish or German)

**Comment by thepapabear** [comment]
I set the pokemon ball back to 20 so it has a value so it can catch low cp pokemon again for xp.

**Comment by thepapabear** [comment]
Ever since I did the problem got solved.

**Comment by Azantys** [comment]
@thepapabear always keep like 5 or 10 pokeballs; the program will farm them and recycle the rest

**Comment by thepapabear** [comment]
@dcg121288 Yes I solved the problem, read my other comments.

**Comment by dcg121288** [comment]
ok, please close the issuse

we need to help to @Ar1i
