### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Emmi911** [Ar1i/PokemonGo-Bot#2067]
Add Farm only mode. Doesnt visit all pokestops only when u run out of pokeballs. Farms all pokemons.

Add proxy support maybe to avoid those ip bans.

**Comment by arjunvegda** [comment]
#1916

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
