### ISSUE TITLE
Not an issue but would just appreciate help :)

### ISSUE THREAD

**Issue by bluntt420** [Ar1i/PokemonGo-Bot#2069]
Could someone please tell me some co ordinates where i can make maximum use of the bot?

**Comment by arjunvegda** [comment]
here - #1916

**Comment by hades2795** [comment]
plss can give me new version bot link i want download

**Comment by arjunvegda** [comment]
@hades2795 - https://github.com/Ar1i/PokemonGo-Bot.git

**Comment by dcg121288** [comment]
San Francisco:
a lot of pokestop and some charmander: 37.791002, -122.388905
a lot of pokestop and squirtle 37.807195, -122.432028
a lot of pokestop and bulbasaur 37.800861, -122.467896

**Comment by hades2795** [comment]
but still cant find pokestop 5000! sir

**Comment by peptidoglikan** [comment]
delete your file and re-extract the files. then try again.

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
