### ISSUE TITLE
Error Rocket API

### ISSUE THREAD

**Issue by Zwenkek** [Ar1i/PokemonGo-Bot#207]
[15:01:28] Starting Execute on login server: Google
[15:01:29] Error: Pokemon Go Rocket API
[15:01:29] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   bei PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\user1\Desktop\Kmo\PokemonGo-Bot-master\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:Zeile 34.
   bei PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\user1\Desktop\Kmo\PokemonGo-Bot-master\PokemonGo.RocketAPI\Client.cs:Zeile 128.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\user1\Desktop\Kmo\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 50.
[15:01:29] Trying to Restart.
[15:01:29] Restarting in 10 Seconds.

This is waht comes up with the NEW version. I reloaded it like 5 times.
i dont know waht to do. The old version still works fine tho

**Comment by justchil** [comment]
Wrong password?

I'm not having troubles even with 2-step auth.

**Comment by qlimax89** [comment]
i have the same problem but my password is correct 
so i dont underdstand

**Comment by Zwenkek** [comment]
Yes i just tested my PW is working.
Also tested it on NOX and i can login...

**Comment by Zwenkek** [comment]
I still get the Same Error

**Comment by Karimoto** [comment]
same problem here

**Comment by Zwenkek** [comment]
This is what i get on my other old Version acc. 
[15:25:45] We got the API Url: pgorelease.nianticlabs.com/plfe/38
[15:32:30] We got the API Url: pgorelease.nianticlabs.com/plfe/535
[15:44:07] We got the API Url: pgorelease.nianticlabs.com/plfe/345
[15:44:43] We got the API Url: pgorelease.nianticlabs.com/plfe/345
[15:47:06] We got the API Url: pgorelease.nianticlabs.com/plfe/345
i dont know if it helpes you.. But this is another thing i often get.

**Comment by Zwenkek** [comment]
OKay sry for the First one THE google Login server are Offline thats why i gues...

**Comment by 13XxM1CHA3lxX37** [comment]
PokemonGo.RocketAPI.Exceptions.GoogleException: **BadAuthentication**
This usually means wrong password/email/nick or Server down,
