### ISSUE TITLE
New Error: Error at Request PostProtoPayload ReleasePokemonResponse retrying 1/3

### ISSUE THREAD

**Issue by fa5584** [Ar1i/PokemonGo-Bot#2071]
Hi,

i get this error

[19:19:11] Error at Request PostProtoPayload ReleasePokemonResponse retrying 1/3

Thanks

**Comment by cyb0rg01** [comment]
Are you running the latest version? - I guess this should be fixed a couple of minutes ago.

**Comment by fa5584** [comment]
I have the version 19:05

**Comment by fa5584** [comment]
ok solved
