### ISSUE TITLE
We can't find any pokestops

### ISSUE THREAD

**Issue by mertcemq** [Ar1i/PokemonGo-Bot#2072]
It is always saying this 
![image](https://cloud.githubusercontent.com/assets/20794628/17489313/13a0097a-5da6-11e6-973c-44b4a43619d4.png)

**Comment by Dextiz** [comment]
Don't run more than 3 accounts, you are probably IP softbanned for 15-30 minutes.

**Comment by mertcemq** [comment]
Thanks
