### ISSUE TITLE
PokeBot Not Transferring Pokemon

### ISSUE THREAD

**Issue by BradleyFlorence** [Ar1i/PokemonGo-Bot#2073]
In the Item Settings I have my Pokémon set to transfer exactly what I want and need to go away, I have it set so that I can only have two of the best Pokemon of that type or they should be transferred if I have to many, this is not the case, i'll have about 9 Pidgeys or Rattatas and they will not at all transfer and just stay there and not only keep two of them, my settings as follow:

<img width="410" alt="capture" src="https://cloud.githubusercontent.com/assets/11214309/17489373/9e4d6486-5d6b-11e6-81f1-167e77bda04a.PNG">

This issue makes it to where I can no longer gain any more pokemon after my bag fills and it makes it impossible to gain more XP.

**Comment by peptidoglikan** [comment]
+1

**Comment by BlackHatching** [comment]
tick auto transfer double pokemons

**Comment by BradleyFlorence** [comment]
@BlackHatching I had that on earlier today and it still had the same problem and I decided to turn it off hoping that would help the problem but the button doesn't seem to have any effect on anything.

**Comment by hozzerford** [comment]
#2060

**Comment by BradleyFlorence** [comment]
@Ar1i Known Issue here that needs Fixing.

**Comment by urangotango** [comment]
@BradleyFlorence why you have max IV at 0 ?? if is an important stat of your pokemons keep it up at example on 80% or 90% an select transfer doubles and you will see it will work perfect try it out and let me know.

**Comment by eliteknight** [comment]
0% IV...he never transfer a pokemon...

**Comment by urangotango** [comment]
@eliteknight y thats why pokemons under 0 dosnt exist ;)

**Comment by BradleyFlorence** [comment]
@urangotango @eliteknight Actually I had all the settings done correctly at the IV was at 90% I was just messing around with some of the settings today to see if maybe I could fix the issue.

**Comment by eliteknight** [comment]
he keep all over 0%

**Comment by BradleyFlorence** [comment]
I currently have my IV running back at 90% and I am still having the issue, it still wants to keep the double Pokemon even if I have it checked.

**Comment by urangotango** [comment]
@BradleyFlorence hmmm i use this version of bot since the API update and i transfere all perfectly witouth any mis...
do you have TS3 ?? maybee we can solve this issue i think it is just some setup error

**Comment by eliteknight** [comment]
Auto transfer double Pokemons = no transfer
keeps evolving pokemons = no transfer if it selected

**Comment by BradleyFlorence** [comment]
@urangotango I'll eventually get it. It's just I keep running into the same issue of it keeping double Pokemon.

**Comment by cyberwolf888** [comment]
uncheck "keeps evolving pokemons" in main tab

**Comment by BradleyFlorence** [comment]
@cyberworld888 Thanks! That actually fixed my problem! The tab said "Keep Pokémon if they Can be Evolved" And that fixed it right up!!!

**Comment by eliteknight** [comment]
you read my post?...

**Comment by BradleyFlorence** [comment]
@eliteknight You too! Thanks for the Help!
