### ISSUE TITLE
Start/stop button

### ISSUE THREAD

**Issue by QustomiZed** [Ar1i/PokemonGo-Bot#2074]
Can we get a start/pauze/stop button ? I have to close my bot when i have coords for pokesniper.

**Comment by Ar1i** [comment]
quick tip to stop the bot, just select in the console something and it holds on

**Comment by urangotango** [comment]
@Ar1i and what is if we wanna change coords ?? can we do that tough the console ? with any command i mean.

**Comment by Ar1i** [comment]
atm not
