### ISSUE TITLE
Exception: System.NullReferenceExeception

### ISSUE THREAD

**Issue by favtim96** [Ar1i/PokemonGo-Bot#2075]
Misstake;
![fehler](https://cloud.githubusercontent.com/assets/20910729/17489526/abc47c2a-5d9e-11e6-9bf2-05326b20c2f6.png)
However, I have noticed , when you hook the non- clicking the update of Pokemons . Does it run without problems .

**Comment by BradleyFlorence** [comment]
Ar1i Just released a Fix for this, update to the Newest Build.

**Comment by cyb0rg01** [comment]
Are you running the latest version? - There is an update about around 20 minutes ago which fixes that.

**Comment by BradleyFlorence** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only

**Comment by favtim96** [comment]
This is the new Update.

**Comment by favtim96** [comment]
Just wanted people help where it does not work

**Comment by BradleyFlorence** [comment]
When did you update it?

**Comment by favtim96** [comment]
5 minutes ago

**Comment by Ar1i** [comment]
This cant be the newest update. Cause the red message doesnt exist anymore.
