### ISSUE TITLE
New way to bypass the new softban?

### ISSUE THREAD

**Issue by eden764** [Ar1i/PokemonGo-Bot#2077]
guys do you think there is away to bypass the new softban (ip ban)?

**Comment by QustomiZed** [comment]
IP ban u can use a proxy server....

**Comment by 13XxM1CHA3lxX37** [comment]
Yes.
VPN, Reconnect, Proxy

**Comment by QustomiZed** [comment]
With a IP ban, your account is gone.

**Comment by Biscuit090** [comment]
Actually the "40 pokestop spin" method still works, I tried it just now on NOX and I got unbanned lol

**Comment by QustomiZed** [comment]
thats only for a softban
