### ISSUE TITLE
some pokemon still run away ver. 1.0.8.0

### ISSUE THREAD

**Issue by freetogameplay** [Ar1i/PokemonGo-Bot#2079]
still have run away sir ![9](https://cloud.githubusercontent.com/assets/11550302/17489818/0993b0a2-5dca-11e6-854a-da1b8b33140f.png)

**Comment by Waiiim** [comment]
Well that's life lol, nothing the bot can do

**Comment by freetogameplay** [comment]
just tell ar1i

**Comment by Ar1i** [comment]
Cause you got a fcking softban...

**Comment by Ar1i** [comment]
And you cant catch every pokemon its normal that sometimes they get away

**Comment by 120607** [comment]
I could catch the first 3 then got softban again. Any safe settings?

**Comment by freetogameplay** [comment]
I 've tried without using your software is the same result like that

**Comment by eliteknight** [comment]
softban

**Comment by filoh** [comment]
I'm getting this too, getting soft ban, Any new setting that I have to change?
i'm using 50 km and 5000 radios.

**Comment by freetogameplay** [comment]
@eliteknight of couse, i think 40% got away
