### ISSUE TITLE
[Update] Updater link

### ISSUE THREAD

**Issue by niikooartz** [Ar1i/PokemonGo-Bot#208]
ist mir grad so aufgefallen :D am besten ist es eigtl den updater link direkt auf den build only ordner zu verlinken :D 

`Process.Start("https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only");`

**Comment by Ar1i** [comment]
Jaein, das soll auf die Haupt-Github Seite leiten.
