### ISSUE TITLE
cause of softban ? 

### ISSUE THREAD

**Issue by themagiciandoz** [Ar1i/PokemonGo-Bot#2080]
i've changed my location from LA to NY within an hour this morning, and since 1 hour now i've been facing this problem : pokemons getting away 

is my sudden change of location the cause of my softban ? or is it a config related issue ?

**Comment by OfficialMorise** [comment]
yes, softban :)

**Comment by NagaCS** [comment]
Yes, anytime you teleport far away @themagiciandoz you will receive a soft ban

**Comment by Waiiim** [comment]
It's because you teleported and 1h is too short so yes you got softbanned
Try to use the "Force Unban" button on your list

**Comment by freetogameplay** [comment]
try to delete lastcoords

**Comment by sylva91** [comment]
is there a time/distance limit i should respect not to be softbanned ?
