### ISSUE TITLE
Pokeball Issue - again!

### ISSUE THREAD

**Issue by Excruciator23** [Ar1i/PokemonGo-Bot#2082]
@Ar1i 
Hey - before the API was changed everything was fine but now I am expieriencing the same issue - I set the count for pokeballs in my inventory to 0, but the bot continues to try to catch pokemon with them - which - of course - fails all the time due to my fairly high player level !

Could you fix that again ?
Last time I made the suggestion you could sharpen the mechanism throwning away unwanted items so that there are never pokeballs even available for the bot to throw or something ..

please - I already lost probably hundreds of Pokemon ..

**Comment by Biscuit090** [comment]
....then set it to something higher.

**Comment by Excruciator23** [comment]
Oh yeah - and I read another issue concerning that they always get away when setting the item counter to 0 for pokeballs - well I tried also 10, 20 and some other counts - then he continues to use them - of course.

**Comment by Biscuit090** [comment]
Set it to at least 20 pokeballs. It works for me at about 20 or higher.
