### ISSUE TITLE
Pokemon no Catching

### ISSUE THREAD

**Issue by bloodmoonx2** [Ar1i/PokemonGo-Bot#2083]
Hello i have a problem the bot settings is normaly.
but the bot not catching pokemons show this .. :/

![why](https://cloud.githubusercontent.com/assets/20911039/17489955/e46e2556-5da0-11e6-8302-5289dc97cf42.PNG)

when you help me its awsome :) 
sorry my english is not good ...

**Comment by Damantium** [comment]
Set Pokéballs to more than 0 and slow your move speed down!

**Comment by Biscuit090** [comment]
That just means the pokemon keeps escaping from your pokeball. Or you don't have any pokeballs?

**Comment by BradleyFlorence** [comment]
Or it means your Banned according to Niantic.

**Comment by bloodmoonx2** [comment]
no im not banned i have fix this problem to the settings with 20 pokeballs :) then it works :) ok i try with walking speed slow down ^^ :)

**Comment by freetogameplay** [comment]
i think the new version of pokemon go is difficult to catch now, maybe it issue from niantic

**Comment by xRealMaks** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
