### ISSUE TITLE
Eggs

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#2084]
The egg incubation on the bot still doesn't work, at all.

**Comment by Biscuit090** [comment]
Then do it manually. It ain't perfect boi

**Comment by urangotango** [comment]
you can do it manualy just log on nox player on your account near the bot location put the exs in the incubator and log out on nox GG

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
