### ISSUE TITLE
Inventory Space

### ISSUE THREAD

**Issue by Damantium** [Ar1i/PokemonGo-Bot#2085]
I have 450 inventory space but the bot only goes up to 350 since new API

**Comment by Biscuit090** [comment]
download newest bot, some things were updated recently within the last hour

**Comment by KnewNothing** [comment]
Change the options in Items and also THERE ARE NO MASTERBALLS so even if it says "450" and you have masterball at 100. Then bot sees your item cap at 350. Set masterball to 0 and divide the 100 between items you do want

**Comment by testo4life** [comment]
doenst matter WHAT u have in innvetory it is showing the WRONG stats !
have selected 

item setting
30
50
70
20
0
20
20
70
0
20
20
 have aprox 200 items stil showing 443 !

**Comment by Niubbo** [comment]
yes this is a kind of error, hoping ar1i will fix it soon with the auto egg evolve
