### ISSUE TITLE
Error catching Pokemon

### ISSUE THREAD

**Issue by PokemonGoer** [Ar1i/PokemonGo-Bot#2088]
"Error catching Pokemon: PokemonInventoryFull"

Anyone else have this issue?

**Comment by BradleyFlorence** [comment]
It means you have to many pokemon and if you have to transfer them or have it set to do an Automatic transfer.

**Comment by freetogameplay** [comment]
u can manual transfer from GUI

**Comment by eliteknight** [comment]
clear your inventary...

**Comment by BradleyFlorence** [comment]
^Yes, delete every single Pokémon and you will be fine.

**Comment by PokemonGoer** [comment]
I set it to auto transfer but its not working
