### ISSUE TITLE
auto evolve

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#2089]
does the bot not auto evolve the pokemon, even if i select it in settings?

**Comment by BradleyFlorence** [comment]
It does, just have to have it setup correctly.

**Comment by Tr1n0va** [comment]
how i do it correctly

its just a check box

**Comment by PokemonGoer** [comment]
I'm having the same issue right now, I have them checked but they aren't evolving

**Comment by eliteknight** [comment]
you need essences to evolving...

**Comment by Tr1n0va** [comment]
the bot also says "(49 Evolvable)" but dont do it

**Comment by eliteknight** [comment]
Which you selected?

**Comment by Tr1n0va** [comment]
stop a moment, hav i also check the pokemon to evolve in pokemon tab???

**Comment by Tr1n0va** [comment]
dam... now it works

Sorry
