### ISSUE TITLE
Loop code?

### ISSUE THREAD

**Issue by vietp03** [Ar1i/PokemonGo-Bot#2090]
Every time one pokemon ran away, it seem to run into a infinite loops and causing me to keep going on a pokemon that might have disappear. I always end up losing razzyberry and pokeball cause of it.  I let it ran for five min and stop when it caught a different pokemon but still go for the charmander one. 
![screenshot 4](https://cloud.githubusercontent.com/assets/20911104/17490259/fa061558-5d6f-11e6-9a26-92f2cf3cbe04.png)

**Comment by hozzerford** [comment]
Does hitting the 'Force Unban' do a temporary fix?

**Comment by eliteknight** [comment]
softban...use force unban

**Comment by BradleyFlorence** [comment]
Since when was there a Force Unban feature ?

**Comment by hozzerford** [comment]
@BradleyFlorence It's on the Pokemon List window. Only been added recently I believe.

**Comment by xhalfbakedguy** [comment]
@BradleyFlorence its not in 1.0.7.1 as far as i can tell. im using this version because im afraid if i update some shit gets fked up

**Comment by eliteknight** [comment]
left picture upper button on right side...

**Comment by Ar1i** [comment]
@xhalfbakedguy you should update, if you want to stay safe.. added some big security updates

**Comment by vietp03** [comment]
it not a soft ban cause i caught a nidorian during those loop and still walking to pokestop and collecting item

**Comment by gummyruler** [comment]
If you have no pokeballs it will shred all your berries. So make sure you have pokeballs.
