### ISSUE TITLE
bug: start walk from default location is not working well now.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#2093]
It seems that always start in the selected point instead of last saved point on last session.

**Comment by shahroozal** [comment]
Me too. I keep getting soft banned for that.

**Comment by swtrpeter** [comment]
+1

**Comment by xJustx** [comment]
It's not a bug. The lastcords-file was deleted.
But it will be added soon again :p 
Please be patient.
