### ISSUE TITLE
Brazil language? Really?

### ISSUE THREAD

**Issue by spotterd** [Ar1i/PokemonGo-Bot#2097]
Why is there a flag of Brazil on the translation tab? Why not a flag of Portugal ?

**Comment by eliteknight** [comment]
send your translation and you got it...

**Comment by PippoAe** [comment]
Ar1i decided to honor brazil because of the olympia.
U mad now?

**Comment by Ar1i** [comment]
^ hahahahaha

**Comment by spotterd** [comment]
@eliteknight you know there is no such thing as a brazilian language right?

**Comment by xuban** [comment]
Dont waste time send translation, you dont go it.

**Comment by HBraga** [comment]
lol brazilian is not a language...
Its always Portuguese even if Pt-Br which is Portuguese-Brazilian...
(im  portuguese btw...)
So yeah there should be a portuguese flag and not a brasilian one lol!

**Comment by spotterd** [comment]
Some people are uneducated... wow.

**Comment by xuban** [comment]
few days ago we sent the Spanish correction well written and without Latin words and pull have closed. Therefore I do not recommend you not to lose much time on this. I use the English version reads better.

**Comment by spotterd** [comment]
@Xuban Please seek a mental hospital, You do not sound like a functioning human being.

**Comment by eliteknight** [comment]
@spotterd 
read and understand....

**Comment by spotterd** [comment]
@eliteknight Nah man, no man will ever understand this sentence "few days ago we sent the Spanish correction well written and without Latin words and pull have closed. Therefore I do not recommend you not to lose much time on this. I use the English version reads better."

**Comment by xuban** [comment]
Thanks for the insults.
My English is not very good and I use translator. I guess not correctly expressed, but that insult ... anyway, I'll shut up. You have enough whiskers with the Portuguese.

**Comment by HBraga** [comment]
Spotterd chill mate! Leave the kid alone lol..

**Comment by m-a-r-c-e-l-o** [comment]
@spotterd cause this translation is for brazilian portuguese. There are more people who speak Brazilian Portuguese than Portugal. Why did u not send your translation before? Don't cry, just accept. Kiss
