### ISSUE TITLE
auto evolve

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#2098]
if ilet the bot auto evolve all pokemon, can i get the third step of evolution?
because i think it ever evolve the basic pokemon to second evolution, and never get the third of caus befor it gets enough candy, it evolve another basic pokemon first....

**Comment by natsukuro90** [comment]
right ;)

**Comment by eliteknight** [comment]
selected manually works well...

**Comment by Tr1n0va** [comment]
ok ;-)
