### ISSUE TITLE
Just updated the bot to the version you released 11mins ago (No Pokemon Icons)

### ISSUE THREAD

**Issue by Inforcer25** [Ar1i/PokemonGo-Bot#2099]
After updating this to the version you released about 11mins ago none of the icons work in the pokemon list
![srto9vv](https://cloud.githubusercontent.com/assets/16230645/17491124/87b52ca0-5da6-11e6-8515-fe2ec9da20e8.png)

**Comment by silentassassonwp** [comment]
same

**Comment by Tr1n0va** [comment]
the bo even dont start for me

**Comment by KnewNothing** [comment]
The newest doesnt work for me

**Comment by shahroozal** [comment]
And also only gray text...
![untitled2](https://cloud.githubusercontent.com/assets/20831147/17491225/fbdef41c-5da6-11e6-85d4-adb87d4bafad.png)

**Comment by DiTechRacer** [comment]
![1111](https://cloud.githubusercontent.com/assets/14916371/17491236/06ca1d0c-5da7-11e6-8c16-618410331736.PNG)

SAME!

**Comment by madeinyashiro** [comment]
Same here

**Comment by BluCone** [comment]
same here
The older version worked for me great than the update came out and nothing is wroking

**Comment by iZ4iN** [comment]
Same here. But i think the Problems are on the Server

**Comment by Inforcer25** [comment]
@shahroozal Restart your computer. That will fix your issue with file in use

**Comment by shahroozal** [comment]
@Inforcer25 I already deleted the file multiple times. The robot keeps leaving the file open.

**Comment by Inforcer25** [comment]
@shahroozal I didn't say delete it. Just restart your computer and it will be fixed. I had the same problem

**Comment by shahroozal** [comment]
@Inforcer25 I know you didn't :-) The gray Exceptions are the main problem though which I hope are related to the servers.

**Comment by eLDeMe** [comment]
@shahroozal #2110

**Comment by jmo93** [comment]
me too, no pics

**Comment by DrHPain** [comment]
restart the pc, did it for me

**Comment by Inforcer25** [comment]
I figured out how to fix the pokemon icons. Just stop the bot and remove the pokemon list in the Config folder then start the bot.

**Comment by jmo93** [comment]
yes , but after evolve a pokemon the pics remove again

**Comment by Inforcer25** [comment]
@jmo93 Yeah i also saw that. I believe it is something to do with the retrieval of the icons not and it is not  removing the old icons #2129
