### ISSUE TITLE
Stop Problem

### ISSUE THREAD

**Issue by esatarslan** [Ar1i/PokemonGo-Bot#210]
10-15 minutes later bot is stopping. Not crashing, doing nothing.

**Comment by VisualBoyAdv** [comment]
True, just went afk and found it stopped around 25m~ ago. No message so i restarted it

**Comment by Whoopass** [comment]
same. got the newest version

**Comment by duyphuc1610** [comment]
same. it auto for 15-20 mins then stop without reason. I have to start again :(

**Comment by amarinediary** [comment]
Bug was related to the slowdow fnc. it's been corrected in the new patch i think

**Comment by duyphuc1610** [comment]
Yeah, I hope so :)

**Comment by Whoopass** [comment]
Its not. Still stops after 10-20 minutes.

**Comment by VisualBoyAdv** [comment]
![image](https://cloud.githubusercontent.com/assets/20724656/17251602/7879b51c-5577-11e6-9e71-f6a1004619f7.png)
It's 10:31 AM for me atm, i started at 9:45 AM. The bot stopped working 15m ago

**Comment by New123WeN** [comment]
The same problem. The bot stopped after about 30 minutes. I used the newest version that does not help.

**Comment by Ar1i** [comment]
Uhm will take a look at it.. got probably an idea on how to fix that.

**Comment by Ar1i** [comment]
Should be fixed in the Update. If not open a new Issue, with a Screenshot please.
