### ISSUE TITLE
It is possible?

### ISSUE THREAD

**Issue by eliteknight** [Ar1i/PokemonGo-Bot#2100]
hey arti,

it is possible to combine this app with a radar tool like pokemonradargo to farm specific pokemons?

**Comment by D3VASTATlON** [comment]
if so could we add functionality to locate the pokemon desired off a table then see if its possible to walk to that pokemon given the desired speed and also catch it before it disappears?

**Comment by eliteknight** [comment]
Yes, but currently knows the app no spawn points and spawn times.
This would retrieve them from a radar

**Comment by xJustx** [comment]
If you implement this, yes :p
