### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by TTorreS96** [Ar1i/PokemonGo-Bot#2101]
http://prntscr.com/c36yon

**Comment by micreu** [comment]
same for me
Win 10 64bit, run as admin

**Comment by robinsipos** [comment]
same here

**Comment by Animehq** [comment]
+1

**Comment by arjunvegda** [comment]
![image](https://cloud.githubusercontent.com/assets/14841132/17491249/cc02388a-5d74-11e6-8e93-48ee353c1272.png)

**Comment by Roli0116** [comment]
same here

**Comment by ineedtostudy** [comment]
Run as admin, running it as admin worked for me

**Comment by vallerydelexy** [comment]
same here.

**Comment by jackg0h** [comment]
+1

**Comment by joelx3** [comment]
fucking download the update..

**Comment by Tr1n0va** [comment]
+1

**Comment by robinsipos** [comment]
Run as admin , solved

**Comment by arjunvegda** [comment]
@joelx3  Its already a new version

**Comment by HeIIoWorld** [comment]
@joelx3 it happens after the update

**Comment by DiTechRacer** [comment]
![1111](https://cloud.githubusercontent.com/assets/14916371/17491293/45b1187c-5da7-11e6-84cf-a5abc4bde1f6.PNG)

**Comment by gummyruler** [comment]
Same problem

**Comment by DiTechRacer** [comment]
With Latest Build - 08.08 20.15.rar

**Comment by vallerydelexy** [comment]
**Run As Administrator**

**Comment by stormlolz** [comment]
same

**Comment by eliteknight** [comment]
delet your folders...config, sprites and translation

**Comment by Kuzmarin** [comment]
yep 1+

**Comment by ineedtostudy** [comment]
RUN AS ADMIN

**Comment by ineedtostudy** [comment]
I RAN IT AS ADMIN AND IT WORKED

**Comment by arjunvegda** [comment]
SAME THING @vallerydelexy @robinsipos @ineedtostudy

**Comment by HeIIoWorld** [comment]
running it as admin does not work for me

**Comment by joelx3** [comment]
Administrator dont works!

**Comment by micreu** [comment]
run as admin dont work!!!!!!!!

**Comment by eliteknight** [comment]
read my post...

**Comment by arjunvegda** [comment]
Running as Admin got rid of the CSV error but gives this instead

![image](https://cloud.githubusercontent.com/assets/14841132/17491352/4d2f4ede-5d75-11e6-9713-39923d20cc3d.png)

**Comment by Abbasoo** [comment]
Update AND Run as ADMIN || https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2008.08%2020.15.rar

**Comment by Pyroman2300** [comment]
Running as admin did not fix the problem at hand.
Neither than deleting and re-installing.

**Comment by Pyroman2300** [comment]
@abbasoo, they did that...

**Comment by gregory-yet** [comment]
## Run as admin and re install did the trick.

**Comment by vallerydelexy** [comment]
Try again, completely exit the bot
and the **RUN AS ADMIN** again

works for me

**Comment by micreu** [comment]
clean install , run as admin does not work

**Comment by HeIIoWorld** [comment]
does someone else gets a pokemon list error too?

**Comment by arjunvegda** [comment]
@HeIIoWorld I do

**Comment by TTorreS96** [comment]
http://prntscr.com/c3730j
run admin and dont work on last build

**Comment by Abbasoo** [comment]
@Pyroman2300 I updated it and I didn't run it as admin and it's WORKING FINE ! 
I have this error in the previous build. NOW IT'S GONE.

**Comment by Pyroman2300** [comment]
@Abbasoo Well thats nice and all, I ran as admin and re-installed all the files and it still doesn't work.

**Comment by micreu** [comment]
rolling back the update didnt fix the problem, maybe niantic servers down again

**Comment by Pyroman2300** [comment]
@micreu Nothing to do with servers: http://ispokemongodownornot.com/

**Comment by TTorreS96** [comment]
update build pls

**Comment by icewick** [comment]
hey people ....


i tryed the new version and have the same problem ... run as admin redownloaded all after deleting ... but dont worked ... the version before works fine for me ... catches pokestops and pokemon ... no roblem

**Comment by micreu** [comment]
@Pyroman2300 i doubt it http://www.mmoserverstatus.com/pokemon_go

**Comment by Ar1i** [comment]
#2110
