### ISSUE TITLE
Error  - last update 

### ISSUE THREAD

**Issue by FerMedina86** [Ar1i/PokemonGo-Bot#2102]
![error-bot](https://cloud.githubusercontent.com/assets/20867022/17491312/b3447306-5d6c-11e6-8e5e-ddc93cb03d3d.jpg)

**Comment by gregory-yet** [comment]
Same here

**Comment by Walus32** [comment]
Yeah same :) at all ver .

**Comment by jeremie152** [comment]
yeah me too

**Comment by HBraga** [comment]
Same...

**Comment by eden764** [comment]
same :(

**Comment by Toshiro-Hitsugaya** [comment]
same

**Comment by SpectraOne** [comment]
:-( same

**Comment by gregory-yet** [comment]
## Run as admin and re install did the trick for me.

**Comment by jeremie152** [comment]
problem with list info player and all pokemon . csv only with account google

**Comment by xuban** [comment]
Run as admin only work with pokemon list. 
The problem of reconnect still persist.

**Comment by filoh** [comment]
How did you re install?
I only download the rar file and run the exe. Not installing anything.

**Comment by jeremie152** [comment]
y run as admin dont help me too

**Comment by jeremie152** [comment]
i have try delete info player in config but problem persist

**Comment by cyb0rg01** [comment]
I can't confirm any of these helps. I also restarted my entire system; even set my virtual machine back to an older state (clean registry and so on). Not running.

**Comment by marcop888** [comment]
yeah me too

**Comment by joelx3** [comment]
look at my fix

**Comment by jeremie152** [comment]
dont worry just be patient for new update ar1i roxx for update fast ^^

**Comment by Pyroman2300** [comment]
@joelx3 Can you post a link to it?

**Comment by cyb0rg01** [comment]
@Pyroman2300 He means this: https://github.com/Ar1i/PokemonGo-Bot/issues/2107

**Comment by DiTechRacer** [comment]
but it dosent work...

**Comment by instinctftw** [comment]
I'm just gonna sit my ass down and wait lol

**Comment by jeremie152** [comment]
no worry just wait new update or log on with ptc and work again^^

**Comment by HeIIoWorld** [comment]
@jeremie152 but he said on twitter this would be the last update for today. I hope he saw the errors before sleep

**Comment by Ar1i** [comment]
#2110

**Comment by qyxii69** [comment]
Necro bot and pokebuddy's up.. google auth in app ? XD

**Comment by jeremie152** [comment]
np run an admin and wait its work sometime

**Comment by jeremie152** [comment]
not choice  for the moment

**Comment by jeremie152** [comment]
haha he is here yeahhhh update coming

**Comment by Toshiro-Hitsugaya** [comment]
Closing application and restarting works for me
