### ISSUE TITLE
I have a problem with the new version

### ISSUE THREAD

**Issue by MadD0g25** [Ar1i/PokemonGo-Bot#2103]
Hello everyone,

I have a little problem with the new version of the robot

http://www.zupimages.net/up/16/32/o49p.png

Where did this come from ?

Regards,

**Comment by gRullo** [comment]
the same

**Comment by eden764** [comment]
same :(((

**Comment by filoh** [comment]
same

**Comment by giordanojr** [comment]
same

**Comment by gemgio** [comment]
same for me too

**Comment by gregory-yet** [comment]
## Run as admin and re install did the trick for me.

**Comment by MadD0g25** [comment]
maybe you have to use the old version ?

**Comment by CreativiTimothy** [comment]
Using the old version, reinstalling, and running as adming did not work for me

**Comment by MadD0g25** [comment]
Ah ! it works again ;)

**Comment by Buddhasama** [comment]
The old version started doing that as well

**Comment by yasin939** [comment]
Run the program as an administrator .

**Comment by jeremie152** [comment]
no worry just wait new update or log on with ptc and work again^^

**Comment by Ar1i** [comment]
#2110
