### ISSUE TITLE
[NO ISSUE] Best place to catach pokemon?

### ISSUE THREAD

**Issue by Kenjizje** [Ar1i/PokemonGo-Bot#2104]
Hello guys i wanted to know 1 thing.. Where is the best to catch Pokemons? Im farming now in central park 50k EXP /h ... Better place somewhere? Ty for answer

**Comment by gregory-yet** [comment]
I'm farming in central park too, work fine. Lvl 26 very quickly and a lot of powerful pokemon with great IV (~90%)

**Comment by HBraga** [comment]
wich central park ? lol

**Comment by Kenjizje** [comment]
Whats your settings?  speed ? and move radius?

**Comment by Abbasoo** [comment]
@HBraga First default location when you start the bot.

**Comment by gregory-yet** [comment]
@Kenjizje Same as default configuration, which is 50 Km/h and 5000 meters.

**Comment by Kenjizje** [comment]
hmm intresting im level 33 and 50k exp /h and i cant get any good pokes...

**Comment by gregory-yet** [comment]
@Kenjizje For you, what is a good Poké ? Maybe my Pokés are bad lol ^^

**Comment by Ar1i** [comment]
Sorry, but this isnt a issue, so it has nothing to search here

**Comment by PokePro21** [comment]
37.8075122641545 -122.420654296875 this is best place for Magikarp . i have 600+ Magikarp candies & for dratini to
