### ISSUE TITLE
C:\Users\Ari\PokemonGo Bot

### ISSUE THREAD

**Issue by eskirex** [Ar1i/PokemonGo-Bot#2105]
http://i.hizliresim.com/QQENvV.png

**Comment by Astifleure** [comment]
same pb bro...

**Comment by PoDaMo** [comment]
selbe bei mir auch nach dem letzten update

**Comment by Pyroman2300** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/2102

**Comment by joelx3** [comment]
look at my fix.

**Comment by DiTechRacer** [comment]
Jop, hier geht auch nix.. die haben bestimmt wieder die api gefixt

**Comment by tryndamerewu** [comment]
@eskirex you have 2 of the same programe file on close them all then  restart i had same error becaause  had 1 account on then i  rename somting in the map that give me this same error just  close all  restart should be fine

**Comment by yasin939** [comment]
Run the program as an administrator .

**Comment by Ar1i** [comment]
#2110
