### ISSUE TITLE
Cant start the Bot

### ISSUE THREAD

**Issue by Experte9** [Ar1i/PokemonGo-Bot#2108]
If i start it now:
![unbenannt](https://cloud.githubusercontent.com/assets/20842528/17491615/a87a4a40-5da8-11e6-968e-4f52a0a26962.JPG)
Can u fix it or tell me whats wrong?

**Comment by joelx3** [comment]
FOR FUCK SAKE! THERE ARE TONS OF POSTS? WEHY THE FUCK ARE YOU POSTING IT TOO?

**Comment by jeremie152** [comment]
stop post a lot lol

**Comment by jeremie152** [comment]
no worry just wait new update or log on with ptc and work again^^

**Comment by yasin939** [comment]
Run the program as an administrator .

**Comment by Waiiim** [comment]
Joelx3 Could you like... calm the f*ck down? Yelling like a moron isn't gonna change much

**Comment by Abbasoo** [comment]
@Experte9 DELETE the previous build, DOWNLOAD THE UPDATE and RUN AS ADMIN !!!

**Comment by Wi1dHunt** [comment]
@yasin939 doesn't change this problem

**Comment by arjunvegda** [comment]
@joelx3  Well dude you opened a new issue called "FIX HERE"

**Comment by akangnduz** [comment]
delete your Configs FOLDER then start setting again it WORK!!!!

**Comment by Ar1i** [comment]
#2110
