### ISSUE TITLE
Pokemon List Error

### ISSUE THREAD

**Issue by ineedtostudy** [Ar1i/PokemonGo-Bot#2109]
With the latest update, within 5mins of botting I received an error
![error](https://cloud.githubusercontent.com/assets/20897325/17491816/6d32d034-5d66-11e6-9ada-129663dc28d2.PNG)

**Comment by Waiiim** [comment]
Yep, it's what the last 10 issues are all talking about
Wait next update, people are talking about putting it administrator but doesn't work for me

**Comment by Ar1i** [comment]
#2110
