### ISSUE TITLE
trainsferr all my pokemon

### ISSUE THREAD

**Issue by ankhmok** [Ar1i/PokemonGo-Bot#2115]
I just back to home and check result, but I find out all my Pokemon being transferred with no reason 

I set my transferre IV as 90% and CP1800 is that mean all of the Pokemon which is under that value(IV90% OR CP1800) will be transferred

**Comment by SpecialOOps** [comment]
Did you use the latest version ?

**Comment by eliteknight** [comment]
have you selected transfer all pokemons?

**Comment by ankhmok** [comment]
Of coz I didn't selected transfer all the Pokemon
I'm using the version which I download last night I can't sure is the latest version or not because I had turn my computer off and using my phone to leave this comment

**Comment by spotterd** [comment]
That means that the bot will transfer all pokemon who are below 1800cp and below IV90%

**Comment by chapones** [comment]
I also have some problens with transfer function, its not transfering all pokemons that should transfer and   still transfering wrong ones.

**Comment by eliteknight** [comment]
all posts about wrong auto transfer are worng...

**Comment by ankhmok** [comment]
What if I favourite some of my Pokemon will the bot also transfer them?

**Comment by xJustx** [comment]
Do you have the newest version?
