### ISSUE TITLE
Not working auto incubate

### ISSUE THREAD

**Issue by Adukas** [Ar1i/PokemonGo-Bot#2116]
Not working auto incubate with basics incubators

**Comment by eliteknight** [comment]
don't work atm...

**Comment by jeremie152** [comment]
y never worked for the moment^^

**Comment by Niubbo** [comment]
let's hope he will fix it soon as he can :)

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
