### ISSUE TITLE
new error 

### ISSUE THREAD

**Issue by itzjaydon** [Ar1i/PokemonGo-Bot#2117]
anyone know a fix?
![image](https://cloud.githubusercontent.com/assets/20823634/17492565/42a3c4f2-5da4-11e6-9b0a-1816efd9d130.png)

**Comment by akangnduz** [comment]
delete your Configs FOLDER then start setting again

**Comment by Midnlght** [comment]
Updated to newest version? and i get that at times too, it usually just fix it self but try deleting your configs folder

**Comment by itzjaydon** [comment]
@akangnduz @Midnight thanks ill give it a shot

**Comment by itzjaydon** [comment]
worked for a few seconds then happened again :(

**Comment by Stanced** [comment]
I have the same problem. deleting the configs won't do it. 
btw. I logged in with my other account and it works. lul

**Comment by itzjaydon** [comment]
@Stanced cool ill give it a shot too

**Comment by itzjaydon** [comment]
it seems to work then does the error every now and then

**Comment by itzjaydon** [comment]
then i get this 
![image](https://cloud.githubusercontent.com/assets/20823634/17492807/74f52e18-5da5-11e6-90e9-9bffdc7a5510.png)

**Comment by Mixone-FinallyHere** [comment]
maybe a mutex issue?

**Comment by Stanced** [comment]
also there are no pokemon icons in the list (error icon). bust just on this acc. mhm....

**Comment by devilexclonz22** [comment]
@Ar1i always soft banned after 5 minutes in 2 bot in new update .. 1.8.1

**Comment by itzjaydon** [comment]
works fine now hope its fixed for you guys

**Comment by itzjaydon** [comment]
.

**Comment by xJustx** [comment]
?
