### ISSUE TITLE
Pokestop error -.-

### ISSUE THREAD

**Issue by MarvinSCR** [Ar1i/PokemonGo-Bot#212]

**Comment by FelipeMallmann** [comment]
same here!

**Comment by FelipeMallmann** [comment]
someone said if you delete %temp% files it works again, but idk if i do that.

**Comment by niikooartz** [comment]
http://prntscr.com/bz2lsw same :d

**Comment by VisualBoyAdv** [comment]
![image](https://cloud.githubusercontent.com/assets/20724656/17250146/0bff2706-5571-11e6-8f11-ce21cb4a3d6d.png)
pretty much loops like this

**Comment by niikooartz** [comment]
working again ^^

http://prntscr.com/bz2nrj

**Comment by uyusuak** [comment]
Same here :/

**Comment by FelipeMallmann** [comment]
i think that is niantic servers unstable.. because here worked again

**Comment by VisualBoyAdv** [comment]
It seems to be random? Mine just stopped working, but it will probably work later.

**Comment by Ar1i** [comment]
Servers.
