### ISSUE TITLE
Telegram notification bug

### ISSUE THREAD

**Issue by SxS46** [Ar1i/PokemonGo-Bot#2121]
If a non authorized telegram user write a message to the bot he gets "You have no power here" and after that all future notification are sent to him instead of me.
Example:
![photo_2016-08-08_21-19-04](https://cloud.githubusercontent.com/assets/20704913/17492800/ca23ea0c-5dad-11e6-972a-73ccc6457855.jpg)

**Comment by BlackHatching** [comment]
Not easy to modify phone contacts

**Comment by martinjamesl** [comment]
How to setup the notif?
