### ISSUE TITLE
Items number is wrong

### ISSUE THREAD

**Issue by croghostrider** [Ar1i/PokemonGo-Bot#2122]
Hi Ar1i
the mobiele app and the bot, show not the same item number (app:261 bot:395 ).
![print](https://cloud.githubusercontent.com/assets/8603272/17493064/fb30d078-5dae-11e6-9c94-95c8936c58b6.png)
![screenshot_20160808-212308](https://cloud.githubusercontent.com/assets/8603272/17493072/0537829c-5daf-11e6-9ef6-f5a6ce6410c3.png)

**Comment by PhantomKidding** [comment]
same here

**Comment by Niubbo** [comment]
same here

**Comment by Abbasoo** [comment]
Same here.

**Comment by BlackHatching** [comment]
he didnt fix it

**Comment by 666triv** [comment]
same

**Comment by ozdenor** [comment]
same here, too.
![capture](https://cloud.githubusercontent.com/assets/20899336/17551033/9e2567ba-5f00-11e6-988e-02f47d5e7137.PNG)

**Comment by mushroomhead** [comment]
@ozdenor @666triv @Abbasoo @Niubbo @PhantomKidding @croghostrider 
bug may not fixed, but....
I found way to resolve is **Sold some pokemon.**

Before : I found same error and I have pokemon around 200+.
After : I sold a lot pokemon (I think 50+) which IV less than 50%, and IT WORKS! items count back to normal.

hope this help you.

ps. sorry for my language.
