### ISSUE TITLE
error found

### ISSUE THREAD

**Issue by D3VASTATlON** [Ar1i/PokemonGo-Bot#2124]
i have the newest verison of the bot getting this error on one of my instances but not the other one (2 total)

![ss 2016-08-08 at 03 29 08](https://cloud.githubusercontent.com/assets/20890128/17493413/39e57ad4-5d7e-11e6-8281-515899aeab2a.png)

**Comment by BlackHatching** [comment]
dont tick auto incubate eggs

**Comment by D3VASTATlON** [comment]
ok thnx

**Comment by xJustx** [comment]
^
