### ISSUE TITLE
IVS Selection

### ISSUE THREAD

**Issue by ThinkerPad** [Ar1i/PokemonGo-Bot#2125]
Is there a way to only keep pokemons with the highest IV ?

Where can I get the source code ? (I can add such condition).

Thank you

**Comment by gregory-yet** [comment]
There is already an option like this in Transfer parameter, you can set the minimum IV of Poké bot catch.

**Comment by ThinkerPad** [comment]
But in case it caught a 2nd poke, will it keep the one with highest IV or the old one ?

**Comment by PippoAe** [comment]
It will keep both if the second pokemon is above your configured "maximum cp to tranfer" or "maximum IV to transfer".

**Comment by roooochi** [comment]
if you have keep 2 pokemon and theres a 500cp pikachu with 70% IV and another thats 600cp 60% IV then you get a 400cp 90% (or whatever you set your value to) it will keep all 3

**Comment by xJustx** [comment]
^
