### ISSUE TITLE
Running multiple bots at the same time

### ISSUE THREAD

**Issue by hupiukko** [Ar1i/PokemonGo-Bot#2126]
Can someone explain to me how running multiple bots at the same time works?
-Can you have different configs on them?
-Does it work by just running the .exe again while the other one is running ?
-Is there any limitations of how many bot you can have at the same time (so you dont get bans)?

Sorry if dumb questions, i'm just trying to be careful not to get softbans because i have a feeling niantic is flagging account for botting and will ban them all simultaneously at some point.

Thanks to everyone who answers

**Comment by AiVo7z** [comment]
If you're afraid of getting banned, dont use bots. If they wan't to block you for using it, they will regardless of running 1 or 2 bots. Just unzip the bot twice or more. Or simply Name the Folder diffrently. Then open .exe in each Folder every .exe got their own config then. Just Login (2 diffrent accounts) and thats it.

**Comment by hupiukko** [comment]
Thanks aivo7z :) Yep i know, I'm not stupid. Of course i dont bot on my "main account" but it would be nice to possibly keep the botted accounts as well after they try to ban people. Thats why im trying not to get any softbans so my accounts wont get flagged.
