### ISSUE TITLE
Soft Ban?

### ISSUE THREAD

**Issue by filoh** [Ar1i/PokemonGo-Bot#2127]
All pokemons still running away.
This is soft ban?
What can I do to fix this? Already tryed the Force Unban button but no work.

Should I close the bot and wait some hours?

**Comment by Inforcer25** [comment]
Just press the force unban button

**Comment by filoh** [comment]
Already tryed that

**Comment by ineedtostudy** [comment]
wait 15-30mins, its probably ip ban

**Comment by filoh** [comment]
Oh, already figurite out I guess, I'm with 0 pokeball, and I think the bot is trying to use normal pokeballs to catch, and with 0 all pokemons escape.
But my bot is set to 20 pokeballs.

**Comment by filoh** [comment]
Yes, now I have the pokeballs, It's back to catching.
