### ISSUE TITLE
Not catching anything

### ISSUE THREAD

**Issue by PhantomKidding** [Ar1i/PokemonGo-Bot#2128]
Almost lost every pokemon. Tested on mobile end but no softban.

![image](https://cloud.githubusercontent.com/assets/8907855/17493554/7e988bce-5d76-11e6-942b-948812882c04.png)

**Comment by ineedtostudy** [comment]
You are softbanned, press the Force Unban

**Comment by PhantomKidding** [comment]
@ineedtostudy Why can I catch pokemons on my phone if im softbanned.

**Comment by AiVo7z** [comment]
I've had same prob. Mobile it worked, bot seemed to have softban. I catched a couple on mobile and it instantly the bot worked again. Weird softban if you ask me. It's bugged don't ask why it happens, but you aint the only one.

**Comment by gitovahere** [comment]
If you can get XP from pokestop and not catching pokemons then you're not banned. 
Here's a fix: https://github.com/Ar1i/PokemonGo-Bot/issues/1930

**Comment by xBudSpencer** [comment]
i dont get anything from pokestops and no catching pokemons ....  it said: softban detected ... maybe unbanned... but nothing happend... force unban dont work

**Comment by PhantomKidding** [comment]
@gitovahere Problem solved. Running out of normal pokeballs is the issue I believe. It works now.

**Comment by granate1974** [comment]
Hi, same also for me. Nothing from Pokestop and no Pokemon could be caught.

Force Unban also didn't work. But in output is is mentioned in red, that a softban is active and it will be removed, but still nothing.

**Comment by PhantomKidding** [comment]
@granate1974 If this happens on your mobile, then you are softbanned. One way is picking one pokestop, then open, spin, and close for 40 times.
