### ISSUE TITLE
Pokemon list Icon error

### ISSUE THREAD

**Issue by Inforcer25** [Ar1i/PokemonGo-Bot#2129]
@Ar1i  So i fugured out. If you delete the PokemonList.cv file from the config and restart the bot the icons are fixed. But when you press reload it shows error. I also dont think its the servers because i tested the previous bot ant the previous bot didnt have that issue. It seems like its the Reload button that is causing the error.

**Deleted the PokemonList.cv file and started the bot:**
![l90chfu](https://cloud.githubusercontent.com/assets/16230645/17494095/8f9664f4-5db3-11e6-85d1-eaf355dcf1a9.png)

**After pressing the reload button:**
![gab7e4i](https://cloud.githubusercontent.com/assets/16230645/17494128/a4537120-5db3-11e6-94d9-d481408d7489.png)

**Comment by kazzaluis** [comment]
#2110

**Comment by Inforcer25** [comment]
@kazzaluis I guess you didnt fully read what I posted. I know about that and I dont have any server issues. Even when I manually go to the icon it works so plz read it before posting a comment

**Comment by xJustx** [comment]
#2145
