### ISSUE TITLE
Its Login down? or what is this?

### ISSUE THREAD

**Issue by DomeSs97** [Ar1i/PokemonGo-Bot#2130]
Hi, i have little problem.. all acount say this: 

http://screenshot.cz/R90HR/

**Comment by CruSherFL** [comment]
Works fine here with newest version although i got a message like that too about 15min ago.

**Comment by DomeSs97** [comment]
every 1 minit say it.. catch 1 pokemon, find 3 pokestop and go down.. CZech Server latency max 170ms..

**Comment by Experte9** [comment]
maybe this helps, #2110

**Comment by DomeSs97** [comment]
restart bot.. and delete config files = fixed..
