### ISSUE TITLE
question- pokeball

### ISSUE THREAD

**Issue by Mamutebr** [Ar1i/PokemonGo-Bot#2132]
If the end pokeball
the bot will use greatball ?

**Comment by PippoAe** [comment]
No

**Comment by MythosOfGaming** [comment]
Please Close your issues if the problem doesnt exist anymore

**Comment by Experte9** [comment]
@MythosOfGaming This is a stupid question but..... how can i close my own Issue?

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
