### ISSUE TITLE
All pokemons goes away

### ISSUE THREAD

**Issue by Manugc1** [Ar1i/PokemonGo-Bot#2134]
![screenshot_3](https://cloud.githubusercontent.com/assets/20894332/17494113/b2519bfa-5d89-11e6-8961-fdd849249f66.png)

**Comment by PippoAe** [comment]
You don't have pokeballs in your inventory.
You need normal pokeballs or the bot won't catch anything under 499cp.

**Comment by filoh** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/20794024/17494197/0ef44cea-5d8a-11e6-9f20-09f561be92a5.jpg)
here man, set this config on the itens GUI

**Comment by PhantomKidding** [comment]
#2128 Had same problem.

**Comment by Manugc1** [comment]
Thanks, now is working!

**Comment by PippoAe** [comment]
You're welcome.
Don't forget to close the issue,
