### ISSUE TITLE
Translation, language

### ISSUE THREAD

**Issue by Lexobama** [Ar1i/PokemonGo-Bot#2135]
There is a bad French translation, and accent bugs in the interface.

**Comment by Experte9** [comment]
Maybe help them?

**Comment by Mynymoys** [comment]
How we can help?

I want help for translate to 100% in French.

**Comment by Experte9** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pulls

**Comment by xJustx** [comment]
^
