### ISSUE TITLE
Pokecrot

### ISSUE THREAD

**Issue by TMaddox** [Ar1i/PokemonGo-Bot#2136]
Well HE (https://www.pokecrot.com) is now DMCA protected. 

Edit: he copies now another bot so yea ^^

**Comment by Experte9** [comment]
Virus detected, by Avast!

**Comment by kazzaluis** [comment]
lol

**Comment by Affenasmo** [comment]
i dunno why but after i installed and tried to use pokecrot on my VM....the proxy settings of all browsers changed...just fyi

**Comment by lailaps** [comment]
Messa Harianto Oktavian

I would not download anything from that person.
You can find a lot of sites with changed content and info:

Hacked by Messa Harianto Oktavian.

No one seems to care in such a shitty country like Indonesia.
