### ISSUE TITLE
cant play pokemon go on my phone after shut down the bo

### ISSUE THREAD

**Issue by Safti54** [Ar1i/PokemonGo-Bot#2137]
So my problem is when i shut down the bot i wait like 10 minutes then i log in on my phone but its still like softbanned, but in the game it doesent tell me that im softbanned thats why im confused, i cant spin pokesotps neither catch pokemons, so my question is what does all this mean can i ever play again whith my ac on my phone or na i dont know.

**Comment by Inforcer25** [comment]
a soft ban lasts more than 10 minutes. What I do is is when I use the bot I set the location in NYC. But when I wanna use my phone I set it to my location so that the bot can unban me and then i just shut down the bot again and use my phone then it works TADAAAAAAAA

**Comment by Safti54** [comment]
nice thanks xDD
