### ISSUE TITLE
Not Catching Pokemon!

### ISSUE THREAD

**Issue by 666triv** [Ar1i/PokemonGo-Bot#214]
Amazing work so far!
But 1 slight issue for every 10 pokestops  only catch 1/2 Pokémon and when it does catch them they are not transferred as request and instead are kept even though it is specified to transfer.... Ive slowed the speed right down to 10 - 20 -25- 30- 40 to see if this was because I was going to fast... I'm using the default location which looking on the radar is flooded with catches...

**Comment by 12348766754** [comment]
I saw in another topic that Pokemon GO downed the cap.
That results in less pokemons an hour.

**Comment by Ar1i** [comment]
^this. And the Servers are laggy sometimes.
