### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#2141]
![adsiz](https://cloud.githubusercontent.com/assets/19182149/17495101/5fcdbc42-5dc0-11e6-873c-6f80b96b9059.png)

new version giving error

**Comment by Saonji** [comment]
i have this Error too

**Comment by DomeSs97** [comment]
delete config folder.. and start as admin

**Comment by xJustx** [comment]
is it working now ?

**Comment by navygino** [comment]
no, it doesn't work

**Comment by lucas2107** [comment]
It happend when you lost connection to Pokemon GO servers ( I think ), check your firewall.

**Comment by navygino** [comment]
DomeSs97 is right! Solved by:
1,) Delete everything in the Config folder.
2.) Run as admin

**Comment by xJustx** [comment]
^
