### ISSUE TITLE
Game Crashes Tried running in Admin but crashes after 15 sec.

### ISSUE THREAD

**Issue by mikeyrgarcia** [Ar1i/PokemonGo-Bot#2143]
Game crashes after about 15 seconds.

**Comment by Affenasmo** [comment]
maybe u should update all driver netframework etc.....mine runs on win 7.8.10 64/86 without any problems

**Comment by mikeyrgarcia** [comment]
I have currently running 4.6

**Comment by Experte9** [comment]
#2110

**Comment by mikeyrgarcia** [comment]
the bot starts but now it crashes after about 10 minutes or so.

**Comment by xJustx** [comment]
Somes error before the crash?

**Comment by mikeyrgarcia** [comment]
no just closes no errors

**Comment by xJustx** [comment]
How much RAM do you have?

**Comment by mikeyrgarcia** [comment]
16 gb

**Comment by xJustx** [comment]
Try to download the newest version und try it again please.

**Comment by mikeyrgarcia** [comment]
restarted computer and now its not crashing its been up for about 40 minutes now, closing this issue. Thank you guys for helping me appreciate it alot.
