### ISSUE TITLE
Force unban not working

### ISSUE THREAD

**Issue by Lassetheg** [Ar1i/PokemonGo-Bot#2144]
Why is the Force Unban not working? Please Fix
Thanks <3

**Comment by CreativiTimothy** [comment]
Yeah, it does not appear to work. I have to go into the game and unban myself before going back since the force unban no longer works

**Comment by Lassetheg** [comment]
okay

**Comment by Waiiim** [comment]
Is the softban disabled after 10mins? or is it way longer

**Comment by MiGaBelG** [comment]
i tough it was for 1-2 hours
