### ISSUE TITLE
Pokemon List error

### ISSUE THREAD

**Issue by Saonji** [Ar1i/PokemonGo-Bot#2145]
Hey,

erst mal danke für die Arbeit die du in den Bot steckst das ist erste Sahne.
Auch dass so schnell die neue API funktioniert.

Leider bekomme ich mit dem neusten Build folgenden Fehler:

![pokemon error](https://cloud.githubusercontent.com/assets/20913678/17495462/6a655a54-5db9-11e6-843e-2b842e6d0207.JPG)

Das komische ist dass er aber nur unter 2/3 Bot Instancen Auftritt.
Bei der 3 nicht.

**Comment by bkrandy** [comment]
came back after a couple of refreshes for me

**Comment by Saonji** [comment]
not for me ;/

**Comment by Experte9** [comment]
#2110

**Comment by xJustx** [comment]
Restart your bot and it will work
If you press reload the bug comes again...

**Comment by Saonji** [comment]
Yeah xjust thats the Problem but only on 2/3 instances. On the 3 i can hit reload as often i want and there are no "error" Pics. Thats a bit spooky. Every bot instance has his own folder.

**Comment by xJustx** [comment]
Mh.. okay. Thanks for the info @Saonji.

**Comment by xJustx** [comment]
It's fixed now. Please download the newest version.
