### ISSUE TITLE
[enhancement] save time by recycling only when needed

### ISSUE THREAD

**Issue by globsch** [Ar1i/PokemonGo-Bot#2147]
I suggest to change the recycling. Lets do if if the inventory is full or close to full. (like normal people would do!)
We would be more human like and faster.

I would code it myself if possible :-(

**Comment by averocity** [comment]
Suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by xJustx** [comment]
^
