### ISSUE TITLE
no pokemon list

### ISSUE THREAD

**Issue by reimerth** [Ar1i/PokemonGo-Bot#2148]
yeah I downloaded the new version with the update but I have not the pokemon list from before. so i cant transfer in mass or see my pokemon cp and everything. can someone help me plz I have no idea what to do!!!

**Comment by Experte9** [comment]
#2110

**Comment by reimerth** [comment]
the window with all the pokemon is not openning at all, that's what I mean

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
