### ISSUE TITLE
[Pokemon] CP XXX IV XX% got away while using ItemPokeBall

### ISSUE THREAD

**Issue by DevilBlyat** [Ar1i/PokemonGo-Bot#2149]
Hello,

I got this every time I meet a pokemon and it's a desaster because it's so random. Once, it doesn't happen and the other time, it happens. 

Could you explain to me the reason ?

**Comment by Fertigpizza** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/2146

Same issue here!

**Comment by Safti54** [comment]
same

**Comment by Fertigpizza** [comment]
this is a major issue, I'm at 12 pokemon/ now...

**Comment by BEKKNQV** [comment]
dont set normal Pokeballs to 0

**Comment by Fertigpizza** [comment]
so how do I prevent the bot to not use them at all?
I want to get all normal pokeballs recycled and only use greater balls for now. Later in the game it should skip them too and only use ultra balls...

**Comment by Ravathyra** [comment]
I have so many GreatBalls and my Bot use them. But got the same **Issue**
<a href="http://www.fotos-hochladen.net" target="_blank"><img src="http://img5.fotos-hochladen.net/uploads/errors1rx05e6cp.png" border="0"></a>

My Bot didn´t catch the Pokemon anymore. And i haven´t got a soft bann.

**Comment by CreativiTimothy** [comment]
Same. I can spin Pokestops, but for some reason, it doesn't catch Pokemon. Necrobot works fine however

**Comment by roooochi** [comment]
maybe have atleast 20 of each pokeball? lol

**Comment by Ravathyra** [comment]
@roooochi In my Picture i have a Full Inventory and i set pokeball to 20, superballs to 20 and greatballs to 500. I have enough. It´s a Bug in the Bot

**Comment by gitovahere** [comment]
If you're able to farm pokestop but not catching then you're not banned. It's your setting. Fix in here: https://github.com/Ar1i/PokemonGo-Bot/issues/1930

**Comment by AguilaHub** [comment]
you should just have 330 items in your inventory whatsoever

**Comment by filoh** [comment]
set your itens like this
![0ef44cea-5d8a-11e6-9f20-09f561be92a5](https://cloud.githubusercontent.com/assets/20794024/17501111/04ac578c-5db2-11e6-92b5-eb654566e3bd.jpg)

**Comment by sunit1998** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20731094/17501172/c0062d68-5df9-11e6-8589-3a12f03fd39e.jpg)
this setting works great for me and never got any error whatsoever

**Comment by xRealMaks** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
