### ISSUE TITLE
[Request] Implement the eggs incubator and live location

### ISSUE THREAD

**Issue by Jukera** [Ar1i/PokemonGo-Bot#215]
hey,
please implement the eggs incubator and live location screen :)

**Comment by HaydarOzturk** [comment]
Live Location screen might not be a good idea. But I support egg incubator.

**Comment by FishyUniverse** [comment]
Would love being able to hatch eggs too! ^-^

**Comment by Ar1i** [comment]
Its currently not in the API, but i will take a look at it.

**Comment by cwirek91** [comment]
eggs incubator should be nice feature ;-)

**Comment by NewfieVortex** [comment]
I'd love this. There are not many Pokemon around my area and I don't want to go too far so I don't get banned. Egg hatching would help me greatly :)
