### ISSUE TITLE
FOR THE NEWBIES!!!

### ISSUE THREAD

**Issue by money1989** [Ar1i/PokemonGo-Bot#2151]
GUYS PLS
idf you get an error:
1. reinstall (means delete the whole bot and reinstall it!
2. if you get a softban(softban means 10min!)
- dont use more then 3 bots on 1 IP
if. you  still use more then 3 bots u get a riskt to get an IP BAN!

thx 
Love u ar1i
<3

**Comment by Waiiim** [comment]
Softban isn't only 10mins

**Comment by xJustx** [comment]
TY - but nobody will read this too :P
And a softban is not only 10 minutes ^^
