### ISSUE TITLE
Auto Evolve + Auto Transfer Bug

### ISSUE THREAD

**Issue by andyfeb** [Ar1i/PokemonGo-Bot#2152]
Well... let's say that I have 100 Pidgey Candies and I have turned on my Auto Transfer if there are more than 2 same Pokemon. I have setting my Auto Evolution list not to Pidgey but Pidgeotto (or let's say I don't setting it at Pidgey and Pidgeotto at all). Then the bot didn't Auto Transfer Pidgey if there are more than 2 Pidgeys but more than 4 Pidgeys (to Evolve 1 Pidgey need 25 candies)

**Comment by CL0UD09** [comment]
I don't think you're running into a bug. You either have the "keep pokemon that can be evolved" setting checked, or some of your pidgeys are exceeding your IV/CP threshold and aren't being transferred.

I would reply with exactly what CP/IV the pidgeys your pidgeys have, along with your current config. Chances are you have something set incorrectly.

**Comment by milanstiano** [comment]
If you want autotransfer, so please fill the column with 0 (zero) and checked "keep pokemon that can be evolved" it's work for me

**Comment by andyfeb** [comment]
well... yeah... I'm sorry... it's my mistake...
I skipped "keep pokemon that can be evolved"
Then this is not an issue...
