### ISSUE TITLE
location issue

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#2154]
The bot dosnt know my Last Position where i closed it.

It Starts every Time in New York.

I have to reallocate it every Time i restart.

Bevor the New api it Starts always at the location i closed it.
If i Chose a Different Location it walkt from old location  to the New.

Now it "Spawns" in New York....

**Comment by EvilEmpireDriftTeam** [comment]
Bot is not working, what it says about the API, again!!!
