### ISSUE TITLE
Force Unban

### ISSUE THREAD

**Issue by Waiiim** [Ar1i/PokemonGo-Bot#2156]
Am I the only one for who "Force Unban" does not work?
It says : "Unbanning you at next Pokestop" I arrive to the pokestop and nothing happens.
And I know i'm softbanned because I have pokeballs in my inventory, and every single pokemon is fleeing

**Comment by MicGakaMilo** [comment]
How donyounforce unban?

**Comment by MicGakaMilo** [comment]
Same but can you presse tell me how i force unban?

**Comment by Waiiim** [comment]
On your pokemon list there's "Power up" "Transfer" etc and there's also Force Unban

**Comment by xJustx** [comment]
#2144
