### ISSUE TITLE
best speed 

### ISSUE THREAD

**Issue by loudjedi** [Ar1i/PokemonGo-Bot#2159]
please can you guys tell me what is the best speed to catch more pokemons ? 
thanks

**Comment by DomeSs97** [comment]
i work on 300KM/h.. still ok.. 24hours = 2.400.000 XP

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by loudjedi** [comment]
really ? 300 ? i chose 10 
i just want more pokemons 
and how much for distance ?

**Comment by DomeSs97** [comment]
really 300km/h.. 250 pokemons 5000km range and 100k XP/h
