### ISSUE TITLE
The bot stopped after 30minutes

### ISSUE THREAD

**Issue by New123WeN** [Ar1i/PokemonGo-Bot#216]
around 30 mins mark The bot time count stopped, also all the actions, its like paused. I currently have 4 running happened to all of them. Is it just me?

**Comment by VisualBoyAdv** [comment]
No it is not, kind of annoying since you can't go afk!

**Comment by omgcharliecat** [comment]
same here...

**Comment by Ar1i** [comment]
Should be fixed in the Update. If not open a new Issue, with a Screenshot please.
