### ISSUE TITLE
Install/Startfehler...

### ISSUE THREAD

**Issue by waldiludi** [Ar1i/PokemonGo-Bot#2161]
Okay, ich habe es genau wie im video gezeigt gemacht; habe gerade die neuste version runtergeladen. Starte alles wie früher, drücke auf PokemonGo.RocketAPI.Console, lege es als startprojekt fest, Drücke srtg+F5. Jetzt kommt: "Fehler beim erstellen. Möchten sie den Vorgang fortsetzen und den letzten erfolgreichen build ausführen? Drückt man auf ja kommt eine fehlermeldung und nichts passiert. Danke für hilfe im vorraus! MFG

**Comment by xJustx** [comment]
Benutze erstmal das bitte: https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
