### ISSUE TITLE
Geschwindigkeit ?!

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#2162]
was ist die Beste geschwindigkeit um nicht gebannt zu werden 
habe es nun auf 21 Km/h gestellt.

Frage läuft der bot auch bei schnellerer Geschwindigkeit ohne dass man einen softban oder sogar einen Vollen Ban erhält ? 

freue mich auf eure antworten :) mfg

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
