### ISSUE TITLE
For real, ar1i? 

### ISSUE THREAD

**Issue by martinkanz** [Ar1i/PokemonGo-Bot#2164]
I dont think 8 virus programms lie man, sorry but get the malware code out of the program please. 
Danke, dass ich gerade so angst um malwares habe und sämtliche virenschutzprogramme durchlaufen lasse. 
![image](https://cloud.githubusercontent.com/assets/20915020/17498713/5374e3c2-5dc9-11e6-98c9-fb9c25ca5f10.png)

**Comment by roooochi** [comment]
no1 cares

**Comment by xJustx** [comment]
If you don't trust us take a look into the source and build it yourself.

**Comment by Ar1i** [comment]
Jo bidde, würdest du 1x googlen würdest du raffen das es false positve is.

**Comment by Ar1i** [comment]
Und btw ein ZIP zu Scannen ist immer schlau. Da es genau 0 bringt.

**Comment by martinkanz** [comment]
@Ar1i die meisten öffnen die zip. 
warum entfernt man nicht einfach den false positive code?

**Comment by xJustx** [comment]
Es können nicht einfach mal alle entfernt werden..

**Comment by Ar1i** [comment]
Na dann such ma den false positve im Winrar Code. Viel spaß?

**Comment by Logxn** [comment]
Bist ein vollidiot ganz im ernst.
RAR zu scannen.....

Scan doch lieber die EXE. Wenne da was findest dann darfste von mir aus nochmal rumheulen, dann rede ich auch anständig mit dir.. uff

**Comment by martinkanz** [comment]
@Ar1i Der code liegt laut norton in der console. Und norton öffnet die zip zu 100%. 
@Logxn na danke dir :+1: feier den botmacher zwar total, lasse den bot aber nur noch in einer vmware laufen.

**Comment by xJustx** [comment]
Ist ja kein Problem, wenn du das so machst, dann ist das so :o

**Comment by Logxn** [comment]
Ok.
Das ist deine entscheidung.

Fakt ist, alle die uns nicht vertrauen können sich eigentlich verpissen.
