### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by waldiludi** [Ar1i/PokemonGo-Bot#2165]
Die DLL "encrypt.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden. Habe gerade schon einen fehler gemeldet, dass ich nicht starten kann und mir wurde eine Build geschickt. Jetzt wird der obige text die ganze zeit gespammt und der bot findet keine Pokestops. Danke wieder im vorraus

**Comment by xJustx** [comment]
lade dir nochmal die Builds Only bitte herunter. Sollte gehen.

**Comment by Ar1i** [comment]
Buildest du selbst? Wenn ja, pack die encrypt.dll aus dem Builds Only in den Debug Folder. MfG.

**Comment by waldiludi** [comment]
@Ar1i habs in den debug ordner verschoben aber immernoch das selbe problem mfg

**Comment by xJustx** [comment]
Lade dir mal bitte die BuildsOnly herunter und versuche es damit.

**Comment by xJustx** [comment]
Wenn es nicht funktioniert, öffne bitte ein neues issue.
