### ISSUE TITLE
Is the auto incubation not working properly?

### ISSUE THREAD

**Issue by GreYzZ** [Ar1i/PokemonGo-Bot#2167]
Hello,
I have the feeling that the auto incubation is not working properly
if you only have a basic incubator.

Any confirmations on this?

Greetings from Germany,
GreYzZ

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.

**Comment by GreYzZ** [comment]
@xJustx 
okay thanks
