### ISSUE TITLE
Evolving Bug.

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#2168]
Hab grade diesen Fehler bekommen. 

"Failed to evolve Ekans. EvolvePokemonOutProto.Result was FailedInsufficientResources."
![error](https://cloud.githubusercontent.com/assets/20752818/17499064/54f07a2a-5dcb-11e6-97d8-b49c691cdfce.png)

**Comment by xJustx** [comment]
Bei jedem Pokemon?

**Comment by FAymYs19** [comment]
Nope.

**Comment by Logxn** [comment]
MAN.
INSUFFICIENT RESOURCES.

So wad brauchta beim Evolven....??? CANDYS RICHTIIIIIIIIIG.
Hat er die? NEEEEEEEEEEEEEEEEIN.

#Closed

**Comment by xJustx** [comment]
Nicht genug Candy?

**Comment by FAymYs19** [comment]
#Toxic Ich hab ja nicht manuell entwickelt...

**Comment by xJustx** [comment]
Überprüfe mal das Candy zu dem Pokemon in der Pokemonlist.
Und sorry für die Antwort von Logxn.

**Comment by FAymYs19** [comment]
NP. wollte nur zeigen das der Bot es versucht hat, obwohl er es nicht konnte.
Es hat also keine überprüfung der Candy gegeben.
Bin kein wirklicher Informatiker / Coder aber man kann da doch noch ne if-Bedingung reinsetzen.
^^

**Comment by xJustx** [comment]
Werde ich mal so weiter geben.
Ich lasse das so lange offen, bis das gefixxt ist.

**Comment by xJustx** [comment]
#1959
