### ISSUE TITLE
API Token And Name ?

### ISSUE THREAD

**Issue by fvzkync07** [Ar1i/PokemonGo-Bot#217]
I cant start bot ı need api token and name

**Comment by Ar1i** [comment]
You dont need, just let it empty.

**Comment by fvzkync07** [comment]
Error: Pokemon Go Rocket API
[18:31:38] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   konum: PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs içinde: satır 34
   konum: PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs içinde: satır 128
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs içinde: satır 50

**Comment by fvzkync07** [comment]
oh lol i am so sry i write wrong password :(
