### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by GreYzZ** [Ar1i/PokemonGo-Bot#2170]
Hello,
I have this problem: http://prnt.sc/c3ahdk

What is this error?

**Comment by ineedtostudy** [comment]
Could be server being down. Try redownloading

**Comment by Manugc1** [comment]
Servers are down

**Comment by JCortexs** [comment]
uo

**Comment by JCortexs** [comment]
up

**Comment by Pyroman2300** [comment]
Pokemon go just had an update, that could be causing it.

**Comment by jivie2006** [comment]
server lagging, just be paitent, wait a few mins-few hours for poke go to get its stuff together

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
