### ISSUE TITLE
Pokemon Go UPDATE IOS 1.0.3 android 0.33.0, new API change?

### ISSUE THREAD

**Issue by uchitake84** [Ar1i/PokemonGo-Bot#2171]
New update rollout someone cant confirm API change?

**Comment by GreYzZ** [comment]
I dont think there was a API Change because the bot is working for me like default

**Comment by uchitake84** [comment]
Release notes http://pokemongolive.com/en/post/update-080816/

**Comment by Pyroman2300** [comment]
@GreYzZ Doesn't work for me after the newsest update.

**Comment by cktisaac** [comment]
don't think so, BOT works well with me

**Comment by MiGaBelG** [comment]
Bot works fine for me since i restarted it for several times

**Comment by Pyroman2300** [comment]
I re-downloaded it, ran as admin, and still nothing.
