### ISSUE TITLE
*Question not issue*

### ISSUE THREAD

**Issue by silentassassonwp** [Ar1i/PokemonGo-Bot#2172]
Can i have the app open while bot is running

**Comment by MiGaBelG** [comment]
it works for me but it could cause for an soft ban

**Comment by FAymYs19** [comment]
Just dont activate GPS and ur are fine.

**Comment by Pyroman2300** [comment]
Yes you can have it open, just turn location services off.

**Comment by Key123456** [comment]
to turn off the GPS of your phone.

**Comment by roooochi** [comment]
i have the bot running and on my phone perfectly fine, doesnt matter if locations are on for me, just dont collect pokestops or catch pokemon from your phone

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
