### ISSUE TITLE
This is just a Question not a Problem

### ISSUE THREAD

**Issue by Criispey** [Ar1i/PokemonGo-Bot#2173]
Does some1 know any Dratini spawns or any spawns of pokemons at all ? any site ?

**Comment by Manugc1** [comment]
Sidney, next to the "Museum of contemporary art" or in the pierd 2/3. 
Santa Monica pier and beach is good too

**Comment by Criispey** [comment]
Whats setting in the bot do you use

**Comment by Manugc1** [comment]
I only have "Enable Pokemon list GUI", "Auto incubate" (its not working), "Auto tranfer doble Pokemons"
and Speed 20 km/h

**Comment by chickeflonoah** [comment]
why 20km/h? @Manugc1

**Comment by Criispey** [comment]
do you get more pokemons with lower speed ?

**Comment by Manugc1** [comment]
I put 20 km/h because is a normal speed, like walking. I dont want to be banned haha

**Comment by chickeflonoah** [comment]
They cant ban u for being in a car. Its the same hahaha :D

**Comment by Manugc1** [comment]
Haha i just wanna be secured

**Comment by idkwateva** [comment]
Human walking speed average = 5km/h 
20km/h either is running, cycling or in a vehicle...

**Comment by roooochi** [comment]
use 30k
and the viaduct in auckland/new zealand is good for dratini spawns, i got about 40 candies in a few hours

**Comment by Criispey** [comment]
ill try it ty sir @roooochi

**Comment by madpada** [comment]
pier 39 in san francisco has given me enough dratini though its much better for magikarp (4000+ magikarp candies)  I've found many iv 100% dratini also.
lat: 37.8094957575491
long: -122.410118579865

**Comment by Criispey** [comment]
@madpada Km/h settings ? do those matter ?

**Comment by Criispey** [comment]
Lol 1 minute at the pier and already 5 magikarps the heck

**Comment by madpada** [comment]
i usually do 50/kmh and 5000... but 5k is probably excessive... you could take that down to 3000.

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
