### ISSUE TITLE
the pokemon always run aways but iam not getting banned

### ISSUE THREAD

**Issue by zackbond** [Ar1i/PokemonGo-Bot#2176]
i dont know what happen ? am i get banned or not?

**Comment by MiGaBelG** [comment]
Can u spin pokestops?

**Comment by gitovahere** [comment]
Please search, it's been discussed to death!
Here: https://github.com/Ar1i/PokemonGo-Bot/issues/1930

**Comment by zackbond** [comment]
@gitovahere thank you sir ....

**Comment by xJustx** [comment]
^
