### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by kickodor** [Ar1i/PokemonGo-Bot#2177]
My virsus program just stop the bot right now 01.15 cause it detected a malware virus. have been working fine since the new update but my virus program just kicked in. is this because its a unspessified execute program that my virus program just does not like and it kicks in or is it a malware virus?

Sorry for bad english

**Comment by Pyroman2300** [comment]
None of my anti-viruses picked this up, it could be throwing a false-positive at you.

**Comment by kickodor** [comment]
ok what anit-virus are u using? i use norman

**Comment by kickodor** [comment]
but 2 anti-viruses picked it up

**Comment by kickodor** [comment]
Got it 2 work again was a slight new update on the program so i just updated it, probebly had 2 patch some holes

**Comment by xJustx** [comment]
It's a false positive. Take a look into the source if you don't trust it and build it yourself.
