### ISSUE TITLE
Servers are down?

### ISSUE THREAD

**Issue by ruubs11** [Ar1i/PokemonGo-Bot#2178]
Seems like the bots are not working annymore or am i the only one?
I cnat login on my phone either, servers down?

**Comment by owned85** [comment]
+1

**Comment by MiGaBelG** [comment]
same here

**Comment by ineedtostudy** [comment]
its back up

**Comment by MiGaBelG** [comment]
back up

**Comment by andyfeb** [comment]
I don't get any server down on here

**Comment by ruubs11** [comment]
its working on 2 out of 3 running bots here so i guess its up again
