### ISSUE TITLE
"Trainers must confirm they are not driving in order to continue playing." -0.33 update

### ISSUE THREAD

**Issue by Pyroman2300** [Ar1i/PokemonGo-Bot#2180]
Anyone know the max speed for this to not pop-up, or will this not effect the bot at all?

http://pokemongolive.com/en/post/update-080816/

**Comment by MiGaBelG** [comment]
didn't effect mine tho... running 60km/h

**Comment by pokerave** [comment]
Pokémon GO 0.33.0 out anything new?

**Comment by QustomiZed** [comment]
Im Usan Bolt i can walk very fast

**Comment by Pyroman2300** [comment]
@pokerave What do you mean? Are you asking if the update brought anything new?

**Comment by kickodor** [comment]
what if u dont update will it then affect you?

**Comment by Midnlght** [comment]
doubt it @kickodor

**Comment by gitovahere** [comment]
Google "average jogging speed." That way you could get your eggs hatched. Faster speed won't registered into the hatching.

**Comment by QustomiZed** [comment]
my speed is 300 and it hatch eggs

**Comment by pokerave** [comment]
@Pyroman2300 the Pokemon Go App just updated to 0.33.0 for android , did they implement something to get the bot not working again or something?

**Comment by QustomiZed** [comment]
You can change once your nickname

**Comment by Midnlght** [comment]
the bot is working fine @pokerave

**Comment by OhhPian** [comment]
now can change our trainer name ? @QustomiZed

**Comment by QustomiZed** [comment]
yes once

**Comment by Pyroman2300** [comment]
@pokerave I linked the update in the OP lol.

**Comment by sunit1998** [comment]
after the new update there is a chance of a perma ban on the players who uses speed above 18 kmph so please try to stay between the speed 10-30 kmph not above that

**Comment by Pyroman2300** [comment]
@sunit1998, You can still play it while in a car sooo

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
