### ISSUE TITLE
More than 3 Instances...

### ISSUE THREAD

**Issue by AguilaHub** [Ar1i/PokemonGo-Bot#2181]
I just noticed something: The Settings Menu says: "If you run more than 3 Instances you get softbanned". Does that mean I can 3 Bots for the same Account at the same time?! That would be too awesome, wouldnt it?

Can someone tell me plz?

---Aguila

**Comment by pokerave** [comment]
No. Bot with different folders and different account each

**Comment by roooochi** [comment]
i use same folder for 2 accounts and it works perfectly fine lol

**Comment by xJustx** [comment]
It's cause ip ban :p

**Comment by AguilaHub** [comment]
Well I cant use multiple bots (2) for the same account... would have been a bit to nice
:D
