### ISSUE TITLE
Why doesn't the bot use Ultraballs?

### ISSUE THREAD

**Issue by aquilinachu** [Ar1i/PokemonGo-Bot#2182]
I got 100 ultraballs in my inventory, about 10 greatballs and 0-3 pokeball (whatever it gets from a pokestop) but bot tries to use pokeball when my character clearly doesn't have one, ends up with pokemon running away. I rarely see it using greatball but I haven't seen it using ultraball so far. Is it just me?

(My backpack is limited to 400 and I set bot to exactly 400 items. 200 for pokeballs, 200 for pot-revive-berry)

**Comment by gitovahere** [comment]
It's programmed to use regular pokeballs for lower CP pokemons.

**Comment by aquilinachu** [comment]
What I meant was, why won't it say "oh we are out of pokeballs, let's use greatballs until I can find more pokeballs"

**Comment by roooochi** [comment]
simply doesnt need to, if it catches them with normal pokeballs why is that bad lol

**Comment by gitovahere** [comment]
I get what you're saying. That's extra work the developer has to add in. Yah, it will try to throw pokeball even though you have none. lol. Best is to request the programmer to add it. It's the least of his/her concern IMO.

**Comment by aquilinachu** [comment]
So that's just the way it works, got it. I'll just keep more pokeballs and reduce the amount of ultra-great ones since bot rarely ever misses any pokemon.
