### ISSUE TITLE
no pokestops within 5000m message?

### ISSUE THREAD

**Issue by drjack6** [Ar1i/PokemonGo-Bot#2183]
I used to get that message when the servers were down before API change. Now im getting it after a few minutes of up-time every time. I am using 6 bots at once. If I only use 3, will this problem go away??

**Comment by roooochi** [comment]
why in the fuck do you need 6 accounts anyways?

**Comment by Affenasmo** [comment]
youll get softbanned automatically if using more than 3 bots at once.....or the servers in the region ur farming is down

**Comment by Pyroman2300** [comment]
Delete your configs folder if you have the problem with the no-pokemon in range message.

**Comment by Manugc1** [comment]
I've been using 4 bots for 2 days and im not banned

**Comment by drjack6** [comment]
first i have 3 accounts, one in asia, australia, and london for the region specific pokemon. Another in a place where Lapras shows up a lot, cuz after getting to lvl 28 on a beach, I still havnt found a lapras. 1 im experiemtnting with some settings. And the 6th is focused on leveling p fast so I can trade all pokemon to a lvl 40 account when trading is included

**Comment by Otegh28** [comment]
read ari post please before post a new issue

**Comment by drjack6** [comment]
im gonna run 3 for a while and see if that fixes the problem

**Comment by arjunvegda** [comment]
@drjack6 I tried... Got banned. Took me an hour to get unban. Still testing...

**Comment by AguilaHub** [comment]
But, whats the maximum speed not to get banned anyways?
I wondering cause the faster it is the better it becomes, doesnt it?

**Comment by drjack6** [comment]
i use 30km/h

**Comment by AlpaEZPZ** [comment]
18

**Comment by roooochi** [comment]
i started at 50km and moved to 30km
before the api change 50 was fine for me and never got softbanned but after i had do reduce to 30
no idea why

**Comment by arjunvegda** [comment]
@roooochi I am at 50 still. Working like charm..

and @AguilaHub the less speed the safer it is.

**Comment by sunit1998** [comment]
i am at 500 never got softbanned after api change

**Comment by Kidnub** [comment]
i use 10km/h cause it is from logic cause a bike ride who watch pokemon on phone cannt ride 15-20 Km/h without any big trouble XD (i even had a softban cause same location of both bots xD)

**Comment by drjack6** [comment]
USING ONLY 3 DID THE TRICK

**Comment by xJustx** [comment]
^
