### ISSUE TITLE
Dratini Catch

### ISSUE THREAD

**Issue by AguilaHub** [Ar1i/PokemonGo-Bot#2185]
Its not a real issue but rather a missing feature: 

When I see: Well at position X are 5 Dratini on the radar, lets go there, most of the time I will just catch one cause the pathing moves away from the pokemon. Can I fix this somehow? Or do you have any settings and locations where I can farm them reliably?

TY

**Comment by roooochi** [comment]
what?

**Comment by gitovahere** [comment]
You'll have to set the walking speed to very low in that way the bot will step away but still have time to encounter them and see them in range.

**Comment by AguilaHub** [comment]
Well, the problem isnt that the bot doesnt encounter them when they are in range, but that they dont even come in range. because the bot runs into the opposite direction.

My idea is either a feature (hard way) to set a static path the bot follows or someone experienced who can give me a good Dratini catch setup. Both solutions are welcome!

**Comment by CreativiTimothy** [comment]
Yeah, I would like soemthing like that -- a priority setting to chase the Dratinis (or a certain Pokemon) rather than chasing Pokestops.

**Comment by aquilinachu** [comment]
37.8090041274005
-122.410161495209
Pier 39

I got 150 dratini candies last night and a 100% IV dratini which is now a fully grown dragonite with 3k CP :) Enjoy

**Comment by momo0206** [comment]
@aquilinachu and your moveradius?

**Comment by blaik2k4** [comment]
pier 39 in ca is where i got most of mine too

**Comment by momo0206** [comment]
@blaik2k4 and which move radius ?

**Comment by aquilinachu** [comment]
I keep it at 5000m, you can go smaller if you don't want your char to move too much.

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Austin333** [comment]
What's ur speed also ?
