### ISSUE TITLE
Suggestion and Question

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#2186]
what about an option like

Only use Berry with This Pokemons [x]Dratini [ ] Pidgey [x] Pikachu

every time when i got a berry the bot use inmediatly

and is the egg hatching sistem works??

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
And please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
