### ISSUE TITLE
PLEASE an autostart option where there is no options/config gui popup! Just instant bot startup. 

### ISSUE THREAD

**Issue by iridescently** [Ar1i/PokemonGo-Bot#2187]
Also maybe an auto start and anti close app
maybe even anti delete or rename
almost like malware lel

**Comment by aquilinachu** [comment]
Is it really that hard to press an extra button?

**Comment by kazzaluis** [comment]
:V

**Comment by Midnlght** [comment]
really... lol @iridescently

**Comment by JeCelle** [comment]
just create a shortcut and add "-no gui" to the target.
![image](https://cloud.githubusercontent.com/assets/20881462/17500779/210d1e76-5e0b-11e6-94f5-72153fc50c70.png)

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
