### ISSUE TITLE
* B R E A K I N G* Real difference

### ISSUE THREAD

**Issue by slobro** [Ar1i/PokemonGo-Bot#2188]
Hello,

Can someone explain the real difference between IV and CP? I got a Wartortle of 962 cp and 18 percent IV and a Wartortle with 959 cp and 17 percent IV, Their percent IV both suck... shall I transfer them and wait for a greater one?

Should I transfer my 705 Staryu with 62 percent IV and keep my 580 cp with 93 percent IV?

or delete my 791 cp and 59 percent IV Slobro and keep my 590 cp 94 percent IV...

Catch my Drift, how do you pro guys see this? Whats the line to keep and transfer?

Greetings

**Comment by blaik2k4** [comment]
IV is what you want highest because the higher it is the higher the max cp can be for your pokemon

**Comment by slobro** [comment]
Where do you draw the line...

example.

Slobro 600 cp 70 percent Iv
Slobro 870 cp 40 percent Iv

Is this a math problem or a feeling?

**Comment by aquilinachu** [comment]
Go for IV since those pokemons aren't really worth keeping except the whole PokeDex - Gotta Catch'em All thing. They will all get owned by a Snorlax or a Lapras.

**Comment by slobro** [comment]
What about magicarps?

Mc 181 cp with 61 percent IV
Mc 152 cp with 91 percent IV

Still go for IV???

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
