### ISSUE TITLE
Error Like This

### ISSUE THREAD

**Issue by Versake** [Ar1i/PokemonGo-Bot#2189]
[07:26:56] Error: Pokemon.Go.Rocket.API
[07:27:07] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C
:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login
\GoogleLogin.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Des
ktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 43

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\D
esktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:lin
e 62
[07:27:07] Trying to Restart.

what's the problem? i try on my laptop it works but when I'm trying to use it on my pc it's getting error.
Miracle please :)

**Comment by Pyroman2300** [comment]
Delete it and re-install it. then run it as an administrator. Seems to fix it for everyone.

**Comment by JeCelle** [comment]
"GoogleException: BadAuthentication" have you double checked your google login credentials?

**Comment by Versake** [comment]
@Pyroman2300 um thanks I'm trying
@JeCelle what do u mean by double checked google login credentials sir?

**Comment by Pyroman2300** [comment]
@Versake Have you made sure that your google login info is right?

**Comment by JeCelle** [comment]
I mean, maybe you type your password wrong? Because that's what it looks like based on your error message.

**Comment by Versake** [comment]
I enter my password correctly and i have re-install it but it still error. Any other ways to fix it?

**Comment by Versake** [comment]
@Pyroman2300 @JeCelle okay fixed already thanks for the help
