### ISSUE TITLE
Help: This comes up for both accounts

### ISSUE THREAD

**Issue by shibby1889** [Ar1i/PokemonGo-Bot#219]
![capture1](https://cloud.githubusercontent.com/assets/20709248/17254013/ea362d1c-5567-11e6-83be-1b1dcb26e087.PNG)
I have tried with 2 accounts and cant get either to work now.  I thought the new update would fix it but it hasnt

**Comment by Ar1i** [comment]
Servers probably lagging.

**Comment by shibby1889** [comment]
ok, I mean servers are running great on go, should I just keep it running until something happens cause this happened all day yesterday too

**Comment by 13XxM1CHA3lxX37** [comment]
Maybe try to extract the whole folder. Seems like it's all in Temp and not extracted

**Comment by shibby1889** [comment]
when you say extract the whole folder, I downloaded the update using WinRAR, what else would I need to do.  sorry kind of new to all of this
