### ISSUE TITLE
Bot can find specific pokemons?

### ISSUE THREAD

**Issue by pedromaia1234** [Ar1i/PokemonGo-Bot#2192]

**Comment by aquilinachu** [comment]
If you select every other pokemon on Pokemon - Not to Catch tab, it will pass other pokemons and collect only the ones you want it to capture. If you mean like snipe a specific pokemon, no it won't.

**Comment by pedromaia1234** [comment]
@aquilinachu tnks ;)

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
