### ISSUE TITLE
still can't catch any pokemon

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#2193]
for the past 12+ hours I can get exp from pokestop but not get any pokemon I tried everything and YES i have the newest version

**Comment by sunit1998** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20731094/17501150/9a10ea44-5df9-11e6-9a9b-dd585b2a6e08.jpg)
use this configuration

**Comment by xJustx** [comment]
Any screenshots?

**Comment by Juiche** [comment]
me too. already used that setting

**Comment by gitovahere** [comment]
Please search, it's been answered numerous times. 
Here: https://github.com/Ar1i/PokemonGo-Bot/issues/1930

**Comment by OGcpalm** [comment]
i said I tried everything I have done everything posted on here nothing is working

**Comment by gitovahere** [comment]
Do you get XP from pokestop?

**Comment by OGcpalm** [comment]
yes

**Comment by gitovahere** [comment]
Could u post screenshot of "ITEMS" tab like the one above?

**Comment by OGcpalm** [comment]
https://i.gyazo.com/acb44285b90506eb8e50827bfdb99dac.png

**Comment by gitovahere** [comment]
What kind of errors do you get?

**Comment by gitovahere** [comment]
Other than pokemons getting away...

**Comment by OGcpalm** [comment]
nothing that's it it won't catch any pokemon

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
