### ISSUE TITLE
MEWTWO NOW AVAILABLE??

### ISSUE THREAD

**Issue by Biscuit090** [Ar1i/PokemonGo-Bot#2194]
Pokesniper.com sighted multiple mewtwo's throughout Disneyland and other theme parks! Going to try and use NOX to confirm these sightings!

![mewtwo](https://cloud.githubusercontent.com/assets/20826708/17501146/cbb94f1e-5d90-11e6-9869-c236e39d8bf2.PNG)

**Comment by xJustx** [comment]
Not an issue-

**Comment by xRealMaks** [comment]
Maybe you should use issues like issues and not like a information blog. lol
