### ISSUE TITLE
bot settings?

### ISSUE THREAD

**Issue by kimjongun69** [Ar1i/PokemonGo-Bot#2195]
what are your bot settings like the speed and evolving thing? i set my speed to 100,000 and range 10,000 but nothing will work? also said's i might be soft banned and i try force unban but no work?

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by xRealMaks** [comment]
Use issues like issues. 
Official thread: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
