### ISSUE TITLE
Auto Transfer Issue

### ISSUE THREAD

**Issue by Streakz** [Ar1i/PokemonGo-Bot#2196]
So I let the bot running for an hour, and I found many pokemon are more than 3 (max limit I set before). And this happened for some pokemon not at all, especially zubat, caterpie, weedle.

Anyone has same problem?

**Comment by xRealMaks** [comment]
Make sure you unchecked the checkbox "Keep Pokemons which can be evolved", otherwise the bot keeps all pokemons that you could evolve. (more than you max limit set before)

**Comment by Streakz** [comment]
I think I got the answer, thanks mate

**Comment by Sw3rv3** [comment]
I am having this same issue and I don't see a box for keep pokemons which can be evolved
