### ISSUE TITLE
Cant collect more than 500 Items even when I have 700

### ISSUE THREAD

**Issue by PokeDudeAlf** [Ar1i/PokemonGo-Bot#2197]
498/700 and cant gain anymore.
<img width="480" alt="james" src="https://cloud.githubusercontent.com/assets/20801636/17501342/01435396-5d9b-11e6-8cc1-881d232d900c.png">

**Comment by arjunvegda** [comment]
@PokeDudeAlf Post your Items screenshot here

**Comment by moops44** [comment]
did just setup the items right, maybe u choose to collect max 500 items

**Comment by moops44** [comment]
![ok](https://cloud.githubusercontent.com/assets/20789896/17501926/ad8170c8-5de3-11e6-81e5-11158602d7c6.PNG)
change it then restart bot

**Comment by PokeDudeAlf** [comment]
Deleting the config worked, thx
