### ISSUE TITLE
Cant find pokestop at range xxxx meters

### ISSUE THREAD

**Issue by laxawana** [Ar1i/PokemonGo-Bot#2199]
Please help

**Comment by xJustx** [comment]
Change your location und try it again please.

**Comment by xXSHOOTER-PRXx** [comment]
We can't find any pokestops in a range of 2000m 
Why I already change my location still nothing

**Comment by milanstiano** [comment]
Softban it is.. Wait a minute

**Comment by xXSHOOTER-PRXx** [comment]
It's been 10 min nothing

**Comment by Burrito159** [comment]
I've had this issue for about 2 days. Both with different versions of the bot. Still can't figure it out.

**Comment by laxawana** [comment]
I've been tryin to change my location multiple times.. doesnt work at all
