### ISSUE TITLE
Pokemon got away, when player's level is above 30 using normal poke ball

### ISSUE THREAD

**Issue by haoxuw** [Ar1i/PokemonGo-Bot#2200]
Hello,

GREAT WORK!

A small thing, could you please change the default ball choice to great, or ultra, or better even, add an option?

Thanks!

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
