### ISSUE TITLE
*UPCOMING BAN*

### ISSUE THREAD

**Issue by slobro** [Ar1i/PokemonGo-Bot#2201]
When opening the bot, at the bottem it says, if you run 3 more instances you get a soft ban...

whats an instance?
whats the soft ban?
how do I prevent?

thanks

**Comment by gummyruler** [comment]
@slobro Softban is when you eat ice cream and someone kidnaps you. Nah I'm just kidding man. But seriously though? Why use so many bots 1 should suffice right? It's not as if you're selling accounts for money.

**Comment by slobro** [comment]
I am only using one account! Could it be I accidently logged in while online with my computer bot?

**Comment by Fertigpizza** [comment]
• instance of a program, dont open bot more then 3 times simultaniously.
• period of time while you cant collect pokemons/poke stops
• dont run more than 3 instances and dont hop between spots too far away from each other.

summary?: Always read forum and other topics first instead of posting!

**Comment by JeCelle** [comment]
And here I thought there was an announcement from Niantic that there's a ban wave incoming -_-

**Comment by slobro** [comment]
Ok, thank you the information. Today I was at work while the bot was working and  I accidently had my phoneapp open too for 5 minutes or something. Could that do any harm?

How do I reset everything so I only have the bot running? I have been really carefull with gps locations, nothing that couldn't be done by foot from my home location. ...Only openeded at my work once or twice... and thats 15km from home

**Comment by sunit1998** [comment]
if u accidently opened the app that would have given u a softban for a few minutes as the softban is removed by the bot so no worries ur fine just dont open the app again whe the bot is running

**Comment by slobro** [comment]
Thanks @sunit1998 , so that would mean the owner of the app knows I am using a bot or cheating with the gps location? That doesn't sound much good, right?

**Comment by instinctftw** [comment]
Oh, slobro lol. #slobro

**Comment by slobro** [comment]
start walk from default location... does that mean

it will start from the location I entered or some other location?

**Comment by eblebleh** [comment]
I open the app on the phone while boting, as long as you don't turn on the gps on phone it is fine

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
