### ISSUE TITLE
**Walking a certain direction**

### ISSUE THREAD

**Issue by slobro** [Ar1i/PokemonGo-Bot#2205]
start walk from default location... does that mean

it will start from the location I entered or some other location?

**Comment by shadowahs** [comment]
Default location is the one you entered

**Comment by slobro** [comment]
why is there an option not to start from the location you entered? What location  does it start from then?

**Comment by bkrandy** [comment]
you do start from the location you entered and from that point theres a radius that you choose (5000 meters default) and your bot will walk within that radius from the point you entered

**Comment by sunit1998** [comment]
once all pokestops are covered in 5000m distance you will return back to the location you have selected and will start all over again from there and the cycle goes on

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
