### ISSUE TITLE
*PokeStop* Problem!

### ISSUE THREAD

**Issue by Pixeek** [Ar1i/PokemonGo-Bot#2206]
![issue](https://cloud.githubusercontent.com/assets/20917576/17502436/6b3b5232-5dad-11e6-829f-c348779ad327.png)

why?

**Comment by bkrandy** [comment]
must be a server problem, working for me

**Comment by razalghul** [comment]
![sin titxsulo](https://cloud.githubusercontent.com/assets/20917431/17502531/b9e1af36-5db6-11e6-982c-6eeb425f4eab.jpg)

**Comment by sunit1998** [comment]
try deleting config and start again or check ur movespeed if its too high u will not find any pokestops around you

**Comment by Pixeek** [comment]
@sunit1998  Speed = 10 km :(

**Comment by razalghul** [comment]
It is rare , delete everything and start again turned to lower the speed of movement.

**Comment by fikrirmd** [comment]
change ur IP address or change your pokemon location, it works for me.

**Comment by Sw3rv3** [comment]
Make sure you aren't running more than 3 accts, IP bans stop anything from spawning after 3

**Comment by Pixeek** [comment]
Just have one account. I try everything and nothing works.

**Comment by Sw3rv3** [comment]
close out of it for a little bit and reopen

**Comment by dsRonald** [comment]
I'm having the exact same issue, did you find a solution?

**Comment by xJustx** [comment]
Change your location und try it again please.
If the issue appears again, open a new issue.
