### ISSUE TITLE
Big issue for high level

### ISSUE THREAD

**Issue by hoangtuut** [Ar1i/PokemonGo-Bot#2207]
It doesn't allow to use greatball or ultraball for catching Pokemons. Only Pokeballs are used and that's why I never can catch Pokemons in high level or common Pokemons such as: pikachu, charmanders, squirtel and bulbasaur.

**Comment by motemo77** [comment]
don't make your problems be our problems!

**Comment by lionellex** [comment]
well, you could set your item settings to 0 for pokeball.

**Comment by sunit1998** [comment]
i m level 35 and i never had any problem
![xp per hour](https://cloud.githubusercontent.com/assets/20731094/17502582/ce441612-5e06-11e6-99cb-3d074ec95ff3.jpg)

this is my other acc xp per hour with same setting as my main account

**Comment by sunit1998** [comment]
dont set pokeball to 0 or else no pokemon will be caught

**Comment by lionellex** [comment]
ahhh, got it. thanks m8

**Comment by ineedtostudy** [comment]
@sunit1998 how do you get 745k per hour?

**Comment by SkyWalkerMc** [comment]
@sunit1998 can you share long and lat your location ?

**Comment by dahnoochie** [comment]
Is that xp/hour from the startup of the bot or after some time running?

**Comment by hoangtuut** [comment]
@sunit1998 in your setting, can you catch any charmander, bulbasaur and pikachu???

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
