### ISSUE TITLE
New update.

### ISSUE THREAD

**Issue by mariobros33** [Ar1i/PokemonGo-Bot#2208]
Hi, I just check the new updates came up. Can someone put the new links here? Can't even know what's necessary.

**Comment by lionellex** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2009.8.16%2000.39.rar

click on 'download'

**Comment by mariobros33** [comment]
That's the only thing that I need to change? There's like another 4 or 5 .txt

**Comment by lionellex** [comment]
all i did was i delete the old ver bot and replace this one. and it works.

**Comment by mariobros33** [comment]
Alright thank's working now.

**Comment by Jinnocid** [comment]
![image](https://cloud.githubusercontent.com/assets/20916720/17502672/5af20690-5e1c-11e6-99d6-12b418312e69.png)

another issue

**Comment by ineedtostudy** [comment]
bump

**Comment by xJustx** [comment]
no issue
