### ISSUE TITLE
new problem with only one account ? why and how to solve ?

### ISSUE THREAD

**Issue by oXNARXo** [Ar1i/PokemonGo-Bot#2210]
hey
i have been running 4 accounts since level 1

(one of them is my main wich i used to play normaly with it) ((higher level))

however

it started to show me this problem Note: it was working fine , even if i open it alone with out any other account still same error ! 

**((also i still get 50 xp from pokestops sometimes so i don't think it's softan))**
http://i.imgur.com/jebGKr0.png
![screenshot 77](https://cloud.githubusercontent.com/assets/20825103/17502674/78bee9ce-5df2-11e6-9987-69a39520d17c.png)

**Comment by fikrirmd** [comment]
whenever i get that, i change my location.

**Comment by gitovahere** [comment]
Your IP address is banned for that account. Generate a new IP address.

**Comment by xJustx** [comment]
^
