### ISSUE TITLE
100% probability but still not catching it. Why is this so?

### ISSUE THREAD

**Issue by carrrt** [Ar1i/PokemonGo-Bot#2211]
I dont know what is wrong , i understand pokemon like snorlax or those rare ones gives you a catch rate of <10% sometimes. But honestly even 100% catch rate pokemon are escaping. Why is this so? am i doing anything wrong?

**Comment by razor9302** [comment]
You are softbanned, get yourself unbanned.

**Comment by carrrt** [comment]
Im auto unbanned. But still happening.

**Comment by gummyruler** [comment]
Slow down what's your speed settings? I'm at 100kmph.

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
