### ISSUE TITLE
Server's down?

### ISSUE THREAD

**Issue by pedromaia1234** [Ar1i/PokemonGo-Bot#2212]

**Comment by jmo93** [comment]
Yes, my google acc  isn't working too

**Comment by jmo93** [comment]
Pokemom trainer acc is working

**Comment by starscd** [comment]
i got this problem few seconds ago 

![image](https://cloud.githubusercontent.com/assets/19983125/17502808/6d922f6a-5dc1-11e6-9a29-a7fbe2dc55b2.png)

**Comment by jmo93** [comment]
Now working

**Comment by jmo93** [comment]
Servers are unstable, pls close this issue

**Comment by Pyroman2300** [comment]
Servers are fine http://ispokemongodownornot.com/

**Comment by itsCris** [comment]
now its working

**Comment by jmo93** [comment]
http://www.mmoserverstatus.com/pokemon_go
