### ISSUE TITLE
Stoped working?

### ISSUE THREAD

**Issue by starscd** [Ar1i/PokemonGo-Bot#2213]
![image](https://cloud.githubusercontent.com/assets/19983125/17502799/56557348-5dc1-11e6-8ab4-4d35914fcad8.png)

**Comment by OGcpalm** [comment]
same

**Comment by artasakha** [comment]
same

**Comment by pedromaia1234** [comment]
same

**Comment by timewizard19** [comment]
same here

**Comment by verybadboy85** [comment]
Same

**Comment by ineedtostudy** [comment]
same

**Comment by Thinkinge** [comment]
same

**Comment by Austin333** [comment]
Same

**Comment by RazerSharkz** [comment]
API Change Maybe?

**Comment by ineedtostudy** [comment]
ap didnt change, its working for one of my bots

**Comment by itzjaydon** [comment]
api not changed because necrobot.io still works

**Comment by dragobite** [comment]
One of my 3 bots is also working

**Comment by Jinnocid** [comment]
Log Off then Logged in do the trick ;)

**Comment by starscd** [comment]
guys just close the CMD and open again, working back

**Comment by ineedtostudy** [comment]
http://www.mmoserverstatus.com/pokemon_go

Many servers are down

**Comment by itzjaydon** [comment]
nothing to do with servers

**Comment by OGcpalm** [comment]
itzjaydon does that other bot have the anti ban method thing?

**Comment by razalghul** [comment]
![sin titxsulo](https://cloud.githubusercontent.com/assets/20917431/17502922/c7930c26-5db9-11e6-869d-0953fd03dad2.jpg)

**Comment by itzjaydon** [comment]
yes

**Comment by dragobite** [comment]
Log in/off not working, currently only 1 bot is working for me

**Comment by OGcpalm** [comment]
where do i get it?

**Comment by itzjaydon** [comment]
ill get it link

**Comment by Pyroman2300** [comment]
@razalghul, delete your config folder and set it up again. its an error with your last location.

**Comment by TheMisterAPPLE** [comment]
working for me after close mcd console and reopen

**Comment by TheMisterAPPLE** [comment]
cmd* xD

**Comment by OGcpalm** [comment]
tried all that stuff nothing works

**Comment by itzjaydon** [comment]
@OGcpalm https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.7.8

**Comment by devilexclonz22** [comment]
One of my 3 bots is also working (1)

**Comment by itsCris** [comment]
now its working

**Comment by dragobite** [comment]
@devilexclonz22 same here

**Comment by itzjaydon** [comment]
what did you do to fix @itsCris

**Comment by itzjaydon** [comment]
works now

**Comment by itzjaydon** [comment]
nevermind not working

**Comment by peptidoglikan** [comment]
+1

**Comment by tookieboyyy** [comment]
We will have to wait it out

**Comment by itsCris** [comment]
i just closed the app and I open again. And it works @itzjaydon

**Comment by TheMisterAPPLE** [comment]
yeah same for me

**Comment by dragobite** [comment]
bots seems to be randomly crashing

**Comment by artasakha** [comment]
not works for me yet

**Comment by AguilaHub** [comment]
may it be because new translations were implemented? ^^

**Comment by AguilaHub** [comment]
btw, necro bot doesnt get to log in either

**Comment by DomeSs97** [comment]
same, 1 of 3 bot still work..

**Comment by OGcpalm** [comment]
he shouldn't have released the bot with this many problems can't even use it for more then 5 mins without being at the computer to restart it, + why put egg hatcher option in there if it doesn't even work.

**Comment by Dr-arachnicus** [comment]
Looks like some more sleepless nights for some coders.

**Comment by AguilaHub** [comment]
well for me it worked more than 24 hours... and then it crashed lol
I got quite some exp out of that

**Comment by OGcpalm** [comment]
i have not even been able to catch pokemon for hours upon hours only farming pokestops..

**Comment by artasakha** [comment]
i try the older vercion and it running smoothly

**Comment by OGcpalm** [comment]
i don't have any old verisons :(

**Comment by DomeSs97** [comment]
server are up.. bots works :)

**Comment by Killmachine** [comment]
can't get it to work whatsoever.

**Comment by AguilaHub** [comment]
I can confirm: 08.08 works.... kinda... a lot of exception shit but finally it gets running

**Comment by Killmachine** [comment]
deleted the "Config" file and restarted the bot just now. It is working now.

**Comment by AguilaHub** [comment]
well now its in a loop

**Comment by tookieboyyy** [comment]
Working for me right now, it has been running for 3 minutes

**Comment by tookieboyyy** [comment]
WORKING

**Comment by tookieboyyy** [comment]
It ran 10 minutes+ solid for me, got it again

**Comment by OGcpalm** [comment]
not working for :( how did you guys fix.

**Comment by Asdrubalgp** [comment]
use 07.08 21.04 version. it still works for me

**Comment by AiVo7z** [comment]
Strange. One out of three work, can agree on other posts here. I set it up all over again,all 3 works for a while then crash again. Somehow I always get softbanerror on one of my acc. Sometimes Im softbanned for real, sometimes not. I guess using the bot atm is more riscy then ever. Getting softbanned every 5 min cant guarantee that this acc isnt flagged for further or future bans. Be careful guys.

**Comment by AiVo7z** [comment]
And this were my first softbans ever btw. Botted for weeks with a couple accs and never gotten this before. :(
