### ISSUE TITLE
Error loading pokemon list. error

### ISSUE THREAD

**Issue by kimjongun69** [Ar1i/PokemonGo-Bot#2214]
not sure what this is... but just found it when i came back to my PC.. how to fix?
![dada](https://cloud.githubusercontent.com/assets/20916482/17502968/f3b1aa4c-5da0-11e6-8fb7-8827ab48a8a8.png)

**Comment by peptidoglikan** [comment]
+1

**Comment by bluezerodany** [comment]
I have the same problem

**Comment by kimjongun69** [comment]
but i ran to check my brother pc, and his is running just fine?

**Comment by tookieboyyy** [comment]
Same, mine works for 15 seconds and then get the error - Rinse and repeat lol

**Comment by Sw3rv3** [comment]
server could be down

**Comment by jmo93** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by kimjongun69** [comment]
i dunno about that, my bro's is working tho

**Comment by cameron3911** [comment]
i have the same problem happening right now

**Comment by tookieboyyy** [comment]
We will have to wait it out

**Comment by cameron3911** [comment]
r u guys using your main or second acc?

**Comment by itzjaydon** [comment]
its nothing to do with the servers becuase necrobot is working

**Comment by kimjongun69** [comment]
im using both accounts

**Comment by kimjongun69** [comment]
its working now for me

**Comment by cameron3911** [comment]
[22:53:03] Export Player Infos and all Pokemons to CSV not possible. File seems be in use!

this is what i got

**Comment by itzjaydon** [comment]
+1

**Comment by Sw3rv3** [comment]
working again

**Comment by tookieboyyy** [comment]
@cameron3911 its just when you launch

**Comment by cameron3911** [comment]
what do you mean?

**Comment by itzjaydon** [comment]
this is why i have two bots haha

**Comment by jodirt282** [comment]
Its the pokemon servers guys. I can't even log on my phone. Just wait it out.

**Comment by itzjaydon** [comment]
no its not necrobot is still working

**Comment by tookieboyyy** [comment]
Necrobot does not login

**Comment by itzjaydon** [comment]
im logged in

**Comment by jodirt282** [comment]
Yes it is. I debugged in visual studio. The error is at login.

**Comment by Sw3rv3** [comment]
I closed it out and reopened it is working fine again

**Comment by cameron3911** [comment]
works now

**Comment by itzjaydon** [comment]
@Sw3rv3 same with me then 1min later back to error

**Comment by cameron3911** [comment]
same now its error again

**Comment by tookieboyyy** [comment]
It doesn't work, it works for 15-30 seconds and then error

**Comment by itzjaydon** [comment]
hahaha

**Comment by cameron3911** [comment]
omg zzz

**Comment by jodirt282** [comment]
Just wait guys. The server are jumping from Online to Unstable every 30 seconds. http://cmmcd.com/PokemonGo/

**Comment by itzjaydon** [comment]
![image](https://cloud.githubusercontent.com/assets/20823634/17503162/a82244ca-5de5-11e6-8b2c-7e0c8fa130d8.png)

**Comment by itzjaydon** [comment]
necrobot is working

**Comment by cameron3911** [comment]
how do we download necrobot?

**Comment by itzjaydon** [comment]
https://twitter.com/NECROBOTIO

**Comment by itzjaydon** [comment]
https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.7.8

**Comment by bluezerodany** [comment]
How you use necrobot?

**Comment by itzjaydon** [comment]
same way as this one

**Comment by itzjaydon** [comment]
1) extract the files 
2)open the  application
3)follow instructions shown on cmd

**Comment by cameron3911** [comment]
hey can someone tell me the long and lat of centeral park?

when i put in the cord it said error for some rerason

**Comment by itzjaydon** [comment]
40.771133 lat

**Comment by itzjaydon** [comment]
-73.974187 long

**Comment by cameron3911** [comment]
thank you

**Comment by itzjaydon** [comment]
no problem

**Comment by itzjaydon** [comment]
@bluezerodany there is a extension you can get where you snipe rare pokemon want the video link for tutorial?

**Comment by cameron3911** [comment]
yes please

**Comment by cameron3911** [comment]
and btw 

[23:06:43] (UPDATE) Perfect! You already have the newest Version 0.7.8
[23:06:43] (INFO) Logging in using Google

**Comment by cameron3911** [comment]
it wont load anything else

**Comment by itzjaydon** [comment]
close and reopen

**Comment by itzjaydon** [comment]
https://www.youtube.com/watch?v=bYTa-kUPuAw video for sniper

**Comment by bluezerodany** [comment]
@itzjaydon thanks :+1:

**Comment by itzjaydon** [comment]
@bluezerodany no problem bro

**Comment by tookieboyyy** [comment]
WORKING

**Comment by itzjaydon** [comment]
what is?

**Comment by tookieboyyy** [comment]
This one lol

**Comment by itzjaydon** [comment]
i know been working for the last 10 mins

**Comment by tookieboyyy** [comment]
crazy

**Comment by DemonBytes** [comment]
ari bot dead

**Comment by itzjaydon** [comment]
ok?......

**Comment by bluezerodany** [comment]
yeah it works now

**Comment by Abbasoo** [comment]
Ar1i bot is not dead !

![untitled](https://cloud.githubusercontent.com/assets/20796710/17503473/c62e0608-5df8-11e6-98db-6a577a5a7ade.png)

**Comment by DemonBytes** [comment]
latest version?

**Comment by bluezerodany** [comment]
yes

**Comment by DemonBytes** [comment]
mine looks like that 
![screenshot_2](https://cloud.githubusercontent.com/assets/20744697/17503526/d1a03ff4-5df0-11e6-992d-cfd7735c0712.png)

**Comment by Biscuit090** [comment]
If you're getting that annoying grey text, it's probably your internet speed or you just need to restart the bot. It happens every now and then to me but quickly fixes itself within a minute or two.

**Comment by DemonBytes** [comment]
well. its on a virtual machine over vpn. maybe thats the prob

**Comment by bluezerodany** [comment]
bad loggin maybe

**Comment by DemonBytes** [comment]
seems like the vpn causes it. whatever. servers seem to be down anyways atm. trying to fix that vpn shit

**Comment by itzjaydon** [comment]
mines working fine though

**Comment by itzjaydon** [comment]
![image](https://cloud.githubusercontent.com/assets/20823634/17514486/c9c3fbf6-5e2a-11e6-925d-386a76299c4a.png)

**Comment by xRealMaks** [comment]
Cant fix bad servers ^^
