### ISSUE TITLE
Add option to,

### ISSUE THREAD

**Issue by iridiumkills** [Ar1i/PokemonGo-Bot#2215]
Ar1i! Please implement options that read "Catch Pokemon", and "Farm Pokestops". I would like to be able to turn both either off or on

**Comment by Captnred** [comment]
For suggestions please refer to the forum. Don't post them here.

**Comment by gummyruler** [comment]
close thread not an issue. Suggestions can be made here: 

https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
