### ISSUE TITLE
Somethings wrong

### ISSUE THREAD

**Issue by Austin333** [Ar1i/PokemonGo-Bot#2216]
Xport player infos and all pokemon to CVS not possible ..... then keeps reseting every 10 seconds. Can any one help me ?

**Comment by kayoriceball** [comment]
same here, try using a VPN

**Comment by Austin333** [comment]
How would u go about doing That

**Comment by zyf911** [comment]
same here

**Comment by kayoriceball** [comment]
http://www.cyberghostvpn.com/en_us/download/windows-vpn
download this and run it, it worked for me
