### ISSUE TITLE
POGOprotos

### ISSUE THREAD

**Issue by fabostrong** [Ar1i/PokemonGo-Bot#2217]
This isn't an issue but I'd love it if someone would tell me how these work and how to implement them. Thanks.

**Comment by MaikelxD** [comment]
You asking to steal his content? LOL

**Comment by fabostrong** [comment]
Not at all. I thought the POGOprotos were other ways to get ahead in the game. I can't develop shit lol. I'm not stealing anyone's content.

**Comment by xRealMaks** [comment]
As you said, not an issue, so dont open an issue ^^
