### ISSUE TITLE
PokeStop Problem????

### ISSUE THREAD

**Issue by cerravox** [Ar1i/PokemonGo-Bot#2218]
"We can't find any Pokestops in a range of 5000m!"
.......
Anyone know how to fix this problem? https://gyazo.com/b4441b194549d60a6d5d940a7b6ebf87

**Comment by Sw3rv3** [comment]
you are softbanned  due to too many accesses from a single IP.

**Comment by lifeofkuli** [comment]
i tot we can unban it?
