### ISSUE TITLE
Exception : System.NullReferenceException ?

### ISSUE THREAD

**Issue by wa666** [Ar1i/PokemonGo-Bot#2219]
![pd](https://cloud.githubusercontent.com/assets/20918380/17503294/0f3d48c2-5def-11e6-820b-6b4666dc3205.png)
Hello Do you know what is the problem please?
Thanks in advance.

**Comment by JunpeiL** [comment]
same here

**Comment by AguilaHub** [comment]
we all got this prob, look the other issues.. noone found a reliable solution yet

**Comment by wa666** [comment]
Do you think this is an API change or Niantic that change anything?

**Comment by wa666** [comment]
![wkw](https://cloud.githubusercontent.com/assets/20918380/17503434/0ebeddec-5df0-11e6-85c1-9fe027e36afb.png)
It's strange sometimes the bot works and not after.

**Comment by chuahood** [comment]
same here =(

**Comment by JunpeiL** [comment]
monitoring... restarted the bot, doing good so far

**Comment by wa666** [comment]
JumpeiL What monitoring?
Restarting bot ??

**Comment by JunpeiL** [comment]
lol, just say i will keep my eyes on the bot cmd windows

**Comment by tookieboyyy** [comment]
It ran 10 minutes+ solid for me, got it again

**Comment by wa666** [comment]
Okay okay..

**Comment by chuahood** [comment]
hmm. did i update the bot wrongly? just need to download the lastest build right and copy your old config file?

**Comment by wa666** [comment]
A setting has days bot will probably tomorrow..

**Comment by JunpeiL** [comment]
solid 10 mins for me.....

**Comment by wa666** [comment]
:(

**Comment by CYB3R0ID694** [comment]
API Patched.. 😐😑👿

**Comment by wa666** [comment]
Yes.. Niantic shit!

**Comment by wa666** [comment]
![tt](https://cloud.githubusercontent.com/assets/20918380/17503691/1c8d0c94-5df2-11e6-9126-d1f5cc12dd7b.png)
his works again me :c
