### ISSUE TITLE
starting agian in 10 seconds ?

### ISSUE THREAD

**Issue by rangar305** [Ar1i/PokemonGo-Bot#2220]
it works for moments a time than it says starting in 10 seconds
when i restart the bot i get a diffrent error followed by the same thing starting in 10 seconds
https://cloud.githubusercontent.com/assets/20918428/17503483/00e36364-5da5-11e6-9f35-f77613b9244b.PNG

**Comment by tookieboyyy** [comment]
Just wait it out

**Comment by CYB3R0ID694** [comment]
M confirm that Nantic just patched APi again..

**Comment by shengzie** [comment]
having the problem also on my other account but the other 4 is working eprfectly fine

**Comment by rangar305** [comment]
again :( damn and she just posted her latest update like 4 hours ago nantic are a bunch of try hards lol

**Comment by Snorlax16** [comment]
What location do you use?? @rangar305

**Comment by thepeople03** [comment]
gg pokemon go patched it again? cuz im also wondering why im getting the "starting again in 10 seconds error." ?anyone knows why and how to fix? o3o

**Comment by Abbasoo** [comment]
@CYB3R0ID694 @thepeople03 #2226

**Comment by rangar305** [comment]
yea it was the servers but now there back up and working again :D

**Comment by Asdrubalgp** [comment]
use 07.08 21.04 version. it still works for me
