### ISSUE TITLE
my other account is having this issue for a while now 

### ISSUE THREAD

**Issue by shengzie** [Ar1i/PokemonGo-Bot#2221]
![2v3rqv2rv2v2v23vr23vr2](https://cloud.githubusercontent.com/assets/15166056/17503606/ae4d97da-5e23-11e6-895b-2219e807350e.jpg)

the other one seems working perrfectly fine

**Comment by xRealMaks** [comment]
Get the newest version. If your issue is still there open a new issue, so we can get rid of old/already fixed issues
