### ISSUE TITLE
Please Help/Bitte Hilfe

### ISSUE THREAD

**Issue by Fastnrg** [Ar1i/PokemonGo-Bot#2222]
Kurz und Knapp:
Mein Bruder hat an seinem pc einen bot am laufen.
Ich habe 2 Bots an meinem PC am laufen.
Bei einem kommt immer das.
![unbenannt](https://cloud.githubusercontent.com/assets/20918759/17503659/e528de90-5df1-11e6-8678-d826ff5e15df.JPG)

**Comment by DomeSs97** [comment]
delej config folder, and run as admin

**Comment by DomeSs97** [comment]
delete*

**Comment by Abbasoo** [comment]
It's WORKING now "the poke servers was down"
