### ISSUE TITLE
The bot works for me and you?

### ISSUE THREAD

**Issue by wa666** [Ar1i/PokemonGo-Bot#2223]
![tt](https://cloud.githubusercontent.com/assets/20918380/17503661/e95026c2-5df1-11e6-8f01-bfdd8e71d9e1.png)
The bot works for me and you?

**Comment by Abbasoo** [comment]
Working.

**Comment by OGcpalm** [comment]
what hell :( how

**Comment by wa666** [comment]
Give us further notice people using the bot.

**Comment by Qurus1** [comment]
Inventory full

**Comment by wa666** [comment]
:p

**Comment by lifeofkuli** [comment]
not working....

**Comment by xRealMaks** [comment]
Not an Issue ^^
