### ISSUE TITLE
razzberry

### ISSUE THREAD

**Issue by roynarddd** [Ar1i/PokemonGo-Bot#2227]
how to change the razzberry use for pokemon ? like using razzberry for cp 1000 and iv 80 or something like that. i didnt find the config which can change this razzberry setting.
because my berry always running out everytime. even for a bad pokemon

**Comment by bkrandy** [comment]
you cant change it but an option wouldnt be a bad idea, noticed my bot uses them on pidgeys or whatever that seems to be around 400cp

**Comment by Captnred** [comment]
You can't change this, the bot automatically does it. It's part of how it's configured. Also this is not an issue please close this thread.
