### ISSUE TITLE
It's working now!

### ISSUE THREAD

**Issue by lucasxvieira** [Ar1i/PokemonGo-Bot#2229]
for some reason the error is gone for me, anyone else??

![untitled-1](https://cloud.githubusercontent.com/assets/20726859/17504417/e77db5f8-5db5-11e6-80ae-c1554c6e244f.jpg)

**Comment by zackbond** [comment]
@lucasxvieira  you use old or new bot ???

**Comment by lucasxvieira** [comment]
I'm using the new one and it's working perfect now! i was having the problem too, but now it's fine! @zackbond

**Comment by zackbond** [comment]
![image](https://cloud.githubusercontent.com/assets/20852122/17504394/1984073a-5e2b-11e6-9d5f-b8a33ee35565.png)

**Comment by FallenAvenger** [comment]
#2110

**Comment by CYB3R0ID694** [comment]
M confirm it's working

**Comment by DomeSs97** [comment]
is work from 8.8.2016 2:00 AM - in the presence .. with 1 connect loss..

**Comment by Xzky** [comment]
Thanks to the authors for the great work, apreciate it a lot!!
