### ISSUE TITLE
bot no transfer pokemon

### ISSUE THREAD

**Issue by Luxor1945** [Ar1i/PokemonGo-Bot#2230]
i have a problem with the bot. the bot not transfer low pokemon.

**Comment by patipakdeeying** [comment]
i have this problem too ,

**Comment by joker041913** [comment]
problem with transfer when putting
Max.CP and Max.IV to transfer
it just transfer everything even when Max.IV is set to 80+ %

**Comment by xRealMaks** [comment]
Make sure you unchecked "Keep Pokemons which can be evolved"
