### ISSUE TITLE
Why The API Not Works For ME ?

### ISSUE THREAD

**Issue by fourmansyah** [Ar1i/PokemonGo-Bot#2231]
<a href="http://imgur.com/i58K0S2"><img src="http://i.imgur.com/i58K0S2.jpg" title="source: imgur.com" /></a>

**Comment by Luxor1945** [comment]
Soft ban?

**Comment by fourmansyah** [comment]
i try Force Unban But It Still Like This

**Comment by ineedtostudy** [comment]
wait 10-15mins

**Comment by maksim2047** [comment]
![gdfdh](https://cloud.githubusercontent.com/assets/20919595/17504649/71484a74-5e2d-11e6-9966-4e606c27529e.png)
HELP

**Comment by maksim2047** [comment]
![gdfdh](https://cloud.githubusercontent.com/assets/20919595/17504670/abbf1c5a-5e2d-11e6-9479-2f7d4f8e6a14.png)
HELP

**Comment by eLDeMe** [comment]
restart your modem/router

**Comment by Asdrubalgp** [comment]
use 07.08 21.04 version. it still works for me

**Comment by pokerave** [comment]
I will try to help., when i had this issue I transferred to a different state, seems to solve the issue to me, after a while, you can comeback to that location, 2-3 hrs, give it a day to be sure.
