### ISSUE TITLE
Pokemon get away

### ISSUE THREAD

**Issue by shahroozal** [Ar1i/PokemonGo-Bot#2233]
So I got the last update but the bot can not capture any pokemon and they get away with the first throw. Just like a softban but the bot detects no softban and force unban doesn't do anything.

**Comment by gummyruler** [comment]
Make sure you have plenty of pokeball they escape of course if you don't have pokeball. And the loop will keep running making you get stuck there. I have mine set at 35.

 /closethread.

**Comment by shahroozal** [comment]
@gummyruler I have more than 100 Ultraballs...

**Comment by FallenAvenger** [comment]
dude he just said make sure u have pokeball too. set like 10 pokeball 20 greatballs or something

**Comment by shahroozal** [comment]
Worked. Thanks guys.
