### ISSUE TITLE
Transferring Best

### ISSUE THREAD

**Issue by PureDizzi** [Ar1i/PokemonGo-Bot#2236]
Please make it transfer from lowest to highest IV when there are duplicates. I would like to keep my best even though it's not passed the threshold.

**Comment by JunpeiL** [comment]
+1

**Comment by eLDeMe** [comment]
+1

**Comment by DomeSs97** [comment]
+1

**Comment by PureDizzi** [comment]
Bot just transferred my 81% Pidgeotto, which is hard to come by.

**Comment by tayhr** [comment]
+1

**Comment by chusski** [comment]
+1

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
