### ISSUE TITLE
Bot only use normal Pokeball

### ISSUE THREAD

**Issue by astrostra** [Ar1i/PokemonGo-Bot#2237]
Even when you don't have any Pokeballs left in your bag (the normal ones) the bot think he's throwing one... explaining the error ''...got away while using a pokeball.''

You need the restart the rotation between every ball so when you don't have any normal left he can switch thru the great or ultra pokeballs.

Hope that'll help some people understand what really happens here.

**Comment by PureDizzi** [comment]
Ye, took me a moment to figure out why the Pokemon were getting so good at juking. Can you not check what's in your inventory? if ( pokeball > 0 ) { throw ball } else { please don't }

**Comment by cacaz** [comment]
well yes it doesnt use great or ultraballs even i deleted all normal pokeballs from my inventory. it just uses razzberry and pokemon goes away. 
is there any solution to force it to use great or ultra balls?

**Comment by Arkinslize** [comment]
It's working for me. It recycles correctly my items according to my setting, so the bot always have 30 pokeballs. It also use Great and Ultraballs normally.

**Comment by xRealMaks** [comment]
The bot catch all pokemons < 500CP with normal pokeballs, so make sure you got enough of them ;)
