### ISSUE TITLE
dratini location?????

### ISSUE THREAD

**Issue by yashmhatre** [Ar1i/PokemonGo-Bot#2238]
Not n isssue anyone know DRATINI nest LOCATIONS

**Comment by astrostra** [comment]
San Francisco, Pier 39.

**Comment by Pyroman2300** [comment]
STOP POSTING THIS, GO TO GOOGLE.

Pokevision alternatives
http://pokemonradargo.com
http://Pokegofind.net
http://fastpokemap.com
http://Skiplagged.com/Pokemon
http://easypoke.com/
https://map.siakbary.my.id/
https://pokestumble.com (not sure if its working yet or not)

Sniper sites
http://pokesnipers.com
http://pokezz.com
http://pokespawns.be/
http://pokewatchers.com/
http://pokesniper.report-service.xyz/
http://pokesniffer.com/

Nest
http://pkmngotrading.com/wiki/Nests

**Comment by OGcpalm** [comment]
pier 39 isn't a location just tried it nothing there but magikarp

**Comment by yashmhatre** [comment]
ya need a perfect location these sites to dont show correct

**Comment by momo0206** [comment]
When you farm at Pier 39, which Speed and Moveradius settings do you have?

**Comment by Captnred** [comment]
This is not an issue please close this thread.

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
