### ISSUE TITLE
Bot not evolving the pokemon

### ISSUE THREAD

**Issue by wai0324** [Ar1i/PokemonGo-Bot#2239]
the bot won't automatically evolve any pokemon even after ticking the option "evolve pokemon when enough candy"

**Comment by wrobe06117** [comment]
you need to tick the pokemon you want to evovle on the pokemon tab of the bot

**Comment by wai0324** [comment]
okay thanks for the help and quick reply

**Comment by Captnred** [comment]
Please close this thread as your issue has been solved
