### ISSUE TITLE
Softban on all Accounts after Update .

### ISSUE THREAD

**Issue by Joxiii** [Ar1i/PokemonGo-Bot#224]
I download the new Update and after 1 min. 

http://prntscr.com/bz46gb

Unban not work.

**Comment by Ar1i** [comment]
Post a bigger Screen, with more Informations.

**Comment by Kelendris** [comment]
I get Softbann too ... dont have screen, because i closed

**Comment by Joxiii** [comment]
me too

**Comment by andrekkn** [comment]
me too

**Comment by Sinan102** [comment]
I did get ( i did not delete config folder )

**Comment by Doberok** [comment]
and which version to download? I 1.0.2.9 and no ban

**Comment by Hitra** [comment]
![softban](https://cloud.githubusercontent.com/assets/20727686/17254627/d13de842-55b5-11e6-9480-ef1d6375042c.JPG)

softban and after restart cant find pokestops

**Comment by gnzl0o** [comment]
can i bot two accounts? or you dont advise me taking the risk

**Comment by Joxiii** [comment]
> can i bot two accounts? or you dont advise me taking the risk

Normal yes ^^ never had problems with 4 Accounts

**Comment by plowzey** [comment]
The unbanning works by spinning a pokestop 40-50 times, you're getting this error because you aren't close enough to any pokestops to spin them.

**Comment by 13XxM1CHA3lxX37** [comment]
Let the bot work, it will unban you itself.
You get unbanned if you move around and simulate a human being that is walking. Just try to not change locations that rapidly or let the bot walk you to your desired location
