### ISSUE TITLE
How to force unban

### ISSUE THREAD

**Issue by M31860** [Ar1i/PokemonGo-Bot#2240]
Hi
Sorry for this question;)
How do i find the button force unban?
Its under the pokemon list right? How can i open the pokemon list? it should open when i start the bot or am i wrong now?

**Comment by DomeSs97** [comment]
you must in GUI press "Checkbox" for Pokemon list GUI.. will start when you save config

**Comment by wrobe06117** [comment]
gui on general tab of the bot when you start it

**Comment by M31860** [comment]
Thanks;)
Its incredible that i did not see it:D

**Comment by Captnred** [comment]
Please close this thread as your issue has been solved.
