### ISSUE TITLE
after patch only low pokemons?

### ISSUE THREAD

**Issue by eliteknight** [Ar1i/PokemonGo-Bot#2242]
Hello,

caught someone after the new pokemon go patch a high lvl pokemon?
Im found only low lvls with low cp....
Nothing over 2k+ ...

**Comment by OGcpalm** [comment]
where the fuck did you ever find 2k+ wild pokemon to begin with?

**Comment by eliteknight** [comment]
Found many Pokemons of these...

**Comment by jodirt282** [comment]
What level are you? :O

**Comment by eliteknight** [comment]
33

**Comment by jodirt282** [comment]
Make sense. Im 23. Got a Jolteron 1.3k like 5 minutes ago.

**Comment by eliteknight** [comment]
but now only crap...

**Comment by Scantraxzu** [comment]
lvl 33? thats almost impossible to a human lol, u better slow down that botfarming :)

**Comment by pokerave** [comment]
I think new patch from Pokemon go V.033 make it harder to farm. (I THINK)

**Comment by eliteknight** [comment]
Im thinking NY is not more good to farming

**Comment by Scantraxzu** [comment]
just farm in a city close to you cause if the bot goes down for some reason you can still play without any bans

**Comment by eliteknight** [comment]
never play on handy my city is NY^^

**Comment by Captnred** [comment]
This is not an issue please close this thread.
