### ISSUE TITLE
who can explain transfer function ?

### ISSUE THREAD

**Issue by patipakdeeying** [Ar1i/PokemonGo-Bot#2243]
who can explain transfer function ?

1.Max. CP to transfer what does it mean ?
2.Max. IV to transfer what does it mean ?

Thank you for help :D

**Comment by eliteknight** [comment]
CP = Combat Power of your Pokemon
IV = is an internal value with attack defense and stamina, with additional points on these skills.
max 15 points!
The % value indicates how perfect your Pokemon is 15-15-15 = 100%

**Comment by pokerave** [comment]
1. MAX CP = 1000 - If you have 2 pokemon it will transfer pokemon with LESS 1000, ELSE overridden with IF you have 
2. Set your MAX IV = 90% It will keep all pokemon with 90% IV

**Comment by patipakdeeying** [comment]
ok i understood thank you sir :)

**Comment by gummyruler** [comment]
Close thread please.
