### ISSUE TITLE
Did they change API again?

### ISSUE THREAD

**Issue by sarnic** [Ar1i/PokemonGo-Bot#2245]
Hi Guys,

well since this morning I get again the same problem before ur update of the bot. Did they change the API again?

![image](https://cloud.githubusercontent.com/assets/1611693/17506201/3caa42ac-5e07-11e6-9c8f-751748f3df5e.png)

**Comment by totedan** [comment]
Same here!

**Comment by pokerave** [comment]
Let me Help.

I had this issue, I had a soft ban then when bot unbans me there are no more pokestop within xxxxxm
What I did was transfered to a different state(location ei, from NY - CA),

then just come back 2-3 hrs in the same spot, make it a day to be safe.

**Comment by akangnduz** [comment]
that soft banned IP...simply restart router or vpn to change your IP

**Comment by Melancolie** [comment]
Are you sure that's what's happening? @akangnduz 
The servers are not stable, maybe that could be the problem

**Comment by offroadfreak8582** [comment]
Can someone tell me if IP block is temporary?

**Comment by DemonBytes** [comment]
i use 2 bots now. since that it works again

**Comment by Captnred** [comment]
To answer the question no they did not change api again. It's a soft ban use the force unban feature. Softbans are always temporary. Please close the thread.
