### ISSUE TITLE
[Suggestion] UI themes?

### ISSUE THREAD

**Issue by majorvegas** [Ar1i/PokemonGo-Bot#2246]
It might be a stretch to ask but is there anyway we could get themes for UI components? Personally I'd like a darkened theme for things like the pokemon list and the actual log.  Just something to mute the colors and white-ness would be greatly appreciated.

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread
