### ISSUE TITLE
how to snipe pokemon?

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#2248]
when I change my location for the pokemon off pokesnipers i can't catch it because I'm obviously softbanned? so what do I need to do so I can catch it?

**Comment by pokerave** [comment]
do not use the bot while sniping?

**Comment by OGcpalm** [comment]
what do you mean?

**Comment by eliteknight** [comment]
not possible without softban.
But the bot unban you...

**Comment by OGcpalm** [comment]
the problem is it will try to catch the pokemon right away before I can get unbanned

**Comment by OGcpalm** [comment]
2 other people said they used the site to snipe pokemon thought maybe there a trick to use or something

**Comment by pokerave** [comment]
1. ask the sniper developer you are using.
2. im using sniper too BUT ONLY WHEN my ACCOUNT on the BOT IS NOT IN USE.
3. check your SNIPER location from your LAST LOCATION.

**Comment by eliteknight** [comment]
?
When you port to a location...the bot are unban the softban and catch the pokemon if is possible.
No pokemon on the location no catch...

**Comment by OGcpalm** [comment]
I'm confused as f to be honest I am using this website http://pokesnipers.com/ and putting the coords into the bot, what do you do ?

**Comment by eliteknight** [comment]
and where the problem?

**Comment by pokerave** [comment]
You have a different way of sniping.. lol use a sniper app.

**Comment by OGcpalm** [comment]
poke you are using a program to snipe pokemon?

**Comment by pokerave** [comment]
@OGcpalm YES

**Comment by instinctftw** [comment]
@pokerave   do tell, i have a iphone and android

**Comment by OGcpalm** [comment]
@pokerave yes please do

**Comment by akangnduz** [comment]
1 .go to http://pokesnipers.com/ 
2.copy paste location
3.start bot then quickly push force unban button hope that it will unban 1st before it encountered the rare pokemon
4 you got dragonite LOL

**Comment by gummyruler** [comment]
That lapras though it's uncatchable.

**Comment by akangnduz** [comment]
lapras 2 month error

**Comment by jief78** [comment]
the best is to use pokesniper v2 1.11 for sniping pokemon in addition to pokesipers.com
 but make sure your bot is closed before sniping 

https://mega.nz/#!KU9hBSwL!7S2rFnMh-itMMQdVCg9XOzJrfgvGsJz1ivHXm05kgZQ

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566079-pokesniper2-pokemon-sniper-catch-any-pokemon-no-matter-where-you.html

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
