### ISSUE TITLE
No pokestops?

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#225]
![screenshot_5](https://cloud.githubusercontent.com/assets/20727615/17254355/d1cc3ab2-55b4-11e6-858a-9948dc769ee5.png)

**Comment by Logxn** [comment]
Try setting your location to something else then default

**Comment by gnzl0o** [comment]
already try it before it did not work

**Comment by Logxn** [comment]
Deleting lastcoords.txt and setting it to a new location needs to work.
Other then that simply wait. It will fix itself.

**Comment by gnzl0o** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/20727615/17254582/a55df6e0-55b5-11e6-8aa0-68d2a8120729.png)

what about this error?, ill try moving it somewhere else near by

**Comment by gnzl0o** [comment]
its working! :100:

**Comment by WKKevinC** [comment]
Same issue like gnzl0o, it doesn't find any Pokestops

**Comment by Logxn** [comment]
@WKKevinC 

Deleting lastcoords.txt and setting it to a new location needs to work.
Other then that simply wait. It will fix itself.

**Comment by 13XxM1CHA3lxX37** [comment]
Probably a server issue

**Comment by Ar1i** [comment]
^this.

**Comment by WKKevinC** [comment]
Thanks a lot!

Same issue happens in 30 version.

On Jul 30, 2016, at 12:18 AM, Logxn <notifications@github.com<mailto:notifications@github.com>> wrote:


@WKKevinC<https://github.com/WKKevinC>

Deleting lastcoords.txt and setting it to a new location needs to work.
Other then that simply wait. It will fix itself.

-
