### ISSUE TITLE
Exception: System.Net.WebException

### ISSUE THREAD

**Issue by adrian1999** [Ar1i/PokemonGo-Bot#2250]
Everytime i open the bot, it work for a few second and it starts to repeat this message 

![pokemon go bot error ps1](https://cloud.githubusercontent.com/assets/20921017/17506943/54b7bb80-5e3f-11e6-853c-7dc5da98864c.png)
![pokemon go bot error ps2](https://cloud.githubusercontent.com/assets/20921017/17506954/6374ec56-5e3f-11e6-8e31-138412971719.png)

**Comment by Kranios** [comment]
I have the same problem
