### ISSUE TITLE
Can't farm xp from pokestops.

### ISSUE THREAD

**Issue by derekurizar** [Ar1i/PokemonGo-Bot#2252]
Hi , I can't farm xp from pokestops but if I play in my cellphone I can.

**Comment by b3shoy** [comment]
screenshot?

**Comment by derekurizar** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/20921579/17507581/ad3bb1ca-5dcd-11e6-97b7-ff2c68e75651.png)

**Comment by dadaxd** [comment]
same problem... gleiche problem

**Comment by dadaxd** [comment]
warten und neustarten, dann geht es wieder!

wait 1h and start again... now its work!

**Comment by b3shoy** [comment]
maybe resetting your router can help, don't know for sure.
Are you having 3 or more bot instances running at same time?
