### ISSUE TITLE
why always soft ban help !!

### ISSUE THREAD

**Issue by alvarokanzu** [Ar1i/PokemonGo-Bot#2253]
any solution for always get soft ban and then after close bot taraaaaa ! ! !
![asdasd](https://cloud.githubusercontent.com/assets/20921321/17507026/78c9633c-5e37-11e6-8311-2bbbce03fa5c.jpg)

**Comment by b3shoy** [comment]
That's not a softban at all, it seems that the server is having issues/not responding.

**Comment by alvarokanzu** [comment]
@b3shoy this not working for unbanned method can't farm 
![qweq](https://cloud.githubusercontent.com/assets/20921321/17507367/798706b0-5e39-11e6-9ac3-a0e6cf550b12.jpg)

**Comment by pilota56** [comment]
Turn Off for 10 Minutes should help

**Comment by totedan** [comment]
Router reset -> New Public IP solves your issue!

**Comment by M31860** [comment]
i have this problem when i use 3 bots at the same time...

**Comment by alvarokanzu** [comment]
Already I tried your suggestion but the results are the same

**Comment by alvarokanzu** [comment]
i just 1 only runing bot and get always soft banned

**Comment by pilota56** [comment]
Change the Location

**Comment by elenex23** [comment]
i cant get even 2 bots running without ban. i constantly am refreshing ip. I will try new locations but I doubt it will fix.

**Comment by TrainerNr1** [comment]
Servers are unstable. Wait a little bit. No fault of the bot.

**Comment by alvarokanzu** [comment]
I use HSS vpn and now I have been able to use the bot to perfection done ! !

**Comment by lovakosh** [comment]
So we need to use VPN now to use the bot?
Can you share your VPN clinets? (link)
Thanks.

**Comment by alvarokanzu** [comment]
yap i use hotspot shield vpn search on google to download

**Comment by petetpetet** [comment]
to download Hotspot shield go to http://l.gohss.co/share, and download the shield, u can try free trial first @lovakosh

**Comment by lovakosh** [comment]
It's free for one day.
Anyway i'm getting soft ban even with the VPN when I run more then one instance.

**Comment by xRealMaks** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
