### ISSUE TITLE
Can't find any PokeStops 

### ISSUE THREAD

**Issue by Gin520** [Ar1i/PokemonGo-Bot#2255]
had been unable to do any botting, it kept on saying "We can't find any PokeStops in a range of ######m"
I tried different location, doesn't work
I had slow down to 30 to 50km, doesn't work...
I tried to force unban, doesn't work

**Comment by Montrazul** [comment]
Did you download the latest version?

**Comment by Gin520** [comment]
yup
latest one is 1.0.8.2 right?

**Comment by Montrazul** [comment]
Yes. Im running it right now and it works perfectly. Reset your Router to get a new IP. Restart your computer also and try again.

**Comment by pilota56** [comment]
And wait 10 Minutes, then the Softbann should be gone.

**Comment by offroadfreak8582** [comment]
If I understand correctly IP block is temporary? I have the same issue.

**Comment by marcop888** [comment]
yeah me too

**Comment by pilota56** [comment]
I think so. I also had a Softbann because of to many Bots (IP Bann) and after 10 Minutes i startet the Bot and it works. Dont start all Bots the same time, only evere 2 Minutes. For me, only 2 Bots work at the same time, if i start the third, i get a softbann.

**Comment by Gin520** [comment]
tried what you guys suggested, still not working.
And It was running OK early this morning, and then it suddenly can't find any Pokestops.
Why would my IP suddenly got banned. 

I only had one bot opened

**Comment by pilota56** [comment]
Renew the IP or do you have a permanent IP?

**Comment by Gin520** [comment]
using office computer right now

**Comment by pilota56** [comment]
Oh, OK. I think the Softbann is temporary. Wait 10 or 15 Minutes and then it should work.

**Comment by pilota56** [comment]
The "Force Unbann" Button does not work?

**Comment by marcop888** [comment]
its not softban i think.. like Gin520 said.. it was running OK and then Suddenly cant find any pokestops

**Comment by cEhrnsberger** [comment]
Same Problem here.

**Comment by Gin520** [comment]
ok, will just wait about 20 minutes and try again.
Will update after that

**Comment by marcop888** [comment]
it works but 5mnts only and get softban every 5 minutes

**Comment by pilota56** [comment]
Ok, i think ist a IP Bann. I forced the Bann by starting 3 Bots the same time.
![bild1](https://cloud.githubusercontent.com/assets/20906845/17509677/7c4a2986-5e1b-11e6-9dce-31fa680e7cc6.jpg)

**Comment by Ar1i** [comment]
Change location, if you dont find anything there too, change your IP.

**Comment by pilota56** [comment]
After 10 minutes waiting, it works fine with the same location.

**Comment by Gin520** [comment]
ok, it's working fine again now. 
hopefully it won't suddenly ban my IP again. 

Thanks all
