### ISSUE TITLE
normal pokeball issue

### ISSUE THREAD

**Issue by cacaz** [Ar1i/PokemonGo-Bot#2257]
it doesnt use great or ultraballs even i deleted all normal pokeballs from my inventory. it just uses razzberry and pokemon goes away.
is there any solution to force it to use great or ultra balls?

**Comment by pilota56** [comment]
Why, set the normal Balls to 10.

**Comment by cacaz** [comment]
let me try

**Comment by cacaz** [comment]
now working. @pilota56 thanks :)

**Comment by zzzz9999** [comment]
@cacaz if its working CLOSE issue please

**Comment by roooochi** [comment]
close issue pls, 
people really need to check other closed issues to see if their question has already been asked...
sadly this one has been asked wayyyy too many times... waste of time tbh

**Comment by xJustx** [comment]
^
