### ISSUE TITLE
Set my IV to 95% but I dont know which monsters it is

### ISSUE THREAD

**Issue by REDiiiX** [Ar1i/PokemonGo-Bot#226]
Can you please add a list of  IV we get

If I'm away from keyboard and when I come back have to my PC, maybe you can export all the best IV to a notepad
I set my IV to 95% but I do not know which pokemon it belongs to please add this feature

I like powering up pacific Pokemon to get the most potential out of the evolve

**Comment by REDiiiX** [comment]
would this be possble ty

**Comment by Ar1i** [comment]
Under /config/ their is a excel file with informations
