### ISSUE TITLE
[No Issue] New Pokemon Go App version released

### ISSUE THREAD

**Issue by totedan** [Ar1i/PokemonGo-Bot#2261]
**What's New in Version 1.3.0 (iOS)**

Pokémon GO has been updated to version 1.3.0. Below are some release notes and comments:

- Added a dialog to remind Trainers that they should not play while traveling above a certain speed. Trainers must confirm they are not driving in order to continue playing
- Made improvements to the accuracy of a curveball throw
- Fixed a bug that prevented ”Nice,” ”Great,” and “Excellent” Poké Ball throws from awarding the appropriate experience bonuses
- Fixed achievements showing incorrect Medal icons
- Enabled the ability for Trainers to change their nickname one time, so please choose your new nickname wisely
- Resolved issues with the battery saver mode and re-enabled this feature
- Added visuals of Team leaders - Candela, Blanche and Spark
- We're currently testing a variation of the "Nearby Pokémon" feature with a subset of users. During this period you may see some variation in the nearby Pokémon UI.
- Minor text fixes

 **What's New (Android)**
- Added a dialog to remind Trainers that they should not play while traveling above a certain speed; Trainers will have to indicate they aren’t the driver
- Fixed a bug that prevented ”Nice,” ”Great,” and “Excellent” Poké Ball throws from awarding the appropriate XP bonuses
- Enabled the ability for Trainers to change their nickname one time, so please choose your new nickname wisely
- Resolved issues with the battery saver mode on iOS and re-enabled the feature
- Other fixes

**Comment by Captnred** [comment]
Thanks for the update, but this is for issues. Please close the thread.

**Comment by xRealMaks** [comment]
As @Captnred said, this is not an issue. The bot still works fine.
