### ISSUE TITLE
Request unban on first run

### ISSUE THREAD

**Issue by ibazkom** [Ar1i/PokemonGo-Bot#2262]
On next update, Can you please add feature to do force unban on first run? or maybe do force unban triggered by button (no need to wait at next pokestop)? It's really help for us when we want to haunt, thanks..

**Comment by xhalfbakedguy** [comment]
there is a button for that in the pokemon list section

**Comment by ibazkom** [comment]
But, it will do the unban only when player stop on the next pokestop CMIIW

**Comment by AguilaHub** [comment]
I had this idea before, glad u mention it!

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
