### ISSUE TITLE
Detecting softbans?

### ISSUE THREAD

**Issue by Damantium** [Ar1i/PokemonGo-Bot#2263]
I am using one bot and it's walking around at 5/kms and it keeps getting soft banned?

**Comment by Ar1i** [comment]
How many bots do you run? And change your IP.

**Comment by Damantium** [comment]
Just the one, I'll try resetting my router!

**Comment by moops44** [comment]
@Ar1i  ist bei mir auch so, nur ein bot läuft aber ständig softban nach ip reset läuft es bisschen dann wieder bann :/

**Comment by moops44** [comment]
@Damantium servers are unstable
http://www.mmoserverstatus.com/pokemon_go

**Comment by Damantium** [comment]
Would that make softbans a thing at the speed I am going?

**Comment by Waiiim** [comment]
It's probably not even a softban 
Just the servers who are really laggy so it seems that you're softban because the bot can't do anything correctly

**Comment by Damantium** [comment]
Ah okay, I'll close the issue then. Cheers guys!
