### ISSUE TITLE
error loading pokemon list : badauthentication ?

### ISSUE THREAD

**Issue by ikibucukcaner** [Ar1i/PokemonGo-Bot#2264]
![screenshot_1](https://cloud.githubusercontent.com/assets/20923590/17510228/b9ae5152-5e26-11e6-92e7-41a67f3206d2.png)

**Comment by keustii** [comment]
Check your account information

**Comment by HBraga** [comment]
either wrong user name or password input...

**Comment by gummyruler** [comment]
@ikibucukcaner  It means you put the right characters yet you're trying to login on Google while your account is on PTC.  or wrong username.
