### ISSUE TITLE
hatching eggs

### ISSUE THREAD

**Issue by himmelgr** [Ar1i/PokemonGo-Bot#2265]
hatching eggs doesnt work ? (unable to use any incubators)

**Comment by pilota56** [comment]
Yes, it doesnt work. You have to put the eggs manually in the incubator

**Comment by roooochi** [comment]
theres no point in using eggs, youre getting enough pokemon anyways arent you?

**Comment by emilie253** [comment]
we need egg to get rare pokemon ;)

**Comment by DHBios** [comment]
getting rare pokemon is easy when you always using bot, but finding rare pokemon with high IV is hard and we need to hatch our egg to make it easier

**Comment by Captnred** [comment]
There are numerous threads about this please use the search feature. They're working on fixing this please be patient. Please close this thread as this is a known issues.

**Comment by killiandh10** [comment]
if we spped at 10km/h it will make hatch the eggs?

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
