### ISSUE TITLE
Cant catch pokemon

### ISSUE THREAD

**Issue by keustii** [Ar1i/PokemonGo-Bot#2267]
I can famr pokestop but pokemon.while away evry time?
Its from niantics srv or i take ipban ?

Thx

**Comment by L00N1** [comment]
I have the same issue. I set number of pokeballs to 0, since I wanted the Bot to use Greatballs. But it keeps using pokeball and so it can't catch anything. Any solution?

**Comment by ADIMORGAN** [comment]
me 2

**Comment by ADIMORGAN** [comment]
i have 250 ultra balls he use the req dont know how it work but it stoped catch any

**Comment by roooochi** [comment]
you guys need to check other posts before complaining, set all pokeball types to 20 or more...

**Comment by keustii** [comment]
U right. I turn off.pokeball.to 10its work thx guys !!!! :)
