### ISSUE TITLE
IV calculation is off 

### ISSUE THREAD

**Issue by SoloCN** [Ar1i/PokemonGo-Bot#2268]
for example:
Squirtle CP:715 0-12-11 bot gives IV: 36% while the actual IV count should be 51.1%

**Comment by arjunvegda** [comment]
Still not fixed after update @Ar1i 
![image](https://cloud.githubusercontent.com/assets/14841132/17515669/bbab0870-5e07-11e6-952b-057a745b1181.png)

**Comment by arjunvegda** [comment]
I dont think its fixed yet..


![image](https://cloud.githubusercontent.com/assets/14841132/17515759/46c73320-5e08-11e6-829c-67be7200799b.png)

**Comment by SoloCN** [comment]
It's not fixed that's y I opened this issue lol

**Comment by xRealMaks** [comment]
The code for IV caluclation (in the newest version) is:
return (poke.IndividualAttack + poke.IndividualDefense + poke.IndividualStamina) / (45.0) * 100.0;
In your case:
return (0 + 12 + 11) / (45.0) * 100.0;
which is 51.1%
So its already fixed

**Comment by arjunvegda** [comment]
@xRealMaks Then why its different in the pokemon list and in the bot ?

**Comment by arjunvegda** [comment]
@xRealMaks its right above. I am using the newest version.

**Comment by xRealMaks** [comment]
Sorry for that. The IV calculation in the console is not fixed.
I thought you meant in the pokelist.
