### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by Arkinslize** [Ar1i/PokemonGo-Bot#2270]
Hello, i'm french, so naturally i'm using the french version when i'm choosing the settings.

However, there's a problem that had consequences for me since the bot evolved a shitty growlithe whereas i didn't want. Why this mistake of mine? Because of this:

In english, in the Pokemon page, there's a "Pokemon -To evolve" option, whereas in the french version, the same option is translated "Pokemon - A ne pas évoluer", which means "Pokemon- Not to evolve"

So if someone can tell me what is the right meaning of this, so i don't make the mistake again, and maybe fix the wrong translation for the next update.

**Comment by Arkinslize** [comment]
There's also "move radius", which in french should be "rayon" rather than "périmètre", which in this case corresponds to "circumference" in english.

**Comment by JeCelle** [comment]
I'm not french but the in the pokemon tab of the bot, there are three listboxes namely: 
Pokemon not to transfer - pokemon not to catch - and pokemon TO evolve. So the french translation might have gotten wrong by the translator.

**Comment by Gunjha** [comment]
we made an update in the pull request somes days ago but not yet implanted

**Comment by xRealMaks** [comment]
Do a pull-request. Thanks
If you dont know how to do that, you can post it here https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
