### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by puresfplayer** [Ar1i/PokemonGo-Bot#2271]
build keeps throwing my razzberries away. i got from 90 down to 0 due to build. How to make it stop doing that?

**Comment by Waiiim** [comment]
When you open the bot, you have a tab who opens, in that tab there's an icon "Item" click on it and you put the amount of items you wanna keep the rest will be thrown away

**Comment by puresfplayer** [comment]
yeah i did that part. i think i exceeded the max amount of items i can keep. What is the capacity?

**Comment by Damantium** [comment]
350
