### ISSUE TITLE
[Request] VPN Support

### ISSUE THREAD

**Issue by magiccube007** [Ar1i/PokemonGo-Bot#2272]
Would be nice to have a function where you can add a list of vpns in the gui the bot starts using, so you can run more than one bot a time (i even get ip-bannes for using only two bots). Each window should than be using their own vpn.

Hope that is possible.

**Comment by Waiiim** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by Ar1i** [comment]
Currently adding proxy support

**Comment by elenex23** [comment]
can confirm 2 or more bots gets me softban. trying just one for now

**Comment by magiccube007** [comment]
@Ar1i nice ;D
