### ISSUE TITLE
[REQUEST] FAQ for common issues

### ISSUE THREAD

**Issue by cyb0rg01** [Ar1i/PokemonGo-Bot#2278]
It is just a request for an FAQ for common issues, like "My Bot does not catch any Pokemons" or "How many instance of Bots I can run?" and so on.

I could start writing an FAQ after I finished my work at 5pm (GMT +1).

@Ar1i if you like, I could help you finishing it.

**Comment by urangotango** [comment]
@ar1i @cyb0rg01 yea i think this will be an realy nice stuff for all that ppl who dont understand how to work with your bot ;) (idk how they cant understand it ) but i think will be nice.

**Comment by Emmi911** [comment]
Then read through the issues and write it. Ar1i is busy enough with coding

**Comment by cyb0rg01** [comment]
@Emmi911 Thank you for beeing polite.
@urangotango I gonna start writing it and let @Ar1i in some way know when I am finished.

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread
