### ISSUE TITLE
Impossible to catch a pokemon ? :'(

### ISSUE THREAD

**Issue by Spankedude** [Ar1i/PokemonGo-Bot#2279]
Hello ^^

First : Ty Ar1i for your bot, just a good job ! : ) i use it since the beginning and it's the first time i have a problem :p

So, since this morning (since i download the new version of the bot :'( ), the bot can't capture any pokemon, they always run away... and it's not a sofban, because the bot have no problem on pokestop and i just launch pokemon go 5 mn ago, go out and catch a pokemon with no problem, so it's the bot who can't catch pokemon, but... why ? (and no i have instead for pokemon 192 for 250 place ^^)

**Comment by Waiiim** [comment]
Maybe you have 0 pokeballs

**Comment by coolbuddy26** [comment]
yeah keep pokeballs go to items and keep some pokeballs

**Comment by Abbasoo** [comment]
Pokemon servers are laggy || http://www.mmoserverstatus.com/pokemon_go

**Comment by Spankedude** [comment]
ho yeah i have no pokeball anymore, only superball and hyperball, he does not use it ?

**Comment by PokePro21** [comment]
it use only for high cp pokemons

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17512320/d25b1c3a-5e44-11e6-818a-a154ad18f820.png)

**Comment by JeCelle** [comment]
The way it works, the bot will use an ordinary pokeball if the CP of the pokemon to be caught is from 0-499, then a greatball for those pokemons with CP from 500-999, and lastly ultraball for 1000+ CP

**Comment by Spankedude** [comment]
mmmmm ok, so i have to try to have new pokeballs ?

**Comment by Waiiim** [comment]
You have to make space in the item slot for pokeballs, respect the "350" maximum and pokemons will come back to you

**Comment by Spankedude** [comment]
ok ty, it was that, perfect ^^, can delete the topic, ty guys ! :D

**Comment by coolbuddy26** [comment]
close the topic spank beside comment there must be an option

**Comment by gummyruler** [comment]
You have to have ultras or else you will be stuck on a limbo when it comes to high CP pokemon.

**Comment by pFallenAngelq** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/20930591/17523270/f9c4c702-5e27-11e6-942b-b21d3f118c18.png)

Got the same problem and it isn't lack of pokeballs, got 100 poke, 50 super and 50 ultra. Pokemons just keep on going away.

**Comment by xJustx** [comment]
^
