### ISSUE TITLE
Not an issue , question

### ISSUE THREAD

**Issue by Amnzya** [Ar1i/PokemonGo-Bot#2280]
Hello, and thanks for the awesome work u provided the past few weeks :)
The bot is working fine atm, but with the last update i cant see the pokemon's window :( 
it just dont open when i start :(
Any ideas ? :)

**Comment by keustii** [comment]
check  "Enable pokemon GUI List"

**Comment by Amnzya** [comment]
it was checked , i dont know what happend but its working again with the last update :)
thx anyway ^^
