### ISSUE TITLE
Egg Auto Incubate is not working

### ISSUE THREAD

**Issue by Serimert90** [Ar1i/PokemonGo-Bot#2281]
Egg Auto Incubate is not working.. when an egg hatches and there is free slot for default incubate, it does not randomly choose an egg and start incubating auto... Necessary options are ticked

**Comment by Waiiim** [comment]
Yeah we know, that option doesn't work yet, you have to do it manually

**Comment by xRealMaks** [comment]
Will be added/fixed soon.
