### ISSUE TITLE
Excessive usage of raspberries..

### ISSUE THREAD

**Issue by Serimert90** [Ar1i/PokemonGo-Bot#2282]
Bot needs to balance usage between raspberries and  greatball/ultraballs. Bot always use raspberries if it's catch probability  is lower than < %33 with red ball, till it catches the pokemon, it uses raspberry again. I think sometimes it should try again with red or blue without using raspberries. Sometimes after hours 1-2, my all raspberries are consumed even bot finds 30 pokestops in radius..

As i observe, it keeps wasting raspberries for 300+ rattatas and pidgeyss..

**Comment by Madrocker85** [comment]
I have noticed the bot uses a lot of berrys for low Pokemon.

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread

**Comment by Serimert90** [comment]
Maybe it is not a software issue, but functional issue^^
