### ISSUE TITLE
Incorrect [Player Status Update] and Log Texts

### ISSUE THREAD

**Issue by Serimert90** [Ar1i/PokemonGo-Bot#2283]
Item count and pokemon count text infos are wrong
Also when bot uses raspberries, the remaining raspberry info is also wrong.

**Comment by simoniuxxx147** [comment]
me too i have 320 items but bot shows 430

**Comment by k756u** [comment]
count of item infos are wrong, i have 350/350 bot show 250/350

**Comment by GreYzZ** [comment]
Yep can agree to this
Got the same issue
