### ISSUE TITLE
over 700.000 xp/h (on level 34) new record :)

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#2286]
![bot](https://cloud.githubusercontent.com/assets/20746711/17513190/e172e874-5e2b-11e6-82da-dbb2e0eefda7.png)

**Comment by expertepokemon** [comment]
whats the location? :+1:

**Comment by lailaps** [comment]
After 30 mins. you will have average ~220.000 - 300.000, but that bot I used for this isn't good to configure and doesn't have a GUI.

**Comment by expertepokemon** [comment]
but where is it? do u walk 50kmh? or faster? is it a other bot? can u send me the link pls

**Comment by lailaps** [comment]
Haxton
But like I told not very comfortable and a lot of people having problems (mostly you can only run one Haxton, so atm. I run a few VM, every VM with VPN and inside every VM I am using different bots.

Ar1i bot is with best GUI and very nice to configure.
Necrobot is as fast sometimes 10.000 xp/h faster but no GUI and ok to configure.
Haxton is extremely fast 350.000 xp/h often standard, but no GUI, not very good to configure, a few bugs and many people have problems to get it run.

**Comment by lailaps** [comment]
I recommend always, try to level up fast, doesn't matter what kind of Pokemon you have.
Once you are something between level 36 - 40 combine a bot with Autosniper solution and let it run for maybe 8 hours.

After that use Ari1 bot to select best and strongest Pokemon, I only choose >90 IV.
You should need only a few days, no need for login via. mobile phone before.
