### ISSUE TITLE
why is my bot doing this? :O

### ISSUE THREAD

**Issue by ripharambe** [Ar1i/PokemonGo-Bot#2287]
![image](https://cloud.githubusercontent.com/assets/20925417/17513249/304c5df4-5e2c-11e6-9af8-3098d0dabdee.png)

**Comment by pilota56** [comment]
IP Bann, get new IP or wait 15 Minutes. Maximum 2 Bots and do not start at the same time. Min 1 Minute between starts.
Everytime the same post

**Comment by Ar1i** [comment]
Change location, if that dont work try to get a new ip

**Comment by dragobite** [comment]
Having the same issue, any solutions?
Hat jemand eine Lösung?

**Comment by dragobite** [comment]
Wie kriege ich eine neue IP?

**Comment by dragobite** [comment]
Ist die nicht festgelegt, oder meinste proxy?

**Comment by ripharambe** [comment]
Thanks guys :) Waiting a few minutes is the way to fix it :)

**Comment by pilota56** [comment]
Starte deinen Router neu bzw trenne die Internetverbindung kurz. Leute, so schwer ist das doch nicht.
