### ISSUE TITLE
can we change device id manually

### ISSUE THREAD

**Issue by bac123** [Ar1i/PokemonGo-Bot#2288]
everyone use same device id may lead to banned
can we change it?

**Comment by Ar1i** [comment]
everyone use same device id may lead to banned
can we change it?

DeviceID is random. Look at the Source.

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread

**Comment by bac123** [comment]
is it only generate at first time run 
or generate everytime ?
tks for reply

**Comment by gummyruler** [comment]
@bac123 Bottom line is Device id = dynamic, IP = static. You can have 10 VMs yet you will still be caught because of your IP.

Correct me if I'm wrong @Ar1i .

**Comment by Ar1i** [comment]
@bac123 atm every time

**Comment by czokalapik** [comment]
@Ar1i could that cause "Account requires action" problem? #1967

**Comment by bac123** [comment]
can we just edit unique device id and keep it?

**Comment by xJustx** [comment]
You can change it in the source if you want.
