### ISSUE TITLE
best locations ?

### ISSUE THREAD

**Issue by expertepokemon** [Ar1i/PokemonGo-Bot#2289]
i farm 40k at the centrual park, pls better locations 

thx all

**Comment by pilota56** [comment]
Santa Monica Pear Los Angeles. 75km/h 10K, ca. 50K per hour at the Moment, sometimes more.
Disneyland Tokyo, 48K at the Moment 75km/h, 10K.

**Comment by pilota56** [comment]
48.854690, 2.347689 Paris more than 50K

**Comment by ronnyouxia** [comment]
is it ok use speed more than 10?

bout soft banned?

**Comment by pilota56** [comment]
my bots work fine with 75km and also catch pokemon. I get no Softbann. But not more than 2 Bots the same time. And 1-2 Minutes between starting each bot.

**Comment by xRealMaks** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
