### ISSUE TITLE
Auto Incubator 

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#2290]
Ar1i when will be fix auto incubator ?

Thanks

**Comment by Yahook** [comment]
Yes, this feature would be great. I have compared one manual account and one auto account where I only use bot. First one has better pokemons because I incubated few 10km eggs there.

**Comment by emilie253** [comment]
i cant find incubator, so i use only "the first incubator" if ar1i can fix auto incub, it's perfect :)

**Comment by xRealMaks** [comment]
Will be added/fixed soon. See Issue #2281
