### ISSUE TITLE
LOCATION ISSUE

### ISSUE THREAD

**Issue by chickeflonoah** [Ar1i/PokemonGo-Bot#2292]
Maybe you could show in the location map, the move radius which we chose to see where we can see how far we can move from our start location :)

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread

**Comment by xRealMaks** [comment]
thanks, @Captnred
