### ISSUE TITLE
Can't command via bot telegram

### ISSUE THREAD

**Issue by Bangden** [Ar1i/PokemonGo-Bot#2293]
![issue](http://image.prntscr.com/image/f796641f39f64f9f8107bd13bd2318d8.jpg)

On Telegram showing this image
![telegram](http://image.prntscr.com/image/9ed577ea43b747cb992c0ecddb1bfa37.png)

**Comment by ArFGLR** [comment]
You should write your telegram username on bot's setting.

**Comment by Bangden** [comment]
@ArFGLR Thanks solved :+1:
