### ISSUE TITLE
We can't find any pokestops in a range of 5000m!

### ISSUE THREAD

**Issue by jolekko** [Ar1i/PokemonGo-Bot#2294]
Still the same error: "We can't find any pokestops in a range of 5000m!" and bot not working. When you fix it?

**Comment by PokePro21** [comment]
beacuse of ip ban

**Comment by Borosiek69** [comment]
+

**Comment by jolekko** [comment]
What can i do now?

**Comment by Borosiek69** [comment]
pc format

**Comment by 0ny** [comment]
Same problem but i think and hope its just because servers got over 900 ms

**Comment by kalcheat** [comment]
> beacuse of ip ban

Indeed it looks like an ip ban. I restarted my Router and it works again.

**Comment by Captnred** [comment]
It's most likely an ip ban. Try restarting your router, or changing your ip through a vpn.

**Comment by xJustx** [comment]
Change your location und try it again please.

**Comment by xRealMaks** [comment]
IP-Ban and/or pokemon servers slow/down
We got enough issues that solved the problem.
Please use the search function ;)
