### ISSUE TITLE
pokemon not to catch isnt working

### ISSUE THREAD

**Issue by ankhmok** [Ar1i/PokemonGo-Bot#2295]
pokemon not to catch isnt working

**Comment by xRealMaks** [comment]
I tried it out myself and it worked.
In console it should like this: 
![Image of Console](http://i.m4ks.cf/QLTnpbXI.png)
Make sure you run the newest version.

**Comment by ankhmok** [comment]
omg i try it again and im useing V09.8.16 11.51

**Comment by xJustx** [comment]
Do you have enough pokeballs?

**Comment by xRealMaks** [comment]
Delete everything and extract again
