### ISSUE TITLE
I cant catch any pokemon

### ISSUE THREAD

**Issue by Nkeys1337** [Ar1i/PokemonGo-Bot#2296]
Hi,
first of all good job, it is a nice bot.

My problem is the bot catches all the time pokemon but if I want to try it on my own @my home the run away.. is this a softban ?

and sorry for my english :D

**Comment by Abbasoo** [comment]
You will get softban if you were in USA and the next second in Iran :) .

**Comment by xRealMaks** [comment]
When you turn the bot off, the position of the player is saved by niantic. If you use the app now, there is no way for you to travel the long distance in that short period of time, so you will get a softban.

To fix that, search the location where you live with the help of the map, and let the unban script do the work (After that you should not get softbanned if you open the app) Or you just wait a bit until you open the app with your real position.

**Comment by Nkeys1337** [comment]
thanks! :+1:
