### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by velfisadri** [Ar1i/PokemonGo-Bot#2298]
It would be nice if bot would show time to next level with current exp/h next to % of lvl  :)

**Comment by gummyruler** [comment]
Dear sir/mam post suggestions here: (Do not open threads that are not ISSUES this is ISSUE only page)

https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by xRealMaks** [comment]
thanks, @gummyruler
