### ISSUE TITLE
[REQUEST] Add pokemonts to faborite.

### ISSUE THREAD

**Issue by chusski** [Ar1i/PokemonGo-Bot#2299]
[REQUEST] ADD pokemon to faborite list, and bot ignore the faborite list to transfer plz
and ignore to compare for transfer.

Thx very much

**Comment by FAymYs19** [comment]
Not an issue, but a pretty cool feature.

**Comment by Captnred** [comment]
Please use the forum for suggestions and close this issue.

**Comment by chusski** [comment]
can plz give me link of the forum ? plz

**Comment by Captnred** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
