### ISSUE TITLE
Can't Find Pokestops

### ISSUE THREAD

**Issue by marcop888** [Ar1i/PokemonGo-Bot#2300]
Still can't find pokestops.. Server Down?

**Comment by Abbasoo** [comment]
@marcop888 Yes.

**Comment by xRealMaks** [comment]
In NewYork (defalt location), the bot works fine. Try to change the position of the bot.

**Comment by Captnred** [comment]
You could as well be ip banned. Try restarting your router, or changing your ip in a vpn. Also check the server status of pokemon go.

**Comment by testo4life** [comment]
dont use more than 1bot/ip otherwise u get banned !

**Comment by suljo94** [comment]
Go to the config folder and delete the lastcoo file

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
