### ISSUE TITLE
unban nt working ?? 

### ISSUE THREAD

**Issue by loudjedi** [Ar1i/PokemonGo-Bot#2301]
please ! unbaning is not working ! 
it unbun for the next pokemon and i become baned egain

**Comment by Abbasoo** [comment]
@loudjedi Change your IP.

**Comment by lailaps** [comment]
Or close all bots and wait maybe 15 minutes.
Should be also possible!

**Comment by loudjedi** [comment]
thanks i'll try it

**Comment by gummyruler** [comment]
too much bots 2+ = IP softban

**Comment by Captnred** [comment]
If the unban isn't working your ip banned. Change your ip with a vpn or try restarting your router.

**Comment by Bash0070** [comment]
same here,  every pokemon i try to catch its running away , changed ip still same problem , since 2 days , anyone know wts going on plz ?

**Comment by Bash0070** [comment]
if i play without bot , its working fine and i can catch pokemons , only in bot all pokemon are running away

**Comment by loudjedi** [comment]
still not wrking .... unbaning does not work

**Comment by xRealMaks** [comment]
Probably IP ban. Restart your Router or use a VPN. Dont run more than 2 bots at the same time
