### ISSUE TITLE
Lucky Egg usage

### ISSUE THREAD

**Issue by Buddhasama** [Ar1i/PokemonGo-Bot#2302]
The bot seems to be using lucky eggs even tho I selected it not to.

**Comment by Abbasoo** [comment]
There's item number ERROR. So check the app first.

**Comment by Buddhasama** [comment]
No, the console clearly says "Used Item Lucky Egg"  . They are not being thrown away and I definitely didn't select to use them.

**Comment by PippoAe** [comment]
Also, if you set "use lucky egg to evolve" and a lucky egg is already active when you start the bot, the bot tends to spend another lucky egg without checking if one is active already.
