### ISSUE TITLE
Not so many pokemons..

### ISSUE THREAD

**Issue by Roli0116** [Ar1i/PokemonGo-Bot#2304]
I got around 17k xp and 70 pokemons/hour.
Now i barely get 15 pokemons and 4k xp/hour.
Is it an issue or am i in a bad place?

**Comment by gummyruler** [comment]
check pokemon density here:
https://skiplagged.com/catch-that/

**Comment by Captnred** [comment]
It's just a bad place, try new ones. Also since this is not an issue please close the thread.
