### ISSUE TITLE
Pokemon list, Level 30,5 is shown as 35

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#2306]
If a Pokemon has Level 30,5 its shown as Level 35 at Pokemon List.

31,5 and 32,5 is shown correct.

Version 1.0.8.4

**Comment by thepapabear** [comment]
Just try using the latest version 09.8.16 11.51

**Comment by xRealMaks** [comment]
@thepapabear, its the newest version.
@Scanda85  I will forward it. Thanks for your help. :+1:
