### ISSUE TITLE
PokeBalls

### ISSUE THREAD

**Issue by JCortexs** [Ar1i/PokemonGo-Bot#2308]
I know we can use all tipes of pokeball now but they only use them when theres no normal pokeball, its posible to set CP to use diferent pokeballs? 
pokeball  0-300 CP
greatball 300-600
Ultraball 600-???
If its posible to manual modiffy can you guys tell me how?
Thanks!

**Comment by Logxn** [comment]
No you cant manual modify that

**Comment by JCortexs** [comment]
then tthats the only way to use them rigth?
