### ISSUE TITLE
[REQUEST] Favorite pokemon

### ISSUE THREAD

**Issue by CPUzer0** [Ar1i/PokemonGo-Bot#2312]
If it is possible with the current API it would be great to have a way to mark pokemans as favorite to keep them safe from being transferred. The bot apparently replaced my starmie with optimal moveset with a slightly higher CP one that has useless moves, revealing the need for such feature.

**Comment by CPUzer0** [comment]
I also just realized that this is probably not the place for suggestions.

**Comment by gummyruler** [comment]
all requests go here: 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

also close the thread.

**Comment by xRealMaks** [comment]
@gummyruler, thanks for your help, but Requests/Suggestions go here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
