### ISSUE TITLE
not transfering pokemon

### ISSUE THREAD

**Issue by davidp234** [Ar1i/PokemonGo-Bot#2314]
the bot is not transfering any pokemon and there are no options to make it do so like the old ones

any chance you could take alook and maybe re-add the settings??

**Comment by Ar1i** [comment]
there are options in the gui?

**Comment by JeCelle** [comment]
Mine transfer pokemons just fine. 
![image](https://cloud.githubusercontent.com/assets/20881462/17516120/209fada0-5e6f-11e6-921e-51969a77be0a.png)
Do you have "Keep pokemons which can be evolved" option checked? (It should not be checked for it to transfer pokemons that the bot can evolve)

**Comment by davidp234** [comment]
i know that i can do it when im on the pokemon list but i leave the bot running and when i come back i have so many ratattas pidges and weedels (and many more) my pokemon bag is full after about 2 hours

**Comment by davidp234** [comment]
this is my setup
http://prntscr.com/c3i2oy

**Comment by JeCelle** [comment]
Hmmm. your setup in the general tab is fine. What about your settings at the Pokemon tab?
"Max duplicate pokemons" and Max CP and IV to transfer?

**Comment by davidp234** [comment]
omfg how stupid am in i didnt even see the other 2 tabs im so sorry for this

**Comment by Luxor1945** [comment]
+1
