### ISSUE TITLE
all pokmons escape ! unbaning does not wrk still  

### ISSUE THREAD

**Issue by loudjedi** [Ar1i/PokemonGo-Bot#2315]

**Comment by keustii** [comment]
have u some pokeball ?

**Comment by jmo93** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by Abbasoo** [comment]
@loudjedi Change your IP.

**Comment by Bash0070** [comment]
dont change any ip,  just add 20-30 pokeballs , the red balls , you cant catch low cp pokemon without normal pokeball , try it and let me know

**Comment by melody09341** [comment]
i have tried . At now we can't open more than 2 bots  . i set my vpn at japan and location @ 35.672963 , 139.698338  .  2 bots still working but the 3rd bots after i start it will non-stop softban  also the 1st and 2nd bots will starting softban

**Comment by jmo93** [comment]
So if I start two bots on my Computer and my sister one bot on her Computer, there will be problems?

**Comment by melody09341** [comment]
@jmo93  if you are using same IP address you can't  or it will locked your IP to stop your bots untill you changed your IP

**Comment by jmo93** [comment]
Ok thanks

**Comment by melody09341** [comment]
@jmo93 NP :)

**Comment by loudjedi** [comment]
thanks guysss
