### ISSUE TITLE
Transfer not working

### ISSUE THREAD

**Issue by Bash0070** [Ar1i/PokemonGo-Bot#2316]
Transfer is not working properly , its very rare to find the bot transfering a pokemon , any idea how to fix this ?

**Comment by k756u** [comment]
I is not worried of transfer

**Comment by melody09341** [comment]
my 2 accounts still auto transfer may be you re-download builds rar?

**Comment by xRealMaks** [comment]
take a look #2196

**Comment by Bash0070** [comment]
@melody09341 , whats the setting you are putting for iv and cp ?

**Comment by melody09341** [comment]
95% and 1200 cp

**Comment by Bash0070** [comment]
@melody09341 mine is almost the same , and still no transfer , evolve when enoguh candy not checked too. dunno wts going on

**Comment by xRealMaks** [comment]
and before open a new issue open your eyes. The same issue was posted at least 5 times before

**Comment by Bash0070** [comment]
@xRealMaks kindly respect your self little bit before you comment in my post , the post you are talking about has no solution for my problem , evolve if enough candy is not checked anyway  and still no transfer.

**Comment by xRealMaks** [comment]
My bad that i didnt know that you disabled "evolve when enoguh candy"...
Transfer works. If transfer dont work for you, check your settings. 
It was just the first thing i thought when i read your very detailed description of your problem.

**Comment by Bangden** [comment]
Just delete configs folder and try re-login bot.
Dn't forget to Run as Administrator

**Comment by Luxor1945** [comment]
Me too my bot cant not transfer. u have fix for me? thx

**Comment by Hydro420** [comment]
Ive noticed with me personally - If I run the bot too fast it will transfer pokemon only when there is no pokemon around or a bunch of pokestops to hit... It really doesnt take long at all to do it manually, and I would suggest that too as you get to see the hidden stats & keep the better of pokemon.

**Comment by xRealMaks** [comment]
Closed. If the Issue is still a thing after you tried @Hydro420 solution, open a new issue with more information (screenshots, logs etc.)
