### ISSUE TITLE
Softban for nothing since update

### ISSUE THREAD

**Issue by jeremie152** [Ar1i/PokemonGo-Bot#2317]

**Comment by jeremie152** [comment]
i got softban and next never unban and pokemon not transfert the update is sh......

**Comment by Bash0070** [comment]
what do you mean by softban ? are you not being able to catch any pokemon ?

**Comment by pilota56** [comment]
Not more than 2 Bots at the same time.

**Comment by gummyruler** [comment]
Stop using 10 bots at the same time stop at 1.

**Comment by melody09341** [comment]
at the moment you can only use 2 bots @ same IP . If you are using more than 2 bots you will only have softban IP  the 3rd or later bots doesn't work

**Comment by jeremie152** [comment]
i mean my 3 bot got softban try methob 1337 for unban and nothing ban continu

**Comment by jeremie152** [comment]
and pokemon dont tranfert auto too so i stop and wait update^^

**Comment by pilota56** [comment]
Not more than 2 Bots.
Check Settings, my Bot transfer pokemon.

**Comment by jeremie152** [comment]
since few day i up 3 bot and its work i dont need bot only 2

**Comment by jeremie152** [comment]
us can use only 2 bots cause this?

2016. 8. 8
Trainers, Pokémon GO has been updated to version 0.33.0 for Android and 1.3.0 for iOS.

**Comment by jeremie152** [comment]
last question can help for futur ban to have a vpn before open bot?

**Comment by xRealMaks** [comment]
Then they will softban the VPN IP.
A VPN feature will be added soon.

**Comment by jeremie152** [comment]
ok ty
