### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by cerravox** [Ar1i/PokemonGo-Bot#2318]
When I opened the client today it went to the link https://github.com/Ar1i/PokemonGo-Bot and there is a bunch of things everywhere how do i update :/ ?

**Comment by JeCelle** [comment]
Go in here -> https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
and click the latest build you can find, and click download. #1916

**Comment by xRealMaks** [comment]
Open the link.
Click on Builds Only.
Click on the .rar file.
Click download.
Unzip.
Copy new files in the folder of the old bot.
Click on Overwrite.
.
Profit. :dollar:

**Comment by melody09341** [comment]
you need to dl the latest builds only rar file then unzip it and recover your old files
