### ISSUE TITLE
trad list pokemon

### ISSUE THREAD

**Issue by k756u** [Ar1i/PokemonGo-Bot#2319]
Bonjour a tous :) si besoin je peu traduire la liste des pokemon en français je ne trouve juste pas le fichier ou ils se trouvent :)

google trad : Hi all :) I need so little to translate the list of pokemon in French I just do not find the file or they are :)
@Ar1i

**Comment by emilie253** [comment]
si tu pouvais le faire, je serai content)
If you can do it, i will be happy (on ne se moque pas de mon anglais).^^

**Comment by k756u** [comment]
dans ce cas je vais cherche si je trouve quelque part cette fameuse liste ou si quelqu'un peu m'indiquer ou elle est et je fait sa :)


in this case I 'm looking for if I find somewhere that famous list or if someone just tell me where she is and I did her :)

**Comment by OwKuuT** [comment]
UP its can be cool.
Petit coquin tu essaye de te faire une place!

**Comment by OwKuuT** [comment]
Il y a un chat sur github j'aimerais te parler ?

**Comment by k756u** [comment]
non pas du tout :) j'ai a peine quelques notions dans le c et c++, pour moi le partage est le principale! Et si je peu donner un coup de main pour les traduction sa me va :)

not at all :) I barely few concepts in c and c ++, for me sharing is the main ! And if I just give a hand for her translation is me :)

**Comment by k756u** [comment]
non je ne crois pas qu'il y est un tchat sur github

**Comment by k756u** [comment]
voila j'ai fini de traduire tout les pokemon dans 3 langues en espérant que sa servira ;)


here I have finished all the pokemon IN 3 Translate the language Esperant Let his will ; )

[trad pokemon.txt](https://github.com/Ar1i/PokemonGo-Bot/files/409274/trad.pokemon.txt)

**Comment by xJustx** [comment]
Please open a new issue in english :p
