### ISSUE TITLE
Error 0xc000007b in Windows 7

### ISSUE THREAD

**Issue by Bnt5** [Ar1i/PokemonGo-Bot#2320]
Hello

I have a problem !  I wanted to download your bot on Windows 7 !
I extract it file by Winzip ! But when i want to launch PokemonGo.RocketAPI.Console a Error appears !
Error 0xc000007b ! Do you have the solution

**Comment by JeCelle** [comment]
Hi,
Do you know your .NET Framework version? 
and do you have vc++ redist installed?
https://www.microsoft.com/en-ph/download/details.aspx?id=48145

**Comment by Bnt5** [comment]
Thank for answer !
My Pc is relly messing ....
I want to Download Vc++ but i have an other Error (I think it's a joke !!!) "Error 0x80240017"
And i have Microsoft .NET Framework 4 !

**Comment by JeCelle** [comment]
haha, I was in a similar situation like yours too before(my PC is getting old), and I managed to fix mine by downloading this:
https://www.sereby.org/site/all%20in%20one%20runtimes?cat=aio <-- Of course, Please download at your own risk
(Sorry, I also forgot which vc++ version was it that allowed me to run the bot so I can't pinpoint to you which one to install)

**Comment by xJustx** [comment]
Should be fixed in the newest version, if the issue appears again, open a new issue.
