### ISSUE TITLE
niantic change api again ?

### ISSUE THREAD

**Issue by Polarbear008** [Ar1i/PokemonGo-Bot#2321]
i cant find poke stop

**Comment by Rhukz** [comment]
do not use more than 2 bots! thats the problem

**Comment by Polarbear008** [comment]
i just use 1 bot

**Comment by xRealMaks** [comment]
To answer you question. They didnt.
Try to change your location or the servers are overloaded.
Please use the search function and dont open a new issue, if we answered the question 20 times.
