### ISSUE TITLE
Not an issue or maybee yes // max IP x Pokemon Go 

### ISSUE THREAD

**Issue by urangotango** [Ar1i/PokemonGo-Bot#2322]
hi ppl and @Ar1i 
i remember there was some way to simulate multiple IP adresses on the same system... 
any 1 know how to do it ??(i remember there was some way but dont remember how to do it ... ) so that we can keep botting with more than 2 accounts..

or mabe ar1i you can check if this feature can be implimentet inside of your bot tool..

**Comment by gummyruler** [comment]
Stop at 1 it's not like you're commercializing these accounts. If you are please donate 50% to the maker of the bot.

**Comment by urangotango** [comment]
@gummyruler 
1) i dont comercalize a shit 
2) i have 4 accs to take arenas 
3) i did just a question and i dont did it to take an fag..t no sense answere.. gg

**Comment by Bangden** [comment]
U can just buy VPS Windows for another account

**Comment by gummyruler** [comment]
If you were botting why use multiple accounts to take gyms? It's an unfair advantage and will likely get you banned sooner than most of us since people will screenshot your name and report you. Use your brain please.

**Comment by xRealMaks** [comment]
VPN/Proxy feature will be added soon.
Also this is for issues only. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
