### ISSUE TITLE
multi bot

### ISSUE THREAD

**Issue by Rhukz** [Ar1i/PokemonGo-Bot#2324]
hy there, i use 4 bots and i need it because the continet pokemon... maybe we can fix it 2 use maximum 4 bots? it will BE GREAT!

**Comment by xRealMaks** [comment]
Niantic softban all accounts with the same ip if there are more than 2 accounts connected. A VPN function to get around this will be added soon.

**Comment by gummyruler** [comment]
It's IP based man. Get a VM and put hotspot shield in it.
