### ISSUE TITLE
[Suggestion] Block Pokemon from transfer

### ISSUE THREAD

**Issue by filoh** [Ar1i/PokemonGo-Bot#2327]
@Ar1i Can you add a feature that blocks some pokemons from transfer?
I feel a little scary from transfer a great pokemon by mistake. This way we can block some favorite pokemons from transfer.

Thanks, and again, excellent job with the bot.

**Comment by JeCelle** [comment]
Isn't this what you're suggesting?
![image](https://cloud.githubusercontent.com/assets/20881462/17517269/3a2927b4-5e75-11e6-84cd-3f808b2dd3d3.png)

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by filoh** [comment]
@JeCelle Actually no, this is the auto transfer, I mean block on the GUI Pokemon List.
I transfer a lot of pokemons daily, I feel scary from transfer a great pokemon by mistake.

@xRealMaks ok, I will make a suggestion there.

**Comment by JeCelle** [comment]
@filoh I see, that's a good suggestion then. I think the confirmation pop-up after clicking transfer already helps avoid such mistake though. Anyway, prevention is still better than cure. :)) Like a "filter" list right? on the GUI Pokemon List, if the list is filtered say.. "Don't show super duper extreme mega great l337 pokemons" it would hide the pokemons you don't want to transfer.. interesting..
![image](https://cloud.githubusercontent.com/assets/20881462/17518192/785abbfc-5e79-11e6-94f9-3c41b53138f5.png)

**Comment by filoh** [comment]
Yes, I already transfer a high pokemon by mistake once, I regret about that, this pop-up confirmation will be a great feature.
