### ISSUE TITLE
bot is down ?

### ISSUE THREAD

**Issue by joe112** [Ar1i/PokemonGo-Bot#2328]
bot is down ?

**Comment by JeCelle** [comment]
What's your basing for asking that? It seems to be working fine here at my end.
![image](https://cloud.githubusercontent.com/assets/20881462/17517750/5cb21a64-5e77-11e6-9f6e-bdb39b5e50b3.png)
And I do believe that the bot can't be "down" because the bot is not hosted in a server for it to run?

**Comment by xRealMaks** [comment]
Maybe the servers are slow, but not down.
The devs do not have access to the servers btw.
And next time, describe your problem more accurate.
