### ISSUE TITLE
Pokemons flüchten

### ISSUE THREAD

**Issue by momo0206** [Ar1i/PokemonGo-Bot#2329]
Kennt sich wer mit Pokesnipers.com aus? also wenn ich die daten im bot eingebe findet der das pokemon auch was ich bei Pokesnipers rausgesucht habe, aber kann es nicht fangen weil es flüchtet. denke wegen dem softban, kennt einer eine möglichkeit das zu ändern?

**Comment by PippoAe** [comment]
Versuch es mal mit dem "Force Unban"-Knopf in der Pokemon-liste.
Habe bereits gehört das Force-Unban im Moment nicht ordentlich klappt, aber ein Versuch wäre es wert.

**Comment by xJustx** [comment]
^
