### ISSUE TITLE
EGGS OPTION and SOFT UNBAN

### ISSUE THREAD

**Issue by Dejamelofiao** [Ar1i/PokemonGo-Bot#233]
Hi, my english its very bad, but i try explain the problem, 

Your software works very well , you did a great job, you're really good , but I would like to propose an idea, you could put the eggs option open automatically , giving priority to eggs 10 km ? and could you please review the soft unbanned , I think it does not work

THANKS FOR YOUR ATTENTION

**Comment by Oguzcan13** [comment]
The anti softunbann is already in place

**Comment by Dejamelofiao** [comment]
Okay, very well, and i think that open the eggs its good idea, regards

**Comment by plowzey** [comment]
Eggs are a good idea and i feel like there should be presets, for like (filter shitty pokemon) (search for rarest pokemon only)

**Comment by Dejamelofiao** [comment]
Yeah, the eggs options i think that is good idea, and one question, you capture many pokemons ?, or is it just me that captures me and appear few.
