### ISSUE TITLE
IV´s werden falsch berechnet/angezeigt. (Build 09.8.16 11.51)

### ISSUE THREAD

**Issue by 41271** [Ar1i/PokemonGo-Bot#2330]
![unbenannt](https://cloud.githubusercontent.com/assets/20927236/17518020/6915ea82-5e46-11e6-8201-926e179aa3e4.png)

Ich kann auch falsch liegen, da ich bezüglich Prozentrechung bzw. wie das Spiel die IV´s berrechnet, keine Ahnung hab.

**Comment by Logxn** [comment]
warum durch 45?

**Comment by jmo93** [comment]
15+15+15= 45, deswegen durch 45. oder irre ich mich?

**Comment by Ar1i** [comment]
>         public static double CalculatePokemonPerfection(PokemonData poke)
        {
            if (poke.CpMultiplier + poke.AdditionalCpMultiplier == 0)
                return (poke.IndividualAttack + poke.IndividualDefense + poke.IndividualStamina) / (45.0) * 100.0;

            BaseStats baseStats = GetBaseStats(poke.PokemonId);
            var max_cp = CalculateMaxCPMultiplier(poke);
            var min_cp = CalculateMinCPMultiplier(poke);
            var cur_cp = CalculateCPMultiplier(poke);

            return Math.Round(((cur_cp - min_cp) / (max_cp - min_cp)) * 100.0);
        }

**Comment by Ar1i** [comment]
Eigentlich sollte die Berechnung ja richtig sein?

**Comment by jmo93** [comment]
Hmm

**Comment by 41271** [comment]
Geschlossen, weil das Problem warscheinlich behoben ist.
