### ISSUE TITLE
bot has a problem

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#2334]
Hello AR1i bot has problem sometimes is frozen and coming closeing button can u check ur code?

**Comment by gummyruler** [comment]
Can you give us a screen shot when it happens? It'l give us more information as to why it's happening.

**Comment by CritSin** [comment]
ok but if it is work more time it is frozen i dont understand. if it will give again i will send screen shot

**Comment by xJustx** [comment]
And please add the log.

**Comment by xJustx** [comment]
If the problem still occurs, please open a new issue with all infos.
