### ISSUE TITLE
error

### ISSUE THREAD

**Issue by immonts** [Ar1i/PokemonGo-Bot#2335]
![image](https://cloud.githubusercontent.com/assets/20926389/17518779/cdcb4c4e-5e7b-11e6-8e2d-6b6dc305dcd3.png)

anyone knows how to fix this sirs?

**Comment by PokeMungo** [comment]
close the bot. update to new version. check username/email or password correctly again,

**Comment by gummyruler** [comment]
Seems like you entered the wrong credentials. wait 15ms. and try to log-in again using the right credentials.
