### ISSUE TITLE
Issue with Pokestops not being available

### ISSUE THREAD

**Issue by Jacowork** [Ar1i/PokemonGo-Bot#2336]
Hi,

when starting the app, I get the following issue when entering a new location.

[15:54:32] We can't find any PokeStops in a range of 5000m!
[15:54:32] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

I used
Australia, Circular Quay
-33.86110602207955,151.21090650558472

Which worked, like an hour ago.

When trying Necrobot, I get the same issue. Is it something with the Niantic servers?

**Comment by Jacowork** [comment]
I only run 1 instance BTW.

**Comment by Jacowork** [comment]
Using latest.
PokemonGo-Bot Ar1i -Build 09.8 16 11.51

**Comment by PokeMungo** [comment]
soft ban. wait for 30 minutes

**Comment by PokeMungo** [comment]
or use force unban. or change location. 
Note: do not use more that 2 accounts to AFK 2 bots. They will detect and softban

**Comment by Jacowork** [comment]
Did an unban. Not working. So no running necro and pokebot for 2 different accounts on 1 machine?
Ok.

Thx.

**Comment by PokeMungo** [comment]
yap. ^. i tried... if i run 3 accounts in 1 machine(pc), i get softban, so use two only.

**Comment by pilota56** [comment]
Get a new IP or wait 15 Minutes. Its a IP Bann.

**Comment by Jacowork** [comment]
The @PokeMungo @pilota56  I will only run 2 accounts.

**Comment by PokeMungo** [comment]
^ restarting router or new IP is much faster :)

**Comment by suljo94** [comment]
Go to the config folder and delete lastcordinates
