### ISSUE TITLE
Every Time I log in the bot my phone asks me to verify my Google account 

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#2339]
I CHECKED my Google account security and nothing changed but it is quite annoying because I can't use any google apps until I log in

**Comment by JeCelle** [comment]
Since the bot uses a different "fake" GPS in order for it to catch pokemons, google thinks that your account has been compromised and somebody else is using it from the other side of the world. It annoyed me too, so I ended up using PTC accounts for my bot.

**Comment by MiGaBelG** [comment]
Smart ^^

**Comment by suljo94** [comment]
@JeCelle I use fake gps on my phone to make it think it is in the same area and when not using the bot it didn't ask me to verify but as soon ass I turn the bot on it asks for verification,  seems like it is more then just location

**Comment by JeCelle** [comment]
I see. If that's the case, then most probably it has something to do with device ID. (i believe necrobot has that on their latest release)
"Google has various checks in place, one of them is a check to see if the login is valid (logging into a new location gives a warning message + prevents me from logging in using my bot)." Like, if google sees you logging in from your phone(e.g. iPhone) even if it's from a different location based from the GPS, it still allows you to pass the security check, but if it's from an unknown device then it throws off that annoying verification notif. This is just a guess though, hopefully somebody else can enlighten us in that issue.

**Comment by Hydro420** [comment]
I get this as well - you can simply ignore it if using BlueStacks. Click back on the "Android" tab & open Fake GPS again (should work this time). Enable you spoofed location & the only thing it will have you do is type the password for your goggle account when you launch PokemonGO.

**Comment by Ar1i** [comment]
should be anwsered
