### ISSUE TITLE
[Issue|GER|ENG] Visual Studio Datein geblockt | Visual Studio Files blocked

### ISSUE THREAD

**Issue by BotDeveloperGo** [Ar1i/PokemonGo-Bot#2340]
[GERMAN]
Hey Ar1i und oder Community,

wenn ich die Visual Studio Datei öffne und anfangen will rum zu testen wird mir immer angezeigt das App.config und UserSettings.settings nicht gefunden werden können und im Projekt Mappen Ordner ist an den zwei Dateien ein gelbes Dreieck was kann ich machen ?

MfG
Niklas

[ENGLISH]
Hey Ar1i and or Community,

is i open visual studio and begin edit the files come the message the App.config and UserSetting.settings noch found an in the Project folder are on the files a yellow triangle what can i do ?

BR
Niklas

**Comment by Ar1i** [comment]
guck ma obs jetzt geht

**Comment by BotDeveloperGo** [comment]
Ja warte

**Comment by BotDeveloperGo** [comment]
Ja klappt alles wieder danke, wann machst du das mit dem eier ausbrüten oder seid ihr da schon dran ?

**Comment by AgentBallermann** [comment]
Is das nicht schon din ?!

**Comment by Leak1337** [comment]
Er Brütete aber die eier nicht aus auch wenn es ein Kontroll Kästchen dafür gibt

Man kann immer noch nicht Debuggen fehlen immer Dateien
