### ISSUE TITLE
When filling the inventory the bot does not transfer.

### ISSUE THREAD

**Issue by questioner01** [Ar1i/PokemonGo-Bot#2341]
When filling the inventory the bot does not transfer and is only going pokestops.

**Comment by MiGaBelG** [comment]
restart the bot !

**Comment by hazmad** [comment]
Yup, I had this issue too. I asked for an "Always Transfer" option that I think would solve it. 

Right now mines set to keep 3 and transfer all duplicates, but there's some you might not want at all. For example: I want to capture enough ratatta to evolve them and get XP,  but I don't want any Raticate's taking up space. It would be nice to have an "Always Transfer" list. 

the work-a-round is to go in every 30-60 mins and transfer the crappy one's out yourselg

**Comment by b3shoy** [comment]
@hazmad or you can simply raise your maximum CP to transfer for like 900 or 1000, so in this case even the best raticate can be transferred, and decrease duplicate pokemons to 2, that should help too (leave IV at 85% if you want the better ones).

**Comment by hazmad** [comment]
@b3shoy ..Maybe I just hate Raticates and don't want to see them in my pokedex. LOL 

I have my max CP set to 1600, but it'll still keep 3 of everything, yeah, I'm going to try 2 as well

**Comment by b3shoy** [comment]
You can select them in the Transfer list, so you can have only 2 of them at a time :smile:

**Comment by Hydro420** [comment]
Guys you might also note that if you select option to "keep pokemon" that can evolve, it will not transfer it, regardless of your other settings.

**Comment by xJustx** [comment]
First: Did you checked "Keep pokemon which can be evolved"?
Second: Do you have enough pokeballs, and check your settings:
![Settings](http://i.xjustx.cf/seYQOJvq.png)

**Comment by xJustx** [comment]
If the problem still occurs, please open a new issue with all infos.
