### ISSUE TITLE
Pokemon Getting away 

### ISSUE THREAD

**Issue by menaze818** [Ar1i/PokemonGo-Bot#2342]
I have a curious Question/Issue 

Am i the only one whose getting the majority of their Pokemon getting away even using great balls + Razberries the majority of the Pokemon i find are getting away.. I don't mean all of them but the vast majority. Im able to catch Pokemon once a while but majority get away. i tried unbanning and didn't work as i was still able to receive pokestops items and able to catch. 

i'm just left clueless and curious

**Comment by pilota56** [comment]
Which Level? With higher Level it will be harder to catch Pokemon.

**Comment by menaze818** [comment]
I'm level 28, it get's harder according to level ? That may explain it. Although the majority of the times i am using Razberry great - ultra balls which is confusing me

**Comment by hazmad** [comment]
Try changing locations. I had this issue too. It seems like an area goes stale if you use it too long. I've experienced this in Tokyo, but strangely never in NYC.

**Comment by menaze818** [comment]
Ah i see thank you i will try this

**Comment by menaze818** [comment]
woops

**Comment by JeCelle** [comment]
Nothing of that sort is happening to me so far. But umm, have you tried observing the console logs of the bot? Does it say something like Probability below 10% or something?
![image](https://cloud.githubusercontent.com/assets/20881462/17520003/b1a6f7c0-5e80-11e6-99c0-ca6e4203fda7.png)
I'm also level 28 as you can see.

**Comment by hazmad** [comment]
It gets worse after 30

**Comment by b3shoy** [comment]
close please

**Comment by menaze818** [comment]
i get Pokemon with catch probability of 51 under, Surprisingly i can catch random pokemons but majority just get away

**Comment by menaze818** [comment]
I switch bots, now it says possible soft ban ill try in a few hours to see if it still there ... Thanks for your help guys :)

**Comment by DrHPain** [comment]
The Last Update changed the curvedball behavior. If this isn't implemented yet it could be the cause, i think.

**Comment by menaze818** [comment]
I just logged on my phone surprisingly the first thing it said i was going to fast and mainly said im a passenger lol

**Comment by Hydro420** [comment]
Its not a problem with the bot... With the recent update to game it made it harder to catch pokemon. The work around is to make sure in your "items" section - there is not more than 330 items. So set pokeballs to 100, rest whatever you want just make sure its not over 330 total.

Use these settings and the bot should catch pokemon perfectly fine.. This was stated in previous opened issues..
![untitled](https://cloud.githubusercontent.com/assets/20824888/17521800/4efc6a30-5e1a-11e6-9971-dc5947299e7e.png)

**Comment by menaze818** [comment]
oh thank you i will try this
