### ISSUE TITLE
Dutch Translation for Belgium and Netherlands

### ISSUE THREAD

**Issue by Jacowork** [Ar1i/PokemonGo-Bot#2343]
Here is a dutch translation for Belgian and Netherlands players.
I didn't know where to upload, so did it here.

Cheers.

[dutch.docx](https://github.com/Ar1i/PokemonGo-Bot/files/409144/dutch.docx)

**Comment by ingmar3** [comment]
Where is the original English file ?

**Comment by xRealMaks** [comment]
Post as a Pull-Request and not as an Issue. Thanks.
