### ISSUE TITLE
Pokemon Running - Set New Rules?

### ISSUE THREAD

**Issue by Koshyy** [Ar1i/PokemonGo-Bot#2344]
Hi, sometimes there are quite rare pokemon but it uses a greatball instead of an ultraball (which I have). Is there a way to change which pokeballs the system uses for which cp/IV ranges?

**Comment by b3shoy** [comment]
@Ar1i I think this is a valid argument, an option can be added so that great and ultra balls can be used when CP > certain number.

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
