### ISSUE TITLE
use more than 2 or 3 bots

### ISSUE THREAD

**Issue by killiandh10** [Ar1i/PokemonGo-Bot#2345]
hi , do you know how to use a lot's of bots at same time? like 4, 8 or 10?
thnaks!

**Comment by b3shoy** [comment]
You will get IP banned if you opened more than 2 bot instances at once.

**Comment by lailaps** [comment]
Make some VM with Windows 7 - 
Run VPN inside every VM.
Use 2 accounts per VM and IP!

**Comment by b3shoy** [comment]
@lailaps so hectic lol

**Comment by killiandh10** [comment]
@lailaps ok thanks, good idear XD

**Comment by artasakha** [comment]
pay internet cafe manager to run your bot, 2 on every PC lol
