### ISSUE TITLE
Inventory full?

### ISSUE THREAD

**Issue by charlesyu08** [Ar1i/PokemonGo-Bot#2346]
When I farm a pokestop it keeps showing Item: Nothing (Inventory full?)
But my inventory is 410/500.

**Comment by JeCelle** [comment]
Have you tried checking your inventory on your mobile? There's a bug to be fixed regarding the inventory display issue (not showing correct amount)
like this one #2291

**Comment by pilota56** [comment]
But ist right, the Inventory is Full. You have to mark down your Items.

**Comment by hazmad** [comment]
what your inventory limit when you look in the app?

**Comment by charlesyu08** [comment]
The amount is right but i still getting nothing
