### ISSUE TITLE
[IDEAS] Implement these simple functions?

### ISSUE THREAD

**Issue by ingmar3** [Ar1i/PokemonGo-Bot#2349]
- Heal Pokémon/Revive Pokémon
- Sort Pokémon on Number
- Set region u want to be walking in
- Save/Load Settings of your bot?

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Logxn** [comment]
- Could do that
- Click on "name" in pokelist
- Uhm, nah
- Uhm, nah
