### ISSUE TITLE
Many accounts

### ISSUE THREAD

**Issue by Oguzcan13** [Ar1i/PokemonGo-Bot#235]
I don't sell account. Just i want that you add a form for add my account in a save list. Are you understand ?

**Comment by Logxn** [comment]
You can change the title 9 more times.
"You dont understand"

**Comment by plowzey** [comment]
Og, It doesn't take that much effort to legit just put a username/email and a password in, you're complaining over nothing, you could quite easily put passwords and emails/usernames in a notepad and copy and paste/

**Comment by Oguzcan13** [comment]
This is very easy to say but very difficult to put in place. Why you're not agree ? However good idea...

**Comment by Oguzcan13** [comment]
when you're tired is good
