### ISSUE TITLE
i cant catch pokemon(s) and im not banned

### ISSUE THREAD

**Issue by Lassetheg** [Ar1i/PokemonGo-Bot#2351]
I dont know is this a bug? or can any one help me?
idk am I ip banned?
How i can change my ip?
![git hud 2222222222222222222](https://cloud.githubusercontent.com/assets/20913616/17520756/2bfb4740-5e51-11e6-810b-bfc39506aed2.png)

**Comment by vike02** [comment]
hai iam too a bot user not a dev.....pls check weather the pokemon go is officially released in ur reegion.....u can do this by opening pokemon go in ur phone and check wether u see any pokemons or pokestops or any gyms......if yes.....check the location u have set ur bot to work in.....the best place is manhattan newyork to catch rare pokemons and they are available a lot....try it out......

**Comment by Lassetheg** [comment]
@vike02 can you add me in skype? My name: jottschi 
Can you do it please <3
i have a panda on my profile

**Comment by Hydro420** [comment]
Did you read thru the other issues before posting this? Please do so.... The bot is working perfectly fine.

**Comment by Lassetheg** [comment]
i have a problem with my bot
thats why i opened a issues

**Comment by Hydro420** [comment]
Its not a problem with the bot... With the recent update to game it made it harder to catch pokemon. The work around is to make sure in your "items" section - there is not more than 330 items. So set pokeballs to 100, rest whatever you want just make sure its not over 330 total.
![untitled](https://cloud.githubusercontent.com/assets/20824888/17521301/71158f90-5e18-11e6-895b-4f4285844905.png)

**Comment by pilota56** [comment]
There is no Problem, i think the Pokeballs are emty or you put the Settings for the Pokeballs to "0"

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/17521506/3bca5b3a-5e19-11e6-8453-a2d0a56a1d8b.png)

**Comment by Lassetheg** [comment]
oh tanks so much <3

**Comment by pFallenAngelq** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/20930591/17522168/024e2e1c-5e24-11e6-8e2b-88da4957f0ea.png)

Same problem here and playing at Central Park. The issue started yesterday night, stopped the bot and now I have launched it to see if it was a temporary fail but it keeps like past night.
