### ISSUE TITLE
---suggestion---

### ISSUE THREAD

**Issue by Chris20000** [Ar1i/PokemonGo-Bot#2353]
Thanks to all the developers of this great bot! I´m also very impressed by the effort you made in fixing the api problem as fast as possible.

Although, I have a suggestion:
It would be great, if there was an option that you can select, that under a certain cp level, pokemon are directly sent to the professor.

Another bug/issue is, that sometimes, especially with the very common pokemon, the bot doesnt respect the limit (3 in my case) of the identical pokemon kept in the inventory and stacks them until my inventory is full. 
((it isn´t the most important thing, because I´ve already put the not to catch rule for most of the very common pokemon))

sry for the long post ;)

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
