### ISSUE TITLE
No Pokestops?

### ISSUE THREAD

**Issue by Major1337** [Ar1i/PokemonGo-Bot#2355]
I'm starting the bot ... set location and my data aaaand ... nothing
Everytime theres the message, there are no PokeStops within 5000m ... do i have to run something else before i run the bot? ... help

**Comment by hazmad** [comment]
are you running the app or do you have any other pokemon go bot running?

**Comment by suljo94** [comment]
Go to the config folder and delete the lastcoo file then restart

**Comment by pilota56** [comment]
Sounds like the IP Bann. Get new IP or wait 15 Minutes. ONly 2 Bot at same Time. 1 Minute beetween starten each Bot.

**Comment by Major1337** [comment]
i only use 1 bot ^^ but i think i figured out, how i can run it ... changed the location from the bot, deleted last coords and all fine ... thx for ur help :)

**Comment by bonisss** [comment]
![image](https://cloud.githubusercontent.com/assets/20930215/17521705/7e9520b6-5e7e-11e6-9853-f5b60baae5ab.png)
how to fix it ? 
how to delete last coor 
plz help me

**Comment by pilota56** [comment]
Looks like the IP Bann. Get new IP or wait 15 Minutes.

**Comment by Ar1i** [comment]
Or try to switch location

**Comment by bonisss** [comment]
i change location , but still like this.
i've tried repeatedly

**Comment by Ar1i** [comment]
change ip, or wait 20 mins or longer.

**Comment by hachihiki** [comment]
this happened to me. i opened pokemon go from my phone (same IP with my laptop). its been 30 mins and still no pokestop. do i have to change IP now?

**Comment by bluecito** [comment]
@Ar1i I would like to ask if there is a chance to add in the bot options to "not stop in Pokestops" so we have more chance to get the Pokemons we look for, since it takes lot of time stopping on every Pokestop and sometimes the Pokemons we look for just dissapear.

**Comment by suljo94** [comment]
@bonisss from where you have extracted the bot you will find a new folder called configs, open that folder and look for the lastcoords.txt file now delete it and restart bot( you will need to set location again. I had it and it works flawlessly
