### ISSUE TITLE
Feature Request auto transfer specific pokemon based on name

### ISSUE THREAD

**Issue by blaik2k4** [Ar1i/PokemonGo-Bot#2356]
I find myself with 50 of a type of pokemon and the lv is really good but i dont need that many. i would love it if i caould transfer them automaticly based on pokemon name

**Comment by hazmad** [comment]
+1

**Comment by corydoraswhite** [comment]
Put on Auto Transfer and select the ones you dont want to get rid of in the Don Not Transfer list.

**Comment by blaik2k4** [comment]
it doesnt seam to work like that i still get like 15 of one based on IV and thats the issue

**Comment by AiVo7z** [comment]
It should tranfer the worst of each Kind if you have more than X. That doesn't work, atleast after a while, a Feature that's probably bugged, otherwise I don't see areason Ar1l would build that in.

**Comment by blaik2k4** [comment]
It would improve the app

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by czokalapik** [comment]
actually.... that's a bug

**Comment by blaik2k4** [comment]
YouCaring     YouCaring is dedicated to compassionate crowdfunding,
providing free and easy online fundraising and support for humanitarian
causes. 
                   View Online
<https://www.youcaring.com/rickbowen-917483?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
<https://www.youcaring.com/?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
             Help Before Homeless
<[[FundraiserURL]]?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
       Rick Bowen wants you to know about this fundraiser..     My Name is
Rick. I am 37 years old from Auburn NY. I have gone through some hard
circumstances lately. my roommates moved out suddenly a month a head of
schedule and i cant afford to live here now. If I can Raise my fund raiser
I have a place to go with a job. Please have a heart. If you cant give...  
           View Fundraiser    
<https://www.youcaring.com/rickbowen-917483?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
        *This message was sent by Rick Bowen through YouCaring.com*. 
 Please do not reply to this message as Rick Bowen will not receive your
email.        Help spread the word about this fundraiser
<https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
<https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
<https://api.addthis.com/oexchange/0.8/forward/email/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
                  What is YouCaring?   YouCaring is a FREE Crowdfunding
Platform that empowers people to help others overcome hardships and enjoy
happier, healthier lives.             Find out more    
<https://www.youcaring.com/free-fundraising?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
                     
——————————————————————————————————





This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
unsubscribe from this list (http://mandrillapp.com/track/unsub.php?u=30332225&id=7f17261ba1b34b1bbe054ca0f5d877c1.UOVTLtaoWnsO04T9Qh0xCJPxSoc%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dreply%252B013f27b01444023b2635b6a1475fa85d974c87e838d6529c92cf0000000113c1bc9192a169ce0a24e6a7%2540reply.github.com)
