### ISSUE TITLE
Running 3 bots = softban?

### ISSUE THREAD

**Issue by ineedtostudy** [Ar1i/PokemonGo-Bot#2357]
It might be just me but before I could run 3 bots just fine even after the ip ban. Now I could only find my self to run 2 bots only. One google and the other PTC.

**Comment by pilota56** [comment]
Since today only 2 Bots.

**Comment by rayito45** [comment]
only need to wait 20 minutes for unbann mi ip? :D

**Comment by ineedtostudy** [comment]
I wait 10 mins and its back. However, it keeps on happening over and over. I'm running 2 now and its running fine. Everytime i run the third it softbans me

**Comment by pilota56** [comment]
es, ist the same with my bots. Only 2 at the same time or you use different IPs with VPN or Proxys.

**Comment by ineedtostudy** [comment]
Ah ok thanks!
