### ISSUE TITLE
Bot  coords what is the best bot place??

### ISSUE THREAD

**Issue by sHaXx69** [Ar1i/PokemonGo-Bot#2358]
Bot  coords what is the best bot place??

**Comment by PokePro21** [comment]
San Francisco Pier 39 is the best nest for dratini but after 7 a.m until 6 p.m(Turkey hour) there are. I suppose noone wanna share own location. Please be more helpful!
Utah Park in Aurora, CO
Chandler Hovey Park.
Eeeve nest - 43.3152733,-1.9004924
43.3193456,-1.9773019
35.632747, 139.880266
-33.861739, 151.209852
37.78814160,-122.407460460


37.8075122641545 -122.420654296875 for magikrap

**Comment by moops44** [comment]
is this an issue??
NO
use google for questions like this

**Comment by burnSMACKER** [comment]
Do Brooklyn Bridge Park at 40.700681, -73.996721 if you want Magikarp candies. I got 1200 in a couple days.

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by pilota56** [comment]
Is there another Board? Because i was banned there.
