### ISSUE TITLE
Please fix auto incubate egg's.

### ISSUE THREAD

**Issue by dami1236** [Ar1i/PokemonGo-Bot#2360]
Please fix auto incubate egg's.

**Comment by JeCelle** [comment]
#2354  #2352 #2011 #1551 #2290 #2281

**Comment by k756u** [comment]
il faut attendre un peu ne vous plaigniez pas les développeurs travaillent deja d'arrache pieds! un peu de patience!

**Comment by PippoAe** [comment]
this

**Comment by Bangden** [comment]
Try for alternative
Login Pokemon go via device and dnt forget, GPS do not turn on GPS.
fast your egg incubation and quickly exit the application pokemon Go
