### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sosa03** [Ar1i/PokemonGo-Bot#2361]
pokemon list wont load

**Comment by PippoAe** [comment]
Can you reproduce this error?
I sometimes have the same problem but it hasn't been reproducable yet.

**Comment by xRealMaks** [comment]
This can happen due to slow pokemon servers. 
We cant fix this issue.

**Comment by PippoAe** [comment]
But the guy hangs sometimes if I "reload" the pokemon list.
But this issue is just minor.
Please make the Egg-Incubation and lured pokestops work <3
