### ISSUE TITLE
Item recycling 

### ISSUE THREAD

**Issue by yaowa** [Ar1i/PokemonGo-Bot#2362]
Is there a way to make this NOT happen? I would prefer that it only recycle items once my inventory is full as opposed to it recycling items when I am at 602/1000. It makes very little sense to me, so if there is a way to have this eliminated as a future request, that would be great!

**Comment by Damantium** [comment]
set your item list the way you want it then?

**Comment by yaowa** [comment]
I do but it will still cycle out items before it meets the threshold for any given item.

**Comment by PippoAe** [comment]
This is a suggestion not an issue.
But you're correct, the bot does walk - find pokemon - post stats - recycle items - catch pokemons which is rather unefficient.
But sadly we can't mark issues as suggestions on this system here.

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by yaowa** [comment]
Will do. Sorry!
