### ISSUE TITLE
Where is my character moving ??

### ISSUE THREAD

**Issue by Hamouda55** [Ar1i/PokemonGo-Bot#2363]
How to know wherre is the bot moving north east west south !!?!?

**Comment by Damantium** [comment]
Click on the little map on the Pokémon list

**Comment by Hamouda55** [comment]
Nothing he is standing stil...

**Comment by PippoAe** [comment]
If you've set the moveradius to more than 0 it bot should be moving inside the set radius from the starting position in a random manner.
If you click on the map it takes a moment to start showing your current position.

This is not a forum, close this issue ASAP or you'll be banned.
