### ISSUE TITLE
Error loading pokemon list: out of memory and more

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#2365]
Issues encountered: 
1. Error loading pokemon list: out of memory
2. Not all pokemon transferred
3. Intermittent soft ban even though i only used 1 location since then

**Comment by Damantium** [comment]
As for the softban how many instances are you running? Any more than two and you get softbanned, it was three yesterday today it only works with two,

**Comment by PippoAe** [comment]
2. Not all pokemon transferred
Did you maybe check the "don't tranfer if pokemon can be evolved" checkbox?

**Comment by idoled1** [comment]
i am also getting the pokemon list error

**Comment by coffeexp** [comment]
I unchecked the "dont transfer if pokemon can be evolved".. 
i am having 2~3 soft bans before being cleared from ban..
and now i cant connect at all: 
We can't find any pokemon in a range 10000m
...
...

sometimes i wait for 5~10 minutes to automatically connect again.. but now i waited 30mins to 1hr and still having that error.. :(

**Comment by xRealMaks** [comment]
You probably got a IP-Ban. Do not run more than 2 instances of the bot at the same time.

**Comment by drsweg** [comment]
Im having the error loading pokemon list bad authentication. Can't use any bot

**Comment by OgJesty** [comment]
I have the same issue @drsweg
