### ISSUE TITLE
German Translation suggested fix

### ISSUE THREAD

**Issue by FeelTheFairyLaw** [Ar1i/PokemonGo-Bot#2366]
"useLuckyEggAtEvolve":"Glücksei bei Entwicklung",
"useIncense":"Verwende Rauch alle 30 Minuten",

I think it's a coding issue - CamelCase it's the word, isn't it?
Former Version: useLuckyeggAtEvolve, but it should be useLuckyEggAtEvolve.
Further - the translation of "LuckyEgg" and "Autoincubate" are still in english.

**Comment by xRealMaks** [comment]
I will forward it. Thanks.
