### ISSUE TITLE
I CANT FIND FORCE UNBAN BUTTON !?!

### ISSUE THREAD

**Issue by Hamouda55** [Ar1i/PokemonGo-Bot#2367]

**Comment by sunit1998** [comment]
its in the pokemon gui list

**Comment by Damantium** [comment]
^

**Comment by PippoAe** [comment]
"fore unban"-Button is on the Pokemon-Gui-List.
This is not a forum, close this issue ASAP or you'll be banned.

**Comment by Hamouda55** [comment]
ok but i also did not find IT #CLOSED
