### ISSUE TITLE
Just a small question, will be closed directly

### ISSUE THREAD

**Issue by Chris20000** [Ar1i/PokemonGo-Bot#2368]
I have just 4 small questions: 
-How is the risk of running more than 1 instance of the bot with the same account
- How is the risk of running more than 1 instance of the bot at two different locations
- Do i have to wait until I chance the location to another one which is far away, f.e. from NY to LA or from America to Germany
- can I play on my phone while the bot is running

**Comment by PippoAe** [comment]
- Same account + Same bot won't work.
- Two accounts on two instances of the bot will work.
- Yes.
- No.

This is not a forum, close this issue ASAP or you'll be banned.

**Comment by FoolYah** [comment]
1. I runned 6 acc at the same time and nothing happened

2. I didnt and nothing happened

3. Yes. But sometimes evolution or Power up buggs arround. But if u mean like playin outside and farming pokestops: no u will get allways auto soft banned bec of bot. u have all 30 sec to spin the poke stop 40 times and that would suck.

**Comment by Feyron1996** [comment]
Same account and same bot doesn't work, but you can run different accounts.
It is better when you wait some time, because maybe you get a softban.
You can go online while botting.
