### ISSUE TITLE
The Bot Does Not Run on an AWS VM

### ISSUE THREAD

**Issue by cooluser1** [Ar1i/PokemonGo-Bot#2369]
Hello, I am trying to run the latest version of the bot on an Amazon Web Services Virtual Machine but I keep receiving the error on the screenshot below. Is it possible to run the bot on this system? Thank you.

![bot_error](https://cloud.githubusercontent.com/assets/20931343/17523992/48851abc-5e65-11e6-936a-dff964b69598.png)

**Comment by sylva91** [comment]
same here, but it did go by itself

**Comment by PippoAe** [comment]
Did your already try to start as an administrator?

**Comment by cooluser1** [comment]
Yes, I did. Also tried the compatibility settings but none worked :(

**Comment by idoled1** [comment]
i am getting the same error on multiple pcs

**Comment by Hameroc** [comment]
I have no problem on my Windows 2012 Server @ Vmware vsphere

I Think the Problem is amazon

**Comment by Bangden** [comment]
My server, I think its okay. dn't have problem
I've run the bot in windows server

**Comment by cooluser1** [comment]
Well then it seems like the problem is caused by Amazon (or maybe by the VM's AMD processor). Are there any alternatives to Amazon that you can suggest? 

I just want to be able to RDP to my VM from my mobile device (i.e. VM with a static and open IP) even if my laptop is switched off :)

**Comment by Bangden** [comment]
@cooluser1 What you've tried to use azure?

**Comment by cooluser1** [comment]
@Bangden I am going to try it now :) thanks

**Comment by cooluser1** [comment]
Unfortunately, I am receiving the same exact error on Azure too :( @Bangden

**Comment by Meisterxoxo** [comment]
It doesn't seem to run on Windows server. My friend tried it on Azure and i tried in on Amazon AWS. Both Windows Server 2012 R2.

**Comment by lailaps** [comment]
I only run them on windows server.
NET Framework should be installed!

**Comment by Yogissimo** [comment]
![image](https://cloud.githubusercontent.com/assets/20912908/17532868/ca726044-5e82-11e6-9a1f-c00582b2481a.png)

**Comment by cooluser1** [comment]
I hope @Ar1i can understand why the bot does not work on AWS and Azure and help us solve the issue.

**Comment by DR6116** [comment]
@lailaps 
What VPN do you use?

**Comment by OGcpalm** [comment]
it doesn't work on this VM, all other Rocket API has same problem

**Comment by Meisterxoxo** [comment]
@lailaps Running Necrobot (Another Pokémon GO Bot) gives me an error saying that the IP might be blocked. Niantic may have blocked Amazon and Azure IPs or something. Enableing .NET Framework 3.5 didn't change anything.

**Comment by lailaps** [comment]
Yes, possible!
I am using an dedicated OVH server with VMs and VPNs.
