### ISSUE TITLE
Very Low Exp Per Hour

### ISSUE THREAD

**Issue by Wolfie407** [Ar1i/PokemonGo-Bot#2371]
Hey there,

I am noticing a drastic decrease of exp gain per hour and this is with and without using lucky eggs.  I went from having 40k exp to now only 7?  I haven't changed my location.

**Comment by zzzz9999** [comment]
What is your speed?

**Comment by Bangden** [comment]
try speed 70 km/h and radius 10000

**Comment by Hydro420** [comment]
I was also wondering what the best speed/radius is for a nice XP gain.  I go 50km with 15000 radius at 40k/hr

**Comment by downspath** [comment]
i have  16kmh and dont auto evolve, i get with a radius of 5000m 28k exp in london

**Comment by Wolfie407** [comment]
Ah, I had it on the default, I will try increasing the speed and radius :)  I'll let you know if the exp is still an issue.

**Comment by PokePro21** [comment]
@Bangden 10K radius is good does it will get soft banned?

**Comment by sunit1998** [comment]
my speed is 500kmph and radius 10000m and i get 60k xp per hour

**Comment by PokePro21** [comment]
@sunit1998 really or kidding ? does you get soft banned ? are you from india?

**Comment by Bangden** [comment]
@PokePro21 If you do not want to take risks, use 60 km/h and radius 10000.
But I prefer a setting that I use today. _(Not recommended, and I'm not responsible)_
^^v

**Comment by Hahahaha0** [comment]
i got the same issue but not only low exp per hour but also the amount of pokestop nearby, sometime it show more than 144 and sometime it only 2-7 pokestop nearby

**Comment by Wolfie407** [comment]
It's now only showing 11k exp per hour :\ with a 70k/10,000 radius

**Comment by Wolfie407** [comment]
It almost looks like it's not visiting pokestops and is only catching pokemon.

**Comment by Bangden** [comment]
try 55 km/h radius 5000

**Comment by NaveTK** [comment]
sigh, it mostly depends on the location... I'm using 100km/h and only a 2000m radius but getting around 70K exp (and around 5 dratinis) per hour in san francisco at pier 39

**Comment by Wolfie407** [comment]
But what I don't understand is how I used the same location and was getting 40k exp an hour but now I am only getting 7k?  Well, now 11 since I increased the speed and radius.  That makes 0 sense.  I am not softbanned either.

**Comment by Abbasoo** [comment]
@Bangden try 55 km/h radius 5000

Worked for me.

**Comment by AiVo7z** [comment]
I get 40kxp/h and 20kxp/h 2 bots, same Location, same Speed. I use Default ones. I don't think 1000 or 2000 miles per hour would Change a Thing, it slows down to 10mph once you're Close. Get to a crowded place and neither the Speed matters much, nor the radius.

**Comment by jtapay** [comment]
any recommendation for bot?! area?! long at lat?!

**Comment by SirSamShaw** [comment]
im using santa monica anywhere in that area. Pokevision always started their page there when it was up and there were always pokemon there

**Comment by mariobros33** [comment]
Can someone recomment a good area? "Long" "Lat"

**Comment by SirSamShaw** [comment]
34.0195° N, -118.4912° W

**Comment by xJustx** [comment]
Check this: https://high-minded.net/threads/pokemon-go-settings-locations.51020/page-3#post-497686
