### ISSUE TITLE
Evolution branch classification in pokemon list GUI

### ISSUE THREAD

**Issue by FazePedro** [Ar1i/PokemonGo-Bot#2372]
I think it would be easier to manage your evolution within branches with 3 pokemons if a way to classify them by their evolution branch would be added. I sometimes dont know their evolutions and it makes it hard to see if you should wait to evolve the 2nd pokemon in that branch or rather evolve the first for better eventual results. Just an idea. Thank you

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
