### ISSUE TITLE
Botting not transfering pokemons

### ISSUE THREAD

**Issue by Hamouda55** [Ar1i/PokemonGo-Bot#2375]
the bot is not transfering any pokeemons any idea ?

**Comment by Luxor1945** [comment]
me too. :(

**Comment by xRealMaks** [comment]
can you sent a screenshot of your settings, console, and pokemon-list?

**Comment by Greenman1805** [comment]
Turn of "Keep Pokemons which can be evolved" in Other Settings

**Comment by Luxor1945** [comment]
THX!!!! ITS WORK!!!!
