### ISSUE TITLE
Pokemon Catching

### ISSUE THREAD

**Issue by seebyy0102** [Ar1i/PokemonGo-Bot#2377]
The bot is bugged or what? I can't catch the pokemons :/ the CP doesn't matter it can't catch the 100CP pokemons too :/ Any idea guys? Help me pls!!

**Comment by xRealMaks** [comment]
Try the Force-Unban button.

**Comment by seebyy0102** [comment]
im doing it everytime when i can, but still cant catch them :/

**Comment by xRealMaks** [comment]
How many bot do you have currently running?

**Comment by seebyy0102** [comment]
only one :O

**Comment by xRealMaks** [comment]
got the newest version?

**Comment by seebyy0102** [comment]
yes, i did download it before 5 mins

**Comment by xRealMaks** [comment]
Your movement-speed?

**Comment by seebyy0102** [comment]
50km/h

**Comment by xRealMaks** [comment]
Can you try to lower it to 8kmh for testing?

**Comment by seebyy0102** [comment]
wait i think i was the idiot :D without pokeballs i can't catch 'em :D i'm so sorry :DDD i'm a bit tired :D but thanks for helping :)

**Comment by xRealMaks** [comment]
xD
Have a nice day.
