### ISSUE TITLE
Lure Leeching and Catching all the pokemon

### ISSUE THREAD

**Issue by jtapay** [Ar1i/PokemonGo-Bot#2379]
Is it possible that the bot is just standing near the lures and catch all the respawning pokemons?!.. coz before the bot im just standing to this 6 pokestop and catching all the pokemons..

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
