### ISSUE TITLE
[Requests & Ideas]

### ISSUE THREAD

**Issue by Emmi911** [Ar1i/PokemonGo-Bot#238]
First of all. Good job and thanks for the bot.

Requests for now:
- Option to select a location where the bot should walk to before ending. (If you're using it with a wider range you press a hotkey and he walks back to your real home and shuts down automatically).
- Power up selector (Instead of clicking one by one for every pokemon update we need a feature to levelup a pokemon until its limit is reached or you ran out of stardust/points.

Maybe in the future when everything is more stable:
- Time selector when the bot starts/sleeps to make it more human like and even more automated.
- Automatic updates without manually replacing the files.
- Interactive bot mode. (It stays in contact with other bots, if a specific selected pokemon was found at a near place that is possible to reach in time without getting a softban, the bot will walk there and back to catch it).

**Comment by plowzey** [comment]
+1

**Comment by Dejamelofiao** [comment]
Please you can put in request HATCH EGGS i think that its necesary

thanks

**Comment by Flocke90** [comment]
i wish there would be a sorting function for name/cp/percentage/... in the pokemon list while the bot is running :)
