### ISSUE TITLE
automatic egg hatching not working

### ISSUE THREAD

**Issue by kbhargav22** [Ar1i/PokemonGo-Bot#2383]
i tried to hatch eggs automatically but it does not work. I have to put the egg in the incubator myself. i reduced the speed to 12kmph but it is still not working. please provide a solution. Thank You

**Comment by xRealMaks** [comment]
put the speed to 8kmh and you'll be fine.

**Comment by kbhargav22** [comment]
12km/h is ok as the distance is registered but the bot is not starting an incubation automatically after an egg is hatched. I have to do it manually.

**Comment by xRealMaks** [comment]
#2360 #2354 #2352 #2011 #1551 #2290 #2281
