### ISSUE TITLE
Pokemon caughting

### ISSUE THREAD

**Issue by Trekzalf** [Ar1i/PokemonGo-Bot#2384]
All the pokemon i encouther run a away, Im running the last bot. and 1 bot open.. I also use incense

**Comment by PippoAe** [comment]
Make sure to set the normal Poke-Balls to atleast 20 and try again.
All pokemons below CP 500 get catched with normal poke-balls.
The Item-count for normal pokeballs cant be 0.

**Comment by Trekzalf** [comment]
I will try this. The first poke i see is getting caught. I will keep u posted in 3 min if this was the sollution

**Comment by Trekzalf** [comment]
Thanks PippoAe This was the fix !
