### ISSUE TITLE
Bot not capturing Pokemons

### ISSUE THREAD

**Issue by Tadukiari** [Ar1i/PokemonGo-Bot#2386]
My bot is configured by not tanking pokeballs but tanking greatball and ultra ball, and while capturing a pokemon says that i didnt capture anything bcz i used a pokeball, but i dont have any !

https://gyazo.com/8dc0ac203762da02775dd5a626000d3d

Print for example.

**Comment by Bangden** [comment]
Softbanned detected

**Comment by Tadukiari** [comment]
Hmm Thank u !

**Comment by Hydro420** [comment]
Its not a problem with the bot... With the recent update to game it made it harder to catch pokemon. The work around is to make sure in your "items" section - there is not more than 330 items. So set pokeballs to 100, rest whatever you want just make sure its not over 330 total.

Use these settings and the bot should catch pokemon perfectly fine.. This was stated in previous opened issues..
![untitled](https://cloud.githubusercontent.com/assets/20824888/17526642/b7b179e0-5e2d-11e6-928e-6e713b20721e.png)

**Comment by nekudah** [comment]
Bot ALWAYS uses pokeballs in certain pokemons, so configure your tab itens as your REAL bag inventory in game (let some space free for incense, lucky and lure)

**Comment by cyl2usdragoon** [comment]
![image](https://cloud.githubusercontent.com/assets/20928244/17526780/e151006c-5e92-11e6-951f-4d4e119481b5.png)

**Comment by Hydro420** [comment]
Try these settings..... 
![untitled](https://cloud.githubusercontent.com/assets/20824888/17526822/76dd6572-5e2e-11e6-9304-5dfc8c4e8291.png)

![untitled2](https://cloud.githubusercontent.com/assets/20824888/17526826/7ade7c10-5e2e-11e6-842d-37e756001f97.png)

**Comment by Tadukiari** [comment]
So we can just capture pokemon with pokeball? Cant caught with great or ultra?

**Comment by JeCelle** [comment]
That is how the current algorithm of the bot is setup. Uses pokeball for pokemons with 0-499CP, greatball for 500-999, ultraball for 1000+cp And currently, we cannot change that.

**Comment by Tadukiari** [comment]
Ok, another problem, the location set can not be permenently where we want? Bcz every time the bot closes the location resets to New York. I want to lock Sydney.

**Comment by cyl2usdragoon** [comment]
I set on you, but it is also the same.
![image](https://cloud.githubusercontent.com/assets/20928244/17526920/7f5ec01e-5e93-11e6-9056-dd1afa997ef8.png)

**Comment by cyl2usdragoon** [comment]
thxxx

**Comment by Lentsha** [comment]
@Tadukiari The bot saves the last location you set, unless you open the map from the settings window. You can check that with the greyed coordinates before and after openning that map used to choose start location.

**Comment by xJustx** [comment]
^
