### ISSUE TITLE
Feature Suggestion: Add Evolve Preference

### ISSUE THREAD

**Issue by lilemon** [Ar1i/PokemonGo-Bot#2387]
This is just suggestion

Right now, it seems like auto-evolve starts from the lowest CP of all evolve-able pokemons.

Would love to have the bot take the following preference as evolve options if possible:

- When evolving, evolve from the highest IV/CP
- Automatically use LuckyEgg when there are more than 60 evolvable pokemons (number changeable)
- Evolve when Pokemon Inventory is over 90% full (number changeable) (so not always evolving)

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
