### ISSUE TITLE
bot doesn't hatch eggs

### ISSUE THREAD

**Issue by PHDVALLI** [Ar1i/PokemonGo-Bot#2389]
hi,
the bot doesn't hatch eggs... any solution?

Thanks in advice

**Comment by xRealMaks** [comment]
Hatch or automaticly put in incubators?

**Comment by jmo93** [comment]
Good morning

**Comment by PHDVALLI** [comment]
automatically put in incubators...

**Comment by xRealMaks** [comment]
#2360 #2354 #2352 #2011 #1551 #2290 #2281 #2383
