### ISSUE TITLE
Can you make it more friendly? Read this

### ISSUE THREAD

**Issue by Flareons** [Ar1i/PokemonGo-Bot#2390]
Can you make this GUI?

http://prnt.sc/c3m7yu

I have problem about the logic of Transfering Pokemon.
Can you make it more specified?

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Flareons** [comment]
Is this not an issue?

I dont know. Is this an issue or i just dont know how to use the transfer.
every day, i just setting the Max IV to 95% and Max CP to 1000
but still keep pokemons under 95% and Under CP 1000
Example : zubat - CP 43 - IV 35%

Can you tell me how to configure it Just keep pokemons over 95% IV ?
Just IV.

**Comment by Flareons** [comment]
@xRealMaks

**Comment by xRealMaks** [comment]
Maybe this is still active?
![pic](http://i.m4ks.cf/WOX1zgad.png)
