### ISSUE TITLE
[BUG] Tooltip on Pokemon List shows capture date: Today + 1d + 1Y

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2392]
When put cursor on Pokemon of list it shows supposed captured date (right?).

However is showing today's date +1 day + 1 year.
..

![bot1](https://cloud.githubusercontent.com/assets/20780971/17527356/fdb81324-5e62-11e6-949d-4df4a6f66e9d.png)

**Comment by xRealMaks** [comment]
I will forward it. Thanks for report. :+1:

**Comment by emilie253** [comment]
and for me (french) + 2 hours ^^
