### ISSUE TITLE
Why is it crashing with 500km/h

### ISSUE THREAD

**Issue by Probey1337** [Ar1i/PokemonGo-Bot#2394]
almost every 20 minutes is my Bot crashing. with 500km/h and im just getting 50-70k exp why?

why can i not get 100k or 200k exp? with 500km/h i should get (just from the pokestops) about 400-500k exp/h

**Comment by JeCelle** [comment]
What are you? Like a bullet train?

**Comment by Probey1337** [comment]
but a german developer wrote in a Interview that he gained 500l exp/h and 500poke/h he did short jumps to the pokestops. So short that the Niantics server didnt detected it. why do i just get 50-70k and he 500k?

**Comment by xRealMaks** [comment]
Maybe he used another bot..
Lower your speed and it wont crash anymore.

**Comment by Emmi911** [comment]
That was a while ago. Niantic now detects that. 50-70k is alot i get 30k

**Comment by JeCelle** [comment]
Maybe you're referring to another bot. "Haxton"
![image](https://cloud.githubusercontent.com/assets/20881462/17528816/62a16548-5ea3-11e6-98fe-8f5aa33f3b05.png)

**Comment by Probey1337** [comment]
im getting 50-70k exp with 500km/h and also 50-70k exp with 15-50km/h

**Comment by Probey1337** [comment]
Im getting more pokemon with slower speed and the same amount of pokemon

**Comment by Probey1337** [comment]
does any1 know good poke nests?

**Comment by xRealMaks** [comment]
Thats cause you are so fast, that if you walk to a pokemon with 500 km/h you walk away gain (you miss them.)

**Comment by mariobros33** [comment]
So what the perfect speed and radius?

**Comment by Experte9** [comment]
15-20km/h and 3000m
