### ISSUE TITLE
[ERROR] looping at strarting

### ISSUE THREAD

**Issue by toroageito** [Ar1i/PokemonGo-Bot#2395]
![untitled](https://cloud.githubusercontent.com/assets/20931857/17528245/c1a43fb2-5e98-11e6-8fe2-40650ece7167.jpg)

**Comment by Buddhasama** [comment]
http://www.mmoserverstatus.com/pokemon_go

Servers are unstable

**Comment by toroageito** [comment]
oh. i see.
Great bot, btw.
GJ
