### ISSUE TITLE
Banned for good.

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#2396]
Got soft banned on all my 3 bots (which never happened before) and then I keep having this (which also never happened before)
[14:23:58] We can't find any PokeStops in a range of 5000m!
[14:23:58] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

Am I definitly banned?

**Comment by PokePro21** [comment]
use only 2 bots

**Comment by CowMadness** [comment]
Yeah, found out that I can't have 3 bot now for some reason. But, how do I fix this?

**Comment by NaveTK** [comment]
no, you're not banned. turn your bots off, wait 5 minutes, start them again... did you only have 3 bots running or more than that? or did somebody maybe start the original app on his phone while using the same wifi as your bots? (that would count as a fourth account connecting from the same ip and thus softbanning all of them)

**Comment by dragobite** [comment]
Change your ip, simply go to router config and change it or dl hotspot shield.

**Comment by sunit1998** [comment]
just delete configs of all 3 bots and start them again and u will be done

**Comment by elenex23** [comment]
look in the forum first before just blindly posting the same issue over and over

**Comment by JCortexs** [comment]
im with 3 bots and working!

**Comment by elenex23** [comment]
I wish I could get three to work =( Max I can have is one for some reason.

**Comment by JCortexs** [comment]
if i get 4 working it freezes my pc

**Comment by Hydro420** [comment]
Post "Banned for Good" without doing any research? .... :/

**Comment by xRealMaks** [comment]
You'll get softbanned if you use more than 2 bots at the same time. Niantic changed that.
You should shut-down one bot and the unban-script run
