### ISSUE TITLE
Polish Translation (Not issue just request) 

### ISSUE THREAD

**Issue by maku001** [Ar1i/PokemonGo-Bot#2398]
Firstly sorry that I'm writing on issue buy Could you guys added a Polish translation of course when you will make an update. If you can, here it is; 

{
"accountType":"Rodzaj konta:",
"username":"Nazwa uzytkownika:",
"password":"Haslo:",
"locationSettings":"Ustawienia lokalizacji",
"speed":"Predkosc:",
"moveRadius":"Zasieg:",
"meters":"metrów",
"startFromDefaultLocation":"Zacznij od domyslnej lokalizacji",
"botSettings":"Ustawienia bota",
"autoTransferDoublePokemon":"Automatyczny transfer powtarzajacych sie pokemonów",
"maxDupPokemon":"Maks. ilosc powtarzajacych sie pokemonów",
"maxCPtransfer":"Maks. CP do transferu:",
"maxIVtransfer":"Maks. IV do transferu:",
"telegramSettings":"Ustawienia Telegram",
"infoline1":"Ten bot jest darmowy i jest open-source! Natychmiast zazadaj zwrotu pieniedzy jezeli za niego zaplaciles!",
"infoline2":"Jezeli napotkasz sie na nazwe 'Pokecrot', powiedz im, ze bot zostal skradziony",
"maxPokeballs":"Maks. Pokeballe:",
"maxGreatballs":"Maks. Greatballe:",
"maxUltraballs":"Maks. Ultraballe:",
"maxMasterballs":"Maks. Masterballe:",
"maxRevives":"Maks. Revives:",
"maxTopRevives":"Mak.s Top Revives:",
"maxPotions":"Maks. Potions:",
"maxSuperpotions":"Maks. Superpotions:",
"maxHyperpotions":"Maks. Hyperpotions:",
"maxToppotions":"Maks. Toppotions:",
"maxRazzberrys":"Maks. Razzberry:",
"totalCount":"Razem:",
"pokemonNotToTransfer":"Pokemony - nie przenosic",
"selectAll":"Zaznacz wszystko",
"pokemonNotToCatch":"Pokemony - nie lapac",
"pokemonNotToEvolve":"Pokemony- nie ewoluowac",
"saveConfig":"Zapisz konfiguracje / Wlacz bota",
"otherSettings":"Inne ustawienia",
"useLuckyeggAtEvolve":"Uzyj Lucky Egg podczas ewoluowania",
"germanPokemonNames":"Niemieckie nazwy Pokemonów",
"useIncese":"Uzyj Incense co 30 minut",
"evolvePokemonIfEnoughCandy":"Ewoluuj Pokemony gdy jest wystarczajaca ilosc cukierków",
"enablePokemonListGUI":"Wlacz liste z posiadanymi Pokemonami",
"keepPokemonWhichCanBeEvolved":"Zachowaj pokemony, które mozna ewoluowac",
"autoIncubate":"Automatyczne wykluwanie",
"useBasicIncubators":"Uzywaj zwyklych inkubatorów",
}

**Comment by xRealMaks** [comment]
Thanks for your work, but submit a pull-request please.
This is only for issues.

**Comment by maku001** [comment]
Sorry, already done it. Thx
