### ISSUE TITLE
1 sujestion to help bot.

### ISSUE THREAD

**Issue by Tadukiari** [Ar1i/PokemonGo-Bot#2399]
I have a sujestion.
Bot with % of chocking egg.
Pernently spot location when we want that location.
Auto Egg chock
Caught pokemon and transfer imedeatly if CP doesnt match want we want.

Its opinions.
Btw sry for bad english. :)

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
