### ISSUE TITLE
Skiplist (one of the mostly asked feature)

### ISSUE THREAD

**Issue by Dmnation** [Ar1i/PokemonGo-Bot#24]
To farm specific pokemons and to avoid 400 taubsis and 300 rattfratz, a skiplist would be perfect.
I think that this is one of the mostly asked features and this will be one of the best features :)

Thanks for this wonderful work! This coder is amazing!!

**Comment by Ar1i** [comment]
Adding that, thanks for the Suggestion.

**Comment by Dmnation** [comment]
You're the best!
