### ISSUE TITLE
Help - Captured Pokemon Flooding

### ISSUE THREAD

**Issue by singh763173** [Ar1i/PokemonGo-Bot#2400]
Hi guys,

As the menus have now been hidden and reside in the config files, I need a little help.

I want to only keep 3 of the top level pokemon each however I keep capturing them all and filling my available spots.
I don't want stop capturing them, I want it to keep capturing but transfer them so that only the top 3 are kept if that makes sense.

Is this possible?

Thanks

**Comment by xRealMaks** [comment]
This is working. Maybe you should disable the "keep pokemons which can be evolved".

**Comment by singh763173** [comment]
Hi xRealMaks, I'll give that a try.

In case it's useful, my config file is below

`Google
User
Password
Long
Lat
0
50
5000
True
True
3
True
999


5000
1
True
False
True
90
True
True
True
True
True
`

**Comment by xJustx** [comment]
Is it working now?

**Comment by singh763173** [comment]
Sort of but I still have multiples (I.e more than 3 of certain Pokemon :( so not 100% sure)

**Comment by xRealMaks** [comment]
![pic](http://i.m4ks.cf/vNbhspKq.png) uncheck the marked checkbox

**Comment by blaik2k4** [comment]
i have the app configured to save 1 pokemon dup and i still have like 10 poliwags its a bug in the app its a bug thats been there for a while

**Comment by amaslkw** [comment]
posted similar issue but it got closed. didnt have time to reply it 
#2046 
it is still happening to me and its not zubat only now. its happening to my psyducks too.
they just keep stacking up even their IV is low. and I did uncheck the "keep pokemons which can be evolved option"

**Comment by blaik2k4** [comment]
Me too

**Comment by singh763173** [comment]
Glad it's not just me!

I unticked the box and it still appears to be happening :(

**Comment by xRealMaks** [comment]
@blaik2k4 Maybe they're over 1000 CP and/or over 90% IV (standard settings)?

**Comment by singh763173** [comment]
xRealMaks - not defo a lot of them are over 1000 (any way to change this so it disregards levels - I only ever want the top 3) but at the same time, it also retains those under 1000.

Same with IV - it disregards over or under.

**Comment by xRealMaks** [comment]
![s](http://i.m4ks.cf/kYZ2ABLI.png)
Every Pokemon over 999 CP (in my case) wont be transfered even if it is th 4th, 5th or 6th...

**Comment by singh763173** [comment]
Thanks @xRealMaks looks like this is working now - need to play with the Max IV to transfer field as well but I think it's doing as I need!

Thanks again - closing the thread.

**Comment by singh763173** [comment]
Actually need to re-open - looks like I've found a bug. It transfers the highest rather than the lowest! :(

**Comment by xJustx** [comment]
#2564

**Comment by blaik2k4** [comment]
YouCaring     YouCaring is dedicated to compassionate crowdfunding,
providing free and easy online fundraising and support for humanitarian
causes. 
                   View Online
<https://www.youcaring.com/rickbowen-917483?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
<https://www.youcaring.com/?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
             Help Before Homeless
<[[FundraiserURL]]?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
       Rick Bowen wants you to know about this fundraiser..     My Name is
Rick. I am 37 years old from Auburn NY. I have gone through some hard
circumstances lately. my roommates moved out suddenly a month a head of
schedule and i cant afford to live here now. If I can Raise my fund raiser
I have a place to go with a job. Please have a heart. If you cant give...  
           View Fundraiser    
<https://www.youcaring.com/rickbowen-917483?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
        *This message was sent by Rick Bowen through YouCaring.com*. 
 Please do not reply to this message as Rick Bowen will not receive your
email.        Help spread the word about this fundraiser
<https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
<https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
<https://api.addthis.com/oexchange/0.8/forward/email/offer?url=https%3a%2f%2fwww.youcaring.com%2frickbowen-917483&pubid=ra-540f22690b78f120&ct=1&title=Help+Before+Homeless&pco=tbxnj-1.0?utm_source=mandrill&utm_medium=email&utm_content=GNL-Share-Email&utm_campaign=Action-Based-Gnl-Trx>
                  What is YouCaring?   YouCaring is a FREE Crowdfunding
Platform that empowers people to help others overcome hardships and enjoy
happier, healthier lives.             Find out more    
<https://www.youcaring.com/free-fundraising?utm_source=mandrill&utm_medium=email&utm_content=Link&utm_campaign=Donor>
                     
——————————————————————————————————





This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
unsubscribe from this list (http://mandrillapp.com/track/unsub.php?u=30332225&id=4f385f68ed6f46f59be9de84b72de888.dvVZXosIP9cbFRQXalpmGmmeIGo%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dreply%252B013f27b0567667b3af8c291b5ef8bb91c716225d1e873b4d92cf0000000113c24c7992a169ce0a25a5c9%2540reply.github.com)
