### ISSUE TITLE
Pokemon run away

### ISSUE THREAD

**Issue by 0ny** [Ar1i/PokemonGo-Bot#2402]
![d](https://cloud.githubusercontent.com/assets/20843226/17529091/4b5d2290-5e72-11e6-922b-7bd43b460b4e.PNG)

have this like 100 times, so i dont get any pokestops and wasting my time

**Comment by Damantium** [comment]
Your Pokéballs are set to 0, you need pokeballs change your item list

**Comment by 0ny** [comment]
its set to 50

**Comment by KennyHK9** [comment]
yes. you set to 50. but your bag is full. not get pokeball in pokestop

**Comment by arjunvegda** [comment]
Because pokemon go servers were down. They are still laggy

http://www.mmoserverstatus.com/pokemon_go

**Comment by Hydro420** [comment]
Use these settings.., Its been posted countless times & you can find the solution to your problem rather quick (as did I yesterday).

![untitled](https://cloud.githubusercontent.com/assets/20824888/17530370/d0608bf2-5e3c-11e6-8ff6-8f847d3475a4.png)

![untitled2](https://cloud.githubusercontent.com/assets/20824888/17530375/d4a9add8-5e3c-11e6-8df9-ab0775fc724a.png)

**Comment by xJustx** [comment]
^
