### ISSUE TITLE
Pls add a list to select all pokemon which will be transfered instantly

### ISSUE THREAD

**Issue by Probey1337** [Ar1i/PokemonGo-Bot#2405]
Pls add a list to select all pokemon which will be transfered instantly

Golbats are annoying

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
