### ISSUE TITLE
Bot Crashes after 10 min

### ISSUE THREAD

**Issue by markprisacaru** [Ar1i/PokemonGo-Bot#2406]
No record of crashing/shutting down randomly after 10 min in any of the log files.
Dont know what to do.

**Comment by xJustx** [comment]
Please restart your PC and try it again.
And make sure you have the newest version.

**Comment by markprisacaru** [comment]
did that

**Comment by xJustx** [comment]
Is it working now?

**Comment by Hydro420** [comment]
Must be since they just disappeared (seems like).

**Comment by markprisacaru** [comment]
it works 10 min then just disappears
no traces in task manager

**Comment by getta22** [comment]
me too :S
