### ISSUE TITLE
Issue with Finding and Catching Pokemons

### ISSUE THREAD

**Issue by Bizarrd** [Ar1i/PokemonGo-Bot#2407]
Hey, first of all thanks for the great work @Ar1i. I really appreciate the time you invest in this project.

This is more or less an issue but more a suggestion.
Is it possible to invert the row the bot is working? I'm mean, as you can see in the picture, the bot found a Pokemon, he is posting the Updates (what is actually great) then he recycles and transfers first instead of catching the Pokemon first. Is it possible that after he finds a Pokemon he will catch it immediately? Because sometimes after recycling and transferring the Pokemon is gone.

Thanks a lot :)
<img width="406" alt="bildschirmfoto 2016-08-09 um 21 01 17" src="https://cloud.githubusercontent.com/assets/20934116/17529993/dbf51184-5e75-11e6-865e-95e7b248a6f7.png">

**Comment by JKK2** [comment]
Leider sind alle Pokemon nicht fangbar. Ich habe keinen Softbann und trotzdem entwischt jedes Pokemon. danach wird das gleiche Pokemon wieder versucht zu fangen
![2016-08-09](https://cloud.githubusercontent.com/assets/20934266/17530208/ea5fcb0a-5e76-11e6-8465-7edfebf3fce4.png)

**Comment by JKK2** [comment]
Leider sind alle Pokemon nicht fangbar. Ich habe keinen Softbann und trotzdem entwischt jedes Pokemon. danach wird das gleiche Pokemon wieder versucht zu fangen. ACC daten habe ich vom Bild gelöscht!
Erstmal vielen Dank für deine arbeit @Ar1i 
![2016-08-09](https://cloud.githubusercontent.com/assets/20934266/17530386/953cc064-5e77-11e6-96a8-88ef780cf80d.png)

**Comment by JKK2** [comment]
Leider sind alle Pokemon nicht fangbar. Ich habe keinen Softbann und trotzdem entwischt jedes Pokemon. danach wird das gleiche Pokemon wieder versucht zu fangen. ACC daten habe ich vom Bild gelöscht!
Erstmal vielen Dank für deine arbeit @Ar1i 
![2016-08-09](https://cloud.githubusercontent.com/assets/20934266/17530423/bf2a7fba-5e77-11e6-94fd-a2f1ba5108b9.png)

**Comment by xRealMaks** [comment]
Hast du genug normale Pokebälle?

**Comment by Hydro420** [comment]
It just happens sometimes - bot is traveling too fast.. if you ever played the game on cell while driving in car you will run across same issue.

**Comment by JKK2** [comment]
Ja hatte genug normale Pokebälle.... habe alles gelöscht uns jetzt noch mal versucht. Jetzt geht es wieder. Komisch komisch :D trz danke

Aber ich feier euch einfach so derbe für den Bot. Wohne so fern ab vom schuss ohne den bot findet man einfach seltene Pokemon gar nicht :D und habe auch nicht so lust für pokemon go jedes mal 100km oder so zu fahren! Ein fettes Danke schön!
