### ISSUE TITLE
Softban

### ISSUE THREAD

**Issue by xmagiczreaction** [Ar1i/PokemonGo-Bot#2408]
I get a Softban every 5 min and i dont know why.
65km/h
radius 2,5km

**Comment by Probey1337** [comment]
65km/h is to much

**Comment by xmagiczreaction** [comment]
@Probey1337 how fast are you going?

**Comment by Probey1337** [comment]
50km/h i get also softbanns if im going faster but thats because Niantic

**Comment by marcop888** [comment]
I get a Softban every 5 min too

**Comment by Tymoc** [comment]
Change your speed... I have mine at a pathetic 14kph... but NO ban whatsoever after almost 8 hours...

**Comment by marcop888** [comment]
i restart the bot and then no poketops are detected.. T_T

**Comment by czokalapik** [comment]
I got softbanned maybe 3 times in two days with speed set to 10-22km/h (i'm changing it every time i launch the bot, keeping it under hatching speed - 24km/h).

**Comment by xJustx** [comment]
^
