### ISSUE TITLE
Start/Stop button

### ISSUE THREAD

**Issue by QustomiZed** [Ar1i/PokemonGo-Bot#2409]
Pls give it to me :( i pay for it!

**Comment by FadeEntity** [comment]
This isnt an issue just close the bot when you want it to stop and open it when you want to start it again

**Comment by QustomiZed** [comment]
Its just for sniping alot easier with a stop button dude.

**Comment by QustomiZed** [comment]
otherwise i get a softban

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
