### ISSUE TITLE
Best Coordinates?

### ISSUE THREAD

**Issue by favtim96** [Ar1i/PokemonGo-Bot#2410]
Hello Pokemon Trainer, 

at the last time I often search for many good Spots where you can catch em all.

-Where can I make many XP?

-Where can I catch Pokemon like; Snorlax, Dragonite, Bulbasaur, Squirtle, Growlithe, Kangaskhan and many more legendary Pokemon?

-Where can I find many Pokemon per hour?

All Tips and Coordinates please with kmH and range of meters.

Thank you very much!

Sorry for my bad English

**Comment by Affenasmo** [comment]
Not an issue plz close

(as for ur question...big cities...sydney/Tokio/NY/London/Paris)

**Comment by favtim96** [comment]
Where can i ask my questions?

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
