### ISSUE TITLE
IV transfer issue

### ISSUE THREAD

**Issue by delta-dude** [Ar1i/PokemonGo-Bot#2412]
Somehow programm transfers wrong pokemons.. example: Psyducks with IV 78 and 39, when there's a 46 and 35 left now.. out of 4 previously. Why doesn't it transfer those with lowest IV? It already transfered some of my 80+IV pokemons..

I want to transfer those duplicates with lowest IV, and set not to transfer above 80 IV, but if I  have none above 80, I'd like bot to count the highest IV as non-transferable if he wants to get rid of duplicated ones.

**Comment by delta-dude** [comment]
And I want to add, that it also transferred automatically 4/4 magnetons, leaving me only 2 magnemites, thought it was set to duplicates above 2 only..

**Comment by xRealMaks** [comment]
If the max setting for one pokemon is set to 3 and you catch the 4th one, the bot transfers the pokemon with the lowest CP (at least i think so)

**Comment by delta-dude** [comment]
@xRealMaks yeh, that's sad part. CP is smth u can increase, IV is smth that you can only be lucky with. There should be an option which sets a priority CP/IV

**Comment by xRealMaks** [comment]
Ok.. Now I got it.
This is not an issue, so normally I had to close this. But I'll mark this as an enchancement, because it would be more logic to transfer low IV pokemons.

**Comment by delta-dude** [comment]
@xRealMaks Thanks pal

**Comment by FerMedina86** [comment]
transfer first low IV pokemones would be excellent

**Comment by chusski** [comment]
Yeah, we need option to bot ignore CP and compare IV its more relevant. ( CPs can be upgraded but IV its only luck )
And an option to ADD pokemons to favorite list will be great too. ^^
