### ISSUE TITLE
traduction liste pokemon

### ISSUE THREAD

**Issue by k756u** [Ar1i/PokemonGo-Bot#2413]
I finished the translation of the list pokemon in french or I post ?

**Comment by xJustx** [comment]
You can do a pull request for this. Thanks for your help!

**Comment by xRealMaks** [comment]
Or you can post it here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by k756u** [comment]
I do not just happen : P make a pull request ^^'
no problem assistance is keyword in this area :)
