### ISSUE TITLE
cant catch any pokemon

### ISSUE THREAD

**Issue by daniverr** [Ar1i/PokemonGo-Bot#2415]
i was able to catch pokemons an hour ago but now all i see is the same pokemons over and over again and still unable to catch em

http://puu.sh/qvxZC/5b34b83917.png

got the latest version btw

**Comment by loudjedi** [comment]
check if you have any normal red pokeball ...... if not ..... you have t change settings (y) ;)

**Comment by FerMedina86** [comment]
try Force unban !

**Comment by xRealMaks** [comment]
Check if you got enough normal pokeballs

**Comment by Kossmyn** [comment]
same problem here, i don't have ban, first i had just ultraballs and now i have all 3 pokeballs, and is not catching any of the pokemon

**Comment by xRealMaks** [comment]
set the max amount of pokeballs to 20 to make sure that you got enough when you try to catch a pokemon. 
Pokemon < CP 500 get caught with normal pokeballs

**Comment by daniverr** [comment]
Well now it's not picking up any item from the pokestops, says my inventry is full, and its not!

**Comment by xRealMaks** [comment]
Send a screenshot of your console, please

**Comment by daniverr** [comment]
http://puu.sh/qvzrK/a8fa1539c2.png

**Comment by xRealMaks** [comment]
Please delete the configs folder and start the bot again

**Comment by daniverr** [comment]
Okay it works now! Thanks!
http://puu.sh/qvA3S/6ad3777f52.png

**Comment by xRealMaks** [comment]
No problem.
