### ISSUE TITLE
A task was canceled

### ISSUE THREAD

**Issue by Jinnocid** [Ar1i/PokemonGo-Bot#2417]
![image](https://cloud.githubusercontent.com/assets/20916720/17533826/1868aba6-5eb9-11e6-9970-b7e396849b49.png)

**Comment by xJustx** [comment]
Please try to reinstall your .NET Framework.

**Comment by Jinnocid** [comment]
Nope it didnt fix it , and still having the same error

**Comment by Jinnocid** [comment]
I Noticed that i couldnt logged into my phone as well then i realize it might be an IP Issue, since my ISP made my Line a Dynamic i just reset my router and i got a new Address then the problem is gone i think they are tracing it and IP banning peepz
