### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by Vxphal** [Ar1i/PokemonGo-Bot#2420]
sorry friend I asked, IV it what it does ?

sorry i'm newbie

**Comment by Hydro420** [comment]
Hidden stats of pokemon - % 0-100  (Attack, Defense, Stamina). Higher % higher stats thus the better the pokemon. This will most likely be implemented into the game at some point in time.

**Comment by xRealMaks** [comment]
IV is the "Quality" of the Pokemon. You got Attack, Defense and Stamina. All 3 got their max at 15. 

Example: Your Magikarp got 15-15-14 stats.
So your Magikarp got 44/45 which is 0,977 which is 97.7%

btw: This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
