### ISSUE TITLE
Every pokemon gets away 

### ISSUE THREAD

**Issue by AngryJerbear** [Ar1i/PokemonGo-Bot#2421]
While using the bot every pokemon that pops up escapes how do i fix this?

**Comment by xJustx** [comment]
It's possibly that you're softbanned. On the other hand it's possible that you don't have any pokeballs. Can you check it please?

**Comment by AngryJerbear** [comment]
Im not soft banned its picking up poke stops and i have lots of pokeballs and razzberries

**Comment by Sintonic** [comment]
same problem. I am not soft banned!

**Comment by DomeSs97** [comment]
Look on items.. do you have normal pokeball set on 5-10 pcs?

**Comment by akv70** [comment]
Hey i have this problem too

**Comment by xJustx** [comment]
Mh... strange. For me it's working:
![pic](http://i.xjustx.cf/s0uCI7v4.png)

**Comment by AngryJerbear** [comment]
mines kinda working now

**Comment by AngryJerbear** [comment]
most are escaping but some arent

**Comment by DomeSs97** [comment]
do you have "Razz Berries" ? when i dont have Razz Berries.. pokemons go away.. 1 from 5 is catchable..

**Comment by eLDeMe** [comment]
you need to have normal pokeballs always

**Comment by joe112** [comment]
We can't find any PokeStops in a range of 20000m!
[06:20:18] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

**Comment by xJustx** [comment]
@joe112 Please open a new issue if you have another problem.

**Comment by eLDeMe** [comment]
@joe112 you are sofbaned, you need to wait 5mins or get a new IP, do not open more than 2 instances (bot) at the same time

**Comment by hevelins** [comment]
You can harvest from poke stops right? Then you are not soft banned.
Check your inventory, you need to have normal pokeballs.

**Comment by Sifika420** [comment]
My lower level accounts are having no issues at all, but my higher level (32+) have some trouble catching pokemon when I run out of Razzberries. Unfortunately that seems to happen quite often past level 30.

**Comment by gitovahere** [comment]
@Sifika420 Thanks for letting me know. I'll set much higher Razzberries. I'm constantly running out of Razzberries even at level 28. Best to set it high (75).
