### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bluecito** [Ar1i/PokemonGo-Bot#2422]
I would like to ask if there is a chance to add in the bot options to "not stop in Pokestops" so we have more chance to get the Pokemons we look for, since it takes lot of time stopping on every Pokestop and sometimes the Pokemons we look for just dissapear. Thx for all

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
