### ISSUE TITLE
is this a false positive?

### ISSUE THREAD

**Issue by glabella** [Ar1i/PokemonGo-Bot#2424]
![false](https://cloud.githubusercontent.com/assets/19846525/17536893/2610963c-5ea1-11e6-8041-51f745448ab2.png)

**Comment by Inkedmadman457** [comment]
mine was doing that too, there is no virus on here. Just give it permissions and tell it to shut up lol

**Comment by Pyroman2300** [comment]
Yes its a false positive.

**Comment by xRealMaks** [comment]
Yes, its a false-positve.
If you dont trust us, you can check the code by yourself (Opensource :heart: )
