### ISSUE TITLE
BOT STILL CRASHING

### ISSUE THREAD

**Issue by ISim0nI** [Ar1i/PokemonGo-Bot#2428]
![8d2be8ca-2434-4db4-9582-f1e97df1c296](https://cloud.githubusercontent.com/assets/20937282/17537221/fa262d62-5e9a-11e6-8753-0fa151006811.jpg)
![925f80bc-9a3f-4c9e-993a-d0d35254cb2b](https://cloud.githubusercontent.com/assets/20937282/17537220/fa25e78a-5e9a-11e6-9f0d-35d1264b4328.jpg)

The bot crashes after a while.
Newest Version.
Crash is random.

**Comment by xJustx** [comment]
Wir schauen uns das morgen mal an. 
Wir können aktuell nicht feststellen, woran das Problem liegt. Ich gebe das mal weiter.

**Comment by ISim0nI** [comment]
Danke

**Comment by Farox1988** [comment]
Hmm Hab 3 Vermutungen 
1 Die Server sind Überlastet und deshalb kommen die bots nicht mit!
2 Und die andere wäre das Niantic wieder dazwischen funkt mit irgendeinem update!
3 Der Bot selber hat nen hau weg ( Pokebuddy läuft super) deshalb die vermutung ^^

Mfg Farox^^

**Comment by Safti54** [comment]
mein bot findet seit 2 stundne keine pokestops habs paar ma neu gestartet aber nichts püassiert

**Comment by xJustx** [comment]
@Safti54 Wenn du ein anders Problem hast, öffne bitte ein neues issue. Vielen Dank!

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
