### ISSUE TITLE
Being prompted for 2FA even though I don't use 2FA on my account

### ISSUE THREAD

**Issue by tehreverand666** [Ar1i/PokemonGo-Bot#2430]
![capture](https://cloud.githubusercontent.com/assets/20937562/17537796/90d892be-5e6d-11e6-8da1-005b227a9b07.PNG)

This a bug or not?

**Comment by xJustx** [comment]
It seems you're using 2FA!?

**Comment by tehreverand666** [comment]
But I'm not, never have.

**Comment by xJustx** [comment]
Mh.. I don't have any idea.
I would forward this. So please be patient.

**Comment by itsforscience** [comment]
The iPhone app just got updated....I wonder if there is a detect now.

**Comment by tehreverand666** [comment]
Ok I went ahead and setup 2FA and setup an App password and now it works again. I really don't want 2FA on my account but if it makes the bot work I'll do it :P so I guess this can be closed.

**Comment by xJustx** [comment]
Mh.. okay. You can try to disable 2FA now and try to use the bot.
