### ISSUE TITLE
Pokemon Go Rocket API stopped working

### ISSUE THREAD

**Issue by Xcutioner** [Ar1i/PokemonGo-Bot#2432]
Error running pokemon list.. problems withh rocket.API

![naamloos](https://cloud.githubusercontent.com/assets/20899664/17538505/4a849bee-5ea6-11e6-8fd6-bc73a7ce8cd6.png)

**Comment by xJustx** [comment]
Can you try to redownload the bot, set up him and try it again?

**Comment by Xcutioner** [comment]
Stil does not work

**Comment by Ar1i** [comment]
fixed
