### ISSUE TITLE
Can we change pokemon catching XP?

### ISSUE THREAD

**Issue by wauss417** [Ar1i/PokemonGo-Bot#2433]
I would like to get 100 xp (normal catch) instead 210 xp (perfect + curve catch), because i just want to farm dust and candies and high lvl it's getting suspicious.

**Comment by kayoriceball** [comment]
just disable catching and farm pokestops

**Comment by xJustx** [comment]
^
![screen](http://i.xjustx.cf/bKcCO571.png)

**Comment by RedDelfin** [comment]
He wants to farm dust and candys...  so he has to catch some pokemon!

**Comment by xJustx** [comment]
Mh.. you're right @RedDelfin ..
