### ISSUE TITLE
Constantly unbanning me.

### ISSUE THREAD

**Issue by kayoriceball** [Ar1i/PokemonGo-Bot#2435]

**Comment by kayoriceball** [comment]
![image](https://cloud.githubusercontent.com/assets/20828205/17538852/5dc6134c-5e77-11e6-9ba0-b0dce174f3a7.png)

**Comment by kayoriceball** [comment]
![image](https://cloud.githubusercontent.com/assets/20828205/17538858/671f35a4-5e77-11e6-8c5e-b3f7cd79e131.png)

**Comment by kayoriceball** [comment]
just switched to No Pokestops within 5000m.

**Comment by kayoriceball** [comment]
![image](https://cloud.githubusercontent.com/assets/20828205/17538892/a924fe3e-5e77-11e6-95e1-3f4aa0069a7d.png)

**Comment by Captnred** [comment]
What are you're settings? Need more info then a SS of how you're getting unbanned.

**Comment by kayoriceball** [comment]
Settings are literally default.

**Comment by kayoriceball** [comment]
Made sure to log out and close app on device as well.

**Comment by Captnred** [comment]
It seems you're most likely getting IP banned. Try resetting your router, or switching your IP in a VPN. (This is just an educated guess though.)

**Comment by OGcpalm** [comment]
don't run more then 3 bots

**Comment by lucas2107** [comment]
Unban don't work. Stop playing for 10 minutes and launch bots again. Don't run 3+ instances. 2 Max.

**Comment by kayoriceball** [comment]
I don't think I was running more than 1...

**Comment by JeCelle** [comment]
What about in your mobile devices? Are you the only one playing pokemon Go using your WiFi? (because they'd still count, and you can't have more than 2 playing PoGo)

**Comment by vootone** [comment]
Same thing happened to me, I think its because I logged on with my iPhone.. Will wait 10 minutes and try again..

**Comment by xJustx** [comment]
Is it working now?

**Comment by xJustx** [comment]
If the problem still occurs, please open a new issue.
