### ISSUE TITLE
Error initializing the boot.

### ISSUE THREAD

**Issue by piai46** [Ar1i/PokemonGo-Bot#2436]
Hello, I'm having an error in the boot startup, I do not know what is causing it, if anyone able to help me, please comment below.
Follow the error screenshot:
![image](https://cloud.githubusercontent.com/assets/20868902/17538841/96262918-5e7f-11e6-9a4f-45ce489fe499.png)

HUGS!

**Comment by xJustx** [comment]
It seems you're using a wrong email and/or password. Can you check it please?

**Comment by piai46** [comment]
Thank you!
