### ISSUE TITLE
Razzberry

### ISSUE THREAD

**Issue by snowdrop1018** [Ar1i/PokemonGo-Bot#2437]
Am I the only one that has the bot constantly using my berry?  Cuz I have my item count to like 70 berries but since the bot keeps using it, I only have 3 atm.  Please help

**Comment by Sifika420** [comment]
The bot used to have me at max berries all the time, even while it was using them. Lately I have 0 on most of my accounts, and its been failing at catching on my higher level accounts because of that. 

Not sure what to change, I tried messing around with max items but that didn't help.

**Comment by snowdrop1018** [comment]
yeah its something similar for me too.  Might be something they might wanna fix if they can on future updates.

**Comment by peoplearmy** [comment]
It will require a code change and new build.

**Comment by Captnred** [comment]
The bot will always use your berries to capture pokemon. There is no way around this unless they recode the bot and lets be honest they're not going to do that. You may get lucky and they'll add a feature to use berries or not. Till then please close your thread as this is not an issue.

**Comment by snowdrop1018** [comment]
yeah, i understand, thank you guys for you help :)
