### ISSUE TITLE
want to share good spot for bot?

### ISSUE THREAD

**Issue by redark77** [Ar1i/PokemonGo-Bot#2438]
hey huys. please share your good spot for bot. i need recommended place.

**Comment by blaik2k4** [comment]
peir 39 in California dratini nest

**Comment by Captnred** [comment]
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Comment by Pyroman2300** [comment]
^^

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
