### ISSUE TITLE
move big distances

### ISSUE THREAD

**Issue by GeneralAurelius** [Ar1i/PokemonGo-Bot#244]
just wanted to return from new york to my home in germany, but it doesnt work?
can i only use it in america?

**Comment by mauxak** [comment]
No, you can use it in the whole world. What is the console saying?

**Comment by GeneralAurelius** [comment]
that coords are differnent, but i fixed it now, just deleted the LastCoords.txt file :+1:

**Comment by Flocke90** [comment]
you need to remove the Configs/LastCoords.txt file, set new coords in the GUI, start the Bot, probably get soft banned but the ingame 1337-softban-routine will work that out for you. Grüße nach Deutschland :)

**Comment by GeneralAurelius** [comment]
yeah thanks :D but now it says, that there is no pokestop in range of 5000m :o

**Comment by mauxak** [comment]
Just wait, servers are having issues at the moment

**Comment by baeckstrom** [comment]
When jumping large distances it's a good idea to calculate actual travel by air to avoid soft-ban or eventual perma-ban in the future. Use http://www.travelmath.com/time/ or similar services.

**Comment by legalalien1994** [comment]
Hi guys! First off all... Biggest thanks ever! :) I want to ask you if i move from one city to the other inside the same country, can i get banned? Its like 30 minutes betwen them, should i wait that time before to move? Thank you all

**Comment by 13XxM1CHA3lxX37** [comment]
wait a bit

**Comment by legalalien1994** [comment]
All rigth! Thanks :)
