### ISSUE TITLE
Incubation not working at all!

### ISSUE THREAD

**Issue by s6fregne** [Ar1i/PokemonGo-Bot#2440]
Auto incubation doesnt work for me and my friends... also not every double pokemon types transfer automatically.

**Comment by Captnred** [comment]
This is a known issue on the incubation. As far as the pokemon go make sure you don't have keep evolvable pokemon checked.

**Comment by xJustx** [comment]
Currently it's not working.
But it will be added soon :p 
Please be patient.
#346
