### ISSUE TITLE
radius??

### ISSUE THREAD

**Issue by ricardorohde** [Ar1i/PokemonGo-Bot#2441]
Hi, i put move radius at 50000
and the maximun distance at pokestop is 2.8km...

that have 7 pokestop in my city, but found 4 :(

help!

**Comment by Captnred** [comment]
Have you been running the bot before you change the radius? Did the bot already hit those pokestops and the bot passed them before they came claimable again?

**Comment by ricardorohde** [comment]
yes, i set and re-open...
its start that point and running at 4 pokestop, others dont
see photo...
bot running at circle blue
![postop](https://cloud.githubusercontent.com/assets/12731085/17540523/46cf0c64-5e8d-11e6-8ae9-434634df7b32.png)

**Comment by Captnred** [comment]
It may be a radius issue have you tried playing with the numbers? Increasing them a bit more or decreasing? It may be that it might just further then the radius you have. Try that and let me know what happens.

**Comment by ricardorohde** [comment]
Hi, the distance of pokestop are 2.5 KM

in bot, i put 10000, 50000 and dont works :(

**Comment by ricardorohde** [comment]
[00:09:21] We can't find any PokeStops in a range of 50000m!
[00:09:21] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..
[00:09:21] Starting again in 10 seconds...

**Comment by ricardorohde** [comment]
not work in last version...
its found 4 pokestops, not 7 :(
