### ISSUE TITLE
Question about Transferring Pokemon

### ISSUE THREAD

**Issue by RolloutGaming** [Ar1i/PokemonGo-Bot#2443]
Was wondering if there is a way to transfer all duplicate pokemon but keeping the one with the higher CP. Thanks.

**Comment by Captnred** [comment]
Yes ctrl click all the pokemon you want to transfer, then hit transfer. 

Also this..

If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Comment by xJustx** [comment]
^
btw: This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
