### ISSUE TITLE
We cant find any PokeStops in a range of 5000m

### ISSUE THREAD

**Issue by wa666** [Ar1i/PokemonGo-Bot#2445]
![0e49312c716c4c98b141f5a5aaa87b98](https://cloud.githubusercontent.com/assets/20918380/17540811/c345d468-5eb9-11e6-9c22-05fe402c6e5c.png)
And you ?

**Comment by Safti54** [comment]
same sometimes working sometimes dont

**Comment by razalghul** [comment]
I have the same problem , and change ip, only with an account

**Comment by razalghul** [comment]
I have the same problem , and change ip, with an account

**Comment by Safti54** [comment]
I just öeave it alone it fixes it self after a cupple minutes but it still
not the best way for a bot to work ^^ but i still think the bot is great

Am Mittwoch, 10. August 2016 schrieb razalghul :

**Comment by filipilimarj** [comment]
I have this when i try to open more than 3 bots at same time... i`m opening just 3 and working normaly for while...

**Comment by chavall** [comment]
same problem after 5 minute, already change ip or restart, still same ^^

**Comment by ricardorohde** [comment]
i have this problem too

**Comment by kayoriceball** [comment]
I have this problem as well.

**Comment by NidiKea** [comment]
Me to

**Comment by pilota56** [comment]
Only 2 Bots at the same time. Renew IP and wait 15 - 20 Minutes.
My 2 Bots work fine since 8h.

**Comment by gummyruler** [comment]
@wa666  See if the server is up before posting. there are a lot of sites out there.

**Comment by xJustx** [comment]
Change your location und try it again please.
Try to change your proxy, if you're using one as well.

**Comment by ricardorohde** [comment]
not work in last version...

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone

**Comment by ricardorohde** [comment]
i running one bot! i reset my ip!

and bot search 4 of 7 pokestops :(

the raius distance not working
