### ISSUE TITLE
Every Pokemon gets away

### ISSUE THREAD

**Issue by Dmouse92** [Ar1i/PokemonGo-Bot#2449]
im not banned still getting stuff from pokestops any ideas thanks

**Comment by gitovahere** [comment]
Try this: https://github.com/Ar1i/PokemonGo-Bot/issues/1930#issuecomment-238158081

**Comment by Dmouse92** [comment]
Also my items are not changing thet are way over at 438/350? help

**Comment by gitovahere** [comment]
Yes, most of us have the same inventory count error. It's just a reporting error, it doesn't reflect your actual inventory. Just set regular pokeballs @ ~20. Let me know.
If you have plenty of standard pokeballs then the problem lies somewhere else. lol

**Comment by Dmouse92** [comment]
Also Im not getting my lvl up stuff any ideas

**Comment by Dmouse92** [comment]
and thank you

**Comment by Wolfie407** [comment]
I too was having this problem and I adjusted the items in my inventory.  It works just fine but sooner or later, it begins having the same issue once again.  Change the values again and it fixes but after a while, I keep running into this problem.

**Comment by xJustx** [comment]
@Dmouse92 Do you have enough Pokeballs?
