### ISSUE TITLE
What is the problem ?

### ISSUE THREAD

**Issue by Kelendris** [Ar1i/PokemonGo-Bot#245]
![untitled](https://cloud.githubusercontent.com/assets/20727621/17256892/cc68d61a-55bf-11e6-88c8-e382cce6100e.png)

**Comment by Oguzcan13** [comment]
Pokemon go servers are currently unavailable

**Comment by MarvinSCR** [comment]
5-10minutes waiting is normal

**Comment by plowzey** [comment]
Happening to me aswell.

**Comment by plowzey** [comment]
Problem has stopped and working fine for me now.

**Comment by Oguzcan13** [comment]
This is normal to wait a little stop ouvire positions for this type of error
