### ISSUE TITLE
Not getting lvl up stuff

### ISSUE THREAD

**Issue by Dmouse92** [Ar1i/PokemonGo-Bot#2450]
when I lvl up I dont get anything no lucky eggs or incubators! HELP PLEASE

**Comment by victorpiva** [comment]
Its normal @Dmouse92 , check here: http://www.ign.com/wikis/pokemon-go/Level_Rewards_and_Unlockable_Items

**Comment by Dmouse92** [comment]
THANK YOU

**Comment by victorpiva** [comment]
@Dmouse92 , please close the topic.
