### ISSUE TITLE
Found Dragonite

### ISSUE THREAD

**Issue by JunoBotboy** [Ar1i/PokemonGo-Bot#2451]
40.7531097060271/-73.9828651949341;Dragonite;636063828364324445;8/9/2016 11:40:36 PM

can anyone decipher this? i wanna know how i caught it.
Probably just a Ultra Ball....

40.7531097060271/-73.9828651949341 means where i found it

**Comment by JeCelle** [comment]
Can you not look at the logs from the Configs folder of the bot?

**Comment by JunoBotboy** [comment]
i cant look at it because i have the bot on

**Comment by JeCelle** [comment]
Ehh? How come? I can open mine just fine, even if the bot is running. Could you try opening it using Notepad++?
