### ISSUE TITLE
account banned?

### ISSUE THREAD

**Issue by auyeungsja** [Ar1i/PokemonGo-Bot#2453]
![image](https://cloud.githubusercontent.com/assets/20940998/17542122/92f5347c-5ef8-11e6-8e5a-94b950a19ef0.png)

**Comment by Dmouse92** [comment]
I think servers are just down.

**Comment by Bangden** [comment]
check connection

**Comment by sunit1998** [comment]
the servers are laggy due to new update and people are flooding in so u got that screen try to log in again and again and u will get inside the game.

**Comment by gummyruler** [comment]
Server update.

**Comment by xJustx** [comment]
^
