### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by shahroozal** [Ar1i/PokemonGo-Bot#2456]
So since the last hour or so it started to Only showing this Exceptions and does not work at all:
![unbenannt](https://cloud.githubusercontent.com/assets/20831147/17543028/e00a0b78-5ecd-11e6-8cfc-2332245f0d1b.png)

**Comment by hsc2712** [comment]
Same here

**Comment by joker041913** [comment]
got the same I restart and its working now.

**Comment by shahroozal** [comment]
@joker041913 restart the bot or the computer?
