### ISSUE TITLE
Error reloading pokemon list : Badauthentication

### ISSUE THREAD

**Issue by HunterzZ** [Ar1i/PokemonGo-Bot#2458]
i have that problem can someone help <3 ?

**Comment by PokeMungo** [comment]
1. close the bot. 
2. re-open bot :)

**Comment by 1337Panther** [comment]
Same error

**Comment by andyfeb** [comment]
Are you sure that your username and password is the right one?

**Comment by HunterzZ** [comment]
yeah

and pokemungo i did that every time but didnt work

**Comment by xJustx** [comment]
It seems that your username and/or password is incorrect. Can you check it please?
