### ISSUE TITLE
Vorschlag :)

### ISSUE THREAD

**Issue by shuksieno123** [Ar1i/PokemonGo-Bot#246]
wäre es möglich dass, der Bot auch Favorisierte Koordinaten anzeigt die man auswählen kann :+1: :?

**Comment by Oguzcan13** [comment]
he says "it would be possible that the bot also displays Favorite coordinates that you can choose"

**Comment by mauxak** [comment]
Deeper going thought: Share your best coordinates with others so that they can choose from a list of coordinates which were submitted by the users

**Comment by 13XxM1CHA3lxX37** [comment]
In implemention of this could also be helpful:
http://pkmngotrading.com/wiki/Nests
