### ISSUE TITLE
Cant find any Pokestops?!

### ISSUE THREAD

**Issue by favtim96** [Ar1i/PokemonGo-Bot#2463]
![fehler](https://cloud.githubusercontent.com/assets/20910729/17544659/dff4cd66-5ed8-11e6-97de-fb6f5e23d7bd.jpg)

**Comment by favtim96** [comment]
I have the newest Version

**Comment by tweetthehens** [comment]
same to me, they changed?

**Comment by andyfeb** [comment]
yes, me too. I'm using 3 sessions to botting 3 accounts.

**Comment by favtim96** [comment]
Niantic has updatet?

**Comment by sunit1998** [comment]
yes i think so there is a update or the servers are too unstable

**Comment by gummyruler** [comment]
Before posting this kind of issue please check if the server is on here: 
 http://downdetector.com/status/pokemon-go

**Comment by DomeSs97** [comment]
same to me after 72 hours..

**Comment by favtim96** [comment]
@gummyruler you are safe that this server Problems?

**Comment by johnykkk** [comment]
me2 same problem

**Comment by Guiseppe3** [comment]
Guys its over. Finally, I´m free !!!

**Comment by andyfeb** [comment]
@gummyruler well... I think this not about the server is down... because we can still load the pokemon list and the bot can login perfectly

**Comment by Guiseppe3** [comment]
The server might be down.
Tho I was having 2 accounts turned on. One of them couldnt find a Pokestop and the other one was constantly soft-banned (which is weird since ive been on the same spot the whole night)
It`s GG basically :)

**Comment by favtim96** [comment]
okay thank you
'closed
