### ISSUE TITLE
Radius Question

### ISSUE THREAD

**Issue by bouncyharu** [Ar1i/PokemonGo-Bot#2464]
Hi guys, i set the radius to 5000m , 10000m, 20000m and 30000m and i don't think it's working properly. Say i set it to 30000m, the pokestop it detected remained the same as if i have set it up @ 5000m.

**Comment by phodem** [comment]
u just need to find good spot. Im botting in 500m with 75 pokestop but way faster than the 5000m 256 pokestops radius. So don't worry about the radius and numbers of pokestop.
