### ISSUE TITLE
Can't find any pokestops, just happened!! 

### ISSUE THREAD

**Issue by Inf4mousEnergy** [Ar1i/PokemonGo-Bot#2465]
i don't get it , its been doing this for the past 5 minutes, can someone explain why???
https://gyazo.com/1b44623134f0dd6c610a82fc85f7916c

**Comment by wrobe06117** [comment]
server prob down cos i can log in my phone but no poke stops or gyms

**Comment by kickz** [comment]
I have same problem.

**Comment by Inf4mousEnergy** [comment]
Oh thank god , i thought i got a ip ban, because i'm only running one bot,

**Comment by favtim96** [comment]
yes this is right the server are down

**Comment by richie86** [comment]
same here. But I doubt it's server problem. More like API / handshake changed?
IP Ban? Tried changing my IP not work.
Server Problem? as soon as I got this problem, closed my bot. Open game with my phone and I can see the pokestop near by.

Current Location: Malaysia

**Comment by johnykkk** [comment]
hahahaha cool! is update!!!

**Comment by FGonzalezBon** [comment]
When see this problem only reload program.

**Comment by kickz** [comment]
Its interesting, because i couldnt see no gym / pokestop in game.

**Comment by favtim96** [comment]
@kickz yes and this is why the bot is not working beacause niantic have shit server :dancer:

**Comment by kickz** [comment]
But my friend dont have problem with it on Android.

**Comment by basvb1** [comment]
Bluestack also down only roads no pokestops

**Comment by gummyruler** [comment]
@kickz PTC and Gmail accounts have different servers. 

Before posting this thing try to see if the server is on or OFF come on. there are a lot of sites out there.

**Comment by Yummster** [comment]
Google account now working again, must have been their servers

**Comment by kickz** [comment]
@gummyruler  Omg i saw the status server, so please try stop saying again.
Check it: https://p.datadoghq.com/sb/1xfifX-a17f211ecb?tv_mode=true

**Comment by kickz** [comment]
Now i test  PTC login and Google,  everything is good but in game is problem with display pokestop and gym, pokemons nerby.

**Comment by Yummster** [comment]
Hmm, server status is a ok, but now both ptc and google accounts are soft banning.

**Comment by basvb1** [comment]
other account  is not used in the bot is also not displaying pokestops

**Comment by xxhamsterxx** [comment]
www.ispokemongo.online
My current position should be online

**Comment by TrainerNr1** [comment]
Seems only one bot works at same time now :(.

**Comment by duyphuc1610** [comment]
same here :(

**Comment by kickz** [comment]
So, for this moment please try again run game in your mobile devices, i have display pokestop, gym and pokemons :)

**Comment by Yummster** [comment]
Went on game on device and was able to access stops but noticed the driving warning popping up regularly. lowered my speed in the bot and it seems to be running quite happily... for now.

**Comment by tommyjai** [comment]
TrainerNr1 :Seems only one bot works at same time now

**Comment by kickz** [comment]
Bot works now.

**Comment by kickz** [comment]
![screen](https://cloud.githubusercontent.com/assets/14926592/17546353/fe6e5f6a-5ee1-11e6-8fd2-457d51f8dcad.PNG)

**Comment by duyphuc1610** [comment]
why it doesn't work for me

**Comment by Yummster** [comment]
As soon as I started a second bot I got soft ban detected. No problems now running just the one bot.

**Comment by kickz** [comment]
After some minutes my problem was gone. So try wait some minutes.

**Comment by duyphuc1610** [comment]
kickz, where is the location that you bot ?

**Comment by Inf4mousEnergy** [comment]
Perfect, bot and servers are up for me now

**Comment by duyphuc1610** [comment]
where is location ?

**Comment by kickz** [comment]
I said it @Inf4mousEnergy, i am glad to hear it :+1:

**Comment by Inf4mousEnergy** [comment]
Duy, what do you mean man? like where my bot is located atm?

**Comment by duyphuc1610** [comment]
yeah, because in Aus still can't find anything :(
 it said "We can't any pokestop"

**Comment by Inf4mousEnergy** [comment]
Currently in central park, if that's what you're asking for 40.764883 , -73.972967

**Comment by kickz** [comment]
Location must be near you, because when you will try big distance, so you will have problem with strange (fast) move to other locations or countries and it will cause Softban

**Comment by duyphuc1610** [comment]
i always bot in my location, but since the server was going down, so I have error like this

**Comment by Inf4mousEnergy** [comment]
ya just wait till they get back up in your location, that's what i'd suggest for the mean time, that's what i did atleast

**Comment by duyphuc1610** [comment]
I try to bot in default location, but it doesn't work

**Comment by richie86** [comment]
got it work a while and not working again. probably give it a rest now.

**Comment by kikado** [comment]
Had 2 bots running and they can't find any pokestops.
Turned both bots down and restarted one of them, still cant find any pokestops.

Changed IP using VPN, started ONE bot and it's working.

**Comment by andyfeb** [comment]
I think it's already work... this issue can be closed :)

**Comment by Logxn** [comment]
IP Ban yes.
2 bot ban - no
