### ISSUE TITLE
[FYI] - Various errors while using bot

### ISSUE THREAD

**Issue by cyb0rg01** [Ar1i/PokemonGo-Bot#2467]
Lately I am experiencing various error while using the bot. Nothing is really big, just for your information to investigate further. (take a look at screenshots below)

The only thing, which brings the bot getting crashed is when "Auto reloading" is triggered and you are powering up your Pokemons to the maximum. While the system is still powering up Pokemons and the bot reloads the list, it sometimes getting crashed the hole bot, but also sometimes only the Pokemon List crashed.

I am running the latest build (1.0.8.4) and only one bot per IP (have around 24 different IPs to my free use / no one is banned!).

![error1](https://cloud.githubusercontent.com/assets/20904908/17544856/13f68478-5eda-11e6-8d1e-bb9c30ddf307.png)

![error2](https://cloud.githubusercontent.com/assets/20904908/17544860/18ab0656-5eda-11e6-9db4-8c22a27f93ba.png)

![error3](https://cloud.githubusercontent.com/assets/20904908/17544862/1e9d5e74-5eda-11e6-9388-252833e572d7.png)

![error4](https://cloud.githubusercontent.com/assets/20904908/17544870/26bad3ac-5eda-11e6-81b1-49a0d68cd47e.png)

**Comment by pilota56** [comment]
I think the Servers are down, laggy

**Comment by gummyruler** [comment]
Try lowering your speed? They added a new feature for game to make sure no one is driving while playing the game.

**Comment by cyb0rg01** [comment]
I was used to get it running with 100 km/h, then I lowered it down to 50 km/h and since the last update I am used to let it run with 20 km/h.

**Comment by gummyruler** [comment]
I tried 70 no bans like these. It could be different then. best of luck

**Comment by cyb0rg01** [comment]
It doesn't look like a ban, because it is just for some seconds and is going to work again.

**Comment by Logxn** [comment]
Thanks.
Finally someone who is able to post complete screens :)

"EncounterClosed" is this new fancy niantic error message I believe.
I will take a look at it

**Comment by johnykkk** [comment]
its OK NOW! WORK

**Comment by cyb0rg01** [comment]
@Logxn I am working in the IT industry for ages now. So, I know how to handle with error messages and providing screenshots to others. :-D But thanks for that. :-)
