### ISSUE TITLE
Pokemon Transfer

### ISSUE THREAD

**Issue by seebyy0102** [Ar1i/PokemonGo-Bot#2469]
Hi Everybody! Someone can help me why the bot says that the pokemon was transfered, but nothing happened, so it can't transfer the pokemons?

**Comment by Logxn** [comment]
it transfers fine for me

**Comment by seebyy0102** [comment]
for me it just says that transfered, but in the pokebag is still in :/

**Comment by pokerave** [comment]
are you looking at the GUI? press reload or check the box(reload every XXs)

**Comment by seebyy0102** [comment]
i think i know what was the problem :) i checked the keep evolveable pokemons :) thats why it didnt transfer them :D i hope that i cant help for anyone with this post :D
