### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by nidico100** [Ar1i/PokemonGo-Bot#2470]
On Telegram when using the /information (topic) command 
only the topics: "all-enable" , "all-disable"  and "Pokestop"  are working, any other just enable/disable the pokestop information, but not the information it should change

**Comment by CruSherFL** [comment]
Better written than I did :)
#1964

**Comment by CruSherFL** [comment]
Something to add: Level up also don't work when /information all-enable is active.

**Comment by CruSherFL** [comment]
Another thing to add: when I request /top I'll get a lot of decimal places.
![image](https://cloud.githubusercontent.com/assets/12624399/17556434/ab94916a-5f13-11e6-8cbc-3116a5c44f3c.png)
