### ISSUE TITLE
Can't find any pokestops

### ISSUE THREAD

**Issue by gottahub** [Ar1i/PokemonGo-Bot#2471]
what happen?
![can t](https://cloud.githubusercontent.com/assets/20944255/17546560/0088e4f2-5f0d-11e6-9ebf-35a96e5e3d5b.JPG)

**Comment by gummyruler** [comment]
Check server status, and stop using so many bots.

**Comment by chickeflonoah** [comment]
I have the same problem. Server arent down. I think Niantic is the problem

**Comment by Farox1988** [comment]
I think, Niantic has a update for the API =(

**Comment by adriendillens** [comment]
Guys, There is a pokemonGo update (apk) needed to play and maybe another server-side... I think it's the problem ?

**Comment by gummyruler** [comment]
Bot is working for me without any hiccups.

**Comment by Yummster** [comment]
I think the problem is Niantic changed their method of tracking players and now track ip address, so running two bots on the same ip will make it look like youre teleporting all over the place and get you a soft ban.

**Comment by chickeflonoah** [comment]
And how can I unban me?

**Comment by tommyjai** [comment]
How many bot are u using ? Try to use one only

**Comment by chickeflonoah** [comment]
At the moment 1, but its not working. I will change my ip and try it again. But u are right because I let the bot do the work with 2 account while i was sleeping.

**Comment by tweetthehens** [comment]
seems ok now

**Comment by DLe111** [comment]
The reason why its not working because your IP got banned.

**Comment by gottahub** [comment]
Thank you,...is done and working. case closed

**Comment by Gin520** [comment]
It happened to me yesterday, and it's happening again today. 
But today is different, I'm using my office computer, and first time open bot today and can't search any pokestops already. waited over 20 minutes, open bot again and still can't find any.

only had 1 bot running.

**Comment by Logxn** [comment]
False information(s)
