### ISSUE TITLE
Pkmn go apk Update... maybe server-side too...

### ISSUE THREAD

**Issue by adriendillens** [Ar1i/PokemonGo-Bot#2472]
Hi everyone,
Bot doesn't work for me since apk update. I think there was a server-side update too.
Can anyone confirm ?

Thanks.

**Comment by seebyy0102** [comment]
did you download the latest version of the bot?

**Comment by adriendillens** [comment]
Yeah. 1.0.8.4 version !

**Comment by chickeflonoah** [comment]
Doesnt work for me too

**Comment by sunit1998** [comment]
bot has started to work fine for me extract latest build and use that with speed below 50 i had the same problem but now its fine

**Comment by chickeflonoah** [comment]
No thats not the reason. @adriendillens did u use 2 bots at the same time?

**Comment by adriendillens** [comment]
@chickeflonoah i use 1 bot pokemonGo-Bot and another one PokeBuddy ^^.
But now, i only have one, pokemonGo-Bot running with another IP, it works

**Comment by Logxn** [comment]
Its not Serversided

**Comment by adriendillens** [comment]
Very fast softban now. Bot only works 3 min and softban happens
