### ISSUE TITLE
My solution to the BOT-Problem

### ISSUE THREAD

**Issue by Guiseppe3** [Ar1i/PokemonGo-Bot#2474]
Listen. Had 2 bots running, both got banned. 
Reason : IP BAN
Solution : incase you have a dynamic IP address, just restart your router (you can just plug out and in).
Result : Works again, tho I was hoping to get a ban and stop checking the bot constantly :(

**Comment by Logxn** [comment]
uhm no.
I have 2 bots running - no ip ban.
False information

**Comment by FGonzalezBon** [comment]
Check using TunnelBear VPN for change your IP.

**Comment by joker041913** [comment]
had 2 bot running and started not seeing pokestop also log in to check if its just the bot but its also when i login with my phone no pokestop then i tried to connect to different internet my phone internet and its working just fine can some1 take a look at that i think its ip ban.

**Comment by Guiseppe3** [comment]
thats what im tellyou Joker.
Your IP got a ban. While I had this issue I turned of the wifi on my phone and Pokemon GO started to work without issues. Dunno why Logxn ist starting to b**ch around :D

**Comment by explore01** [comment]
yup, i agreed with guiseppe3 and joker041913
i didn't believe it either at first, so i try to give it a go, run a bot... wait for some time, work just fine..
open another bot... both works just fine... so i tought, nah, false alarm...
but after running like 10 minutes, i check it back, found detected soft banned! and any effort make (1337) didn't solve it.... so i closed both, open another bot, different id, and found no pokestop...
so i suspect IP banned as well...
please re-check.. thanks for the great work!

**Comment by explore01** [comment]
a lot has suspecting this issue, please re-open this.. @Logxn thanks

**Comment by explore01** [comment]
can found pokestop again after an hour.....
i haven't successful using VPN to check wether this is really ip bann or just server being overload?
