### ISSUE TITLE
Ban Wave 

### ISSUE THREAD

**Issue by McLovin1337** [Ar1i/PokemonGo-Bot#2476]
So i got banned couple minutes ago and thats why the bot didn't worked for me.
Just reset ur router so gettin' a new IP. ( **Works only for dynamic IP** )

**Comment by phodem** [comment]
1 ip 1 account i think

**Comment by Logxn** [comment]
Thats not a ban wave.

1 Bot per IP

**Comment by McLovin1337** [comment]
@Logxn I only used 1 bot , and still got banned.

**Comment by FilyaGG** [comment]
I go there says pocket stops all have such a problem?

**Comment by elenex23** [comment]
I cannot find pokestops for over 1 hours now. I can only run 1 bot at a time but even that got softbanned and Im having trouble since. ps i love logxn

**Comment by Logxn** [comment]
If you run a bot make sure that none of the pokeballs are set to 0
Also take a lower speed like 1-70km/h

P.S. I hope your a girl, otherwise I'm going homo xD

**Comment by elenex23** [comment]
I logged into the real game and I cant see anything. No pokemon stops gyms. Is this a new ban possibly?

**Comment by Logxn** [comment]
Most likely a server error

**Comment by McLovin1337** [comment]
@Logxn Why u closing that theard? Seems like more ppl having these issues O_o

**Comment by Logxn** [comment]
cuz its simply not a banwave

**Comment by elenex23** [comment]
If its a server issue why are some people good and others are not? Because where I'm located or perhaps where I'm try to farm?
