### ISSUE TITLE
pocket stops

### ISSUE THREAD

**Issue by FilyaGG** [Ar1i/PokemonGo-Bot#2477]
I go there says pocket stops all have such a problem?

**Comment by pokerave** [comment]
ummm what?

**Comment by jeremie152** [comment]
http://cmmcd.com/PokemonGo/
learn this site when have 0 pokestop its server unstable stop ask all time

**Comment by xJustx** [comment]
@FilyaGG Can you give me a precise description? Like the log-file?

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
