### ISSUE TITLE
no pokestop found

### ISSUE THREAD

**Issue by joker041913** [Ar1i/PokemonGo-Bot#2478]
just did something to check if its ip ban or not.
was connected to home internet and its not finding any pokestop also when i check to see if its only bot i tried to check to login with my phone but still no pokestop.
then i tried to connect to different internet and i just used my phone 4g and its working just fine i see pokestop and i try using bot started getting pokestop.
can any1 confirm for me if there is an ip ban coz my home internet is not seeing any pokestop but my phone 4g is seeing pokestop.

**Comment by chickeflonoah** [comment]
Yeah thats correct. I use a vpn and its working for me but thats shit. How can I just change my home ip?

**Comment by Gin520** [comment]
oh, i assume that's what's happening to me at office, IP ban then.
because i tried using the bot and on phone through the office network, found nothing.
When I use my own phone data, it's working fine.

**Comment by Tracynew** [comment]
i dont know about this, i think 1 ip for 1 account if you used 3 account you must change your ip...

**Comment by elenex23** [comment]
I am having the exact same problem. I did ipconfig /release and then ipconfig/renew in my cmd to no avail.

**Comment by chickeflonoah** [comment]
@Tracynew and hoe can i do that?

**Comment by chickeflonoah** [comment]
@elenex23 did u fix the problem through that?

**Comment by elenex23** [comment]
@chickeflonoah No. Normally it works but this time it is not helping. I was only running one bot at the time i got the softban message.

**Comment by joe112** [comment]
[15:55:30] We can't find any PokeStops in a range of 10000m!
[15:55:30] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..
always like this :(

**Comment by pokerave** [comment]
change to another state for a few hours. get unban(force unban) there

**Comment by elenex23** [comment]
I just downloaded Betternet Free VPN for google chrome. Activated it, and open bot. It is working now.

**Comment by joker041913** [comment]
just connected to my home net now its working i think what u need to do is w8 for it to get unban so there is an ip ban if you use more then 1 or 2 bot i think for 1 ip address some1 pls confirm coz i don't want to give wrong info.

**Comment by b3shoy** [comment]
close plz//
