### ISSUE TITLE
multiple instances(clients)

### ISSUE THREAD

**Issue by Melancolie** [Ar1i/PokemonGo-Bot#2479]
Does someone know a clear answer as to how many clients can we use at once?
In the client it says 3 is max, I get softbanned using 3, and I can no longer see pokestops after using 2. Is it really down to 1?

**Comment by untesty** [comment]
It depends so there's not really a clear answar to that. I for example can run 4 bots with no problem, but other people can only run 1 at a time so idk.

**Comment by andyfeb** [comment]
if you experience no longer see the pokestops, then it's server problem.
if you ask about limit of instances, I agree with @untesty , I can run multiple instances well until recently. I still can't answer whether I got soft banned because of server issue or multiple instances

**Comment by pokerave** [comment]
im using 3 clients 1PC for 24hrs and its fine.

**Comment by ineedtostudy** [comment]
@pokerave r u using any vpn's?

**Comment by pokerave** [comment]
@ineedtostudy  Yes.

**Comment by xJustx** [comment]
^
