### ISSUE TITLE
Force unban

### ISSUE THREAD

**Issue by Kaeryth** [Ar1i/PokemonGo-Bot#2481]
Where is the force unban button? i cant find it...

Thanks!

**Comment by ripharambe** [comment]
in the pokemon list in new versions ;)

**Comment by Kaeryth** [comment]
And where is that list? 

Sorry, im blind :p

**Comment by phodem** [comment]
Turn on Pokemon hub, in the pokemon list

**Comment by Kaeryth** [comment]
Ok ok, thanks!
