### ISSUE TITLE
I keep getting Ip banned with only 2 bots

### ISSUE THREAD

**Issue by dragobite** [Ar1i/PokemonGo-Bot#2483]
I don`t know what I`m doing wrong but I`m getting IP banned even tho I`m using just 2 bots and I`m sure that it`s just 2.

**Comment by phodem** [comment]
Down to 1 now

**Comment by james741** [comment]
so now i only can on 1? wtf... i was helping my sister to bot....

**Comment by QustomiZed** [comment]
i have the same problem how can i fix  1?

**Comment by DLe111** [comment]
Reset your router

**Comment by Jinnocid** [comment]
after reset same thing happens

**Comment by gitovahere** [comment]
TWO things: IP banned and you can only run ONE bot per IP address. As soon as you load up a 2nd bot, the first one will no long see/encounter pokemons but could farm pokestop. Now the 2nd bot could catch pokemons. After that both bots can't farm from pokestops nor see pokemons. Generate a new IP address and run one bot, works after that.

**Comment by james741** [comment]
reset? now i cant even find anything .....
we cant find any poke stops babababa~

**Comment by TrainerNr1** [comment]
Same here, only one bot works.

**Comment by pokerave** [comment]
I have 3 running bots everyday. for almost 20-23 Hrs a day. RUNS FINE.

**Comment by wrobe06117** [comment]
it would be nice if @Ar1i  can add a ip change for ea client so we can run multiple clients

**Comment by marcop888** [comment]
yeah me too

**Comment by gitovahere** [comment]
@wrobe06117 that's impossible, even your internet provider can't give you more than one IP addresses with a single modem connection.

**Comment by QustomiZed** [comment]
i cant even run a single bot

**Comment by joker041913** [comment]
so WARNING to all that's getting no pokestop its probably ip ban if your using more then 1 bot.

**Comment by Buddhasama** [comment]
And ip bans started to last longer now .

**Comment by james741** [comment]
cant even run a single bot now... 
i only on 1 
@joker041913

**Comment by QustomiZed** [comment]
i see no pokestops and pokemons when i logged in on my ipad

**Comment by sunsiskos** [comment]
I couldnt find any pokestops, lowered to 1 bot and its working fine

**Comment by joker041913** [comment]
when did it happen coz i had to w8 like 30m-1h b4 i was able to make it work again.

**Comment by elenex23** [comment]
If you cannot even get 1 bot to work, and reseting your ip is not working, I started using vpn and am working fine now, with 1 bot.

**Comment by james741** [comment]
omggggggggggggggggggggggggggggggggggggggg

**Comment by joker041913** [comment]
try connecting to dif internet and it should work fine think u got ip ban get back on me if it works with different net connection.
@sunsiskos

**Comment by QustomiZed** [comment]
free vpn?

**Comment by joker041913** [comment]
my bad @sunsisko  was talking to QustomiZed.

**Comment by james741** [comment]
@joker041913 
not even 1 bot is working, so i just try to reset my modem??

**Comment by pokerave** [comment]
Like I said.. No ones reading.. Im Running 3 BOT 1 PC(24hrs like 20-23hrs a day). ITS FINE with me.

**Comment by urangotango** [comment]
@pokerave do you use any kinda of hotspot shield ? or do you have more lan cards on your PC ? becouse as you say you are the only 1 with 3 working bots....

**Comment by gitovahere** [comment]
@pokerave we're reading you but we can't do more than 1. haha. What version of bot are you using?

**Comment by joker041913** [comment]
@james741 
i tried that and it didn't work for me u can try and see but i just had to w8 for ip to get unban.

**Comment by joker041913** [comment]
@pokerave 
well its not all the same with other people some are getting ip ban and a lot of people confirm that it has ip ban and I'm 1 of them LOL.

**Comment by pokerave** [comment]
@gitovahere lates1.0.8.4..... USE VPN if you get ban.

**Comment by ber84130** [comment]
hi anyone know a good vpn free ?

**Comment by urangotango** [comment]
@joker041913 do you have an internet provider with fixed ip maybee ? if y you have to use an VPN to change your ip

**Comment by gitovahere** [comment]
@joker041913 who is your internet provider? If they offer static IP then you'll have to change the MAC address.

**Comment by JeCelle** [comment]
VPN Gate has lots of servers to choose from and it's free.

**Comment by james741** [comment]
@pokerave what vpn and can u share the link pls :dancers:

**Comment by joker041913** [comment]
i didn't do anything just had 2 w8 for it was connected to my phone internet for while then i tried it on my home net after like 1h then started fine...

**Comment by keustii** [comment]
PokeSrv are.laggy

**Comment by marcop888** [comment]
restart your router may works...

**Comment by urangotango** [comment]
guys seems that @ar1i did release an proxy fix just 7 minutes ago!! check it out

**Comment by adriendillens** [comment]
it seems the incubator crash the bot ! now i disable it, it works fine !

**Comment by marcop888** [comment]
yeah its work but only 5 minutes.. then getting softban

**Comment by james741** [comment]
@urangotango 
do i have to redownload the new Builds Only?

**Comment by jeremie152** [comment]
now one instance limite botting suck now

**Comment by urangotango** [comment]
@james741  y you have to download the new build 
@jeremie152 try the new buld with proxy fix released like 20 mins ago.

**Comment by jeremie152** [comment]
proxy fix how i got this?

**Comment by jeremie152** [comment]
and i have the new build since yesterday

**Comment by jeremie152** [comment]
im trying to redownload hotspotshield something wrong^^

**Comment by urangotango** [comment]
@jeremie152 do you read my answere to james741 ?
there did come a # new one 20 mins ago + - check the builds and the Ar1i comits omg

**Comment by jeremie152** [comment]
ah ok thanks man i see update a day ago maybe laggy^^

**Comment by jeremie152** [comment]
urangotango last ask how i fix proxy?

**Comment by chusski** [comment]
How update my bot if , dont update the Builds Only ? plz

**Comment by jeremie152** [comment]
https://github.com/Ar1i/PokemonGo-Bot

**Comment by jeremie152** [comment]
look this link is not ar1i its logxn he say proxy working now

**Comment by james741** [comment]
@urangotango how i use proxy fix?

**Comment by jeremie152** [comment]
but next you come back on the last build i think just he have to fix some setting but not update the version

**Comment by xJustx** [comment]
If you get a ban with 2 bots, then run only 1 at the same time.
