### ISSUE TITLE
bot wont work

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#2485]
Normally I run3 bots for each familymember and it always worked.
Now I only use 1 botas somone sayed in a different thread.
I aso changed ipand location and it still wont run

**Comment by gitovahere** [comment]
Here: https://github.com/Ar1i/PokemonGo-Bot/issues/2483
Please close your thread.

**Comment by xxhamsterxx** [comment]
@gitvahere Read my Message again.
I already use a VPN and Even one bot is to much

**Comment by keustii** [comment]
poke srv look like laggy

**Comment by keustii** [comment]
http://downdetector.com/status/pokemon-go

**Comment by xJustx** [comment]
^
