### ISSUE TITLE
Ip banner

### ISSUE THREAD

**Issue by sergrusur** [Ar1i/PokemonGo-Bot#2488]
Does anyone know how long this ban?

**Comment by pokerave** [comment]
some say 30 mins, some say 3hrs, some say 6hrs.

**Comment by james741** [comment]
some say forever

**Comment by sergrusur** [comment]
Hope it last the least ;-)

**Comment by joker041913** [comment]
last for 1h for me.

**Comment by multik3d** [comment]
I usually just run my first bot for 10-20 mins then run my second right after.

**Comment by chavall** [comment]
Eat, Sleep, Bot Pokemon, Repeat :v:

**Comment by james741** [comment]
@chavall shhh u not helping..

**Comment by TrainerNr1** [comment]
The ban ends if the bot is running??? or should I close the bot an hour??? thx

**Comment by b3shoy** [comment]
this is not an issue, please close//

**Comment by james741** [comment]
@b3shoy what u mean this not a issue? we getting ban left and right here

**Comment by b3shoy** [comment]
because you are using more than the bot instances limit.

**Comment by maku001** [comment]
Well force unban does not work all the time, you have to change your ip, but what's the best way? Plug in modem etc doesn't work.

**Comment by kikado** [comment]
Cable modems usually have an static IP. Your mobile phone does not. Your phone's IP address changes everytime you connect to the Internet. So I suggest you create an WiFi hotspot with your phone untill your Cable modem's IP is unbanned.

Or use an VPN.

**Comment by b3shoy** [comment]
Ok guys, I'm sorry... It seems it was an issue, and @Logxn just fixed it.
You can try now I think.

**Comment by gottahub** [comment]
try
    Click Start->Run, type cmd and press Enter.
    Type ipconfig /release at the prompt window, press Enter, it will release the current IP configuration.
    Type ipconfig /renew at the prompt window, press Enter, wait for a while, the DHCP server will assign a new IP address for your computer.

**Comment by sergrusur** [comment]
30 min it last. I close the issue, thanks everybody

**Comment by Damantium** [comment]
@gottahub that hasn't worked
