### ISSUE TITLE
No pokestops??

### ISSUE THREAD

**Issue by multik3d** [Ar1i/PokemonGo-Bot#2493]
Error occured again?? Servers are unstable should I wait to bot later?

**Comment by MrNobodyj** [comment]
same for me

**Comment by MrNobodyj** [comment]
when i open the nox didnt see pokestops or pokemons  
prob. server is down

**Comment by xChakululu** [comment]
i have the same problem

**Comment by urangotango** [comment]
@multik3d seems pokemon server sided error pls close the issue. THX

**Comment by james741** [comment]
@urangotango r u sure is pokemon server? not bot problem?
