### ISSUE TITLE
Force ban issue

### ISSUE THREAD

**Issue by maku001** [Ar1i/PokemonGo-Bot#2494]
Well force unban does not work all the time, you have to change your ip, but what's the best way? Plug out an plug in cables in modem etc doesn't work.

**Comment by cyberwolf888** [comment]
#2495

**Comment by Poupoul80** [comment]
when you open Pokemon Go on your smartphone you cant see any pokestop or pokemon Map is empty.
Hope its not a definitive ban... :/

**Comment by urangotango** [comment]
@maku001 did you download the last build with proxy fix? 
pokemon go last fix = 1 account for each IP 
@poupoul80 i dont think so try again seems some pokemon server errors my bots startet to work again farming pokestops

**Comment by james741** [comment]
hey @urangotango what u do mean proxy is working now. All this time i using Builds Only 
tell me am new here

**Comment by maku001** [comment]
@urangotango yeah i did, but i dunno what to 'put in proxies. If you could be so nice and tell me what to put there I would appreciate it.  I play with my brother so we got same ip that may be  an issue as well for us.

**Comment by maku001** [comment]
ok i fit it.
