### ISSUE TITLE
change location error?

### ISSUE THREAD

**Issue by lumamamtuh** [Ar1i/PokemonGo-Bot#2496]
why if i set location the cordinate of "altitude" always 0 or it don't change? i cant find pokestop because of that..
anyone can help me with this problem?
i already download and use the latest build btw...

**Comment by xChakululu** [comment]
its not because of your location everyone has this problem
(cant find pokestops)

**Comment by james741** [comment]
@xChakululu so u saying no one is botting right now?

**Comment by cyberwolf888** [comment]
#2495

**Comment by xChakululu** [comment]
I think so cause the pokemon servers are ok

**Comment by gottahub** [comment]
try

    Click Start->Run, type cmd and press Enter.
    Type ipconfig /release at the prompt window, press Enter, it will release the current IP configuration.
    Type ipconfig /renew at the prompt window, press Enter, wait for a while, the DHCP server will assign a new IP address for your computer.

**Comment by lumamamtuh** [comment]
@xChakululu @gottahub thanks broo.. my bot is already working again!
you are awesome.. :D

**Comment by rvonz** [comment]
mine can't find pokestop, if there is the same as me?
