### ISSUE TITLE
Incubation

### ISSUE THREAD

**Issue by robertrapt** [Ar1i/PokemonGo-Bot#2497]
Thank you for your work.
I use the bot "Builds only", but it does not work incubating eggs.
That I have to do?
Thanks

**Comment by emilie253** [comment]
he dont works but i dont understand why.
they can fix proxy , crack pokemon go etc.... but no up auto incub in 5 min? ^^
(while others bot do it )

**Comment by OwKuuT** [comment]
tp on ur home, force unban, connect on ur phone > incubate your egg and continue !

**Comment by Ar1i** [comment]
@emilie253 if you can, then make a pull request before writing bullshit :) but fixing that atm so calm down

**Comment by urangotango** [comment]
@Ar1i @Logxn. guys they working atm hard to keep up the bot against ip blocks and other hard shits... if they have time im pretty sure they will wix this minor issue to

**Comment by emilie253** [comment]
Ar1i : I have great respect for you and for you work, but I was wondering just why it take time to fix it when i see your work on others things.

**Comment by Ar1i** [comment]
Cause proxy got a higher property atm now egg

**Comment by xRealMaks** [comment]
#2360 #2354 #2352 #2011 #1551 #2290 #2281 #2383
Will be added in the next few days (hopefully :smile: )

**Comment by OhhPian** [comment]
@emilie253 Why dont u create your own bot then ? its easy right ? 5min ?
