### ISSUE TITLE
Google login problems?

### ISSUE THREAD

**Issue by Spensky** [Ar1i/PokemonGo-Bot#2498]
I can not login whit google account , no permisison or something ? But i can whit PTC !
Can someone tell me how to give google permission or sth , please ?

**Comment by Ar1i** [comment]
Error message? More informations please.

**Comment by Spensky** [comment]
@Ar1i  Look ==  [url=https://postimg.org/image/ab6qjkn79/][img]https://s10.postimg.org/ab6qjkn79/SAE.png[/img][/url]
