### ISSUE TITLE
Which Proxy do i have to use=?

### ISSUE THREAD

**Issue by Tonyjaain** [Ar1i/PokemonGo-Bot#2499]

**Comment by chusski** [comment]
how to proxy work s?

**Comment by Tonyjaain** [comment]
Yeah how does it work?

**Comment by akangnduz** [comment]
same problem

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
