### ISSUE TITLE
Proxy Help

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#2501]
What do i have to enter in the proxy secrion ?

**Comment by MythosOfGaming** [comment]
![2016-08-10 12_13_06-greenshot](https://cloud.githubusercontent.com/assets/20840606/17550164/eb7ebcb2-5ef3-11e6-9dd5-390e55c25ded.png)

**Comment by MythosOfGaming** [comment]
is this right ?

**Comment by iwangrp** [comment]
@MythosOfGaming i dont know, please help to using this config proxy

**Comment by kikado** [comment]
https://twitter.com/loganpunkt/status/763316897513345024

**Comment by xRealMaks** [comment]
1. Go to http://proxylist.hidemyass.com 
2. Copy IP & Port
3. Enter it in the bot, press save and start the bot

BTW: This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by banceto** [comment]
i got new ip from here https://www.sslproxies.org/ and it works.

**Comment by aquilinachu** [comment]
Only HTTPS proxies work. And please open a question tab here because no one is going to bother with registering to a forum and wait for a reply there. This site is much faster and community helps each other.

**Comment by emilie253** [comment]
and when you change country, i get ban IP ... :( need reboot box after change ?

**Comment by Captnred** [comment]
I understand you don't know how things work, but this isn't a issue. He posted directions on how to use the proxys.

If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.
