### ISSUE TITLE
3 client, 3 proxy, don't work

### ISSUE THREAD

**Issue by Mancuz** [Ar1i/PokemonGo-Bot#2504]
i use 3 client with 3 different proxy , but neither of these works, all says: we can't find any pokemons in a range of xxxx.

why? :/

**Comment by Ar1i** [comment]
use https proxy

**Comment by MythosOfGaming** [comment]
Ar1 can you looak at my issue ? #2501

**Comment by Mancuz** [comment]
yeah I'm using those https

**Comment by multik3d** [comment]
could be server issue

**Comment by QustomiZed** [comment]
i used a proxy server did it for 10 min after that i changed back to my own ip and it works again

**Comment by Tonyjaain** [comment]
@QustomiZed  how do you use a progy? what did you wrote in the proxer field?

**Comment by Mancuz** [comment]
1 of the client not using proxy, but my ip, but even that works

**Comment by QustomiZed** [comment]
@tonyjaain i use a program for it

**Comment by Yummster** [comment]
I'd had one bot running without problems for two hours, tried the proxy bot on two bots and both soft banned after 2 minutes.

**Comment by QustomiZed** [comment]
Yh me 2 all the time im done with it i keep 1

**Comment by SkillsPayBills** [comment]
@Ar1i Does the bot catch pokemon from pokestops with lures?

**Comment by Ar1i** [comment]
fixed
