### ISSUE TITLE
How do I change my IP?

### ISSUE THREAD

**Issue by NikiMon** [Ar1i/PokemonGo-Bot#2506]
I am Ip Banned because of 2 Bots running at the same time.

ppl told me to change my IP but idk how.

Thx :)

**Comment by martinjamesl** [comment]
same here

**Comment by Logxn** [comment]
How to set up the proxy:

1. Go to http://proxylist.hidemyass.com 
2. Copy IP & Port
3. Enter it in the bot, press save and start the bot

**Comment by NikiMon** [comment]
@Logxn 
Enter it where in the bot?

**Comment by jotayc** [comment]
I do that and It doesn't work

**Comment by NikiMon** [comment]
Worked, thx
