### ISSUE TITLE
Proxies and Aunthentication

### ISSUE THREAD

**Issue by ankhmok** [Ar1i/PokemonGo-Bot#2507]
Any explanation or any link which is talking about the new features Proxies and Aunthentication

i have no idea what they are and how i work and the setting

**Comment by aquilinachu** [comment]
http://proxylist.hidemyass.com/ 

Find a fast HTTPS proxy.
Enter IP on top, port on bottom (IP is the long one and port is usually 80 or 8080 etc)
Click save and start

**Comment by 0ny** [comment]
Any Free ? 
This cost money lol

**Comment by ankhmok** [comment]
sorry guys im so silly on it, what if i dont set any Proxies and Aunthentication the Bot will still work?

**Comment by 0ny** [comment]
Yes but only 1 / IP

**Comment by Captnred** [comment]
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Comment by xJustx** [comment]
^
Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
