### ISSUE TITLE
Proxy Help

### ISSUE THREAD

**Issue by xXNagatoXx** [Ar1i/PokemonGo-Bot#2509]
Kann mir bitte iergendwer sagen wo ich was genau eintragen muss bitte weil der bot bei mir garnicht mehr funktioniert.
English : Can anyone please tell me where I need to what exactly please insert because the offered me no longer at work.

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by xXNagatoXx** [comment]
Was soll der kak ? da antwort mir auch keiner

**Comment by xRealMaks** [comment]
Ist es denn ein Issue? Nein. Also poste kein Issue. Wir haben genug richtige Issues die wir bearbeiten müssen, da brauchen wir keine Fragen.

Geh auf https://www.sslproxies.org/
Such dir ein proxy aus.
Trage die IP in die textbox links oben ein
Trage den Port in die Textbox links unten ein
Drück save proxy
starte den bot
