### ISSUE TITLE
Breeding Eggs

### ISSUE THREAD

**Issue by AlpaEZPZ** [Ar1i/PokemonGo-Bot#2512]
Hello,
am i able to breed eggs with the current version of the bot ?
Just asking caus i tried to use incubators but i doesnt work.

If its fine sorry for opening an issue.

greetings

**Comment by xRealMaks** [comment]
in the next few days.

**Comment by gummyruler** [comment]
It doesn't work people are more concerned of the current "can't bot 100x "problem" these days."
