### ISSUE TITLE
again the same

### ISSUE THREAD

**Issue by xChakululu** [Ar1i/PokemonGo-Bot#2513]
PokeBot says
[12:28:31] We can't find any PokeStops in a range of 5000m!
[12:28:31] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

dont know what to do

**Comment by multik3d** [comment]
Same issue for me :/

**Comment by bonisss** [comment]
yeah same with me :(

**Comment by shaor4n** [comment]
same here

**Comment by QustomiZed** [comment]
Open not more than 1 bot a the time

**Comment by LuckyBoy1101** [comment]
same

**Comment by xChakululu** [comment]
@QustomiZed i have only one bot

**Comment by bonisss** [comment]
i hav only 1 account and 1 bot sir 
![image](https://cloud.githubusercontent.com/assets/20930215/17550742/a32dc58e-5f20-11e6-9956-bd99596ec678.png)
but still like this 
i use proxy 
see that

**Comment by xChakululu** [comment]
me too only 1 acc and one bot with a proxy

**Comment by Thinkinge** [comment]
don't use proxy, I just consider that if somebody use the same proxy with me, both of us will be banned? so I think that if u use the proxy, and others use the same IP address with u. it could mean that one IP runs two acc, is that right? I just guess ;)

**Comment by shaor4n** [comment]
now it's working again.
