### ISSUE TITLE
error proxy

### ISSUE THREAD

**Issue by emilie253** [Ar1i/PokemonGo-Bot#2516]
Hello, i have a error when i use proxy (and when it's good, no found pokeshop)

![bug bot](https://cloud.githubusercontent.com/assets/20780055/17550656/52b1682e-5ef6-11e6-868b-80384e8b18bd.png)

thank you for your help

**Comment by Teamozuka** [comment]
somehow pct and proxy do this but goole login does fine

**Comment by gummyruler** [comment]
Google does the same.

**Comment by Lukyczk** [comment]
I have the same error with PTC

**Comment by untesty** [comment]
same here

**Comment by Spensky** [comment]
same

**Comment by Mancuz** [comment]
i have that error when i use http proxy, try to use https

**Comment by emilie253** [comment]
same with https :s

**Comment by Dliang2k** [comment]
i get this error and use a socks5 proxy. (Dante-Server unter Ubuntu)
with Proxifier and dante proxy work fine
