### ISSUE TITLE
[ISSUE] Tranfer IV first

### ISSUE THREAD

**Issue by chusski** [Ar1i/PokemonGo-Bot#2517]
At the moment.
If got 2 on Max duplicate.  and got 90 on Max IV to transfer. Do bot this:
Abra 100 89% tranfered
Abra 300 15% saved
Abra 120 33% saved
Abra 333 90% saved
Abra 444 91% saved

If active this new fuction transfer alot of pokemons because get reference to the pokemons are you  get saved from Max. IV to transfer: (90 in my case ) %. 
Abra 100 89% transfered
Abra 300 15% transfered
Abra 120 33% transfered
Abra 333 90% saved
Abra 444 91% saved

I think the best are bot dont compare with this other pokemons saved from  Max. IV to transfer: (90 in my case ) %.
Abra 100 89% saved
Abra 300 15% transfered
Abra 120 33% saved
Abra 333 90% saved
Abra 444 91% saved

Sorry for my poor english. 
And Thx for your time^^

**Comment by cyl2usdragoon** [comment]
How do you set

**Comment by xRealMaks** [comment]
#2412 
The bot transfers the lowest CP
We know that it would be better like that

**Comment by chusski** [comment]
xRealMaks i think i explain bad or you dont understand my :(

**Comment by xRealMaks** [comment]
Your "Issue" is that it would be better if the bot transfers the lowest IV and not the lowest CP one, right?

**Comment by chusski** [comment]
Yes are great new option, but problem are the bot compare the saved pokemons from Max. IV to transfer, and dont need to do that because all pokemons be transfered if you got one 90 .
The problem with what pokemons saved compare.
