### ISSUE TITLE
[Request] Only hold on to what you can evolve

### ISSUE THREAD

**Issue by UserWest** [Ar1i/PokemonGo-Bot#252]
I'm requesting a system that will observe the number of a specific candy you have and only maintain the number of that pokemon that you could evolve. (Example: you have 24 pidgey candies, so the bot automatically transfers all but 2 pidgeys until you have 36 where it holds on to 3, etc) I like to save my lucky eggs for when i have a lot of pokemon saved up to evolve and this would save me a LOT of manual transfering and math. Great job on the bot so far by the way.

**Comment by FrancYescO** [comment]
+1
