### ISSUE TITLE
 can't find any PokeStops

### ISSUE THREAD

**Issue by Can7** [Ar1i/PokemonGo-Bot#2520]
[13:48:12] We can't find any PokeStops in a range of 5000m!
[13:48:13] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..

How can i fix this?

**Comment by PokeMungo** [comment]
soft ban.

**Comment by PokePro21** [comment]
using more than 2 bots ?

**Comment by dadaxd** [comment]
i use only 1 bot...same problem whit the new update....

**Comment by xChakululu** [comment]
i used one bot and my brother too now he closed his bot
and i got the message no pokestops found

**Comment by Lukyczk** [comment]
Im getting the message too right now

**Comment by dadaxd** [comment]
all have the same problem....nice =D

**Comment by xChakululu** [comment]
#2513 same issue

**Comment by Lukyczk** [comment]
I think the servers are down

**Comment by Can7** [comment]
When i login with Nox, i cant see any pokestop or pokemon. But the account opens. Is it can be ip ban?

**Comment by Lukyczk** [comment]
How long does an IP Ban stay ?

**Comment by xChakululu** [comment]
@Lukyczk no the servers are ok 
http://ispokemongodownornot.com/

**Comment by Lukyczk** [comment]
:-/

**Comment by Can7** [comment]
@Lukyczk Last 20min

**Comment by Lukyczk** [comment]
You know what worked to me to fix it ?

**Comment by Lukyczk** [comment]
I downloaded an app named Betternet

**Comment by Lukyczk** [comment]
And connected to their servers, then it worked

**Comment by Mancuz** [comment]
mee too : we can't find any pokestops in a range of xxxx [i run just 1 client]

**Comment by Lukyczk** [comment]
mhm

**Comment by Thinkinge** [comment]
is anybody used proxy?

**Comment by Thinkinge** [comment]
I just consider that if I and others use the proxy and same IP address, does it mean that one IP runs two acc?

**Comment by Lukyczk** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/2515

**Comment by ShaaiLo** [comment]
same issue !!

**Comment by PokeMungo** [comment]
do not use the proxy. i bot fine
![screenshot](https://cloud.githubusercontent.com/assets/20927654/17551685/38e46a6e-5f04-11e6-9a87-9e176c3b7336.jpg)

**Comment by multik3d** [comment]
If you can't find any pokestops you're probably soft-banned either change your ip or use proxy. From what I know Soft ban lasts 30mins-4hours.

**Comment by Kidnub** [comment]
get a new ip  XD

**Comment by PokeMungo** [comment]
no problem :)

**Comment by Can7** [comment]
Ib ban I am sure. Reset your modem if not use VPN ..

**Comment by Kidnub** [comment]
but watch it , you can easy get a softban on 2 bot i had now 2 softbans ;(

**Comment by sunsiskos** [comment]
Modem restart seems to work on me

**Comment by Spensky** [comment]
i have static ip... any solution  to get away whit softban ? And even if i got away to prevent it ...

**Comment by Captnred** [comment]
Please use the search feature, there are multiple threads with same issue. No need for  a new one. Please close this thread.

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
