### ISSUE TITLE
How do i set up a proxy

### ISSUE THREAD

**Issue by TNLzItalic** [Ar1i/PokemonGo-Bot#2521]
The two bars make me confused what do i put in each? Help??

**Comment by Raiderman1105** [comment]
i think in First input you have to put in IP adress and in second the Port but i dont know not tested

**Comment by TNLzItalic** [comment]
Thanks ill try it

**Comment by TNLzItalic** [comment]
If i have 1 bot running on my wifi no proxy and i go on the account on my phone at the same time does it ban me?

**Comment by Damantium** [comment]
Proxies don't seem to be working, everyone using the same free proxies and getting IP banned.

**Comment by Raiderman1105** [comment]
hm Damantium :/ you are right

**Comment by TNLzItalic** [comment]
ok, i dont want to run 2 bots i just want to know if i can go on my bot account on my phone while its in new york and not get banned

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by BangBhexe** [comment]
hi bro , i use 1 bot at 1 time and using the proxy setting , and it's work fine by now 
![2016-08-10 18_03_28-how do i set up a proxy issue 2521 ar1i_pokemongo-bot](https://cloud.githubusercontent.com/assets/20933955/17551571/284b8a9a-5f25-11e6-8fe9-7cc37ca92c45.png)

first open this site http://proxylist.hidemyass.com/search-1650249#listable
and look at this screenshoot i made 

![2016-08-10 18_01_28-free proxy list public proxy servers ip port hide my ass](https://cloud.githubusercontent.com/assets/20933955/17551613/5eddfde0-5f25-11e6-8c01-03f2ccf3083f.png)

and look at the point i check it then click update result , at the bellow it will be a list with ip and port

![2016-08-10 18_02_45-pokegobot gui edition _ gui by greengold _ edit by iceq1337 gatno _](https://cloud.githubusercontent.com/assets/20933955/17551641/85ad4818-5f25-11e6-87f3-ae3609ec1834.png)

then pick the ip and port and put it at the proxy setting then save proxy and start the bot

i hope it will help
