### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by DrFirex** [Ar1i/PokemonGo-Bot#2524]
So i was using the bot just fine when it suddenly stopped working so i got on the website and found the new update. However after installing it i encountered this probem. I have tried restarting the program but it didn't work. Please help thank you.
![image](https://cloud.githubusercontent.com/assets/20947154/17551411/17241a30-5f24-11e6-98e6-0ede5350eec0.png)

**Comment by xRealMaks** [comment]
Wait 15 minutes and try again

**Comment by PokeMungo** [comment]
delete your bot folder. extract again. then open bot again.

**Comment by DrFirex** [comment]
I opened it after an hour and it's working again now thanks guys.

**Comment by xRealMaks** [comment]
np
