### ISSUE TITLE
Autosoft ban after 18km/h

### ISSUE THREAD

**Issue by eowin** [Ar1i/PokemonGo-Bot#2526]
Hi,

I read on the last update, that an auto softban has been added for drivers, when you are more than 18km/h on the application a message appear to tell you if you're the driver or a passenger. 

Do you know if on the last update, an autocheck on "passenger" has been added ? 

Thx

**Comment by elenex23** [comment]
im going at 50km/h and having no problems.

**Comment by eowin** [comment]
I often see a message to tell me that i'm softban :/

**Comment by PokeMungo** [comment]
same here. 50 kmh and still no soft ban

**Comment by Ptitout** [comment]
I m going at 50 km/h and i often softban

**Comment by xRealMaks** [comment]
API does ignore that.
50kmh and no softban
