### ISSUE TITLE
After new Update/Nach neuem Update

### ISSUE THREAD

**Issue by dadaxd** [Ar1i/PokemonGo-Bot#2527]
![neu](https://cloud.githubusercontent.com/assets/20825003/17551661/b351baa8-5efb-11e6-87f5-d2fd1f611983.png)

 Nach dem Update findet er keine Pokestops mehr 

Habe einiges probiert, aber keine loesung...

**Comment by xRealMaks** [comment]
Mach den bot mal aus und warte mal 15 minuten.

**Comment by dadaxd** [comment]
ok ich probiere es mal. danke

**Comment by multik3d** [comment]
Soft-banned

**Comment by PokeMungo** [comment]
^ softban. restart router. change IP> then apply UNBAN button. always works for me. no 30minutes to hour waiting

**Comment by dadaxd** [comment]
i try it, thanks

**Comment by xRealMaks** [comment]
The bot got no pokestops, so the bot can unban him..

**Comment by Melancolie** [comment]
unban doesn't work @xRealMaks

**Comment by dadaxd** [comment]
it works, restart router ! thanks all
