### ISSUE TITLE
Keine Pokestops!

### ISSUE THREAD

**Issue by DiTechRacer** [Ar1i/PokemonGo-Bot#2528]
Gleiches Problem wie als sie die letzte API geschlossen haben..

**Comment by xRealMaks** [comment]
Mach den bot aus und warte 15 minuten.
Bei mir funktioniert der bot.

**Comment by PokeMungo** [comment]
^ softban. restart router. change IP> then apply UNBAN button. always works for me. no 30minutes to hour waiting

**Comment by xRealMaks** [comment]
The bot got no pokestops, so the bot cant unban him

**Comment by emilie253** [comment]
i can't find pokestop... even if i change my ip with proxy :(

**Comment by DiTechRacer** [comment]
Kanns daran liegen das 2 Bots über die selbe IP laufen? IP change ist nicht möglich^^ hab eine feste IP

**Comment by emilie253** [comment]
no, i use 1 bot :(

**Comment by xRealMaks** [comment]
@DiTechRacer Ja. die haben das wieder geändert. Mach 15 minuten den bot aus und starte dann nur ein bot.

**Comment by PokeMungo** [comment]
i use 2 bot with no problem.
![screenshot](https://cloud.githubusercontent.com/assets/20927654/17552209/27cc564e-5f07-11e6-9eb8-7c80a08b1874.jpg)

**Comment by Kidnub** [comment]
benutze einen bot nur , hole dir ne neue ip (router neustart ect ) dann unban einmal wenn der bot gestartet ist , und bitte nur ein bot pro ip ;) .. sont brauchste pro bot einen proxy ;)

**Comment by xRealMaks** [comment]
Er hat ne feste IP..

**Comment by Kidnub** [comment]
ja habe ich jetzt erst gesehen dann bleibt nur noch proxy ;(

**Comment by DiTechRacer** [comment]
Okay, die 15min sind gleich rum.. bin gespannt

**Comment by xRealMaks** [comment]
Sollte dann eigentlich wieder unbanned sein.

**Comment by DiTechRacer** [comment]
Hat nicht geklappt.. 20min. gewartet.. muss jetzt auch erst mal weiter arbeiten.. hoffe es geht heut abend wieder

**Comment by xRealMaks** [comment]
Sollte dann wieder klappen..

**Comment by DiTechRacer** [comment]
Danke vorerst für eure hilfe ;)

**Comment by xxhamsterxx** [comment]
bei mir geht es trotz vpn und nur ei em bot nicht

**Comment by xRealMaks** [comment]
Öffne ein neues Issue @xxhamsterxx

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
