### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by SkillsPayBills** [Ar1i/PokemonGo-Bot#2529]
![image](https://cloud.githubusercontent.com/assets/20889679/17551745/2f8f2a22-5f3f-11e6-987f-aa6172e5750c.png)
**Every now and then this happens, please fix.**

**Comment by PokeMungo** [comment]
restart bot

**Comment by SkillsPayBills** [comment]
I know but it happens often and I want it fixed

**Comment by PokeMungo** [comment]
so make your own bot.

**Comment by urangotango** [comment]
in germany was some nice words for ppl that want ;) 
Die kinder die was wollen kriegen was auf die bollen. 
in italian exist 
l`erba voglio e finita da un pezzo
XD
