### ISSUE TITLE
Deleting all my non-double pokemon

### ISSUE THREAD

**Issue by deezmasterballz** [Ar1i/PokemonGo-Bot#2530]
same configuration as all the last updates, but this most recent update just keeps wanting to transfer everything i have. double checked all config files and all is right. what is the new option transferfirstlowiv?

**Comment by xRealMaks** [comment]
Delete your config folder and try again

**Comment by PokeMungo** [comment]
put 2 or 3 in option to keep duplicate. you already have working GUI, why bother checking config?

**Comment by deezmasterballz** [comment]
what is the new option in gui in the pokemon tab "TransferFirstLowIV". and i have everything set in the gui and config files and its still deleting my mons.

**Comment by BangBhexe** [comment]
well this is my setting and it work fine 
![2016-08-10 18_24_16-pokegobot gui edition _ gui by greengold _ edit by iceq1337 gatno _](https://cloud.githubusercontent.com/assets/20933955/17552059/c4162fd2-5f27-11e6-8b3a-7d55f64e35f6.png)
![2016-08-10 18_24_03-pokemon list _ user_ phantomvanzdrey _ pokemons_ 86_250](https://cloud.githubusercontent.com/assets/20933955/17552061/c6fa721c-5f27-11e6-8949-511f59448dfd.png)
