### ISSUE TITLE
HKTL_POGOBOT

### ISSUE THREAD

**Issue by PokeGooo** [Ar1i/PokemonGo-Bot#2531]
Is there any way you can get rid of HKTL_POGOBOT in the encrpyt.dll, so I can get the bot downloaded? There were never any viruses in the previous versions, why is there one now?

**Comment by urangotango** [comment]
@xRealMaks ka ob das hier rein gehoert.......

**Comment by Yotumn** [comment]
@PokeGooo  Are you using windows 10? if you are I recommend you uninstall & delete all your 3rd party anti-virus programs. Win10 has an excellent built-in virus- & mallware detection system, which I have found very trustworthy.

**Comment by xRealMaks** [comment]
Just tell your Anti-virus to keep the file.
There is no virus. You can check the code if you want to (Open-Source :heart: )
