### ISSUE TITLE
no pokemon list after update anymore

### ISSUE THREAD

**Issue by saudeplao** [Ar1i/PokemonGo-Bot#2532]
now when i'm starting to bot, there's no pokemon list to check cp or IV 
![image](https://cloud.githubusercontent.com/assets/20947697/17551932/076ec754-5f27-11e6-8c54-bf3ca36729e4.png)

**Comment by xRealMaks** [comment]
Restart the bot

**Comment by saudeplao** [comment]
still nothing happened, i did it more than 10 times

**Comment by emilie253** [comment]
or you can find pokestop? I find nothing even if i use proxy :(

**Comment by xRealMaks** [comment]
hmm.. delete the config folder and try again

**Comment by PokeMungo** [comment]
or just delete the whole bot folder. then extract again the bot folder. and run bot again.

**Comment by saudeplao** [comment]
#emilie, i couldnt find pokestop an hour ago, i went to sleep and now it's normally

**Comment by saudeplao** [comment]
#xreal #pokemungo let's me try

**Comment by emilie253** [comment]
delete folders dont works :(

**Comment by saudeplao** [comment]
it's dont works to me too guys :(

**Comment by Gtalol123** [comment]
someone know how to use the new proxy thing

**Comment by xRealMaks** [comment]
Hmm.. very strage.
is this enabled?
![http://i.m4ks.cf/IAyrOPsV.png](http://i.m4ks.cf/IAyrOPsV.png)

**Comment by PokeMungo** [comment]
Xrealmark, hide your PTC username. they may ban you. bahahaha

**Comment by saudeplao** [comment]
holy, i forgot to check it, tks so much Xrealmark

**Comment by xRealMaks** [comment]
^^

**Comment by saudeplao** [comment]
now i got ban for 2 account bot :))

**Comment by xRealMaks** [comment]
@PokeMungo, fck.. thank you
