### ISSUE TITLE
proxy still not working on me

### ISSUE THREAD

**Issue by iwangrp** [Ar1i/PokemonGo-Bot#2533]
why proxy still not working on me ?

**Comment by WhoBotWhoBad** [comment]
The proxy works. I got 3 bot running in different proxies

**Comment by Gtalol123** [comment]
how i use the proxy

**Comment by iwangrp** [comment]
@WhoBotWhoBad i use in https://www.sslproxies.org/ , its right ?

**Comment by WhoBotWhoBad** [comment]
Heres the proof: https://s9.postimg.org/a42tap9vz/proxy.jpg

@iwangrp I used Gather Proxy

**Comment by bendeko** [comment]
@iwangrp @WhoBotWhoBad 

Are you entering the ip address under 'use proxy' box with the port number below the ip address if so it isn't working for me ?

**Comment by WhoBotWhoBad** [comment]
@bendeko Yes I did what you said and click save first before running the bot. Check your proxy in your browser first to see to it that your proxy works.
