### ISSUE TITLE
PokeStops not found! (Can´t find a solution in other issues)

### ISSUE THREAD

**Issue by PureSkill** [Ar1i/PokemonGo-Bot#2534]
So, it can´t find any pokestops, already tried the proxy, I use only 2 bots at the same time.

How to fix ? Can´t find in the other issues

Thanks

**Comment by Kidnub** [comment]
use only one bot per ip and get once a new ip , then use the unban button after start the bot ... pls use with one ip only one bot XD (free wifi ripped XD)

**Comment by PureSkill** [comment]
Still not working :(

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
