### ISSUE TITLE
How to unban IP SOFT BAN - easy help

### ISSUE THREAD

**Issue by prdlyandel** [Ar1i/PokemonGo-Bot#2536]
Easy way how to finish your IP SOFT BAN

1.Windows + R
2.Enter "cmd"
3.Enter into cmd.exe "ipconfig"
4.Enter into cmd.exe "ipconfig/release"
5.Enter into cmd.exe "ipconfig/renew"
6.Test your bot and use it only for 1 account

**Comment by emilie253** [comment]
dont work for me, i tried this morning x)

**Comment by emilie253** [comment]
need restrat my box :(

**Comment by PureSkill** [comment]
"No Operation can be performed on xxxxx while it has its media disconected"

**Comment by prdlyandel** [comment]
I have made this before 5 minuts and it helped me. I didnt find any other way.

**Comment by supermario007** [comment]
@prdlyandel does not work if you have a router behind your modem. Then you only renew your local IP-adres.

**Comment by jeremie152** [comment]
only one bot now?..........................................

**Comment by lailaps** [comment]
Yes, I also changed from 2 bots per IP to one!

**Comment by Captnred** [comment]
Thanks for the tips but also this:

If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Comment by ozdenor** [comment]
Thanks. It worked for me. Cheers :smile:

**Comment by jeremie152** [comment]
ok ty

**Comment by xJustx** [comment]
Not an issue
