### ISSUE TITLE
New app and everyone is getting softbanned

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#2537]
Could it be possible that Niantic changed something in unk6 so that botters are flagged,  because the ip softbans only started happening when the app was updated 2 days ago.

**Comment by xRealMaks** [comment]
Just run 1 instance of the bot.
It works for me

**Comment by suljo94** [comment]
@xRealMaks I am running just 1 instance

**Comment by Captnred** [comment]
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Comment by xRealMaks** [comment]
@Captnred.. its a question. Please post the right link.. https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by suljo94** [comment]
@Captnred but it is a issue I only have 1 account and a static ip because my provider, I keep on getting banned even on a vpn SO i asked you just to check the md5 of the libs because if that iss the problem we are bmaking a bad thing worse by using vpn/other ips and we are getting flagged every time we use the bot. when I am unbanned I can play without an issue by spoofing but as soon as I start the bot instand ban,; this happened befort on the night of the 3rd of august when niantic activated serverside verrification and now you vcan do what ever you want on the app(just don't jump too far but as soon as the bot is active you will get banned
