### ISSUE TITLE
Pokemon GO Bot Arena Kampf unmöglich?

### ISSUE THREAD

**Issue by Schob1337** [Ar1i/PokemonGo-Bot#2538]
Hey Leute,
Hab komplett googel durch gegoogelt, und finde leider garnix! 

Habe mich auf lvl 30 Hochgebottet und jetz hab ich das problem, ich kan wenn ich mich übers Handy einlogge keine Pokestops mehr aufnehmen oder auch keine Arena Kämpfe mehr betretten,
Jetz denkt ihr softban, aber nein seit 48h kan ich keine Arena betretten, seit 48h hab ich mich in den Bot nicht eingeloggt und habe auch vor 48h "unbann" benutzt.. 

Kennt jemand das problem? 
mfg.

**Comment by lailaps** [comment]
Hast Du den Account bestaetigt...
Teste mal ob er wirklich aktiviert ist!

**Comment by xRealMaks** [comment]
Du bist warscheinlich soft-banned, da du dich von NewYork (standartlocation) zu dir nach hause "geportet" hast. 
Stell den bot auf deine location und lass ihn mal 5 minuten laufen. der softbann sollte dann vom unban-script reomoved werden.
