### ISSUE TITLE
iv Berechnung

### ISSUE THREAD

**Issue by pwnjke** [Ar1i/PokemonGo-Bot#2540]
![untitled](https://cloud.githubusercontent.com/assets/20947780/17552211/cd37e106-5efe-11e6-92c0-d32c64412100.png)
das kann doch nicht wahr sein, oder? der zweite Eevee hat 39 aus möglichen 45 und hat 90,17%, wobei der dritte mit 42\45 hat nur 1% Unterschied zu dem zweiten. Oder verstehe ich was falsch? Ist es nicht so, dass der 0% perfect hat 0-0-0, also 0\45 und der 100% perfect hat 15-15-15, also 45\45? Wenn es tatsächlich so ist, dann ist doch jeder einzelne Punkt in attack-def-stam ungefähr 2,22% zu iv. Aus meinem Screenshot der erste markierte eevee sollte ja ungefähr 93,4% haben. warum ist er so schlecht bewertet, wenn ihm nur 3 Punkte bis 100% nicht reichen? und warum hat der zweite größeren iv Wert, obwohl ihm im Vergleich zu dem ersten die doppelten Punkte bis 100% nötig sind?

P.S. Vielen Dank für Ihre Arbeit, Jungs. Der Bot ist megageil.
P.S.S. Sorry wenn mein Deutsch zu schlecht ist, bin ziemlich neu in Deutschland

UPD
![untitled](https://cloud.githubusercontent.com/assets/20947780/17554080/7bf108e4-5f09-11e6-9c35-d4de160d57d3.png)
vielleicht hilft das irgendwie, ich habe keine Ahnung vom Programmieren. die beiden Krabbys sollten doch gleich vom % sein

**Comment by xRealMaks** [comment]
Richtig. Wir berechnen den IV-Wert bevor er gerundet wird. Daneben stehen dann die gerundeten werte.

**Comment by pwnjke** [comment]
da bin ich wieder. ich habe noch was zu iv gemerkt
![untitled](https://cloud.githubusercontent.com/assets/20947780/17561644/5c1d8894-5f27-11e6-876a-93c9b5d67c6e.png)
der neu gefangene dratini hatte wirklich 84% iv. aber der wurde weggeschickt, weil der Bot dachte, dass der auf der rechten Seite unterstrichene das selbe iv hatte
