### ISSUE TITLE
Suggest : Italian language 

### ISSUE THREAD

**Issue by asmamalik** [Ar1i/PokemonGo-Bot#2541]
{
-    "accountType": "Tipo Account:",
-    "username": "nome utente:",
-    "password": "Password:",
-    "locationSettings": "Settaggio località",
-    "speed": "Velocità:",
-    "moveRadius": "Raggio di Azione :",
-    "meters": "metri.",
-    "startFromDefaultLocation": "Inizia da Posizione predefinita",
-    "botSettings": "Settaggio Bot",
-    "autoTransferDoublePokemon": "Auto Trasferimento Pokemon doppi",
-    "maxDupPokemon": "Max. Pokemon duplicati :",
-    "maxCPtransfer": "Max. Trasferimento CP:",
-    "maxIVtransfer": "Max. IV trasferimento:",
-    "telegramSettings": "Settaggi Telegram",
-    "infoline1": "Questo Bot è completamente gratuito ed open source ! Se avete pagato per questo , fatevi rimborsare ! "
-    "infoline2": "Ogni volta che si verifica qualcosa di simile a un ' Pokecrot ' , dite loro che il BOT è stato rubato ! "
-    "maxPokeballs": "Маx. Pokeballs:",
-    "maxGreatballs": "Маx. MegaBalls:",
-    "maxUltraballs": "Маx. UltraBalls:",
-    "maxMasterballs": "Маx. MasterBalls:",
-    "maxRevives": "Маx. Revitalizzante:",
-    "maxTopRevives": "Маx. TopRevitalizzante:",
-    "maxPotions": "Маx. Pozione:",
-    "maxSuperpotions": "Маx. SuperPozione:",
-    "maxHyperpotions": "Маx. IperPozione:",
-    "maxToppotions": "Маx. TopPozione:",
-    "maxRazzberrys": "Маx. BaccaLampon:",
-    "totalCount": "Totale :",
-    "pokemonNotToTransfer": "Pokemon da non trasferire",
-    "selectAll": "Seleziona tutto",
-    "pokemonNotToCatch": "Pokemon da non catturare",
-    "pokemonNotToEvolve": "Pokemon da non evolvere",
-    "saveConfig": "Salva Configurazione / Inizia ",
-    "otherSettings": "Altri Settaggi",
-    "useLuckyeggAtEvolve": "Usa Fortunuovo per evolvere",
-    "germanPokemonNames": "Usa nomi tedeschi ai Pokemon",
-    "useIncese": "Usa modulo esca  ogni 30 minuti.",
-    "evolvePokemonIfEnoughCandy": "Evolvi i Pokemon se non ci sono caramelle",
-    "enablePokemonListGUI": "Abilita Lista Pokemon",
-    "keepPokemonWhichCanBeEvolved": "Mantenere il Pokemon che puo' essere evoluto"

**Comment by asmamalik** [comment]
i traslate for italian language

**Comment by xRealMaks** [comment]
Thanks for your translation. Please open a Pull-Request ^^

**Comment by asmamalik** [comment]
I can not create it
