### ISSUE TITLE
% Abweichung im GUI

### ISSUE THREAD

**Issue by AlpaEZPZ** [Ar1i/PokemonGo-Bot#2543]
Hallo,

Ich habs leider nicht ganz verstanden, obwohl es in ein paar threads bereits besprochen wurde.
Ich habe folgende abweichung festgestellt:

![10-08-2016 13-50-02](https://cloud.githubusercontent.com/assets/20835995/17552789/4594e5a6-5f02-11e6-9374-091f1983b529.jpg)

Zu erkennen sind zwei farblich gekennzeichnete bereiche, in denen offensichtlich der IV bzw % abweichen.

Kann mir eben nochmal jemand erklären warum das so ist, oder ist es ein bug ?
Welcher Wert ist jetzt für mich entscheidend bei der weiterentwicklung ?

MfG Alpa

**Comment by Requal** [comment]
Warum was ist?
Warum die IV abweichen oder?
Höheres IV heisst bessere  powerups, evolutions.

**Comment by AlpaEZPZ** [comment]
schon klar auf dem bild links ist aber zu sehen 94% und rechts 69%.
Auf mich wirkt das sehr verwirrend.

**Comment by Requal** [comment]
Weil links hatt doch weniger CP...
CP ist Kampfkraft und ist primär.
IV ist nur eine Berechnung wie gut es werden kann.
Deshalb hatt es denn mit wenig CP getranfered.

**Comment by zorndyke** [comment]
you just caught pinsir [13:46:25], look at the console at left picture.
the pokemon list table on right side are old data, you must press reload to get new data.
the new pinsir not registered on the table yet.
nothing wrong with it

**Comment by Requal** [comment]
Aaaah warte... du meinst weil er sagt best 94%...
Aber rechts ist kein 94% da...?

**Comment by Requal** [comment]
Ja was er sagt click mal reload
