### ISSUE TITLE
Bot geht immer noch nicht 

### ISSUE THREAD

**Issue by tarnerus** [Ar1i/PokemonGo-Bot#2544]
Habe immer noch das problem habe auch 15 min gewartet. was soll ich jetzt machen damit er wieder geht? es kommt immer das gleich

 
![bot geht nicht](https://cloud.githubusercontent.com/assets/20948391/17552852/aca2e914-5f02-11e6-8558-3ff02c1628e8.png)

**Comment by Kidnub** [comment]
neue ip?

**Comment by Dinja1990** [comment]
Hallo Ich habe das Problem auch.

**Comment by xxhamsterxx** [comment]
neue ip hilft nichts -_-

**Comment by Requal** [comment]
Hab ich auch.
IP ist nicht das problem weil auf dem handy über wifi funkt es gut.

**Comment by Dinja1990** [comment]
Geht bot über Handy?
Wenn ja dann wie?

**Comment by dadaxd** [comment]
Router neustarten, habe das problem wenn 2 bots laufen...aber bei einem keine probleme...

**Comment by tarnerus** [comment]
okay das versuche ich mal

**Comment by fourmansyah** [comment]
just go with Auto Proxyfier, The IP will Change In 30 Minute .. And That Will Fix it Auto.

**Comment by xJustx** [comment]
^
