### ISSUE TITLE
Beeping (Tested with Win 7 & 8.1)

### ISSUE THREAD

**Issue by Efotia** [Ar1i/PokemonGo-Bot#2545]
Hello guys my bot is beeping for no reason i was using Windows 7 x64, Just to be sure i reinstalled my windows and now using 8.1 Pro x64.

Sadly beep is still continues..  

**-Solutions which i've already tried-**

1.There no beeping if i exit bot (tested few hours)
2.Delete bot folder and download newest version
3.Reinstall/Change windows version

![2](https://cloud.githubusercontent.com/assets/20907961/17552826/f60b89f0-5f0a-11e6-8ced-edd0336f1c31.png)
![3](https://cloud.githubusercontent.com/assets/20907961/17552828/fa7a01f6-5f0a-11e6-96e7-02d731144b33.png)

I'm not blaming anyone just trying to fix what i got here but if bot has no any sound , Why theres a volume control for bot in sound settings ( Its appeared right after i install Win 8.1 )

![adsiz](https://cloud.githubusercontent.com/assets/20907961/17552830/fc7286cc-5f0a-11e6-98fd-9268390e8861.png)

**Comment by xRealMaks** [comment]
Check the code. There is no "beep" or something like that.
Maybe there is a setting in windows, which make your console beep when a ceratin event happen.
But now you can just mute the console. There's nothing we could fix.
