### ISSUE TITLE
Proxy funktioniert nicht

### ISSUE THREAD

**Issue by GreYzZ** [Ar1i/PokemonGo-Bot#2546]
Hallo,
kann es sein, dass das Proxy setting im Bot nicht richtig funktioniert?
Ich verwende verschiedene Proxys, sobald ich 2 Bots laufen lasse
bekommen beide einen Ban.

Jemand nen Tipp?

**Comment by xRealMaks** [comment]
Es kann sein, dass Niantic auch bans verteilt die auf die selbe System-ID (vom handy). Versuch mal den Bot 2x in verschiedene Ordner zu extrahieren und dann die bots aus den verschiedenen Ordner zu starten.

**Comment by GreYzZ** [comment]
Schon probiert funktioniert auch nicht

**Comment by rondellini** [comment]
Hat bei mir so nicht funktioniert xRealMaks, habe auch seit Beginn zwei unterschiedliche Ordner für die Bots mit unterschiedlichen Instanzen. Habe einen Bot auf meiner IP laufen lassen und einen per Proxy eingerichtet. Haben zum selben Zeitpunkt einen Softbann bekommen.

**Comment by ridd97** [comment]
Bei mir geht es auch nicht, ladet euch Necrobot Runter und lasst Necrobot und diesen Bot gleichzeitig laufen, mach ich seit 20 Min ohne Probleme oder softbanns.

**Comment by KingKacke** [comment]
Hey, weiß nich wo ich sonst fragen soll, aber wozu genau wird die Proxysache hier beim Bot genutzt? 2 Bots parallel auf einem Account?! Danke schonmal für die Hilfe!

**Comment by xRealMaks** [comment]
2 Bots auf einem Account sollte zu einem Soft-Ban führen. 
Wenn man für sein Kollegen ein Account boosten will, dann brauch man ein Proxy damit nicht beide auf der gleichen IP laufen, was sonst auch zu einem Softban führen würde.

**Comment by xRealMaks** [comment]
@GreYzZ bekommst du so eine meldung wenn du mit proxy startest?
![http://i.m4ks.cf/uo7iUmGc.png](http://i.m4ks.cf/uo7iUmGc.png)

**Comment by GreYzZ** [comment]
@xRealMaks, ja die bekomme ich auch

**Comment by xRealMaks** [comment]
Habs mal als bug geadded..

**Comment by GreYzZ** [comment]
@xRealMaks, okay danke.
Hast ne möglichkeit @Ar1i auf die schnelle zu erreichen?

**Comment by geebart1337** [comment]
Ich habe genau das selbe Problem.
Habe die Bots aus verschiedenen Ordnern gestartet mit jeweils anderen https Proxy servern aus Deutschland, bekomme trotzdem softbans bei mehr als einem Account, obwohl er sich korrekt über den Proxy einloggt.
Meine IT-Kenntnisse sind nicht groß, aber könnte es daran liegen, dass mehrere Leute den selben Proxyserver von z.B. der free proxy list von hidemyass benutzen?

**Comment by xRealMaks** [comment]
@GreYzZ Ar1i ist grad nicht zuhause^^

**Comment by deface0x2** [comment]
Klar kann das sein @geebart1337 - die Wahrscheinlichkeit habe ich bei mir z.B. schon ausgeschlossen, da ich den Bot mit meiner IP schon ca. 10 Stunden am laufen hatte. Nachdem ich den zweiten per Proxy gestartet hatte, wurden beide direkt Softbanned.

**Comment by xRealMaks** [comment]
Make sure you use a HTTPS proxy

**Comment by GreYzZ** [comment]
Yep I'm using HTTPS Proxys
But got the problem

**Comment by Ar1i** [comment]
yes, should be fixed.

**Comment by Ar1i** [comment]
Should be fixed in newest build
