### ISSUE TITLE
Bot Don't Work !

### ISSUE THREAD

**Issue by pitacho15** [Ar1i/PokemonGo-Bot#2547]
![c](http://i.imgur.com/2pnrZEl.png), Our pokemons ever fo out :s

**Comment by arjunvegda** [comment]
unable to open the URL please paste the image @pitacho15

**Comment by pitacho15** [comment]
![1111](https://cloud.githubusercontent.com/assets/20948565/17553222/9c5867b0-5efc-11e6-815f-6ac0673bee98.png)

**Comment by Dinja1990** [comment]
I'VE this one too.... :(

**Comment by xRealMaks** [comment]
Just wait. We got plenty of these "bugs", all got solved by waiting 15 minutes. Probably a downtime of pokemon servers ^^

**Comment by Praxthisnovcht** [comment]
surely a ban.
log on your smartphone and watch if you see or pokestop arena

**Comment by sunsiskos** [comment]
Try to restart your modem, it worked for me. Using 1 client only atm.

**Comment by Dinja1990** [comment]
On my smartphone i see all pokestops and this work. But bot i have error.
Sorry for my english.

**Comment by xRealMaks** [comment]
Maybe IP-ban. As @sunsiskos said, try to restart your modem.

**Comment by Dinja1990** [comment]
I tryed restart my modem but it dont work 😣

**Comment by fourmansyah** [comment]
just go with Auto Proxyfier ... cange your IP in 30 Menute Automaticly

**Comment by sunsiskos** [comment]
@Dinja1990 I waited few mins after restarting and it worked on me. 
http://i64.tinypic.com/2j2wyed.jpg

**Comment by pitacho15** [comment]
Yes, its a IP BAM ty

**Comment by pitacho15** [comment]
But now i have this problem  all pokemons go away 
![22222](https://cloud.githubusercontent.com/assets/20948565/17553596/949ea0c8-5efe-11e6-893e-36489a6ff82d.png)

**Comment by fourmansyah** [comment]
if u use Auto Proxyfier, The Ip will Change Auto. If the IP on Bot Is Blocked .. Just Set The  Proxyfier Fokus On the BOT .. like This...

<a href='https://postimg.org/image/5lxaqre23/' target='_blank'><img src='https://s9.postimg.org/o1hro5s6n/image.jpg' border='0' alt='1'/><br /><a target='_blank' href='https://postimage.org/'>free jpeg images</a><br /><br />

**Comment by pitacho15** [comment]
How to config  ?

**Comment by Dinja1990** [comment]
i have this problem always
 http://de.tinypic.com/r/2ngdkap/9

**Comment by pitacho15** [comment]
@Dinja199 You have  your ip ban, restart your modem our change  your IP

**Comment by Yummster** [comment]
@fourmansyah just a headsup, you've included your unique usernames on the image.

**Comment by ahya93** [comment]
i think server is down now...

**Comment by sunsiskos** [comment]
Bot is working fine for 1h now after restarting modem and waiting for a while.

**Comment by Nolera** [comment]
I can find all pokestop but all pokemon ran away... cant catch it.

**Comment by ahya93** [comment]
Now server online :dancer: 
@Nolera click Force Unban Button

**Comment by JCortexs** [comment]
its working for me but every 15 min i have to restart

**Comment by JCortexs** [comment]
not working again

**Comment by getthub** [comment]
not working on me :(
