### ISSUE TITLE
After update bug

### ISSUE THREAD

**Issue by Yacineabed** [Ar1i/PokemonGo-Bot#2548]
![capture](https://cloud.githubusercontent.com/assets/20948655/17553217/f61d30ca-5f04-11e6-8cf2-629dbf9301eb.PNG)

Help me !!

**Comment by xRealMaks** [comment]
Error sounds like a downtime of google-servers ^^
Wait 15 minutes and try again

**Comment by sidd1993** [comment]
dont worrie... bot are not working right now....

**Comment by urangotango** [comment]
i have Version 1.0.8.0 running since yesterday with 1 istance and it is keep running 
no banns 
no stucks 
anything ok... 
but just 1 istance

**Comment by urangotango** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20893546/17553497/6077f9c2-5f06-11e6-8380-ea798de24706.png)

**Comment by Bangden** [comment]
Delete ur folder and restart laptop or pc.
try re-extract bot and relogin bot

**Comment by BlackHatching** [comment]
No its just Google accounts (US) are laggy now
