### ISSUE TITLE
POKEMON NO TRANSFER

### ISSUE THREAD

**Issue by uena** [Ar1i/PokemonGo-Bot#2551]
pokemon no transfer why?

**Comment by xRealMaks** [comment]
![u](http://i.m4ks.cf/P4yhaVJl.png)
Uncheck this

**Comment by uena** [comment]
thanks you

**Comment by xRealMaks** [comment]
does it work?

**Comment by uena** [comment]
not good work

**Comment by xRealMaks** [comment]
So does it work?

**Comment by uena** [comment]
work sometimes

**Comment by xRealMaks** [comment]
Maybe they got a high CP/IV so that they wont get transfered

**Comment by uena** [comment]
max cp to transfer 600 max iv to transfer 60 and no transfer ;/

**Comment by uena** [comment]
sometimes transfer

**Comment by michi04** [comment]
max cp to transfer to 2500, max iv to transfer 99% and it could work..
