### ISSUE TITLE
Strange error. My first encounter

### ISSUE THREAD

**Issue by WhoBotWhoBad** [Ar1i/PokemonGo-Bot#2553]
Maybe you can have a look. It went back after it throw a bunch of exception errors

![error](https://cloud.githubusercontent.com/assets/20833381/17553546/fe8176ca-5f38-11e6-821e-1703539c67bd.jpg)

Thanks by adding proxy by the way. 5 bot running now in 5 different proxies :dancers:

**Comment by janusmiranda** [comment]
can someone teach me in proxy...

**Comment by xJustx** [comment]
I think this is cause the proxy.
