### ISSUE TITLE
Setting Bug

### ISSUE THREAD

**Issue by SkyWalkerMc** [Ar1i/PokemonGo-Bot#2555]
Some Setting reset when i re-run bot, ex :

checked auto use lucky egg
unchecked first IV
unchecked use proxy

**Comment by Efotia** [comment]
Same here

**Comment by WhoBotWhoBad** [comment]
The uncheck use proxy works when you click the save button. It just the check mark doesnt appear.

**Comment by xRealMaks** [comment]
You have to click the "Save Configuration / Start Bot"- Button when you changed something..
I tried i out myself and the bot saved my settings

**Comment by pwnjke** [comment]
my bot saves not the new "low iv transfer first". when i restart the bot, it is always checked. and some more. i dont know how and why, but the bot ate all of my lucky eggs i got at lvl 30. i had disabled everything about lucky eggs

**Comment by dragon2011** [comment]
same here, its bugged
