### ISSUE TITLE
Still getting softbans while using Proxy's

### ISSUE THREAD

**Issue by geebart1337** [Ar1i/PokemonGo-Bot#2556]
I'm still getting softbans while using Proxy's.
I'm located in germany and am using https Proxy servers located in germany.
I used a different Proxy server for each bot. When I start the bot it connects correctly with the Proxy server and 1 bot is farming correctly. But 2 bots at the same time are giving me softbans.

Any ideas?

**Comment by xRealMaks** [comment]
Known issue. We look into that.
#2546
