### ISSUE TITLE
Not Issue || Just Fix Your All Problem

### ISSUE THREAD

**Issue by fourmansyah** [Ar1i/PokemonGo-Bot#2557]
First The Issue Like Blocked IP ...
1. Download New Version Of This ar1i BOT
2. Insert Proxy To Proxy Tab [ If U Want Some Proxy Just Go To http://spys.ru/
3. Save Your IP Proxy
4. Its Done

[If u Have Run 3 Bot MAke All Of Them Different IP]

If U Want Easely Get The Ip Cange If Blocked Jus Download Software Auto Proxyfier Online. And Set Fokus On The BOT .. If Ip Blocked It Will Change Automaticly.
If u Want Change The IP Manually Just Go With HotspotShild Or BETTERNET Or Something Like This Software .. Thanks.

And One More Important Thing, You Can Only Running 3 BOT.

If U Have Any Problem Just Ask. May be I Can Help U.

Sorry For My Bad English, I just Want To Help Mr.Ar1i for Some Issue. His Bot Is Realy Amazing ..

**Comment by xRealMaks** [comment]
This is only for issues. Sorry. But thanks for your work.. I'll link that to issues

**Comment by Nolera** [comment]
@fourmansyah org indo yah... nanya donk saya kurang ngerti pake bot yg terbaru ini agak ribet, ga kaya yg kmaren2... auto proxy itu donlot dimana yah heheh
