### ISSUE TITLE
Soft Ban on Bot AND phone?

### ISSUE THREAD

**Issue by Tymoc** [Ar1i/PokemonGo-Bot#2558]
I tried to use the newest bot on my regular IP, and noticed the proxy setting - so I tried a proxy, and seems to have been soft banned... "no pokestops within 5000 meters" etc.  So I tried to log into the account on the phone, and it seems as if everything disappeared. Is this also a soft ban?  Never ran into this problem before - so how long does this soft ban last?

**Comment by PokePro21** [comment]
it happened with me also try after 2-3 hours.it will get fixed

**Comment by xRealMaks** [comment]
^

**Comment by Tymoc** [comment]
Definitely IP ban... i turned off wifi - logged back into game using 4G and everything was there...

**Comment by xJihadx** [comment]
I was IP banned on my home IP a few days ago, nothing was on map for hr's. If I logged on a VPN all was good, so I reset my home IP address and everything was good.

I would suggest when your botting use Hotspot shield, it offers a free VPN.

**Comment by Tymoc** [comment]
@xJihadx  - Im at work at the moment... so it's a business IP... and im on wifi as well... will that work in this case?
