### ISSUE TITLE
Good pokemon transfered

### ISSUE THREAD

**Issue by iano85** [Ar1i/PokemonGo-Bot#2559]
Omg , i lose 5 - 6 pokemon and i close immediatly (growlite 1k ). Why happening?? example :  transfer my 1300 goldbat and the bot say that the best goldbat in my account is goldbat 1300 . Sorry for my english.

**Comment by NaveTK** [comment]
Check the settings of your bot, there is a checkbox that says "TransferLowIVsFirst" or something like that and uncheck it. If it's enabled that means the bot keeps the Pokemon with the highest IVs instead of the highest CP, if it's disabled then it's back to how it worked before

**Comment by iano85** [comment]
Ok , i try. What is the best setting IV and CP ?

**Comment by dragon2011** [comment]
its bugged, my box wasnt checked and it trasfered high cp pokemon

**Comment by xJustx** [comment]
#2564
