### ISSUE TITLE
*issue* ok issue about the ip ban i confirmed it

### ISSUE THREAD

**Issue by wrobe06117** [Ar1i/PokemonGo-Bot#2560]
regarding the idea of others saying you cant open 3 client in a single ip this is the findings i got after some experiment with the bot

1.i tried using 3 bots without proxy after 15mins i get ip ban
2.i tried using 3 bots with proxy after 15mins i get ip ban also
3.i tried lowering the bot walking speed to 5km/h with 3 account still ip ban
4.i tried lowering the bot walking speed to 5km/h with 1 account no ip ban
4.i tried using only 1 bot without proxy on 300km/h speed after 15mins and some more i dint get ip ban
5.i tried using only 1 bot with proxy on 300km/h speed after 15mins and some more i dint get ip ban

so for now the only fix is just use 1 bot dunno why the ip proxy isnt working either as a solution

**Comment by xRealMaks** [comment]
#2546
we know about that.

**Comment by wrobe06117** [comment]
@xRealMaks  ohh sorry dint understand the language so when i checked about the issue i thought no one experimented on it

**Comment by xRealMaks** [comment]
No problem.. it was the first post, so we kept that.. I sure we'll fix that today-tomorrow
