### ISSUE TITLE
Maximum walking radius

### ISSUE THREAD

**Issue by NaveTK** [Ar1i/PokemonGo-Bot#2561]
So either the new livemap feature does not display the max radius correctly, or the bot just ignores it, eitherway it shows the bot simply walking outside the area and using PokeStops there. It's not a huge problem atall but just wanted to let you know (the radius I used is 2000m)
![locationbug](https://cloud.githubusercontent.com/assets/20726254/17554716/8cbac644-5f0c-11e6-8fcb-a01ea4d6ed67.png)

**Comment by coolbuddy26** [comment]
yeah the bot goes into the ocean where there are no pokestops
