### ISSUE TITLE
How I unbanned my account

### ISSUE THREAD

**Issue by HackerPide** [Ar1i/PokemonGo-Bot#2562]
I got a softban from using 2 bots on same pc. Then I tried to see on Nox if I could see any pokestops where I couldn't but then I tried looking at pokestops from my phone's Pokemon GO app(different ip) then I could see pokestops on my app(although i teleported to me current location from the place i set on the bot). Thne i tried running the bot on a different country and the bot was working perfectly.

**Comment by xRealMaks** [comment]
Only one Bot per IP or you will get a IP-Ban.

If you're softbanned, you see pokestops, but you dont get items/xp from them

**Comment by xRealMaks** [comment]
But its not an issue.. closed
