### ISSUE TITLE
[Bug] Transferring BUG

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#2564]
Keep my low level Paras and Transferring my high level CP anyone ?
![paras](https://cloud.githubusercontent.com/assets/20843400/17554972/40b0f4b6-5f2b-11e6-9a50-ed438432bc0b.png)
![paras1](https://cloud.githubusercontent.com/assets/20843400/17554975/45727baa-5f2b-11e6-9497-77b17f9add0c.png)

**Comment by xRealMaks** [comment]
did you checked this?
![p](http://i.m4ks.cf/UuN1QFSL.png)

**Comment by PokePro21** [comment]
yes

**Comment by PokePro21** [comment]
okay i got it

**Comment by PokePro21** [comment]
just beacuse of that only @xRealMaks  ?

**Comment by xRealMaks** [comment]
pretty sure.

**Comment by dragon2011** [comment]
same happened to me, but my box was NOT checked, it transfered my high level blastoise and kept the low level blastoise because low level blastoise had higher iv, but the box wasnt checked for that, i am using 1.0.84 version now, 1.0.85 still to buggy

**Comment by testo4life** [comment]
its a bug whenever is UNCHECk it the next time il start it checked again!

**Comment by kazzaluis** [comment]
#2622

**Comment by PokePro21** [comment]
@Ar1i  thus it get fixed now?
