### ISSUE TITLE
Proxies don't work

### ISSUE THREAD

**Issue by Tymoc** [Ar1i/PokemonGo-Bot#2566]
So if my IP is soft banned (which it seems to be right now) - and I put in a new proxy - it should work?  But this is not the case... somehow Niantic knows it is my IP or at least the originator.

Any clue / help on this?

**Comment by GreYzZ** [comment]
#2546

**Comment by Tymoc** [comment]
Sorry - I don't speak German?

**Comment by xRealMaks** [comment]
We are aware of this problem
