### ISSUE TITLE
We can't find any pokestops in a range of 5000! again and again

### ISSUE THREAD

**Issue by smoreaudve** [Ar1i/PokemonGo-Bot#2569]
Hello, 
Thank you for the app.

But i restart and update my version, but always : 

"We can't find any pokestops in a range of 5000!"

Seriously, im going crazy ^^
Please, just keep me in touch. Thank you

**Comment by shaor4n** [comment]
yes. just happened on me too

**Comment by ozdenor** [comment]
Your IP has been banned! 

#2536

**Comment by fourmansyah** [comment]
use software to change your ip auto.

**Comment by smoreaudve** [comment]
ah ;) cool thank you for the answer, i will test that ;)

**Comment by Efotia** [comment]
I had same issue few hours ago just restart your modem ~ it worked perfectly for me

**Comment by Psycherl** [comment]
Your IP is banned! Make it change ;-)

**Comment by smoreaudve** [comment]
And Is the ip can be debanned after some time ?

**Comment by IDonated** [comment]
Why if Im static ip? Proxies?

**Comment by ManoBM** [comment]
@Efotia  thank for that man
