### ISSUE TITLE
Bot unable to catch Pokemon.

### ISSUE THREAD

**Issue by Fidanzaa** [Ar1i/PokemonGo-Bot#2570]
![](https://i.gyazo.com/179dd4fe9e34f103b172a4ef31a87bbb.png)

![](https://i.gyazo.com/2bdb733e27fd7d9b18a0cc4ec2a89e07.png)

As you can see every time the bot encounters a Pokemon it tries to catch it while it fails every time.

**Comment by coolbuddy26** [comment]
make pokeballs to 25 atleast

**Comment by ozdenor** [comment]
All pokeballs have to be different than zero.

**Comment by Fidanzaa** [comment]
Thanks for the quick reply, I will try your recommendations!

**Comment by Fidanzaa** [comment]
The issue has been solved, thank you!
