### ISSUE TITLE
BUG!!!!!

### ISSUE THREAD

**Issue by Xeroxs** [Ar1i/PokemonGo-Bot#2571]
hello I have the same problem as the last authentic, it gives me the sentence:
![image](https://cloud.githubusercontent.com/assets/20836902/17555769/13290fd4-5f11-11e6-981b-7a4e9a154504.png)

what is it that can help me SVP

**Comment by aztenjin** [comment]
What is the location you put in?

**Comment by Xeroxs** [comment]
I was your Syndey

**Comment by aztenjin** [comment]
Is the game available in Sydney yet?

**Comment by Xeroxs** [comment]
I know when I have half my position in New York is its my say the same thing is also Paris

**Comment by aztenjin** [comment]
what are the coordinates shown in the game client?

**Comment by Psycherl** [comment]
Not a Bug, your IP is just banned!

**Comment by Xeroxs** [comment]
40,764883
-73,972967

**Comment by Xeroxs** [comment]
I must do what?

**Comment by CruSherFL** [comment]
Try it again in 1 hour. It should work then.

**Comment by Xeroxs** [comment]
are you sure ?

**Comment by starscream151** [comment]
yes, it's not a bug, your ip just banned, try again in 30 minutes... i only run 1bot/ip now

**Comment by Ar1i** [comment]
^or use https proxy
