### ISSUE TITLE
Auto Incubate - Translation Problem (German)

### ISSUE THREAD

**Issue by Experte9** [Ar1i/PokemonGo-Bot#2573]
Hi, ich weiß jetzt nicht welcher Übersetzung ich glauben soll...
![eng](https://cloud.githubusercontent.com/assets/20842528/17556099/77a02a64-5f12-11e6-9e73-bccda10c79e9.JPG)
![de](https://cloud.githubusercontent.com/assets/20842528/17556100/77a6c112-5f12-11e6-900e-5eaff1a7aef5.JPG)
Ich möchte das der Bot **nicht** die begrenzten nutzt!

Danke :)

**Comment by LuckyBoy1101** [comment]
tut mir leid kann dir da net helfen
aber des funktioniert allgemein net mit dem auto incubate

**Comment by Experte9** [comment]
@LuckyBoy1101 Ach echt? 
Wurde das schon als Issue gemeldet?

**Comment by Ar1i** [comment]
ja is schon bekannt

**Comment by Experte9** [comment]
@Ar1i und was muss ich anhacken damit (wenn es behoben wurde) **nicht** die begrenzten genutzt werden?

**Comment by batuhanoktem** [comment]
Text encoding must be UTF-8, please convert it
