### ISSUE TITLE
Help with Proxy

### ISSUE THREAD

**Issue by yaowa** [Ar1i/PokemonGo-Bot#2574]
############# Check-list. read before posting! #############
I SEARCHED MY PROBLEM IN THE ISSUES

MY ISSUE DIDNT GET ANSWERD PREVIOUSLY

MY ISSUE IS AN ISSUE AND NOT A QUESTION/SUGGESTION

I USE THE NEWEST VERSION
#####################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Post. Mods feel free to remove/move this, as it is not an issue, but can someone please walk me through the use of the proxy feature? Is there a known proxy or is this up to the user? Also, what is the authentication? If someone could please advise me of how to properly use this added feature it would be incredibly helpful.

**Comment by MiGaBelG** [comment]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/570331-quick-ip-unban-vpn-ip-no-ban.html
That tutorial explains it all ;)
