### ISSUE TITLE
How do you create a new IP

### ISSUE THREAD

**Issue by edwfgthyb2rfjdk** [Ar1i/PokemonGo-Bot#2576]
Please help because it takes ages for it to unband me

Add a screenshot!

Choose a good title!

Post.

**Comment by aztenjin** [comment]
You dont, Your ISP assigns IP addresses


Your best possible solution is to unplug your modem / router, from all cables, and reconnect in an hour, that MIGHT get the ISP to assign you a new IP address

**Comment by MariusSolaat** [comment]
VPN seems to work

**Comment by jodirt282** [comment]
If after rebooting modem you still have same IP. Go into router configuration and change MAC Address, then unplug router and modem.

**Comment by LordBunny** [comment]
1)Open cmd
2)Type and press enter "ipconfig"
3)Type and press enter "ipconfig/release"
4)Type and press enter "ipconfig/renew"

I have this from MPGH and maybe this works for you; it change your ip.

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
