### ISSUE TITLE
Bot can't catch pokémon

### ISSUE THREAD

**Issue by NatyNaytor** [Ar1i/PokemonGo-Bot#2577]
Bot visit poké stops, transfert items and pokémons but can't catch any pokémon.
I try to change ip, with another account, and also unistalling and reinstalling bot files.
Someone can help me?
![dasdadadasdasdsadasd](https://cloud.githubusercontent.com/assets/20950971/17557152/70b6e2b6-5f16-11e6-96d2-be11b0362432.png)

**Comment by Experte9** [comment]
Bot catch Pokemon:
0-499 CP --> Pokeball
500-999 CP --> GeratBalls
<1000 CP --> UltraBall

so check your settings

**Comment by Experte9** [comment]
Bot catch Pokemon:
0-499 CP --> Pokeball
500-999 CP --> GeratBalls
<1000 CP --> UltraBall

check settings if u have 20 Pokeballs.

**Comment by NatyNaytor** [comment]
Solved! Tx Experte9
![dasdadadasdasdsadasd](https://cloud.githubusercontent.com/assets/20950971/17558352/96f7d1f2-5f1a-11e6-9616-726b9ef5c25d.png)

**Comment by xJustx** [comment]
^
