### ISSUE TITLE
new Build

### ISSUE THREAD

**Issue by neocrypton** [Ar1i/PokemonGo-Bot#2578]
############# Check-list. read before posting! #############
I SEARCHED MY PROBLEM IN THE ISSUES
a
MY ISSUE DIDNT GET ANSWERD PREVIOUSLY

MY ISSUE IS AN ISSUE AND NOT A QUESTION/SUGGESTION

I USE THE NEWEST VERSION
#####################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Post.

**Comment by blue7790** [comment]
![image](https://cloud.githubusercontent.com/assets/20891928/17557294/d64d831c-5f40-11e6-9edb-1f62e637dc10.png)

**Comment by Hydro420** [comment]
Update .net Framework
