### ISSUE TITLE
 [Recommended] value is below a certain CP, auto transfer.

### ISSUE THREAD

**Issue by yamio** [Ar1i/PokemonGo-Bot#2580]
Recommendations can be set below a certain value or less CP
Auto transfer Pokemon can dream, can avoid the Pokemon more than 250, stop working..

**Comment by Fertigpizza** [comment]
this is an excellent idea! Every few hours I need to manually delete pokemon

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
