### ISSUE TITLE
Bot Not Working :/

### ISSUE THREAD

**Issue by Sho0t3r** [Ar1i/PokemonGo-Bot#2581]
![d13a55212a5d22a5345bc00a9d90e0c6](https://cloud.githubusercontent.com/assets/20951112/17557354/259fd32c-5f17-11e6-8dc4-95c1ccd9d2f2.png)

**Comment by Hydro420** [comment]
Update the bot and make sure your cords are set where there is actually pokestops.

**Comment by emilie253** [comment]
restart your box to change ip :)

**Comment by Hydro420** [comment]
I doubt its IP ban? I had softban pop up last night and Unban feature worked like a charm within 5 seconds I was back to farming.

**Comment by Sho0t3r** [comment]
i think im ip banned cause they are realy no pokestops and pokemons in the near... what can i do?
