### ISSUE TITLE
error for the bot ?

### ISSUE THREAD

**Issue by Hamouda55** [Ar1i/PokemonGo-Bot#2582]
![image](https://cloud.githubusercontent.com/assets/20893012/17557351/22c3aeee-5f17-11e6-9967-ff962a56895d.png)
Image says it all.

**Comment by tmkhanh** [comment]
Same, look like the code try to connect using Proxy when we didn't choose to use.

**Comment by Hamouda55** [comment]
well thats not nice i want to catch pokemons please somebody answer :'(

**Comment by tmkhanh** [comment]
@Hamouda55 use old version waiting for next release.

**Comment by Hamouda55** [comment]
@tmkhanh link please ?

**Comment by Major1337** [comment]
Same problem here ...

**Comment by xJustx** [comment]
Are you using a proxy?
