### ISSUE TITLE
ERROR Microsoft.NET framework last update 10.8.16.16.33 /10.08.16.33

### ISSUE THREAD

**Issue by ONOBARY** [Ar1i/PokemonGo-Bot#2583]
![desert](https://cloud.githubusercontent.com/assets/20884771/17557453/78d9ffa2-5f41-11e6-9416-459c99c6639c.jpg)
![desert](https://cloud.githubusercontent.com/assets/20884771/17558153/e1d73a36-5f43-11e6-88bd-7052f27808a1.jpg)

**Comment by Sho0t3r** [comment]
same

**Comment by 6gal6ler6** [comment]
Same Error

**Comment by ShujiYagami** [comment]
Same.

**Comment by hapoek** [comment]
same with me

**Comment by Ar1i** [comment]
uploading new

**Comment by ONOBARY** [comment]
im back to using Latest Build - 09.8.16 11.51 very stable no issue

**Comment by Ar1i** [comment]
Download newest Version

**Comment by ONOBARY** [comment]
THANKS @Ar1i  for amazing work

**Comment by xJustx** [comment]
^
