### ISSUE TITLE
Getting softbanned using ONE bot

### ISSUE THREAD

**Issue by dragobite** [Ar1i/PokemonGo-Bot#2584]
I`ve tried proxy and it worked for like 5 min. Changed my IP adress and used only one bot, it ran for an hour and now it got softbanned again

**Comment by Hydro420** [comment]
You're running the bot too fast or your opening up the application (via cellphone, or emulator) too far from your bots cords & too fast... Before running the bot you want to open the game via cell or emulator with fake cords on where the bot will start working from. Exit app, config cords in bot & your good to go.

**Comment by Ar1i** [comment]
^
