### ISSUE TITLE
Multiple catching patern

### ISSUE THREAD

**Issue by vahnz89** [Ar1i/PokemonGo-Bot#2586]
Maybe this could avoid a softban, just maybe 

How can i create multiple catching patern?
thanks for help

**Comment by Ar1i** [comment]
What? More information

**Comment by FGonzalezBon** [comment]
vahnz89 I believe what you want is to throw pokeballs until he finally take the pokémon or leave.

**Comment by vahnz89** [comment]
It just my wild imagination that maybe it will look suspicious if we always get exellent throw with curve
so maybe if we can make it more natural it will be safer (from softban), i guess
