### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by 6gal6ler6** [Ar1i/PokemonGo-Bot#2587]
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: P. Path 'infoline2', line 17, position 56.

**Comment by Ar1i** [comment]
Download newest please

**Comment by hapoek** [comment]
still error.. i use a new one
![capture](https://cloud.githubusercontent.com/assets/20836081/17557844/4be95204-5f4b-11e6-8f2b-f9f35094a551.PNG)

**Comment by Ar1i** [comment]
Fixed in newest build! :)
