### ISSUE TITLE
Files to Update to 1.032

### ISSUE THREAD

**Issue by lkaragjo** [Ar1i/PokemonGo-Bot#259]
I have version 1.0. When I open it it brings me here saying there is a new update. What files do I download or how do I update to this latest version? Anyone with any information greatly appreciated. I am computer novice :(

**Comment by MarvinSCR** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Build%201.7%20-%2029.07%2019.14.rar

**Comment by lkaragjo** [comment]
oh crap new version 1.7? I thought 1.032 was the new one.

**Comment by lkaragjo** [comment]
is there a link with recommended settings for max xp?

**Comment by KortakNL** [comment]
that link gives error 404.. page not found
