### ISSUE TITLE
Still Error .Net Framework 

### ISSUE THREAD

**Issue by hapoek** [Ar1i/PokemonGo-Bot#2592]
![capture](https://cloud.githubusercontent.com/assets/20836081/17558018/de723afa-5f4b-11e6-8cb6-c286da7e48ba.PNG)

**Comment by 6gal6ler6** [comment]
Same Error

**Comment by Hydro420** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=42643

**Comment by Ar1i** [comment]
uploading atm

**Comment by thomasfuk** [comment]
still not work

**Comment by cemaro1982** [comment]
![error](https://cloud.githubusercontent.com/assets/20951832/17558651/f43157ba-5ee0-11e6-9bdb-a5e050f81bf4.png)

**Comment by ken4896tan** [comment]
i facing 2 problem~
1)automatic use my lucky egg,even i m not tick that function~(both of them)
2)no function on auto uncubate
![untitled](https://cloud.githubusercontent.com/assets/20951973/17559003/227b06ca-5f4f-11e6-8cfb-1726117a3c2c.png)

**Comment by DatBoiiiii** [comment]
Hi I can't find any pokestop anywhere I put it on map
![screenshot_7](https://cloud.githubusercontent.com/assets/20952116/17559150/60ea2332-5f1d-11e6-9d39-651c733de772.png)

**Comment by ohgitu** [comment]
![ccd](https://cloud.githubusercontent.com/assets/20832883/17559183/718c280a-5f47-11e6-9ec0-c1c19526100d.jpg)

**Comment by Kaizhoul** [comment]
I have a question, it's possible to put 15 or 20 account with different ip and proxy

**Comment by xuban** [comment]
@ken4896tan Reopens the bot and see that it is selected. It does not matter if you copied the configuration folder, I happened to me the same.

**Comment by Sobro111** [comment]
Cant find any pokestop ub rabfe of 5000m! :S

**Comment by ken4896tan** [comment]
@xuban just saw it!!reopen will auto select auto use lucky egg=_=||

but houw about auto uncubate is it ok for u guys?its seem no function to me

**Comment by ken4896tan** [comment]
@Sobro111 ,restart your router first~
its work to me

**Comment by ohgitu** [comment]
now work sir, thanks for your work :)

**Comment by DatBoiiiii** [comment]
Can we do two bot with the same proxy?

**Comment by Shak4zoo** [comment]
![image](https://cloud.githubusercontent.com/assets/20952327/17559574/fa324c6c-5f1e-11e6-8666-088114ec2028.png)
of this problem or vien?

**Comment by xuban** [comment]
@Shak4zoo The pokestop is working in Spain. I think the problem is the server.
@ken4896tan reopen and see if autoincubate is marked... the same problem haha.

**Comment by Shak4zoo** [comment]
@xuban so I can not make use of bot ?

**Comment by xuban** [comment]
I dont know.
For me is working.
![bot](https://cloud.githubusercontent.com/assets/950547/17559834/e4de526a-5f1f-11e6-990b-1fd4e8c5e22d.jpg)

**Comment by Shak4zoo** [comment]
@xuban 
HOW YOU THE SET ?

**Comment by xuban** [comment]
I have the same settings of the other builds. I copy the "Config" folder from older to new version always.

**Comment by Shak4zoo** [comment]
@xuban How you its copy the Config folder ?

**Comment by ponduu** [comment]
This build Transfer My First Best Pokemon . (- - )'

**Comment by xuban** [comment]
Copy this folder to the new downloaded build @Shak4zoo 
![bot1](https://cloud.githubusercontent.com/assets/950547/17560102/10826932-5f21-11e6-8d02-0910907df56e.jpg)

**Comment by ohgitu** [comment]
now, not working again :(

**Comment by Shak4zoo** [comment]
@xuban I put the old config folder in the new ?

**Comment by xuban** [comment]
The config folder creates when u open the first time the bot. If u have now conf folder in the downloaded build, delete it.
After copy the folder and open the bot again, check LUCKY EGG settings because the bot has a bug (is checked by default.)

**Comment by frankiecws** [comment]
[23:49:43] We can't find any PokeStops in a range of 5000m!
[23:49:44] We can't find any PokeStops, which are unused! Probably the server are unstable, or you visted them all. Retrying..
[23:49:44] Walking back to default location.
[23:49:44] Distance to target location: 1.42 meters. Will take 0.64 seconds!
[23:49:47] Starting again in 10 seconds...

**Comment by xuban** [comment]
Please see the Pokemon Go servers.
There are several lagged. USA one of this.
http://www.mmoserverstatus.com/pokemon_go

**Comment by Shak4zoo** [comment]
@xuban I managed many good thank you capture ;)
