### ISSUE TITLE
Cant start the Bot (V1.0.8.8)

### ISSUE THREAD

**Issue by Experte9** [Ar1i/PokemonGo-Bot#2593]
![unbenannt](https://cloud.githubusercontent.com/assets/20842528/17558191/1959a720-5f1a-11e6-89bf-df8d3e295c5e.JPG)
 Title say all

**Comment by jodirt282** [comment]
Same issue.

**Comment by Ar1i** [comment]
download newest

**Comment by Experte9** [comment]
@Ar1i Its the newest. Version 1.0.8.8

**Comment by oklt** [comment]
same for me

**Comment by xxKevinSniperxx** [comment]
@Ar1i  the problem still proceeds in the new build

**Comment by xxKevinSniperxx** [comment]
Nvm i got it working

**Comment by ManoBM** [comment]
IP ban?

**Comment by Experte9** [comment]
lol, it work right now. Maybe server was on high ping xD 
(http://www.mmoserverstatus.com/pokemon_go)

**Comment by oklt** [comment]
still not for me
