### ISSUE TITLE
LastCoords.txt is in use by another process. 

### ISSUE THREAD

**Issue by jodirt282** [Ar1i/PokemonGo-Bot#2594]
10.08 16.40

![image](https://cloud.githubusercontent.com/assets/20918228/17558295/201db8e4-5ee8-11e6-9131-8d086111c912.png)

First time running bot from fresh folder.

**Comment by jodirt282** [comment]
10.08 16.49 ->
![image](https://cloud.githubusercontent.com/assets/20918228/17558420/8d1969ac-5ee8-11e6-9c05-7cb9f7f08ff5.png)

**Comment by Experte9** [comment]
just delete "LastCoords.txt" and start again.

**Comment by jodirt282** [comment]
Done that. Same error. Even rebooted PC and exported build to fresh folder. Always same error.

**Comment by xJustx** [comment]
Try to redownload the bot and set up him again please.

**Comment by bkrandy** [comment]
I had this error and deleting LastCoords.txt and rebooting worked for me.
