### ISSUE TITLE
Problem new version

### ISSUE THREAD

**Issue by Niveur** [Ar1i/PokemonGo-Bot#2595]
I install the zip file of the latest version but I can not find the executor

**Comment by NatyNaytor** [comment]
You unzipped the file in "builds only" directory? 
![immagine](https://cloud.githubusercontent.com/assets/20950971/17558606/792d3f76-5f1b-11e6-961b-7a74777a39ac.png)

**Comment by Niveur** [comment]
OMG thx you ;)

**Comment by Experte9** [comment]
pls close Issue if all works. thx
