### ISSUE TITLE
VPN issue with New updates.

### ISSUE THREAD

**Issue by xJihadx** [Ar1i/PokemonGo-Bot#2596]
So, I kept getting this error loading list, I tried everything to fix the issue.. I then turned off my VPN (that I used since first build) and it worked.

After the in app proxy update, I can no longer use my VPN to mask my ip??
![0ba196c4-5ede-11e6-8403-ed8e611e2d8c](https://cloud.githubusercontent.com/assets/20819213/17558526/e2b2d15a-5ee8-11e6-8437-5ef2ea4914a2.jpg)

**Comment by Experte9** [comment]
there are problems without VPN too #2593

**Comment by xJihadx** [comment]
#2593 looks like server lag, my issue is only when VPN is on.

**Comment by Experte9** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by xJustx** [comment]
^
