### ISSUE TITLE
Still getting banned with https proxy

### ISSUE THREAD

**Issue by Yummster** [Ar1i/PokemonGo-Bot#2598]
I am using the latest release. Started fine saying it was using the proxy, and started capturing and collecting. 3 minutes later the tell tale visits to posts but no collecting and no signs of seeing pokemon, a minute of that then soft banned.

If the proxy being used fails for whatever reason does it automatically revert back to the true ip as it caused the second bot running to soft ban as well.

**Comment by james741** [comment]
same

**Comment by Safti54** [comment]
same

**Comment by 6gal6ler6** [comment]
same

**Comment by sandilaice** [comment]
same with mee
![pokemon](https://cloud.githubusercontent.com/assets/20952010/17559052/ef24d48e-5f46-11e6-8996-5dd027426dab.jpg)

any solusition? or im doing wrong when start bot?

**Comment by jodirt282** [comment]
I also get no PokeStop, tried over 10 proxies. Nothing works.

**Comment by sandilaice** [comment]
maybe pokemon server is down?

**Comment by chusski** [comment]
same

**Comment by urangotango** [comment]
here the same thing... after 5 minutes using 2 different HTTPS proxy i take banns on on both accounts in the same momment... 
i did test it 10 times before comming in the forum and it is not pokemon server status relatet...

**Comment by bendeko** [comment]
same for me also

**Comment by jhepskie** [comment]
al of as getting that error got soft ban

**Comment by Spensky** [comment]
Running just one client w/o proxy or anything works fine as of 15 minutes into the game

**Comment by sandilaice** [comment]
any solusition?

**Comment by urangotango** [comment]
i keep tryng with some different HTTPS ports i let you know in 30 mins + - if it works 
now i have running 2 accs for 10 mins

**Comment by KnewNothing** [comment]
everyones using the same proxies resulting in double ip's

**Comment by PokeProgress** [comment]
If i start a new proxy while another acc is running can I essentailly run multiple accounts>

**Comment by sandilaice** [comment]
i stiil cant fix it, LOL. 

i try to open my account with nox, theres no pokestop too -__-

**Comment by captnbrick** [comment]
i figure we are all using the same proxy servers, resulting in ban?

**Comment by sandilaice** [comment]
i tried on another PC with different conection and its work

its mean ip banned?

**Comment by UserWest** [comment]
Tried running multiple instances with only one not proxied, all got ip banned including the not proxied one, meaning no one could have been sharing that particular connection. This leads me to believe that the proxy option is not functional for now.

**Comment by U2EZNeko** [comment]
Firewall, maybe?

**Comment by lifebeforeme** [comment]
same problem here, keep getting banned when i'm trying to run multiple instance at once with different proxies

**Comment by butcha** [comment]
I would say the proxy option is not working, since even if i put in wrong details it still goes on to connect.
It is most likely just using your local IP anyway.

**Comment by Eloick** [comment]
What abour ppl using the same https proxy?
Will it present same ip per proxy to niantic, so the proxy ip is banned?

**Comment by Eloick** [comment]
Did you try to run a bot locally and one with proxy?

**Comment by KaV0** [comment]
please do not implement (remove) the proxy function.
for what people need 5 million pokemon accounts do be bottet?
be happy with one working, or are you freaks, that evaluate your worth of live with the amount of pokemon bots u have on lvl 40?
the function will just be abused by sites, saying, give us 15$ per day, we boost your pokemon account.. blabla.

**Comment by butcha** [comment]
I would say the proxy option is not working, since even if i put in wrong details it still goes on to connect.
It is most likely just using your local IP anyway.

I host my own HTTPS proxy on a remote server, it works fine for use in my browser etc, but the bot never even connects to it.

**Comment by xJustx** [comment]
It is possible that other guys are using your proxy too.

**Comment by UserWest** [comment]
In my case, it's not very likely that the bot i was running without a proxy happened to get banned at the same time as the ones I was running with proxy. I live alone and no one else has access to my connection as it is not wireless, there is no chance that a bot was running on my ip without my knowledge.
