### ISSUE TITLE
Releasing Pokemon

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#2599]
when i started the bot begin to release pokemon but i see this, maybe is a bug

![image](https://cloud.githubusercontent.com/assets/1984839/17559076/7209d8e6-5ee2-11e6-9876-f5450389caf2.png)

release the hight pokemon too ??

**Comment by ManoBM** [comment]
u use Transfer Frst Low IV?

**Comment by kazzaluis** [comment]
yes  

![image](https://cloud.githubusercontent.com/assets/1984839/17559194/e9930c98-5ee2-11e6-8846-4f133397b6d7.png)

**Comment by kazzaluis** [comment]
now i have a haunter with 35 ivs and my 90 ivs go away

**Comment by kazzaluis** [comment]
do i must uncheck the firstlowiv ??

**Comment by Streakz** [comment]
same here, i lost my very best slowpoke and magikarp :(

**Comment by butcha** [comment]
I got the same thing.. Transfered a lot of my best Pokémon :/

**Comment by kazzaluis** [comment]
fix it please :(

**Comment by BeeeMadre** [comment]
That Transfer Frst Low IV is bugged, it just transfered mrmime with higher CP and IV.
![untitled](https://cloud.githubusercontent.com/assets/20711092/17559421/e15cb29c-5f26-11e6-8e3a-781efb21250b.png)

**Comment by rochadl** [comment]
can u make the transfer calculation like this ?
1. compare level pokemon x, remove highest level pokemon x from transfer list(we call this temporary list transfer pokemon x)
2. compare CP pokemon x on the temporary list, remove highest cp pokemon x from transfer list(we call this temporary list transfer pokemon x)
3. compare IV pokemon x on the temporary list, the lowest IV was the one will be transfer (only lowest lvl pokemon with lowest CP n lowest IV will be transfer)
