### ISSUE TITLE
[Bug] Walk Radius causes Login Loop - LuckyEgg auto usage

### ISSUE THREAD

**Issue by ilhamazdi** [Ar1i/PokemonGo-Bot#26]
* Walk radius causes login loop

I've set my walk radius to 100m, so It stay on lured pokestops area. Then as the screenshoot below, bot keeps relogging and sometimes restarting as it can't search for unused pokestop.

![capture](https://cloud.githubusercontent.com/assets/7246466/17085455/b740a9ae-5202-11e6-8e1e-b038f25786d1.JPG)

* Telegram top pokemon

When I'm using /top command in telegram with big number (example : 250) the bot crashing. I think you should define the max number of /top command. I know this is somewhat dumb if you try /top command like that, but, yeah... :sweat_smile:

**Comment by Ar1i** [comment]
Should be fixed..

**Comment by ilhamazdi** [comment]
- [x] Telegram /top Command bug resolved
- [ ] Login loop still occuring when there are no unused pokestop
- [ ] Please add an option whether we want to auto-use LuckyEgg
- [ ] Bot keep using LuckyEgg even if the last use of LuckEgg buff still active

See screenshot below for more detail

![capture](https://cloud.githubusercontent.com/assets/7246466/17108462/da364264-52bd-11e6-9755-e20a3090e679.JPG)
