### ISSUE TITLE
No Pokestops

### ISSUE THREAD

**Issue by oklt** [Ar1i/PokemonGo-Bot#2600]
the bot is still not working for me no pokestops (i got already the newest version)
![not working](https://cloud.githubusercontent.com/assets/20951766/17559119/43f164b6-5f1d-11e6-889f-880f3ba7915b.JPG)

**Comment by eNNj0y** [comment]
the same problem here

**Comment by 6gal6ler6** [comment]
same here...

**Comment by xxKevinSniperxx** [comment]
same here.

**Comment by LordBunny** [comment]
same

**Comment by jhepskie** [comment]
probably softban i have same problem

**Comment by oklt** [comment]
fixed

**Comment by oklt** [comment]
re installed the bot
