### ISSUE TITLE
caught new? error?

### ISSUE THREAD

**Issue by aulterra** [Ar1i/PokemonGo-Bot#2601]
http://image.prntscr.com/image/d241a737aa854b11ae03a05bf928656c.png

Is this cause for concern?

**Comment by kazzaluis** [comment]
is not an error

**Comment by aulterra** [comment]
@kazzaluis  What is it? Never seen it before. I've already caught psyducks before ....

**Comment by kazzaluis** [comment]
yes but is a new Psyduck in the pokemon bag i guess

**Comment by aulterra** [comment]
but @kazzaluis why would it say new psyduck when i've got psyducks already and it doesn't say new for any others, it said new magikarp before too but I have heaps of them

**Comment by kazzaluis** [comment]
well is bugged

**Comment by xJustx** [comment]
@aulterra please post a new issue. I can't see anything..
