### ISSUE TITLE
Keine Pokestops ??

### ISSUE THREAD

**Issue by eNNj0y** [Ar1i/PokemonGo-Bot#2602]
![unbenannt](https://cloud.githubusercontent.com/assets/20887831/17559168/7165ffe2-5f1d-11e6-832f-db69d1128a22.jpg)

Wo liegt das Problem ?

**Comment by xJustx** [comment]
Versuche mal deine IP zu wechseln.

**Comment by dragonuts330** [comment]
Been this way all day for me regardless of settings/proxy.

**Comment by teejvyx** [comment]
i have this exact problem.. anyone know how to fix?

**Comment by MythosOfGaming** [comment]
http://www.mediafire.com/download/3baivu124pq8d28/iprenew.exe


Falls ihr ne neue IP braucht

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
