### ISSUE TITLE
Can't run more than 2 bots? (with different https proxies)

### ISSUE THREAD

**Issue by starscream151** [Ar1i/PokemonGo-Bot#2603]
It's working when I only run 2 bots (with 2 different https proxies),
but when I'm running the 3rd one...
All the bots getting banned

![aaaaaaaaaaaaauntitled](https://cloud.githubusercontent.com/assets/20950801/17559164/57ced1c4-5f47-11e6-88b1-aff54cea3dda.png)

**Comment by Damantium** [comment]
everyone already knows this it's due to MAC address I guess. Moral of the story only use one bot

**Comment by MrKush420** [comment]
hey what proxy do you use and how do i use it i got a vpn hotspot shield
