### ISSUE TITLE
Ignore not working???

### ISSUE THREAD

**Issue by Jinnocid** [Ar1i/PokemonGo-Bot#2604]
![image](https://cloud.githubusercontent.com/assets/20916720/17559295/592482ae-5f50-11e6-8ccc-d13cd2e9cc5e.png)

![image](https://cloud.githubusercontent.com/assets/20916720/17559316/6e27cea4-5f50-11e6-84d6-46a9eb5a4f75.png)

**Comment by Hydro420** [comment]
Sorry for this comment... But where the heck did you get the Farfetchd!!!? :-D I want one so bad

**Comment by Jinnocid** [comment]
santa monica pier

**Comment by tylerkc1130** [comment]
hong kong Tsim Sha Tsui

**Comment by bendeko** [comment]
hong kong

**Comment by Jinnocid** [comment]
so anyone can help me active the ignoring of pokemon?
