### ISSUE TITLE
cant catch pokemon right now

### ISSUE THREAD

**Issue by tylerkc1130** [Ar1i/PokemonGo-Bot#2605]
i cant catch pokemon after updated latest version

############# Check-list. read before posting! #############
I SEARCHED MY PROBLEM IN THE ISSUES

MY ISSUE DIDNT GET ANSWERD PREVIOUSLY

MY ISSUE IS AN ISSUE AND NOT A QUESTION/SUGGESTION

I USE THE NEWEST VERSION
#####################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Post.

**Comment by LPschenkel** [comment]
same problem

![unbenannt](https://cloud.githubusercontent.com/assets/20952282/17559541/e27bb7de-5f1e-11e6-82b1-14095b7f34ac.PNG)

**Comment by tylerkc1130** [comment]
this is my problem.

**Comment by tylerkc1130** [comment]
this is my problem.
![3](https://cloud.githubusercontent.com/assets/20952250/17559631/82530460-5f51-11e6-8908-b9486ee83a63.png)

**Comment by tylerkc1130** [comment]
problem solved, thanks

**Comment by LPschenkel** [comment]
how?
