### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by rochadl** [Ar1i/PokemonGo-Bot#2606]
############# Check-list. read before posting! #############
I SEARCHED MY PROBLEM IN THE ISSUES

MY ISSUE DIDNT GET ANSWERD PREVIOUSLY

MY ISSUE IS AN ISSUE AND NOT A QUESTION/SUGGESTION

I USE THE NEWEST VERSION
##################################################
@Ar1i 
first of all i want to thank you for your great work, this was really help me
after i use the newest update, i found something critical, it about transfer calculation
more than once it keep transfer my highest cp pokemon n keep lowest cp pokemon

below was copy from the log
[21:58:08] Caught New Poliwag CP 30 IV 43% using ItemPokeBall got 420 XP.
...
[21:58:50] Transfer Poliwag CP 443 IV 54% (Best: 462 CP, IV 54%)

something i ask my self "why it keep pokemon with lowest cp n transfer pokemon with highest iv n cp?"

high CP = high level pokemon
high IV = high value pokemon on that level

can u make the transfer calculation like this ?
1. compare level pokemon x, remove highest level pokemon x from transfer list(we call this temporary list transfer pokemon x)
2. compare CP pokemon x on the temporary list, remove highest cp pokemon x from transfer list(we call this temporary list transfer pokemon x)
3. compare IV pokemon x on the temporary list, the lowest IV was the one will be transfer

sorry if my explanation was bad

**Comment by kazzaluis** [comment]
#2599  chek this

**Comment by rochadl** [comment]
@Ar1i 
another consideration for formula transfer

example if pokemon more than 2
Pokemon CP      IV                         LVL    comparation (CP/LVL)
Bulbasur  635    7.68%  0-1-3         26     24.42
Bulbasur  625    31.82%  0-2-15     24     26.04
Bulbasur  64      11.10%  0-5-2       3       21.33

conclusion transfer the lowest comparation Bulbasur


example if pokemon only 2
Pokemon CP        IV                         LVL  comparation (CP/LVL)
fearow     1100    76.38% 13-12-9   23     47.83
fearow     909      76.53%  12-15-8  19     47.84

add more formula for this case (only 2 pokemon compare)

if "CP of highest comparation" < "CP of lowest comparation then
    if "LVL of lowest comparation - LVL of highest comparation" < 2 then 
       "conclusion transfer the lowest comparation Ferrow"
    else
       "conclusion transfer the highest comparation Ferrow"
    endif
else ("CP of highest comparation" >= "CP of lowest comparation)
    "conclusion transfer the lowest comparation Ferrow"
endif
