### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by DangerousHIV** [Ar1i/PokemonGo-Bot#2607]
I have an error like 5 min of running no pokestops 5000 meters and it wokred perfectly fine minute ago with new update any ideas on solution

**Comment by kazzaluis** [comment]
use Hotspotshield and don't  open more than 1 bot please

**Comment by DangerousHIV** [comment]
you cant use more than one bot ok... i was before and whats hotspotshield

**Comment by DangerousHIV** [comment]
and how do i do this via windows 10

**Comment by DangerousHIV** [comment]
hey @kazzaluis i got that and turned it on it did all sorts of erros now that i cant explain soon as i took of hotspot shield it took away those errors and put cant find poke stops 5000 meters
