### ISSUE TITLE
Used Lucky Egg, even I Uncheck both option

### ISSUE THREAD

**Issue by martinjamesl** [Ar1i/PokemonGo-Bot#2608]
############# Check-list. read before posting! #############
I SEARCHED MY PROBLEM IN THE ISSUES

MY ISSUE DIDNT GET ANSWERD PREVIOUSLY

MY ISSUE IS AN ISSUE AND NOT A QUESTION/SUGGESTION

I USE THE NEWEST VERSION
#####################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Post.

**Comment by kazzaluis** [comment]
do this things before make a post

Describe your problem!

Add a screenshot!

Choose a good title!

Post.
