### ISSUE TITLE
Transfers best Pokémon

### ISSUE THREAD

**Issue by setoy** [Ar1i/PokemonGo-Bot#2610]
My problem is easily describable by this screenshot :D
![image](https://cloud.githubusercontent.com/assets/6497266/17559727/8aa1af54-5f1f-11e6-9e40-3455e4d47e87.png)

I've got "keep 1 duplicate" set in my settings.

**Comment by kazzaluis** [comment]
#2599

**Comment by testo4life** [comment]
its not saving changes on option transferlowivfirst so u have to uncheck that option every time u restart

**Comment by rochadl** [comment]
#2606

**Comment by setoy** [comment]
Alright, thanks. My bad. :)
