### ISSUE TITLE
We can't find any PokeStops in a range of 5000m! (German)

### ISSUE THREAD

**Issue by exxDGroup** [Ar1i/PokemonGo-Bot#2612]
ist der Fehler bekannt und gibt es dafür eine Lösung?
Liegt das am Server oder mache ich was falsch? 

Ich habe soweit alles getestet, bekomme keine Fehler nichts. Hat auch über Nacht funktioniert ohne probleme. 

![unbenannt](https://cloud.githubusercontent.com/assets/20952251/17559688/70dbb9e8-5f1f-11e6-95b6-1b3c17f00583.jpg)

**Comment by oklt** [comment]
hab den bot neu installiert und dann ging es wieder bei mir also kommplett neu gezogen

**Comment by kazzaluis** [comment]
Use Hotspotshield

**Comment by eNNj0y** [comment]
habe die neuste Version & den gleichen Fehler..
Gerade nochmal neu installiert & es geht nicht

**Comment by exxDGroup** [comment]
Als Info 

Jetzt gehts ohne das ich was gemacht habe.

![unbenannt](https://cloud.githubusercontent.com/assets/20952251/17560147/3d2d60b8-5f21-11e6-870c-2bc5a2147d2e.jpg)

**Comment by NaveTK** [comment]
das passiert wenn deine ip gesoftbannt wird... wenn du mehrere bots gleichzeitig laufen lässt und/oder sich jemand vom handy aus einloggt kann das mal passieren

**Comment by xuban** [comment]
http://www.mmoserverstatus.com/pokemon_go
See the servers status.

**Comment by xGuardianx** [comment]
@kazzaluis    "Use Hotspotshield"

Was meinst du damit?

**Comment by crazyoskar** [comment]
How to fix ? Tell me in english pls

**Comment by frankiecws** [comment]
I also want to know how to fix
Pls

**Comment by xJustx** [comment]
^

**Comment by exxDGroup** [comment]
I dont real fix it... Iam just waiting a while and stop play whit 2 bots in same time. Think my IP was get an Softban. 
Hope u understand my stupid english xD
