### ISSUE TITLE
ALL POKEMONS IS GOT AWAY ! how to fix ???

### ISSUE THREAD

**Issue by pitacho15** [Ar1i/PokemonGo-Bot#2616]
![333333333](https://cloud.githubusercontent.com/assets/20948565/17560051/7cf64510-5f18-11e6-925f-11c7b0ed7430.png)

**Comment by LPschenkel** [comment]
same problem

**Comment by kazzaluis** [comment]
maybe juts bad luck bro

**Comment by testo4life** [comment]
no softban doesnt work anymore properly ! same issue noticed !

**Comment by jmo93** [comment]
Restart router and restart Computer

**Comment by Enzoklopaedie** [comment]
same

**Comment by ripharambe** [comment]
just let it do his job, bot will fix it ;)

**Comment by pitacho15** [comment]
Dont work Restart router and restart Computer this erro is from the bot

**Comment by pitacho15** [comment]
other bots work perfect

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17560508/f84e2ae4-5f3f-11e6-8f8a-8a2a1861e234.png)

**Comment by PokePro21** [comment]
because of 0 pokeballs

**Comment by Ar1i** [comment]
Dont set it to zero balls, but currently i am fixing

**Comment by pitacho15** [comment]
Work, ty <3

**Comment by PokePro21** [comment]
@Ar1i please read #2564

**Comment by fenlyn** [comment]
poke list...FORCE UNBAN Close pokelist done.

**Comment by Ar1i** [comment]
Working on it, so you can set it to 0

**Comment by Ar1i** [comment]
if you use the source, it will work. build will be updated later
