### ISSUE TITLE
Invalid Player Item count, pokestop inventory full

### ISSUE THREAD

**Issue by dullahx** [Ar1i/PokemonGo-Bot#2618]
Hello,

I am getting this error since a few builds, i've seen similar issues closed without real explanation, but my problem is still here.

My real item number is over 350/350, but the bot shows less than this (270 ish)

here's the log : 
[17:44:36] Level/EXP:*************
[17:44:36] PokeStops visited: ******KM Walked: ********
[17:44:37] Pokemon: 126 + 9 Eggs /250 (0 Evolvable)
[17:44:37] Pokedex Completion: 72/150 48%
**[17:44:38] Items: 270/350 Stardust: xxxxxxx**
[17:44:41] Next Pokestop: ************ in 65,67m distance.
[17:44:41] Distance to target location: 65,67 meters. Will take 4,73 seconds!
[17:44:43] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
**[17:44:47] Farmed XP: 100, Items: Nothing (Inventory Full?)**

Thanks for your help, and sorry if i missed an explanation.

**Comment by kazzaluis** [comment]
maybe when you visit a pokestop some times the game say "Try again later " or some that in english

**Comment by dullahx** [comment]
No, the problem is about reporting an invalid player item count.
Read my post.

**Comment by Ar1i** [comment]
Already reported, its cause the inventory isnt getting updated everytime.. else niantic would block our connections tho.

**Comment by Damantium** [comment]
@Ar1i I face a similar problem, I have 450 inventory space but as soon as I get 350 items the bot tells me its full

**Comment by dullahx** [comment]
@Ar1i 
Thanks for your answer, i might have missed it.
For me, that behavour is going on since the new API update/reverse.
!is there a way to reset or correct that item count ? it is causing alot of issues, mostly regarding pokemon catching.

**Comment by gummyruler** [comment]
I have a 400 bag and it's not having any error.

**Comment by dullahx** [comment]
still having the problem after last build update. :(
