### ISSUE TITLE
Not evolve=not transfer their duplicate BUG

### ISSUE THREAD

**Issue by Niubbo** [Ar1i/PokemonGo-Bot#2620]
usually i set some kind of pokemon to not be auto evolved, these kind of pokemon even if match the autotransfer option doesn't are transfered and i have to do it manually

**Comment by kazzaluis** [comment]
did you update ?¡?

**Comment by PokePro21** [comment]
@Ar1i  Please read #2564

**Comment by Niubbo** [comment]
i have the last update

**Comment by Ar1i** [comment]
should be fixed
