### ISSUE TITLE
Was tun bei 2 Bots? 

### ISSUE THREAD

**Issue by brumbumbum** [Ar1i/PokemonGo-Bot#2621]
hallo Ar1i,

du hast ja mitbekommen, dass wir die ganze Zeit einen softban oder IP ban bekommen. jetzt geht das boten mit einem account wieder aber sobald ich den 2ten dazu schalten möchte, bekommt der erste einen Ban. kannst du mir da bitte weiterhelfen und mir sagen wie es möglich ist, beide gleichzeitig boten zu lassen? 

danke

**Comment by neocrypton** [comment]
stell deine fragen auf englisch wie viele andere deutsche auch, dann wird dir eher geholfen.... nicht jeder hier spricht deutsch

**Comment by xRealMaks** [comment]
This is only for issues. Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by brumbumbum** [comment]
That doesnt help me! can u please answer my Question! Why cannot i not use 2 bot at the same Time and how can i fix that Problem ?!
