### ISSUE TITLE
Latest Build - 10.08 17.51.rar Transfer Pokemon still bug

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#2622]
![image](https://cloud.githubusercontent.com/assets/1984839/17561201/a06111f2-5eea-11e6-8d6c-3633eab80b89.png)

**Comment by dreamboatcap** [comment]
I have this bug too. It happens when i check the choice "TransferFirstLowIV"

**Comment by kazzaluis** [comment]
@Ar1i  this is in the last update

**Comment by Ar1i** [comment]
you sure your pokemon list is up2date?

**Comment by dreamboatcap** [comment]
@Ar1i come here and see the problem https://github.com/Ar1i/PokemonGo-Bot/issues/2633

**Comment by Ar1i** [comment]
found the error, its cause of cached pokemon list.. doing a simple trick to get it updated.

follow this thread here #2633

**Comment by kazzaluis** [comment]
ty @Ar1i

**Comment by PokePro21** [comment]
@Ar1i thus this get fixed?
