### ISSUE TITLE
unable to load encrypt.dll

### ISSUE THREAD

**Issue by hahacarter** [Ar1i/PokemonGo-Bot#2625]
couldnt find the encrypt.dll file anywhere to place into folder at top of list for load order. It is in the archive of the Builds but it never extracts even manually.

![untitled](https://cloud.githubusercontent.com/assets/20953106/17561281/2c0fdd20-5eda-11e6-91d5-c7a65d48d0fd.png)

**Comment by dcg121288** [comment]
Download again: 
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2010.08%2017.51.rar
and replace

**Comment by Ar1i** [comment]
^
