### ISSUE TITLE
WHAT'S THIS? "Caught New "...." got 310 XP.

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#2627]
![screenshot_12](https://cloud.githubusercontent.com/assets/20727615/17561361/e0285abc-5f25-11e6-852f-622c6b9346d2.png)

I mean, why is it read like if it was something important, I already caught magikarp in the past so i dont see how i'm receiving more exp, or why is it "New"

**Comment by PokeProgress** [comment]
its not you have a lucky egg running and threw a great ball

**Comment by akangnduz** [comment]
same here no lucky egg running
![screenshot_1](https://cloud.githubusercontent.com/assets/20890824/17561547/cc0e9a70-5f50-11e6-9023-7c120cf1049c.png)

**Comment by gnzl0o** [comment]
i do not have a lucky egg, can somebody explain @Ar1i ?

i just want to know what is it

**Comment by Ar1i** [comment]
New means just, its the first time you catched the pokemon.. nothing more

**Comment by Ar1i** [comment]
Or you enabled lucky egg... that can happen the issue too..

**Comment by gnzl0o** [comment]
i already had magikarp in my pokedex, lucky egg was not running, im lvl 33, how can magikarp be "New".

seems not to matter so i'll just ignore the "issue" @Ar1i  

Thnks
