### ISSUE TITLE
[GER]POKESTOPS

### ISSUE THREAD

**Issue by Kamylicious** [Ar1i/PokemonGo-Bot#2628]
Findet immernoch keine Pokestops.... jemand ne Lösung?

**Comment by brumbumbum** [comment]
Hast du schon einen Router Neustart gemacht? Den neusten Bot runterladen? Und lässt du blos 1 Account laufen? Dann müsste es gehen

**Comment by OfficialMorise** [comment]
Die Server sind zurzeit auch sehr unstabil, einfach mal abwarten. :)

**Comment by Kamylicious** [comment]
Also eben ging es mit dem Proxy server aber dann hat er keine pokemons gefangen hab den neusten cleitn ca 22 min ago gedownloadet :) und ja nur 1 acc

**Comment by Ar1i** [comment]
proxy usen welcher nicht öffentlich ist, oder einfach mal router neustarten
