### ISSUE TITLE
2 Requests

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#263]
Add a location based on actual pokemon spawning (http://pkmngotrading.com/wiki/Nests this may help)
Add a 'Evee evolution picker' so the bot evolves evee's to whatever you want.

**Comment by baeckstrom** [comment]
@plowzey For the second request, do you refering to renaming the Eevee before evolving it into chosen pokemon?

**Comment by plowzey** [comment]
Yes exactly that @baeckstrom

**Comment by 13XxM1CHA3lxX37** [comment]
The names are 

Sparky -> Jolteon/Blitza
Pyro -> Flareon/Flamara
Rainer -> Vaporeon/Aquana

btw
