### ISSUE TITLE
Bot fails to catch pokemon

### ISSUE THREAD

**Issue by Pokemonstal** [Ar1i/PokemonGo-Bot#2630]
The Bot successful catching rate is pretty low for me. 7 out of 10 were got away! Why is it like this? I have 70+ pokeball in bag. Dont think i was banned as i still able to capture few of them.

<img width="392" alt="capture" src="https://cloud.githubusercontent.com/assets/20953294/17561570/42b5f31e-5f59-11e6-8afb-ecadd8406d9b.PNG">

**Comment by Ar1i** [comment]
softban probably or you set the pokeballs to 0
