### ISSUE TITLE
Happened again "Can't find pokestop"

### ISSUE THREAD

**Issue by mytically** [Ar1i/PokemonGo-Bot#2631]
![image](https://cloud.githubusercontent.com/assets/20953335/17561538/b8d38cae-5f50-11e6-9303-f7bff2b545d4.png)

hour ago, my bot was running smoothly and then I played it on my android device. I couldn't farm pokestop and battle in gym. Now, I tried to run the bot again but it says can't find pokestop.

please help

**Comment by Anonymous131** [comment]
my bot just cant find pokestop and i have done nothing to the accounts, I didnt even log in ^^

**Comment by fenlyn** [comment]
set ur proxy..

**Comment by Bangden** [comment]
Banned IP

**Comment by Kenjizje** [comment]
@Bangden  what is set proxy can u explain me?

**Comment by Bangden** [comment]
http://www.freeproxylists.net/ 

choose proxy with support HTTPS or port 3128/8080

**Comment by ricopratama303** [comment]
bannded account!!

**Comment by mytically** [comment]
@Bangden but how about the problem with the app? It is useless if at the end I can't play it to battle at gym

@ricopratama303 ciyus gan? trus gimana ya? bikin account baru? tadi saya juga coba pake akun baru, sama aja sih -,-

**Comment by Anonymous131** [comment]
Even with proxy it doesn´t work for me atm.

**Comment by Zixey13** [comment]
same here.

**Comment by ricopratama303** [comment]
haha, ga kayaknya gan. tunggu aja new build.

**Comment by adriendillens** [comment]
1 - Reboot your box (you get new IP)
2 - Download the last build of PokemonGo-Bot and extract it
3 - Go to : http://proxylist.hidemyass.com/
      search for HTTPS only proxies -> IMPORTANT
      AND 
      take a proxy corresponding to your botting location -> IMPORTANT 
4 - Go to Proxy settings in PokemonGo-Bot
      Put the ip from a proxy and the port
5 - Set your botting location corresponding to your proxy country
6 - Start ;-)

**Comment by Bangden** [comment]
@mytically Better not start a battle in the gym when you do not reach the target level by using bots.
Itu ip agan yang kena banned bukan akun.

**Comment by Anonymous131** [comment]
did exactly this W7O hide my ass with another site..

the bot is dead.

**Comment by fenlyn** [comment]
@Ar1i take a look this

**Comment by adriendillens** [comment]
@Anonymous131 I had the same problem, and i follow all the steps, it works now.
I think HTTPS proxy and (location proxy = botting location) are very important

**Comment by jenso0** [comment]
every proxy i want to use is enabel....

**Comment by fenlyn** [comment]
try bot in another country..like japan ahahaah^^

**Comment by rikudomatsuyama** [comment]
@ricopratama303 @Bangden @mytically ane pakek proxy lanjay lagi gan, sebelumnya kena banned IP juga wkakwak

**Comment by Xysas** [comment]
When you get ip ban you get perma ban? !

**Comment by adriendillens** [comment]
@Xysas No. No perma ban known atm. Just softban

**Comment by PokeProgress** [comment]
I changed my proxy to New york and thats where the location is and still got the 5000km message. Also i get an update prompt event hough I have updated

**Comment by MiGaBelG** [comment]
http://prntscr.com/c41cva
got myself a proxy and still nothing

**Comment by mytically** [comment]
jiahh gak work nih gan. cemana ya. udah ganti2 proxy, ganti2 negara -,-

hadeuh hadeuh -,-

proxy thing is just not working for me. any other solution?

**Comment by Xysas** [comment]
And  when you get  ip ban  like i did  in my 3 acc  in 4 mins   what should  i do in order to unban cause this is not sofban!
@PokeProgress

**Comment by rikudomatsuyama** [comment]
how if I run 2 bot at the same time, but using proxy. it is safe?

**Comment by rikudomatsuyama** [comment]
Reset dlu modem gan @mytically

**Comment by mytically** [comment]
@rikudomatsuyama tetep gak bisa hadeuh...

**Comment by Xysas** [comment]
Can anyone tell me how can i unipban my acc?

**Comment by Zixey13** [comment]
i follow all the steps, but here still doesn't work

**Comment by Bangden** [comment]
@mytically ikutin step2 ini gan

1. hapus folder bot
2. restart laptop
3. restart modem
4. download bot versi terbaru
5. ekstrak file bot seperti biasanya
6. setting bot sesuai dengan settingan agan
7. jangan lupa setting proxy. _(Proxy lebih baik cocokan dengan negara yang akan kita buat farming)_
8. jangan start bot dulu, tunggu kurang lebih 20 menit atau lebih.
9. Berdoa terlebih dahulu
10. start bot

Nb: Lain kali kalo login dari hp jangan langsung di buat bot gan.

**Comment by mytically** [comment]
haha you are right, my IP is banned. I am using connection from my phone and set the proxy, and it's working. I can sleep now.

btw, do you have solution to my another problem? I can't farm and battle from app while I am not botting.

**Comment by mytically** [comment]
one more, if my IP get banned, I wont be able to play pokemon from the IP? is it right? is there anything to unban the IP?

**Comment by Bangden** [comment]
nothing, u can't save our IP is already banned

**Comment by Zixey13** [comment]
with phone can you log in to the game? cause i can, but the bot doesn't work

**Comment by mytically** [comment]
@Bangden dafuk? seriously? mati lah awak

@Zixey13 yes, I can login to the game with my phone but if I use my home wifi, it shows no pokestops and gym, but if I use my cell network, I can see pokestops and gym, but I can't catch any pokemon (it will run away), I can't farm, and I can't battle at the gym.

lets play fair lah. no more bot hahaha

**Comment by rikudomatsuyama** [comment]
Tanya dong om @Bangden . bukannya klo mifi tiap reset itu ganti lagi IP ya?

**Comment by Bangden** [comment]
@mytically : 1 option, please hack database server pokemon go ^^v
@rikudomatsuyama : Tergantung dari provider tersebut, menggunakan IP dinamis atau statis, tetapi kebanyakan provider indo menggunakan ip dinamis.

**Comment by rikudomatsuyama** [comment]
woghh gitu, trus cara kita tau providerny pakek IP dinamis/statis bijimana om? btw ane pakek mifi idiotfren yg 4G @Bangden

**Comment by Bangden** [comment]
@rikudomatsuyama caranya mudah, cukup restart modem. Namun sebelum restart modem catat dulu IP agan. Bisa dilihat di sini http://www.myipaddress.com/. Setelah modem menyala cek kembali di halaman situs tersebut. Apakah berubah atau tidak. Jika berubah suda pasti IP agan dinamis. ^^v

**Comment by rikudomatsuyama** [comment]
woghh woke om makasih pencerahannya hehe @Bangden

**Comment by Midnlght** [comment]
worked you are a life saver @adriendillens

**Comment by adriendillens** [comment]
@Midnlght  you're welcome ;-)

**Comment by CakiL182** [comment]
@Bangden makasih infonya bangden

**Comment by Bangden** [comment]
@rikudomatsuyama : Sip, sama2 :+1: 
@CakiL182: semoga masalahnya terselesaikan! :)

**Comment by xCrezYxBoYx** [comment]
Kann mir hier jemand auf deutsch erklären was und wie dieses Proxy geht? Danke im voraus mein Englisch Kenntnisse sind 0 tut mir leid ...

**Comment by xRealMaks** [comment]
servers slow/down atm. just wait

**Comment by jerFXD** [comment]
Had the same issue a while ago and I just did reset my modem and bot is now working fine again.
