### ISSUE TITLE
Recommended botting Settings, Locations...

### ISSUE THREAD

**Issue by neocrypton** [Ar1i/PokemonGo-Bot#2632]
actually i use the bot 2 times, one with my account and the second from my girlfriend...
with my acc iam in Central Park, New York, walking speed 10km/h in a range between 1500 and 2500meters
with the account from my girlfriend i am in Germany same walking speed and range

i'll try to look the botting so real as possible... but in some screen i see botting in range of 50k EXP/h

have you favorite locations like central park? existing pokemon nest for Charmander, Squirtle and Bulbasaur???

**Comment by Bangden** [comment]
https://skiplagged.com/catch-that/
