### ISSUE TITLE
bot transfert best pokemon...

### ISSUE THREAD

**Issue by alexis01120** [Ar1i/PokemonGo-Bot#2633]
hey, the bot transfert the best pokemon when he catch a new pokemon, for exemple i have a magicarp at 177pc and when i caugth a magicarp at 165pc the bot transfert the magicarp at 177pc! can you help me?

**Comment by Anonymous131** [comment]
better IV won i guess. my bot didnt work since 1 hour

**Comment by alexis01120** [comment]
i select transfer low first but don't work

**Comment by ManoBM** [comment]
u select transfer frst low IV?

**Comment by neocrypton** [comment]
pokemon who absolutely not transfered I mark manually as favorite


but maybe it would a good function if i can marc / demarcate pokemon as favorit in the Pokemon list of the bot

**Comment by rickepk** [comment]
same here. Pls back to max cp dont transfer and verify IV

**Comment by ManoBM** [comment]
u can select what u want transfer low Cp or IV

**Comment by Eloick** [comment]
Same here, IV is properly setup, but transfer is made on CP only

**Comment by rickepk** [comment]
dont select to transfer low IV... and bot text show to transfer the lowest but transfer the max.

**Comment by Ar1i** [comment]
So the bot transfers atm the best iv instead of the lowest iv? right?

**Comment by dragon2011** [comment]
yes transfer low iv first is broken and active even if you swith it off, i am using old version now because you will lose all your high cp pokemon because it will always keep higher iv

**Comment by dragon2011** [comment]
no the bot keeps high iv, bot transfers high cp, cant switch it of in config

**Comment by Souluzumaki** [comment]
i switched it off and its keeping the highest cp

**Comment by dragon2011** [comment]
i switched off aswell but it still transfers high cp and it keeps high iv

**Comment by fraguvaz** [comment]
Hi, I have the same problem.
![sin titulo](https://cloud.githubusercontent.com/assets/20953708/17562259/5406ed0a-5f2a-11e6-83f9-757c030dae33.png)

**Comment by nekudah** [comment]
All of you turn OFF !TRANSFER IV" !!!! At Pokemon Tab

**Comment by kazzaluis** [comment]
> rochadl commented an hour ago • edited
@Ar1i 
can u make the transfer calculation like this ?
1. compare level pokemon x, remove highest level pokemon x from transfer list(we call this temporary list transfer pokemon x)
2. compare CP pokemon x on the temporary list, remove highest cp pokemon x from transfer list(we call this temporary list transfer pokemon x)
3. compare IV pokemon x on the temporary list, the lowest IV was the one will be transfer (only lowest lvl pokemon with lowest CP n lowest IV will be transfer)

**Comment by dragon2011** [comment]
@nekudah IT IS TURNED OFF but it still transfers high cp and keeps high iv

**Comment by Souluzumaki** [comment]
what is your config on max cp and max iv to transfer

**Comment by SahnCH** [comment]
Please @Ar1i  write a small explanation so we are sure of the consequence of activating "transfer low IV first", can be a disaster at this point :p

**Comment by nekudah** [comment]
@dragon2011 You don't need high CP you just need High IV, CP you can use dust to upgrade later. I use 2000 CP and 90% and IV Turned OFF, working well

**Comment by dragon2011** [comment]
999cp and 95% iv, i had 800cp 67iv blastoise, i caught 380cp 90iv blastoise, the bot transfered 800cp blastoise, BUT IV TRANSFER IS OFF

Yeah sure @nekudah LOL

**Comment by Ar1i** [comment]
cause of your settings, make a screenshot before screaming here @dragon2011

**Comment by dragon2011** [comment]
not screaming, giving a proper reply to answers i receive

**Comment by elenex23** [comment]
damnit i just turned it off and restarted bot, now im ban...

**Comment by nekudah** [comment]
@Ar1i  just asking since u'r online now, any possibilities of hatch eggs come back to work ? :D Thanks for the amazing work dude

**Comment by elenex23** [comment]
nekudah please delete your comment

**Comment by Ar1i** [comment]
follow this one here #2622
