### ISSUE TITLE
end of stack trace from previous location helppp :(((( 

### ISSUE THREAD

**Issue by Nikeliss** [Ar1i/PokemonGo-Bot#2635]
![beda](https://cloud.githubusercontent.com/assets/20953428/17561721/1276427c-5f30-11e6-8865-584ea9ceaf4a.png)

**Comment by Ar1i** [comment]
your proxy isnt working

**Comment by Nikeliss** [comment]
im from lithuania so what proxies i need to use? :(

**Comment by Ar1i** [comment]
go to proxie tab, and click disable proxy should work then

**Comment by Nikeliss** [comment]
![beda2](https://cloud.githubusercontent.com/assets/20953428/17562092/d4b10cb8-5f31-11e6-934a-6a85d27ca836.png)

**Comment by BennyAlex** [comment]
i think u have to pai for these proxies so take a free one

**Comment by Nikeliss** [comment]
where to find them? :( i found it in free proxy list

**Comment by Nikeliss** [comment]
okey its working thanks Ar1i
can i use more than one acc?

**Comment by Ar1i** [comment]
if you got working proxys which are https yes. else no

**Comment by Nikeliss** [comment]
Thank you <3
