### ISSUE TITLE
Error plss helppp

### ISSUE THREAD

**Issue by sHaXx69** [Ar1i/PokemonGo-Bot#2636]
![error](https://cloud.githubusercontent.com/assets/20890373/17561964/cbedfd4c-5f28-11e6-9a8a-cfab09cd55fd.png)
###################### RULES. READ BEFORE POSTING! ######################
#
#-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!
#
#-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!
#
#-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!
#
#-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!
#
#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Post. please help me :(

**Comment by xJustx** [comment]
Hast du die LastCords irgendwie noch offen?

**Comment by Amnzya** [comment]
u need to define a position ...worked for me :p

**Comment by sHaXx69** [comment]
ohh sry thx for help <3  bot is on thx xjustx
