### ISSUE TITLE
Request formula transfer

### ISSUE THREAD

**Issue by rochadl** [Ar1i/PokemonGo-Bot#2637]
@Ar1i 

another consideration for formula transfer

example if pokemon more than 2
Pokemon      CP     IV                     LVL      comparation (CP/LVL)
Bulbasur      635   7.68% 0-1-3       26        24.42
Bulbasur      625   31.82% 0-2-15   24        26.04
Bulbasur       64    11.10% 0-5-2      3         21.33

conclusion transfer the lowest comparation Bulbasur

example if pokemon only 2
Pokemon     CP     IV                          LVL        comparation (CP/LVL)
fearow       1100   76.38% 13-12-9     23            47.83
fearow         909   76.53% 12-15-8     19            47.84

add more formula for this case (only 2 pokemon compare)

if "CP of highest comparation" < "CP of lowest comparation then
    if "LVL of lowest comparation - LVL of highest comparation" < 2 then 
       "conclusion transfer the lowest comparation Ferrow"
    else
      "conclusion transfer the highest comparation Ferrow"
   endif
else ("CP of highest comparation" >= "CP of lowest comparation)
   "conclusion transfer the lowest comparation Ferrow"
endif

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
