### ISSUE TITLE
Egg incubator

### ISSUE THREAD

**Issue by Cagatay342** [Ar1i/PokemonGo-Bot#2639]
Hi. i searched code a few mins and saw that part about incubator was close i opened that and now it works 
![a](https://cloud.githubusercontent.com/assets/5398334/17562419/8d938552-5f33-11e6-8603-80abf5966530.png)

closed function is  StartIncubation()

**Comment by sunit1998** [comment]
how to do it can u post a video or screenshots how to do it?

**Comment by SebiWolze** [comment]
Would be nice if that would be open for everyone.
@Ar1i is that possible in the near future?

**Comment by Ar1i** [comment]
@Cagatay342 yeah, i know that it works.. but couldnt try it atm.. wanted to see if a pokemons comes out lol

**Comment by Cagatay342** [comment]
i can share of course but if you have visual studio find   private async Task StartIncubation() and clean green :) i will add debug file in a few minute

**Comment by SebiWolze** [comment]
:D would be a pleasure to try it :)

**Comment by Yahook** [comment]
If it works why it's not opened for everyone?

**Comment by Cagatay342** [comment]
i didnt see any error except one but maybe it doesnt work %100 healthy

**Comment by elenex23** [comment]
where did you change the code?

**Comment by Cagatay342** [comment]
find StartIncubation in code you will see. cant i add here .zip file ?

**Comment by Abbasoo** [comment]
@Cagatay342 Add it.

**Comment by Cagatay342** [comment]
i didnt try it too much .it would be better to try it with fake account first (https://www.dropbox.com/s/pat49effh7ij08o/Debug.rar?dl=0)
![capture](https://cloud.githubusercontent.com/assets/5398334/17562931/c0e778c6-5f35-11e6-98ce-3b7d527c43d9.PNG)

**Comment by xRealMaks** [comment]
Guys.. There is a reason why this isnt implemented yet. Its not tested. Wait a few hours and its implemented and tested..

**Comment by xRealMaks** [comment]
@Cagatay342 Sorry for removing your post, but as it is not tested and you could added a virus or so (what i dont think). In the end we're responsable for that.. Just wait a few hours ^^

**Comment by Spensky** [comment]
Does it REALLY works ? Can you prove egg hatching ?

**Comment by Cagatay342** [comment]
no its ok. thats why i had said that remove that function :)

**Comment by xRealMaks** [comment]
Implemented in the newest version. DOWNLOAD IT AND HATCH YA EGGS! :egg:

**Comment by eLDeMe** [comment]
@Ar1i I'm testing the new update and hatching eggs it's working for me, no problem at all, 3 2km eggs opened so far and looks good for me

**Comment by eLDeMe** [comment]
![image](https://cloud.githubusercontent.com/assets/20787975/17567113/489529ca-5efb-11e6-854c-668b19861dc0.png)
