### ISSUE TITLE
[GER] Keine Pokemons

### ISSUE THREAD

**Issue by Kamylicious** [Ar1i/PokemonGo-Bot#2640]
Ich mal wieder hab gerade das mit den Pokestops gefixt nach 10 minuten findet er keine pokemons mehr und wenn ich dann restarte kommt das mit den Pokestops wieder .... -.-

**Comment by SebiWolze** [comment]
Hat man mal, neustarten, neu runterladen, configs löschen neu anlegen, Pokebälle nicht auf 0 lassen usw...

**Comment by xRealMaks** [comment]
1000x beantwortet. PokeServer down/slow oder IP-ban.
Neu starten oder neu runterladen oder config löschen oder router neustarten
Danke für's -.- ist ja nicht so, als hätten wir das schon 1000x beantwortet.
