### ISSUE TITLE
how too convert radius distance

### ISSUE THREAD

**Issue by ricardorohde** [Ar1i/PokemonGo-Bot#2642]
Hi, how too convert radius distance??
in bot the default value is 5000 m

5000m is in miles? 1 meter?

**Comment by chickeflonoah** [comment]
3,106856 Miles = 5000meters

**Comment by b3shoy** [comment]
Five thousand meters.

**Comment by xhalfbakedguy** [comment]
http://lmgtfy.com/?q=meter+in+miles

**Comment by Spensky** [comment]
when you start the bot a window named pokemon list appears . There in the bottom right corner you will see a map ,click on it and that will show you the radius

**Comment by ricardorohde** [comment]
Ok, but i put the distance in MILES or METER ?

**Comment by xRealMaks** [comment]
meter

**Comment by ricardorohde** [comment]
ok, thanks!

**Comment by xRealMaks** [comment]
imperial system sucks lol :smile:
