### ISSUE TITLE
Got the new version

### ISSUE THREAD

**Issue by Safti54** [Ar1i/PokemonGo-Bot#2643]
Still dosent find pokestops or pokemons tryed to change ip restarted a hundret times still dosent work

**Comment by xRealMaks** [comment]
PokeServers Slow/down atm.

**Comment by Reverse010** [comment]
You sure thats the problem?
not some kind of ban or something?

Even without Using Proxy

**Comment by xRealMaks** [comment]
IP-ban would get fixed with proxy and softban isnt the reason, cause to remove a soft-ban you need pokestops. 
Other kind of bans are not known.
