### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by xxKevinSniperxx** [Ar1i/PokemonGo-Bot#2644]
![](http://i.imgur.com/tIZOna7.png)

**Comment by kazzaluis** [comment]
servers down guess

**Comment by gummyruler** [comment]
Wrong credentials that's what it means. make sure you entered the right password and username. Also don't forget to change if u are PTC or Google.

**Comment by xRealMaks** [comment]
^

**Comment by xxKevinSniperxx** [comment]
i'm still getting the error

**Comment by xxKevinSniperxx** [comment]
nvm i fixed it
