### ISSUE TITLE
Use gimmeproxy.com for Random Proxies

### ISSUE THREAD

**Issue by Lasertrap00** [Ar1i/PokemonGo-Bot#2645]
Why don't use gimmeproxy.com API instead of needing the User search one and put it in?`:)

**Comment by xRealMaks** [comment]
Tell me one thing.. why you didnt read the rules for issues in the issue-template?

**Comment by Lasertrap00** [comment]
Sorry its new to me
I am here since 100 Commits

Am 10.08.2016 7:20 nachm. schrieb "xRealMaks" <notifications@github.com>:
