### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Shak4zoo** [Ar1i/PokemonGo-Bot#2646]
![bg](https://cloud.githubusercontent.com/assets/20952327/17563522/205ca7a0-5f30-11e6-88a4-7209bebfe428.png)
how to fix this ereur ...

**Comment by peptidoglikan** [comment]
same here

**Comment by IMituky** [comment]
Same (have the problem the whole day) :(

**Comment by dragonuts330** [comment]
used proxy was good for 5m and then I got softbanned now no matter which proxy I use I'm getting this ip ban crap. aka no pokestops found

**Comment by HydroSnail1** [comment]
I tried a proxy, hotspotshield and reinstalling. Nothing worked.

**Comment by lailaps** [comment]
If 2 people use same proxy, guess what will happen...
Now all people use linked ones...

**Comment by HydroSnail1** [comment]
It didnt work any of the other times though. Even when im not using a proxy.

**Comment by lailaps** [comment]
Change your home IP or use VPN, which is not well known like Hidemyass.

**Comment by HydroSnail1** [comment]
I used hotspotshield and it didnt work.

**Comment by HydroSnail1** [comment]
it showed a bunch of red errors

**Comment by HydroSnail1** [comment]
when i turned it off it worked but wouldnt find any pokestops

**Comment by lailaps** [comment]
That is a softban!
Use VPN...
![bot](https://cloud.githubusercontent.com/assets/20746711/17564590/2a4bc1a2-5f34-11e6-9353-fb16cd7ef606.jpg)

**Comment by HydroSnail1** [comment]
I dont have a softban, I checked on my phone. i will try the vpn, how do i do it?

**Comment by HydroSnail1** [comment]
Hello?

**Comment by HydroSnail1** [comment]
I installed a vpn and it still doesnt work

**Comment by Captnred** [comment]
You may be IP banned and all you have to do is reset your router if that's the case. Typically people say just wait 2-4 hours and it resolves itself, but i can't say that works for everyone.
