### ISSUE TITLE
Pls add the number of the pokemon to the list and sorting by name ore number

### ISSUE THREAD

**Issue by PinkmanHD** [Ar1i/PokemonGo-Bot#2647]
Pls add the number of the pokemon to the list so i can find it faster 
+sorting Name(a-z/z-a), Nr.(1-99/99-1) and if it is ticked

Example(created with Ps):
![screen](https://cloud.githubusercontent.com/assets/18481447/17563485/dec2ca36-5f2f-11e6-901a-8c4adc97efdd.PNG)

**Comment by azisbhe** [comment]
pls add in box pokemon list too, when bot is running

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Read the rules in the issue template!

**Comment by PinkmanHD** [comment]
ok sry
