### ISSUE TITLE
am not being unbanneed ?!!

### ISSUE THREAD

**Issue by Hamouda55** [Ar1i/PokemonGo-Bot#2649]
Post.

**Comment by xRealMaks** [comment]
read the issue template when create an issue. 
after that you can open a new issue following the template.

**Comment by Hamouda55** [comment]
i didnt  find  it ofcourse i wont search in a thread with 300+pages ... @xRealMaks

**Comment by xRealMaks** [comment]
And the other few things? A description? A Screenshot?!
