### ISSUE TITLE
Tranfering the way I want doesnt work :/?

### ISSUE THREAD

**Issue by Mikexus** [Ar1i/PokemonGo-Bot#2650]
Im Trying to just save up only pokemons that is iv 99% only 
And I want the bot to Transfer the rest and only save everything that is over 99% 

But I always get full after 2-3 h :/ without the bot transfering ...
Could anyone help :(?
Thanks for replies!

![bild1](https://cloud.githubusercontent.com/assets/20954140/17563603/69eea044-5f30-11e6-9ca4-4c83c222255b.jpg)

**Comment by xRealMaks** [comment]
make sure you unchecked that 
![](http://i.m4ks.cf/DMxKC9Js.png)

**Comment by Mikexus** [comment]
Think it works now! thanks!
