### ISSUE TITLE
**REQUEST** Pokemon transfer error

### ISSUE THREAD

**Issue by xJihadx** [Ar1i/PokemonGo-Bot#2656]
I've seen many people stating the bot transferred their high lvl pokemon, this is frightening to think my 3k  Dragonite's and Snorlax's can be transferred.

Is there a way to make the bot (Not able) to transfer pokemon that you added to your favorites list? That way we can favorite all are pokemon we don't want transferred due to errors.

**Comment by xRealMaks** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xRealMaks** [comment]
Read the rules in the issue template
