### ISSUE TITLE
please add pokemon snipping feature in bot its a humble request...

### ISSUE THREAD

**Issue by mehfoozzz** [Ar1i/PokemonGo-Bot#2657]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect the them, your issue get closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by xJustx** [comment]
huso MfG

**Comment by xRealMaks** [comment]
retard alert

**Comment by mehfoozzz** [comment]
I dint get yu.. y u closed my request....

**Comment by xRealMaks** [comment]
you defnetly read that..
