### ISSUE TITLE
[BUG] Bot stuck after update

### ISSUE THREAD

**Issue by TheSmartly** [Ar1i/PokemonGo-Bot#266]
After the newest update, the bot is stuck at 

> [20:47:34] You added -nogui! If you didnt setup correctly with the GUI. It wont work.
> [20:47:37] We got the API Url: pgorelease.nianticlabs.com/plfe/526

--EDIT-- 

It only works if i close the pokemon list. If i dont, it is stuck there.

**Comment by Ar1i** [comment]
Fixed.
