### ISSUE TITLE
lucky egg activating by itself ?

### ISSUE THREAD

**Issue by pmaster4545** [Ar1i/PokemonGo-Bot#2660]
i immediately closed the bot when this happened. will it happen again ?

**Comment by xRealMaks** [comment]
do you use the newest version?

**Comment by pmaster4545** [comment]
ye

**Comment by xRealMaks** [comment]
Did you configue your bot after the update?

**Comment by pmaster4545** [comment]
oh wait, its checked. that's weird, i never checked the lucky egg config.

**Comment by jeremie152** [comment]
lol if full update continu soon the bot take 0 pokemon i dont understand why botting so look 10 mn take just one pokemon in disneyland tokyo!!!! fix this

**Comment by jeremie152** [comment]
and egg activate but not work to 10kmh
