### ISSUE TITLE
Send highest IV, but TransferFirstLowIV is on...

### ISSUE THREAD

**Issue by LPschenkel** [Ar1i/PokemonGo-Bot#2661]
Builld 1.0.9.1

The bot is sending some pokemons which are great for my bag.
The bot have to send in my opinion the lowest IV pokemon, but it doenst.
How do I fix it? Do I have any selections wrong?

![unbenannt](https://cloud.githubusercontent.com/assets/20952282/17564052/5f2db904-5f32-11e6-8151-b08bc2140541.PNG)

**Comment by Hydro420** [comment]
Prototype phase - I believe.. was just implemented in a version today.. Give it some time to get perfected.

**Comment by kazzaluis** [comment]
![image](https://cloud.githubusercontent.com/assets/1984839/17564103/efd1154a-5ef7-11e6-8479-5932d0961194.png)

![image](https://cloud.githubusercontent.com/assets/1984839/17564131/06015cd0-5ef8-11e6-9091-3753b6eb010f.png)


same problem

**Comment by instinctftw** [comment]
is the bot running for yall? Because it is not for me.. lol

**Comment by gummyruler** [comment]
Just don't check the transferfirst LOW IV for now.

**Comment by Bangden** [comment]
same with me :(
