### ISSUE TITLE
10.08 19.17.rar - Transfer Pokemon still not working

### ISSUE THREAD

**Issue by dreamboatcap** [Ar1i/PokemonGo-Bot#2662]
<a href='https://postimg.org/image/b77czac7f/' target='_blank'><img src='https://s9.postimg.org/up20f895b/Untitled.jpg' border='0' alt='Untitled'/>

**Comment by xJustx** [comment]
Please restart your bot and watch in the list again.

**Comment by kazzaluis** [comment]
![image](https://cloud.githubusercontent.com/assets/1984839/17564144/10d8aee2-5ef8-11e6-8301-cf6b3e6ebaed.png)


![image](https://cloud.githubusercontent.com/assets/1984839/17564167/260e3cf0-5ef8-11e6-9a86-f5f400d002d7.png)


same problem in this uodate

**Comment by mehfoozzz** [comment]
reload the gui

**Comment by kazzaluis** [comment]
i did

**Comment by dreamboatcap** [comment]
i restarted the bot, checked the "TransferFirstLowIV", same problem!!

**Comment by mehfoozzz** [comment]
sorry @dreamboatcap  taking word back
I am also facing same problem in new update
