### ISSUE TITLE
Pidgeys are being transferred instead of getting evolve.

### ISSUE THREAD

**Issue by mon2x2** [Ar1i/PokemonGo-Bot#2663]
Pidgeys are being transferred instead of getting evolve.

**Comment by Hydro420** [comment]
It will transfer if you don't have the candy to evolve.

**Comment by mon2x2** [comment]
but I got more than enough candies to evolve it since it requires 4 pidgeys to evolve to pidgeotto the bot transfered 12 pidgeys instead of evolving it.

**Comment by pokerave** [comment]
show screen shot of settings.
