### ISSUE TITLE
The Incubator use all the incubator when just checked the basic one

### ISSUE THREAD

**Issue by raflein** [Ar1i/PokemonGo-Bot#2666]
Just information, i know it might not work, so i am just testing it
it added all the egg to all the incubator
![sdfssg](https://cloud.githubusercontent.com/assets/11917417/17564193/da3d77ea-5f5c-11e6-9cd3-ff633b2c1ef9.PNG)

**Comment by Yogissimo** [comment]
yes, but breeding works fine

**Comment by pwnjke** [comment]
i don't use the option "use basic incubators" and the bot uses limited incubators only for 10km eggs. basic will be used for 2km and 5km. the only trouble is that you get no message what the pokemon was in your egg

**Comment by eLDeMe** [comment]
@pwnjke yeah, but you still got it the poke

![image](https://cloud.githubusercontent.com/assets/20787975/17567802/186ab4d8-5efe-11e6-82a0-57e05e1912cf.png)
