### ISSUE TITLE
Lucky EGGs

### ISSUE THREAD

**Issue by mon2x2** [Ar1i/PokemonGo-Bot#2668]
the bot still has a lucky egg activated but when Iturned off the bot to set a new location it will use again another lucky egg even if the lucky egg is not expired.

**Comment by PippoAe** [comment]
At the momemt the bot uses an internal clock for the lucky egg.
If you restart the bot it forgets that there's already a egg active and uses another one.

So take care if you restart the bot while an egg is active ato set the bot to not use eggs.
