### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by XxAirWalker26xX** [Ar1i/PokemonGo-Bot#267]
- A way to sort the pokemon inventory
- A way to transfer certain pokemon (Pidgeys, etc) when the inventory is full
- An option to activate a lucky egg then evolve all pidgeys, weedles and caterpies as a grind option
- A way to c the IVs of all the pokemon

**Comment by TheSmartly** [comment]
@XxAirWalker26xX  for nr. 3 you only need to hover over the pokemon in the pokemon list

**Comment by XxAirWalker26xX** [comment]
Ye but its a hassle to see it but if they used a list view it would make things much more clear and easier to view
