### ISSUE TITLE
Red Vulpix

### ISSUE THREAD

**Issue by AKBlizzard** [Ar1i/PokemonGo-Bot#2671]
Why is it coming up red, it's not because it's new either. I've caught over 100 of them before and never came up red and with 300xp.
![untitled](https://cloud.githubusercontent.com/assets/20829322/17564780/21b23a42-5ee1-11e6-99ef-82533e0fce2d.jpg)

**Comment by xuban** [comment]
Me too with other pokemons.

**Comment by pokerave** [comment]
same, but its just the  first catch thats red then goes to normal.

**Comment by AKBlizzard** [comment]
No it's not because it's come up for ekans twice. @pokerave

**Comment by pokerave** [comment]
mine resumed to green after the first one.

**Comment by Crabbey** [comment]
It's because there's more than 300XP gained in the catch.
