### ISSUE TITLE
pokemon keep getting away

### ISSUE THREAD

**Issue by choolol** [Ar1i/PokemonGo-Bot#2675]
![screenshot 2016-08-11 01 18 47](https://cloud.githubusercontent.com/assets/20955101/17565096/94290038-5f68-11e6-977d-20a1190d2f17.png)

after countless force unban, still getting the same problem

**Comment by pokerave** [comment]
POKEBALL DO NOT SET to 0

**Comment by choolol** [comment]
pokemon wasn't set to 0

**Comment by xwolfonx** [comment]
is the pokemon go  
not the bot
