### ISSUE TITLE
Got banned again. only opened 1 bot

### ISSUE THREAD

**Issue by pmaster4545** [Ar1i/PokemonGo-Bot#2676]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect the them, your issue get closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by KaV0** [comment]
stop this spam guys..

**Comment by pmaster4545** [comment]
its not a spam, its a template provided by Arl1 everytime you started new issue. you only need to read the title

**Comment by beanie212** [comment]
keep getting softban every 2min only running one bot ![screenshot 1](https://cloud.githubusercontent.com/assets/20955243/17565433/5f6126f2-5f2f-11e6-90d9-096d35aabad0.png)

**Comment by Daud1337** [comment]
Same problem
![screenshot_9](https://cloud.githubusercontent.com/assets/20892493/17565515/05a8768e-5f38-11e6-8292-e73352dfcaf5.jpg)

**Comment by Daud1337** [comment]
And this 
![screenshot_11](https://cloud.githubusercontent.com/assets/20892493/17565573/473f1a8a-5f38-11e6-9f73-e30c28d53e66.jpg)

**Comment by beanie212** [comment]
yes i had that aswell but this latest update seemed to get rid of that been getting the soft ban problem all day tho was working fine yesterday

**Comment by beanie212** [comment]
well just looked and yes ive got the same as u on screen again think its the end for the bots tbh not been right since its come back

**Comment by beanie212** [comment]
maybe pokemon go servers where it cant find a poke stop yes but whats the problem with the soft bans?

**Comment by xwolfonx** [comment]
is the server pokemon go

**Comment by Elitcody** [comment]
It could be Pokemon go servers, It has happend to me too... I waited for 3h and then worked again...

**Comment by LMDR2016** [comment]
Again ... how many bots do you have open at the same time? Looks to me you are possible IP banned or even a soft ban.

**Comment by TheHackerman** [comment]
If you cant detect any pokestops in 5km range on bot or on phone, you probably got IP bannned. Its not the bots fault.

**Comment by turantulpar** [comment]
modem reset and ony 1 bot !

**Comment by turantulpar** [comment]
http://i.hizliresim.com/kErDzq.png

**Comment by bboylost** [comment]
Man, your phone using the same IP address with your computer, think before you post.... if you are really just using "ONE" bot/pokemon go game,  it wont happen.

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by pmaster4545** [comment]
i never used my phone.
