### ISSUE TITLE
New kind of Ban ? (permban)?

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#2679]
I've never encountered this Problem before and I browsed alot of Issues here.

- I can't Login my account anymore, it keeps saying "Unable to login" if I keep trying "No Connection to Server". 
 
- tried it with phone, bot and Nox.
- If I start the bot a big red wall of text appears with tons of exceptions. 

- This isn't the normal IP or softban
- PTC email confirmed, acc is 1 week old

Other accounts work. Doesn't matter if I use phone, bot nox, every account work, except this one, is that one of the first permabans?

**Comment by ineedtostudy** [comment]
What account are you using? If you are using a PTC and you made it recent, you need to confirm your email for it to work again. It happened to me.

**Comment by AiVo7z** [comment]
It's PTC, email confirmed and approx 1 week old. This isn't the Issue.

**Comment by ineedtostudy** [comment]
Try logging onto the official pokemon website. See if that will work

**Comment by AiVo7z** [comment]
I can Login Website. Just can't Access the game anymore. Trying since 10h every once in a while.

**Comment by AiVo7z** [comment]
The Strange Thing is, it keeps popping up very fast on mobile or nox. Difficult to explain. If you Launch the app and you can't connect, you get that poppup once till you click OK. For this account it keeps popping up fast a couple of times. Really strange!

**Comment by pokerave** [comment]
you have screenshot?

**Comment by AiVo7z** [comment]
Screenshot of that unable to Login popup of the game? Don't think you'll Need that, it doesn't explain anything. But I can screenshot the error the botlog Shows.
![fgdgfh](https://cloud.githubusercontent.com/assets/20877777/17566044/2dd845a6-5f3a-11e6-9500-726e1b6582ab.jpg)

**Comment by AiVo7z** [comment]
As soon as I Change the Login Details to another acc of mine for this same bot, it works perfectly. Just this account and as I said can't even Login to mobile or nox which was possible ever since.

**Comment by AiVo7z** [comment]
I guess the bot sent so much requests that my acc is stuck. I really can't explain it otherwise. If they would have banned me for real, they would show another popup.

**Comment by pokerave** [comment]
ok try this, check and uncheck those boxes. see if that does anything.
![checkuncheck](https://cloud.githubusercontent.com/assets/20603254/17566333/a3c1bf28-5f43-11e6-94fb-505fe558ed2c.png)

**Comment by AiVo7z** [comment]
I downloaded bot at a new Folder, using older Version, nothing helps. Tried what you said tho, same still error. And as I said as soon as I Change to another acc (same Folder, same bot) everything works. Except that one mentioned acc. Lol wtf.

**Comment by Waiiim** [comment]
Aaaah fuck... I hve the same prob

**Comment by AiVo7z** [comment]
@Waiiim can you Login your mobile phone or nox? That the bot Shows some weird error is nothing new to me...

**Comment by pokerave** [comment]
1 more, nothing else to loose right? try password recovery in the PTC website.

**Comment by AiVo7z** [comment]
Hm Since I can Login to PTC Website and I ddin't log off on my mobile I don't think that a wrong PW could be the reason. You probably hope it resets the account ? I'll try, but the Website is bugged as fuck

**Comment by pokerave** [comment]
yup hoping that @AiVo7z

**Comment by eLDeMe** [comment]
maybe its a problem in PTC server

**Comment by pokerave** [comment]
@eLDeMe its not i have 2 bot running in PTC account

**Comment by AiVo7z** [comment]
Didn't work. What's pretty suspect that new flashing popup when I try to Login my phone and everything else work. So its maybe PTC Server Problem BUT just for some accounts... if there was lag/bug/maintance/down for any Server, I would have that Problems for every account.

**Comment by Waiiim** [comment]
Well I can't connect Phone and on Nox they're asking me to do the update, but you can't download it on nox

**Comment by AiVo7z** [comment]
I updated this morning and Login worked. So Im running newest Version. Can't be outdated anyway, if other accounts work. I logged of on nox, tried diffrent acc and no Problem occurs. @ Waiiim

**Comment by Waiiim** [comment]
Did you try a proxy server? @AiVo7z

**Comment by AiVo7z** [comment]
I tried Proxy. Still can't Login. Other accounts don't find pokestops I mean the Servers are fucked up anyway. I'll try later again.

**Comment by mon2x2** [comment]
login to the game using your phone and unbanned it manually then use your bot again.

**Comment by lailaps** [comment]
If they would use something like permban, I would have one, be sure!
No permban, atm.

**Comment by SahnCH** [comment]
I had the same problem. 
You must be using a PTC account, and you didn't activate your account by email. Correct ? 
After 2 days without confirming your email (click on activation link), PTC block your account. 

At least I had very same symptomes as you and I solved it this way.

**Comment by lailaps** [comment]
He already wrote:
It's PTC, email confirmed and approx 1 week old. This isn't the Issue.

**Comment by AiVo7z** [comment]
@lailaps they don't read what I've written. The guy above Sahn said try mobile. Even tho I've tried everything. I've got like 10 ptc and 5 Google accounts. Everything works except this one. I don't think it's a permban either, but for sure it's not a Problem on my end, nor a prob. with the bot... just something that the bot maybe caused.

200.000 xp per h sounds a Little bit too much ? Without luckyegg it's kinda impossible, uber high movespeed?

**Comment by ineedtostudy** [comment]
@AiVo7z How'd you get 200k xp/hr? I use luckly eggs and the highest ive ever gotten was 150k xp/hr and that was for a limited time

**Comment by AiVo7z** [comment]
@ineedtostudy you didn't read carefully, I asked lailaps the same. He mentioned that he gets 200k xp per hour and I asked how he manage that. Im 40k average without lucky egg, I use Default Settings.

**Comment by ineedtostudy** [comment]
oh mb,

**Comment by lailaps** [comment]
@AiVo7z
I use another bot to level up, but I have to change my IP mostly every 2 hours.
Changing VPN IP is done by a script so mostly I can relax. I check it 2 or 3 times a day.
Take a look at running time and xp per h, but if you are not able to change your IP fast it would be worthless.

![bot](https://cloud.githubusercontent.com/assets/20746711/17570425/a17e5cae-5f4c-11e6-949d-307d4ca2330a.jpg)

**Comment by Spartacusbr** [comment]
@lailaps Auto Spinner, that means you use a bot that catches everything on a hot spot super fast, than teleports to a different location, say from LA to NY, auto spin to un-softban, catch everything and teleports again? If that's true, isn't that really risky?

**Comment by lailaps** [comment]
Every account using a bot can be detected easily.
Niantic servers are asking for our coordinates and height.
It does not matter where we are, we send always the same height, even if we are on Mount Everest for example.

The guys from Reddit who cracked the new API did not changed it, because they do not want to support bots, so it does not really matter what you do, they can track and identify every account using this new API.

So my goal is being fast, reaching level 40, catching the best Pokemon and after that the accounts will never see a bot again and used only on mobile phones, the correct way!

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
