### ISSUE TITLE
Problem with walking distance

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#268]
I want to change the region to my home which is in a different country.
The program tells me that I have towait 4000000 seconds.
I tried to be faster then 50 so I changed it to 500000.
This worked but after I opened the app again I had the same problem.

**Comment by duyphuc1610** [comment]
same problem

**Comment by 13XxM1CHA3lxX37** [comment]
Go to ./Configs
And change coordinates in LastCoords.txt

You will get a softban, but it will be removed after some time and you will be in your home country

**Comment by xxhamsterxx** [comment]
how to get there?

**Comment by SlDracon** [comment]
Where your exe is, you have a folder "Configs". In there is a file called "LastCoords.txt" delete it.
