### ISSUE TITLE
2 km egg

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#2682]
it is measure every time 2 km it is not come down

**Comment by pokerave** [comment]
seems to be working fine with me. already hatched a few 2km eggs

**Comment by Cyberlink4200** [comment]
Maybe it depends on your speed, I set mine to 19 and it works.. Remember they count everything above 20 as driving as far as I know.

**Comment by pokerave** [comment]
![egg](https://cloud.githubusercontent.com/assets/20603254/17566204/24574000-5f43-11e6-9202-02af4b064cbe.png)

**Comment by CritSin** [comment]
i did to be speed 15 km but it is same

**Comment by pokerave** [comment]
show screen shot

**Comment by pwnjke** [comment]
it needs some time to refresh. sometimes i get a message that my egg needs 400m more, but the pokemon is already in my bag

**Comment by Phylo94** [comment]
After the Update my bot dont work 😕

**Comment by Ar1i** [comment]
The egg is not updating directly, it needs some time

**Comment by CritSin** [comment]
i did to be speed 10 it is working now but very slowly

**Comment by Phylo94** [comment]
I have a 
Exception: system.badimageFormatException 

Error or better the error is starting with this line 😪

**Comment by jtapay** [comment]
my speed is 100 and i think egg hatching is working..
![image](https://cloud.githubusercontent.com/assets/20932300/17567074/f0d2761c-5f4e-11e6-8628-1606a3a71bcb.png)

**Comment by SebiWolze** [comment]
Whats the best Speed for hatching? I am running with 8kmh, but i think it could work with 19? Somebody got experience?

**Comment by Yotumn** [comment]
I have a set speed of 15 km/h works PERFECTLY!!

The issue I have is; it does not show which pokemon hatched from the egg..
@Ar1i any ideas on this? thanks! ;)

![image](https://cloud.githubusercontent.com/assets/20876425/17570727/ed0cee28-5f4d-11e6-9da6-244731258281.png)

**Comment by eLDeMe** [comment]
I've 150km hatching egg, no problem at all, usually I use 35km, but I was testing only (109m in 2sec)

![image](https://cloud.githubusercontent.com/assets/20787975/17571226/98d3340c-5f0c-11e6-98f2-0c30b070af39.png)

**Comment by Yotumn** [comment]
@eLDeMe this is not a foolproof way of knowing what was in the egg. My transfers are almost always in bulk of 3-8 pokemon, how can i know which one was in the egg then?

**Comment by eLDeMe** [comment]
@Yotumn Sorry, that image was for other post, I used this time just to show my point of the speed and proof that hatching eggs works even a high speed in response to @CritSin 

It's no a problem for me to know what comes from the egg, because it can be transferred if is useless for me, (under 95%)

**Comment by Yotumn** [comment]
@eLDeMe you have a point about the IV% but it would be nice to know what it is, regardless of it being good or not :)

**Comment by eLDeMe** [comment]
@Yotumn Sure, I'm not saying the oposite, it would good if they add it, but isn't something that I personally really need :smile:
