### ISSUE TITLE
Doesn´t collect any item

### ISSUE THREAD

**Issue by machucam** [Ar1i/PokemonGo-Bot#2683]
The bot are running ok, but when it arrive in a pokestop, it dosn´t collect any item.
![sin titulo](https://cloud.githubusercontent.com/assets/20955522/17566093/a2e4339a-5eff-11e6-8a31-27af8369fd2c.jpg)

**Comment by Phylo94** [comment]
You have a Softban read the red line if you have a softban you can not collect items and so one

**Comment by machucam** [comment]
I don´t belevie that, because I open the app in my cellphone and i can get items froms the pokestops.
and the steps of the bot doesn´t count too.

**Comment by LMDR2016** [comment]
you have a soft ban or are IP banned .... if you use the force unban option what happens?

**Comment by Hydro420** [comment]
IP ban if you get items from anything other than BOT

**Comment by machucam** [comment]
Well, i try go outside with my phone, and i can get the pokestops, so i´m not softbaned
I return to my computer and the problem persist
![sin titulo2](https://cloud.githubusercontent.com/assets/20955522/17567285/552ad870-5f04-11e6-8b25-4344c74675e5.jpg)

Any idea ?

**Comment by Hydro420** [comment]
Your IP has been banned.... Stop opening the APP on phone then running the bot right away! Its an obvious sign of spoofing/botting......

**Comment by machucam** [comment]
Please, forvige me if i writhe bad in english, cos i´m mexican. Thanks

**Comment by ahya93** [comment]
download this https://www.psiphon3.com/psiphon3.exe vpn tunneling :dancer: its work but dont run more than 1 bot....

**Comment by Hydro420** [comment]
People make the mistake of playing the game on their phone/emulator. Then run the bot immediately after without changing the "last cords."

**Comment by machucam** [comment]
I change the ip and nothing. After i use psiphon3 and nothing :'( 
I belevie this dosn´t work with me :p

**Comment by machucam** [comment]
Any way, thanks for your help

**Comment by TexasDFW** [comment]
The same thing happened to me i was running a proxy spoof and even when i changed my IP still would not get items i turned off my proxy and it solved the problem...

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
