### ISSUE TITLE
we can't find any pokestops???

### ISSUE THREAD

**Issue by lucasxvieira** [Ar1i/PokemonGo-Bot#2688]
i'm not banned, so please tell me what the hell is going on! :/

![untitled-1](https://cloud.githubusercontent.com/assets/20726859/17566583/42e21878-5ef9-11e6-9622-12ea2d3a0c7b.jpg)

**Comment by xRealMaks** [comment]
read the other issues with the same problem

**Comment by herman12366** [comment]
its the servers

**Comment by Safti54** [comment]
same!

**Comment by Safti54** [comment]
servers are unstable neither proxy works
