### ISSUE TITLE
Location set Bug

### ISSUE THREAD

**Issue by GbRJ** [Ar1i/PokemonGo-Bot#2689]
Location : Keisei Ueno

lat : 35,7113953710537
long : 139,773473739624
Alt : 15,173855

When u set the pocation just set the Lat / Log .. the Alt Still 0

**Comment by xRealMaks** [comment]
just move the map a bit around and it should be fixed

**Comment by GbRJ** [comment]
XRealMaks Don't Work already Tried !

**Comment by Hydro420** [comment]
ALT is automatically adjusted - I never set ALT...

**Comment by GbRJ** [comment]
This  "bug" maybe  can not be why sometimes que get the error "DONT FIND ANY POKESTOPS ON XXXXm Ditance" ?

**Comment by lailaps** [comment]
It works, no bug.
Just move a bit on the map, thats all.
Close thread.

**Comment by Ar1i** [comment]
Its wayne if there is 0, cause it will auto get the info on moving :)! And it has nothing to do with dont find any pokestops

**Comment by Hydro420** [comment]
No... Just no....

**Comment by lailaps** [comment]
2nd one no bug too, just IP ban...

**Comment by GbRJ** [comment]
ok thx  !
