### ISSUE TITLE
[Feature Request] Save settings from previous build and put them in another build

### ISSUE THREAD

**Issue by CodingIsLyfe** [Ar1i/PokemonGo-Bot#269]
It's quite a hassle having to recheck all the same boxes after downloading another build. It'd be handy to be able to export the configuration (in one file) and then put it in another. I know you could just copy all the files in the Config folder and paste it in the new build, but just think about it.

**Comment by HaydarOzturk** [comment]
Or an auto patcher or an updater kind of thing

**Comment by UserWest** [comment]
Your settings from the last build can be copied by copy/pasting the configs folder to the new directory. or you can just replace the old files when an update comes out by extracting it to the same folder and replacing the old files.

**Comment by CodingIsLyfe** [comment]
Yeah, I figured you could do that, but just for simplicity and laziness I suggested it.
