### ISSUE TITLE
Error loading image from the new build?

### ISSUE THREAD

**Issue by JunpeiL** [Ar1i/PokemonGo-Bot#2690]
![8-10-2016 11-52-23 am](https://cloud.githubusercontent.com/assets/14263528/17566737/7dc2526c-5ef1-11e6-9a78-d1e377254aaa.png)

Sprites folder has no image files.

**Comment by pokerave** [comment]
delete sprite folder an restart bot.

**Comment by Ar1i** [comment]
Or download this here, and extract it in the Sprites folder. https://github.com/Ar1i/PokemonGo-Bot/blob/master/PokemonGo.RocketAPI.Console/Sprites/Sprites.rar
