### ISSUE TITLE
I have noticed an item glitch on the bot!

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#2691]
so it does not count the right amount of items you have on the bot.It says i have 361/350 in reality i have 240/350.But still great work guys keep it up!

**Comment by jmo93** [comment]
yes, bei mir auch

**Comment by Hydro420** [comment]
Stated in previous open issues... Its really nothing to be bothered with - just let the bot do its thing...

**Comment by army69** [comment]
![error bot](https://cloud.githubusercontent.com/assets/20955864/17567129/afc31236-5f70-11e6-9c2c-6a8ec16e5e23.png)
