### ISSUE TITLE
close some notice

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#2692]
how can i did it 
for example everytime gave notice 
**We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.**

**Comment by pokerave** [comment]
huh??? what is the question here? why is the bot slowing down when it comes near a pokestop. THINK ABOUT it for a moment.

**Comment by CritSin** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/19182149/17567033/6b611982-5f46-11e6-928b-9dc9b366ecc2.png)
i said this one
