### ISSUE TITLE
can't catch any pokemon. unban is not working

### ISSUE THREAD

**Issue by dafook** [Ar1i/PokemonGo-Bot#2693]
can somebody help me with this? i've been like this since yesterday. i didn't play pokemon on my phone yet and i didnt change location at all. pls help i cant catch pokemon at all and the unban isn't helping.

![asdfgfg](https://cloud.githubusercontent.com/assets/20955839/17566941/e527440c-5f6f-11e6-88f7-0146f7ec378a.jpg)

**Comment by xRealMaks** [comment]
no comment.
