### ISSUE TITLE
cancel notice

### ISSUE THREAD

**Issue by CritSin** [Ar1i/PokemonGo-Bot#2694]
pokerave please look at picture how can i cancel it
![adsiz](https://cloud.githubusercontent.com/assets/19182149/17567099/a81861fa-5f46-11e6-919e-332409b4b448.png)

**Comment by pokerave** [comment]
its part of the bot you can not cancel it. you can if you program your own bot thou.
also please stop spamming. use the original post you made and close this or the other.

**Comment by dafook** [comment]
why does my post keep getting closed....

**Comment by Hydro420** [comment]
Most likely because the solution to your problem is on here already - just takes a bit of looking/reading.

**Comment by pokerave** [comment]
@dafook because you have to learn to read. your problem has been solve a hundred if not a thousand times.

**Comment by bboylost** [comment]
because you are posting something that is already ON THE FORUM, you are just spaming your" problem" , which it doesnt help, stop crying like a baby learn to read ffs.

**Comment by bboylost** [comment]
and what do you mean by "cancel it" ?  its part of the bot programme which tells you the details in game. dont use it if you dont like what you seeing.

**Comment by AiVo7z** [comment]
Slowing or pausing a script/bot helps to not Crash (on your end or sever sided), he didn't try to troll you or something, it has to be done. Botting is already fast as fuck, you ever catched by Hand? Lol

**Comment by bboylost** [comment]
@AiVo7z Some guys just complains about anything without thinking

**Comment by Ar1i** [comment]
edit the source by urself
