### ISSUE TITLE
cant catch pokemon, not softbanned

### ISSUE THREAD

**Issue by dafook** [Ar1i/PokemonGo-Bot#2697]
![asdfgfg](https://cloud.githubusercontent.com/assets/20955839/17567205/fcaddcb6-5f70-11e6-82d1-1d5961816714.jpg)

**Comment by Hydro420** [comment]
Ugh here we go again....

**Comment by pokerave** [comment]
DO NOT SET POKEBALL TO 0

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/17567238/2414839e-5f04-11e6-9498-d0c7bd0499b0.png)

![untitled2](https://cloud.githubusercontent.com/assets/20824888/17567243/27e759b0-5f04-11e6-912b-1454de93f575.png)
