### ISSUE TITLE
falsche Reihenfolge der Abfrage ?

### ISSUE THREAD

**Issue by Wendelstein** [Ar1i/PokemonGo-Bot#27]
[20:24:54] We cant find any PokeStops in a range of 5000m!
[20:24:54] We found 132 PokeStops near.

![image](https://cloud.githubusercontent.com/assets/17088057/17085602/cda06e58-51dc-11e6-991b-4467821f46af.png)

**Comment by Ar1i** [comment]
Fixed that Problem with the newest Update.
