### ISSUE TITLE
Error Server down?

### ISSUE THREAD

**Issue by Phylo94** [Ar1i/PokemonGo-Bot#2700]
My bot dont work 

Sorry for the German picture 

![image](https://cloud.githubusercontent.com/assets/20954957/17567513/f68912e6-5f3f-11e6-9a85-1fa8fa9c9071.jpg)

**Comment by Ar1i** [comment]
Lad dir mal das neuste NET Framework runter

**Comment by pokerave** [comment]
dont be sorry bout the german pic.. be sorry its sideways lol

anyway is that a PTC or Google account? using VPN/proxy?  If google you might have a 2 Step authentication

**Comment by Phylo94** [comment]
Habe das aktuellste net Framework auf dem Rechner

**Comment by Phylo94** [comment]
Geht wieder nach deinem Update dank dir 👍
