### ISSUE TITLE
Unable to find pokestops with bot

### ISSUE THREAD

**Issue by kimjongun69** [Ar1i/PokemonGo-Bot#2701]
so i know there's many threads with people not finding pokestops using the bots, 5000km thing.
but I pokemon go app that does walking for me and i was able to find pokestops and all and was able to get items. maybe not server sided?

i tried restarting modem and router lol and still couldn't find on bot

**Comment by ahya93** [comment]
download this https://www.psiphon3.com/psiphon3.exe vpn tunneling :dancer: its work but dont run more than 1 bot.

**Comment by kimjongun69** [comment]
i'd much rather not download an outside source program lol. thx

**Comment by jodirt282** [comment]
I had the same problem after updating the bot and keeping my old configs. I had to Set Location again or it would open in the middle of nowhere with no pokestop. Moved it to Santa Monica and now works perfect.

**Comment by kimjongun69** [comment]
yeah i used phone app and was in middle of ocean. set to SF and it works for my phone but not for the bot..

**Comment by ahya93** [comment]
its up to you i just give some solution 

http://image.prntscr.com/image/57ca3056ed3e4035b92938858c21a6db.png

**Comment by Hydro420** [comment]
Configs folder - Set your cords there in the .txt files.

"Last Cords" should always be where you opened the game at (for example the middle of the freakin ocean)

**Comment by kimjongun69** [comment]
i did that hyodro and its the same. cantr find pokestop in rage of 50000m lol. rip

**Comment by Archimondee** [comment]
Try this #2722

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
