### ISSUE TITLE
On phone, every Pokémon runs away no matter what?

### ISSUE THREAD

**Issue by shadowahs** [Ar1i/PokemonGo-Bot#2703]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by machucam** [comment]
You have a softban

**Comment by pokerave** [comment]
On phone? using normal APP? call niantech you might be softban. lol

**Comment by shadowahs** [comment]
How do I fix this?

**Comment by gummyruler** [comment]
2 PGo in 1 ip = IP softban.

**Comment by shadowahs** [comment]
So how can I fix it?

**Comment by shadowahs** [comment]
If I wait a few hours with my router off, will it reset?

**Comment by xRealMaks** [comment]
nice description of your problem..

**Comment by Ar1i** [comment]
Softban or IP ban. Restart your Router or use a Proxy.
