### ISSUE TITLE
cant catch pokemon

### ISSUE THREAD

**Issue by dengkono** [Ar1i/PokemonGo-Bot#2704]
I cant catch pokemon. what the solution? I keep click on force ban but doesn't work. help me pls

**Comment by pokerave** [comment]
AGAIN DO NOT SET POKEBALL to 0

**Comment by sealtx** [comment]
same problem, i think that it's ip ban, but idk what to do

**Comment by pokerave** [comment]
AGAIN for the 10000 times DO NOT SET POKEBALL to 0

**Comment by Criispey** [comment]
@pokerave  xD 
i think they cant read

**Comment by sealtx** [comment]
@pokerave @criispey do you know what's the issue? 
![screenshot_34](https://cloud.githubusercontent.com/assets/20894644/17567974/44025000-5f4a-11e6-871c-6392acd54c36.png)

**Comment by dengkono** [comment]
no . I didn't set the pokeball to 0. but it still cant catch pokemon. is there need new update? it can unban the acc if I update?

**Comment by kralleo** [comment]
it shouldnt use pokeball at all. it should start at great. maybe pokebalss onyl for cp less than 100

**Comment by davegoskate** [comment]
@sealtx i got same issue im sure its ip ban was running gf bot and mine on two  different folders but after updating it game me the same prompt your getting

**Comment by Archimondee** [comment]
Try this #2722

**Comment by jerFXD** [comment]
Set pokeballs to atleast 50, greatballs to 50. Just make space for the pokeballs. If you ran out of pokeballs, it will always fail to catch. The bot doesn't support yet the use of greatballs.
