### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Zzzeeroo** [Ar1i/PokemonGo-Bot#2706]
closed

**Comment by Zzzeeroo** [comment]
close

**Comment by pokerave** [comment]
:disappointed: in the human race
![maxcpiv](https://cloud.githubusercontent.com/assets/20603254/17568136/22e01c26-5f4b-11e6-852b-60355338b9d3.png)

**Comment by pokerave** [comment]
Close BUTTON below comment box
