### ISSUE TITLE
I tried many proxies and cords but on all i cant find pokestops what to do? 

### ISSUE THREAD

**Issue by Nikeliss** [Ar1i/PokemonGo-Bot#2707]

**Comment by pokerave** [comment]
you tried, example you are in New York to Boston?

**Comment by Nikeliss** [comment]
tried new york
tokyo 
sydney 
maybe i got ban?

**Comment by pokerave** [comment]
Press FORCE UNBAN in the GUI.

**Comment by sealtx** [comment]
...and there no pokestops...

**Comment by AiVo7z** [comment]
Could be Serverlagg. No softban so force unban doesn't work anyway... try later, 30 - 60min

**Comment by Nikeliss** [comment]
i think i got the ip ban, same was in the day after few hours one of acounts started working :) but now i tried to log in more acc on proxy ant then boom all of them is not working

**Comment by pokerave** [comment]
MAX BOT for 1 PROXY is 2.. <<- TESTED my SELF

**Comment by Sobro111** [comment]
well , mine pokestops dissapered when i opened two bots , right now it works just on 1 bot.
when i opening another one , in 2-3 mins both bots are banned for 30 mins.

**Comment by Nikeliss** [comment]
Every bot i used, used on diffrent proxy

**Comment by Ar1i** [comment]
Try to use newest version
