### ISSUE TITLE
Softban with proxy server 

### ISSUE THREAD

**Issue by Gkl75** [Ar1i/PokemonGo-Bot#2709]
Hello,

I buy 3 proxys but when i launch 3 bots with 3 differents proxy,I'm getting banish on the 3 accounts. 
The proxy option realy work ? 
![screenshot_42](https://cloud.githubusercontent.com/assets/20956419/17568179/f846406a-5f42-11e6-8a19-9eeca90c6162.png)
Thank's you and sorry for my bad english

**Comment by toddeay88** [comment]
its not working

**Comment by stenidor** [comment]
Hi, i same problem ^^

**Comment by blasanru** [comment]
it seems a mistake of the bot or Niantic servers.

Same problem

**Comment by kvarnis33** [comment]
Got same problem :/

**Comment by stenidor** [comment]
Lunch Nox, you can not see a pokestop ! Aïe Aïe aïe

**Comment by pokerave** [comment]
do you have private proxy servers or using public free?? IF PUBLIC FREE dont you think others using it also pokemon go bot?

**Comment by Ar1i** [comment]
Your IP is banned, switch your IP. Or use a working https proxy which isnt used by anyone else.

**Comment by stenidor** [comment]
account not hacked is same thing

**Comment by stenidor** [comment]
Ar1i No, I changed 5 times ip it changes nothing

**Comment by stenidor** [comment]
With my phone is same. ByeBye Pokemon go ^^

**Comment by blasanru** [comment]
@stenidor  The bot is just working for me now.

I reboot my router and wait for 10 minutes.

**Comment by stenidor** [comment]
@blasanru idem
