### ISSUE TITLE
new error [20:50:32] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.

### ISSUE THREAD

**Issue by kevcussick** [Ar1i/PokemonGo-Bot#2714]
![Uploading image.png…]()

[20:50:32] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.

is this because servers down again?

**Comment by pokerave** [comment]
screen shot?

**Comment by Ar1i** [comment]
PokemonGo.RocketAPI.Exceptions.GoogleOfflineException - yes

**Comment by kevcussick** [comment]
thanks nice one (guessed as much) well done now less Ar1i adding this stops all the 0 pokastops questions ;)
