### ISSUE TITLE
LOG FILE ERROR

### ISSUE THREAD

**Issue by blasanru** [Ar1i/PokemonGo-Bot#2715]
Hi

Log file (folder Configs) cant be open with this new bot version.

The message is;  you cant get access log.txt Maybe the file is damaged or be only read.

Sorry for my bad English.

Thanx

**Comment by pokerave** [comment]
I can open it fine. try to delete it.

**Comment by blasanru** [comment]
The problem was log was opened by other API.

I closed it in task bar.

Thank you ^^

**Comment by blasanru** [comment]
i dont know what is happening but wilth older version i can see log.txt but now i cant.  it shows the same error again. I restart my computer.

**Comment by blasanru** [comment]
OMG...now its working...
