### ISSUE TITLE
Automatic Update?

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#2716]
@Ar1i 

Don't know if that ever been asked before, but do you plan to build in a Feature to update your opened bot instead of downloading the newest build everytime ? Don't know of it's possible. Hope you got what I've tried to say :)

**Comment by downspath** [comment]
it would would take to much time, time he spends on more features and bugfixes of the bot :)

**Comment by xuban** [comment]
This is a pull request, no issue. Please dont spam this section.
