### ISSUE TITLE
Proxy Server dont works

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#2717]
![2016-08-10 21_56_18-greenshot](https://cloud.githubusercontent.com/assets/20840606/17568762/5ee5df0e-5f45-11e6-9c60-437834e5548a.png)

I am using the newest version of the bot and everytime i use more than 1 bot i get ip banned although i am using a proxy.

And for everyone who needs a new ip try this http://www.mediafire.com/download/3baivu124pq8d28/iprenew.exe

**Comment by pokerave** [comment]
well seems like a proxy problem not bot.

**Comment by deface0x2** [comment]
#2546

**Comment by Ar1i** [comment]
if its a public proxy its probably in use.
