### ISSUE TITLE
Proxy Funktion läuft nicht!!

### ISSUE THREAD

**Issue by toddeay88** [Ar1i/PokemonGo-Bot#2718]
ar1i.... ich denke du solltest dir das doch nochmal angucken..... 2 laptops hier.... ich über proxy und alles läuft.... wenn meine freundin ihren  bot startet ohne proxy werden wir beide nach paar minuten gleichzeitig ip gebannt. das wiederholt sich nach jedem router reset auch... nix zu machen obwohl einer mit proxy einer ohne...  iwas passt da nicht

**Comment by deface0x2** [comment]
#2546

**Comment by xRealMaks** [comment]
known issue.
