### ISSUE TITLE
saving config

### ISSUE THREAD

**Issue by mon2x2** [Ar1i/PokemonGo-Bot#2720]
is there a way to save a config?

**Comment by pokerave** [comment]
goto bot folder, config folder, config.txt - check what you need.

**Comment by mon2x2** [comment]
should I back up everything in configs folder? so that when I input another account for botting it will not override the configuration?

**Comment by kevcussick** [comment]
just copy and paste the entire config folder 

then add it to latest release folder

**Comment by mon2x2** [comment]
thanks guys
