### ISSUE TITLE
Please add a option to turn off automatic unban

### ISSUE THREAD

**Issue by downspath** [Ar1i/PokemonGo-Bot#2721]
I want to place my char at a farming spot (radius 50m-70m) but i need to turn off the automatic unban option

**Comment by xRealMaks** [comment]
Why?

**Comment by downspath** [comment]
Because i want to set the radius at 50-70 m and if the bot tryes to spin the pokestops again he thinks it is softbanned

**Comment by xRealMaks** [comment]
Why would you farm one spot?

**Comment by downspath** [comment]
for pokemons :)

**Comment by xRealMaks** [comment]
You get more pokemons if you walk around.

**Comment by downspath** [comment]
but not the ones i want as example: in my city is one spot where always a glumanda spawns every time at the exact same spot

**Comment by geebart1337** [comment]
but it won't use the auto unban unless you got softban?!

**Comment by eLDeMe** [comment]
@xRealMaks Bot should look for farm pokemon before pokestop. Example, Central park is full of pokemons but you only caught some of them if they are ONLY in your way to a pokestop
