### ISSUE TITLE
Solution if bot cant find any pokestop at xxxxmeter

### ISSUE THREAD

**Issue by Archimondee** [Ar1i/PokemonGo-Bot#2722]
if bot cant find any pokestop at xxxx meter. it soft banned too.

Try this :
1. Try to disconnect your connection and connect again.
2. Click force unbanned in bot
3. Wait 15 - 30 minute and try again using bot
4. Try to another location

Maybe it will help your question to stop asking that. Thanks you. Please read or find your question in search box before you create new issue.

**Comment by xRealMaks** [comment]
Thanks for your work. I'll link that if somebody got these issues.
