### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by GreYzZ** [Ar1i/PokemonGo-Bot#2723]
Hello @Ar1i and the complete development team,
I just have here some suggestions:

- Integration of Pokesnipe.de like the Necrobot

- Make the proxy working properly

- Maybe add a second menu for the Pokelist just for the items

Thats all 💃

**Comment by xRealMaks** [comment]
Pokesnipe will be added soon.
Proxy get fixed in the next update.
Maybe ^^
