### ISSUE TITLE
[suggestion] Dust

### ISSUE THREAD

**Issue by k756u** [Ar1i/PokemonGo-Bot#2724]
He shook rather nice to add the number of star dust available :)

**Comment by Kuzmarin** [comment]
+1 it will be very useful so we can calculate for full power up

**Comment by geebart1337** [comment]
Maybe you could add how much star dust is needed for max power up?
or maybe show how much % of maximum CP a pokemon has.

**Comment by xRealMaks** [comment]
Thanks for reading the rules in the issue template..
