### ISSUE TITLE
1337 unban method

### ISSUE THREAD

**Issue by k3npachi** [Ar1i/PokemonGo-Bot#2725]
Hi, I can not find what is it 1337 unban method 

I look in the source code, but not find 

thanks

**Comment by xRealMaks** [comment]
Its our secret unban methode ^^

**Comment by k3npachi** [comment]
seriously ?

**Comment by deface0x2** [comment]
We should change the typo to "method" instead of the german "methode"

**Comment by k3npachi** [comment]
anyone to tell me how to access

**Comment by KoffeinSchluck** [comment]
Probably turn a PokeStop more the 20 times in a row

**Comment by k3npachi** [comment]
I just want to know what it is that the method 1337

**Comment by xRealMaks** [comment]
Its a special unban method for softbans.
The bot basicly spins one pokestop 60 times..

**Comment by k3npachi** [comment]
ok thanks

it's just the method used in the bot, nothing has done more
