### ISSUE TITLE
Always shows Cought New "Pokemon".....

### ISSUE THREAD

**Issue by xXDjMikeXx** [Ar1i/PokemonGo-Bot#2726]
Always shows Cought New "Pokemon".....
its realy confusing because i thought its an error message because its red!

![unbenannt](https://cloud.githubusercontent.com/assets/20925297/17569375/38f376f0-5f48-11e6-8d10-7d109d9356fe.png)

![unbenannt](https://cloud.githubusercontent.com/assets/20925297/17569431/81c811ce-5f48-11e6-8a03-6af8b7b2a405.png)

**Comment by Ar1i** [comment]
You activated lucky egg or? If yes, its the reason!

**Comment by emilie253** [comment]
i have same, but no lucky egg.

**Comment by Ar1i** [comment]
Probably you did, cause you got 420 xp normally you get 210 xp :p

**Comment by emilie253** [comment]
me i had 310 xp :) ^^

**Comment by lucas2107** [comment]
lucky egg activated auto for me ...

**Comment by Yotumn** [comment]
@lucas2107 check your bot settings before starting it. Lucky egg is now activated standardly.. even if you change it once, it does not seem to update in the config file.
@Ar1i This might be a bug? Dno.
@ everyone else: anyway lucky egg can be "unchecked" if you don't want to use it.

**Comment by Ar1i** [comment]
@Yotumn normally you dont get more then 300 xp per pokemon, only if you activated lucky egg or its a new pokemon.. but i will take a look. and yeah it fires at 300xp +

**Comment by lucas2107** [comment]
@Ar1i is the auto incubation working? And, second question can you add a changelog please ? :)

Thanks for your awesome bot :) <3

**Comment by Yotumn** [comment]
@Ar1i yes I know about the exp amounts, regularly around 210 exp / pokemon caught without lucky egg.
But the option "use lucky egg when not running" is always ON when you open the .exe
Even if you uncheck the option, and save config (doesn't use lucky egg so works fine), when you close the bot and relaunch the .exe the option is checked again. So it doesn't save it in the config.
This is only a minor issue if you ask me, and if ppl would look carefully at their settings they would have problems with it at all ;)

**Comment by Yotumn** [comment]
@lucas2107 Auto Incubation works like a charm!

**Comment by lucas2107** [comment]
@Yotumn Okey thanks :dancer:

**Comment by emilie253** [comment]
@Ar1i 
![bug bot](https://cloud.githubusercontent.com/assets/20780055/17573976/3ab05204-5f5e-11e6-914d-892d747ea2a5.png)

**Comment by Yotumn** [comment]
@emilie253 I have encountered this also in the past hour or so (3 or 4 times), it doesn't really bother me that I get 100 free exp though :D

**Comment by emilie253** [comment]
me too, but it's for @Ar1i  :)
