### ISSUE TITLE
Pokestops problem .. 

### ISSUE THREAD

**Issue by bloodmoonx2** [Ar1i/PokemonGo-Bot#2727]
Woran kann das liegen das immer die fehlermeldung kommt : We cant find any Pokestops which are unused ?? ... 
![poke](https://cloud.githubusercontent.com/assets/20911039/17569386/4292ca30-5f48-11e6-8a88-4ec6cab73fc3.PNG)
und weiß da jemand einen fix ?

**Comment by xRealMaks** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues?utf8=%E2%9C%93&q=Pokestops
Danke dass du es nochmal postest und die regeln einfach ignoriest..
