### ISSUE TITLE
Every pokemon got away always...

### ISSUE THREAD

**Issue by JFKKDown** [Ar1i/PokemonGo-Bot#2728]
I don't know why but bot doesn't catch any pokemon by me anymore... Is it bug or ban or something others? 
![bez nazvu](https://cloud.githubusercontent.com/assets/20956963/17569424/7738e06c-5f48-11e6-93c1-2223efb50430.png)

**Comment by xRealMaks** [comment]
Use the search function. lol 
solved more than 20 times
