### ISSUE TITLE
keep getting no pokestops in 5000m

### ISSUE THREAD

**Issue by MiGaBelG** [Ar1i/PokemonGo-Bot#2730]
So i've been waiting for almost 2hours.
even tried proxy's and other ip's 
Please ar1i help me out or someone else <3

**Comment by MiGaBelG** [comment]
Or Please add me in skype to help

**Comment by MiGaBelG** [comment]
+ on my phone with the same wifi i can see pokestops

**Comment by webdevzde** [comment]
you should be logged out on your phone if you want to use the bot.

**Comment by xRealMaks** [comment]
IP-Ban and / or low pokemon servers
