### ISSUE TITLE
Someone selling your bot?

### ISSUE THREAD

**Issue by Freshwood** [Ar1i/PokemonGo-Bot#2732]
Look at this ebay link:
http://www.ebay.de/itm/Selten-Pokemon-go-Pokemons-fangen-am-PC-Pokemon-Go-Bot-/282130512649?hash=item41b049fb09:g:voUAAOSwgZ1XqzxR

It looks like your bot. 
I think this is not okay to sell stuff from an open source repository!!!

Greetz
Freshwood

**Comment by xRealMaks** [comment]
You pay for the "research".
But its ebay. Hardly to prevent that.

**Comment by xRealMaks** [comment]
But its a known issue. Thanks for your report :heart:

**Comment by bboylost** [comment]
I would love to report this item and get his ebay account banned , but I cant read that language, someone can do it ? report that item to ebay

**Comment by gateseee** [comment]
The guy write that you pay for his research and the tutorial he wrote. 
It's hard to prevent idiots like this from what they doing.
