### ISSUE TITLE
Nothing happens when using Proxy

### ISSUE THREAD

**Issue by geebart1337** [Ar1i/PokemonGo-Bot#2733]
Using latest version. Tried to connect via https Proxy, but nothing happens except saying "proxy enabled ip xxx.x.xx.xx:xxxx" then after a few minutes it says "error loading pokemon list" and then the bot tries to restart but it won't start. 
In older versions it was connecting correctly via proxy.
But still, one bot without proxy is working absolutely fine. especially with egg hatching now. thanks for that!

**Comment by adriendillens** [comment]
i have the same issue ! exactly the same.

**Comment by adriendillens** [comment]
I try reboot my modem. Try to use 3 different proxies... still doesn't work.
Help ? ^^
Maybe get the previous build if it's possible ?

**Comment by Ar1i** [comment]
Probably proxy down? & @geebart1337 in older version it only used proxy at login

**Comment by geebart1337** [comment]
I tried to use several Proxies as well. Same issue. 
Well, I don't really know what's the difference now. Older versions used proxy only for login, what does the latest version do with the proxy? I just can tell you that the bot started farming regulary in older versions while using a proxy.

**Comment by adriendillens** [comment]
I try to disabel proxy and ... it's works ! since i will be IP ban, of course ^^

**Comment by geebart1337** [comment]
yeah without proxy 1 bot at a time is working totally fine. Makes sense, right? :P

**Comment by adriendillens** [comment]
@Ar1i Yeah... looks like @loganpunkt done good stuff finally xD (joke)

**Comment by PokemonAddict** [comment]
Same here... ^^
