### ISSUE TITLE
Question --> asking for release notes

### ISSUE THREAD

**Issue by mancmanGER** [Ar1i/PokemonGo-Bot#2734]
Could we get a release note or so?
Just to see what has changed in the new builds.

Would be highly appreciated.

**Comment by Spartacusbr** [comment]
Seconded.

**Comment by eLDeMe** [comment]
+1

**Comment by ShujiYagami** [comment]
+1

**Comment by GreYzZ** [comment]
Look at the commits.
https://github.com/Ar1i/PokemonGo-Bot/commits/master

**Comment by Captnred** [comment]
Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you'd be so kind to close this thread as it's not an issue.

**Comment by Spartacusbr** [comment]
@GreYzZ I think he means a little more information than that.

**Comment by mancmanGER** [comment]
What I meant is a bit more in "normal language", what people understand was has been fixed.

Sorry I am not a programmer.

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/commits/master
