### ISSUE TITLE
Older Version working better for me??

### ISSUE THREAD

**Issue by multik3d** [Ar1i/PokemonGo-Bot#2735]
So I tried to use the new versions with proxies and that didn't work out to great.
Issue with NEW: No pokestops, IP Bans (1 Bot)

v.1.0.8.4 works great for me (1 bot)

Note: I have changed my IP multiple times but the proxy one always gives me ban/no pokestops.

**Comment by bboylost** [comment]
just dont use the proxy with the latest bot it works fine. Because everyone is using the SAME proxy..... this is not hard to understand isnt it
