### ISSUE TITLE
VPN Issue with G-Mail

### ISSUE THREAD

**Issue by OldBlue13** [Ar1i/PokemonGo-Bot#2737]
![gmail](https://cloud.githubusercontent.com/assets/20956181/17570506/97b28c7a-5f44-11e6-89e9-c15197fa600a.png)-

Anyone encountered this? Link to g-mail acc takes me to a page that doesn't exist.

**Comment by Ar1i** [comment]
Dont use VPN, try Proxys. Proxys are not affecting the Google Login!
