### ISSUE TITLE
Pidgeys, Weedles, Caterpies and so on doesn't get transfered.

### ISSUE THREAD

**Issue by gateseee** [Ar1i/PokemonGo-Bot#2738]
Hello!

If i run the bot without keeping an eye on it, after a short time (about 1 hour), no new pokemon can get catched because the pokemon inventary is full. 

If i look at the pokemon inventory there are tons of Pidgeys, Weedles and Caterpies which doesnt getting transferred of the bot. But if i look at the log, i see that other rare pokemons directly get transferred after getting caught. 

How could i setup the Bot correctly that those Pokemon get transferred as it should. 

![1](https://cloud.githubusercontent.com/assets/11542432/17570612/673ca1bc-5f4d-11e6-9ae0-82e1bcbc54b3.PNG)
![2](https://cloud.githubusercontent.com/assets/11542432/17570611/6739f462-5f4d-11e6-97bd-bac67661c453.PNG)

**Comment by daledo** [comment]
Evolve them and get more XP then they transfer.

**Comment by PippoAe** [comment]
you need to check the pokemons that you would like the bot to evolve on the "Pokemon - to evolve" list.

**Comment by totolef** [comment]
I think you check the box who say "Keep Pokemons which can be evolved" ?

**Comment by gateseee** [comment]
Thanks for your answers. Where can i find this box totolef. 

Daledo and PippoAe - You mean i should tick the box for those weak pokemons so they get evolved and the rest transferred?

Br

**Comment by PippoAe** [comment]
Yes, the bot will start to evolve the pokemons you ticked in the list.
If you tick "keep pokemons that can be evolved" all the other pokemons that could be evolved will stay if they arent ticked in the "Pokemon - to evolve" list.

**Comment by gateseee** [comment]
Oh, i understand, the answer was so close and it seems like i was blind :)
It works now.. Thanks!
