### ISSUE TITLE
Confusing Message

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#2740]
Minor Bug
![escapecaught](https://cloud.githubusercontent.com/assets/20603254/17570810/9883be6e-5f56-11e6-9acb-49f96e299977.png)

**Comment by geebart1337** [comment]
That's fucking normal. 
It just means that the Pokemon left the ball by chance and didn't escaped yet and the bot caught it with the second try.

**Comment by Ar1i** [comment]
^
