### ISSUE TITLE
Start Walk From Default Location, not working?

### ISSUE THREAD

**Issue by Spartacusbr** [Ar1i/PokemonGo-Bot#2742]
I've tested both checked and unchecked and the bot always start walking from default location. Even when it crashes and reloads in 10 seconds. That's a recipe for getting softbanned, because after a crash you basically teleports to the default location in no time at all.

Also, "Start Walk from default location" has always been confusing to me, when you read the sentence, it implies you always want the bot to start walking from the "Default" location, therefore, the location you've selected on the map above, and ignore the "LastCoords.txt". So, logically if you want the bot to use "your last location" and NOT the "Default" location, the option should be unchecked.

Only that's not what happens, at least until the last server update, when the bot stopped working, "Start walking from DEFAULT location" checked, meant actually use "Last location" and unchecking it, meant always use Default location, even though that makes no sense.

On the current bot, it makes no difference anyways, because it always goes back to the default location, no matter what it says on LastCoords.txt or if the box is checked or not.

Thanks for everybody's work.

**Comment by zorndyke** [comment]
up for this issue

**Comment by Spartacusbr** [comment]
@zorndyke unfortunately the way github works it doesn't really goes back to the first page, can't "up" an issue post. But thanks for the support, and let's hope the Dev or one of the moderators read's this Issue.
