### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kevcussick** [Ar1i/PokemonGo-Bot#2743]
any way to add transfer all

like the dont catch option but catch and dont keep... so as not to fill up on pigeys ect but still collect xp + candies for catching... and free up some room in pokedex

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by KnewNothing** [comment]
That exists. Go to NOT TRANSFER and uncheck all of it. On the bottom it says max duplicate and set it to be 0. set Max IV to 100% and Max CP to 3000. That transfers out ALL pokemon
