### ISSUE TITLE
I have a bug / j'ai un beug

### ISSUE THREAD

**Issue by 4lex42** [Ar1i/PokemonGo-Bot#2744]
![image](https://cloud.githubusercontent.com/assets/20721353/17571128/37f9e64c-5f4f-11e6-8416-da8286f01c62.png)

it's my bot and i don't know how to resolve this. help me please / c'est mon bot et je ne sais pas comment resoudre sa aidez moi svp

**Comment by k3npachi** [comment]
i have the same with the last version

**Comment by xJustx** [comment]
Read this please: https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by SnxArste10** [comment]
Same for me

**Comment by jeremie152** [comment]
vous etes relou a poster pour rien cest normal look ca http://cmmcd.com/PokemonGo/ 
et met le en marque page

**Comment by jeremie152** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/222648408-Permissions-update
look this all soon account google is the best for botting

**Comment by geebart1337** [comment]
Had this issue as well. Worked after 10-20 minutes again. Propably kind of a softban for your IP.

**Comment by jeremie152** [comment]
quand cest instable taura rarement acces au pokestop juste att un peu

**Comment by 4lex42** [comment]
ok merci tout le monde

**Comment by jeremie152** [comment]
np^^

**Comment by jeremie152** [comment]
et surtout 1 seul bot sinon ban direct

**Comment by 4lex42** [comment]
et si je met un bot pour mon compte et un deuxieme pour le compte d'un pote sa marche ou ban aussi

**Comment by jeremie152** [comment]
ban apres 1 mn car cest ton ip

**Comment by 4lex42** [comment]
ha ok ba c'est pour sa alors merci pour ton aide

**Comment by jeremie152** [comment]
ya 2 jour on pouvait en mettre 3 maintenant que 1 et je te conseil pas dutiliser le proxy il marche pas

**Comment by jeremie152** [comment]
de rien par contre essaye ca du coup
ipconfig /flushdns
ipconfig /release
ipconfig /renew  
exit
tu met ca dans un fichier txt que tu renome en .bat ca tevitera de redemarrer la box

**Comment by 4lex42** [comment]
ok je vais faire sa

**Comment by jeremie152** [comment]
bon botting a toi^^ et bonne soiree

**Comment by jeremie152** [comment]
pour eviter le .bat met les ligne dans cmd direct 1 par 1

**Comment by SnxArste10** [comment]
Vous avez toujours des problèmes pour les pokéstops ?

**Comment by k3npachi** [comment]
i have test 3 proxi , and with this 3 i have error we cant find pokestop 

the proxy is dead, everyone will use the same

**Comment by jeremie152** [comment]
y proxy dont work then us got ban

**Comment by jeremie152** [comment]
oui toujour encore veridier la dessus attender que se soit vert
http://cmmcd.com/PokemonGo/

**Comment by jeremie152** [comment]
if you need a vpn free premium 
https://www.okayfreedom.com/en/
dl and install 
https://www.okayfreedom.com/specials/pcformat0816/of
give one adress email and go seek the code premium and insert in vpn and profit^^

**Comment by k3npachi** [comment]
![2016-08-10 23_26_29-](https://cloud.githubusercontent.com/assets/20956969/17571849/29468f26-5f52-11e6-9b8b-3828dc051bf4.jpg)

**Comment by jeremie152** [comment]
ca cest un ban^^

**Comment by jeremie152** [comment]
ipconfig /flushdns
ipconfig /release
ipconfig /renew 
enter one per one command in cmd and test more

**Comment by jeremie152** [comment]
or reboot box or use a vpn for change ip

**Comment by k3npachi** [comment]
yes but I tested 3 proxy , 2 I have not used and ban

**Comment by jeremie152** [comment]
normaly its only one now but im not sure

**Comment by jeremie152** [comment]
i think the proxy is only for protect us but not for have more bots

**Comment by k3npachi** [comment]
proxi dont protect from Web Rtc leak

**Comment by jeremie152** [comment]
ok then he is here for nothing^^

**Comment by jeremie152** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by jeremie152** [comment]
toujour down?

**Comment by jeremie152** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/12750555/17572876/2ad6542a-5f57-11e6-8c9b-46467aa6379f.png)

**Comment by jeremie152** [comment]
next have reboot modem

**Comment by jeremie152** [comment]
close thread
