### ISSUE TITLE
Wrong IV value the bot is using

### ISSUE THREAD

**Issue by Ragza** [Ar1i/PokemonGo-Bot#2746]
I found out an issue with the latest version.
In the picture you can see the bot not checking th IV value of the pokemons correct

![unbenannt](https://cloud.githubusercontent.com/assets/20943122/17571308/fd62bc42-5f4f-11e6-9fb9-2aaa306898ee.png)

My highest squirtle was IV 30,13% and not 52,76.
But the bot still transfered the CP230 IV52,76%.

Any suggestions about this?

**Comment by FerMedina86** [comment]
maybe in the next update , i hope so !

**Comment by wannaD1E** [comment]
[00:10:28] Caught Machop CP 147 IV 16,32% using ItemPokeBall got 210 XP.
[00:10:37] Transfer Machop CP 556 IV 72,22% (Best: 556 CP, IV 72,22%)

So bad((

**Comment by wannaD1E** [comment]
Guys! stop auto transfer....

**Comment by FerMedina86** [comment]
you have the  uncheck the option  i think is'nt working

**Comment by cyb0rg01** [comment]
Please provide any screenshots of your transfer settings, else we are not able to help you guys.

**Comment by FerMedina86** [comment]
!! wannaD1E commented 14 seconds ago
Guys! stop auto transfer.... !!

best option for now !!

**Comment by Ragza** [comment]
This are the settings I used
![setting](https://cloud.githubusercontent.com/assets/20943122/17572036/0150e592-5f53-11e6-98f0-dc1267602be1.jpg)

**Comment by arcy12** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20957974/17572089/1cb7418a-5f7d-11e6-8fe0-1824a5705b4c.png)

**Comment by pwnjke** [comment]
![1](https://cloud.githubusercontent.com/assets/20947780/17572046/0b6970b2-5f53-11e6-8ebc-0122ce3bcd99.png)
it was just a pidgey, but for example...

![2](https://cloud.githubusercontent.com/assets/20947780/17572107/4758fbb0-5f53-11e6-9820-425bc799a2ea.png)

**Comment by arcy12** [comment]
after turn off Tranfer fistlowIV

![screenshot_2](https://cloud.githubusercontent.com/assets/20957974/17572272/bbaeb78c-5f7d-11e6-9ebd-6cc001034ac6.png)

**Comment by cyb0rg01** [comment]
@pwnjke the bot is working fine for you, as far as I can see. You unchecked "TransferFristLowIV", which is pretty normal what your bot is doing. It drops your Pokemons selected by CP.

@Ragza it is pretty normal too. If the IV is equal, the bot keeps the Pokemon with the highest CP, I guess.

@arcy12 there are still your settings missing.

**Comment by Ragza** [comment]
@cyb0rg01 But I don t have a squirtle with a IV of 52,76% as you can see in the picture.
If the IV of the caught pokemon is higher than the pokemon you already have, it just shows the IV value of the new pokemon.
After that it is comparing the CP and transfer the lower one.... but the IV check of the existing pokemon is wrong.

**Comment by arcy12** [comment]
@cyb0rg01 problem solved, just turn off  "TransferFristLowIV"

**Comment by cyb0rg01** [comment]
@Ragza I just had the same issue on one of my accounts. Shame on me.

@Ar1i you should really take a look at this option again. I had a similar wired transfer. It dropped the high CP and IV Pokemon for less CP and IVs.

**Comment by pwnjke** [comment]
@Ragza @cyb0rg01 i think i understood something. sorry for bad english, but (best: cp xx iv xx) is NOT for one pokemon. the bot takes the best cp of existing pokemon AND the best IV, that can be from other pokemon in your bag. then the bot transfers that one, that has lower cp

**Comment by chusski** [comment]
@Ar1i  I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^
