### ISSUE TITLE
Can't power up/full power up on some Pokemon

### ISSUE THREAD

**Issue by geebart1337** [Ar1i/PokemonGo-Bot#2748]
I can power up/full power up Pokemon without problems. Having this issue the first time now and it's only happening when i try to power up Poliwrath. I have 12 Candy and more then enough star dust, but it say I don't have enough stardust and/or candy. Any other Pokemon is working fine when I power up.

![unbenannt](https://cloud.githubusercontent.com/assets/20949249/17571598/33b21eea-5f51-11e6-9a31-6de66ab1d93d.png)

**Comment by k756u** [comment]
it is not be the maximum for your level...?

**Comment by geebart1337** [comment]
weeeeeell. That is something I didn't thought about. Tried with my other Poliwrath and it worked.
Would be a nice feature if the bot would show how many % of the max CP is reached.

**Comment by k756u** [comment]
I also made me ^^ have a check on your phone

**Comment by NaveTK** [comment]
the maximum level you can power up a pokemon is your trainer level + 2... it appears you're level 32, that's why poliwrath is maxed out at 34 (for now)

**Comment by k756u** [comment]
exact'! :)

**Comment by geebart1337** [comment]
@NaveTK yes thats correct. good to know. But why is one of my Poliwrath (even the lower one displayed in the picture) after I upped him 3 times when he was lvl29 and now 35?! even my trainer lvl +3?

**Comment by NaveTK** [comment]
@geebart1337 that's a rare visual bug I expirienced before aswell, it's not actually level 35 (compare the CP to the level 34 one), it fixes itself after you power it up one more time
