### ISSUE TITLE
Hi, i have big problem with ip and proxy

### ISSUE THREAD

**Issue by Kaizhoul** [Ar1i/PokemonGo-Bot#2749]
i have a problem with my ip and my proxy, pokebot bug when i open this application 

![sans titre](https://cloud.githubusercontent.com/assets/20952066/17571699/910ab32c-5f51-11e6-8683-2fef5ff43e75.png)

**Comment by failcakee** [comment]
Just wait few seconds...

**Comment by jeremie152** [comment]
normal server login google unstable

**Comment by jeremie152** [comment]
and the proxy dont work if you need open more bot^^ you got ban 1 mn later

**Comment by Kaizhoul** [comment]
i wait and a list red with ligne of code apparess, older version is good but the new is bug :/

**Comment by jeremie152** [comment]
http://cmmcd.com/PokemonGo/ normal server unstable

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
