### ISSUE TITLE
i get banned???

### ISSUE THREAD

**Issue by ladows** [Ar1i/PokemonGo-Bot#2750]
i have error not pokestop in a range.
[http://imgur.com/a/t1roO](url)

**Comment by kevcussick** [comment]
servers down again...

**Comment by jeremie152** [comment]
http://cmmcd.com/PokemonGo/

**Comment by beasttry** [comment]
im having same problem!

**Comment by cyb0rg01** [comment]
It seems like, that the proxy is already in use. On my set up, the but is running perfectly at the moment.

**Comment by Saonji** [comment]
for me everything works fine

**Comment by beasttry** [comment]
its not working

**Comment by ladows** [comment]
http://imgur.com/J9ttTeE

**Comment by elenex23** [comment]
I dont use any proxy but I can imagine if you do not have your own private proxy, this maybe an issue.

**Comment by beasttry** [comment]
we got hit by the banwave!

**Comment by jeremie152** [comment]
log ptc is up but google no and for proxy you can disable in the setting or he continu next you open console^^

**Comment by cyb0rg01** [comment]
Using Google Server to login.

![working](https://cloud.githubusercontent.com/assets/20904908/17572113/4d358940-5f53-11e6-98ec-5a9c6aacf49a.png)

**Comment by ladows** [comment]
http://imgur.com/MYszsdQ i have disable proxy ut not work

**Comment by beasttry** [comment]
im using google and it still dont work

**Comment by jeremie152** [comment]
hehe gj^^ http://www.mmoserverstatus.com/pokemon_go

**Comment by ladows** [comment]
I tried to use two storied account and maybe that's the problem ?

**Comment by jeremie152** [comment]
maybe only one instance for dont get ban

**Comment by beasttry** [comment]
time to panic

**Comment by PureDizzi** [comment]
i can log in my the app but i cant find pokestops on the bot. They change API again?

**Comment by jeremie152** [comment]
no cyborg work its only unstable some have luck other no^^ me exemple dont work^^

**Comment by beasttry** [comment]
USA servers down GG

**Comment by jeremie152** [comment]
xd a lot bot!!!!! the rest c'ant connect hahahaha

**Comment by jeremie152** [comment]
538 ms

**Comment by jeremie152** [comment]
only cyborg work? u status?

**Comment by cyb0rg01** [comment]
Well, it is working for me @jeremie152

**Comment by jeremie152** [comment]
y but you only or other work too?

**Comment by ladows** [comment]
all are sure i'm not get ip banned?

**Comment by jeremie152** [comment]
no me too its strange before today log in fast

**Comment by jeremie152** [comment]
profit for reboot box good idea for wait
me too then ^^

**Comment by cyb0rg01** [comment]
Just try to restart your router / modem to fetch an new IP from your ISPs guys or be a bit patient.

I gonna go to sleep now.

**Comment by hazmad** [comment]
it's not you it's their servers. It happened earlier today for about a hour

**Comment by jeremie152** [comment]
gn cyborg

**Comment by jeremie152** [comment]
gn  cyborg^^

**Comment by jeremie152** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/12750555/17572884/350f03a6-5f57-11e6-99ff-2daf00c1b962.png)

**Comment by jeremie152** [comment]
next have reboot modem

**Comment by jeremie152** [comment]
close thread

**Comment by xJustx** [comment]
Please look into the closed issues.
