### ISSUE TITLE
Sorry, i have a new question :) 

### ISSUE THREAD

**Issue by Kaizhoul** [Ar1i/PokemonGo-Bot#2751]
If I put several account pokebot with proxy, that would work, or i wait, because i need to several account 
but he's write "we're find pokestop of 5000 range blablabla" and it's a problem for me and i asked has my friend and with several account he bug 

Thank you for your hard work

**Comment by Xcutioner** [comment]
Getting same error wait for a fix.

**Comment by chickeflonoah** [comment]
ALWAYS THE SAME QUESTION, WHATS GOING ON

**Comment by xJustx** [comment]
Please look into the closed issues. Thank you.
