### ISSUE TITLE
pogo file cant be loaded

### ISSUE THREAD

**Issue by itzjaydon** [Ar1i/PokemonGo-Bot#2752]
![image](https://cloud.githubusercontent.com/assets/20823634/17572274/73501724-5f4b-11e6-9f79-0ee7d6422653.png)

**Comment by shadowahs** [comment]
where did you put the codes in? I've been looking for a command window to put in Pogo files but i cant

**Comment by xJustx** [comment]
Please redownload the bot, set up him again and start him.

**Comment by shadowahs** [comment]
@xjustx where do you input those codes?

**Comment by xJustx** [comment]
which codes @shadowahs ?

**Comment by shadowahs** [comment]
The POGOprotos were meant to be input somewhere correct? Where do those files go to implement them into the bot?
If i'm misinterpreting the way they work, please tell me

**Comment by Ar1i** [comment]
download and put it in a folder
