### ISSUE TITLE
How to i put a proxy to use on the bot?

### ISSUE THREAD

**Issue by shadowahs** [Ar1i/PokemonGo-Bot#2753]
I can't seem to find out how to use the proxy, what goes under the proxy IP and proxy Port boxes?

The bot catches pokemon fine, but the actual app, everything runs away after one ball

**Comment by k3npachi** [comment]
last version of bot, in settings there is a proxy box

**Comment by shadowahs** [comment]
I know this, but what goes inside the "HTTPS Proxy IP" and "Proxy Port" boxes?

**Comment by k3npachi** [comment]
i dont understand your question sorry

**Comment by shadowahs** [comment]
![image](https://cloud.githubusercontent.com/assets/20916831/17572535/a72e0988-5f1a-11e6-99d2-1809bbe27cd9.png)
what goes in those two boxes?

**Comment by elTrollKingPS** [comment]
same bro, I dont' know

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
