### ISSUE TITLE
Two bots on same IP banned

### ISSUE THREAD

**Issue by AuroraHD** [Ar1i/PokemonGo-Bot#2756]
How many bots does it take to get IP banned? I heard it was 4 or more, but I've tried two and a couple seconds later, both the bots give the message that no pokestops are in range of 10000 m. VPNs don't work as it gives a really long message, and no free proxies are working.

**Comment by shadowahs** [comment]
At the moments, 2 get banned

**Comment by AuroraHD** [comment]
Oh, alright then. Will the number of bots per IP be changed?

**Comment by shadowahs** [comment]
I'm not sure, but I ran two bots, me and a friend, and my IP was banned. Just for same measure, i turned my router off for a few hours, not sure if it helped, but on the Pokemon Go app, pokemon still run away after one throw. However on the bot, everything is caught just fine

**Comment by AuroraHD** [comment]
I've read somewhere if you go to a pokestop and flip the coin and press the 'x' and doing it over at least around 40 times, you'll be able to catch pokemon and visit pokestops on the phone

**Comment by dreyan1** [comment]
What do you do if z get IP banned? I think i am IP banned right now :S

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
