### ISSUE TITLE
Still cant find pokestops

### ISSUE THREAD

**Issue by Safti54** [Ar1i/PokemonGo-Bot#2757]
My bot still cant find pokestops and softbannes everywhere why does this happen i have the newest version of the bot but it still wont work, it doesent work in sidney in SanFransisco, NY, Zurich and Milano

**Comment by beasttry** [comment]
same here idk whats going on

**Comment by xJustx** [comment]
How much bots are running for you?
Are you using a proxy?

**Comment by Safti54** [comment]
just one bot and yeah with or without proxy it doesent matter it doesnt find pokestops

**Comment by lucas2107** [comment]
Hey, try using this proxy ( working for me ): 

85.109.75.244
8080

**Comment by beasttry** [comment]
#2762 click it(works for me)

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
