### ISSUE TITLE
Anzeigen welches Pokemon geschlüpft ist?

### ISSUE THREAD

**Issue by SebiWolze** [Ar1i/PokemonGo-Bot#2759]
Ist es korrekt, dass das geschlüpfte Pokemon nicht angezeigt wird?
Ich laufe derweil mit 8kmh, vorhin wurde ein 5km Ei gebrütet, nachdem der Bot die Meldung machte "noch 0,3xxxxxx km" war die nächste "Eiermeldung" "added next 5km Egg" - es gab keine Meldung was geschlüpft ist, und ob überhaupt was geschlüpft ist.

Da ich kein Coder bin, stellt sich mir die Frage ob dies so korrekt ist, oder es sich hier um einen Bug handelt.

Danke vorab.

**Comment by PippoAe** [comment]
Scheint ein bug zu sein.
Es sollte eine Meldung erscheinen mit ""Egg hatched and we got a XX CP: XX MaxCP: XX  Level: XX IV: XX.

**Comment by AlpaEZPZ** [comment]
Bezüglich dem brüten der eier,
kann es sein das nur 5km eier genommen werden ? oder ist das ein krasser zufall bei mir ?

**Comment by PippoAe** [comment]
Der Bot setzt die langen Eier in die 3xInkubatoren und die kurzen in den unlimitierten, mit der Ausnahme dass er die langen bevorzugt falls du nur den unlimiterten hast.

Hast wohl nur den unlimiterten, dann rackert er erst durch die langen Eier ;)

**Comment by AlpaEZPZ** [comment]
Du scheinst dich recht gut auszukennen, kannst du mir vielleicht noch sagen warum die %(IV) Werte bei manchen pokemon bei mir immer schlechter werden ? mein bestes Enton ist mitlerweile auf 17% nurnoch.
Ich hab die markierung bei dem kästchen, das er IV höher bewerten soll als CP gesetzt.

sorry für die abweichung vom Hauptthema ich bitte um absolution

**Comment by PippoAe** [comment]
Hab mir eben Visual Studio installiert damit ich den Code etwas besser studieren kann.
Finde mich noch nicht ganz zurecht aber lese mich langsam ein.

Zu deiner Frage:
Habe in einem anderen Issue(#2705) gelesen, dass der Bot in der neusten Version eventuell die falschen Pokemon verschickt wenn die Funktion "TRANSFERFIRSTLOWIV" aktiviert ist, diese also besser erstmal sein lassen.

**Comment by globsch** [comment]
das stimmt so nicht, der bot macht genau das was er soll, nur nicht das was du evtl. willst ;-)

**Comment by AlpaEZPZ** [comment]
Ich würde gerne das er die pokemon mit dem höheren IV wert behält, allerdings müsste das zwangsläufig dazu führen das die IV% Werte besser werden.
Das tun sie aber nicht sondern werden vereinzelt sogar schlechter.

**Comment by deface0x2** [comment]
Kann diesen Bug auch nicht bestätigen. Bei mir kommt eine Meldung welches Pokemon geschlüpft ist.

**Comment by SebiWolze** [comment]
BItte beim Thema bleiben, Danke!

**Comment by SebiWolze** [comment]
Gerade entdeckt, dass soeben angezeigt wurde welches Pokemon geschlüpft ist.
