### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#2760]
Hab ein Problem und zwar lasse ich den bot laufen und nach ca 1 - 2 minuten bekomme ich einen softban 
nachdem ich diesen entfernt habe bekomme ich nach 1-2 minuten wieder einen :/ 

weiss wer woran es liegt und wie ich den fehler beheben kann nutze kein Proxy

**Comment by Safti54** [comment]
ich ba das problem auch schon seit geräumiger zeit und bei mir findets auch keien Pokestops mehr..:(

**Comment by Flashnasty** [comment]
dann hast du einen IP Ban dauert ca 30 min bis 1 Stunde dann ist er weg dann findest du wieder pokestops ;) trotzdem finde ich es irgentwie sehr komisch dass ich nach 1-2 minuten direkt wieder einen softban bekomme :/ muss ja irgentwo drann liegen

**Comment by SebiWolze** [comment]
IP Ban halt, nutz einen Proxy, ändere deine IP (Router Neustart) und gut.

**Comment by Flashnasty** [comment]
schon gemacht und trotzdem bekomme ich nach 1 - 2 min einen Softban :/ ein IP Ban habe ich nicht sonst würde er ja nicht 1-2 min pokestops abfarmen und Pokemon fangen ;)

**Comment by Safti54** [comment]
wie benutze ich proxy kann mir das einer erklären ? :)

**Comment by Flashnasty** [comment]
Ar1i hat eine Liste im Pokemon Bot drinne musst du nur drauf klicken ;) dann siehst du die proxy IP und den Port eintragen specihern fertig :D

**Comment by Flashnasty** [comment]
hab nur ich dass problem dass ich nach 1-2 minuten wo der bot normal läuft direkt einen softban nach dem anderen bekomme ? :O

**Comment by Safti54** [comment]
nei hab ich auch. @Flashnasty wo finde ich die liste ?

**Comment by cyb0rg01** [comment]
Welche Settings hast du denn eingestellt? - Lass den Bot vielleicht etwas langsamer laufen; so mit 25 - 50 Km/h

**Comment by Flashnasty** [comment]
lasse den schon ganze zeit auf 21 KmH laufen :/ 
also daran kann es nicht liegen settings alle standard

**Comment by Flashnasty** [comment]
die liste findest du im bot wenn du auf proxy klickst oben in der liste da steht nen link dann darauf klicken @Safti54

**Comment by xJustx** [comment]
@Flashnasty Wie viele Bots hast du gleichzeitig am laufen?

**Comment by Safti54** [comment]
proxy funktioniert net bei mir..

**Comment by Flashnasty** [comment]
nur 1 :/

**Comment by Flashnasty** [comment]
über proxy geht gar nix ausser das er die pokemon liste lädt und ohne proxy direkt nach 1-2 min softban und jetzt sogar IP Ban heisst halbe stunde wieder warten heute dass 3 mal ://

**Comment by Safti54** [comment]
hab mein modem rebootet proxy laufen lassen das ganze etwa 5 mal gemahct in den letzten 35 minuten aber nichts hat funktioniert nichts rein gar nichts

**Comment by Flashnasty** [comment]
bei mir auch nicht :/ niantic scheinnt wohl langsam zu checken wie die uns rauskicken können :/

**Comment by RoterKnecht** [comment]
habe das selbe problem

**Comment by xJustx** [comment]
Sehr merkwürdig,
Ich habe meinen Bot jetzt seit 10 Minuten ohne Probleme am laufen.
Es muss also an irgendwas anderem liegen..

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
