### ISSUE TITLE
Can't find any pokestops (READ)😤😱😨😤😩

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#2762]
BOTS=NOT WORKING(USING GOOGLE & LOCATED IN USA)
SERVERS=ARE UP
API STATUS=MIGHT BE DOWN
SOFT BANNED=STRONG MAYBE
IP BAN=NOT 100% SURE
FORCE UNBAN ON BOT=DON'T WORK CAN'T FIND POKESTOPS
QUESTION=Who's Bot is working right now and what country are you located at and are you using PTC or GOOGLE?
PROBLEM SOLVED=REBOOT UR MODEM :) ENJOY😃😬😲🕵

**Comment by SebiWolze** [comment]
Mine, germany.

**Comment by cyb0rg01** [comment]
Mine is working. Germany and Google Auth. Did you tried to restart your router / modem to fetch an new IP from your ISP?

**Comment by Kidnub** [comment]
mine works fine XD np google works like a good beer _XD

**Comment by shadowahs** [comment]
Mine works fine, USA

**Comment by beasttry** [comment]
weird,mine can't find any Pokestops in range of 1000m and it restarts in 10 seconds and then repeats.

**Comment by shadowahs** [comment]
Where did you set it for? Mines the default location on Central Park, try hitting the force unban button

**Comment by shadowahs** [comment]
And try setting it for 5000km

**Comment by beasttry** [comment]
i hit the force unban it does nothing.i set the location inside my town 50km/h

**Comment by shadowahs** [comment]
Set it to somewhere with an abundance of pokestops

**Comment by xJustx** [comment]
@beasttry Are you using a proxy?

**Comment by beasttry** [comment]
oh trust me it has alot of pokestops and no im not using a proxy,i heard it doesnt work

**Comment by xJustx** [comment]
How much bots are running?

**Comment by beasttry** [comment]
normally just 2

**Comment by xJustx** [comment]
Please try it with 1 bot + use a proxy.

**Comment by beasttry** [comment]
i tried a VPN and it didnt work

**Comment by Ushushu** [comment]
1 bot running atm, France.
Got the same problem and it's solved after a single modem rebooting.

**Comment by kevcussick** [comment]
uk
google login
1 bot
vpn / proxy / isp ip
not working

**Comment by beasttry** [comment]
i will try the modem rebooting sec guys.........😱

**Comment by k3npachi** [comment]
In France we have fixed IP, reboot the box doesn't work, ip stay the same

**Comment by beasttry** [comment]
REBOOTING WORKED!!!!!YAY GUYS!!😃😬😲🕵

**Comment by hades2795** [comment]
same me in indonesian i cant pokestops 5000m and im done to restart pc and modem

**Comment by beasttry** [comment]
@hades2795 reboot your modem steps=disconnect your modem leave it off for 2 minutes and plug back in!enjoy

**Comment by k3npachi** [comment]
@beasttry no in france we have a fixed IP

if you reboot the modem that does not change anything

**Comment by Dinja1990** [comment]
@k3npachi i´ve this too, have fixed ip :(

**Comment by beasttry** [comment]
it just stopped working and its happening again ................greaaaaaaaat
