### ISSUE TITLE
summary in my console (it's possible?)

### ISSUE THREAD

**Issue by emilie253** [Ar1i/PokemonGo-Bot#2763]
Hello. Often, i run the bot and i go to see my tv ^^.
But when i come back, i would like to have a summary (each pokemon do i have caught, who i have invoke in my eggs...) but my console is very small (maybe 50 lignes).

It's possible to up my console to use "search" and to see what i want after 1 hour???
it's not en suggestion for the bot, just a request for ma console ^^

Thank you for your help.

**Comment by totolef** [comment]
There is a log file in the Config folder. You can see all logs and search in with a good text editor.

**Comment by emilie253** [comment]
it's not very convenient, but it works. ty ;)

**Comment by xJustx** [comment]
If you have a suggestion you can post it here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by emilie253** [comment]
it was not en suggestion, juste for some monsters and eggs. config folder it's good ;)
