### ISSUE TITLE
bot via proxy are dead

### ISSUE THREAD

**Issue by k3npachi** [Ar1i/PokemonGo-Bot#2765]
I think use bot with proxy is dead 

i have 3 accounts, i have use 1 account with my VPN and the 2 others with proxy and 2 with proxy stops working

proxy dont protect from Web Rtc leak, Niantic = google, they have the means to bypass this breach and see our IP behind a proxy

![2016-08-10 23_26_29-](https://cloud.githubusercontent.com/assets/20956969/17572659/05abd69e-5f56-11e6-8f9c-343b4f8a9f72.jpg)

**Comment by geebart1337** [comment]
I can't use Proxies either. Maybe you need a private proxy cause several people are using the same public and free proxy.

**Comment by k3npachi** [comment]
maybe, but I do not want to pay for a proxy

**Comment by xJustx** [comment]
^
