### ISSUE TITLE
Auto transfer broken?

### ISSUE THREAD

**Issue by ingmar3** [Ar1i/PokemonGo-Bot#2766]
I have set in both checkboxes, only hold 1 copy  unless 1800 or more CP or 95% IV

e.g. this will stay there

![image](https://cloud.githubusercontent.com/assets/20929799/17572697/3802fd20-5f56-11e6-9b20-35239497abe5.png)

also happens for Zubat, Magnemite, NidoranFemale, Poliwag, Ratata, Spearow and Pidgey

**Comment by Kidnub** [comment]
no no its no bug check your on start on the check boxes (keep pokemon which can be elvol) uncheck it and start the bot again XD

**Comment by starscream151** [comment]
did you ticked this?
![ucheeckntitled](https://cloud.githubusercontent.com/assets/20950801/17572902/3a548a14-5f81-11e6-9b9e-a66493ab2193.png)

**Comment by ingmar3** [comment]
Solved indeed, had it checked. sorry
