### ISSUE TITLE
Error starting bot!

### ISSUE THREAD

**Issue by tomo101** [Ar1i/PokemonGo-Bot#2767]
Having this error every time I open it. I have tried re-installing the program 3-4 times.... Still getting this same thing. Please help!!!

There was an error uploading screen shot:
So I uploaded it to imgur...
https://imgur.com/a/JLHuQ

**Comment by lucas2107** [comment]
Missing the encrypt.dll file, reinstall

**Comment by xJustx** [comment]
^
This would fix it.
