### ISSUE TITLE
No Pokestops Within 5000 Metres

### ISSUE THREAD

**Issue by kcalcitas** [Ar1i/PokemonGo-Bot#277]
Hi,

Tried running the bot where I usually run it (default location) to get pokestops and it seems like they are all gone? Screenshot below - thank you for your help! I downloaded the update updated 10  minutes ago. 

<img width="638" alt="screen shot 2016-07-29 at 12 57 04 pm" src="https://cloud.githubusercontent.com/assets/14828758/17261787/252819b2-55c7-11e6-8e35-0c5b04af384c.png">

**Comment by Kelendris** [comment]
You must wait 20 min. because you have a Softbann :)

**Comment by kcalcitas** [comment]
Ah thanks! I thought that a different message popped up for soft bans but seems like this is also a soft ban.

Thanks!
