### ISSUE TITLE
transfer and cp reader is wrong.

### ISSUE THREAD

**Issue by elenex23** [Ar1i/PokemonGo-Bot#2770]
[![Capture1.png](https://s9.postimg.org/hn3gt2gb3/Capture1.png)](https://postimg.org/image/yauyvkb2j/)

[![Capture.png](https://s10.postimg.org/agpp7zsi1/Capture.png)](https://postimg.org/image/qeyey4mpx/)

These are the same pokemon but the cp is reading different. Also I don't believe the lowest iv duplicate pokemon is being transferred. CP does not matter AT ALL, please fix bot to only transfer pokemon based on iv and please ignore cp completely. 
Thank all of you for all the hard work.

**Comment by xJustx** [comment]
#2705
