### ISSUE TITLE
i'm have ip ban how to resolve?

### ISSUE THREAD

**Issue by ladows** [Ar1i/PokemonGo-Bot#2771]
i have gotta a ip ban have to resolve this?
i have tried to restart modem not work
![ban 2](https://cloud.githubusercontent.com/assets/20957908/17573548/77d09de0-5f5b-11e6-9691-260f38bbdae6.jpg)

**Comment by beasttry** [comment]
#2762 click it

**Comment by joeykyubi** [comment]
on the pokemon list gui try pressing the force unbann button

**Comment by Safti54** [comment]
Me either i rebootet my modem plus tryed it on proxy restartet the modem nothing works it still cant find any pokemon and poestops...

**Comment by jeremie152** [comment]
reboot modem and forget proxy exist^^

**Comment by lucas2107** [comment]
3/4 of proxies are not working. No pokestop found is an ip ban, try using vpn and run only 1 bot/IP !

**Comment by jeremie152** [comment]
yeah vpn run only 1 bot and forget the PROXY he work only for have a lot problem^^

**Comment by jeremie152** [comment]
https://www.okayfreedom.com/en/
dl this and install
next go to the link
https://www.okayfreedom.com/specials/pcformat0816/of
add you email in the case for
and go to the mail for take the code premium insert in icone okayfreedom and profit gn

**Comment by ladows** [comment]
i have restart the modem/router but not work.i tried spam a unban but not work

**Comment by ladows** [comment]
i tried the program but give me some error in pokemon go bot

**Comment by bboylost** [comment]
@jeremie152  thanks for the VPN, one question, can we bot more than 1 bot with this VPN?

**Comment by bboylost** [comment]
@ladows restarting the modem/router ALWAYS work,  just shut down your modem/router for a good 10 = 15 mins. It will 100% work

**Comment by beasttry** [comment]
@bboylost i tried that and it didnt work

**Comment by jeremie152** [comment]
no only one instance bot^^ and np

**Comment by jeremie152** [comment]
maybe need restart pc dont remember^^

**Comment by Criispey** [comment]
The Programm works perfectly

**Comment by Kaizhoul** [comment]
jeremie create account pokemon club

**Comment by jeremie152** [comment]
yes xd its more sure i think^^

**Comment by elenex23** [comment]
the vpn allowed my ptc account to snipe, but not my google account. when vpn is on i cannot open pokebot successfully

**Comment by phodem** [comment]
when that happen, wait 1 hour and relog again, it will work. happened to me multiple time. Don't try anything funny, just wait exact 1 hour.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
