### ISSUE TITLE
Suggestion : Pokeball Choice

### ISSUE THREAD

**Issue by Saccarai** [Ar1i/PokemonGo-Bot#2773]
First, congratulation for all your good work, really amazing and very appreciate (Second, sorry for my bad english).

I have a suggestion about the pokeball choice the bot makes when it's catching pokemon. 

The choice of the ball is made based on the CP value. I don't know exactly the value but it's about >250, the bot use a pokeball, >650 a greatball and >1000 a ultraball. 

I think it's not the most efficient way to make the choice. I'm currently farming the great Charmander and they usually escape because the bot is using normal pokeball... But it's not easy to catch them with pokeball, great or even ultraball seem better because Charmander have a low probability (of catching)percent. 

I suggest that the choice would be make by this value (probability) and not CP's value. Things like >80%, use a pokeball, >30 greatball and under 30 a ultraball.

I don't know if my suggestion is legit but I think it could be a pretty thing to do to make the catching more efficient, and if it's technicly possible.

However, thanks for reading and thanks for your great work.

**Comment by emilie253** [comment]
suggestion isn't here :)
