### ISSUE TITLE
READ THIS BEFORE POST FOR NOTHING vpn free premium + link status server google and other

### ISSUE THREAD

**Issue by jeremie152** [Ar1i/PokemonGo-Bot#2776]
for softban when you pass near the pokestop but dont take use this 
https://www.okayfreedom.com/en/
dl this and install
next go to the link
https://www.okayfreedom.com/specials/pcformat0816/of
add you email in the case for
and go to the mail for take the code premium insert in icone okayfreedom and profit 

when you detect with the bot 0 pokestop its a softban or just unstable server look this
http://www.mmoserverstatus.com/pokemon_go

plz limit thread look if a thread exist for the problem before post a new gn.

**Comment by beasttry** [comment]
is this the vpn

**Comment by jeremie152** [comment]
yeah free premium

**Comment by elenex23** [comment]
just tried this, didnt work. thanks though
