### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by lucas2107** [Ar1i/PokemonGo-Bot#2777]
This happend sometimes... not a critical error because the bot restart ^^

![screenshot_1](https://cloud.githubusercontent.com/assets/11612016/17574242/dfb474a0-5f5f-11e6-83f0-0f6adc9ac7a0.png)

**Comment by emilie253** [comment]
same ;)

**Comment by Ar1i** [comment]
you can ignore that, but it should be fixed
