### ISSUE TITLE
Issue with bot transfering highest pokemon instead of lowest

### ISSUE THREAD

**Issue by 4ndr0id19** [Ar1i/PokemonGo-Bot#2778]
As shown in the attached pictures, the bot caught an evee and it was not  the highest in my inventory. instead of transfering the lowest evee, it transfered my highest and kept the lowest one it just caught.

![pokemon go transfer issue](https://cloud.githubusercontent.com/assets/20684547/17574238/29c85d58-5f25-11e6-8411-f08a94fb2919.png)
![pokemon go transfer issue1](https://cloud.githubusercontent.com/assets/20684547/17574239/29c8d0c6-5f25-11e6-9114-9a40c4fc4c89.png)

**Comment by emilie253** [comment]
transferfirstlowIV bug, deactived it

**Comment by lucas2107** [comment]
Uncomment TransferFirstLowIV.

Working fine with this configuration

![screenshot_2](https://cloud.githubusercontent.com/assets/11612016/17574285/29213696-5f60-11e6-81df-fbe1f1e44fa8.png)

**Comment by chusski** [comment]
TransferFirstLowIV not working welll :(

**Comment by lucas2107** [comment]
Default settings transfer lowest CP

**Comment by 4ndr0id19** [comment]
Not working well? more like working exactly the opposite as it should. -.-
