### ISSUE TITLE
Still can't find pokestops

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#2779]
![image](https://cloud.githubusercontent.com/assets/20891276/17574306/b312f956-5f25-11e6-8764-fefbb1d293cc.png)
proof

**Comment by lucas2107** [comment]
Maybe IP banned, how many bots do you run?

**Comment by beasttry** [comment]
i run one and my brother runs one also sooo 2...

**Comment by lucas2107** [comment]
Okey, so it's 1 bot/ IP.

Restart your router and only run 1 bot. Others bots will run with a proxy but... 3/4 of proxys are not working.

**Comment by jeremie152** [comment]
softban add this line in command cmd run as admin
ipconfig /flushdns
ipconfig /release
ipconfig /renew 
enter this command one per one 

reboot box dont forget wait 30 seconde before reconnect the modem and add this line before

**Comment by beasttry** [comment]
no proxy is working..........what do i do

**Comment by coffeexp** [comment]
same here!! even using proxy.. :(

**Comment by astrostra** [comment]
Even by running a VPN i still get the same thing, so no, this has nothing to do about an iPBan.

(I'm only running 1 bot.)

**Comment by coffeexp** [comment]
@astrostra might be an ip ban.. coz if i change to my other isp, i dont have any issue on my bot.. the only issue is that my 2nd isp is having intermittent dc so my grinding/leveling is a little slow.. :(

**Comment by EvilEmpireDriftTeam** [comment]
With the program http://hideme.ru/ changed the IP and everything. bot works!!!! all found, pokemon catches, so that leaves IP banned still
