### ISSUE TITLE
Findet keine Pokestops ?

### ISSUE THREAD

**Issue by RoterKnecht** [Ar1i/PokemonGo-Bot#2780]
Hatte den Bot circa eine Stunde laufen , aufeinmal findet er keine pokestops mehr und fängt auch keine pokemon. jedes mal steht da das er in 5000m keine pokestops findet. Was muss ich machen ? Anderer Account geht auch nicht .

**Comment by lucas2107** [comment]
In english ? pls :)

**Comment by xwolfonx** [comment]
server pokermon is the problem

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
