### ISSUE TITLE
Incubation Error

### ISSUE THREAD

**Issue by lucas2107** [Ar1i/PokemonGo-Bot#2781]
Error about incubation, idk what happend but the bot still running.
![screenshot_3](https://cloud.githubusercontent.com/assets/11612016/17574387/2416a0ea-5f61-11e6-844e-91fd8ff7e0c4.png)

**Comment by rhotacist** [comment]
I got a question... how can i eclosionate my eggs withou using the blue ones? only the infinited... (sorry for my english)

**Comment by Ar1i** [comment]
should be fixed
