### ISSUE TITLE
SkipLastFieldCalled error in the bot

### ISSUE THREAD

**Issue by derekurizar** [Ar1i/PokemonGo-Bot#2784]
I don't know why happen this
![screenshot_5](https://cloud.githubusercontent.com/assets/20921579/17574393/200bf678-5f1e-11e6-8265-513bd80caa21.png)

**Comment by EvilEmpireDriftTeam** [comment]
тоже самое

**Comment by monoxacc** [comment]
I think Niantic blacklisted your server ip range. For example Amazon AWS is blacklisted, too.
FeroxRev/Pokemon-Go-Rocket-API#103
