### ISSUE TITLE
[Error] I get this error using my private proxy

### ISSUE THREAD

**Issue by magiccube007** [Ar1i/PokemonGo-Bot#2786]
If i use my private proxy i think the authentication isn't working, cause i everytime i try it with a puplic one it works till someone else uses the proxy too and i get ipbanned.
Btw THE PROXY WORKS 100%
![unbenannt](https://cloud.githubusercontent.com/assets/20615827/17574522/327415ea-5f62-11e6-9432-f0e9a1c0e708.png)

**Comment by beasttry** [comment]
where do you find your proxy

**Comment by magiccube007** [comment]
i host it on my friends server

**Comment by lucas2107** [comment]
Proxy isn't working or is not HTTPS

**Comment by magiccube007** [comment]
it is https and it is working on my phone in pokemon go

**Comment by EvilEmpireDriftTeam** [comment]
bane ip yes

**Comment by lucas2107** [comment]
Your server can't connect to google servers.

Server fault.

**Comment by EvilEmpireDriftTeam** [comment]
With the program http://hideme.ru/ changed the IP and everything. bot works!!!! all found, pokemon catches, so that leaves IP banned still
