### ISSUE TITLE
I do not think that's its just IP ban

### ISSUE THREAD

**Issue by k3npachi** [Ar1i/PokemonGo-Bot#2789]
My pokemon account with Google is still banned, and I just noticed on my smartphone there is a mistake I am no longer logged

![screenshot_2016-08-11-01-30-16](https://cloud.githubusercontent.com/assets/20956969/17574722/efd49208-5f63-11e6-9dea-135820ed8e0c.png)

I think it's not just IP but the linked account, they send a ban on the account because it deconnect my account on smartphone

**Comment by immoempe** [comment]
No, this problem sometimes happen, just login again, it's something with your google configuration (less secure apps)

**Comment by Waiiim** [comment]
Happens to me all the time mate, si tu essayes de lancer le bot maintenant avec sa nouvelle version, il va te demander de sécuriser ton compte google justement

**Comment by k3npachi** [comment]
I have 4 google accounts, and it does that only with the google account pokemon
