### ISSUE TITLE
Detection Rate on Pokestop with Boost to low

### ISSUE THREAD

**Issue by Zapper2k3** [Ar1i/PokemonGo-Bot#279]
I play in real with the pokemon app , and get 4 -5 pokemon at the boosted spots. With the Bot i finding verry few pokemons

**Comment by Hitra** [comment]
yea true, slowing down to 2 km can make the difference i guess

**Comment by Zapper2k3** [comment]
i only walk in 200m around the spawn spot. it is possible to do an feature which allows to wait on an individual time maybe adjustable with an timer ? 

usally it takes 3 -4 Seconds for an Pokemon to spawn in the area in Germany.

**Comment by Zapper2k3** [comment]
I walked around my hole city here spawns nothing around 4km 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Hitra <notifications@github.com> Datum: 29.07.16  22:12  (GMT+01:00) An: Ar1i/PokemonGo-Bot <PokemonGo-Bot@noreply.github.com> Cc: Zapper2k3 <Zapper2k3@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [Ar1i/PokemonGo-Bot] Detection Rate on Pokestop with Boost to low
  (#279) 
yea true, slowing down to 2 km can make the difference i guess

**Comment by Zapper2k3** [comment]
Sorry wrong recipient 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Hitra <notifications@github.com> Datum: 29.07.16  22:12  (GMT+01:00) An: Ar1i/PokemonGo-Bot <PokemonGo-Bot@noreply.github.com> Cc: Zapper2k3 <Zapper2k3@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [Ar1i/PokemonGo-Bot] Detection Rate on Pokestop with Boost to low
  (#279) 
yea true, slowing down to 2 km can make the difference i guess

**Comment by Moresp4m** [comment]
I am having a similar problem, when I play live (or via spoof) at this location (-33.8590524438994,
151.213122010231) there are 4 Pokestops almost on top of each other and they are constantly lured. 

This means the Pokemon spawn rate is crazy (3-4 always up) yet the bot does not find anywhere near this amount (It hardly finds any, maybe 1-2 every know and again).

I have set the bot to only 150m and speed to 1km/h but still nothing.
