### ISSUE TITLE
Download hideme.ru works with all!!!

### ISSUE THREAD

**Issue by EvilEmpireDriftTeam** [Ar1i/PokemonGo-Bot#2790]
Download hideme.ru works with all!!!
With the program http://hideme.ru/ changed the IP and everything. bot works!!!! all found, pokemon catches, so that leaves IP banned still

**Comment by k3npachi** [comment]
its a simple VPN, you can run only 1 bot

**Comment by elenex23** [comment]
it wants me to buy or something? this vpn shit isnt fixing anything
