### ISSUE TITLE
,

### ISSUE THREAD

**Issue by beasttry** [Ar1i/PokemonGo-Bot#2792]

**Comment by immoempe** [comment]
This work for softbans, no IP bans

**Comment by deface0x2** [comment]
We need more capslock in topics. This solution is already implementend in the bot and it's only usable for softbans, as immoempe just said. Please read the forums instead of posting more "issues".

**Comment by Waiiim** [comment]
If ever you're truely banned, you can't acces to your account anyway lol

**Comment by bboylost** [comment]
someone remove this retard post

**Comment by bboylost** [comment]
yea, and ask someone to "test it out" and then on the topic says" I THINK I HAVE SOLVED THE BANS EVERYONE IS DEALING WITH!" why dont you go f yourself?

**Comment by beasttry** [comment]
lol relax kid

**Comment by gummyruler** [comment]
You can close the thread by clicking the button right next to comment.
