### ISSUE TITLE
unable to load encrypt.dll AGAIN

### ISSUE THREAD

**Issue by hahacarter** [Ar1i/PokemonGo-Bot#2793]
i dont know why you closed my ticket when it still isnt solved, i downloaded the new build AGAIN and it still has the same issues. 
there is no encrypt.dll file anywhere to unpack or existent in the build i downloaded 6 minutes ago. 
its present in the archive, and the link to the actual file is nonexistent as was the link posted in my original ticket. (er 404).

It would be nice to have some positive feedback. Thanks.

**Comment by phodem** [comment]
try disable your anti virus, it works fine for me

**Comment by hahacarter** [comment]
ive ran the game up until the mid .09 build
i dont have a problem with my anti virus. it is off. let alone i dont have any.

**Comment by hahacarter** [comment]
this is a recent problem with the new builds im having
