### ISSUE TITLE
Powerup - FullPowerup

### ISSUE THREAD

**Issue by gRullo** [Ar1i/PokemonGo-Bot#2795]
From the GUI doesn't work, ofc i tried with enough candy/stardust.

**Comment by AschHack** [comment]
Maybe you have reach the max Level for the pkmn ? Reminder : The max level for a pkmn is your level +1.5

**Comment by gRullo** [comment]
no its not at max lvl, i checked it but thank you to ask

**Comment by gRullo** [comment]
sorry i'm an idiot... i forgot the pokemon is in a gym right now, thats why doesnt work from the GUI ofc. I'm sorry :P
