### ISSUE TITLE
TransfertFirstLowIV

### ISSUE THREAD

**Issue by AschHack** [Ar1i/PokemonGo-Bot#2796]
Hello.

The function TransfertFirstLowIV release in first the pokemon with the HIGHER IV.
Maybe a little probleme with the list that stores duplicate pkmn ? ;)

Bye.

**Comment by chusski** [comment]
@Ar1i  I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^

**Comment by AlpaEZPZ** [comment]
sounds correct

**Comment by Ar1i** [comment]
fixed
