### ISSUE TITLE
Pokemon Transfer logic problem

### ISSUE THREAD

**Issue by bennyfei** [Ar1i/PokemonGo-Bot#2798]
There appears to be a logic problem when the bot decides which pokemon to transfer once it hits the amount limit. 

I had a growlithe with CP986 and IV61%. when the bot caught a new growlithe with CP237 IV55%, it transferred the one with CP986 and kept the CP237....while the IV value doesn't make a whole lot different and both are under IV90%. 

![capture](https://cloud.githubusercontent.com/assets/20959586/17575351/62a16b86-5f1d-11e6-98af-2a66e8cf417a.PNG)

**Comment by k3npachi** [comment]
i have the same error , the bot have transfer a hypno with 92 IV and 750 CP, and a jynx

**Comment by AlpaEZPZ** [comment]
same error here, got a psyduck with 21% and the bot transfered one with 71%

**Comment by chusski** [comment]
@Ar1i I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.
The problem are when comparation

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^

**Comment by gitovahere** [comment]
That part is broken after version 1.0.8.2.
The latest version transferred most of my higher IV, I had to downgrade and use the old version. Works fine.

**Comment by Ar1i** [comment]
fixed
