### ISSUE TITLE
Can't say what's happening, don't think it's a proxy problem.

### ISSUE THREAD

**Issue by Waiiim** [Ar1i/PokemonGo-Bot#2799]
![capture d ecran 111](https://cloud.githubusercontent.com/assets/20826690/17575453/9f91c026-5f69-11e6-9412-96130f3dc915.png) I clicked on "Force Unban" at the start

**Comment by gummyruler** [comment]
That's a wrong credential error. The bot ddn't even login. @Ar1i said use port 80 ones.

**Comment by xJustx** [comment]
Mh.. Port 8080 is nice too..
Try to change your proxy. And keep in mind: It has to be a HTTPS Proxy.

**Comment by chusski** [comment]
i have same problem

**Comment by Waiiim** [comment]
Yep i'm on a Koreon proxy with high spped high connexion, and the port is 8080

**Comment by Ar1i** [comment]
should be your proxy

**Comment by Waiiim** [comment]
It is an https ....

**Comment by Ar1i** [comment]
for sure its working and not an public one?

**Comment by Waiiim** [comment]
I tryed on my private vpn and on a public proxy, none work
And it's not written that I'm banned :c

**Comment by fourmansyah** [comment]
i use auto Proxyfier Online And I fokus The Proxy To BOT , And If IP From BOT Broken The Proxyfier Will Change It Automaticly, Or U just Use HideMyIp... And Your Ip Will Not Readed .. its look Like Imposible But I use That .. So I Can Open 10, Or More then it ...

**Comment by Waiiim** [comment]
I can't connect via my phone or Nox, but people say that the real bans haven't started and it's not written " you are banned " 
It must be just a probleme with my account but I don't know what..

**Comment by Waiiim** [comment]
I managed to connect with the new proxy update =) 
The only problem remaining is that there is 30 seconds - one minute of delay between each action 
[15:20:18] Next Pokestop : blabla in 12m, will take 1,49 secondes
[15:22:36]Farmed XP; 50 
lol
