### ISSUE TITLE
Bot shows Coordinates of the Pokestop

### ISSUE THREAD

**Issue by bamoas** [Ar1i/PokemonGo-Bot#28]
Hey, i wondered if it's possible to show the Coordinates or even the Street of the Pokestop to which the Bot is walking. Im alwas curious about where the Bot is at the moment, so i can know if the Bot went far example too far outside of the Central Park. 

Besides, i wanted to thank the Programmer and Developer for that great Bot, it's unbelievable how fast i climb the Levels, would've never reached it in 3 month :D

**Comment by Ar1i** [comment]
Uhm it already Outputs the PokeStop name, should be enough first... cause normal users wont need that...

**Comment by crss** [comment]
edit logic.cs in PokemonGo.RocketAPI.Logic

search for $"Next Pokestop: {fortInfo.Name}
add ({pokeStop.Latitude} {pokeStop.Longitude})
