### ISSUE TITLE
Console Problem

### ISSUE THREAD

**Issue by kingdom1241** [Ar1i/PokemonGo-Bot#280]
[22:12:32] Restarting in 10 Seconds.
[22:12:43] Error: Pokemon Go Rocket API
[22:12:43] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   bei PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:Zeile 34.
   bei PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:Zeile 128.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 50.

**Comment by mauxak** [comment]
Your username or password is wrong
