### ISSUE TITLE
Bot transfered highest CP Pokemon

### ISSUE THREAD

**Issue by Whael1673** [Ar1i/PokemonGo-Bot#2800]
Hello, 
I changed my settings to get rid of some low Pokemon. Everything worked fine until the the bot transfered my best cp Pokemon ( an 2,7k Exeggutor). 

My Settings
![unbenannt](https://cloud.githubusercontent.com/assets/20894092/17575500/e7ec2bb8-5f69-11e6-9f0b-02828e85d400.PNG)

18 other 2k+ Pokemon were not tranfered. 

I´m not sad about this because it´s bottet and i´ll get a new one soon but I just want to share.
Sorry for my bad english. I´m German. :)

**Comment by Farox1988** [comment]
Genau aus dem grund miste ich lieber selber aus^^
Weil das ist echt ärgerlich naja fehler passieren und sagtest ja selber kokowei hast de flott wieder;)
ICH denke das der Bot indem moment auf IV geguckt hatte KOKOWEI war unter 90% und hat ihn deshalb weggehauen, wobei der bot aber vergaß ( ^^ ) das er auch denn CP wert beachten sollte.

**Comment by xJustx** [comment]
#2564
