### ISSUE TITLE
IV miscalculation? Transfer error?

### ISSUE THREAD

**Issue by JunpeiL** [Ar1i/PokemonGo-Bot#2801]
Appreantly i don't have squirtle which has IV 22.36%

![image](https://cloud.githubusercontent.com/assets/14263528/17575643/df00e470-5f1f-11e6-9a80-dbf66d13ef36.png)

**Comment by AlpaEZPZ** [comment]
I have the same error / bug.
I saw this while i had a 71% psyduck and it was transfered for a psyduck with 21%.
I think

**Comment by chusski** [comment]
@Ar1i I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.
The problem are when comparation

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^

**Comment by ade182** [comment]
@chusski before you copy and paste ar1i's answer , you'd better watch closely to the question , not all the IV question have the same answer as yours :)

BTW i have some similar case to this one , do the GUI and the bot have different calculation ?

**Comment by JeCelle** [comment]
@ade182 O_O That's not Ar1i's answer, he's just trying to call the attention of Ar1i to notice his "observation" regarding the TransferFirstLowIV feature.

**Comment by Whael1673** [comment]
I noticed the issue in the picture too. I think it works this way. (Best: CP 709 , IV 22.36%) These values dont belong to 1 Pokemon. It shows the best Cp value and the highest IV value of the same Pokemon type.

**Comment by rickepk** [comment]
error show transfer but transfer correct.
![best_cp_wrong_iv](https://cloud.githubusercontent.com/assets/20685209/17577538/57c3bc90-5f55-11e6-8f9c-11f627aaee3c.jpg)
Show the correct CP for best but show wrong IV. In screenshot show it.

**Comment by JunpeiL** [comment]
Workaround:
Use the old build from yesterday if you have it.

**Comment by xJustx** [comment]
Thank you!
I'll mark this as a minor bug.

**Comment by vitus0123456** [comment]
i have the same problem, it looks like the console takes the highest CP from one pokemon and the highest IV% from another then displays as the best one.
