### ISSUE TITLE
JsonReaderException  when run on  os in unicode jap

### ISSUE THREAD

**Issue by chouitsu** [Ar1i/PokemonGo-Bot#2802]
My os is in unicode japan  and  error on start   after version   "Latest Build - 09.8.16 11.51"  .

I have tried  every new version released and tried delete Translations folder and no use.
![image](https://cloud.githubusercontent.com/assets/20959666/17575769/33ebb064-5fa7-11e6-8a3a-23700d1a4efe.png)

Now I can run bot by changing unicode to  US.  
Can you solve this problem  and thanks for this wonderful project.

Sorry for my poor English.

**Comment by Ar1i** [comment]
uhm try to update please
