### ISSUE TITLE
Bot does not fufill the walking map specified 

### ISSUE THREAD

**Issue by bennyfei** [Ar1i/PokemonGo-Bot#2803]
I felt like the bot never went to certain area that I wanted it to go so I tracked the location for a little while and here's what I got: 
![capture](https://cloud.githubusercontent.com/assets/20959586/17575800/552cdb4e-5f21-11e6-8243-fb9a73dec18d.PNG)

Not only does it not fully cover the area I specified on the settings, but also going outside of the specified area. The radius I set was 2km. I had the start walking from default location option checked.

**Comment by Whael1673** [comment]
I think 2km radius is to big for the bot. He simply cant go to all Pokestops within 5 minutes. So he starts to take the same route again.

**Comment by xJustx** [comment]
We're using this issue now for this problem :p #2819
