### ISSUE TITLE
Transfer bug IMPORTANT URGENT

### ISSUE THREAD

**Issue by daniele978** [Ar1i/PokemonGo-Bot#2806]
I have very important bug in transfer, currently only this
Sorry my english
![bug transfer](https://cloud.githubusercontent.com/assets/20801871/17576330/bd1442ba-5f71-11e6-91bd-bf1f9d4f3b2c.PNG)

**Comment by stromblade** [comment]
I have the same problem
![vvcap 2016-08-11-08-33-03](https://cloud.githubusercontent.com/assets/20960490/17576625/e43e1474-5f9e-11e6-87fe-16930d728662.png)

**Comment by oXNARXo** [comment]
there is no bug here ! you just gotta set up your own settings

**Comment by volturi04** [comment]
how?

**Comment by daniele978** [comment]
transferlowiv is the setting cause this problem
Deselect this impostation
