### ISSUE TITLE
Help with proxy please, I'm kinda noob.

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#2807]
I havn't found any post conerning proxies on the website. I would like some help about them because I don't even know what a proxy is used for, I am kinda noob with stuff like that.

If you can help I would appreciate because my bot is banned at the moment.

Thanks.

**Comment by Captnred** [comment]
Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

Or research this thread with the search function. 
If you wouldn't mind closing this issue; as it's not an issue.

**Comment by xJustx** [comment]
^
