### ISSUE TITLE
Which IV is right? in console or pokemon list?

### ISSUE THREAD

**Issue by SoloCN** [Ar1i/PokemonGo-Bot#2808]
pokemon list IV and console IV is different for the same pokemon which one is correct?

**Comment by arjunvegda** [comment]
Pokemon List. I have tried to notify this bug manier times but its still not fixed.. So lets wait for Ar1i to fix it. But meanwhile you can look up on the pokemon list and rely.

**Comment by SoloCN** [comment]
It's transferring all my higher IV Pokemons 😂😂😂

**Comment by gitovahere** [comment]
That part is broken after version 1.0.8.2.
The latest version transferred most of my higher IV, I had to downgrade and use the old version. Works fine.

**Comment by Captnred** [comment]
Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

and if you wouldn't mind please close this issue; as this is not a issue.

**Comment by arjunvegda** [comment]
@Captnred Well it is a issue.. IV calculation in the console is broken clearly.

**Comment by Captnred** [comment]
He stated "pokemon list IV and console IV is different for the same pokemon which one is correct?" Which in this case is asking which one of these is correct; so therefor this is a question. Now The IV calculation does bug out from time to time, but that issue as well already has a thread on it and the devs are working on it.

**Comment by arjunvegda** [comment]
@Captnred So after his statement I cleared the fact that its of course an issue so according to me your response should be referencing to the particular thread you are addressing to. Rather than requesting to post questions elsewhere.

**Comment by xJustx** [comment]
Thank you!
I'll mark this as a minor bug.
