### ISSUE TITLE
IDP.ARES.Generic getting flagged by AVG

### ISSUE THREAD

**Issue by mrhappypantz** [Ar1i/PokemonGo-Bot#2809]
Searched for something along the lines of that didnt' find anything.

IDP.ARES.Generic was flagged by AVG when opening the console.  What is it?

**Comment by AmbientLights** [comment]
yep I got that too 
![capture](https://cloud.githubusercontent.com/assets/20725097/17577951/846fade8-5f51-11e6-8c3c-f6d12f3a670c.PNG)

**Comment by xJustx** [comment]
Mh.. that's a false positive.
If you don't trust us you can check the source und build it yourself.
