### ISSUE TITLE
[Compliments to the Devs!] [Feature Request]

### ISSUE THREAD

**Issue by Gioele1334** [Ar1i/PokemonGo-Bot#281]
Best Devs ever, Already 3 Updates today! Good work!
i need an option for ignore pokèmons with CP Down to 100
and an option for farming pokèstops or Catching Pokemons (Checkboxes)

**Comment by HaydarOzturk** [comment]
That last idea is really good. We could only use pokestops for some times... I support this one.

**Comment by Ffm42** [comment]
Well just saying. There is an option called "pokemon to not catch". If you use "select all" it shouldn't catch any pokemon and so it should focus on the pokestops. The other feature would need an update. But I don't think capturing pokemons without farming the pokestops would be a good idea as you would run low on pokeballs pretty fast....

**Comment by Gioele1334** [comment]
i am saying this because i ran out of pokeballs, so i need to farm some
pokestops

Il 29/Lug/2016 22:49, "Ffm42" <notifications@github.com> ha scritto:
