### ISSUE TITLE
We can't find any PokeStops in a range of 5000m

### ISSUE THREAD

**Issue by sergiohacks3** [Ar1i/PokemonGo-Bot#2810]
We can't find any PokeStops in a range of 5000m IN THE LATEST VERSION UPDATE :(

I'm in a vps and I want to change proxy vpn but I do not work but at the option of the boot of the proxy tab I get this error We can't find any PokeStops in a range of 5000m

me on my computer works perfect but in no vps few days ago I worked, I can not have my pc all day ..

**Comment by Serg02** [comment]
same problem...

**Comment by dominic0807** [comment]
same problem here

**Comment by Qurus1** [comment]
change of location

**Comment by xJustx** [comment]
#2804
