### ISSUE TITLE
error when trying to open app

### ISSUE THREAD

**Issue by ipaul07** [Ar1i/PokemonGo-Bot#2811]
I downloaded the bot and after saving it i try to open up the app and get this error. i have updated everything on my pc so not sure what else it could be.

thanks

![error](https://cloud.githubusercontent.com/assets/20960380/17576715/fb93f5c4-5f32-11e6-9e2f-e7918612300d.png)

**Comment by Captnred** [comment]
Try running it as administrator?

**Comment by ipaul07** [comment]
How do I do that?

**Comment by Captnred** [comment]
Right click it and click run as administrator

**Comment by ipaul07** [comment]
it didnt work

**Comment by Captnred** [comment]
In your screenshot it says it can not find the file? Did you move it or is it in the same folder?

**Comment by ipaul07** [comment]
When I extract it I save it to desktop. The file is saved in a temp file that I can't locate

**Comment by Ar1i** [comment]
extract to a folder and run from there
