### ISSUE TITLE
double pokemon transfer bug, really annoying

### ISSUE THREAD

**Issue by Niubbo** [Ar1i/PokemonGo-Bot#2812]
i have to manually transfer lower cp double pokemon 
i.e. i have 10 evee (my setup is max 1 double and iv 90 max transfer) 5 is major than 90 and is ok to have it, and others are lower cp and lower iv and the bot doesent transfer them, same for other pokemon and if i dont manually transfer them i reach the 250 limit and i cant farm anymore and this is annoying
i've noticed the bug is present more on pokemon i dont selected for be autoevolved

pls fix it 
thank you very much

**Comment by davegoskate** [comment]
its tedious work but yea its been like that for awhile now i just literally finished sorting the 133 pokemon from highest iv and evolving them while still keeping one of each type but i managed to do it lol.

**Comment by gitovahere** [comment]
That part is broken after version 1.0.8.2. 
The latest version transferred most of my higher IV, I had to downgrade and use the old version. Works fine.

**Comment by Captnred** [comment]
Sorry for the trouble you're having, but please use the search feature on this thread. Many people have posted this and it's well known. So if you could please close your issues; as the developers are trying to fix everything.

**Comment by amaslkw** [comment]
this problem has been there for a while. just manually do it. you gotta do some work occasionally xd
