### ISSUE TITLE
PokemonGo - Bot not work in win 32

### ISSUE THREAD

**Issue by lambeng88** [Ar1i/PokemonGo-Bot#2814]
![image](https://cloud.githubusercontent.com/assets/20960946/17577062/c799ff18-5fa3-11e6-9737-42aad0f593a1.png)

**Comment by eLDeMe** [comment]
It works in 32 bit, but it seems like don't work on XP

**Comment by xJustx** [comment]
Mh.. 
I'll mark this as a minor bug.

**Comment by Ar1i** [comment]
no xp support
