### ISSUE TITLE
Error: mscorlib

### ISSUE THREAD

**Issue by nickpkm** [Ar1i/PokemonGo-Bot#2815]
![errorbot](https://cloud.githubusercontent.com/assets/20961059/17577170/0ac8dec4-5f51-11e6-87eb-39c49c3fd091.PNG)

Error in the last version

**Comment by xJustx** [comment]
Please try to use a other proxy.
It seems that the proxy is down or is a http proxy.

**Comment by nickpkm** [comment]
I tried 6 different proxys, the same thing happned ...

**Comment by xJustx** [comment]
And what happens if you're using no proxy?

**Comment by nickpkm** [comment]
Ah :D wtf, i tried to use no proxys all the night and now it start to work ! 
![bugfix](https://cloud.githubusercontent.com/assets/20961059/17578916/781e9068-5f65-11e6-99db-2b327ce5607e.PNG)
