### ISSUE TITLE
R.I.P. Razzberry

### ISSUE THREAD

**Issue by OracleMaster14** [Ar1i/PokemonGo-Bot#2816]
![image](https://cloud.githubusercontent.com/assets/20961076/17577210/97016cd8-5fad-11e6-981e-f909ec2eb8a5.png)

why it's always using razzberry????

**Comment by Whael1673** [comment]
I run out of Razzberrys all the time. Maybe he could add a feature : Use razzberrys at.... (same like evolve pokemon x) 
So we can decide when to use it.

**Comment by Captnred** [comment]
Its because its programmed that way. 
Please close this thread 
For questions try here please. https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by SoloCN** [comment]
this is a issue.. console and pokemon list is not consistent

**Comment by Captnred** [comment]
That's not what he's saying. He clearly asked "why it's always using razzberry????" So therefor it's a question, not an issue. Now if he were to have a problem with the razzberry count which will correct it's self in the next encounter. Then it would be an issue, but that specific issue already has a thread.

**Comment by xJustx** [comment]
Do you have enough pokeballs?

**Comment by AiVo7z** [comment]
Well low % to catch, so he's using a berry. Higher chances of catching it, the bot doesn't. I don't see a Problem here? Except it'd use a berry EVERY pokemon, but that's something your screenshot does not show.

**Comment by Ar1i** [comment]
^
