### ISSUE TITLE
We can't find any PokeStops in a range of 5000m but...

### ISSUE THREAD

**Issue by pepeyon** [Ar1i/PokemonGo-Bot#2817]
Ok, I usally runs two bots but now for don't get banned I run one bot in this computer (desktop) and another bot in a Laptop so I ran the bot and the **2** accounts get the issue "We can't find..." Why I having this? I'm using two differents computers.

**Comment by faridpuri** [comment]
because you have a static IP ( usually from router ), so the server still counting you login 2 account in one IP

**Comment by Captnred** [comment]
Make sure your not softbanned, or IP banned. If softbanned please use the force unban. If IP banned try resetting your router, or changing the IP in your VPN.

Also please use the search feature, there are many threads with the same issue. No need to create a new one.

**Comment by fernandofc16** [comment]
There is a difference between public and private IP addresses. The one that counts in this matter is the public one. Cause when you are sending a request to niantic servers you're using your public IP.

In another words: When a computer is assigned a private IP address, the local devices sees this computer via it's private IP address. However, the devices residing outside of your local network cannot directly communicate via the private IP address, but uses your router's public IP address to communicate.

So how to change my public IP? Simple, use a VPN.

**Comment by pepeyon** [comment]
Thank you so much, I will reset my router and try to connect to an VPN. This surprised me because the past days I put 4 bots in one computer and nothing bad happend.

**Comment by Captnred** [comment]
Please let us know if this fixes it, or if it doesn't.

**Comment by fernandofc16** [comment]
I used a proxy once and it didnt work for me. What you could do is in one device run a bot using your public IP and in another device run a bot using a VPN. Or use VPN for both devices, just dont run more than one bot per public IP. And some times you may face a IP ban using VPN, does it mean that VPN is not working? No, it means someone else is using the same public IP probably with the same VPN for his/her bot so keep changing until you find one IP that is working.

**Comment by pepeyon** [comment]
Ok, now I can and I reset the router but has been 2 hours from that, so now I don't know If was the reset router or wait 2 hours. Now I have fear try with the desktop computer.
