### ISSUE TITLE
Seaking Icon showing Error Image :)

### ISSUE THREAD

**Issue by dramr** [Ar1i/PokemonGo-Bot#2818]
not that much of a issue but just letting you guys know :))

**Comment by Captnred** [comment]
The devs are well aware of it; as there are numerous threads about pokemon icon issues. Thanks for the tip, but if you wouldn't mind closing this thread as there are many many others of this.

**Comment by xJustx** [comment]
Thank you!
I'll mark this as a minor bug.

**Comment by Ar1i** [comment]
delete sprite folder
