### ISSUE TITLE
walking out of zone

### ISSUE THREAD

**Issue by FinFis** [Ar1i/PokemonGo-Bot#2819]
walking out of zone?
![untitled](https://cloud.githubusercontent.com/assets/20888475/17577465/af55046c-5f43-11e6-8673-24386bf83b2b.jpg)

**Comment by vitus0123456** [comment]
@FinFis how do you assign favorite from the pokemon list?

**Comment by Captnred** [comment]
I'm pretty sure you have to do that in the game app and the pokemon list will carry it over.

**Comment by xJustx** [comment]
Thank you!
I'll mark this as an minor bug.

**Comment by zzzz9999** [comment]
@FinFis how dou you have a Dragonite 3350?
Did you full powerup him?

**Comment by FinFis** [comment]
zzzz9999  yes

**Comment by zzzz9999** [comment]
@FinFis Niceeeee :P
