### ISSUE TITLE
Can't catch pokemon

### ISSUE THREAD

**Issue by PokemonGoer** [Ar1i/PokemonGo-Bot#2821]
Here's a photo of my issue

http://puu.sh/qx5sB/980308528b.png

Pokemon keep running away from my pokeballs. I've tried turning the bot off for a few hours and reloading it but had the same issue. Is my account banned?

**Comment by Captnred** [comment]
If you cant find any Pokestops, or catch any pokemon; try to change the location. If that doesn't work your IP banned. Change your IP, or use VPN/Proxy.

**Comment by Juiche** [comment]
here
https://github.com/Ar1i/PokemonGo-Bot/issues/1930

**Comment by PokemonGoer** [comment]
Thank you Juiche, I must of ran out of Pokeballs

**Comment by Captnred** [comment]
Awesome if that fixed the problem please close this issue. If it didn't please let us know.
