### ISSUE TITLE
softban , empty pokemon go map

### ISSUE THREAD

**Issue by erikyam** [Ar1i/PokemonGo-Bot#2822]
it says that a sofban was detected then i close pokemon go bot and go to my phone log in theres nothing on the map. i waited almost have an hour and it was working but when i run pokemon go bot again it works for like 5 minutes or less and again a sofban was detected and when i go to my phone again i have an empty map.i log in to my other account the account that i dont use pokemon go bot and theres still an empty map .what does this means?

**Comment by AmbientLights** [comment]
it seems to IP ban your modems IP so your homes network gets banned

**Comment by erikyam** [comment]
so i turn off the wifi and turn it back on?

**Comment by AmbientLights** [comment]
no your modem like your internet providers device that gives your router/phone internet

**Comment by Captnred** [comment]
No you have to reset your router/modem. Turning off the wifi will not do the trick. You can unplug your router/modem for thirty seconds, or hit the tiny button thats in the back of it

**Comment by erikyam** [comment]
thankyou im going to try it right now and do u think dis would work ? https://youtu.be/qvE9f9raQDU

**Comment by AmbientLights** [comment]
yea probably

**Comment by Captnred** [comment]
Please let us now if this fixes it and of course if it doesn't as well.

**Comment by dragonite1895** [comment]
is the bot working for you guys ?

**Comment by erikyam** [comment]
i unpluged the router/modem for a few minutes and it didnt work .

**Comment by AmbientLights** [comment]
you can try the VPN you can also use your mobile data to tether your computer if all your running is the bot

**Comment by JunpeiL** [comment]
It is working fine for me. Just try not to bot 2 accounts at the same time. Your Internet provider (AT&T, Comcast etc) usually assign one static IP to your box/router. When you have more than one devices connected to the box/router, the router will relay all the requests to the WAN, and WAN will treat those request come from single IP. (NAT)

**Comment by AmbientLights** [comment]
it seems if I run my bot and play on the phone on a different account I sometimes get IP banned lol

**Comment by erikyam** [comment]
does the cyberghost has to be in the same city as bot?

**Comment by AmbientLights** [comment]
probably not

**Comment by erikyam** [comment]
can i use this? - http://proxylist.hidemyass.com/search-1297445#listable

**Comment by AmbientLights** [comment]
https://twitter.com/search?f=tweets&vertical=default&q=pokemon%20no%20pokestops&src=typd it seems niantic is IP banning some cell towers lol

**Comment by s1umlord** [comment]
mine was down for about a hour it is the servers they go own but i am back up and running check it and see if you are. would you ip location make a diff if the servers are down in that area? does it alot at night it runs great during the day?

**Comment by xJustx** [comment]
I don't know if this is a problem with the servers from niantic.. wow okay :o
Thanks @AmbientLights for sharing this Link...

**Comment by erikyam** [comment]
if your IP got banned download this program- http://www.cyberghostvpn.com/en_us/download/windows-vpn  - it works my IP was banned and i couldn't use the bot anymore but with this program its working now!!

**Comment by lordminion** [comment]
I can Play with bot, but not with My phonre, Same Location in Germany. If i Start the bot he load all Fine working. I close the bot wait 5 mins and Login with phonre but empört map..  I restart My phone Turn gps Off nothing help

**Comment by Kill-Bot9000** [comment]
I kept getting soft banned, jumped on my VPN and now it looks like it is working fine.

**Comment by Kill-Bot9000** [comment]
Spoke too soon, ran 2 instances, one of the two got a soft ban within a few minutes.

**Comment by Spensky** [comment]
I keep getting softbanned over and over again :dart: ... how you guys even manage to play whit a single bot ?

**Comment by Kidnub** [comment]
sound bad i use my bot as always just max 10KM/H and then gogo power rangers XD 
so  i have no big problem s at the last 36H XD with one bot XD maybe you run to fast maybe you have logged over phone once in if you botting .. i dont know my personal tipp for you .. Dont go over 10KM/h XD then you can be easy sure that he has no soft ban (if you jump to fast the aeria even if it s just 30Km away from your basic run route you will get a softban .. so dont switch too fast to a new spot)

**Comment by Captnred** [comment]
@erikyam  Glad everythings working now if you wouldn't mind closing this thread.

**Comment by Spensky** [comment]
@Kidnub ok thnx for the tip , i was running 150km./h :D
