### ISSUE TITLE
Proxy Do Not Work? or Maybe Poks Detect Same "Model"

### ISSUE THREAD

**Issue by WhoBotWhoBad** [Ar1i/PokemonGo-Bot#2825]
Firstly, I ran more than 3 bots at the same time, so if the proxy really works and niantec detect multiple connection in the same IP, in my case there should no problem because all of my bots have different proxy address but all of them experience softban. I am aware that maybe somewhere out there is using the same proxy with me so I get the soft ban. But I got 1 of my office proxy which I am the only one using it also experience softban.

The second one is maybe niantec is detecting which one is really a mobile device? Like most cellphone, it has its own manufacturer, model and built version, maybe niantec system detected that we are all using the same model as others do that is why we all get softban?

@Ar1i , quick question bro, are we using the same built? if yes, is there any thing that we can spoof each bot act like a real phone built and model. 

Thanks.

**Comment by Gin520** [comment]
I tried using the new proxy setting at home and at office, but run with 1 bot only. 

At home:
1. I tried using 2 different IP, first one works fine
2. 2nd one doesn't work, so move back to the first one

At office:
1. tried the same IP, doesn't work at all, and it keeps on saying Can't find any pokestop.

**Comment by eLDeMe** [comment]
#2788

**Comment by WhoBotWhoBad** [comment]
@eLDeMe I didnt now you already posted it :) Good point right there.

**Comment by WhoBotWhoBad** [comment]
@Gin520 all of them are using the same bot version? probably its because niantec detect same model

**Comment by Gin520** [comment]
@WhoBotWhoBad yea, same bot version. I'm wondering if it's my office IP that it permanently blocked and the proxy never went through. I wasn't able to run the bot at office for 3 days already, and it works fine at home.
