### ISSUE TITLE
New red Text

### ISSUE THREAD

**Issue by JunoBotboy** [Ar1i/PokemonGo-Bot#2826]
What does "Caught new" means?

http://imgur.com/a/hxlVz

![newpokego](https://cloud.githubusercontent.com/assets/20761289/17578396/2120a594-5f56-11e6-907d-d811b7499d53.png)

**Comment by nickpkm** [comment]
U Caught a new poke (: Nothing to worry about

**Comment by JunoBotboy** [comment]
i already have one, ive had plenty

**Comment by JunoBotboy** [comment]
the one i kept is the 100% IV Pinsir....
