### ISSUE TITLE
How long does IP ban last?

### ISSUE THREAD

**Issue by chue76** [Ar1i/PokemonGo-Bot#2828]
Sorry to ask this noob question but i read thru the issues but cannot find the answer to this and would like to know if in all cases everything else failed is it possible to wait out an IP ban? How long does one last? Many thanks in advance

**Comment by phodem** [comment]
1 hour

**Comment by chue76** [comment]
thank you, hopefully those like me who encounter the issue and can't figure out a way can just patiently wait it out without asking repeat questions here. :)

**Comment by AiVo7z** [comment]
Could also be 15min, you've to Keep trying tho.
