### ISSUE TITLE
Throwing more than one razzberry to one pokemon, count of berries is wrong

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#2829]
If the bot throws more than one berry to one pokemon, the count of razzberries is wrong.

At my screenshot there is two times: 12 razzberry.
After the first throw i only should have 11 berries ;)

Version 1.0.9.3
![razzberry](https://cloud.githubusercontent.com/assets/20796795/17578540/71d4cbb2-5f8a-11e6-9b9e-d99befb96466.png)

**Comment by jodirt282** [comment]
Every time a pokemon escape from ball, a new razzberry need to be thrown. It's like that in the official game also.

**Comment by Scanda85** [comment]
Yeah, that's fine.
The only problem is, that the count of razzberries is wrong :)

**Comment by Ar1i** [comment]
already known but atm i cant do anything, cause if i refresh the inventory to fast you get a exception
