### ISSUE TITLE
Bot uses blue incubators, although i don't set the option for basic incubators

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#2830]
Since today the bot uses incubators, but not completely correct.

The bot uses basic incubators (blue ones), although i don't set the option for using basic incubators.

It should only use the orange incubator.

Version 1.0.9.3

**Comment by bkrandy** [comment]
isnt it better though if it hatches multiple eggs using whatever incubators since thats what they are for?

**Comment by Yotumn** [comment]
@Scanda85 if you set "use basic incubators" it will only use the orange incubator.
if you don't set "use basic incubators" it will use ALL incubators.

**Comment by Captnred** [comment]
Yeah the basic incubators is the orange one not the blue ones. Setting that should fix your problem as @Yotumn  has said. Please let us know if that fixes the problem and if so close this thread.
