### ISSUE TITLE
Bot transfered the pokemon with the highest CP

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#2831]
Normally the bot transfered the pokemon with the lowest CP, but actual it transfer the pokemon with the highest CP value. 
Think this could be a major issue ;)

Version. 1.0.9.3

![transfer](https://cloud.githubusercontent.com/assets/20796795/17578638/c6657cd4-5f8b-11e6-9b82-7b138220403e.png)

**Comment by xJustx** [comment]
#2564
