### ISSUE TITLE
Name Error, No Sprites

### ISSUE THREAD

**Issue by TheGhostCode** [Ar1i/PokemonGo-Bot#2832]
Hello, I just installed the latest version of the bot, started it and there are no name and sprites for any pokemon, I have refreshed and restarted, the list also takes quite a while to load now I dont know if this is or bug or not but thanks. 
![screen shot 2016-08-10 at 11 19 49 pm](https://cloud.githubusercontent.com/assets/20962586/17578649/3ecd18d4-5f51-11e6-8782-149b18446071.png)

**Comment by TheGhostCode** [comment]
and yes i can select pokemon cause in this screenshot it was refreshing but still no name or sprites

**Comment by PokeMungo** [comment]
delete bot folder. extract again.. and open bot. :)

**Comment by Ar1i** [comment]
^

**Comment by JakeCube** [comment]
Hi, i been trying delete bot folder and extracted again... it still not working on me

Using 11.08 16.19 latest version
Win7
