### ISSUE TITLE
CANT FARMING in pokestops

### ISSUE THREAD

**Issue by joe112** [Ar1i/PokemonGo-Bot#2833]
![dadasdas](https://cloud.githubusercontent.com/assets/20850464/17578672/23454982-5fb6-11e6-96a7-b9ae5a6018d7.PNG)

**Comment by AiVo7z** [comment]
It even says you're softbanned, can't ppl read?

**Comment by UraharaKisuke07** [comment]
Open your phone. Can you loot any pokestops? If not, then you're softbanned. Please report back if you have any other issues.

**Comment by Xysas** [comment]
Bro  i oppened  2 bots and  have the same problem its like  always softbanned for  3 hours now ... i try everything execpt from vpn...!!!

**Comment by joe112** [comment]
how,i always getting softbanned, im waiting for 1 hour then back again, then soft banned again

**Comment by joe112** [comment]
im just using 1 bot :(

**Comment by Xysas** [comment]
this happens to me all the time!! for like 1 day now!

**Comment by UraharaKisuke07** [comment]
Stop using any bots for 2-3 hours. Go out, have dinner/lunch. 
When you come back, your IP will be unbanned and you can use bots again.
Don't run more than 1 bot at a time. Not even for different accounts.

**Comment by joe112** [comment]
i already do that sir, but bot just work 30 min for me :(, then soft banned again all day long

**Comment by UraharaKisuke07** [comment]
Are you using a public network? 
I've been using Haxton for about 3 hours now, getting 180k xp without evolving and not getting any ip bans. 
Also make sure you're not teleporting all the time and before you start a bot make sure you're not softbanned by checking on your phone.

**Comment by phodem** [comment]
run 1 bot AND do not run pokemon app on the phone with same network. Tell your WHOLE family that too

**Comment by Xysas** [comment]
I  used to run 3 and  Ari told  2 max... so now only one??? aand  what is Haxton new bot |?

**Comment by joe112** [comment]
ok sir thanks for your help, a big thanks to Ar1i :*

**Comment by d4zu4x** [comment]
joe112, can you check your phones?? maybe Gps on your phone active. If it active try unactive it. After 15 minutes re-run the bot.

**Comment by joe112** [comment]
yah sir, my gps is active on my phone, ok i try to re run the bot later thnk for your help

**Comment by AmaliaWinter** [comment]
Maybe try to set a lower km/h because i wouldn't be suprised by myself to getting softbanned if i fly like a jumbojet from pokestop to pokestop
