### ISSUE TITLE
Bot stops midway. It's the second time now.

### ISSUE THREAD

**Issue by gummyruler** [Ar1i/PokemonGo-Bot#2835]
I blurred the exp, but it does this or stop mid catch and doesn't reset the loop just stuck there.
![stopping](https://cloud.githubusercontent.com/assets/20757587/17578926/66cf2976-5f4c-11e6-9f38-c8cd228814ec.png)

Edit 1 hour later: IT happened again

![fudge](https://cloud.githubusercontent.com/assets/20757587/17579950/8ab0d366-5f57-11e6-840f-ce877469c2ee.png)

**Comment by Cyberlink4200** [comment]
gettin the same, bot running for 1 1/2 hour, and it stops

**Comment by gummyruler** [comment]
@Cyberlink4200  BROTHER!!! I guess only Charizards are getting this kind of problem.
