### ISSUE TITLE
BOT TRANSFERRING HIGHEST LVL CP

### ISSUE THREAD

**Issue by immonts** [Ar1i/PokemonGo-Bot#2837]
Can anyone help me with this?  I just got my highest cp pokemon and bot automatically transferred it. -.- and it left the lower cp behind 
![image](https://cloud.githubusercontent.com/assets/20926389/17579276/d09c4450-5fc5-11e6-95a7-ac804815d236.png)

**Comment by srikanthkkolli** [comment]
same problem. Transferred my high cp and IV magicarp :( 
Thanks for the bot.

**Comment by Adukas** [comment]
Same.

**Comment by NikiMon** [comment]
Yup it transferrred my 186 Magicarp :((

**Comment by PokeMungo** [comment]
good thing i still use the old bot. hahaha :dart:

**Comment by JunpeiL** [comment]
don't use the auto transfer for now.... wait for Ar1i to clean up the code. so many bugs in the last build.

**Comment by pingpongplaya** [comment]
true story.. my 100% IV aerodactyl at 1800cp went missing, I could have sworn I never transferred it. And aerodactyl is one of the pokemon in my "don't transfer" list. this was a couple of updates back

**Comment by rvonz** [comment]
its true
i lose lapras cp 2413 and exeggutor cp 2070 and tons of dratini

**Comment by pingpongplaya** [comment]
not complaining though, i gained more from the bot than lost =))

**Comment by burnSMACKER** [comment]
Which version is causing this issue?

**Comment by UraharaKisuke07** [comment]
You guys can always favourite your highest iv pokemons. No bot will transfer them then.

**Comment by hbchang** [comment]
by default setting,it is impossible to transfer the pokemon with IV > 90 or CP > 999.

**Comment by Abbasoo** [comment]
@PokeMungo Can u Upload it?

**Comment by mirageasti** [comment]
Bot isn't transferring Eevees, can someone double check? My storage keeps maxing out from the duplicate Eevees

**Comment by Abbasoo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20796710/17580162/2c186276-5fa5-11e6-8b71-bdcc5606d459.png)

**Comment by PokeMungo** [comment]
1. error catching pokemon is normal because the pokemon time runs out.
2. yep it transfer. so do not use the new version. use old version until it is not fixed yet

**Comment by Abbasoo** [comment]
@PokeMungo what version do you use?

**Comment by NikiMon** [comment]
@PokeMungo where can I download the older version of the bot?

I rlly need it :D

**Comment by PokeMungo** [comment]
i cannot attach it sorry.

it said: 
Unfortunately, we don’t support that file type. Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

try google for now. haha.

**Comment by Qrzy** [comment]
@PokeMungo at least let us know last stable version (name of the file and version number). :)

**Comment by NikiMon** [comment]
@PokeMungo upload it on dropbox or something and send the link

pls

**Comment by Kill-Bot9000** [comment]
Yup mine just killed a 700cp Eevee and left me with two sub 500s.  Never had the issue with the older versions, only the newest version. I'm gonna go ahead and go back two versions.

**Comment by NikiMon** [comment]
@Kill-Bot9000 how do i get the older version?

can you send me a dropbox link or something?

thx

**Comment by chusski** [comment]
@Ar1i I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.
The problem are when comparation

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^

**Comment by Kill-Bot9000** [comment]
@NikiMon https://dl.dropboxusercontent.com/u/10058086/PokemonGo-Bot-master%20(1).zip
