### ISSUE TITLE
BOT is working pretty well!!! so don't complain everything hir. be thankful it's free..

### ISSUE THREAD

**Issue by eehjay01** [Ar1i/PokemonGo-Bot#2838]
Do some research and experiment before you complain.. just saying!!!

Running for 10hrs smoothly. 2 bots (1st bot using proxy ip, 2nd bot using my ip) 

![bot](https://cloud.githubusercontent.com/assets/20963374/17579545/4f1b4f6c-5fc9-11e6-9408-44b66cd4a73e.jpg)

P.s after hours of experimenting diff. ways to use multiple bots... here are my findings..
- you can use multiple bots as long as it is google account.. if you are using PTC you will be softbanned in just 5mins or less..
-you can use multiple bots as long as you use different proxy (ip address) on each of your account.

If you are a PTC user and running multiple bots with no problem. then my findings about ptc user getting softbanned maybe wrong.. feel free to state your opinions.. tnx

**Comment by beasttry** [comment]
how do you get the proxy

**Comment by PokeMungo** [comment]
what version of your bot?

**Comment by fikrirmd** [comment]
i dont know why many ppl complain about softban, proxy etc., im using 3 bots in the last 6 hours, and everything's OK, (im using 1.0.8.4) 
but when i use the newest version(1.0.9.x), i got softbanned in 10mins :(

**Comment by rvonz** [comment]
@beasttry http://proxylist.hidemyass.com/search-1297445#listable

**Comment by eehjay01** [comment]
@beasttry http://proxylist.hidemyass.com/ you can find free proxies here.

**Comment by eehjay01** [comment]
@PokeMungo im using 1.0.8.8..

@fikrirmd if everything is working well on the the lower version don't upgrade..

**Comment by rvonz** [comment]
i use proxy and i cant find pokestop, anyone have solution?

**Comment by mirageasti** [comment]
Running very smoothly for me too, been on and off for a few days now!

Only issue with the latest build is I think the Eevees are always caught and registered as new, and the bot doesn't transfer them even after 10 duplicates lol, which is maxing out my pokemon storage.

Hopefully the devs fix this small issue!

**Comment by PokeMungo** [comment]
oh im using the 10.8.5... and i have no problem also. (except i do not have egg function)

but maybe you should read their comments first. the bug in "new" version is real, its transferring high cp and IV pokemon. and it is good for Arli so he know what to fix.

**Comment by PokeMungo** [comment]
and yes. we are thankful for the bot, haha

**Comment by eehjay01** [comment]
@PokeMungo your right.. What i'm trying point out is some pll are complaining the same thing over over again lol without even reading or researching first. hahah

If its a major bug thats good for the dev to know..

**Comment by PokeMungo** [comment]
hahaha. true. question is always the same. so i just copy paste my answer.
