### ISSUE TITLE
Error loading pokemon list: Skip last field

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#2839]
I have never come across this, what's the fix for this? and why is it happening.

![screenshot_1](https://cloud.githubusercontent.com/assets/20720517/17580215/c3e526ec-5f51-11e6-9cec-0edfa85d3e5b.png)

**Comment by PokeMungo** [comment]
close the bot. and open again.

**Comment by jj1232727** [comment]
I had this issue. If you are using a proxy or vpn turn it off then try. Then log on your phone and attempt again.

**Comment by amylunanala** [comment]
bei mir besteht das problem auch...leider hab ich keine ahnung,was ich ändern soll...
ich benutze schon proxy...(keine free) also kann es daran nicht liegen...
was kann ich tun,damit die liste wieder gesendet wird ?
