### ISSUE TITLE
Bot not transferring Eevees

### ISSUE THREAD

**Issue by mirageasti** [Ar1i/PokemonGo-Bot#2840]
Somehow the bot keeps thinking Eevees are a new catch in the pokedex, resulting in many duplicates which are not transferred.

The transfer threshold I have put is 90%, there are a few <90% Eevees which are starting to pile up as you can see here.

![eevee1](https://cloud.githubusercontent.com/assets/20941404/17580409/c02c4d60-5fe1-11e6-9ae6-3511cdbb8ec8.png)

![eevee](https://cloud.githubusercontent.com/assets/20941404/17580297/e72e0152-5fe0-11e6-8817-8f3fd383c3a1.jpg)

**Comment by PokeMungo** [comment]
i suggest you edit your picture and hide your username. your giving Niantic easy way to ban you. hahaha. and yes bug on Eeevee so wait for boss Arli to fix it

**Comment by PokeMungo** [comment]
MirageAsti :dancers:

**Comment by mirageasti** [comment]
Thanks for the tip, am always careless lol.

**Comment by PokeMungo** [comment]
hahaha NP. its happen to me too sometimes.  :) if you have the old version, use it much better than the new one because it has more bug.

**Comment by Abbasoo** [comment]
@PokeMungo @mirageasti Can anyone upload the old version?

**Comment by gummyruler** [comment]
All those eevees except for 2 are over 90% IV. and you chose keep 2 duplicates right or 3 I can't see the other one? Not a problem at all.

**Comment by mirageasti** [comment]
@gummyruler only 2 haha

**Comment by gummyruler** [comment]
@mirageasti I'm blind bruh ahahaha.

**Comment by PokeMungo** [comment]
i cannot attach it sorry. 

it said: 
Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

try google for now. haha.

**Comment by mirageasti** [comment]
Update for the current build issue - Not only Eevees, Psyducks too! 

Don't have a screenshot of the long list of them rofl, transferred all of them

**Comment by PokeMungo** [comment]
hahahaha. thats is why i keep old version that works fine to me.

**Comment by cyb0rg01** [comment]
@mirageasti can you provide some screenshots of your transfer settings and your normal settings? - It could be, that you have checked "Keep Pokemon if evolvable".

**Comment by Niubbo** [comment]
I have same issue, is possible if u checked "keep pokemon evolvable" and if u check to dont evolve a kind of pokemon ( i.e. evee) the bot doesbt transfer it even if is under the iv and cp transfer limit. I have this issue with all the pokemon i dont wanna evolve like evee, bulbasaur and charmander
