### ISSUE TITLE
20 public proxies 2 Private no Pokestops

### ISSUE THREAD

**Issue by jj1232727** [Ar1i/PokemonGo-Bot#2842]
I had tried many proxies. The first day the feature came out it had worked until midway someone would use the same proxy. I had now used both public and private proxies and both come out with the result of no pokestops spawning. I am unsure of what I am doing wrong. All of the proxies are HTTPS and I tried keeping them in the same location as the bot. Not a clue. If I turn on pokemongo on my phone, no problems at all.

**Comment by pilota56** [comment]
I use 2 different private Proxys and both work fine. But there is only my Bot.
