### ISSUE TITLE
Not all BOT-Traffic is routed via Proxy!! WARNING !!!

### ISSUE THREAD

**Issue by HELLspawnTIM** [Ar1i/PokemonGo-Bot#2843]
Hello all,
got a question on the Proxy function implemented recently.
Could not find that question yet here, that's why I opened a new issue-

I am using latest version "10.08 22.25" for sure.
Configured proxy: 90.63.xxx.xxx (hidden for my security)

But i noticed that not all the traffic the Bot makes with PokemonGO servers is routed via the proxy.
After a few tests and monitoring the traffic with the Microsoft tool "TCPView" (https://technet.microsoft.com/de-de/sysinternals/tcpview.aspx), I saw that only the connections to the official IP "130.211.14.80:443" is re-routed through proxy.
But the connection to all the other official PokemonGO servers is not re-routed.

I wondered why this is programmed this way by Ar1i ???
And I also wonder if PokemonGO servers can still ban my public IP this way ???

Can you please explain?

Regards,
HELLspawnTIM
 
![notviaproxy](https://cloud.githubusercontent.com/assets/20964979/17581175/22696fdc-5fa4-11e6-9179-afe428c7fbee.jpg)

**Comment by logan5171** [comment]
Perhaps Ar1i is collecting statistics worldwide Pokemon ;-)

**Comment by Ar1i** [comment]
I can tell you what isnt using proxy, first the version check, then the picture download of the pokemon gui. And google login, cause that isnt needed. Everything else is send through proxy! :)

**Comment by HELLspawnTIM** [comment]
Ar1i .... man you are the best .... i totally forgot that there is more going on, than the simple PokemonGO connection
Thanks for the quick answer ... now I can rest in peace and watch my 4 BOTs doing there work via your nice BOT tool
Thanks for adding proxy function again!!

**Comment by WhoBotWhoBad** [comment]
Not im my case. I have more than 4 bots running through proxy but I still get softban
