### ISSUE TITLE
Getting This Error On Start ( IT occured after fast close on startup)

### ISSUE THREAD

**Issue by Serimert90** [Ar1i/PokemonGo-Bot#2844]
![ss](https://cloud.githubusercontent.com/assets/16742552/17581265/4909fafe-5fad-11e6-8578-349d0d307b74.PNG)

**Comment by Juiche** [comment]
http://image.prntscr.com/image/e28f659b70b2422782b4f53e5d066a99.png

same.

**Comment by Ar1i** [comment]
clear translation folder
