### ISSUE TITLE
No XP per hour

### ISSUE THREAD

**Issue by wa666** [Ar1i/PokemonGo-Bot#2845]
![eee](https://cloud.githubusercontent.com/assets/20918380/17581412/f3b7dd16-5fa5-11e6-94f3-06ec9f264fac.png)

I do not win xp you also?

**Comment by mirageasti** [comment]
Looks like a softban?

**Comment by wa666** [comment]
No soft-ban..

**Comment by jodirt282** [comment]
Inventory full. It seems all the pokemond you're trying to catch are getting away.

**Comment by cyb0rg01** [comment]
Well, I can see XP per hour in your screenshot. It says "8861". You are not catching any Pokemons. Have you configured store some normal Pokeballs in your item settings? - You need any type of Pokeball available in your stash.

**Comment by phodem** [comment]
0 pokeball or your pokemon inventory is maxed out 250/250

**Comment by wa666** [comment]
Thanks your for reponse, Yes i have 0 pokeball in my inventory lol.

**Comment by PokemonGoer** [comment]
drop all those potions and revives

**Comment by Kidnub** [comment]
also he is faster as 10Km so no egg will open XD also check always that you have min some normal pokeball if not you cannt catch normal small cp pokemon XD
