### ISSUE TITLE
I got a Problem and i dont know why? Explain it

### ISSUE THREAD

**Issue by ArifCNR** [Ar1i/PokemonGo-Bot#2846]
![error](https://cloud.githubusercontent.com/assets/20900409/17581300/35136d26-5fa5-11e6-9772-d40f4d54ff81.JPG)

![1](https://cloud.githubusercontent.com/assets/20900409/17581402/dfedd2ae-5fa5-11e6-9b76-bbb9f23e2831.JPG)
![2](https://cloud.githubusercontent.com/assets/20900409/17581403/e0024054-5fa5-11e6-8c81-4c5344ac1d16.JPG)
![3](https://cloud.githubusercontent.com/assets/20900409/17581404/e003f44e-5fa5-11e6-8a15-a0afe7d83552.JPG)
![4](https://cloud.githubusercontent.com/assets/20900409/17581405/e00877da-5fa5-11e6-9ea5-fca1b63bdb78.JPG)

Where is my failure? I did the same like every time but this aint going no more.

**Comment by ArifCNR** [comment]
PS thats not my real email i yust put a non exsisting email in there.

**Comment by w19ten** [comment]
are you VPN or behind firewall?

**Comment by PokePro21** [comment]
dont set great ball 0 it will not catch pokemon with more CP just a suggestion for you

**Comment by ArifCNR** [comment]
i use the bot at work so i cant open any system settings

**Comment by ArifCNR** [comment]
ahh ok i try the ball thing

**Comment by phodem** [comment]
not, you must have entered wrong id or password. It can't pull data from sever.  Wrong login infor, and the bot auto retry more than 4 times, must have banned 15  mins

**Comment by sylva91** [comment]
same here

**Comment by ArifCNR** [comment]
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: †. Path '', line 42, position 1.
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei PokemonGo.RocketAPI.Logic.Translation.Translation..ctor(String languageCode) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Translation\Translation.cs:Zeile 36.
   bei PokemonGo.RocketAPI.Logic.Translation.TranslationHandler.Init() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Translation\TranslationHandler.cs:Zeile 27.
   bei PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\GUI.cs:Zeile 119.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1055.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly-Version: 1.0.9.3.
    Win32-Version: 1.0.9.3.
    CodeBase: file:///C:/Users/a42124/Desktop/Neuer%20Ordner/PBOT/PokemonGo.RocketAPI.Console.exe.
----------------------------------------
POGOProtos
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/a42124/Desktop/Neuer%20Ordner/PBOT/POGOProtos.DLL.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1055.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System


![1t](https://cloud.githubusercontent.com/assets/20900409/17585045/dd1fee0e-5fb9-11e6-8a5e-cf74f916f37f.JPG)

**Comment by d4zu4x** [comment]
i think that need .net ver 4.5.

**Comment by Ar1i** [comment]
delete translation folder should fix that
