### ISSUE TITLE
How to Setting Tranfer Low IV 90

### ISSUE THREAD

**Issue by Thehackerzii** [Ar1i/PokemonGo-Bot#2848]
![image](https://cloud.githubusercontent.com/assets/20965536/17581807/2280b1e6-5fd2-11e6-8fe6-cdff966f8a05.png)

How to Setting Tranfer Low IV 90

**Comment by PokePro21** [comment]
@Thehackerzii  where you got so much snorlax ? share your Lat & Long . I dont have a single snorlax :(

**Comment by Ouargue** [comment]
You have 3 snorlax > 1000cp, it keeps you 3 pokemons under this limit. Just change your limit CP value

**Comment by PokeMungo** [comment]
where do you farm snorlax? haha

**Comment by immonts** [comment]
coords for snorlax? hehe
