### ISSUE TITLE
The bot can't found pokestop

### ISSUE THREAD

**Issue by DiableXV** [Ar1i/PokemonGo-Bot#2849]
I have put a proxy but the bot say : We can't find any pokestop in a range of 6000 m, and it's a fake adress mail for the screenshot

![2016-08-11_094401](https://cloud.githubusercontent.com/assets/20965471/17581860/84c041fc-5fa8-11e6-9368-31484d36c68e.png)

![2016-08-11_094433](https://cloud.githubusercontent.com/assets/20965471/17581826/55b0a2f8-5fa8-11e6-8644-f49d558ba121.png)

![2016-08-11_094505](https://cloud.githubusercontent.com/assets/20965471/17581830/59db213c-5fa8-11e6-8412-7fb407ffc2f1.png)

**Comment by PokePro21** [comment]
try after some time

**Comment by daemonn54** [comment]
I have this problem too. Did you fixed?

**Comment by keustii** [comment]
sometimes niantic srv are not stable.
just try later

**Comment by HELLspawnTIM** [comment]
I assume somebody else uses your configured proxy 81.21.77.204 : 8083
try another proxy

And as you now posted your proxy server public on this site, I PROMISE that somebody else will now use it. So say goodbye to this proxy man  :-)

**Comment by rvonz** [comment]
same here

**Comment by kalaboso25** [comment]
I can't find any pokestop ..

**Comment by bertojk** [comment]
try to reset your ip address on your router, wait half of one hour and try but just with one login. it works on me

**Comment by immoempe** [comment]
IP ban

**Comment by DiableXV** [comment]
Ok thank you for your answer :)

**Comment by rvonz** [comment]
just wait god ar1i to fixed this bug

**Comment by Ar1i** [comment]
@rvonz cant do anything its IP Ban. Your fault not mine.
