### ISSUE TITLE
SOLUTION - can't find any pokestops in range of X m

### ISSUE THREAD

**Issue by skillxtornado** [Ar1i/PokemonGo-Bot#2851]
Hey! So I saw a lot of you have the same problem I had -  used 2 accounts with the same ip or somehow different so you couldn't find any pokestops anymore. Solution is to download or get back from ur deleted things on ur computer the older version of the bot. Make sure it's the latest build older version not just a different fix but same latest built version as the newest one. So short -  use the older latest build version to fix pokestops problem            PS : I guess ar1i needs to fix it cause it seems like the bot saves the pokestop issue itselfs.

**Comment by sauce2k** [comment]
where can i download older version ?

**Comment by skillxtornado** [comment]
I don't know, maybe search in Google but if u did download it before look up ur "trash can"  of your computer to recycle.

**Comment by dodogtg** [comment]
![no](https://cloud.githubusercontent.com/assets/20829256/17583802/0d3f0e30-5fdd-11e6-96d1-5f7cf8f3d335.jpg)

**Comment by Flashnasty** [comment]
here you can download the Older Verions ;) and no Problem :) 

http://www85.zippyshare.com/v/ZoRtpIzS/file.html

**Comment by Abbasoo** [comment]
Use PokeBot v4.2

**Comment by skillxtornado** [comment]
dodogtg try use the "force unban"  button so it can unban you on the next pokestop

**Comment by aleksej1992** [comment]
@dodogtg You need Pokeballs for most Pokemon. Set on your items like 50 Pokeball

**Comment by dodogtg** [comment]
@aleksej1992 thx btw...

**Comment by sauce2k** [comment]
thanks older version work for me

**Comment by sigmaxbpo125** [comment]
so many old version which 1 to be use?? name of folder?

**Comment by d4zu4x** [comment]
i'm used 10.08.11.28
2 bot with singgle ip, at same pc. running from 3 hours ago and stil running good.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
