### ISSUE TITLE
NOT A BIG ISSUE

### ISSUE THREAD

**Issue by DangerousHIV** [Ar1i/PokemonGo-Bot#2852]
was wondering if theres a way to get it to transfer pokemon i see theres a setting yes but it doesnt seem to transfer them i can do it manually no biggie but just wondering if theres a lil fix to it or if im doing something worng other than that its not a big deal i can go thru and do it manually but wen i leave it afk it fills up

**Comment by gummyruler** [comment]
Check the boxes of pokemon you do not want transferred. Set the CP cap to 4000. and put 99% on the IV keep box. There done.

**Comment by Ar1i** [comment]
^

**Comment by DangerousHIV** [comment]
sir i do this lol still no transfer sorry to say
