### ISSUE TITLE
Seit heute geht bei mir nur noch 1 Bot pro IP

### ISSUE THREAD

**Issue by pilota56** [Ar1i/PokemonGo-Bot#2855]
Ist das bei euch auch so? STarte ich nen zweiten Bot, kommt der IP Bann nach ca. 3-4 Minuten.

**Comment by AlpaEZPZ** [comment]
das ist schon seit gestern so,
vorgestern waren es noch 3 instanzen die man öffnen konnte.
Wenn du es anders willst brauchst du entweder einen proxy für jede instanz oder eine zweite internetleitung ( zb. tethering per handy ( allerdings darf das handy dann nicht im w-lan sein ) )

MfG

**Comment by ochinochin** [comment]
![11](https://cloud.githubusercontent.com/assets/20947976/17584780/a4dca9f0-5fe2-11e6-888e-5fbc0ec7cf71.png)

walking back ???

**Comment by PokeMungo** [comment]
^ soft ban

**Comment by Kidnub** [comment]
geht seit 2 tagen also seit gestern nicht mehr als ein bot XD force unban und lass nur einen laufen XD( vor dem unban bitte eine neue ip machen und dann force unban nach neustart des botes mit neuer ip) 
XD

**Comment by pilota56** [comment]
Ist mir bloß aufgefallen. Ich nutze jetzt 2 Proxys. Hab jetzt drei Accounts laufen, das reicht.

**Comment by Kidnub** [comment]
hoffe das sind private proxys weil public proxy machen in moment auch nicht wirklich viel XD

**Comment by ochinochin** [comment]
งงมาก ไม่มีใครพูดไทยเลย 555

**Comment by pilota56** [comment]
Jap, sind meine eigenen.
Wie machen denn das jetzt die Leute, die an öffentlichen Hotspots spielen? Geht das auch nicht mehr?

**Comment by Kidnub** [comment]
ka glaube das wird das problem von pokemongo aka nintendo XD weil glaube nicht das die alle im public wlan bannen sonst rip wlan XD

**Comment by Melja17** [comment]
Hallo Zusammen,
ich bekomme folgenden Fehler wenn ich mir meinen Standort aussuchen möchte...kann mir da jemand weiter helfen?
"Exception: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
We are sorry, but we don't have imaganery at this zoom level for this region."

Ich kann Zoomen so viel ich will, steht die ganze zeit das selbe da.

**Comment by neocrypton** [comment]
der bann kommt bei mir auch mit proxy beim zweitbot...

**Comment by pilota56** [comment]
Dann läuft vielleicht noch mehr über den Proxy. Meine beiden Proxys laufen ohne Probleme durch.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
