### ISSUE TITLE
Can't Find any PokeStops

### ISSUE THREAD

**Issue by Zefry91** [Ar1i/PokemonGo-Bot#2857]
![screenshot 163](https://cloud.githubusercontent.com/assets/20967454/17585001/fd0816b0-5feb-11e6-8a4d-2c17d0fabf4e.png)
I have been trying to restart the pokebot and my computer but it doesn't seem to work anymore.
How can i fix this?

**Comment by keustii** [comment]
wait, and restarte the bot

**Comment by AlpaEZPZ** [comment]
ip ban restart router or wait for half an hour, and dont start more than one bot...

**Comment by Zefry91** [comment]
I'll try to wait for a few hours @AlpaEZPZ @keustii

**Comment by Kidnub** [comment]
get a new ip and stop multibotting XD one bot= one ip

**Comment by FatXana** [comment]
Do you automatically get unbanned after changing IP?

**Comment by Kidnub** [comment]
no just force once unban ;)

**Comment by FatXana** [comment]
Thanks.

**Comment by multik3d** [comment]
@FatXana If you see no Pokestops you're IP Banned, if you see pokestops but can't collect anything from pokestops you're soft-banned and you can force unban or manually spin a pokestop 40 times.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
