### ISSUE TITLE
มีใครเป็นคนไทยบ้าง ใช้บอทไม่ได้ มันเดินกลับมาที่เดิมตลอด ตั้งค่ายังไง

### ISSUE THREAD

**Issue by ochinochin** [Ar1i/PokemonGo-Bot#2858]
![11](https://cloud.githubusercontent.com/assets/20947976/17585147/54e32490-5fe4-11e6-824d-a813dc1aa1f4.png)
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Thehackerzii** [comment]
ไม่ต้องใช้ไง อิอิ

**Comment by ochinochin** [comment]
โหยยย ง่ายไปอะครับ 
 มันต้องมีวิธีแก้สิ เนอะ

**Comment by ochinochin** [comment]
รออัพเดตละกัน

**Comment by Thehackerzii** [comment]
มันเป็นที่เซิฟ

**Comment by tung7227** [comment]
HTTPS Proxy IP มันทำยังไง ช่วยหน่อยได้ เรางง

**Comment by 0chin0chin** [comment]
งง เหมือนกันเลย แต่ปกติเราก็ไม่ใส่นะ มันก้บอทได้อยู่

**Comment by Ar1i** [comment]
Use english or i cant support you.

**Comment by 0chin0chin** [comment]
Help me please 😁😁
