### ISSUE TITLE
READ BEFORE CREATING NEW ISSUES AGAIN AND AGAIN!!!

### ISSUE THREAD

**Issue by IbnuKhafid** [Ar1i/PokemonGo-Bot#2859]
You know for some of you that got a problem with the bot, dont pressure Ar1i too much with so many questions and etc, instead support him. If you got a problem with the newest bot, use your head before you complained too much, use the older version, like 1.0.7.0 - 1.0.7.9 before the 1.0.8.0 version. I got IP banned too, and I cant botting for a long time with the newest version but I didnt complain, cause I already saw the Issues are already there, so we can just search the SAME ISSUES we got and READ, instead of making so many SAME ISSUES,  So use your head, your brain, think instead of making so many issues that probably made the programmers confused, look at the bright side, they give the best chance for you guys to catch pokemons without getting tired walking around here and there to find pokestops, nearby pokemons and fight in the gyms wuth the highest CP ever, but you guys just complained and complained too much.

So anyone that got problems with the newest version, just use the older one, from 1.0.7.0 - 1.0.7.9.
I got no problems botting with the older version.

LET THE PROGRAMMER FIX IT AND DONT MAKE THE SAME ISSUES THAT ALREADY THERE, U JUST CAN SEARCH AND READ IT.

PLEASE BE GRATEFUL TO SOMEONE THAT WANNA HELP YOU, DONT MAKE THEM SUFFER TOO MUCH BY COMPLAINING TOO MUCH, PUT YOURSELF IN THEIR SHOES AND THINK HOW HARD IT IS TO BE A PROGRAMMER.

BE GRATEFUL GUYS!

**Comment by Yotumn** [comment]
@IbnuKhafid This entire thread you made is pointless.. you are just doing the same thing, only with different words.. Flooding the github with useless threads makes it harder for inexperienced or even slightly dumb people (no offense) to find the correct issue to read.

So pls, if you have nothing useful to say, say nothing at all ;)
