### ISSUE TITLE
Fastest XP/h Config?

### ISSUE THREAD

**Issue by XxAirWalker26xX** [Ar1i/PokemonGo-Bot#286]
Hey guys just asking people what theyre getting for max xp/h and what ur configs are?
Mines 26k/h idk why but it dropped from 60k after an update yesterday.

**Comment by wegweisen** [comment]
Same^^ Started with 60k today than 30k the whole time until now. Just downloaded the new version and now I have 5k EXP per hour.

**Comment by Hitra** [comment]
50 km/h 5000 km evolve rats piggy's ... use lucky egg
![3](https://cloud.githubusercontent.com/assets/20727686/17263297/94b720de-55e0-11e6-82b3-59f8d57dfa26.JPG)

**Comment by XxAirWalker26xX** [comment]
Oml

**Comment by XxAirWalker26xX** [comment]
dont u mean 5000m not km?
