### ISSUE TITLE
Here you can Download the Older Versions of the Bot !!

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#2860]
for the people where the new BOT isnt working

**Comment by neocrypton** [comment]
why?
some older versions didn't work correctly?

**Comment by sigmaxbpo125** [comment]
which version to use?!! so many version

**Comment by PokeMungo** [comment]
i think the new version now is fixed. download it now

**Comment by IbnuKhafid** [comment]
read my issues, you can find it there

**Comment by Ar1i** [comment]
not allowed here @Flashnasty.
