### ISSUE TITLE
Sort Pokemon in Pokemon-List by numbers

### ISSUE THREAD

**Issue by M31860** [Ar1i/PokemonGo-Bot#2861]
@Ar1i  
Is it possible to add another sort method in the pokemon list? It would be very good if you can sort by numbers. Like in Pokedex.
#1 Bisasam
#2 Bisaknosp
and so on.
It would be easier when you transfer and evaluate your pokemons.

**Comment by PokeMungo** [comment]
+1

**Comment by totalyfailed8** [comment]
+1

**Comment by Captnred** [comment]
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by tmathura** [comment]
+1

**Comment by buntu234** [comment]
+1

**Comment by PureDizzi** [comment]
This is better than sorting by name. You can glance at the next evolution of the monster as it is next in the Dex.
