### ISSUE TITLE
Transfer don't seem to be working while farming

### ISSUE THREAD

**Issue by Gin520** [Ar1i/PokemonGo-Bot#2863]
I have set max transfer IV 90%, and CP 1200 
however, when it farms, it says it transferred, but after a while, it will say Inventory full and error catching pokemon. 

When I look at the inventory, i got a lot of the same type of pokemon which it didn't transfer.

**Comment by PokeMungo** [comment]
that is weird. mine is working fine.... try restarting your bot mate.

**Comment by metehank** [comment]
There is a Max. duplicate pokemon number. If you set it to 0, you will have no pokemon under 1200 cp. If you set it to 1 it keeps one for each pokemon type. So if you don't want any pokemon under 1200 cp you should set it to 0.

**Comment by Ar1i** [comment]
Transfer works. Your setrtings is wrong then.
