### ISSUE TITLE
Can't see any pokestops 

### ISSUE THREAD

**Issue by aquaeous** [Ar1i/PokemonGo-Bot#2864]
Just curious if anyone else is having the issue! im running only one bot at a time so i'm pretty sure its not an IP ban are the servers jacking up again or did i just transfer too many pokemon at once?

**Comment by PokeMungo** [comment]
your are soft ban bro. restart router :)

**Comment by aquaeous** [comment]
Ive restarted my router im pretty sure its not an IP ban, again Only running one bot not using any sketchy settings or the like.

**Comment by totalyfailed8** [comment]
change ip

**Comment by DiTechRacer** [comment]
HAHA he said its not an ip softban and everyone says IP change xD thats funny

**Comment by PokeMungo** [comment]
then.. wait for 30 minutes to 1 hour. and it will be Ok.

**Comment by aquaeous** [comment]
its alright ill just check server status i dont think i couldve made this post any clearer

**Comment by PokeMungo** [comment]
multik3d:
If you see no Pokestops you're IP Banned, if you see pokestops but can't collect anything from pokestops you're soft-banned and you can force unban or manually spin a pokestop 40 times.

**Comment by aquaeous** [comment]
pokemungo have you ever heard of down detector? i just found out its a niantic server issue and not an IP ban multiple people are having the same issue and not because they used a bot.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by aquaeous** [comment]
changed my location and found pokestops! oh boy
