### ISSUE TITLE
best coords for xp farm

### ISSUE THREAD

**Issue by faturradani** [Ar1i/PokemonGo-Bot#2867]
can anyone share the best location/coords for xp farm? I tried disneyland tokyo and sydney the best I got is 60k/hour :(

**Comment by Ouargue** [comment]
This isn't a forum... Take a look at google.

**Comment by Bangden** [comment]
read > #2371 and closed

**Comment by gummyruler** [comment]
Not an issue but here:

https://high-minded.net/threads/pokemon-go-settings-locations.51020/page-3#post-497686
