### ISSUE TITLE
Out of track - randomly walking on the map outside of walkways and pathways...

### ISSUE THREAD

**Issue by casqueargent** [Ar1i/PokemonGo-Bot#2868]
Hi,

Just realized that the last version of the bot does not follow the streets and walkways and just randomly make its way through what should be private properties, gardens, buildings and so on (looks a bit suspicious)... This did not happen with the previous versions for which I'd like to first thanks the creators that are doing an amazing work !!

Just wanted to report this. Keep the good work up. And if you manage to correct this bug please let me know. I'm going back on the previous version for now. 

All the best,

M.

![pokemongo](https://cloud.githubusercontent.com/assets/20968354/17586064/bd4131fa-5fbf-11e6-8eab-41e28b4c7c36.jpg)

**Comment by Kidnub** [comment]
you know you use a bot this, bot is like a ghost on maps :) buildings .. sea*s ... fire np ;)
