### ISSUE TITLE
skiplast field called on an end-group tag, indicating that the corresponding start-group was missing

### ISSUE THREAD

**Issue by RyanForrester** [Ar1i/PokemonGo-Bot#2869]
Simply getting red text with this error displaying.

**Comment by monoxacc** [comment]
I think Niantic blacklisted your server ip range. For example Amazon AWS is blacklisted, too.
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/103

**Comment by Ar1i** [comment]
^

**Comment by RyanForrester** [comment]
Aaah - it's running on an Azure vm. Thanks!
