### ISSUE TITLE
[REQUEST] Transfer IV over CP option

### ISSUE THREAD

**Issue by Flocke90** [Ar1i/PokemonGo-Bot#287]
id love to see this in an upcomming version of the bot :) hate it to see my 90%+ mons are getting transfered, while my 1200cp+ (20%) are still prefered somehow by the bot :-/

**Comment by cwirek91** [comment]
Ye its usefull feature. we need this!

**Comment by vsoraas** [comment]
Signed, would love this feature (to be improved). I don't know entirely what the current one does, but I also see a lot of higher IV pokemons get trashed in favor of high CP ones.

Maybe put in an option to keep the highest IV pokemon of a type regardless of what treshold is set?

**Comment by Flocke90** [comment]
yeah or maybe you can sort them internally IV-wise and trash everything thats like below XX%.
