### ISSUE TITLE
MAX CP information

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2870]
On Logfile we can see:
[10:30:03] Egg hatched and we got a Jynx CP: 936 MaxCP: 980 Level: 20 IV: 74,22

Is it possible to include MaxCP information on Pokemon List dialog, for all Pokemon on list?

**Comment by eLDeMe** [comment]
+1

**Comment by mancmanGER** [comment]
This is in the xls file which is automatically generated and saved into your config folder.
Open it an have a look.

**Comment by tmathura** [comment]
+1

**Comment by tmathura** [comment]
I don't see any xls file in the config folder. Do you have a screen shot?

**Comment by zzzz9999** [comment]
True it's there. 4th column.
However I have this info: Arcanine CP/MAX CP: 1760/1875
Then I powered up Arcanine (not full) and get 1960 as maximum ...

**Comment by tmathura** [comment]
cool, saw it there now, it's actually the profile .csv file. Any way we could show this in the gui?

**Comment by suttc1** [comment]
@zzzz9999 on lvl 2 you can't upgrade your pokemon to the max yet....
