### ISSUE TITLE
Großes Problem

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#2871]
Hallo also ich habe ein großes Problem und zwar läuft der bot aber nur ca 1-2 min dann entferne ich den Softban. nachdem er beseitigt ist sammelt mein Char keine neuen Pokestops ein und dann bekomme ich direkt wieder einen Softban :/ den ich allerdings dann nicht entfernen kann da er an keine pokestops iwie mehr ankommt. Jetzt habe ich schon den 4 IP Ban jedes mal eine halbe stunde bis Stunde warten bis dass er weg ist. und ich 1-2 min den bot laufen lassen kann 
habe es jetzt seit 9 uhr probiert iwie geht der bot gar nicht mehr 
ohne dass man gebannt wird :/ 
Lasse nur 1 Bot über meiner Home IP laufen , Router resset bringt rein Gar Nichts :(

![kakce](https://cloud.githubusercontent.com/assets/20914952/17586230/b87af8a8-5fc0-11e6-9f01-24c96f98e762.jpg)

bitte um Hilfe :)

**Comment by neocrypton** [comment]
steht doch da oben softban....

warum können die dummen deustchen nicht einfach mal lesen?

einfach mal 1, 2 stzunden nichts machen. dann läufts bestimmt wieder...

**Comment by Flashnasty** [comment]
ahja :D ich habe den softban ja entfernt und er findet dannach nichts mehr wer lesen kann und bischen englisch versteht könnte probably unbanned now verstehen ;) aber auch egal :D

**Comment by Flashnasty** [comment]
und nach 3-4 stundne wenn er wieder geht bekomme ich nach 1-2 min wo er normal läuft direkt wieder nen softban also es kann nicht nur ein Softban sein ;)

**Comment by pilota56** [comment]
Das ist kein Softbann, sondern ein IP Bann, deshalb bekommt der Bot das auch nicht raus. Du kannst nur einen Bot über eine IP laufen lassen. Sobald ein zweiter über deine IP läuft, kommt dieser IP Bann.

**Comment by Flashnasty** [comment]
ich habe nur einen Laufen :DD dass ist ja dass Problem :/ 
1 bot auf meiner Home IP 
handy war ich ganze zeit nicht online in Pokemon go 
router reset bringt nichts 
und nachdem der IP ban weg ist läuft 1-2 min der bot normal dannach kommen ersma eine reihe softbans
und dann ein IP Ban :/

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
