### ISSUE TITLE
Your google account use 2fa create a password the application

### ISSUE THREAD

**Issue by w33dst4r** [Ar1i/PokemonGo-Bot#2872]
kann mir einer helfen ? 
Kam schon ein paar mal öfters...
ging dann aber wieder. aber jetzt ist das beim 2 account genauso.
aber bei google sagt er mir Die gesuchte Einstellung ist für Ihr Konto nicht verfügbar.

**Comment by jeremie152** [comment]
you have 2 account connected disconnect the first and try anymore

**Comment by w33dst4r** [comment]
wo sollen die denn eingeloggt sein ? ^^ bzw WO soll ich sie abmelden

**Comment by Ar1i** [comment]
Dann deaktiver 2fa für dein google konto

**Comment by w33dst4r** [comment]
das einzige was hier steht ist, Bestätigung in 2 schritten und das steht bei mir auf aus ich weiß echt nicht weiter sorry entweder bin ich zu blöd es zu finden oder irgendwas passt nicht
