### ISSUE TITLE
[Bug] Recycling Items when Inventory is Full.

### ISSUE THREAD

**Issue by b3shoy** [Ar1i/PokemonGo-Bot#2877]
I noticed the below behavior in the latest update.

![inventory full](https://cloud.githubusercontent.com/assets/20810298/17586791/0eefa546-5fc4-11e6-9987-c7811f666f74.PNG)

The bot doesn't recycle items except on Initiation and when it couldn't take anything from the Pokestop.
And my Inventory setup is max 330 Items.

Thanks for your hard work @Ar1i & Co., Really Appreciated! :v:

**Comment by Ar1i** [comment]
That isnt a bug, edited this soo, we do lower requests
