### ISSUE TITLE
Russian language - incorrect encode; IV transfer

### ISSUE THREAD

**Issue by 3v01ut10n** [Ar1i/PokemonGo-Bot#2879]
1. When the Russian language strange symbols, incorrect encoding.
2. At the same IV transfer a stronger pokemon.

![rus](https://cloud.githubusercontent.com/assets/20968560/17586830/45fcb72a-5fd5-11e6-9841-9bbccc004950.png)

**Comment by ArFGLR** [comment]
Same problem with Turkish.
