### ISSUE TITLE
the bot its not working D:

### ISSUE THREAD

**Issue by vShazerJr** [Ar1i/PokemonGo-Bot#288]
[15:11:07] [#1 of 25] retry request https://pgorelease.nianticlabs.com/plfe/89/rpc - Error: System.Exception: Exception of type 'System.Exception' was thrown.
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 31

**Comment by XxAirWalker26xX** [comment]
same it could be their servers

**Comment by Kelendris** [comment]
It works.

![untitled](https://cloud.githubusercontent.com/assets/20727621/17263584/18244644-55e2-11e6-8ca2-1e0de7562e23.png)

**Comment by XxAirWalker26xX** [comment]
Like i said this can be server side

**Comment by Doberok** [comment]
+

**Comment by XxAirWalker26xX** [comment]
its working again for me

**Comment by HaydarOzturk** [comment]
If you could do some research before commenting here, you would know that error is server error and mostly not related to the bot. You would've save a programmer time wich he will use that time to update and make more amazing stuff for people like you! Just don't type everything you encounter. Wait a little bit. Do a search. Watch some videos...

**Comment by MarvinSCR** [comment]
![loading](https://cloud.githubusercontent.com/assets/20703104/17263855/98078780-55e3-11e6-861b-58c77864f9f2.PNG)
no coming more..

**Comment by Hitra** [comment]
servers are down
[http://downdetector.com/status/pokemon-go](url)

**Comment by HaydarOzturk** [comment]
http://www.mmoserverstatus.com/pokemon_go Google server enterence has a lot of ping...

**Comment by Ar1i** [comment]
Server Issue.
