### ISSUE TITLE
Little sugestions

### ISSUE THREAD

**Issue by totolef** [Ar1i/PokemonGo-Bot#2880]
This is little suggestions : 
1) A way to pause the bot. (I use the pokemon list to do many things and I would like to do it without the bot)
2) A translation of the Pokemon names
3) A way to transfer all pokemon under a certain IV except ones we keep for XP
4) Other info about the pokemons in the list like : the type of the attacks, the number of dust needed for PowerUp
5) The map in an other tab of the window, not in an other window

All my ideas for now. Will add more below

**Comment by IceQ1337** [comment]
Read before posting Issues...
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Captnred** [comment]
Also please close this thread as it's not an issue.
