### ISSUE TITLE
Bot not opening on WINDOWS 7 - 64 BIT

### ISSUE THREAD

**Issue by monchen** [Ar1i/PokemonGo-Bot#2881]
Bot (using the new version or old version) not opening or working properly on WINDOWS 7 - 64 BIT. 

 I already tried installing Microsoft .NET and said i have new version.

Need help on fix. TIA

![bot not working on windows 7 64bit](https://cloud.githubusercontent.com/assets/20968999/17587090/9de3e88e-5fce-11e6-9172-abd51081f778.jpg)

**Comment by Ar1i** [comment]
install newest net framework

**Comment by monchen** [comment]
thanks Boss. i will try
