### ISSUE TITLE
Transferring issue

### ISSUE THREAD

**Issue by cacaz** [Ar1i/PokemonGo-Bot#2882]
can anyone tell me how to set transfer settings? i mean.. i set it %90 and max cp 900 but it keeps everything i caught.
should i set anything else?

**Comment by VisualBoyAdv** [comment]
Maybe because you allowed a lot of duplicates so they keep it?

**Comment by Zodice** [comment]
You have to change the amount of duplicate pokemon that  you want.

**Comment by Kidnub** [comment]
or has not undo the check box ;)

**Comment by Zodice** [comment]
Sorry VisualBoyAdv just posted one second before me, i didn't want to say something useless !

**Comment by cacaz** [comment]
![ss](https://cloud.githubusercontent.com/assets/20922100/17587204/6bcc46f6-5fcf-11e6-8c3e-d4fcd8a3ea1f.jpg)
this is my settings and still transferring nothing.

**Comment by eLDeMe** [comment]
@cacaz Uncheck this

![image](https://cloud.githubusercontent.com/assets/20787975/17587240/31e98d54-5f84-11e6-9a24-1bfd9d913616.png)

**Comment by DirtyAssign** [comment]
Are that wrong settings? Or why is my geowaz tranfered with the higher CP?
![transfer_error_transfer_stronger_pokemon](https://cloud.githubusercontent.com/assets/20907595/17587251/54b313b2-5fc7-11e6-9ec9-e94799fa8208.png)

**Comment by eLDeMe** [comment]
@DirtyAssign download new version

**Comment by Zodice** [comment]
I have exactly the same problem but with my highest IV.

**Comment by DirtyAssign** [comment]
Ok. It seems to be solved. After downloading newest version.

**Comment by eLDeMe** [comment]
@DirtyAssign great, now close your thread, please

**Comment by DirtyAssign** [comment]
@eLDeMe I haven't opened a thread. I wrote only my error in this issue.

**Comment by Captnred** [comment]
You have opened a thread. That's what this is. Now near the comment button should be a close issue button. If you wouldn't mind clicking that please.

**Comment by DirtyAssign** [comment]
I haven't. I did only some comment's. Because of that,  I can delete my comment's only. Have a look at the screenshot.
![issue](https://cloud.githubusercontent.com/assets/20907595/17588877/de6d9f14-5fd1-11e6-983d-67f62e865397.png)
