### ISSUE TITLE
Transfer Pokemon % IV issue

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#2883]
Hi,

there is a big problem with transfering pokemons.
Sometimes, there is a message "Transfer Magikarpe CP 100 IV 90% (Best is CP 100 IV 90%)".
So i lost a lot of very good pokemon with very good IV.
Of course the option "low IV first" is on.

I don't know if it's only me or a problem in the bot, but i had to say it.

Thank you,

Zodice.

**Comment by eLDeMe** [comment]
@Zodice show screenshots of configs and what version are you using

**Comment by eLDeMe** [comment]
@Zodice Latest Build - 11.08 11.28  ver. 1.0.9.4 working perfect for me

**Comment by Zodice** [comment]
That wasn't the latest version.
And just a few second there is already a new version.

**Comment by Zodice** [comment]
The 1.0.9.5 is available now.

**Comment by eLDeMe** [comment]
@Zodice  I know, I already downloaded but not tryed

**Comment by eLDeMe** [comment]
@Zodice If new version fix your problem, please close your thread :smile:

**Comment by rvonz** [comment]
turn off auto transfer

**Comment by toroageito** [comment]
I have same problem with new version. Not happend all the time with all pokemon, but I lost my good exeguttor.

**Comment by eLDeMe** [comment]
@toroageito show screenshots of your configs

**Comment by Zodice** [comment]
The problem is that now i don't use the transfer option anymore because i'm afraid of losing my 97% IV magikarpe and 90% Dratini.

**Comment by PrasadS1992** [comment]
Untick the "low IV first" option and and select all the important pokemons
in "Do not transfer " option. That way even if if transfers a
pidgey/pinsir/krabby etc of high cp/IV by mistake, wont really matter.
Anyways gym battles are won with Dragonites and snorlaxes.

Thank you
Prasad

**Comment by AlpaEZPZ** [comment]
seems like its fixed with last update.

**Comment by Zodice** [comment]
![name error](https://cloud.githubusercontent.com/assets/20968987/17588067/a3dc8d56-5fcc-11e6-8ffc-e163412422fa.png)

New problem on the last version


![config 1](https://cloud.githubusercontent.com/assets/20968987/17587699/14c394d6-5fca-11e6-992d-658d214f38a9.png)
![config 2](https://cloud.githubusercontent.com/assets/20968987/17587700/14c48b16-5fca-11e6-9a0a-20525236978a.png)
![config 3](https://cloud.githubusercontent.com/assets/20968987/17587698/14c1234a-5fca-11e6-9e46-9352d159d5f0.png)
![config 4](https://cloud.githubusercontent.com/assets/20968987/17587697/14b432e8-5fca-11e6-978f-42fe63145495.png)
And all the config

**Comment by Zodice** [comment]
@PrasadS1992 I can do this but i want my "bad pokemons" to have a good IV too.
