### ISSUE TITLE
สอนตั้งค่าการใช้ siting Proxies and siting Pekeball , Help me please

### ISSUE THREAD

**Issue by ochinochin** [Ar1i/PokemonGo-Bot#2887]
![12](https://cloud.githubusercontent.com/assets/20947976/17587550/498e658c-5ff3-11e6-9108-485c83937e3e.png)

How to siting ???

**Comment by ochinochin** [comment]
สอนตั้งค่าหน่อยครับ

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you wouldn't mine closing this thread. Seeing how this is not an issue.

**Comment by Ar1i** [comment]
i dont understand your language, so i cant help sorry
