### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by MaTiUs77** [Ar1i/PokemonGo-Bot#2888]
When i start the application, this error appears, and not read the config file, i need reconfigure all the box

> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: †. Path '', line 42, position 1.
   en Newtonsoft.Json.JsonTextReader.Read()
   en Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   en Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   en Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   en Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   en PokemonGo.RocketAPI.Logic.Translation.Translation..ctor(String languageCode) en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Translation\Translation.cs:línea 36
   en PokemonGo.RocketAPI.Logic.Translation.TranslationHandler.Init() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Translation\TranslationHandler.cs:línea 27
   en PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\GUI.cs:línea 119
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://cloud.githubusercontent.com/assets/8823839/17587438/d3f454de-5f9e-11e6-8027-ed89e120ad7c.png)

**Comment by Ar1i** [comment]
Try to delete translation folder

**Comment by frostono** [comment]
translation folder will rebuild everytime

**Comment by Ar1i** [comment]
should be fixed in newest build
