### ISSUE TITLE
some weird errors

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#289]
Hi,

I get these errors atm:
https://gyazo.com/4d48d09cf7df0454f718b2033b2886f1

My second bot is working 100% fine.

**Comment by inurbad** [comment]
im getting the same issue on 2 bots and have 4 other ones running fine

**Comment by MarvinSCR** [comment]
its fixxed now server is ready no bug

**Comment by Ar1i** [comment]
Server Issue.
