### ISSUE TITLE
how to check your items?

### ISSUE THREAD

**Issue by mon2x2** [Ar1i/PokemonGo-Bot#2890]
how to check your items via bot?

**Comment by joe112** [comment]
u cant check it bro, just open on your phone

**Comment by mon2x2** [comment]
thanks! :D

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you wouldn't mind closing this thread. Seeing how it's not an issue.

**Comment by mon2x2** [comment]
yup please do close this thread i'm sorry I dont know where to post for questions :D but thanks anyway :D

**Comment by Captnred** [comment]
I posted the link for the questions. Also if you wouldnt mind closing the thread. The button should be near the comment button.
