### ISSUE TITLE
eventuell hilfreich :D nach IP Ban :P

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#2891]
für die Leute die keine Pokestops finden und direkt gebannt werden !! 
ich dummkopf :P habe nur den stromstecker vom Router gezogen und dachte damit sei alles geregelt neue IP weiter geht der bot :D doch dass war falsch haha :D

Nein ihr habt hinten am Router ein Kleines Loch da steht RESET da steckt ihr iwas rein damit sich der Router Komplett resettet und von neu eine Verbindung aufbaut dann sollte es auch wieder alles funktionieren nach einem IP Ban :P bei mir hat es wunderbar funktioniert

hoffe dem einen oder anderen konnte ich damit weiter helfen :D also ich war zu dumm dafür :DD

**Comment by AlpaEZPZ** [comment]
nur das dann alle einstellungen zurückgesetzt werden...
irgendwie nicht so richtig optimal.

**Comment by mancmanGER** [comment]
Also ich denke Verbindung trennen und neu verbinden gibt die eine neue IP --> ist auf jeden Fall bei T-online und fritzbox so.

**Comment by Flashnasty** [comment]
also bei mir musste ich keine einstellungen neu einstellen alles wie vorher hat verbindung aufgebaut und internet ging sofort bin übrigens bei Unitymedia :)

**Comment by Kidnub** [comment]
nicht alle de provider haben ip dns XD also das du immer wieder ne neue bekommen tust ... zb telecom hat das  dass du ip wechseln kannst , aber kabel/voda haben fix ip ... da ist nix mit router aus an und neue ip nö nö ... das kann man aber mit einen anruf bei den klären weil man mit 2€ mehr kosten ca dann keine fix ip mehr bekommen kann ( kosten sind ca angaben und monatlich) daher wer bei tcom ist , hat luck.. die anderen müssen gucken ob sie die möglichkeit haben ip wechsel zu machen oder ob es fix ist wenn fix provider anrufen fragen ob man ne dynamische ip haben kann weil fix stört XD (normal bieten alle provider das an aber meisten mit extra kosten. )

**Comment by deface0x2** [comment]
Bitte mal nachdenken bevor du anderen einen reset vorschlägst. Das bringt in dem Zusammenhang genauso viel wie ein Neustart, ist nur um einiges dümmer da sämtliche Einstellungen auf den Urzustand hergestellt werden. Wer dann noch zusätzlich seine Internetzugangsdaten in den Router eintragen muss, hat dann eventuell einen nicht unerheblichen Aufwand.

**Comment by Flashnasty** [comment]
ok dann sage ich so wer >> KUNDE BEI UNITYMEDIA << ist für den ist es was ;)

**Comment by deface0x2** [comment]
Noch nie gehört, dass sich bei Unitymedia mit einem reset die IP erneuert. Die Erkennung der Router dort geschieht durch die MAC beim Provider, und dadurch kannst du eigentlich die IP-Vergabe nicht beeinflussen.

**Comment by AlpaEZPZ** [comment]
Die geräte bei unity media werden ähnlich sein wie die von kabel deutschland, dort konfigurieren sich die geräte nicht per hand sondern bekommen ihre konfiguration vom KD server.
Für kunden von anbietern wie kabel deutschland gibt es auch eine lösung eine neue IP zu bekommen.
Im Router muss dafür die DNS manuell verändert werden, somit verliert der router die verbindung und holt sich alles neu ( auch die IP ).

**Comment by SebiWolze** [comment]
Bei UM hat man IPv6 DualStack Lite, da sind die Leases sogar noch ein Stück länger als bei v4.
Daher hilft bei den Kabel-Anbietern in Deutschland sich auf die Weboberfläche einzuloggen, und dann im Router sagen "Neue WAN IP" oder "neu verbinden" anklicken, erst dann gibts auch wirklich eine neue IP.
