### ISSUE TITLE
Sugestion for map

### ISSUE THREAD

**Issue by MaTiUs77** [Ar1i/PokemonGo-Bot#2893]
The application saves the coordinates in HunStats.txt. Someone can add this data to the map? ,
With this, we can see where the Pokémon is captured, and then returns to catch more!

**Comment by Captnred** [comment]
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.
