### ISSUE TITLE
No spot (1.0.9.5)

### ISSUE THREAD

**Issue by Ushushu** [Ar1i/PokemonGo-Bot#2895]
I just update the new  bot and he dont found any stop. My ip is clean and i use proxies (i try 3 differents)
My proxy is in my country and i use bot near my real location. 

![screenushu](https://cloud.githubusercontent.com/assets/20891767/17588202/8cb4d632-5fcd-11e6-8f4c-5c3b184ebc41.jpg)

I already reboot my modem.

Thx for help :)

Sorry for my english.

**Comment by mancmanGER** [comment]
Is the account activated?

**Comment by Ushushu** [comment]
@mancmanGER : Account activated ?

**Comment by w33dst4r** [comment]
ich ahb das selbe problem aber erst wenn ich meinen 2ten bot starten willl...

**Comment by Kidnub** [comment]
proxy?  public ? then find a private proxy

**Comment by Kidnub** [comment]
bitte keine public proxys versuchen das bringt nix bitte hold euch einen private proxy damit sind die chancen höher XD

**Comment by Ushushu** [comment]
Sorry i dont understand deutch. 

I try 3 different proxy from "proxylist.hidemyass.com" perfectly work yesterday but dont work today...

**Comment by deface0x2** [comment]
You are probably IP banned, remember that everyone can use a public proxy.

**Comment by Ushushu** [comment]
Just try 4 more proxies and still dont work ... 7 proxies ban from 3 different list it's a little strange.

**Comment by Saccarai** [comment]
Same problem for me...

**Comment by d4zu4x** [comment]
is that account on bot is same with your phones?? try off your gps on phones. wait 15 minutes. start again. thanks

**Comment by Saccarai** [comment]
It's been 45 min that my phone is off so I think it's not that...

**Comment by monchen** [comment]
that is why i never use the proxy. only 2 bot in 1 PC works well.

**Comment by Ushushu** [comment]
I already reboot modem, 
I ony use 1 bot on my full house,
I dont use that account on my phone,
I already change 13 times my proxy (private and public).

If someone can help :)

**Comment by lucas2107** [comment]
7/10 Proxies are already banned. A lot of people are using proxies and all public proxies are going to be banned. Try using a VPN.

No Pokestop found --> Ip ban.

**Comment by UgitheBugi** [comment]
@Kidnub hey wenn du das schon mit privaten proxy ansprichst kannst du mir da eine seite empfehlen wo man sich da einen holen kann? :+1:  Danke im voraus!

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
