### ISSUE TITLE
NEW ERROR NMIVE NEVER SEEN

### ISSUE THREAD

**Issue by DangerousHIV** [Ar1i/PokemonGo-Bot#2896]
give me end of stack error i have picture but cant figure out how to place but it says skiplastfield called on end-group tag, indicating that the corresponding start group was missing

**Comment by DangerousHIV** [comment]
![1](https://cloud.githubusercontent.com/assets/20882438/17588507/6a92b50e-5f84-11e6-96c6-1a2afaeedfeb.PNG)
![capture](https://cloud.githubusercontent.com/assets/20882438/17588509/70d5cf82-5f84-11e6-82c6-f7b0e4f57f11.PNG)

**Comment by DangerousHIV** [comment]
@Ar1i

**Comment by DangerousHIV** [comment]
and this was right after you bput new update @Ar1i

**Comment by DangerousHIV** [comment]
if someone could help me with this that be great was working 100% till i got .4 to .5 and now same error with pokesniper
![2](https://cloud.githubusercontent.com/assets/20882438/17588841/4b06fe3c-5f86-11e6-9db7-6d3a066a26f9.PNG)

**Comment by brunomassa** [comment]
this error is probably because of the pokemon go server is unstable

**Comment by DangerousHIV** [comment]
other firends of mine are using right now very weird

**Comment by brunomassa** [comment]
the servers are unstable not down is because of that, I have the seame error

**Comment by brunomassa** [comment]
And a @DangerousHIV a question what type of account are you using, a Google or pokemon trainer club?

**Comment by Ar1i** [comment]
Probably of server unstable or the Server where you run the bot is banned
