### ISSUE TITLE
Best locations?

### ISSUE THREAD

**Issue by miaszakal** [Ar1i/PokemonGo-Bot#2897]
Im searching best locations to exp for bot

**Comment by pilota56** [comment]
My best are Santa Monica Peer L.A., 75km/h, 10K Radius ca. 50K / h
Tokyo Disney Land, same settings, 50K per hour

**Comment by gummyruler** [comment]
This is not an issue. Issues only

**Comment by Zodice** [comment]
If you want to "do" your eggs, you have to be a 18km/h maximum.

**Comment by gummyruler** [comment]
All questions and suggestions go here: 
high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

this is issues only.
