### ISSUE TITLE
[ISSUE] Can Someone Explain This?

### ISSUE THREAD

**Issue by itamoye** [Ar1i/PokemonGo-Bot#2898]
trying snipe pokemon with pokesnipers.com and i got this when try catch 1000++ CP 

https://postimg.org/image/t42qcepyz/
![untitled](https://cloud.githubusercontent.com/assets/20969947/17588488/9d748cfc-5ff9-11e6-817b-dce4c0d32f4a.png)

**Comment by deface0x2** [comment]
Doesn't seems like to be a bot issue. It's normal that you can't catch them all.

**Comment by galinha1** [comment]
how use pokesniper on Ar1i/PokemonGo-Bot???

**Comment by Kidnub** [comment]
seems you have no ultra balls XD

**Comment by Zodice** [comment]
Same problem, they go away everytime, i have hyper ball and all.
