### ISSUE TITLE
[Request] Farm Mode

### ISSUE THREAD

**Issue by sufficey** [Ar1i/PokemonGo-Bot#29]
Hey. You may be aware that using Niantics API you can see nearby pokemon (obviously.) You should add a mode where it'll hunt one specific pokemon only and keep going to the nearest pokemon. Ex: Magikarp. It'll keep finding Magikarps and walk to the nearest one. This is useful for getting Gyadros, or just evolving rare pokemon in general.

**Comment by bamoas** [comment]
Good Idea, hope that will be possible soon

**Comment by Ar1i** [comment]
Will add that later, thanks for the suggestion.

**Comment by Ar1i** [comment]
wops dont want to close it

**Comment by gatno** [comment]
That would be great!

**Comment by bamoas** [comment]
@Ar1i  Good Evening, 
did you already had a look for that option ? 
It's nice to farm for example in a spot where many rare pokemons spawn like dratini.. 
there's such a spawn with low Pokestops, thats why it's hard to farm there since it skipps all the dratinis :P
