### ISSUE TITLE
Pokemon (ALWAYS) Got Away while using Pokeball

### ISSUE THREAD

**Issue by Wi1dHunt** [Ar1i/PokemonGo-Bot#2900]
![screenshot 514](https://cloud.githubusercontent.com/assets/20787535/17588845/aa80d17e-5ffb-11e6-857e-fa4774a4cc5f.png)

i have no idea about this

**Comment by Bangden** [comment]
check u're pokeball

**Comment by dominik1122** [comment]
i think you have a softban

**Comment by bendeko** [comment]
you need to make sure you have pokeballs in inventory not just great and ultra balls

**Comment by miaszakal** [comment]
you propably set pokeballs in invent to 0 set 10 and it should help

**Comment by lucienlo** [comment]
If your bag is full and no exist basic pokemon balls,
It will cause this problem.

**Comment by Ar1i** [comment]
^
