### ISSUE TITLE
Wrong date catched pokemon

### ISSUE THREAD

**Issue by 3v01ut10n** [Ar1i/PokemonGo-Bot#2902]
In Pokemon List after aiming (2017 year)
![bug](https://cloud.githubusercontent.com/assets/20968560/17589180/3df530c0-5fe4-11e6-855a-4ceb3365a0cc.png)

**Comment by monchen** [comment]
who cares about date?

**Comment by Kidnub** [comment]
a good dev cares XD but its just a minor problem XD easy to fix for them nice info catch XD

**Comment by monchen** [comment]
hahaha
