### ISSUE TITLE
Suggestion for pogolocationfeeder

### ISSUE THREAD

**Issue by yordii** [Ar1i/PokemonGo-Bot#2903]
Hi,

I know that we may not post suggestions here, but i don't know how to reach the makers of the Bot to know this. 

With Necrobot you can use pogolocationfeeder to get the coords of Pokémon around you / over the world. That's so handy, you can search for example for Charizard and Pogolocationfeeder gives you the coords so u can use it in the bot. 

Maybe it's an idea to implent this in here. 

Please don't hate because this isn't an issue, but i don't know how to tell the makers this. So i opened a issue. 

Pogolocationfeeder: https://github.com/5andr0/PogoLocationFeeder

**Comment by Juiche** [comment]
pokefeeder integrated for pokesniper for auto snipe

**Comment by galinha1** [comment]
@Juiche can you explain the use????

**Comment by gummyruler** [comment]
This is how you reach them close this:

high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
