### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by soulbanes** [Ar1i/PokemonGo-Bot#2904]
Can I have the latest updates download link?

Thank you.

**Comment by bendeko** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2011.08%2013.06.rar


lol

**Comment by monchen** [comment]
go to <> Code tab. select "Build"

**Comment by galinha1** [comment]
plz close

**Comment by deface0x2** [comment]
http://lmgtfy.com/?q=how+to+download+on+github
