### ISSUE TITLE
Problem capturing

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#2905]
Think there is a problem ..

![sans titre](https://cloud.githubusercontent.com/assets/20968987/17589288/2afaf726-5fd4-11e6-9273-2b77e15a0dd1.png)

**Comment by bendeko** [comment]
you need to make sure you have pokeballs in your items not just ultra and great balls

**Comment by Zodice** [comment]
Yes i have all of this

**Comment by lucas2107** [comment]
Maybe softbanned

**Comment by Zodice** [comment]
That's like when you just started the bot you can't capture any pokemons

**Comment by Zodice** [comment]
No, juste after this i captured some pokemons

**Comment by Zodice** [comment]
Or maybe when you are in a new place, because i changed my location, but that's the same : when you just started the bot you can't catch pokemons

**Comment by Zodice** [comment]
![100](https://cloud.githubusercontent.com/assets/20968987/17590047/5ccd0b8c-5fd8-11e6-8f79-3deabe622cea.png)
There is definitly a problem, i didn't captured a 100% capturable ....

**Comment by 1w37** [comment]
Seems like you are soft-banned ! could you use your iPhone to capture Pokemon ? need to spin pokestops

**Comment by lucienlo** [comment]
The item of basic balls is emptied.
It cost me many time to conquer the problem.
I guess the source code is only write the type ball....

**Comment by lucienlo** [comment]
If your bag is full and no exist basic pokemon balls.
It will cause this problem.

**Comment by Zodice** [comment]
I just checked : i have all types of balls, i have place to capture pokemons and i can capture pokemons. The bot can also capture pokemons, after some time.
So the problem come from the bot, when you start it.
