### ISSUE TITLE
cant find pokestops 

### ISSUE THREAD

**Issue by bendeko** [Ar1i/PokemonGo-Bot#2906]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe y
![poke](https://cloud.githubusercontent.com/assets/20948354/17589373/8cfd9092-6028-11e6-9107-931dde56b326.jpg)
our problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by bendeko** [comment]
Anybody know how to fix this ?

**Comment by monchen** [comment]
IP ban. restart router

**Comment by bendeko** [comment]
is that the fake ip ive entered or my actual ip?

**Comment by Experte9** [comment]
Ip ban, or server laggy

**Comment by pilota56** [comment]
A fake IP? Do you use an open https Proxy? Only 1 Bot with 1 IP.

**Comment by bendeko** [comment]
yeah different ip per bot i run ive got 2 running no problem but when i try run a 3rd bot that pops up

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
