### ISSUE TITLE
Mehrere Bots gleichzeitig aufmachen? (GERMAN)

### ISSUE THREAD

**Issue by PCKGOHCKTEAM** [Ar1i/PokemonGo-Bot#2911]
Hey liebe Community,

ist es nun nicht mehr möglich mehrere Bots mit verschieden Accounts gleichzeitig laufen zu lassen?

Wenn doch bitte mit Lösung ;)

Danke im Vorraus!

**Comment by Experte9** [comment]
Nein, da sonst deine IP gesperrt wird.

**Comment by IceQ1337** [comment]
ES IST DOCH ALLES BESCHRIEBEN?
Proxys verwenden oder sein lassen...

Keine Issues erstellen die keine sind!

**Comment by pilota56** [comment]
Schade, dass hier kein Forum mit dran ist. IN dem verlinkten High-Mindet wird man nur beschimpft und wenn man sich wehrt, wird man gebannt. Gibt's noch ein anderes Forum wo man sich anmelden kann um solche Fragen zu klären?

**Comment by testo4life** [comment]
Seid mal, können die Kinder nicht mal lesen ? WTF ! STEHT doch groß im GUI geschrieben 1bot eine Ip sonst ip ban. WAS IS DARAN NICHT ZU VERSTEHEN ?

**Comment by Experte9** [comment]
@pilota56 naja, wie man es nimmt. Das hier ist eigentlich ein solches forum. Nur wurden diese Fragen schon zichmal gestellt. Und irgenwann verliert man dann doch mal die Fassung. 
Wer hier nämlich etwas aktiv ist merkt das täglich die selben fragen kommen.

Bitte erst lesen dann melden. 
Danke

**Comment by pilota56** [comment]
Ich weiß. Ich habe auch schon ca. 100 mal das gleiche erklärt. :-)

**Comment by IceQ1337** [comment]
@Experte9  Nein, dass hier ist eben kein "solches Forum"...
Das ist ein Bereich, den Github zur Verfügung stellt, um Bugs und sonstige Probleme zu melden...
Vorschläge, sowie Fragen, haben hier nichts zu suchen!

Im High-Minded Forum wird man nicht beschimpft etc.
Dies ist der Fall, wenn Fragen zum 100sten Mal beantwortet werden müssen.
Am meisten regt es die Leute jedoch auf, wenn sogar überall steht was Sache ist und die Leute einfach nicht lesen können.
