### ISSUE TITLE
Add http://pokesnipers.com/ api

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#2913]
I'm not in the write place but i don't know where to post it.

So i juste discovered http://pokesnipers.com, and i saw that there is an api of the website.

So i thought that i could be add in the bot, to improve our chance to find rare pokemons.

Thank you for reading.

**Comment by yordii** [comment]
Yes. We really need something like this. Or pogolocationfeeders. That goes to the coords where a rare pokemon is. 

We really really need this

**Comment by Zodice** [comment]
If they add pokesnipers which find the localisation of rare pokemons and pogolocationfeeders which go to the localisation of these rare pokemon, the bot will win a loooooooooooooooooooooooooot of users.
With this, they could add a new app "Super Capture" or something like this, you chose the pokemons that you want, you could have an option "minimum of CP/IV" or "capture all" and voila.

**Comment by Zodice** [comment]
they could add a new page* (not a new app)

**Comment by Zodice** [comment]
Someone know how are the developpers ? To ask them to see that

**Comment by hcarrega** [comment]
Yes sniping is a must

**Comment by yordii** [comment]
Its's hard to ask the developers a question. Hopefully they don't close this issue and really think about this

**Comment by Zodice** [comment]
But to add this they will have to resolve the problem that make the bot not abble to capture pokemons, i don't know if it's when the bot just started or when you go to a new location ..

**Comment by Zodice** [comment]
@yordii Maybe they don't close this issue because they don't even saw it aha

**Comment by gummyruler** [comment]
All suggestions go here:
high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

This is issue only boards.
