### ISSUE TITLE
problem :(

### ISSUE THREAD

**Issue by merth7** [Ar1i/PokemonGo-Bot#2914]
![adsiz](https://cloud.githubusercontent.com/assets/20950245/17590205/79f0a2d8-5fe1-11e6-849d-049c90ec74b6.png)

help me... :(

what should I do. I could not find a solution. :/ :-1:

**Comment by Brayan8337** [comment]
You put your password wrong that's why

**Comment by merth7** [comment]
thank you @Brayan8337  :) idiot me :)

but a new problem :/ 

![ekran alintisi](https://cloud.githubusercontent.com/assets/20950245/17590585/ed623d66-5fe2-11e6-9337-858524548c92.PNG)

**Comment by pilota56** [comment]
IP Bann. Renew your ip.

**Comment by merth7** [comment]
woow thanks bro :+1:  @pilota56
