### ISSUE TITLE
net frame eror

### ISSUE THREAD

**Issue by Tracynew** [Ar1i/PokemonGo-Bot#2915]
my bot suddenly showed this warning..

can you help me?
http://prntscr.com/c4ezvu

![Uploading Screenshot_12.png…]()

**Comment by thepapabear** [comment]
Same problem

**Comment by Ar1i** [comment]
try newest version, if it still happens open a new issue!

**Comment by kyoshofantom** [comment]
i got netframe error with newest version but  Build - 10.8.16 11.55 run ok...
