### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by 121x157** [Ar1i/PokemonGo-Bot#2916]
my ta not rising level appears it. help me please
![sem titulo](https://cloud.githubusercontent.com/assets/20970017/17590977/6549a12e-5fb2-11e6-842e-85f89ff92028.png)

**Comment by hcarrega** [comment]
Possible IP ban

**Comment by 121x157** [comment]
What can I do? I have turned off the modem, but always appears the same screen.

**Comment by hcarrega** [comment]
Need to get other IP...make a router release DNS..or use a VPN or proxy

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by 121x157** [comment]
I rebooted the modem and put the proxy on the bot and now it appeared .
