### ISSUE TITLE
Transferring help

### ISSUE THREAD

**Issue by tomo101** [Ar1i/PokemonGo-Bot#2919]
Could someone please help me quickly with transferring?

Everytime I tick all the boxes to enable things to transfer, I always still have 10cp magikcarp and all that still in my inventory. What is going on? 

I have keep pokemons when can be evolved unticked,,,, Auto trans double poke ticked, max dup pokemons 10, max iv 90 and max cp 999.

What is wrong?

**Comment by pilota56** [comment]
" I always still have 10cp magikcarp "
and "max dup pokemons 10"

Thats the reason.

**Comment by tomo101** [comment]
What? That makes no sense, I change max dup to 2 and it still does not trans....

**Comment by Ar1i** [comment]
probably cause of the cp/iv worth.. and you unchecked keep pokemon which can be evolved?

**Comment by pilota56** [comment]
If the magicarp has 91% IV it stay in your Pocket. If 10 Magicarp has more 90% IV or over 999 CP they all stay in your pocket.
