### ISSUE TITLE
ask for proxy setting

### ISSUE THREAD

**Issue by freetogameplay** [Ar1i/PokemonGo-Bot#2920]
how can i use proxy setting ?

**Comment by 12348766754** [comment]
open the tab.. fill in the info.. lol

**Comment by Zodice** [comment]
What is a proxy ?

**Comment by freetogameplay** [comment]
my proxy or search google?

**Comment by 12348766754** [comment]
@Zodice  http://lmgtfy.com/?q=What+is+a+proxy%3F
@freetogameplay your own proxies. If you use shared, there is a possibility another user is running pokemon as well.

**Comment by Zodice** [comment]
No i mean hum what is the utility of a proxy for the bot ? Because a proxy is just doing like where are not on our computer but on another ?

**Comment by 12348766754** [comment]
@Zodice  a proxy will change your IP number. This will result in you being able to run mutliply bots without getting IP Banned.

**Comment by xJihadx** [comment]
I don't use proxy settings, I use hotspot shield VPN. VPN's are easy to use and most offer free services. hotspot shield or Cyber Ghost.

Can change ip's and jump state to state.

**Comment by Zodice** [comment]
So if i often change location, to have rare Pokémon, it's better if i use a proxy ? If i do this i will not be banned ?

**Comment by 12348766754** [comment]
That's something totally different. This will allow you to use multiply bots at the same computer at the same time. Changing location will not be possible wihtout receiving a softban.
