### ISSUE TITLE
Need help still....

### ISSUE THREAD

**Issue by tomo101** [Ar1i/PokemonGo-Bot#2922]
Could someone please help me quickly with transferring?

Everytime I tick all the boxes to enable things to transfer, I always still have 10cp magikcarp and all that still in my inventory. What is going on?

I have keep pokemons when can be evolved unticked,,,, Auto trans double poke ticked, max dup pokemons 10, max iv 90 and max cp 999.

What is wrong?

CONTINUED ON: I changed my max dup to 2 and it sitll doesn't trans. Can someone show me their settings that have things transferring fine?

**Comment by tomo101** [comment]
Edit: The box is unticked. What does the % mean? What is Max IV anyway?

**Comment by tomo101** [comment]
What do you mean by the Magiccarp has over 90% or over 999cp?????

**Comment by tomo101** [comment]
The main question is that I am asking, what should I change the boxes and that too in the pokemon tab so that things really transfer...

**Comment by pilota56** [comment]
You speak German, ist hard for me to explain in English.

**Comment by tomo101** [comment]
Please man, this thing has been troubling me for a while. I have to keep transferring manually, when I could have it done automatically. Can tell me the way you have your pokemon tab set up, so I can copy it and all the transfers can be automatic?

**Comment by pilota56** [comment]
http://up.picr.de/26471154vg.jpg

Like this. The IV is to high for Transfer.

**Comment by tomo101** [comment]
Thank you.

**Comment by Zodice** [comment]
The IV is the amount of attack, defense and stamina. It's better to have a magikarpe with 100% IV but only 10CP than a magikarpe CP 400 but with only 10% IV.

**Comment by Zodice** [comment]
I tooke magikarpe for the exemple but that's the same for all pokemons.

**Comment by pilota56** [comment]
Many magicarp i catch have a high IV but a low CP.

**Comment by Zodice** [comment]
Never mind, a low CP can be changed with candys and stardust, but a low IV is permanent, and the IV is thé most important

**Comment by Captnred** [comment]
Sounds like everything was solved, glad to hear it!

Now if we could get this thread closed ;)
