### ISSUE TITLE
Some pokestops cannot be found.

### ISSUE THREAD

**Issue by 1nf0** [Ar1i/PokemonGo-Bot#2923]
Some pokestops in range cannot be found. I know there is a pokestop there but just bot can't detect it. (never saw an issue like that, sry if it's duplicate).

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by Kaizhoul** [comment]
Yes but restart the router (...) change your ip with vpn

**Comment by 1nf0** [comment]
I think I wasn't clear enough. It can find most of pokestops and farm them properly, except a few of them in range.
