### ISSUE TITLE
Detected a Soft ban many many times

### ISSUE THREAD

**Issue by w3njember** [Ar1i/PokemonGo-Bot#2924]
Need help,
I updated to latest version
Launch my bot and no more than 5 minutes, it says 
detected a soft ban trying to use our special 1337 unban method
then bot is walking again, i think still in softban condition, than it says again
detected a soft ban trying to use our special 1337 unban method
then bot walking again.. and detected softban again.. over and over

please help
![screen shot 2016-08-11 at 9 25 57 pm](https://cloud.githubusercontent.com/assets/20972192/17591994/b710fcb6-600a-11e6-9e56-49e22682d1d7.png)

**Comment by SahnCH** [comment]
Same issue.
Since using this morning's build, I have one IP ban, et one perma-soft ban.

**Comment by pilota56** [comment]
Thats a IP ban, not a Softban. You only can use 1 Bot at the same time.

**Comment by w3njember** [comment]
![screen shot 2016-08-11 at 9 38 00 pm](https://cloud.githubusercontent.com/assets/20972192/17592317/0f0a1834-600c-11e6-93f6-bede3b65ade3.png)

Now that happen

**Comment by pilota56** [comment]
Ist the IP Ban. Renew your IP and only use 1 Bot. If you use 2 Bot with same IP, you get this IP Ban.

**Comment by SahnCH** [comment]
I never used 2 bot on the same IP and still got banned :-/

**Comment by pilota56** [comment]
Renew your IP.

**Comment by pilota56** [comment]
Maybe another guy Play with your ip in your Network.

**Comment by Tracynew** [comment]
server down dude...

use this

http://www.mmoserverstatus.com/pokemon_go

search proxy with country

like cambodja, island,ireland,etc

**Comment by SahnCH** [comment]
Maybe another guy Play with your ip in your Network.
Lol....

**Comment by w3njember** [comment]
use proxies and still get IP Ban
please suggest

**Comment by testo4life** [comment]
dont use proxy just one bot if u get ip ban wait or use vpn for the time u banned !

**Comment by johnykkk** [comment]
come on servers is down!

**Comment by w3njember** [comment]
problem solved..
i put different proxies on all my bot

thanks a lot guys

**Comment by Captnred** [comment]
Glad to hear the problem is solved

Now if we can close this thread.
