### ISSUE TITLE
Mscorlib error

### ISSUE THREAD

**Issue by Wetback** [Ar1i/PokemonGo-Bot#2926]
(searched for this and didn't find anything, so I'm posting it).

When trying to connect using a proxy it always gives me this error. 
I'm using PTC account, port 80.
When using my google account without proxy runs without problem.

![mscorlib](https://cloud.githubusercontent.com/assets/20972426/17592511/9758f824-5fb0-11e6-8576-4d943dfcc97f.jpg)

How can I fix this? I would like to use more than 1 account. Thank you.

**Comment by pilota56** [comment]
I think thats a Problem with the Proxy. Is this your Proxy or an open Proxy?

**Comment by Wetback** [comment]
It's a proxy from the list that the program provides.

It happens with every single Proxy (always HTTPS)

**Comment by pilota56** [comment]
But if it works without the Proxy, i Thing ist a Problem with the proxys

**Comment by Wetback** [comment]
I dont know what you are trying to say.

I have used with the proxies but now it is always giving me that error.
