### ISSUE TITLE
i have some problem with this!!!!!

### ISSUE THREAD

**Issue by nukzcp** [Ar1i/PokemonGo-Bot#2927]
before i can open bot for along time but now i have some problem with this
plzzz help me to fix TT

![111](https://cloud.githubusercontent.com/assets/20972444/17592524/d866cba0-600c-11e6-9c29-eb7c403c261c.JPG)

**Comment by pilota56** [comment]
Do you use a Proxy? Looks like the Internet Connection does not work.

**Comment by nukzcp** [comment]
1.i'm not use proxy
2.the internet connection is working

so i don't why bot does't work TT

**Comment by MrNobodyj** [comment]
you need to restart your pc. 
İts worked for me ;)
