### ISSUE TITLE
cant fin any pokestop with proxy

### ISSUE THREAD

**Issue by nabi11** [Ar1i/PokemonGo-Bot#2929]
I can't run the bot with a proxy enabled and I don't know why? without it, work perfectly, but with the proxy he didn't find any pokestop or pokémon :/ (tested with a ptc and google account but same result)

**Comment by pilota56** [comment]
Sounds like the Proxy you use is IP banned

**Comment by johnykkk** [comment]
servers are down!

**Comment by MrNobodyj** [comment]
guys i have a question.
İv been every used proxy didnt work.  Some how everytime ipbanned by the way my two bots are down untill change the ip and modem reset.  What i m gonna do for ; working the same time my two bots. 

Sorry for bad eng.
