### ISSUE TITLE
Every pokemon got away

### ISSUE THREAD

**Issue by N4rsha** [Ar1i/PokemonGo-Bot#2931]
I'm using proxy and every pokemon that i find got away (ratata,pidgy 50cp ecc) 
http://prnt.sc/c4ft34

**Comment by Kidnub** [comment]
get normal balls check inventory setup ;(

**Comment by danig105** [comment]
I have every balls and the inventory setup is the default

**Comment by pilota56** [comment]
Min 20 normal Pokeballs. You get something at the pokestops?

**Comment by N4rsha** [comment]
i only encouter pokemon

**Comment by pilota56** [comment]
Push the Button "Force unban"

**Comment by generaljoke** [comment]
SOFTBANNED JUST TRY TO CLICK THE FORCE UNBAN YOU CAN TELL IF IT IS SOFT BANNED OR IP BANNED. 

IP BANNED = "WE CANT FIND A POKESTOP BLAH BLAH BLAH.. " 

SOFT BANNED="NO LOOT FROM POKESTOP BUT THE BOT CAN SEE THEM"

**Comment by Sparta1990** [comment]
Yeah me too.. its not soft ban some how if we play bot too long it will be like that.. still can loot from pokestop but cant catch any pokemon..

**Comment by nochelo** [comment]
disable proxys it works

**Comment by N4rsha** [comment]
even without proxy is the same

**Comment by M4rtian** [comment]
i have same problem with N4rsha, anyone help? :(

**Comment by ukrityoke** [comment]
I can spin Poke Stops but cant catch any pokemon too
