### ISSUE TITLE
Pokemons werden nicht entwickelt (GER)

### ISSUE THREAD

**Issue by PommespanzerTM** [Ar1i/PokemonGo-Bot#2934]
Hai Community, 

Ich hab das Cap auf IV über 75 eingestellt damit das ein oder andere entwickelt wird für die zusätzlichen Erfahrungspunkte.

Ich habe ein Sterndu mit über 75 IV und Bonbons habe ich auch mehr als genug dafür.
Hacken bei Entwickeln bei genügend Bonbons hab ich auch gesetzt.

Jemand einen tipp ?
Danke:)

**Comment by globsch** [comment]
Tip #1: Versuch bitte etwas auf Kommasetzung zu achten
#2: hast du die neuste Version?
#3: Screenshot?

**Comment by PommespanzerTM** [comment]
Zu #1 Ich werde es versuchen ;)
Zu #2 1.0.9.6 sollte jetzt nicht einen wesentlichen unterschied machen.
Zu #3 Im Anhang
![sdd](https://cloud.githubusercontent.com/assets/20973168/17596487/e404f1dc-5ff1-11e6-95de-96900e7a7534.PNG)
![sddd](https://cloud.githubusercontent.com/assets/20973168/17596486/e40224ac-5ff1-11e6-9573-486241777a76.PNG)

**Comment by Tirelas** [comment]
bei mir funktioniert es, ich habe bei dem Tab Pokenmon, die rechte spalte (Pokemon to evolve) alle aktiviert

**Comment by globsch** [comment]
jop die müssen sein, sonst macht er nix.

**Comment by PommespanzerTM** [comment]
Danke euch :)
Läuft nun :)
