### ISSUE TITLE
 It showed as the picture!!!!

### ISSUE THREAD

**Issue by Zippobear** [Ar1i/PokemonGo-Bot#2935]
![bug](https://cloud.githubusercontent.com/assets/20973482/17594511/c6a84a0e-6013-11e6-9596-831c5f49b7d8.jpg)
 It showed softban with red letter then I closed the program.
When I start the program later it showed as the picture.What should I do friend.
Thank guys

**Comment by lucas2107** [comment]
Just click continue :)

**Comment by generaljoke** [comment]
your internet connection is slow. if you try to click continue you will notice that there is a difference between normal gui and the errored one :) just click quit and run it again and again and again.
