### ISSUE TITLE
WE CANT FIND POKESTOP TEMPORARY REMEDY

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#2936]
try to download this guys the old version https://github.com/Ar1i/PokemonGo-Bot/blob/315c5825af4a7698341ed607fbbeba31537b4095/Builds%20Only/Latest%20Build%20-%2010.08%2017.51.rar  less banned just use psiphon to avoid ip banned and just use 1 account per ip or per bot. stay in one country for example Unitedstates = Newyork. this will work if ou have a brain. 100% working properly fine for the past 3 hours. TEMPORARY ! HOPE THAT DEV WILL NOTICE THIS BUG OR SOMETHING WE DONT KNOW 
![capture](https://cloud.githubusercontent.com/assets/20971723/17594640/948cc870-601c-11e6-8087-8a141cf049c8.PNG)

**Comment by Ar1i** [comment]
What bug should be in the newest version?

**Comment by Teddy73x** [comment]
it can't seem to find any pokestops

**Comment by Ar1i** [comment]
thats cause your ip banned, has nothing to do with newest version

**Comment by generaljoke** [comment]
i think that there is something with this https://github.com/Ar1i/PokemonGo-Bot/commit/96a982be584b8f9011e2bd5844538f4d5998ba48 before that it is working properly less bans. I tried both of them, switching them and tried to compare the 1.0.9.1v  to the newest version and as ive said before 1.0.9.1 which titled  "Added incubator (testing mode)#2639 & fixed #2622 " working fine for me. maybe the egg hatching is the main problem here with the server but im not sure.
