### ISSUE TITLE
Bot went out of entered range

### ISSUE THREAD

**Issue by Ragza** [Ar1i/PokemonGo-Bot#2937]
My bot is walking outside the range I told him.
My entered range is 1050m.
Is this normal or a bug?

![image](https://cloud.githubusercontent.com/assets/20943122/17594803/d7a994f8-5fea-11e6-952f-2554d7b14ce1.png)

**Comment by generaljoke** [comment]
WHAT DO YOU THINK ? OBVIOUSLY A BUG -.-
