### ISSUE TITLE
It takes 2 mins to start up or sometime just frozen....

### ISSUE THREAD

**Issue by navygino** [Ar1i/PokemonGo-Bot#2938]
Issue happen with Latest Build - 11.08 16.19, speed set to 80km/hr

See attached
![2016-08-11_23-35-30](https://cloud.githubusercontent.com/assets/20778474/17594738/f130baaa-601c-11e6-9678-7adb11fb5d2a.jpg)

**Comment by Ar1i** [comment]
probably your proxy is slow?

**Comment by thomasmaradonaa** [comment]
Arli this new bot cant recycled item like pokeball...my inventory always full

**Comment by Ar1i** [comment]
@thomasmaradonaa it does, but not directly if you get full message it clears

**Comment by navygino** [comment]
I did not use any proxy

**Comment by Ar1i** [comment]
there was only 1 freeze, probably cause of a server lag
