### ISSUE TITLE
Pokemon go bot issue

### ISSUE THREAD

**Issue by lordsoncrey25** [Ar1i/PokemonGo-Bot#2939]
Hi, i have this error with the bot, can anyone help me ?

![image](https://cloud.githubusercontent.com/assets/20970849/17595230/298b1746-5fba-11e6-8fff-04fffc8f174d.png)

**Comment by lucas2107** [comment]
Can't connect to google or pokemon login servers.

Bad password / e-mail?

**Comment by lordsoncrey25** [comment]
No, the email and password was entered correctly

**Comment by Ar1i** [comment]
Using proxy? If yes, the proxy is the problem.

**Comment by gummyruler** [comment]
Proxy problem choose another one.

**Comment by lordsoncrey25** [comment]
how change the proxy? can you give one please?

**Comment by FinFis** [comment]
@lordsoncrey25 google https proxy and there are a lot free 1 out there. most i tries have been ban too ask pple also use that for botting and got it ban lol
