### ISSUE TITLE
-

### ISSUE THREAD

**Issue by OzanBarsal** [Ar1i/PokemonGo-Bot#294]
hello it seems every time the bot catches a pokemon, it catches with an excellent throw and curveball as we can see in the exp gain (210exp).

This makes it obvious that we use a bot so can you include an option to make it random or at least select how to catch it?

you know there is no reason to use bot i we get banned

**Comment by Tochez** [comment]
At the moment there is no need for that much security. Niantic hasn't even started talking about botting yet. This game is still very new and they do not have time to worry about this. They only care about releasing it to the world.  It might be a problem in the late future but right now its not. People are even selling machines that does perfect throws and curveballs. Just search them up at ebay and you can find it.

**Comment by OzanBarsal** [comment]
your reason seems legit, i was just concerned about it because my friends told me that niantic started banning bots, of course this was just a talk with no source.
