### ISSUE TITLE
Which proxy ip & port to be use?

### ISSUE THREAD

**Issue by sigmaxbpo125** [Ar1i/PokemonGo-Bot#2941]
i tried a lot of proxy ips and ports.. keep cannot found pokestop within 5000meter..

please give some guide.. which proxy ip and port to pick ? 

http://gatherproxy.com/proxylist/country/?c=Malaysia

Thank for help

**Comment by Ar1i** [comment]
free proxys suck like 99% you need a https private proxy

**Comment by sigmaxbpo125** [comment]
any website recommended? thanks mate

**Comment by gummyruler** [comment]
You have to find a vacant one. Some of the IP don't work, some have such high MS. Most are taken by other PGo players.
