### ISSUE TITLE
Pokestop problem!

### ISSUE THREAD

**Issue by silentcrazy** [Ar1i/PokemonGo-Bot#2942]
No pokestops found!
![cattura](https://cloud.githubusercontent.com/assets/20886021/17595649/1eb03b1a-5fee-11e6-93ff-a5fb4a35df6e.PNG)

**Comment by gummyruler** [comment]
How many bots are you running? If it's more than 1 you've been IP soft banned.

**Comment by Heuk** [comment]
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone
