### ISSUE TITLE
hello i have latest version but ....We can't find any pokestops in a range of 5000m ....

### ISSUE THREAD

**Issue by leonidisli** [Ar1i/PokemonGo-Bot#2943]
hello i have latest version but ....We can't find any pokestops in a range of 5000m ....
![1eb03b1a-5fee-11e6-93ff-a5fb4a35df6e](https://cloud.githubusercontent.com/assets/20974005/17595833/f63d1da0-5fee-11e6-826f-e15a41640255.png)

**Comment by ahya93** [comment]
u have ip banned. wait for 15 minutes

**Comment by Impossibeulman** [comment]
I have the same problem. // J'ai le même problème.
![capture ban](https://cloud.githubusercontent.com/assets/20974145/17595987/b274aa10-5fef-11e6-9511-8124f8ef86c3.PNG)

**Comment by ahya93** [comment]
@Impossibeulman dont use more than 1 bot... READ THE WARNING ON BOTTOM OF THE BOT..

**Comment by NaveTK** [comment]
When you start up the bot it says "If you run more than one instance with the same IP you'll get softbanned" in big fat letters... why does nobody read? .__________.

**Comment by leonidisli** [comment]
Thx so much I changed the ip .I don't use more that 1 it s last time thx

**Comment by Impossibeulman** [comment]
J'utilise google traduction, j'avais pas compris l'allusion de deux bot par IP. Mon modem est en IP FIX. Je ne peut donc pas en changer. Tempi pour moi.

I use google translation, I had not understood the allusion two bot IP. My modem is IP FIX. I therefore can not change it. Tempi for me.

**Comment by gummyruler** [comment]
2 bots = IP ban intiendes?

**Comment by DHBios** [comment]
@Impossibeulman I think you can restart your pc/laptop, that way it will reshuffle your IP Address, or just disconnect you wifi, and reconnect it again. I don't think it's possible to have only 1 IP for a modem, therefore it's worth trying this method :)

And don't open 2 bots at the same time, currently niantic just set a rule that says 1 IP equal to 1 Account, so whenever you open 2 bots, it will automatically get banned for 15 mins (can be called as Soft-Ban)/Get banned for your current IP (Currently the only solving problem was changing your IP Address)

**Comment by arjunvegda** [comment]
@ahya93 So would they unban you if you wait for 15 mins ? Because I am waiting since so long tried changing couple of IPs but same error.
