### ISSUE TITLE
Random Error #2

### ISSUE THREAD

**Issue by lucas2107** [Ar1i/PokemonGo-Bot#2944]
This is a random error like the first i've posted:

![screenshot_1](https://cloud.githubusercontent.com/assets/11612016/17595685/47178ac2-5fee-11e6-9bcb-526ced175aee.png)

**Comment by generaljoke** [comment]
i dont think that is an error, it is trying to start again which is indicated there after the first loop.

**Comment by lucas2107** [comment]
The first error like that was a real error and fixed by @Ar1i

**Comment by ahya93** [comment]
yeah same to me if long time used and it will looped until i restart the bot..
