### ISSUE TITLE
[Info] VPN / PROXY Not Work / Change Language to EN error

### ISSUE THREAD

**Issue by ahya93** [Ar1i/PokemonGo-Bot#2946]
I have run 2 of bot in 2 different PC (1 with vpn) but it's still get ip banned...
what method that niantic used to know our real ip address.. my ip address static so i cant change that with restart of modem. must waiting on 15 minutes to use bot again..

And a minor bug, if change the language i cant change back to the en language..

![GitHub Logo](http://image.prntscr.com/image/ad2669d882484c15b9fc28f0f16c366e.png)

**Comment by gummyruler** [comment]
Bud hide your username.

**Comment by gottahub** [comment]
yupz...hide ur ID lol

**Comment by ahya93** [comment]
@gummyruler @gottahub forget that hahaha.. editing now hahaha..
proxy or vpn not work -_-

**Comment by gummyruler** [comment]
@ahya93 It does you just have to find a working IP. Since most of those IP are taken.

**Comment by ahya93** [comment]
@gummyruler i use my private vpn bro, and with different pc too i dont know what method that niantic use to know that.. 2 account has softbanned...

**Comment by gummyruler** [comment]
@ahya93 maybe they disabled the use of dynamic ip. It's the most sensible explanation. Have you tried turning on the DMZ for the other PC? It could fix your problem.

**Comment by PokemonAddict** [comment]
Same failure in my case. With Proxie I can't connect in the new update, before it worked. Tried with 6 Proxies....

**Comment by gummyruler** [comment]
@pokemonaddict Try some mo5re bud. It took me 1 day to find a working one.

**Comment by k3npachi** [comment]
patch Web Rtc , if your VPN are not protected niantic see your real IP

**Comment by urangotango** [comment]
i got some private ip till now it was like 5 minutes running and than ip banned both on the same moment with private porxys(maybe it dosnt bypass my real IP) . now i did set other 2 of my 10 proxy seems running lets see what happen in the next 10 minutes i hope that it works good for me now... 

but at the end @Ar1i and @Logxn realy good job keep going and have patience with us user.

**Comment by bertojk** [comment]
there is only one thing you can do. i'm still trying this method but what you can do is using different connection (I use virtual machine and can works with different IP) since I have 2 different wifi on my place. I'm still trying to run @Ar1i's code with linux and still progressing.

**Comment by urangotango** [comment]
hi here again for now anything is running at the best way 0 banns in the last 30 minutes and i did open other 2 bots so for now im on 4 bots running with HTTPS private dedicatet proxy ..i hope it keeps going on this way.

**Comment by urangotango** [comment]
ok i can confirm that if you have good and clear proxy HTTPS IPs it works 100% i run alright more than 1 h with 4 bots witouth bans or other craps.. GJ

**Comment by ahya93** [comment]
this the vpn ip
![GitHub Logo](http://i.prntscr.com/7b54aea6e5304484b8656307ac05a1bb.png)

Not Detected my real ip, i'm on indonesia...

**Comment by k3npachi** [comment]
@urangotango can you tell me which proxy you use ?
