### ISSUE TITLE
Better performance for developing eggs

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#2948]
Tried with different speeds, but doesn't work. Anybody know, how to fix that prob? Only some meters were walked (I guess shirt before the pokestop...)

**Comment by edale2** [comment]
I set the bot for 20 km/h and it hatches eggs fine.

**Comment by PokemonAddict** [comment]
Now it worked - seems like a server prob of Niantic

**Comment by DHBios** [comment]
Just to remind ou to close the Issue, whenever the issue is solved :)

**Comment by justchil** [comment]
I'm using 75 km/h and it's working just fine.  It takes a bit because it's only counting the slowdown periods I would imagine.  /notanissue

**Comment by Captnred** [comment]
Glad to see everything working

Please close this thread as the problem has been solved.
