### ISSUE TITLE
Solution for stopping bot

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#2949]
Is there a solution to stop the bot, without closing the bot/prog?

**Comment by navygino** [comment]
Also howcom the bot closed when ENTER is pressed??

**Comment by gummyruler** [comment]
You don't enter an empty command while something is trying to run. Just don't.

**Comment by testo4life** [comment]
Click with your mouse on the cmd screen of the bot. Bot stops press enter bots starts

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
