### ISSUE TITLE
Cant Find Pokestops

### ISSUE THREAD

**Issue by AcFORR3ALoo** [Ar1i/PokemonGo-Bot#2952]
I am using the latest version

it kept detecting soft ban on both my profiles then just stopped and when i reloaded them it could not find pokestops so i change my ip and created a fresh account and it still could not find poke stops is the bot offline?

**Comment by PokemonAddict** [comment]
since <5 Min. also with me. Something changed.

**Comment by gummyruler** [comment]
<B><Color: ff0000> READ: </B></Color>

![dumasses](https://cloud.githubusercontent.com/assets/20757587/17597365/aefca974-5fb2-11e6-899d-f569ba9a582b.png)

**Comment by AcFORR3ALoo** [comment]
i did i made a fresh account with a new ip and it still was the same issue

**Comment by demonized** [comment]
It seems proxy implementation does not work properly. When I open second bot with different proxy, it gets banned.

**Comment by AcFORR3ALoo** [comment]
yes but im using a program outside of the bot to mask my ip

**Comment by lailaps** [comment]
demonized
Lol, guess how many people are now using the same proxy...
Effect will be the same, as if you run 2 bots on same IP...

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md
