### ISSUE TITLE
Cannot recycle the items

### ISSUE THREAD

**Issue by pipicat3066** [Ar1i/PokemonGo-Bot#2953]
it cannot recycle the items but only once the bot starts

the bag is now fully with pokeballs and potions....

please help :(

**Comment by gummyruler** [comment]
Take a screenshot of your Item setting. and drag it on the comment.

**Comment by Bangden** [comment]
This is not an issue, please arrange your return items.
If your inventory is 350, set items to 345

**Comment by pipicat3066** [comment]
![image](https://cloud.githubusercontent.com/assets/20974856/17597599/1a898a9c-6029-11e6-90b5-54c11fae7ee0.png)

Here is my setting. I got 800 inventory and it still cannot drop the items with this setting

**Comment by Bangden** [comment]
please try,
Exit bot and re-setup items.

![screenshot_4](https://cloud.githubusercontent.com/assets/20925585/17597925/3c440c86-6022-11e6-9cea-080a780b8127.jpg)

**Comment by pipicat3066** [comment]
tried and it still do drop items once the bot starts

thanks again

**Comment by Ar1i** [comment]
It recycle only if your inventory is full no bug.
