### ISSUE TITLE
Error reloading Pokemon list: badauthentication

### ISSUE THREAD

**Issue by 0891679592** [Ar1i/PokemonGo-Bot#2955]
i cant use it :(

https://scontent.fbkk1-2.fna.fbcdn.net/v/t35.0-12/13950516_1224136984316896_1469519000_o.png?oh=f371443820eeb7eb2236bdfc74bfe9da&oe=57AE7B4C

**Comment by duykhoi189** [comment]
you used a wrong account, check your id or password

**Comment by 0891679592** [comment]
already check. it's didnt wrong
