### ISSUE TITLE
Appears to be malicious

### ISSUE THREAD

**Issue by DR6116** [Ar1i/PokemonGo-Bot#2956]
When i try to download the newest update, trend micro says that 3CC8.tmp has been removed. this has not happened in any other update.

![image](https://cloud.githubusercontent.com/assets/20747177/17597797/79222596-5fc5-11e6-8d3a-095dc5872ce5.png)

**Comment by simonmy** [comment]
don´t use it if you do no trust the coder lol

**Comment by lailaps** [comment]
trend micro lol...

**Comment by DR6116** [comment]
@lailaps trend micro has never done me wrong before.

**Comment by lailaps** [comment]
How old are you...
Download the source code, take a look inside and compile it, so you can see that nothing is malicious.

**Comment by Ar1i** [comment]
build yourself the exe then
