### ISSUE TITLE
Game version.0.33.0 is available 

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2959]
Was it reversed engineering to check any major update that could compromise bot usage?

**Comment by xuban** [comment]
What has this to do with the section "issues"?

**Comment by zzzz9999** [comment]
So, if not an issue and definitely not a suggestion, tell me with your expertise, where it should be, mr knows everything.

**Comment by zzzz9999** [comment]
That is not of your competency to decide. If not an issue what is it? A suggestion, enhancement?

**Comment by xuban** [comment]
I did not say that is my work and am deciding anything. Just be read and this section has a name.
If you want you can continue to open questions in this section, it is your decision. You can also operate on you in the office fire and extinguish a fire with an ambulance, to give you more ideas.

**Comment by testo4life** [comment]
Seriously dude that is NOT in issue close that Thread. Too many Posting unrelated stuff without thinking.

**Comment by zzzz9999** [comment]
?? Are you on drugs? Alcohol?

**Comment by zzzz9999** [comment]
I'm sorry, I'm the first guy to suggest closing issues, but definitely this can be a  issue. 
Focus on the main problem that is a new version of game!

**Comment by xuban** [comment]
I dont take drugs and alcohol.
Can you understand that it works gitbuh and this section? It is not.
Version 0.33 has left three days ago. The only significant changes that occurred in reference to the bot is shut mandatory notice when you drive fast.
I do not know you are looking with your question because it does not reflect any real problems.

**Comment by zzzz9999** [comment]
Ok put here suggestions forum link. 
I will close issue and post this question there.

**Comment by xuban** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pulls this is suggestion section.
But realy this isn't a suggestion.

**Comment by xuban** [comment]
Bad link, the real is this: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by zzzz9999** [comment]
Ok i didn't know new version had 3 days. Let's forget this.
