### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by UnknownGuy123** [Ar1i/PokemonGo-Bot#296]
How do I make it to be like that?

**Comment by 3210x** [comment]
Git PULL ^^

**Comment by UnknownGuy123** [comment]
What? Didnt get what you said

**Comment by 3210x** [comment]
download a git hub desktop app. and u can pull update when u want.

**Comment by UnknownGuy123** [comment]
Download link fam?

**Comment by am3yar0ra** [comment]
This is a good idea. We don't have to download manually each time if this feature will be added.

**Comment by FelipeMallmann** [comment]
@3210x  but why sould i use git pull in the hole project? how can I convert that into dll.s like ar1i does in the .rar at Builds Only ?

**Comment by Ar1i** [comment]
Not coming cause of some Forums which dont allow that
