### ISSUE TITLE
Dont know how to open 

### ISSUE THREAD

**Issue by ThiesBoll** [Ar1i/PokemonGo-Bot#2960]
Hello,                                         (i am German but speak english too)
I came from holidays and i saw on Ar1i´s twitter that the bot is working i downloaded it again but i dont know how to open it now ... can you pls help me? Ty.
![unbenannt](https://cloud.githubusercontent.com/assets/20975594/17598721/1ba80e30-5ffc-11e6-89b2-45508190253a.PNG)

**Comment by oPwnYo** [comment]
Entpacken... ^^

**Comment by ThiesBoll** [comment]
hab ich schon ^^

**Comment by ThiesBoll** [comment]
danke ich voll idiot
