### ISSUE TITLE
But I am getting error while building.

### ISSUE THREAD

**Issue by abdulkadiraktas** [Ar1i/PokemonGo-Bot#2961]
I made a few changes to the program. But I am getting error while building.

Previously there was no such problem.

Screenshot: The http://prntscr.com/c4i3s

Google Translate GG

**Comment by CruSherFL** [comment]
I do not want to point any fingers.. but probably since the 2 commits of @3v01ut10n ?
![image](https://cloud.githubusercontent.com/assets/12624399/17599190/299da1b0-5ffe-11e6-8a87-cc2a09489a47.png)
Commit id: 3883e3ca300efb891ff751905ebb84c9052ae1b8

**Comment by CruSherFL** [comment]
found the error. commit coming.
