### ISSUE TITLE
GER : Bot fängt seit heute keine Pokemon mehr

### ISSUE THREAD

**Issue by Hawke17** [Ar1i/PokemonGo-Bot#2962]
Hi,
seit heute fängt der Bot bei mir nurnoch sehr selten Pokemon..nach ungefähr 30x " Get away while using Superball" fängt er mit Glück mal eins..Liegt das am Bot oder am Spiel?

**Comment by CruSherFL** [comment]
Je höher das level, desto schwieriger wird das fangen. :)

**Comment by dragobite** [comment]
@CruSherFL Trololol weiter bro, also ich hab dasselbe Problem

**Comment by bloodmoonx2** [comment]
ich hab das problem das ich keine 2 bots laufen lassen kann liegt das an der IP sprich muss ich da nen Proxy verwenden oder woran kann es liegen ?

**Comment by Daisytwo** [comment]
@Hawke17 hast du pokeball und superball auf 0 gesetzt?

**Comment by dragobite** [comment]
liegt an der IP musst ein proxy verwenden. @Hawke17 Hab das problem gelöst einfach die IP geändert, scheint eine Art Bann zu sein

**Comment by Hawke17** [comment]
Ich hab erst die Pokebälle auf 0 gesetzt, und dann die Superbälle..immer das selbe.
Ich versuchs mal mit einem anderen Proxy, Danke

**Comment by Daisytwo** [comment]
@Hawke17 Du darfst die nicht auf 0 setzen er versucht die den troßdem zu benutzen

**Comment by Hawke17** [comment]
Achso ok :D  ich habe jetzt 5 andere Proxy's versucht..bei jedem kommt direkt "Can't find any Pokestops"

**Comment by bloodmoonx2** [comment]
bei mir auch :(

**Comment by pilota56** [comment]
Das geht nur mit privaten Proxys, also solchen, wo kein anderer drüber spielt. Ich hab mei nem Freund nen Raspberry mit nem einfachen https Proxy hingestellt und das läuft super da drüber, da er selbst nicht drüber spielt. Es darf immer nur ein Account pro IP eingeloggt sein.

**Comment by bloodmoonx2** [comment]
ja ich habs bemerkt :D

**Comment by bloodmoonx2** [comment]
wenn ich kein geld für ne private VPN habe wie kriege ich das sonst hin 2 bots laufen zu lassen oder mehrere .. kann mir das bitte einer erklären bin eher neuling auf dem Gebiet ? :x

**Comment by albii687** [comment]
weiss jemand wieso das der bot alle meine pokemons transferiert ? kann mir jemand helfen ? 

https://gyazo.com/38d2a38b8c6a43484985f1905900e315

**Comment by brainoutput** [comment]
@albii687 Schau dir mal die Einstellungen an, evtl hast du nur 1 behalten und den Hacken bei allen versenden drinn.
