### ISSUE TITLE
Proxy 

### ISSUE THREAD

**Issue by waropatrik1234** [Ar1i/PokemonGo-Bot#2964]
Hello, do i need to use proxy for towns? like new york located proxy for new york, san francisco located proxy for san francisco?

**Comment by DHBios** [comment]
I don't think you need to put the exact same proxy server for that specific area
Never tried to use proxy before, but, it'll be better to put a different proxy server for each bot you're running, might be work

**Comment by waropatrik1234** [comment]
What if Niantic will start control if you have same ip location and gps? :D cuz, if im catching in New york with german proxy its funny :D

**Comment by pilota56** [comment]
I also do so. I catch Pokemon in LA and Tokyo with german IP. But you can also use a VPN on your Phone with German Gateway, so i think ist no Problem.

**Comment by waropatrik1234** [comment]
ok, thank you guys for reply :)

**Comment by guibr321** [comment]
I¡m catching in New York with Spanish IP and I was worried about it. I don't use any proxy, Thank you!
