### ISSUE TITLE
catch strong pokemon_?

### ISSUE THREAD

**Issue by merth7** [Ar1i/PokemonGo-Bot#2968]
Hello everyone,

Very high power ones, how and where can we catch you? for example, CP 2k pokemon.

Does anyone have information?

thnks

**Comment by noaheaven** [comment]
leveling up to 30+ and u can get high cp and good IV. new york is good. dragonite snorlax lapras and others strong pokemon

**Comment by merth7** [comment]
@noaheaven Thank you bro my level more than 25. We expect you to be level 30. :dancers:

**Comment by noaheaven** [comment]
your welcome. good luck in new york. and thanks to arl1 for this gem

**Comment by Ragza** [comment]
Does anyone have a good position for lapras in NY?

**Comment by gummyruler** [comment]
This is not a question board it's issues only please refrain from posting questions on this board. 

All questions and suggestions go here:
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

**Comment by noaheaven** [comment]
central park. because it has lake near there. and also have charizard. in there almost you can find rate S type pokemon for attacking and defending gym. sorry sir the web you suggest in german ?
