### ISSUE TITLE
Some small things.

### ISSUE THREAD

**Issue by k3nny222** [Ar1i/PokemonGo-Bot#297]
- Auto Update
- German Names in GUI
- Settings Button with Restart Option
- Button to Github
- Use of Eggs

BIGS:
- Map to watch the travel or maybe click/set points to set a own/new travel route
- Arena Fighting and Arena Lvling

Also best regard and thank you for your big perfect project!!!

VERY GREAT!!!!!!!
Tested some Bots and it´s the best working. Not that much function like the other but you are extremly working on it :D

**Comment by Tochez** [comment]
> Map to watch the travel or maybe click/set points to set a own/new travel route
You can use telegram to see where your walking #95
