### ISSUE TITLE
HTTP or HTTPS proxy

### ISSUE THREAD

**Issue by waropatrik1234** [Ar1i/PokemonGo-Bot#2972]
What should i use? HTTP or HTTPS proxy?

**Comment by Damantium** [comment]
HTTPS

**Comment by Damantium** [comment]
Close this it isn't an issue

**Comment by waropatrik1234** [comment]
What if i use http?

**Comment by xuban** [comment]
Please, dont spam issue section. If u want to know how proxy works, search in google.
