### ISSUE TITLE
It doesn't transfer pidgeys, rattatas and ekans

### ISSUE THREAD

**Issue by Yaruru** [Ar1i/PokemonGo-Bot#2973]
Well it seems it doesn't transfer pidgeys, rattatas and ekans, it makes my inventary full of these and 99% are low ones. I didn't check them in "not transfer" and the bot transfers other pokemons normally

**Comment by pilota56** [comment]
First Screen, disbale "do not send pokemon to envolve" or so. Dont know in English. :-)

**Comment by kazekiki** [comment]
did u stick " keep pokemons that can be evolved" ?

**Comment by Yaruru** [comment]
Ohhhh my bad, that was it, thank you very much!

**Comment by testo4life** [comment]
Check out their iv if the duplicate Pokemon have high IV like over 90% it will keep  u can change the IV rate though

**Comment by Captnred** [comment]
Im glad everything worked out!

Seeing how everything is fine now could we close this thread?

**Comment by Yaruru** [comment]
Sure!
