### ISSUE TITLE
Wie stell ich richtig ein das mein Bot die Pokemons automatisch wegschickt?

### ISSUE THREAD

**Issue by germanPoke** [Ar1i/PokemonGo-Bot#2975]
Hallo Leute,

ich habe ne kurze Frage. Wie stell ich ein das mein Bot die low Pokemons direkt wieder wegschickt?
Die ganzen Rattfratzs und Taubsis Raupis Hornlius....Die müssen alle weg^^
Ich möchte das immer nur 1 da ist. Das heißt sollte ein 2tes gefunden werden soll das niedrigere weggeschickt werden. Wie stell ich das ein?

Danke für eure Hilfe :)

**Comment by pilota56** [comment]
Einzeln geht das nicht. Du kannst es nur für alle einstellen. Ich hab von allen 3 drin. Das haut so ungefähr hin. Außerdem kannst du einstellen ob er die mit niedrigem CP oder mit niedrigen IV weg schickt. Ich hab da IV eingestellt. Außerdem muss der Haken raus, das er entwickelbare nicht weg schickt. Ich schickdann zweimal am Tag noch per Hand weg, dass man Rucksack nicht voll läuft.

**Comment by germanPoke** [comment]
kannst du nen bild reinstellen von deinem bot? Also die einstellungen?

**Comment by pilota56** [comment]
Ok, warte kurz.

**Comment by HELLspawnTIM** [comment]
Wie wäres mit dieser Einstellung hier von mir ??
Verschickt alle Pokemon, außer wenn es das letzte ist, außerdem höchste IV gehen vor höchstem WP, verschickt nix unter IV 90% und nix über 1299wp
Kannst Du gerne auf deine Bedürfnisse anpassen.
Funktioniert wunderbar
![transfer](https://cloud.githubusercontent.com/assets/20964979/17601883/8926b2f0-600a-11e6-9d4b-e1c334e8019f.jpg)

**Comment by pilota56** [comment]
![bild](https://cloud.githubusercontent.com/assets/20906845/17601954/caff4d7c-600a-11e6-8c9b-70d9192aed44.jpg)

**Comment by pilota56** [comment]
Und der Button "Keep Pokemons which can be envolved" muss raus, sonst behält er die ganzen kleinen Taubsis Ratzfatz etc.

**Comment by HELLspawnTIM** [comment]
Oh ja, der Haken is ganz wichtig.
Im Standard is der Haken drin, was ich auch gut finde.
Denn ansonsten würde der BOT beim ersten anwerfen als erste Handlung bei den meisten erstmal viele viele Pokemon wegschicken, das würde viele erschrecken.

**Comment by germanPoke** [comment]
Danke Leute :) Top antworten.
