### ISSUE TITLE
"Can't find any pokestops in a range of 5000m!"

### ISSUE THREAD

**Issue by Waiiim** [Ar1i/PokemonGo-Bot#2976]
I don't understand :c 
And I'm running only 1 bot + proxy, so it can't be an IP softban

**Comment by HELLspawnTIM** [comment]
This is usually an IP ban
Try using another proxy. If it is a public proxy, somebody else could use it now  :-)

**Comment by Heuk** [comment]
same problem, new ip dpesnt fix it proxy doesnt fix it new location doesnt fix it running one bot only it works fine in cellphone

**Comment by Kaizhoul** [comment]
Stop always ask the same questions please

**Comment by HELLspawnTIM** [comment]
This has been asked 1000 times in the last 2-3 days
YOU HAVE AN IP BAN !!!

Solutions:
- Wait until your IP us unbanned
- Use different proxy
- Reset your router to get new public IP (if your ISP provides new public IP by reset)

**Comment by Heuk** [comment]
its not an ip ban... there is no static ip in my country every reset gets a new public ip, i used diferent proxys nono  works, i dont know what it is but is not an ip ban....
