### ISSUE TITLE
Proxy Bug 

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#2979]
Proxy is not working after new update the proxy is not working detecting softban before the update it  was working now i cant run more than 1 bot @Ar1i @Logxn Please try to fix. Getting soft ban in this build cant open more than 1 bot in this build Latest Build - 11.08 16.19.
  It was working fine previous buid

**Comment by Ar1i** [comment]
Proxy is working. Your proxy is probably a public one. Which is already in use. Or blacklisted.
