### ISSUE TITLE
however its use

### ISSUE THREAD

**Issue by k756u** [Ar1i/PokemonGo-Bot#2982]
Hello everyone :)
I vien to the update and I do not understand the usefulness : s
a window pops up with nothing at the launch ... and 2nd  % with the bay :)
thank you in advance :)
![what](https://cloud.githubusercontent.com/assets/20924571/17603939/aab51d18-6013-11e6-99a5-bd6a33e323ed.png)

**Comment by gummyruler** [comment]
if chance of capture = <25% it uses berries.

**Comment by k756u** [comment]
ah okay I had not seen anything like her : p thank you very much ^^ '
topic closed thank you :)
