### ISSUE TITLE
Bot going outside search area

### ISSUE THREAD

**Issue by edale2** [Ar1i/PokemonGo-Bot#2983]
using build: 11.08 16.19 (and I really can't figure out the numbering conventions for this...)

When having a set search radius (in this case 1 km), the bot will sometimes go widely outside the set search area. This can be a problem if you want the bot to stay close to an area when hunting for rare pokemon. 

![tracking2](https://cloud.githubusercontent.com/assets/20962345/17603856/05dc2840-5fe1-11e6-9a6b-188ff6457fca.png)

**Comment by elenex23** [comment]
Is there a way to make that black circle appear or is it something you did?

**Comment by downspath** [comment]
i searched this on the map you made a 500m radius ;)

**Comment by PokemonAddict** [comment]
i guess the radius is not correct :P

**Comment by Ouargue** [comment]
The Radius is made by the bot not by him. So this is a minor bug.
