### ISSUE TITLE
the auto incubate work ?

### ISSUE THREAD

**Issue by Khorajuste** [Ar1i/PokemonGo-Bot#2987]
the auto incubate Work ?
(not for me :/ )
someone have the same problem ? :/

**Comment by Abbasoo** [comment]
No, It's working.

**Comment by gummyruler** [comment]
Why do you think it's not working. We can't just post things without evidence can't we?

**Comment by Khorajuste** [comment]
i have the latest version , no big , only the auto incubate dont work i dont know why , no message of error , just dont work i selec the auto incubat with basic incubator but nothing , everytime i play with my phone all the eggs are here , no incubator activated :/ 
thats why i dont give screen shot because there is nothng to screen i just want to know if someone have the same problem and if he found a way to fix it :)

**Comment by Waiiim** [comment]
Guys once the egg hatched, is there a way to see the pokemon you got? or must you seek the intruder in your pokemon list?

**Comment by teejvyx** [comment]
just got to see which one you didnt have before.. guessing game really unless you have the bot not catching pokemons and just farming pokestops @Waiiim

**Comment by PokemonAddict** [comment]
doesn't really work. Visited 50 stops, 500m walked - in this direction... Tried different speeds
