### ISSUE TITLE
Update has an issue...

### ISSUE THREAD

**Issue by UnknownGuy123** [Ar1i/PokemonGo-Bot#299]
https://gyazo.com/7f20fbe90145d58509e33a4bd3505ac5

**Comment by ObsessedHacker** [comment]
Same Here don't worry I think he will fix it ASAP

**Comment by UnknownGuy123** [comment]
Why did I update? :( And deleted old version...

**Comment by VisualBoyAdv** [comment]
Should I not update it?

**Comment by am3yar0ra** [comment]
I don't face any such problems. Try deleting the files and reinstall from scratch. Make sure you guys save the config folder for reference.

**Comment by VisualBoyAdv** [comment]
I'm pretty sure it's because of the servers.. Just checked it and wasn't so good.

http://ispokemongodownornot.com/

**Comment by ObsessedHacker** [comment]
@UnknownGuy123 Just wait for another update that will fix it
@VisualBoyAdv Don't update from Build - 30.07 00.34.rar
@am3yar0ra Because you didn't downloaded Build - 30.07 00.34.rar
@VisualBoyAdv It's not server issues, I think it's because of the update.

**Comment by ObsessedHacker** [comment]
Uh now the issue solved. I guess it was SERVER ISSUES.

**Comment by daneil1999123** [comment]
yeah it was a server problem

**Comment by Kjiz** [comment]
Still the same issue by me

**Comment by Playhard89** [comment]
Try to delete the last coords founded in config file.Then restart the bot.  I prefer santa monica

**Comment by Kjiz** [comment]
okay thank you

2016-07-30 1:03 GMT+02:00 Playhard89 <notifications@github.com>:

**Comment by Kjiz** [comment]
i prefer santa monica too :D



2016-07-30 1:16 GMT+02:00 LPmit Kjiz <gaming.by.kjiz@gmail.com>:
