### ISSUE TITLE
Transfer First Low IV

### ISSUE THREAD

**Issue by Fackma** [Ar1i/PokemonGo-Bot#2992]
kurze Erklärung bitte zu dem Feld "Transfer First Low IV"?
Meine Settings:
http://www.bilder-upload.eu/show.php?file=2d8314-1470947697.png
Danke

**Comment by fesetoni** [comment]
In der Theorie sollte der Bot dann die Pokemon wegschicken die die geringsten IV Werte haben (das sind individuelle Werte die die Viecher als Bonus haben), da diese im gelevelten Zustand schwächer sind als Pokemon mit höheren IV Werten. Leider funktioniert das aber zumindest bei mir nicht.

**Comment by Fackma** [comment]
genau das dachte ich mir auch, kann es aber auch nicht Bestätigen.
Aber das würde bedeuten, dass er ein Pokemon behält (je art), und zwar das mit den höchsten IV. Den rest schickt er weg. was macht er bei gleichen werten? geht er dann nach CP oder nach Attacks?

**Comment by FerMedina86** [comment]
![image](https://cloud.githubusercontent.com/assets/20867022/17605534/7ed0042a-5fe0-11e6-93c3-d36b69eb8f92.png)


Es ist sehr gut funktioniert , hängt es , vielleicht können Sie gefangen "X" pokemon mit 10 cp und 100% iv , warten nur für die beste iv und cp , ziehe ich " IV " können Sie , einschalten und erhalten "cp" aber iv nicht

**Comment by AlpaEZPZ** [comment]
der bug wurde soweit ich weiß mit einem fix von heute morgen behoben. ich sehe keine auffälligkeiten mehr.

**Comment by PokemonAddict** [comment]
Funktioniert bei mir auch tadellos!
