### ISSUE TITLE
help proxy don't work

### ISSUE THREAD

**Issue by opggdata** [Ar1i/PokemonGo-Bot#2995]
hi i can't find any pokestop in range of 5000 i'm probably ip banned but why it's doesn't work with proxy of u'r proxy list?

**Comment by teejvyx** [comment]
this really helps explain your problem..

**Comment by opggdata** [comment]
hi i can't find any pokestop in range of 5000 i'm probably ip banned but why it's doesn't work with proxy of u'r proxy list?

**Comment by opggdata** [comment]
yes i failed x)

**Comment by opggdata** [comment]
ok finally after 20min of "can't find any pokestop" it's work i close this.
