### ISSUE TITLE
low exp/hr if using proxies

### ISSUE THREAD

**Issue by darkyehwa** [Ar1i/PokemonGo-Bot#2997]
hi, i'm using 3 bot at the same time 1 original IP and the other 2 using free proxies but the original ip had 50k xp/hr but the proxies one is only 15k xp/hr

how i could improve this?

thanks

**Comment by teejvyx** [comment]
are all the settings on the bots exactly the same? @darkyehwa

**Comment by Waiiim** [comment]
Use a higher connection proxy
Public proxies are weak such as free vpn's :c Can't improve much excepted buying one

**Comment by chusski** [comment]
where you buy proxys guys ? plz

**Comment by Ar1i** [comment]
Probably slow af proxy
