### ISSUE TITLE
Suggestion about "set location"

### ISSUE THREAD

**Issue by blasanru** [Ar1i/PokemonGo-Bot#2998]
Hi there.

Its possible in future version to add the option set location like google maps (put the street, country, etc)

For example: hyde park, Retiro Madrid, road Street 

Thanks

**Comment by emilie253** [comment]
isn't not a pirority.
And isn't here for suggestion.

**Comment by blasanru** [comment]
i cant find it. where is?

Tx

**Comment by urangotango** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/  here they have an suggestion section

**Comment by Captnred** [comment]
^ the proper link is  here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
