### ISSUE TITLE
[Feature Requested] Able To See Where Character Is.

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#300]
The title pretty much sums it up. If you can implement a way to see where your character is going.

**Comment by TheSmartly** [comment]
Connect the Telegram bot
Wite /stats
go on omne of the links 
profit

**Comment by Tochez** [comment]
where do i get the telegram bot? sorry im new

**Comment by Tochez** [comment]
@TheSmartly

**Comment by TheSmartly** [comment]
@Tochez https://github.com/Ar1i/PokemonGo-Bot/issues/95

**Comment by Tochez** [comment]
oh ok thanks @TheSmartly
