### ISSUE TITLE
Help on German please 

### ISSUE THREAD

**Issue by xCrezYxBoYx** [Ar1i/PokemonGo-Bot#3000]
Kann mir hier jemand auf deutsch helfen? Und mir das mit den Proxies erklären? Wäre echt dankbar ❤

**Comment by PokemonAddict** [comment]
Sorry, wer nicht weiß, wie man einen Proxy wie hier konfiguriert, sollte auch kein Bot benutzen... Sorry!

**Comment by xCrezYxBoYx** [comment]
Anstatt diesen Text zu schreiben könntest du es mir ja erklären jeder fängt mal klein an
