### ISSUE TITLE
Which % for razzberrys?

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#3002]
Guys, the auto-suggested percentage is 35%. What are your settings?

**Comment by bkrandy** [comment]
id say around 25 is good

**Comment by Ar1i** [comment]
35 was default, and i am still using 35

**Comment by emilie253** [comment]
we can change???

**Comment by PokemonAddict** [comment]
yes - since last update. 35% is a little too high in my eyes.

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/


If you wouldn't mine closing this thread. Seeing how this is not an issue.
