### ISSUE TITLE
Some change

### ISSUE THREAD

**Issue by Nivvdiy** [Ar1i/PokemonGo-Bot#3003]
Hello, I made some change in your code to add french pokemon name and to add a column for the pokedex number to the pokemon list. I would like to submit you my modifications.
![pokebot](https://cloud.githubusercontent.com/assets/20977958/17606506/2b6f6bc8-6020-11e6-9294-27917c8e8328.PNG)
![pokebot2](https://cloud.githubusercontent.com/assets/20977958/17606505/2b6f0f48-6020-11e6-9d6b-ee0525e990a1.PNG)

**Comment by Captnred** [comment]
For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

If you wouldn't mine closing this thread. Seeing how this is not an issue.

**Comment by Nivvdiy** [comment]
This is not an issue and not really a suggestion but yeah i'll post it one the thread, thanks :)
