### ISSUE TITLE
we can't find any pokestops in a range of 5000 m ?

### ISSUE THREAD

**Issue by kobraman22** [Ar1i/PokemonGo-Bot#3004]

**Comment by immoempe** [comment]
sounds like you are IP Banned, reset your router or use proxy/vpn to bypass the ban

**Comment by urangotango** [comment]
At first try to restart your router if you dont have an fixed IP this will solve your problem for bot client

**Comment by DVD-DY** [comment]
Maybe you have a altitude problem like me look here #3034
