### ISSUE TITLE
NOT WORKING ! erreur when i start

### ISSUE THREAD

**Issue by loudjedi** [Ar1i/PokemonGo-Bot#3005]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by loudjedi** [comment]
![prob](https://cloud.githubusercontent.com/assets/20914496/17606642/85799448-6018-11e6-9f8a-77e663b5eece.PNG)

**Comment by loudjedi** [comment]
please help

**Comment by immoempe** [comment]
try downloading/extracting the files again (download the new version)

**Comment by urangotango** [comment]
if this dont help try to delete confix folder and start the bot again

**Comment by loudjedi** [comment]
i did its the new version which did this probelem

**Comment by loudjedi** [comment]
same thing does't work

**Comment by Ar1i** [comment]
should be fixed in update
