### ISSUE TITLE
what mean for "Device"...?

### ISSUE THREAD

**Issue by BangBhexe** [Ar1i/PokemonGo-Bot#3008]
any1 can can explain?

**Comment by sealtx** [comment]
what phone you are using to play poke go

**Comment by BangBhexe** [comment]
im usinng xiomy note 3 pro 
in the list does not exist
What should I do?

**Comment by BangBhexe** [comment]
whether it will be problematic if I select the device that is incompatible with the device that I use

**Comment by ilinbkili** [comment]
yea I too am playing on an iPhone and that is not listed either

**Comment by FerMedina86** [comment]
Salvador Jr. Garcia ‏@realmono705  37 minhace 37 minutos 
@Ar1iDev  of we don't have the device listed and we don't want do we leave it as it is ?
0 retweets 0 me gusta
Responder   Retwittear    
Me gusta  
Más
 Ar1i ‏@Ar1iDev  34 minhace 34 minutos 
@realmono705 yeah or just choose any of that, you dont need to have it

Ar1i ‏@Ar1iDev  39 minhace 39 minutos Ver traducción
@_aidenfisher nah, atm its like every bot user got the same smartphone.. which could look shiity you know? its just security update
0 retweets 1 me gusta
Responder   Retwittear    
Me gusta 1  
Más

**Comment by Kidnub** [comment]
i play on a huawei p8l XD and itis even not in but you can have more as one phone or tablets ?

**Comment by FerMedina86** [comment]
Salvador Jr. Garcia ‏@realmono705 37 minhace 37 minutos 
@Ar1iDev of we don't have the device listed and we don't want do we leave it as it is ?
0 retweets 0 me gusta
Responder Retwittear

Me gusta

Más
Ar1i ‏@Ar1iDev 34 minhace 34 minutos 
@realmono705 yeah or just choose any of that, you dont need to have it

its just security update

**Comment by FerMedina86** [comment]
chose one device , but always the same

**Comment by BangBhexe** [comment]
hope it may not a big problem

thx :)

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
