### ISSUE TITLE
New Device Added to List

### ISSUE THREAD

**Issue by BradleyFlorence** [Ar1i/PokemonGo-Bot#3009]
All the Devices that the Bot is supposed to run on are, android devices, and I usually run the game on an iPhone which can be an issue for me and might cause a ban or some type.

**Comment by k756u** [comment]
add lg g3  :3

**Comment by urangotango** [comment]
i think this will be not an problem you can  have an iphone and 20 android tablets ...

**Comment by kingwizardz** [comment]
Add Galaxy Tab A    Please !!

**Comment by FerMedina86** [comment]
Droid Ultra =)

**Comment by Dmouse92** [comment]
I use a OnePlus One getting a OnePlus 3 add both

**Comment by lkk168** [comment]
Add HTC_M9px     (HTC M9+)

Thank you

**Comment by teeou12345** [comment]
Add Xperia X performance Please !!
Thank you

**Comment by teekeiei** [comment]
Add Xperia x performance Please !!

Thank you =)

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/


If you wouldn't mine closing this thread. Seeing how this is not an issue, but a fear of being banned.
Just an fyi its an extra security method.  Say you used the bot it would randomly generate ur device etc, but now it gives you an option to keep the same selected device.
