### ISSUE TITLE
Still nothing from pokestops and no pokeballs

### ISSUE THREAD

**Issue by Dmouse92** [Ar1i/PokemonGo-Bot#301]
I get a / when I hit a pokestop. and I cant catch any pokemon because I have no pokeballs. PLEASE HELP

**Comment by Playhard89** [comment]
cant you go to a pokestop by yourself then start the bot ?

**Comment by HaydarOzturk** [comment]
or stop moving radius and speed and select a location with couple of pokestops and just let the program pick pokeballs from pokestop. But ıf you can't get anything that is because you probably soft banned...

**Comment by Dmouse92** [comment]
I figured it out I had too many items. lol
