### ISSUE TITLE
Bot does not  recycle  pokemons  .... 

### ISSUE THREAD

**Issue by Xysas** [Ar1i/PokemonGo-Bot#3012]
Bot does not delete my  pokemons... like  stacks with   pokemong that i  have choosen to delete ... i have 1 of each  delete max cp 1200+ and   iv  90+

**Comment by kingwizardz** [comment]
OMG !!

**Comment by Kidnub** [comment]
check you checkboxes on start XD 
http://www2.pic-upload.de/thumb/31437252/justuncheckthatbox.jpg and then start the bot

**Comment by Xysas** [comment]
lol my bro i did  its fine 
![lel](https://cloud.githubusercontent.com/assets/20915192/17607462/8bba9f08-602e-11e6-8fbe-6abd9b25fdb5.png)
