### ISSUE TITLE
Proxy? (GER)

### ISSUE THREAD

**Issue by PCKGOHCKTEAM** [Ar1i/PokemonGo-Bot#3013]
Kann mir das mit den Proxy Servern bitte mal wer erklären?

Ich hab mir die IP und den Port aus dem Internet gesucht, aber bekomme nur Fehlermeldungen.

In anderen "Issues" steht immer was von eigenen HTTPS oder so :D 

Leider blick ich nicht ganz durch :sos: 

Danke für eure Antworten :tada:

**Comment by brainoutput** [comment]
Also dein Rechner bracht eine andere IP Adresse wenn du mehrere Clients laufen lassen willst.
Das heisst, das der Bot einen Tunnel (VPN) zu einem andern Netzwerk macht und von dort ins Internet geht. Die Proxiserver die du im Internet findest, sind schon gebraucht worden, oder auf einer schwarzen liste beim Spiele Hersteller.
Ich habe zu beispiel einen ASUS Router auf dem man mit wenigen klicks eine VPN verbindung einrichten kann, also solltes du bei deiner Oma oder Freunden ein VPN einrichten und den BOT dort hin schicken.
In der regel braucht man dafür einen Usernamen, Passwort, und eine IP oder Dyndns Namen.
Du kannst auch nur einen Bot laufen lassen, dann hast du keine Probleme.

**Comment by PCKGOHCKTEAM** [comment]
@brainoutput Endlich mal eine Vernünftige Erklärung! Danke! :)

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
