### ISSUE TITLE
Any Good Private Proxy Site?

### ISSUE THREAD

**Issue by bendeko** [Ar1i/PokemonGo-Bot#3014]
_Unable to find pokestops_ if i run more than one bot. Anybody have a good site to get private proxys that work i dont mind paying.

**Cheers!**

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/


If you wouldn't mine closing this thread. Seeing how this is not an issue.
