### ISSUE TITLE
2 windows error adding bot

### ISSUE THREAD

**Issue by sergiohacks3** [Ar1i/PokemonGo-Bot#3016]
the second I open window to open the bot according as I worked before will not now me. I put in a new folder, with another account, another proxy other settings and always gives me error the second, they are updating can not be put 2 bots?

**Comment by brainoutput** [comment]
Read button message on client. (Only 1 Bot with same IP)

**Comment by sergiohacks3** [comment]
I do not have the same IP, I have another proxy in the second bot

**Comment by sergiohacks3** [comment]
this error : https://gyazo.com/6da17c27d4df955c716ea5fbde87a3cb

**Comment by brainoutput** [comment]
maybe public proxy? Dont take public proxy.
