### ISSUE TITLE
Item issues!

### ISSUE THREAD

**Issue by xWickedx420** [Ar1i/PokemonGo-Bot#3018]
Hey Ar1i thanks for the great work man, much appreciated! Anyways over the last few builds I've noticed the item calculation is wrong or something, currently it says my items are 363/350 and I was literally just on my phone and I only had 100 items, I've been seeing the bot do this fairly often, might want to look into! Thanks!

**Comment by xWickedx420** [comment]
Even after redownloading and verify I don't have a lot of items the bot still seems to be showing item numbers that are way off

**Comment by SkyWalkerMc** [comment]
Same here. Old bug

**Comment by xWickedx420** [comment]
Well it worked perfectly two days ago, I use the bot for items when I run out, whatever got changed messes me up big time because I have no clue when my items are good to go
