### ISSUE TITLE
share private proxy website

### ISSUE THREAD

**Issue by k3npachi** [Ar1i/PokemonGo-Bot#3020]
Hi, I think it would be some sharing their private proxy site

I have find this, but it is expensive

https://buyproxies.org/panel/cart.php?gid=2
Squidproxies.com
MyPrivateproxy.net

share website with low price for help

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
