### ISSUE TITLE
Change Name And Mark A Favorite

### ISSUE THREAD

**Issue by xrufino** [Ar1i/PokemonGo-Bot#3021]
please add the ability that we can change the name of the pokemon or marked as favorite from the pokemon list, i dont know if this belong here is my first time using the page, but i just want to make that opinion...

**Comment by elenex23** [comment]
Not an issue but I agree.

**Comment by Srihernogo** [comment]
Me too, please to support that..

**Comment by Captnred** [comment]
For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

Please close the thread as this is a suggestion not an issue.
