### ISSUE TITLE
Pls Ar1i use this lib for updating

### ISSUE THREAD

**Issue by xAzzzu** [Ar1i/PokemonGo-Bot#3023]
Hey Ar1i,
if im allowed to i would recommend you this lib: 
http://www.vb-paradise.de/index.php/Thread/110666-nUpdate-Die-einfache-Updatel%C3%B6sung/?pageNo=1

the how to use guide is on german so it should be really easy to understand for you.
It's easy to manage update packages i also used it for some projects and for the normal user its easier to update. 

Viele Grüße
xAzzzu :)

**Comment by Captnred** [comment]
For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

Please close the thread as it's a suggestion.
