### ISSUE TITLE
No pokemons

### ISSUE THREAD

**Issue by estwr2014** [Ar1i/PokemonGo-Bot#3024]
I can start the bot. Everything is normal except there is no Pokemons. I could farm only. Any one help?

**Comment by MocroMind** [comment]
U cant catch pokémon anymore.

[01:20:11] Found 4 catchable Pokemon(s).
[01:20:13] Encountered Poliwrath CP 770  IV 28,14% Probability 11%
[01:20:17] Thrown ItemRazzBerry. Remaining: 56.
[01:20:17] Poliwrath CP 770 IV 28,14% got away while using ItemGreatBall..

Every pokemon is running away now

**Comment by iOwner** [comment]
potential softban

**Comment by Polarbear008** [comment]
new update cant find poke stop

**Comment by estwr2014** [comment]
So it is saying that I can't catch any pokemons any more if using the bot?

**Comment by MocroMind** [comment]
Unban doesnt work anymore i think because another account can catch pokemon but my main not.

**Comment by wannaD1E** [comment]
If there is no pocket stops - IPban

**Comment by gummyruler** [comment]
2 accounts in 1 ip = softban. You use bot and someone in your network logs in PGo its only a matter of time till u get softbanned.
