### ISSUE TITLE
I would like some support/help.

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#3025]
Hi, I was wondering if, @Ar1i , you could leave a post (issue) concerning the new updates you did on the new bot release just so we can stay up to date. 
Because I work all day and sometimes I can't come to follow the current updates on the bot so I'm a bit lost when I get home and see that I've missed 2-3 updates and there's new things on the bot which I didn't know about. 
For example that device and proxy thing.
I tried to go on the website but its mostly in german and I'm french/english so I don't understand what's going on there.. xD

Thanks for your support and your great job.

**Comment by Pyroman2300** [comment]
Right click - Translate to English.

**Comment by wannaD1E** [comment]
I don't understand the question... the Device, choose any. This is necessary so that the server does not swear. Proxies for those who use more than 2 bots. Need a paid https proxy

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

Please close this thread as it's not an issue, but requesting information.

**Comment by gummyruler** [comment]
Let me get you up to speed @CowMadness:

1.The proxy is for people who run 2 or more bot at the same time.
2. Find proxy sites and copy the IP (E.G 63.150.152.151) for the top panel and Port (E.G 8080). for the lower panel.
3. When using proxy: 
                                - Make sure the proxy is all on 
4. The Device is to make sure our device type is consistent (Correct me if I'm wrong)
