### ISSUE TITLE
JSON bug.

### ISSUE THREAD

**Issue by Raz0r62** [Ar1i/PokemonGo-Bot#3028]
Can't use the bot. I'have Json error, and cant have pokemon list. 
Sorry for my bad english.

> screen > 
![json bug](https://cloud.githubusercontent.com/assets/20980262/17609314/1212de3a-6034-11e6-8f1b-34ef6edfec8a.JPG)
![no list](https://cloud.githubusercontent.com/assets/20980262/17609318/1beb9e60-6034-11e6-9454-5753b7dc4887.JPG)

**Comment by Raz0r62** [comment]
And i want precise i use the new version !
Latest Build - 12.08 00.16.rar	json error fix	2 hours ago

But for me it was no fix !
I try 3 times.

**Comment by wannaD1E** [comment]
Delete translit derectory

**Comment by wannaD1E** [comment]
directory*
And use the search

**Comment by Raz0r62** [comment]
Oh ! its good ! Thx  @wannaD1E !
