### ISSUE TITLE
Cant battle Gyms or get pokestops

### ISSUE THREAD

**Issue by elijamesn2001** [Ar1i/PokemonGo-Bot#3029]
I have been using the bot for 2 days now and went out to go pokemon hunting with my normal account. I took over a gym and i wasn't able to add my pokemon to it with the bot account, it would just say error same for when i try to battle. Also when i went to spin a poke stop i would be able to just keep spinning it and i never got anything from the stop i tried several different stops.

**Comment by Jasmineb772** [comment]
You're probably soft banned, the bot should unban you after a while or you'll have to change your IP

**Comment by tonyaf123** [comment]
can you possibly add a feature where the bot fights the gym for you




                                 ,Thank
                                     Tony

**Comment by elijamesn2001** [comment]
So do I click the force in an button? I say a thing that said I was soft banned he morning but then the console soda something like 1337 and I thought that would automatically un ban me

**Comment by spena1024** [comment]
No go to a pokestop on your device... swipe the pokestop then hit close... open the pokestop and swipe then hit close... nothing will fall out.. repeat this 40 times and on your 41st try you will get pokeballs and your unbanned... the game takes 40 tries to reset everything

**Comment by CruSherFL** [comment]
@tonyaf123 bad idea, most people get reported and banned by this.
