### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by Jasmineb772** [Ar1i/PokemonGo-Bot#3030]
Every time I try to open the bot I get the error below. All I did after downloading was extract the "Latest Build - 12.08 00.16.rar" into the "Builds Only" file, nothing else.
![pokemonerror](https://cloud.githubusercontent.com/assets/20980482/17609482/9481f652-6003-11e6-9eae-561ff7aef914.png)

**Comment by lucas2107** [comment]
Try to run it as administrator

**Comment by Jasmineb772** [comment]
That was the first thing I tried, but the same error comes up

**Comment by lucas2107** [comment]
Do you have the .NETFramework 4.5 ?

DL here: https://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by yomathyo** [comment]
Same problem here. .netframwork 4.5 installed. All the previous version was running perfectly.

 Thanks for your help guys.
