### ISSUE TITLE
Pokemon List - Error under Pokemon Names

### ISSUE THREAD

**Issue by Vachelon** [Ar1i/PokemonGo-Bot#3031]
Pokemon names show up as error under the Pokemon List. No picture of the pokemon is shown.
![a](https://cloud.githubusercontent.com/assets/445461/17609755/770c7ebe-606a-11e6-92bb-61d255be0d87.PNG)

**Comment by lucas2107** [comment]
Restart the bot

**Comment by Vachelon** [comment]
Still the same.
