### ISSUE TITLE
Bot starting error

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#3033]
Guys I can't run the bot I get some errors here is the full logs: http://pastebin.com/Q9wx6q8y

I have another account that work great with the same setting son't know with this accoun doesn't work even if it's not banned or soft banned or anything 
both are PTC

**Comment by dodogtg** [comment]
![no](https://cloud.githubusercontent.com/assets/20829256/17610327/2da91834-6067-11e6-847a-44f218242f20.jpg)


me too, can't find any pokestop in a range of 5000m!

**Comment by bkrandy** [comment]
#3034  altitude maybe?

**Comment by abdellahaski** [comment]
read the logs guys It's not the same issue

**Comment by vxizzlv** [comment]
I'm having the same problem ^

**Comment by bkrandy** [comment]
i got the same issue but mines saying Object reference not set to an instance of an object.

**Comment by vxizzlv** [comment]
same here

**Comment by vxizzlv** [comment]
I think it only affects a ptc account bc its working on my gmail account

**Comment by bkrandy** [comment]
i have 2 google accounts my main doesnt work but the other does

**Comment by abdellahaski** [comment]
@vxizzlv It's working on another ptc account

**Comment by vxizzlv** [comment]
thats weird.

**Comment by liwenzhuo1216** [comment]
our accounts were banned?

**Comment by abdellahaski** [comment]
No I'm actually using it on another bot and it's works greats

**Comment by chavall** [comment]
Change IP or Restart wait until 30 minute = always can't find any pokestop in a range, some solution
