### ISSUE TITLE
Problem with altitude when you cant find pokestops

### ISSUE THREAD

**Issue by DVD-DY** [Ar1i/PokemonGo-Bot#3034]
I found the problem when you cant find pokestops, all say is for ip banned, but i tried so much IPs, VPNs and internet connections and all say the same We can't find any PokeStops... 

Well i try with diferent altitude and found the problem, if you use a higher altitude to 1000 does not work!! look my tests with the same location.

TEST with my real altitude 2534 and later with 0
![p1](https://cloud.githubusercontent.com/assets/20962102/17610339/b1ce1a02-6002-11e6-8da4-4fa00a8f64a9.jpg)

TEST with altitude 50 and 500
![p2](https://cloud.githubusercontent.com/assets/20962102/17610350/db2fb784-6002-11e6-8c89-48151b358781.jpg)

TEST with max altitude 1000 if you use 1001 not works
![p3](https://cloud.githubusercontent.com/assets/20962102/17610363/f0a7afc2-6002-11e6-8c82-6f931f88a6e6.jpg)

Please need a update!

**Comment by rvonz** [comment]
not work for me

**Comment by Heuk** [comment]
yes it works i changed the altitude in the config file to 15 and it worked great

**Comment by Romanoski** [comment]
I Have the same problem, I try to change the altitude but does not work here
I try with 4 version, 0.7; 1.0.8.1; 1.0.9.9; 12.08.00.16, stranger thing is, that start happen to me yesterday, 
before that, all is going good
I use different proxy and ip, still the same, so, yeah, I'm the guy what have the badluky in the world

**Comment by Ar1i** [comment]
Thanks for that found. Fixing it.
