### ISSUE TITLE
Could I stand a fixed location not moving to catch pokemons ?

### ISSUE THREAD

**Issue by Duncan1976** [Ar1i/PokemonGo-Bot#3035]
Sorry my pool English
As tittle
Set a fixed location without moving to catch pokemons
How to set up ?

**Comment by bkrandy** [comment]
try a radius of 10 or less

**Comment by OArda** [comment]
ı tryed but same problem. Cant catch any pokemons

**Comment by zliong2007** [comment]
maybe he want to use pokesniper ? 
cause i have same idea.
is it possible ?

**Comment by OArda** [comment]
Just turn pokestops, find pokemons but all run away

**Comment by gunner5365** [comment]
i would love if they added this as a feature or to only farm pokemon no pokestops
