### ISSUE TITLE
mutliple issues ?

### ISSUE THREAD

**Issue by z3254963** [Ar1i/PokemonGo-Bot#3037]
1st - item number always wrong?
![image](https://cloud.githubusercontent.com/assets/20981816/17611188/a84d0e32-6077-11e6-9724-0808f9062d90.png)

2nd - can i prioritize iv over cp?

3rd - in the pokemon list window, can i sort my list with poke-index? it is difficult to manage when the same family is always separated

4th - i think transfer_first_low_iv is inversed cos when i have it on it keep the 2nd high iv pokemon and when it off its transferred...........

Thank you for solving my problems <3

**Comment by gummyruler** [comment]
1. Stop nitpicking
2. Yes, you just have to read
3. Click name on the top panel
4. No its not.
