### ISSUE TITLE
Not Farming pokestops

### ISSUE THREAD

**Issue by elChieff** [Ar1i/PokemonGo-Bot#3038]
The bot works fine, it walks around and all, but everytime i get to a pokestop, i dont get any items or xp, the bot just go to the next pokestop

**Comment by SivertTB** [comment]
Same for me bro, tried to actually log into the game and tried to delete some stuff in my inventory but that didn't help either.

**Comment by ade182** [comment]
sometimes when you pass the pokestops , maybe it has been spinned or something ? so the bot keep moving through.

**Comment by proyugi** [comment]
I have the same problem. I can still catch pokemon, found pokestops in the nearby area.

I don't get IP banned for sure. But the other accounts work fine.

**Comment by Ar1i** [comment]
#3074
