### ISSUE TITLE
After update all settings reset 

### ISSUE THREAD

**Issue by GreteKlein1337** [Ar1i/PokemonGo-Bot#3039]
Is that normal that after every update, i download new .rar file, Unpack it and then have to select again all pokemons and set item values; account name & password etcc?

How to save those things?
Sorry for bad english. :)

**Comment by ade182** [comment]
just extract the file to the previous existing folder and you won't need to do all the settings again :)

**Comment by Captnred** [comment]
You'd copy over your config file from your last one. 

If you'd please refer to asking questions here though 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

Since this isn't an issue would you mind closing the thread.

**Comment by gummyruler** [comment]
![j2](https://cloud.githubusercontent.com/assets/20757587/17611987/82d8f030-6009-11e6-86ba-d7bff917c671.jpg)
