### ISSUE TITLE
lucky egg

### ISSUE THREAD

**Issue by blahblah1227** [Ar1i/PokemonGo-Bot#304]
how are you able to tell if it actually used a lucky egg? i have it checked and i evolved but i cant tell if it used an egg or not. the experience gained from stops and catching pokemon seem to be the same.  is there a way to actually use the lucky egg manually? so u know u actually used it before evolving. i can confirm that it doesnt use a lucky egg

another question... is there a way to see you inventory list?

**Comment by Ar1i** [comment]
It post in console if you used one, and no atm not
