### ISSUE TITLE
Pokemon got away

### ISSUE THREAD

**Issue by SivertTB** [Ar1i/PokemonGo-Bot#3040]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

So for some reason pokemons get away after using a pokemonball, but if it use Greatball it catches it why?

I don't have a picture

**Comment by gummyruler** [comment]
Did you set pokeball to 0? If so that's why.
