### ISSUE TITLE
failed to get game data error (Important)

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#3041]
after i downloaded tghe new update i got the error and the bot was not working so i started up my phone and closed the bot and the game in my phone isnt working says failed to get game data but when i logged into my other account it worked fine. Did the bot just make my account go banned?or the servers are not working for my that single account? please help me out.

**Comment by bkrandy** [comment]
#3033  #3036

**Comment by ade182** [comment]
don't you ever blame the bot, if you can't open your account , create another one or at least you got another id which can be opened , stop crying and be a man :+1:

**Comment by sunit1998** [comment]
ade if u cant help out dont open ur mouth please

**Comment by TwoMew** [comment]
I got the same problem. But I cant even loggin on my phone. Hopefully I am not perma banned.

**Comment by gummyruler** [comment]
![j2](https://cloud.githubusercontent.com/assets/20757587/17611964/42dd7794-6009-11e6-994a-1bbbeb066bd9.jpg)

**Comment by zorndyke** [comment]
tried with other bot and on phone, the results are same, it mean my account are banned (permanently ?)
but other account still works

**Comment by gummyruler** [comment]
![j2](https://cloud.githubusercontent.com/assets/20757587/17611979/7152e474-6009-11e6-92e2-74b5a62dd166.jpg)

**Comment by liwenzhuo1216** [comment]
wave ban... fuck

**Comment by TwoMew** [comment]
@liwenzhuo1216 Where did you get that?

**Comment by liwenzhuo1216** [comment]
When i log in on phone, it says "we are surprised by your incredible response, we are resolving this issue."    It appears only one time and when i tried to login in again,  its says "failed to get game data error "

**Comment by TwoMew** [comment]
@liwenzhuo1216 I got nearly the same.

**Comment by liwenzhuo1216** [comment]
@TwoMew , well, hope that was not a permanent ban :(

**Comment by TwoMew** [comment]
@liwenzhuo1216 I hope so too. But I just read that accounts with a high XP boost get banned since 4-5 hours or so ...

**Comment by liwenzhuo1216** [comment]
@TwoMew , the only thing we can do is to wait for official confirmation...

**Comment by timewizard19** [comment]
just wait the confirmation about this, its just banned for 4-5 hours maybe

**Comment by TwoMew** [comment]
Hopefully

**Comment by TwoMew** [comment]
@gummyruler I tried. Also re-installed the app. Nothing solved it.

**Comment by mhjick** [comment]
Its permanent ban, niantic deleted our game data while using bot similar also to this

**Comment by wasabi201** [comment]
damn i think it perm ban too. my other account work . but not my boting....

**Comment by Ar1i** [comment]
#3074
