### ISSUE TITLE
choose pokeballs

### ISSUE THREAD

**Issue by BrodyHough** [Ar1i/PokemonGo-Bot#3042]
iv been having my bot trow greatballs and untrabulls at pokemon with less then 100cp is it posable to add a new setting that lets you choose what level cp or IV it trows the certain poekball like 100% iv or 1000+cp it will trough a ultraball and less then 50% IV or less then 500 cp it will trow a basic pokeball

**Comment by Captnred** [comment]
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/

For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

If you wouldn't mine closing this thread. Seeing how this is not an issue.
