### ISSUE TITLE
catch Pokemon

### ISSUE THREAD

**Issue by Synthek** [Ar1i/PokemonGo-Bot#3043]
hi guys i cant catch pokemon but im not banned so the bot throw a pokeball and allways the pokemon runs away

**Comment by ineedtostudy** [comment]
^ I'm having the same problem. I'm not ip banned, i can still farm pokeshops but can't catch any pokemons. They keep running away.

**Comment by SivertTB** [comment]
Same for me

**Comment by PokemonGoer** [comment]
Probably out of pokeballs try dropping all your potions and revives

**Comment by ineedtostudy** [comment]
@PokemonGoer Nope, these are my usual settings. They worked a couple of hours ago. Now it doesn't work. I ran the bot for 30mins now and still. I ran other bots, including haxon and necro and i still encountered the same problem 
![capture](https://cloud.githubusercontent.com/assets/20897325/17611991/9d68f882-6009-11e6-941a-f27b614599f6.PNG)

**Comment by gummyruler** [comment]
Do you have pokeballs? If not then yea that's why.

**Comment by eLDeMe** [comment]
Same here:
![image](https://cloud.githubusercontent.com/assets/20787975/17612581/d339b10c-6010-11e6-928a-fa85c2c83666.png)
![image](https://cloud.githubusercontent.com/assets/20787975/17612586/e39845b8-6010-11e6-87a9-835946b4f615.png)

**Comment by eLDeMe** [comment]
Older version has the same problem, but it was working good some hrs ago, niantic change something? :(

**Comment by bkrandy** [comment]
@eLDeMe somethings going on as most peoples main accounts arent able to login in atm it seems

**Comment by eLDeMe** [comment]
login in bot or app?

**Comment by eLDeMe** [comment]
In pkgo app cant catch neither, I have this proble only in 1 account, new kind of ban? :(

**Comment by gummyruler** [comment]
Check your altitude.

**Comment by Ar1i** [comment]
#3074
