### ISSUE TITLE
Can't login on bot and phone | Perma banned?

### ISSUE THREAD

**Issue by TwoMew** [Ar1i/PokemonGo-Bot#3044]
Is it possible that I got perma banned? On the screen is a message "Server Error. Please Try again later". After a few restarts it tells me "Player data could not be retrieved from the server."

**Comment by gummyruler** [comment]
Did you confirm your email?

**Comment by TwoMew** [comment]
@gummyruler I didn't get a confirm email.

**Comment by gummyruler** [comment]
![j2](https://cloud.githubusercontent.com/assets/20757587/17612051/6848ac28-600a-11e6-8b60-e66b2e90a048.jpg)

**Comment by gummyruler** [comment]
They deleted your account for the lack of email confirmation.

**Comment by TwoMew** [comment]
@gummyruler ? I never ever got an E-Mail for confirming anything with Pokémon?

**Comment by zorndyke** [comment]
how to get mail confirmation if logging with google account? #3041

**Comment by gummyruler** [comment]
@TwoMew You have to do it to activate your account in PGo once you've registered. You're using google right?

**Comment by TwoMew** [comment]
@gummyruler Okay? Can't remember that. Yeah right, google

**Comment by gummyruler** [comment]
@TwoMew You should've went to your google mail and click on the link they gave you to confirm your account. Sadly bud your account is gone now.

**Comment by zorndyke** [comment]
i got email confirmation with ptc account but google.
whhelppp
![failed](https://cloud.githubusercontent.com/assets/20897536/17612243/f095d866-6079-11e6-9d20-283ca3078860.png)

**Comment by timewizard19** [comment]
@zorndyke  same with me zorn, always failed login, but my other account can login

**Comment by gummyruler** [comment]
Look at your google mail it's there. Same email account as your PGo.

**Comment by timewizard19** [comment]
i use google not ptc, i didnt got any email from poke go

**Comment by TwoMew** [comment]
@gummyruler I looked. Never got an email?

**Comment by zorndyke** [comment]
@gummyruler it's not there, yes there's 1 email confirmation from my ptc account, BUT (not with) GOOGLE login.

**Comment by liwenzhuo1216** [comment]
no email!!! google account.

**Comment by timewizard19** [comment]
google account didnt get any email i think

**Comment by gummyruler** [comment]
You all do get one.

![pgo](https://cloud.githubusercontent.com/assets/20757587/17612307/a858dc72-600d-11e6-9296-feedd6ab0934.png)

**Comment by timewizard19** [comment]
its verification, only for ptc, all ptc user get it

**Comment by gummyruler** [comment]
That's my google account and I still have to click it. PTC in order for you to play they require you to activate your account first.

**Comment by TwoMew** [comment]
All emails ever received with this account. These 3 google emails are just the 3 standard emails you get when creating a new gmail account.
![unbenannt](https://cloud.githubusercontent.com/assets/20982469/17612329/f5779f3c-6050-11e6-928c-d08dab5d53f9.PNG)

**Comment by timewizard19** [comment]
i use google account but i didnt receive the email

**Comment by gummyruler** [comment]
Sorry bud, but the request might be lost somewhere or considered as spam.

**Comment by zorndyke** [comment]
thiis is my email confirmation, only 1 mail from pokemon, and it's only confirmation to ptc.
![untitled](https://cloud.githubusercontent.com/assets/20897536/17612348/0d487ea4-607b-11e6-9bb1-3926cc1e5a50.png)

**Comment by liwenzhuo1216** [comment]
@gummyruler , our accounts are gone???  it is not fair because only a few accounts were banned.

**Comment by TwoMew** [comment]
@gummyruler that's strange because also on my other accounts I didn't get anything from Pokémon.

**Comment by gummyruler** [comment]
This is mine. Same google account that got email conf. 
![mine](https://cloud.githubusercontent.com/assets/20757587/17612381/79b4978e-600e-11e6-8c8f-ff852d42512c.png)

**Comment by gummyruler** [comment]
@liwenzhuo1216 it's not a ban. they removed your account.

**Comment by TwoMew** [comment]
Is it possible to get a new email conf. for my accounts?

**Comment by rodyxp** [comment]
It may be a server issue too.. Keep trying..

**Comment by gummyruler** [comment]
@TwoMew You can try. IDK how to though.

**Comment by bkrandy** [comment]
only ptc users needed to confirm their accounts

**Comment by gummyruler** [comment]
try this.

https://www.youtube.com/watch?v=lCmVfdFW1XA

**Comment by timewizard19** [comment]
its not release account i think, i use 3 google account and i didnt get the confirmation email, but only 1 of my account is failed to login

**Comment by liwenzhuo1216** [comment]
![7855e248-f591-4698-a71a-871d5c431a16](https://cloud.githubusercontent.com/assets/6996382/17612498/0e957334-6085-11e6-8504-ebde7d28620e.png)

**Comment by gummyruler** [comment]
Ok guys my bad. I just realized I made an account PTC, but can't login using the account. So I just logged in using gmail. U don't need to confirm your account. But there are fixes out there for the bug.

![dumasses](https://cloud.githubusercontent.com/assets/20757587/17612490/94cfda78-600f-11e6-8ef5-66cffa87c677.png)

**Comment by timewizard19** [comment]
yup, after retry and retry got that message, its server issue i think

**Comment by TwoMew** [comment]
@gummyruler I tried. Also re-installed the app. Nothing solved it.

**Comment by timewizard19** [comment]
@liwenzhuo1216 just wait 4-5 hours maybe, hope its not perma-banned

**Comment by angelloisaac** [comment]
it is the "infinite loading screen" , its a server side issue.

**Comment by timewizard19** [comment]
some player get that issue, and the other didnt got it

**Comment by liwenzhuo1216** [comment]
@timewizard19 , it seems server side issue!

**Comment by timewizard19** [comment]
@liwenzhuo1216 yeah, just wait a hours, and wait for the confirmation

**Comment by gummyruler** [comment]
What I feel right now:

![troll](https://cloud.githubusercontent.com/assets/20757587/17612547/79db1178-6010-11e6-88a2-8de6589b8f6d.jpg)

**Comment by Juiche** [comment]
no email activation required if u using GOOGLE LOGIN!

**Comment by bkrandy** [comment]
gettin everybody thinking their accounts are deleted lol

**Comment by gummyruler** [comment]
@bkrandy I'm done bruh.

**Comment by gummyruler** [comment]
@juiche No need to confirm Gmail. It's only a bug.

**Comment by elenex23** [comment]
I "used" to have two ptc accounts that I can no longer log into. It has been around one week since they were "banned?" When trying to log in it tells me I need to verify my accounts. I already have and played after verifying a week prior. I went to ptc webpage and request a new verify link but the email never comes. To make sure they have email registered correctly I submit help ticket which I did receive an email receipt of. In conclusion I considered these two accounts banned but I just don't know.

**Comment by crazyandy3** [comment]
"It appears  that there is a new type of ban happening. It does not appear to be an IP-ban, rather an account one. There is not many details yet, it is all a mix of speculations and rumors, but there is definitely something happening.

**Comment by mhjick** [comment]
mine too showing failed to load my game data.  But my 3 other account including my trainer account can be logged in. sucks this should be perma ban.

**Comment by wasabi201** [comment]
i cant log in my main account but my other is fine. i think i got banned.....

**Comment by rvonz** [comment]
play a lot of accounts, if one of your account getting banned, then the other account is still there to be played

**Comment by wasabi201** [comment]
lol my main is banned. spend like $200 on it...fml...
10 dragonite, 10snorlax,10laprass most are 100% and maxxed

**Comment by liwenzhuo1216** [comment]
@wasabi201 , me too,  fuck!

**Comment by wasabi201** [comment]
now i am stuck with 2 lvl 30's account. with shit pokemon...damn it

**Comment by whitemouse14** [comment]
Yes. Its surely banned.
I hv 3 google accnts and those 2 account work fine but my last account which use bot doesnt seem to work as well.

**Comment by whitemouse14** [comment]
I owned 20 gyms, 
So damn guys.
Hopefully its not a perm ban

**Comment by Zykhatslover** [comment]
Permaban ban 109% :).

**Comment by whitemouse14** [comment]
Is it really???

**Comment by SaniX0** [comment]
I have this error too, and i think this is 100% not a server issue.. is a ban. All my friends can login but i can't.

**Comment by Zykhatslover** [comment]
Ofc it is. I tried to log with a legit account and it worked so it's a permanent ban :p well Pokemon go was fun but it's... Oooooveeeer back to the real life guys :D

**Comment by SaniX0** [comment]
@zykhatslover yes it was nice for 3 weeks but maybe we get unbaned.

**Comment by Ar1i** [comment]
#3074
