### ISSUE TITLE
All Pokemon CathFlee [Pokestops Work] OR Vice Versa

### ISSUE THREAD

**Issue by angelloisaac** [Ar1i/PokemonGo-Bot#3045]
Probably a new kind of softban; all pokemon flee but pokestops work or vice versa. 
![issue](https://cloud.githubusercontent.com/assets/20943045/17611977/6e0ebe1e-6009-11e6-910b-6aacf45dfd25.png)

Just wait, stop playing from your account and it should start working again

**Comment by gummyruler** [comment]
How many bots are you running?

**Comment by angelloisaac** [comment]
@gummyruler 1 bot; it started working again after waiting for about 30 minutes

**Comment by gummyruler** [comment]
Yea, you can't login 2 PGo now. A lot of people are reporting that when they login 2 PGo accounts on the same wifi they can't catch anything. Same goes for the bot and your phone.

**Comment by Captnred** [comment]
Glad to hear it started working again

Now only if we could close this pesky thread :P

**Comment by angelloisaac** [comment]
yep yep :)
