### ISSUE TITLE
IP BAN solution.

### ISSUE THREAD

**Issue by rodyxp** [Ar1i/PokemonGo-Bot#3046]
As the title say, for those who got IP BAN just run psiphon3.exe and start the bot.
Very simple and reliable.

Find psiphon3 in the below link or google it.
Thank you 

www92.zippyshare.com/v/3mO9LtXl/file.html

**Comment by immonts** [comment]
thanks will try this

**Comment by BonJaZu** [comment]
Anyone try this and can confirm it?

**Comment by rodyxp** [comment]
Am using it.. Its safe try it

**Comment by spena1024** [comment]
im using it seems to work... your banned until you get to your first pokestop then your unbanned... so confirmed it works i changed locations 6 times worked all 6 times

**Comment by odesse** [comment]
![captured](https://cloud.githubusercontent.com/assets/20943845/17613685/7f3e148c-6068-11e6-8ea1-97875d792209.PNG)
How to fix this guys?  cant use vpn

**Comment by rodyxp** [comment]
Its due to google security.. Use PTC account or turn off google 2 step verification

**Comment by Ar1i** [comment]
#3074
