### ISSUE TITLE
what i need to compile my own version?

### ISSUE THREAD

**Issue by sekilo004** [Ar1i/PokemonGo-Bot#3047]
Hi! i want to compile my own version of this incredible bot. I want to personalize with some addons, obviously I need visual studio and a basic knowledge of c#, but what api and other programs are needed?

sorry for my bad english.
I promise not to steal this work, I use only for personal purposes.

**Comment by CruSherFL** [comment]
You only need Visual Studio 2015 and C# skills. 
Because this is GPL3 (or at least RocketAPI), your changes have to be public (e.g. in your fork)
