### ISSUE TITLE
Can someone give me the link for the full download of the latest version? 

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#3048]
I have had so much troubles with these newer versions now. and I feel like its cause I dont have certain files.

**Comment by timewizard19** [comment]
last version poke go ?

**Comment by timewizard19** [comment]
http://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-33-0-release/pokemon-go-0-33-0-android-apk-download/

**Comment by steezespot** [comment]
and all of a sudden it works again... i dont get it, its very buggy, i'll screenshot once it happens again, meanwhile please close, sorry admin!
