### ISSUE TITLE
Device not Found

### ISSUE THREAD

**Issue by schn33man** [Ar1i/PokemonGo-Bot#3052]
Please can you add the ONEPLUS ONE and the ONEPLUS THREE to the device list

**Comment by SkyWalkerMc** [comment]
for what ? use device on the list is not problem

**Comment by SkyWalkerMc** [comment]
for what ? use device on the list is not problem

**Comment by gummyruler** [comment]
Can we add 0 / 0 too? Please?!

**Comment by schn33man** [comment]
@SkyWalkerMc ist damit nicht dein handy gemeint ?

**Comment by Ar1i** [comment]
Just choose a random device
