### ISSUE TITLE
Post-Login Error

### ISSUE THREAD

**Issue by crypticc** [Ar1i/PokemonGo-Bot#3055]
After logging in and setting up the bot the bot sits and gives the error: "Error reloading Pokemon list: Object Reference not set to an instance of an object." I'm really not sure what this exactly means therefore I wouldn't know how to fix it. 

![image](https://cloud.githubusercontent.com/assets/20983689/17613125/8f137382-601f-11e6-805e-c7b0ecd2dd2e.png)

**Comment by trainermortiz** [comment]
same here... help!

**Comment by bkrandy** [comment]
#3044

**Comment by crazyandy3** [comment]
"It appears  that there is a new type of ban happening. It does not appear to be an IP-ban, rather an account one. There is not many details yet, it is all a mix of speculations and rumors, but there is definitely something happening.

**Comment by drsweg** [comment]
happened to me aswell...any info on a fix yet??

**Comment by Bastii1988** [comment]
I have the same problem. Seems to be a permanent-ban from niantic. They said that a banwave will happen... I don't think that we can fix this problem and so we don't get our accounts back i think...

**Comment by SkullNajera** [comment]
Yep, I have this issue too. I don't think it get fixed, but I hope so. :/

**Comment by drsweg** [comment]
Damn so I got banned??? :/

**Comment by SkullNajera** [comment]
Yeah, I think so

**Comment by drsweg** [comment]
I just got informed that is servers are down at the moment.. I'm hoping I
did not

**Comment by Bastii1988** [comment]
The servers are live...! 99,9% we've got banned...!

**Comment by drsweg** [comment]
The US servers are down so I'm hoping that is my issue

**Comment by SkullNajera** [comment]
Servers are down here too, but when I try to log in with another account, it sends me directly to the common error, while when I login with my original account, it send me the account error.

**Comment by drsweg** [comment]
From what I'm reading it's one of 2 things. 1 it's a soft ban that will
last a little longer than usual or 2 it's the servers that are down or
possibly a combination of the 2

**Comment by Bastii1988** [comment]
Can't be a softban. I have 2 accounts... With my bot-account i can't login with my phone... Everytime i get an error... With my second account i can login and play without problems. So i think that they deleted our accounts or banned our accounts permanent.

**Comment by drsweg** [comment]
I'm not sure I'm gonna try to login again in a couple hours
