### ISSUE TITLE
CHOOSE ANY POKEMON TO CATCH.... THIS LINK HAS ALL THE LOCATIONS!!!

### ISSUE THREAD

**Issue by spena1024** [Ar1i/PokemonGo-Bot#3056]
CLICK http://pokesnipers.com/ THE LINK 

it snipes the pokemon out,.... just change location and type in coordinates and bam

**Comment by PokePro21** [comment]
NIce

**Comment by 08081965** [comment]
how to change location but not get softbanned, i tried and i always get softban and poke runs away

**Comment by PokePro21** [comment]
tysm @spena1024 because of you i caught venusaur

**Comment by monchen** [comment]
90% of the pokemon in the locations are not true. hahaha

**Comment by gummyruler** [comment]
@monchen K den

![kdne](https://cloud.githubusercontent.com/assets/20757587/17614179/50d7cdb4-6021-11e6-89dd-98cd7ab0df8f.png)

**Comment by monchen** [comment]
gummy, then teach us not get soft  banned :D

**Comment by gummyruler** [comment]
Press force unban found on the GUI. If your character sees the pokemon before he gets to the pokestop you basically missed the pokemon.
