### ISSUE TITLE
Cant find any pokestops?

### ISSUE THREAD

**Issue by Teedbag** [Ar1i/PokemonGo-Bot#3057]
![pokenot](https://cloud.githubusercontent.com/assets/20983889/17613426/1fcd27e6-602b-11e6-84a5-cec0c7eaf24c.PNG)

**Comment by gummyruler** [comment]
How many bots are you running? 
![dumasses](https://cloud.githubusercontent.com/assets/20757587/17613553/f116ae0e-601b-11e6-94b9-cec1db57d41c.png)

**Comment by duyennsiro** [comment]
help, please give me new IP

**Comment by gummyruler** [comment]
wait 30mns

**Comment by Teedbag** [comment]
i had just started running a second without thinking but it started working again after i turned both off  and once i changed my location again it did the same thing

**Comment by merth7** [comment]
IP Bann. Renew your ip.

**Comment by Teedbag** [comment]
how sir

**Comment by merth7** [comment]
change DNS settings. The problem will be eliminated.

209.244.0.3 – 209.244.0.4 or 208.67.222.222 - 208.67.220.220  choice is yours

**Comment by merth7** [comment]
#2914

**Comment by Teedbag** [comment]
thank you much obliged

**Comment by Teedbag** [comment]
changed the DNS settings still having the same issue

**Comment by doctorbeanjr** [comment]
same , i was changed DNS, still having this issue

**Comment by rodyxp** [comment]
I posted a solution for IP ban. try that #3046

**Comment by Romanoski** [comment]
I Don't think is IPBAN, because I try with to many IP's differents and do not work
Still the same problem

**Comment by Ar1i** [comment]
#3074
