### ISSUE TITLE
Problems.

### ISSUE THREAD

**Issue by SkillsPayBills** [Ar1i/PokemonGo-Bot#3059]
For some reason all the Pokemon the bot runs into escape but I still can get items from pokestops very odd.
![screenshot_4](https://cloud.githubusercontent.com/assets/20889679/17613760/dc6c2c12-60a3-11e6-9485-2eac713323ad.png)
 Even after I unban myself
![screenshot_2](https://cloud.githubusercontent.com/assets/20889679/17613986/c9a08f9a-60a5-11e6-9498-9fbcd28d8d86.png)
I use the latest build
![screenshot_4](https://cloud.githubusercontent.com/assets/20889679/17614095/c8a1ce00-60a6-11e6-91a3-0fc658a91609.png)

**Comment by trainermortiz** [comment]
maybe you only have 1 incubator

**Comment by phodem** [comment]
im having same problem pokemon escape, just happened  with 3 of my bots

**Comment by TheDavenger** [comment]
Same here

**Comment by jas0513** [comment]
It's the altitude for some reason it doesn't change anymore

**Comment by jas0513** [comment]
It's always zero

**Comment by gado2** [comment]
same problem. all pokemons fled, but still can loot pokestops.

**Comment by jas0513** [comment]
![capture](https://cloud.githubusercontent.com/assets/20984442/17614016/40657a84-6095-11e6-8472-2fcc87a2f945.JPG)
![sadasf](https://cloud.githubusercontent.com/assets/20984442/17614015/4060318c-6095-11e6-962b-da96fd47f57f.JPG)

**Comment by maksim2047** [comment]
same problem. all pokemons fled, but still can loot pokestops. +1

**Comment by phodem** [comment]
tested with my 2nd account and it runs fine. something to do with # of hours log in per day? lol

**Comment by Reyfun** [comment]
i agree with @phodem, maybe now niantic apply a method for limitation bot user to farm, or maybe it's just like "don't play too much, take some rest". if it's the second, then maybe we can do catch pokemon again after offline for x hour(s)

**Comment by gummyruler** [comment]
For all you who can't read here:
![dumasses](https://cloud.githubusercontent.com/assets/20757587/17614225/ce08c7ca-6021-11e6-9c77-cd50f8dab146.png)

**Comment by gummyruler** [comment]
@SkillsPayBills As for you sir, you have no pokeball. So yea don't set pokeballs to 0.

**Comment by gummyruler** [comment]
@jas0513 Set it to 14.

**Comment by Reyfun** [comment]
@gummyruler it's not ip ban, or softbanned. it's really different cases. and u can see in @SkillsPayBills picture that he have enough pokeball from pokestop.

**Comment by gummyruler** [comment]
That was IP then.

**Comment by SkillsPayBills** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/20889679/17614414/80fefe26-60a9-11e6-9b8e-09d35c52a80e.png)

**Comment by Reyfun** [comment]
@gummyruler if it was ip ban, then why my 2nd account work fine?

note: i just use 1 bot at a time, so my main account, going alone, when this problem occours, i close my main account and use my 2nd account

**Comment by HELLspawnTIM** [comment]
I have the same problem with one of my 3 BOTs
All BOTs use different proxies.
The affected BOT can farm Pokestops fine, gets EXP and gets ITEMS
He also has enough Pokeballs (~25) and other balls. His Item-Inventory is NOT full and his Poke-Inventory is NOT fulll
Walking speed 50km/h

But still all Pokemons get away ... no chance to catch them

Any fix for this??
![nocatch3](https://cloud.githubusercontent.com/assets/20964979/17614581/c86b34ce-6067-11e6-9b9f-45bdd3328f79.jpg)
![nocatch2](https://cloud.githubusercontent.com/assets/20964979/17614582/c86c3216-6067-11e6-9dfe-5a272f8db899.jpg)
![nocatch](https://cloud.githubusercontent.com/assets/20964979/17614583/c86dabdc-6067-11e6-8c20-abf5d9fb06aa.jpg)

**Comment by Elvete** [comment]
I have the same problem...cant catch pokemons

**Comment by gummyruler** [comment]
Just wait it out then. Servers are laggy ATM. PTC and Gmail are off.

**Comment by james741** [comment]
#3069

**Comment by HELLspawnTIM** [comment]
@gummyruler 
PokemonGO Servers are up and running
Dont talk bullshit
http://ispokemongodownornot.com/

**Comment by Elvete** [comment]
i entered on nox ffrom an another acc and uc an catch he pokemen... but rom this 37 account i cnat catck pokemons..but still get pokestops..wt on phone and nox 2 the same sh1t

**Comment by Rolandian** [comment]
I have the same problem here but can't farm any pokestop as well, unbanning is not working. Anyone has any idea to sort out this?

**Comment by thomatbu** [comment]
Same problem. Maybe we farmed a long time with the same ip or same place

**Comment by halocannn** [comment]
ı have the same problem, "not cathing pokemons" please help??

**Comment by Ar1i** [comment]
#3074
