### ISSUE TITLE
Error loading pokemon list

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#3061]
I have one PTC running perfect on a proxy. I open another window to run another PTC account and I save a new proxy ip. When I try logging in I get this error. Could it be that account is BANNED or is my IP banned? Or what settings am I doing wrong to get this error. I have tried restarting and still nothing.
![screenshot_1](https://cloud.githubusercontent.com/assets/20720517/17614060/e9842c4c-6017-11e6-8f6e-df6438f8d6e9.png)

**Comment by PokePro21** [comment]
SAME WITH ME ;(

**Comment by AlexisNarvaez** [comment]
Tal vez sea tu ip cámbiala.

**Comment by AlexisNarvaez** [comment]
Tal vez es tu ip cambiala.

**Comment by Farox1988** [comment]
PTC ACC run fine only google acc failed=(

**Comment by RagequitInc** [comment]
same goes for my Google Acc - runs fine but on my Main Machine the PTC wont work and dies with the same Messege - since last Update it happends

**Comment by samy361** [comment]
What can i Do? for this problem ?

**Comment by PokePro21** [comment]
#2979

**Comment by cyberwolf888** [comment]
Im not using proxy and only run 1 bot.
My google account got this error too.

**Comment by PokePro21** [comment]
![012](https://cloud.githubusercontent.com/assets/20843400/17614436/f5332fd6-6083-11e6-9991-710e07d30f7b.png)
Same probllem for me also @Ar1i please fix

**Comment by cyberwolf888** [comment]
I feel this is perma ban, I try to login with my google account to the game but always failed. Damm my 100% IV Dragonnite lvl 33 is gone!

**Comment by addius8** [comment]
same problem with Google account and im only running one bot :( I cant even play it with the Pokemon GO app. I think its ban.

**Comment by james741** [comment]
#3069

**Comment by samy361** [comment]
i think ist a ban, because with my PTC the boot run ? :(

**Comment by addius8** [comment]
The servers are down now. I think i will wait a few hours and when I cant login with my app, I think I ask Niantic per Email. Is it a good idea or not? What do you guys think?

**Comment by samy361** [comment]
ist a good idea !! but i cant wait till the boot run :D i will wait too till 2 pm

**Comment by addius8** [comment]
I will wait till the evening. 

Haha german auto correction ;)
Some more germans here...

**Comment by Kidnub** [comment]
LOL are you med with germans ? XD @addius8  XD?? http://ispokemongodownornot.com check server status and to fix this poke list problem ... stop auto refresh the pokelist and restart once the bot XD

**Comment by addius8** [comment]
Haha I restarted the bot but still not loading pokemon list... Im really thinking this is a kind of ban or your account was deleted by Niantic. Is there no Admin who knows more about this problem ???

**Comment by samy361** [comment]
i wrote to niantic whats the matter of this problem and why i cant log in ?? now im still waiting for the answer.
