### ISSUE TITLE
Last update - Softban each 10 minutes

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#3062]
![vystrizek](https://cloud.githubusercontent.com/assets/14926592/17614194/95572064-6064-11e6-813a-49fc791b85c3.PNG)
After last update i have problem with softban.
I use iphone but this device isnt in device in bot.

**Comment by AlexisNarvaez** [comment]
Cambia de ip.

**Comment by NastyZ98** [comment]
Ban too on two accounts, this isn't ip bans, check with legit account on the same ip

**Comment by jim3D** [comment]
Same for me , unban don't work anymore , i checked with an other account on same IP , it still works , so it's not a ban IP.

**Comment by proxyghost** [comment]
ive also ran into the same softban, wasnt a problem until i ran two accounts

**Comment by gummyruler** [comment]
Pokemon server down regional. Please check server status before posting.

**Comment by proxyghost** [comment]
gui down or pokemon  go itself? i can login just fine atm but run into problems on the gui

**Comment by gummyruler** [comment]
@proxyghost Delete the folder > redownload the latest build > extract the rar on an empty folder. 

Gmail and PTC.

**Comment by james741** [comment]
#3069
