### ISSUE TITLE
Calling. what should I do.

### ISSUE THREAD

**Issue by tung7227** [Ar1i/PokemonGo-Bot#3063]
![untitled](https://cloud.githubusercontent.com/assets/20952224/17614335/cb0ceec0-608f-11e6-84bd-787c0996705d.png)

**Comment by 1nf0** [comment]
You should put your hands together and pray god this is not a permaban.

**Comment by PokePro21** [comment]
permaban ninantic started ? @1nf0  ?

**Comment by 1nf0** [comment]
Normal accounts working, bot accounts do not working. For now, I hope.

**Comment by cyberwolf888** [comment]
My google account got error like this.
But my PTC account still fine.

**Comment by joe112** [comment]
yo this is i think perma ban, my account cant opened

**Comment by james741** [comment]
#3069
