### ISSUE TITLE
cannot run on windows xp??

### ISSUE THREAD

**Issue by cavaler4** [Ar1i/PokemonGo-Bot#3064]
Dear Arli

are this application can run on windows xp 32 bit, if can run on windows xp, i have problem like on the picture

![untitled](https://cloud.githubusercontent.com/assets/20984539/17614391/24b66370-6090-11e6-8a01-6c54aefad840.JPG)

**Comment by Reyfun** [comment]
it required at least net framework 4.5, win xp just can be upgraded till version 4.0

**Comment by james741** [comment]
#3069

**Comment by cavaler4** [comment]
ok tq for the info
