### ISSUE TITLE
They changed the way how you can remove a softban.

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#3065]
...you CAN farm XP by visiting Pokestops, but all Pokemon will get away if you try to catch them.

Changing IP or using the unban method does not work anymore for many people!

**Comment by PokePro21** [comment]
you must have 0 pokeballs

**Comment by PokePro21** [comment]
& your inventory got full

**Comment by Reyfun** [comment]
#3059

**Comment by lailaps** [comment]
lo, no...
Stop talking this kind of trash, if you do not know me.
Just wait until more people get this problem, they will post here.

**Comment by gummyruler** [comment]
And this my friends is why we should practice humanlike botting.

**Comment by FatXana** [comment]
Yep the old way to remove softban doesn't work, atleast for now.

**Comment by lailaps** [comment]
It is maybe an ID ban, I will try with changed device ID inside bot.

**Comment by HELLspawnTIM** [comment]
I have the same problem with one of my 3 BOTs
All BOTs use different proxies.
The affected BOT can farm Pokestops fine, gets EXP and gets ITEMS
He also has enough Pokeballs (~25) and other balls. His Item-Inventory is NOT full and his Poke-Inventory is NOT fulll
Walking speed 50km/h

But still all Pokemons get away ... no chance to catch them

Any fix for this??
![nocatch3](https://cloud.githubusercontent.com/assets/20964979/17614637/1613b174-6068-11e6-9704-e98d1605e3a3.jpg)
![Uploading noCatch2.jpg…]()
![Uploading noCatch.jpg…]()

**Comment by james741** [comment]
why u guy still botting 
you going to get permanent ban

**Comment by pingpongplaya** [comment]
confirmed, having the same issue on one account. the other cannot get into the actual game. receiving the "fail to to get game data from server" and object instance not found in the bot.

**Comment by HELLspawnTIM** [comment]
@james741 
Nobody got any perm ban since

**Comment by vitus0123456** [comment]
29 poke ball, 200 great ball, 279 ultra balls, item: 688/700
pokemon runs away every time, can't catch a single one.  been 2hr+ already.  Must be some kind of new ban?

**Comment by lailaps** [comment]
Yes, changing Ip does not work anymore and you can still get XP by visiting Pokestops.

**Comment by james741** [comment]
#3069

**Comment by lailaps** [comment]
They just may have server issues in that case. lol

**Comment by lailaps** [comment]
Damn, would just need 24 h to reach Level 40 with 11 accounts.

**Comment by phodem** [comment]
This happens when you bot for a long period of time.
# of hours your account been online.
# of exp you are getting per day.

**Comment by HELLspawnTIM** [comment]
@lailaps 
PokemonGO Servers are up and running
Dont talk bullshit
http://ispokemongodownornot.com/

**Comment by lailaps** [comment]
Fact is, that we do not have a perma ban and if this guy would be perma banned he would get notification instead of removed login credentials.
Better read whole thread, than you may understand what I am talking about.

**Comment by lailaps** [comment]
Checked it with 2 accounts on same IP.
1. Account which I was not using for 24 hours works and can catch Pokemon.
2. Account is able to get XP by visiting Pokestops but can not catch any Pokemon.
So it is a new kind of softban.

**Comment by deadshoot123** [comment]
I got same problem. does anyone know this new kind of softban?

**Comment by lailaps** [comment]
I think for now, just wait some hours and close the bot with that account.

**Comment by james741** [comment]
@HELLspawnTIM  #3069

**Comment by lailaps** [comment]
You can still battle gyms with this kind of ban, so no, it is not a perma ban!

**Comment by joy0824** [comment]
so many silly assumptions, i suggest stop saying its not permanent, it is something serious close to permanent maybe. they taking action for sure. me and another fellow have tried login with different account with same ip, one work, the other gets warning and unable to login.

stop acting "positive" its real.

**Comment by deadshoot123** [comment]
I can't battle now.

**Comment by lailaps** [comment]
It is like the IP ban before. Don try to login for a couple of hours.
Try it again in the afternoon and only with one account.

**Comment by HELLspawnTIM** [comment]
@lailaps 
Goood idea, will do

**Comment by drsweg** [comment]
![screenshot_2016-08-12-03-29-04](https://cloud.githubusercontent.com/assets/20933416/17615659/b24ee5f2-603d-11e6-8b2a-c16167436f62.png)
This Is what I get on my phone and on my bot I get Error reloading pokemon list: object reference not set to an instance of an object

**Comment by HELLspawnTIM** [comment]
@drsweg
PTC or Google Account ?

**Comment by drsweg** [comment]
Google

**Comment by elenex23** [comment]
My google account cant catch pokemon at the moment, however I just loaded up my ptc account and it is working fine. Im in california, 39km/h 2000range. No proxy. I believe this is just new form of softban, I will give my google account a few hours before re-attempt to login

**Comment by HELLspawnTIM** [comment]
@drsweg
Then you are surely using the US servers
They are down currently
EU is up

http://ispokemongodownornot.com/

**Comment by drsweg** [comment]
Yes I am using US server...I really hope I didn't get banned

**Comment by HELLspawnTIM** [comment]
@drsweg 
There are no reports about any permanent bans yet
It's surely just a US server issue for you
And surely just another kind of softban for the others

Wait and see....

**Comment by drsweg** [comment]
Thanks for the info man I'll wait a few hours and try my phone again and
not use the bot for awhile

**Comment by Ar1i** [comment]
#3074
