### ISSUE TITLE
Error reloading pokemon list: object reference not set to an instance of an object

### ISSUE THREAD

**Issue by drsweg** [Ar1i/PokemonGo-Bot#3066]
Any Ideas??

**Comment by PokePro21** [comment]
#3061

**Comment by hades5a** [comment]
If u use PTC, you have to verify PokemonGO

https://club.pokemon.com/us/pokemon-trainer-club/edit-profile/

Go to PokemonGO settings and its fine :)

**Comment by drsweg** [comment]
I'm using a Google account

**Comment by ninipokemongo** [comment]
same here....

**Comment by ninipokemongo** [comment]
![image](https://cloud.githubusercontent.com/assets/20985814/17615463/d129d20a-6044-11e6-990c-b67844326d6e.png)

**Comment by drsweg** [comment]
Damn so you think it's a permanent ban?

**Comment by drsweg** [comment]
![screenshot_2016-08-12-03-29-04](https://cloud.githubusercontent.com/assets/20933416/17615574/2b8ad800-603d-11e6-9125-92c82e1fea09.png)
This is what I get from my phone aswell

**Comment by gummyruler** [comment]
Where do you guys live then? Country wise East or West. South or North?

**Comment by drsweg** [comment]
North America on the east coast

**Comment by Kidnub** [comment]
EU XD np to login XD

**Comment by Kidnub** [comment]
http://ispokemongodownornot.com #3044 #3074 #3044 #3069 #3075  pls check alltime the status of login this side is one of the best to check the server status XD 
(i luve pokevision)

**Comment by nikica251** [comment]
I get the same error,is it a ban or what?

**Comment by ogogo1** [comment]
i guess our accs are banned cannot login either same problem here in EU

**Comment by ninipokemongo** [comment]
..and?

**Comment by Alexgabriel0** [comment]
PTC, failed to log in from the bot / app in europe. I think it is a perma

**Comment by drsweg** [comment]
Hey guys yeah I think our accounts got banned for good. I waited 9 hours
and still can't login :/

**Comment by ogogo1** [comment]
BANNED

**Comment by drsweg** [comment]
Damn.. there's gotta be a way to get unbanned

**Comment by SkullNajera** [comment]
Do you guys think there will be a way to un-ban accounts?

**Comment by drsweg** [comment]
I hope so but all we can do is wait..

**Comment by wasakangedsa** [comment]
sad , so there's no fix as of the moment? mine to got the same error.

**Comment by yonathanbrazil** [comment]
me too
