### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PryntHD** [Ar1i/PokemonGo-Bot#3067]
https://gyazo.com/35083537791e07a37585475a9e21d04e The issue i am having

**Comment by gummyruler** [comment]
Are you using proxy?

**Comment by PryntHD** [comment]
no

**Comment by gummyruler** [comment]
Try to check if your username and password is right. Also make sure you're logging in from the right server. (PTC or Gmail.)

**Comment by PryntHD** [comment]
it is

**Comment by james741** [comment]
#3069

**Comment by PryntHD** [comment]
all my shit is low its 15km 5000m

**Comment by gummyruler** [comment]
Server unreachable then.

**Comment by Ar1i** [comment]
#3074
