### ISSUE TITLE
Warning. A permaban wave might have come.

### ISSUE THREAD

**Issue by 1nf0** [Ar1i/PokemonGo-Bot#3070]
Niantic did something and many bot accounts cannot login into server but normal accounts are working properly. Also people hasn't been banned yet get softban more frequently. I don't know what is going on actually but my personal suggestion; do not run your bot account if it hasn't been banned yet until situation gets clear or devs make an explanation about this.

**Comment by joy0824** [comment]
something has changed. not sure if that is permanent ban or what. just stop botting for now i suggest.

i can login, i can claim exp from pokestop but catching pokemon becomes 100% fail. not sure if this is new type of softban or what but it looks scary. i stopped..hopefully not banned

**Comment by cyberwolf888** [comment]
perma ban wave is coming ?

**Comment by james741** [comment]
#3069 
is already here not coming

**Comment by Elvete** [comment]
tyhis is not perma ban but better stop botting until clears up

**Comment by joy0824** [comment]
ok now i relogin with nox, its permanant.

**Comment by Elvete** [comment]
post ab printscreen and show what does it say

**Comment by 1nf0** [comment]
Well, I intended to take&collects gyms on nox but it always failed to get data bla bla and retry and same. Now on phone, it just stucks on loading screen with half bar, no comment or anything.

**Comment by Elvete** [comment]
i can connect on nox and on my iphone... wwith no problems pokestops are fine but cant catch pokemens

**Comment by sunit1998** [comment]
just wait a day or two days it will be cleared my frnd told me that coz that happened to him 5 days ago but now he can play so we should keep our hopes high that we are not banned

**Comment by Elvete** [comment]
its a new kind o sotban..the last one was just bs ez as fk 2 get unbanned

**Comment by NastyZ98** [comment]
Stop using PokemonGO-Bot until dev didn't give us informations about this ban wave, personally I can log in on my android

**Comment by Khorajuste** [comment]
I have 3 account : Vanilla , bot level33 , bot level35 and I can connect with with Vanilla and bot level 35 only the bot level  33 don't work the account who run that night 
So don't run the bot atm just be patient don't panic follow Pokemon go news

**Comment by lailaps** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/3065

**Comment by Abbasoo** [comment]
I use another bot and it's working fine.
The bot i use shows me where the pokemons nearby.
I never get softban or permaban.

**Comment by Georgiexoh** [comment]
Yea same issue here, bar gets half way when loading and says failed to retrieve data from server, So we just wait and see what happens i assume?

**Comment by monchen** [comment]
i tried again. back to normal. bot time :P

**Comment by whitemouse14** [comment]
I hope so.
I stop using bot since 2 dys ago.
And been using it normally. But today when i started logging in, it didnt work.
Oh my ..
Farewell my dragonite 
Farewell 10gyms

**Comment by monchen** [comment]
check your server maybe only down. after i check my server is online i tried again. and its OK
![normal bot](https://cloud.githubusercontent.com/assets/20968999/17615727/b5a01272-6078-11e6-9911-bc96c136fc1c.jpg)

**Comment by crazyandy3** [comment]
so its only apearing like this cuz server down ? how do i check this ?

**Comment by whitemouse14** [comment]
Try to loggin via phone,
And let me know if its ok.

**Comment by monchen** [comment]
check _>> http://www.mmoserverstatus.com/pokemon_go

**Comment by crazyandy3** [comment]
then why only 1 account cant log in :( and all my other  account log i fine at nox :package:

**Comment by monchen** [comment]
dunno. maybe just wait when server is stable

**Comment by Biscuit090** [comment]
Dude I had like 14 accounts I botted and they all got the same message "Failed to retrieve game data from server" guess the ban hammer has been dropped on us. Nice knowing you guys

**Comment by 1nf0** [comment]
Guys, please, this is not a server issue. We say we can login with normal accounts but not bot accounts. I don't know is this a new kind softban or a permaban, just not server issue.

**Comment by whitemouse14** [comment]
@Biscuit090 just try it first dude.
It seems like google server is going down.
Lets think positively.
If Niantic would like to banned us, they could do it to us on the very first day.

**Comment by monchen** [comment]
i can login just fine. same with my laptop with 2 level 35. your saying?
![normal bot](https://cloud.githubusercontent.com/assets/20968999/17615975/69eea7a6-607a-11e6-81ce-552c4165a91e.jpg)

**Comment by whitemouse14** [comment]
@1inf0 i have 2 account that using BOT. And stop using bot 2 days ago. And keep using my highest level to play normal with fly gps. 
And guess what? The one that i use cant loggin but the other account can.
2 account using BOT since the first level.

**Comment by Elvete** [comment]
Resolve: https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by monchen** [comment]
DONT PANIC IDIOTS

**Comment by whitemouse14** [comment]
@Elvete dude, come on. Its not funny at all.
Please be mature

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by pilota56** [comment]
My Bots also works fine. No Problem.

**Comment by Elvete** [comment]
#3074

**Comment by 1nf0** [comment]
Sigh. I don't know what is the upper limit of dumbness for humanity. I said, it is not clear what is going on, there are so many reports about this situation as never had before. I have also the ability to check the server situation, server in my country works perfect, thanks. I just SUGGESTED you to stop botting for standing on SAFE SIDE. Ofc do whatever you wish I don't and won't care whether you play or get ban.

**Comment by xuban** [comment]
Stop trolling with Ban or something. There isn't a Ban issue. The servers are down or laggy.
Close this shit thread.

**Comment by FatXana** [comment]
@monchen  what coordinates are you using?
