### ISSUE TITLE
We can't find any pokestops - Any Real Solution ??????

### ISSUE THREAD

**Issue by Romanoski** [Ar1i/PokemonGo-Bot#3071]
![pokemon](https://cloud.githubusercontent.com/assets/20985318/17615244/4eeaae6e-6043-11e6-9aa4-a9bb92fb7186.png)
If you will say that's BAN IP, please, do not waste time with it !!!!

**Comment by phodem** [comment]
IP BAN!

**Comment by james741** [comment]
#3069

**Comment by Ar1i** [comment]
Is your alt 0?

**Comment by Elvete** [comment]
Resolve: https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by PokemonAddict** [comment]
Created a new account, also using a proxy. Can't find pokestops. Has defintely to do with an ip error or way of looking for a pokestop with the bot. Same IP with my phone - no problems...

**Comment by Elvete** [comment]
#3074
