### ISSUE TITLE
Bot Issue

### ISSUE THREAD

**Issue by wuttiwong01** [Ar1i/PokemonGo-Bot#3072]
![untitled](https://cloud.githubusercontent.com/assets/8930227/17615530/13667f0c-6099-11e6-9e91-758c61c7d977.png)

**Comment by james741** [comment]
#3069

**Comment by wegweisen** [comment]
@james741 can you pls stop to just write your threat? Hes not banned! This is just a normal error which also appears to me sometimes. Just wait a bit and the bot will work again. Im also still not banned and im botting since yesterday the whole time.

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by Elvete** [comment]
#3074
