### ISSUE TITLE
Is this IP ban or what?

### ISSUE THREAD

**Issue by ripharambe** [Ar1i/PokemonGo-Bot#3073]
Guys, i let the bot working all night while i was sleeping and now when i woke up this happened. Is this IP ban or it will be easy to fix it? :)
Thank's for answering.

![14017924_1288172681206333_1446235627_n](https://cloud.githubusercontent.com/assets/20925417/17615737/6a7c7842-6070-11e6-9646-00fbac9e7f42.png)

**Comment by monchen** [comment]
try delete your app. then re-install.

**Comment by beexyooj420** [comment]
Maybe you should clear data resign in?off location too

**Comment by Elvete** [comment]
Resolve : https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by ripharambe** [comment]
Maybe it's because of server's down, we will se but thank's

**Comment by Georgiexoh** [comment]
I have the exact same issue, so its confirmed not a permanent ban, just unstable servers?

**Comment by Elvete** [comment]
#3074
