### ISSUE TITLE
Another type of softban?

### ISSUE THREAD

**Issue by cirnolp** [Ar1i/PokemonGo-Bot#3075]
I got the standard thingy which happens when you're softbanned: Pokestops dont give me any items (but they're shown).
But the funny thing is, that I still can **catch** encounters. Just no items from Pokestops.
![unbenannt](https://cloud.githubusercontent.com/assets/20665850/17616036/7d656ac0-6072-11e6-8cc7-3c3daebe0883.PNG)

**Comment by Elvete** [comment]
ressolve: https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by alleyezonme420** [comment]
Did it unbanned you after or not if it did no point..

**Comment by cirnolp** [comment]
It didnt unbanned me, still no items and xp from Pokestops, but encounters.

**Comment by alleyezonme420** [comment]
Still able to catch it

**Comment by cirnolp** [comment]
@alleyezonme420 As you can see in the log, yea.

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by alleyezonme420** [comment]
It doesnt show anything after softban.? Only b4 u got softban.?

**Comment by cirnolp** [comment]
The site you gave to me said, that the US servers are down. I'm currently on dutch servers (hollidays).

**Comment by Elvete** [comment]
https://www.youtube.com/watch?v=vfc42Pb5RA8 resolve guys its not permaban

**Comment by Siriondiil** [comment]
Perhaps IP banned, reboot your router

**Comment by cirnolp** [comment]
Already thought about an ip ban, but then why can I still catch pokemon?
Already stopped the bot and waiting a bit till the IP Ban runs out because my internet provider here dont have dynamic ip adresses. (Public VPN's are already overused)

**Comment by alleyezonme420** [comment]
Ip ban would show no poke shop between ###?

**Comment by rvonz** [comment]
i play pokemon go everyday, i lay pokemon go....

**Comment by gummyruler** [comment]
Or maybe bud you're traveling at the speed of light?

**Comment by cirnolp** [comment]
Traveling speed is 57 km/h tho

**Comment by Siriondiil** [comment]
Yup sir, Ip ban is a soft ban on your ip so you can't see the pokéstops

**Comment by alleyezonme420** [comment]
Did u let the special 1337 unban methdo load or close right after u saw that?

**Comment by cirnolp** [comment]
That was like the 10th time it was doing that "special method".

**Comment by Elvete** [comment]
is perma guys..thats lie  ,...https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by alleyezonme420** [comment]
10 times? I only see one time and no log after server issue no ban.

**Comment by cirnolp** [comment]
Elvete, get out of here if you can't help.

Another screenshot after I restarted the bot. Still the same issue.
![unbenannt](https://cloud.githubusercontent.com/assets/20665850/17616710/4c83cf56-6076-11e6-95ec-6888fa0c6df6.PNG)

**Comment by thomatbu** [comment]
I think the problem is your walking speed and distance. Try reducing them.

**Comment by cirnolp** [comment]
Then, why was it working before for hours?
But I gonna try that.

**Comment by Elvete** [comment]
then go king read my psot..belive em u will see it.. looka t this guide or legendary pokemon 1st https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by Elvete** [comment]
#3074

**Comment by cirnolp** [comment]
After setting the travel speed to 24km/h, which should be slow enough, still the same issue.
![unbenannt](https://cloud.githubusercontent.com/assets/20665850/17616955/9b2ff3b8-6077-11e6-930e-b2ecc74a9fa9.PNG)

~~Btw: The Game servers here in the Nederlands are still up, so it can't be a connection problem.~~
Ignore that, the servers are on high ping here for about 2hrs, maybe it's a connection problem.

**Comment by Elvete** [comment]
Reamthat king #3074  its a sotban change or sure

**Comment by alleyezonme420** [comment]
Regional unstable probly turn off try again if stsble

**Comment by gummyruler** [comment]
Force unban is patched.

**Comment by Ar1i** [comment]
^

**Comment by zragon** [comment]
Yeah... i got Exactly the same issue... All PokeStops have the error 'Please try again later'. Again, mentioned ALL POKESTOPS. But, i still can catch pokemons.... but right now, i already used up ALL my pokeballs... the remaining is only Great Ball and Ultra Ball though.
