### ISSUE TITLE
NEW TIPE OF BAN ?

### ISSUE THREAD

**Issue by toroageito** [Ar1i/PokemonGo-Bot#3076]
All may account cannot catch any pokemon with 100% possibility
here the screen shoot
![untitled](https://cloud.githubusercontent.com/assets/20931857/17616153/12918230-609d-11e6-8ae2-5720bb3b4460.jpg)

**Comment by Kidnub** [comment]
get some pokeballs and all is fine XD

**Comment by L00N1** [comment]
close plz and read other threads

**Comment by elenex23** [comment]
seriously how blind can you be

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by Elvete** [comment]
https://www.youtube.com/watch?v=vfc42Pb5RA8 resolve it worked for me
