### ISSUE TITLE
Update on #3069 - Permanent ban is real, Bot and spoofers*

### ISSUE THREAD

**Issue by james741** [Ar1i/PokemonGo-Bot#3077]
Update: Not sure if this a new way of getting solf-ban or not. Going to wait out. Update u guys asap if i find anything new.

**Comment by alleyezonme420** [comment]
Umm..screenshot?

**Comment by Kaluminatie** [comment]
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by james741** [comment]
@alleyezonme420  #3069

**Comment by gummyruler** [comment]
PTC is up bot is running.

![no problemo](https://cloud.githubusercontent.com/assets/20757587/17616323/2ec6335e-6031-11e6-86f0-47fb0f9b069a.png)

**Comment by james741** [comment]
@gummyruler you not helping no one say bot is down...

**Comment by thomatbu** [comment]
I can't catch pokemons anymore, only pokestops and gyms work. What's happening? New ban?

**Comment by Elvete** [comment]
I CANT BELIVE IT https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by testo4life** [comment]
started nox fine on my second main cant login seem like perma ban !

**Comment by PokemonAddict** [comment]
@Elvete Stop spamming

**Comment by Elvete** [comment]
Dont u like the tutorial or what?

**Comment by mezo91** [comment]
thanks for the video, it changed my life.

**Comment by gummyruler** [comment]
@james741 Bot is up that means your accounts might just be having some regional issues. Especially if you're logging in from your phone.

**Comment by Kidnub** [comment]
@Elvete just stop spamming XD and all this topics of ban are non sens cause the server are just unstable XD

**Comment by xuban** [comment]
Close this useless thread.

**Comment by theo2904** [comment]
Alle pokemons seem to escape for me. No idea why. I have unbanned myself. Could anyone help me?

**Comment by mase2015** [comment]
@theo2904 hast du normale pokebälle auf 0 stehen?

**Comment by Elvete** [comment]
@theo2904  look here https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by mase2015** [comment]
@Elvete :-D i click every time... :-D

**Comment by xuban** [comment]
@theo2904 wait one hour to play and if u can restart ip.

**Comment by Elvete** [comment]
Thats my boy

**Comment by Kidnub** [comment]
lol das ding hat knapp 4million clicks XD
any one can close this non sens issue ?

**Comment by mase2015** [comment]
@theo2904 do you have normal pokeballs set to 0? that was my mistake.

**Comment by Kidnub** [comment]
http://ispokemongodownornot.com to check server status of PTC/google acc XD

**Comment by elffish** [comment]
@gummyruler Is the egg hatching working? Do we have to click manually to hatch every time?

**Comment by theo2904** [comment]
Thanks guys! Now i catch 'more' pokemons atleast haha. Still havng trouble catching caterpie :P :100:

**Comment by Georgiexoh** [comment]
![server down](https://cloud.githubusercontent.com/assets/20882361/17617126/a3863c90-60bb-11e6-9104-92316f81b0cc.jpg)

**Comment by NagaCS** [comment]
I've had mine running all day, no issues spinning stops or catching anything and ive jumped locations a bit

**Comment by rvonz** [comment]
its work fine
![kancol](https://cloud.githubusercontent.com/assets/20837463/17617393/1d7ad3d4-60a4-11e6-9fb8-2fccafeb5231.png)

**Comment by elenex23** [comment]
@rvonz Were you new softbanned and now it is working fine? Or you never got the new softban? My ptc account is running fine but I am looking for someone who got the new softban on a google account and is now working fine.

**Comment by Zykhatslover** [comment]
You'll get permaban soon guys, better stop botting right now :p

**Comment by elenex23** [comment]
@zykhatslover lvl 40 or bust bro

**Comment by rvonz** [comment]
@elenex23 i never got the softban

**Comment by elenex23** [comment]
I just accidently sniped using my ptc account that is currently botting, and the bot instantly cannot catch anymore pokemon. fml.

**Comment by Ar1i** [comment]
#3074 http://www.mmoserverstatus.com/pokemon_go
