### ISSUE TITLE
System.NullReferenceException 

### ISSUE THREAD

**Issue by kikado** [Ar1i/PokemonGo-Bot#3079]
![system nullreferenceexception](https://cloud.githubusercontent.com/assets/20841440/17616919/5804fdcc-6077-11e6-9c9f-0e7af4493217.jpg)

![settings](https://cloud.githubusercontent.com/assets/20841440/17616995/cb51e09c-6077-11e6-9844-d5c0c445a0eb.jpg)

**Comment by Elvete** [comment]
#3074

**Comment by webdevzde** [comment]
I had this error because my ptc account was not verified with an email. But it could be a softban as well.
