### ISSUE TITLE
Transfer Features, Lucky Egg Options and More!

### ISSUE THREAD

**Issue by MrVSATs** [Ar1i/PokemonGo-Bot#308]
The automatically Transfer opinion doesnt work for me could you add something like a button where u can click and it will transfer all under the CP u typed in. Also u have the opinion to use incense every 30min can u also add the opinion for a Lucky Egg ? theres is only one but for Evolve. And a Filter in the Pokemon Inventory would be very useful like u can search for Pinser and u can only see the Pinser and can Transfer them easily would be very awesome Options.

Anyways Keep up the good work at the Bot and the Daily Updates. Awesome!

**Comment by Ar1i** [comment]
already posted
