### ISSUE TITLE
No farm 

### ISSUE THREAD

**Issue by Recopak** [Ar1i/PokemonGo-Bot#3081]
I cant catch anything.
:(
![adsiz](https://cloud.githubusercontent.com/assets/20833776/17617402/a5f1a868-6082-11e6-90b3-56e6c827a4b9.jpg)

**Comment by Elvete** [comment]
#3074

**Comment by Rolandian** [comment]
same issue here, I can't farm any pokestop nor catch anything

**Comment by Ar1i** [comment]
#3074 http://www.mmoserverstatus.com/pokemon_go
