### ISSUE TITLE
iOS Device IDs possible?

### ISSUE THREAD

**Issue by SebiWolze** [Ar1i/PokemonGo-Bot#3082]
Hi @Ar1i just wanted to know, if its possible to add also iOS Device IDs?

**Comment by Georgiexoh** [comment]
What are those?

**Comment by kikado** [comment]
![settings](https://cloud.githubusercontent.com/assets/20841440/17617635/7bc58822-607b-11e6-9c81-8c1fb60630d3.jpg)

@Georgiexoh

**Comment by Georgiexoh** [comment]
Thank you

**Comment by Ar1i** [comment]
Not needed atm, its just that not every user uses the same device
