### ISSUE TITLE
Soft Banned?

### ISSUE THREAD

**Issue by LazeBear** [Ar1i/PokemonGo-Bot#3083]
I used NOX to login, an hour ago, it says 'GPS SIGNAL NOT FOUND', and it's all blank, can't move anywhere.
minutes ago, I can login, can catch pokemon, but the pokestop is black(the spin part), and when i spin it, it says 'Try again later'.
Haven't tried bot though
Do I get soft banned or it's NOX's problem?

**Comment by Georgiexoh** [comment]
At least you can log in man

**Comment by bboylost** [comment]
yea i got the same problem maybe.  suddenly my character is soft banned, but I tried spinning the pokeshop 40 times. actually 80 times, and I am still banned, pokemon go away . i dont know what is this going on

**Comment by LazeBear** [comment]
weird thing is, I can catch pokemon, but can't spin stops

**Comment by bboylost** [comment]
then we are different, u are fine, just server is lagging on the pokeshops, as soon as u can catch pokemon nothing u need to worry

**Comment by volturi04** [comment]
really permanent ban?? :(

**Comment by Ar1i** [comment]
#3074 http://www.mmoserverstatus.com/pokemon_go

**Comment by daniel2keer** [comment]
i can logg in find pokestops but any pokemon i try to catch run away im i banned or just server down?
