### ISSUE TITLE
REQUEST - inklude MAP 

### ISSUE THREAD

**Issue by marion808** [Ar1i/PokemonGo-Bot#3084]
Hey,it would be e good thing to inklude map in bot to see who you walking!

**Comment by creiner** [comment]
Its included, just go to the pokemon list and click on: 
![image](https://cloud.githubusercontent.com/assets/137896/17617714/e8bd8312-607b-11e6-9cbd-72bfce7d110e.png)

**Comment by lsarmiento** [comment]
We already have this feature;

![image](https://cloud.githubusercontent.com/assets/20063148/17617723/438800ce-60ae-11e6-8c38-2be9047c470a.png)
