### ISSUE TITLE
Is this Niantic site new / request for removing ban

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#3085]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

**Comment by Elvete** [comment]
whats that? ur account or what?

**Comment by lsarmiento** [comment]
Never use that "form" when removing ban from your account. we have our own way.

**Comment by xuban** [comment]
Dont send this form!!
The servers has problem.

**Comment by lailaps** [comment]
Lol, just asking if this is new, because if so they would have something like perma ban.
lsarmiento... atm we do not have a way to remove this new kind of ban...
xuban... only in some countries, Niantic is using a new kind of maybe softban!
Read a bit more before posting something like this!

**Comment by xuban** [comment]
@lailaps softban is one thing, and the login/servers problems is other.
Now the servers has problems. 
Please, CHECK before posting trolling threads. http://www.mmoserverstatus.com/pokemon_go

**Comment by lailaps** [comment]
@xuban
Go to bed son, when you wake up, even you will understand.

**Comment by xuban** [comment]
Like you have a problem reading comprehension.
I've already said that one thing is a softban and what happens to other servers. Here you put your link to a form which can lead to a person really be permanently banned for notifying that has been (for example) spoof the location.

By the way, I with my Spanish has not been able to connect from 6 hours and with Asia has been the bot on until 20 minutes ago smoothly. Both with google.
Be smart and think before writing and alarm people with a form that has been there from the first day of the game.

Quiet, I do not need to call or send you child to sleep. I only need to use your head to think before inciting people to make mistakes.

**Comment by lailaps** [comment]
It was a question of mine if it is new, never told someone to use it for contacting Niantic, lol.
You still to awake, son...
