### ISSUE TITLE
PLEASE HELP!BAN?!

### ISSUE THREAD

**Issue by b1ll3** [Ar1i/PokemonGo-Bot#3087]
Please help getting this error...i used bot sensibly without skipping locations...i hope there is a solution to this. Thanks!
![error](https://cloud.githubusercontent.com/assets/20987643/17618102/77f24012-609b-11e6-9696-5eaf56676ee8.jpg)

**Comment by Elvete** [comment]
#3074  http://www.mmoserverstatus.com/pokemon_go

**Comment by Ar1i** [comment]
thanks for helping @Elvete your doing a great job!
