### ISSUE TITLE
Where I can find System.Data.hashFunction.Interfaces

### ISSUE THREAD

**Issue by lsarmiento** [Ar1i/PokemonGo-Bot#3088]
How to reference this assembly?
![image](https://cloud.githubusercontent.com/assets/20063148/17618192/da43fbec-60b0-11e6-82cd-95c76a9b3bd8.png)

**Comment by Ar1i** [comment]
Use nuget:
Install-Package System.Data.HashFunction.Interfaces

**Comment by lsarmiento** [comment]
Thanks
