### ISSUE TITLE
Bug server

### ISSUE THREAD

**Issue by TheGarmer72** [Ar1i/PokemonGo-Bot#309]
Hello, 

Thanks your bot is really great but now i can't connect to server : 
![capture](https://cloud.githubusercontent.com/assets/20732643/17265783/409a3d44-55f2-11e6-995d-82ce7731ddcf.PNG)

Can you help me please ?.... 

Thanks

**Comment by TheSmartly** [comment]
Setp 1: Wait
Step 2: Try Again

Repeat until it works

**Comment by TheGarmer72** [comment]
Ok I try this in 1 hour ;)

**Comment by inurbad** [comment]
should've gone with the gmail =P

**Comment by Tochez** [comment]
ptc servers are usually trash. its true u should of went with gmail.
