### ISSUE TITLE
Error (GER)

### ISSUE THREAD

**Issue by PCKGOHCKTEAM** [Ar1i/PokemonGo-Bot#3090]
Der Objektverweis wurde nicht auf eine Objektinstantz festgelegt?

Weis wer was darüber?

**Comment by ShaaiLo** [comment]
Permaban

**Comment by Mehmetabi** [comment]
gibts schon was offizielles oder ist das ne vermutung von dir @ShaaiLo

**Comment by Siphernom** [comment]
Habe das selbe Problem, liegt das nicht daran dass die Server down sind?

**Comment by Mehmetabi** [comment]
wenn ich micht mit meinem anderen account einloggen will, der nie gebottet hat, dann funzt alles super.

daher glaube ich, dass tatsächlich accounts gebannt werden.

**Comment by ShaaiLo** [comment]
Ist erstmal eine Vermutung. Es liegt nicht daran das die Server Down sind !
ich habe 3 Acc's die mit Google verbunden sind. Mit 2 Accounts kann ich mich problemlos einloggen. und der 3. Accounnt mit dem ich gebottet habe, komme ich nicht rein und da steht " Spieldaten konnten nicht vom Server abgerufen werden. " und mein bot sagt wie oben "Der Objektverweis wurde nicht auf eine Objektinstantz festgelegt"

**Comment by RJX9** [comment]
Ich habe gerade nur wieder einmal das PokeStop Problem, gebannt bin ich aber nicht

**Comment by PCKGOHCKTEAM** [comment]
Vielleicht weiß ja @Ar1i  was darüber :+1:

**Comment by Ar1i** [comment]
Abwarten..

**Comment by LuckyBoy1101** [comment]
mach dir ne neue ip

**Comment by PCKGOHCKTEAM** [comment]
@LuckyBoy1101 haben wir bereits.

**Comment by LuckyBoy1101** [comment]
also starte den router neu habe des problem au schon öfters gehabt

**Comment by LuckyBoy1101** [comment]
scheiße 
also wird des bei mir jetzt au nix mehr bringen?
da meine accounts au geblockt sind

**Comment by LuckyBoy1101** [comment]
bis jetzt wars ja so dass du nur dann gebannt wurdest wenn du 3 mal das land gewechselt hast oder du 2 hackbots über die selbe ip hast laufen lassen
