### ISSUE TITLE
Antivirus problem :(

### ISSUE THREAD

**Issue by LaMut** [Ar1i/PokemonGo-Bot#3091]
Since the last version, i cant open the bot at work, my Officescan detects something wrong.
Yesterday, it used to work well.
Do you know why its going wrong today?

Ty <3

**Comment by AlpaEZPZ** [comment]
U opened a bot at ur work desk ?
are u serious... ?

**Comment by AlpaEZPZ** [comment]
at least ur antivirus is doing its job by locking out untrusted software...

**Comment by LaMut** [comment]
yeah i know ^^
Just saying that yesterday it didnt block anything :p

**Comment by AlpaEZPZ** [comment]
men never take a untrusted software into the network u are working with,
this time its just a bot, next time its a bot with some maleware.
just an advice...

**Comment by LaMut** [comment]
ok ty mate :)

You can close the topic, sorry ;)
