### ISSUE TITLE
Translation - German - Pokemon Tab

### ISSUE THREAD

**Issue by M1503** [Ar1i/PokemonGo-Bot#3097]
The Tab Translation for Pokemon to envolve (or to NOT envolve??) is telling different in eng and german.
But in german it runs out of field, too!

![image](https://cloud.githubusercontent.com/assets/20988129/17618937/c161e716-6082-11e6-9aa0-016f371bcd48.png)

**Comment by CruSherFL** [comment]
Sollte mit der aktuellen Version behoben sein.
