### ISSUE TITLE
The bot is disabled, until we found out why Bans are happening.

### ISSUE THREAD

**Issue by obzc** [Ar1i/PokemonGo-Bot#3098]
The bot is disabled, until we found out why Bans are happening.
![image](https://cloud.githubusercontent.com/assets/5241625/17619025/8acfdd76-608b-11e6-951e-0b7974dd0929.png)

**Comment by lucas2107** [comment]
Now, go out and play without bot :)

**Comment by HELLspawnTIM** [comment]
@obzc 
OMG YOU CAN READ !!!
You are a fucking GENIUS !!!

**Comment by Ar1i** [comment]
+1

**Comment by bboylost** [comment]
@lucas2107 the thing is my accounts are already "soft banned" and cant use the pokeshop 40 times spin method to un ban too hahahah

**Comment by melody09341** [comment]
![image](https://cloud.githubusercontent.com/assets/20904752/17619081/c09e0ff2-60b5-11e6-9822-7bb67a85dd1b.jpeg)
after lv30 they banned my 3 accounts

**Comment by GHANT** [comment]
You're not supposed to use 3 accounts per IP address..

**Comment by bboylost** [comment]
@GHANT well , i know that , to be exact it is 1 account per IP address.  what I am saying is my accounts were soft banned one after one

**Comment by GHANT** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/15823731/17619264/30c77f8e-6052-11e6-8409-d184ce157a86.jpg)

My game isn't showing any pokestops. I'm in central park on nox player.

**Comment by melody09341** [comment]
btw  1st account i didn't log in for 2 days. At this mornning i log in then auto banned    2nd account  i didn't log in 1 day and auto banned again   3rd ac after i turn off bot auto banned
i am not using 3 bots at same time   they are catching over lv30 ppl  .  　My friends lower than 28 were not banned

**Comment by GHANT** [comment]
I was afraid they would think of this idea... too bad it took them a month to implement it.

**Comment by melody09341** [comment]
from hong kong taiwan japan they are catching over lv30 ppl  
So tonight i need to restart bot again😏😏😏
