### ISSUE TITLE
WISH: Save Window Size and Position for next start

### ISSUE THREAD

**Issue by M1503** [Ar1i/PokemonGo-Bot#3099]
I would like to ask you to save the last set window size and position.
So that at the next start the windows fill the screen like users wish.

Ich würde gerne darum bitten, die Fenstergröße und -Position zu speichern, so dass man beim Neustart die selben Positionen hat, und nicht immer alles wieder neu anpassen muss. Das wäre echt toll.

Dies ist außerdem mein dritter Vorschlag und ich möchte mich hiermit für die tolle Arbeit bedanken und darauf hinweisen, dass meine Eingaben als Feedback und nicht als Nörgelei gedacht sind. Ich möchte nur helfen, euer tolles Projekt zu verbessern und euch an dieser Stelle loben! Super Sache das!

**Comment by WhoBotWhoBad** [comment]
You can do that easily.
1. Right click on the pokemon ball in yung bot window and choose Properties
2. Position your window wherever you desire and resize window.
3. Uncheck the "Let system position window"
4. OK.

The next time you run your bot it will remember your window position and size. Win10 here.

My pleasure!
