### ISSUE TITLE
Fix crash if you view more pokemons than you have with /top

### ISSUE THREAD

**Issue by Blu3scReeN** [Ar1i/PokemonGo-Bot#31]
Change the /top part in TelegramUtil.cs to something like this. This is how i fixed it.
http://pastebin.com/ZU1NQD8P

if you type for example /top 300 the bot will crash, this snippet will fix it and yes, the count in the foreach is not that good.

**Comment by Ar1i** [comment]
Should be fixed, with the current Update. If not Open a new Issue. Thanks!
