### ISSUE TITLE
Bot is DISABLED ?

### ISSUE THREAD

**Issue by Abbasoo** [Ar1i/PokemonGo-Bot#3100]
![untitled](https://cloud.githubusercontent.com/assets/20796710/17619117/05b707c6-608c-11e6-9779-310f64d56509.png)

**Comment by RJX9** [comment]
Yes...

**Comment by joy0824** [comment]
told you there is a special ban going on, mine affect. go ahead and bot if u feel like getting some risk. mine IS BANNED until now cannot get any pokemon and nonsense 40 spin on same pokestop won't work

**Comment by Ar1i** [comment]
#3074

**Comment by lucas2107** [comment]
Use old version if you want to be banned, we don't know what bans are happening.

**Comment by Kidnub** [comment]
nonon idid only unban with the old version fast my one account and now i ll stop it untill all is fine again . thx Arli and the other dev for the fast bot killswitch XD
