### ISSUE TITLE
Bot is Disabled !!!!!!!!!!!!

### ISSUE THREAD

**Issue by emreaslantas** [Ar1i/PokemonGo-Bot#3102]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by b1ll3** [comment]
#3074

**Comment by lucas2107** [comment]
@Ar1i

**Comment by joy0824** [comment]
I THINK THERE IS SPY FROM POKEMON COMPANY! make this community secret!

**Comment by joy0824** [comment]
%@%@#@$^@$ YOU SPY
