### ISSUE TITLE
Is this permanent BAN ? 

### ISSUE THREAD

**Issue by w3njember** [Ar1i/PokemonGo-Bot#3105]
![screenshot_2016-08-12-17-00-25](https://cloud.githubusercontent.com/assets/20972192/17619296/93ba2676-60ae-11e6-8014-a11bf403c184.png)

Is that permanent BAN ? 

Tried to log in via bot can not connect 
Then tried to login via Mobile Phone it say failed to get game data

**Comment by b1ll3** [comment]
#3074 @Ar1i

**Comment by shahroozal** [comment]
Servers are having problem.

**Comment by Georgiexoh** [comment]
I get the same thing, I hope server is having issues, but other people in my country can log in..

**Comment by momo0206** [comment]
Cant see Pokestops and Arenas. PermaBan? what can i do ?

**Comment by joy0824** [comment]
its new ban for sure. just create new account and login u'll find out new account have no problems, just stop botting for now. wait further update to either forever stop botting or there will be solution.

**Comment by b1ll3** [comment]
@momo0206 @Georgiexoh #3074

**Comment by GHANT** [comment]
I don't want to stop botting.. I wanted lvl 40. I'm level 36... so close...

**Comment by GHANT** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/15823731/17619410/49c85390-6053-11e6-9964-bce76d323f31.jpg)

I can log in, but there are no pokestops or poke sightings..
