### ISSUE TITLE
Microsoft.NET Framework Problem at starting 

### ISSUE THREAD

**Issue by RickPatx** [Ar1i/PokemonGo-Bot#3107]
![unbenannt](https://cloud.githubusercontent.com/assets/20988625/17619559/530f14c4-6086-11e6-9999-02dac80afb75.JPG)

Get this window every time i want to start the Bot.

if i press continue (weiter), the GUI comes up but all my data are deleted(location, username. ..) and i cant select Google or PG Trainer Club and something like that

**Comment by akangnduz** [comment]
delete inside translation folder

**Comment by RickPatx** [comment]
Thanks mate
