### ISSUE TITLE
Cant use pokestop  try again rater

### ISSUE THREAD

**Issue by thearmelly** [Ar1i/PokemonGo-Bot#3108]
How to fix it plz

**Comment by tainhx** [comment]
Wait from author....

**Comment by thearmelly** [comment]
How about your account get ban or not ?

**Comment by tainhx** [comment]
Not found any pokestops around 3000m.....

**Comment by GHANT** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/15823731/17619744/67078366-6055-11e6-84d7-529e25c3a8bb.jpg)

**Comment by blasanru** [comment]
#3074

**Comment by gottahub** [comment]
![working](https://cloud.githubusercontent.com/assets/20944255/17619796/f1b12ca4-60b1-11e6-9812-7da5562889b2.JPG)

still working from Latest Build - 12.08 10.59
i hope my ID not banned

**Comment by Experte9** [comment]
Servaer are down atm (http://www.mmoserverstatus.com/pokemon_go)
