### ISSUE TITLE
why this problem?

### ISSUE THREAD

**Issue by blade90** [Ar1i/PokemonGo-Bot#3109]
![immagine](https://cloud.githubusercontent.com/assets/20888636/17619768/cbd36120-6087-11e6-965c-86289765199d.jpg)
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Waiiim** [comment]
Just happened to me too
I guess to answer your question, read what is written in red..

**Comment by GHANT** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/15823731/17619789/acab81ec-6055-11e6-8ee2-4e1f9a7aa83e.jpg)

Try reading the text.

**Comment by thearmelly** [comment]
Ohh level 36 Got ban so sad time

**Comment by sysandrew** [comment]
perma ban is here...

**Comment by astrostra** [comment]
@GHANT this is the new softban method, it's an iP ban, try and connect yourself on another network such as a public wifi or LTE. 

@sysandrew Permaban hasn't and won't be confirmed yet, so the answer is no.

**Comment by Waiiim** [comment]
@astrostra it's not just a simple IP ban, otherwise Ar1i wouldn't close the bot to find a way out of it

**Comment by blade90** [comment]
when you will solve this ban ?

**Comment by Doberok** [comment]
This ban on IP, LTE you turn on your phone and it works

**Comment by blade90** [comment]
ok but the bot will be back online in the next few days or not?

**Comment by Experte9** [comment]
#3074

**Comment by Ar1i** [comment]
#3074
