### ISSUE TITLE
ช่วยที่คับ คนไทย บอทตัวใหม่ กดแล้ว Enter แล้วดับไม

### ISSUE THREAD

**Issue by tung7227** [Ar1i/PokemonGo-Bot#3110]
เป็นเหมือนกันไม ช่วยบอกที

**Comment by wuttiwong01** [comment]
มีปัญหาการแบนอยู่ครับ เลยปิดบอทชั่วคราว เพื่อหาวีธีแก้ไข

**Comment by wuttiwong01** [comment]
ถ้าอยากบอท ก็ใช้ตัวเก่าไปก่อนคับ ใช้ได้อยู่ แต่ระวังโดนแบนหน่อย

**Comment by thearmelly** [comment]
อาการเดียวกันสินะครับ

**Comment by thearmelly** [comment]
ตอนนี้ เลเวว 29 ผมมีปัญหา ตรงที่ หมุน เสาไม่ได้ แต่จับโปเกมอ่นได้

**Comment by tung7227** [comment]
ขอบคุณคับ คงช่ายเวอซันเก่าไปก่อนเนนาะ

**Comment by tung7227** [comment]
หมุนเสาไม่ได้ เพราะกระเป๋าเต็มป่ะคับ

**Comment by thearmelly** [comment]
ไม่ครับมันขึ้น Try again rater

.

**Comment by thearmelly** [comment]
ปวดใจแท้

**Comment by wuttiwong01** [comment]
ช่วงนี้รู้สึกคนถูกแบนบ่อยมาก

**Comment by tung7227** [comment]
ผมโดนแบน ภาวร ไปหนึ่งไอดีคับ แสบมาก ไอดีหลักด้วย

**Comment by nismotue1** [comment]
error pokestop มันหาเสาไม่เจอ เจอแต่ทุ่ง รอเขาแก้ก่อน

**Comment by nismotue1** [comment]
ผมไม่แน่ใจว่าแบนถาวรเป็นยั

**Comment by tung7227** [comment]
บอทแถวไหนได้ ไคริว คับ เห็นเพื่อน ได้มา cp3000

**Comment by nismotue1** [comment]
ผมไม่แน่ใจว่าแบนถาวรเป็นยังไง แต่ไอดีนึงผมติ่ด faile to game data อ่ะไรนีแหล่ะ ค้างหน้าโหลดเข้าไม่ได้เลย

**Comment by wuttiwong01** [comment]
ผมโดนแบน ip บ่อยมาก

**Comment by dewtheking** [comment]
ของผมขึ้น detected a softban. trying to ues our special 1337 unban methode
แต่หมุนเสาได้ครับ โดน softban ย้ายตำแหน่งเกิน 5000M.

**Comment by nismotue1** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/20989325/17620837/5344cfbe-60b9-11e6-801c-b297eb054a3c.jpg)


ไอดีที่2

**Comment by nismotue1** [comment]
ไอดีแรกก็ยังเข้าไม่ได้
![weeee](https://cloud.githubusercontent.com/assets/20989325/17620868/a2be2f4a-60b9-11e6-9a74-8e085703cf37.jpg)

**Comment by tung7227** [comment]
อันนี้ล่ะ โดนแบนถาวร

**Comment by ochinochin** [comment]
ตอนนี้บอทยังใช้ได้อยู่หรอ ?? แล้วใช้ หรือ ตั้งค่า Proxy กันยังไง ผมใช้บอทไม่ได้ตั้งแต่เมื่อวานละ 

 แล้วค้นหา Proxy หรือ ไอพี ตัวใหม่กันยังไง ?? ใช้ ไอพีไหนก็เข้าไม่ได้สักอัน

**Comment by nismotue1** [comment]
นี่ผมลองสร้างไอดีใหม่ แต่ตั้งค่าให้มันเดินช้าๆสัก5km ลองดูจะรอดไหม
![wwww](https://cloud.githubusercontent.com/assets/20989325/17621048/f5a2b95a-60ba-11e6-9d6d-828eb8cbf462.png)

**Comment by wuttiwong01** [comment]
ตอนนี้เวอร์ชั่นปัจจุบันใช้ได้แล้วครับ

**Comment by ochinochin** [comment]
ตรงช่องที่ให้ใส่ ip  กับ Proxy port  ต้องใส่อะไรอะ เคยลองใส่แล้วก็ไม่เห็นจะเข้าได้ ??

 อยากรู้วิธีหาไอพีใหม่ ๆ แล้ว การใส่ไอพี อะ เราใส่ไม่ได้เลย

**Comment by ochinochin** [comment]
อยากเห็นการตั้งค่าของคนที่ใช้ได้จัง เขาตั้งค่ากันยังไงนะ 555 ^^

**Comment by ochinochin** [comment]
ลองยังไง ก็ขึ้นแบบนี้ตลอดเลยอะ 

![123](https://cloud.githubusercontent.com/assets/20947976/17621259/2e97d956-60bc-11e6-9a64-62996b07edf3.png)

**Comment by wuttiwong01** [comment]
หา Proxy จากนี้เลยครับ
http://proxylist.hidemyass.com/search-1297445#listable
http://www.freeproxylists.net/
https://incloak.com/proxy-list/

หรือไม่ก้ใช้โปรแกรมเปลี่ยน ip เอาครับ 
SoftEther VPN Client Manager

**Comment by nismotue1** [comment]
อันนี้คอนฟิคผมนะ ไม่ได้ใช้proxy  ลองสร้างไอดีใหม่มาลีอคดู gmailกะptcอย่าลืมเปลี่ยนนะ
![qqqqq](https://cloud.githubusercontent.com/assets/20989325/17621333/cd0577c4-60bc-11e6-9621-a16483e636bf.jpg)

**Comment by dewtheking** [comment]
มีเคล็ดลับเปลี่ยนตำแหน่งไหมครับ พอดีเปลี่ยนตำแหน่งที มันตรวจเจอ โดน softban ตลอด

**Comment by nismotue1** [comment]
ผมว่าที่โดนแบนกันเพราะเราสั่งให้มันเดินเร็วเกินไป สั่งเกตุข้อความในบอทมันจะเตือนslowing down -10km/h ตลอด เวลาเราตั้งเกิน10 ลองปรับเหลือสัก4-5 แล้ววาปไปลงจุดที่pokestopเยอะๆเช่น สยามพารากอน จตุจัก เดินช้าๆไล่เก็บเนียนๆ โอกาสโดนน้อย Tip.อย่าเปิดปิดบอทบ่อยจะทำให้โดนแบนได้ง่ายๆถ้าพิกัดที่เรายืนกับพิกัดที่จะบอทอยุ่ไกลหลายกิโล ส่วนรัศมีตั้งสัก1000ก็พอแล้วให้มันวนอยุ่แต่แถวนั้น

**Comment by nismotue1** [comment]
อย่าให้บอทเดินลงไปในคลองนะ มันผิดวิสัย โดนแบนได้เหมือนกัน ตั้งรัศมีแคบๆ

**Comment by dewtheking** [comment]
จับที่ไหนกันบ้างครับ ม่อนไคริวเขาจับที่ไหนกัน ผมปล่อยทิ้งไว้ที่นิวยอก แต่เวลาจะเลื่อนตำแหน่งเข้าไทยมันลำบากหน่อย

**Comment by AdamFYan** [comment]
just copy+ paste ขอบคุณคับ คงช่ายเวอซันเก่าไปก่อนเนนาะ
