### ISSUE TITLE
Fake Gps is also banned ?

### ISSUE THREAD

**Issue by Cagatay342** [Ar1i/PokemonGo-Bot#3111]
After bot was banned , i opened nox and it was working but in 5 min it was banned (try again later for all pokestops . restarted game and there was nothing on map). And i thought it was ip banned and i changed ip then it worked after 5 min it was banned again. can a few of you test it too ?

**Comment by sergrusur** [comment]
same here

**Comment by zzzz9999** [comment]
official servers are having issues
#3112

**Comment by Cagatay342** [comment]
But at first it works i dont think its bcuz of servers.it seems they see illegal using from gps

**Comment by malekisma** [comment]
How I Change my IP?

**Comment by Cagatay342** [comment]
if you dont use static ip restart your modem

**Comment by malekisma** [comment]
ok thank you i will try it

**Comment by malekisma** [comment]
@Cagatay342  I restart my modem but the bot says again he will close :(

**Comment by Cagatay342** [comment]
No i dont mean bot.bot will say same thing until ar1i team solve it.i talk about nox app player

**Comment by fourmansyah** [comment]
if u use emu .. just change Your EMI and your Phone Series .. It will fix it

**Comment by malekisma** [comment]
i use only bot and flyGps

**Comment by fourmansyah** [comment]
i use ip great britain .. and i use ELITE Proxy.. nad i open 5 BOT ... and it work for 5 hours notting get banned .. but i focus the ELITE proxy To Bot .. And all of the bot use Different IP>

**Comment by Experte9** [comment]
#3074

**Comment by Ar1i** [comment]
#3074
