### ISSUE TITLE
Pokemon Go Server STATUS

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#3112]
![serverstatus](https://cloud.githubusercontent.com/assets/20603254/17619992/c782bd50-6091-11e6-987c-4fbfe14ec089.png)

**Comment by pokerave** [comment]
![bye accounts](https://cloud.githubusercontent.com/assets/20603254/17620082/699c2086-6092-11e6-823c-acb27d90dc2e.png)

**Comment by b3shoy** [comment]
@pokerave WHAT?!! You are not joking right?

**Comment by OhhPian** [comment]
@pokerave how do u check this ?

**Comment by mase2015** [comment]
U can't check this... it's a FAQ site. Do you even read?

**Comment by taimutorabera** [comment]
can't login since hours... 
![screenshot_2016-08-12-13-05-52](https://cloud.githubusercontent.com/assets/11350656/17620628/f0c4d21a-608d-11e6-9afd-a063d9d47ac8.png)

**Comment by Experte9** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by taimutorabera** [comment]
other accounts working?! why?

**Comment by DHBios** [comment]
i have 5 accounts, last time im using bot was when there's only 1 IP for 1 Account rule

and out of my 5 account, my main account was banned, and the other 4 was running fine, when i opened pokemon go from my phone :(

And when i try to login to my main account, it's said that it can't find my gaming data :(

**Comment by Ar1i** [comment]
#3074
