### ISSUE TITLE
Temporary solution.

### ISSUE THREAD

**Issue by hinccvi** [Ar1i/PokemonGo-Bot#3113]
The server is working fine! If you use your current ip address to check the server status, it will clearly show you that server is down. Pokemon go has banned your ip address if you've use any fake gps or bot. Try changing your ip address or use other network, it will work. Iam currently using my cellular network to play pokemon go, tested and working.

**Comment by thearmelly** [comment]
I can catch pokemon and battle in the gym but I cant spun pokestop everywhere

**Comment by guibr321** [comment]
Is 'Force Unban' still working?

**Comment by hinccvi** [comment]
Nope.

**Comment by Experte9** [comment]
Servaer are down atm (http://www.mmoserverstatus.com/pokemon_go)

**Comment by hinccvi** [comment]
![screenshot_20160812-193408](https://cloud.githubusercontent.com/assets/20989063/17621196/3fc623e2-60c4-11e6-8af8-d5b586d7b9d1.png)
Nope nope.

**Comment by Ar1i** [comment]
#3074
