### ISSUE TITLE
STRANGE Pokemon Server Issue Not The Bot! - Stop complaining about permaban!

### ISSUE THREAD

**Issue by WhoBotWhoBad** [Ar1i/PokemonGo-Bot#3114]
This is really strange issue not to the bot but for Pokemon Server.

This is my friends account. In screenshot, the bot says level19. I ask her to login from her phone with GPS off, she said shes still level 5. (She gave her account at level 5) I bot it till level 19.

So I open my emulator and login her account and this is what it came in. Create new account with the same account shes using right not at level 5 at in my bot its level 19.

Her Phone = Level 5
My Bot = Level 19
My Emulator = Level 1 (create new account)

All of them under the same account!

![strange](https://cloud.githubusercontent.com/assets/20833381/17620122/a2c7b1f2-60bc-11e6-8b3a-afad8f972d99.jpg)

**Comment by JJhonh** [comment]
So , After the servers are stabilized everything will be normal again?

**Comment by WhoBotWhoBad** [comment]
It will go back to normal soon. Here is another screenshot of my friend. He havent login from is phone yet, I just check his account in my emulator side-by-side with the bot and its pretty normal.

![strange2](https://cloud.githubusercontent.com/assets/20833381/17620496/4b51fa42-60bf-11e6-8542-b578db10490e.jpg)

**Comment by joy0824** [comment]
i find it amusing =) *chuckles*

**Comment by Experte9** [comment]
#3074

**Comment by IDonated** [comment]
I'm saying like 40 minutes that the very same happened to me yesterday, noone believe me. Panic is strong on this ppl.

**Comment by PokeProgress** [comment]
Someone said they got an email saying they were perm banned.

**Comment by IDonated** [comment]
@PokeProgress proofs or bullshit

**Comment by PokeProgress** [comment]
@IDonated what? it was in the issues section

**Comment by WhoBotWhoBad** [comment]
@PokeProgress  I check their email and no email from NIANTIC. Can you guide us where it was posted. tnx

**Comment by PokeProgress** [comment]
@WhoBotWhoBad https://github.com/PokemonGoF/PokemonGo-Bot/issues/3724 andi checked my email with what everyone is saying with the failed to login and i havnt gotten an email but i can login with my other accounts

**Comment by WhoBotWhoBad** [comment]
@PokeProgress "Someone said" - it has no proof. Also it would be believable if they provide screenshot from their email.

I also experience the same error about "Failed to get game data from the server." on my other account, but how will you explain this issue I posted?

**Comment by WhoBotWhoBad** [comment]
Also, I got this Server Problem message every time I run their account for the first time. I close Pokemon Go and re-open and the problem stays. Same thing to the no issue account. I still get that Server Probem message from first open.

![gino5](https://cloud.githubusercontent.com/assets/20833381/17621675/93529f88-60c7-11e6-858d-155d7b51a73b.jpg)

**Comment by Ar1i** [comment]
#3074

**Comment by allesdrop** [comment]
How do u get the pokemon list thingy?
