### ISSUE TITLE
Can't find any pokestops in a range of 5000!

### ISSUE THREAD

**Issue by Berkthe7urk** [Ar1i/PokemonGo-Bot#3115]
I cannot seem to be activating the bot because it says cannot find pokestops in a range of 5000m. please help! i logged into pokemon go and probably i got soft banned but i am not sure if i got banned or soft banned.  how do i fix this and what is wrong? i clicked on the unban button but still didnt change anything

**Comment by SebiWolze** [comment]
#3074

**Comment by danny77** [comment]
Just wait in one hour jou will get unbaned,

**Comment by Berkthe7urk** [comment]
its a problem with servers or its just me?

**Comment by guibr321** [comment]
Have you got the uploaded versión of the bot?

**Comment by Berkthe7urk** [comment]
what you mean @guibr321  ? i downloaded it

**Comment by Maxpentrator** [comment]
Restart your router

**Comment by Berkthe7urk** [comment]
works again no need to thanks guys @Maxpentrator @guibr321 @danny77

**Comment by Experte9** [comment]
If your problem solved, pls colse issue

**Comment by carlon55** [comment]
berk u nub
I know u in real life
