### ISSUE TITLE
Newest update. Iphone not in device selection.

### ISSUE THREAD

**Issue by Pokehacker163** [Ar1i/PokemonGo-Bot#3116]
After the newest update you have to select wich device you're on. I have got an Iphone 5s and it's not in the selection. Please help and let me know if you have the same problem.

**Comment by 4lex42** [comment]
Yes i have he same problem and i don't know what i do

**Comment by 12348766754** [comment]
Neither is the Xiaomi Mi Note, would be nice if this could be added.

**Comment by Pokehacker163** [comment]
I find it a bit wierd that Iphone wich is one of the biggest phone brand out there isn't an option.

**Comment by rparada1980** [comment]
I also need to select as device "iphone"

Thanks.

**Comment by Pokehacker163** [comment]
It works without selecting a device..
