### ISSUE TITLE
My IP has banned

### ISSUE THREAD

**Issue by MERTCU** [Ar1i/PokemonGo-Bot#3118]
Hello guys!
I have just started to use this application this morning. I left it open when i went to the shops. When i came back, it was not working and apparently I couldn't connect to the Pokemon go with my home wifi ( When i have connected, there was no Pokemon around, no gyms and no PokeStops). However, I m able to play Pokemon go with my cellular data.
What should I do? Thank you for any recommendation

**Comment by 12348766754** [comment]
Wat should I do -> fix a proxy

**Comment by MERTCU** [comment]
What do you think is the problem? Any device connected to my Wifi is not able to play Pokemon Go. Thank you for your answer

**Comment by gottahub** [comment]
turn off your modem and try again

**Comment by guibr321** [comment]
You can try fake your IP. But I think you should just wait a couple of hours more and it should work.

**Comment by MERTCU** [comment]
Thank you both of you guys. I  havent done anything and it has fixed itself. What precautions should I take next time while using the bot?

**Comment by Ar1i** [comment]
#3074
