### ISSUE TITLE
Bot Didnt work since update

### ISSUE THREAD

**Issue by Schob1337** [Ar1i/PokemonGo-Bot#3121]
Es kommt immer diese fehlermeldung:

Error reloading Pokemon list: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

jemand ein plan was da los is? :c

**Comment by LuckyBoy1101** [comment]
bei mir wurde noch kein update angezeigt

**Comment by dhiw** [comment]
bei mir kommt auch: Error reloading Pokemon list: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

**Comment by Experte9** [comment]
#3074

**Comment by cirnolp** [comment]
Die Server sind momentan sehr instabil, wie man hier sehen  kann.
http://www.mmoserverstatus.com/pokemon_go

**Comment by Ar1i** [comment]
#3074
