### ISSUE TITLE
Pokemon get away

### ISSUE THREAD

**Issue by shahroozal** [Ar1i/PokemonGo-Bot#3124]
So I'm using the latest version but it seems that every pokemon I encounter gets away, altough I have enough PokeBalls and I still can loot the PokeStops.

![unbenannt](https://cloud.githubusercontent.com/assets/20831147/17621055/17cd2ca6-6091-11e6-895e-c0f34699f9e7.png)

**Comment by aslan568** [comment]
I have that same problem :(

**Comment by TeamRedd** [comment]
yep same here , was there an update or something?

**Comment by aslan568** [comment]
All I calculate the ban went all seven :(
