### ISSUE TITLE
OLD VERSION Bot is working for GOOGLE/PTC ! ( 1.0.9.6 )

### ISSUE THREAD

**Issue by Vini1337** [Ar1i/PokemonGo-Bot#3125]
So i saw there was a new update this morning and i saw the shitload of issues getting posted here so decided to leave the old version ( 1.0.9.6 ) running and its still working. Im even catching more Pokemon/h then before but i think thats just random. Im "playing" on a google account so that is working just fine as always. Maybe we should all stop complaining till the issue got fixed and thank Ar1i and the other developers for this amazing bot ? Thank you ! And btw sorry for my bad english, im from germany xd

( I know we shouldnt post about old updates in the issues tab but i think this will help many :+1: )

![one](https://cloud.githubusercontent.com/assets/20989743/17621097/5f93921e-6091-11e6-9ff1-31cda94501f1.PNG)
![one2](https://cloud.githubusercontent.com/assets/20989743/17621101/644c2870-6091-11e6-94ce-44c305d24445.PNG)

**Comment by thearmelly** [comment]
New version no problem too.

**Comment by Vini1337** [comment]
@thearmelly I just wrote this because many people wrote issues about the new version not working, sorry if im wrong !

**Comment by joker041913** [comment]
so the bot is working fine now right??

**Comment by Vini1337** [comment]
@joker041913 not sure about 1.1.x.x but 1.0.9.6 is working fine. Maybe just wait for the next hotfix and use the "old" bot for the next 3-4 hours

**Comment by jeremie152** [comment]
how take other version? i see only one the last

**Comment by Vini1337** [comment]
@jeremie152 well thats why i am backupping every version xd I could upload it for you but im not sure if the @Ar1i and the other devs like that :D

**Comment by Damindo25** [comment]
Vini1337
Is with you so  Detected a softban. Trying to use our special 1337 unban methode.

**Comment by jeremie152** [comment]
ok thanks im sure he is ok^^ its for help all

**Comment by Vini1337** [comment]
@Damindo25 I dont get what you mean, im sorry xd

**Comment by Damindo25** [comment]
Ja ich kann einiges aber English nicht so gut xD

**Comment by Damindo25** [comment]
Kann ich dir wo schreiben ?

**Comment by Vini1337** [comment]
@Damindo25 http://steamcommunity.com/profiles/76561198045430430/

**Comment by Ar1i** [comment]
thats bullshit.

**Comment by Vini1337** [comment]
@Ar1i just wanted to help because many users are having trouble but i guess you know it better right ?

**Comment by Damindo25** [comment]
habe kein steam Account Schreib mir mal Facebook   Heiße dort Mamas Kind

**Comment by jeremie152** [comment]
ar1i is here wait 2 mn and update coming

**Comment by Vini1337** [comment]
@jeremie152 yeah thats what i said aswell, just wait, but no reason to get salty just because im trying to help some users xd

**Comment by gottahub** [comment]
![working](https://cloud.githubusercontent.com/assets/20944255/17621471/b1c30aa2-60bd-11e6-8ce9-3879144cadcb.JPG)

i use old version 1.1.0.1

**Comment by jeremie152** [comment]
y ar1i understand us need help other user when you is not here its normal...

**Comment by Vini1337** [comment]
Gottahub Google or PTC ?

**Comment by gottahub** [comment]
@Vini1337 Google

**Comment by jeremie152** [comment]
need some version in build only for no problem in the futur

**Comment by Vini1337** [comment]
@gottahub well i guess its working again then, im sorry for making trouble

**Comment by Damindo25** [comment]
wäre cool wenn du mir kurz helfen Könntest : )

**Comment by Vini1337** [comment]
@Damino25 Mamas kind gibt es 200x auf facebook sorry da suche ich jetzt nicht den richtigen ^^

**Comment by jeremie152** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/12750555/17621597/93e9a302-6094-11e6-8d9f-d380f1670ca2.png)

**Comment by Damindo25** [comment]
https://www.facebook.com/hagen.hanisch

**Comment by jeremie152** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/12750555/17621636/eb0135ec-6094-11e6-98d2-21a993e8193f.png)
and the resultat now and dont say im ip banned lol im not a rabbit of 15 day

**Comment by rvonz** [comment]
yeah it working fine but, sometimes i cant catch high rate pokemon like bulbasaur, dratini bla bla
