### ISSUE TITLE
Unban not working since last update

### ISSUE THREAD

**Issue by aloadsl** [Ar1i/PokemonGo-Bot#3128]
like image please fix it
![adsadasd](https://cloud.githubusercontent.com/assets/20989737/17621304/84a41986-60bc-11e6-91d7-e79f736f869b.png)

**Comment by bboylost** [comment]
Please read the forum and stop posting shits before you read

**Comment by bboylost** [comment]
you just woke up and found the bot "not working" and first thing is to come here and post ?

**Comment by bboylost** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/3074

**Comment by SahnCH** [comment]
What is the link for the forum ?

**Comment by L00N1** [comment]
I can confirm it is working.

It's server issue

![capture](https://cloud.githubusercontent.com/assets/20923954/17621483/df95325e-6093-11e6-9682-a5a81b145f55.PNG)

**Comment by madc270** [comment]
Me too, it's working again.

<a href="http://www.bilder-upload.eu/show.php?file=f47e77-1471002532.png" target="_blank"><img src="http://www.bilder-upload.eu/thumb/f47e77-1471002532.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by guibr321** [comment]
I was afraid to ask if Unban was working. Thank you guys!

**Comment by aloadsl** [comment]
i try to restart it more than 10 times and wait for about 30 mins but it still not working

**Comment by guibr321** [comment]
![awsome](https://cloud.githubusercontent.com/assets/20976921/17621699/7c15dfec-6095-11e6-8712-3497df88ee6f.PNG)
I've just travelled to catch this rare Pokemon ;) 
Try to download the most updated versión of the bot...

**Comment by aloadsl** [comment]
im using 1.1.0.1

**Comment by Ar1i** [comment]
#3074
