### ISSUE TITLE
Telegram /information Response Text Error

### ISSUE THREAD

**Issue by hartmantam** [Ar1i/PokemonGo-Bot#3129]
The Telegram Bot on `/infomation` command will response a opposite status. For example, I want to enable `Catch` notification, I type in `/information catch`, but it will report that `Catch` is current disabled. Hope someone fix it.

![pokehackbot 0](https://cloud.githubusercontent.com/assets/8369976/17621276/f78d24ae-6046-11e6-9963-8fde10abee7c.jpg)

**Comment by OwKuuT** [comment]
There is a tuto to use the telegram? thx

**Comment by joeisme90** [comment]
my way to do it../information all-enable then /information Pokestop. This will enable info on catch only

**Comment by hartmantam** [comment]
@OwKuuT Go look [here](https://github.com/NECROBOTIO/NecroBot/wiki/Telegram), the setup method is pretty similar. BTW, it is a `issue` tap for software coding problems and errors, not a forum-like Q&A place.

**Comment by CruSherFL** [comment]
Already submitted. #1964

**Comment by hartmantam** [comment]
@CruSherFL I had reviewed that issue too, but it is not the same. in #1964, the program triggered a wrong function. In my case, the program is printed with a wrong message only, it don't effect the type of information which outputs.
