### ISSUE TITLE
What ist the problem? Softban or server problems?

### ISSUE THREAD

**Issue by PlsTarget** [Ar1i/PokemonGo-Bot#3131]
I CAN catch pokemon and i can find pokestops but i can't get them. the bot ist walking to next pokestop and after 5 mins i get themessage
[13:24:06] Detectet a softban. Trying to use our special 1337 unban methode.
no response
after i restart the bot is the same
![ofp8rx5](https://cloud.githubusercontent.com/assets/20891381/17621418/6e4c8fc0-6093-11e6-93d4-5547f3b8787f.png)

And when i unbanned i cant get the pokestops

**Comment by ripharambe** [comment]
wait 15 minutes and then start bot ;) if not help, let it opened and bot will fix it

**Comment by joy0824** [comment]
level 33, RIP
