### ISSUE TITLE
Unbanning don't work ?

### ISSUE THREAD

**Issue by OwKuuT** [Ar1i/PokemonGo-Bot#3134]
Look :
![unbanning don t work](https://cloud.githubusercontent.com/assets/20926981/17621601/9d040400-6094-11e6-8a4d-1bf3e73c41cd.PNG)

**Comment by joy0824** [comment]
same level as me, RIP buddy.  i want to play back so badly..

**Comment by zliong2007** [comment]
same here... frequently "detected a softban... "

**Comment by filoh** [comment]
Same here, all pokemons running away.

**Comment by jodirt282** [comment]
level 26. everything works.

**Comment by OwKuuT** [comment]
No problem i close issue, its a server problem i think, i'm lvl 25 - 99% :( :( :(
