### ISSUE TITLE
BANNED OR SERVER DOWN ?

### ISSUE THREAD

**Issue by ONOBARY** [Ar1i/PokemonGo-Bot#3136]
![screenshot_2016-08-12-18-55-25](https://cloud.githubusercontent.com/assets/20884771/17621670/2326ee24-60bf-11e6-9912-a325ba535945.png)

**Comment by gottahub** [comment]
http://www.mmoserverstatus.com/index.html

**Comment by xuban** [comment]
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzz...

The same question again.  U cant search before posting? https://github.com/Ar1i/PokemonGo-Bot/issues/3074

**Comment by X-ONX** [comment]
Retry!

**Comment by filoh** [comment]
Just for knowing, what server did the bot use?
German? Google? USA?

**Comment by xuban** [comment]
Google or PCT to login and others to play.

**Comment by Pokator9000** [comment]
Probably banned because this is how it looks if the server have problems:
![screenshot_20160812-134737](https://cloud.githubusercontent.com/assets/20990294/17621790/11929218-6096-11e6-86f0-8a008491835e.png)

**Comment by ONOBARY** [comment]
Since over 9 hours  im server in indonesia i chek server indonesia 9 hours ago is ok  and  other account is fine im using google account

**Comment by ONOBARY** [comment]
This notification before server down on  http://www.mmoserverstatus.com/index.html

**Comment by xuban** [comment]
@Pokator9000 The servers are unstable. The better option is wait to fix them, and after u can say if u are banned.

**Comment by ONOBARY** [comment]
I hoppe not banned  and tomorow fixed this issue

**Comment by cyberwolf888** [comment]
Probably banned. 
Just create new account.

**Comment by Pokator9000** [comment]
@xuban this doesn't have something to do with the servers... It's two different messages. One account ist showing always the same message (first picture). Other accounts are working or the second picture shows up because of the server.
If you have the first picture, your account is probably fucked. Just deal with it.

**Comment by Ar1i** [comment]
#3074

**Comment by ANNORMALE** [comment]
http://www.mmoserverstatus.com/index.html

on which server accesses Pokémon ?  Buy Language ? Or GPS Signal ? how is server chosen?

**Comment by xuban** [comment]
@Pokator9000  stop confusing. A lot of "regular (no bot)" people is reporting the same problem in Pokemon Go App oficial account.... https://twitter.com/pokemongoapp

**Comment by Pokator9000** [comment]
@xuban can't find anything there? What should I see?
