### ISSUE TITLE
I can't find POKEMON!!! It is a NEW Bann System! HOW FIX? PLS Ar1i!

### ISSUE THREAD

**Issue by Cenatrex** [Ar1i/PokemonGo-Bot#3137]
# Can't find Pokemon! 

## This is today since 3:00am already so. **Germany TIME!**
------------------------------------------------------------------------------------------------------------
# PLS HELP!!!

![pokemon bot catch nothing](https://cloud.githubusercontent.com/assets/20989729/17621763/dc9093e4-6095-11e6-96ae-5c760198d2dc.jpg)

**Comment by xuban** [comment]
And the same question again....
# **DONT SPAM WITH THIS QUESTION AND PLEASE SEARCH BEFORE POSTING**
https://github.com/Ar1i/PokemonGo-Bot/issues/3074

**Comment by shengzie** [comment]
FFS pls back read #3074

**Comment by Cenatrex** [comment]
Thanks Guys, the Problem is this Page is so confused!

**Comment by joy0824** [comment]
interesting, level 39 , one more level to go =) anyway, RIP. there is no solution so far, and possibly permanant ban, look for new game..

**Comment by joy0824** [comment]
i got solution for you, at least to your brain
https://twitter.com/johnhanke/status/761358072224755712
https://en.wikipedia.org/wiki/John_Hanke

at least u can be certain now
