### ISSUE TITLE
can we have something to unban at least for now to go back into legit. sorry, had to ask this..maybe u're working on it.

### ISSUE THREAD

**Issue by joy0824** [Ar1i/PokemonGo-Bot#3138]
well titles says all but oh well just wanna login back account in legit manner and wait everything clear...before they decided to put down the thor hammer.. =( dragonite...

**Comment by xuban** [comment]
Again again again... with the same question. 
U can stop spam and search the correct thread? https://github.com/Ar1i/PokemonGo-Bot/issues/3074

**Comment by gottahub** [comment]
can i sleep now?

**Comment by joy0824** [comment]
its not a question, its request @xuban  dumbass

**Comment by joy0824** [comment]
i am one of the first who warned this, u think i know nothing about this, dumbass

**Comment by joy0824** [comment]
read properly before u respond.

**Comment by xuban** [comment]
Mmmmm.... It's a request and u write in "issue" section? And now i'm dumbass? hahaha.
Please, go to school. U are in time to do.
