### ISSUE TITLE
Softbann 40mal drehen funktioniert nicht mehr??

### ISSUE THREAD

**Issue by Dinja1990** [Ar1i/PokemonGo-Bot#3141]
Leute ich versuche mich um unbannen
Geht irgendwie nicht. Weißt einer warum?

**Comment by CruSherFL** [comment]
Weil niantic das wohl gefixt hat.

**Comment by Dinja1990** [comment]
Gibt bestimmt keine andere Möglichkeit  sich selbst zu unbannen?

**Comment by knightofdemons** [comment]
warte 2-3 stunden, dann ist der softbann wieder weg. andere möglichkeit gibt es nicht

**Comment by Damindo25** [comment]
Hey Läute habe auch ein Problem weiß einer was man da machen kann heute Morgen war alles noch okay nur jetzt bekomme ich immer diese Nachricht  Detected a softban. Trying to use our special 1337 unban methode.    Also bekomme da Immer ein Softban :(

**Comment by Dinja1990** [comment]
Ist es dann auf bot auch, also wenn es nicht mehr so funktioniert dann kann es mit bot auch nicht funktionieren?
Oder sehe ich es falsch?

**Comment by Dinja1990** [comment]
@Damindo25 leider bekommt jeder zur zeit einen siftbann wie es aussieht......

**Comment by Damindo25** [comment]
aso okay dann ist es gut Das ich nicht alleine Davon betroffen bin :package:

**Comment by knightofdemons** [comment]
Also bei mir läuft der Bot seit viel Stunden mit der aktuellsten Version. Wichtig ist halt, das ihr keine gebannte IP haben dürft (falls ja mal nen halben Tag alles liegen lassen und nicht andauernd versuchen), dann auch mit der Geschwindigkeit runtergehen (25km/h ist ein bisschen viel), kein Locationhopping (nehmt einen Standort der zu eurer IP passt - eine deutsche IP wird nie in den USA sein) und vorallem kein Multi-Account. Nur einen Account pro IP. Die public Proxyserver könnt ihr übrigens vergessen - da bekommt man gleich einen Insta-Bann. Bleibt am besten bei eurer eigenen IP und sitzt den Softbann eben aus. Das alles hat zumindest für mich bisher sehr gut funktioniert.

**Comment by knightofdemons** [comment]
(war auch heute morgen Softbanned btw - hat sich schnell wieder gegeben)
