### ISSUE TITLE
bug cercle localisation to farm

### ISSUE THREAD

**Issue by emilie253** [Ar1i/PokemonGo-Bot#3142]
![bug bot](https://cloud.githubusercontent.com/assets/20780055/17622237/54809fb8-6099-11e6-93d7-ec875624efc8.png)
My "guy" go outside of cercle to farm. i never had this bug, it's normal?

Thank you

**Comment by monchen** [comment]
what app or program you use to crack your movement? thanks

**Comment by emilie253** [comment]
i use just bot
