### ISSUE TITLE
Can u guys help me? 

### ISSUE THREAD

**Issue by Kenjizje** [Ar1i/PokemonGo-Bot#3143]
I started the bot im softbanned i click to the force unbann " we will unbanned u in the next pokestop " detected a  softban - Probably unbanned you ... But the pokes still goes away? What doing im wrong?

**Comment by knightofdemons** [comment]
wait about an hour or two and your softban gets lifted. please make sure to make a more unique title next time. i couldnt figure out what you want on reading the title. most people probably wont even click your question
