### ISSUE TITLE
โพสนี้สำหรับ คุยเกียวกับปัญหาที่ทุกคนได้พบได้เจอ รวมกันเราอยู่.

### ISSUE THREAD

**Issue by thearmelly** [Ar1i/PokemonGo-Bot#3145]
ใครมีอาการ บอทแปลกๆมาแลกเปลี่ยนกันครับผม

**Comment by Siriondiil** [comment]
Ok. '-'

**Comment by dewtheking** [comment]
อาการที่เจอก็ หมุนป้ายได้ แต่จับโปเกม่อนไม่ได้ครับ 
แต่พอสมัคไอดีใหม่ มาลอง มันหมุนได้ จับได้ ครับ

**Comment by Natthawat220** [comment]
ตอนนี้ใช้บอทตัวล่าสุดอยู่ครับ 1.1.0.2 ทางคนทำเปิดให้ใช้แล้ว แต่ก็ยังมีความเสี่ยง
ให้มันเดิน 5km/h รัศมี 800-1000 พอ ยังไม่เจอปัญหาอะไรครับ เสถียรดี ปิดบอทเข้าใหม่บอทก็อยู่ตำแหน่งเดิม เดินเก็บเนียนๆ ไป ไม่พยายาม Transfer, PowerUp, Evolve ในบอท เผื่อจะลดความเสี่ยงได้

ส่วนไอดีหลักตอนนี้ ขึ้น "failed to get game data from the server" เข้าไม่ได้ตั้งแต่เช้า สงสัยจะบิน
แต่ก็ยังสรุปไม่ได้ใช่ไหมครับว่า โดนแบนถาวร หรือ มีปัญหาเกี่ยวกับเซิร์ฟเวอร์ ลุ้นกันไป

ไคริว 100 % คาบิก้อน 92% ไปซะละ

**Comment by thearmelly** [comment]
ผม จับโปเกมอ่นได้ สู้ยิมได้ แต่... หมุนป้ายไม่ได้แหะ

**Comment by soshi125** [comment]
ของเราขึ้นแบบนี้เป็นเพราะอะไร

![image](https://cloud.githubusercontent.com/assets/20992383/17625141/c54fe90a-60d1-11e6-9b3d-da93c27d982a.png)

**Comment by nismotue1** [comment]
Build 12.08.14.19 ปรกติิคับ เวล1-13 ครึ่งวัน เรื่อยๆ เดิน5 กว้าง1000 เปิดปิดแค่2ครั้ง
อยากรู้ว่าตรงช่อง Max cp to transfer มันบัคหรือเปล่าหรือมันทำงานยังไง บอกทีคับ
![siam](https://cloud.githubusercontent.com/assets/20989325/17626933/93d6d2a0-60d9-11e6-9d26-5d5b1b5767da.png)
