### ISSUE TITLE
Settings for evolving (exp farming)

### ISSUE THREAD

**Issue by knightofdemons** [Ar1i/PokemonGo-Bot#3146]
Hello,

i just recently started using the bot. Its an awesome piece of work, nice developement! Thank you very much, sir!! Keep it going.
So iam trying to figure out which are the best settings for exp farming.
Usually you are using pidgey, ratta and habitak for evolving and farming exp - because they are like rats, just everywhere.
So i want to find a setting which evolves them on catching and send them away on their next level.
But it neither developes them on catching. I'm currently 'collecting' them and evolve them manually. After evolving they get auto-transfered. But this takes the risk of getting my pokebox full real quick.
Do you guys know a setting which works like that instead of transfering them immediatly without evolving?
![unbenannt](https://cloud.githubusercontent.com/assets/8983377/17622356/211c56e8-609a-11e6-8ad1-157c14877b1a.png)

**Comment by GHANT** [comment]
Select all pokemon to catch.

Max double pokemon 1
Max IV: 95%
Max CP: 1200

Don't check anything else.

**Comment by knightofdemons** [comment]
Nope...that just transfers the pokemon without evolving them in the first place.
That just collects me bonbons.
I want to catch a pidgey. Then evolve it to a pidgeotto. And then transfer it.

**Comment by Guiseppe3** [comment]
There is no such option. Idk why. Tho knight is correct here. Just do what he said and youll be fine in P. GO.
