### ISSUE TITLE
All pokemons got away

### ISSUE THREAD

**Issue by Dans30000** [Ar1i/PokemonGo-Bot#3147]
Having this now... " all pokemons get away when using pokeballs or greatballs"

Am not softbanned... someone have the same ?

Sorry if its double post

**Comment by Zixey13** [comment]
same here

**Comment by albii687** [comment]
:/

https://gyazo.com/3a1cec64db22e92521574672dc260593

**Comment by feraso25** [comment]
Here is normal!

You download the latest version?

**Comment by Dans30000** [comment]
Yeah i have the latest version...

**Comment by ukrityoke** [comment]
latest version cant fix
I can spin Poke Stops but cant catch any pokemon
