### ISSUE TITLE
Pokemon Run Away

### ISSUE THREAD

**Issue by elijamesn2001** [Ar1i/PokemonGo-Bot#3149]
Whenever I try to catch a Pokemon and it escapes it automatically runs away on the first time. I have no idea why this is happening.

**Comment by Abbasoo** [comment]
Same here.
![untitled](https://cloud.githubusercontent.com/assets/20796710/17622660/59ab99ce-60a4-11e6-8a88-4b0cd1bd89ef.png)

**Comment by Sohail852** [comment]
Its because u dont have pokeball and greatball in inventry.
Fix:Get some pokeball and greatball it will fix :)

**Comment by Abbasoo** [comment]
@Sohail852 I have 60 Pokebaill, 60 Greatball AND FU****ING 75 Ultraball.

**Comment by GHANT** [comment]
@Sohail852 Honestly, are you blind? He has over 350 items. Learn to read.

**Comment by Sohail852** [comment]
@GHANT He can recycle some potions and get pokeballs.
Same thing happned to me. I tryed that and it fixed.

**Comment by Sohail852** [comment]
@Abbasoo i don't know about that but it fixed for me.

**Comment by Abbasoo** [comment]
@Sohail852 
![untitled](https://cloud.githubusercontent.com/assets/20796710/17622883/c588cada-60a5-11e6-941f-594ed804f4d2.jpg)
just take a look AND SHUT THE F*** UP.

**Comment by uberder** [comment]
Dude you need to chill, if you don't have anything nice to say than don't. 

I am having the same issues, I have also changed my amount of pokeballs to 70.  I have waiting now and still issue has been resolved.

**Comment by Dans30000** [comment]
Wtf is going wrong with you, hes just trying to help you... fuckin kid

**Comment by uberder** [comment]
Sorry the issue has NOT been resolved

**Comment by Abbasoo** [comment]
@uberder In Pokefarmer.
![untitled](https://cloud.githubusercontent.com/assets/20796710/17623155/4c5d2334-60a7-11e6-9f27-69340edf4236.png)

**Comment by shahroozal** [comment]
Same thing happened to me. Mine is softban which can not be unbanned for now.

**Comment by TeamRedd** [comment]
Right now i'm avoiding  catching anything, just collecting 50xp from every pokestop around me till some one fix the problem, better then nothing haha

**Comment by akangnduz** [comment]
same problem...i got 37 pokeball,12 great ball etc..pokemon keep running away but i can farm xp pokestop

**Comment by gummyruler** [comment]
There's a new softban that bans you only from catching pokemon.

**Comment by elijamesn2001** [comment]
How do I go about getting unbanned from that
