### ISSUE TITLE
XP/H IS LOW

### ISSUE THREAD

**Issue by New123WeN** [Ar1i/PokemonGo-Bot#315]
Hi Ar1i, you work for the bot is amazing and I really appreciate what you have done for us for free. I noticed that the XP/H is relatively low about 10000/h in a hot place. Could you please check for this. Some people had the same problem. Thanks!

**Comment by colearker** [comment]
in central park mine is normaly 35000/h

**Comment by Tochez** [comment]
seems weird im gaining around 30k exp/h in a non crowded area

**Comment by Tochez** [comment]
central park for me saids about 130k/h.

**Comment by Tochez** [comment]
i catch every pokemon that goes by and eggs :/

**Comment by stormlolz** [comment]
Tochez what your speed and radius ? Thx

**Comment by ObsessedHacker** [comment]
It's also depend on other settings like "Auto Transfer CP".
