### ISSUE TITLE
Error reloading pokemon list (bot won't work since yesterday evening)

### ISSUE THREAD

**Issue by collwyr** [Ar1i/PokemonGo-Bot#3155]
Describe your problem! so I get some error everytime I try loading up the bot, I've deleted all the files and have redownloaded and tried it that way and it still gives me the same error, haven't seen anyone posting about it since yesterday evening (when it started randomly in the middle of botting)

Add a screenshot!  - https://gyazo.com/44781744f2c74ba110a4f0ba7cb10204

**Comment by Troj4ner** [comment]
Same here with a google Account...PTC works perfect...

**Comment by mystery1312** [comment]
Same please help :/

**Comment by collwyr** [comment]
yes I can also confirm my account is a google account also.

**Comment by mystery1312** [comment]
Me too

**Comment by SajetS** [comment]
Leider das selbe Problem mit den neuen Versionen.
Mit 1.0.8.3 funktioniert noch alles.
