### ISSUE TITLE
Suggest to fix fleeing ban

### ISSUE THREAD

**Issue by gonopo** [Ar1i/PokemonGo-Bot#3156]
Hi @Ar1i , i created a new ptc account and was able to catch first 3 pokemons, then the fourth one break away and i stepped into the "fleeing ban"

from the log i think we might be too quick on collecting the pokemon (seems to me like catching is done in millisecond, one after another), could we put a delay there? like a real person normally do, i would suggest delay between catches should be > 2 - 5 sec (picking randomly)

**Comment by zzzz9999** [comment]
or even more seconds between catches.
also transfers and evolves could have some sort of deliberate delay

**Comment by ponogo** [comment]
^ yea those ones also

**Comment by Hydro420** [comment]
I assume its pretty easy to see who is botting and who is not when actually looking at the account - regardless of how you try to run it.

One of my accounts can not catch pokemon anymore & the other seems to be Perm Banned. Been over 12Hrs still can not run bot or login with any device. "Can't get player info from game server."

**Comment by ponogo** [comment]
with millions of accounts and billions of activities, i doubt it would an easy job to mine in and detect who cheats who, key point i think it's all about settings, need to make it real, dont be too greedy to set walking with the pace over 10 km/h

**Comment by Hydro420** [comment]
Thats why you make a program to run calculations and ban accounts

**Comment by JacksonTrue** [comment]
Exactly! I have already created a theme that is softban issued for non- timing . When Pokémon caught bursts in milliseconds . See illustrative screenshot http://screenshot.ru/824318bbb2135830487e885d3643b462 

It is now many accounts can not enter , there is a suspicion that the number of software stacks bans , and then given permanent. Make the timings and the problem will be solved . It is desirable to be set in the interface.

**Comment by JacksonTrue** [comment]
1 more screenshot , the problem is obvious http://screenshot.ru/5b5eab060cbe65904d656f72ba4093ac
need timings in catching Pokémon .

**Comment by gonopo** [comment]
great example there @JacksonTrue , thanks alot, i wish i know some .net so i could jump in and contribute something to the app

**Comment by JacksonTrue** [comment]
Sorry for the poor knowledge anliyskogo , if I understand correctly , we are talking about jumping and speed. I is 5 kilometers per hour

**Comment by JacksonTrue** [comment]
and 1 sample http://screenshot.ru/bc5ea7b90faf72140dc618ffc648c8bf

**Comment by JacksonTrue** [comment]
http://screenshot.ru/9180fcfdd2b3ab01f28853642e21d696

**Comment by JacksonTrue** [comment]
everything seems obvious , add timings please

**Comment by JacksonTrue** [comment]
If you pay attention , the records are repeated . As if caught 1 Pokémon .
http://screenshot.ru/dd9bc7ae6721921202dd7842d78613af

**Comment by halocannn** [comment]
ıs there any solution for this problem?

**Comment by zzzz9999** [comment]
some sort of delay for catching pokemon and bulk actions (transfer/evolve) is needed to avoid softbans, please
@Ar1i

**Comment by Ar1i** [comment]
Uploading newest Version, with harder delays

**Comment by zzzz9999** [comment]
thanks @Ar1i

**Comment by zzzz9999** [comment]
@Ar1i what are the new values for delay? (Cant find them on code)

**Comment by zzzz9999** [comment]
is this right?
await RandomHelper.RandomDelay(1000, 3000);
Is it not too few? Why not put it configurable (in the UI)
@Ar1i 
T H A N K S 4 A L L

**Comment by zzzz9999** [comment]
Also can you consider a delay on bulk transfer/evolve?

**Comment by gonopo** [comment]
thanks @Ar1i

**Comment by gonopo** [comment]
at least things now are catchable! fleeing rate is still high (only 1 or 2 out of 10 successful), niantic really want to hammer us all this time haha

**Comment by gonopo** [comment]
![screenshot](http://i.imgur.com/tzqdEns.jpg)
