### ISSUE TITLE
I think i got an Account -hardbann

### ISSUE THREAD

**Issue by Hans1910** [Ar1i/PokemonGo-Bot#3158]

**Comment by Hans1910** [comment]
![fehler](https://cloud.githubusercontent.com/assets/20991253/17623207/281b8c16-609f-11e6-9148-689f6ce484d9.png)
i think i got hardbanned is there a work around or where i can see how long the bantime is ?

**Comment by james741** [comment]
well done, same 
so no one have any know how on this issues?

**Comment by py4989** [comment]
same... i think i got hard banned too

**Comment by gummyruler** [comment]
#3074

**Comment by james741** [comment]
permanent ban ~

**Comment by NidiKea** [comment]
Hier dasselbe

**Comment by nevrrmind** [comment]
@NidiKea , einfach mal lesen ;) "SERVERS DOWN *New Bans are happening, we are taking a look ..."

**Comment by NidiKea** [comment]
Ja, hab ich gelesen.  Ney bans are happening heisst neue Bans sind im Umlauf richtig? Mich wundert nur immer noch, wieso der Account, der wurde gar nicht benutzt tageland und war vor Wochen nur 1 mal kurz im Bot
