### ISSUE TITLE
[Feature Request] Walk to Location

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#316]
I think its a good way for people to travel far into the world without getting solfbanned.(Unless this was already added)

**Comment by NWExKraken** [comment]
the average human walks about 5km/h so set it to that and itll walk like a normal human

**Comment by Tochez** [comment]
So I just need to set the location and my character will walk there? @NWExKraken

**Comment by NWExKraken** [comment]
itll walk to pokestops within a certain range u set its the speed and distance that gets u soft banned but he will auto walk there

**Comment by Tochez** [comment]
So I set the located to where i want to be (New York to Boston) and the character will be at Boston. right?
@NWExKraken

**Comment by NWExKraken** [comment]
yep

**Comment by Tochez** [comment]
do i tick the start walk from default location on or off? @NWExKraken

**Comment by NWExKraken** [comment]
default as it sets it to the location u have selected not where u left off

**Comment by Tochez** [comment]
oh ok alrighty thanks @NWExKraken

**Comment by NWExKraken** [comment]
no problem

**Comment by Tochez** [comment]
Youre outside of the defined Max Walking Radius. Walking back! wat does this mean?

**Comment by NWExKraken** [comment]
ur character location is farther than the limit is

**Comment by Tochez** [comment]
does that mean i cant go beyond that limit?

**Comment by Tochez** [comment]
it dissapears when i set the move radius to 50000 meters

**Comment by NWExKraken** [comment]
u cant go beyond the limit u set

**Comment by NWExKraken** [comment]
new york to boston is more than 50000 meters

**Comment by Tochez** [comment]
oh i got it. btw i still set the walking distance to 5 km or i can have it higher(such as 50km)

**Comment by NWExKraken** [comment]
u can have it as high as u want its the soft bans and the pokemon that u get thatll differ

**Comment by Tochez** [comment]
Sorry for asking a LOT of questions but can u help me of this:
[20:06:09] Youre outside of the defined Max Walking Radius. Walking back!
[20:06:09] Distance to target location: 290529.15 meters. Will take 20918.1 seconds!
the second line, does it mean im walking to boston or walking back to the default location

**Comment by NWExKraken** [comment]
whatever u have set

**Comment by Tochez** [comment]
I put it to a place in boston. It walking there am i correct?

**Comment by Tochez** [comment]
![capture](https://cloud.githubusercontent.com/assets/20713623/17266698/759ba042-55c9-11e6-82ae-67ffbfec84db.PNG)
I have it set like this. Is this how your suppose to do it?
