### ISSUE TITLE
perma ban

### ISSUE THREAD

**Issue by barashnukor** [Ar1i/PokemonGo-Bot#3160]
Hallo,

woher weiss ich, ob es ein perma ban ist? Ich kann nicht mehr einlogen. Bekomm auf meinen Handy ständig eine Fehlermeldung. würde ich im fall eines perma bans eine mail bekommen?

mfg

**Comment by Dinja1990** [comment]
Also ich kann noch rein aber nichts machen 😓

**Comment by NidiKea** [comment]
Ja ich habe dasselbe Problem keine Spielerdaten vorhanden aber auf einem Account den ich nur auf dem Handy Spiele.  Und nun

**Comment by NidiKea** [comment]
Also ich komme nicht mehr rein

**Comment by barashnukor** [comment]
die frage nun ist: perma ban, oder was anderes... wie wird man über einen ban informiert ?

**Comment by M31860** [comment]
Also wenn keine Spielerdaten mehr vorhanden sind, sieht das mM nach schlecht aus.
Ich hab das Ding 24/7 laufen lassen und kann seit 12 Uhr ca. keine Pokestops mehr drehen und alle Pokemons flüchten.
Aber rein komme ich noch... Fragt sich nur wie lange:D

**Comment by NidiKea** [comment]
Sind eure Konten gebannt mit denen ihr hier angemeldet seid ? Nicht dass einer hier alle Leute aus dem Forum auf ne Ban Liste packt also wisst ihr was ich meine ?.Denn der Account war wenn nur 1 mal kurz im bot und seitdem nur auf dem Handy unterwegs an . Das ist seltsam dass Grade der gebannt wurde mit dessen email ich hier angemeldet bin .

**Comment by AiVo7z** [comment]
Ich kann pokemon per Hand fangen, aber keine Stops drehen ... Bot geht nicht...

**Comment by M31860** [comment]
@NidiKea 
Ich bin hier mit einem anderen Mailaccount angemeldet als mit den PoGo Adressen...

**Comment by NidiKea** [comment]
Ok. War ja nur eine Idee hätte ja sein können
