### ISSUE TITLE
Bei Account steht nun es können keine Spuelerdaten abgerufen werden ?

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#3162]
Hallo
Bei mir steht nun beim anmelden es können keine Spielerdaten gefunden werden . Den Account habe ich nur auf dem Handy benutzt? Ist der nun gelöscht ?

**Comment by Pokator9000** [comment]
Möglicherweise Permanent gebannt. Einfach abwarten.

**Comment by NidiKea** [comment]
Ja es haben jetzt Grad viele gepostet.  . Ich hoffe nicht das wäre schade.  Aber es war klar dass sowas kommt.  Kann sowas rückgängig gemacht werden  ?

**Comment by DiTechRacer** [comment]
Also ich werde den Bot nicht mehr an machen.. ist mir zu gefährlich.. War ja auch nur eine Frage der Zeit bis die perma bans in massen kommen..

**Comment by MicGakaMilo** [comment]
Ich hab den Bot nur für Glumandas gebraucht um mir Glurak zu machen. Nun sind alle meine Pokemon verloren und Glurak hab ich ebenso nicht. Den Bot werd ich nicht mehr an machen.
Frage mich nur was mit meinem Account passieren wird...hoffe echt nicht auf einen Permaban sonst war alles umsonst. =/

**Comment by NidiKea** [comment]
Ich hatte damit den bot doch an ganz am Anfang 1 mal aber danach diesen Account nicht mehr also nur unterwegs auf dem Handy. Der nun gebannt ist.  Das ist aber der Account mit dem ich im Forum hier angemeldet bin. Kann das irgendwer mitlesen und die Adressen bannen ?

**Comment by DiTechRacer** [comment]
Die frage ist viel eher, hast du hier im Forum den selben User namen wie in Pokemon?

**Comment by NidiKea** [comment]
Nein Username ist anders

**Comment by NidiKea** [comment]
Kann ich dennoch meinen Usernamen hier ändern.

**Comment by DiTechRacer** [comment]
Ja kannst du.. in deinem Profil

**Comment by NidiKea** [comment]
Dennoch seltsam dass der Account gebannt wurde habe ihn auch 5 Tage nicht genutzt mehr und Grad gesehen erst

**Comment by NidiKea** [comment]
Danke

**Comment by DiTechRacer** [comment]
Vllt. stimmt ja auch nur irgendwas mit den Servern nicht.. Die Zeitspanne von den angeblichen Bans bis zum jetzigen Zeitpunkt ist viel zu klein um es sicher sagen zu können.

**Comment by M31860** [comment]
Also ich kann seit 12 Uhr keine Pokestops mehr drehen und keine Pokemon mehr fangen.
Aber ich komme wenigstens noch in den Account hinein mit meinem Handy. Hab mich auch schon ab und wieder angemeldet. Denke wir müssen etwas warten... Solange die Spielerdaten noch vorhanden sind, kann man denke ich von einem Softban ausgehen. Die Frage ist nur wie lange der dauert... Sonst war ja nach ner halben Stunde ca. alles wieder im Lot:)

**Comment by NidiKea** [comment]
Bei Mir sind keine Spielerdaten mehr zu finden steht da also er meldet sich nicht an

**Comment by AiVo7z** [comment]
Mit Handy geht alles außer Pokestops, immer "versuche es später". Fangen usw. geht perfekt, nur irgendwann gehen die Bälle aus haha

**Comment by The1nooneknows** [comment]
Bei mir steht einfach dass er die Spielerdaten nicht abrufen kann auf dem Handy.
Hab jetzt neuen Account als Backup erstellt und angefangen mal...

**Comment by NidiKea** [comment]
Was heisst als Backup? Meinst du wo du später alles drauf packst sobald tauschen geht? 
Packst du den in den Bot?

**Comment by The1nooneknows** [comment]
@NidiKea Ja genau. Hoffe dass das auch so klappt wie ich es mir denke ^^
Nee..ist mir zu riskant. Hab auf dem Mainacc 139 im Pokedex eingetragen und bin Lvl 32..Keine Lust das "nochmals" aufs Spiel zu setzen. =)

**Comment by NidiKea** [comment]
Ja, aber bei mir haben sie gebannt obwohl ich den einige Tage nicht an hatte und das als ich ihn auf dem Handy an hatte. Ich befürchte die schauen jetzt wirklich , wer hoch im Level ist und oft die Lokation wechselt wird gebannt

**Comment by The1nooneknows** [comment]
Genau. Darum lass ich das mit meinem neuen Account sicherlich.
