### ISSUE TITLE
Niantic permanent ban appeal page

### ISSUE THREAD

**Issue by james741** [Ar1i/PokemonGo-Bot#3163]
and now we know...

https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by Utopik** [comment]
Oh my god! I cant enter my account, too. Failed server. May i be permabanned, too?

**Comment by AlpaEZPZ** [comment]
this is not perma ban.

**Comment by james741** [comment]
@AlpaEZPZ what ur source?

**Comment by OhhPian** [comment]
lol u guys never play mmo before ? That Ban Appeal is for someone who are "innocent" getting permanent ban. As far as i know there is no one here are innocent lol xD

**Comment by AlpaEZPZ** [comment]
i cant catch pokemon like u and i cant loot pokestops like u guys.
but a few seconds ago i fight in a arena in central park and there were no problems so think about it if they would perma ban why can i still pvp. that makes no sense caus pvp is most affected by cheaters.

**Comment by untesty** [comment]
It's just the servers. In the beginning we had also a lot of these problems. I was "perm banned" like you guys call it. And after waiting for like 2 hours ( I mean not opening anything related to pogo in that time ) everything was fixed for me. Bot is working, nox is working and on my phone it's also working. Just leave it alone for a couple hours

**Comment by generaljoke** [comment]
# **https://github.com/Ar1i/PokemonGo-Bot/issues/3166**

**Comment by OhhPian** [comment]
Some people just lazy to read xD

**Comment by james741** [comment]
@generaljoke lol dont think so. never on that bot account or show to anyone before. is always for botting

**Comment by marcop888** [comment]
I cant enter my account, too. Failed server. May i be permabanned?? Pls inform me

**Comment by lailaps** [comment]
No confirmed perma ban atm...

**Comment by ONOBARY** [comment]
Confirmed failed get data on server 

https://mobile.twitter.com/PoGoServer/status/764106960874668033
