### ISSUE TITLE
softban after transfer.

### ISSUE THREAD

**Issue by mezo91** [Ar1i/PokemonGo-Bot#3165]
anyone noticed getting soft-banned after selecting multiple pokemon to transfer?

thank you.

**Comment by 41271** [comment]
I always select a full page and never got soft banned.
If you have questions use https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/page-334 please, this is only for issues.

**Comment by Serg02** [comment]
Im sorry... Is the server down ? cuz I cant understand the language in the forum link you provided.. hehe

**Comment by L00N1** [comment]
only got softbanned after evolving a bunch of pokes

**Comment by zzzz9999** [comment]
#3156

**Comment by zzzz9999** [comment]
some sort of delay for catching pokemon and bulk actions is needed to avoid softbans.
@Ar1i
