### ISSUE TITLE
PRANK "for god sake ALIENS"

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#3166]
# you can be banned if someone reported you. And if niantic caught you cheating but how the f they will know if you are using a private vpn or something so hightech to hide your accounts. So the best way for niantic "for now" to banned cheaters is by REPORTING. **https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal**
![Uploading Capture.PNG…]()

**https://github.com/Ar1i/PokemonGo-Bot/issues/3074**

PS: SERVERS ARE UNSTABLE FGS **mmoserverstatus.com/pokemon_go**

**Comment by L00N1** [comment]
This is not reporting. It's possibility to unban yourself, if you prove u r  an innocent, that got accidentally banned

**Comment by thomatbu** [comment]
You have to learn more English =.=

**Comment by AlpaEZPZ** [comment]
omg... xD

**Comment by shengzie** [comment]
get off them medz now fam them pidgey dont do you good
