### ISSUE TITLE
pokemon just fled

### ISSUE THREAD

**Issue by LUFFYTHETHIRD** [Ar1i/PokemonGo-Bot#3169]
Have you guys noticed all pokemon encountered just fled now more often even when using berry and have a low cp?is it just me experiencing it?

**Comment by LordBunny** [comment]
Its a soft ban or hardban/perm ban

**Comment by LUFFYTHETHIRD** [comment]
is there a way I can do to correct this?

**Comment by knightofdemons** [comment]
red other threads and please close this issue. just wait 3 hours and dont login over and over again
