### ISSUE TITLE
Erreure Bot Pokemon Go Rocket API (FR)

### ISSUE THREAD

**Issue by zortosse** [Ar1i/PokemonGo-Bot#3170]
Bonjour depuis se matin le bot se lance est quand il veut me co sa me dit "la référence d'objet n'est pas définie a une instance d'un objet" est sur mon téléphone sa me dit "Erreur des lecture des données depuis le serveur" J'ai un compte PTC j'ai essayer avec un compte google sa marche très bien que faire?

**Comment by owathan** [comment]
Ton compte a était banni.

**Comment by zortosse** [comment]
Est comment on le déban?

**Comment by owathan** [comment]
Ya un formulaire de déban dans la FAQ du site de pokémon go, je ne sais pas si ça marche, sinon tu peut laisser tomber.

**Comment by Deki60** [comment]
Je "bottai" avec 3 comptes sur les 3 (config de la même façon) 1 a le même problème et les autres fonctionnes toujours... j'ai coupé les bots en attendant d'y voir plus claire ! le truc qui me fait grave chier la c'est que c'était le compte d'un enfant de 11 ans....

**Comment by zortosse** [comment]
tu peut envoyer le lien plz

**Comment by Deki60** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal
tiens nous au courant si sa fonctionne...

**Comment by zortosse** [comment]
ok

**Comment by Deki60** [comment]
Pour y voir plus claire tu quel était tes réglages ? 
Perso sur le compte qui as le même problème 
10km/h
12000 m
localisation : US
Proxy : US
