### ISSUE TITLE
Perm Ban Confirmed !!

### ISSUE THREAD

**Issue by MOE4HACKS** [Ar1i/PokemonGo-Bot#3175]
.Open https://club.pokemon.com/us/pokemon-trainer-club/sign-up/
.Try to register your account username that u cant access
.If its available , then its a ban.

THX

**Comment by Treeckors** [comment]
if you use it under the ptc, its its own unique id, it does not give you the name of the first 6-8letters of the email you provided. google log in for the game is currently offline

**Comment by questioner01** [comment]
ban the problem is only with google accounts?
Perma ban is real?

**Comment by Treeckors** [comment]
it does not give you the name of the username you requested, for pokemon go i shouldve been more specific, my bad.

**Comment by pokemav** [comment]
dont be silly, PTC is not linked to gmail accounts, nor pokemon go nicknames. If you create an account at PTC it-ll be a new one

**Comment by Ar1i** [comment]
this is dumb
