### ISSUE TITLE
always catch fail pokemon got away while using pokeball(Green word) and cant spin poke stop , detected softban repeat and repeat unstopped.

### ISSUE THREAD

**Issue by lancelkh** [Ar1i/PokemonGo-Bot#3179]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by inijefri** [comment]
![fail](https://cloud.githubusercontent.com/assets/20828153/17626829/2531e20e-60d9-11e6-890b-d20b97e740dd.jpg)

**Comment by nickpkm** [comment]
Having the same problem here

**Comment by MERTCU** [comment]
same

**Comment by zyxelgg** [comment]
I have  the same problem, please help

**Comment by knightofdemons** [comment]
softbann, read the other threads. wait 3 hours, dont use the bot, then it will be fine again

**Comment by lancelkh** [comment]
aikz..... hope wait 3 hour can solve the problem.

**Comment by shengzie** [comment]
yeezus is coming
