### ISSUE TITLE
[Not an Issue] Bot is working so fine, unban also

### ISSUE THREAD

**Issue by sylva91** [Ar1i/PokemonGo-Bot#3180]
I'm using the 09.08 build from yesterday, i've opened and closed it many times, changed the location many times too (NY, Paris, Rome, Tokyo). I've been -normally- softbanned after every location change but unbanned easily with the bot.
I'm always moving at a 9kph and using a google account. 
this can give you the suggestion of a speed related bans

**Comment by itamoye** [comment]
can u give location on tokyo?

**Comment by velfisadri** [comment]
i can catch pokemong and cant spin pokestops ;/ always try again later msg ;/

**Comment by jordanpillefernandez** [comment]
sylva91 are you sure of this ?

**Comment by sylva91** [comment]
i've just changed my location from Eiffle tower in Paris to Shibuya crossing in tokyo (35.659469, 139.702112) : 
![screeeeeeen](https://cloud.githubusercontent.com/assets/4414999/17627604/b756933a-60a9-11e6-832e-a0f75ca0aa99.png)

**Comment by XxSHADOWxWOLFxX** [comment]
i use version 1.0.9.3
works fine for me. 
i can change locations without problem.
my bot runs in japan yoyogi park (around 60 to 80k xp/h) with 150 kph without softbans or other problems.
i dont use proxy. 
i use a google account and only one session.

**Comment by jordanpillefernandez** [comment]
wow incredible... do you use smartphone to play pokemon go to ?

Are you sniping pokemon ?

**Comment by ashleycolton** [comment]
Yes my home ip was banned from accessing the server for pogo. Can we have proxy configured automatically for the bot

**Comment by XxSHADOWxWOLFxX** [comment]
i play via blue stacks on pc, too for sniping the 100% pokemons. 
before i start blue stacks i close the bot and teleport to the pokemon i want.
after that i gon in battle and change the location vie fake gps to japan, because my last position the park in japan. 
after im back in japan im still in the battle with the pokemon and you can catch it withouta ban, because i caught it in the park.
its a nice trick :)

**Comment by ashleycolton** [comment]
@XxSHADOWxWOLFxX
I can't seem to play via bluestacks, it gives me error when i try to root it :/
But that could be another way to help with sniping and not get banned!

**Comment by XxSHADOWxWOLFxX** [comment]
i used kingroot for rooting blue stacks and for installing fake gps i used lucky patcher

**Comment by sylva91** [comment]
before i play with my smartphone, i set the bot's location to my actual location so the bot unban me and i'm free to go ;)
