### ISSUE TITLE
ALIENS

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#3182]
## **https://twitter.com/Ar1iDev**

![capture](https://cloud.githubusercontent.com/assets/20971723/17626850/a013b2d8-60e1-11e6-9a67-7c320dba715c.PNG)

**Comment by IbnuKhafid** [comment]
told anyone to be patient, but apparently some of them just so ignorance and kept on doing the same thing again and again, look at what he said, told u to be grateful but so many of them just so selfish. pppffftttt so funny these guys, just LOOK AT WHAT HE SAID AND READ. LOL. dont u guys (for them that really ignorance) know to be patient and just wait and not pressuring him? LOL.

**Comment by IbnuKhafid** [comment]
hey @generaljoke please rename the title and keep it to TWITTER UPDATE Ar1i, so everyone can read what he felt all this time
