### ISSUE TITLE
why don't catch pochemon?

### ISSUE THREAD

**Issue by blade90** [Ar1i/PokemonGo-Bot#3184]
![immagine](https://cloud.githubusercontent.com/assets/20888636/17627128/6522f458-60b0-11e6-9efc-362486b6b66a.jpg)

**Comment by Niiickel** [comment]
Same for me

**Comment by zyxelgg** [comment]
same for me

**Comment by pokerave** [comment]
ANY of you tried this one?

![0pokeball](https://cloud.githubusercontent.com/assets/20603254/17627407/d21b71d0-60b9-11e6-8a9b-33dc3e4bcfc4.png)

**Comment by zyxelgg** [comment]
@pokerave  No

**Comment by generaljoke** [comment]
OMG ALREADY SPAMMED SO MANY TIMES **# A SOFTBANNED** FOR GOD SAKE

**Comment by Niiickel** [comment]
I didn't set Pokeballs to 0 still not catching

**Comment by itamoye** [comment]
http://ispokemongodownornot.com/ 
http://www.mmoserverstatus.com/pokemon_go

**Comment by zyxelgg** [comment]
Not the server problem, I tried another account in BOT, works fine.
So this is a new type of ban?

**Comment by osnake** [comment]
perment ban

**Comment by itamoye** [comment]
@zyxelgg me too, alrdy try with other acc and still work, but bfore im try with main acc, and get new type of ban.

**Comment by zyxelgg** [comment]
How did you know this is perment ban?

**Comment by AmbientLights** [comment]
its a new type of ban you can spin pokestops in the game but all pokemon just run away

**Comment by itamoye** [comment]
just wait till all server up, then ar1i and dev can solve this problem, and DONT POST MANY ISSUE ABOUT PERM BAN OR OTHER!

**Comment by osnake** [comment]
if I use noxplayer there are no pic in pokestop

**Comment by blade90** [comment]
then I should change the area to capture pokemon?

**Comment by AmbientLights** [comment]
lol necrobot has ceased development

**Comment by AmbientLights** [comment]
Due to legal action being started against other bot creators/devs

**Comment by osnake** [comment]
not working

**Comment by Dans30000** [comment]
Yep i got the same error, i tried to catch pokemon on my phone and it goes away. Its a ban for sure... permanent or not, i dont know.
