### ISSUE TITLE
New type of ban?

### ISSUE THREAD

**Issue by hazmad** [Ar1i/PokemonGo-Bot#3185]
You might be banned if (temp/perm?):
you go to pokestop it says "try again later". 
All pokemon flee. 
It freezes when you try to enter a gym

New type of ban on our hands or maybe just their shitty servers again?

**Comment by LikeAFisch** [comment]
its normal softban.

**Comment by pokerave** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by knightofdemons** [comment]
Dont open a new thread please, there are already plenty of those. Please close the issue

**Comment by marcop888** [comment]
Error reloading Pokemon list: Object reference not set to an instance of an object.

is this permabanned?
