### ISSUE TITLE
JUST BE THANKFUL

### ISSUE THREAD

**Issue by pokerave** [Ar1i/PokemonGo-Bot#3187]
Just be thankful you are not abandoned

![thanks](https://cloud.githubusercontent.com/assets/20603254/17627596/71143f4c-60ba-11e6-96a3-fa4116a0c6af.png)

**Comment by Killmachine** [comment]
@pokerave Where did you find this information? Could you give the link to it please?

**Comment by pokerave** [comment]
Discord

**Comment by testo4life** [comment]
its true necro just died !

**Comment by tainhx** [comment]
So can we still use bot?

**Comment by pokerave** [comment]
![legal](https://cloud.githubusercontent.com/assets/20603254/17627791/28bb7fe8-60bb-11e6-907c-5b6bfb28afe1.png)

**Comment by knightofdemons** [comment]
true! kudos to the developer!

**Comment by tainhx** [comment]
So which is suitable Speed at this time ?

**Comment by IbnuKhafid** [comment]
try to read ALIENS ISSUES

**Comment by knightofdemons** [comment]
@tainhx 10-15km/h ...walkingspeed

**Comment by tainhx** [comment]
thanks !
