### ISSUE TITLE
Item recycle quantity bug

### ISSUE THREAD

**Issue by Turlututu69** [Ar1i/PokemonGo-Bot#3189]
Hi,

Here is my settings about items : 
![image](https://cloud.githubusercontent.com/assets/20993695/17627754/a3e3853e-60b2-11e6-9faf-1f78b3b98db6.png)

And here what the bot display : 
![2016-08-12_17h28_12](https://cloud.githubusercontent.com/assets/20993695/17627803/cf5967ec-60b2-11e6-9a57-894bb2b44cd1.png)

After that, bot still can catch pokemons, it's not a real recycle.

**Comment by pokerave** [comment]
ultraball IS A POKEBALL

**Comment by Turlututu69** [comment]
ok, fixed. Thanks

**Comment by PeakZabver** [comment]
me too bro ! how to unrecycled ? i don't need to recycled my Potion.
