### ISSUE TITLE
TRICKS TO AVOID NIANTIC

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#3190]
reduce the walk speed, mine is currently 10km/h.. patience for those who wants a teleportation 9999km/h  ..we need to wait for devs to have a new solution for this new bans. 
![capture](https://cloud.githubusercontent.com/assets/20971723/17627875/6b2ed26a-60e5-11e6-948b-07fa118ff440.PNG)

USE YOUR BRAIN IF YOU HAVE

PS: 
FIRST DONT MIND THE SKIPPED POKEMON JUST MIND THAT WE GET A LOOT FROM POKESTOPS
SECOND IF YOU CAN GET LOOT FROM POKESTOPS , YOU CAN CATCH A POKEMON OBVIOUSLY (for dumb people)

**Comment by pokerave** [comment]
This is True I have 10k XP/HR

**Comment by TrainerNr1** [comment]
I have a softban with 10kmh also. But think I have to wait for unban!?

**Comment by shengzie** [comment]
mine is just 9km/h lol i dont get why someone have 200 or 9999 even lol

**Comment by generaljoke** [comment]
if you are desperate reduce it more with new ipadds

**Comment by LetMeKnowYourName** [comment]
I use 16 km/h - 800 mts radius. All good, so far. Servers are unstable, though. Even when using a proxy.

Also, I don't set the bot to do everything by itself, only catching pokémon and farming pokéstops. Every hour I check for catched pokémon, transfer, evolve, etc.

**Comment by cinkho** [comment]
necro bot they closed what happen with them

**Comment by XxSHADOWxWOLFxX** [comment]
use 120 km/h in japan yoyogi park (around 60 - 80k xp/h) never got softbans. :)

**Comment by didi271** [comment]
@XxSHADOWxWOLFxX 
Same as you, Disney land Tokyo 150km/h for 5 hours now, nothing happen

**Comment by cinkho** [comment]
https://github.com/NECROBOTIO/NecroBot/releases "shutdown"

**Comment by rvonz** [comment]
its done for necro

**Comment by cinkho** [comment]
what happen with them @rvonz ?

**Comment by AhmedVohra** [comment]
10km/h speed 500 radius, catching pokemons at the same pace, 30k exp per hour 161 poke/h

**Comment by rvonz** [comment]
i dont know

**Comment by generaljoke** [comment]
just be thankful for developers..

**Comment by TrainerNr1** [comment]
have 9kmh now, banned also.

**Comment by rvonz** [comment]
update your bot to latest version dude

**Comment by velfisadri** [comment]
great i can catch pokemons but i cant spin pokestops - any solution ?

**Comment by geebart1337** [comment]
10km/h 300m radius in san francisco pier 39, 30kexp/h ~100 pokemon working fine for 4 hours now.

My other Account wich run the night with 150km/h got "banned", but i can login on the phone, use pokestops and fight arena, but can't catch pokemons since 4 hours or so.

**Comment by cinkho** [comment]
https://github.com/NECROBOTIO/NecroBot sayonara necrobot! :(

**Comment by rvonz** [comment]
20km/h 5000 radius
10k exp per hour 30 poke per hour
anyone have best location with many pokemon?

**Comment by Baanksim** [comment]
There are differents softbans i think... I can catch pokemons but have no rewards on pokestops... We just have to wait and see what will happen ;)

**Comment by AhmedVohra** [comment]
^ Fort Mason, San Fransisco.

**Comment by rvonz** [comment]
thanks dude

**Comment by ShujiYagami** [comment]
Paris, France, 25km/h not softbanned for a while.

**Comment by JCortexs** [comment]
Santa monica 12km/h , 9hrs and keeps working
