### ISSUE TITLE
Der "Transfer" klappt nicht ganz

### ISSUE THREAD

**Issue by ItsMeBrian** [Ar1i/PokemonGo-Bot#3191]
Wenn ich einstelle, dass er alles unter 95% IV transferiert (egal wie hoch die CP ist) will er es nicht tun. Schlussendlich muss ich immer wieder die Pokemon manuell versenden. Dasselbe mit den CP's.

**Comment by knightofdemons** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8983377/17628196/892a9b86-60b4-11e6-9b05-5432ec0a6507.png)
versuch die einstellungen, klappt bei mir super

**Comment by ItsMeBrian** [comment]
Aber wenn ich da den Haken reinmache, also bei den Pokemon oben, dann sollte er die ja nicht verschicken, oder wie darf ich das verstehen? Wie funktioniert das dann?
