### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by xxKevinSniperxx** [Ar1i/PokemonGo-Bot#3192]
http://i.imgur.com/FOa4sO2.png

i'm on the latest version
when i turn off the pokemon list gui i only get the grey message 
i checked and my wifi works perfectly fine and nothing is interrupting the connection

**Comment by nickpkm** [comment]
same here

**Comment by iZ4iN** [comment]
same here

**Comment by iZ4iN** [comment]
But i think this is because the servers are down.
