### ISSUE TITLE
Exception caught, writing LogBuffer.

### ISSUE THREAD

**Issue by zyxelgg** [Ar1i/PokemonGo-Bot#3194]
I didn't modify anything in any config, but suddenly shows me the error message, anyone can help for that?

**Comment by zyxelgg** [comment]
![ff](https://cloud.githubusercontent.com/assets/20980801/17628481/0e9fff80-60e8-11e6-94e4-3a57f93cc5a1.jpg)

**Comment by Delivator** [comment]
This is not the NecroBot.
