### ISSUE TITLE
missing pokemon all the time

### ISSUE THREAD

**Issue by stbbworld** [Ar1i/PokemonGo-Bot#3196]
hi guys,

well its missing the pokemon all the time. or the pokemon got away. 
![error](https://cloud.githubusercontent.com/assets/7337466/17628525/f81ae57c-60b5-11e6-9976-a6677ebaf7e2.png)

thanks for all your hard works. 

greetings

bala

**Comment by hbchang** [comment]
Same here! my items are full.

**Comment by AhmedVohra** [comment]
Restart the bot. 
Worked for me.

**Comment by stbbworld** [comment]
oke i will try

**Comment by Baanksim** [comment]
You are softbanned... Are you getting rewards from pokestops ? If not u maybe have no more pokeballs to catch pokemons ;)

**Comment by generaljoke** [comment]
CLOSED ISSUE
