### ISSUE TITLE
PLEASE CLOSE ISSUE PAGE!!! PPL ARE RUINING THE HOLE PROJECT!!

### ISSUE THREAD

**Issue by MocroMind** [Ar1i/PokemonGo-Bot#3199]
DEAR @Ar1i ,

Can u please close this issue page and shutdown any communication with ppl who use the Bot?
Empty your mind and try to fix it, if its not fixable then GG np u gave us a nice time and ppl dont even appreciate something you gave them for FREE! 

BLEHH bullshit flamekids

**Comment by Baanksim** [comment]
+1

**Comment by monchen** [comment]
+1 too many idiots

**Comment by zzzz9999** [comment]
@Ar1i check this topic

**Comment by SkyWalkerMc** [comment]
@Ar1i please close issue tab

**Comment by Millenniunn** [comment]
I saw he closed it half hour ago, then reopened it, idk why.

**Comment by MocroMind** [comment]
Yeah because ppl are spamming him with nonsense.
one big unthankful mess

**Comment by starscream151** [comment]
![untitlevjhhgvgvhjghvghgvghvgvd](https://cloud.githubusercontent.com/assets/20950801/17628767/2126be5c-60e1-11e6-9fda-05eb51f86fd4.png)

**Comment by jodirt282** [comment]
Close issues till server become stable.
