### ISSUE TITLE
It can't find any PokeStops in a range of 5000m

### ISSUE THREAD

**Issue by Idelan94** [Ar1i/PokemonGo-Bot#320]
So I just installed the las update and It says "We can't find any pokestops in a range of 5000m" I have the coordenates set in central park so I don't know whats going on

**Comment by NWExKraken** [comment]
same issue here

**Comment by 55any99** [comment]
me too

**Comment by DevPXL** [comment]
Go to a other location i had the same porblem but i change my location and it works fine

**Comment by Kjiz** [comment]
Or go to the Config folder and delete the Last Coords

**Comment by DevPXL** [comment]
or so than its work ^^

**Comment by 55any99** [comment]
what 2500 secs how an i fix it

**Comment by classiemoodo** [comment]
I got the problem also. First it works and now i got the same problem. I have deleted "Last Coords" and change location but nothing hapens.

**Comment by classiemoodo** [comment]
It's working again by me. I have delete the player profile and Last Coords and he works by me.
