### ISSUE TITLE
Goodbye? ;(

### ISSUE THREAD

**Issue by DargQ** [Ar1i/PokemonGo-Bot#3200]
Will you close your bot like Necrobot?Due to legal action being started against other bot creators/devs

**Comment by generaljoke** [comment]
**# for god sake just shut up, delete this stupid post
for god sake just shut up, delete this stupid post**

**Comment by monchen** [comment]
stop dragging other people down with your failures. you have crab mentality issue.

 i guess your tone of the owner of "paid bots" who cannot fix their own bot and and just copy coding from AR1i.

**Comment by zzzz9999** [comment]
@DargQ CLOSE THIS !

**Comment by Serg02** [comment]
what a sad guy :(
