### ISSUE TITLE
i use phone spin pokestop get nothing. 

### ISSUE THREAD

**Issue by lancelkh** [Ar1i/PokemonGo-Bot#3201]
I already try spin 40-50 still same cannot get pokeball , use bot it will skip spin pokestop and show my item full , but I use phone check my item not yet full , whos can solve? already try reopen bot and restart pc.

**Comment by MocroMind** [comment]
U are banned. There is no fix yet.
#patient !

**Comment by pokerave** [comment]
call ur mobile provider your phone is damage

**Comment by Auranixide** [comment]
Put your phone in the microwave, that works.
