### ISSUE TITLE
Error : We are within 40 meters of the target. Slowing down to ~10/km to not pass the target.

### ISSUE THREAD

**Issue by NiowGo** [Ar1i/PokemonGo-Bot#3204]
![error running](https://cloud.githubusercontent.com/assets/20826867/17628870/aac5e8e2-60b7-11e6-973e-c8855afe0db8.PNG)

**Comment by NiowGo** [comment]
Config 9/km

**Comment by HeIIoWorld** [comment]
you can't read, right? that's not an error

**Comment by jodirt282** [comment]
It's not an issue ffs.

**Comment by NiowGo** [comment]
No :c

**Comment by zzzz9999** [comment]
even with 9km on settings is giving that message

**Comment by NiowGo** [comment]
![error running 2](https://cloud.githubusercontent.com/assets/20826867/17629171/60b1fd0c-60b9-11e6-9f72-4f5596660e2b.PNG)
