### ISSUE TITLE
how ı can remove unban 

### ISSUE THREAD

**Issue by FarukReis** [Ar1i/PokemonGo-Bot#3206]
# how ı can remove unban  urgent answer

**Comment by kazzaluis** [comment]
RIP

**Comment by generaljoke** [comment]
RIP

**Comment by deface0x2** [comment]
#3199

**Comment by FarukReis** [comment]
1337

**Comment by patrayat5505** [comment]
RIP ENG

**Comment by FarukReis** [comment]
![ekran alintisi](https://cloud.githubusercontent.com/assets/20926821/17629566/afcda972-60c3-11e6-841f-0d5ebe5e39fc.PNG)
