### ISSUE TITLE
Japanese / Chinese chars is showing ????????

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#3208]
When farming on Japan/China with those characters in pokestops names, on console it appears ??????

![bot1](https://cloud.githubusercontent.com/assets/20780971/17629257/63a69b74-60b1-11e6-9d1a-5ae0caec9629.png)

**Comment by Millenniunn** [comment]
u need to install Chinese language package... nothing wrong with the bot.

**Comment by zzzz9999** [comment]
where can I find that

**Comment by zzzz9999** [comment]
install in Windows?
