### ISSUE TITLE
error reloading pokemon list

### ISSUE THREAD

**Issue by blukutuk** [Ar1i/PokemonGo-Bot#3209]
![err](https://cloud.githubusercontent.com/assets/20994560/17629269/b43925ca-60e3-11e6-910c-68c69ae5b1a5.jpg)

how solve this ... help me...

it works until i change the coordinate and then show message at the picture
after that i also can't login with my smartphone...
but i use another id, it works.
banned?

**Comment by zzzz9999** [comment]
That is during login, before getting pokemon list ...

**Comment by osnake** [comment]
wait for update
