### ISSUE TITLE
I got permanent ban, you guys should be more careful !

### ISSUE THREAD

**Issue by Necrofilia** [Ar1i/PokemonGo-Bot#3211]
Hey i got permanent ban, i cant use bot using my 1 account and i cant open my account in any pokemon go!  But i can open my other account!
![untitled](https://cloud.githubusercontent.com/assets/20994814/17629308/e12d1f32-60e3-11e6-8819-104c36b9d0f5.png)

**Comment by zzzz9999** [comment]
Hey! You use a bot! You risk!
Stop complaining!

**Comment by Necrofilia** [comment]
read title dude

**Comment by zzzz9999** [comment]
sorry

**Comment by zzzz9999** [comment]
(sorry)

**Comment by iZ4iN** [comment]
i dont think that this is a perma ban. Just the servers i think.

**Comment by Necrofilia** [comment]
i can use my any other account in bot or pokemon go, only this one account that i cant use......
i guess it is a permanent ban maybe, let just wait and see

**Comment by blukutuk** [comment]
hahahahaha... same like me
![err](https://cloud.githubusercontent.com/assets/20994560/17629432/81a370e2-60e4-11e6-815c-fa74c4eccd22.jpg)

**Comment by blukutuk** [comment]
i can open my other account too

**Comment by iZ4iN** [comment]
I have the same problem but when i login with my phone it says they having server problems.
So why you should be banned than.

**Comment by Necrofilia** [comment]
yea try login using with you other account dude.

**Comment by blukutuk** [comment]
with my phone i can't play too

**Comment by Treeckors** [comment]
if it is google, theyre down for some people, when i load up my app when i go to choose google login it cant even open it up, its stuck on buffering

**Comment by marcop888** [comment]
yeah me too.. hope its just server doen..   T_T

**Comment by Necrofilia** [comment]
yea let us just wait and see guys, i hope it is just the server!

**Comment by iZ4iN** [comment]
I use PTC
And my other account is still working (google) and botting level 33.

**Comment by blukutuk** [comment]
necrofilia, may i ask you.
that message show after doing what?
or suddenly appear?
from me, that message appear after bot stuck and i change the coordinate. and then...error
