### ISSUE TITLE
Can´t load bot with any account(google, pokemon trainer club)

### ISSUE THREAD

**Issue by darkaelv** [Ar1i/PokemonGo-Bot#3213]
That is, I can´t use the bot because display a code error.
![sin titulo](https://cloud.githubusercontent.com/assets/20994891/17629333/61af0658-607f-11e6-8011-7ab21062a649.png)

**Comment by generaljoke** [comment]
DL LATEST VERSION

**Comment by darkaelv** [comment]
I have this: Latest Build - 12.08 16.59.rar

**Comment by MocroMind** [comment]
Permabanned..
Niantic started banning bot users permanently

RIP bro

**Comment by darkaelv** [comment]
But I can enter from the app and play normal
