### ISSUE TITLE
thx you come again Ar1i . proud of you . cheers

### ISSUE THREAD

**Issue by totalyfailed8** [Ar1i/PokemonGo-Bot#3216]

**Comment by yaowa** [comment]
bravo ar1i! Any news on if perma bans have been issued?

**Comment by TrainerNr1** [comment]
welcome back.

**Comment by xRealMaks** [comment]
:+1:

**Comment by Damindo25** [comment]
^xD

**Comment by emilie253** [comment]
what's happen? finish, no finish?

**Comment by Farox1988** [comment]
Ok help me??? is this bans or google fail ?

**Comment by dstN** [comment]
oh my god. he deleted all issues because you kids are too dumb to realize what "issues" are... can you please just f... off to twitter or anywhere else? thank you.

**Comment by BradleyFlorence** [comment]
wait what happened ?

**Comment by emreaslantas** [comment]
can we login the bot ?

**Comment by Farox1988** [comment]
give me news pls whats going on today^^

**Comment by yaowa** [comment]
Pretty sure its server issues guys. Calm down

**Comment by k756u** [comment]
nice nice nice nice!!!!!!!!!!!!!!!!!!! :D :+1:

**Comment by totalyfailed8** [comment]
dont make his mad again.. just follow the ruless~ ez ggwp

**Comment by Ar1i** [comment]
Thanks! But this isnt a issue, so I am closing this here. But thanks!

**Comment by Hydro420** [comment]
Im sure Ar1i knows we all appreciate what the team is doing here & his bot.. Now lets respect the fact that they are most likely trying to clean these threads up.

**Comment by NexusCore07** [comment]
@yaowa https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by BradleyFlorence** [comment]
hui
