### ISSUE TITLE
Not an issue, just a question or two :)

### ISSUE THREAD

**Issue by zozomerf** [Ar1i/PokemonGo-Bot#3220]
Alright so to start, I really appreciate all of the constant work you folks are putting in. With this new update, there are a few things I don't really understand. In extremely basic terms, could someone explain what the "Random Sleep @catching 1-3 seconds" function does? Also, under the device section there is no selection for the iPhone 5S which I use. I'm not sure what it does, or if it even matters, just posting about it just in case. The last question I have is how much does the altitude in your location settings change your chances of finding pokemon, if there is any change at all?

Thank you very much,
Lucas Szczesny

**Comment by Ar1i** [comment]
It adds more seconds, before catching.. And the device is, that not everyone using the bot uses the same device!
