### ISSUE TITLE
Livechat?!

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#3221]
@xJustx has nothing to do.. Soo here is a LiveChat he will try to help you. 
http://poke-support.ar1i.xyz/

But take some waiting time..

**Comment by mhicarl** [comment]
is it true that once we open the newly updated file will remove all rare pokemons that we have?
This is a question..

**Comment by Ar1i** [comment]
No?

**Comment by mhicarl** [comment]
okie thanks for your work

**Comment by WhoBotWhoBad** [comment]
I think you should ask that queston is the poke-support Ar1i just posted

**Comment by mhicarl** [comment]
oohh ok. thanks

**Comment by malekisma** [comment]
@Ar1i  Thank you arli ♥

**Comment by Kapperoni** [comment]
I had like 4 questions and one issue. I was in the middle of typing and stuff, the live chat suddenly left?

**Comment by ILikeBots** [comment]
Is it save to use the bot now? Or does the unban thing not work anymore?

**Comment by IamcoolzSnoxd** [comment]
The unban thing was patched by Niantic, you can still use the bot without a problem but if you get soft banned, there's no way around the wait time now.

**Comment by mhicarl** [comment]
There's a queue on live chat support so i we better wait for the answer to our questions

**Comment by ILikeBots** [comment]
Oh okey, are the dev's working on it right now? And btw the soft bans are 3 hours right? Sorry for some bad english, i'm from the Netherlands.

**Comment by cirnolp** [comment]
Botstatus is "Use at your own risk."
Niantic is definately starting to fight against bots with... eh... "enhanced Bans". So if you dont want to loose your account, wait for an official response that it's safe.

**Comment by rvonz** [comment]
i try the unban and its work?!

**Comment by explore01** [comment]
dude, you are the best!

**Comment by ILikeBots** [comment]
rvonz wait really?

**Comment by JaymzThomasson** [comment]
I imagine Ari is trying to figure out a way around it, the bot is fine to use.

**Comment by rvonz** [comment]
yeah for sure

**Comment by mhicarl** [comment]
yeah the whole bot system works fine

**Comment by ILikeBots** [comment]
Wait this is confusing. Is the unban working or not?

**Comment by fourmansyah** [comment]
Thanks For Your Hardwork Mr. ar1i ... U are The MAN

**Comment by elenex23** [comment]
Bot is working fine. Just let me know if you find a new way to unban accounts =p

**Comment by JaymzThomasson** [comment]
The unban has been patched, so it is not. I am not sure what that other guy is saying.

**Comment by adjam1992** [comment]
Hi , I've problem, literally dont got the pokeballs/exp from pokestops :s help?

**Comment by godzadid** [comment]
Thx U very much i form thai i can talk in eng but i can say thx u very much for come back my bro . . . .

**Comment by ILikeBots** [comment]
adjam you're inventory is probably full with potions etc. Unban, than go to youre phone and throw away some potions and berry;s

**Comment by adjam1992** [comment]
I tried it, my inventory has 186/350 and the problem persist, its so wtf, and I'm not banned lol

**Comment by oOPaikiaOo** [comment]
error reference not set to an object, cannot load pokemon list.
restarting

what seems to be the problem?

**Comment by fourmansyah** [comment]
may be this Can help Your all Problem ... 
just download HotspotShilt ELITE Version ... And change The County To Great Bretain ..i tested it Work 100% ??

**Comment by jmo93** [comment]
one question, is this a soft or a permanentban? because I change my IP and still can't log into the normal app.

**Comment by JJhonh** [comment]
If you get softbanned you will need to stay 20 min without playing or trying to log in

**Comment by liklaysh** [comment]
Ar1i thank you for your work!

**Comment by fourmansyah** [comment]
And After bot .. u want open your account in Emu Or Phone .. First Open The Bot And Change The Location To u True Location and Press Force Unban .. after u unbanned And Open Your account in EMU or Phone .. I tasted It 100% Works..

**Comment by rvonz** [comment]
ahh I forgot to say .. welcome back @ar1i :D

**Comment by ILikeBots** [comment]
With the device thing it does not show iphone.. isn't it needed if you bot on iphone?

**Comment by yordanfy** [comment]
Thanks and WB @Ar1i ..... You're the real MVP...

**Comment by Killmachine** [comment]
I have waited for half an hour just to see the message "the representitive has left the conversation". He didn't even say anything lol.

**Comment by iZ4iN** [comment]
Yeah nice : Momentan sind alle Berater in Beratungsgesprächen, wir bitten um etwas Geduld. Ihre Position in der Warteschlange: 9. Die voraussichtliche Wartezeit beträgt 1 Minute(n).
Bitte haben Sie noch etwas Geduld, falls Sie nicht warten möchten können Sie uns eine Nachricht hinterlassen. Vielen Dank!
Momentan sind in dieser Abteilung keine Berater aktiv, bitte probieren Sie es zu einem späteren Zeitpunkt erneut oder hinterlassen Sie uns eine Nachricht: Nachricht hinterlassen. Vielen Dank!

**Comment by adjam1992** [comment]
I'm not getting exp/pokeballs from pokestops, help !  /  My inv has many slots :s

**Comment by ILikeBots** [comment]
Adjam, try to re-install the bot. That will probably work. Maybe you did change something accidentally.

**Comment by rvonz** [comment]
change your ip, wait for 20/30 minutes and reopen bot

**Comment by adjam1992** [comment]
ok thx, I'll try that

**Comment by cadenpopps** [comment]
live chat did nothing lol, just left

**Comment by hsc2712** [comment]
All pokemon got away. cannot catch.
Tried to reboot the router also change the location.

**Comment by adjam1992** [comment]
hsc2712 check if you have pokeballs and space in your inv

**Comment by hsc2712** [comment]
yes, a lot of space.
Pokemon 355/500
Item 601/1000

**Comment by s4db** [comment]
when bot found pokemon it cant catch them alway say "got away" or log "Error catching Pokemon: EncounterNotinrange"

**Comment by rvonz** [comment]
I'm confused, why i cant transfer nidoranfemale?!

**Comment by pokerave** [comment]
https://discord.gg/w43Wp6Q   -- MAYBE this?

**Comment by AiVo7z** [comment]
@rvonz maybe the bot sent it away alrdy or evolved it..

**Comment by juanmiconlup** [comment]
The soft-unban, doesn't work :(

**Comment by hbchang** [comment]
I can farm pokestop but cannot catch any pokemon. Is this kind of soft-ban? By the way, I have pokeballs.

**Comment by juanmiconlup** [comment]
@hbchang same as me, I think it's a soft-ban cause we haven't received any letter from niantic yet

**Comment by s4db** [comment]
log "Error catching Pokemon: EncounterNotinrange" when bot catch any pokemon   : c

**Comment by hbchang** [comment]
@juanmiconlup I can also fight in a Gym. :)

**Comment by adjam1992** [comment]
I cant farm pokestops/ cant catch pokemon, but I can join in my phone normally

**Comment by gummyruler** [comment]
@Ar1i The new softbans is it possible to bypass it once again? Like our force unbans?

**Comment by adjam1992** [comment]
Im no banned, I catch a charmander 30seg ago :s

**Comment by Rolandian** [comment]
I can't farm any pokestop but I can catch pokemon and everything else goes fine as well. I don't know if anyone knows how to fix this?

**Comment by rvonz** [comment]
press the button unban repeatedly, maybe it could be.... :D

**Comment by urangotango** [comment]
Atm niantic is crazy like shit and make an ban zunami

**Comment by urangotango** [comment]
And this is an official notice.. and as zpu can see  on official pokemon Web site theyou add an part wehre you can appeal to bans since this morning after this implementation banns startet
