### ISSUE TITLE
Permanent Bann oder nicht?

### ISSUE THREAD

**Issue by legMissingNo** [Ar1i/PokemonGo-Bot#3225]
Hallo,
Ich habe deinen Bot gerne genutzt und finde es auch sehr gut, dass du weitermachst, aber ich habe mal eine Frage an alle, die sich mit den Bannverhalten in Pokemon Go auskennen. Was ist das für ein Bann?:
Ich kann Pokemon fangen, aber keine Arenen benutzen und wenn ich einen Pokestop ansteuer, sagst der mir, ich solle es später noch einmal versuchen...
Wäre nett wenn zurück geschrieben wird, villeicht weiß ja jmd eine Lösung oder weiß, welche bannart das ist...

**Comment by Ar1i** [comment]
#3218 wissen momentan auch nicht mehr.

**Comment by malekisma** [comment]
Kann sein das es eine zeitsperre ist oder nicht?

**Comment by AiVo7z** [comment]
Bei mir das Gleiche, schon seit mehr als 8 Std. Einziger Unterschied zu dir, ich kann alles machen außer Pokestops also auch Arenen usw. wirklich nur Pokestops.

**Comment by MomoGER** [comment]
Hey, Ar1i und die andren ich kann nicht so gut Enlisch des sonnst würd ich nicht extra fragen bei steht Spieldaten konnten von Server nicht abgerufen werden ich hab ein Bann das weiss ich komme mit andren ACC rein ausser den einen und woher die Info von der Seit http://www.giga.de/spiele/pok-mon-go/news/achtung-betrueger-in-pokemon-go-werden-nun-dauerhaft-gesperrt/
ich wollte frag ob ihr wisst wie man den Permabann fixt sag ich mal
