### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by bunnymuny** [Ar1i/PokemonGo-Bot#3226]
######################## RULES. READ BEFORE POSTING! ########################

I would like to suggest to add delay between sweep and sweep thanks!!!

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by dstN** [comment]
before posting an issue:
 
delete the template which is now shown in your post.
