### ISSUE TITLE
STOP FLOODING STUPID QUESTIONS, IDIOTS

### ISSUE THREAD

**Issue by monchen** [Ar1i/PokemonGo-Bot#3227]
STOP FLOODING AR1i PAGE. HE IS DOING THIS FOR FREE. SO STOP BEING DEMANDING. 
LEARN TO GOOGLE AND READ OPEN AND CLOSED ISSUES TO SOLVE YOUR PROBLEM.

**Comment by PokemonGoer** [comment]
This doesn't help...

**Comment by monchen** [comment]
DSTN, I HURT YOUR FEELING? IDIOT

**Comment by BigManTyrone** [comment]
this is only your isue plz close

**Comment by rvonz** [comment]
please close if you want to help ar1i

**Comment by dstN** [comment]
i hope Ar1i closes the issues again.. this is such bullshit with this 12yr old children

**Comment by monchen** [comment]
DSTN HURT. DONT CRY

**Comment by bboylost** [comment]
if you want to help and support, click donate button @monchen
