### ISSUE TITLE
IP / Proxy section not working

### ISSUE THREAD

**Issue by Tymoc** [Ar1i/PokemonGo-Bot#3228]
I purchased a private proxy, enter the information with Authentication and it doent work.  Is that section still working?

I tried without the IP and it works fine... once I enter the IP - nothing works.

Help?

**Comment by bboylost** [comment]
Check with the private IP, the bot itself works.

**Comment by jodirt282** [comment]
Proxy does not work for me. Using VPN it unban me right away. Using proxy no unban. Tried over 100 proxies.

**Comment by k3npachi** [comment]
one proxy dont protect from **Web Rtc leak** , niantic can see your real IP 

proxy is in bot, not protect your full connexion

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
