### ISSUE TITLE
New tab with rare pokemons

### ISSUE THREAD

**Issue by Eizoman** [Ar1i/PokemonGo-Bot#3229]
Hi,would like to see in next update a new tab rare pokemon that is based on the website http://pokesnipers.com. It is possible?

**Comment by Hydro420** [comment]
Go slap yourself for posting this in an issue thread please

**Comment by bboylost** [comment]
in the heat of moments like this , can you not request anything more ? Ar1i wanted to give up the bot earlier today and now he come back for us, doing it for free. Be glad of what you are having .

**Comment by bboylost** [comment]
Dickhead.
