### ISSUE TITLE
Issues running new bot?

### ISSUE THREAD

**Issue by tripout** [Ar1i/PokemonGo-Bot#3230]
When I run the new bot, I now get the following errors showing up on the screen.  It continually tries to reconnect.

https://i.imgur.com/fvEkyy3.png

**Comment by dstN** [comment]
i'm not quite sure, but it seems thats the "ban"-message. cause i can't log in with phone either.

**Comment by tripout** [comment]
I tried with the new "Hotfix" build as well.

**Comment by cadenpopps** [comment]
this seems like more of a bot issue or server issue, doesn't really seem like a ban message lol. but i'm getting the same error

**Comment by dstN** [comment]
yeah, me too. but with phone it says "Couldn't retrive data from server".

**Comment by Sparta1990** [comment]
new update no more force unban??

**Comment by Ar1i** [comment]
Probably servers. Try to wait some time.

**Comment by cadenpopps** [comment]
i just logged in with an account that i am sure isnt banned, and got the same message

Pretty much a new account

**Comment by kizziace** [comment]
servers getting an update?? I'm having the same problem, even made a new account just to check...

**Comment by tripout** [comment]
if you made a new account and are getting that same message I would guess it's with the servers then.

**Comment by dstN** [comment]
i can play with freshmade account.

**Comment by kizziace** [comment]
that's odd now I can get on to one of my accounts, but with my google account I cant get on
