### ISSUE TITLE
Add Iphone Device to Device Menu

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#3231]
I don't Know how to start a Pull Request 

i'm a Iphone User and only see Android Device, can you add them ?

**Comment by Hydro420** [comment]
Dont request anything at this moment... No one is certain which route the bot will take or if it will even continue to operate.

**Comment by cadenpopps** [comment]
it doesnt matter...?

why would you waste everyones time with this request?

**Comment by Ar1i** [comment]
The API Requests are from Android phone.. it isnt a good idea to make iPhone requests then. And thats not needed atm!
