### ISSUE TITLE
What does this mean its in German

### ISSUE THREAD

**Issue by Safti54** [Ar1i/PokemonGo-Bot#3232]
![issue pokebot](https://cloud.githubusercontent.com/assets/20845060/17632718/2eea9fca-60ca-11e6-8a00-1d43f7b3e490.PNG)
 was heisst das?

**Comment by Safti54** [comment]
i cant choose any altutude in the bot and on my phone i cant login

**Comment by Ar1i** [comment]
Servers down probably

**Comment by Ar1i** [comment]
#3233
