### ISSUE TITLE
We can't find any PokeStops which are unused.

### ISSUE THREAD

**Issue by Killmachine** [Ar1i/PokemonGo-Bot#3236]
I get this error message when I try to log in and start the bot with a Proxy (the one the bot provides).
When I don't start the bot with the Proxy active, however, the bot can detect the pokestops, spin them but can't catch any pokemon because they flee (softban). Many players are experiencing this as of now and I decided to take the lead and post about this specific problem.

Any suggestions and ideas?

![issue](https://cloud.githubusercontent.com/assets/20741707/17632947/b5cf492e-60d3-11e6-91d2-11e68db7c684.jpg)

**Comment by HeIIoWorld** [comment]
unknown kind of ban just wait 'til we know more about that

**Comment by Perfectibilist** [comment]
I also having this problem, i hope someone will figure it out soon

**Comment by Killmachine** [comment]
@HeIIoWorld Seems like Niantic can now detect if we use Proxy or not judging from the fact that my bot behaves completely different when I use Proxy and when I don't. There seems to be two different types of bans and I get this one (which don't let any PokeStops to appear) when I use the Proxy, and I get the classic flee softban when I don't use it. But, yeah. We can only wait to find out I guess.

**Comment by wimpo** [comment]
not really hard to search an ip address for location and the cross reference with actual location. when km with used ip and actual location is more than 50 km? is ban?

**Comment by HughJanos** [comment]
I have a bit different problem with pokestops. I can see them when using the app and the bot finds them too but i cant use them - i spin it but nothing happens, just text pops up that says: try again later.

**Comment by Kaizhoul** [comment]
STOP ASK THE SAME QUESTIONS, IT'S A BAN IP

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
