### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by abcderfg** [Ar1i/PokemonGo-Bot#3238]
Cant start the game!
![drtzzhgdz](https://cloud.githubusercontent.com/assets/20824352/17633066/e0b67282-60cb-11e6-94d4-c5db75d2da7f.PNG)

**Comment by kickz** [comment]
Try delete the pokemon list and run again

**Comment by ProGO1** [comment]
i have the same problem i think we got banned

**Comment by dstN** [comment]
#3233

**Comment by abcderfg** [comment]
haha ok thx can u still login with that acc on ur phone?
