### ISSUE TITLE
help me bot works but dont catch pokemons they get away every time

### ISSUE THREAD

**Issue by ProGO1** [Ar1i/PokemonGo-Bot#3239]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by HeIIoWorld** [comment]
Softban or an unknown ban that is going around atm

**Comment by pokerave** [comment]
#3218

**Comment by dstN** [comment]
"Describe your problem!

Add a screenshot!"

"Dont forget to delete this template!" 

.. close please.
