### ISSUE TITLE
how ı can remove unban 

### ISSUE THREAD

**Issue by FarukReis** [Ar1i/PokemonGo-Bot#3240]
how ı can remove unban urgent answer

![ekran alintisi](https://cloud.githubusercontent.com/assets/20926821/17633098/6476e66c-60d4-11e6-85c0-a9cdc437ca9e.PNG)

**Comment by pokerave** [comment]
#3218

**Comment by kickz** [comment]
When you got ban, so try wait some seconds after that i got unban.

**Comment by Requal** [comment]
Remove unban?
So you want to be banned?

**Comment by DiTechRacer** [comment]
xD

**Comment by FarukReis** [comment]
If I wait will it open again?
