### ISSUE TITLE
Cant catch a pokemon when out of normal pokeball

### ISSUE THREAD

**Issue by jamskie08** [Ar1i/PokemonGo-Bot#3242]
![image](https://cloud.githubusercontent.com/assets/20888201/17633367/82fb4f30-60ff-11e6-8947-18b789741656.png)

I Think bot dont use great ball and ultra ball

Please help?

**Comment by cadenpopps** [comment]
banned

**Comment by jamskie08** [comment]
but i can still use normal pokeball and catch them with any pokeball when not using bot?

**Comment by starscream151** [comment]
#3218

**Comment by jamskie08** [comment]
I can catch pokemon when using old bot
![image](https://cloud.githubusercontent.com/assets/20888201/17633630/d835abf2-6100-11e6-87b1-36df6b7bccd7.png)

**Comment by pendeus** [comment]
This is my problem..pls help guys i cant catch any pokemon

**Comment by jamskie08** [comment]
use old bot it will work

**Comment by pendeus** [comment]
I'm using old bot but doesen't work ( xycz..... got away while using itemgreatball/pokeball)

**Comment by LordBunny** [comment]
I got the same problem

**Comment by hknshn** [comment]
same problem about 1 hour

**Comment by urangotango** [comment]
i got the same problem on 1 of mine accounts just log them off and try again in 24hours..  **seems** some kinda of advice ban to show you that they know you did use some 3th party software. 

lets see if in 24h the accounts rrun normaly

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
