### ISSUE TITLE
Go Bot Not Catching Pokemon

### ISSUE THREAD

**Issue by DEEE38** [Ar1i/PokemonGo-Bot#3243]
![pokemongo](https://cloud.githubusercontent.com/assets/20997293/17633520/9a777e72-6082-11e6-9d9d-ebeedb8af21b.png)

**Comment by Daud1337** [comment]
soft-ban

**Comment by HughJanos** [comment]
i have the same thing - cant catch any pokemon and also i cant use pokestops - i can see them but nothing happens after spinning them

**Comment by omega2016** [comment]
same here.. not catching any and getting soft bans a lot

**Comment by dragonuts330** [comment]
its something different, I can use the pokestops and get items. but the pokemon still run. I have all the balls it requires.

**Comment by DEEE38** [comment]
I dont think its soft bans. Pokestops are fine it is just not catching any Pokemon

**Comment by DEEE38** [comment]
I think the server is detecting the bot and somehow not allowing it to catch the pokemon at all

**Comment by DEEE38** [comment]
Anyone else having this same issue?

**Comment by slobro** [comment]
Niantic going mental in banning...can't blame them either

**Comment by jamskie08** [comment]
I have the same issue, Pokemon will run if you dont have pokeballs even you have ultra ball or great ball. i tried collecting normal pokeball first then use old but and it works currently using 12.08.00.16

**Comment by burnSMACKER** [comment]
Definitely not a soft ban, it's affecting bot users wide.

**Comment by Abbasoo** [comment]
How can i un-ban my acc?
It has been 7 hours.

**Comment by hknshn** [comment]
same problem how can i fix it

**Comment by Elvete** [comment]
my acc is still baned after 15 hours

**Comment by urangotango** [comment]
i got the same problem on 1 of mine accounts just log them off and try again in 24hours.. # **seems** some kinda of advice ban  to show you that they know you did use some 3th party software.

**Comment by vitus0123456** [comment]
After 18hrs, i can catch pokemon again.  It is a warning i guess, next time could be a perma ban.

**Comment by DylanBeek** [comment]
Okay guys, I have very good news for the people who recieved a soft ban i.e. being able to loot pokéstops but not being able to catch any pokémon, (catch/flee).

That is what happend to me this morning, and as of now my softban has been lifted. I have never felt so good to catch a 10cp pidgey!😉

Anyway, for the conspiracy theorists among us. I am sorry I do not have any proof of this, you've just got to trust a complete stranger for once. Wanted to share the good news, I'll be staying away from botting for a little while.

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
