### ISSUE TITLE
Softban after mass transfer/mass evolve

### ISSUE THREAD

**Issue by Fertigpizza** [Ar1i/PokemonGo-Bot#3244]
getting softbans after mass transfer/mass evolve. Maybe put in a delay there too? (like with catching pokemon)

**Comment by cadenpopps** [comment]
the latest version includes a delay.

also read other posts and use newest version before posting an "issue"

**Comment by elenex23** [comment]
had the same issue, just got one of my bots banned because of mass evolve. am using most up to date build

**Comment by Fertigpizza** [comment]
@cadenpopps : There's only a delay for catching pokemon, not for transferring/evolving....

**Comment by cadenpopps** [comment]
youre lucky if you can get it working at all honestly... just turn off the features until ar1i fixes it, he said he wont be on until tomorrow
