### ISSUE TITLE
Detected soft ban every 10 seconds??

### ISSUE THREAD

**Issue by lucasxvieira** [Ar1i/PokemonGo-Bot#3247]
it says detected softban and after it says "probably unban you", then again detected softban and keep doing the same thing

**Comment by cadenpopps** [comment]
you are an actual idiot, sir or maam

please read other posts as well as the RULES OF POSTING before posting

**Comment by DiTechRacer** [comment]
Noob Alert!

**Comment by Elvete** [comment]
https://www.youtube.com/watch?v=vfc42Pb5RA8 thats why
