### ISSUE TITLE
some one can help me with this problem? (unhandle exception)

### ISSUE THREAD

**Issue by knight16** [Ar1i/PokemonGo-Bot#325]
![image](https://cloud.githubusercontent.com/assets/20701626/17267384/7171fe5e-5631-11e6-820e-9e266babd861.png)

**Comment by Tochez** [comment]
try redownloading it

**Comment by knight16** [comment]
many time but can't :(

**Comment by Ar1i** [comment]
Google the error it has something to do with your System
