### ISSUE TITLE
How to unban and setting for not get ban easy

### ISSUE THREAD

**Issue by KwangGan** [Ar1i/PokemonGo-Bot#3250]
unban method
1. Open and sign game with you mobile network do not use same wifi with bot instance 
2. try to walk and spin some Pokestop and playing as normal for a while catch some pokemon
this method should fix problem like bot can't find any pokestop or any pokemon around 

for setting 

1. Use speed setting  19 km/h  try to move like human 
2. Use only 1 instance per network 
3. Do not jumping or change coord around world like crazy 

thx!

**Comment by dstN** [comment]
i got banned with using bot in my hometown with 12km/h (for egg hatching) with a radius of 5km.

**Comment by burnSMACKER** [comment]
19kmh is too fast, that is very fast on a bike. Do 10kmh.

**Comment by iOwner** [comment]
@dstN How long ago was that?

**Comment by dstN** [comment]
@iOwner i got banned today. was at the doctor today (1pm) could login without problems. tried to login after Ar1i put the bot on "deactivated" status and it doesn't work anymore. 2 other googleaccs are working (one freshmade, one level 3)

**Comment by Microrock** [comment]
-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

**Comment by blasanru** [comment]
I put 6 km/h... always in Madrid. Its very slow but i think this way you dont get a ban

**Comment by blasanru** [comment]
i will play 3 hours, not all night....i would like prevent ban with this new account

**Comment by dstN** [comment]
well i hope at least that all those level35+ accs gets banned as well if i get banned with a friggin lvl26 account lol.

**Comment by iOwner** [comment]
@dstN i'm most likely banned to then... i left for work at 8:30 and the bot was running fine. Then around 12pm i started seeing people complain the bot wasn't working, and because i was at work and my laptop was at home i couldn't turn it off or until my lunch break at 1:30... lucky my mum was home and turned off my laptop. I just reached level 35 haha not going to log in for about 2 days and see

**Comment by Microrock** [comment]
10 - 13  clear

dl a new version now

u can see your answer why get ban

**Comment by NidiKea** [comment]
My Account ist banned too. It was Level 22 and I always played at the phone, only one time long ago I used a few minutes the bot. I never changed the City or Country.  I did not use it for 4 days and totay the first time and cannot log in. So I do not understand why they banned the account but it was the risk. So now i walk ;-) I think Niantic will get more and more aggressiv against "cheating" , it ist not fine but it was always the risk :-(

**Comment by pepeyon** [comment]
5 km/h man.

**Comment by elenex23** [comment]
I have one account that cannot catch pokemon. So i am having him walk around (8km/h) collecting pokestops only. However I maybe getting stuck on pokemon I'm ignoring. [![new.png](https://s10.postimg.org/ut8f6uem1/new.png)](https://postimg.org/image/hp2uu5mk5/)

**Comment by wackovireshnik** [comment]
Funny guy who oppened this thread for give advice like "19km/h" ...plz better shut up instead of spam, ur words only shit. A human walk to 4-5km/h..even with a bike 12 km/is fast..19 is just worst.

**Comment by SahnCH** [comment]
I'm botting 24/24 in my own town, 46 km/h - 8500m radius
I'm lvl 34, never been banned. 

Several time I though I was banned, but after few hours everything comes back normal.

**Comment by michaelp96x** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20994990/17636038/b8a260ce-60d2-11e6-9a78-7108d3a3d505.png)
I'm level 31. Using an older version of the bot. The settings I have are doing well however XP per hour is a little slow. 
Location is Times Square, New York. 
Speed - 10 km/h
Distance - 5000m radius.

**Comment by daniverr** [comment]
@michaelp96x which version are you using? Can you upload it to MEGA so I can try it?

**Comment by michaelp96x** [comment]
@danvierr sure thing bro. Let me see if I still have it. Also I've changed my speed to 50 km/h and it is still working fine. Just ran out of razz berries so I'm struggling to catch pokemon of a higher level 
![untitled 1](https://cloud.githubusercontent.com/assets/20994990/17636176/8ed2e5c4-60d3-11e6-8898-8ef945242c2d.png)

**Comment by michaelp96x** [comment]
Here's the link and decryption key pal. 
https://mega.nz/#F!o00mDarD 
!c42SeLS8h215by4XLTWJBw

Good luck. 

Personally I think the people running into problems are expecting too much from the bot. Possibly setting the travelling speed too high. Changing location too often. 
Shoutout to the developer(s) for a great bot which is FREE and available to anyone.

**Comment by Elvete** [comment]
Problem as found..trying 2 fix it >> https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by dstN** [comment]
@michaelp96x i don't think thats the problem. i never ever was in another location than my hometown and was never faster than 12km/h. 

i just think that niantic collected account infos since the last update (when the bot wasn't working anymore because of an API update) which have suspicious runtimes / suspicious fast levelling / suspicious long uptime and banned them permanently.

**Comment by schang1987** [comment]
@michaelp96x Thanks for sharing! I'm always using less then 10k/hr

**Comment by michaelp96x** [comment]
@dstN That is very unfortunate and unlucky for you pal. I have been running the bot on 4 different google accounts for the past few days sometimes running the pokesniper bot alongside them w/out a proxy and haven't been perma banned. I was temporarily softbanned roughly 6 hours ago when I used my mobile with real time location while the bot was running but that was the end of that. 

The bot seems to be working great. My only problem now is I have zero razzberries left and pokemon over 500 can't be caught and it seems to be stuck on a continuous loop lol.

**Comment by urangotango** [comment]
another good suggest is if your device is not lisstet in the device list to use an tablet device from the list the most ppl that use smartphones have an tablet at home and they cant say nathing if you use same conecction with phone + tablet same if you use your phone as hotspot .

**Comment by Captnred** [comment]
Not an issue please close this thread.

**Comment by hamburg55** [comment]
If I change the speed to 5 km/h and set the locarion to my hometown would it work without a hardban?

wenn ich die Geschwindigkeit auf 5km/h setze und den Standort nur auf meine Stadt beschränke, könnte ich dann den Bot benutzen ohne einen Permanentbann zu bekommen?

**Comment by darkaelv** [comment]
I can play normal in the app, but when I use the bot have the error in the image
![sin titulo](https://cloud.githubusercontent.com/assets/20994891/17638650/254b2d90-60b1-11e6-894b-1d98a55de83d.png)

**Comment by schn33man** [comment]
Ich wurde gebannt :( hat irgendjemand von euch lieben noch einen Account für mich?  Ich war natürlich nicht so schlau mir einen zweiten Bot anzulegen :/
