### ISSUE TITLE
Error pokestops

### ISSUE THREAD

**Issue by bjandir** [Ar1i/PokemonGo-Bot#3252]
![niantic](https://cloud.githubusercontent.com/assets/20978804/17634210/1ab95a24-6097-11e6-90a2-87bff3a3f3f5.png)

Banned?

**Comment by EvilEmpireDriftTeam** [comment]
now shake yourself via google in the old version of the bot prior to this update with a warning. everything is fine. everything is working swinging. the soft ban was given after a minute unban. and shakes collects pokemon on. everything is fine no ban
And another Trainer using this canoe writes. but it seems to me that it fell off the server
Failed to retrieve game data from the server

**Comment by jodirt282** [comment]
#3236 Duplicate issue again. Can't you guys read?

**Comment by xJustx** [comment]
^
