### ISSUE TITLE
Error reloading Pokemon list: BadAutheniation

### ISSUE THREAD

**Issue by Leasy361** [Ar1i/PokemonGo-Bot#3253]
http://img5.fotos-hochladen.net/uploads/unbenanntcyaktbzro5.png

Help me pls!°

**Comment by dstN** [comment]
#3233 STOP SPAMMING ISSUES

**Comment by jodirt282** [comment]
Read the 100 other issues about it, you will get your answer.
There is nothing to do. Just wait and read #3233

**Comment by cyberwolf888** [comment]
![permaban](https://cloud.githubusercontent.com/assets/8720485/17634967/8881f622-6107-11e6-8cb5-d691daa9cfef.png)

**Comment by xJustx** [comment]
^
