### ISSUE TITLE
can catch pokemon but cant farm pokestop

### ISSUE THREAD

**Issue by funzqlm** [Ar1i/PokemonGo-Bot#3255]
![help](https://cloud.githubusercontent.com/assets/20997903/17634596/a04280a6-60fd-11e6-9313-a7059ee70c5f.png)
im testing in pokegobot and my iphone 
in bot see pic i cant farm pokestop but can catch pokemon
in iphone roll pokestop it say try again later and can gym fight, can catch pokemon
now my pokeball has down buz cant farm pokestop Can help?

**Comment by dstN** [comment]
sounds like a softban. maybe stop botting / playing for the next 1-2 days and it should be great again, but maybe you get flagged with a warning already.

**Comment by velfisadri** [comment]
i have same issue since today morning ;(

**Comment by funzqlm** [comment]
@dstN Thanks for suggest
@velfisadri Me too :(

**Comment by cyberwolf888** [comment]
![permaban](https://cloud.githubusercontent.com/assets/8720485/17634959/83d30346-6107-11e6-9fab-b8c46dbe4efa.png)

**Comment by dstN** [comment]
@cyberwolf888 this doesn't sound like a permban.

**Comment by cyberwolf888** [comment]
@dstN read this for more information
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by dstN** [comment]
@cyberwolf888 still, his problem doesn't sound like a permban. it's more likely a softban.

**Comment by cyberwolf888** [comment]
@dstN  My main acc got this issues before perma ban. better stop the bot for now.

**Comment by schang1987** [comment]
oh well, I'll just farm pokestop then lol! 5000 exp /hr...better then nothing

**Comment by Elvete** [comment]
Thats the problem https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by nekudah** [comment]
For me I can farm PokeStop but can't catch pokemons haha

**Comment by zyxelgg** [comment]
Anyone knows how long does it ban?
I mean can farm pokestop but can't catch pokemons

**Comment by urangotango** [comment]
seems an advice ban or the preparation to the perma ban log the account off if you did use an proxy keep it safe for the next log in try... if you stoped on an location keep in mind wich location and try it again in 24h like 2 - 5 km away from the last logged location with the same last ip and last device setting on the bot.. if your device is not listet use an tablet device if i remember right there is some tablet in list.

**Comment by AiVo7z** [comment]
Im getting this starting bot #3233 

-- BUT -- I can Login with phone, catch pokemon, walk around, fight aernas just can't spin pokestops.

**Comment by funzqlm** [comment]
@dstN @cyberwolf888 i can spin pokestop now
