### ISSUE TITLE
POKEMON RUBY! EMU :D ? MEANWHILE ^_^?

### ISSUE THREAD

**Issue by qyxii69** [Ar1i/PokemonGo-Bot#3257]
So, i've tested this... they've added a cooldown method after using your IP, which cannot allow a new proxy/ip . TO AVOID this.. you can run any bot within walking speeds like 5-7 km/h

**Comment by jodirt282** [comment]
nope. my dads account is still working and hes changing IP very often using VPN.

**Comment by cyberwolf888** [comment]
![permaban](https://cloud.githubusercontent.com/assets/8720485/17634909/43569a6c-6107-11e6-91d7-c7c8d62b7913.png)

**Comment by Microrock** [comment]
wow hero!  

i'm waiting for surprise

**Comment by jodirt282** [comment]
@cyberwolf888 And where does this Necronomicon got this information from??? Don't believe everything you read on discord because some guys said so. It started happening only today there is no proof about a PermBan.

**Comment by dstN** [comment]
#3233

**Comment by cyberwolf888** [comment]
@jodirt282 It's from Necrobot dev team
and read this article 
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal
My main account got perma ban too
Damm this is nightmare

**Comment by Waiiim** [comment]
@cyberwolf888 But there's no login system, is it just a general message or does it mean i've been banned too lol

**Comment by Hydro420** [comment]
Just says player info cannot be retrieved from server.. Prob PERM ban. Happened to one of my accounts, over 15hrs now and still same error.

**Comment by dstN** [comment]
#3233

**Comment by xJustx** [comment]
Thanks.
