### ISSUE TITLE
New functions baseas ideas in NecroBot ( Dead )

### ISSUE THREAD

**Issue by Malakia007** [Ar1i/PokemonGo-Bot#3259]
Fast You could provide more settings que existed for NecroBot already que This was waxed , As For example:

- Pokemon Search option Sniper ( providing as Exact cordenadas )

- Rename option altomaticamente Pokemons WITH high IV , putting his IV in front of Pokemon Name

- Progressing Option altomaticamente of All Pokemons Within hum Range Determined IV OR CP

You are in doing great work um , these are ONLY paragraph ideas get even better. XD

**Comment by IceQ1337** [comment]
Do not use the issue-section for suggestions.
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xJustx** [comment]
^
