### ISSUE TITLE
Feature Request for Pokemon List GUI:  Powerup "Max"

### ISSUE THREAD

**Issue by justchil** [Ar1i/PokemonGo-Bot#326]
First off thanks for the work folks.  This is awesome.

I'm finding 98% IV pokes that I want to keep power up.  How nice would it be if there is a button that will keep powering up until your candy is gone?

I don't see anyone asking about a feature like this right now but if so I apologize and /close.

Thanks!

**Comment by Ar1i** [comment]
Great Idea, will take a look at it.
