### ISSUE TITLE
New Softban type, Not Permiban

### ISSUE THREAD

**Issue by blaik2k4** [Ar1i/PokemonGo-Bot#3263]
From all the sources i read they have changed it so you cant spin at a stop more than once thus messing up softban fix. new solution still not found. maybe devs have some ideas. also cooldaowns on ip switches from what ive read

**Comment by PokemonAddict** [comment]
absolutely true

**Comment by emilie253** [comment]
so, you can change localisation without to have a ban?

**Comment by untesty** [comment]
You also have to wait a while in between when you shut down the bot on 1 account and opening the bot with another account

**Comment by xJustx** [comment]
Thanks for this info!

**Comment by Kapperoni** [comment]
It could be a new soft ban type, or simply a permanent ban.

**Comment by urangotango** [comment]
my idea to try to remove the new soft bas was like no pokemon = interupt serch for pokemon > go try to spin like 40 different pokestops > and see if this will remove the new softban.. maybee it works. 

if you take some strange message on the log in desk on the phone APP that means sure you got banned and your acc got was deleted. you can also check it out create an new acc and try to ghive your old char name to the new char..
