### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#3264]
@Ar1i Can pin a topic to the top to prevent new issues?

What is the current state of the bot? Have another one which is working still perfect. I tried your but hours ago again with a new account and worked. Catched some Lapras and Dragoran all over the world and getting back to my place and recieved a "ban"... Maybe it would be useful to make a short FAQ to prevent ban-waves etc.

**Comment by xJustx** [comment]
Bot is currently working! Nobody would read a FAQ :/
