### ISSUE TITLE
THIS IS NOT AN ISSUE BUT *it is a sugestion*

### ISSUE THREAD

**Issue by JJhonh** [Ar1i/PokemonGo-Bot#3267]
I would like to know if it is possible to choose what type of pokeball you want to use , like , if i want to use only great balls , ultra balls , or if i can use ultra balls when find something important

**Comment by Captnred** [comment]
For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xJustx** [comment]
^
