### ISSUE TITLE
Suggestion section on HM forum is still closed 

### ISSUE THREAD

**Issue by urangotango** [Ar1i/PokemonGo-Bot#3268]
https://high-minded.net/forums/pokemon-go-cheats-tricks.184/

@Ar1i @Logxn @xJustx 

maybee will be nice if you open it again for suggestions

**Comment by Captnred** [comment]
For suggestions try here :https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by xJustx** [comment]
@Captnred :D

**Comment by xRealMaks** [comment]
gg

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
