### ISSUE TITLE
i dont know whats happening to you but my older version works just fine

### ISSUE THREAD

**Issue by Amnzya** [Ar1i/PokemonGo-Bot#3269]
hi...im sorry but i think there is a problem...my older version of the bot works just fine and im not getting soft banned...maybe its due to the new validation when the speed is set to high...does the bot says yes to " are  you a passenger ? " i have no clue why some ppl are getting banned for more than 12 hours...(my best friend ! kapppa ) 

does anyone have a single clue of what is going on ? ^^

**Comment by emilie253** [comment]
which version?  mine old dont works :(

**Comment by chickeflonoah** [comment]
I think we all got banned, what can we do now?

**Comment by EvilEmpireDriftTeam** [comment]
Version 1.0.9.7 works great!!! Everyone collects, all catches, all good!!! I do not know you for me personally everything is OK. after collecting pokemon. I'm from the other strvny moved to get your software banned and unbanning immediately. and I go quietly from the phone. it.... and phone!!!

**Comment by vitus0123456** [comment]
does anyone that got the problem with pokemon always get away now can you do it?  or is it permanent?

**Comment by Heuk** [comment]
version 07.08 21.04 works perfectly

**Comment by olvirgo** [comment]
where  version 07.08 21.04 ?

**Comment by emilie253** [comment]
cant open my old 07.08 21.04 she crash :(

**Comment by Safti54** [comment]
Can someone upload the older version that actually works?

**Comment by waropatrik1234** [comment]
Safti54 i have old versions but i dont know which one works

**Comment by Safti54** [comment]
@waropatrik1234 well the nfind out wich one works then upload it so everybody can try it ^^

**Comment by gummyruler** [comment]
Turn it off for now. Yo6u might get pokemon collection ban.

**Comment by rockslayer** [comment]
upload old file plz thx

**Comment by EvilEmpireDriftTeam** [comment]
https://yadi.sk/d/EP8pksgLuBGX3
1.0.9.7

**Comment by xJustx** [comment]
12h ban
