### ISSUE TITLE
"HOT" -> Lucky egg Buguse* Please Add

### ISSUE THREAD

**Issue by absoluttechno** [Ar1i/PokemonGo-Bot#327]
if the Bot activates lucky egg, please make infinite time -> yes it will work, please try it radat.

ich bin raus aus dem bot und ging wieder rein und der Lucky Egg war noch 2 min Aktiv (in der App nicht im Bot) doch dann kommt beim Bot "Using lucky egg - time remaining 29m 59s"

so und nun krieg ich immer noch die doppelten EP (ich habs live mitverfolgt mit der app" obwohl kein lucky egg eingesetzt wurde.

also nehm ich mal an, wenn du lucky egg hier auf 893782937h einstellst wirds genauso lange funktionieren wie der bot an ist, bitte versuchs mal privat mal aus (Y)

**Comment by absoluttechno** [comment]
If the developers dont speak german please sas it to me, but this buguse would be great and safe money and get fulltime double xp

**Comment by Nomaan12345** [comment]
translation 

I 'm out from the bot and went back inside and the Lucky Egg was still 2 minutes active ( in the app in Bot ) but then comes the Bot "Using lucky egg - time remaining 29m 59s "

so and now I still war the double EP ( I habs followed live with the app " although no lucky egg was used .

So I suppose times when you lucky egg here on 893782937h einstellst wirds work just as long as the bot is on , please try it privately times from ( Y )
