### ISSUE TITLE
Exception: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

### ISSUE THREAD

**Issue by assassinscat** [Ar1i/PokemonGo-Bot#3271]
wurde gebannt oder?

**Comment by ProGO1** [comment]
ja

**Comment by urangotango** [comment]
ka hatte vorhin auch die meldung aber da hatte sich nur der meine ip umgestellt. mein proxy provider benutzt meine locale ip als auth ip verwendet habe da meine neue auth ip angegeben und alles war wieder ok

**Comment by assassinscat** [comment]
Spieldaten konnten nicht vom Server abgerufen werden, kommt wenn ich mit Handy rein will.

**Comment by urangotango** [comment]
accaunt wirde gelöscht anscheinend... letzter versuch erstelle einen neuen account und versuche deinen alten trainer namen zu benutzen falls dies geht ist dein alter acc zu 100% von den pokemon go servern removd worden

**Comment by The1nooneknows** [comment]
gleich bei mir.

**Comment by IceQ1337** [comment]
@urangotango Warum sollte irgendjemand dafür in Rechenschaft gezogen werden (können)?
Das ist absoluter Schwachsinn...

**Comment by pwnjke** [comment]
Konto wird nicht gelöscht. Ich habe auf der Seite eingeloggt und Passwort geändert. Das geht. Mit dem neuen Passwort kommt man aber nicht ins Spiel rein. Eure Trainers sind auch da, ich habes gecheckt indem ich auf dem anderen Account den Namen gegen den Namen des blockierten Bots zu ändern versuchte. Geht nicht. Also die Characters und die Accounts existieren noch, sind halt nur geblockt

P.s sorry für mein Deutsch, bin neu in DE

**Comment by urangotango** [comment]
@IceQ1337 gibt immer dumme leute due meinen die bot ersteller dum anzumachen von wegen "du hast den bot gemacht du bist shuld das mein acc weg ist" etc etc bla bla bla...

@pwnjke ich konnte meinen alten trainer namen einem neuem trainer geben von daher wurde er removed.

**Comment by IceQ1337** [comment]
Der o.g. Fehler kann auch auf eine falsche Handhabung des Bots zurückzuführen sein.

@urangotango Diese Leute werden auch meckern wenn irgendwo eine solche Nachricht steht^^
Solche Nachrichten etc. werden sowieso ignoriert.

**Comment by pwnjke** [comment]
@urangotango bei mir geht die Namenänderung nicht, vielleicht wird noch gelöscht

**Comment by IceQ1337** [comment]
@assassinscat @pwnjke @The1nooneknows Eventuell einfach mal einen Tag warten.
Es tauchen ja gerade vermehrt Beiträge darüber auf, dass gebannte Accounts wieder spielbar sind.

**Comment by pwnjke** [comment]
Jetzt aber habe ich den Namen geändert. Mein Bot ist dann weg

**Comment by urangotango** [comment]
@IceQ1337 richtig moritz mit der hand habung deswegen habe ich einfach mal ein paar typs angegeben wie er testen kann ob seine spieldaten von den servern gelöscht wuden wie es bei mir und vielen anderen der fall war.
joa nervt halt extrem immer zu lesen das sie rumheilen wen sie gebannt werden... XD 

account weg egal mach nen neuen hast ehe nicht viel dran gemacht 2 tage bist wieder aufm gleichen stand und wen mehrere tage gebraucht werden ebenfals gut XD

**Comment by IceQ1337** [comment]
@urangotango Ja das ist richtig, im Normalfall sollten diese "Issues" aber auch zuverlässig geschlossen werden, was trotz mehrerer "Mods" hier nicht der Fall ist, aber eventuell liegt es auch an der Uhrzeit^^

Was ich allerdings immernoch nicht verstehe ist, wieso dieser Beitrag mit "Major Bug" gelabled wird, wenn es sich offensichtlich nicht um einen solchen handelt...

**Comment by pwnjke** [comment]
Komisch, Jungs. Kann man eigentlich 2 gleiche Nicknames haben, aber eins im google account und zweites im ptc?

**Comment by urangotango** [comment]
@IceQ1337 denke mal wegen meiner anfrage so das zu mindestens die deuteschen sich meinen post lesen und diese methode zum testen benutzen. 

@pwnjke nein eig nicht

**Comment by pwnjke** [comment]
@urangotango also ich habe auf dem google account den Namen vom gebannten Bot genommen, aber vom neuen ptc könnte ich nicht mehr den alten Namen vom google wählen

**Comment by IceQ1337** [comment]
@urangotango Ja das mag sein, wer halbwegs intelligent ist, kommt darauf aber von selbst.
Ich persönlich finde es seltsam das heutzutage gesperrte Accounts gänzlich entfernt werden.

@pwnjke Ich habe gerade mal eben versucht einen PTC Account mit meinem Nick vom Google Account zu erstellen. Es bleib bei einem Versuch.

**Comment by bloodmoonx2** [comment]
mal schauen wie das wird @IceQ1337 also wird das alles zurückgesetzt praktisch auf 0 ? und man muss von neu anfangen?

**Comment by IceQ1337** [comment]
@bloodmoonx2 Was wird zurückgesetzt?
Es ging lediglich darum, dass keine zwei Accounts mit dem selben Nickname existieren können.
(PTC/Google) Wenn dein Account entfernt wird und du einen neuen erstellst wirst du wohl von vorne anfangen müssen, allerdings glaube ich immernoch nicht so richtig an eine permanente Löschung der Accounts.

Allein dieses Zitat "If you believe your account has been terminated in error incorrectly, you can appeal that termination through this form." gibt uns die Information, dass Accounts wiederhergestellt werden können, also praktisch einfach ein Unban möglich ist.

**Comment by urangotango** [comment]
@IceQ1337 richtig moritz aber sie worden vorerst aus dem game server genommen... deswegen kann man auch den alten namen benutzen. macht einen appeal und versucht eure accs wieder zu bekommen versuchen ist nicht verboten.

**Comment by bloodmoonx2** [comment]
@urangotango appeal?? 
@IceQ1337 Ja dann passts ja eh hoffe das wird so :)

**Comment by urangotango** [comment]
@bloodmonx2 
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by pwnjke** [comment]
Scheisse. Das geht doch. Ich habe gerade zwei accounts mit gleichem namen

**Comment by bloodmoonx2** [comment]
@pwnjke ja dann wird wohl der account aus dem spiel genommen worden sein bzw die spieldaten

**Comment by IceQ1337** [comment]
Ich würde mich in den nächsten Tagen mal hier, in unserem High-Minded Thread und auf Reddit rumtreiben, da die Leute bereits intensiv am "ermitteln" sind :dancer: 

@pwnjke Ein Account ist wohl dann entfernt worden. Sonst ist es nämlich nicht möglich einen Account mit dem selben Namen zu erstellen. Ich habe es gerade extra in beiden Situationen getestet. (Google Name -> PTC / PTC Name -> Google)

**Comment by bloodmoonx2** [comment]
@IceQ1337 kannbst du mir den reddit link schicken ? :x

**Comment by IceQ1337** [comment]
@bloodmoonx2 https://www.reddit.com/r/pokemongo/
Sortiere nach neuen Beiträgen oder verwende die SF (Nur in diesem Subreddit suchen).

**Comment by pwnjke** [comment]
Hm
Ich habe den ptc bot mit einem namen, der läuft und sammelt da alles. Und jetzt habe ich auch im Bluestacks einen google account. Die Namen sind gleich und die beiden sind online. Nichts wurde gelöscht. Mein charmander auf dem neuen google ist immer noch da

**Comment by bloodmoonx2** [comment]
Ich hoffe das alles wird schnell behoben :/

**Comment by bloodmoonx2** [comment]
@pwnjke hä wie es wurde bei dir nix gelöscht :x muss ich das verstehen ? :D

**Comment by pwnjke** [comment]
Es war die Rede dass zwei accounts nicht gleichzeitig existieren können. Mit einem Namen also. Bei mir geht aber. Ptc bot lvl 13, bluestacks google lvl 1,5. Habe auch versucht beide zu schließen und wieder einzuloggen

**Comment by IceQ1337** [comment]
@pwnjke In welcher Reihenfolge hast du die Accounts erstellt? Bei mir ging es in beide Richtungen nicht^^

**Comment by pwnjke** [comment]
Erstmal war ptc. Der ist schon paar wochen alt. Und den google habe ich gerade neu registriert

**Comment by bloodmoonx2** [comment]
und bei welchem ist jetzt das alles wieder da?

**Comment by pwnjke** [comment]
Bei beiden. 13lvl bot farmt noch. Und der neue 1,5lvl google steht afk in california

**Comment by bloodmoonx2** [comment]
aber wie is das möglich das alles wieder da is warte mal pokemon go hat sich aber ned selbst einen bug eingespeißt oder ... :x

**Comment by urangotango** [comment]
lol strange sihit Oo

**Comment by IceQ1337** [comment]
Mist, jetzt habe ich keinen Google Account mehr übrig und auch keine Lust einen neuen zu erstellen um die Uhrzeit... :disappointed: War ein Account vorher gesperrt? Hab da nicht aufgepasst. Wenn ja, seit wann bzw. wie lange. Wenn nicht, dann sollte eventuell jemand nochmal probieren einen bestehenden PTC Nick über einen Google Account wieder zu verwenden, eventuell funktioniert es einfach doch in diese Richtung.

**Comment by bloodmoonx2** [comment]
ich hab noch ein google account :D aber kein ptc account

**Comment by pwnjke** [comment]
Nein nein. Nicht gesperrt.

**Comment by pwnjke** [comment]
Wer nicht glaubt, kann ich auch nen Screenshot machen für paar minuten

**Comment by bloodmoonx2** [comment]
in welche richtuzng google zu PTC ?

**Comment by IceQ1337** [comment]
@bloodmoonx2 Verwende mal den Nickname "pokemongo5522" bitte über den Google Account.
@pwnjke Ja wir glauben dir schon^^ Jetzt wird getestet ob es einfach in diese Richtung möglich ist.

**Comment by pwnjke** [comment]
Registriert war zuerst ptc

**Comment by bloodmoonx2** [comment]
@IceQ1337 hast du skype? :D

**Comment by pwnjke** [comment]
Zuerst ptc, und jetzt vor 20 minuten google

**Comment by IceQ1337** [comment]
@bloodmoonx2 Ja, benutz ich aber kaum und eigentlich will ich mich für diese Nacht auch gleich hiervon distanzieren :P  Wäre nur cool wenn du das eben testen könntest mit dem Namen. Der Name ist von einem bestehenden PTC Account.

**Comment by pwnjke** [comment]
Auf dem ptc habe ich vor einer woche ganz fair den lvl 7 gekriegt

**Comment by bloodmoonx2** [comment]
@IceQ1337 wie meinst du distanzieren :D ?? xDDD

**Comment by bloodmoonx2** [comment]
werde es testen sobald ich bluestacks wieder habe :D

**Comment by bloodmoonx2** [comment]
weil auf dem handy geht es ned :(

**Comment by IceQ1337** [comment]
@bloodmoonx2 Ich will jetzt eigentlich noch ne Runde zocken und dann pennen gehn :DD
Ich bin nur so lange hiergeblieben, weil sich so viele unnütze Threads mit Unbans aufgetan haben.
Es gibt ja im Moment wenig Informationen über diese "Möchtegern Hard/Perma-Bans".
Es wäre halt cool zu wissen ob man von PTC -> Google einen gleichen Nick verwenden kann.
Andersherum geht es nämlich nicht.

**Comment by pwnjke** [comment]
Soll ich vielleicht doch screen posten? xD

**Comment by bloodmoonx2** [comment]
@IceQ1337 achso ja is ja kein stress :D werde jetzt dann testen wegen skype könnten ja das privat machen um das hier ned so vollzuspammen XDD 

@pwnjke wir glauben dir ja :D wir wollen es nur wissen weil ich auf meinen google acc 30+ bin und 2 dragorans habe -.- die will ich z.B wieder haben xDD

**Comment by pwnjke** [comment]
Bei mir wurde auch nichts gelöscht.

**Comment by IceQ1337** [comment]
@pwnjke Nicht nötig, aber es wäre halt gut zu wissen, WARUM dies funktioniert.
Funktioniert es einfach so oder wird der Name verfügbar wenn ein anderer Account aus der Datenbank gelöscht wird etc. etc. Da du aber nicht von diesem seltsamen Ban betroffen warst kann ich mir halt nur vorstellen, dass die zwei verschiedene Tabellen verwenden und diese nur in eine Richtung abgleichen anstatt in beide. 

@bloodmoonx2 Gib mir einfach mal deinen Skype Namen.

**Comment by bloodmoonx2** [comment]
@IceQ1337 xjan2208

**Comment by urangotango** [comment]
uhh sehe da einer meiner bots wurde wieder abilitiert

**Comment by pwnjke** [comment]
Is es nicht so, dass die google und ptc accounts auf verschiedenen Server spielen? Sonst kann ich mir nichr vorstellen, wie zwei gleiche nicknames existieren können

**Comment by urangotango** [comment]
@pwnjke sind die 2 accounts in der gleichen location ? wen ja schau mal in eine arena rein wen da die gleichen spieler drin sind sind es die gleichen server

**Comment by pwnjke** [comment]
Wollte ich auch. Aber eins ist doch bot.

**Comment by urangotango** [comment]
ich gehe pennen gute nacht an alle

**Comment by IceQ1337** [comment]
@pwnjke Hast du nicht gesagt, die sind in verschiedenen Locations unterwegs?
Dann wären sie zumindest auf unterschiedlichen Gameservern, dass hat allerdings nicht zwingend bzw. eigentlich so gut wie garnichts mit der Account-Datenbank zu tun (einfach gesprochen es gäbe nur eine).

**Comment by bloodmoonx2** [comment]
@urangotango nacht 
@IceQ1337 soweit ich das alles sehe gibt es nur eine Account datenbank gefiltert mit PTC und google accounts :D war ja bei meinen game servern auch ned anders :D xD die Acc datenbank is unabhängig von gameservern :D

**Comment by pwnjke** [comment]
Die beiden sind im gleichen Platz. 1km unterschied

**Comment by bloodmoonx2** [comment]
die können ja am gleichen platz sein trotzdem hat das nichts mit der Acc-Table in der Datenbank zu tun :D

**Comment by pwnjke** [comment]
Ich versuche mal die gyms zu prüfen :d

**Comment by IceQ1337** [comment]
@pwnjke Da sollten die selben Spieler drinstehen^^ Anders kann es auch eigentlich nicht sein.
Es gibt ja keine Realms so wie in World of Warcraft oder so^^

**Comment by bloodmoonx2** [comment]
anders is es auch ned xD //
schau ma morgen nochmal ;)

**Comment by IceQ1337** [comment]
Morgen haben die Leute auf Reddit sowieso schon alles wichtige herausgefunden :dancers:

**Comment by bloodmoonx2** [comment]
passt kannst mir ja den link dann schicken :P

**Comment by pwnjke** [comment]
die gyms sind gleich, ja)

**Comment by IceQ1337** [comment]
@pwnjke Kann auch nicht anders sein^^
Morgen wird nochmal getestet den Account-Namen nochmal zu verwenden.
Ansonsten hat sich das hier erledigt.

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by dstN** [comment]
#3233
