### ISSUE TITLE
Use at your own risk, Niantic is banning these days!

### ISSUE THREAD

**Issue by igkobzxd** [Ar1i/PokemonGo-Bot#3272]
What does this mean does it mean we can't use bot anymore?

**Comment by Defwang** [comment]
**Use at your own risk**means you can use it....

**Comment by Captnred** [comment]
If you wouldn't mine closing this thread. Seeing how this is not an issue.

**Comment by urangotango** [comment]
funny guys any 3th party software is at your own risk if you got banned just dont start to cry

**Comment by xRealMaks** [comment]
^

**Comment by urangotango** [comment]
@xRealMaks WB du meister des tread closen ;)

**Comment by hamburg55** [comment]
If I change the speed to 5 km/h and set the locarion to my hometown would it work without a hardban?

wenn ich die Geschwindigkeit auf 5km/h setze und den Standort nur auf meine Stadt beschränke, könnte ich dann den Bot benutzen ohne einen Permanentbann zu bekommen?

**Comment by urangotango** [comment]
ka wo du deinen bot momentan am laufen hast aber wen er extrem weit weg ist warte mindestens 2 stunden bevor du ihn nach hause holst.. ist denke ich mal besser

**Comment by hamburg55** [comment]
habe seit ca. 2 tagen nicht den bot benutzt. dachte wenn ich den vielleicht auf meine Stadt einstelle würde es gehen..

**Comment by hamburg55** [comment]
habe im Internet nur entnehmen können das man noch nicht genau weiß was die gründe für einen Bann sein können.. hatte hoffnung das mir hier jemand weiter helfen kann

**Comment by urangotango** [comment]
naja auf der offizielen pokemon seite stehen nen paar gründe ;) 
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by hamburg55** [comment]
@urangotango hmm verstehe.. die gründe treffen genau auf den Bot zu. Ich glaube das wars jetzt endgültig mit cheaten in Pokemon Go.. Werde erstmal darauf verzichten und abwarten bevor ich noch gebannt werde. danke dir für deine Hilfe! wünsche dir noch einen schönen Abend ;)

**Comment by urangotango** [comment]
kein tema freue mich immer wen ich jemandem helfen konnte
