### ISSUE TITLE
GUYS ATTENTION PLEASE :) about BAN

### ISSUE THREAD

**Issue by Onono88** [Ar1i/PokemonGo-Bot#3273]
Today (12.08.2016 ) i had a problem with catching pokemons.(My problem was like all of yours pokestops and gyms visits were not problem) It was 8.00 am now it is 01.00 am (13.08.2016) i downloaded latest bot and started around 3 or 4 hours result OK :D Now it is unbanned speed is still 50 km/h
![asdasdasd](https://cloud.githubusercontent.com/assets/20999702/17638421/9c4a2d10-60f2-11e6-83a5-f4355e6e86bd.png)
 and radius is 5000 ( Sorry for mistakes for using English, from Turkey)

**Comment by Onono88** [comment]
By the way i changed my regular location..

**Comment by urangotango** [comment]
you did let him run all that time just spinning pokestops and try to hunt pokemons?

**Comment by suljo94** [comment]
You cant farm pokestops so they will escape again as soon as your regular  poke balls run out

**Comment by Onono88** [comment]
Yes i let him run for 3 4 hours and now i can farm and catch pokemons.. If you want anytime i can upload pictures

**Comment by urangotango** [comment]
@suljo94 see hes last pokemon after around 4h he got again an pokemon he was just able only to take pokestops and than plup he got an pokemon

**Comment by Onono88** [comment]
yes that is why i took ss from bot menu. He wasn't able to catch and suddenly it started to work and catch.

**Comment by xJustx** [comment]
not an issue

**Comment by Onono88** [comment]
It is not an issue, i know but i'm new in here after banned i started to follow here. Now maybe you can find a solution from here. This is my first topic sorry ..
