### ISSUE TITLE
IMPORTANT UNBANNED NOW

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3274]
Just like many here I was banned gor using the bot and I couldn't farm pokestops but could catch pokemon.  Now after 24h I can farm again so it is a new typ op softban not a perm ban

**Comment by tuki144** [comment]
Where you getting the white lines of code (error)?

**Comment by xJustx** [comment]
not an issue

**Comment by cirnolp** [comment]
Even if it's closed, just for personal research:
Did you keep the bot running all the time or did you log off till it worked?

**Comment by suljo94** [comment]
@cirnolp I closed it but the other guys didn't so it doesn't maatter I think but 24h might be the time you are quarentined, I think they are checking idividual cases and banning but if they don't treat your case in 24h you get off the hook, but you will if banned again be put higher on the list  but again this is just speculation

**Comment by suljo94** [comment]
@xJustx I think I know how we were flagged ca
