### ISSUE TITLE
All my banned accounts are now unbanned. No info just PSA

### ISSUE THREAD

**Issue by elenex23** [Ar1i/PokemonGo-Bot#3278]
Just for information sake all my accounts seems to be unbanned. My google account that was banned exactly at 11pm last night (could not catch pokemon) is now full restored (I can catch pokemon again). From 11pm to 3pm is when I was banned. I did nothing to reverse this, just waited. Good luck bros, thank you ar1i and the rest of the crew.  Feel free to close if you want or I will in 8 hours.

**Comment by lovakosh** [comment]
same for me. the question is to run the bot again or not? :)

**Comment by elenex23** [comment]
I do have one of my lower accounts botting for the last 6 hours just fine. 8km/h at 1500 range. No mass transfer or evolve. I continue to run this less important bot ahwhile longer before hooking up one of my higher accounts

**Comment by lovakosh** [comment]
yeah, I guess I will do the same

**Comment by igkobzxd** [comment]
Is it still safe?

**Comment by Onono88** [comment]
ı still use 50 km/h and radius 5000m still can use bot

**Comment by igkobzxd** [comment]
Are you sure its safe to use it always?

**Comment by xrufino** [comment]
i dont know you but my acc still ban, ''Failed to get game....." so not all got luck

**Comment by lovakosh** [comment]
If you have some other account make test on it. I will do it during the night and see what's happen. I'm using older version of the bot. 1.0.9.7

**Comment by trwk** [comment]
It was not a ban I think it was a bug on pokemon servers 
I think those who using bot got stuck somehow capturing a pokemon

**Comment by bloodmoonx2** [comment]
i have this problem with Pokemon Player data can not downloded
its a ban or bug ?

**Comment by bloodmoonx2** [comment]
@lovakosh can you send me a older version of 1.0.9.7 btw then what you use ? pls ? :;)

**Comment by b1ll3** [comment]
@elenex23 can you please tell the exact hours you were banned for please... N were you checking in between if its on or not. Thanks

**Comment by M31860** [comment]
@b1ll3 
I was banned for about 12 hours. I tried to farm on my mobile device very often.
Couldnt spin pokestops and catch pokemons for this time.

**Comment by elenex23** [comment]
about 16 hours. I was checking in and messing around.

**Comment by coffeexp** [comment]
Did niantic post blogs or articles about banning accounts?

**Comment by iOwner** [comment]
@coffeexp one of the developers on twitter replied to someones tweet saying "very soon" in the context of getting rid of botters and this was about 3/4 days ago

**Comment by velfisadri** [comment]
if i will teleport now and get softban - can i normay unban myself by spinning pokestop? Or i will get same 12h ban?

**Comment by M31860** [comment]
@velfisadri 
i tried this during my 12 hour ban on many different pokestops... didnt work:(

**Comment by drsweg** [comment]
Hmm I wonder what's going on..my account is still banned but I can't login at all so

**Comment by smedicejr** [comment]
My two strongest accounts, google with level 35 and Ptc with level are getting the error "failed to get game data from server", but my third account which is a PTC level 18 didn't suffer anything. The first two account were bad-asses things, more than 1,000,000 stardust, and so on... The question is, will be after some time my first two account payable? I'm betting in "no".

**Comment by coffeexp** [comment]
it is so suspicious here in philippines to have high levels since they just opened the server 2 weeks ago..i think i should laylow my bots for now.. i will just lurking around what niantic plans.. :)

**Comment by drsweg** [comment]
Well I checked the server status for Pokemon go and it says it's down

**Comment by bleh235** [comment]
servers are not down i tried with my "main" account (never used the bot) its all fine on my side.
only my test acc is getting failed to get game data from server.

**Comment by hades2795** [comment]
Guys bot still work or not? Plss reply

**Comment by Wortan89** [comment]
The Bot works fine with a new Account.
I dont log in with the Main at the moment

**Comment by hades2795** [comment]
With old account cant?

**Comment by Wortan89** [comment]
I created a new one , my mainaccount had the issue that he could farm pokestops but cant capture Pokemons. I will try it tomorrow when the little acc. dont get in trouble

**Comment by joe112** [comment]
@elenex23 you just get a soft banned cant get pokestop and cant catch pokemon , i think perma ban is "failed to get game data from server", this problem cant even open  acc . that's why your account is back.

**Comment by drsweg** [comment]
Still hoping it's not a permanent ban because the servers seem to have
issues still

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by drsweg** [comment]
This guy needs to stop trolling

**Comment by joe112** [comment]
im still hoping, and already wait for 12 hours, my account is not back yet

**Comment by drsweg** [comment]
Yeah I've been "banned" for a day now hoping there's a fix or its just
server issues and not a ban
