### ISSUE TITLE
TIPPSS! before pokemon RUN AWAY!

### ISSUE THREAD

**Issue by phodem** [Ar1i/PokemonGo-Bot#3279]
This is not ip banned or softbanned. This is about ID banned and it's permanent.
If you still can bot , GOOD for you, im just sharing my tips ,  6 out of 10 of my account got banned.  They are all high level.
It happens when you see " Pokemon Run Away" for every pokemon you meet. You can do Gym and pokestops but after 24 hours, your account will be permanent banned and will give you " failed to connect".
sooo to avoid this you MUST
--  **Do not bot same account for more than 8 hours a day.** 
The game detects your online hours , number of the pokemon you caught per hour and the the amount  of exp you're getting per hour.  Niantic will temp ban you for 24 hours to investigate, in the mean time you can't catch any pokemon. if you lucky, they will unban you

The bot still runs good, but better be safe than sorry.

**Comment by Romanoski** [comment]
Thx for warning

**Comment by IceQ1337** [comment]
This is not an issue and therefore this isn't the right place for that, but it looks like being actually a thing.
Further investigation on this will provide more information about this.

**Comment by M31860** [comment]
I had been banned for about 12 hours. Since 12 o´clock i couldnt spin stops and catch pokemon. Now everything works fine again.

**Comment by urangotango** [comment]
thx for the comucation it will help a lot to try out that what you did say 
@IceQ1337 ich erstelle mir gerade 2 weitere accounts um das mal zu testen auf langzeit

**Comment by M31860** [comment]
@urangotango 
Mein zweitaccount läuft seit anderthalb Stunden. Der war aber auch nicht von einem Ban betroffen.
Also ich gehe nicht von Serverproblemen aus.
Läuft ohne Probleme... Allerdings nicht im Central Park sondern in der nächst größeren Stadt in meiner Nähe;) Und mit nur 7 kmh:D

**Comment by Ted0504** [comment]
Seems everybody works fine again? I just checked my account is normal now.

**Comment by hamburg55** [comment]
also hab ich es richtig verstanden?: ich kann den bot benutzen muss meine schnelligkeit auf am besten 5 km/h stellen und nicht länger als 8 Stunden am Tag benutzen (weniger wäre besser) ohne einen Bann zu erhalten.

**Comment by bleh235** [comment]
my test account which i made yesterday got banned during morning i guess.
im stuck@the loadingscreen and it says failed to get data or something like that.
to be fair i used the bot since making this account and let the bot run if i get unbanned i will let y know

**Comment by Cyberlink4200** [comment]
Well.. earlier (12 hours ago) I suddenly couldnt spin stops or catch pokemons (But still fight gyms).. I checked it regular, and now after 12 hours, all back to normal, workin again.. seems new softbans might be 12 hours :)

**Comment by hamburg55** [comment]
does it mean I can use the bot but have to change the speed to 5 km/h, not longer than 8 hours a day and only at my hometown without getting a ban?

**Comment by IceQ1337** [comment]
@hamburg55 Was der OP sagt, ist nicht bestätigt, aber eine relativ plausible Erklärung.
Es ist noch kein Account von mir jemals gebannt gewesen, deshalb kann ich weiteres nicht sagen.
Ich habe den Running-Speed und die Location mit mehreren Accounts gewechselt seitdem diese "neuen Bans" aufgetaucht sind und bisland konnte ich noch nichts genaueres feststellen, da alles einwandfrei läuft bei mir... Mehrere Bots laufen mitlerweile auch mehr als 8 Stunden mit einer Geschwindigkeit von 6-10 km/h ohne Probleme durch. Ein Bezug auf meine IP wird wohl momentan auch nicht genommen, da ich meine IP nicht verschleiere und trotzdem in Amerika und Japan unterwegs bin. Ich finde es sehr seltsam, dass das System nicht in jedem Fall auf die selbe Art und Weise greift, da dass was ich eben beschrieben habe, ja wohl anscheinend bei vielen Leuten zum Ban geführt hat.

**Comment by bloodmoonx2** [comment]
man müsste doch den bot so schreiben können das er das alles bypasst oder nicht ?? also theoretisch gesehen das du keine einschränkungen hast was du eingibst an speed usw wenn der nämlich bemerkt das man zu schnell ist dann soltle er runterregeln und man müsste herausfinden was die maximale geschwindigkeit ist weil ja im spiel die meldung mit dem autofahrer angezeigt wird aber wenn es an der geschwindigkeit liegt darf man ja dann ned mal mehr mit dem auto rumfahren oder fahhrad oder roller oder sowas :/ also würde ich das aussschließen

**Comment by IceQ1337** [comment]
@bloodmoonx2 Das was du in deinem Kopf vorhast ist nicht möglich. Das Spiel sagt dir in keiner Weise "Hey, wenn du weiter so schnell läufst, weiterhin dieselbe Geschwindigkeit für Stunden beibehälst, etc., wird dein Account gesperrt". Der Bot kann also nicht "von selbst bemerken, dass er zu schnell ist".

**Comment by bloodmoonx2** [comment]
Aber es muss da eine lücke geben :/ // bin in der hinsicht neuling :/ // aber wenn der bot einen softban erkennt dann sollte er auch erkennen können wie schnell er maximal laufen darf um keinen softban zu kriegen

**Comment by IceQ1337** [comment]
@bloodmoonx2 Der Bot erkennt einen Softban im Prinzip durch die Log.
Wenn er merkt "moment mal, ich fange keine pokemon mehr, bekomme keine xp für stops, etc.", dann sagt sich der Bot eben "oh, ich habe wohl einen softban erhalten". So in etwa funktioniert das^^

**Comment by Johnybackaa** [comment]
I guess it's permaban ^^

**Comment by immoempe** [comment]
"It happens when you see " Pokemon Run Away" for every pokemon you meet. You can do Gym and pokestops but after 24 hours, your account will be permanent banned and will give you " failed to connect". sooo to avoid this you MUST"

Not really, i got this kind of ban yesterday, around 18 hours without catch pokemon, today I'm free of the ban.

The best all can players do it's wait, 1 - 4 days, maybe a week for those who are getting the error about  data login, we don't know why is going to happen, and having "panic attacks" won't solve the problem...

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8 rip i  am perma
