### ISSUE TITLE
How To Use Telegram Bot

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#328]
For me all it saids is "I cant hear you"

**Comment by gise88** [comment]
You have to put your telegram username in the name field (right below the API token field)

**Comment by Tochez** [comment]
Where is my telegram username?

**Comment by Tochez** [comment]
is it the one that saids Tochez Hi?
![capture](https://cloud.githubusercontent.com/assets/20713623/17267581/cae6e168-55da-11e6-815d-cf9c4864253c.PNG)

**Comment by Tochez** [comment]
nvm found out what it was
