### ISSUE TITLE
Livechat

### ISSUE THREAD

**Issue by xJustx** [Ar1i/PokemonGo-Bot#3280]
If you have problem and don't want to open a new issue you can join our livechat here: http://poke-support.ar1i.xyz/

**Comment by Onono88** [comment]
I think accounts became normal (unbanned ) right ?

**Comment by bleh235** [comment]
when im banned, am i stuck@the loading screen ?

**Comment by jeremie152** [comment]
nice this good idea i need just say a big thanks to ar1i my account is not banned next 12 hours sorry for have doubt^^ now gn to all i go for today gl for botting this night 02h14 here cya to tommorow

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
