### ISSUE TITLE
New kind of softban?

### ISSUE THREAD

**Issue by HubergTino** [Ar1i/PokemonGo-Bot#3281]
![fur github](https://cloud.githubusercontent.com/assets/20999924/17638727/6c6d349e-60ec-11e6-87ce-121768ef06f4.png)
I can farm Pokestops, but i don´t get any pokemon.
Is this a kind of softban?
And another question. Does Niantic ban permanent at all?

**Comment by HubergTino** [comment]
And my pokeballs are at 20 as well

**Comment by chickeflonoah** [comment]
I got the same problem, but a bit different
Cant farm stops but can catch pokemon haha

**Comment by Waiiim** [comment]
Niantics don't perm ban yet it's only temp bans

**Comment by hamburg55** [comment]
@Waiiim  are you sure? that Means i can use the bot without getting a perm ban? and how long would be a temp ban ?

**Comment by hamburg55** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by iOwner** [comment]
Permanent bans are now out as Niantic are starting to boost their secruity. Don't listen to @Waiiim

**Comment by ayaxelrey** [comment]
i heard   that  today  the  perma  bans  started but  im  not  quite  sure  mi  bot  is  working  fine

**Comment by hamburg55** [comment]
does it mean I can use the bot but have to change the speed to 5 km/h, not longer than 8 hours a day and only at my hometown without getting a ban? or should i wait ?the last time i used the bot was 2 days ago..

**Comment by Manegar** [comment]
It seemes I just got banned permanently. so be careful.
![13902630_10154414236568967_1556684129111865823_n](https://cloud.githubusercontent.com/assets/21000181/17639289/5a978228-60b6-11e6-8de4-583b8b085a47.jpg)

**Comment by Utopik** [comment]
Hey now is it permaban or tempban???

**Comment by Manegar** [comment]
Permanent!!!

**Comment by bboylost** [comment]
@Manegar it is the server down on google accounts... update us tomorrow, if it is still like this then say it is a ban

**Comment by Manegar** [comment]
@bboylost ok bro. will do.

**Comment by xBudSpencer** [comment]
i have the same like Manegar .. but with a ptc acc. . . it looks like an perma ban ... be carefull guys

**Comment by kakksa** [comment]
i am not banned lvl 34 easy quited yesterday

**Comment by Elvete** [comment]
https://www.youtube.com/watch?v=vfc42Pb5RA8 RESOLVE

**Comment by itamoye** [comment]
dude i think pogo server is down look at this one http://ispokemongodownornot.com/
and this http://www.mmoserverstatus.com/pokemon_go do not have ping at many country

if that permnt ban, why if im try on this site https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ and login, no one notice i get ban (sry my english bad)

**Comment by bboylost** [comment]
@itamoye thank you for the statics replies, my accounts is gmail, so the pokemon trainer web site wont see anything , but my PTC account has been unban after 10 + hours
