### ISSUE TITLE
Unban by myself

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#3282]
Hi guys! But works great again after update with the "new" unban method. How can I use this for my own with a special tool? I have only the "old" unban tool Fastspin... I need it for sniping...

**Comment by b1ll3** [comment]
What new unban method?

**Comment by igkobzxd** [comment]
Can permanent ban still be fixed?

**Comment by PokemonAddict** [comment]
mhh not really. tried exactly this... All Pokemon fled.

**Comment by PokemonAddict** [comment]
with a new account I can snipe all. but then I've to farm pokeballs. Setting the new position in the near of the new sniping, shutting bot down. Then sniping again... all pokekom fled. Don't know why.

**Comment by PokemonAddict** [comment]
ahhh... maybe the different ip!? used my bot with a proxy. What I want to know how the 1337 unban method works or how I can integrate sniping ^^

**Comment by Utopik** [comment]
i dont dont want snipping i dont to spawn. i wanna back my account

**Comment by XxSHADOWxWOLFxX** [comment]
dont set the position with the bot.
for example: im in japan (tokio, yoygi park) for xp farming.
if i want snipe pokemon in new york or sydney ,i shut down the bot and start blue stacks and teleport to the pokemon via fakeg gps.
i go into battle and teleport back with fake gps to the park in japan and catch the pokemon.

**Comment by PokemonAddict** [comment]
k, so the trick is manual catching? The sniping tool does exactly the same in my opinion!? maybe the altitude is also missing!? The thing is, before I farm it works, after farming not. It works with sniping around 30 Pokemons...

**Comment by PokemonAddict** [comment]
Hah! Look now with the bot, the unban works ^^ but when I shut down now the bot and want to snipe by tool it doesn't work.

**Comment by XxSHADOWxWOLFxX** [comment]
i catch the pokemon manual the save way without ban. 
using this side:
http://pokesnipe.de/
i hunt only 100% pokemon :)

**Comment by PokemonAddict** [comment]
interesting. me this: http://pokesnipers.com/ There I can't see the percentage but it makes totally sense to wait first for 100 IV and then powering up ;)

**Comment by PokemonAddict** [comment]
if we have the time of course... :D

**Comment by coffeexp** [comment]
@XxSHADOWxWOLFxX @PokemonAddict im curious.. how to use pokemon snipe though? what to install?? is it in mobile or pc? haha.. tia :)

**Comment by PokemonAddict** [comment]
with the pages at least you have to find it alone ;) you can do it...

**Comment by k3npachi** [comment]
@XxSHADOWxWOLFxX  can you say me how sniping correctly, explain your technique please

**Comment by joe112** [comment]
i want my account back

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
