### ISSUE TITLE
My account banned...

### ISSUE THREAD

**Issue by wa666** [Ar1i/PokemonGo-Bot#3283]
![13950964_187784211638509_1956638729_o](https://cloud.githubusercontent.com/assets/20918380/17639187/2595e97c-60f0-11e6-850a-041f4898d9b4.jpg)

This is a permanant ban please? :(

**Comment by tuki144** [comment]
I suggest you read before making an issue,  you idiot.

**Comment by wa666** [comment]
Sorry i'm not english.. Please answer me.

**Comment by lucasxvieira** [comment]
@tuki144 don't need to be mean, you stupid fuck..

**Comment by Utopik** [comment]
I think that yes :/ i have banned for my two accounts :/

**Comment by tuki144** [comment]
You said it best brother.

**Comment by wa666** [comment]
We are banned :'(

**Comment by tuki144** [comment]
Oui oui

**Comment by xJustx** [comment]
^
Maybe only a 12h ban.

**Comment by wa666** [comment]
@xJustx  Just 12 hours ban account ??
