### ISSUE TITLE
error reloading pokemon list: Object refernce not set to an nstance of an object

### ISSUE THREAD

**Issue by nmo0ory** [Ar1i/PokemonGo-Bot#3284]
Describe your problem!
when i try to use the new pokemongo bot i got this problem
i have last one but i use old config

![MyProblem](http://content.screencast.com/users/nmo0ory/folders/Jing/media/cc549ce5-f491-45f7-bf1d-6d3d88073d9b/2016-08-13_0156.png)

**Comment by tuki144** [comment]
Please read the Previous posts... You aren't unique

**Comment by nmo0ory** [comment]
are you sure some one has same as my problem ? 
i have try new config and same

**Comment by xxKevinSniperxx** [comment]
you're banned, now close this

**Comment by wa666** [comment]
@xxKevinSniperxx  Banned permently ?

**Comment by nmo0ory** [comment]
are you sure that its a ban ?

**Comment by wa666** [comment]
@nmo0ory  Yes your account is banned I hope not permanent.

**Comment by tuki144** [comment]
By the looks of it, just temp but we don't know how long

**Comment by tuki144** [comment]
Many people getting unbanned,  good luck.

**Comment by wa666** [comment]
Ohh Ah this is perhaps a temporary ban? @tuki144

**Comment by tuki144** [comment]
Maybe

**Comment by nmo0ory** [comment]
i thought it was problem on the API

**Comment by wa666** [comment]
No.. @nmo0ory

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by drsweg** [comment]
The more and more I read up on it it's a permanent ban

**Comment by dstN** [comment]
#3233
