### ISSUE TITLE
Help :s 

### ISSUE THREAD

**Issue by harudomerugu** [Ar1i/PokemonGo-Bot#3285]
![help](https://cloud.githubusercontent.com/assets/21000330/17639497/15b2dcb0-60f3-11e6-9e37-0a073048c827.jpg)

**Comment by bleh235** [comment]
same on banned acc

**Comment by xxKevinSniperxx** [comment]
http://lmgtfy.com/?q=how+to+delete+my+github+account

**Comment by wa666** [comment]
Banned permently forced ?

**Comment by bkrandy** [comment]
#3218

**Comment by xxKevinSniperxx** [comment]
close this

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by dstN** [comment]
#3233
