### ISSUE TITLE
just tricked it no harm

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#3286]
as of 7:18am from 2:00am , v1.0.9.1 still kickin with 30km/h 4000radius,  i got softbanned 2 times only within that hour , just get some new ip and start it again. easy choice.. NOT AN ISSUE

![capture](https://cloud.githubusercontent.com/assets/20971723/17639572/156b0f7e-6126-11e6-97cd-05f253412092.PNG)

**Comment by bboylost** [comment]
1 bot and still ban?  lol  not worth posting, I am running 200 km . 5000 radius , the bot worked 24 hours + no bans or anything at all. and this is how it should be

**Comment by generaljoke** [comment]
good for you , i will take 30km/h and you take that 200km/h :) as if you can avoid softbans :)
