### ISSUE TITLE
How can i use the Pokemon Go List Application only?

### ISSUE THREAD

**Issue by patrayat5505** [Ar1i/PokemonGo-Bot#3287]
im now afraid to use the bot so i am asking how can i use the POKEMON LIST application without farming or running the bot?

**Comment by IceQ1337** [comment]
Try a walking speed of 0 km/h in a 5 meter radius :laughing:

**Comment by kbessote** [comment]
The Poke Go Bot List is very good, pls do a .EXE for only the list, evolved, transfer, and see real IV its very good, dont need "walk 0 km/h",...

**Comment by IceQ1337** [comment]
@kbessote I will add this feature after i got some sleep if @Ar1i likes it^^

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
