### ISSUE TITLE
Using razzberry ??

### ISSUE THREAD

**Issue by Onono88** [Ar1i/PokemonGo-Bot#3288]
As i said before banned account became normal and i use bot now. But razzbery item doesn't use by bot ? Is there any solution ?

**Comment by urangotango** [comment]
there is an new setting wehre you can setup on how manny % chance the bot have to use berrys 
default setting is 35% chance  so if the chance is higher than 35 % the bot will not use berrys

**Comment by Onono88** [comment]
Ops my mistake thank you so much :)
