### ISSUE TITLE
Bot wanders out of radius

### ISSUE THREAD

**Issue by bkrandy** [Ar1i/PokemonGo-Bot#3289]
![mapbot](https://cloud.githubusercontent.com/assets/20913426/17639870/b962c6ba-60ab-11e6-9c33-149949f10036.png)

Radius set to 600m, and is currently wandering beyond that

**Comment by IceQ1337** [comment]
WoW. This could actually be a real "Issue" :DD
Does he move away from the specified radius or does he walk just past the border-line.

**Comment by bkrandy** [comment]
it walks well past the radius, heres a updated pic

![mapbot](https://cloud.githubusercontent.com/assets/20913426/17639967/2aee870a-60ad-11e6-982a-63d8684ab168.png)

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by IceQ1337** [comment]
@bkrandy I think i figured it out.
I will check it when i'm awake again.

**Comment by bkrandy** [comment]
@IceQ1337 awesome
