### ISSUE TITLE
How do I set start location to my own coordinates without ERROR

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#329]
Error says that I am too far away from 'starting' location and when I put it at Santa Monica Pier, I do not walk to any pokestops?

I'm tired of walking around central park and finding the same pokemon over and over again.

**Comment by absoluttechno** [comment]
Put in by speed 10000000km /h

Wait till it arrives and the softban-unbanner starts after a few tries to catch oder get pokestops


After unbanned message comes wait for 5 catches or 5 pokestops get.

Restart the bot <3

**Comment by steezespot** [comment]
Can you explain?

I set the coordinates to where I want to start. And I did put speed 10000000km/h. It reaches and starts to see pokemon but fails to catch 'they run away' due to softban.

But I wait and it never gets 5 catches for me to restart bot? 

![screenshot_2](https://cloud.githubusercontent.com/assets/20720517/17268638/0f765e08-55e5-11e6-9b68-c040ede2b8b0.png)

**Comment by steezespot** [comment]
After I teleport to the location i want (not central park default) using 10000000km/h, i wait like 5 minutes and it finally works.

But my setting is still 1000000000km/h, how do i reduce this to 50km/h? When I reset the bot, it goes back to central park.

**Comment by kclo4** [comment]
Easiest way is to first delete LastCoords.txt, set new location to whatever you want, ????, Profit.
