### ISSUE TITLE
Favorite Pokemon

### ISSUE THREAD

**Issue by deviljin666** [Ar1i/PokemonGo-Bot#3290]
Hello. I have all the pokemons and i have added them as favorites. I want to farm for new but i dont want to loose those i have added as favorites. On Pokemon - Not to transfer if i select NONE, will i loose my favorites?

**Comment by IceQ1337** [comment]
They will get transfered if their IVs and CP are below the maximum IV and CP to transfer you set.

**Comment by deviljin666** [comment]
If i choose them all not to be transfered? i will keep all of them? and favorite and non favorite?

**Comment by IceQ1337** [comment]
If you select the pokemon in the "not to transfer" list, not a single one of it's kind will get transfered.

**Comment by deviljin666** [comment]
then maybe its a good idea to add an option to keep favorites... :)

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8
