### ISSUE TITLE
Motorola Devices

### ISSUE THREAD

**Issue by nerbock** [Ar1i/PokemonGo-Bot#3292]
Why doesn't have Motorola telephones? im have Moto X play and cant add,have one method to im add manually or help you to add?
 Thanks for all my friends and if possible add Etherium donations.

**Comment by IceQ1337** [comment]
Provide us with the following information, maybe we can add your device to the list.
(I'm not sure if @Ar1i is actually going to add more devices, so don't expect anything.

`            { "moto-x-play",
                new Dictionary<string, string>()
                {
                    { "AndroidBoardName", "" },
                    { "AndroidBootloader", "" },
                    { "DeviceBrand", "" },
                    { "DeviceId", "" },
                    { "DeviceModel", "" },
                    { "DeviceModelBoot", "" },
                    { "DeviceModelIdentifier", "" },
                    { "FirmwareBrand", "" },
                    { "FirmwareFingerprint", "" },
                    { "FirmwareTags", "" },
                    { "FirmwareType", "" },
                    { "HardwareManufacturer", "" },
                    { "HardwareModel", "" }
                }
            },`

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by HSMatheus** [comment]
Pls add Moto G2
