### ISSUE TITLE
Bot dosent work?

### ISSUE THREAD

**Issue by favtim96** [Ar1i/PokemonGo-Bot#3293]
I have no idea why it dosent work
![fehler](https://cloud.githubusercontent.com/assets/20910729/17640134/a24c23aa-60fa-11e6-9c19-2b5fd7bb375d.png)

**Comment by xxKevinSniperxx** [comment]
you are most likely banned

**Comment by favtim96** [comment]
If I log in at my mobile Phone, i don't had any Problems like I banned?
All things are ok

**Comment by Thinkinge** [comment]
same here, I use my main acc, and it doesn't work, but when I change the acc ( a test acc) it works. I don't know why , but I use my phone with my main acc, there is no problem

**Comment by favtim96** [comment]
exactly the same problem at my account. If I log in to an other account, it works. at my account in the Bot it doesnt work, but at the mobile Phone I doesnt had any Problems like these

**Comment by igkobzxd** [comment]
Restart Browser its 90% fix

**Comment by favtim96** [comment]
I also deleted the Bot and install it again, but always the same problem

**Comment by igkobzxd** [comment]
Restart browser its 90% fix
i fix mine that way

**Comment by k3npachi** [comment]
change your IP

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by elffish** [comment]
It's so great that  some of you guys can still log it. One of my bot account has been banned for hours. The logging screen on the cellphone it says "failed to get game data from server". There are posts saying once this is over and you get connect, the pokedex will be cleared and your account will be reset. :(

I am monitoring that account using my other account. One of my pokemons in the bot account is still holding gyms. At least that's good. But everyone... stop using bots. I manually played that bot account to lv 22, if it's gone, I still feel sad.

**Comment by Juiche** [comment]
yes some of player after got that notice, their character rolled back to lvl 1

**Comment by elffish** [comment]
I do have another manually played low level account that only tested bot once. It's logging in without problem. But sadly it's on a different team... so weird attacking gyms my other account is holding... lol. I would wait for another several hours see if my bot account is been reset or not. :(

**Comment by itamoye** [comment]
dude i think pogo server is down look at this one http://ispokemongodownornot.com/
and this http://www.mmoserverstatus.com/pokemon_go do not have ping at many country

if that permnt ban, why if im try on this site https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ and login, no one notice i get ban (sry my english bad)

**Comment by FacuM** [comment]
I have already experienced the "Failed to get game data from server" and nothing happened after, just had to tap several times until the connection got successfully reached. It's latency is too high, and the servers are too overloaded.

**Comment by bboylost** [comment]
@FacuM Thanks for the info dude , my gmail account is having the "Failed to get game data" screen, it has been almost 12 hours, how long did it last on yours and was it google account ?

**Comment by elffish** [comment]
@FacuM Were you just keep tapping "retry "and get in? Is everything in your account still there?

**Comment by dstN** [comment]
#3233 stop opening the same issue on and on again
