### ISSUE TITLE
error connect

### ISSUE THREAD

**Issue by Touch-My** [Ar1i/PokemonGo-Bot#3294]
hello, error for connect : 

![mik](https://cloud.githubusercontent.com/assets/17107837/17640256/42ad7b9a-60fc-11e6-8214-b6003def1fa9.png)

**Comment by igkobzxd** [comment]
Try to restart browser

**Comment by Touch-My** [comment]
I restarted the game, I even uninstall and reinstall it makes me ig and also via the bot

**Comment by generaljoke** [comment]
whats the connect with browser seriously ? just change your ip for god sake what a dumb answers

**Comment by Touch-My** [comment]
I tested with another connection made her the same things

**Comment by generaljoke** [comment]
CHANGE IP NOT THE CONNECTION

**Comment by Touch-My** [comment]
if I change connection it also changes the IP ... it is a logical

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by Touch-My** [comment]
song pokemon no resolve problem !

**Comment by wa666** [comment]
Your account is banned. ^^

**Comment by generaljoke** [comment]
so you mean you have different kinds or enough connection or isp just to change your ip everytime you banned ?

**Comment by Touch-My** [comment]
I logged on pokemon club via their website not he says I'm banned knowing that this is the first time I used a cheat, which launches this not seen the error of listing of the Pokemon

**Comment by wa666** [comment]
Banned temporary.. 12 hours ?

**Comment by Touch-My** [comment]
how to know?

**Comment by wa666** [comment]
Tu est français ?

**Comment by Touch-My** [comment]
oui

**Comment by Touch-My** [comment]
tom.pels

**Comment by rvonz** [comment]
it permaban dude
stop crying oke, coz my accs too

**Comment by itamoye** [comment]
dude i think pogo server is down look at this one http://ispokemongodownornot.com/
and this http://www.mmoserverstatus.com/pokemon_go do not have ping at many country

if that permnt ban, why if im try on this site https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ and login, no one notice i get ban (sry my english bad)

**Comment by rvonz** [comment]
hmmm hopefully
I have give up if it is perma ban

**Comment by dstN** [comment]
#3233 stop opening the same issue on and on again.
