### ISSUE TITLE
brauche mal hilfe :) 

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#3296]
guten abend habe gerade einen softban bekommen auf lvl 22 
es stand zwar dass er entbannt wurde 
aber er sammelt keine pokestops mehr ein weder ep noch items 
jemand ne ahnung ? z.b wie lange dieser softban ist

**Comment by Elvete** [comment]
REsolve https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by Flashnasty** [comment]
sehr hilfreich xD ^^

**Comment by LordTrupa** [comment]
Ich glaube 20 min.....
