### ISSUE TITLE
Error(methodnotfound)

### ISSUE THREAD

**Issue by jaschoo1988** [Ar1i/PokemonGo-Bot#3297]
There's a problem after extract the file, when trying to launch the exe file, a pop up show error message as screenshots;

Unhandled exception : system.missingmethodexception:methodnotfound
![13987874_10154304354879627_2071448857_o](https://cloud.githubusercontent.com/assets/21001049/17640449/5a99f194-6132-11e6-92e8-2d1c01909f87.jpg)

it's the os system too outdated for this file? using windows 7 btw...

**Comment by suljo94** [comment]
No the os is not outdated but he coudn't find a specific task try redownloading the bot then just past the new files on top off the old ones and click replace current files with new files in the pop up

**Comment by jaschoo1988** [comment]
@suljo94 

its a first time users, he dun have any old files... or maybe is the winrar version too lousy make extraction got problem?

**Comment by IceQ1337** [comment]
Make sure to have visual studio or at least its components (dont have links on mobile device, sorry) installed. Download the newest version and try starting the bot via visual studio.
