### ISSUE TITLE
[Request] Anti-ban functions

### ISSUE THREAD

**Issue by xdlinkimo** [Ar1i/PokemonGo-Bot#3299]
Let the bot plays more like a human, please add some functions:
1.  Delay between each catch.  (Let user define seconds)
2.  Let user define delay between each actions.
3.  Auto resting. (Let user define running how many minutes before taking a short break or log out)
4. Maximum Pokemon catching per hour (let user define their own number)
5. Maximum Pokemon evolve per hour and you need some delay between them, right now it's way too fast, sever can simply catch you if you evolve 10 pokemon within 20 seconds. (let user define) 
6. Maximum EXP per hour (let user define)

Thank you.

**Comment by filoh** [comment]
Good

**Comment by suljo94** [comment]
1 you can alreadt chose this (up to 3 sec randomized
2 /
3, in windows set in energiesetting the time you want it to be active bofore entering sleepmode(works only If pc is not in use but if it is in use you can do it mannually
4/
5. disable the auto evolve function set keep max duplicates to desired number and evolve mannualy when you want it
6, /

**Comment by bluecito** [comment]
Add to '' Non stop on poke stops'' at my lvl i only need stardust for upgrade pkms i not interesting lvl up. I guess too many people more. Sorry google traductor.. my english its bad ;)

**Comment by Ark4n0s** [comment]
1. Being able to choose the time range between catches (3-5 / 5-10)
2. Same as the first
3. Be able to set a maximum usage time in minutes or hours)
4. .....
5. It is not necessary, it should be a manual process to avoid ban
6. Max exp per hour, goes hand in hand with the amount of pokemon you can catch and pokestops you can take, in this case you catch some exceptions regardless of the limits placed (Dratini, jynx, etc)
7. Failure some Pokeballs or use better or random sometimes.

Extra.
Fix the bug that some pokemon are not transferred when many repeated and that this transfer is more delay between each.

I know it's asking too much but some details that can help prevent PemaBan and excuse my English, use the Google translator

**Comment by thenitramz** [comment]
+1

1. delay should be more than 3 seconds.
2. there should be delays for other actions too (evolving 10-15 sec) or transfer (at least 3 sec)
3. always 210 exp for catching is also a sign for bot (possibility to randomize or even miss some balls)
