### ISSUE TITLE
Soft Bans

### ISSUE THREAD

**Issue by Caaspaj** [Ar1i/PokemonGo-Bot#330]
So if you get soft banned can you use the console or something to unban you? I know how to manually do it but I just get banned again when I start up the console. And yes I know I can change the location or whatever to somewhere close to me but If I do I barely get any xp lol

**Comment by Tochez** [comment]
They have there own unbanning system. Just keep the bot going and it will unban you

**Comment by Caaspaj** [comment]
Oh yeah I see that. Thanks heaps

**Comment by louzifer** [comment]
can the bot always do it when u start a new run? so its better to farm a special pokemon, when using pokevision ;)

**Comment by kclo4** [comment]
> can the bot always do it when u start a new run? so its better to farm a special pokemon, when using pokevision ;)

Repeat that in English and I'm sure we can help you.

**Comment by mauxak** [comment]
The bot will detect if you are softbanned or not

**Comment by Ar1i** [comment]
^ this
