### ISSUE TITLE
brauche mal hilfe 

### ISSUE THREAD

**Issue by lostxblood** [Ar1i/PokemonGo-Bot#3301]
![pokemon erreor jpg](https://cloud.githubusercontent.com/assets/21001240/17640553/3c7d7b5c-6102-11e6-9f7b-244a6ca0e242.jpg)

ist das ein hard ban wenn ja kriegt man den weg? danke im vorraus

**Comment by FacuM** [comment]
I'm experiencing the exact same issue. Please fix.

**Comment by lostxblood** [comment]
we both get hard ban

**Comment by lailaps** [comment]
Koennte ein Hard/Ban sein.
Was passiert wenn ihr euch versucht via Handy einyuloggen_

**Comment by lostxblood** [comment]
daten zum server konnten nich geladen wrden@lailaps

**Comment by lostxblood** [comment]
@lailaps

**Comment by lailaps** [comment]
Dazu gibt es bislang keine Lösung und Antwort.
Sieht nach hardban aus.
Bisher niemand bekannt, der danach den Account wieder nutzen konnte.
Einen Level 38 Account von mir hats auch erwischt, die anderen Level 38er funktionieren seit 24 Uhr wieder, aber hatte dort auch nur den "catchflee" softban.

**Comment by lostxblood** [comment]
hab neN lv 32 acc verloren :(  Hab jz keinen anderen mehr

**Comment by lostxblood** [comment]
@lailaps

**Comment by lostxblood** [comment]
hast du vllt noch ein acc den du nich brauchst @lailaps

**Comment by lailaps** [comment]
Ich schaue mal.

**Comment by lailaps** [comment]
Hab noch einen angefangenen Level 25er. Hab den seit Tagen nicht mehr im Bot gehabt.

**Comment by lostxblood** [comment]
wäre echt korrekt wenn du den mir geben könntest haste fb poder skype oder so?
@lailaps

**Comment by lailaps** [comment]
Kann ich mailen.

**Comment by lostxblood** [comment]
ich wäre dir unendlich dankbar
meine email ist lostxblood17@gmail.com@lailaps

**Comment by lostxblood** [comment]
@lailaps

**Comment by black9140** [comment]
Mein Vater wurd auch gebannt ohne zu booten..Er ist in Italien und ich hab sein Account für Arenen benutzt und er wurd jetzt auch gebannt..und neu anfangen will der nicht :D Hast du evtl noch ein Account xD

**Comment by lailaps** [comment]
@lostxblood
Teste mal, müsstest Mail haben (ggf. im Trash folder)
Ich nutze immer die englische Version von Mail.ru da ich dort pro Mail 10 alias mails erstellen kann.
Super praktisch gewesen xD.

**Comment by lostxblood** [comment]
nice aber 
hab leider nx bekommen

**Comment by lostxblood** [comment]
@lailaps

**Comment by lostxblood** [comment]
ok hab was thx

**Comment by black9140** [comment]
@lailaps hast du noch einen account für mein Vater damit der bald wieder spielen kann?

**Comment by lostxblood** [comment]
![unbenannt5](https://cloud.githubusercontent.com/assets/21001240/17640736/e2e55b46-6106-11e6-88fc-712ca6ce1bbd.jpg)
da ist jz der error weist du was der bedeuted @lailaps

**Comment by lailaps** [comment]
Ich denke nicht, dass der Account geblockt ist. Hast das Passwort schon geändert? Wenn nein teste ich es nochmal.

**Comment by lostxblood** [comment]
ich hab nix geändert kannste machen aber musste daspasswort mit den  hhashtags eingegeben werden

**Comment by lailaps** [comment]
klar

**Comment by lailaps** [comment]
Ok, ich teste es mal eben.

**Comment by lostxblood** [comment]
ok

**Comment by lailaps** [comment]
Bekomme die gleiche Meldung, teste es mal eben mit einem anderen Bot!

**Comment by lostxblood** [comment]
ok

**Comment by lailaps** [comment]
Ok, dort auch die gleiche Meldung, hab es dann über NOX versucht, da kommt der Hinweis, dass das Passwort zu oft falsch eingegeben wurde und der Account für 15 Minuten gesperrt ist.
Entweder hast Du dich vertippt oder es war beim kopieren ggf. ein Leerzeichen mit dabei. ^^

**Comment by lostxblood** [comment]
ok ich schau mal danke trzdm

**Comment by lostxblood** [comment]
falls es dann nich funkt kd trzdm danke für die mühe:)

**Comment by lailaps** [comment]
Mach am besten folgendes, logge dich in 15 Minuten auf der Webseite ein und ändere das Passwort in was leichteres. Dann versuche es mit dem Bot.
Der Account lebt jedenfalls, es kam nicht die Data Fehlermeldung.

**Comment by lostxblood** [comment]
ok und noch mal ein riesen großes danke

**Comment by lailaps** [comment]
Gib Feedback wenn es geklappt hat.

**Comment by lostxblood** [comment]
mach ich

**Comment by lostxblood** [comment]
funkt irgendwie nich haste vllt noch nen acc da steht immer passwor falsch @lailaps

**Comment by lostxblood** [comment]
ok doch jz funkts 
@lailaps

**Comment by lostxblood** [comment]
dankeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
@lailaps

**Comment by lailaps** [comment]
Bitte

**Comment by dstN** [comment]
#3233
