### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lostxblood** [Ar1i/PokemonGo-Bot#3302]
![pokemon erreor jpg](https://cloud.githubusercontent.com/assets/21001240/17640565/7d1abf08-6102-11e6-956b-135b6b96118e.jpg)
is this a hard banif it is how to fix thanks for every answer

**Comment by hartmantam** [comment]
@Ar1i Already posted on his [Titter Channel](https://twitter.com/Ar1iDev). If you got banned, he can do nothing. So use at your own risk.

**Comment by lostxblood** [comment]
ok no problem

**Comment by barrumonk** [comment]
When it happened to me, it was cuz i was saving the config folder from the old versions, try to delete your config folder and restart, it worked for me.

**Comment by lostxblood** [comment]
dont funcion but thx anyways

**Comment by dstN** [comment]
#3233 stop opening the same issue on and on again.
