### ISSUE TITLE
Can't start bot, badly programmed line.

### ISSUE THREAD

**Issue by FacuM** [Ar1i/PokemonGo-Bot#3303]
I'm experiencing the next error:

[22:02:23] Exception: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:línea 280
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en PokemonGo.RocketAPI.Rpc.Inventory.<ExportPokemonToCSV>d__41.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:línea 514
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:línea 124
[22:02:23] Starting again in 10 seconds...
[22:02:24] Error reloading Pokemon list: Referencia a objeto no establecida como instancia de un objeto.
[22:02:26] Error reloading Pokemon list: Referencia a objeto no establecida como instancia de un objeto.
[22:02:28] Error reloading Pokemon list: Referencia a objeto no establecida como instancia de un objeto.
[22:02:30] Error reloading Pokemon list: Referencia a objeto no establecida como instancia de un objeto.
[22:02:32] Error reloading Pokemon list: Referencia a objeto no establecida como instancia de un objeto.

![image](https://cloud.githubusercontent.com/assets/3741108/17640586/2ae5b5ea-60d9-11e6-9280-ba61ae54e4e0.png)

**Comment by lostxblood** [comment]
got hard banned
 i think

**Comment by suljo94** [comment]
in stall visualstudio and its components reboot and if issue persists reupload error(preferbly in english)

**Comment by itamoye** [comment]
dude i think pogo server is down look at this one http://ispokemongodownornot.com/
and this http://www.mmoserverstatus.com/pokemon_go do not have ping at many country

**Comment by FacuM** [comment]
suljo94, thanks for your help, but I can't get it to work. Am I doing sth wrong? I don't want to download VB Studio, I'm not going to develop sth right now.

**Comment by barrumonk** [comment]
When it happened to me, it was cuz i was saving the config folder from the old versions, try to delete your config folder and restart, it worked for me.

**Comment by FacuM** [comment]
barrumonk, that was the first thing I've tried. But thanks for your help anyways ;).

**Comment by FacuM** [comment]
Any news?

**Comment by ShujiYagami** [comment]
Hard ban, proxy banned.PTC Lag, Server Down.... 
It's 4am on Dev country so...just wait.

 I'm running one right one and everthing is OK.

**Comment by FacuM** [comment]
Thanks, I'm going to wait for him to answer.

**Comment by Yaruru** [comment]
ban?

**Comment by dstN** [comment]
#3233 stop opening the same issue on and on.
