### ISSUE TITLE
Unban function (softban) not working

### ISSUE THREAD

**Issue by UncensoredMango** [Ar1i/PokemonGo-Bot#3306]
Hi,

Both the automatic unban function & "force unban" function don't appear to be working for me. I'm definitely softbanned (checking into pokestops gives no loot/xp and all pokemon flee after first try) but the bot's 1337 unban methode doesn't do anything.
No hurry, just wondering if there's something on my end that's causing it or if other people are experiencing this too.

Thanks :)

Pics for refrence:
![softban 1](https://cloud.githubusercontent.com/assets/21001368/17640696/e986d65e-6148-11e6-902c-5f254fba2606.PNG)
![softban 2](https://cloud.githubusercontent.com/assets/21001368/17640697/ee577e5e-6148-11e6-8bfc-c9a433663700.PNG)

**Comment by lailaps** [comment]
Yes, they are not working anymore. Do you live behind the moon ;)

**Comment by Millenniunn** [comment]
close your bot and wait 12 hours... and read other posts before post urs.

**Comment by UncensoredMango** [comment]
Sorry guys, just had a look. Oopsie :p

**Comment by blue7790** [comment]
just wait like 6 hour or more..will fix automatic
