### ISSUE TITLE
can't transfer pokemon 

### ISSUE THREAD

**Issue by YassineOFF** [Ar1i/PokemonGo-Bot#3308]
![demande](https://cloud.githubusercontent.com/assets/21001414/17640796/2f251f70-6100-11e6-98b3-c4c227b2aeaf.png)
![sans titre1](https://cloud.githubusercontent.com/assets/21001414/17640800/45acadbc-6100-11e6-8be4-5bfa22f3175c.png)
![sans titre2](https://cloud.githubusercontent.com/assets/21001414/17640802/4fdba18a-6100-11e6-99d0-e7346cd5156a.png)
![sans titre3](https://cloud.githubusercontent.com/assets/21001414/17640804/57a73960-6100-11e6-9d82-0f19fb4fc2fa.png)

**Comment by MaikelxD** [comment]
yes remove some pokemons
u have 241 pokemons and 9 eggs..

**Comment by MaikelxD** [comment]
select all @ pokemons to evolve

**Comment by YassineOFF** [comment]
i don't want to evolve my pokemon , i want the bot transfer my pokemon automatically , I have chosen to transfer all pokemon below than CP:420.

**Comment by lailaps** [comment]
lol...

You checked "Keep Pokemons which can be evolved"...
What do you expect will happen...

You have to uncheck it xD

**Comment by kayoriceball** [comment]
Uncheck that button and preferably turn off the IV transfer.
