### ISSUE TITLE
hey any one got a acc left my are all banned just aquestiton thx anyways

### ISSUE THREAD

**Issue by maxschnei** [Ar1i/PokemonGo-Bot#3310]

**Comment by UncensoredMango** [comment]
No sorry...

**Comment by bboylost** [comment]
this isnt any issue of the bot, please close it, NO ONE WOULD GIVE YOU FREE ACCOUNT while you have the FREE bot  , just bot another account and dont ever post this kind of retarded post here again.

**Comment by maxschnei** [comment]
no problem sry @bboylost  the bot is dont working any more on my pc

**Comment by maxschnei** [comment]
just asking

**Comment by kayoriceball** [comment]
i have 3, only one is good, i have 29, 11, and 5 i mean if you want a level 5 account lol

**Comment by maxschnei** [comment]
no but thx anyways

**Comment by Hahahaha0** [comment]
@kayoricebal Hahahaha
btw may i know what is the new issue?

**Comment by kayoriceball** [comment]
what do you mean, with the accounts or the bot?

**Comment by Hahahaha0** [comment]
both?

**Comment by maxschnei** [comment]
@Hahahaha0  has you got a maybe a acc left?:)

**Comment by bboylost** [comment]
the bot is working, you spend so much time here asking why dont you go download the new bot and test it out yourself, stop being a tard

**Comment by Hahahaha0** [comment]
i just tried my lv 1 acc... it says can't find any pokestop in range 5000m... so it was perm ban?

**Comment by TerrranceB** [comment]
working fine. yall trippin

**Comment by maxschnei** [comment]
just tried
dont work @bboylost

**Comment by TerrranceB** [comment]
put some respect on it

**Comment by Hahahaha0** [comment]
can someone answer my question?

**Comment by maxschnei** [comment]
maybe is cause of my newo perating system

**Comment by lailaps** [comment]
@ Hahahaha0  Change Ip!

**Comment by fenlyn** [comment]
im already 20 ID in banned status(Softband12Hours),,and still bot with another ID

**Comment by dstN** [comment]
NOT AN ISSUE. CLOSE !
