### ISSUE TITLE
NIANTIC already fix permanent ban issues

### ISSUE THREAD

**Issue by joe112** [Ar1i/PokemonGo-Bot#3312]
in the new bot, Ar1i said "use your own risk niantic is banning these day", yoo we are got perma ban sir, perma ban is real !!

**Comment by aznboi4sho** [comment]
I believe it...Been roughly 14 hours and still cant catch a pokemon but im just going to wait couple days to see if true hopefully not.... Crossing fingers...

**Comment by bboylost** [comment]
can you remove this useless post on the "isue" page?  Ar1i wants to keep this area as clean as possible.

**Comment by bboylost** [comment]
@aznboi4sho I can confirmed that your account is fine if you can log in still. I have accounts like this and I just waited thats all. the problem now is the accounts with the "cant get game data from server" these may be really banned.

**Comment by bboylost** [comment]
#3218 Read forum and "dont open a new issue"

**Comment by aznboi4sho** [comment]
ya thats what i have at the moment haha... So like i said cross fingers... and yay delete this post

**Comment by TerrranceB** [comment]
you fucked up bigtime
