### ISSUE TITLE
Hat  Jemand einen ac Übrig den er nich gebrauchen kann falls ja danke,danke für jede Antwort

### ISSUE THREAD

**Issue by maxschnei** [Ar1i/PokemonGo-Bot#3313]

**Comment by verybadboy85** [comment]
Wieso brauchst du ein acc

**Comment by maxschnei** [comment]
Meine wurden allle gebannt und der pokebot funkt nic mehr und 0 bock von forne anufangen

**Comment by maxschnei** [comment]
vorne
@verybadboy85

**Comment by verybadboy85** [comment]
Hast bestimmt nur nen 12 std bann. Hatte ich heute also gestern auch

**Comment by Wortan89** [comment]
Ich habe auch gedacht meiner wäre gebannt, die Zeiten wurden nur krass erhöht.
Wegwerfemail, im PokemonGoClub regestrieren und ab gehts.

**Comment by NidiKea** [comment]
Also ich bin nach wie vor auch gebannt leider.

**Comment by dstN** [comment]
this ist not an issue. CLOSE THIS PLEASE
