### ISSUE TITLE
[NOT ISSUE] Solution for the "permaban"

### ISSUE THREAD

**Issue by nekudah** [Ar1i/PokemonGo-Bot#3315]
Softbanned = ¬¬ please...
"Banned" = Can catch pokemons, can't pokestops / Cant catch pokemons, can pokestops

1- DON'T login for 6h~12h~24h on the account "banned",
2- Use Nox, and try to catch 1 pokestop, and one pokemon using the best itens possible
3- Works ? = Profit

Want to keep using bot (ban WILL come one day) ?
1- Speed 2~6 m/s
2- Don't set bot to do 192381923 things
3- Stop teleporting/sniping/flash/goku or w/e
4- Set your location different from botland (Central Park, Times Square, Disneyland, Las Vegas, Santa Monica)

Hope that works for you guys, worked for me, sorry for the bad english :)

**Comment by JokerFrown** [comment]
is would be amazing if the bot had path variation
i.e. walk in a 'squiggle' as opposed to a straight mechanical line

**Comment by maxschnei** [comment]
you got maybe a acc left mine all banned if not thx anyways

**Comment by maxschnei** [comment]
@nekudah

**Comment by nekudah** [comment]
Just have one ^^, the one I use

**Comment by maxschnei** [comment]
ok thx anyways:)
@nekudah

**Comment by kayoriceball** [comment]
Bot in foreign countries, as they are generally less prone to a mass bot ban. I use Australian parks and beaches as they spawn amazingly.

**Comment by Hahahaha0** [comment]
so what is perm ban? how did you know you get perm ban?
i just tried my lv 1 acc and it says can't find pokestop in range 5000m, is that perm ban?

**Comment by kayoriceball** [comment]
@Hahahaha0 That's usually an IP ban when it gives the 5000m error, I mean I didn't work on the bot or anything, just giving advice on past experiences. Wait like half a day or reset your IP address.

**Comment by Hahahaha0** [comment]
ohh i see... i used 3 acc and all says 5000m error... so what is perm ban btw?

**Comment by kayoriceball** [comment]
@Hahahaha0 Well the name is sort of self-explanatory, the accounts are well, banned xD

**Comment by Akuma9GK** [comment]
Also be aware that Niantic has a way of making Google ask to relogin on other devices such as Android phones. It is a way for them to detect if botting. Keep your Android phone handy to resign in.

**Comment by kayoriceball** [comment]
^ yep i resign in every time.

**Comment by suds420** [comment]
LOL I thought this was shut down?!

**Comment by Streakz** [comment]
so the message "cant get data from the server" is that means perma ban?

**Comment by xxKevinSniperxx** [comment]
what is Nox?

**Comment by Akuma9GK** [comment]
Yes it means permanent ban. And Nox is an Android emulator

**Comment by suds420** [comment]
Guys I have a question, if my accounts didnt get banned by now does that mean im safe? (I've stopped botting on them and made alternates to bot in)

**Comment by Swaggerup** [comment]
so i see your method does not work, even ultra ball cant catch weedle

**Comment by thomasdaniton** [comment]
is this method supposed to solve permanent bans? when i log in to pokemon it comes up with servers are down, but when i go onto a different account it works fine, so i think im permanently banned

**Comment by Johnnybulking** [comment]
Cant log in to nox

**Comment by lailaps** [comment]
@thomasdaniton
Nope!

**Comment by PokeMungo** [comment]
nekudah can you give me good longitude/latitude spot for this spot you mentioned:
Central Park, Times Square, Disneyland, Las Vegas, Santa Monica

TIA

**Comment by Streakz** [comment]
check this out dude..

http://pkmngotrading.com/wiki/Nests

**Comment by boylondon** [comment]
i was set walking speed to 30Km/h then in 20 minutes i had soft ban,.. now i reduce to 10KM/h seems everything fine running for 4 hours, so don't take risk for EXP/h, as long as you can bot is thankful,.. be KIND

**Comment by alerp88** [comment]
i had bot for 10hours with the new update bot. with new id. set to 50km speed. It's run smoothly without softban. One of my account got deleted by niantic ""Failed to get game data from the server."" lol :dart: I only run one bot right now.

**Comment by WhoBotWhoBad** [comment]
I got 2 bot running. It was 20m/h then... I read this thread, I immediately close all my bot and set my walking to 7km/h

NICE!  :clap:  :metal:

**Comment by nekudah** [comment]
@PokeMungo the places i said are Botlands, choose other places, not so bot populated

**Comment by coffeexp** [comment]
nahh.. i set my dummy account to 150km/h and still not banned.. well, this is just my dummy account to test if it gets perma banned or soft banned.. :) from level 1, it is now level 19 in 6~7hrs continuous running of bot.. :)

**Comment by akangnduz** [comment]
this solution is work!!!!!!!!! i can farm from pokestop but can't get any pokemon so i try turn off my acc 1 hour then start using NOX to catch a pidgey...then i start bot again and finally i can catch pokemon...already 3 hours and no softbann

**Comment by AiVo7z** [comment]
Devs detect third party progs, therefore bot. Your config doesn't matter man.... if you ain't banned yet you're lucky

**Comment by NightOwl94** [comment]
I cant catch pokemon or collect from pokestops,i can log into my acct on my phone fine but not on the bot,anyone know how I can fix the problem?

**Comment by thomasdaniton** [comment]
what is the best speed to set?

**Comment by vitus0123456** [comment]
There is not solution to permaban, permanent ban means your character's data is moved and deleted from the server.  It is gone for good.  There is no hope unless the gods at Niantic directly give mercy to your soul.  bitter truth, sadly.

**Comment by NightOwl94** [comment]
I can still log onto my phone so its not  perma ban,i can log on and do everything manually,just not on the bot

**Comment by Arkinslize** [comment]
Never got any softban/ban of any sorts.

But i don't use the bot like a madman. What's the point to be lvl 40 if it's actually impossible for a normal man to be above lvl 30? Use your brains...

I only use it 2-3 hours per day, speed:8km/h, location in my city, so if i log out 5-10min the bot, i can immediately use pokemon go on my phone.

I'm levelling up like a normal humain, but without doing the stupid grinding associated.
