### ISSUE TITLE
Is this the new Account softban?

### ISSUE THREAD

**Issue by Swaggerup** [Ar1i/PokemonGo-Bot#3317]
So i tried all my devices at same location log in and the pokestop cant be spin, it just says try again later, i tried different ip and its the same? have anyone found any new softban unban method? If yes, please share. I am working on it too by using several methods

**Comment by Millenniunn** [comment]
read other posts.... there are about 50+ posts today which have same issue as u.

**Comment by Swaggerup** [comment]
hmm for people have doubts on different ban check this: https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by james741** [comment]
not new kind of solf ban 
is permanent ban bro

**Comment by fenlyn** [comment]
no thats 12hours softban..please log on for another risk

**Comment by Swaggerup** [comment]
@fenlyn well have you been unban?

**Comment by Swaggerup** [comment]
@james741 any proved? unless you are banned for more than 24hour that could not be so sure. Well if it really is why would they not just ban your whole account but softban instead

**Comment by fenlyn** [comment]
some account already done 12 hours ban...if thats permanent ban of course ur ID not be USED/cant login ^_^

**Comment by Swaggerup** [comment]
@fenlyn hmm thanks for confirmation

**Comment by fenlyn** [comment]
for now just do like this member said..safety ways..https://github.com/Ar1i/PokemonGo-Bot/issues/3315

**Comment by Swaggerup** [comment]
@fenlyn my account has been soft ban 3 hour ago, and using the best ball to catch does not work. (tested) only way is to wait for 12hours.

**Comment by Swaggerup** [comment]
@fenlyn this is what is happening to me currently ran bot for 12hours and got softban https://www.reddit.com/r/pokemongodev/comments/4xdhut/softban_question/

**Comment by LetMeKnowYourName** [comment]
I was softbanned for 12hrs, I could catch pokémon and fight on gyms and everything, but pokéstops wouldn't get me any items. After exactly 12hrs, it gave me items again, weird part is that I don't bot in foreign lands, I bot near my home in a park with 80 pokéstops and I never let the bot take care of everything, just catching and farming, I do the rest.
