### ISSUE TITLE
checkpoint validation for ban

### ISSUE THREAD

**Issue by taisfus** [Ar1i/PokemonGo-Bot#3320]
hey, not sure anyone post this already, but if anyone actually play the actual game while in the car that is moving. It will pop up a message saying you are moving too fast and should not be playing while driving. Then it makes you click on " I am a passenger" if you don't click on that, the pop up will not go away and I am sure if you are actually playing, you will click on it since it block most of the screen. Maybe that's a new checkpoint to valid if it a human playing? Sorry I don't remember the exact message because I didn't know how to screen shot my phone. It seems like if the bot is running under 10km/h, you will only get softban, but if it goes a lot faster, you will be perm ban and if you are botting under 10k/h, the checkpoint message most likely will not popup since you are not going fast enough.

**Comment by Swaggerup** [comment]
@taisfus Thanks you for your information, that could be a possible reason for how they detect soft ban.

**Comment by Depotys** [comment]
I use a 9 km/h without a problem.

**Comment by WhoBotWhoBad** [comment]
Hmm... interesting.

**Comment by Kayl51** [comment]
I play on iphone and I is not yet updated the application, I is not the message when I am a passenger

sorry google trad English

**Comment by taisfus** [comment]
Is it possible to program the bot to click on the "I am a passenger" popup? It actually pop up very frequently, maybe every 10 or 15mins for validation. It's most likely the root issue of all this ban detection. I am sure they can't said people that are moving 30mph are all robots because some people actually drive or ride bike around the city to catch pokemon instead of walking.


________________________________

**Comment by taisfus** [comment]
Well you didn;t update yet, so that probably why you didnt see it yet. I don't remember seeing that message before, it just started.

**Comment by WhoBotWhoBad** [comment]
That is why you need to confirm that you are driving. Maybe they are really detecting through that kind of method. Say if 8 popup and still no confirmation that you are indeed driving... then youre softban or worse hard ban.

**Comment by Thikez** [comment]
I'm observing running at 8kph today. Slow, but no red soft ban message yet.

**Comment by Kill-Bot9000** [comment]
The popup only happens if you go over 20kph. At least that's what I noticed while driving around today.

**Comment by Microrock** [comment]
#Thikez 

Please confirm on next hour.

It's Work or Not ?

**Comment by angelph** [comment]
so what is the right kph? 20kph/hr?

**Comment by Kill-Bot9000** [comment]
@angelph I'd say stay under 10kph to make it less obvious that you're a bot.

**Comment by HughJanos** [comment]
I was using 5 km/h and i think i still got banned - can use pokestops but impossible to catch a pokemon

**Comment by Kill-Bot9000** [comment]
@HughJanos were you running multiple instances, or in an area that is typically botted in? (NYC, Santa Monica, etc)

**Comment by HughJanos** [comment]
no it was a park in Prague Czech Republic so i dont think

**Comment by Kill-Bot9000** [comment]
And you weren't jumping long distances in short periods of time? Like that park, then somewhere else miles away only a few seconds later, or anything? If not then it sounds like you just got unlucky

**Comment by HughJanos** [comment]
no i set the location for that park and the speed (5 km/h) and went to sleep . When i woke up everytime the bot encountered pokemon it escaped

**Comment by ajangel** [comment]
Hi i have question said trying to Restart

**Comment by ajangel** [comment]
Do you guys know what is the problem

**Comment by Kill-Bot9000** [comment]
Can you still login to the game on your phone? If so that is just a soft ban. Stay logged out for a day and it should be fine. If not then you're probably f**ked.

**Comment by ajangel** [comment]
Ok thank you

**Comment by L00N1** [comment]
Rather than that. I suppose the new softban (12 hours) is related to the speed of catching pokemons. Numerous people got banned after third continuous catch while travelling under 10km/h and not teleporting. (btw. I can confirm the 1337 unban method was working by the time i was teleporting, that means 13o'clock Prague +1) no screenshots, just trust me

**Comment by vitus0123456** [comment]
I can confirm that runing 11km/hr can get you ban.  This happened to me.  I think they know you're botting no matter what you set.  So, it is better to let things cool down a bit.  If you are still running bot but haven't got a ban yet, watch out!

**Comment by pepeyon** [comment]
Damn. This is ultra interesting, that could be a "captcha". @Ar1i hope you can see this and see if there's a possibly new anti-bot method.

**Comment by Thikez** [comment]
I'm back, bot is still running @ 8kph, no red soft ban messages, and still that almost perfect catch rate.
