### ISSUE TITLE
bot stopped, and can't access game from my mobile device

### ISSUE THREAD

**Issue by Gin520** [Ar1i/PokemonGo-Bot#3321]
after running for a night, the bot suddenly stopped and ask me to close it down.
I open the game on my mobile device, and it say it failed to get game data from server.

Is this a perm ban?

**Comment by rohit9022** [comment]
yes it is

**Comment by Streakz** [comment]
you get perma ban, congrats mate..!!

**Comment by ONOBARY** [comment]
![screenshot_2016-08-13-12-20-46](https://cloud.githubusercontent.com/assets/20884771/17641591/c8f1892c-6150-11e6-8921-2d0c680e6b7c.png)

**Comment by ONOBARY** [comment]
I HOPE MY APPEAL HAS ACCEPTED :(

**Comment by Gin520** [comment]
@ONOBARY how do you appeal?

**Comment by ONOBARY** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/requests/new?ticket_form_id=233187

**Comment by Gin520** [comment]
@ONOBARY i never received this email, did they send to you once you get banned? 
Or did you send them something first and they reply you with this?

**Comment by pingpongplaya** [comment]
well, they threw the bait. you freaked out and appeal now they can have all their fun investigating and for sure permanent banning you. congrats

**Comment by ONOBARY** [comment]
I'm not revcive email banned from niantic just I contac to niantik  I hope my account back normal again

**Comment by Kill-Bot9000** [comment]
This is why I made another alternate account and have it going at 2kph. Might be slower than fuck but I'll take slower than fuck with a lower chance of being banned. Ran it for 12 hours today with no problems.

**Comment by Microrock** [comment]
BANNED with **BOT** not BANNED with FAST or SLOW.

# It,s true story.

**Comment by ade182** [comment]
Yeah you're right microcock ~

**Comment by dstN** [comment]
#3233
