### ISSUE TITLE
Failed to get game data from server

### ISSUE THREAD

**Issue by JunoBotboy** [Ar1i/PokemonGo-Bot#3322]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by burnSMACKER** [comment]
You're banned.

**Comment by JunoBotboy** [comment]
theres nothing i can do about it?

**Comment by JunoBotboy** [comment]
anyone has any other answer

**Comment by bkrandy** [comment]
start over

**Comment by Microrock** [comment]
Try to open on your phone with new signal internet 3G , 4G  , wifi hotspot etc.

If u still get fail

I thing u get BANNED
