### ISSUE TITLE
CLOSE ISSUE

### ISSUE THREAD

**Issue by Microrock** [Ar1i/PokemonGo-Bot#3324]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

Thankyou.

**Comment by WhoBotWhoBad** [comment]
This is not the right section bro. Use google!

**Comment by Microrock** [comment]
sorry sir.

**Comment by TrainerNr1** [comment]
You can use Nox with Fake GPS.

**Comment by immoempe** [comment]
Nox has the gps feature, and this is not an issue, please close this post
