### ISSUE TITLE
Object Reference Not Set to instance

### ISSUE THREAD

**Issue by coolbuddy26** [Ar1i/PokemonGo-Bot#3326]
![capture](https://cloud.githubusercontent.com/assets/20897846/17641634/9cb61978-6145-11e6-9f1b-da19fd6d725f.PNG)

**Comment by Archimondee** [comment]
me too

**Comment by JunoBotboy** [comment]
Try the phone app to see that it says "Failed to get game data from server"

Youre both banned

**Comment by coolbuddy26** [comment]
Now what to do then ???

**Comment by bkrandy** [comment]
start over

**Comment by Eniotnacram11** [comment]
This is a permanent ban?

**Comment by Microrock** [comment]
I think about your picture It's error from BOT program only

try to open on your phone device with manual paly and new signal internet with 3G 4G etc.

if u get other massage in game on mobile device

This is BANNED

**Comment by Eniotnacram11** [comment]
![14012282_1063635377037862_1115425555_n](https://cloud.githubusercontent.com/assets/21004480/17641976/4d9d8836-6103-11e6-9a94-41448884b201.jpg)

**Comment by Eniotnacram11** [comment]
And this? what it is?

**Comment by dstN** [comment]
#3233
