### ISSUE TITLE
[Feature Suggestion] XP gain problem

### ISSUE THREAD

**Issue by Aren1984** [Ar1i/PokemonGo-Bot#3327]
When I reach LV 20, I don't care Level anymore( I know more Level meet more CP, but stardust & candy are more important)

I wish I can slowdown XP got by two way(maybe the checkbox?)

1. Catch always gain 210 XP (I think no one can do this)
 => a random to get XP, like 100, 110, ..., 210?
 => or dependent on Probability?

2. Port touch can get item and XP, but item always recycled and XP is useless(for me)
 => item has two threshold, more than X will be recycled, less than Y will touch port

Thanks the Bot developer :)

**Comment by Microrock** [comment]
I think u can farm Stardust and Candy forever 

Don't serious about XP

I need My Level for high pokemon CP.
