### ISSUE TITLE
Softban now does not just detect speed.

### ISSUE THREAD

**Issue by Swaggerup** [Ar1i/PokemonGo-Bot#3330]
I tried and now i got softban again, the speed does not matter anymore for twice, i ran for around 3 pokestop and catch 5 pokemon with 210xp and the 6pokemon i realise i was softban. I guess they now look at 210xp as well?
my speed was 9km/h radius 3000.
IP ban was no longer a issue but the softban keeps coming. somehow is detecting something

**Comment by Swaggerup** [comment]
So after 8 minutes i got unbanned again. Updated.

**Comment by Microrock** [comment]
BANNED with BOT not BANNED with speed

It's True 

Wait for developer to slove this problem

**Comment by Swaggerup** [comment]
Well its working for me with the bot

**Comment by HughJanos** [comment]
But they will not solve it... They stopped working on the bot cause Niantic was sending letters to other bot developers ... or did they not stop?

**Comment by AiVo7z** [comment]
Well since the new API they told you they can detect third Party plugins. Means you tell the devs hey here, im botting, get me, but you can't I act like a human. Don't fool yourself. Bot as you like, if they want you to get banned, they will, whatever your configs are.

**Comment by Swaggerup** [comment]
Well. As far as i know they detect 3rd party plugins with API are because for example Pokevision who uses data from pokemon go server to find pokemon nearby But for bots, correct me i am wrong. They are just auto catching, spinng pokestop scripts, fake gps, walking scripts and just like any other ordinary phone connecting to pokemon go server. There should not be a way to detect usage of bots if you are catching pokemon like how others do it legit the similar way.

**Comment by pokerave** [comment]
**I RAN THE BOT ALL NIGHT 50km/hr 1 BOT, 1 IP Proxy, NO ISSUE not BANNED ONCE.**

**Comment by Swaggerup** [comment]
@pokerave well does it still works now?

**Comment by HughJanos** [comment]
I just hope that Niantic will loose this battle :D i just aint walking!! :D

**Comment by Swaggerup** [comment]
@HughJanos theres no way they are losing and giving up Profits are at stake lel

**Comment by pokerave** [comment]
@Swaggerup i just wrote STILL RUNNING (17hrs) there right?

**Comment by HughJanos** [comment]
:D but common all my friends have issues with the game and they are not botting.. the game itself constantly changes your location - sends you over a river and such things.. and then on the other hand the bot works perfectly fine - frequent patches and updates.. Niantic just sucks :D
