### ISSUE TITLE
How many bandwidth is the PokemonGo-Bot using?

### ISSUE THREAD

**Issue by MocroMind** [Ar1i/PokemonGo-Bot#3331]
Hello Guys,

Im using the bot on a Laptop who has a build-in phonecard for data.
How many does it use?

**Comment by Microrock** [comment]
Manual play with phone device use a little data bandwidth

With BOT I don't know

sorry

**Comment by untesty** [comment]
bot uses +/- 20 mb per hour

**Comment by MocroMind** [comment]
@untesty are u sure?
