### ISSUE TITLE
I have been using bot for a long time and also this new one works just as fine. The Unban feature works too. But right now all of a sudden I am unable to catch any pokemon. I thought I am softbanned so I used the Unban feature but I am able to farm pokestops. So I am not banned? What does this mean?

### ISSUE THREAD

**Issue by Akshadraj** [Ar1i/PokemonGo-Bot#3332]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by akangnduz** [comment]
#3315

**Comment by dstN** [comment]
can you use the search before posting duplicate after duplicate?...

**Comment by elenex23** [comment]
Had the same issue. 16 hours later everything was normal.
