### ISSUE TITLE
Permanent ban/Server issue/Soft ban? Let's figure out!

### ISSUE THREAD

**Issue by thomatbu** [Ar1i/PokemonGo-Bot#3333]
I have an error: "Failed to get game data from server" when I open Pokemon Go. Some people say that it's permanent ban. But...
I tried to fake a Japan ip address and create two new accounts (both Google and Poke Club)

And I got this message on both two new accounts that I just created:
https://gyazo.com/6fbef0e0e84531892b9361f8be19f298

Then, I checked server status here:
http://www.mmoserverstatus.com/pokemon_go

As you see, the server is down (high ping) at United States, Google Login, Poke Club.
I thought if I changed ip address to Japan, it would work fine to check.
That's why I chose Japan ip address.

So, the question is why some people still can play normally (bot and legit)
Can you comment here and tell us:
+ Your location
+ Your Login account (Google or Poke Club)
+ Which problems are you having?(Can't catch pokemons but can spin pokestops, and fight gym/Can catch pokemons but can't spin pokestops/Or more....)
+ If you are using bot or playing legit well. Try to create two new account with new Google account and Poke Club account to check if you can play/login/catching/spin pokestops normally.

I don't believe that they can ban us easily like this. Or if it's possible, we need to know how they can.
And...shhhhhhh. Niantic is watching. Do it as fast as possible. Like a ninja.

**Comment by Kapperoni** [comment]
I can confirm, it's either a permanent ban, or a new type of softban. I have both botted accounts, and legit ones. Yesterday I thought it was the server status, but I was clearly wrong, as I can log in fine on new accounts I make. I can log in on all my accounts, except one account, on which I used super obvious bot configs.

**Comment by maudron** [comment]
Me too i have 3 accounts, 2 for bots and 1 legit well. This night i use the bot and this morning the account bot appear error "Failed to get game data from server" 
This is permanent ban no? :(
I'm from spain

**Comment by AiVo7z** [comment]
Don't think you can find a method that you not going to get banned by botting. It never been safe and that should be common sense. Some bans are totally random and even those I know who played legit for real struggle with new bans. Looks like their failureqoute of giving out bans is pretty high even to non botters. But tbh it's impossible to get your account back, while fair Players can still email them and explain themself and only Need to wait for devs to unlock again, a botuser doesn't even Need to try. Botting is too obvious, we're greedy.
We send 'em back to fast, evolve too fast, catch too fast, travel to fast (and too Long!) not every fake ip works btw. 
Only Thing you can do, create a couple of accounts. Bot with every ofe them, as soon  as you're satisfied (i.e. lvl 30) Switch to another. If all of 'em are 30 try to get one of the acc further. If all of 'em are banned just quit or repeat al over. That's what I do...

**Comment by Microrock** [comment]
Last night in Thailand ( +7 )

I use bot 1.1.0.4  I got the red massage soft banned 3 times in 10 minutes

I use unbanned button it's work all

Now i stop to use BOT and wait for slove by developer

(I can play with my phone device without BOT)

**Comment by alleyezonme420** [comment]
Just wait it out see afterward math

**Comment by Kapperoni** [comment]
I think there are plenty of ways for Niantic to catch someone botting. It's pretty simple and easy, however this is all my speculations and it's not proof. 

- Character movement speed, anything below 10km/h is safe
- How fast you level up, leveling up fast flags your account, so make sure you take breaks every now and then.
- How much EXP you get per hour
- Same device as 1000 other people (ie. Nox, BlueStacks, these bots)
- Multiple accounts on the same IP at the same time
- Multiple accounts on the same device simultaneously
- Niantic's own logs
- How many PokeStops used per hour
- IP's location and account's location(GPS spoofing) can't be different
- Device model (Nox, BlueStacks, Emulators, bots)
- Character teleportation from country to country in 1 minute (Sniping)
- Who has a nickname, a team, starter pokemon and an avatar. (When we use the bot on a fresh account, it won't have a nickname, avatar, team or a starter pokemon, so for that account to level up, it's pretty fishy)
- Number of previous softbans, and the reasons (Too many softs bans can result in perma ban)
- The obvious places everyone bots (Santa Monica Piers, Central Park, All the Disneylands, Times Square, Bryant Park, Metropolitan Museum of Art, etc.)
- Logging on the same account, on two devices at the same time (ie. Your phone and the bot, or the bot and NOX/Bluestacks)
- KM's walked in one day, I doubt anyone can walk over 100 KM's in one day

**Comment by NidiKea** [comment]
I understand. Niantic writes it to me they will ban if you cheat in all ways. I have 3 Children and a husband und my sons play the game and we both to on the same Wlan. But i think this is ok? Or not? 3g is expensive at prepaid cards in the cell phones and so they must use at home wlan.

**Comment by Swaggerup** [comment]
So as you can see as long as you are able to access your account. You are not perm ban, why would they allow you to see pokestop and pokemon if you are perm ban? does'nt make sense to me.
If you are unable to access the server with multiple account that would means the server issues.
For people who are unable to spin pokestop with the "try again later" or unable to catch pokemon. It is just a temp softban, it will go away. Max ban can be up to 24hour as far as i have experience.

**Comment by NidiKea** [comment]
Na there stands no player data found. And i cant log in

**Comment by NightOwl94** [comment]
I cant hit pokestops or catch pokemon,can log onto the game on my phone just not the bot,ill try again tomorrow afternoon

**Comment by Kapperoni** [comment]
@NidiKea Using the same IP(Wlan/Wifi), different accounts and devices is okay. As long as you guys don't log in on the same device, it's okay.

**Comment by Swaggerup** [comment]
@NidiKea as far as if you are unable to log in with different devices and account with similar IP you are probably account banned.
@NightOwl94 You should just wait for around 3-7hours and try again if not wait for 24hour. It should be good again.

**Comment by coffeexp** [comment]
getting softban now at level 20.. force unban not working.. lucky egg and incense are running..

**Comment by Microrock** [comment]
I try to test bot with new ID 

it's work a hour ago.

speed 5 km/h only

[url=http://www.uppic.org/share-30AE_57AED389.html][img]http://www.uppic.org/thumb-30AE_57AED389.jpg[/img][/url]

**Comment by whizzyke** [comment]
So for those with iOS (iPhone) and getting "Failed to get game data from server" here is how I managed to login.

- delete app (Pokemon GO) from device
- goto setting - safari - Clear History and Website Data
- redownload app (Pokemon GO)
- joy

Hope it helps. I had the error messege yday and this morning but was waiting to see whats going on. Did these steps mostly to clear up catch etc. as many other apps tends to use Safari catching etc.

Cheers,
Whizz

**Comment by Arkinslize** [comment]
It's working for me. Never got any ban on any sorts.

Since it's almost impossible to be above lvl 30 without using it even if you played a lot since the beginning, i don't use it more than 3h per day and stop using it if i'm making progress too fast.

For my settings, speed: 8km/h, location: in my city, so if i log out 5-10min, i can use  pokemon go on my phone.

**Comment by maudron** [comment]
Not working for me because im banned
