### ISSUE TITLE
So nun spiele ich nicht mehr.....

### ISSUE THREAD

**Issue by NidiKea** [Ar1i/PokemonGo-Bot#3334]
Ich hatte einen zweiten Account auf dem Tablet. Hab den in Holland im Urlaub hoch gelevelt und jetzt in Deutschland bis heute morgen gespielt. Heute morgen hab ich mich aus geloggt und dann wieder eingeloggt und nun ist er gebannt????? Das bedeutet wenn ihr euch ausloggt dann werdet ihr gebannt. 
Also hab ich nun keine Lust mehr . Also bloss nicht 2 Accounts haben und aus oder einloggen bleibt eingeloggt!!!

**Comment by eNNj0y** [comment]
habe mich direkt ausgeloggt & wieder eingeloggt.

Geht.!

**Comment by NidiKea** [comment]
Hast du dich dazwischen mit einem anderen Account eingeloggt? Also wie gesagt davor lief er ohne Probleme und nach 5 Minuten , wo ich mich wieder einloggen wollte...nix mehr. Und wie geschrieben hab ihn nur auf dem Handy benutzt

**Comment by NidiKea** [comment]
Das schlimme ist, ich bin damit wirklich in Holland rum gelaufen und hab Pokémons  gefangen ...das ärgert einen echt schon sehr

**Comment by untesty** [comment]
(Sorry can't speak german but I do understand) I had the same issue so I tested it with a couple accounts. I figured that you should wait at least 30 minutes between log out and sign in. Then it worked fine for me. Even when I switch accounts I leave 30 minutes in between and it's fine

**Comment by NidiKea** [comment]
Ich hab Niantic mal angeschrieben:


Trainer,

We have received your appeal. Our goal is to provide a fair, fun and legitimate game experience for everyone. Use of any other third-party software or app, including but not limited to scripts/apps, applications used to falsify your location, using emulators, modified or unofficial software and/or accessing Pokémon GO clients or backends in an unauthorized manner is considered cheating.

Please consider your account permanently terminated unless we reply back to your appeal.

-NianticOps

Kann mir jemand den letzten Satz übersetzen? Meint das: bitte versteh dass dein Account permanent gebannt wurde und wir melden uns?
Hat das schon wer gemacht dort hin geschrieben?

**Comment by NidiKea** [comment]
untesty: thank you for your request but now its to late

**Comment by AiVo7z** [comment]
Nein, das heisst sollten wir nicht auf deine Anfrage antworten, gehe davon aus das dein Account permanent gebanned wurde (in dem Kontext zurecht gebanned)

**Comment by AiVo7z** [comment]
Keine Antwort = zurecht gebanned, für immer ;)

**Comment by dstN** [comment]
this is not an issue. just close.

**Comment by AlpaEZPZ** [comment]
nidikea ich hatte genau das selbe problem wie du.
Du musst eine weile warten, solange du dich einloggen kannst bist du nicht permanent gebannt.
Ich hab ungefähr 12 stunden warten müssen bis mein account wieder pokemon fangen konnte und pokestops looten konnte.

**Comment by NidiKea** [comment]
nein, ich kann mich nicht einloggen und meine Söhne wurden automatisch ausgeloggt und können sich nun auch  nicht mehr einloggen. Die haben bestimmt keinen Bot oder Cheat benutzt sondern ihre Beine

**Comment by AlpaEZPZ** [comment]
wie schnell hast du deinen bot laufen lassen ? also in km/h

**Comment by NidiKea** [comment]
Bei den Account meiner Söhne und diesem gar nicht.  Beim anderen 7

Am 13.08.2016 10:20 schrieb "AlpaEZPZ" <notifications@github.com>:

**Comment by AlpaEZPZ** [comment]
7 kmh ? ich bin mit 25 gelaufen... hmm das klingt komisch.
War der bot mal eingeloggt als auch deine kinder sich eingeloggt haben ? also bei pokemon go.

**Comment by NidiKea** [comment]
Ja ich glaube ja. Wir waren in Holland dann in Deutschland und mein einer
Sohn ist mit Oma in Holland und wurde dort nun gebannt.

Am 13.08.2016 10:23 schrieb "AlpaEZPZ" <notifications@github.com>:

**Comment by AlpaEZPZ** [comment]
also an deiner stelle würde ich noch 24h warten und vorallem mal die logindaten überprüfen.
Sollte es nach 24h nicht gehen kannst du den niantic support anschreiben und denen etwas darüber erzählen das deine kinder das spielen und du FÄLSCHLICHERWEISE! gebannt wurdest obwohl du NIEMALS einen bot benutzt hast. Bleib da hartnäckig, ich mein stell dir mal vor ich benutze in einem cafe mit meinem laptop in deren freiem wlan einen bot. das würde ja bedeuten das alle die derweil auch eingeloggt sind im wlan des cafes, einen bann bekommen. Ich würde versuchen so zu argumentieren.
Ihr wart in holland im urlaub und vielleicht war in einem öffentlichen wlan wo ihr was getrunken habt jemand der gecheated hat.

**Comment by AlpaEZPZ** [comment]
falls du mehr hilfe benötigst schreib mir auf twitter 
https://twitter.com/Schiggy_Meute
falls dein "issue" hier geschlossen wird.

**Comment by NidiKea** [comment]
Hab ich mal versucht.  Kenne mich mit Twitter noch nicht aus lach

Am 13.08.2016 10:36 schrieb "AlpaEZPZ" <notifications@github.com>:

**Comment by AlpaEZPZ** [comment]
jo nur falls du mal wieder was wissen willst.
weil drei gebannte account sind ja schon blöd...
