### ISSUE TITLE
CAN I USE 2 ACCOUNTS IN BOT??

### ISSUE THREAD

**Issue by janusmiranda** [Ar1i/PokemonGo-Bot#3336]
Can i use 2 account in bot?? anyone?? ty :D

**Comment by Sobro111** [comment]
dunno, if you got any program which changing ip , actually bot work just on 1 ip

**Comment by getta22** [comment]
you can copy the bot files twice then use them with different accounts, I do it all the time :smiley:

**Comment by Microrock** [comment]
DANGER !

**Comment by Swaggerup** [comment]
lel anyone here working with only 1 bot 1 IP and still working for at least 2-3hours now?

**Comment by dstN** [comment]
this is not an issue. close.

**Comment by starscream151** [comment]
lol, people stop using the bot for a while, cause of the new ban,
and you here ask "CAN I USE 2 ACCOUNTS IN BOT??"
just wait bro...
close this

**Comment by elenex23** [comment]
what @starscream151 said

**Comment by Microrock** [comment]
@elenex23 

@janusmiranda

http://www.uppic.org/image-27A5_57AEE440.jpg
