### ISSUE TITLE
If you want to bot, here is a new SLOW method.

### ISSUE THREAD

**Issue by Swaggerup** [Ar1i/PokemonGo-Bot#3338]
-10km/h speed (checked)
-Under 1000 radius (checked)
-untick box below radius setting (checked)
-Click do not catch any pokemon (checked)
-Using only 1 bot (checked)
-Only 1 device log into account (checked)
-1 Ip address (checked)

Its good to go~ :)
Currently status for me: No softban, No IP ban, No account ban
Timer: Been 62 minutes (testing new things max timer 62 minutes )
Actually it is a very super duper slow method for people who do not want to get ban, well you get to hatch your eggs ;)
_**Well :) the bot seems fine now for me with catching pokemon unless you are scare continue using this if not check this -> #3338 (No softban, No IP ban, NO account bans)**_

**Comment by starscream151** [comment]
Ar1i will update the bot later,
so just wait..........................
close #3218 
![cgchfgfghhffgfgjjghggjkjkjhhhkkkhjuntitled](https://cloud.githubusercontent.com/assets/20950801/17642292/ad2f5156-6169-11e6-8cb8-aaa2bee62f8c.png)

**Comment by Swaggerup** [comment]
Well it is working so just sharing this method for people who can't wait but still farm slow exp :)

**Comment by mosty1982** [comment]
becarfull the most dangerous r the first and the third options in the list ( -10km/h speed (checked) and  -untick box below radius setting (checked)) 99% of guys get banned cos of those

**Comment by Swaggerup** [comment]
hahahaha if you are that scare just stop botting and go play it the legit way. We are people who bot all the way, we have nothing to lose. Updated time.

**Comment by Hyperbeam** [comment]
well.. i'm still playing with 5000 m radius and 50 km/h speed and nothing happened.. running since yesterday

**Comment by mosty1982** [comment]
lol man i say ur right in the list not as u think i said the most important the first and the third 1 in the list >D

**Comment by elenex23** [comment]
ty hyber beam. im at 8 about to turn up to 30. wish me luck

**Comment by pokerave** [comment]
@Hyperbeam You are right. me too. but im using 1 bot per ip

**Comment by Swaggerup** [comment]
One reason is they sense your perfect catching. i tried it thrice and after few catches i got softban

**Comment by Swaggerup** [comment]
@Hyperbeam well good for you

**Comment by mosty1982** [comment]
yes me too but after while they unban me and again and again just like that its very slow to level with this banns

**Comment by elenex23** [comment]
ive been perfect catching all day long. The bot started mass evolving when i try to turn up speed so i cut it off. Now I wait 12 mins again before trying anything.

**Comment by mosty1982** [comment]
elenex23  -untick box below radius setting (checked) u need to do this

**Comment by Swaggerup** [comment]
@elenex23 hmm thanks for information, i am going to try catching pokemon again with some changes

**Comment by elenex23** [comment]
@mosty1982 ty bud that is a good tip

**Comment by mosty1982** [comment]
no i think when he restarted the bot his character teleported to the defaula location he get banned

**Comment by elenex23** [comment]
My radius is only 800 so if i wait 12mins its enough time to adjust and wait on api

**Comment by Swaggerup** [comment]
@mosty1982 No.. if i am not wrong. yesterday i posted a tread on that if you have that on he will sometimes teleport in game. But i am certain if you restart the bot it always go back to default location

**Comment by Microrock** [comment]
Slow   but   Sure

I just to test with Main ID now ^^

my config

http://www.uppic.org/image-B4D7_57AEDD1F.jpg

Slowdown All Trainner.

**Comment by Swaggerup** [comment]
@Microrock glad to hear that :)

**Comment by elenex23** [comment]
I turned my bot up to 35+ and it seems to be working well. I'd advise not using 50 as default. I'd go lower but for example choose your speed 51, 39, 45, 21 etc

**Comment by Microrock** [comment]
**# It's WORK

Keep slowdown Keep your Life.**

HAHAHA

**Comment by shadowahs** [comment]
I am testing the default settings on a new account, it has been over 4 hours, leveled up to level 19, no bans whatsoever (yet, hopefully stays this way).
I dont recommend anyone using the default settings though

**Comment by bertojk** [comment]
5 hours my bot are still going
Setting:
speed 15 kph
radius 10000 m
1 ip address
can catch + take item

hope @Ar1i can modified about speed so we just input minimum and maximum speed and bot will run randomly (for example 15-38 kph)
