### ISSUE TITLE
Troy Disc?!?

### ISSUE THREAD

**Issue by NikiMon** [Ar1i/PokemonGo-Bot#3339]
I just got a troy disc, wtf is that?

**Comment by Microrock** [comment]
- -*

**Comment by Swaggerup** [comment]
@NikiMon well that is a very rare item most of us have not seen it before, we have no idea what it does but it is in the code of pokemon go.

**Comment by Microrock** [comment]
look like Tron Disc ?

http://emblemsbf.com/img/55051.jpg

just kidding

**Comment by Swaggerup** [comment]
@NikiMon could have a screenshot because there has been people seeing it but we have no idea if it really exist or if it is real.

**Comment by NikiMon** [comment]
@Swaggerup well, if i want to look at my items i have to stop the bot and open it on my phone and i will probably be banned, is there a way of looking in the inventory while the bot is running?

**Comment by Swaggerup** [comment]
@NikiMon well..it should not affect anything if you restart your bot

**Comment by NikiMon** [comment]
@Swaggerup but the bot is running in a different location to where i live, if i open the account on my phone now, i will probably be banned

**Comment by Microrock** [comment]
screenshot please

**Comment by NikiMon** [comment]
@Microrock wait a sec

**Comment by Swaggerup** [comment]
@NikiMon =_=...its just a soft ban at most

**Comment by NikiMon** [comment]
@Swaggerup ok, well ill try

**Comment by Swaggerup** [comment]
@NikiMon wait off your location on your phone before going in

**Comment by NikiMon** [comment]
![13978074_919529328192865_2092188339_o](https://cloud.githubusercontent.com/assets/20946517/17642395/fb24f0de-6144-11e6-88a9-82667398fe97.jpg)

**Comment by Swaggerup** [comment]
@NikiMon oh it is probably a lure module i guess

**Comment by NikiMon** [comment]
@Swaggerup yup, on my phone theres absolutely nothin

**Comment by AiVo7z** [comment]
You lvled up it seems? There's no such reward for any lvl :(

**Comment by Microrock** [comment]
Not from Pokestop. From lv up.
