### ISSUE TITLE
[News] Ban changed

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3342]
This is no issue in useage of the bot, still some guys here probably want to know.

I've been botting with a couple accounts and one of my accounts had already 10h softban while all other got free after waiting period.
That softbanned account could catch pokemons, fight Arenas, walk around, could hatch eggs BUT NOT spin pokestops.

I waited approx 24h and now it keeps saying (only for this account) gamedata failed to load from Server. I guess this is a perm ban, no matter what you guys say. I've been trying with diffrent devices as well as diffrent times, multiple times within the early morving till now and every account instantly logs in (normal pokemon go without mod/hack/bot) except this account.

I guess there's not much hope left once you get this error, some of those may still appear even tho you're not banned but the Server laggs. But in my case and amny others it's obvious. Don't bother to send log to niantic, they won't even reply and remain those accounts banned.

**Comment by Swaggerup** [comment]
Well... you must have did some brave decision to get ban..

**Comment by justicero** [comment]
I have a question for you AiVo7z, is this account banned one was over level 35 ?

**Comment by AiVo7z** [comment]
Lvl 33....

**Comment by justicero** [comment]
i had a theory. I used bot on 2 accounts one with EU ip one with US ip both got perma banned once they hit level 36. I am thinking once you hit over 35 they verify it somehow and if it is bot they ban it.

**Comment by AhmedVohra** [comment]
It is not physically possible to reach level 31 above, even if you play 24/7

**Comment by AhmedVohra** [comment]
I recommend you stop leveling up at lvl 30

**Comment by wa666** [comment]
@justicero  my account banned level 37..

**Comment by mosty1982** [comment]
my accounts perm banned r level 14, 19 , 26 , and level 39 this last 1 was monstr account full pokedex with 5 100% dragonites, i know other ppl,s hacking 30+ but nothing happen to them

**Comment by AiVo7z** [comment]
My other account is lvl 31 almost full pokedex 3 dragonite (low iv but maxed wp 3k if I remember right) tons of garados etc. and not even softbanned, can Play since 2-3 days without hacks and anoy everyone around in gyms, but I liked my lvl 33 acc way more, even better pokemons ... sigh.
