### ISSUE TITLE
IF you like botting~, lets take some risk. It is still quite bugged but these happen (Working fine as of now, BANNING over seems fine with bots again)

### ISSUE THREAD

**Issue by Swaggerup** [Ar1i/PokemonGo-Bot#3343]
![wtf](https://cloud.githubusercontent.com/assets/20989926/17642411/08d112b6-6178-11e6-9174-291a049f510c.PNG)
![lol the](https://cloud.githubusercontent.com/assets/20989926/17642412/0c1c5d40-6178-11e6-8dce-f47de0c59b95.PNG)

**PLEASE when botting, try not to go oversea like superman flying. 
-Bot in near your current location. 
-One device log in. 
-One IP address (do not keep changing like mad man)
-One bot running only one man ONLY ONE**

Well i got softban while trying and was trying some new configuration and it seems to work fine now.
Just some bug
Will update again later on the setting to use.
Here is the setting i am using:
![1](https://cloud.githubusercontent.com/assets/20989926/17642425/1eb27fc4-6179-11e6-82a9-c9c8d38bf0f0.PNG)
![2](https://cloud.githubusercontent.com/assets/20989926/17642426/20e8c096-6179-11e6-9862-7b4efcd4402a.PNG)

As you can see it bugged and i caught with 310xp as well as it somehow unban me with the 1337 unban method
I am currently testing to see how long it can run and if it is safe catching pokemon with 210xp.
Timer: Been running for 29 minutes still no sign of bans
Currently it seems like niantic have stop softbanning people? i have no idea? It work now. (NOT Guarantee ) Comment below what you think?

**Comment by Swaggerup** [comment]
Check the slow method if you are scare @3338

**Comment by Microrock** [comment]
# It's WORK

# Keep Slowdown Keep your Life

**Comment by Swaggerup** [comment]
@Microrock LeL

**Comment by NightOwl94** [comment]
I'm getting an error pop up so I can use the bot

**Comment by Swaggerup** [comment]
@NightOwl 94 screenshot?

**Comment by NightOwl94** [comment]
sorry to ask this but how do you ss?

**Comment by Swaggerup** [comment]
@NightOwl94 your computer should have a build in app "Snipping Tool" just use it and save it then share the picture here

**Comment by elenex23** [comment]
i can assure you 30-40 km/h is fine. tested on 2 accounts so far

**Comment by Microrock** [comment]
Still running with slowdown   Main ID

http://www.uppic.org/image-C780_57AEE8F2.jpg

**Comment by Swaggerup** [comment]
@elenex23 well i am going back to slow farming in about 3hours from now. The ban wave might come again at night. Probably only after the bot get updated :P if not i going to hide at night
@Microrock Well slow and steady win the race

**Comment by NightOwl94** [comment]
![capture](https://cloud.githubusercontent.com/assets/20989898/17642524/71b7a60e-618d-11e6-97bb-da3a916e6c42.PNG)

**Comment by NightOwl94** [comment]
that's what I getting

**Comment by Microrock** [comment]
@Swaggerup 

I just to go to hide with you about 3 hours later

for sneak the ban wave.

**Comment by elenex23** [comment]
@Swaggerup ban last night was exactly at 11pm pst. It is past that now just fyi but good luck

**Comment by NightOwl94** [comment]
@Swaggerup do you know anything about this error I'm getting

**Comment by Microrock** [comment]
now 16.45 on THAILAND [+7]

what time to hide for me?

**Comment by elenex23** [comment]
pardon my french but dont be a pussy

**Comment by kopralnjono** [comment]
i am not activate my account for 10 hours before, then i teleport to some place with 19 hour flight in real life. so, there is a gap of 9 hour.  it work..everything normal

**Comment by volturi04** [comment]
failed to get game data from the server
permaban??

**Comment by Swaggerup** [comment]
@NightOwl94 are you sure is there such account?

**Comment by NightOwl94** [comment]
@Swaggerup I got the info correct I'm sure of it,ill retype it in and tell you if it changed

**Comment by Microrock** [comment]
try to login google account on PC

**Comment by NightOwl94** [comment]
@Swaggerup it logged in now,not sure what went on

**Comment by Swaggerup** [comment]
@NightOwl94 probably server issues or you type wrong information. it sometimes happen.
