### ISSUE TITLE
Can't Find Pokestops

### ISSUE THREAD

**Issue by JusticeRD** [Ar1i/PokemonGo-Bot#3345]
The Bot was working all day till i closed it.
Now every time I log in this pops up.
![untitled](https://cloud.githubusercontent.com/assets/20825639/17642470/4c3da440-60fd-11e6-9dcf-3ddbd69f4dc1.jpg)
Not sure if anyone else is getting the same problem.

**Comment by Swaggerup** [comment]
@JusticeRD You just got IP banned, restart your router

**Comment by JusticeRD** [comment]
Okay thanks mate.
