### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by Magn5405** [Ar1i/PokemonGo-Bot#3346]
Danish Translation
`{
	"accountType":"Kontotype:",
	"username":"Brugernavn:",
	"password":"Adgangskode:",
	"locationSettings":"Lokations instillinger",
	"speed":"Fart:",
	"moveRadius":"Radius:",
	"meters":"Meter",
	"startFromDefaultLocation":"Start fra standardlokation",
	"botSettings":"Bot instillinger",
	"autoTransferDoublePokemon":"Automatisk overfør dobbelte pokemons",
	"maxDupPokemon":"Max. dobbelte pokemons",
	"maxCPtransfer":"Max. CP til at overføre:",
	"maxIVtransfer":"Max. IV til at overføre:",
	"telegramSettings":"Telegram instillinger",
	"infoline1":"Denne bot er gratis og åben kilde hvis du har betalt så spørg om at få en tilbagebetaling",
	"infoline2":"Når du ser navnet 'Pokecrot' Så fortæl alle at det er stjålent.",
	"maxPokeballs":"Max. Pokebolde:",
	"maxGreatballs":"Max. Superbolde:",
	"maxUltraballs":"Max. Ultrabolde:",
	"maxMasterballs":"Max. Mesterbolde:",
	"maxRevives":"Max. Genoplivere:",
	"maxTopRevives":"Max. Top-Genoplivere:",
	"maxPotions":"Max. Trylledrik:",
	"maxSuperpotions":"Max. Supertrylledrik:",
	"maxHyperpotions":"Max. Hypertrylledrik:",
	"maxToppotions":"Max. Top-trylledrik:",
	"maxRazzberrys":"Max. Bær:",
	"totalCount":"Samlet:",
	"pokemonNotToTransfer":"Pokemon - Ikke til at ovføre",
	"selectAll":"Vælg alle",
	"pokemonNotToCatch":"Pokemon - Ikke til at fange",
	"pokemonNotToEvolve":"Pokemon - Ikke til at udvikle",
	"saveConfig":"Gem konfiguration / Start bot",
	"otherSettings":"Andre instillinger",
	"useLuckyeggAtEvolve":"Brug Lykkeæg til at udvikle",
	"useRazzBerry":"Brug bær",
	"germanPokemonNames":"Tyske pokemon navne",
	"useIncese":"Brug røgelse hver 30 minutter",
	"evolvePokemonIfEnoughCandy":"Udvikl pokemon hvis der er nok slik",
	"enablePokemonListGUI":"Pokemon liste GUI",
	"keepPokemonWhichCanBeEvolved":"Behold pokemons som kan udvikles",
	"autoIncubate":"Automatisk ruge(Ingen garanti for at det virker)",
	"useBasicIncubators":"Bruge basale inkubatorer"
}`

**Comment by FoolYah** [comment]
i love Danish ppl <3
