### ISSUE TITLE
brauche hilfe :/

### ISSUE THREAD

**Issue by Flashnasty** [Ar1i/PokemonGo-Bot#3347]
ich kann Pokemon Fangen jedoch bekomme ich keine EP oder Items mehr von Pokestops 
es stand softban detected 
habe ganze nacht den bot ausgelassen 
ist der jetzt Permanent gebannt ?

**Comment by AiVo7z** [comment]
Hatte gleiche Problem gestern, heute perm banned... muss bei dir nicht sein und ja das wurde hier 1000x gefragt, genau das...
