### ISSUE TITLE
[SOLVED] New update error at launch

### ISSUE THREAD

**Issue by HoloryTV** [Ar1i/PokemonGo-Bot#3348]
`[11:42:25] Exception: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 280
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<ExportPokemonToCSV>d__41.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 514
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() dans C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 134`

**Comment by wa666** [comment]
Il s'agit d'un bannissement permanent.

**Comment by HoloryTV** [comment]
Ah c'est bien ce que je pensais, merci !
Bizarre que l'application ne le dise pas directement.

**Comment by wa666** [comment]
Beaucoup de rumeurs à ce sujet. Il parait que c'est un nouveau type de soft ban on ne sais pas.

**Comment by HoloryTV** [comment]
Wait and see, merci pour la réponse rapide.

**Comment by wa666** [comment]
Je suis français t'inquiète et aucun problème
