### ISSUE TITLE
Brauche Hilfe -_-

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#3349]
Ich kann keine Pokestops in meiner Nähe finden.
Wie behebe ich das?

**Comment by AiVo7z** [comment]
Email an niantic und dich beschweren das du für Bot benutzten einen Softban bekommen hast. Die entblocken dich wieder, oder du wartest 48h

**Comment by xxhamsterxx** [comment]
@aivo7z Ich hab den Bot zuletzt vor einer Woche genutzt. Soviel dazu -_-
