### ISSUE TITLE
Pokemon sell systemdoesnt work

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#335]
I have 30 pinsir and i have activated that I only need 3 per pokemon.
Can you please fixthis bug?

**Comment by SlDracon** [comment]
For me it's working. (2 per pokemon) What have you set for "Max CP to transfer"? And do they have higher CP?

**Comment by SlDracon** [comment]
Or do they have higher "Max IV to transfer"?

**Comment by kclo4** [comment]
> I have 30 pinsir and i have activated that I only need 3 per pokemon.
Can you please fixthis bug?

Might they be above CP 999 which is pre-set? 

Change it to higher if that's the case.

**Comment by Ar1i** [comment]
Change that what the ppl told its working.
