### ISSUE TITLE
Permanent Ban is real! Not server error.

### ISSUE THREAD

**Issue by thomatbu** [Ar1i/PokemonGo-Bot#3350]
I have 1 account with error " Failed to get game data from the server"
After being banned, I can spin all pokestops, take all items, fight gyms. But I can't catch any pokemon, all of pokemons fled away.
So we have no doubt that server error or softban.

I create a new account and it works fine with bot and legit playing on phone too.
So I can confirm with everyone and myself. PERMANENT BAN IS REAL if you get the same error with me.
*crying in the cornor* my level 37 account :((

**Comment by wa666** [comment]
My account level 37 is banned
errror read servers

**Comment by thomatbu** [comment]
I know that feel bro :(((

**Comment by wa666** [comment]
may be new soft ban?

**Comment by Swaggerup** [comment]
@thomatbu I am not sure about "failed to get game data from the server" it could be due to server lag or your account is banned try again in few hours
As for your accounts that you can logged into but you cant spin pokestop with "try again later" or catch any pokemon it is just a minor softban

**Comment by wa666** [comment]
@Swaggerup maybe ""failed to get game data from the server"" new type of soft ban?

**Comment by Swaggerup** [comment]
guys please read the issue treads before posting. there is information solution all there. but the banwave is currently over bot are working fine as of now

**Comment by Swaggerup** [comment]
@wa666 retry it with another account if it is all the same it is server issue if not your account is banned.
Well there is suggestion to prevent hard core botting and getting ban read the **treads...**

**Comment by M31860** [comment]
When you get the message " Failed to get game data from the server", try to create an account with the exact name like the banned one.  If this works your account is maybe deleted...
When you cant catch any pokemon or farm at pokestops or can farm but not catch, but you can login, its a softban. My account was banned 12 hours yesterday. Now everything is fine again.

**Comment by Swaggerup** [comment]
Check my treads #3343 and #3338

**Comment by wa666** [comment]
@M31860 12 hours ban and you can not connect to you?

**Comment by M31860** [comment]
@wa666 
I could login but not farm and catch...

**Comment by Microrock** [comment]
you can spin all pokestops, take all items, fight gyms. But you can't catch any pokemon, all of pokemons fled away.

I think it's not BAN

If you get BANNED you can not to login game

This is basic for all game.

May be you just to reinstall game and test by new signal internet.

**Comment by wa666** [comment]
We can not log in game..

**Comment by Swaggerup** [comment]
lel.. these people not reading the treads people have post it over and over again..

**Comment by thomatbu** [comment]
I have this error about 1 day, new account is normal

**Comment by omega2016** [comment]
Bot cant catch Pokemons again. Farming is ok

**Comment by Maxpentrator** [comment]
No permabans are not real!!!

**Comment by M31860** [comment]
You just have to wait...

**Comment by thomatbu** [comment]
The problem is 12 hours ago, I still can log in and spin pokestops and fight gyms. Then 6 hours later, I got error when using bot and I can't log in that account anymore. That error is shown

**Comment by Swaggerup** [comment]
It just probably means your account is banned. Check your gmail if it is google account niantic might have send something. If not issue a request to niantic: https://support.pokemongo.nianticlabs.com/hc/en-us/requests/new?ticket_form_id=265607 
or appeal your ban: https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

**Comment by thomatbu** [comment]
No email from Niantic btw

**Comment by Swaggerup** [comment]
Ban only happen when you either 
-teleporting like GOKU
-flying at speed of lightning
-Sending too much request for the bot

You are asking for it. You have been warned over and over again in the treads i have posted so many post as well as others here.

**Comment by M31860** [comment]
Just wait and do not start your bot every 5  minutes...

**Comment by rvonz** [comment]
sending to much request to bot? what do you mean @Swaggerup ?

**Comment by mosty1982** [comment]
heads up guys i already lost 4 accounts 1 of them level 39 full pokedex 5 dragonights 100% +3.4k 5 grad, 3 vapor, 2 flor, and 1 charaza,, all r full :D my new account is already 22 but soft ban lol

**Comment by M31860** [comment]
Many requests=starting your bot every minute

**Comment by mosty1982** [comment]
@M31860 bro i tried everything the slow method may work for 12 hour but at end u may catch soft ban i think the perfectball issue need to be fix

**Comment by Swaggerup** [comment]
@rvonz It is the same as for example transfering all your pokemon and evolving a lot of pokemon at once if you make your bot do things so fast its very obviously you are botting. we would try to avoid something like this.

**Comment by rvonz** [comment]
ohh i see, thanks dude

**Comment by M31860** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20891505/17642700/0908d7dc-6150-11e6-93bd-832023d61f23.jpg)

**Comment by Swaggerup** [comment]
@M31860 yea we are all waiting these are just temporary solution

**Comment by rvonz** [comment]
i'm waiting for this

**Comment by Mayban36** [comment]
Stop with this post GOD.
NOBODY knows what this type of "ban" means, permban not confirmed, niantic said NOTHING. If it was a real ban they would sent to you an e-mail telling you that. All the pics you see around the web of an e-mail of niantic saying "account banned"(Its always the same picture) its complete garbage, not true. Just wait and stop this threads.

**Comment by Swaggerup** [comment]
@Mayban36 It is not confirmed but adding a ban appeal in niantic support just might be a perm ban for hackers, i see no reason why niantic need to inform us of perm ban, it does not concern most of their legit users. The community have niantic as back up for introducing a perm ban. If you are unable to log into your account but other account work fine. Expect for the worst.

**Comment by M31860** [comment]
Like i said...

**Comment by rvonz** [comment]
emmm hopefully
