### ISSUE TITLE
Pokestop IMG debug in console

### ISSUE THREAD

**Issue by maxlehot1234** [Ar1i/PokemonGo-Bot#3356]
Hi, in the console, for each pokestop, I have this error:

![image](https://cloud.githubusercontent.com/assets/5159244/17983856/ac4aa08e-6adc-11e6-8d82-34faad3887b6.png)

It is weird, but all works fine. Any way to update the bot and remove this?

Thanks again

**Comment by gkal19** [comment]
extract zip in Build Only Folder

**Comment by JustinVermeij** [comment]
Also got this, fresh install. Extracted the RAR file inside the Build only folder.

**Comment by ali117major** [comment]
how do you extract the rar file inside the build only folder? thank you

**Comment by xJustx** [comment]
It's only a debug message. You can ignore it.
