### ISSUE TITLE
PokemonGo-Bot

### ISSUE THREAD

**Issue by Gigant123** [Ar1i/PokemonGo-Bot#3359]
Hello !
I've been using your bot for a while, it's the best I've seen.
But one of my accounts were blocked because we caught 8 pokemon in 15-20 seconds. It happened in front of my eyes when I was watching the history log.
So my suggestion is this; can you please add more options to the  "Random Sleep @Catching 1-3 seconds"? So that I could add more? Like any number? I don't mind slow speed of exp gathering, if I can protect account from the ban.
Sincerely, Michael
Thank you again for the work you are doing!

**Comment by Ar1i** [comment]
added
