### ISSUE TITLE
I Dont Want To Stay in Central Park Default Spawn

### ISSUE THREAD

**Issue by steezespot** [Ar1i/PokemonGo-Bot#336]
How can I move to somewhere else? I do not understand the settings!

**Comment by joshfedo** [comment]
Change your location, youll need to long/lat of where you want to go.  google some thing like disneyland longitude and latitude will give you what you need.

**Comment by mauxak** [comment]
Press Set location an change your location. To avoid walking from central Park to your new location please delete lastcoordinates.txt
