### ISSUE TITLE
Why we take  500 from  pokestops? 

### ISSUE THREAD

**Issue by Xysas** [Ar1i/PokemonGo-Bot#3361]
![xp](https://cloud.githubusercontent.com/assets/20915192/17988689/9896ae58-6b30-11e6-91d1-951edf2e1c28.png)

**Comment by lvling8057** [comment]
may i know what meaning of red color words? cause i have this issue

**Comment by ali117major** [comment]
i cant even find the exe file to launch after extracting wtf

**Comment by Trifauce** [comment]
i have the same errors...

**Comment by viplavip15** [comment]
same errors

**Comment by Xysas** [comment]
@lvling8057  bro  just download the new update
 ffs!!

**Comment by NiklasDevYT** [comment]
the bot is not finish

**Comment by Logxn** [comment]
Its not an error.
Its a debug message => Logic.cs, Line 335 - remove that.

**Comment by Logxn** [comment]
To fix the pokestop exp:

Logic.cs, Line 360 Logger.ColoredConsoleWrite(ConsoleColor.Green, $"Farmed XP: {fortSearch.ExperienceAwarded}{fortSearch.GemsAwarded}{", Egg: " + egg}, Items: {items}", LogLevel.Info);

this must be

 Logger.ColoredConsoleWrite(ConsoleColor.Green, $"Farmed XP: {fortSearch.ExperienceAwarded}{", Egg: " + egg}, Items: {items}", LogLevel.Info);

**Comment by Ar1i** [comment]
fixed
