### ISSUE TITLE
Problem with berries

### ISSUE THREAD

**Issue by lDarkcito** [Ar1i/PokemonGo-Bot#3362]
At one point remains stuck with the message that is using berries, also do not get a message indicating how many Pokeballs and berries have obtained in each pokestop , and the xp gained out 500 or 1000 , 
I have also problems when place me on the map, does not recognize me altitude, is a mistake ?

**Comment by deadelf0** [comment]
Same, I having a problem with the berry bug, sometimes it keeps throwing berries even though I have 0, usually it happens catching Staryu. One more thing is, I think it could be the proxy I'm using I change them so much. but sometimes the bot well crash out of nowhere with the white error messages. The previous build is working excellent still. Thank You. I was really happy when I seen the Pokemon images started working without an error.

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
fixed
