### ISSUE TITLE
is this safety if i start botting with this new version?

### ISSUE THREAD

**Issue by lvling8057** [Ar1i/PokemonGo-Bot#3363]
![untitled](https://cloud.githubusercontent.com/assets/21250633/17989108/6d5dac78-6b5d-11e6-8871-994568fdc837.jpg)

**Comment by TeamRedd** [comment]
i'm using the old version right now cap is lvl 21-24 all my lvl 25 and up account is ban , 11 account  ban so far haha , I know nothing about the new version just waiting for a positive feedback then I will try it out=)

**Comment by ali117major** [comment]
when i extract i cant find find the exe file to launch the bot, please help

**Comment by lvling8057** [comment]
but old version never remind someone about this notice

**Comment by lvling8057** [comment]
ali117major : i'm not sure i did it correct or not.. sorry i can't teach you cause i scare you will be banned if wrong message to you..

**Comment by ali117major** [comment]
Hey man dont worry, im not asking about bot configuration, my problem is that when i download the zip file, i extract it to my desktop but once i open the files on my desktop, i cant find any exe file to launch the bot. basically i only have files and no pokemon go bot icon to click on to launch the bot. Im seeying people saying to extract zip in Build Only Folder, how do i do that? thank you so much!

**Comment by yanyzor** [comment]
@ali117major:  Hey man in the folder you extract there is a folder called PokemonGo-Bot-master\Builds Only  extract and there you will find (PokemonGo.RocketAPI.Console)
is not the final version he is working on it , hope i was helpfull

**Comment by lvling8057** [comment]
ali117major: i have facing this case before. you must closed your firewall before you extract. im not sure your case same as my problem but you can try it actually..^^

**Comment by ali117major** [comment]
Thank you so much to both of you it finally works :D! Feels good man, have a great day

**Comment by vglaprimo** [comment]
have anyone tested the updated version of bot?

**Comment by rvonz** [comment]
hmm what is this?
![capture-20160826-114854](https://cloud.githubusercontent.com/assets/20837463/17994478/35af8898-6b83-11e6-90bc-e3d72302a634.png)

**Comment by lvling8057** [comment]
ali117major: you welcome..^^ you too..

**Comment by lvling8057** [comment]
vglaprimo: i haven't try it yet...^^ maybe i will try it later

**Comment by Logxn** [comment]
Yes this version is "safe".

It works. 
If you get banned, no one can say.
Its a testing version

**Comment by Buckrogers81** [comment]
We are testing since this morning and evenrything looks good as far. It will be interessting to see what happens if the accounts go past Level 25
