### ISSUE TITLE
Pokestop bug

### ISSUE THREAD

**Issue by generaljoke** [Ar1i/PokemonGo-Bot#3364]
![image](https://cloud.githubusercontent.com/assets/20971723/17990698/a057db46-6b6a-11e6-9bea-c7a3efd28980.png)
****

showing 500xp in pokestop

**Comment by giullyan** [comment]
The same thing happened to me

**Comment by lvling8057** [comment]
i think all people have the same issue here

**Comment by Logxn** [comment]
Logic.cs, Line 360,  Logger.ColoredConsoleWrite(ConsoleColor.Green, $"Farmed XP: {fortSearch.ExperienceAwarded}{fortSearch.GemsAwarded}{", Egg: " + egg}, Items: {items}", LogLevel.Info);

must be

Logger.ColoredConsoleWrite(ConsoleColor.Green, $"Farmed XP: {fortSearch.ExperienceAwarded}{", Egg: " + egg}, Items: {items}", LogLevel.Info);

**Comment by Ar1i** [comment]
fixed
