### ISSUE TITLE
Antiban suggestions (i know this is the wrong path)

### ISSUE THREAD

**Issue by Emmi911** [Ar1i/PokemonGo-Bot#3365]
I can't find the section for suggestions. Sorry for posting here.

1.
Can you add random walking speed?
2 fields to select the speed. For example 5-15 km/h.

Would be more human like.

2.
Also a selection to turn on random item recycling. If u recycle every pokeball once u hit 20 it's quite obvious to detect that it's not a human. Adding a random +-1-3 would be better. Sometimes the bot recycles at 18 pokeballs sometimes at 22. 

3.
Rest option. Option to select a range when the bot should take a break. Either log off or just chill at 1 spot, maybe the option to stay at 1 pokestop for a specific range.

Example: Break every 20-150 minutes for 3-10 minutes. Pokestop (yes/no). Log off (yes/no)

Probably wrong API calls get the most people banned but once that is fixed niantic will probably spot bots with those things mentioned earlier.

**Comment by Buckrogers81** [comment]
Or, maybe the Option to Stay at PokeStops if there is a location with 2 or more Stops with active Lockmodules

**Comment by gitovahere** [comment]
We need to set a device ID so we're all coming from a unique "mobile device." If we all have the same device ID then basically we all are using the same "device." Ex: android-we8768sad7f98

**Comment by Ar1i** [comment]
@gitovahere look at the source next time, its generated the first time you start the bot m8

**Comment by czokalapik** [comment]
@Ar1i Use device info like in NecroBot where you can set all required device info from your phone (not only device ID)

@Emmi911 randomize walking speed, random item recycling - YES! and set warning above 5kmph walking speed, because its normal human walk speed, going up to 9kmph in some cases

Plus: 
* set max pokemons/pokestops per 24h you can catch to current softban limits 
* use walking using actual streets

atm i think NecroBot is most human-like bot out there and those ideas come from there, 5/5 of my accounts using it survived ban waves.

**Comment by fakybaby** [comment]
Zusätzlich wäre es sehr gut, dass man auch die würfe weniger perfekt gestalten könnte.
ich habe im echten leben noch keinen einzigen wurf mit 210 xp quittiert bekommen, ... ich denke so 15% 210 xp wären sicher besser als volle 100% der würfe...

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by spamverdacht98** [comment]
Es wäre auch sinnvoll, wenn es möglich wäre eine Art "Zurück zum Ausgangspunkt" zu machen. So dass man z.b. eine Laufzeit von 3 Stunden und dann läuft er zurück zum Ausgangspunkt und der Bot meldet sich ab bzw. beendet sich. Normale Spieler beenden Ihre Runde auch meistens am Anfangspunkt.

**Comment by fakybaby** [comment]
Zum Thema Egg-Hatching denke ich, dass es eine zusätzliche Abfrage geben sollte, in der Form, dass wenn ein Ei unter XX Meter fällt, "intensiver" Beobachtet wird, dass nach dem eigentlichen ausbrüten, nicht z.B. noch 2 Pokemon gefangen werden, 3 Pokestops gedreht werden, usw....
So wie es jetzt ist, jedenfalls in der Ausgabe, rennt man noch mit unter eine ganze Weile herum bis das geschlüpfte Pokemon abgeholt wird und erledigt noch so einiges davor.

**Comment by MTK4355** [comment]
> Es wäre auch sinnvoll, wenn es möglich wäre eine Art "Zurück zum Ausgangspunkt" zu machen. So dass man z.b. eine Laufzeit von 3 Stunden und dann läuft er zurück zum Ausgangspunkt und der Bot meldet sich ab bzw. beendet sich. Normale Spieler beenden Ihre Runde auch meistens am Anfangspunkt.

I like this. I'll add this logic to the "Time to Run" feature soon.

**Comment by MTK4355** [comment]
> Zum Thema Egg-Hatching denke ich, dass es eine zusätzliche Abfrage geben sollte, in der Form, dass wenn ein Ei unter XX Meter fällt, "intensiver" Beobachtet wird, dass nach dem eigentlichen ausbrüten, nicht z.B. noch 2 Pokemon gefangen werden, 3 Pokestops gedreht werden, usw....
So wie es jetzt ist, jedenfalls in der Ausgabe, rennt man noch mit unter eine ganze Weile herum bis das geschlüpfte Pokemon abgeholt wird und erledigt noch so einiges davor.

Can someone please translate this to English for me? Google mangled it, but I want to understand the suggestion.

**Comment by MTK4355** [comment]
> Use device info likoe in NecroBot where you can set all required device info from your phone (not only device ID)

Can you tell me what device info you need? I don't have a copy of the necrobot code, and their repository is obviously gone now, so....

**Comment by spamverdacht98** [comment]
Mir ist aufgefallen, dass bei der Auswahl des Handys immer die identische Mac Adresse in der Deviceinfo.txt steht. Die ersten 6 Stellen gibt den Hersteller des Gerätes an, die müssen natürlich übereinstimmen. Der letzen 6 Stellen sollten über einen Zufallsgenerator erstellt werden.

**Comment by Schnitzelvernichter** [comment]
Fixes #3365
