### ISSUE TITLE
Is Proxy Enabled Not Working?

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#3366]
I am getting an IP banned but when i tried enabling the proxy, i cant login.. but without proxy enabled, i can login but cant find usable pokestop..

Screenshots:
PROXY DISABLED:
[https://postimg.org/image/pqgm3bonl/]

PROXY ENABLED:
[https://postimg.org/image/gwppm81ox/]

i tried 5 different proxies already.. :)

Thanks!!

Cheers! Happy Botting!

**Comment by pilota56** [comment]
My Proxy works fine. I think ist a Problem with your Proxy.

**Comment by Logxn** [comment]
^ proxy works
