### ISSUE TITLE
how to update i but it in the old file but didnt work...

### ISSUE THREAD

**Issue by bakerbaqa** [Ar1i/PokemonGo-Bot#3367]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Logxn** [comment]
"How to put everything in the title so no one can read your actual problem"

**Comment by bakerbaqa** [comment]
what?

**Comment by Logxn** [comment]
Cant you explain your problem properly?
