### ISSUE TITLE
Cannot login with phone while bot is running

### ISSUE THREAD

**Issue by siapaa1** [Ar1i/PokemonGo-Bot#3369]
Im start using new bot since morning and i'm away from computer while my bot is still running.
But now i'm just want to checked my account through pogo official apps (without turned on the GPS) but it says unable to authenticate, i guess my account is get banned now
![screenshot_2016-08-26-16-36-39_com nianticlabs pokemongo](https://cloud.githubusercontent.com/assets/20996733/18001179/b90294c4-6bab-11e6-9695-3d56f4c3a198.png)

**Comment by NiklasDevYT** [comment]
You Are banned

**Comment by Logxn** [comment]
Yeah no shit, when you are still using emulators.

Emulators do not send sensor data to Niantic.
Which means you get banned 2fast. (Same is with GPS Fakers)

**Comment by siapaa1** [comment]
Lol, but i'm not using Nox or emulators to login with my bot account.
But it's okay. Thank's btw bro 💃

**Comment by Logxn** [comment]
I can see the black button to move around :D?

**Comment by siapaa1** [comment]
Yah, it's quick ball i'm using it with my android like the iphone hahahaha

**Comment by Logxn** [comment]
Yeah its getting you banned

**Comment by Buckrogers81** [comment]
Why log in wile the Bot is running???? Its obviously what will happen!
