### ISSUE TITLE
Who knows a good place where I can find a pickachu?

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#337]
Please send me the coordinates or the place where i can find it

**Comment by Doberok** [comment]
46.481168, 30.757161 in the park

**Comment by xxhamsterxx** [comment]
which one is what?

**Comment by xxhamsterxx** [comment]
Should I disabel default location?

**Comment by HaydarOzturk** [comment]
I don't this is the right place to ask. This is not a forum!
