### ISSUE TITLE
about updating

### ISSUE THREAD

**Issue by carlo266** [Ar1i/PokemonGo-Bot#3371]
do wee need to do something to update  or it will  be automatic that our bot will be updated

**Comment by Logxn** [comment]
you need to download manually

**Comment by carlo266** [comment]
which is the latest version can you teach me sir, can i have the link. Thank you in advance

**Comment by Logxn** [comment]
https://github.com/Ar1i/PokemonGo-Bot/archive/master.zip

**Comment by carlo266** [comment]
What will i do to that ill extract that to my bot that im using or what? I'm really sorry sir because i dont know how to do with this i all already done downloadin that sire hehe.

**Comment by Logxn** [comment]
make a new folder.
extract it there.
go into the builds only folder
extract the zip 
open exe
set it up

**Comment by carlo266** [comment]
is this official or this is not done yet?

**Comment by carlo266** [comment]
sir how can i remove the debug message?

**Comment by Ar1i** [comment]
wait for an offical update of the build only or compile it yourself
