### ISSUE TITLE
.NET Error (New Update)

### ISSUE THREAD

**Issue by Hydro420** [Ar1i/PokemonGo-Bot#3376]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18005891/71b3aaf2-6b62-11e6-9e64-fcd39b8f94fc.png)

**Comment by Oliver4Vood** [comment]
me too! wth?

**Comment by lvling8057** [comment]
i have this problem also..

**Comment by Hydro420** [comment]
Just wait it out guys - should be a quick fix, or use an older version for now.

**Comment by Oliver4Vood** [comment]
how long wait fix? CHEEKI BREEKI

**Comment by Logxn** [comment]
^ Debug on your own

**Comment by deadelf0** [comment]
Right now this new build is working great! Thanks Man.

**Comment by Hydro420** [comment]
Yup! No issues with current build.. (Please close issue). THANK YOU!!! Much appreciated.
