### ISSUE TITLE
Just what is it?

### ISSUE THREAD

**Issue by Jeremy2131** [Ar1i/PokemonGo-Bot#3377]
![1](https://cloud.githubusercontent.com/assets/20999549/18006026/4dbbd4d2-6ba6-11e6-93c6-59493c1fdb88.jpg)
If u need translate i can,or use translator :D

**Comment by lvling8057** [comment]
what is this actually?

**Comment by Hydro420** [comment]
Had same issue - You did not copy/overwrite some files..

**Comment by deadelf0** [comment]
I tried both update methods I get this error when I use a proxy, the a few mins it starts up. I will try to extract the update correctly once more, But I see no difference in doing that.

**Comment by ShaaiLo** [comment]
i have the same issue

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
download newest and delete the old folder complete
