### ISSUE TITLE
force unban not working, every pokemon flee

### ISSUE THREAD

**Issue by angelcuenta** [Ar1i/PokemonGo-Bot#3378]
i have changed proxy/ip and still "softbanned" any tip'?

**Comment by Hydro420** [comment]
Yea - stop running 15 bots at once...

**Comment by MTK4355** [comment]
!5 bots gets you an IP ban, you would not find any pokestops in any range. 

There is a bug if you run out of normal pokeballs all Pokemon flee. Make sure your inventory is not full and increase the number of normal pokeballs you keep from 20 to 500 or 100. 

I'm about to submit a pull request with a potential fix but I just haven't finished testing it.

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
@MTK4355 fixed it, thanks!
