### ISSUE TITLE
Dont show Pokestops to Map / Pokeballs/ Deviate from preset Range

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3379]
![12345](https://cloud.githubusercontent.com/assets/21258333/18008472/e7c13432-6bb0-11e6-834b-ea4f036363c1.png)
Doesnt show the pokestops as it supposed to
When there are no available pokeballs it doesnt use greatballs till it find more pokeballs from stops(dont know if thats a glitch),ofc  i dont have pokeball set to 0 it just run out of pokeballs sometimes.

**Comment by Hydro420** [comment]
Its set to use certain balls for certain CP's (as far as I know). It will farm balls and catch more, just let it do its thing.

**Comment by k0ut4li4n0s** [comment]
I wanna add that it goes out of the range that i ve set too

**Comment by deadelf0** [comment]
Oh, cool The poke stops just started showing up on the map!

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by MTK4355** [comment]
You have to open the location map right away when you start the bot for the pokestops to show up, or wait for the logic to circle back around to the pokestop search bit. 

The bot will leave your designated range from time to time (especially if you run out of usable pokestops inside your radius) but again, the logic has to loop around to the point where it notices and walks you back to your default location. 

Some intelligent refactoring could fix these issues, but that kind of reorganization takes time. Fork the repo and give it a shot. :)

**Comment by MTK4355** [comment]
@k0ut4li4n0s are you using the latest version? @Ar1i recently merged some changes that should tell you when you are out of pokeballs and start using greatballs.

Please let me know if you have the latest updates and are still seeing this problem, because I worked on that logic yesterday and I hate leaving bugs in my code. lol.

**Comment by k0ut4li4n0s** [comment]
@MTK4355 At moment i set my pokeball/greatball limit to 50/50 but i didnt see the problem again although i think it was because i was getting too fast out of pokeballs,but it shouldnt use the next better option for example greatballs?

**Comment by MTK4355** [comment]
![image](https://cloud.githubusercontent.com/assets/11677019/18028450/546a02a0-6c45-11e6-8fa3-3f9ca5b9b028.png)

You should see this when you run out of pokeballs now. It will say so, then switch to greatballs.

**Comment by k0ut4li4n0s** [comment]
@MTK4355 great so i can set my pokeball back to 5 again :P

**Comment by k0ut4li4n0s** [comment]
The problem i was saying about the range

![12345](https://cloud.githubusercontent.com/assets/21258333/18029699/fe29352e-6ca7-11e6-8d42-f57cd04bc090.png)

**Comment by MTK4355** [comment]
Interesting.. I've never seen mine wander that far. Definitely something off there. Can you close this issue and create a new one with a focused title and only your last post? 

It is difficult to manage a project backlog when issues are nested like this.

**Comment by k0ut4li4n0s** [comment]
@MTK4355 Sure i will open a new issue focused on that .

**Comment by MTK4355** [comment]
Thanks!
