### ISSUE TITLE
PTC SERVER OFFLINE?!?!

### ISSUE THREAD

**Issue by MarvinSCR** [Ar1i/PokemonGo-Bot#338]
![ofof](https://cloud.githubusercontent.com/assets/20703104/17268939/a8929f52-563a-11e6-9e84-e65e1015bc82.PNG)

**Comment by Gioele1334** [comment]
yes, Sucks a lot the PTC servers of niantic, Haves a low uptime

**Comment by Gioele1334** [comment]
Google is better to Login
