### ISSUE TITLE
Please fix the Force Unban. 

### ISSUE THREAD

**Issue by qokemon** [Ar1i/PokemonGo-Bot#3380]
Please fix this Bug / Glitch / Wrong Coding. It worked yesterday. here is what i get.. https://gyazo.com/a098d3ff000927a63eac63b32ac60ed3  It says im getting unbanned on next Pokestop. But it does'nt. Please fix this. -Best Regards | Level 24: qokemonuser

**Comment by Hydro420** [comment]
Please stop using the bot or pay someone to make you one with those "demands."

Force unban stopped working since Niantic changed the API - your probably IP Banned or dont have your settings right in items section.

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18010505/67e31dfa-6b76-11e6-9fd7-eb82937dfbaf.png)

**Comment by Ar1i** [comment]
force unban is not working anymore

**Comment by deadelf0** [comment]
Use Quick Spin that works for me.

**Comment by deadelf0** [comment]
Yay, A new updated!

**Comment by EizoSik** [comment]
Unban working in version 1.0.9.6

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
@EizoSik stop posting urls.

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by EizoSik** [comment]
ar1i I'm sorry,but I'm only trying to help

**Comment by rvonz** [comment]
hell.. my pokeball turn be zero 
![pokeball](https://cloud.githubusercontent.com/assets/20837463/18028093/1e8c8194-6c9f-11e6-8754-f9ac021de6d2.png)

**Comment by mahmttt** [comment]
Thank you for return , love you my friend (ar1i) <3

**Comment by mahmttt** [comment]
bot Running smoothly

**Comment by chaelebski** [comment]
there's now a limit for pokemon you can catch and pokestop you can get item per day. if you already noticed that pokemon always run or the bot always detects softband, stop your bot and wait for the next day to reset the limit.
