### ISSUE TITLE
Problems place me on the map

### ISSUE THREAD

**Issue by lDarkcito** [Ar1i/PokemonGo-Bot#3381]
I try to place me in another town, but the altitude remains at 0 and will not let me change it or start the bot.

<a href="http://es.tinypic.com?ref=2n0vpz8" target="_blank"><img src="http://i64.tinypic.com/2n0vpz8.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by MoMGeek** [comment]
I have same problem

**Comment by Ar1i** [comment]
its fixed when you start the bot so their shouldnt be any problems

**Comment by deadelf0** [comment]
The build before this latest one corrected this issue at start up.
