### ISSUE TITLE
error!!

### ISSUE THREAD

**Issue by Celelio** [Ar1i/PokemonGo-Bot#3384]
![untitled](https://cloud.githubusercontent.com/assets/21267641/18017114/f4c6c1da-6be0-11e6-8499-6d16c1afe97a.png)

hello there.. 1st of all thx for ur great effort dude.. but i keep getting error whenever i start the bot , with 10 sec restarting msg!!
its not my 1st time using the bot, so i know the basics on how to start it..
my acct  isnt banned coz i tried to login normally & its fine..
plz help.. thanks alot

**Comment by qokemon** [comment]
It does not work on PTC.

**Comment by qokemon** [comment]
sorrey

**Comment by deadelf0** [comment]
Yeah, I have one ptc account that the bot can't find any stops but the main app, and quick spin are working with this account which is so strange, may be the proxy though.

**Comment by Celelio** [comment]
im using google acct ... not a PTC, no proxy also..
any idea ?

**Comment by deadelf0** [comment]
This happen to me a few mins ago, turns out I forgot to change the drop down bar to google. lol

**Comment by deadelf0** [comment]
Although, that other account did jump 5 levels last night. my main PTC account went all night and is still going strong at level 29.

**Comment by deadelf0** [comment]
Damn! a 100% Evee got away :(

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
Your password is wrong
