### ISSUE TITLE
Sleeping

### ISSUE THREAD

**Issue by ctimevelo** [Ar1i/PokemonGo-Bot#3385]
Hi,

ist es normal das der bot zwischendurch mal 10 minuten nichts macht?

Nach 8-10 Minuten farmt er dann ganz normal weiter, dies hat natürlich zur folge das die exp/h erheblich sinken. Dient das der Security oder liegt der fehler bei mir?

lg

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
gefixt
