### ISSUE TITLE
no pokestops

### ISSUE THREAD

**Issue by codman96** [Ar1i/PokemonGo-Bot#3387]
i have no pokestop within 10000 error plz help

**Comment by deadelf0** [comment]
Same, but my main account and ip are still going strong.lol

**Comment by codman96** [comment]
is this happening for everyone?

**Comment by angelcuenta** [comment]
no pokestops on last build

**Comment by deadelf0** [comment]
I just keep trying proxies until one works.

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
Probably banned or your IP banned.
