### ISSUE TITLE
1km/h not working?

### ISSUE THREAD

**Issue by tweetthehens** [Ar1i/PokemonGo-Bot#3390]
Trying to place a bot at 1km/h but it won't walk after start up, any idea?

it could be good if it suppose decimical like 1.345km/h

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by TeamRedd** [comment]
EizoSik you have ur log in info on there man I can log and run your account ....

**Comment by Ar1i** [comment]
1km is not working, put in 2 orso
