### ISSUE TITLE
A little suggest for the bot to avoid ban

### ISSUE THREAD

**Issue by pekexeneize** [Ar1i/PokemonGo-Bot#3391]
Can I suggest an option that I saw in other bots ? Make the bot stop at a certain time , and then run again. As a pause for the game to avoid ban.

**Comment by Logxn** [comment]
Why ask? Simply suggest

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by MTK4355** [comment]
I'm working on adding a "Pause Button" that will stop walking while the bot keeps looking for Pokémon but WPF observables are not my forte and it's annoying the magi-crap out of me so I've tabled it a few times. 

If anyone is interested in helping I can check in the unfinished code on my fork.

**Comment by Ar1i** [comment]
@MTK4355 need to say that, you're doing a really really great job here!

**Comment by chaelebski** [comment]
having pause won't really avoid ban. to avoid ban, you shouldn't bot 24/7 because there's a limit now for pokemon to catch / pokestop to take per day. It is better if there will be a feature that can list the number of pokemon we caught and pokestop we took in a day and refresh it on the next day. problem is, I don't know what exact time niantic resets the limit per day and what is the limit per day.

**Comment by k0ut4li4n0s** [comment]
@chaelebski  +1

**Comment by D3m0t3p** [comment]
I'm now unable to compete In a gym, is this normal ?
I get an error

**Comment by MTK4355** [comment]
Having a pause will absolutely help avoid a ban, if for no other reason than by being more human-like.  Also, if you are botting in an area with a zillion pokestops, you could easily hit the pokestop ban threshold before the pokemon catch limit. I  

I think a session counter for pokestops/pokemon would be nice, but I wouldn't count on something like that to prevent an account from being banned, unless you left a ton of room for error. I think a more useful feature would be a bot timer: "Run bot for: X minutes" that way all risk taken (or caution given) is still completely under my control.

**Comment by Logxn** [comment]
This is already implemeted.
Thanks to @MTK4355
