### ISSUE TITLE
The bot can't follow the 'not to catch' orders

### ISSUE THREAD

**Issue by CADUCOAYER** [Ar1i/PokemonGo-Bot#3392]
![qweqew](https://cloud.githubusercontent.com/assets/21274283/18025724/d71347e2-6c32-11e6-89aa-fe65549a148a.png)

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by Ar1i** [comment]
@EizoSik last time until i block you, dont post links. Old versions are not safe.

**Comment by CADUCOAYER** [comment]
Was that Such mean comment for me? Explain pls, ty.

I am not a pro user, i download and use what i think its updated, i can do mistakes.

I saw 'add your screenshot'

I really don't understand

Can anybody HELP me?

**Comment by chaelebski** [comment]
do you know you can get random pokemon from eggs right?
