### ISSUE TITLE
A simple idea

### ISSUE THREAD

**Issue by Takotero** [Ar1i/PokemonGo-Bot#3393]
Now there is a new type of ban, the pokestops ban. 
1000 PokeStops 1 day (ban 1h)
2000 PokeStops 1 day (permanent ban)

You could put a button for desactivate catching pokestops.

**Comment by Zodice** [comment]
The solution : walk at a low speed, around 15 km/h, it makes the bot more "human" and it avoid the problem that you're talking about.

**Comment by Takotero** [comment]
It could work. :)
