### ISSUE TITLE
Problem with connection

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#3394]
Hi,

i try many accounts to connect, but i have same problem after each run the bot.
![error](https://cloud.githubusercontent.com/assets/14926592/18027093/176695e8-6c5a-11e6-9b03-a17fad6d8cc4.JPG)

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)

**Comment by kickz** [comment]
So new version didnt function ?

**Comment by Archimondee** [comment]
dont try to click that link, its bullshit, try to download newest, its working normally for me. 

try to restart your connection or router. or try to login on your phone. 
i dont know its hard banned, ip banned, or soft banned or permanent ban, just try :)

**Comment by Ar1i** [comment]
Dont use a old version. Risk of getting banned is much higher. BadAuthentication means your Login data is wrong.
