### ISSUE TITLE
Shortcut Keys

### ISSUE THREAD

**Issue by s030097** [Ar1i/PokemonGo-Bot#3395]
While I am using the bot for transferring unwanted pokemon, I realised that I would be great if there were shortcut keys for several buttons/functions, say for example, for "Transfer", we can select the pokemon and press "Ctrl+T".
Although I do not know whether it is workable and feasible to add shortcut keys, I sincerely hope there would be similar features in the future. Thank you so much for the bot and appreciate all the hardworks for the developers:)

**Comment by Zodice** [comment]
+1

**Comment by MTK4355** [comment]
Please add to the #issues thread on discord
