### ISSUE TITLE
Change the sorts of pokemons

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3398]
Hi,

it could be cool to change the sorts of pokemons. Currently, you can chose only one type of sorts. For example sort by CP or IV. 
But if you could sort by name and IV for example, we could know which is your highest IV magikarp's, and you will not have to see all of the magikarp to know which is the best.

**Comment by k0ut4li4n0s** [comment]
@Zodice thats simple , you can do it now too. just set the bot to transfer the lowest IV first and set the number of duplicates to the number you want to keep. Additional set the desirable IV you want to keep. Problem solved :)

**Comment by Buckrogers81** [comment]
You can Sort by every column by clicking of the Name of the Column. 

Like if you would like to sort by Name just klick "Name" an voila!

**Comment by Zodice** [comment]
Yes but you can chose only one column that's what i'm talking about
