### ISSUE TITLE
This Git needs a Wiki

### ISSUE THREAD

**Issue by MTK4355** [Ar1i/PokemonGo-Bot#3399]
@Ar1i this Git could really use a Wiki. 

People are never going to stop creating issues to ask questions and make suggestions.. Why not provide a forum for the discussion so you don't have to spend all day closing issues? (including this one :)

**Comment by k0ut4li4n0s** [comment]
Still some1 need to filter the suggestion box and must know if the suggestions are doable :/ . I dont disagree with the wiki and what you can do with the bot 
+1

**Comment by Ar1i** [comment]
Puhhhh Wiki would be usefull af, but I need a person which manages it.. but a good idea tho

**Comment by MTK4355** [comment]
@Ar1i I'm going to start building one on my fork. Feel free to use it verbatim if you want! 
https://github.com/MTK4355/PokemonGo-Bot/wiki

**Comment by Zodice** [comment]
Hi, i would like to help you on the wiki, how can i right something ?

**Comment by Logxn** [comment]
@Ar1i 
@MTK4355 

I will be managing the wiki over the days :)
