### ISSUE TITLE
-

### ISSUE THREAD

**Issue by OzanBarsal** [Ar1i/PokemonGo-Bot#340]
i'm botting at near central park this place is bloated with pokestops but bot seems to farm pokestops like every 20 seconds, i logged into my bot account from game and check if ths bot already farmed all pokestops but nope. 

does it do this to conserve pokeball sources so it can more constantly catch pokemons? if yes, pokestop farming is also another option, in placed with lllots of pokestops it could bring good exp.

**Comment by ObsessedHacker** [comment]
Same
