### ISSUE TITLE
Deviate from preset Range+1Suggestion

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3401]
Tested twice for more than an hour and the bot deviates from preset range. And one question how it chose the next pokestop ? Because i see there are available some near and it chooses one pretty far than others near. And something last as a suggestion i suppose is it possible to make it follow the routes instead of going through buildings/rivers/sea/etc ? I think that should help in ban waves too .

![asdfaraf](https://cloud.githubusercontent.com/assets/21258333/18058829/c5bf204a-6e1e-11e6-8144-71c4547d3f7f.png)

**Comment by k0ut4li4n0s** [comment]
![12345](https://cloud.githubusercontent.com/assets/21258333/18035562/c84a00c8-6d60-11e6-9be3-2101a463c4e6.png)

Dont know if there was any fix on that but still moves away from the range, using the latest version for an hour plus

**Comment by MTK4355** [comment]
@Ar1i I squeezed this one into my latest pull as well. 

I also looked into routing, but using the google directions api would need a paid license, or at least an individual dev license per instance. I think you only get 2500 free API calls per day or something. There may be free providers out there, but wouldn't be as easy to implement.
