### ISSUE TITLE
Bot wont spin any pokestops or get any items.. it just catches pokemon

### ISSUE THREAD

**Issue by Aid-en** [Ar1i/PokemonGo-Bot#3402]
it has just stopped recently, and then eventually I run out of poke balls. No other issues have occurred. I don't have poke balls set to 0 either. not sure what to do. I do not use any proxies either. In the screenshot, you can see it visits pokestops but it doesnt get any xp or items from them, and my great/utraballs have run out. 
![capture2](https://cloud.githubusercontent.com/assets/20967644/18031063/a5586b5c-6d12-11e6-9f62-7869eaf004a3.PNG)
![capture3](https://cloud.githubusercontent.com/assets/20967644/18031064/b527a82c-6d12-11e6-9f85-11aedaa1405d.PNG)

![capture](https://cloud.githubusercontent.com/assets/20967644/18031061/7cbcb64e-6d12-11e6-868a-b64169e77a79.PNG)

**Comment by chaelebski** [comment]
stop botting for now. wait for tomorrow to reset the daily limit for pokestops taken. better bot another account for now.

**Comment by blackwing182** [comment]
so this now can bypas  niantic  loggin acces from other apps and wont get banned?

**Comment by silentassassonwp** [comment]
same for me man

**Comment by TxShack** [comment]
As for me it was the pokemons that were escaping all the time but I assume it is the speed making it think im using a 3rd party program. Pokestops stopped working for like 10 seconds, then they went back to normal. I haven't go a time to thank @Ar1i  for its great work and amazing job. Thanks for the updates and hard work. :+1:

**Comment by Aid-en** [comment]
@TxShack So its the speed that needs to be decreased?

**Comment by TxShack** [comment]
@Aid-en I do think it has to be decreased cause even when on my car when going fast and playing it fails to capture pokemons all the time.

**Comment by Buckrogers81** [comment]
i thonk its some kind of Ban. rest yor IP and wait 2 hours and you can cpntinue

**Comment by Aid-en** [comment]
![capture5](https://cloud.githubusercontent.com/assets/20967644/18032685/6f4a5f3c-6d50-11e6-853d-f9853d602a7f.PNG)
Look. In this capture, i have no poke balls left, and then at the top, it visited poke stops, but didnt get any xp or items. Because of this, i run out of poke balls and then i have nothing to catch with. I've put my speed down??? What do i do?

**Comment by Aid-en** [comment]
@TxShack @Buckrogers81 how do i reset my ip? @silentassassonwp

**Comment by TxShack** [comment]
@Aid-en For me it looks like ip ban. Just use a different source to connect to the internet, like tether or another wifi connection.

**Comment by Buckrogers81** [comment]
go to your router Config and reset the Internet Connection. and then ceck f the external IP changed.

**Comment by Buckrogers81** [comment]
or just stop botting for a while dnt be to greedy

**Comment by Aid-en** [comment]
@Buckrogers81 i havent been botting all day because of this lmao

**Comment by Aid-en** [comment]
@Ar1i still having the same problem. and it doesnt seem to be just me. is it a text issue or am i ip banned?

**Comment by MTK4355** [comment]
What exactly did you "put your speed down" to? I still see the "Slowing down to ~10km/hr" message in your client screenshot.  Try something 5-9 km/hr and select all pokemon in the "Pokeon not to catch" config.  

There might be a bug here, but I have personally only seen this happen at high speeds. 

At any rate, 100% of the accounts I  have used at speeds over 15km/hr have been banned, even when limiting the total pokestops and pokemon per day..

**Comment by Aid-en** [comment]
@MTK4355 down to 5, all set to do not catch: still nothing. fixes after i dont open it for an hour, but after 5 mins of starting it same bug happens.

**Comment by MTK4355** [comment]
Hmm.. Have to see if I can get your configuration and location information to attempt a repro. Can't seem to trigger it myself.
