### ISSUE TITLE
to Perfect

### ISSUE THREAD

**Issue by spamverdacht98** [Ar1i/PokemonGo-Bot#3404]
Hello , you can change the bot so that it does not always produce a perfect throw .
A player sustaining usually 100 -150 Ep . Your Bot throws course always perfect ( 210 Ep )
Thanks

**Comment by Archimondee** [comment]
i think he will make a random throw later

**Comment by Zodice** [comment]
But it help for the gain of EP

**Comment by Aid-en** [comment]
@Zodice but niantic home in on these repeated perfect throws. its like a beacon for hackers to be spotted

**Comment by MTK4355** [comment]
@Ar1i This feature is included in my latest pull request

**Comment by Logxn** [comment]
Fixed
