### ISSUE TITLE
AUTO EVOLVE WONT WORK

### ISSUE THREAD

**Issue by angelcuenta** [Ar1i/PokemonGo-Bot#3405]
DONT WORK AT LAST BUILD

**Comment by Logxn** [comment]
Actually it does.
I had so many unevolved shit I got a level up reward for it

**Comment by fenlyn** [comment]
in here to..i need to click pokemon on pokelist 1st to evolve

**Comment by MTK4355** [comment]
I'm assuming you have checked both the GUI setting on bot startup page and the individual pokemon in the "Pokémon to Evolve" section? Works fine for me.
