### ISSUE TITLE
No pokeballs - error

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#3407]
Why i couldnt catch the pokemons ? 

I have pokeballs.

![no_poke](https://cloud.githubusercontent.com/assets/14926592/18033486/c4ffaa92-6d26-11e6-9dfe-6100210baa32.png)

**Comment by Buckrogers81** [comment]
because u ran out of pokeballs. thats what the yellow line says. u should play a wile without catching taubsis. hornlius , then your Pokeballs should fill up

**Comment by kickz** [comment]
No, not right, because i collect only pokeballs. I check log of items and i have enought.

**Comment by Buckrogers81** [comment]
try to get a new IP and whait  hours

**Comment by kickz** [comment]
Same problem

**Comment by MrJur1** [comment]
restart router and wait a few hours.. after that it will work again!
