### ISSUE TITLE
Option to walk to stops without using them

### ISSUE THREAD

**Issue by HighVector** [Ar1i/PokemonGo-Bot#3408]
Hey,
Since high levelled ppl also get targeted by the bans maybe making the bot walk to stops but dont use them could reduce the amount of experience the bot earns. For me for example, I just want the bot to catch some good pokemon but the amount of exp he earns through the stops is still too much. Or maybe just use the stops once items (pokeballs) are reduced to a critical amount so that he starts to gather some and then stops it again.

**Comment by Aid-en** [comment]
lol im actually having this issue. after not getting the pokestops, I run outta pokeballs and then i cant catch any pokemon... I need a fix :(((

**Comment by HighVector** [comment]
I also had that but after stopping the bot for a few hours it started working normally again :D

**Comment by Buckrogers81** [comment]
Just exclude the most common Pokemon in the "Not to Catch-List" . You will save-up some Balls if you do that

**Comment by Siul89** [comment]
I would ask an option not to farm from the pokestops, since for what I usually use the bot is just to hatching eggs, ie just walk without capture pokemon (as this) or that I picked up objects
I also want to ask for an option to put on and remove favorite pokemon

(sorry for my english, i'm spanish and don't know some translations of terms)

**Comment by HighVector** [comment]
Yeah exactly. That option would be very useful

**Comment by MTK4355** [comment]
@Ar1i this feature is included in my latest pull

**Comment by Siul89** [comment]
and where is the feature? i can't find it

**Comment by HighVector** [comment]
The build doesnt seem to be out yet but he will prob put one out soon. 
Great work and thx btw for the feature :D

**Comment by Siul89** [comment]
thank you, it works perfect

**Comment by Logxn** [comment]
added
