### ISSUE TITLE
No "idea" part

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3409]
We can see that there is a lot of ideas that are posted in the "issues".

So can we add  an "idea" part ? It could be better

We could make something like everybody vote for the best/more needed idea to help the developer to chose.

**Comment by Logxn** [comment]
;D

The Idea ( ;) ) is good but we cant simply add tabs.
These Tabs are GitHub standarts and cant be modified.

**Comment by Zodice** [comment]
2 days ago there wasn't the wiki tab, so i think that it's possible !

**Comment by MTK4355** [comment]
Go create a repository and see for yourself! :) Wiki is one of the pre defined tabs that Git offers, Ideas is not. I thought the wiki could be community managed but it appears I was wrong about that. :,(
