### ISSUE TITLE
Fehlermeldung bitte um hillfe

### ISSUE THREAD

**Issue by ShaaiLo** [Ar1i/PokemonGo-Bot#3410]
![unbenannt](https://cloud.githubusercontent.com/assets/20891139/18034849/98ff90b2-6d47-11e6-96b4-77316a6791f3.png)

Wie kan ich das beheben ?!

**Comment by Buckrogers81** [comment]
Mehr Details bitte:

Verwendest Du einen Proxy?
Wurde der Account gesperrt? ( also klappt die ANmeldung am Handy?

**Comment by Logxn** [comment]
LoginFailedException

irgendwas stimmt nicht.
Entweder Username/PW falsch, Account nicht verifiziert oder die Server waren gerade down

**Comment by ShaaiLo** [comment]
Ich verwende kein Proxy.
Account ist Neu & ja anmeldung klappt

**Comment by jay-2-rome** [comment]
So einen ähnlichen Screen kriege ich wenn ich manuell in der DeviceInfo.txt rumspiele.

Entpacke mal den Bot und änder nur die Configs.txt und sonst nix anderes. Dann müsste wieder alles funktionnnieren...

**Comment by Ar1i** [comment]
Lad den Bot mal komplett neu
