### ISSUE TITLE
can i get banned?

### ISSUE THREAD

**Issue by Sho0t3r** [Ar1i/PokemonGo-Bot#3411]
is the bot updated and like a human?

**Comment by Zodice** [comment]
No, it's why there is a message when you open the bot.

**Comment by TxShack** [comment]
When hacking it is impossible to get banned m8.

**Comment by Logxn** [comment]
that is not true @TxShack

**Comment by TxShack** [comment]
@Logxn ... m8... you understand sarcasm?!

**Comment by PrOCheaTer** [comment]
if you use legit settings you wont be banned, i use the Bot since first Release...

3 x 40 Acc... No Ban!

**Comment by shadowfak3r** [comment]
@PrOCheaTer can you tell us how your setting are setup please and thanks

**Comment by stickmick12** [comment]
@PrOCheaTer yes tell us you settings please

**Comment by Zodice** [comment]
Low speed (~15 km/h), be carefule with your position, when using bot delete your pokemon go's app from your phone, and don't use the bot for 10h straights, that's totally not human !

**Comment by shadowfak3r** [comment]
thanks #Zodice

**Comment by PrOCheaTer** [comment]
as @Zodice says.. low speed, dont push from germany to usa usa in 1 minute.. do breaks... 

like if you will farm from usa->central park and you location is Berlin.. turn off the Bot for 2 Days then get a USA->IP and start Bot in USA... if you come back to Berlin 2 Days Break.. understood :D ?

**Comment by Zodice** [comment]
I think you don't have to take a different IP, just take the right time : i mean don't do New York - Paris in 1h. And if you take the right time everytime, you can't make new york - Paris every 2 days. Think, be logic, be clever.
