### ISSUE TITLE
Pokespot not farmmed !!

### ISSUE THREAD

**Issue by Andy217ACE** [Ar1i/PokemonGo-Bot#3412]
Hello,

     I have the following problem the pokespots are not farmmed: 
![untitled](https://cloud.githubusercontent.com/assets/21294414/18035212/b5a764f8-6d59-11e6-952b-4a8df572b420.png).

Please advise

**Comment by Zodice** [comment]
You're probably soft banned

**Comment by Andy217ACE** [comment]
So if i change my ip i get rid of this?

**Comment by Sikilmik** [comment]
I have the same problem, if you know of to get rid of this, tell me :/

**Comment by Andy217ACE** [comment]
Yes changing the ip solved the problem

**Comment by Andy217ACE** [comment]
It seems tat changing the IP it's only a temporary solution it worked for 20 minutes and now it is not working again...

**Comment by Logxn** [comment]
Because you are going to fast. Set it something lower

**Comment by Andy217ACE** [comment]
How low?

**Comment by Archimondee** [comment]
working normally in 30km\h

**Comment by Andy217ACE** [comment]
So i've changed the speed to 10km and i've changed the ip and everything seems to be ok. Thanks guys I will close the issue. Gr8 job @Ar1i
