### ISSUE TITLE
Doesn't capture pokemons but...

### ISSUE THREAD

**Issue by TxShack** [Ar1i/PokemonGo-Bot#3415]
![nocappok](https://cloud.githubusercontent.com/assets/21256298/18035803/eb0f8d8e-6d2a-11e6-8b40-cfb9dc4bac7a.png)
As you can see pokemons escape but I do get the xp farmed out of the pokestops. New updated and new ip address.

**Comment by Logxn** [comment]
IP banned.
Change IP or use proxy.

**Comment by TxShack** [comment]
"New updated and new ip address."
                                                                                  -TxShack (In the post above)

Please read before posting.

**Comment by abhi290** [comment]
Auto transfer of pokemons not working.

**Comment by Theseppinator** [comment]
@abhi290 Please make a new post.

**Comment by fetmamm** [comment]
Softbanned, wait about 7 hours and try again :)

**Comment by Andy217ACE** [comment]
Change the ip and the speed to 10km and everything will be ok @TxShack

**Comment by TxShack** [comment]
@fetmamm thanks and @Andy217ACE I'll post updates.

**Comment by Andy217ACE** [comment]
Is it working @TxShack ?

**Comment by TxShack** [comment]
It is not working but if it is a softban it will go out by itself so I'll be able to notice it if I leave the bot running. At least it happened like that before. New IP doesn't WORK.

**Comment by abhi290** [comment]
i m new to this.

can u brief me with the IP thing and also what does  IV mean in the bot.


Get Outlook for Android






On Mon, Aug 29, 2016 at 12:50 AM +0530, "TxShack" <notifications@github.com> wrote:












It is not working but if it is a softban it will go out by itself so I'll be able to notice it if I leave the bot running. At least it happened like that before. New IP doesn't WORK.

**Comment by Andy217ACE** [comment]
what level do you have?

**Comment by TxShack** [comment]
25

**Comment by abhi290** [comment]
m new to this.
can u brief me with the IP thing and also the IV on the bot.

**Comment by TxShack** [comment]
New ip even with VPN. Doesn't work.

**Comment by Andy217ACE** [comment]
For me it's working... but i only get xp from pokestops and from time to time i get the rest

**Comment by TxShack** [comment]
It was a softban. Same ip and already capturing and pokestops working. THE END.
