### ISSUE TITLE
What is new? i thin the bot is offline?

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#3416]
As ist neu dachte der bot ist off weil du das entfernt hast hier?

**Comment by Logxn** [comment]
Nein der Bot ist wieder da.
Ist aber kein 100%iger Ban sicherer Bot :)

**Comment by stickmick12** [comment]
Hea und wieso ist der jetzt wieder da?

**Comment by abhi290** [comment]
is it possible we can actually have a pokemon go screen also running alongside showing all the movements, pokemon catches and all?

**Comment by stickmick12** [comment]
@Logxn gibt es den einen der sicher ist?

**Comment by PrOCheaTer** [comment]
@stickmick12  auch dieser Bot ist legit, mit ordentlichen Einstellungen!
