### ISSUE TITLE
Catch miss rate

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3419]
I have found that the miss rate is set way too low, not a lot of people are that bad at throwing pokeballs, I'm willing to give up 2 balls for a pidgey, but not 5.

![kajoeuc](https://cloud.githubusercontent.com/assets/21261582/18035971/2b9e4fbc-6d61-11e6-8657-8ed562686848.png)

**Comment by TxShack** [comment]
I support this. Pokeballs go out of stuck by so many misses.

**Comment by MTK4355** [comment]
I just added a bunch of logic in my fork to improve the overall odds and limit the max misses.. Hopefully @Ar1i will merge my pull request for you guys, otherwise you are always welcome to build mine yourself.

**Comment by Theseppinator** [comment]
> I just added a bunch of logic in my fork to improve the overall odds and limit the max misses.. Hopefully @Ar1i will merge my pull request for you guys, otherwise you are always welcome to build mine yourself. 

That'd be awesome :D

**Comment by Ar1i** [comment]
done
