### ISSUE TITLE
cant find any pokestop at 5000 m

### ISSUE THREAD

**Issue by Mortifero** [Ar1i/PokemonGo-Bot#3420]

**Comment by Mortifero** [comment]
he dont see pokestops and he says probaly se server is down

**Comment by Mortifero** [comment]
and also not is 20000000000 meter so maybe the server is down?

**Comment by Andy217ACE** [comment]
server was down ... maybe for the moment

**Comment by Theseppinator** [comment]
Do you have 2 bots running by any chance (on the same IP)

**Comment by suljo94** [comment]
Softban wait 4h

**Comment by MTK4355** [comment]
Not a softban. IP Ban. 

I think the 40 spin method no longer works since the last update.

Come to think of it..... I haven't had an account get softbanned since the last update either....

**Comment by kimjongun69** [comment]
@MTK4355 i havent gotten softbanned before on this one account im using before either. but i had same issue and its soft banned for me. not IP. i tried different account and it worked

**Comment by kimjongun69** [comment]
what im worried about is, if i get soft banned once, is the account more than likely going to be perma banned? if so, i rather started new account and bot again LOL.
