### ISSUE TITLE
Error for Ar1i to see

### ISSUE THREAD

**Issue by Andy217ACE** [Ar1i/PokemonGo-Bot#3421]
This is for Ar1i. This error appers some time.
![untitled](https://cloud.githubusercontent.com/assets/21294414/18036097/aae0b864-6d6b-11e6-8bd2-4d4999679508.png)

**Comment by Logxn** [comment]
the bot wanted 5 responses but got 0.
=> Servers were down.

I got them too

**Comment by Mortifero** [comment]
when do is comes back again?
