### ISSUE TITLE
After IP change, bot doesn't work.

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3422]
Noticed that when you change IP, the bot won't work.
(PS: It's Dutch ;D)

![glitch](https://cloud.githubusercontent.com/assets/21261582/18036363/db57745e-6d68-11e6-9adb-c86d8d768aba.png)

**Comment by PrOCheaTer** [comment]
IP or Account banned...

**Comment by Kidnub** [comment]
account is banned for sure ... if you need aproof that this is a ban just test a new account and you will see that account of you is death ;(

**Comment by Theseppinator** [comment]
**If my account would be banned, I wouldn't be able to log in**.. I don't think that's the case. **IP banned COULD be**, but I **changed my IP** **and** then the **bot** just **doesn't work** anymore xP

**Comment by MTK4355** [comment]
Not true. Login is still successful when your account is banned. Player data is even returned. Failure is evident only when trying to retrieve your pokemon list and items. Try logging in from an actual device, and you will likely see "Failed to retrieve game data" 

Sorry bud. looks like the hammer got you.

**Comment by Theseppinator** [comment]
> Not true. Login is still successful when your account is banned. Player data is even returned. Failure is evident only when trying to retrieve your pokemon list and items. Try logging in from an actual device, and you will likely see "Failed to retrieve game data" Sorry bud. looks like the hammer got you.


As I said, I can log in with my samsung galaxy s6 edge and a different s6, no problem, I can even fight gyms ;P
