### ISSUE TITLE
Der Bot ist geil, aber es fehlt noch 1 was ;)

### ISSUE THREAD

**Issue by PrOCheaTer** [Ar1i/PokemonGo-Bot#3424]
Danke für die super Arbeit [https://github.com/Ar1i](url).
Aber 1 was vermisse sicherlich nicht nur ich. Was noch richtig geil wäre, wenn es möglich ist dass man Coins addn kann.

Eine Antwort wäre toll ;')

Thx

**Comment by Rhaego110** [comment]
alter da bekommt man ja krebs wenn man das liest

**Comment by PrOCheaTer** [comment]
@Rhaego110 Verpiss dich doch wenn es dir nicht passt.

**Comment by Ar1i** [comment]
Nein Arenen werden nicht geaddet
