### ISSUE TITLE
brauche Proxy erklärung

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#3425]
Die proxy seite die bei dem Bot dabei ist die benutzt doch jeder die Proxys dort deswegen werde die accs sowieso gebannt? und muss man bei jedem acc einen anderen Proxy benutzten?

**Comment by Kidnub** [comment]
Ja du brauchst bei jedem bot der läuft auch eine neue ip und bitte drauf achten das es keine public proxys sind .... und alle https haben XD ... und um dem ban zu endgehen eine ip ein bot ... steht aber auch im bot selber in der gui XD

**Comment by stickmick12** [comment]
Wo finde ich den keine Public proxys?

**Comment by hoffhouse** [comment]
suche bei google nach private proxy - da gibt es viele Anbieter.

**Comment by stickmick12** [comment]
Oke uns frage nochproxyssind einfach Ip adressen ja?

**Comment by stickmick12** [comment]
1K

**Comment by Kidnub** [comment]
proxys gehen zz nicht --- #3428

**Comment by stickmick12** [comment]
Ah oke

**Comment by hoffhouse** [comment]
Das stimmt nicht! Proxys funktionieren.
Ich nutze GERADE eben für 10 Accounts 10 IPs!!!

Bei newipnow.com gebucht und mitgeteilt, dass man die private proxys für Pokemon benötigt.

Viel Erfolg!

**Comment by Ar1i** [comment]
Proxys gehen. Nur keine Müll Proxys.
