### ISSUE TITLE
Max Capture of a Pokemon

### ISSUE THREAD

**Issue by TxShack** [Ar1i/PokemonGo-Bot#3427]
I set my bot to cap. max. of 2 per pokemon. It is not working for some of them. Zubat, Weedle, Magnemite and others. Would like to know if that could be fixed. Thanks.

**Comment by Kidnub** [comment]
pls check your check boxes on the setup of the bot if the checkbox is active keep pokemon for evolving then uncheck it .... that should easy fix your problem .. 
http://www2.pic-upload.de/img/31575019/Unbenannt1.jpg check the screenshot ... if you setup it like this you should not have more as 2 pokemon of each type but pls check even the pokemon hold option in the middel tab that their is only that checkbox active which you wane hold ... if their is a klick on hold zubat then you even can have more as one zubat ..     so check the middel tab also if their is mostly all you dont wane hold unchecked XD thx bye and i hope i could help you a bit to fix it XD

**Comment by TxShack** [comment]
Thanks @Kidnub for fast reply. No I have not checked any box of the pokemons. Did this so I could get faster exp and candy for every pokemon. Once again it doesn't happens with all of them, only few. @Ar1i if it's not too much problem to ask to check this I'll be grateful.

**Comment by TxShack** [comment]
@Kidnub Thanks for the advice checked again and when clicked the boxes of the pokemons had trouble with the check mark appeared and disappeared. I had some glitch I don't know. Thanks again!
