### ISSUE TITLE
Bot funktioniert bei mir nicht / error: mscorlib

### ISSUE THREAD

**Issue by radoyx** [Ar1i/PokemonGo-Bot#3428]
Wollte den Bot nach längerer Zeit mal wieder nutzen. Hab eigentlich alles gemacht so wie damals, bekomme aber immer nur diese Fehlermeldung. 
Ja, ich nutze Proxys. Die Proxy zu wechseln macht keinen unterschied. 
Der Account ist auch nicht gebannt. Übers Handy komme ich jedenfalls rein und kann auch alles machen. 

Bot neuinstalliert habe ich ebenfalls schon. 
Kann mir jemand sagen, wie ich das Problem beheben kann? :/ 
Hatte auf anhieb auch kein Thread gefunden, wo jemand das selbe Problem hat. 

![unbenannt](https://cloud.githubusercontent.com/assets/20887764/18044999/d7642e38-6dd0-11e6-81cb-94cdecf7a816.png)

**Comment by Ar1i** [comment]
Proxy geht nicht
