### ISSUE TITLE
I need an answer sorry for the issue

### ISSUE THREAD

**Issue by CharlieDeIta** [Ar1i/PokemonGo-Bot#3430]
Hi, I'm sorry to post a question here but I need an answer and I don't know where to post it.

So here is my question : What is a proxy and how it works ? 

Thx for answers !

**Comment by D3m0t3p** [comment]
> In computer networks, a proxy server is a server (a computer system or an application) that acts as an intermediary for requests from clients seeking resources from other servers.[1] A client connects to the proxy server, requesting some service, such as a file, connection, web page, or other resource available from a different server and the proxy server evaluates the request as a way to simplify and control its complexity. Proxies were invented to add structure and encapsulation to distributed systems.[2] Today, most proxies are web proxies, facilitating access to content on the World Wide Web and providing anonymity. 


[wiki](https://en.wikipedia.org/wiki/Proxy_server)

**Comment by Buckrogers81** [comment]
Not to forgett the reverse-Proxy-functionality :-) 

But you would have been faster if you would have typed that question in to Google.
