### ISSUE TITLE
Bot läuft raus aus dem walkradius

### ISSUE THREAD

**Issue by pwnjke** [Ar1i/PokemonGo-Bot#3432]
also das Problem steht schon im Titel
![2](https://cloud.githubusercontent.com/assets/20947780/18050532/7a4d2834-6def-11e6-8492-ab74414d3748.png)
# **ABER**
Vor 20 minuten habe ich so eine Meldung bekommen, nachdem der Bot wahrscheinlich den neuen Radius definiert hat
![1](https://cloud.githubusercontent.com/assets/20947780/18050551/98818534-6def-11e6-9ce8-15728d06b0d6.png)
hat gestern die ganze Nacht gelaufen und als ich aufgewacht bin, habe ich den Bot ca. 4km weg vom ursprunglichen Startpunkt gefunden, obwohl in den Settings habe ich 1000m Radius. habe auch versucht mit dem "start from default location" zu spielen, funktioniert nicht. Hilfe!
Und sorry für blodes Deutsch :D

**Comment by pwnjke** [comment]
Jetzt zufällig noch einen Crash gesehen, nachdem er links die neue Pokestops auf der Karte gezeigt hat
![3](https://cloud.githubusercontent.com/assets/20947780/18050801/08147900-6df1-11e6-8521-72a5c0db41f5.png)

**Comment by Rhaego110** [comment]
dumme frage wie lässt du dir den weg anzeigen wie er gelaufen ist?

**Comment by pwnjke** [comment]
lass einfach die Karte offen. ab dem Zeitpunkt wo du die geöffnet hast, wird der ganze Weg angezeigt

**Comment by peni01** [comment]
Wieso schreibt ihr mir ich kann dir nicht helfen

Am 29.08.2016 13:56 schrieb "pwnjke" <notifications@github.com>:
