### ISSUE TITLE
Bot freezes at first pokestop

### ISSUE THREAD

**Issue by Takotero** [Ar1i/PokemonGo-Bot#3434]
Bot freezes at first pokestop. @Ar1i 

[https://i.gyazo.com/27dc328a66c4c8baca6605359b4bd484.png]

**Comment by MTK4355** [comment]
There's a pretty wide random delay in there now, are you sure it's frozen?

**Comment by Monadologie** [comment]
Got the same issue :/

**Comment by Ar1i** [comment]
Pushing out a fix, and @MTK4355 probably the delay is to high edited something

**Comment by Takotero** [comment]
For me was frozen for 2 minutes.

**Comment by MTK4355** [comment]
The long delay was actually intentional, but I can see how it might appear to be broken. @Ar1i I'll leave it out of my pull requests going forward.

**Comment by Monadologie** [comment]
@Ar1i Issue is vanished!
