### ISSUE TITLE
no ultra ballas no  greatballs  (FYI no  greatballs)

### ISSUE THREAD

**Issue by Xysas** [Ar1i/PokemonGo-Bot#3435]
![pokeballs](https://cloud.githubusercontent.com/assets/20915192/18051451/5272c518-6dfd-11e6-9875-ba55cc569786.png)

**Comment by Takotero** [comment]
How you have configuered recycle options?

**Comment by Hydro420** [comment]
Get the latest version of the bot and ull see the pokeball count for each one - bot is set to use certain pokeballs on certain pokemon.

**Comment by Theseppinator** [comment]
Maybe the bot threw all your balls away?

**Comment by ajangel** [comment]
Can you  send  me  the link pls

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 29, 2016 at 5:37 AM, Hydro420<notifications@github.com> wrote:   
Get the latest version of the bot and ull see the pokeball count for each one - bot is set to use certain pokeballs on certain pokemon.
