### ISSUE TITLE
Not farming at all!

### ISSUE THREAD

**Issue by Araben** [Ar1i/PokemonGo-Bot#3436]
hey
i just downloaded the lastest version, and i got this problem, the bot goes to the pokestops but it dosesn't farm them at all

screenshot: http://store1.up-00.com/2016-08/1472473602581.png

-------------------------
#update 
-------------------------

@Hydro420 @Takotero yeah its really weird :/ im trying to change my ip now and start the bot again.

-------------------------
#update2 
-------------------------
sorry it took i bit time because after changing my ip the bot said there is new version so i had to download it

but no, i still have the same problem :(

-------------------------
#update3  
-------------------------

thanks for all the answers guys, gonna try to make a new account now :(

please keep it up if you know any fix for this 

-------------------------
#update4
-------------------------

## ITS WORKING!

just tried to start the bot again with 120 km/h speed, and yes! its working again! 

btw i disabled the proxy and used my normal swedish ip again, the place that im farming at is santa monica, im switching to new york tomorow tho because i need farm more than pokemons right now :dancer:

**Comment by Hydro420** [comment]
Thats odd... Looks like a weird type of soft-ban lol. Can catch pokemon but not get exp from stops lol

**Comment by Takotero** [comment]
Works for me, probably you have ip ban.

**Comment by thibautdavid27** [comment]
I have the same problem someone can help me

**Comment by Takotero** [comment]
Try whith another account.

**Comment by GiaPune** [comment]
I have the same problem...I need balls !!!!!!!!!!!!!!!

**Comment by Hydro420** [comment]
Mine is working fine for an HR now running at 120kmh - I switch between 15-120 every hr or so. Been working smooth so far.

**Comment by PrOCheaTer** [comment]
oh oh, your acc will be banned you forgot to hide your username...

and btw 120 km/h ? wtf ? enjoy your ban :D 

1-2-3-4-5-6-7-8-9-10-11 KM is fine!

**Comment by k0ut4li4n0s** [comment]
rofl i have to hide my name on ss :O ?

**Comment by GiaPune** [comment]
@Hydro420 
120 km/h....too fast lol...
It's working on <12km/h or >20km/h

**Comment by MTK4355** [comment]
I finally reproduced the issue and the response from the API is "Inventory Full" even though my inventory is clearly not full..... Standby for more information as I dig into this.

**Comment by daggen92** [comment]
Same thing here, says ive got 374 items and it caps at 350, while the fact is i've got under 100 items.

**Comment by MTK4355** [comment]
In my case, the item count in the logger is right, around 230 items. Niantic's servers are telling me that my inventory is full when the bot spins a pokestop.

**Comment by daggen92** [comment]
i logged in on an emulator, same area as the bot where running. dont seem to be able to farm pokestops there either, and i cannot enter gyms. block from niantic maybe?

**Comment by MTK4355** [comment]
That's what I'm leaning toward. I think we should view this as a new type of soft ban from Niantic until we can find out more about it....
