### ISSUE TITLE
Big space

### ISSUE THREAD

**Issue by Takotero** [Ar1i/PokemonGo-Bot#3437]
There is a big space on the starting log. @Ar1i 
![2016-08-29 14_41_09-takogamerhd lvl24- 82 195_150 000_54 8 _ stardust_ 149044_ xp_h_ 15 415_ pokemo](https://cloud.githubusercontent.com/assets/21259916/18051750/b31dcd92-6df6-11e6-9e61-9d020f364ce6.png)

**Comment by MTK4355** [comment]
Seems to be random...
I didn't see it at startup  
![image](https://cloud.githubusercontent.com/assets/11677019/18051946/464a8e0a-6dbd-11e6-96ba-90aaa2c3e3ab.png)
Then it happened in the middle of the session
![image](https://cloud.githubusercontent.com/assets/11677019/18052009/904d867e-6dbd-11e6-9aaa-835953e364ff.png)
