### ISSUE TITLE
[Request] Teleport und Move TO, EGGS, EIER

### ISSUE THREAD

**Issue by Caddyrn** [Ar1i/PokemonGo-Bot#344]
@Radat kannst du ne Funktion einbauen das wir einstellen können das er manchmal Portet, hab mir das so vorgestellt.

Kontrollkästchen ob alle 6-7 Std ein Port gemacht werden soll.
Wird dieses aktiviert geht ein dropdownmenü oder mini GUI auf wo ich die Standorte selbst eingebe, oder am besten nur ein Harken setze, die GPS Daten könntest du ja z.B von deinem Thread Post entnehmen.
Dann makiere ich mir z.B New York, Miami Beach und Berlin. Dann portet er alle 6-7 std automatisch zum nächsten Ort, entbannt sich und macht dann wieder weiter.

Oder eine Moveto funktion, per Telegram wenn das mit dem Teleporten nicht gehen sollte. Das ich ihm in Telegram sage wo er hinläuft und dann läuft er dahin, wobei das mit dem Teleport natürlich total geil wäre

Eier ausbrüten wäre auch noch so ne Sache ^^

Liebe Grüße

**Comment by xxhamsterxx** [comment]
Kannst  du mir sagen ob ich defaultlocation aktivieren soll wenn ich  von New York nach München wechesel.
Dasoll es nähmlich ein Pokemon geben aber es wird nicht geagngenvieleicht liegt es daran?

**Comment by Caddyrn** [comment]
Nein du musst die LastCords datei löschen im APICONSOLE->DEBUG-BIN-CFG Ordner ^^ Default Location nutzt er um zu merken wo er sich einloggt, damit er sich auch da wieder einloggt, läuft aber auch über die Last Cords. Also die Last Cords löschen, dann Bot starten GPS nochmal setzen, default Location ja und los

**Comment by Kelendris** [comment]
Ich finde die LastCords datei nicht ? :)

**Comment by xxhamsterxx** [comment]
Hast du eine Idee wo ich Pikachus finde?

**Comment by Euskater2** [comment]
leute, eine frage ? ich komme zwar rein aber sammelt nichts mehr ein .. wahrscheinlich ist mein ordner nicht up to date oder softban oder sonst was... hab mich wieder entbannt indem ich ein stop 40 mal gespinnt habe und dann gings wieder und dann wieder nach NY aber der sagt immer er findet keine stops oder entweder wurden schon alle gefarmt oder so.. und wenn er welche pokemons findet dann verschwinden die steht da. 

hilfe :D

**Comment by Caddyrn** [comment]
@euskater2 dann ist NEw York aktuell down, haben dort immer wieder Server Probleme 
@Kelendris du musst nach PokemonGo.RocketAPI.Console/bin/debug/configs dort ist die datei drin, einfach löschen, PS: Windows hat auch ne suchfunktion ^^

**Comment by Euskater2** [comment]
danke :)  aber hab auch hier in DE ausprobiert und selbes Problem :D naja egal... letze Frage ... wie update ich mein Ordner richtig ?  auf dieser seite steht ja zb. bei einer datei vor 10 stunden geändert und wenn ich alle datein runterlade also hier und in meinem alten rodner reinpacke und ersetze ändert sich nichts ... richtig kommisch.

**Comment by Euskater2** [comment]
achja ich mach das über M. VISUAL

**Comment by Caddyrn** [comment]
@euskater2 richtig musst neu Compilen, ich mach das direkt mit github. Ich hab Git auf Windows installiert geh nur in den Ordner rein und tipp in die console git pull, dann updatet er das automatisch. Danach noch compilen und alles ist gut. Will noch schauen das ich ein Compile SCript schreibe, hab 8 Bots laufen (nein verkaufe nicht, nur ne Familie die sich net mit PCs auskennt :D). Mit ner Bat updatet er alle startet alle und schließt alle, compile bat wäre noch fett
aber man kann net alles han :)

**Comment by Euskater2** [comment]
okei suuper danke :)

**Comment by Ar1i** [comment]
Not possible atm, need to update to the newest api first for egg. Teleport kannst auch selbst machen einfach speed hoch.
