### ISSUE TITLE
Elektek IV100% ist weg!

### ISSUE THREAD

**Issue by liebbert** [Ar1i/PokemonGo-Bot#3440]
Hi!
Ich habe Autotransfer an, ab 2 doppelten IV nicht über 89% zusätzlich noch einige Pokémons ausgewählt, die nicht transferiert werden sollen, darunter auch Elektek. Ich hatte einen mit IV 100% und hab ihn sogar mit ca. 150.000 Sternenstaub aufgepowert. Nun ist er weg und bin mir ziemlich sicher ihn nicht manuell transferiert zu haben!? Wäre nett wenn das evtl. mal untersucht wird, leider etwas ärgerlich, aber halt das Risiko wenn man es nicht manuell macht.
Zusätzlich noch als Vorschlag was noch in den Einstellungen interessant wäre:
-die Geschwindigkeit vielleicht auf Kommastellen erweitern oder einen Bereich wählbar zu machen z.B. random speed 4km/h - 7km/h so dass der Bot variiert und nicht fest mit einer Geschwindigkeit läuft

Ansonsten von mir mal ein Danke für die Mühe und Zeit die in die Entwicklung und Programmierung investiert wird!

**Comment by stickmick12** [comment]
gute idee

**Comment by PrOCheaTer** [comment]
Random Geschwindigkeit habe ich bei dem Projekt von Ar1i schon eingebaut.
Der Bot wechselt zwischen 2 & 11 km/h.
Da ich aber keine Outside Links Posten darf, kann ich es leider nicht Anbieten.

**Comment by Ar1i** [comment]
@Procheater mach ein pull request

**Comment by Zodice** [comment]
Can you say it in english please ?

**Comment by Logxn** [comment]
@PrOCheaTer 
Lern wie man pulls erstellt.
