### ISSUE TITLE
addition delay in action

### ISSUE THREAD

**Issue by evetaku** [Ar1i/PokemonGo-Bot#3441]
addition delay in action setting manualy, example transfer,power up and evo,7000ms for transfer,7000ms for power up and 10000ms for evo

**Comment by MTK4355** [comment]
Are you saying that there is an additional delay in those actions, or are you requesting an additional delay?

**Comment by evetaku** [comment]
@MTK4355  yes, i mean additional delay in those actions example for transfer, power up, and evo
