### ISSUE TITLE
Device field is not saved at close.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#3443]
If you write any different model of device in devide combobox when you close the applicationn and open it again you always have selected "lg-optimus-g" so you need change it always than you open the bot.

**Comment by Ar1i** [comment]
you shouldn't write anything in it, just choose one of the devices lol

**Comment by javiermartinalonso** [comment]
Exactly how this feature works?

Is there any limit to the number of devices you can use an account of pokemon go?

If so, we are not using or repeating the id of the phone when using the bot?

There any way to properly set this property with the characteristics of the actual phone we use?

Thank you very much and congratulations on the great work you are doing
