### ISSUE TITLE
Speed Auto setup in code? 

### ISSUE THREAD

**Issue by Kidnub** [Ar1i/PokemonGo-Bot#3445]
so with the version from 6hours ago i saw the speed is auto faster as i did setup it in the gui.... is this an error or now normal because this i switch back to the version before cause their i can setup the speed to 8Km/h XD .... see screenshots ;( http://www2.pic-upload.de/img/31579453/BestSetup4.jpg (old version)
Newversion http://www2.pic-upload.de/img/31579537/BestSetup4.jpg (version proof SS )
Problem ---->> http://www2.pic-upload.de/img/31579653/BestSetup5.jpg (bug nor error=?)
but it did say slow down on speed with near to the target (on 8KM/H??) add screen 
so mit der neuen version ist der speed nun auto egal was mann mach also egal wie ich ihn einstelle ...
weil ich habe ihn normal auf 8Km/h aber nun scheint der bot schneller als normal zu sein in der neuen version so wie ich sagte der alte bot von gersten np mit dem speed aber der neue slowed down beim pokestop 
 i think it is a bug or ===???

**Comment by suljo94** [comment]
@kidnub hide your name on the screenshots niantic is activly banning btw the bot will get you banned since he keeps trowing 210 xp

**Comment by Kidnub** [comment]
@suljo94 this account has no name XD it is the name of the bot np XD why i did erase the mail XD this what you can see is only the name of my bot XD np but thx for the info XD and i know niantic is banning like np i dont bot with my main account.... i just do it to get some lurke items XD and may if the bot is alive at trading i can trade some XD rest np i wont even start him over my mobile phone to prevent HWID ban XD

**Comment by MTK4355** [comment]
Any bot will get you banned. Right now gaining too much XP too fast is the quickest way to get the hammer.

Walk slowly, be patient, and don't get attached to your account. 

@suljo94 The throws will be randomized sooner than later. Don't be a troll.

**Comment by MTK4355** [comment]
@Kidnub There is a walking speed randomizer in play here, that slightly increases or decreases your chosen walking speed each leg of your route. 

If your speed is at or near 10km/hr the randomizer will surely push you over 10 every so often, giving you the "slowing down..." message when you approach the destination pokestop.

**Comment by Kidnub** [comment]
thx @MTK4355 i know you from twitter XD and iknow you support now many freesource bots XD so you meen ineed to put on 5Km or some like that  i wont get that slow down info  =?
 and i sayed on other post .. i really often shut down the bot to let it look like human so my exp earning in 4-5days in not so high .
i am also suprised to you here XD then i close this issue ... thx
