### ISSUE TITLE
version 29/08 xp randomizer doesn't work 

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3446]
keeps trowing 210 xp balls which caused you to be flaged by the server, I know this because the api developers said so

**Comment by MTK4355** [comment]
I would LOVE to randomize this but I don't know what the acceptable ranges are for the API call and I haven't had time to look. These are the defaults used: 
double normalizedRecticleSize = 1.950, double spinModifier = 1, double normalizedHitPos = 1
Anybody know what the acceptable range is?

**Comment by suljo94** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/2548/files

**Comment by MTK4355** [comment]
@suljo94 
I meant more like this:
    SpinBonusThreshold: 0.5
    ExcellentThrowThreshold: 1.7
    GreatThrowThreshold: 1.3
    NiceThrowThreshold: 1
    MilestoneThreshold: 100
found here:
https://gist.github.com/anonymous/077d6dea82d58b8febde54ae9729b1bf

The first implementation will have to be less involved than the Necro code (unless you want to help write it?) but thanks for the reference!

**Comment by MTK4355** [comment]
So..........I lied. I ended up using most of that reference in my latest pull. Thanks again @suljo94

**Comment by suljo94** [comment]
@MTK4355 no problem but I can't really help to code because I already got 1 c&d for another project a few years ago,  won't risk it again
