### ISSUE TITLE
Question for any1 :D

### ISSUE THREAD

**Issue by Jeremy2131** [Ar1i/PokemonGo-Bot#3450]
I just idk how i can ask question
Can any1 say me optimal settings,that would be the chance of a ban was minimal
And.. Who can tell me what is it and how i can use it?
http://prntscr.com/cbtxcz

**Comment by caraoge** [comment]
Create a account for telegram messenger using your phone, install the desktop application, go to https://core.telegram.org/api and start a new chat with "The Botfather" and create a new bot and a new token for it (Botfather will tell you what you've to do). Then you have to enter the generated api token in the first field and your username (without the @) you have choosen in the second field.

**Comment by Jeremy2131** [comment]
@caraoge What is the use?

**Comment by Jeremy2131** [comment]
@caraoge how i can start to chat with the botfarther?

**Comment by Jeremy2131** [comment]
@caraoge i done,nvm, But what i can do with that?

**Comment by Jeremy2131** [comment]
@caraoge console say me if do somethink with bot i can via commans to get information about your account,as I understand it

**Comment by lifeofkuli** [comment]
how to avoid ban?
