### ISSUE TITLE
Suggestion: Items Manager

### ISSUE THREAD

**Issue by Monadologie** [Ar1i/PokemonGo-Bot#3455]
Is it possible to display items (which are in inventory) as Pokemon list (in a windows) when the bot is working. Thanks to that, players'll be able to transfer easily items, for instance when their inventory is full.

**Comment by Hydro420** [comment]
Latest version displays pokeball count for each type - The potions and such don't matter, would only be a waste of time in my opinion. We don't need to see how many potions we have while running the bot, by your item settings you should already know your count.

**Comment by MTK4355** [comment]
Yeah, the feature would take precious time to implement that could be better spent making the bot less detectable by Niantic.

**Comment by Logxn** [comment]
@MTK4355 says it all!
