### ISSUE TITLE
Add pokedex data in list of Pokemons

### ISSUE THREAD

**Issue by RaZer0k** [Ar1i/PokemonGo-Bot#3457]
i add pokedex number to GUI list for best control evolutions and have or not have pokemons.
Please someone add this to source...file attach

[pokemons.diff.txt](https://github.com/Ar1i/PokemonGo-Bot/files/445028/pokemons.diff.txt)

**Comment by suljo94** [comment]
why not pull the source makes everything a lot easier

**Comment by Logxn** [comment]
create a pull request please
