### ISSUE TITLE
please help me !!!!

### ISSUE THREAD

**Issue by josh215** [Ar1i/PokemonGo-Bot#3458]
how can i fix this thing? 'Gmap.Net.WindowsForms.GMapControl'threw an exception.
please help me with this problem and thanks for advance

**Comment by MTK4355** [comment]
Really not much info here. What are you trying to do? Are you running one of @Ar1i's builds or have you changed the code in any way?

**Comment by josh215** [comment]
i am trying to run the map from Ar1i but its not working and thats what it
say .

**Comment by MTK4355** [comment]
Sorry, I still have no idea where to begin looking for a problem.

Anything more specific than "run the map" would be helpful... :/

I don't know which map you are referring to nor how you are trying to run it.

What Version of the application?
Steps to reproduce the problem? 
Screenshots?

**Comment by josh215** [comment]
​i am using latest version and when im clicking tge set location. this
whats happen

**Comment by Reyman69** [comment]
guys, 
When I turn on the bot , it picks up some pokeballs and others. After a few minutes , it runs the pokestop but not catch anything. Just win xp.

why? my version is 1.1.0.8 (i dont see yet where is the update for download)

**Comment by josh215** [comment]
reyman what do u mean by not catching .. hmm i think thats not a problem
maybe ur bag is full thats why youve got only xp .. check ur bag in pokemon
go if its full

**Comment by Reyman69** [comment]
the maximum limit set for this 350max ( the bot) he should recycle. am I right ?

**Comment by MTK4355** [comment]
Only if you have configured it to recycle the right amount of everything to keep your inventory below 350!

**Comment by Reyman69** [comment]
i will update my inventory..i used the old version yet. 1.1.0.4, i never know where i download the last version :(

**Comment by SscSPs** [comment]
download the latest version from from "Builds Only" folder
