### ISSUE TITLE
Clarification...

### ISSUE THREAD

**Issue by navzmic** [Ar1i/PokemonGo-Bot#3459]
is it possible not to get ban (not soft ban or ip ban)
if i using 2 bot at same ip address.. and same location also? (same centrak park).

**Comment by MTK4355** [comment]
Always assume that if you bot, the account will be banned. Not saying you always WILL be banned, but it is very likely unless you are extremely careful about how you use a bot. 

That being said, using two instances of the bot on the same IP address goes against the recommendation clearly legible in the bot GUI and is not at all being careful......

**Comment by 13XxM1CHA3lxX37** [comment]
It's impossible. Imagine Niantic sees two Account with same IP, that can't go together

**Comment by navzmic** [comment]
thank you mate for answering my question.. ^_^
god bless guys...
