### ISSUE TITLE
Pokemon egg incubation

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#346]
can u add a setting in which we can set the eggs to incubate or the eggs or incubated directly coz whenever an egg hatches i have to open the game and put on the other egg to hatch so please try to add that setting. I have donated 10$ so keep up the good work

**Comment by Ar1i** [comment]
Not possible atm, need to update to the newest api first

**Comment by Ar1i** [comment]
But thanks for the Donate! Appreciate it really much!
