### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by Andy217ACE** [Ar1i/PokemonGo-Bot#3463]
Can a schedual be implemented for exemple a 30 min pause every 2 hours. And random speeds every 10 minutes? @Ar1i

**Comment by kobaX383** [comment]
Yes that would be very nice.

**Comment by deadelf0** [comment]
I was thinking maybe a pokestop module button, for when you're paused at a stop. bot is running excellent, perfect!

**Comment by MTK4355** [comment]
I'm adding a Time To Run feature, so it may not be too difficult to throw in a scheduled stop.
