### ISSUE TITLE
Hopfully helpful but not an issue

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3465]
can the mods create an issue thread just for ideas, to provent ideas cluthering up the issues page

**Comment by MVDNESS** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pulls

**Comment by Hydro420** [comment]
^^That's what the "Pull requests" are for.

**Comment by suljo94** [comment]
@Hydro420 most people don't know that that is why they keep creating threads
