### ISSUE TITLE
No Pokeballs

### ISSUE THREAD

**Issue by MVDNESS** [Ar1i/PokemonGo-Bot#3466]
Does anyone have the same problem. Click on Screenshot.

![screenshot_3](https://cloud.githubusercontent.com/assets/20828103/18110959/ed4bb65c-6f1b-11e6-9519-507c9cb144a3.png)

**Comment by MTK4355** [comment]
Set the bot to not catch pokemon for a while and let it farm pokestops to restock, still trying to balance the miss chance..

**Comment by Theseppinator** [comment]
I like the miss rate now, most misses I had is 3-4 or so.

**Comment by MTK4355** [comment]
Yeah, at three I forced a hit regardless of the random factor. When actually playing the game after a few misses you generally get pretty serious about getting on target, I don't care who you are! lol.

**Comment by MVDNESS** [comment]
Ok I'll try it, thanks.

**Comment by left03** [comment]
I had this issue two days ago, when I was farming with 50km/h, after changing the speed to 8km/h everything got fine.

**Comment by MVDNESS** [comment]
It works, but very slowly
