### ISSUE TITLE
No Poke Stops

### ISSUE THREAD

**Issue by kazzaluis** [Ar1i/PokemonGo-Bot#3468]
i'm in a new PC and with a new account in a new Modem.... how can i fix it ??

![image](https://cloud.githubusercontent.com/assets/1984839/18113445/83c5f204-6ef5-11e6-856a-e83e3747cb93.png)

**Comment by kazzaluis** [comment]
Same Problem With Proxy 
![image](https://cloud.githubusercontent.com/assets/1984839/18113478/d2f1b6a6-6ef5-11e6-84fe-c0e0afe02779.png)

**Comment by kazzaluis** [comment]
i'm using a other PokeStops Farmbot and no problem ....
![image](https://cloud.githubusercontent.com/assets/1984839/18113508/08915672-6ef6-11e6-8671-2b72c011b131.png)

**Comment by MTK4355** [comment]
Are you running both bots on the same Proxy IP?

**Comment by kazzaluis** [comment]
just 1

**Comment by MTK4355** [comment]
Right, one at a time. But have you tried the same IP from the bot that works in the one that doesn't?

**Comment by kazzaluis** [comment]
in the item bot works but ar1i bot not work just one at time

**Comment by pilota56** [comment]
My Bts work fine. I think ist an IP Bann. Change you IP and try. Or wait a hour.

**Comment by Theseppinator** [comment]
I have experienced this problem more than once. Don't try and run 2 bots on the same IP, lol xP.

**Comment by Ar1i** [comment]
download newest version
