### ISSUE TITLE
IDEA: Mass evolve

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3469]
It'd be really neet if there was a function that you could enable/disable that saved up your selected pokemons (probably pidgey, rattata, caterpie) and then if you had a certain amount of candy, it pops a lucky egg and evolves them all.

**Comment by pilota56** [comment]
You can do this manually in just two Minutes. I think we do not need not a button for everything.

**Comment by Zodice** [comment]
You can do it with the actual bot : you catch a lot of pidgey when you have enough candy, you put pidgey in "to evolve" and the bot will automatilcy evolve all the pidgey available, if you have enough candys.
