### ISSUE TITLE
Was working perfectly fine, when i updated this happened...

### ISSUE THREAD

**Issue by DannySpeed** [Ar1i/PokemonGo-Bot#3473]
![image](https://cloud.githubusercontent.com/assets/21357608/18121904/bc81d838-6f5e-11e6-9ace-738f41db1108.png)

I am not the most technical guy in the world when it comes to coding, so please bare with me, I updated the build to the latest one and got the above. I then deleted all the files and extracted an older build that was definitely working previously and got the same thing, any idea guys?

**Comment by MTK4355** [comment]
Looks like Perma-Ban to me... Sorry Homie. :(

**Comment by Theseppinator** [comment]
Try logging in with a phone.

**Comment by chiliness** [comment]
same error to me
in my phone it worked

**Comment by Kidnub** [comment]
try then the old verion of the bot from yesterday and if it works show it us? @DannySpeed ?`XD

**Comment by Persada7** [comment]
same like me when i login use PTC

**Comment by Adj1e** [comment]
Work fine. thanks

![screenshot_10](https://cloud.githubusercontent.com/assets/21359601/18126069/a8e2f1fa-6fa3-11e6-820c-77fd641f0ad3.jpg)

**Comment by SscSPs** [comment]
Works just fine for me. 
It could be a network error on your side. because i get something like that when my connection is lost(never bothered to read it all to remember).

**Comment by Hydro420** [comment]
Its a Perm-Ban... Happened to like 5 accounts of mine I had.. Just keep making new ones and be smarter on how u run bot.
