### ISSUE TITLE
Cannot Solve Softban

### ISSUE THREAD

**Issue by Streakz** [Ar1i/PokemonGo-Bot#3476]
I run my account for an hour, but I found my account (probably) get softban, it cant farm at pokestop and cant catch any pokemon even with greatball

this is my ss.

![softban](https://cloud.githubusercontent.com/assets/20916454/18126903/8ca14506-6fa7-11e6-9e9a-f6820f602237.jpg)

Thanks for any help

**Comment by Theseppinator** [comment]
Indeed, a softban. The backdoor that bots used to do, got fixed by Niantic. Just wait your time out. Sorry mate.

**Comment by Hydro420** [comment]
Soft-ban indeed. Kinda odd this happaned to my lvl 28 account 3 times and still no perm-ban, just waiting for Niantic to smack that account too. lol

**Comment by ramigora** [comment]
how long does the soft-ban stay? what if i change settings to not catch pokemon, but only farm pokestops for xp?

**Comment by Hydro420** [comment]
If Soft-Banned you can not get XP from pokestops or catch pokemon. It is random intervals on how long the soft-ban lasts, just turn the bot off and try again in a cpl hrs.

**Comment by AiVo7z** [comment]
@Hydro420 I've had an account which never got softbanned (just botted a Little on that one and kept my eye on it) then didnt log in for a week with the bot. I used it on my mobile device for a while and then got perm banned. They simply detect your 3rd Party prog. if you're unlucky so far I don't think you can survive every banwave if you botted.

**Comment by ramigora** [comment]
for some reason I can farm xp from pokestops, but i'm missing every single pokemon catch

**Comment by Hydro420** [comment]
@Aivo7z I had the same happen to me with a lvl 33 account.. Botted on it, got one soft-ban. Started using on mobile device & I think thats when they finally caught on and Perm-banned it.

**Comment by AndrewTanST** [comment]
I don't think it get fixed by Niatic, the force unban is still working for older version 1.1.0.3, just when this project being redo and then the force unban became broken.

For mobile, spin the same pokespot 40+ times still able to unbanned the soft ban.

**Comment by Hydro420** [comment]
@AndrewTanST Ive personally tested this out & it did not work for me.. I had older version of bot and force unban did not unban me... Nor did logging into a mobile device, spinning pokestops. You might be in a different region running on a older version of the game.. Updates roll out to regions in different times, but regardless by this time, you should have the latest build.

**Comment by AndrewTanST** [comment]
@Hydro420 my Pokémon version is 0.35.0
