### ISSUE TITLE
Pokemon list get stuck when click evolve 

### ISSUE THREAD

**Issue by zyxelgg** [Ar1i/PokemonGo-Bot#3478]
As title, when I click evolve button, the list stuck

**Comment by ArFGLR** [comment]
We have evolve, transfer delay.

**Comment by MTK4355** [comment]
There is a delay of 30-35 seconds after evolving each pokemon to account for the game animation. Pain in the ass, I know, but much safer!

**Comment by itrpower** [comment]
there should be a option to delay it
