### ISSUE TITLE
Misses too much 

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3479]
As i say to title , misses too much and its on some pokemons with 100% probability and the result is to spend all pokeballs/great/etc for nothing. If its possible set it to miss on 50% probability . And i think it doesnt use berries , although not sure 100%

**Comment by AiVo7z** [comment]
Could be a softban. Without more Information this thread is useless.

**Comment by MTK4355** [comment]
"Missed" means the throw did not hit the pokemon. it doesn't matter what the probability of an encounter success is, you can still miss the pokemon with the ball! 100% hit rate on any encounter probability is not realistic. 

We may need to tweak the miss rate again at some point, but it is much better than it used to be.

**Comment by k0ut4li4n0s** [comment]
@AiVo7z  No its not a soft ban,

@MTK4355 i know that you set it to randomly miss some but i think its too much or doesnt farm all pokestops and have less pokeball. Either way pokeballs/great/etc are getting consumed too fast or dont farm pokestops. I think its an issue because i have to keep an eye on it so i restart it and let it farm only pokestops for some time so i can farm pokeballs and let it farm pokemons and pokestops later again

**Comment by MTK4355** [comment]
I don't know about you, but I've certainly run out of pokeballs in real-life PG.... I'm afraid to adjust the miss rate much more in favor of a hit, but I have an idea or two to make it require less babysitting.

**Comment by k0ut4li4n0s** [comment]
@MTK4355 ye thats what i meant, to need less to 0 babysit :))

**Comment by thejundguy** [comment]
bump.. is it possible to not use great ball on rattata/pidgey and misses it?

**Comment by MTK4355** [comment]
Can't make it pokemon specific without a ton of work... Too many other priorities.. Sorry! You can always disable catching the common pokemon if you find they are not worth it.
