### ISSUE TITLE
(Suggestion) Throw ball and catch delay

### ISSUE THREAD

**Issue by xdlinkimo** [Ar1i/PokemonGo-Bot#3481]
Since now we have evolve, transfer delay, we also need throw ball delay, fail catch delay and catching delay to match the game animation.
Things like this will get you banned:
[14:46:25] Found 1 catchable Pokemon(s).
[14:46:26] Encountered Mankey CP 75 IV 26.73% Probability 78%
[14:46:26] Caught New Mankey CP 75 IV 26.73% using ItemPokeBall got 710 XP.
[14:46:28] Found 1 catchable Pokemon(s).
[14:46:29] Encountered Eevee CP 163 IV 61.76% Probability 50%
[14:46:30] Caught Eevee CP 163 IV 61.76% using ItemPokeBall got 210 XP.

Caught 2 Pokemons within 5 second isn't possible with the game, especially where there is a new pokemon.

**Comment by Hydro420** [comment]
Agreed

**Comment by AiVo7z** [comment]
If the bot throws a pokeball and misses he keeps trying that fast it's scary. Whichs way worse than catching 2 pokemons that fast. But same for evolving, Recycling items or sending useless pokemons.

**Comment by MTK4355** [comment]
Good call guys. @AiVo7z I just added delays for evolving, recycling, and transferring. Are you using the latest version?

**Comment by KrustyBooga** [comment]
No doubt this is partly how they can work out who is botting. Catch speeds!

**Comment by MTK4355** [comment]
Added Catch delay in my latest pull.

**Comment by Logxn** [comment]
added
