### ISSUE TITLE
New update, Pokestop

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3482]
It's kinda issue as well as Suggestion. Since the new update you're able to choice if your bot farms pokestops or not (whichs a good Thing imo) but on the bad side you'll run outa pokeballs sooner or later. It only works if you observe the bot all the time and relaunch the bot and Change the Setting. 

My Suggestion, could you Change that Feature a Little? It could pause pokestop farm for xx mins and then farm again, or skip X amount of times, i.e. only every 5th pokestop gets looted. This should work way better especially for being afk whichs the purpose of a bot, except you're to lazy to walk around anyway. :p

**Comment by MTK4355** [comment]
What if the bot detected you ran out of pokeballs and started farming pokestops again, then when you recycled a pokeball stops farming pokestops? Would that make you happy? Because it's coming. Just need more time or more help. lol

**Comment by AiVo7z** [comment]
Why should I run out of pokeballs if I've stacked plenty (no potions needed, low beery amount rest pokeballs) and skip a few spots only? I think you can code it the way it avoids this case. Just saying I don't have an use for pokestop avoiding button except I watch the bot doing its work.
