### ISSUE TITLE
bot dont remove softbann

### ISSUE THREAD

**Issue by Sho0t3r** [Ar1i/PokemonGo-Bot#3484]
The bot is not removing the soft bann and go to any pokestops.. why

**Comment by MTK4355** [comment]
From what I understand, Niantic changed the softban with the last update and the fix no longer works. The latest version does not even have a Force Fix Softban button anymore.

**Comment by Andrewtst** [comment]
I dunno why Ar1i mentioned Niantic change the code where the Force Unban no longer work, but... in older version 1.1.0.3 is still working perfectly, actually the older version 1.1.0.3 had less issue than new version. I still using older version as I find new version is full of issue and without the Force Unban consider totally useless to capture rare pokemon you found the location.

This Force Unban only start not working when this project being revised after some period of no update.

**Comment by MTK4355** [comment]
How about trying harder to avoid a softban in the first place? I haven't even seen one on any of my accounts in weeks. Does it really happen to you that often?

**Comment by AndrewTanST** [comment]
I only get soft ban when I change location (different country) won't happen if you stay is similar location.

**Comment by Hydro420** [comment]
@AndrewTanST - You have the option to hit "Force Unban" but it does not work.. If you dont get EXP from pokestops and cant catch pokemon, hit the Force Unban button and the result will be the same...

**Comment by MTK4355** [comment]
Ah, That's why I don't see it anymore. Ranging out that far has resulted in a perma-ban for me every time, so I don't do it anymore.

**Comment by MTK4355** [comment]
@Hydro420 The latest version doesn't even have the button anymore. Since it wasn't working anyway I repurposed it for the pause walking feature because I got frustrated trying to get a button working on the map layer. lol.

**Comment by Hydro420** [comment]
@MTK4355 Yup - LOVE IT!!! I was just referring to his "older version" (having the option, but it dont work)

**Comment by AndrewTanST** [comment]
Old version is working perfectly fine until today, I catch all my wanted pokemon using old version successful.

New version I try many times, and don't work.
