### ISSUE TITLE
Catch pokemon

### ISSUE THREAD

**Issue by xsmothyx** [Ar1i/PokemonGo-Bot#3485]
Hi i have problem i can open pokestops and get items but i cant catch any pokemons why?

**Comment by AiVo7z** [comment]
Welcome to softban-club

**Comment by xsmothyx** [comment]
but i can use pokestops

**Comment by Hydro420** [comment]
Its odd - I'm not sure what to make of the soft bans anymore.. The other day i was able to catch pokemon but no EXP or items from pokestops.

**Comment by xsmothyx** [comment]
maybe day cap

**Comment by lifeofkuli** [comment]
same to me, any idea?
