### ISSUE TITLE
Antivirus detected trojan in .exe file

### ISSUE THREAD

**Issue by ocuellar** [Ar1i/PokemonGo-Bot#3486]
Hello,

This morning my antivirus detected a trojan located in the .exe file of this application in the 29th versión
I have been using the bot and this is the first time I am getting this error.
Please advice

**Comment by Akuma9GK** [comment]
Microsoft Defender sees it as a Trojan due to how the bot works.

**Comment by AndrewTanST** [comment]
Certain version got this issue not all version, one of the version even make my windows 10 unable to shutdown in proper until I let the windows defender completely remove it.

**Comment by bboylost** [comment]
mate.. this is a game hack... what you expect? lol  dont use any kinds of hacks or bot if you are so scared

**Comment by MTK4355** [comment]
The build just before this one got removed by windows defender for me too. Not sure why it didn't happen previously or since, but it is something I am curious about.
