### ISSUE TITLE
Early Morning Exception

### ISSUE THREAD

**Issue by Buckrogers81** [Ar1i/PokemonGo-Bot#3487]
Moin,

every moring I receive a Exception, as follwos later. I am Botting during the evening- and nighttimes. With my configuration there is no Problem starting the Bot at 6 PM and let it run until the next Morning 5:30 or even 7:00 AM. So the Bot runs 12 hours and more without a problem.
But if I start in the morning and leave for work, the Bot shuts down short after. Sometimes at 8:00, sometimes at 6. But usualy I start at 5:30 and short time after the Bot goes down. After I restart the bot everything works fine.

Exception:
[08:10:39] Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 84.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Player.cs:Zeile 41.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Navigation.cs:Zeile 90.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__19.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 313.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__12.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 153.
[08:10:39] Starting again in 10 seconds...

**Comment by Hydro420** [comment]
Looks like a Perm-Ban buddy... Dont run the bot overnight - its better to run it during the day and run it in coordinates where there is a large population of players.

**Comment by MTK4355** [comment]
Can't be tied to time of day, because in my real-world pokehunting (Entirely Bot-Free Account) I ONLY hunt at night. Too damn hot where I live... lol. 

In fact, there's a popular farming location in my hometown where four pokestops overlap, and they are lured 24 hours a day. Some folks sit out there for 8+ hours every night catching mountains of pidgeys and grinding XP.

**Comment by Hydro420** [comment]
I got ya MTK - but with the way the bots previous built was, I'm sure it was way easier for Niantic to figure out who was botting and not depending on the active player's in region/time?

**Comment by MTK4355** [comment]
I get it, safety in numbers sort of thing? Possibly. 

This image explains why I added the "pause walking" feature. I can just park my bot right on the corner of this intersection while farming these four stops over and over, and catch pokemon for hours without worrying about the abnormal routing giving me away..
![image](https://cloud.githubusercontent.com/assets/11677019/18138401/189fa2e0-6f72-11e6-8c35-210261b8f6d3.png)
Niantic, if you're watching this is not my account so please don't ban this poor dude. lol

**Comment by Hydro420** [comment]
LoL - I think i'll start doing the same to catch a bunch of dratinis near the Planetarium Downtown :-D

My exact thought - "Safety in Numbers."  by the way, thanks a bunch for the work. I love the pause option when I'm using the bot to evolve or transfer pokemon.

**Comment by MTK4355** [comment]
Me too... This might give you some hope for the future.. Not nearly ready to release, but it's coming along!

![image](https://cloud.githubusercontent.com/assets/11677019/18140941/385ddea2-6f7d-11e6-82eb-4c10fc648f61.png)

**Comment by Buckrogers81** [comment]
Like i wrote, there is no BAN! I can start the Bot again and keep going. And this only happens in the Morning.
