### ISSUE TITLE
Latest build dose not work

### ISSUE THREAD

**Issue by Andy217ACE** [Ar1i/PokemonGo-Bot#3488]
Hello,

     For me the latest build dose not work i ant farm pokestops but with the previous one it works.

**Comment by MTK4355** [comment]
Screenshots please? Settings and Client logs if you will, but please don't forget to remove your login/player info before snapping a screenshot.

**Comment by Andy217ACE** [comment]
i can give you a team wiever if you want

**Comment by Andy217ACE** [comment]
add me: https://www.facebook.com/ciupitu.andrei

**Comment by toxic189090** [comment]
use http://prnt.sc/ its easier

**Comment by Andy217ACE** [comment]
Old build
![untitled](https://cloud.githubusercontent.com/assets/21294414/18139077/7997201e-6fb8-11e6-8d9e-df773ace0dcc.png)
New Build
![untitled2](https://cloud.githubusercontent.com/assets/21294414/18139082/836264be-6fb8-11e6-89ab-060656d7e9b1.png)
Same settings
![untitled3](https://cloud.githubusercontent.com/assets/21294414/18139098/985999dc-6fb8-11e6-9d3a-ca671caa4cf8.png)
![untitled4](https://cloud.githubusercontent.com/assets/21294414/18139099/98610c58-6fb8-11e6-918b-b015254f3dc3.png)

**Comment by Andy217ACE** [comment]
Same settings but the new build dose not farm

**Comment by Andy217ACE** [comment]
I can give acces to my pc and my account if it is needed

**Comment by MTK4355** [comment]
Let me try to recreate locally first. Might take a while. standby.

**Comment by Andy217ACE** [comment]
i've paused the bot for 2 hours and i've tryed again, same problem the old version works the new one not working. For me there is no problem i will use the old one but maybe there is something wrong. You dont nedd to check it up just to know about

**Comment by Kidnub** [comment]
you know the chance of ban is high so ?

**Comment by Andy217ACE** [comment]
i know the risk but i  was testing something, also the bot still dose not work, even i will lose the account i will still test with other accounts. I've drawn some conclusion about the bot, and i will comunicate them to the team when my test will be done. i have around 20 accounts on different pc's with different ip i'm trying to find some patterns how the server is throwing pokemns on the map so that  some day to be able to ppredict where a certain pokemon will be found. It is a lot of data to gather and to process. I'm using 1000m radius and i'm carefull to position the cicles so that they overlay a bit. Anyway my main account is working fine but with the old version not the new one. also the other accounts are using old versions i've not updated them.
