### ISSUE TITLE
a way to not farm pokestops?

### ISSUE THREAD

**Issue by brooky325** [Ar1i/PokemonGo-Bot#349]
is there a setting or something i can delete to stop farming pokestops i just want to catch selected pokemon

**Comment by TMaddox** [comment]
why would you do this ?

**Comment by brooky325** [comment]
because im a high level and dont want the extra xp of pokestops untill i need pokeballs

**Comment by Ar1i** [comment]
That makes no sense m8, if i got time i put it in
