### ISSUE TITLE
Bot failing to restart

### ISSUE THREAD

**Issue by SmileFX** [Ar1i/PokemonGo-Bot#3490]
Hello There!

Since about 1 hour I am having issues with the bot, within vers. 1.1.0 - 1.1.1.2... 

I just let it do his thing, but suddenly he tried to restart all over, every ten seconds ;/
After i restarted him on my own (including multiple versions) He won't do his thing either...
Any solutions?

Here is my Error I am getting (Sorry, that it is in German):

![unbenannt](https://cloud.githubusercontent.com/assets/21368565/18140501/1fb9689c-6fb6-11e6-8a45-cf23ce386457.JPG)

Thanks for your help!

>> EDIT: I am NOT softbanned or banned, I just logged in with my mobilephone, but logged out again! <<

**Comment by Hydro420** [comment]
Looks like a Perm-Ban buddy... That account is gone.

**Comment by SmileFX** [comment]
It isn't, just recently (About 2 minutes ago) logged into it with my mobile and was able to do whatever I wanted to ^^

**Comment by SmileFX** [comment]
But yes, your write! It has to do something with the PTC login (Servers are up and running)

**Comment by Hydro420** [comment]
I get same message for my perm-banned accounts.. Does it work yet? Try bot with a different account, if it works than its an obvious perm-ban.

**Comment by SmileFX** [comment]
Ok, I think I can close this thread, I found the problem:
- My acc isnt banned at all
- Others are working (Glad I didnt bot my main account)
Its not working cause I have to verify my email at the PTC, but I used a 10min mail, so this is impossible ^^ 

Anyway, just creating another account, walking around in San Francisco Beach 24/7, wanna be lvl 26 (as I was) in a few days again! Thanks a lot, Botcreators!

**Comment by SmileFX** [comment]
// closed
