### ISSUE TITLE
Hibernate while running the Bot

### ISSUE THREAD

**Issue by Viper2k4** [Ar1i/PokemonGo-Bot#3491]
Hi,

my PC goes into hibernate while running the bot. Yes i could change my power-settings. But i would say it woul be even more cool if the bot prevent somthing like this by it self.

I use this class in my tools and i would share it with u:
```

public static void PreventSleep()
{
    SetThreadExecutionState(ExecutionStates.Continuous | ExecutionStates.SystemRequired);
}

public static void AllowSleep()
{
    SetThreadExecutionState(ExecutionStates.Continuous);
}

#region Nativ-Calls
[DllImport("kernel32.dll", SetLastError = true)]
internal static extern ExecutionStates SetThreadExecutionState(ExecutionStates esFlags);

/// <summary>
/// Enumeration of execution states.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2217:DoNotMarkEnumsWithFlags")]
[Flags]
public enum ExecutionStates
{
    /// <summary>
    /// No state configured.
    /// </summary>
    None = 0,

    /// <summary>
    /// Forces the system to be in the working state by resetting the system idle timer.
    /// </summary>
    SystemRequired = 0x1,

    /// <summary>
    /// Forces the display to be on by resetting the display idle timer.
    /// </summary>
    DisplayRequired = 0x2,

    /// <summary>
    /// Enables away mode. This value must be specified with ES_CONTINUOUS.
    /// Away mode should be used only by media-recording and media-distribution applications that must perform critical background processing on desktop computers while the computer appears to be sleeping. See Remarks.
    /// 
    /// Windows Server 2003 and Windows XP/2000:  ES_AWAYMODE_REQUIRED is not supported.
    /// </summary>
    AwayModeRequired = 0x40,

    /// <summary>
    /// Informs the system that the state being set should remain in effect until the next call that uses ES_CONTINUOUS and one of the other state flags is cleared.
    /// </summary>
    Continuous = unchecked((int)0x80000000)
}
```

Now u could call "PreventSleep" this will prevent the PC go in hibernate. I would create a PR. But atm. i dont have the time to search the functions the stop and the start the bot^^ ( it hink there are maybe some more points).

Bot start call 'PreventSleep'. 
Bot stop (by user) call `AllowSleep`. 

Its not necessary to call `AllowSleep` if the user close the bot. Its only for the case the User stopes the bot and dont close the console.

**Comment by MTK4355** [comment]
I'm not comfortable being that invasive, personally. Cool function though. :)

**Comment by Viper2k4** [comment]
SetThreadExecutionState is very safe to use. It dont change a user setting or anything else:

https://msdn.microsoft.com/en-US/library/windows/desktop/aa373208(v=vs.85).aspx

"Enables an application to inform the system that it is in use, thereby preventing the system from entering sleep or turning off the display while the application is running."

That is what we want.

"The system automatically detects activities such as local keyboard or mouse input, server activity, and changing window focus. Activities that are not automatically detected include disk or CPU activity and video display."

And this is our Problem ^^

(and sry for my englisch :/)

**Comment by SscSPs** [comment]
Make a pull request with the implementation.

**Comment by Viper2k4** [comment]
mh ok. But i dit it the simple way (`PreventSleep` at start and `AllowSleep` after close). Mayber there a some better points, but it work^^

**Comment by Ar1i** [comment]
done
