### ISSUE TITLE
[bug] When you open the map and close it. The bot crashes

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#3493]
When you open the map and close it. The bot crashes:
And other thing, does not show pokestop with or without checkbox checked.

This is the exception thas throw

Exception: System.ObjectDisposedException: No se puede obtener acceso
 al objeto eliminado.
Nombre del objeto: 'LocationSelect'.
   en System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate meth
od, Object[] args, Boolean synchronous)
   en System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   en PokemonGo.RocketAPI.Console.LocationSelect.handleLiveGeoLocations(GeoCoord
inate coords) en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\Pokemon
Go.RocketAPI.Console\Location.cs:línea 122
   en PokemonGo.RocketAPI.Logic.LogicInfoObservable.GeoLocationHandler.Invoke(Ge
oCoordinate value)
   en PokemonGo.RocketAPI.Logic.LogicInfoObservable.PushNewGeoLocations(GeoCoord
inate newValue) en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\Pokem
onGo.RocketAPI.Logic\LogicInfoObservable.cs:línea 23
   en PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__24.MoveN
ext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.Rocke
tAPI.Logic\Logic.cs:línea 478
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la
excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() en
C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logi
c\Navigation.cs:línea 95
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la
excepción ---

**Comment by MTK4355** [comment]
You need to open the map ASAP when starting the bot or the pokestops will not render until the next logical loop where the bot queries all available pokestops. 

This could be hours depending on your location and configuration.

I have this on my list of TODO but it's pretty far down the list.

**Comment by Logxn** [comment]
Which actually is pretty darn easy to fix...

**Comment by MTK4355** [comment]
Sooooooooo implement the fix and submit a pull request. One less thing on the list for everybody. :)

**Comment by kimjongun69** [comment]
how do u open the map?

**Comment by MTK4355** [comment]
As soon as the pokemon list loads its the big button on the bottom right that looks like a map.

**Comment by MTK4355** [comment]
![image](https://cloud.githubusercontent.com/assets/11677019/18154670/5ac1f574-6fcc-11e6-879a-dd12303b1d98.png)

**Comment by kimjongun69** [comment]
@MTK4355 rofl been watching it a bit. im teleportinggg
