### ISSUE TITLE
Telegram settings don't work

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3495]
when I try to send a command I get a picture of dumbledor you have no power here when I reopen the bot the api token is 0

**Comment by Ar1i** [comment]
You probably didn't entered your username

**Comment by suljo94** [comment]
Yep it but it resets it and it doesn't accept commands

**Comment by ArFGLR** [comment]
Yes, it doesn't save token.

**Comment by ArFGLR** [comment]
Also, it doesn't save some other options.

**Comment by suljo94** [comment]
@Ar1i it doesn't save walk settings either just checked and it wason a clean version 01/09 and 31/08

**Comment by OkamiHoshizora** [comment]
Same problem, how do we got information from the telegram bot?
