### ISSUE TITLE
Gem counter at poke stops

### ISSUE THREAD

**Issue by toxic189090** [Ar1i/PokemonGo-Bot#3498]
![5eace19f3ed046288a0e74c3ad43ba98](https://cloud.githubusercontent.com/assets/21367666/18150727/1b9a45b4-6fb7-11e6-8f30-cb555cb15c04.png)

im confused why is there a gem counter?

**Comment by Zodice** [comment]
I have no idea too, if anyone know ..

**Comment by MTK4355** [comment]
No idea what that does either, but I don't like removing other's code unless there is a functional reason for the omission. Haven't ever seen it do anything though!
