### ISSUE TITLE
Can't catch pokemon if you have no pokeballs?

### ISSUE THREAD

**Issue by omgcharliecat** [Ar1i/PokemonGo-Bot#350]
Version "Builds only 30.07" -  I tried to set my pokeballs to zero and some weird stuffs happens. It seems the bot doesn't know how to switch to greatballs if there are no more pokeballs. Personally I want to use **only** greatballs for catch pokemons for higher catch rate since we get so many of them anyway. Please Investigate thanks :)

**Comment by globsch** [comment]
please post an error log. this shouldn't happen according to the code.
GetBestBall
Logic.cs l511-542
`return balls.OrderBy(g => g.Key).First().Key;`

**Comment by Tharock** [comment]
is that  working ?

**Comment by maekzi** [comment]
Bot works as the code says. When i am out of Pokeballs he uses Great and after that Ultra.

I have my Pokeballs set to 0 too but sometimes he still uses the ones he got on the latest Pokestop bc he did not recyle em before catching the next one :D

**Comment by omgcharliecat** [comment]
oh, most of my pokemons are run away if i set my pokeballs to zero not sure why. will try again

**Comment by Ar1i** [comment]
Try newest version, should be fixed
