### ISSUE TITLE
"Cant find any pokestop" error!!

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3500]
i facing this issue just now.. can i know whats the problem? 
![error](https://cloud.githubusercontent.com/assets/21377477/18155357/a66f5e1c-703f-11e6-803c-12b382f733e9.jpg)

**Comment by Jeremy2131** [comment]
Check u inventory, or try reboot bot :)

**Comment by lifeofkuli** [comment]
@Jeremy2131 because of inventory full? I thought it should be a soft ban?

**Comment by nasierache** [comment]
my inventory is 255/300.. i just run the bot again...now everything is fine. but i just want to know what may cause that problem?

**Comment by lifeofkuli** [comment]
@nasierache  hi, I got the same error when I run more than 1 acc

did u bot more than 1 acc?

**Comment by nasierache** [comment]
im using a wifi and my friend are using the same wifi connection...both of us run bot at the same time..are this consider run 2acc on same ip?

**Comment by lifeofkuli** [comment]
@nasierache yes, it is

**Comment by tmkhanh** [comment]
No, it's not. You will probably have different IPs in your local network (Wifi, cable) but will have same IP going out from your Internet router to Internet.

**Comment by nasierache** [comment]
@lifeofkuli how to unbanned the ip that has been banned by niantic? im using this wifi connection 20hr per day..lol

@tmkhanh yeahhh i know that..but i think niantic detect the IP on the domain connection not the devices IP...thats why i got this softban..

**Comment by MTK4355** [comment]
If you reboot your Modem (where the coax cable or dsl line convert to LAN) it can sometimes get a new IP from your ISP, but otherwise just wait and it will cycle to a new IP. Gotta love residential service. lol. If you have a business ISP account with static IP addresses (usually for web sites or web apps) you'd be screwed! lol.

**Comment by lifeofkuli** [comment]
@nasierache stop botting for 2 days, thats what i did

**Comment by nasierache** [comment]
@MTK4355 i see.. thanks for the info
@lifeofkuli  noted..i will stop botting for now..
