### ISSUE TITLE
French does'nt work

### ISSUE THREAD

**Issue by MarSonik** [Ar1i/PokemonGo-Bot#3501]
If you click on the french flag, the console still in English. Name of pokemon too.

In English : 
![image](https://cloud.githubusercontent.com/assets/21366172/18159912/20177dd6-702b-11e6-8f35-e53b5d869ffe.png)

In French :
![image](https://cloud.githubusercontent.com/assets/21366172/18159924/29fc461a-702b-11e6-9117-f4ee995de24d.png)

**Comment by Zodice** [comment]
Le français n'est pas encore totalement au point, et encore moins pour la liste des pokémons quand le bot est actif.
