### ISSUE TITLE
Time to run

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#3507]
Hello,
Time to run is written to API Token after restart of the Bot, i think this is a bug.

THX for the Bot!!!!!!

**Comment by vitus0123456** [comment]
sorry kindda new to the new interface, what's this "Time To Run" for?

**Comment by MTK4355** [comment]
The logic will stop the bot after running for the number of minutes you provide in the Time to Run field...

**Comment by vitus0123456** [comment]
ah. thanks
