### ISSUE TITLE
Walking Speed (Always at MIN)

### ISSUE THREAD

**Issue by Hydro420** [Ar1i/PokemonGo-Bot#3508]
As stated - bot randomizes walking speed and is always set to the lowest walk speed as I've noticed. Was this meant to be or is it a bug? I figured it would pick a random number between the lowest walk speed and the current set speed (when starting bot)?

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18170183/f7627a06-7022-11e6-83ea-17f97f424d36.png)

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18170264/550266d0-7023-11e6-96a7-1b15b48e049a.png)

**Comment by MTK4355** [comment]
Good call, next pull will fix.

**Comment by Hydro420** [comment]
@MTK4355 Thanks a bunch! You Ar1i & the rest of the guys are doing an amazing job. I can't express enough gratitude in making this an open "free" project.
