### ISSUE TITLE
Lure Stop

### ISSUE THREAD

**Issue by arkzzzzz** [Ar1i/PokemonGo-Bot#3509]
Thanks for your great worked on it man
so is it possible to set bot walking around Lure Stop than just standing for found more pokemon

i'm just suggestion 

Thanks

**Comment by Kidnub** [comment]
lol yes and the bot it doing it with you would watch the new gui Tab XD

**Comment by MTK4355** [comment]
Like circle around in a radius? or the closest few pokestops? Probably. Though the idea is that the dude would be resting from walking around all day! lol.

**Comment by arkzzzzz** [comment]
@MTK4355 sry man i'm confused my self ! lol. Just get the point of break at lure features. do apologize !

**Comment by MTK4355** [comment]
Well, it might make sense to move around a bit, lures can get pretty slow at times. I'll put that in the hat for future consideration. Thanks for your feedback!

**Comment by AiVo7z** [comment]
@MTK4355 does the bot run straight to a Lure module atm or just stops as soon as it's within range? Didn't test new Version yet, too busy but soon I will. It would be more human-like to aim for Lure modules and only walk between those who're pretty Close ans especially not have a river inbetween or something.

**Comment by MTK4355** [comment]
If the next pokestop you are walking to has a lure module active, the bot plans to wait at the lure until it expires. at the moment it will not prioritize pokestops with a lure but that is a good idea. 

I wouldn't know how to detect that there is a river on the map from the code, but once I have the google directions API stuff done the bot will be able to use real-world directions between pokestops.

**Comment by Nath789** [comment]
I think the feature "Use Lure at break" gets enabled even we don't. Does it even check the settings? I think it is not even saved based on the Configs folder.

**Comment by MTK4355** [comment]
Right. I just sumbmitted a pull request to fix the default. Workaround until next build is to check and uncheck the box before starting the bot EVERY TIME.
