### ISSUE TITLE
Your bot is awesome and wonderful, you create the most convenient Gui. It's ok but i think your bot will more perfect if you add some features: rename pokemon, sniper pokemon, farm rare candy. Thank you so much and hope you so!

### ISSUE THREAD

**Issue by duyennsiro** [Ar1i/PokemonGo-Bot#3510]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Kidnub** [comment]
NO cause then it looks again not like a human being pls not stuff like that ... now he is closly perfect,,,
rename maybe a good idea but the rest no no no no no no no no XD

**Comment by angelcuenta** [comment]
im with he, need more features but thanks whatever

**Comment by nasierache** [comment]
i will prefer to add 'avoid cross blue color(water) on the map features...it sometimes across lake and river frequently..lol...in this case they(niantic) may detect bot is active and we maybe got ban...lol

**Comment by jay-2-rome** [comment]
No way! Just keep the bot the most human-like possible!!!
