### ISSUE TITLE
[BUG] Altitude stay at 0

### ISSUE THREAD

**Issue by maskime31** [Ar1i/PokemonGo-Bot#3511]
In 1.1.1.2 and 1.1.1.3 version I have a bug where altitude keep staying on 0 meters even if it's a different location.

![1](https://cloud.githubusercontent.com/assets/21686213/18172059/722d9540-7064-11e6-9030-8a5fedbed829.PNG)

And after changing localisation 

![2](https://cloud.githubusercontent.com/assets/21686213/18172185/c4b74662-7064-11e6-8711-2fedfd27f8e9.PNG)

Thanks !

**Comment by NerdisDev** [comment]
+1

**Comment by SscSPs** [comment]
Doesn't matter much, it is fixed when you start the bot(let it play).

**Comment by maskime31** [comment]
Il tries to restart every 10 seconds, I let it truc during 10 minutes so...

**Comment by SscSPs** [comment]
close the not and open again. 
If that does not help, please paste the error/exception generated, here.

**Comment by Ar1i** [comment]
Cause google don't accept any request blocked sometimes idk why. But it's get fixed if you start the bot! :)

**Comment by maskime31** [comment]
Il tried maybe 10 times. It should came from my internet connexion...
Thanks ! I suppose you can close this issue. ☺️
