### ISSUE TITLE
Someone Merge this file to pull request [POKEDEX ADDED]

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#3514]
[pokemons.diff.txt](https://github.com/Ar1i/PokemonGo-Bot/files/450194/pokemons.diff.txt)
@Ar1i @MTK4355 @Logxn

**Comment by SscSPs** [comment]
why not just make a pull request?

**Comment by PokePro21** [comment]
I tried but dont know how to do that

**Comment by SscSPs** [comment]
the way i do is 
step one: fork the current repo
2: add the code in your repository(forked).
3: come back to this repo(Ar1i/PokemonGo-Bot) and go to "Pull Requests" on the top.
4: create pull request from there.

just this simple.
Try it out

**Comment by PokePro21** [comment]
how to fork the current repo?

**Comment by PokePro21** [comment]
Thank You so much @SscSPs

**Comment by Ar1i** [comment]
doing it, next time don't do a diff, edit the code directly and push it then :p would be easier can accept directly
