### ISSUE TITLE
I'm ban ?

### ISSUE THREAD

**Issue by santrale** [Ar1i/PokemonGo-Bot#3515]
I don't know so i'm ban because the bot , he doesn't want take some pokestop and he doesn't take pokemon

screen : http://www.noelshack.com/2016-35-1472747835-ban.png

**Comment by SscSPs** [comment]
No, you are not banned. you are just standing at a pokestop which have a lure module. 
the latest version have many bugs, those will be fixed soon(supposedly). 
For now, you can use 1.1.1.2 instead of 1.1.1.3

**Comment by santrale** [comment]
how choose the version ?

**Comment by SscSPs** [comment]
you do not have the previous version?

**Comment by santrale** [comment]
no, i don't 
I deleted the version

**Comment by SscSPs** [comment]
You can download from my fork, it have the 1.1.1.2 version
https://github.com/SscSPs/PokemonGo-Bot

**Comment by santrale** [comment]
Thank you :)

**Comment by SscSPs** [comment]
@Ar1i close this
