### ISSUE TITLE
Suggestion!!

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3517]
it will be more perfect if your team can add **'avoid cross blue color(water) on the map'** feature...it sometimes across lake and river frequently..lol...in this case they(niantic) may detect bot is active and we maybe got ban...lol.. by adding this features will made the bot is like human perfectly..in my opinion..

**Comment by MTK4355** [comment]
In the new Walk Settings tab in GUI you will see a place for google maps API key. When this feature is finished, it will allow you to get routing from google directions, meaning you will walk along actual paths of travel to reach each pokestop! :)
