### ISSUE TITLE
Delay Transfer

### ISSUE THREAD

**Issue by caiom1** [Ar1i/PokemonGo-Bot#3519]
Hi, i like to much Ar1i bot because it is the only can realy keep pokemons that can evolve when i transfering. But today, in version 1.1.1.3, when i transfer my pokemons, the delay is too large, 6,7,8seg to 1 transfer, while others versions is just 1 secound. How i can back to 1 sec for 1 transfer? Thanks

![image](https://cloud.githubusercontent.com/assets/21690941/18176977/672d719e-704e-11e6-93b1-af9e1fa105d5.png)

**Comment by SscSPs** [comment]
Use previous version to get rid of the delay. This delay is added to imitate human behavior. because, the app takes time to transfer pokemons. So, to make the bot more undetectable, this delay is implemented.
You will also notice delay in evolving, it takes somewhere between 15-20 seconds between each evolves. 
Just the other day, i had to evolve 128 pokemons, i used older version to do that because it is faster in the previous versions. But yeah, the risk is higher!

**Comment by MTK4355** [comment]
When I publish my bug fixes today, I'll add a user setting to toggle the app delay, even though I think the risk is too high for any reasonable person to want to disable it! No matter how long it takes, at least you don't have to sit there and ACTUALLY evolve them all one by one in the app! :)

**Comment by SscSPs** [comment]
I generally do mass evolves, mostly around 130 pokemons, 20 second delay for that means 130*20 = 2600 seconds. which is 43 minutes. and i plan to use a lucky egg and that is of 30 minutes, which will be cut off at 30 minutes, i just hate it, thats why i used the older version.

15 seconds will be 32 minutes and that is also not something i like. 
Having the option to change the delay time would be nice as i'll just set it to something suiting my all pokemons to be evolved in 30 minutes! :)

**Comment by MTK4355** [comment]
Still risky, but I'll add the toggle for now and consider making the delay variable if time permits. Thanks for the feedback!

**Comment by SscSPs** [comment]
I'll also try to do what i can if i get time

**Comment by caiom1** [comment]
yeah sscsps, i will do it this, but just version 1.1.1.1 or bellow is possible, i hope Ar1i can put options for us chose

**Comment by SscSPs** [comment]
Lets not talk about the developer by name, just "Dev" is to mantain respect
for all those who work. Naming someone might make others feel a little
less, deep inside.
