### ISSUE TITLE
[Feature Request]Auto-Transfer

### ISSUE THREAD

**Issue by Kjiz** [Ar1i/PokemonGo-Bot#352]
I was thinking about a list in which you can select Autmoatically Transfer Pokemon for example you tick zubat and every Zubat you catch would be transfered automatically
Its a good way to earn xp without having Pokemon you dont want

**Comment by 12348766754** [comment]
Put the amount of double pokemons on 1 and the bot will do it automatically?

**Comment by Kjiz** [comment]
Yea but the Problem is when you have 2 or more of other Pokemon and you wont give em up

**Comment by SlDracon** [comment]
Then put them on the not transfer list.

**Comment by Kjiz** [comment]
You dont understand what i mean

**Comment by Kjiz** [comment]
When you catch a Pokemon and Transfer it you´ll get XP

**Comment by Logxn** [comment]
Would be a good addition.

**Comment by Pseudoxanthoma** [comment]
I have a question. How can I config the bot to keep the top 5 (of the same pokemon) with highest CP? At the moment he keeps everything with 85% IV which includes very weak pokemon with like 10 CP. He always picks IV over CP.
