### ISSUE TITLE
Walking in straight lines

### ISSUE THREAD

**Issue by fetmamm** [Ar1i/PokemonGo-Bot#3522]
Hello.
Noticed when i started up the newest update that the bot walks in straight lines instead of walking to the closest pokestop. Is there any way to fix this?
![hmmmm](https://cloud.githubusercontent.com/assets/21282959/18179000/d38a4696-7080-11e6-93a3-7cbafbb642a2.png)
![gggggg](https://cloud.githubusercontent.com/assets/21282959/18179093/40af33d0-7081-11e6-92a3-3d21e8f863ad.png)

**Comment by MTK4355** [comment]
What's happening there is that the query for pokestops is returning a bunch of results that are outside of your designated radius, then when the bot determines that you are outside of the radius you defined it walks back to the default location. Problem is, the next pokestop in the route is also outside of your designated radius and you end up repeating the process again and again! 

I haven't been able to reproduce the issue of returning that many pokestops outside of my radius, so it is difficult for me to debug. A possible workaround for you might be to increase the size of your radius. Can you try that and show me what happens?

**Comment by MTK4355** [comment]
Another possible workaround would be to uncheck the "Start walk from default location" option, but try the radius increase first. K?

**Comment by Hydro420** [comment]
"Start walk from default location" does not work as I tested it myself.. Best option is to increase the radius and you have no issues at all. Make it the original 5000 meters and you're good to go.

**Comment by Zodice** [comment]
What is the google maps routing ?
And it's better for the eggs to walk in straight lines, they will open quicker.

**Comment by MTK4355** [comment]
The google maps routing will get walking directions from google to make the bot follow actual roads and footpaths between pokestops.

**Comment by MTK4355** [comment]
That's one of the reasons I like slower speeds. if you are pushing the limit of human-walkable speeds while travelling in a straight line between stops, what happens to that speed if you figure in all of the turns it would take you to really walk between those two points? 

Niantic obviously does not see the lines our bot draws from our paths, but they almost certainly have a system that flags accounts which seem to move between places too quickly.

**Comment by fetmamm** [comment]
Alright, I will definately try it when i come home. And post the result here as well :)

**Comment by fetmamm** [comment]
Works just fine now :)
![hejss](https://cloud.githubusercontent.com/assets/21282959/18215056/c4b42e00-714f-11e6-84d4-9872d3c1db85.png)
