### ISSUE TITLE
Walk settings clearing

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3523]
Every time I restart the bot, the walk setings clear, could you make a file that stores the data? It'd be very cool. Thanks!

**Comment by MTK4355** [comment]
Yeah, it's a known issue. There are a few others here: https://github.com/Ar1i/PokemonGo-Bot/pull/3497

**Comment by Hydro420** [comment]
Not too bad at all @MTK4355 - Takes only few seconds to type them in again...
