### ISSUE TITLE
WARNING: I DON'T KNOW HOW PULL REQUESTS WORK, so I did it in here, sorry.

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3525]
Dutch translation:
{
	"accountType": "Account type:",
	"username": "Gebruikersnaam:",
	"password": "Passwoord:",
	"locationSettings": "Locatie instellingen",
	"speed": "Snelheid:",
	"moveRadius": "Radius:",
	"meters": "Meter",
	"startFromDefaultLocation": "Start vanaf standaartpositie",
	"botSettings": "Bot instellingen",
	"autoTransferDoublePokemon": "Dubble pokémon automatisch verkopen",
	"maxDupPokemon": "Max. Dubbele pokémon",
	"maxCPtransfer": "Max. CP om te verkopen:",
	"maxIVtransfer": "Max. IV om te verkopen:",
	"telegramSettings": "Telegram instellingen",
	"infoline1": "Deze bot is gratis en open-source! Als je betaald hebt, vraag onmiddelijk je geld terug!",
	"infoline2": "Wanneer u de naam 'Pokecrot' ziet, laat iedereen weten dat deze wordt gestolen.",
	"maxPokeballs": Max. Pokeballen:",
	"maxGreatballs": "Max. Superballen :",
	"maxUltraballs": "Max. Ultraballen:",
	"maxMasterballs": "Max. Meesterballen:",
	"maxRevives": "Max. Herrijzer:",
	"maxTopRevives": "Max. Top-Herrijzer:",
	"maxPotions": "Max. Drankje:",
	"maxSuperpotions": "Max. Superdrankjes:",
	"maxHyperpotions": "Max. Hyperdrankjes:",
	"maxToppotions": "Max. Top-Drankjes:",
	"maxRazzberrys": "Max. Frambozen:",
	"totalCount": "Totaal aantal pokémon:",
	"pokemonNotToTransfer": "Pokemon - Niet te verkopen",
	"selectAll": "Alles selecteren",
	"pokemonNotToCatch": "Pokemon - Niet te vangen",
	"pokemonNotToEvolve": "Pokemon - Niet te evolueren",
	"saveConfig": "Configuratie opslaan / Bot starten",
	"otherSettings": "Andere instellingen",
	"useLuckyeggAtEvolve": "Geluksei gebruiken bij het evolueren",
	"useRazzBerry": "Gebruik Frambozen",
	"germanPokemonNames": "Duitse Pokémon-Namen",
	"useIncese": "Gebruik lokmiddel",
	"evolvePokemonIfEnoughCandy": "Pokemon evolueren als je genoeg snoepjes hebt",
	"enablePokemonListGUI": "Gevangen pokémon lijst aanzetten",
	"keepPokemonWhichCanBeEvolved": "Houd pokémon die geëvolueerd kunnen worden",
	"autoIncubate": "Automatisch broeden (Niet zeker dat het altijd werkt)",
	"useBasicIncubators": "Allen basis incubators gebruiken"
}

I am dutch myself, so this'll be pretty accurate

**Comment by Josnoww** [comment]
Password should be -> "Wachtwoord"
