### ISSUE TITLE
Bug with Altitude, LastCoords and Path

### ISSUE THREAD

**Issue by RaZer0k** [Ar1i/PokemonGo-Bot#3526]
I have three issues:
1.- when i select a location in the map the altitude always return 0 or default value. Sometimes return the correct value but this is in 1 of 10 occasions.
2.- when i close the console in X2:Y2 location (different from X1:Y1 start location) the bot always start in X1:Y1 not in X2:Y2.
3.- because the second bug... i check the bot always do the same path... this look for the closes pokestop and then got to the next closes... so if you do this repeatedly you get the same path every time. So i recommend to get the 3 closes pokestops and random select one.

**Comment by MTK4355** [comment]
I have a ton of issues with the path, and that's going to be my next focus once I get the walk settings bugs ironed out. 

As for the X1 vs X2, I think that may be a bug, but I like it. From a safety standpoint, this prevents accidentally teleporting if you have to quickly stop and re-start the bot... I would prefer to leave that as the intended behavior and just make it clearer that you should expect that behavior.

**Comment by RaZer0k** [comment]
about second bug report... yes that's what i'm talking about.... my start location is X ...the bot move me to X1... then this move my to X2 and then i close the bot. the LastCoords tell me i'm in X2 locations but when i start again the bot... this not start from X2... this start again from X location. (start location setted in GUI)

soo i think is because the LastCoords.txt data is not priority over Set GUI Locations.

**Comment by SscSPs** [comment]
that would not be a good idea  @RaZer0k , because it will likely make the GUI almost unusable.

**Comment by RaZer0k** [comment]
About Altitude y check the code and you ask to many times altitude... soo google api response "OVER_QUERY_LIMIT" so you have to change the timing of the call... only call for altitude when you press OK.

**Comment by SscSPs** [comment]
I was talking about disabling the GUI while catching a pokemon
because pokemons are being caught almost all the time. i catch about 2 pokemons every minute on an average. sometimes there are 9 pokemons nearby, so there's that!

**Comment by RaZer0k** [comment]
i get you @SscSPs but the bot try to simulate human behaviour... so you cannot catch a pokemon and evolve or powerup another pokemon in the same time.

**Comment by SscSPs** [comment]
I get you.
A better solution would be to start execution of transfer/evolve/powerup after the current nearby pokemons list reaches 0.

**Comment by MTK4355** [comment]
> About Altitude, i check the code and you ask to many times altitude... soo google api response "OVER_QUERY_LIMIT" so you have to change the timing of the call... only call for altitude when you press OK.

@Ar1i Are you using your own API key for this query? If so, I'll modify it to use the directions API key when provided to limit the hits on your api key.

**Comment by Fata1-3rr01z** [comment]
I just pause walking before I do manual transfer/evolve etc but an auto disable would be great
