### ISSUE TITLE
Is the bot safe to use?

### ISSUE THREAD

**Issue by ashenbrownfox** [Ar1i/PokemonGo-Bot#3527]
Been out of the loop lately. I heard Niantic was cracking down on bots. Even Ar1i's bot shut down their github for a while. Why bring it back now? Is the bot safe to use? Is it undetectable?

Is niantic being more lenient on botters recently or something?

**Comment by Hydro420** [comment]
No bot is safe to use - It breaks the Terms of Use. You can take certain precautions such as "running the bot smarter in settings." Nothing you do (while botting) can prevent you from a ban. Its a coin toss.
