### ISSUE TITLE
Exception Thrown When No Berries Available

### ISSUE THREAD

**Issue by HeIsNoOne** [Ar1i/PokemonGo-Bot#3529]
When the bot wants to use berry, but no berries available, an exception will be thrown.
![noberries](https://cloud.githubusercontent.com/assets/21832442/18196987/1ef481ea-70f5-11e6-8df3-9fffb4f0f197.PNG)

**Comment by SscSPs** [comment]
Does this happen every time? or was it just this once? Because for me, its generally happens randomly.
And which version are you using?

**Comment by HeIsNoOne** [comment]
This one is form 1.09 11.47 version.
I saw this only few times when I just started the bot.

**Comment by MTK4355** [comment]
@Ar1i @SscSPs Fixed in my latest Pull Request.
