### ISSUE TITLE
how to upgrade to the latest version?

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3530]
hey guys.. how to upgrade tp the latest version of bot? i have the old version which 1.0.0.9 if im not mistaken..i already download the latest one, but when i extract the file..nothing happen n the bot still load the older one.. can someone guide me on how to upgrade it.. (T_T)

**Comment by Nath789** [comment]
It's very easy tho.

1. Download the build you want here: [Builds Only](https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only)
2. Extract the contents of the RAR archive to the same folder where you run your bot.
3. Start the bot.
