### ISSUE TITLE
How to use telegrams/google maps routing ?

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3531]
All is said in the title. 
I don't know how to use it.

Thanks for helping

**Comment by Hydro420** [comment]
Its not done... Not an option to use it yet...

**Comment by SscSPs** [comment]
About telegram, it have been answered allready. 
Search BEFORE YOU POST.

**@caraoge commented 4 days ago • edited**
Create a account for telegram messenger using your phone, install the desktop application, go to https://core.telegram.org/api and start a new chat with "The Botfather" and create a new bot and a new token for it (Botfather will tell you what you've to do). Then you have to enter the generated api token in the first field and your username (without the @) you have chosen at the account setup in the second field.

**Comment by Zodice** [comment]
I have to create a bot for this ?

And for the google thing ?

**Comment by SscSPs** [comment]
that's not finished yet...

**Comment by MTK4355** [comment]
Still in bug fix mode from the last feature release, but Google Maps Routing is my next focus. If you want to get a head start, go get an API key here: https://developers.google.com/maps/documentation/directions/

**Comment by Zodice** [comment]
Ok i tried to use telegram but it's too complicated.

Thanks @MTK4355
