### ISSUE TITLE
my bot doesn't want take the pokeballs

### ISSUE THREAD

**Issue by santrale** [Ar1i/PokemonGo-Bot#3532]
my bot doesn't want take the pokeballs

screen : 
            1.  http://www.noelshack.com/2016-35-1472811794-1.png
            2.  http://www.noelshack.com/2016-35-1472811798-2.png
            3.  http://www.noelshack.com/2016-35-1472811801-3.png

**Comment by santrale** [comment]
up

**Comment by MTK4355** [comment]
This problem is intermittent, and many other users have reported it. We think it may be another form of softban, but not certain yet. Best advice is to wait a while and set the bot to not catch pokemon for a while once you resume botting.
