### ISSUE TITLE
Evolution time(suggestion not an issue)

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3533]
Evolve time is too much , you can trick niantic even on the app by using evolve then close the app and reopen it which take in sum about 10-20s  and its acceptable . (i got 37sec evolution time ;p roflcopters )

**Comment by Hydro420** [comment]
Thats just a nuisance.. Id rather wait then keep closing and opening the app, doesn't always load as fast as you may think.

**Comment by k0ut4li4n0s** [comment]
Yes but if you want maximum time for the lucky egg thats an option i tried

**Comment by fetmamm** [comment]
use an old version of the bot if you want to evolve faster..

**Comment by SscSPs** [comment]
the option for changing/removing the time delay will be implemented soon. With  a USE AT YOUR OWN RISK warning

**Comment by k0ut4li4n0s** [comment]
@fetmamm well the old versions do it in 1sec thats too fast
A normal evolve on app take 17-20 sec to watch full evo so i think 31+ is a bit much

**Comment by MTK4355** [comment]
I recorded myself doing it in the app, and that was the average time it took to open a pokemon, select evolve, watch the effing animation, select next pokemon.
