### ISSUE TITLE
Pokemon Transfer

### ISSUE THREAD

**Issue by ImTooDry** [Ar1i/PokemonGo-Bot#3534]
It doesn't transfer some of my duplicate pokemons even though I check transfer duplicates and change the maximum duplicates to one, the maximum IV, and CP to transfer.

**Comment by Hydro420** [comment]
Bot  does it automatically every so often. Transfers all when first booting up the bot before farming.

**Comment by maskime31** [comment]
Don't you have the "keep pokemons which can be evolved" box checked ?

**Comment by SscSPs** [comment]
either what @maskime said, or you may have it in NOT TO TRANSFER list

**Comment by Zodice** [comment]
What is your maximum numbers of duplicate pokemons ?
