### ISSUE TITLE
New walk settings tab or features are not working, settings will not save upon starting bot.

### ISSUE THREAD

**Issue by deadelf0** [Ar1i/PokemonGo-Bot#3542]
Tried wiping config files, with no luck.

**Comment by Theseppinator** [comment]
True!&

**Comment by SscSPs** [comment]
that's a known bug

**Comment by Hydro420** [comment]
Known issue - not too big either (takes only seconds to type the info in again). Too tedious of a fix(as stated) for something not that big of a deal.. Chill and it will be fixed in due time.

**Comment by MTK4355** [comment]
Well, it's not really THAT hard to fix but it's boring and I'm lazy. lol. 

I'll get around to it when the google directions routing is done, unless someone else gets to it before me.

**Comment by Hydro420** [comment]
Google first :-D FTW! lol

**Comment by deadelf0** [comment]
What's the work around? None of the walk settings turn on at all.

**Comment by MTK4355** [comment]
Are you setting a "Time to Run" value? I just found that my logic for breaks, catch/farm limits is inside a loop that checks for a time to run... Fixed in my latest pull, but it's not merged or built yet.

**Comment by MTK4355** [comment]
Also, the disable farming pokestops checkbox was completely disconnected. Will be fixed with the next build!

**Comment by deadelf0** [comment]
Everything is working now, awesome!! Yo

**Comment by MTK4355** [comment]
Thanks to @Ar1i for fixing the config data saving.. Please close the issue if you have confirmed it's fixed! ;)
