### ISSUE TITLE
Get back Force Unban

### ISSUE THREAD

**Issue by qokemon** [Ar1i/PokemonGo-Bot#3544]
I use an old version of your bot with Force unban, And it works. You just have to press ForceUnban right after you loaded the bot in. then it should work. I dunno but this works for me.

**Comment by MTK4355** [comment]
Why would it work when first loading the app and no other time? It runs the same code either way..

**Comment by abhi290** [comment]
YES the bot version 1.1.0.4 successfully unbans. Then why cant the new bots unban.

**Comment by MTK4355** [comment]
I'll run some tests, anybody know a sure-fire way to obtain a soft ban? :) I'm really good at getting perma-bans, but haven't hit a soft ban in a while.

**Comment by abhi290** [comment]
yup.
change ur location from one continent to another or from one part of country to the other.
Ull be soft banned

**Comment by edale2** [comment]
catch more than 1000 pokemon, or farm more than 2000 pokestops, in a 23 hour time period. both get different softbans.

**Comment by SscSPs** [comment]
those soft bans can not be undone without time @edale2

**Comment by Kidnub** [comment]
I hade 3 softbans and as qokemon say the softban is still arround and you can still unban with the old version he is on that point right ... ( i had hade the problem and it is still working but the best meth. to be sure of 100% unban on a softban is Ip change and unban 1337 .. XD)
@MTK4355 and MTK4355 could pls you give  us any idea about the new exception error after the new build(02.09.****) (issue 3541) thx also if i still use the version from 31.08. you all in the Dev team are doing a greate job ...

**Comment by Logxn** [comment]
Guys the 40 Pokestop spinning unban does not work anymore.

@MTK4355 I would test it myself but im in italy. There is a new method. But it requieres 100 Pokeballs that need to be miss after throwing

**Comment by AndrewTanST** [comment]
I said before older version soft unban is working, but some just don't believe.

Go try the older version 1.1.0.3 and then you will know the soft unban is work. 
For phone apps itself, some said spin 40+ times not working but mine is still working perfectly include the time I am posting this comment now.

The soft unban only stop working after this project being bring back after sometimes it is silent and remove.

**Comment by Logxn** [comment]
Since I am still in Italy until tomorrow I quickly softbanned me via GPSFaking.
I spinned a pokestop near me 64 times and its still not working.

**Comment by AndrewTanST** [comment]
Just update, yesterday I just route to San Fransisco and spin 40+ times is still working and able to unbanned soft banned.
