### ISSUE TITLE
Traduction française

### ISSUE THREAD

**Issue by DJClement50** [Ar1i/PokemonGo-Bot#3546]
I translated the French version of the bot

[france.txt](https://github.com/Ar1i/PokemonGo-Bot/files/452989/france.txt)

**Comment by Zodice** [comment]
The translation has already been corrected on the topic that is dedicated to, they just have to pute it in the game.

**Comment by DJClement50** [comment]
compared to the latest version was not entirely his

**Comment by Zodice** [comment]
Un autre joueur et moi-même avons corrigé et améliorer les traductions pour les rendre plus faciles à comprendre. Ils n'ont juste pas encore implanté la traduction dans le jeu.

https://github.com/Ar1i/PokemonGo-Bot/pull/3358

**Comment by DJClement50** [comment]
ah ok

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Sat, Sep 3, 2016 at 10:38 AM +0200, "Zodice" <notifications@github.com<mailto:notifications@github.com>> wrote:


Un autre joueur et moi-même avons corrigé et améliorer les traductions pour les rendre plus faciles à comprendre. Ils n'ont juste pas encore implanté la traduction dans le jeu.

#3358<https://github.com/Ar1i/PokemonGo-Bot/pull/3358>

-
