### ISSUE TITLE
New french translation by SnxArste10.

### ISSUE THREAD

**Issue by SnxArste10** [Ar1i/PokemonGo-Bot#3548]
Hi, I corrected the old translation which had many errors. Thanks for your job, you guys are awesome.
[French Trad Ar1Bot.txt](https://github.com/Ar1i/PokemonGo-Bot/files/453090/French.Trad.Ar1Bot.txt)

**Comment by Logxn** [comment]
create a pull request

**Comment by Zodice** [comment]
The translation has already been corrected on the topic that is dedicated to, they just have to pute it in the game.
