### ISSUE TITLE
FULL-PowerUp: "Pokemon not powered up. Not Enough Stardust or Candy."

### ISSUE THREAD

**Issue by Nath789** [Ar1i/PokemonGo-Bot#3550]
Even with sufficient stardust and candies, this doesn't seem working well (build 2.09 20.31).
![screenshot](https://cloud.githubusercontent.com/assets/5668486/18223293/655f2c20-71e5-11e6-927c-d6e2a9db2ede.PNG)

**Comment by SscSPs** [comment]
You need to enter a certain powerup number in the text box above it

**Comment by Nath789** [comment]
Ay, it's no longer like it'll power up the pokemon up to where the stardust and candies can manage. Didn't noticed it.

**Comment by MTK4355** [comment]
That's a bug. If no value is entered, it should power up until out of stardust or candy.

No need to reopen the issue though. I'll add a fix to my open pull.
