### ISSUE TITLE
Tip optimize incubation

### ISSUE THREAD

**Issue by javiermartinalonso** [Ar1i/PokemonGo-Bot#3553]
To choose small eggs hatching 2 or 5 km first. thus more eggs hatch in less time and therefore the chances of getting eggs 10km in pokestops increase.

On the other hand, to reserve the option of using only the basic incubator for the previous option and book incubators three uses only eggs for 10 km.

thanks for the great work you are doing

**Comment by MTK4355** [comment]
Good idea. @Ar1i please keep this open, as I want to do this at some point. Too many bugs to fix before I take on anything new and I don't want to forget!
