### ISSUE TITLE
Dont want to farm pokestops, but the bot does it anyways

### ISSUE THREAD

**Issue by fetmamm** [Ar1i/PokemonGo-Bot#3554]
Hello.
I have unchecked the box so the bot dont farm pokestops, but it does not work.. It farm pokestops anyway
![egg](https://cloud.githubusercontent.com/assets/21282959/18223909/d75d7f22-71c5-11e6-9948-0ab3c4090f56.png)
![pss](https://cloud.githubusercontent.com/assets/21282959/18223908/d75cfe26-71c5-11e6-8196-f41f93e3577b.png)
I have tried to just unckeck the box without typing anything in the max pokestop farm column but it still farms pokestops

**Comment by MTK4355** [comment]
I think I mixed up some of the checkboxes at some point. I'll be going through and cleaning that up next when I add the new fields to the config so your selected values will persist after closing and re-opening the bot.

**Comment by MTK4355** [comment]
Sure enough, I had disconnected this option from the logic. Sorry! Will work right in the next build.
