### ISSUE TITLE
Power up limit bug go unlimited xD

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3557]
I set power up limit 30 and it go till 1500 xD . I took the ss earlier
![12345](https://cloud.githubusercontent.com/assets/21258333/18224354/f35fb752-71da-11e6-9634-636e8dce75ac.png)

**Comment by ramigora** [comment]
i haven't seen a single dragonite...

**Comment by PokePro21** [comment]
I think its showing CP of pokemon

**Comment by Ar1i** [comment]
Should be fixed

**Comment by k0ut4li4n0s** [comment]
@ramigora lolz
 @Ar1i gonna check it asap thnx

**Comment by k0ut4li4n0s** [comment]
@Ar1i  nop it still happens,

**Comment by MTK4355** [comment]
Weird. It worked in my testing last night... I'll see if something was excluded before my last commit. I was really tired. Could have hosed something...

**Comment by edale2** [comment]
only problem I've seen so far is I selected 3 pokemon, set it to 8 levels, and it only leveled 1 pokemon 3 levels, just been doing them individually since and had no problems.

**Comment by edale2** [comment]
Just got a closer look at your screenshot.

Assuming your Dragonite was lvl 1 before, it worked properly. Levels are incremented by 0.5, so gaining 30 levels will only report as gaining 15.

Also keep in mind this isn't a"level to this level" counter, it's a "level this many times" counter. So if you set to level 5 times, and you're level 10, you'll be level 12.5 when it's done.

**Comment by k0ut4li4n0s** [comment]
@edale2 that was happening when i set it on x2 or x4 too it wasnt because i set it too high
