### ISSUE TITLE
Bot restart

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3558]
Hi,

i have a problem really often with the bot, he is saying this : 

![sans titre](https://cloud.githubusercontent.com/assets/20968987/18224853/06292752-71e4-11e6-8ab6-37cc73ab1828.png)

May someone make something for this ?

Thank you.

**Comment by Nath789** [comment]
I also get the same error as above sometimes. What's weird is the error shows a different filepath from ours, lol.

**Comment by MoMGeek** [comment]
I periodically get this as well

**Comment by MTK4355** [comment]
If you have ever used the pokefarmer bot, it does this as well. (but it doesn't restart on it's own) I think the session authentication expires every 30 minutes or so, and the bot has to authenticate again.

**Comment by Zodice** [comment]
But the problem is that when the bot restart, the move radius move, so sometimes it can put you in a place with not enough pokestop for farming.

**Comment by MTK4355** [comment]
Good feedback @Zodice I'll see what I can do about that.
