### ISSUE TITLE
Full-powerup

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3559]
Hi,

if you don't put a limit to the full-powerup, it will says that you don't have enough candy/stardust, instead of just powerup the pokemon at his maximum.

Thank you for reading.

**Comment by k0ut4li4n0s** [comment]
ye happened to me too, forgot to mention on #3557

**Comment by Zodice** [comment]
Where do you find so much dratini ?

**Comment by edale2** [comment]
Try Lat:43.64028065169827, Lng:-79.37606647610664

It's a nice spot right by the waterside in Toronto that usually has 6-7 lures active.

I usually catch dratinis around 12-2 AM/PM (both) EST (don;t check bot often enough to narrow it down more). I'll typically get 4-6 dratini a day.

Other spots: http://techdrake.com/2016/08/best-coordinates-bot-pokemon-go/

**Comment by Austin333** [comment]
I got plenty at pier 39 Los angeles. 800+ candies in 10 days running 8 hours a day, sometimes up to 12 hours.
