### ISSUE TITLE
Still have with the new updatet this error

### ISSUE THREAD

**Issue by Kidnub** [Ar1i/PokemonGo-Bot#3560]
[https://github.com/Ar1i/PokemonGo-Bot/issues/3541](url) even with the new build it is happen to me ;(

**Comment by Zodice** [comment]
What ?

**Comment by Kidnub** [comment]
i still get this error all time if i do updatet the bot XD .. so i am only able to use the version from 01.09
the updates give me always the same Exception error like i post on issue#3541.

**Comment by Zodice** [comment]
But the first link is dead so i can't see what is your issue.
What is your version of windows ?

**Comment by Kidnub** [comment]
http://www2.pic-upload.de/img/31612566/Unbenannt4.jpg 

error text from button detail idid post on the old issue and no the link is not death 
 https://github.com/Ar1i/PokemonGo-Bot/issues/3541
and no it s a bug from the comment box here XD the links are all working XD just copy paste them XD

**Comment by Kidnub** [comment]
Lang change does not solve my error ;( the version of 01.09.11.47.... can i do any to help to get fixed this error ? @MTK4355

**Comment by Kidnub** [comment]
thx thx i am too dumb sry my fault .. thx for he Bouncing behind the check box (lol uncheck german names all is fine sry sry sry i was to high from weed yesterday) CLOSES !!!!!!!!!!!!!!!!!!!!!!!!!
AWESOME WORK DEV TEAM XD (LOGEN/MTK4355/Arli)
