### ISSUE TITLE
German Pokemonname do not work dince Update

### ISSUE THREAD

**Issue by PrOCheaTer** [Ar1i/PokemonGo-Bot#3561]
As the Title says, since 2 Updates the German Pokemonname do not work for me, if i press German Pokemonnames, the Bot do not start and crash. On old Versions working fine.

**Comment by MTK4355** [comment]
On old version the pokemon images do not show up right? I think the pokemon ID's or names changed at some point and the translations have to be re-linked.

**Comment by Viper2k4** [comment]
If u uncheck ALL Pokemon and the "Pokemon"-Tab it work agains. Problem ist the Liste of the Pokemon is still english. And the Bot try to find the Pokemon in the german list and got a "KeyNotFoundException".

Here:

https://github.com/Ar1i/PokemonGo-Bot/blob/master/PokemonGo.RocketAPI.Console/GUI.cs#L708

Here:

https://github.com/Ar1i/PokemonGo-Bot/blob/master/PokemonGo.RocketAPI.Console/GUI.cs#L715

and here:

https://github.com/Ar1i/PokemonGo-Bot/blob/master/PokemonGo.RocketAPI.Console/GUI.cs#L722

**Comment by MTK4355** [comment]
Yeah, I know... None of the new settings I added get stored yet, and I broke some that were working previously. I'm trying to make myself go fix it all but it's just such boring work....... I keep procrastinating.

**Comment by Logxn** [comment]
@MTK4355 dont worry you will get my help tomorrow :)

**Comment by Ar1i** [comment]
@MTK4355 look at skype tho :p
