### ISSUE TITLE
Not issue,just question.

### ISSUE THREAD

**Issue by Jeremy2131** [Ar1i/PokemonGo-Bot#3563]
How i can use commands in telegram bot?
I take my api token and console say me 'u can use bot for info' how?

**Comment by PrOCheaTer** [comment]
[https://www.youtube.com/results?search_query=telegram+bot+pokemon+go](url)

**Comment by Zodice** [comment]
@PrOCheaTer your link is dead

**Comment by Jeremy2131** [comment]
@Zodice just copy CTRL+C and paste

**Comment by Jeremy2131** [comment]
@Zodice dont click

**Comment by Jeremy2131** [comment]
@PrOCheaTer ty dude.

**Comment by dieter90210** [comment]
I'm trying to use the bot but it will only reply to me an image telling "You have no power here"
