### ISSUE TITLE
Possible to add IPhone? 

### ISSUE THREAD

**Issue by MoMGeek** [Ar1i/PokemonGo-Bot#3565]
Non issue, question.  Is there a way to add IPhone to the list of available smartphones to use?  (if there is a reason that it's not, pls excuse my coding noobness).

**Comment by Jeremy2131** [comment]
@MoMGeek why do u need that?

**Comment by MoMGeek** [comment]
I also play on IPhone.  Would it be more "human" to log into the same phone?  or does that not matter much?

**Comment by Gin520** [comment]
possible to add Sony Xperia Z5?

**Comment by Jeremy2131** [comment]
@MoMGeek it does not matter what your device,this ban is not present

**Comment by MoMGeek** [comment]
It lists many different devices to choose from so I wondered if it would be better to choose the one I use in the real world.  If it doesn't matter then thank you.

**Comment by PrOCheaTer** [comment]
@Jeremy2131 aha...

@MoMGeek yeah i can add for you your Phone, if you have Skype send me your Contact...
