### ISSUE TITLE
Google routing question?

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3566]
Does google API key is mandatory if want to use google routing?

**Comment by Jeremy2131** [comment]
@nasierache yep

**Comment by nasierache** [comment]
@Jeremy2131 once i key in the google API key...the pokestop flag is missing..and plus the bot seems do not follow the road path..is this normal?

**Comment by Jeremy2131** [comment]
@nasierache bot go as real human,and that normal :D

**Comment by nasierache** [comment]
noted...hahaha

**Comment by MTK4355** [comment]
Pokestop flag is only missing because you waited too long to open the map. They will show up eventually. Are you seeing directions in the log?
