### ISSUE TITLE
last pokemon catch

### ISSUE THREAD

**Issue by Shoier** [Ar1i/PokemonGo-Bot#3572]
Can you add funct. how is in app Pokemon Go. last cstch pokemon in Pokrmon list. its means that we can whats pokemon bot catch for 2 hours.

**Comment by MTK4355** [comment]
I usually just paste the log into notepad++ and do a find all on "Caught" I suppose this makes a decent wishlist item, but I don't see it being very high on the todo list unless there are a bunch of you out there who would find it useful.

**Comment by Shoier** [comment]
Hmm i understand but myybe you can do it :)

**Comment by Logxn** [comment]
Added :)
