### ISSUE TITLE
how can I force throw different pokeballs?

### ISSUE THREAD

**Issue by abba09060906** [Ar1i/PokemonGo-Bot#3574]
thanks for this great program.
I have a question abbout how can i config different pokemon using different pokeball to cache.
can you add this function?

thanks

**Comment by MTK4355** [comment]
How do you imagine this would be configured, from a UI perspective? I can't think of a way to do it that wouldn't be a ridiculous amount of work.

**Comment by Logxn** [comment]
Well we could do checkboxes "Prefer Masterballs" - then it would only throw masterballs.
But to always choose what ball should be thrown is pointless
