### ISSUE TITLE
just a small spelling issue

### ISSUE THREAD

**Issue by toxic189090** [Ar1i/PokemonGo-Bot#3575]
sorry for pointing this out because it so small

Love the program thanks to all the contributes

![7645b391375836c709fe036039f8bed3](https://cloud.githubusercontent.com/assets/21367666/18228267/5f549322-7214-11e6-8755-a8fe6df768d2.png)

the login is spelt wrong

**Comment by eengg** [comment]
@toxic189090 its not login, but logan
https://twitter.com/LoganPunkt
https://github.com/Logxn

**Comment by AiVo7z** [comment]
yea it's that dudes Name. ist no button to log in to twitter or something :P

**Comment by Logxn** [comment]
Thats my name hehehehe
