### ISSUE TITLE
Throw berry bug?

### ISSUE THREAD

**Issue by zyxelgg** [Ar1i/PokemonGo-Bot#3578]
![ff](https://cloud.githubusercontent.com/assets/20980801/18228610/dcf6cf74-7288-11e6-884e-fb9f110fdf99.jpg)

I set the throw berry is 35%, why bot throw?

**Comment by MTK4355** [comment]
Because the pokemon escaped on the first throw without a berry.

If a pokemon escapes, a berry is thrown (if using berries is enabled) 
If a berry has already been thrown and pokemon escapes it will use the next best ball.

**Comment by Logxn** [comment]
^
