### ISSUE TITLE
Max CP to transfer/Max IV to transfer

### ISSUE THREAD

**Issue by ColdF0rest** [Ar1i/PokemonGo-Bot#358]
Hi !
Can anyone explain what these features do? 

Max CP to transfer : If I set it to 50 does it mean that every Pokemon under 50 will be transfered?

Max IV to transfer : I´ve got no idea what this is supposed to mean.What does IV stand for/mean?

An english explanation is fine but if you speak german I would absolutely appreciate a german explanation :)

**Comment by duyphuc1610** [comment]
IV means if your pokemon is strong or weak, you can check your pokemon in the link below by insert CP, health, Stardust requirement, if they are 90% mean that pokemon is strong. Otherwise just transfer :)
[https://pokeassistant.com/main/ivcalculator](url)

**Comment by TMaddox** [comment]
max cp: if a pokemon has bigger cp then the max value it wont be transferred
max iv : IV... individual value, an average stats value, you can test your IV at https://thesilphroad.com/research and maby watch this vid: https://www.youtube.com/watch?v=-l5bu2444DM (the guy is a bit enthusiastic but he has a pretty good way of explaining things)

now in german:

max cp: wenn ein pokemon mehr cp hat als dieser wert wird es ned verschickt
max iv: durchschnittlicher stats wert, hier kann man ein pokemon testen:https://thesilphroad.com/research und guck dir das video an https://www.youtube.com/watch?v=-l5bu2444DM (gute erklährung)

**Comment by ColdF0rest** [comment]
Alright thank you very much guys!
