### ISSUE TITLE
Pokestops not turning color after collecting since last update.

### ISSUE THREAD

**Issue by MoMGeek** [Ar1i/PokemonGo-Bot#3582]
After completing, it says that it has to wait because there are no pokestops left to farm.  But there are....
![pokestopsaren tturningblue](https://cloud.githubusercontent.com/assets/21235754/18229509/95cafd9c-7241-11e6-83f6-45bea62f053a.GIF)

**Comment by MTK4355** [comment]
I broke the color change and pokestop data update trying to fix another issue where the poekstops would not load unless you opened the map right away.. Sorry, I'll get it right soon.

**Comment by Xelwon** [comment]
Why the pokestop colors are just the contrary of the pokemon go?

**Comment by Logxn** [comment]
Fixed
