### ISSUE TITLE
Not an Issue, only a question:D Sort Pokemons By numbers possible?

### ISSUE THREAD

**Issue by M31860** [Ar1i/PokemonGo-Bot#3584]
Is there any way to do this? @MTK4355 
#2861

**Comment by Xelwon** [comment]
Yes, I would like to sort by number of pokedesk, too.
You can view pokemons and his evolutions together.

**Comment by MTK4355** [comment]
Should be pretty easy, I'll look.

**Comment by M31860** [comment]
@MTK4355 
Thank you:)

**Comment by Xelwon** [comment]
I've done it in this pull request.

https://github.com/Ar1i/PokemonGo-Bot/pull/3630

**Comment by M31860** [comment]
Thank you very very much @Xelwon
