### ISSUE TITLE
Maps Routing dosnt work

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#3585]
![1](https://cloud.githubusercontent.com/assets/20892427/18229870/2d9bd758-7289-11e6-929e-53c322002274.jpg)

**Comment by Xelwon** [comment]
Hi Tr1n0va, or anyother reader, I've created a google maps directios API key.
But I dont know how can I create a route and pass it to the bot.
Is there any documetation in anywhere about it?
I'm using google to search it but I don't find anything. :'(

**Comment by MTK4355** [comment]
You can't create a route at the moment. The bot uses google routing to get directions between pokestops. I'm working on user configurable routing but it's not ready.

**Comment by Xelwon** [comment]
:O, fanstastic mtk4355.
Knowing it, is perferc for me. My idea was make a route to don`t cross building, river an sea :D,
If bot do it for me only putting google api key is perfect :D.
Great job. 
I will try it now. :D.

**Comment by Tr1n0va** [comment]
but the routing dont work @MTK4355 the bot always walk the straigt way to next target?!?

**Comment by Logxn** [comment]
![pokemongo rocketapi console vshost_2016-09-05_10-01-31](https://cloud.githubusercontent.com/assets/20424274/18241120/d553343e-734f-11e6-9230-399cc94603aa.png)

Seems to work for me

**Comment by SscSPs** [comment]
Thats what he said, bot goes from pokestops to pokestops in a straight line, instead of from roads.

**Comment by Logxn** [comment]
my bad

**Comment by MTK4355** [comment]
The bot only does that when there is not a good path from google maps. Some areas do not get good directions, and sometimes the directions do not take us all the way to the pokestop. In those cases the old style of navigation takes over to make sure the bot doesn't blow up, or try to farm a pokestop that is too far away. 

If the bot follows the general path of the roads, but is a little off, the same goal is accomplished. Not all geocoding is perfect in the real world either. Still helps prevent seeming to teleport between stops. 

Looks like it is working in the above screen shots to me. (both traveled paths seem to roughly line up with the nearby roads) What does the log look like? Do you see the turn by turn directions being written? 

![image](https://cloud.githubusercontent.com/assets/11677019/18254117/3ea90872-7360-11e6-8f37-9681522b66b4.png)

**Comment by Logxn** [comment]
I dont

**Comment by MTK4355** [comment]
Then something is not working right.. Look through my commit history and try my API key. 

It's been working flawlessly for me so I am not sure how to help.

**Comment by Tr1n0va** [comment]
That dosnt work, i dont no why. i got an API Key and BOT says that its ok, but dont get a route.

**Comment by Tr1n0va** [comment]
> Look through my commit history and try my API key

I did, dont work for me too

**Comment by MTK4355** [comment]
What location are you using? I'll see if I can reproduce the issue where you are farming. The teleport may give me a reason to test unbanning a softban too. lol.

**Comment by Tr1n0va** [comment]
I used it in Berlin, Germany (52.5185842591136 - 13.4046292304993) in Hamburg, Germany (53.5571358601059 - 10.0167846679688)and also in Detmold Germany (51.9362749966297 - 8.87781143188477).
And some oter places...

THX

**Comment by MTK4355** [comment]
Thanks, I'll test your location later today and report back. 

Even in my latest farming spot where there aren't really any defined roads, I still get some directions logged. 

![image](https://cloud.githubusercontent.com/assets/11677019/18276349/34377774-7410-11e6-8364-bf68e05a21bb.png)
![image](https://cloud.githubusercontent.com/assets/11677019/18276388/5e281782-7410-11e6-9603-4036e0430bb3.png)

**Comment by Gummibal** [comment]
I still do not understand how to assign a route to bot. Can anyone tell me where to find the? Sorry for my English in form Germany

**Comment by MTK4355** [comment]
Instructions are here #3700

**Comment by MTK4355** [comment]
BTW, on the topic of this issue I have identified the cause of the problem with routing in Germany and I am working on a fix.

**Comment by Gummibal** [comment]
when I create a route on the map then is yet not
saved. And generale I meant how to adjust the Google Maps api route so that I stretch can insert again. Sorry for my English i am from germany

**Comment by MTK4355** [comment]
Not sure I understand. Ask the question in German and I'll have a human translate it for me if Google screws it up.

**Comment by Gummibal** [comment]
Ok. Meine eigentliche frage ist wie das mit der Google Maps API funktioniert. Wenn man Den API Key dort einfügt muss man ja auch irgendwie die route einstellen können wo er lang geht. In ihrer Erklärung steht nur drin wie man die Route mit der Karte erstellt. Diese Route bleibt meines Wissens nach nicht gespeichert. Deshalb habe ich auch gefragt gehabt wie man das mit der Google Maps Api macht damit ich die route nicht immer neu machen muss.

**Comment by Gummibal** [comment]
nice now does the Google Maps Api function. But still I do not understand what it entails. Auf Deutsch: nice jetzt funktioniert die Google Maps Api Funktion. Doch noch immer verstehe ich nicht was sie bringt.

**Comment by MTK4355** [comment]
Das ist noch nicht implementiert , aber ich bin auf einem Weg, um die Route, die Sie durch einen Klick erstellen zu speichern.

**Comment by Gummibal** [comment]
Now I understand what Google Maps API brings ever. Forget my old posts I have it all the time misunderstood. I thought man can with Google Maps API to create your own route and then in the bot embed so that the bot no longer Pokestop to Pokestop runs special stop stretch that you have created yourself. In German: jetzt habe ich verstanden was Google Maps API überhaupt bringt. Vergesst meine alten beiträge ich habe es ganze zeit falsch verstanden. Ich dachte mann kann mit Google Maps API sich eine eigene Route erstellen und diese dann in den bot einbinden so das der bot nicht mehr von Pokestop zu Pokestop läuft sonder halt strecken die man selbst erstellt hat.

**Comment by Tr1n0va** [comment]
@MTK4355 
It seems to work now for me, the first time.
at the moment i farme at munich, Germany and it works great!!!

THX

**Comment by Tr1n0va** [comment]
![screenshot 2016-09-09 09 12 54](https://cloud.githubusercontent.com/assets/20892427/18378528/d9aaa2e4-766d-11e6-8420-ef7e2323baa6.jpg)
