### ISSUE TITLE
Lates build forces break

### ISSUE THREAD

**Issue by jmo93** [Ar1i/PokemonGo-Bot#3586]
![screenshot 30](https://cloud.githubusercontent.com/assets/20781018/18230496/449905b6-729d-11e6-852b-c96dd1ff781e.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/20781018/18230497/47939790-729d-11e6-95f3-885bb0c6ffd4.png)

**Comment by Kidnub** [comment]
problem ? cause it count the time down  ? or what  ?

**Comment by jmo93** [comment]
yes, it shows " remaining time until break..."

**Comment by Kidnub** [comment]
and the problem ?

**Comment by AiVo7z** [comment]
That he didn't put in a number or enabled that the bot should to a break maybe? read the title. The bot Forces to break even tho you didn't enable.

**Comment by jmo93** [comment]
thank you @AiVo7z

**Comment by MTK4355** [comment]
Nah, that's a bug! Did you have a value in the break field before, then delete it and start the bot? (or some such thing)

**Comment by jmo93** [comment]
Settings like in the Screenshot, every start same bug

**Comment by AiVo7z** [comment]
He meant if you ever tried that brake and therefore put something in (so it may wrote in your config even tho it's blank, its still there). If that's the case, download a fresh copy and leave it untouched, or simply put in a high number you won't reach? i.e. 200000 mins (or if you don't bot all day Long you could put in something like 900whichs equals 15 hours.

**Comment by MTK4355** [comment]
Or try clearing the field and pressing tab, that should positively overwrite any value with an empty string.

**Comment by MTK4355** [comment]
This issue should be fixed in the latest build. Please confirm and report or close the issue.

**Comment by Logxn** [comment]
@MTK4355 
Put it to 1
Removed the 1

Now it says: Break in 0 Minutes
Goes to the next pokestop and chills there for 10mins

**Comment by Logxn** [comment]
Fun fact: if you restart the bot its at 50mins again ??

**Comment by jmo93** [comment]
<img width="470" alt="screenshot 35" src="https://cloud.githubusercontent.com/assets/20781018/18242966/177e9b60-7359-11e6-8087-65c825b1ea8d.png">
<img width="698" alt="screenshot 36" src="https://cloud.githubusercontent.com/assets/20781018/18242970/1b2fba0a-7359-11e6-8dbf-2be9b022ad57.png">

**Comment by Logxn** [comment]
yeah thats what I ment.
But if you restart the bot its at 50mins again :D

**Comment by MTK4355** [comment]
Oh weird. I'll get it fixed asap. Family stuff going on today, but I'll try to get it done.

**Comment by MTK4355** [comment]
Added a toggle to use break times (or not) for now.. I'll take a closer look at everything later when I have more time.
