### ISSUE TITLE
Latest build: pokestop are not marked blue after farm

### ISSUE THREAD

**Issue by jmo93** [Ar1i/PokemonGo-Bot#3587]
![screenshot 32](https://cloud.githubusercontent.com/assets/20781018/18230511/b75dd20c-729d-11e6-8767-f62e9cc94509.png)

**Comment by Kidnub** [comment]
they are market in milli second they are used XD need to watch carefully XD and he is on (https://github.com/Ar1i/PokemonGo-Bot/issues/3582)pls stop create double issues ;(
