### ISSUE TITLE
[IDEA] Presentation

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3590]
Hi,

i thought that it could be very nice if the tw.o windows (bot + pokemon GUI) was one big window. It could be more easy to use

And i thought too that if the bot was just an application (like google chrome or windows excel) it could be more easy : instead of open a folder, open a second and click to open the bot, you just have to double click on an icon and the bot is opening.
That could help with the new version, because at each new version we lose all the bot's settings, we delete the older bot etc, with my idea it could just make a little upgrade.

Say what you think about it,
thank you for reading.

**Comment by AiVo7z** [comment]
I use the bot on a small netbook 10" Screen and 1 big Screen wouldn't be cool, except they'd make it an Option to enable instead of forcing ús to use it then. My 2 Cents,

**Comment by Zodice** [comment]
In my idea the size of the windows could be changed as you want.

**Comment by AiVo7z** [comment]
if it pops up too big I can't Change the size they easy. Enabling this by Settings (like clicking farm pokestops/evolve, use lucky egg) would Bypass this Problem. More important bugs to fix atm tbh.

**Comment by Logxn** [comment]
Thats not a good idea.
We would need to generate more Windows and elements.

a) Thats not good to do
b) People with small screens are fucked if they have too many bots
