### ISSUE TITLE
Taking a break doesn't work well

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3591]
I enabled that the bot should take a break i.e. every 35 minutes and should rest ONLY 2 minutes. I didn't enable that it should wait and farm pokestops boosted with Cards. Still the bot takes breaks up to 15-20 minutes. I also get the error "pokestop not rdy to farm again blabla" the same second it actually spinned the pokestop. It then takes a couple minutes again until it starts to run. I enabled random pauses but I think still Needs a Little Attention, only happens since the newest update.  Build 4.09 0.36 the previous Version 3.09 14.31 worked better imo. (same Settings)

**Comment by Kidnub** [comment]
watch if you have the checkbox on break on lure ... if yes that is it why he stops their and is their until the troydisk ends XD

**Comment by AiVo7z** [comment]
Learn to read I didn't enable it.  First brake after 35min was 18min, 2nd was as promised 2 minutes 3rd brake was from 15:53:43 to 16:00:22 it even says "break over, back to Walking! this is obviously a bug which makes the bot wait longer than it should, in my example 2 mins. If I checked farm lurecards or w/e, it wouldn't do that after 35 minutes, it does countdown till break and then breaktime jumps crazy around.

**Comment by MTK4355** [comment]
Yep. I can confirm strange behavior. Still ironing out the logic there. It works better with 5min or longer breaks.

**Comment by AiVo7z** [comment]
Ah okay but you try to fix ? I'd rather take a lot short breaks . I tried this Feature. I think bot's still so obvious it doesn't matter.

**Comment by MTK4355** [comment]
The bot already does that, we just don't emit the actual variable to the logs.

**Comment by MTK4355** [comment]
My last pull request should make short breaks work better. Seems good to me. Try again next build and let me know if it still has issues.

**Comment by AiVo7z** [comment]
okay thanks, awesome work.
