### ISSUE TITLE
does someone know a good location for dratini? really need it :) Thx

### ISSUE THREAD

**Issue by NikiMon** [Ar1i/PokemonGo-Bot#3592]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by PokePro21** [comment]
Santa Monica Pier 39

**Comment by AiVo7z** [comment]
All my accounts got perm banned pretty fast farming there (used Proxy) so rather find a place near your Location, try to aim Locations having water around, somehow it only spawned there for me. (diffrent Location, everytime water was near)

**Comment by PokePro21** [comment]
PIER 39, San Francisco, CA, United States

**Comment by ramigora** [comment]
what about dragonite

**Comment by SscSPs** [comment]
i have found 4 dragonites in Sydney at different locations, but yeah, Sydney
