### ISSUE TITLE
Location map suddenly broke down

### ISSUE THREAD

**Issue by jmo93** [Ar1i/PokemonGo-Bot#3593]
![screenshot 34](https://cloud.githubusercontent.com/assets/20781018/18231216/eca0b32a-72b2-11e6-9b05-8a6eaf693426.png)

**Comment by Siufay1** [comment]
i got the same message when i used the function "Walk in Archimedean Spiral".

**Comment by jmo93** [comment]
I didnt use this function

**Comment by scornos** [comment]
same problem here using archimedean walk. Crashes a few second after i open map

**Comment by Logxn** [comment]
@MTK4355

**Comment by MTK4355** [comment]
English translation of error?

**Comment by Logxn** [comment]
@MTK4355 

better you fix that, cuz you wrote it and I dont want to fuck anything up.
Translation:

System.InvalidOperationException: the listing was changed. The enumeration operation may not be executed.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at GMap.NET.WindowsForms.GMapOverlay.OnRender(Graphics g)
   at GMap.NET.WindowsForms.GMapControl.OnPaintOverlays(Graphics g)
   at GMap.NET.WindowsForms.GMapControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly-Version: 1.1.1.7.
    Win32-Version: 1.1.1.7.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/PokemonGo.RocketAPI.Console.exe.
----------------------------------------
POGOProtos
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/POGOProtos.DLL.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Pokemon.Go.Rocket.API
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/Pokemon.Go.Rocket.API.DLL.
----------------------------------------
PokemonGo.RocketAPI.Logic
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/PokemonGo.RocketAPI.Logic.DLL.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 9.0.0.0.
    Win32-Version: 9.0.1.19813.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/Newtonsoft.Json.DLL.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Telegram.Bot
    Assembly-Version: 10.3.1.0.
    Win32-Version: 10.3.1.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/Telegram.Bot.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
Google.Protobuf
    Assembly-Version: 3.0.0.0.
    Win32-Version: 3.0.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/Google.Protobuf.DLL.
----------------------------------------
System.Device
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Device/v4.0_4.0.0.0__b77a5c561934e089/System.Device.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
System.Data.HashFunction.xxHash
    Assembly-Version: 1.8.2.2.
    Win32-Version: 1.8.2.2.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/System.Data.HashFunction.xxHash.DLL.
----------------------------------------
System.Data.HashFunction.Core
    Assembly-Version: 1.8.2.2.
    Win32-Version: 1.8.2.2.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/System.Data.HashFunction.Core.DLL.
----------------------------------------
System.Data.HashFunction.Interfaces
    Assembly-Version: 1.0.0.2.
    Win32-Version: 1.0.0.2.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/System.Data.HashFunction.Interfaces.DLL.
----------------------------------------
GMap.NET.Core
    Assembly-Version: 1.7.0.0.
    Win32-Version: 1.7.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/GMap.NET.Core.DLL.
----------------------------------------
GMap.NET.WindowsForms
    Assembly-Version: 1.7.0.0.
    Win32-Version: 1.7.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/GMap.NET.WindowsForms.DLL.
----------------------------------------
System.Data.SQLite
    Assembly-Version: 1.0.84.0.
    Win32-Version: 1.0.84.0.
    CodeBase: file:///C:/Users/nrgne/AppData/Local/GMap.NET/DllCache/SQLite_v84_NET4_x86/System.Data.SQLite.DLL.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------
System.EnterpriseServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll.
----------------------------------------
S2Geometry
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/S2Geometry.DLL.
----------------------------------------
System.Runtime
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll.
----------------------------------------
GoogleMapsApi
    Assembly-Version: 0.1.0.0.
    Win32-Version: 0.41.0.0.
    CodeBase: file:///C:/Users/nrgne/Documents/GitHub/PokemonGo-Bot/PokemonGo.RocketAPI.Console/bin/Release/GoogleMapsApi.DLL.
----------------------------------------
System.Drawing.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/System.Drawing.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------

**Comment by Logxn** [comment]
also if you disable "show pokestops" its fixed

**Comment by MTK4355** [comment]
If a null collection of pokestops is passed to the map it will break trying to render them. fix incoming.

**Comment by MTK4355** [comment]
I have a pull in place to fix various issues with the map load. Please let me know if this issue persists after the next update.

**Comment by Siufay1** [comment]
still crashing windows in the lastest build 04.09 22.32.  I really love the idea of walking in Archimedean Spiral. Hope u can fix it as well. Thanks for your hard work.

**Comment by MTK4355** [comment]
Keep an eye on this pull request. https://github.com/Ar1i/PokemonGo-Bot/pull/3605
The next build after it gets merged should fix the general load problems. Not sure about the spiral. I guess I should test it but it's not a config I'd ever use myself. Pretty though.

**Comment by Logxn** [comment]
@MTK4355 

Thanks for the fix.
Works like charm :)

@jmo93 
thanks for reporting!
