### ISSUE TITLE
[bug] when the bot ask for the player stats at third time.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#3594]
We found 5 usable PokeStops near your current location.
 Next Pokestop: Waterpalace in 235,45m distance.
 Distance to target location: 235,45 meters. Will take 211,91 seconds!

 Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: 'PokemonGo.RocketAPI.Exceptions.InvalidResponseE
xception'.
   in PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Cicklow\Desktop\PokemonGo-Bot-master_nuevo\PokemonGo-B
ot-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 84

But I dont have anything on this directory 

C:\Users\Cicklow\Desktop\PokemonGo-Bot-master_nuevo\PokemonGo-B
ot-master\PokemonGo.RocketAPI\Extensions

**Comment by AiVo7z** [comment]
Isit White colour ? if the bot keeps running it's just reconnecting bcoz the Server lagged or w/e. If thats the case, ingnore the error.

**Comment by Xelwon** [comment]
Yes, I ignore it and bot continues.

**Comment by Xelwon** [comment]
It happens again, This time sais another code line.

Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: E
xpected 5 responses, but got 0 responses
in PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0
`1.MoveNext() in C:\Users\Cicklow\Desktop\PokemonGo-Bot-master_nuevo\PokemonGo-B
ot-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 47

same function, ( moveNext ) different line 47 instead of 84

**Comment by Logxn** [comment]
I have no errors.

3 Options:

- Redownload
- Compile on your own
- Just some random Niantic error
