### ISSUE TITLE
Does Not Catch Pokemon

### ISSUE THREAD

**Issue by saucepoppa** [Ar1i/PokemonGo-Bot#3596]
-Maybe I'm Using the tool incorrectly, but I'm level ten and have set the quantity to 0 for items I don't have access to yet
-only catches rattattas 
-map set to san fran (highly populated)
-I've used it before in san fran so I know there are plenty pokemon to catch, but it only raids pokestops 
-after about 20 minutes of usage I go ahead and transfer and I end up transferring 0/0 pokemon
-if anyone who uses this tool can please share how to catch the pokemon/use the tool properly if I'm not please share (screenshots of your settings on all tabs would be a big help)

**Comment by Xelwon** [comment]
With default values it works well for my.
May be that altitude value was your problem.
Try to delete all, uncompress last rar version. run it,
put this configuration:
* your account and password
* select a location with the button set location.
* put speed at 4 kms
* unselect use luckyEgg at envolve
* unselect envolve pokemons if enough candy
* unselec use incense every 30 mins
* select lg-g4 device
next tab
* unselect autotransfer pokemons
next tab
* put all items to 200 
next tabs leave as are.

Run bot, and wait 

Those are my current options and works very well.

**Comment by Logxn** [comment]
Hello,

It also workes for me

- Change Device
- Try using proxy
- Change location
- Low Speed (8km/h is always good)
