### ISSUE TITLE
[bug] reading family candy.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#3597]
Sorting my csv list I found this strange result.

Lickitung, Magnemite, Porygon and Voltorb have same family candy: 3  (is wrote as familie candies, I don't why)

The same happens in the next groups too.

Jynx, Lapras, Hitmonlee : 0

Aerodactyl , Dratini: 7

Oddish, Scyther, Magmar: 25

Psyduck, Kabuto (and kabutops, of course): 77

I see it very strange, because in the game its have differents candy names.

**Comment by SscSPs** [comment]
well, Family means all evolution of that pokemons.
like ratata candies are used by raticate to powerup. b
But, different pokemons having same family candies is just a co-incidence.

**Comment by Xelwon** [comment]
I don`t know what want you say.

As I know.

For example aerodactyl and dratini are from diferent family so must have a different identifier in their candies.
Same happens in the rest of the list.

I think may be a conversion data error at time to write csv.

**Comment by SscSPs** [comment]
Please provide a Screenshot to explain what you are talking about

**Comment by Logxn** [comment]
I know what he is talking about but I cant think that this is actually true.
I mean this would mean that there will be errors if the bot tries to evolve this candy tree.

I'll take a look at it

**Comment by Xelwon** [comment]
Ok.
![example_candies](https://cloud.githubusercontent.com/assets/20685015/18233211/c77b6062-72e0-11e6-9c54-2cb4e0068e82.png)

**Comment by SscSPs** [comment]
its just a co-incidence. you just hapen to have 14 eevee candies and 14 exeggcute candies, that's it!
Nothing Wrong.

**Comment by Logxn** [comment]
Its true.
You are not reading the Familie Candy ID but how many Candies you have for that Pokemon.
