### ISSUE TITLE
[Bug] Altitude is not passed correctly from map to GUI.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#3598]
Altitude is not passed correctly from map to GUI.

If you press button to open google map to select start point, when you close it, sometimes put altitude to 0 and other times leave selected value.

Another related thing: Bot does not leave select a custom altitude.

I tried to put in the  map view my own value of altitude but when i close the view always put altitude to 0.

It is not problem because bot if altitude is 0 put a randon value, and works well. But this is a little dangerous, because , for example, I select a point near a the beach and the bot put altitude at 10 meters.
Is like I was flying in a kite board :D.

**Comment by Logxn** [comment]
It is now
