### ISSUE TITLE
NullException

### ISSUE THREAD

**Issue by crss** [Ar1i/PokemonGo-Bot#36]
![snippingtool_2016-07-25_17-03-02](https://cloud.githubusercontent.com/assets/19149356/17106031/fb78b7a6-5289-11e6-8b02-fb77787170f9.png)

**Comment by Ar1i** [comment]
This happens probably, cause PTC Servers are Offline.

**Comment by crss** [comment]
vermutlich. nun wo diese wirklich offline sind, bekomme ich zunächst eine vernünftige meldung. anschließend sieht es wie folgt aus: 
![mstsc_2016-07-25_17-19-26](https://cloud.githubusercontent.com/assets/19149356/17106534/04c51c76-528c-11e6-9cce-dc5e49651bfb.png)

**Comment by Ar1i** [comment]
Should be fixed now, if it happens again open a new ticket.
