### ISSUE TITLE
Remaining time until brake 50 min !?!?

### ISSUE THREAD

**Issue by prophex** [Ar1i/PokemonGo-Bot#3602]
anyone know what is that ?

**Comment by nasierache** [comment]
i do really want explanation about this.... how long it takes for break? and do we need to restart bot every 50minutes?

**Comment by prophex** [comment]
ah ok he make a break for 10 mins nice

**Comment by MTK4355** [comment]
The break interval field in the walk settings tab determines how long the bot will walk until it stops at a pokestop for a break. The break length field determines how long the bot will break each time.

**Comment by MTK4355** [comment]
@prophex Please close this if no issue

**Comment by Logxn** [comment]
Not an issue.
Question awnsered
