### ISSUE TITLE
PogoProtos

### ISSUE THREAD

**Issue by shadowahs** [Ar1i/PokemonGo-Bot#3604]
What do pogoprotos and the other PokemonGo Rocket API links do on this site?

**Comment by shadowahs** [comment]
Basically, how do you add the codes to the bot?

**Comment by Viper2k4** [comment]
what? ^^

**Comment by Viper2k4** [comment]
For:
https://github.com/Ar1i/PokemonGo-Bot/tree/master/POGOProtos

Read this:
https://developers.google.com/protocol-buffers/

RocketAPI:
https://github.com/FeroxRev/Pokemon-Go-Rocket-API

**Comment by shadowahs** [comment]
but what does it actually do

**Comment by Viper2k4** [comment]
I rly dont understand ur question.

**Comment by shadowahs** [comment]
where do i apply the codes? i guess i just dont understand the tutorial

**Comment by Viper2k4** [comment]
ok ur finaly question is how do u run the code?

**Comment by shadowahs** [comment]
what kind of app do i need to run the exe?

**Comment by Viper2k4** [comment]
Windows? ^^

**Comment by shadowahs** [comment]
![capture](https://cloud.githubusercontent.com/assets/20916831/18239222/6cc18bf0-7309-11e6-9b81-e88373cfc843.PNG) 

yes windows,
and which one of the files would i need to run?

**Comment by Viper2k4** [comment]
![6cc18bf0-7309-11e6-9b81-e88373cfc843](https://cloud.githubusercontent.com/assets/15054322/18239245/48c45f76-7344-11e6-9251-f79c8b789da0.PNG)

**Comment by shadowahs** [comment]
yes but to implement pogoprotos? 
or am i taking them the wrong way?

**Comment by Viper2k4** [comment]
Im out. I dont know what u want/whats u plan is.

**Comment by shadowahs** [comment]
i know how to start the bot, it starts fine.
but what do the PogoProtos do exactly?

**Comment by Viper2k4** [comment]
Read this Link:
https://developers.google.com/protocol-buffers/

Like i said above. PogoProtos are the protocol-buffers for Pokemon go:

**Po**kemon**Go****Proto**colbuffers
