### ISSUE TITLE
Google.protobuf Error

### ISSUE THREAD

**Issue by Munddie11** [Ar1i/PokemonGo-Bot#3608]
Ive got that error even if i try to log in via PTC ;(
![protobuf](https://cloud.githubusercontent.com/assets/20951724/18239034/c6e5f344-7342-11e6-89a2-dd440e32416e.JPG)

**Comment by Logxn** [comment]
Wahrscheinlich nur ein Server fehler.
Probiers nochmal.
Wenn dann nicht geht dann eröffne n neues Ticket.
