### ISSUE TITLE
Special 1337 Unban Methode.

### ISSUE THREAD

**Issue by iOwner** [Ar1i/PokemonGo-Bot#361]
The client has detected a softban on one of my accounts. However, the unban method doesn't seem to do the trick. I've left it for a total of 40 minutes now and still nothing has changed.
It says, "Probably Unbanned You" and proceeds to the next pokestop, but still doesn't catch any pokemon or collect items from the pokestop.

Any advice? I know I could wait it out but exp waits for no man, so god knows how long I'll have to wait for.

Could you possibly look into a rework of the softban unban method?

Thank you for reading.

**Comment by UltraVLT** [comment]
May be because of the new version bugged,just like the one yesterday with the false ban report

**Comment by iOwner** [comment]
After around an hour, the client unbanned the account, however the new problem is, it catches pokemon but a new error message appears saying, "we cant find any pokestops in a range of 50000." which i find highly unlikely to be the case seeing as I've set the location to Central Park.

**Comment by UltraVLT** [comment]
Just a bug,it happens often.Wait for a client update

**Comment by StyxHell** [comment]
Yeah, no pokestops to find in Central Park. 
Had the same Problem, checked it with the Pokemon GO Map.
It shows no Pokestops in Central Park, if you move a little down to "Two Bridges" there are plenty of Stops. 
I think its more likely that the niantec servers have some issues.

**Comment by UltraVLT** [comment]
Pokestopsmap still working for me.Just have patience.It will work again later on.

**Comment by raineshh** [comment]
Hi . I have the same problem . I'm using the Program Progressing Two Different Accounts . please help me.

**Comment by Craterus** [comment]
Got Soft-Banned several Times ago, Unban Methode worked 100% :)
Got Soft-Banned today and the Unban Method's not working.

**Comment by MTK4355** [comment]
I have not seen this work since the latest update from Niantic. I think they changed something.
