### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by vinsiong** [Ar1i/PokemonGo-Bot#3610]
it says there is a newer version or update 1.1.1.9  and im still using the version 1.1.1.8 i was unable to update it what happen? ive done it 2
![screenshot_6](https://cloud.githubusercontent.com/assets/21275550/18243142/5734779c-738c-11e6-879b-ec011d4b1452.jpg)
![screenshot_7](https://cloud.githubusercontent.com/assets/21275550/18243143/573c6b82-738c-11e6-8dea-032a20905620.jpg)

 times to download it and still the older version force back..

**Comment by Logxn** [comment]
Try again.
I forgot to update the builds only file.

If you compile it on your own it should be the newest.

**Comment by vinsiong** [comment]
i think the file is broken
![screenshot_8](https://cloud.githubusercontent.com/assets/21275550/18244686/fb2de2c8-7393-11e6-8b26-bf277e533705.jpg)

**Comment by Logxn** [comment]
No its not.
Its a .rar file.
Dont you have winrar?

**Comment by ramigora** [comment]
get 7zip
