### ISSUE TITLE
Need Auto-Evolve HIGHEST IV FIRST please ;)

### ISSUE THREAD

**Issue by Baanksim** [Ar1i/PokemonGo-Bot#3612]
Hello Ar1i !

Can you please add to your bot the choice to first auto-evolve pokemons with highest IV, like you did for the auto-transfer...

Chears !

**Comment by nasierache** [comment]
im not looking for this.. if me, i will save the highest IV for full power-up first before evolve it.. chears!!

**Comment by fetmamm** [comment]
@nasierache why would you do that?

**Comment by Baanksim** [comment]
@nasierache So you will full power up a pokemon that can be really useless because of bad moves after you evolve it ?? Really bad idea...

**Comment by Hydro420** [comment]
@nasierache Evolve first then power up - it costs the same candy/stardust & this way (like the others said), you can see the moves and determine if its worth powering up.

**Comment by Baanksim** [comment]
So are people interessed by doing an option to auto-evolve highest IV first ? We need more voices to make Ar1i do it ;) !!!

**Comment by Logxn** [comment]
Ar1i wont make it this week.
So its all to me. I will take care of this repo for a week now.

**Comment by Baanksim** [comment]
Ok great ;) ty
