### ISSUE TITLE
Can't find PokemonGo.RocketAPI.Console.exe [1.1.1.9]

### ISSUE THREAD

**Issue by Microrock** [Ar1i/PokemonGo-Bot#3613]
Can't find PokemonGo.RocketAPI.Console.exe [1.1.1.9]

and Builds Only folder  rename to Builds-Only

**Comment by SebiWolze** [comment]
Same here.
Would be nice to compile it again, und reupload it.

Thanks.

**Comment by trislyn** [comment]
PokemonGo-Bot-master\Builds Only\Latest Build - 05.0911.48\bin\Debug\PokemonGo.RocketAPI.Console

**Comment by Logxn** [comment]
Redownload.

Its now Builds Only\Latest Build\PokemonGo.RocketAPI.Console.exe

**Comment by Viper2k4** [comment]
Btw. why not simply use:

https://github.com/Ar1i/PokemonGo-Bot/releases
