### ISSUE TITLE
Run?

### ISSUE THREAD

**Issue by lachiefish** [Ar1i/PokemonGo-Bot#3614]
Sorry this might seem like a stupid question, but with the newest version (1.1.1.9), there's no exe file to run, how do i start the bot? :)

**Comment by SebiWolze** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/3613

Look here :)

**Comment by lachiefish** [comment]
Ah sorry!! thanks so much :)

**Comment by Logxn** [comment]
Now also using releases
