### ISSUE TITLE
Niantic adding Captcha 

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3615]
Have you foreseen the thing that niantic will add captca "i am not a robot" thing ? Are you preparing something for it cause they say it's on the next update :/

**Comment by Logxn** [comment]
Yes, we are aware of that.
We have 2 Ideas how we could handle that :)

**Comment by k0ut4li4n0s** [comment]
Awsome ! Nice to know ! Keep up the good work ! Thankfull :) :)

**Comment by Logxn** [comment]
I will close this since its not an issue :) 

If you have any questions you are more then welcome to ask me on twitter :) twitter.com/loganpunkt
