### ISSUE TITLE
Pokestop not ready to farm again

### ISSUE THREAD

**Issue by kullanici112** [Ar1i/PokemonGo-Bot#3616]
-> Pokestop not readt to farm again
-> again
-> After about 10 minutes runtime eror 
->Starting again in 10 seconds...
![cats](https://cloud.githubusercontent.com/assets/21956786/18249722/baed218e-7388-11e6-8907-1531b28a1b1d.jpg)

**Comment by kullanici112** [comment]
its happening every time after the break

**Comment by MTK4355** [comment]
Thanks, I'll take a look!
