### ISSUE TITLE
Break suggestion

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3618]
i think break feature sometimes did not work well, sometimes after 10mins bot still didnt move to next pokestop and still checking pokestop ready/not.

 and for improvement i think you should make break time randomly 1-10mins, it is because i dont think normal human would rest precisely 10mins on every rest that he takes unless he is super particular people..in my opinion :)

**Comment by MTK4355** [comment]
Not a bad idea. Maybe treat the field as a "Max" break time?

**Comment by nasierache** [comment]
plus you can make button to use poke lure during break period...at least more pokemon appear during break and its better then sit and do nothing..its normal for human who stay in same place because of poke lure..seems logic in my opinion. ^_^

**Comment by MTK4355** [comment]
There is an option in the settings to use a lure on break already! It will use a lure the first time it stops for a break

**Comment by nasierache** [comment]
@MTK4355 noted.. thanks
