### ISSUE TITLE
Where To farm...

### ISSUE THREAD

**Issue by navzmic** [Ar1i/PokemonGo-Bot#3620]
i wonder where can i ask the location of charmander nest.. squirtel nest.. bulbasaur nest... pikachu nest..
i dont like the poke snipe.. they have high chance of banning a account..

sorry if i wrote a wrong post in here...

**Comment by SscSPs** [comment]
Search Google. 
And yes, you asked in wrong place. This is no place for such question

**Comment by LeDudeGolfer** [comment]
Hey, 
just wanted to say that Bulbasaur nest is in Prague - Letná park.
