### ISSUE TITLE
Error after new version install

### ISSUE THREAD

**Issue by Killoudu61** [Ar1i/PokemonGo-Bot#3622]
Hi ! Just installed the new version and got this error

![pkmn](https://cloud.githubusercontent.com/assets/22008700/18252438/b69d73bc-738e-11e6-91cc-9126140eb602.png)

**Comment by SscSPs** [comment]
There is some sort of problem in your connection i guess

**Comment by Killoudu61** [comment]
I dont understand, everything was fine before installing the new version

**Comment by SscSPs** [comment]
Try extracting again

**Comment by Killoudu61** [comment]
okay

**Comment by Killoudu61** [comment]
Thanks man, it worked !
