### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by BOYSA** [Ar1i/PokemonGo-Bot#3623]
Hello,
I wonder if one day you will repair the french button because its been several updates and the french still does not work
Please Ar1i

**Comment by Killoudu61** [comment]
C'est vrai ça merci de le poster hahah ;)

**Comment by PapyGeek** [comment]
Hello, if i can help you for translate to french, it's easy .. i'm french ;)

**Comment by Logxn** [comment]
Create a pull request with updated translation?

**Comment by BOYSA** [comment]
Pourquoi faire simple quand on peut faire compliquer sérieux le mec je lui dit juste qu'il y a un problème avec son script après il se débrouille je vais pas créer des ticket a gogo moi perso je m'en fou je c'est lire en anglais, je faisait sa pour les autres !

**Comment by BOYSA** [comment]
après moi j’ai déjà retravailler le script mais quand je sauvegarde le c++ et que je relance le jeu et ben le c++ se remet de base dans la langue d'origine ^^ donc problème du coté de chez eux ^^
