### ISSUE TITLE
Intermittent Error Message

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#3625]
Is this normal for some of you guys? I am having this issue time to time.. like every 30m~45mins.. or sometimes when break is activated.. 

[http://imgur.com/a/KF72W]

**Comment by Akuma9GK** [comment]
Sounds about right.

**Comment by Logxn** [comment]
@MTK4355 

Could this be an issue with you? When it wants to catch a pokemon and it toggles the break?

Cuz I never had that nor I find any annomalys in the code

**Comment by MTK4355** [comment]
I haven't seen that error myself, and I'm using the breaks all day.. @coffeexp can you screenshot configs? I'll try to reproduce.

**Comment by coffeexp** [comment]
@MTK4355 these are the screenshots
Error: http://imgur.com/6LFwPQu
Settings/Configs: http://imgur.com/9Fwpnk6

**Comment by Logxn** [comment]
Thats when your connection times out. nothing bad.
