### ISSUE TITLE
1 acct works but 1 doesnt?

### ISSUE THREAD

**Issue by drjack6** [Ar1i/PokemonGo-Bot#3627]
Tried two accts with newest version. Both are confirmed not banned. Same exact settings for both accounts. One account works. The other just gets no pokestops oin range of 5000m message. The ONLY thing different is the email address. Any ideas why this would be?

**Comment by nasierache** [comment]
did you run 2accts on the same time?

**Comment by drjack6** [comment]
Nope never

**Comment by nasierache** [comment]
its happen to me once when i and my friend run bot via wifi... same as your case, our bot cant gets no pokestops within range..it happen because the ip has been banned by niantic for running 2accts with the same ip. otherwise i had no idea what your account problems.
