### ISSUE TITLE
Suggestion!! pokestop icon can be click/select!!

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3628]
it would be great if you can add feature where we can click/select the pokestop on the map and direct bot walking towards pokestop that we click/select. the reason is sometime bot take times to do the full check when there's a lot of pokestop, and some pokestop doesn't have the pokemon nest that we chase for when bot go through the path to next pokestop..

**Comment by Viper2k4** [comment]
I think a better idear would be import the spawns json from pokemongo-map or so and include the spawnpoints in there routing.
