### ISSUE TITLE
Auto transfer double Pokemons [GUI Build - 30.07 00.34] NOT WORKING

### ISSUE THREAD

**Issue by A4380** [Ar1i/PokemonGo-Bot#363]
Is this a bug ? 
i only wanna keep the pokemon with the biggest CP 
Example
Pikachu CP 100 IV 90
Pikachu CP 200 IV 80
Pikachu CP 700 IV 20
The IV is not relevant
Keep the Pikachu  with the biggest CP [Pikachu CP 700 IV 20]
And if Pikachu is in the [Pokemons to not transfere] Do not transfer any
And keep all 
Pikachu CP 100 IV 90
Pikachu CP 200 IV 80
Pikachu CP 700 IV 20
Please Help 
![build - 30 07 13 10](https://cloud.githubusercontent.com/assets/20731533/17270068/5545189c-560e-11e6-9b58-9b89f2f40e9e.png)

**Comment by UltraVLT** [comment]
if it's max CP on 0 it won't transfer any of them even though u only wanna keep the best one.It's a exception for the auto transfer,so if you would now tick on max CP 800 and Max IV 90% it will transfer the >800CP (100 & 200)

**Comment by Pseudoxanthoma** [comment]
I set: Max duplicate Pokemon to 5
Max CP to transfer to 800
And Max IV to transfer 90%
But I still find Pokemon with very low CP in my list because he picks IV over CP. 
He keeps Pidgey with 54 CP and transfers Pidgey with 300 CP cuz of lower IV.
