### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3631]
is it posibble to add adjust setting feature once bot running? like you can change the amount of items, pokemon that you want to evolve and so on..is it can be done?

**Comment by Logxn** [comment]
I could try it via Hotkey

**Comment by nasierache** [comment]
nice.. thanks

**Comment by Boscao** [comment]
Can't it be done by a tab in GUI? This way would be much easier to keep track of the settings and changes.
