### ISSUE TITLE
Archimedean spiral issue

### ISSUE THREAD

**Issue by TxShack** [Ar1i/PokemonGo-Bot#3634]
My character seemed to be moving at first and then when I zoom in on the map I saw the it was like trying to get outside of the starting location to a pokestop and then another one and it kept trying, but it just couldn't and was really making it to any of the pokestops. Had the picture but forgot where I placed it so I don't know if I'm the only one.

P.S.: Is working fine without it though...

**Comment by SscSPs** [comment]
get another screenshot to help us better understand it.

**Comment by Slayer013** [comment]
similar thing happened to me while using achimedean sphere.. 
it moves correctly on a spiral motion but never goes to a pokestop in its path.. even though it says looking for pokestops around some 30meters... 
it didn't stop for even one pokestop withing the spiral motion...
