### ISSUE TITLE
V. 1121 Virus Detect with Avast

### ISSUE THREAD

**Issue by Microrock** [Ar1i/PokemonGo-Bot#3636]
Avast Antivirus auto delete PokemonGo.RocketAPI.Console.exe

How to fix ? I think the PokemonGo.RocketAPI.Console.exe is not virus.

Please reply for restore this file.

sorry for my language.

[ I can restore and fix this file for out of detect ]

Thank You.

http://www.uppic.org/image-03D2_57CE9C47.jpg

**Comment by Logxn** [comment]
Restore the file.
Its no virus:)

**Comment by Microrock** [comment]
Thank You Sir.

**Comment by Logxn** [comment]
No problem!

**Comment by coffeexp** [comment]
same with me.. is it ok to use the older version for now? thanks!!

**Comment by Logxn** [comment]
Its okay, but I can assure its no virus
