### ISSUE TITLE
Latest version keeps crashing

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3637]
it shows every minute this text seems like the pokelog is beeing used my another process(it only happens when I catch something

[13:36:03] Exception: System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\suljo\Downloads\BOT\Logs\pokelog.txt omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bij System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bij System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   bij System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   bij System.IO.File.AppendAllText(String path, String contents)
   bij PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__33.MoveNext() in C:\Users\nrgne\Desktop\PokemonGoBot\06.09\1.1.2.1\PokemonGo.RocketAPI.Logic\Logic.cs:regel 939
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__5.MoveNext() in C:\Users\nrgne\Desktop\PokemonGoBot\06.09\1.1.2.1\PokemonGo.RocketAPI.Logic\Navigation.cs:regel 95
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bij PokemonGo.RocketAPI.Logic.Logic.<fncPokeStop>d__30.MoveNext() in C:\Users\nrgne\Desktop\PokemonGoBot\06.09\1.1.2.1\PokemonGo.RocketAPI.Logic\Logic.cs:regel 624
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__29.MoveNext() in C:\Users\nrgne\Desktop\PokemonGoBot\06.09\1.1.2.1\PokemonGo.RocketAPI.Logic\Logic.cs:regel 501
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__21.MoveNext() in C:\Users\nrgne\Desktop\PokemonGoBot\06.09\1.1.2.1\PokemonGo.RocketAPI.Logic\Logic.cs:regel 271

**Comment by suljo94** [comment]
disablign the log under misk fixes the issue

**Comment by Logxn** [comment]
k I will look at it.
just to test. when you restart it, does it get fixed?

**Comment by suljo94** [comment]
@Logxn nop keeps crashing, but disabling does the trick

**Comment by Logxn** [comment]
Thats funny.
After the error I restarted it and it works now.
I bet you didn't even try ;)

Regardless I think I have the fix

**Comment by Logxn** [comment]
Fixed redownload please.

(Wait until the newest build was uploaded)
