### ISSUE TITLE
Avast reports .exe contains virus/trojan

### ISSUE THREAD

**Issue by jrance89** [Ar1i/PokemonGo-Bot#3639]
Virustotal.com report: https://www.virustotal.com/es/file/45df2bb4164f484ac58027767a9d18e4ddcc999e5a389751de496c14b9ac7497/analysis/1473165467/

![image](https://cloud.githubusercontent.com/assets/22028245/18273986/74d73fdc-7440-11e6-9ffd-2ffe57fb816d.png)

**Comment by Logxn** [comment]
Evo-Gen is ony Suspisious.
It probably because we generate files and folders
