### ISSUE TITLE
Why Pokemon GO German names has been removed?

### ISSUE THREAD

**Issue by PrOCheaTer** [Ar1i/PokemonGo-Bot#3642]
the title says the question..

Thx

**Comment by Ar1i** [comment]
cause buggy and not needed atm

**Comment by PrOCheaTer** [comment]
wieso buggy? funktioniert tadellos bei einer deiner alten Versionen. Schade, wirklich!

**Comment by Viper2k4** [comment]
It's buggy. Try to activate it and click some pokemon to evolve. The bot will crash.

**Comment by bob2016bob** [comment]
Hallo Leute,
Erstmal danke für den super Bot, wirklich super Arbeit.
Ich hatte auch nie ein Problem mit den Deutschen Namen.
Ich würde mir auch gerne eien bessere Übersetzung für den gesamten Bot (GUI) wünschen da ich es mit Englisch nicht so habe leider.

**Comment by PrOCheaTer** [comment]
Hallo,

So ich habe mich an die Arbeit gemacht und die Funktion wieder eingefügt. 
Da ich mich damit nicht abfinden wollte dass es keine Deutsche Pokemonnamen mehr geben sollte^^
Es switcht ganz normal wieder zwischen Deutsch oder Englisch was man haben möchte.
Beim Entwickeln, PowerUp oder sonstiges gibt es keine Probleme.
Ich für meinen Teil finde meine Arbeit in Ordnung und es funktioniert tadellos.

**Comment by bob2016bob** [comment]
Hallo,
Super und was muss man machen?

**Comment by Schnitzelvernichter** [comment]
man gewöhnt sich ziemlich schnell um....wollt ihr das hier nicht mal zu machen ?
