### ISSUE TITLE
Error on config..

### ISSUE THREAD

**Issue by Kadeshhh** [Ar1i/PokemonGo-Bot#3644]
How do I fix this? I uploaded the screenshot.
![aaa](https://cloud.githubusercontent.com/assets/21364225/18277479/21f175d4-73fb-11e6-9aad-edec3a17bba2.jpg)

**Comment by Logxn** [comment]
Copy the text and post it here please.

**Comment by B4SH4** [comment]
Delete the Config.txt in the Configs folder. The Bot must be stopped, now you need to enter the Login Information again and set the other things again. 
Now the Bot run.

**Comment by tinitix** [comment]
Ich habe seit einigen Versionen ein ähnliches Problem. Mittlerweile startet zwar der Bot, aber es ist alles rot. Hier der Inhalt vom Bot... 

> [19:24:27] Trying to Restart.
[19:24:27] Restarting in 10 Seconds.
[19:24:38] Error: Pokemon.Go.Rocket.API
[19:24:47] PokemonGo.RocketAPI.Exceptions.LoginFailedException: Eine Ausnahme vo
m Typ "PokemonGo.RocketAPI.Exceptions.LoginFailedException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Login.PtcLogin.ExtractTicketFromResponse(HttpResponse
Message loginResp) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\Po
kemonGo.RocketAPI\Login\PtcLogin.cs:Zeile 53.
   bei PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__8.MoveNext() in C:\
Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\P
tcLogin.cs:Zeile 90.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in C:\
Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\P
tcLogin.cs:Zeile 40.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\De
sktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:Zeile
43.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__19.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Z
eile 106.

> 

Kann mir jemand weiterhelfen? 

Vielen Dank schonmal

**Comment by B4SH4** [comment]
Lösch die Config.txt im Configs Ordner das hat mir geholfen

**Comment by B4SH4** [comment]
Aber teste deinen Acc mal auf nem handy oder so. Weil das sieht mir nach einem Bann aus. Deines PTC acc's.

**Comment by tinitix** [comment]
Hallo B4SH4

Weder das löschen der Config.txt oder auch des gesamten Ordners hilft mir weiter ... leider. Kein Plan was da los ist. 

Und der Account ist 100% nicht gebannt. Kann ganz normal über Handy einloggen spielen usw. Wurde bisher auch nur ganz wenig genutzt.

**Comment by B4SH4** [comment]
Neuste Bot Version installiert ? Evtl. eine Funktion, die dies verursacht die Aktuell buggy ist ? Wen ja nimm den haken da raus und warte auf nen Fix.

**Comment by B4SH4** [comment]
Edit, ich sehe es gibt im Error Log ein Problem mit dem Login des PTC acc's. Ursache und Problem behandlung kann ich nicht geben da ich kein Coder bin.

**Comment by Logxn** [comment]
Poste den Error hier ;)
Ich analysier das

**Comment by B4SH4** [comment]
@Logxn scroll mal nach oben erst ist von ihm schon drinne
