### ISSUE TITLE
Hi , was kommt eigentlich von Server zurück ?

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3645]
Hallo , 
wenn man mit den Handy spielt bekommt man doch von N-Server Antworten die das Spiel auf den Handy dann umsetzt.... 
"Handy :Monster versendet" 
"Server : Bohne ok"  usw ...  usw. 
Was macht da eigentlich der Bot damit ? 
oder kommt da nichts von Spieleserver ? 
oder kommt da nur ein "OK" von Server das eigentlich egal ist ...? 
Es macht ja irgendwie keinen Sinn einen Bot zu erstellen wenn man das außenrum nicht beachtet . 

Könnte der Bot diese Serverantworten nicht als Textzeile ausgeben ?  

z.b. : Taubsi gefangen 
         Server "OK" 

aufgrund dieser Antwort könnte man auch Zeitlich RICHTIG erwecken usw....   

Außerdem währe es zwingend notwendig diese Komunikation mal irgendwie aufzuzeichnen und auszuwerten .... gibt es da schon auswertungen darüber ? 
Der Bot soll ja SAVE werden .... 
Ich hoffe ich habe mich verständlich ausgedrückt .  :-)   

Der Bot der letzten Tage gefällt mir überhaupt nicht mehr , ständig irgendwelche Fehlermeldungen oder er macht was er will.... einige Erweiterungen brachten nur neue Fehler ....  

Keine Verbesserungen und erstmal alle Fehler bereinigen währe Sinnvoller ... 
kommt mir hier langsam etwas Chaotisch vor . (Sorry musste jetzt mal raus ) 
Zur Not mal den neuen Kram wieder raushauen .

Ich benutze nur die alten Versionen und bin VOLL zufrieden , hier ein dickes Lob von mir an Ar1i und 
MTK. 
Bis dene ..
Gruß Tom

**Comment by AiVo7z** [comment]
Ich glaube dir das zu erklären würde nichts bringen. Ausserdem brauchst du garnicht denken das sich einer die Mühe hier macht dir detailiert mit Beispielen diesen Vorgang zu erklären. Du kannst natürlich mit einem Bot ein Handy und einen Menschen imitieren. Damals sagten Leute das seit der neuen API die Entwickler unterscheiden können ob eine Software spielt über PC z.b. oder ein Smartphone sich einloggt. Inwiefern sie das umgehen ist für uns beide zu technisch und da es sehr wohl bans gibt (selbst mit realistischen Konfigurationen des Bots) scheint nur selbst zu spielen ohne Cheats/Hacks/Scripts/Bots sicher zu sein. Nicht ohne Grund wird für Bans gewarnt, ein Restrisiko besteht immer... 
Es wurde schon viel am Bot gemacht um Dinge zu verzögern damit es realistischer wirkt und manche Dinge gehen nicht so schnell, z.B. Entwickeln (Zwangsanimation) sowie das Verschicken... deswegen sind dort einfach in den Code Pausen reingesetzt worden, simple... da wird nichts ausgelesen sondern einfach gesagt normalerweise braucht man min (z.B.) 20-25 Sekunden für Entwickeln, also bauen wir 20-25Sek als Timer ein, fertig.

Alte Versionen laufen vlt. augenscheinlich stabiler, aber viel bringt dir zu schnell ein Ban ein, deswegen benutz immer die neuste Version viel davon musst du ja garnicht erst anklicken, ich meide alles mit Breaks, Lures und dieser neuen Spirale beim Laufen. 
Dort wird auch viel im Hintergrund geändert und angepasst. Dinge die du garnicht mitbekommst.
Funktionen wie zufälliges ändern der Laufgeschwindigkeit ist sinnvoll und ich benutze es... 
Im Endeffekt zählt nur eins, dass der Account nicht geblockt wird, sonst brauchst du auch garnicht botten.

**Comment by Logxn** [comment]
Hallo,

Wenn du möchtest könnte ich unter Misc eine experimentelle Funktion einbauen die alle Server Responses zurück gibt.
Das wären aber viele.
So viele, dass du in der Console den TOTALEN überblick verlieren würdest.

Wenn du möchtest kann ich aber die Responses alle in einer .TXT speichern für dich :)
So wie ich es bei "Log caught Pokemon" gemacht habe :)

Grüße,
Logxn

**Comment by Logxn** [comment]
Kleiner Anhang:

Natürlich kommt es bei neueren Funktionen häufig zu Fehlern.
Das lässt mich aber denken, dass du garnicht bei den all zu alten Versionen dabei gewesen bist.
Als die ersten Versionen des bottes gestartet sind hatte @Ar1i wohl nichts anderes zu tun als vieeeeele Fehler auszubesseren.

Ich muss sagen, dass der jetztige Bot deutlich weniger Fehler aufweißt.
Und wenn die Server von Niantic (wegen irgendwelchen Serverproblemen von ihrer Seite aus) die Connection unterbrechen, dann können wir nichts dagegen tun als so eine Nachricht auszuspucken.

Die anderen Error Nachrichten werden ja ziemlich schnell gefixed dank euch :)
Es gibt allerdings bis jetzt paar Errors die wir nicht verstehen. Teilweise weil die Protos noch nicht alle gecrackt wurden und weil sie überhaupt keinen Sinn ergeben, da die Funktion eigentlich erfüllt wurde.

Ich hoffe du kannst verstehen, dass Ar1i viel mehr Zeit in das Projekt gesteckt hat als ich.
Ich bin nur sein kleiner Helfer und versuche euch mit ein paar neuen Funktionen und Bugfixes zu versorgen, oder helfe ihm wenn Niantic mal wieder auf die glorreiche Idee kommt eine neue API rauszubringen(-.-) :b 

Ich hoffe mein (doch etwas größerer) Anhang leuchtet einigen hier ein.
Deswegen möchten wir übrigens auch, dass wir GENAUE Informationen bekommen, was den Error auslöst.

Grüße,
Logxn

**Comment by Viper2k4** [comment]
Das läuft etwas anders als:

"z.b. : Taubsi gefangen
Server "OK" 

Weil in so einem Fall könnte man ja folgendes machen:

"Perfektes Mew gefangen"
Server "ok"

Es läuft eher so das der Server dir z.b sagt Pokemon XY (stell dir eher ne Nummer vor) steht da und da. Dann sagst der Client/Handy nicht das du es gefangen hast sondern er sagt eher sowas wie "Versuche Pokemon XY zu fangen mit einem Guten Curve Ball". Server antwortet dann sowas wie "Nö" oder "jo hat geklappt"

Aber mit alten Versionen musst du echt aufpassen. Stell dir mal vor Niantic ändert was an der Kommunikation mit dem Client. Auch wenn es nur ne kleinigkeit ist. Z.b das der Server jetzt auch wissen möchte ob das Handy grade Vertikal oder Horizontal liegt (oder irgend sowas). Ggf. Arbeitet dein alter Bot dann zwar trotzdem aber dadurch das der Bot dies nicht schickt weiß Niantic quasi direkt das ein Bot läuft da der Normale Client eben diese Info sendet.

usw.

**Comment by Logxn** [comment]
Auch sei dazu gesagt, es mag so scheinen als ob der Server ein "OK" zurückgibt.
Aber bei Niantic könnten durchaus alle Alarmglocken leuten.

Und nur weil der Account nicht gebannt wird, heißt es nicht, dass es ihn einen Monat später doch trifft.

Ich muss auch @Viper2k4 zustimmen.
ALTE Versionen werden ABSOLUT NICHT empfohlen zu verwenden.

**Comment by SebiWolze** [comment]
Danke für deine ausführliche Antwort Logxn, ich verfolge das ganze schon seit dem damaligen Anfang mit. Natürlich wurde mir damals mein MainAcc gesperrt, wer mit 500kmh im Disneyland Tokio rumläuft, und dann 3min später am Santa Monica Pier, der hats aber auch verdient.

Die ganze Geschichte mit dem knacken der API hab im Discord sowie bei reddit verfolgt, muss sagen das war einfach nur geil anzusehen für einen Nerd wie mich.

Sollte die API im Stande sein herauszufinden ob ein Mensch oder eine Maschine dahinter steckt, dann wundert es mich, warum mein aktueller Botaccount welcher nur mit legit Settings, mit allen euren Hilfsmitteln (unterschiedliche Würfe, Geschwindigkeiten usw.) noch immer nicht gebannt wurde. Alles in allem Top Arbeit. Danke.

PS: bin Donator.
PPS: Sorry für Offtopic

**Comment by Viper2k4** [comment]
Ich persönlich glaube auch das es so laufen wird das sie Accounts flagen (aufgrund Fehler in der API wie oben beschrieben) und in ner Bannwave eben diese Accounts weg fliegen. Aber das sind alles nur vermutung :/

**Comment by Ar1i** [comment]
@Viper2k4 die sind nicht hinter dem, überhaupt nicht. Nur der eine Package Name ist noch nicht geändert. Das ist aber kein Problem.

**Comment by Logxn** [comment]
@SebiWolze 

Würden wir alle Maßnahmen nicht im Bot haben
Sondern nur die Standart API nutzen so wie sie ist....
Wären die Accounts weg. Alle. BANNED.

Vor kurzem erst wurde ein weiterer Teil der API genackt wo die API noch mal extra eine Höhe des Spielers verlangt hat. 
Ich denke da ist noch so viel, von dem wir nicht wissen. Aber bis jetzt ist alles gut :)

PS: Danke fürs donaten :)
PPS: Schon gut. Dieser Post hat wenigstens sinn. Und ich hoffe damit werden fragen geklärt

@Viper2k4 
Sicher könnte das so sein, und mich würde es auch nicht wundern. 
Aber ganz ehrlich... bis jetzt habe ich ein gutes Gefühl. Könnte mich aber jederzeit täuschen.

**Comment by Viper2k4** [comment]
@Ar1i 
Echt nicht? Weil gelegentlich bekomme ich ne exception dich sich auf Badresponses in irgend einem Envelope bezieht. Und ich habe das für mich irgendwie immer darauf bezogen und deshalb ignoriert^^

**Comment by Logxn** [comment]
Ja das stimmt, aber die bekommt man ja auch nicht so häufig. 
Pro tag 1x hab ich das, 10 sekunden warten und weiter gehts :)

**Comment by Viper2k4** [comment]
Ja aber als Programmierer verwundert einen sowas und sucht man gern mal nach gründen ^^

**Comment by Logxn** [comment]
Hast du schonmal den Code untersucht?
Vielleicht hast du glück und du findest irgendwas.

Du kannst ja mal ne Kopie des bottes anlegen, die Protos updaten und mal so n Tag oder 2 laufen lassen und uns dein ergebniss sagen :)

**Comment by AiVo7z** [comment]
Ich hatte damals einen Acc mit Lvl 31 den ich aufgehört habe zu botten, nur noch normal gespielt habe und nach 2 Wochen war er permanent geblockt. 
@SebiWolze also ist so eine Aussage total nutzlos weil nur weil dein Acc NOCH nicht gebanned wurde und selbst wenn du jetzt aufhörst zu botten, kann es trotzdem sein das es dich erwischt.
Wie Niantic genau dabei vorgeht und warum man trotzdem solange thirdparty Programme/Plugins benutzten kann, ist mir ein Rätsel, aber vlt. ist genau das der Plan um die Botter so hart zu treffen (Hohes Lvl, top Equip und dann block) das sie von alleine aufhören. Ich botte nur noch aus Langeweile nachdem meine 30+ (teils mit highend WP/IV) geblockt wurden. So nachdem Motto wenns klappt okay, wenn nicht, dann nicht.

**Comment by PrOCheaTer** [comment]
@Logxn 

Hätte auch Interesse an dieser Funktion. Konsolenausgabe oder ein extra Logfile ist mir persönlich Wurst.

PS: Danke für diesen aufschlußreichen Thread.

**Comment by Schnitzelvernichter** [comment]
Danke für die Antworten. Die neusten Versionen laufen übrigens viel besser . 
Sorry wenn ich jemanden auf die Füße bin ...

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw
