### ISSUE TITLE
Auto Transfer not working? Please read my issue

### ISSUE THREAD

**Issue by jackrose01** [Ar1i/PokemonGo-Bot#365]
Hello... first word, i want to say thank you for you guys...
this is awsome logic & features. But i found some features are not working.

# The Bot Setting.

The setting are working at first use. But when i tried again, there is no pokemon transfered.

"Auto transfer double Pokemon" = Checked
"Max.Duplicate Pokemons" = 2
"Max CP to transfer" = 999
"Max IV to transfer" = 99

i tried "Max.Duplicate Pokemons" = 1 and 0. but not working
i tried "Max CP to transfer" = 1. but not working
i tried ""Max CP to transfer" = 1 and "Max.Duplicate Pokemons" = 0 and "Auto transfer double Pokemon" = Unchecked. but not working

is there any manual configuration for this feature?

Sorry for my bad english :)

**Comment by TMaddox** [comment]
max cp to transfer = 1 means you transfer nothing above 1 cp ;)

**Comment by jackrose01** [comment]
but when i use 999. same, not working too >_<

**Comment by TMaddox** [comment]
set it too 3000
and max duplicate 1 (not sure if 0 is working)

**Comment by jackrose01** [comment]
3000 ? all pokemon under 3000 cp will transfered?

**Comment by TMaddox** [comment]
yes i thought you wanted to clear poke inv to speedlvl with lucky egg and evolve the whole inventory

**Comment by jackrose01** [comment]
no, i want to transfer pokemon under IV 99% and keep my pokemon with CP 1000 ++

**Comment by TMaddox** [comment]
then: cp max: 1000 and max iv: 99% (i recommend at least 95%, i have never seen one above 98%)

**Comment by jackrose01** [comment]
my friend have two dragonite with IV 100% hahaha... thats why i just want 100%

wait, i test it first

**Comment by jackrose01** [comment]
# Working at first, but i think i need to restart the console when i want to transfer it.

thats mean, i cant leave my console >_<

**Comment by TMaddox** [comment]
i have three acc all lvl 30 and nothing above 98,5% up to now (one is non cheating but i use the bot to analyze the IV)

**Comment by jackrose01** [comment]
May be you want to check it : https://www.facebook.com/photo.php?fbid=10205398345996637&set=a.2734238933698.97147.1789077094&type=3&theater

**Comment by Ar1i** [comment]
Update, and it works. Disable hold pokemons which can be evolved.
