### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by BOYSA** [Ar1i/PokemonGo-Bot#3651]
Hello if you're interested here all the sprites of the game !
Bonjour si sa vous intéresse ici tous les sprites du jeu !
[Sprites.zip](https://github.com/Ar1i/PokemonGo-Bot/files/457193/Sprites.zip)

**Comment by edale2** [comment]
Beautiful! Honestly, I was about to pull the sprites from the old version of the bot after starting up the new one, don't like the chibified look.

Just extract it into the sprites folder in the bot and overwrite everything, then click refresh in the GUI, no restart needed.

There is a bit of a distortion on some of them
![geo](https://cloud.githubusercontent.com/assets/20962345/18299653/84ca438a-7490-11e6-9ef7-30173a8fc8be.jpg)
I have a few batch editing tools for photos, so if anyone can tell me the exact display dimensions of the bot, I _might_ be able to get everything displaying with this sprite set without distortion, no promises though.

**Comment by ExplodingCore** [comment]
Here you go. I resized all sprites to 200x200 while keeping the proportions. Also fixed some missing pokemon.

(for some reason, github won't allow me to upload any archive file type even .zip, so sorry for external link)
http://www.xup.in/dl,20741369/Sprites_by_xCore.rar/

For some reason though the sprites look very strange at least for me.
It's like the pokemon list uses the wrong color depth or something. 

![pokelist_sprites](https://cloud.githubusercontent.com/assets/22051355/18310743/8ee373c6-7500-11e6-9de2-1a041c52b214.PNG)

Anybody knows how to fix this?

**Comment by edale2** [comment]
Well, guess I don't need to pull out my batch editing tools. Looks GREAT.

It's not the color depth, it's pixelation from the resizing, completely normal. To fix it you need to use a more inclusive photo editor, such as adobe photoshop, to do the resizing (and possibly some touchup work once it's resized).

**Comment by ExplodingCore** [comment]
I used photoshop. Just deleted all the exif data ;)

Well, resizing them all would be easy. Just need the right dimensions. 

So, the new default sprites are 128x128. Just resized all the sprites. Still looks the same though.

**Comment by edale2** [comment]
If you already used photoshop, then it's a case of them simply being shrunk too far, and individual touch-up work is the only fix.

**Comment by ExplodingCore** [comment]
Well, maybe someone with the required knowledge could modify the GUI/Pokemon List to display higher quality pictures /w more colors.

For the time being I tweaked the sprites a bit to make them look better in the GUI and am quite satisfied with the outcome.

Screenshot for comparison
![pokelist_sprites_v2](https://cloud.githubusercontent.com/assets/22051355/18314836/0991cece-7515-11e6-9845-c16fc0e06f30.PNG)

You can download them here (Again, sorry for external link. I can't upload .zip files. Don't know why.)
http://xup.in/dl,20130943

**Comment by BOYSA** [comment]
sorry guys my personal I just managed to get her and I think its not bad
