### ISSUE TITLE
how hard could this be

### ISSUE THREAD

**Issue by toxic189090** [Ar1i/PokemonGo-Bot#3653]
how hard would it be to add in a feature to draw your own route to walk?

**Comment by Hydro420** [comment]
That would be an awesome feature.

**Comment by MTK4355** [comment]
I'm playing with that. Not easy, but doable. Not as much time on my hands as I had last week, but I'll try to get it working.

**Comment by Logxn** [comment]
Not hard.
Thats why its included :)

**Comment by Theseppinator** [comment]
Where is it then?

**Comment by Logxn** [comment]
Open Map, click a marker. Voila

**Comment by toxic189090** [comment]
thanks so much Logxn
