### ISSUE TITLE
Not function auto transfer duplicate pokemons

### ISSUE THREAD

**Issue by kickz** [Ar1i/PokemonGo-Bot#3654]
After last update not function duplicate pokemons.

**Comment by bkrandy** [comment]
they could be at a high IV %, which by default is 90 and so it wont transfer those

**Comment by Hydro420** [comment]
IV - CP - Do Not Transfer List... Or just be patient as at times the bot does not do it right away.

**Comment by Xelwon** [comment]
Same problem as here
https://github.com/Ar1i/PokemonGo-Bot/issues/3659

Currently there are two differents percents, one based on IVs and other based on maximun CP of each level.

The logic of game is currenly using CP percent, it is in the listview on the last column with header "% CP"

Prease, review it.

**Comment by GiaPune** [comment]
The newest can not auto Transfering.
the older could...

**Comment by Logxn** [comment]
Yes it can
