### ISSUE TITLE
how to solve this problem ??

### ISSUE THREAD

**Issue by luanzao** [Ar1i/PokemonGo-Bot#3658]
![asdsadasda](https://cloud.githubusercontent.com/assets/22042542/18298123/2093576e-7484-11e6-932b-0b901e62a230.png)

**Comment by DomeSs97** [comment]
Change IP, run only 1 bot for IP..

**Comment by Logxn** [comment]
Either that or reset your config.

**Comment by luanzao** [comment]
as it does to reset my settings?

**Comment by luanzao** [comment]
You can teach me step by step ?
