### ISSUE TITLE
What is the real IV!?!? 

### ISSUE THREAD

**Issue by numbsoul26** [Ar1i/PokemonGo-Bot#3659]
I wonder what is the right IV calculation?!?!
![capture](https://cloud.githubusercontent.com/assets/22042687/18298190/439dd792-74e9-11e6-80eb-0ccd50321d69.PNG)

Also, Device doesn't save, always gets back to galaxy6.

Thanks

**Comment by k0ut4li4n0s** [comment]
agree with @numbsoul26 about the device that doesnt save and i have to add that maybe need to add some random serial number on device and save to that so it seems like a unique one

**Comment by Xelwon** [comment]
about IV calculation, I explaned it on other thread. The % that you have seeing on the console is calculated based the current cp and maximun cp for his current level, you can see it on last column at the list view.

The % that you can see before IVs is calculated based IVs. 

I have done a modification to use this last % on all places, but it is pending to evaluate yet.
