### ISSUE TITLE
nothing ist working anymore Help pls :)

### ISSUE THREAD

**Issue by Euskater2** [Ar1i/PokemonGo-Bot#366]
i downloaded the new package and installed everything new but nothing works

here is a screeshot : http://puu.sh/qjEaJ/3d8fd3f74a.png

could anybody help please ?:) 

ps: using the console through Visual Studio.

**Comment by StyxHell** [comment]
In Central Park ?

**Comment by Euskater2** [comment]
yes

**Comment by Euskater2** [comment]
also in germany doesnt work

**Comment by StyxHell** [comment]
Also bei mir funktioniert alles, wenns nich im central park is :p 
Etwas weiter unter dem Central Park funktioniert wieder alles..

**Comment by Euskater2** [comment]
ah okei kannst du mir sagen wo ? .. eh ich glaube ich habe einfach irgendwas falsch eingestellt

**Comment by jackrose01** [comment]
may be you need to change it to 1000

i dont know, i have some problem, but when i change it to 1000 i can reach pokestops that under 500 hahahha

**Comment by Euskater2** [comment]
auch wie in den ordner eingestellt hab und so .. könntest du mir sagen wie du es gemacht hast in 5 sätze oder so xD wenns keine umstände bereitet

**Comment by StyxHell** [comment]
With coordinates and Range 5000 everything works fine for me in New York: 40.715466, -74.005114
Walking speed 200. Works flawless. 
Werd mal wieder auf englisch umsteigen, dann is mehr leuten geholfen

**Comment by Euskater2** [comment]
@jackrose01 you mean 1000  radius ? ...and well now i got a notification that tells me a new version uipdate is avalaible .. but dont know how to update ... xD

**Comment by jackrose01** [comment]
just download the new update dude :p hahahhaa

**Comment by StyxHell** [comment]
Just download the newest version from here. 
Start it, make the adjustments and start it again. Thats the Update

**Comment by Euskater2** [comment]
okei nothing to compile or like that ? xD .. well i´ll try then

**Comment by TMaddox** [comment]
@StyxHell 200 walking speed doesnt give you a softban ?
how much xp/hr do you get (luckyegg? / smoke?)

**Comment by UltraVLT** [comment]
musst nur die rar im build only ordner laden,und die datein ersetzen,funzen direkt und übernehmen deine setts meist

**Comment by Euskater2** [comment]
okei dankeschön

**Comment by StyxHell** [comment]
@TMaddox nope, actually i turned up to 300 just to test it. No softbans so far, just got one for jumping from germany to new york. 
Had it running for 24 hours with 200, nothing happend. 
With smoke i get here in new york like 81k xp/hour

**Comment by TMaddox** [comment]
@StyxHell thank you i will try it out (second acc too)

Grüße aus Österreich

**Comment by StyxHell** [comment]
@TMaddox Alles klar. Hab das Gefühl hier wird nich nach laufgeschwindigkeit gebannt so lange man die Strecke zurücklegt während man eingeloggt ist. 

Grüße aus Deutschland :p
