### ISSUE TITLE
After last build all config and other setup wont get read (hole cofing folder broken to read=?)

### ISSUE THREAD

**Issue by Kidnub** [Ar1i/PokemonGo-Bot#3660]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

my problem is that the last built is not reading right at the start the configfolder ....
( it is not a big issue ) i even did delete the hole bot folder once but no change still broken read at the configfolder ...
all infos get not read and set right in the gui ... i had to resetup every gui tab ...
(gui.cs.line270 so the error window say..)
also the bot is using incubators even if you dont have setup up them in the gui....
also auto break is active again ....... strange but np i try to reconfig my bot gui once more now ;(
http://www2.pic-upload.de/img/31642913/Unbenannt1.jpg
if i need to make screenshots from the gui pls tell me will do it np XD

**Comment by Kidnub** [comment]
next i did rollback to the old version ;( (Latest Build - 3.09 14.31.rar) cause that one is really stable for me ;(

**Comment by Logxn** [comment]
@Kidnub 
Just use the new version and redo your config.
Thats all you need to do.

Can you provide a screenshot?
Because it works fine for me. No errors yet

**Comment by Xelwon** [comment]
It happened to me too.
I think, it is used to deleted option for german names. As this option is not saved now, all options back it, was displaced on config file.

**Comment by Logxn** [comment]
redownload
