### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Blubb123** [Ar1i/PokemonGo-Bot#3661]
Sorry, but I did not understand the update.
If I unpack the latest pokemonGo-Bot-master.zip, it has a complete different file structure than my old 1.1.1.9 release.
 I only can find 1.1.1.9 on the Release Site but app told me to update to 1.1.24. But I could not find tihs version, thats why I downloaded the master.
Did I overseen something? Can someone please help me?
Thank you in advance.

**Comment by Fata1-3rr01z** [comment]
Unzip the rar file in the folder "Builds-Only". Go to your old version and copy the entire Config folder and paste it to the new extracted directory. Run the executable file there and you're good to go. You will have to do this every time you update though. You can also paste the new files on top of the old one.

**Comment by Fata1-3rr01z** [comment]
Just updated today, apparently there have been changes to the config structure that makes the old config not work. Just don't copy the config folder for now and manually set the values again.

**Comment by Kidnub** [comment]
i use just an old version again until we have again a stable version XD but thx to arl1 logxn and MTK4355 you all doing a greate job ((but maybe you all should take one day a break or two on coding to refresh your self )

**Comment by Blubb123** [comment]
Thanks Fata!

**Comment by Logxn** [comment]
DO NOT use old versions.
Simply re-do your config.
The new version is stable
