### ISSUE TITLE
Pokesnipers Sprites

### ISSUE THREAD

**Issue by TxShack** [Ar1i/PokemonGo-Bot#3663]
## I already use them and they look nice. If you want to use it here they are.
![preview](https://cloud.githubusercontent.com/assets/21256298/18304126/9d3ea348-74ae-11e6-85ad-04bc1d35aec1.png)

[Sprites.zip](https://github.com/Ar1i/PokemonGo-Bot/files/458543/Sprites.zip)
https://www.virustotal.com/es/file/6ba5a6d67a957bfe859db2dae4291ac96073e377b790d91fa15af9a1528ab767/analysis/1473234933/

**Comment by Logxn** [comment]
Maybe with a pull request :b
