### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by Th3D0ct0r** [Ar1i/PokemonGo-Bot#367]
I get this message with Build 30.07 13.10.  Got this message in the build before and saw that #36 already mentioned it, but wasnt fixed. 

![exception](https://cloud.githubusercontent.com/assets/9108410/17270096/b44f813c-565a-11e6-8e81-e2682b3d387a.jpg)

`[13:33:56] Starting again.. But waiting 10 Seconds..
[13:34:06] Exception: System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, Requests[] customRequests) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 19.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, RequestType[] customRequestTypes) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 47.
   bei PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:Zeile 182.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 127.
[13:34:06] Starting again.. But waiting 10 Seconds..`

**Comment by UltraVLT** [comment]
Download the latest one

**Comment by Th3D0ct0r** [comment]
Downloaded, testing now

**Comment by Th3D0ct0r** [comment]
Same as Build 30.07 13.10 . Still get this message.

`[13:51:49] Starting again.. But waiting 10 Seconds..
[13:51:59] Exception: System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, Requests[] customRequests) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 19.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, RequestType[] customRequestTypes) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 47.
   bei PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:Zeile 182.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 127.
[13:51:59] Starting again.. But waiting 10 Seconds..`

**Comment by Oguzcan13** [comment]
I think that your user name is the password

**Comment by Oguzcan13** [comment]
Personally I have that install the build

**Comment by Th3D0ct0r** [comment]
I am also on 30.07 13.30 , but still get this. What you mean by my username is the password?

**Comment by Th3D0ct0r** [comment]
This happens when server are unstable. For exmaple: I got this in Central Park where the server is unstable, but at the rockerfella center it works.

**Comment by Ar1i** [comment]
Take a deeper look later, but atm it works so everything is fine
