### ISSUE TITLE
WE HAVE A DISCORD

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#3670]
Many of you have asked for a place to post suggestions and or talk with other members.
Since these requests have been going on for a while... here we are!

We have a discord! Everyone can join, everyone can be a part of this project. :)
https://discord.gg/phu3GNN

I'll be waiting for you!

**Comment by NevilleNg** [comment]
bro~!~ help me.. my id cant join your discord~!~am i get banned
