### ISSUE TITLE
.NET Error (New Update)

### ISSUE THREAD

**Issue by Hydro420** [Ar1i/PokemonGo-Bot#3671]
.net error with new update.

![untitled](https://cloud.githubusercontent.com/assets/20824888/18311396/b0cfb116-74c9-11e6-9c15-37b2e277f752.png)

**Comment by Ar1i** [comment]
try to delete all the dll's. you only need the exe and the folders.

**Comment by Hydro420** [comment]
Will try now

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18312029/31979de2-74cd-11e6-9df0-53c1ef5ca607.png)

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18312073/62b94740-74cd-11e6-957a-0f29a2b09de0.png)

**Comment by Logxn** [comment]
LOL.
Redownload => Builds only => Unpack the rar.
There is only 1 EXE.

**Comment by Ar1i** [comment]
Delete everything expect the folders. Then put the exe in and it should work.

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18312460/86f33ad8-74cf-11e6-9a39-f5c9315c0094.png)

**Comment by Logxn** [comment]
click on details and paste it in here please

**Comment by Hydro420** [comment]
Ok I got it working now - it just kept giving me errors when I would copy/paste over my config file so I wouldnt have to re-type everything.. Just doing it the long way now.

**Comment by Logxn** [comment]
But if you save the config... does it get saved an reloaded when you restart the bot?

**Comment by Hydro420** [comment]
No

**Comment by Logxn** [comment]
Thats strange. It does for me with the newest version

**Comment by Hydro420** [comment]
Let me do it again and make sure. (which is why i delete comment)

**Comment by Hydro420** [comment]
Omg I just got myself banned lol... Started bot and the location was totally off - forgot to change location.. fuk i hope they dont slap me with a ban.... Wont login to that account for a few days ...

**Comment by Hydro420** [comment]
Anyway the setting do remain the same when attempting to restarts bot - so all is good.

**Comment by Logxn** [comment]
Good to know
