### ISSUE TITLE
Google map route error

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3679]
--------------------------------------------
 Unhandled Error occurred when getting route[ STATUS:NOT_FOUND ERROR MESSAGE:] Using default walk method instead.

--------------------------------------------

this appears when i use my google key for the routing
+ sth else, it shouldnt follow the roads with the google routing ? (sorry if already asked that )

**Comment by Logxn** [comment]
@MTK4355

**Comment by MTK4355** [comment]
This means that google was unable to determine a path between the bot's current location and the destination lat and long.. Does this happen everywhere for you?

**Comment by k0ut4li4n0s** [comment]
Hmm it was good yesterday in the same point , today with the new build happened. I was good in Greece and San Fransisco(which currently do that). I can check back in Greece again tomorrow though cause i dont wanna trigger the soft ban

**Comment by MTK4355** [comment]
I just added the logging to diagnose why sometimes the route was not followed. Possibly it was happening before but you didn't notice?

**Comment by MTK4355** [comment]
Does it normally follow the route, and throw this only sometimes?

**Comment by k0ut4li4n0s** [comment]
It never follow the route :P but at least it didnt leave the preset range , it was still going through buildings and through sea :/  and today gave me the error

**Comment by Hydro420** [comment]
The key is most likely no good - as I had same issue. Used new key and it was fine.

**Comment by k0ut4li4n0s** [comment]
@hydro420 Does the key have expire date ?

**Comment by k0ut4li4n0s** [comment]
Changed the key and now says "Request Failed! Bad API key?"

**Comment by MTK4355** [comment]
Not the only one seeing this. I'll try to add more verbose logging of the error so we can find out what is going on.

**Comment by k0ut4li4n0s** [comment]
@MTK4355 any news for the routing ? updated bot. Did you add something that we can make our own route ? Map look diffrent

**Comment by Logxn** [comment]
yes

**Comment by k0ut4li4n0s** [comment]
How to use it then ? Tried to click on pokestops for routing but didnt work

**Comment by MTK4355** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/3700
