### ISSUE TITLE
1.1.2.7 method not found

### ISSUE THREAD

**Issue by mcferson** [Ar1i/PokemonGo-Bot#3680]
Hi there : three problems here. 1) there is only the PokemonGo.RocketAPI.Console.exe in archive, 2) you have deleted previous releases (bad idea, nobody can use previous version in case of the last is broken) 3) this last version is broken... See the error below :
`System.MissingMethodException: Méthode introuvable : 'Boolean PokemonGo.RocketAPI.ISettings.get_logManualTransfer()'.
   à PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Logxn** [comment]
1. Redownload
2. Do not have anything in the folder. (Create a new folder for the bot)
3. Drag the ZIP in there
4. Unpack

**Comment by mcferson** [comment]
Ok !
Still only the exe, but ok. thanks !

One question : how can i make a request ?

**Comment by mcferson** [comment]
Yes thanks !
