### ISSUE TITLE
Lost files in latest build archive (07.09 21.26)

### ISSUE THREAD

**Issue by caraoge** [Ar1i/PokemonGo-Bot#3683]
Hey,
there is only the "PokemonGo.RocketAPI.Console.exe" file available in the latest build archive (07.09 21.26).

After updating my bot with this latest *.exe file i always get this error:

> System.MissingMethodException: Methode nicht gefunden: "Boolean PokemonGo.RocketAPI.ISettings.get_logPokemons()".
   bei PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)

Can you please rebuilt the archive?

Thank you for your work!

Br,
Michael

**Comment by Logxn** [comment]
Nein ist richtig so.

Bitte mach nen neuen Ordner und unzip das da.
Dann geh in Builds only und unzip den nochmal.
Dann starte die exe.

grüsse :)

**Comment by caraoge** [comment]
Danke.
Hat funktioniert ;-)
