### ISSUE TITLE
Issue with item recycle

### ISSUE THREAD

**Issue by lovakosh** [Ar1i/PokemonGo-Bot#3684]
There is an issue with recycle items, 
the bot keeping the items instead of recycle it when over reach the amount that was configured.
The recycle option only works when I close the bot and reopen it, and then continue keeping the items until the next time I close and reopen the bot.
Any suggestions?
Thanks

**Comment by MTK4355** [comment]
Might have moved the recycle check outside of the main loop. Thanks for the feedback, I'll check it out.
