### ISSUE TITLE
Faster farming?

### ISSUE THREAD

**Issue by Araben** [Ar1i/PokemonGo-Bot#3685]
hey. i just started marking that my farming is too bad now, like im getting5000 or 10000 max everyhour with my walking speed as 50km/h, any tips and ideas to make it faster? even if it was a bit more dangerous.

my location is santa monica tho.

-----------------------------
#update2 
-----------------------------

thanks for your answers , but i when i said faster so i meant that 5000xp every hour is really slow in santa moncia, whats the options to maker it faster? like what options reduce the speed?

thanks again

**Comment by Logxn** [comment]
I wouldn try pushing your luck against niantic

**Comment by LeDudeGolfer** [comment]
Don't push too much bruh, it would cost you everything. No need to rush.

**Comment by TeamRedd** [comment]
50km is already pushing it , just saying =/

**Comment by Zodice** [comment]
100 000/h is just enormous ! You can't do like this and to not be banned.

**Comment by Georgiexoh** [comment]
What do you guys reckon is a good speed to have? 10km/h? 15? 20?

**Comment by MTK4355** [comment]
I like 10 with a min walk speed of 5 and random reduce speed checked.

**Comment by Zestiria00** [comment]
If u really want to go 200km starting at lvl 1. I had 5 accounts before and only two got banned at lvl 25 after that i decided to go normal and now i have 3 lvl 30+ .
