### ISSUE TITLE
...

### ISSUE THREAD

**Issue by luanzao** [Ar1i/PokemonGo-Bot#3688]

**Comment by Logxn** [comment]
I am hiding.
There is only the EXE.
Open it

**Comment by luanzao** [comment]
how to download the full bot ?

**Comment by dieter90210** [comment]
Just run the exe and all the required folders will be created.

**Comment by deadelf0** [comment]
The new pokemon icons are so, cool.

**Comment by Logxn** [comment]
h3h3
