### ISSUE TITLE
No Pokestops in 5000 meters....

### ISSUE THREAD

**Issue by Titus1987** [Ar1i/PokemonGo-Bot#369]
Hey guys the console says me that no pokestop is in 5000 meters (Central park ) any ideas? sry for my bad english iam german

**Comment by StyxHell** [comment]
Jup, liegt wohl an den Niantec Servern, schon haufenweiße Issues dazu offen, etwas weiter unten bei Two Bridges funktioniert alles wunderbar, liegt anscheinend am Central Park.

**Comment by Ar1i** [comment]
Andere Position nehmen.
