### ISSUE TITLE
Api translation

### ISSUE THREAD

**Issue by dieter90210** [Ar1i/PokemonGo-Bot#3691]
How can i translate the console information? i wish to translate everything to spanish.

**Comment by cicklow** [comment]
Puedes descargar Visual Studio Comunity y abrir el proyecto, asi podras traducir todo a español, aunque tambien lo he pensado de traducir a español, pero hay que armar una base de traducciones, no solo a español, sino tambien los demas idiomas... Pero no es imposible, sino tedioso ir buscando los textos en todo el codigo!

**Comment by dieter90210** [comment]
Mmmm si es hardcoded si que es tedioso

**Comment by Logxn** [comment]
me no understando spanish, brazilian idk?
