### ISSUE TITLE
I want unban Botton on New Bot version.

### ISSUE THREAD

**Issue by ToeyKK** [Ar1i/PokemonGo-Bot#3696]
Unban botton is very good for use

**Comment by Logxn** [comment]
cool. I want a lamborghini aventador

**Comment by jay-2-rome** [comment]
Sure, it was cool to use...

But it doesn't work anymore. Sorry friend.

**Comment by ToeyKK** [comment]
I'm teleport catching pokemon rare  unban botton very good for use
