### ISSUE TITLE
Debug Report

### ISSUE THREAD

**Issue by dreamboatcap** [Ar1i/PokemonGo-Bot#3697]
<img src='https://s18.postimg.org/otxvkk6jd/Capture.jpg' border='0' alt='Capture'/>
What is that debug line means?

**Comment by Logxn** [comment]
Ignore it. I will remove it

**Comment by AiVo7z** [comment]
cant update my bot atm. Isit something we can ignore without the risc of getting banned? I've got not even a slight clue what that error means.
