### ISSUE TITLE
Just A Simple Question

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3698]
Do you guys think is it okay if we do evolve Pokemons while the bot still running? I mean while the bot find Pokestop or catch Pokemons?

Or, we have to do Pause Walking then we start evolve Pokemons?

**Comment by Logxn** [comment]
We will add the option to stop walking

**Comment by erickrisnarinjaya** [comment]
Thanks pal ;)
