### ISSUE TITLE
Missing Pokeball Throw

### ISSUE THREAD

**Issue by bjornberfelo** [Ar1i/PokemonGo-Bot#3699]
I would to have option to miss pokeballs, if you dont have many pokestops arround the player can run out of pokeballs... Can we have a option to not mis pokeballs?

**Comment by nasierache** [comment]
just simple question.. if you playing pokemon in real life, will you manage to throw it directly on target with zero missed percentage?

**Comment by bjornberfelo** [comment]
No Sir, but sometimes you get 5/4 misses in a row... To answer your question, no I dont allways hit. But it was a request, it's up to the users to use it or not. But thank you for the answer

**Comment by thejundguy** [comment]
or maybe have an option to set maximum misses?

**Comment by bjornberfelo** [comment]
That would also be a option

**Comment by MTK4355** [comment]
You cannot have 5 missed throws. We already cap it at three. Might include a toggle at some point but it's not going to be high on the list.

**Comment by bjornberfelo** [comment]
Thank you Sir

**Comment by MTK4355** [comment]
No problem! You can always disable catching pokemon for a while and just farm stops to stock up on pokeballs if you find you are often running out.

**Comment by Logxn** [comment]
@MTK4355

how about min. misses and max. misses?
then random

**Comment by ExplodingCore** [comment]
@Logxn 

That would be a nice solution.
Configurability is key :smiley:

**Comment by MTK4355** [comment]
Sure, if I haven't found something more interesting by the time I clean up the routing and finish the transfer and evolve queuing I'll set this up.
