### ISSUE TITLE
Dont use normal Pokeballs anymore and Automatic Incubator using

### ISSUE THREAD

**Issue by NoticeMeSenpaiPLS** [Ar1i/PokemonGo-Bot#370]
Thanks for all the good work :)

Is it possible to get maybe a setting which allows to stop using normal pokeballs? 
I got more than enoug great or ultraballs, which most of the time didnt got used, couse there are a few pokeballs which are left from the last pokestop.
I lost a few pokemons while catching couse of this. A Option to fix that would be very nice :)

And i wonder why there is nothing to put eggs autmaticly into incubators if there are some of them unused. Dont know it thats possible to write, but if it would be very awesome couse i really wanna have some 10km eggs to get awesome pokemons ^-^
Thanks for reading my Hopes :DD

**Comment by shuksieno123** [comment]
it would be great :)

**Comment by globsch** [comment]
`return balls.OrderBy(g => g.Key).Skip(1).First().Key;`
logic.cs line 552
replace it and it should do the trick (untested!)

**Comment by Ar1i** [comment]
Just set normal pokeballs to 0, egg wont work with that api at the moment
