### ISSUE TITLE
New Button 'IV to Nick'

### ISSUE THREAD

**Issue by xalex51** [Ar1i/PokemonGo-Bot#3704]
Hello all, I'm french
Please can you tell me what is the use of the new button 'IV to Nick'?

**Comment by Xelwon** [comment]
It if for changing pokemon nicknames to put in it  Individual Values and its percent.

**Comment by toxic189090** [comment]
When I click it it says "after doing this it cannot be undone" and it doesn't change the name for me.

**Comment by Xelwon** [comment]
It is not put in a column.
Put the mouse over the name and wait several seconds, a tooltip appears and you can read catch time and nickname.

Or open Pokemon go app, and see your pokemons.

**Comment by Logxn** [comment]
awnsered
