### ISSUE TITLE
PokeStop not found

### ISSUE THREAD

**Issue by Oguzcan13** [Ar1i/PokemonGo-Bot#371]
http://prntscr.com/bzfmpv

**Comment by NerdisDev** [comment]
same

**Comment by daneil1999123** [comment]
same

**Comment by Oguzcan13** [comment]
I guess it is the pokemongo servers that have a problem

**Comment by StyxHell** [comment]
Central Park ?

**Comment by Oguzcan13** [comment]
es surely it must be the central park

**Comment by MarkShark91** [comment]
Same here...I think we got banned

**Comment by Oguzcan13** [comment]
Pokemongo softban fact that no ban has life

**Comment by StyxHell** [comment]
Nah, no bans. Some way down at Two Bridges in New York everything is working fine.

**Comment by MarkShark91** [comment]
I tried with my jailbroken phone...all the pokestops not worked and all pokemon went away too because we got softbanned (4h maybe)

**Comment by Ar1i** [comment]
Choose an other location.

**Comment by Oguzcan13** [comment]
Alternatively you can change the coordinates
