### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3713]
Is it possible to catch lured pokemon without breaking at the pokestop? Thanks.

**Comment by AiVo7z** [comment]
Well that doesn't make much sense to me. Maybe i didn't understand it, but if you run your route and one pokestop is boosted with a luremodul, you'll Encounter those as soon as you move towards it and catch 'em all. We just wanted to have the Feature to have the bot having a break bcoz it's more human-like. 
Maybe you meant if there should be an Option that the bot rather aims for Lure pokestops than "running just around"
