### ISSUE TITLE
Only one file in Builds-Only rar?

### ISSUE THREAD

**Issue by Guazzett** [Ar1i/PokemonGo-Bot#3714]
Hi, in archiv is only exe file. Mising other files.

**Comment by Araben** [comment]
all the files will appear when you first run the exe.

**Comment by Guazzett** [comment]
i see only error message: system.MissingMethodException

**Comment by Logxn** [comment]
1. Create new folder
2. Download ZIP and extract it in the new folder
3. Go to the Builds-Only folder after extraction
4. Extract the ZIP there
5. Start exe
6. Have fun
