### ISSUE TITLE
Help Needed, Please.

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3716]
![2016-09-09_002934](https://cloud.githubusercontent.com/assets/20828057/18357712/9359831c-7624-11e6-9983-d645adf8cfa0.png)

After I updated to the newest version, I cannot set for long and lat in the maps. As you guys can see the image above that I'm showing. Please help for anyone knows this issue. Thanks. Appreciate it.

**Comment by JuanEstrada** [comment]
if you open the map in a tablet try to use the biggest resolution posisible. when that happen to me, i only close it and then open again. keeptrying

**Comment by Logxn** [comment]
Resolution is fucked up

**Comment by erickrisnarinjaya** [comment]
@Logxn Any solutions for this pal?

**Comment by Logxn** [comment]
Find this slider in your resolution settings: http://i.imgur.com/vAyOXBx.png
and set it to 100%
