### ISSUE TITLE
[Feature] Serverstatus

### ISSUE THREAD

**Issue by NerdisDev** [Ar1i/PokemonGo-Bot#372]
A friend of me written a PokemonGo Server Status API
https://go.jooas.com/status 
you could use it in the bot :)!

**Comment by Ar1i** [comment]
nice, will add that probably

**Comment by Oguzcan13** [comment]
Pokemon go servers it's open

**Comment by Oguzcan13** [comment]
good idea

**Comment by Oguzcan13** [comment]
can you put rental search bar?

**Comment by Logxn** [comment]
@Ar1i 

Hab bisschen gearbeitet für dich c:

`using System.Net;
using System.Web.Script.Serialization; //Verweis: System.Web.Extensions.dll`

`var clientx = new WebClient();
            clientx.Headers.Add("user-agent", "#Random");
            var jsonString = clientx.DownloadString("https://go.jooas.com/status");`

            if (pokeStops.Count() == 0)
            {
                PokeService data = new JavaScriptSerializer().Deserialize<PokeService>(jsonString);
                Logger.ColoredConsoleWrite(ConsoleColor.Red, "We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying..");
                Logger.ColoredConsoleWrite(ConsoleColor.Red, "Server Uptime: " + data.go_uptime_hour.ToString() + "%");
                await ExecuteCatchAllNearbyPokemons();

            }`

`        class PokeService
        {
            public bool go_online;
            public double go_response; //Time in seconds
            public double go_idlle; //Time in seconds
            public double go_uptime_hour; //Percentage
        }`

Das muss alles bei Logic.cs rein c:
Je nach dem was du haben willst musst es anpassen

**Comment by Logxn** [comment]
This is how it would look like if you'd put it to the Playerstats:
http://prntscr.com/bzg0n4

**Comment by NerdisDev** [comment]
@Logxn Geil :) Sieht gut aus :)!

**Comment by Logxn** [comment]
Und das gleiche mit pokemon trainer club :b 
http://prnt.sc/bzgbzs

**Comment by NerdisDev** [comment]
@Logxn Gefällt mir sehr :)!

**Comment by Logxn** [comment]
@NerdisDev Ich denke das entspricht deiner erwartung?
Wusste nur nicht wo ich das hinpacken sollte. ^^ 

Mal schauen ob @Ar1i meine Methode übernimmt oder seine eigene anbaut =)

**Comment by NerdisDev** [comment]
@Logxn Jap :). Hab das btw. als App gemacht :D.

**Comment by K0zY** [comment]
how i can use it logxn?

**Comment by Logxn** [comment]
@NerdisDev 
Als App ist das auch ziemlich easy zu machen.
Vorallem mit so nem Sound wenn die Server abschmieren ^^ 

@K0zY
Its not included in the newest version yet.
I made this by myself. Maybe it will be added ;)

**Comment by K0zY** [comment]
@Logxn 
yeah but i sow someone pic's using it with your credits xD
so can you made it? like downloadable kkk for noobs XD

**Comment by Logxn** [comment]
That was fucking me on highminded :D

**Comment by K0zY** [comment]
kkkkkkk
and if u can check :fixed location issue :P

**Comment by Logxn** [comment]
@NerdisDev 

Ar1l hat den Source erhalten =) 
Wird wahrscheinlich in der nächsten Version dabei sein

**Comment by Ar1i** [comment]
@NerdisDev baue ich gerade ein :)

**Comment by Ar1i** [comment]
Your friend can make a counter orso, would be interesting to see how many requests he is getting from bot users. Used special user agent: PokegoBot-Ar1i-Github

**Comment by Ar1i** [comment]
@NerdisDev ^
