### ISSUE TITLE
Metod not found - Latest version

### ISSUE THREAD

**Issue by MordorGames** [Ar1i/PokemonGo-Bot#3724]
![print](https://cloud.githubusercontent.com/assets/22083197/18362767/80bcd87c-75dd-11e6-8748-2ee1f8b328f5.png)
When opening the program is showing this error:
************** Texto de Exceção **************
System.MissingMethodException: Metod not found: 'Boolean PokemonGo.RocketAPI.ISettings.get_UseBreakFields()'.
   em PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   em System.Windows.Forms.ContainerControl.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em System.Windows.Forms.Form.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblies Carregados **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    Versão do Assembly: 1.1.3.0
    Versão do Win32: 1.1.3.0
    Base de Código: file:///C:/Downloads/Programas/Pokemon/BotPokemonGo/PokemonGo.RocketAPI.Console.exe
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.34250 built by: FX452RTMGDR
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.36337 built by: FX452RTMLDR
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.36350 built by: FX452RTMLDR
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Pokemon.Go.Rocket.API
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Downloads/Programas/Pokemon/BotPokemonGo/Pokemon.Go.Rocket.API.DLL
----------------------------------------
POGOProtos
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Downloads/Programas/Pokemon/BotPokemonGo/POGOProtos.DLL
----------------------------------------
PokemonGo.RocketAPI.Logic
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Downloads/Programas/Pokemon/BotPokemonGo/PokemonGo.RocketAPI.Logic.DLL
----------------------------------------
System.Device
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Device/v4.0_4.0.0.0__b77a5c561934e089/System.Device.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.0.30319.36213 built by: FX452RTMLDR
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by Logxn** [comment]
#3725
