### ISSUE TITLE
Method not found / NET ERROR

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#3725]
GERMAN:
1. Neuen Ordner erstellen
2. ZIP runterladen und da entpacken
3. In den Ordner Builds only gehen
4. ZIP dort entpacken
5. Exe starten (Ja, es ist normal, dass da nur eine exe drinn ist)
6. Have fun
Wenn ich nochmal jemand sehe der deswegen nen Issue aufmacht, bei dem wirds einfach geschlossen ohne Antwort. Punkt!

ENGLISH:
1. Create new Folder
2. Download the ZIP and unpack it there
3. Go in to the folder Builds-Only
4. Unpack the zip
5. Start the EXE (YES, its normal that there is ONLY an exe)
6. Have fun.

If I see any more of the "Method not found" or ".NET" Errors I will close them without awnsering!

**Comment by kreian** [comment]
Not found pokestops in the radio, i was farm in this area but now no detect this pokestops. i have all the steps of the method, yet.

![image](https://cloud.githubusercontent.com/assets/21061474/18399554/26136e76-7697-11e6-9097-e0d3ede4b4b4.png)

![image](https://cloud.githubusercontent.com/assets/21061474/18399572/38c14a0c-7697-11e6-92c8-c1faaeec62e9.png)
