### ISSUE TITLE
france.json with a good translate

### ISSUE THREAD

**Issue by HeinTouchable** [Ar1i/PokemonGo-Bot#3727]
Hello , I want to help the progress of the bot for the French language
"AccountType": "Type de compte:",
	"Username": "Nom d'Utilisateur",
	"Mot de passe": "Mot de passe",
	"LocationSettings": "Paramètres de localisation",
	"Speed": "Vitesse",
	"MoveRadius": "Rayon",
	"Mètres": "mètres",
	"StartFromDefaultLocation": "Démarrer depuis la localisation par défaut",
	"BotSettings": "Paramètres Bot",
	"AutoTransferDoublePokemon": "Transfert Pokémon en double",
	"MaxDupPokemon": "Max Pokemon en double.",
	"MaxCPtransfer": "Max CP pour transférer.",
	"MaxIVtransfer": "Max IV pour transférer.",
	"TelegramSettings": "Paramètres de télégramme",
	"Infoline1": "Ce bot est totalement gratuit et Open-Source, si vous avez payé pour ce bot, demandez un remboursement immédiat",
	"Infoline2": "Chaque fois que vous trouvez quelque chose lié à 'Pokecrot', il s'agit d'un plagiat",
	"MaxPokeballs": "Max Pokéballs ",
	"MaxGreatballs": "Max SuperBalls",
	"MaxUltraballs": "Max HyperBalls.",
	"MaxMasterballs": "Max MasterBalls.",
	"MaxRevives": "Max Rappel.",
	"MaxTopRevives": "Max Rappel Max.",
	"MaxPotions": "Max Potions.",
	"MaxSuperpotions": "SuperPotions Max.",
	"MaxHyperpotions": "Max HyperPotions.",
	"MaxToppotions": "Max Potions Max .",
	"MaxRazzberrys": "Max Baie Framby.",
	"TotalCount": "Nombre total",
	"PokemonNotToTransfer": "Pokemon - Ne pas Transférer",
	"SelectAll": "Sélectionner tout",
	"PokemonNotToCatch": "Pokemon - Ne pas capturer",
	"PokemonNotToEvolve": "Pokemon - évoluer",
	"Saveconfig": "Enregistrer les paramètres / Lancer le Bot",
	"OtherSettings": "Autres paramètres",
	"UseLuckyeggAtEvolve": "Utilisez Oeuf Chance pour évoluer",
	"GermanPokemonNames": "noms allemands de Pokémon",
	"UseIncese": "Utiliser l'encens chaque 30min",
	"EvolvePokemonIfEnoughCandy": "Évoluer le Pokemon si vous avez assez de bonbons",
	"EnablePokemonListGUI": "Activer Liste des Pokémon",
	"KeepPokemonWhichCanBeEvolved": "Gardez Pokémon qui peut être évolué"

In hope that this will help you.

**Comment by thedarkeye** [comment]
Make a pull request for the file, it'll probably be merged by the devs

**Comment by Logxn** [comment]
Accepted
