### ISSUE TITLE
Radomly reduce speed Bug 

### ISSUE THREAD

**Issue by Gummibal** [Ar1i/PokemonGo-Bot#3729]
I have often the bug that the random speed changes really fast and the bot does not continue.
 In German: Ich habe öfters den Bug das die zufällige geschwindigkeit  sich richtig schnell ändert und der bot nicht weiter läuft. Here an image from the log file. http://www.bilder-upload.eu/show.php?file=b42fe2-1473367949.png

**Comment by Logxn** [comment]
Isch werd verrücht :^).

Spaß. Du darfst den blauen fetten in der mitte nicht ankreuzen. Das ist nämlich kein Pokestop und führt nur zu bugs :b

**Comment by Gummibal** [comment]
Eigentlich habe ich den Startpunkt (den blauen fetten in der Mitte) Nicht angekreuzt. Und wenn schon denn wäre der Fehler meiner Meinung nach auch erst dann aufgetreten wenn der bot versucht hätte zu ihn hin zu laufen, dass tat er aber nicht. Der Fehler ist mitten auf der strecke zwischen zwei Pokestops aufgetreten. Nochmal auf englisch weil ich nicht weiß ob du jetzt deutsch sprichst oder Englisch : Actually, I have the starting point (the blue fat in the middle) Unchecked. And if because of the error in my opinion would be only occurred when the bot would have tried to run to him out that he did not. The error occurred on the route between two Pokestops middle.

**Comment by Gummibal** [comment]
Den Fehler hatte ich grade nochmal und ich habe mich geirrt. Der Fehler ist nicht aufgetreten wo er zu ein pokestop lief sonder wenn er die route versucht neu zu starten. Muss ich vielleicht irgendwas beachten wenn dich die route in dauer schleife haben möchte. 
In English: The mistake I had just again and I was wrong. The error has not occurred where he was special when he is trying to restart route to a pokestop. Do I perhaps consider something if you would like to have route in permanent loop.
