### ISSUE TITLE
Dont use normal Pokeballs anymore

### ISSUE THREAD

**Issue by NoticeMeSenpaiPLS** [Ar1i/PokemonGo-Bot#374]
Even if i set normal pokeballs to zero, it doesnt recycle every pokeball immediatly after getting them from the pokestop.
If i find a pokemon in the time between farming a pokeball from the stop and recycle them, they get throwed at pokemon and most of the time the pokemon can flee this way :(

Please get a solution for this.

**Comment by Ar1i** [comment]
Fixed in newest Version, that was cause of the cached Inventory!
