### ISSUE TITLE
The IMEI problem

### ISSUE THREAD

**Issue by jake109913** [Ar1i/PokemonGo-Bot#3740]
Updated to the new version but the new version will automatically reset the IMEI to default status.Can I suggest to let us change the IMEI manually in the main menu or can fixed the reset IMEI problem when we changed the IMEI in the config by ourselves.

**Comment by erickrisnarinjaya** [comment]
What is IMEI?

**Comment by jake109913** [comment]
the phone code

**Comment by SscSPs** [comment]
WHERE IS THIS?
