### ISSUE TITLE
์Not Catching Pokemon 

### ISSUE THREAD

**Issue by ToeyKK** [Ar1i/PokemonGo-Bot#3741]
Pokemon Rare and High CP
Got away while all time

4 days earlier Catching normally 

http://www.uppic.org/share-6E72_57D25702.html
http://www.uppic.org/share-93A2_57D24D85.html
http://www.uppic.org/share-6B95_57D24F2E.html

I,m use ver 1.0.9.9

**Comment by Blubb123** [comment]
works for me. ver 1.1.3.3

**Comment by shadowahs** [comment]
I'm using version 1.1.3.3 and mine are also getting away.. 

![capture](https://cloud.githubusercontent.com/assets/20916831/18379891/6dad3d50-763a-11e6-81a0-4dfb184568b1.PNG)

**Comment by Andrewaj** [comment]
Its called soft ban. it should wear off in couple of hrs, but its an indicator that Niantic doesn't like what you are doing. Just by quickly looking on this screenshot, it sounds like you are "walking" too fast.

**Comment by Logxn** [comment]
Soft banned.
Use Proxy

ooooh I wanan dance with somebody :^)
