### ISSUE TITLE
[Bug] Location window crashed

### ISSUE THREAD

**Issue by dennislwy** [Ar1i/PokemonGo-Bot#3745]
Map window crash after awhile in version 1.3.3.4 #3743

Here is the snapshot & error details:

![screen shot 2016-09-09 at 5 09 57 pm](https://cloud.githubusercontent.com/assets/5407099/18381842/c4a25232-76b0-11e6-8fdf-8d7c21245a86.png)

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at System.Collections.Generic.List`1.Enumerator.MoveNext()
>    at GMap.NET.WindowsForms.GMapOverlay.OnRender(Graphics g)
>    at GMap.NET.WindowsForms.GMapControl.OnPaintOverlays(Graphics g)
>    at GMap.NET.WindowsForms.GMapControl.OnPaint(PaintEventArgs e)
>    at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>    at System.Windows.Forms.Control.WmPaint(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ContainerControl.WndProc(Message& m)
>    at System.Windows.Forms.UserControl.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> PokemonGo.RocketAPI.Console
>     Assembly Version: 1.1.3.4
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> Pokemon.Go.Rocket.API
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> POGOProtos
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> PokemonGo.RocketAPI.Logic
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Device
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Device/v4.0_4.0.0.0__b77a5c561934e089/System.Device.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 9.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.Xml.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1082.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Net.Http
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
> ----------------------------------------
> Google.Protobuf
>     Assembly Version: 3.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> Google.Protobuf
>     Assembly Version: 3.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> Telegram.Bot
>     Assembly Version: 10.3.1.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Web
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> ----------------------------------------
> System.Data.HashFunction.xxHash
>     Assembly Version: 1.8.2.2
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Data.HashFunction.Core
>     Assembly Version: 1.8.2.2
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Data.HashFunction.Interfaces
>     Assembly Version: 1.0.0.2
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> GMap.NET.Core
>     Assembly Version: 1.7.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> GMap.NET.WindowsForms
>     Assembly Version: 1.7.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Data.SQLite
>     Assembly Version: 1.0.84.0
>     Win32 Version: 1.0.84.0
>     CodeBase: file:///C:/Users/dennis/AppData/Local/GMap.NET/DllCache/SQLite_v84_NET4_x86/System.Data.SQLite.DLL
> ----------------------------------------
> System.Transactions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
> ----------------------------------------
> PokemonGo.RocketApi.PokeMap
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> PokemonGo.RocketApi.PokeMap
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> RestSharp
>     Assembly Version: 105.2.3.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> S2Geometry
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> System.Runtime
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
> ----------------------------------------
> System.Runtime.Extensions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
> ----------------------------------------
> System.EnterpriseServices
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
> ----------------------------------------
> GoogleMapsApi
>     Assembly Version: 0.1.0.0
>     Win32 Version: 1.1.3.4
>     CodeBase: file:///D:/Dropbox/PokemonGo/Ar1i/Latest%20Build/PokemonGo.RocketAPI.Console.exe
> ----------------------------------------
> SMDiagnostics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
> ----------------------------------------
> System.ServiceModel.Internals
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 
>

**Comment by k0ut4li4n0s** [comment]
I ve got the same problem red X on map and i suppose its the same message(can copy pasta if need) 
@MTK4355

**Comment by Tr1n0va** [comment]
Same here, it seems that it will happen when the bot search for Pokestops nearby.

**Comment by Logxn** [comment]
We are aware of it.
Not @MTK4355 's fault. we're fixing it

**Comment by k0ut4li4n0s** [comment]
@Logxn sorry my fault , thought he was the one handling it

**Comment by DomeSs97** [comment]
same problem, last 3 updates..

**Comment by MTK4355** [comment]
I think I found the problem. Please standby.

**Comment by Xelwon** [comment]
OMG, again?
Incredible. :'(

**Comment by Xelwon** [comment]
I think the problem appeared again at adding pokemons icons to properties.resources (similar to first time with pokestops).

May be better using direcly .png files to markers on google maps

**Comment by InZaNeSkIl1zZ** [comment]
I've the same problem. Version 1.1.4.0

**Comment by GiaPune** [comment]
1.1.4.2 was crashed too.....

************** 例外狀況文字 **************
System.UnauthorizedAccessException: 拒絕存取路徑 'C:\Users\GiaPune\Desktop\Pokemon.Go.Rocket\Translations\de.json'。
   於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   於 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   於 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   於 System.IO.FileStream..ctor(String path, FileMode mode)
   於 PokemonGo.RocketAPI.Console.GUI.Extract(String nameSpace, String outDir, String internalFilePath, String resourceName)
   於 PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)
   於 System.Windows.Forms.Form.OnLoad(EventArgs e)
   於 System.Windows.Forms.Form.OnCreateControl()
   於 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   於 System.Windows.Forms.Control.CreateControl()
   於 System.Windows.Forms.Control.WmShowWindow(Message& m)
   於 System.Windows.Forms.Control.WndProc(Message& m)
   於 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   於 System.Windows.Forms.Form.WmShowWindow(Message& m)
   於 System.Windows.Forms.Form.WndProc(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已載入的組件 **************
mscorlib
    組件版本: 4.0.0.0
    Win32 版本: 4.6.127.1 built by: NETFXREL3STAGE
    程式碼庫: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    組件版本: 1.1.4.2
    Win32 版本: 1.1.4.2
    程式碼庫: file:///C:/Users/GiaPune/Desktop/Pokemon.Go.Rocket/PokemonGo.RocketAPI.Console.exe
----------------------------------------
System.Windows.Forms
    組件版本: 4.0.0.0
    Win32 版本: 4.6.79.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1081.0 built by: NETFXREL3STAGE
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1068.2 built by: NETFXREL3STAGE
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Pokemon.Go.Rocket.API
    組件版本: 1.0.0.0
    Win32 版本: 1.1.4.2
    程式碼庫: file:///C:/Users/GiaPune/Desktop/Pokemon.Go.Rocket/PokemonGo.RocketAPI.Console.exe
----------------------------------------
POGOProtos
    組件版本: 1.0.0.0
    Win32 版本: 1.1.4.2
    程式碼庫: file:///C:/Users/GiaPune/Desktop/Pokemon.Go.Rocket/PokemonGo.RocketAPI.Console.exe
----------------------------------------
PokemonGo.RocketAPI.Logic
    組件版本: 1.0.0.0
    Win32 版本: 1.1.4.2
    程式碼庫: file:///C:/Users/GiaPune/Desktop/Pokemon.Go.Rocket/PokemonGo.RocketAPI.Console.exe
----------------------------------------
System.Device
    組件版本: 4.0.0.0
    Win32 版本: 4.6.79.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Device/v4.0_4.0.0.0__b77a5c561934e089/System.Device.dll
----------------------------------------
System.Core
    組件版本: 4.0.0.0
    Win32 版本: 4.6.79.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mscorlib.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.6.79.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.6.79.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by elmokito** [comment]
I think the problem is with the Show Pokemon code. I tried unchecking the Show Pokemon box and it does not crash anymore.
