### ISSUE TITLE
Arena funktion ....KEIN Battle

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3748]
Hi , 
könnte man für die Arena etwas einbauen ?   (Voll-Battle wäre ich auch dagegen) 

Idee : 

Wenn der Bot an eine Arena mit der gleichen Teamfarbe vorbeikommt  ,
oder in der Nähe sieht , 
setzt er ein Pokemon mit drauf (das Stärkste aus der Liste ..) .

Natürlich nur wenn Platz ist . 

Also keine Übernahme oder hochgelevel . Nur draufsetzen . 

Es gibt sehr viele Spieler die alleine unterwegs sind ..(Rucksack und Handy ..sicher schon gesehen :-) ) 
und die würde man sogar unterstützen . 

Als Nutzer kann man noch wählen nach wieviel Arenen man die Punkte abholt . 
Also Auswahl = 10 oder 20 oder 30 usw. .

Ich würde die Sache ganz gut finden ...

Gruß Tom

**Comment by Logxn** [comment]
Das wäre ziemlich unfair.
Schau wenn du zum Beispiel aus Glück irgendwo nen Mewtou gefangen hast und das grad dein Stärkste Pokemon ist und es in die Arena setzt machst du es dem anderem Team nur schwerer die Arena einzunehmen.

Das ist eigentlich "game breaking".
Es war nie unsere Absicht den anderen leuten den Spielspaß zu nehmen. Was die leute dann letztenendes mit ihren Pokemons machen ist nicht mehr unsere Sache.

Ich bin aber gerne bereit mit euch darüber zu diskutieren und @Ar1i 's Meinung dazu zu hören.

**Comment by Ar1i** [comment]
Naja, Arenen einzunehmen ist so ne Sache.. Vom Prinzip her wäre es sehr sehr einfach ne Arena Funktion mit einzubauen und zu calcn ob man gewinnt oder verliert.

**Comment by Logxn** [comment]
Mit dem Pokemon in eigene Teamfarbe reinzusetzen kann ich mich abfinden.
Aber "einnehmen" ist doch etwas game breaking oder nicht?

Mir ist es gleich, ne funktion dafür kann ich gerne erstellen

**Comment by Tr1n0va** [comment]
Meine Bescheidene Meinung dazu:

Ich fände es schon echt unfair und übertrieben.
Immerhin geht es in dem Moment in dem ich ein Pokemon mit dem Bot in eine Arena Setze um "Echtes Geld" das ich den Entwicklern der Original App "Stehle".

Also ich bin dagegen, oder würde es halt nicht nutzen/wollen!!!

**Comment by jmo93** [comment]
ich bin auch gegen so eine funktion

**Comment by AlpaEZPZ** [comment]
dagegen.

"Es gibt sehr viele Spieler die alleine unterwegs sind ..(Rucksack und Handy ..sicher schon gesehen :-) )
und die würde man sogar unterstützen . "

Du denkst wirklich das ein Spieler der rumläuft der meinung ist DU würdest ihm als botuser helfen ?
denk da bitte nochmal scharf drüber nach...

**Comment by Schnitzelvernichter** [comment]
ne denke ich nicht ...warum auch .....
da gehts weiter =  3810
