### ISSUE TITLE
How to make it to Keep highest IV only

### ISSUE THREAD

**Issue by Revoss** [Ar1i/PokemonGo-Bot#375]
Tittle,

Please and thank you :)

**Comment by jackrose01** [comment]
yeah, im waiting someone answer this question :+1:

**Comment by NoticeMeSenpaiPLS** [comment]
I think thats what you automaticly did with just one duplicate, means no duplicate.
You allways kept the best pokemon. And the best pokemon is the pokemon with the most cp and so also the best IV or am i wrong ?

**Comment by Revoss** [comment]
Best pokemon =/= Highest IV
The game thinks that the best pokemon is the one with the highest CP, but in reality highest CP just means higher level

**Comment by NoticeMeSenpaiPLS** [comment]
is it possible to show the iv in the pokemon list ?

**Comment by Revoss** [comment]
Just mouse over the pokemon in the GUI, would be awesome if we could sort them by IV too!

**Comment by jackrose01** [comment]
Just move the cursor to the pokemon image

**Comment by jackrose01** [comment]
@Revoss  : thats mean, we have Pokemon Go PC Version :v
