### ISSUE TITLE
Getting an error when starting the Bot

### ISSUE THREAD

**Issue by programmar297** [Ar1i/PokemonGo-Bot#3751]
![error](https://cloud.githubusercontent.com/assets/7389820/18386375/a65db764-76d1-11e6-8c05-e342307729d3.jpg)

This comes up every time I try to start the bot

**Comment by nasierache** [comment]
1. Create new Folder
2. Download the ZIP and unpack it there
3. Go in to the folder Builds-Only
4. Unpack the zip
5. Start the EXE (YES, its normal that there is ONLY an exe)
6. Have fun.

**Comment by jeversonjoao** [comment]
Even after upgrade, I keep getting update information.
![ae](https://cloud.githubusercontent.com/assets/22098328/18386603/692b6c5a-766e-11e6-864e-ab903fe4cc0a.png)

**Comment by SscSPs** [comment]
BTW, you dont need to download the whole code as a zip, you can go to https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds-Only
directly and click on the file and then click on RAW(for ZIP/RAR files) or DOWNLOAD to download just the build file

**Comment by Logxn** [comment]
Actually, this is not an average error.
Its because you didnt choose any device!

**Comment by programmar297** [comment]
I upgraded the version, the error is no more. Thanks
