### ISSUE TITLE
Version 1.1.3.6 Error

### ISSUE THREAD

**Issue by jeversonjoao** [Ar1i/PokemonGo-Bot#3753]
Even after upgrade, I keep getting update information.
I emphasize that I have realized download the latest version, and extract the files in an empty folder.

![ae](https://cloud.githubusercontent.com/assets/22098328/18386658/b6c3a77a-766e-11e6-8410-cd5849566fc6.png)

**Comment by nasierache** [comment]
wait until they up the new console...it still 1.1.3.5 if you notice.. but the bot can running without any problems right?

**Comment by jeversonjoao** [comment]
Nearly so, in fact I no longer to farm the breakpoints. I think I softban.
I never had this happened.
In the cell appears message to try later, and will not appear more balls.
