### ISSUE TITLE
Help with charmanders

### ISSUE THREAD

**Issue by Shoier** [Ar1i/PokemonGo-Bot#3754]
Guys I kn ow that is not forum for Cord for exp but maybe some user who botting know where is good spot for catch charamanders In Europe ?? Pls help . Admin I know req but i can t find aninf aout that

**Comment by Andrewaj** [comment]
good spot is London  - Greenwhich Park. There always 2-3 of Charmanders there. 
Latitude: 51.468231640315
Longtitude: 0.00437736511230469

**Comment by Shoier** [comment]
Thanks Man

**Comment by SscSPs** [comment]
Nest: 40.7493479999723, 73.8427376747131

**Comment by Shoier** [comment]
thanks
