### ISSUE TITLE
Year's broken/error

### ISSUE THREAD

**Issue by nasierache** [Ar1i/PokemonGo-Bot#3755]
I've noticed that the date of pokemons been captured are broken. thats was in 1816..did anyone relize about this or its only me that facing this situation?
![untitled](https://cloud.githubusercontent.com/assets/21377477/18388013/62b30a9a-76d2-11e6-955f-f847ddc481b8.png)

**Comment by SscSPs** [comment]
it is for everyone, devs will fix it soon.

**Comment by SscSPs** [comment]
Just created a pull request with the fix. (I think)

**Comment by Logxn** [comment]
Why. We have 1816 dont we?

JK will fix that
