### ISSUE TITLE
Icons!

### ISSUE THREAD

**Issue by deadelf0** [Ar1i/PokemonGo-Bot#3756]
Aw, what happened to the cute icons?

**Comment by erickrisnarinjaya** [comment]
The newest is the better I think.

**Comment by SscSPs** [comment]
Yeah, I liked the previous ones too. Thought i was the only one!

**Comment by deadelf0** [comment]
I've noticed that the Pokemon list loads like 10x faster but still

**Comment by SscSPs** [comment]
that's probably not because of the icons...

**Comment by Logxn** [comment]
The old were to big.

**Comment by SscSPs** [comment]
okay, fine enough. 
But why is the sprites folder removed, i wish it was still there so i could use the ones i liked!
