### ISSUE TITLE
Just wondering, what exactly is this?

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3757]
![2016-09-09_211923](https://cloud.githubusercontent.com/assets/20828057/18388203/53b0786a-76d3-11e6-9ec9-da490398e2ce.png)

Dear honorable devs, can you just explain to me, what is this? Thanks. Appreciate it.

**Comment by SscSPs** [comment]
show the error from starting.

**Comment by erickrisnarinjaya** [comment]
What kind of error do you mean?

**Comment by SscSPs** [comment]
this RED thing.

**Comment by Logxn** [comment]
I mean, its not like there is a text infront of it saying "ignore this" :)
