### ISSUE TITLE
I was wondering if it would be possible to drop off random low level Pokemons at empty or team color gyms to receive coins everyday automatically  

### ISSUE THREAD

**Issue by deadelf0** [Ar1i/PokemonGo-Bot#3760]
Although that would take the last bit of fun out of the real app.  

Maybe that's too much, what about just a simply Icon for Pokemons already at gyms

**Comment by SscSPs** [comment]
Anything Gym related should not be made into the BOT. and YES it will take out the LAST BIT OF FUN of the game.

**Comment by Logxn** [comment]
"Although that would take the last bit of fun out of the real app."

You are right.
It was never our intention to do that.

Btw @SscSPs fix conflicts please :)
