### ISSUE TITLE
Frequently Switching Pokestop targets and never reaching a target

### ISSUE THREAD

**Issue by matodt** [Ar1i/PokemonGo-Bot#3763]
Moving around an area with 100m+ between pokestops and no pokeballs.

Bot would move towards Stop A, which was 80m+ distant.

After 10 seconds, it would switch to a further away stop (B), and begin moving towards it.

After another 10 seconds, it would switch to a different stop, and begin moving towards it.

Eventually it would switch back to Stop A, eventually reaching one of the stops.

My expected behavior for this would be for it to pick a stop (the closest) and head towards it until it has reached it, and attempted a spin.

**Comment by jeversonjoao** [comment]
softban.

**Comment by matodt** [comment]
If that is the case, I'd suggest a better error message.
