### ISSUE TITLE
Repeat route and number of pokestops in range

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3767]
![12345](https://cloud.githubusercontent.com/assets/21258333/18393088/d06b36fe-76bc-11e6-8021-55c75dd64788.png)

This happens after it finish the route i ve set and repeat box is set.

and it shouldnt show the pokestops in 5km that should , its almost arround 700m-1km range that show the pokestops.

**Comment by Logxn** [comment]
Fixed
