### ISSUE TITLE
[Question] Botting without proxy in diffrent country?

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3771]
I know this may doesn't belong here, I'd like to ask anyway if you don't mind. Isit possible to bot in USA using a diffrent Country ip such as switzerland, poland, Germany, France or w/e or will you get banned? Even if it's pretty obvious, Iam not sure if Niantic cares to check this anyway. I didn't find good proxies tho and they may detect your real IP anyway. Even worse alot ppl using the same IP.
Tipps? Experience? Please share. Thank you.

**Comment by SscSPs** [comment]
I use bot in New York, London, Sydney, New Delhi and WITHOUT any proxy server.
And I am not banned(yet).

**Comment by AiVo7z** [comment]
How Long have you been botting like that? Changing Locations crazy like that is even more riscy. I'd like to farm in crowded us places such as SF pier39. Good Chance for dratinis, tons of karpadors etc.

**Comment by SscSPs** [comment]
I dont change location instantaneously. 
I set up the bot at one place(say, London) for a night or longer(6-8 hours). Then I do not play for the whole day and some times for next night and day too.
Then I put up in New York, then same procedure.

**Comment by coffeexp** [comment]
Dont jump places to place.. hahaha.. That is more suspicious for Niantics to detects bots.. :D

**Comment by Logxn** [comment]
^

**Comment by SscSPs** [comment]
I do that because I can take a flight and go there (in the time i am not playing) and rest for a while and then play again.
I farm the same places, not like different areas every time. For example, I always farm Holland Park(Bulbasaur nest), London every time I am in London, and Sydney Harbor, whenever i am in Sydney.
