### ISSUE TITLE
Egg hatching request

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#3774]
Hello,

if possible, can you add a funktion, like:
Hatch 10k eggs first, or 5k, or 2k....
so the bot hatch First my prioryty  Chosen eggs and If no more there, he took another one.

THX
Trinova

**Comment by MTK4355** [comment]
Why? Wouldn't you always want the oldest hatched first?

**Comment by Tr1n0va** [comment]
Cause of rare Pokemone in 10k eggs;-)

**Comment by Tr1n0va** [comment]
I think its only imptience

**Comment by MTK4355** [comment]
I get that, but while waiting on your newest 10km egg to hatch your oldest 2k egg just keeps getting older, and it's level will not adjust as you level up. 

Also, each 2k egg you wait to hatch is a possible 10k you would not be able to collect at the next pokestop! :)

**Comment by MTK4355** [comment]
Well, at least you acknowledge that. lol :D
