### ISSUE TITLE
Log caught pokemons ?

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3777]
Hi,

what is the option "log caught pokemons" ? I thought it was a thing like showing you the pokemons that you just captured, but with or without the option that's the same.

So may someone could explain it to me please ?

Thank you

**Comment by nasierache** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/21377477/18401176/c762fab6-770b-11e6-9cba-6ae2bf1ff7a0.png)
![untitled](https://cloud.githubusercontent.com/assets/21377477/18401177/cc13060a-770b-11e6-8823-6906f42932ef.png)

**Comment by bkrandy** [comment]
does it log hatched pokemon too?

**Comment by nasierache** [comment]
they worked on it now.. soon.. be patient
