### ISSUE TITLE
Suggestion : Scale on the "Select Location Map"

### ISSUE THREAD

**Issue by casqueargent** [Ar1i/PokemonGo-Bot#3778]
Sorry to post my suggestion here but I did not find elsewhere to put. 

Just a thought. When on the main page of the bot you have the "Select location" button, you click and that opens a google map window to select your starting point, that's great but it would be great to have a little scale when you zoom in and out to then define the size of your walking area radius especially if you want to restrain your walk to a specific area and be more precise.
Just a thought.

Otherwise the bot is getting better every day guys. Thanks for the great job !!!!
If you need a french translation of the labels I can happily do it for (note that I don't know anything about coding).

All the best,

**Comment by erickrisnarinjaya** [comment]
Mine doesn't have settings for set lat or long. Please fix that, dear devs. Thank you.

**Comment by erickrisnarinjaya** [comment]
I mean when the map show up, there is no that settings. So I cannot set my starting point at my exact area.

**Comment by MTK4355** [comment]
@erickrisnarinjaya Check your screen resolution and zoom level. I think it gets pushed out of the window at lower resolutions.

**Comment by erickrisnarinjaya** [comment]
Thanks for reply. But, I think now, coz in lower version it works and I can set them as well. I don't know.. But please, could you kindly check again your coding, my dear devs. Thank you.

**Comment by nasierache** [comment]
i think its not coding error.. it works well for me.. check your resolution or redownload the bot again

**Comment by SscSPs** [comment]
If you are unable to set it using the gui, go to "Configs\Config.txt" 
and enter 
Latitude in Line 4, and 
Longitude in Line 5.
Altitude can be put in line 6(if you wish to enter that too)(or it will be fixed when the bot runs).

**Comment by erickrisnarinjaya** [comment]
Thank you. I thought so.
