### ISSUE TITLE
Stopped Farming Pokestops 30 min ago. PICTURE

### ISSUE THREAD

**Issue by drjack6** [Ar1i/PokemonGo-Bot#3779]
Farming is checked. Ran out of balls and now the bot does everything except actually farm the pokestops it visits. Whats up with that?
![img_2210](https://cloud.githubusercontent.com/assets/20915678/18402370/e6040d34-7693-11e6-9aa1-0037968d87f3.JPG)

**Comment by kreian** [comment]
not found pokestops were has many of them (excuseme for my oxidated English)

![image](https://cloud.githubusercontent.com/assets/21061474/18402749/8f2ec8ba-76a6-11e6-96c6-12ad2a33aca8.png)

**Comment by suljo94** [comment]
Press enter 1x

**Comment by drjack6** [comment]
enter closed the app...

**Comment by drjack6** [comment]
kreian thats a diffewrent issue. Please delete that comment and look through the issues threads

**Comment by erickrisnarinjaya** [comment]
Sofban indicated.
Close the bot app and then try again in couplea of minutes or hours.

**Comment by drjack6** [comment]
Maybe i was softbanned i guess. Its working now. Didnt know they still did softbans
