### ISSUE TITLE
French mod

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3781]
Hi,

there is a problem : when i click on the french flag, that's just doing nothing.
But the others flags work so there is just a problem with the french flag.

Thank you

**Comment by ko2i4s** [comment]
And do you need someone to translate all in french ?
I am French and i think i can do it if needed.

**Comment by Zodice** [comment]
Le problème c'est pas du tout la traduction elle a été faite et peaufinée, mais elle n'est juste pas disponible quand on clique sur le drapeau ça reste en anglais.

**Comment by Logxn** [comment]
will fix that
