### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3782]
Hi,

do you think that if i don't open the bot for like 1 day i can move far from my actual location ?
It's wil be like i'm juste in holidays, what do you think about it ?

Thank you

**Comment by MTK4355** [comment]
That's what some say, though I personally don't do it on the accounts I am trying to keep.

**Comment by Adj1e** [comment]
Hy, use pokesniper to unban. I always bot in central park ny and I batle gym in my country. FYI I move from NY to my country in second and that fine to me. You can search pokesniper in github

**Comment by Logxn** [comment]
@MTK4355 answered it perfectly
