### ISSUE TITLE
Google map

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3783]
Hi,

how do we see the google map please ? I turned on the google api and put an api key

Thank you

**Comment by MTK4355** [comment]
How do you see it? What do you mean, like how do you open the map or.....?

**Comment by Zodice** [comment]
Yes, how can i open the map, i thought it was on the windows when the bot is open but there is nothing.

**Comment by Logxn** [comment]
Just open the map in the pokemonlist
