### ISSUE TITLE
Coordinates error.

### ISSUE THREAD

**Issue by 4ndr0id19** [Ar1i/PokemonGo-Bot#3784]
When entering my location ill type in the coordinates and an error will pop up saying that it must be between 180 and -180....... but pretty sure it should say -180 and 180. the current way is mathematically impossible. (Because it would start counting UP from 180 until it reached -180.... which would never happen.)

**Comment by nasierache** [comment]
what is the coordinate that you enter in the box?

**Comment by 4ndr0id19** [comment]
You can just ignore me. I was totally entering the longitude into the latitude box. Like an idiot.
