### ISSUE TITLE
Pokestop and pokemon

### ISSUE THREAD

**Issue by chenrei** [Ar1i/PokemonGo-Bot#3785]
Hi

I just wonder, any maximum pokemon and pokestop per 12hr not to get a softban or perm ban?  Thank you

**Comment by ToeyKK** [comment]
ver 1.0.9.9 the best for use 
Unlocked ban
very good for use

**Comment by SscSPs** [comment]
default is set to max to not get softban
its 1000 pokemons and 2000 pokestops.

**Comment by Ar1i** [comment]
@ToeyKK using old versions is not a good idea. Cause the signature is not up2date. So they can easily ban you.

**Comment by Logxn** [comment]
^
