### ISSUE TITLE
Releases in Github

### ISSUE THREAD

**Issue by Viper2k4** [Ar1i/PokemonGo-Bot#3796]
Hey how why not using this:

https://github.com/Ar1i/PokemonGo-Bot/releases

It would dropt the Size from 10,6mb to 5,2mb (of the Github).

**Comment by devilexclonz22** [comment]
new fiture ? 'throws' how to use it ? haha

**Comment by Logxn** [comment]
Jup. ofc.
It would drop the FILE SIZE from 6.7MB to 1MB simply by moving it.
Go to builds only and simply download the exe only

**Comment by Viper2k4** [comment]
Maybe think a bit before closing it directly? ^^

I download the Zip because i use it for develop. So this file is totaly a "Spacefiller". If u dont want the remove it maybe use gitignore to save github from useless downloads.

And btw. "PokemonGo.RocketAPI.Console/Location.cs" in gitignore is also not the beast idear i think.
