### ISSUE TITLE
New Feature - Send pokemon catched to skiplagged.com

### ISSUE THREAD

**Issue by Konageski** [Ar1i/PokemonGo-Bot#3797]
If catched the pokemon, send localization to https://skiplagged.com/catch-that/ for to improve that map.
Send the name, geolocalization and timeout.

**Comment by Ar1i** [comment]
Uhm any api for that?

**Comment by Xelwon** [comment]
I think there is not api. It would be a quite dangeros. People would send fake pokemons.
