### ISSUE TITLE
 Warning!! Too much "power up"

### ISSUE THREAD

**Issue by xalex51** [Ar1i/PokemonGo-Bot#3799]
Hi,
PowerUP works with BOT or it is disabled on the apk !!
Please developers, look at this.
The Bot up more than the apk !!

**Comment by nasierache** [comment]
means? provide screenshots please

**Comment by xalex51** [comment]
I don't have a screenshot for now
But if you connect on a smartphone and you max "power-up"  a pokemon. And you just after you reconnect to the BOT, you can "power-up" this pokemon one more times!

example:
If i'm lvl24(60%)
-The APK 'Power-up' to the lvl25.5
-The BOT 'Power-up' to the lvl26 (We risk being banned!!)

sorry i'm french :/, I am doing my best 

In French:
Le BOT autorise à recharger (Power-UP) un pokémon alors que sur l'application android, cette option est grisée (verouillée). 
Je suis lvl24 (60%), l'application recharge mon pokémon jusqu'au lvl 25.5 et le bot recharge jusqu'au lvl26

**Comment by evetaku** [comment]
i know this's.
-my account lvl 30
-powerup pokemon lvl 25 until lvl32.
-in reality we can powerup is untul max lvl player lvl30 or lvl30.5

**Comment by xalex51** [comment]
No, the APK, allow power-up 'lvl player' + '1,5'

@Ar1i Please look here

**Comment by thejundguy** [comment]
meaning that the actual app on phone only allows us to power up until <player level> + 1.5 
but the bot can power up till <player level> + 2

the following image shows there's a small gap for max-out pokemon on the actual app (player level 23, pokemon level 24.5)
![image](https://cloud.githubusercontent.com/assets/21860778/18417356/5393fb84-7860-11e6-8eab-31023061e947.png)

didn't notice this until i see this post @.@
I guess this may be one of Niantic's tactic to catch cheaters

**Comment by xalex51** [comment]
Nice! Where is @Ar1i ?? fuck, i go play with other bot sorry he is not reactive...

**Comment by Ar1i** [comment]
@xalex51 just don't use power up then or limit it lmao.

**Comment by xalex51** [comment]
@Ar1i   LOL 'Freetime'   It's just a variable to change!
