### ISSUE TITLE
{Request} Tutorial

### ISSUE THREAD

**Issue by Oguzcan13** [Ar1i/PokemonGo-Bot#380]
I plan to make a tutorial to install the bot

**Comment by LikeAFisch** [comment]
all know how to do that, and there are already many.

**Comment by HaydarOzturk** [comment]
I have one and people already making a lot of these. I don't think it neccesary but if you wanna do it anyway I don't know why are you typing about it :) Just do it...

**Comment by Oguzcan13** [comment]
xD

**Comment by Oguzcan13** [comment]
My Tutorial : https://www.youtube.com/watch?v=Zun2myEJbvw&feature=youtu.be

**Comment by Ar1i** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/ <- read thread
