### ISSUE TITLE
pokemon got away but i still get items on pokestop

### ISSUE THREAD

**Issue by azffar07** [Ar1i/PokemonGo-Bot#3805]
Guys,

Please help me with the problem mention above. Try few days already but sometimes it does happen again. i dont jump on map but when i run it, i cant catch pokemons. my bot does get item when visited
all pokestops in that range. 
please help me out to find why i cant catch pokemons. Thanks.

Thank you! ;)

**Comment by nasierache** [comment]
how is your internet speed connection?

**Comment by azffar07** [comment]
constant speed i guess 4mb/s with wifi connection. i think no prob with that... sad :(

**Comment by nasierache** [comment]
did you try with other acc?
i think maybe a softban
how long did you botting in a day?

**Comment by SscSPs** [comment]
thats a soft ban

**Comment by azffar07** [comment]
@nasierache not yet try with other acc as i only have 1 now. 
i thought so also after reading some issue on the net.
but then i can still collect items in all pokestops i visit and also challenge gym.
so i dont really know if its a softban or wht. if its a softban how should i do it? how long should i wait.
thanks for the reply bro!

**Comment by azffar07** [comment]
@SscSPs is it confirm softban? but still i can have all the items drop from pokestop. how long should i wait for the softban?
Thanks bro for the reply!

**Comment by Xelwon** [comment]
First ban Sereval hours

**Comment by SscSPs** [comment]
There are many types of soft ban

**Comment by azffar07** [comment]
@Xelwon oic, thx bro. so its softban actually?

@SscSPs thx for update. 

Still cant figure how they detect me cos i dont jump around the map.
and good to know theres many type of soft ban. usually i heard of soft ban from my friend
(their pokemon will flee at first catch try and cant get anything from the pokestop) but mine different.

is it anyway to avoid them or how to know to avoid soft ban bcos i didnt jump around the map. or 
per day how long can i bot?

**Comment by vitus0123456** [comment]
@azffar07 
What's your run speed? how long did you let the bot run?

**Comment by azffar07** [comment]
@vitus0123456 10-20km/h few hours i guess. (3hour+)

**Comment by SscSPs** [comment]
how many pokemons have you caught in the last 24 hours?

**Comment by azffar07** [comment]
glad to know this fact! thanks dude! help much.. @SscSPs
