### ISSUE TITLE
Pokestop export to .kms

### ISSUE THREAD

**Issue by hoibat** [Ar1i/PokemonGo-Bot#3806]
Hi! Great bot, and i love the map. :+1: 

maybe there is a way to export the scanned/visited pokestops to a Google *.kms file, so we can start make a accurate pokestop-map of the current location?

Thanks!

**Comment by Viper2k4** [comment]
A better idear would be to use:

https://github.com/PokemonGoMap/PokemonGo-Map

Then u have a Database where u can export all the Stuff u like :)
