### ISSUE TITLE
Bot not seeing lured pokemons

### ISSUE THREAD

**Issue by YellowTomato** [Ar1i/PokemonGo-Bot#3807]
I know this question has been up before. Here are some pics. First look at the difference between fastpokemap.se and pokestumble.com

http://imgur.com/DlCE2gw

At  fastpokemap we see many more pokemons. If you sit for a while comparing the two you will see that the pokemon that are in  fastpokemap – but not  pokestumble – are only around for about 3 minutes. I think  fastpokemap see all pokemon while pokestumble only sees the non-lured ones.

Second: I started a bot here – and it found  exactly the three pokemons from pokestumble and not all the rest. 

http://imgur.com/kTlA3bP

Conclusion: Bot cannot see lured pokemons.

It is not just a question about XP, but consistently not catching lured pokemon is a VERY un-human  behaviour and could possibly be something Niantic is watching for. I think this should be labelled a major bug.

**Comment by jmo93** [comment]
True words

**Comment by Ar1i** [comment]
Yeah lured pokemons are not catched atm building that in.

**Comment by YellowTomato** [comment]
> building that in.

Great! Thank you!

**Comment by Ar1i** [comment]
should be in, but it's untested atm

**Comment by Zestiria00** [comment]
Hi Ar1i! Is there any other way i can set up location? Im using a very old note book laptop and i cant see or use the set up location button  below but i can, in older version right now im using 1.1.3.5 version
![20160912_112051](https://cloud.githubusercontent.com/assets/22138908/18422227/34d8ae08-78db-11e6-8102-de0de18b0b03.jpg)

**Comment by Siufay1** [comment]
The bot can't catch lure pokemon in the lastest bot 1.1.4.3. The user defined route works well . In my case, i walk repeatly in a route of 4 pokestops, and break at lure to catch pokemons. The bot can't refresh the lure condition of pokestop once it had visited. So it walked around the 4-stops route and break at lure to catch pokemons in 1 stop. In fact, the 4 points are always in lure condtion and stop in lure condition in 1 or 2 minutes. Hope u can help look into it. Thank for your hard work. The bot is really awesome..

**Comment by YellowTomato** [comment]
New option to catch lured pokemons does not seem to work. It catches the normal ones and then gets ”Error catching Pokemon: EncounterNotFound”. (I am judging the normal from lured based on  the difference between  pokestumble.com and fastpokemap.se).

Thanks for your great work.

**Comment by Andrewaj** [comment]
i can confirm that it still doesn't catch lured pokemons, i am getting EncounterNotFound error as well.

**Comment by MTK4355** [comment]
Can you please verify that this is still an issue with the latest version?

**Comment by YellowTomato** [comment]
Dropped the bot into a heavy lured area (Bibliotekshaven in Copenhagen) and got two "EncounterNotFound"

![fejl](https://cloud.githubusercontent.com/assets/22130159/18507827/40382c68-7a72-11e6-9fe4-2a1c5fa18f42.png)

**Comment by YellowTomato** [comment]
Using version 1.1.5.1

**Comment by Siufay1** [comment]
still got error when catching lured pokemon in the version 1.1.5.1

**Comment by Siufay1** [comment]
![image](https://cloud.githubusercontent.com/assets/21969539/18522497/e47fb76c-7ae2-11e6-9f24-19a509fc0fec.png)

**Comment by Siufay1** [comment]
Moreover, the bot can't detect most of the lured pokemon.

**Comment by Siufay1** [comment]
still got error in version 1.1.6.5
![image](https://cloud.githubusercontent.com/assets/21969539/18682727/ebdfb2a2-7f9f-11e6-869f-180f9640aa1f.png)
