### ISSUE TITLE
Auto Arena

### ISSUE THREAD

**Issue by Croc0008** [Ar1i/PokemonGo-Bot#3810]
Hey!
Ich weiß, dass das Thema, dass der Bot automatisch ein Pokemon in eine Arena setzt, bereits angesprochen wurden ist, mit dem Grund, dass dies unfair gegenüber den anderen Spielern sei. 
(Für alle die nicht wissen was mit "Auto Arena" gemeint ist: Wenn der Bot an einer Arena mit derselben Teamfarbe vorbeikommt und in dieser Arena noch Platz ist wird das beste Pokemon aus der Liste automatisch in die Arena reingesetzt.)
Ich persönlich finde die Idee eigentlich gut, und die Begründund diese Funktion nicht einzubauen, weil dies unfair gegenüber anderen Spielern wäre irgendwie komisch. Denn eigentlich ist es ja auch unfair gegenüber den anderen Spielern zu botten und den ganzen Tag seinen Account z.B. durch den Central Park zu schicken, obwohl man eigentlich in der Schule oder auf der Arbeit ist.
Ich wäre dafür, dass der Bot das beste Pokemon automatisch in eine Arena reinsetzt und am Besten noch automatisch die Coins farmt.
Für alle, die diese Funktion nicht wollen, ihr müsst sie ja nicht nutzen :)
Und außerdem ist es ja eigentlich egal, ob man nun mit dem Bot oder später mit Hand die Pokemon einer Arena zuweist, das macht ja eigentlich keinen Unterschied.
Wer auch meine Meinung ist einfach mal liken, damit Ar1i es einbaut :smiley: 
Danke fürs Lesen
~Croc0008

**Comment by Ar1i** [comment]
Ist nen unterschied ob du in sagen wir mal Bayern alles einnimmst anstatt bei dir im Dorf. So ein Feature wird es von meiner Seite aus nicht geben.

**Comment by Croc0008** [comment]
okay, schade :/

**Comment by Schnitzelvernichter** [comment]
Setze ein Monster mit höchstens 300 WP drauf ...
und der Bot geht nicht einfach so daran vorbei ....
und die Arena ist nicht umbesiegbar ...
wäre sie sowie nicht bei 2 Spielern oder 10 Spielern oder sonstwas .... keine Arena hält Tagelang ....egal was man draufsetzt....

DER BOT SOLL ARENEN NICHT EINNEHMEN ODER RUNTERSCHIESSEN ODER RAUFSCHIESSEN , kein Spieler geht einfach so vorbei wenn er nur mit draufsetzen kann ....oder ?

**Comment by AlpaEZPZ** [comment]
Reicht euch nicht was wir hier haben ?
Also mir schon...
Ich fänds persönlich sehr nervig wenn Ständig bots plätze in der Arena wegschnappen würden.
Bisher konnte man hier seinen Account hochspielen. Sollte es eine Arena-Funktion geben würde man aktiv ins Spielgeschehen eingreifen - fändet ihr das Reizvoll... ?
Diesbezüglich würde ich sagen Ar1i hat das mit der Arena schon ganz gut verstanden.

**Comment by Schnitzelvernichter** [comment]
Du hast vollkommen recht , wie können wir nur in Spielgeschehen eingreifen .... Unverschämtheit ...
ALTER....Boah ....welch Gedanke ....bis Level 40 botten und dann Account löschen ...das ihr mir ja nicht ins Spielgeschehen eingreift .....auch Später keine Monster tauschen ...ts.ts.ts. und wehe ihr gebt Spawnpunkte weiter .... 
ich denke diese Arenafunktion hier ist bei WEITEN die harmloseste Sache ...
aber ich höre jetzt auf mit den Thema ...Closed das mal hier ...es gibt wichtigeres
