### ISSUE TITLE
Setting Location for low-res devices

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3811]
As soon as I use a device such as a netbook to bot I can't set the Location due to low Screen Resolution, boxes with latitude etc. don't appear. I can't Change the Location on the bot gui either. Could you fix that Problem ? Even if not much ppl are affected, or atleast make it possible to put in the numbers manually in "General" tab. 

Also what does Auto update mean? Keep all configs but the gui is updated? Thanks in advance.

**Comment by erickrisnarinjaya** [comment]
I thought I was alone.

**Comment by Slayer013** [comment]
same here.. i can't use my bot since i can't change my location..
i know they already answered this question before but it don't work for me...

**Comment by Zestiria00** [comment]
I get that too right now im just using an older version 1.1.3.5
![20160912_112051](https://cloud.githubusercontent.com/assets/22138908/18424388/70a313bc-78f2-11e6-9818-7bf791bae7fc.jpg)

**Comment by Ar1i** [comment]
Go in the config file, fixing it later
