### ISSUE TITLE
It does not work incubadore eggs If you disable "catch pokemon"

### ISSUE THREAD

**Issue by javiermartinalonso** [Ar1i/PokemonGo-Bot#3824]
###### ################## RULES. READ BEFORE POSTING!

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment
###### 

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

If you disable "catch pokemon" Incubating eggs stops working.
But this should not be, because these pokestop moving from one to another.

You can walk over 10km through pokestops without counting I walked

**Comment by Ar1i** [comment]
Whats your speed? And the Egg km got some delay

**Comment by javiermartinalonso** [comment]
between 4 and 10 km / h vary, for 2 hours, no progress has the incubadura.
thanks for the support and congratulations for the great work you are doing.
