### ISSUE TITLE
lure?

### ISSUE THREAD

**Issue by Araben** [Ar1i/PokemonGo-Bot#3825]
can someone please tell me whats lure? catch pokemons in lure? 

i saw the new options in the last updates but i never understanded whats the thing about!

----------------------------------
#update2 
----------------------------------

@Ar1i thanks for answering, doesnt the bot see the lured pokemons as normal pokemons and catch them :O?

**Comment by Ar1i** [comment]
Catches the pokemon at a lured pokestop
