### ISSUE TITLE
No Items Pokestop, when "Catch Pokemon" is disabled

### ISSUE THREAD

**Issue by bjornberfelo** [Ar1i/PokemonGo-Bot#3827]
If I disable "Catch Pokemon" I dont get items from Pokestops

![2016-09-12_13-13-34](https://cloud.githubusercontent.com/assets/3984732/18434016/eec68286-78ea-11e6-9f33-3e43a902c6ee.jpg)

**Comment by jeversonjoao** [comment]
Same situation here.

**Comment by Ar1i** [comment]
probably your inventory is full?

**Comment by jeversonjoao** [comment]
Nope. 
![sem titulo](https://cloud.githubusercontent.com/assets/22098328/18438262/f7e701ce-78d6-11e6-8b2a-fcb7d3b7be5b.png)

**Comment by jeversonjoao** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/22098328/18438461/d8bae42c-78d7-11e6-8a86-1d137f28bb16.png)
following error messages

**Comment by jeversonjoao** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/22098328/18438500/09957418-78d8-11e6-8798-ad81179c467f.png)
following error messages

**Comment by alexandrer0x** [comment]
You can mark all pokemon in the "not to catch" list on the tab "Pokemon" until they fix the bug

**Comment by Rukeith** [comment]
I also have this problem.
I have pokeballs and I didn't setting any pokemon in the "not to catch" list

**Comment by drjack6** [comment]
Same problem since two updates ago this morning. Not farming any balls all day
