### ISSUE TITLE
Gespeicherte Koordinaten der gefangen Pokemons anzeigen

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3828]
Hi , 
es gibt ja genialer Weise diese Text Datei mit den gefangenen Pokemons ....
Kann man diese Datei irgendwo einspielen und man bekommt dann eine komplette Übersicht auf einer Map wo welches Monster gefangen wurde ? 
Am besten nur die seltenen oder eine getroffene Auswahl .
Das einzeln über Google Maps zu machen dauert viel zu lange .....
Dann hätte man eine schöne Übersichtkarte ....am besten noch mit Uhrzeiten wann diese Spawnen ...
Gibt es sowas schon oder kann man es einbauen ? 
Wäre echt der Hammer..

**Comment by Gummibal** [comment]
Das wäre echt genial.

**Comment by suljo94** [comment]
services like this already exist pokefind is just one of many, you could also search
http://pkmngotrading.com/wiki/Nests

**Comment by Gummibal** [comment]
No it was not the answer. in this topic, it was not why to find pokemon specifically but rather a function to build a which you can see on a map where you have your captured Pokemon.
 Auf deutsch: nein es war nicht die Antwort. in diesem Thema ging es nicht Darum pokemon gezielt zu finden sondern darum eine Funktion ein zu bauen womit man auf einer Karte sieht wo man seine pokemon gefangen hat.

**Comment by suljo94** [comment]
Pokefind is exactly that a map with locations were specific pokemon were caught

**Comment by Gummibal** [comment]
you do not understand us. we do not want to see where in the world just what is Pokemon. We want only one function where we can see where our from bot prisoners were found pokemon. auf deutsch: du verstehst uns nicht. wir möchten nicht sehen wo auf der Welt grade welches pokemon ist. Wir möchten nur ein funktion wo wir sehen können wo unsere vom bot Gefangenen pokemon gefunden wurden.

**Comment by suljo94** [comment]
Ohh oke so individually ask that in the discord (see main info page)  the issues section is reserved 4 issues only. Please close this thread if my answer was satisfactory

**Comment by Schnitzelvernichter** [comment]
es geht auch einzeln über Google ..viele Monster sind es ja nicht die man vergeblich sucht :-)
ich schliesse das mal ....wenn trotzdem jemand was einbaut wäre das echt klasse .
