### ISSUE TITLE
Gym Maker 

### ISSUE THREAD

**Issue by Gummibal** [Ar1i/PokemonGo-Bot#3829]
What do the new Arena marker? In German : Was bringen die neuen Arena Marker?

**Comment by Blubb123** [comment]
wo hast du Arena marker ? O_o
Ich seh nur Show PokeSTop und Show Pokemon auf der Map und die werden auch nur sporadisch angezeigt.

**Comment by Gummibal** [comment]
![arena marker](https://cloud.githubusercontent.com/assets/21315663/18441873/e2e84804-790e-11e6-8006-d7f6ec82f000.PNG)

Ich habe es dir mal eingekreist und beschriftet.

**Comment by Blubb123** [comment]
nachdem bei mir wie gesagt nur sporadisch icons auftauchen sind die mir also leider noch nicht untergekommen. :D

**Comment by Gummibal** [comment]
wenn die pokestops am Anfang geladen werden werden die Arenen mit geladen. Wenn du den bot startest starte am besten dann auch schnellst möglich die karte dann werden die direkt mit geladen (die Icons) die map darfst du zwischendurch auch nicht zu machen weil dann halt die Icons
 auch nicht mehr gezeigt werden.

**Comment by Blubb123** [comment]
das mache ich jedes mal so wie du sagst, aber icons kommen nicht. ich seh nur den gelaufenen weg.

**Comment by Gummibal** [comment]
Lass mal die map offen (kann auch minimiert sein) und lass den bot einfach laufen. Irgend wann lädt sich das eigentlich neu und dann werden (normalerweise) die Icons mit geladen. Hast du die neuste version vom bot?

**Comment by Blubb123** [comment]
ja hab die neuste Version, seit 2 stunden Fenster offen, keine icons.

**Comment by Gummibal** [comment]
Dann weiß ich auch nicht weiter.

**Comment by Zodice** [comment]
Everybody is making an effort to speak english to be understood by everybody, so please make it too.

**Comment by MTK4355** [comment]
Is there an actual issue here?

**Comment by suljo94** [comment]
@MTK4355 No issue just asking what is does etc.... close it up
