### ISSUE TITLE
Use Break Interval and Length Setting Is Not Saved

### ISSUE THREAD

**Issue by HeIsNoOne** [Ar1i/PokemonGo-Bot#3838]
Use Break Interval and Length Setting works fine.
However this setting is not saved in the configuration file.
So when you start the bot again, it will always be set to false (unchecked).
![Configuration](https://s22.postimg.org/yrcomu6o1/Use_Break_and_Interval.jpg)

**Comment by HeIsNoOne** [comment]
@MTK4355 @Logxn 
Can somebody add this to the PokemonGo.RocketAPI.Console/GUI.cs at line 482?

case 16:
    checkBox_UseBreakIntervalAndLength.Checked = bool.Parse(line);
    break;

That will fix this bug. I don't know how to commit to github.
Thanks!

**Comment by MTK4355** [comment]
Done in next build.
