### ISSUE TITLE
Exception: System.NullReferenceExcption

### ISSUE THREAD

**Issue by thejundguy** [Ar1i/PokemonGo-Bot#3839]
![image](https://cloud.githubusercontent.com/assets/21860778/18464569/5d1e6b48-79c4-11e6-87c0-0d46a913dc38.png)

my high level acc keep on showing this when i'm botting.
doesn't happen to my new accounts.
any idea?

**Comment by HeIsNoOne** [comment]
Do you run multiple bot at the same time with the same IP address?

**Comment by thejundguy** [comment]
nope.. only 1 bot at a time.
bot is OK just that the error comes out frequently

**Comment by Blubb123** [comment]
I have the same issue.

**Comment by Virusdead49** [comment]
erreurBOT Exception: System.ArgumentOutOfRangeException: 'minValue

![2016-09-13_215709](https://cloud.githubusercontent.com/assets/10480101/18489249/12008784-79fd-11e6-9dfb-cbaaa691075f.png)

**Comment by MTK4355** [comment]
This should be fixed in latest release.
