### ISSUE TITLE
Exception System.ArgumentOutOfRangeException PLS HELP

### ISSUE THREAD

**Issue by MythosOfGaming** [Ar1i/PokemonGo-Bot#3840]
![image](https://cloud.githubusercontent.com/assets/20840606/18475273/1a989cce-79c6-11e6-9d5f-b0a4408f5765.png)

**Comment by riautama77** [comment]
something is wrong in the walking config

**Comment by MythosOfGaming** [comment]
![image](https://cloud.githubusercontent.com/assets/20840606/18479831/bc896b8e-79d6-11e6-9256-3d932507941b.png)
What is wrong ?

**Comment by riautama77** [comment]
if you put min walk speed is 10, what did you put in general section, for the max speed?

**Comment by MTK4355** [comment]
Exactly, Your Min Walk speed must be lower than your walking speed in the main GUI. If your min walk speed is the same or higher you will get this error.
