### ISSUE TITLE
Catching Pokemon Disabled - No Pokeballs

### ISSUE THREAD

**Issue by jeversonjoao** [Ar1i/PokemonGo-Bot#3841]
Missing when the program worked for me.
Today I can no longer catch monsters and balls.
My doll is walking forever and does nothing.

Already reinstalled, I've tried with another ip, I've tried everything.

I'm not banned.

![sem titulo](https://cloud.githubusercontent.com/assets/22098328/18475961/bc4dbb26-799e-11e6-8f8d-70e0966d1a3f.jpg)

**Comment by MordorGames** [comment]
Check this option
![image](https://cloud.githubusercontent.com/assets/22083197/18477852/80bed674-79a5-11e6-80db-3828b060a4c7.png)

**Comment by riautama77** [comment]
try not to catch the common pokemons in the config. later your stock of pokeball will be building up. happen to me too

**Comment by riautama77** [comment]
pidgey, weedle and so on.

**Comment by k0ut4li4n0s** [comment]
This happens to me too , but it never reach to the pokeball limit of 1 type. When it get 1 pokeball it catches the pokemon or because of no pokeballs pokemon is fleeing

**Comment by MTK4355** [comment]
Slow your walking speed. Doesn't look like you're getting anything from the pokestops.

**Comment by suljo94** [comment]
also since version 0,37 catching pokemon was made harder which is probably what caused the sudden drop in pokeballs ......again( I swear niantic you are deturing the legitimate players and only the botter/spoofers will remain)

**Comment by Schnitzelvernichter** [comment]
das ist ein Botfehler , war bei mir auch ...der schmeisst alle bälle weg ...müßte aber schon behoben sein ...
für die Deutschen :-)
