### ISSUE TITLE
restart too often + dont show pokemon on map

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3844]
![12345](https://cloud.githubusercontent.com/assets/21258333/18482077/65ff6960-79e7-11e6-902b-d76c4688f222.png)

The restart happens too often and pokemon dont show on map

**Comment by Logxn** [comment]
auto update or redownload.

**Comment by PokePro21** [comment]
you banned RIP

**Comment by k0ut4li4n0s** [comment]
@PokePro21 nah i said too often not every single login.

and sth else @Logxn  auto update bugs and just loads countless times w/o updating is this an issue should i open one to check it ?

**Comment by InZaNeSkIl1zZ** [comment]
It doesn't show any pokemons for me, too. That issue continued for a few updates now

**Comment by Slayer013** [comment]
it doesn't show pokemons & pokestops for me... :(
