### ISSUE TITLE
Newest update urgent

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3846]
doesn't respect set amount of items (in the main gui) it lisens to the amount that is in the secondary gui and those numbers cant be edited
examples
main gui
regular pokeballs 70

secondary gui
regular pokebals 20
currnet regular pokeballs 66=>dumps 46
secondary gui is the one that comes up when the bot starts farming

issue 2
![naamloos](https://cloud.githubusercontent.com/assets/13616056/18485396/ecc87c0c-79ec-11e6-9c88-8aaf43ea2385.png)

**Comment by Ar1i** [comment]
Thanks for reporting, taking a look at it. Fixed everything expect issue 2. Doing that now.

**Comment by Andrewaj** [comment]
I think problem with secondary GUI item count is still there. Item count should be in sync between these 2 menus. I had 50 Revives in primary menu specified, i just started bot and it recycled items before I managed to spot it. secondary GUI should copy inventory from primary menu at starting point.

**Comment by suljo94** [comment]
The new version isn't uploaded yet I think ari would have closed the issue if it was

**Comment by OldSch0ol** [comment]
> ... i just started bot and it recycled items before I managed to spot it @Andrewaj 

Yeah! Lots of my pokeballs are gone :-(

**Comment by Adj1e** [comment]
I just lost my Max Potion 330 item.

**Comment by suljo94** [comment]
@MTK4355 fixed it in last commits(if I saw correctly)  just waiting for new build
