### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3848]
Still have this problem, the french flag don't translate the bot, that's staying in english.

**Comment by FenrirXx34** [comment]
Me too, i'm french ^^

**Comment by nemsriz** [comment]
Some words are already translated in the variables (I don't know if it's the correct word) like "Mot de passe" for "password" and "Mètres" for "meters".

Plus, the variables (still don't know if it's the right word)  have their first letter in capital. That may have a consequence.

Trying to correct those mistakes, when i open the bot, the "france.json" file gets back to its inital form...  or is it because I have another bot window running on...?

**Comment by Zodice** [comment]
That's the correct translation, but i don't know why it's not working ..

**Comment by nemsriz** [comment]
I wasn't sayng the translation isn't right. (je suis français, donc je vois bien que c'est traduit comme il faut)
if you open "france.json" file with a text editor, you'll see : `"Mètres": "mètres",` 
But I think it should be `"meters": "mètres"`
same for "Mot de passe".

**Comment by bencrob** [comment]
don't put capital on the first letter like this : 
{
	"accountType": "Account Typ:",
	"username": "Benutzername:",
	"password": "Passwort:",
	"locationSettings": "Standort Einstellungen",
	"speed": "Geschw.:",
	"moveRadius": "Radius:",
	"meters": "Meter",
	"startFromDefaultLocation": "Starte von Standardposition",
	"botSettings": "Bot Einstellungen",
	"autoTransferDoublePokemon": "Doppelte Pokemon automatisch wegschicken",
	"maxDupPokemon": "Max. doppelte Pokemon",
	"maxCPtransfer": "Max. CP zu senden:",
	"maxIVtransfer": "Max. IV zu senden:",
	"telegramSettings": "Telegram Einstellungen",
	"infoline1": "Dieser Bot ist kostenlos und Open-Source! Fordere ggf. dein Geld zurück!",
	"infoline2": "Wenn du den Namen 'Pokecrot' siehst, teile allen mit, dass dieser gestohlen ist.",
	"maxPokeballs": "Max. Pokebälle:",
	"maxGreatballs": "Max. Superbälle:",
	"maxUltraballs": "Max. Ultrabälle:",
	"maxMasterballs": "Max. Meisterbälle:",
	"maxRevives": "Max. Beleber:",
	"maxTopRevives": "Max. Top-Beleber:",
	"maxPotions": "Max. Tränke:",
	"maxSuperpotions": "Max. Supertränke:",
	"maxHyperpotions": "Max. Hypertränke:",
	"maxToppotions": "Max. Top-Tränke:",
	"maxRazzberrys": "Max. Himmiheeren:",
	"totalCount": "Gesamtzahl:",
	"pokemonNotToTransfer": "Pokemon - Nicht zu versenden",
	"selectAll": "Alle auswählen",
	"pokemonNotToCatch": "Pokemon - Nicht zu fangen",
	"pokemonNotToEvolve": "Pokemon - Zum entwickeln",
	"saveConfig": "Konfiguration Speichern / Bot starten",
	"otherSettings": "Sonstige Einstellungen",
	"useLuckyeggAtEvolve": "LuckyEgg bei Entwicklung",
	"useRazzBerry": "Benutze Himmihbeere",
	"germanPokemonNames": "Deutsche Pokemon-Namen",
	"useIncese": "Verwende Rauch alle 30min",
	"evolvePokemonIfEnoughCandy": "Pokemon entwickeln wenn möglich",
	"enablePokemonListGUI": "Pokemon List anzeigen (GUI)",
	"keepPokemonWhichCanBeEvolved": "Behalte entwickelbare Pokemon",
	"autoIncubate": "Automatisch brüten (Keine Garantie dass es funktioniert)",
	"useBasicIncubators": "Bezahlte Brutkästen nutzen"
}
