### ISSUE TITLE
ProtoPayloadIssues & unban method wont work anymore

### ISSUE THREAD

**Issue by Logxn** [Ar1i/PokemonGo-Bot#385]
http://prntscr.com/bzg2ka

GetMapObjectResponse
PlayerUpdateResponse

Unban Method causes Payload problems and wont even work anymore.

**Comment by Euskater2** [comment]
works fine with the new update

**Comment by Logxn** [comment]
I am using the newest update.

**Comment by Euskater2** [comment]
okei then i dont know ... :/ didnt work to for the first time too .. but then i deleted my last location and it worked... maybe not the issue but it works xD
