### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by lfaveur** [Ar1i/PokemonGo-Bot#3850]
0 - Impossible to resize the GUI window (enlargement is possible but i can't minimize this)... http://prnt.sc/chnqvr

http://prnt.sc/chnrn2
1 - Reload is on all tabs ... bug I think no ?
2 - I think pokemon list item is not writable ... it's not working and it always fix the number item to 20 pokeballs, 20 Razzberrys ...
http://prnt.sc/chnux3
3 - The column numbers are too many ... for ? a futur update ?

**Comment by Nath789** [comment]
**#3**
The reload button adds more columns without clearing the current ones.
I added a code to clear them first at #3847

**Comment by suljo94** [comment]
#2 is reported look 2 issues lower
