### ISSUE TITLE
Reload for pokemon

### ISSUE THREAD

**Issue by toxic189090** [Ar1i/PokemonGo-Bot#3855]
please put back the reload button for Pokemon so it will reload every "x" amount of time

![997fb596ae0679885e2eb9d0b4fc54ea](https://cloud.githubusercontent.com/assets/21367666/18493116/d31c8326-79dc-11e6-9300-8da991b38f3e.png)

**Comment by AlpaEZPZ** [comment]
u have to increase the size of the window...

**Comment by toxic189090** [comment]
ooooh lol thanks

**Comment by toxic189090** [comment]
![12b14b97fe1f0c3dde42e40fd0beb538](https://cloud.githubusercontent.com/assets/21367666/18494194/c22e8306-79e2-11e6-9aed-4610b06f195c.png)

sorta worked

**Comment by suljo94** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/13616056/18495733/7e9b2818-7a20-11e6-95e8-c6689f3787ef.png
@Ar1i @MTK4355  could you update the buildnumber because the update scrips doesn't find 1,4,8 it sees 1,4,7 as the last one

**Comment by MTK4355** [comment]
Done.
