### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by AlexGagne10** [Ar1i/PokemonGo-Bot#3857]
I have a fews problems with the update.

Some Pokemon is not evolvable!
Reload button is on top of the screen
The bot bug when I transfers more than 13 Pokemon
When I resize the screen exemple width 333, its not possible to come back to width 200.

![capture](https://cloud.githubusercontent.com/assets/20649406/18494209/dc5ed94c-79e2-11e6-8dae-631e53b52a4e.JPG)

**Comment by toxic189090** [comment]
im having the same issues

**Comment by AlpaEZPZ** [comment]
have u updated ? since update everything is fine

**Comment by AlexGagne10** [comment]
Yes my version is 1.1.4.7

**Comment by MTK4355** [comment]
Confirm still an issue with 1.1.4.9?

**Comment by AlexGagne10** [comment]
Work Perfect now, thank you very much ;)
