### ISSUE TITLE
Me again with 3 new issues(number 3 is urgent)

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3860]
1   the use lure~~incense/lucky egg~~ buttons don't do anything when clicked/they have a delayed reaction they uwork but it doesn't go out of your inventory directly and the timer is gone, lure button doesn't work tho

~~when you click pause walking the bot thinks he is doing a schedualed pauze and if you didn't set anything in pause time it starts walking after a few seconds~~ FIXED

not ideal when you want him to wait at a pokestop and use a lure and lucky egg and incense

3 keep getting this every 2-3 minutes he cant handle the number of available pokestops that is spit out at the beginning (crashes after the number is spit out) 
`[02:25:39] Exception: System.InvalidOperationException: Invoke of BeginInvoke kan niet op een besturingselement worden aangeroepen tot de vensterkoppeling is gemaakt.
   bij System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bij System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   bij PokemonGo.RocketAPI.Console.LocationSelect.InfoObservable_HandlePokeStop(FortData[] pokeStops)
   bij PokemonGo.RocketAPI.Logic.LogicInfoObservable.AvailablePokeStopHandler.Invoke(FortData[] pokeStops)
   bij PokemonGo.RocketAPI.Logic.LogicInfoObservable.PushAvailablePokeStopLocations(FortData[] pokeStop) in C:\Users\Matt\Source\Repos\PokemonGo-Bot2\PokemonGo.RocketAPI.Logic\LogicInfoObservable.cs:regel 50
   bij PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__36.MoveNext() in C:\Users\Matt\Source\Repos\PokemonGo-Bot2\PokemonGo.RocketAPI.Logic\Logic.cs:regel 643
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__29.MoveNext() in C:\Users\Matt\Source\Repos\PokemonGo-Bot2\PokemonGo.RocketAPI.Logic\Logic.cs:regel 214
[02:25:39] Starting again in 60 seconds...`

**Comment by MTK4355** [comment]
Will it run without error if the location map is not opened?

**Comment by suljo94** [comment]
It wasnt opened
