### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by navzmic** [Ar1i/PokemonGo-Bot#3863]
![untitled](https://cloud.githubusercontent.com/assets/21230846/18500716/a7caa0b8-7a7c-11e6-9752-947517e54b91.png)

**Comment by navzmic** [comment]
what is that at the red text?

**Comment by AiVo7z** [comment]
I get this error like every few minutes and instead of restarting every 10 secs like before, it takes 60 secs.

**Comment by suljo94** [comment]
D #3860 please close this issue it is already rported 2X and move talks to the linked thread to better give the developers an idea what and when it happens also their is an temp fix in the other thread(don't open the map)

**Comment by navzmic** [comment]
i see.. thank you ^_^
