### ISSUE TITLE
being able to choice name, catch starter pkm?

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3865]
If I create a new account, Im forced to log every acc in to skip tutorial, choice a starter pkm as well as picking a Name. Could you build that Feature in ? Something like a popup that asks for the Name you'd like to have. Especially nowdays when we can't Login (due to update) it's a Feature we could Need.

Thanks in advance! Bot rly got great last past week, loving the autoupdate!

**Comment by MTK4355** [comment]
Not sure how we'd make that happen. I think the effort would be better spent trying to make the bot work with 0.37!
