### ISSUE TITLE
Auto-Update while bot is running doesn't work

### ISSUE THREAD

**Issue by InZaNeSkIl1zZ** [Ar1i/PokemonGo-Bot#3866]
When the bot stops to get the newest update, the update doesn't load. If I close the updatewindow the bot starts to run again. But after a few minutes it stops again to update. Still with no results. The code it shows is on the screenshots.

![unbenannt](https://cloud.githubusercontent.com/assets/21690506/18502076/2cd6ba4e-7a55-11e6-85c9-da4217c878ec.PNG)

**Comment by suljo94** [comment]
try creating a new version, since pokelist works for everybody else I would say it is just a misconfig

**Comment by InZaNeSkIl1zZ** [comment]
Okay thanks
