### ISSUE TITLE
Bot recycles every pokeball if you start it

### ISSUE THREAD

**Issue by AiVo7z** [Ar1i/PokemonGo-Bot#3868]
My pokeball amount is set to 80 i.e as soon as I start the bot it recycles 79. Once the bot is running it doesn't do that for collected ones. But as soon as I start the bot again, it recycles every normal pokeball and leave 1 left. If the bot's running it also says 80 pokeballs in the new item tab.

**Comment by MTK4355** [comment]
What version?

**Comment by AiVo7z** [comment]
Lastest Version atm used autoupdates. Sometimes if I check the itemtab it says 1 pokeball, I set it back to 80 and half an hour later when I watched it set itself back to 1. It's kinda random but happens alot, especially if I restart the bot a couple of times.

**Comment by AiVo7z** [comment]
Version 1.1.4.9

**Comment by MTK4355** [comment]
Thanks, I'll take a look.

**Comment by AiVo7z** [comment]
http://www.pic-upload.de/view-31693077/Unbenannt.jpg.html

**Comment by AiVo7z** [comment]
Restarted the bot again for you, as you can see I've had 22 Pokeballs and set 100, then it recycles 21 balls so I was left with only 1 ball left. Itemtab says 100 like wise. Thanks for checking this!

**Comment by AiVo7z** [comment]
updated to 1.1.5.1 now.  It still recycles very pokeball till I've 1 left. (not sure if it was your update, just saying)

**Comment by suljo94** [comment]
@AiVo7z could you make a clean install of the bot and see if it happens again on the clean version, could be a wrongly read config file

**Comment by AiVo7z** [comment]
I've used a new copy and it still recycles my pokeballs :/

**Comment by suljo94** [comment]
Which amounts did you set in the main gui not the pokelist one

**Comment by AiVo7z** [comment]
Both I put in 80 ever since for months, after that error appeared I changed that value to 100 for testings, now that I reinstalled it, I used 80 again. This happened as soon as I updated to Version 1.1.4.9 but newest Version atm 1.1.5.1 got same prob. :/ 

If I disable catch pokemon (to stack pokeball) it enables itself as soon as I atleast got 1 pokeball back from Spinning a pokestop. .....therefore iam 90% out of pokeballs.

**Comment by coffeexp** [comment]
@MTK4355 not the same issue though but related to pokeballs: https://github.com/Ar1i/PokemonGo-Bot/issues/3875 :) hope you have time to answer my query.. thanks!! :)

**Comment by s3if** [comment]
issues with pokeballs also, recycling wrong amounts to keep it at 10 although it should be 50  as i've done in the gui and config, thanks!

**Comment by AiVo7z** [comment]
@coffeexp I wish my bot wouldn't recycle ... wish I had that issue like #3875

**Comment by farid93** [comment]
mine working as normal...

**Comment by AiVo7z** [comment]
I used an old Version and it works like it should. But I don't want to use that old thingy, its like 2 weeks old and misses alot of Features alrdy. :/

**Comment by suljo94** [comment]
@AiVo7z when you set up new version you set it up somwhere else right, not in the same folder?

**Comment by AiVo7z** [comment]
lol ofc I do. I even tried another PC it's still the same.

**Comment by AiVo7z** [comment]
I always put all potions to 1. maybe somehow the bot sets this number for pokeballs as well, I changed all potions to 10 now, but it Needs time to check, I don't have pokeballs to recycle. It's like getting 2 balls but 3 pokemons appear. I used a new account so I've gotten some from lvl up, but it takes longer for lvling now.

**Comment by MTK4355** [comment]
Yeah, still something going on here, but only for some. I think the localization might be an issue somehow.  Not sure how language would affect it, but that's my only guess at the moment. Unless all configs need to be cleared and started fresh? 

Anyone experiencing the problem tried that?

**Comment by suljo94** [comment]
@AiVo7z  could you please upload the itelslist file from the config folder

**Comment by suljo94** [comment]
@MTK4355 okee so my last guess, maybe someone transelated the potion and pokeball wrong and they somehow got mixed up
@AiVo7z does your itemslists match mine in order (must match exactly)
![naamloos](https://cloud.githubusercontent.com/assets/13616056/18517402/6d4610ec-7a9c-11e6-9c0e-060ed698ccc5.png)
![naamloovs](https://cloud.githubusercontent.com/assets/13616056/18517403/6d4aad00-7a9c-11e6-82d7-c3d3a1932e21.png)

**Comment by AiVo7z** [comment]
I've changed the amount of potions to 10 (every Kind of potion, revive etc.) now the bot still recycles on Startup but leaves 10 instead of 1. That means instead of potion it recycles pokeballs. Since I've always put for everything except berrys and pokeballs I only have that error since last couple updates. guess Suljo is right.

**Comment by AiVo7z** [comment]
Yes it matches your Screen, only diffrence that lvl is too low for Ultra balls yet....

**Comment by suljo94** [comment]
and did you change the languege? could you check my pictures and your bot someone transelated wrong I think

**Comment by suljo94** [comment]
But you should be able to see the ultrabal option in the bot

**Comment by Xelwon** [comment]
same as other two thread.
problem was that max potions box are using internal variable of pokeballs, you are putting 0 in max potions so you ar putting 0 in pokeball used to the bug.

problem solved into my fork for now.
https://github.com/Xelwon/PokemonGo-Bot/tree/master/Builds-Only
