### ISSUE TITLE
fixed Location

### ISSUE THREAD

**Issue by larrrlarrr** [Ar1i/PokemonGo-Bot#387]
Yesterday the location was fine. When i put in the coordinates it would teleport me to San Francisco (where i wanted to be) Today on the other hand its default location is central park and when i put the coordinates in it will say walking 348923984 meters will take 290403.23 seconds. I have updated and do not know why it is starting me all the way in new york this time

**Comment by Logxn** [comment]
close the bot.
open the folder "configs"
delete "lastcoords.txt"
start the bot again.

Repeat if you have a new location

**Comment by 3210x** [comment]
you just had to delete LastCoord File, in the Config Directories

**Comment by K0zY** [comment]
[http://prntscr.com/bzgbyi](url)
i dont have that folder configs
