### ISSUE TITLE
1.1.5.0 Permanent die selbe Fehlermeldung

### ISSUE THREAD

**Issue by Blubb123** [Ar1i/PokemonGo-Bot#3871]
Permanent die selbe Fehlermeldung
Bot versucht auf falsches User Profil zuzugreifen C:\Users\Matt\...

![image](https://cloud.githubusercontent.com/assets/21291762/18505361/262a76e2-7a67-11e6-8b0b-a918e93f4151.png)

**Comment by AiVo7z** [comment]
Du musst mit den Optionen spielen, irgendwas davon lässt den Bot abstürzen, versuch mal Evoling komplett raus zu nehmen, wenn du das noch drin hast, bis nen Update kommt.

**Comment by suljo94** [comment]
#3860 please close this issue because it is reported already
