### ISSUE TITLE
0.37.0 

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#3872]
damn!!!  My pogo on phone updated without any notification , i even set it to not update without permission (feelsbadman) but everything works except for the gym everytime i fight a gym just after the Go signal it errors and my avatar runs away from the gym. Can i still bot if i delete the data and cache in my phone??

**Comment by suljo94** [comment]
android or ios, if you are on android download the apk (0,35) fromAPKmirror  and downgrade, keep in mind that you don't update it again or you will get banned my dummy account isn't banned yet either so niantic could think you just downgraded but it is technically not safe for you to bot anymore so nobody will take resposabliity if you get banned and you have a bigger chance to get banned

if you use ios (not jailbroken) you can't downgrade so you can use the bot but with an even bigger chance to get banned

**Comment by mcferson** [comment]
didn't you never think it would be smarter from you to KEEP old versions to download ???
The app is up to date and we are warned ONLY AFTER LAUNCH the bad new version. It's just STUPID.

**Comment by Zestiria00** [comment]
I did keep the older version but it updated by itself. I even set it in google apps to not update without  permission or no auto update on apps but still it did.

**Comment by Blubb123** [comment]
The issue is the new ninantic version, not the bot version...
You can still play the bot, if you don't open the new version of ninantic on your phone.
If you opened the new ninantic version, there is no way back to the bot. 

Maybe there will be a new bot version which can emulate the encrypted message by ninantic, maybe not. 
But thats just a pie in the sky.

**Comment by s3if** [comment]
there's a rooted version for IOS on tutuapp which let's you decide the location and everything to play pokemon go with navigators just released today for 0.37 (android) and 1.7.0 (IOS), is it safer than the original if using the same location? but not at the same time of usage

**Comment by Zestiria00** [comment]
I downloaded the old version again and will try  to bot on my low lvl acc.

**Comment by s3if** [comment]
I tried using rooted version i mentioned earlier then the bot and it's working just fine, enjoy ;)

**Comment by TxShack** [comment]
Well I did opened the .37 apk 1 time. If I get banned IDGAF. Simple.
