### ISSUE TITLE
Can't find any Pokestop

### ISSUE THREAD

**Issue by zemax07** [Ar1i/PokemonGo-Bot#3874]
I was setting my location in a big city, but when I started the bot, it says : "can't find any pokestops..."
it was working before, but not now

**Comment by suljo94** [comment]
You are softbanned for jumping to far

**Comment by zemax07** [comment]
No I jumped next  to my real location and when I play IRL it works without any problem

**Comment by suljo94** [comment]
Delete the last cord file from config

**Comment by Adj1e** [comment]
use https://github.com/MariusSolaat/QuickSpin-1.3. I always jump from Central Park NY (Bot) and Jump to my country to batle at gym (Nox)

**Comment by zemax07** [comment]
Thanks suljo94, it works !

**Comment by suljo94** [comment]
Please vlose the issue😆

**Comment by zemax07** [comment]
But it doesn't work everytime...

**Comment by zemax07** [comment]
When I delete the Lastcord file sometimes it does nothing

**Comment by suljo94** [comment]
Because you need to set location again

**Comment by zemax07** [comment]
I did...

**Comment by suljo94** [comment]
Just stay in one General area and no need to delete it constantly
