### ISSUE TITLE
Items list never cleared when reloaded

### ISSUE THREAD

**Issue by Nath789** [Ar1i/PokemonGo-Bot#3875]
Previously, the columns of the pokemons get a duplicate.
Right now, it's the items list when you use the **Reload** button at the upper right location of the form.

**Comment by suljo94** [comment]
To reload item list click the reload button under the actual item list

**Comment by coffeexp** [comment]
@MTK4355 @Ar1i 
question, is this a bug?
I set my pokeballs to 25 max only but it reaches 100 pcs:
[img]http://i.imgur.com/LJKkNHW.jpg[/img]
<blockquote class="imgur-embed-pub" lang="en" data-id="LJKkNHW"><a href="//imgur.com/LJKkNHW">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
[img]http://i.imgur.com/ROJVeJb.jpg[/img]
<blockquote class="imgur-embed-pub" lang="en" data-id="ROJVeJb"><a href="//imgur.com/ROJVeJb">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by suljo94** [comment]
What number does  the items tab in the pokemon list say

**Comment by coffeexp** [comment]
@suljo94 see attached link for screenshot.. :)

**Comment by suljo94** [comment]
No the one in the pokelist gui after you press run

**Comment by Xelwon** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/20685015/18519849/ac0d839c-7aa5-11e6-8cf4-1bc77bfa2ddf.png)
Currenly, Items tab. have two sections, first is to set how many items you will have as maximum.
Bot recycles values over these each time at start the logic. So if you change values, you will be see more than those number. You will wait to the logic restart and recycle they.

The other section is to see how many items you have currenly. so you need do reload to see items of that moment. Rightclicking you can recycle manualty how many you dont want.

**Comment by coffeexp** [comment]
@suljo94  now this is weird.. i did not touch anything on that tab.. it should have match the numbers/amount on the setting once the bot runs, right?
![tab](https://cloud.githubusercontent.com/assets/20931279/18521983/c927b9f8-7ae0-11e6-8940-42368dbb02d4.jpg)

**Comment by suljo94** [comment]
Hide your name

Yes it should match,  but @MTK4355  has in a stroke of brilliance added a debug logging feature which should give him an answer to the why

**Comment by Xelwon** [comment]
same as other bug

problem solved in my fork for now.

https://github.com/Xelwon/PokemonGo-Bot/tree/master/Builds-Only
