### ISSUE TITLE
Version von 14 09 2016 Error Balls

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3878]
![version14092016](https://cloud.githubusercontent.com/assets/22030029/18520132/da1b7b08-7aa6-11e6-8314-ef8eed85a665.jpg)

why 234 ?

**Comment by Schnitzelvernichter** [comment]
und er sammelt keine Bälle wie er sollte , da laufen in hintergrund irgendwelche Sachen falsch ....
Er benutzt irgendeine eigene Item Liste und nimmt nicht die von user

**Comment by Schnitzelvernichter** [comment]
![lol1](https://cloud.githubusercontent.com/assets/22030029/18520892/0d91c322-7aaa-11e6-964d-ab74a3fb75ab.jpg)
lol

**Comment by Xelwon** [comment]
I found the problem, revives box uses internal variable of pokeballs, so you are not modifying revives.
problem solved in my fork.
https://github.com/Xelwon/PokemonGo-Bot/tree/master/Builds-Only
