### ISSUE TITLE
I took the boat?!

### ISSUE THREAD

**Issue by YellowTomato** [Ar1i/PokemonGo-Bot#3882]
Not a problem - just thought it was funny:
![the_boat](https://cloud.githubusercontent.com/assets/22130159/18525357/6bdffb62-7abc-11e6-8cb4-a97a3857ab44.png)

**Comment by TxShack** [comment]
L3GIT M8. Thats what I call perfect route.

**Comment by Xelwon** [comment]
:D

**Comment by Adj1e** [comment]
Hahaha LOL

**Comment by toxic189090** [comment]
lol that bot has a brain of its own
