### ISSUE TITLE
Sending exception info to Logger

### ISSUE THREAD

**Issue by M31860** [Ar1i/PokemonGo-Bot#3883]
![unbenannt](https://cloud.githubusercontent.com/assets/20891505/18526049/4f74cae0-7abf-11e6-8a0a-7cacf6dc4a19.jpg)

What does that mean?

**Comment by gedous** [comment]
i think, when trying to update client position it threw an exception. u can look into "Navigation.cs" row 101

**Comment by Xelwon** [comment]
Is a controled exception, sometimes the bot wait a response for niantic server bot the response never comes, (or dont comes at time) then the pokemon api throws an exception. That message is to say to the end user that a controled exception was cautch and if he want, can open the log file to read more about it.
