### ISSUE TITLE
URGENT!!!!!! someone  forgot to update the ver number in the build

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3886]
could you update that number or change the git ver.md to 1,1,5,2 because now it tries to update but because the downloaded version is 1,1,5,2(someone forgot to change ità and the git ver;.md is 1,1,5,3 it is stuck in an update loop

**Comment by 1celoved** [comment]
Hey, just to let you know, they have updated the app and fixed the issue. They closed my issue :).

**Comment by MTK4355** [comment]
Closed this one too. :)
