### ISSUE TITLE
error message...

### ISSUE THREAD

**Issue by Slayer013** [Ar1i/PokemonGo-Bot#3888]
Hi Guys!

i tried the new updated bot... after a few minutes of farming this error message appeared...
can anyone tell me what this is about? and what i can do to prevent it?
i've waited for 60 seconds and this error message appeared again..
i'm not good with codes.. sorry >.<

thanks!

![untitled](https://cloud.githubusercontent.com/assets/22064147/18534668/293d8158-7b20-11e6-8c60-49834dc8ea04.jpg)

**Comment by MTK4355** [comment]
Did you have the map open?

**Comment by Slayer013** [comment]
nope... i usually run the bot without opening the map.. because i dont see pokestops on the map too..
i only see the default location and the bot movement but no pokestops... so i just close it...
do i have to keep the map open..? thanks again!

**Comment by MTK4355** [comment]
Yeah, for now. It will bomb like this when closed.. It still tries to update the map and it's not there anymore! Might be fixed in latest version, as the map and Pokemon GUIs are integral.

**Comment by jmo93** [comment]
Same error in the latest version, bot even dont start farmin

**Comment by Slayer013** [comment]
thanks @MTK4355 .. i'll try playing with map open for now.. and try the latest update too!
i'll close this issue now
