### ISSUE TITLE
Tips to don´t get soft banned

### ISSUE THREAD

**Issue by NerdisDev** [Ar1i/PokemonGo-Bot#389]
Hello, here are tips to don´t get a soft ban. 

1. Change the default location. Seems Niantic bans all players which login/start at the default location.
2. Don´t set the speed to high. Don´t be faster than a airplane :D. I think 300km/h is enough.
3. Don´t Teleport to other countrys/locations to fast. wait 4h if you want to switch your country.
4. Don´t power up you Pokémons with the Bot. The bot powers them up, higher than allowed. Niantic bans that.
5. Use an American IP. I recommend CyberGhost it´s for free!

**Comment by TMaddox** [comment]
if you power up a pokemon higher than allowed and you get the softban, then wait or 1337 unban, is it still better than maximum or again normal ?

**Comment by NerdisDev** [comment]
Its still better. ;) But the ban is longer than normal.

**Comment by TMaddox** [comment]
does 1337 unban method work ?

**Comment by NerdisDev** [comment]
@TMaddox No. I tested it on 3 accounts 2 times.

**Comment by TMaddox** [comment]
thx

**Comment by Tochez** [comment]
awkward the 1337 unban method works for me everytime :/ @NerdisDev @TMaddox
