### ISSUE TITLE
Bot with new update okay? 

### ISSUE THREAD

**Issue by shadowahs** [Ar1i/PokemonGo-Bot#3890]
Is it okay if I run the bot (near my real location) while catching pokemon and farming pokestops are off?
Is this any better than catching pokemon, because really i just want candies with the new buddy system

**Comment by AlpaEZPZ** [comment]
u should better catch pokemon and farm pokestops caus this is what the bot can do best at the moment.
The "pokebuddy" feature is new and not implemented to the bot, so i dont know how the bot will behave if u give him a buddy.
