### ISSUE TITLE
Unable to catch any pokemon after new update

### ISSUE THREAD

**Issue by Spoonyi** [Ar1i/PokemonGo-Bot#3894]
I haven't updated the app on my phone and the bot can still spin pokestops and collect items but every pokemon found gets away, is this due to the recent pokemon app update?

I've tested with an older version of the bot and the current 1.1.5.3 version 
![github](https://cloud.githubusercontent.com/assets/22220916/18557068/56df0894-7b65-11e6-88b5-db4b35300419.png)

**Comment by Adj1e** [comment]
use quickspin bro.

**Comment by AlpaEZPZ** [comment]
got same problem. i think it hast something to do with ur count of catched pokemon.
I had this sometimes when i catched about 60 - 90 pokemon per hour. if i waited some hours the problem got solved by itself.
