### ISSUE TITLE
Issue with new Gui & Questions

### ISSUE THREAD

**Issue by matrix1420** [Ar1i/PokemonGo-Bot#39]
#1 

Starting Multiple *Bots* with a simple .bat Restart script =
All Consoles Re-open with the Gui , all Settings are Resetet and the Bot starts again when i Press the Save Configuration "button" But in this Case this makes my RR script pretty useless ..and without Restarts my Bot Freezes sometimes.

#2 what means the the Option "Max CP to Transfer" is this like the old Option " Dont Transfer with CP Over" ? 

#3 Can u add a "Priority Option , like if the "Scan" finds 3 Pokemons that are Able to Catch he try first to catch the Pokemon with Highest Priority if one of these has a "High" Priority ..to avoid escape rare/special&co Pokemons?

#4 Can u add Support for Multiple Accounts ? so that I can add over One Gui  XX Accounts ( Gmail&Ptc Mixed) and the Bot/Gui add in a Config Folder for each of them a single Config 

Sorry for Down Syndrome English skills ;)

**Comment by Ar1i** [comment]
The first point will be fixed later, will add a option to run without gui. But for setting it up, you need to run it. 

2. Yes

3. Probably later..

4. Uhm will probably not happen in the near time..
