### ISSUE TITLE
any advise?

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#390]
![screenshot_9](https://cloud.githubusercontent.com/assets/20727615/17270651/1ee4b46a-5668-11e6-9938-122b11a53e11.png)

**Comment by Logxn** [comment]
Its not bad if it shows this error =)

**Comment by gnzl0o** [comment]
it stops there i waited like 5 minuts

**Comment by gnzl0o** [comment]
i just changed the location very far from central park, and deleted the loc file and its running

**Comment by gise88** [comment]
The first line is the important one.. Seems that another process is using the file "lastcords.txt". Did you have two bots actives in the same moment? Or maybe you have some text editor with this file opened?

**Comment by Ar1i** [comment]
Dont run it directly out of the rar archiv. Put in a seperate folder.
