### ISSUE TITLE
PROBLEM - Very low speed on walking

### ISSUE THREAD

**Issue by OldSch0ol** [Ar1i/PokemonGo-Bot#3903]
This is what I get even setting different walking speeds.

Doing the math in this example below I´m walking near 0,83 Km/h (Yeah less than 1 Km/h)

[18:19:57] Remaining Time to Run: 200,06 minutes
[18:19:57] Remaining Time until break: 49,06 minutes
[18:20:01] Next Pokestop: Gapstow Bridge in 106,06m distance.
[18:20:01] Setting Walk speed for this leg to 0km/h
[18:20:01] Distance to target location: 106,06 meters. Will take 454,59 seconds!

**Comment by suljo94** [comment]
Set your own minimum  speed

**Comment by dannyarboleda** [comment]
I establish my own speed but still supremely slow way , it seems as if not to walk

**Comment by OldSch0ol** [comment]
When i started to write this issue there was no post about it. I was doing some tests before I post id.

I tried to disable random speed - no success
Tried to set high speed (30Km/h) - no success
Tried to set Max and Min speed as equals - no success
Tried to set Max (15-14) and min (2 - 5) - no success

**Comment by coffeexp** [comment]
Same issue.. the travelspeed set to 0!!
![travelspeed](https://cloud.githubusercontent.com/assets/20931279/18568659/da6137c6-7bd0-11e6-8417-0a3975d4382e.jpg)

**Comment by dannyarboleda** [comment]
This error occurred since last update

**Comment by OldSch0ol** [comment]
Working great now!
