### ISSUE TITLE
 It works perfect!! Thank you!! Bugs Fixed !!

### ISSUE THREAD

**Issue by dannyarboleda** [Ar1i/PokemonGo-Bot#3906]
It works perfect!! Thank you!! Bugs Fixed !!

**Comment by suljo94** [comment]
the issues section is only for issues please close this issue to prevent cluthering

**Comment by riautama77** [comment]
still has little problem, 
Error catching Pokemon: EncounterNotFound
this message is still emerging.

**Comment by riautama77** [comment]
secondly, if using google maps routing, 
the pokestops keep refreshing, prefer to stay in pink color after farmed.

**Comment by suljo94** [comment]
The encounter not found happens when the bot sees the pokemon but their timer runs out before he can catch them
