### ISSUE TITLE
CANNOT GET LOCATION

### ISSUE THREAD

**Issue by iggithub** [Ar1i/PokemonGo-Bot#3908]
![00012356](https://cloud.githubusercontent.com/assets/22227886/18570867/3aa681fe-7be0-11e6-9f57-d5bc0ef76152.png)

After I click the "Get Point" bottom, something wrong...
I cant set location

**Comment by Xelwon** [comment]
to use get point you need enter an address before.
But I 'm watching that you can not see set location button, that is after of altitude box.

**Comment by iggithub** [comment]
![00033333333](https://cloud.githubusercontent.com/assets/22227886/18572231/f9ddc2e8-7beb-11e6-8f59-1fd082a06a08.png)

I try again & again....
now I found that No matter where I move，after I click the GET POINT bottom,
it goes to the same point near the sea of Africa....

**Comment by Nikoholic19** [comment]
when you *Get Point* with your adress. You click in the Altitude Field and than click Tabulator. Now you marked the invisible Set Location Button. Klick Enter and you Set your Location.

**Comment by Zestiria00** [comment]
just copy your past config on builds only and paste it on the new
