### ISSUE TITLE
Have finished updating the phone continue to use it to sign bot people?

### ISSUE THREAD

**Issue by tom9517535** [Ar1i/PokemonGo-Bot#3909]
Also I had to go through a few days.
It was someone tested using the update 0.37 finished up to now not been a lock on it?.
sorry I just want to know how much risk.
Finally, of course, very grateful Author.~^^

**Comment by MordorGames** [comment]
I use 0.37 and bot for three days and don't have problem.
I used the test account, does not recommend use the real account.
I will try to sunday, If i have no problem, i will use my real account.
