### ISSUE TITLE
Pokelist: Favorites (Option Favorites wont get transfered) 

### ISSUE THREAD

**Issue by NoticeMeSenpaiPLS** [Ar1i/PokemonGo-Bot#391]
Sometimes its hard to set rules with the current options to transfer just what i wont to get transfered.

Wouldnt it be great if you can set favorites in the Pokelist and these Favorites wont get transfered?
This would make the sorting of our pokemon much more individuall :)

Please think about this idea ^-^

**Comment by NerdisDev** [comment]
this function already exist xD!

**Comment by NerdisDev** [comment]
@NoticeMeSenpaiPLS https://gyazo.com/0f6ac4cc514ffe8abb4873e301bc6dbd

**Comment by NoticeMeSenpaiPLS** [comment]
And what if i just dont want a single one not transfered instead of every pokemon with the same name?

**Comment by TMaddox** [comment]
@NoticeMeSenpaiPLS  you mean like renaiming f.e. a "Magikarp" with 90% IV to "pkm001" and then this specific one wont get tranferred even if you get one with higher IV and CP ?

If yes this would be a good idea

**Comment by jackrose01** [comment]
@NerdisDev  @TMaddox  : Have you open your Pokemon Go Client? there is have a feature to mark a pokemon as favorite. ( Star ) at the top right pokemon description.
