### ISSUE TITLE
Having problems with spinning pokestops!

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#3911]
My avatar marks but  it Can't loot item?? and no exp
![untitled](https://cloud.githubusercontent.com/assets/22138908/18578342/c4d8b1ce-7c32-11e6-94ea-4d7931cfb5b0.jpg)

**Comment by Blubb123** [comment]
softban?

**Comment by Zestiria00** [comment]
I dont think so. Im using a proxy in my place and botting it , after 30 minutes it started to work again then just now(2hrs past) it went to shits again so i just stopped it for now.

**Comment by Adj1e** [comment]
Softban, use quickspin.

**Comment by Zestiria00** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22138908/18587266/704cc60e-7c64-11e6-9b2e-59d3ae3f7232.png). how can it be a soft ban? what cause it? i dont snipe or move 10km/s+ and i've only started botting for 3 hrs bfore and now its happening again in the photo im showing.

**Comment by Zestiria00** [comment]
![received_10202162652064055](https://cloud.githubusercontent.com/assets/22138908/18588429/c8d6207c-7c69-11e6-9821-044671f092fa.jpeg) works fine in knox first try no need to spin 40 times!

**Comment by MTK4355** [comment]
What speed are you using?

**Comment by Zestiria00** [comment]
2-9km only

**Comment by dannyarboleda** [comment]
I do not get anything from the pokestops .
I would also happens the same
![1](https://cloud.githubusercontent.com/assets/22225383/18601984/c8f00f3e-7c2b-11e6-923f-bca25d098fc7.PNG)

**Comment by coffeexp** [comment]
IP banned.. try using proxy.. :)

**Comment by suljo94** [comment]
Check if your items are at max was doing the same here but for some reason it won't recycle

**Comment by Zestiria00** [comment]
If thats an ip ban wouldnt it say that there are no pokestops to a certain mile? My inventory is not full

**Comment by Bence98007** [comment]
Softbanned. Maybe you can come back from that, but I would not use the bot again on that account.

**Comment by Zestiria00** [comment]
"I dont think so.After 30 minutes it started to work again then just now(2hrs past) it went to shits again so i just stopped it for now and even the pokestop turned purple" my 2nd comment said. What im trying to say there's time that its doinf that
