### ISSUE TITLE
I know that is not about bot (MR. Mine) EUrope

### ISSUE THREAD

**Issue by Shoier** [Ar1i/PokemonGo-Bot#3914]
Anybody know where is the nest to Mr. Mine in Europe ? I can t catch them

**Comment by coffeexp** [comment]
I think you can get it through eggs.. :)

**Comment by Buckrogers81** [comment]
try this location. I got a couple of them 

50.082475
8.239889
in a Radius of 7000 meters

**Comment by Buckrogers81** [comment]
And by the way. I still need a location für Ditto ( Pokodex # 132 ) in Australia. Anybody got a glue?

**Comment by suljo94** [comment]
@Buckrogers81 everybody needs ditto since he isn't released yet

**Comment by Buckrogers81** [comment]
Well, I have read lots of stories :-) never give up :-)

**Comment by LeDudeGolfer** [comment]
Hey,
There is plenty of Mr.Mimes in Prague tho. If u have something like pokevision, then u can easily hunt them with bot. 

HF
