### ISSUE TITLE
Wird man seit dem Buddy Update jetzt gebannt oder nicht?

### ISSUE THREAD

**Issue by Croc0008** [Ar1i/PokemonGo-Bot#3916]
Hey!
Ich habe mir auf mein Handy das Buddy Update heruntergeladen. Werde ich dann jetzt gebannt, wenn ich den Bot benutze? Denn wenn man den Bot startet steht da ja, Log dich nicht ein mit der neuen Version!
Ist es jetzt also gefährlich wenn ich mich einlogge oder kann ich das problemlos machen ohne Angst zu haben, dass ich gebannt werde?
~Croc0008

**Comment by Buckrogers81** [comment]
Ja, Du wirst gebannt. Ich würde dir dringend empfehlen das nicht zu tun.

**Comment by Blubb123** [comment]
sorry , aber warum sollte jemand schreiben, dass es gefährlich ist, wenn es das nicht ist ??

**Comment by AlpaEZPZ** [comment]
Es ist nicht empfehlenswert aktuell zwischen handy und bot zu switchen. vorallem wenn man auf dem handy die neuste version hat.
Wenn du deinen account auf dem handy spielen willst würde ich dir raten ein paar tage zu warten und dann nach dem einloggen auf dem handy einen anderen account mit dem bot laufen zu lassen.

**Comment by Logxn** [comment]
^
