### ISSUE TITLE
Not about bot: How to create a new account?

### ISSUE THREAD

**Issue by YellowTomato** [Ar1i/PokemonGo-Bot#3917]
I used to make account wit the app, do the intro, log out and then start botting. That is not a good idea now (since the account will then have played with version 0.37). How can I start a new account?

**Comment by MTK4355** [comment]
You'll need an android device that can run 0.35 unless you want to take the risk of not completing the tutorial. Another option might be to set up Nox or another android emulator to accomplish this.

**Comment by MTK4355** [comment]
The bot will run as long as your account is valid, so in theory you can just create a PTC account on the web and immediately run the bot with it. I would advise against this though, because it would be pretty obvious that you never used the app if someone decided to look.

**Comment by Logxn** [comment]
^
