### ISSUE TITLE
recycling bug

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#3919]
![naamloos](https://cloud.githubusercontent.com/assets/13616056/18595189/f66e1358-7c43-11e6-9d83-d61ff50185ca.png)
I pressed the update items button after it finished the debug and these are my item totals
see set amonts the bot saying that it recyled but it didn't do anything

**Comment by Xelwon** [comment]
all is correct on that image.
gray lines are the result of the recycling.
You must see how many itews had you got before. This information is in green color.

**Comment by Logxn** [comment]
Gray lines are dev messages

**Comment by suljo94** [comment]
@Logxn @Xelwon this was at the begining when the bot starts and It didn't recycle anything before. I know from experience that is starts recycling when you start is and now it doesn't do anything
