### ISSUE TITLE
pokeVision "loop"

### ISSUE THREAD

**Issue by FelipeMallmann** [Ar1i/PokemonGo-Bot#392]
I've just updated to lastest version and I noticed that pokevision finds a pokemon and tries to catch it, but while he is walking to this pokemon, pokevision finds another and then he stop going to the first one and changes to the second and so on.. If pokevision finds a lot of pokemons he wont get any

**Comment by NerdisDev** [comment]
disable pokevision :)

**Comment by Ar1i** [comment]
^this.
