### ISSUE TITLE
No function!!

### ISSUE THREAD

**Issue by dannyarboleda** [Ar1i/PokemonGo-Bot#3920]
No funkaaaa!!
![3](https://cloud.githubusercontent.com/assets/22225383/18596655/e86401de-7c0f-11e6-8f8e-7b51b72a20db.PNG)

**Comment by FenrirXx34** [comment]
stop spam pls
maybe permaban ?

**Comment by Xelwon** [comment]
manda pantallazo de la entrada a pokemon go con esa cuenta. ES una excepción típica de baneo permanente, eso que mandas

**Comment by AlpaEZPZ** [comment]
try to reboot pc, sometimes i have problem with connecting and i restart pc. till now it always fixed it.

**Comment by nasierache** [comment]
login via smartphone and use bot again.. just make sure the app on your smartphone is 0.35
