### ISSUE TITLE
Help mee!!

### ISSUE THREAD

**Issue by dannyarboleda** [Ar1i/PokemonGo-Bot#3921]
![3](https://cloud.githubusercontent.com/assets/22225383/18597036/a40c7ca8-7c11-11e6-863c-88f5c948339a.PNG)

**Comment by Xelwon** [comment]
your account was banned.

**Comment by cogumm** [comment]
The same thing happened with me and my account is not banned.

**Comment by nasierache** [comment]
it happen to me too.. login via smartphone using 0.35 and you can use bot again..
