### ISSUE TITLE
Pokestops New Pokemon Go Update 

### ISSUE THREAD

**Issue by voctavio** [Ar1i/PokemonGo-Bot#3923]
I have been using the bot earlier was working fine.  A new Pokemon Go update just came out, now it's not able to find any pokestops. 

![image](https://cloud.githubusercontent.com/assets/22245758/18599231/e14b857c-7c1c-11e6-84a5-b976916b4d19.png)

**Comment by nasierache** [comment]
ip banned

**Comment by voctavio** [comment]
Is that considered a soft Ban?

**Comment by nasierache** [comment]
no..just ip ban i think. how much acc you run with bot on the same time?

**Comment by voctavio** [comment]
2 not at the same time though. I do them at different locations. Different Service Providers

**Comment by nasierache** [comment]
maybe you change a location to frequently

**Comment by voctavio** [comment]
Thank you are right, IP address banned. connected to different IP and everything is fine now.
