### ISSUE TITLE
Set Location ? 1-1-5-7

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3925]
![location](https://cloud.githubusercontent.com/assets/22030029/18601544/b66a3546-7c63-11e6-8d28-b336aecd975f.jpg)

Does not work

**Comment by MTK4355** [comment]
Try 1.1.5.8 and let me know if still an issue

**Comment by zazabi** [comment]
I have the same issue since yesterday morning update. (GMT+7 here)
now I update to 1.1.5.8 and still have an issue, cannot set location.

ps. thank you for all of you guys works. We are really appreciate your effort.  :)

**Comment by Schnitzelvernichter** [comment]
fault is still present
Bot is not running....no Location
