### ISSUE TITLE
Bot stops catching pokemons

### ISSUE THREAD

**Issue by Buddhasama** [Ar1i/PokemonGo-Bot#3927]
After a while the bot just freezes and doesn't catch anymore pokemons for some good while and stays around the same pokestop. I set it to move at ~15km/h and the radius 15000m .

**Comment by Adj1e** [comment]
me too

**Comment by Buddhasama** [comment]
I understand why now. It has something to do with pausing at lures. The biggest problem in that is that it stops catching pokemons properly at lures.
