### ISSUE TITLE
change-Log

### ISSUE THREAD

**Issue by Buckrogers81** [Ar1i/PokemonGo-Bot#3928]
where do I find out what has been changed in newer versons of The Bot

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by MTK4355** [comment]
Discord

Link is on the readme file here
