### ISSUE TITLE
IV bot calculator bug

### ISSUE THREAD

**Issue by Gee3** [Ar1i/PokemonGo-Bot#3929]
when i open my bot 1.1.1.9 and click the IV bar to organized them by percentage of IV you can see that some list here is bug in calculating iv's of the pokemon especially 85% below. we all know that 85% iv of pokemon is good enough for rare pokemon like Snorlax, Lapras, starter pokemon etc. 

I got a snorlax and in the bot iv range it says it is 84% ( i got it from 10km egg ) so i have 30+ candy so when i saw 84% its not bad to powerup using all the candy. but when i open it in the game and check the quality of your pokemon in the Gym Leader you will be disapointed.

for example. 
**Team instinct** (spark) : “Overall, your (Pokemon) looks like it can really battle with the best of them!”) — IV 81% to 100%

but instead of getting this response it will say that it was below 80%. even when you use other iv calculator or checker it is 75% rating. anyone who had the same problem?

**Comment by terence1016** [comment]
Well, just check the IV "A-D-S"
A means the attack (max value is 15)
D means the defence (max value is 15)
S means the stamina, hp (max value is 15)

if your pokemon is IV 100%, the A-D-S value should be 15-15-15 :). Sometimes A-D-S is 7-15-15, your pokemon still got 80% IV value above lol

Further check is the Primary Moves and Secondary Moves damages.
For example, Snorlax,
Primary Moves can be Lick Fast (5 damage) and Zen Headbutt (12 damage)
Secondary Moves can be Hyper Beam (120 damage), Body Slam (40 damage) and Earthquake (100 damage)

**Comment by Gee3** [comment]
what i meant to say is, the bot iv's calculator is bug, some pokemon iv's  is wrong

**Comment by Xelwon** [comment]
Bot have two method to calculate perfection, First uses IVs direclty and second uses CP (that uses IVs indirectly).

So may be you are seeing in other IVs calculator CP perfection. Try to see in the bot "% CP"  column

**Comment by MordorGames** [comment]
All ivs very diferent than https://pokeassistant.com/main/ivcalculator
