### ISSUE TITLE
Not a bug, just a question.

### ISSUE THREAD

**Issue by AlpaEZPZ** [Ar1i/PokemonGo-Bot#3930]
Guys is someone of u still using nox player ? caus sometimes i want to snipe pokemon but i had some friends got banned by using nox player.
If u know something about it, tell me plz :)

**Comment by Adj1e** [comment]
Hy bro, Im using Bot to farm and catch pokemon, using nox to battle gym and collect 10 coin and I using pokesniper to catch dragonite and their familly that fine. FYI I lev 35, 30, 26 and 18.
