### ISSUE TITLE
This recycling not items

### ISSUE THREAD

**Issue by dannyarboleda** [Ar1i/PokemonGo-Bot#3931]
This recycling not items
![1](https://cloud.githubusercontent.com/assets/22225383/18605976/e3fcd240-7c66-11e6-9267-7457825de1c3.PNG)

**Comment by coffeexp** [comment]
There is an inconsistency on recycling the items.. i restarted the bot so that it will recycle but no luck.. 

![recycling](https://cloud.githubusercontent.com/assets/20931279/18606222/d7982d04-7cdb-11e6-837a-f8c7c5253ec4.jpg)

i  will observe this for a few minutes if it will recycle the excess items..

**Comment by Adj1e** [comment]
Same me to. 
http://prntscr.com/ciyop3

**Comment by coffeexp** [comment]
ok.. after almost an hour, still not recycling.. i tried changing the pokeballs to 15 to trigger the bot but no luck at all.. :( 

![update](https://cloud.githubusercontent.com/assets/20931279/18606466/9017ac0e-7ce3-11e6-83d6-7f7d9786974a.jpg)

**Comment by Jas0nBourne** [comment]
Items recycling in not functional in latest build.

**Comment by suljo94** [comment]
I is functional but it only happens like 1 time every 2 h, maybe you guys could decrease the tick timer

**Comment by MTK4355** [comment]
It will only recycle when you are within 20 items of inventory full. More human-like. I never recycle till my bag is too full to collect more stuff! lol.

**Comment by Jas0nBourne** [comment]
It's just gone wrong with v1.1.5.8. Mine get over 450/350 (stacked from leveling up) with no recycling happen. And it's back to normal in v1.1.5.9. Thank you!
