### ISSUE TITLE
Regarding the latest bot...

### ISSUE THREAD

**Issue by elmokito** [Ar1i/PokemonGo-Bot#3934]
Which is more vulnerable to get a permanent ban? the one with a google account or the one with the ptc account? I started botting at lvl2 with my ptc account, and now I am lvl 20 using the latest version which is v1.1.5.8. I already logged in using this account with the latest version of pogo 0.37.0. what do you think?

**Comment by TeamRedd** [comment]
it don't matter really if they catch u ur done .. from past experience --->5 google account ban 11 ptc account ban .. that when they did mass ban , smart enough never to use ur main account. it never safe to use a bot in the first place .Right now if ur setting ur bot correctly u be good.

**Comment by elmokito** [comment]
So what you're telling me is if I configured my bot right, I won't get banned?

**Comment by Bence98007** [comment]
Well, yes.

**Comment by MTK4355** [comment]
Not if you are using the 0.37 version of the app and then logging in from the bot. Only a matter of time before you are toast, my friend. :(

**Comment by MTK4355** [comment]
PTC or Google doesn't matter. That is just a means of authenticating a user. Either one just as likely to get a ban.

**Comment by vitus0123456** [comment]
In my experience, if you get a soft ban, your account is doom to get hammered.  So, careful and use this great bot wisely to not trigger soft ban. Happy botting :)

**Comment by coffeexp** [comment]
I will patiently wait for the bot to update that includes the buddy system.. and without worrying on opening the app in 0.37 version... ^_^ 

cheers for the awesome bot!!!
