### ISSUE TITLE
pokeball and berries

### ISSUE THREAD

**Issue by spinning149** [Ar1i/PokemonGo-Bot#3935]
i've noticed that the latest version is set using greatball at above 500 so it waste a lot of balls for such a useless pokemon (most of pokemon over 500cp but less than 1000cp is the low iv)  and also the berries, i set to use if chance under 27% but mostly it use at any percentage even over 50% if they found 1 time escaped.

**Comment by MTK4355** [comment]
Right. Any time a pokemon escapes it will use a berry. If berry used already and pokemon escapes it will use next best ball. Greatly reduces the chance of pokemon Flee. Why is this a problem? runnign out of Greatballs or razzberry? Not a problem for me.

**Comment by Bence98007** [comment]
It's not a problem for me too. If the pokemon is below the % limit, the bot will throw a berry. (But you can still select which pokemon the bot should not catch)
The bot collects a lot of pokeballs, so dont worry about that.

**Comment by spinning149** [comment]
Perhaps you may adjust the min cp for using greatball to be 700cp or sth would be appreciate. Thank you for your great work. (Just recommend but if not it would be ok)

**Comment by MTK4355** [comment]
I'll make it variable soon.
