### ISSUE TITLE
Skipping all Pokemon

### ISSUE THREAD

**Issue by M31860** [Ar1i/PokemonGo-Bot#3937]
Hi
Is it normal that the bot sets automaticly the option to do not catch any pokemon?
I have the newest version...
I set it to catch pokemon and after 5 minutes i get this message.
I have no pokeballs, but isnt it so that it then uses the other balls?
![unbenannt2](https://cloud.githubusercontent.com/assets/20891505/18609179/e2ee2a4e-7cfb-11e6-888a-1d9daa176646.jpg)

**Comment by M31860** [comment]
Ok i think i have a problem here... I do not get any items at pokestops?!?

**Comment by M31860** [comment]
I think i have it... The bot did not automaticly transfered the Items. I dont know why...
Restarted the bot and now i get pokeballs after transfering all surplus items.
Close this one

**Comment by Rukeith** [comment]
I also have this problem
