### ISSUE TITLE
Location set Error

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3939]
from 3925

 Schnitzelvernichter commented 20 hours ago

location

Does not work
@MTK4355
Collaborator
MTK4355 commented 20 hours ago

Try 1.1.5.8 and let me know if still an issue
@zazabi
zazabi commented 4 hours ago • edited

I have the same issue since yesterday morning update. (GMT+7 here)
now I update to 1.1.5.8 and still have an issue, cannot set location.

Also, 1.1.5.9 still have an issue. ;(

ps. thank you for all of you guys works. We are really appreciate your effort. :)
@Schnitzelvernichter
Schnitzelvernichter commented just now

fault is still present
Bot is not running....no Location

**Comment by Schnitzelvernichter** [comment]
![location](https://cloud.githubusercontent.com/assets/22030029/18609953/061cc92c-7d0f-11e6-86b1-a195d0cf4172.jpg)

**Comment by Schnitzelvernichter** [comment]
![loca2](https://cloud.githubusercontent.com/assets/22030029/18609969/434cc2de-7d0f-11e6-870d-fae87c3b46e1.jpg)

**Comment by MTK4355** [comment]
Woah. Weird. What's your monitor resolution?

**Comment by chifayeh** [comment]
I have same problem, my resoluition is 1920X1080

**Comment by harewei** [comment]
I have the same situation.  1920X1080 Windows 7

**Comment by zazabi** [comment]
my resolution is 1920x1080 Windows 8.

I can use the bot by let it start from the last finish run but can not select new location. :)

**Comment by Schnitzelvernichter** [comment]
ahhhhhhaaaaaaa 
![locaok](https://cloud.githubusercontent.com/assets/22030029/18614371/8d5f951c-7d8d-11e6-9c1e-39d1c9eb5244.jpg)

**Comment by zazabi** [comment]
Schnitzelvernichter how did you fix it?  :)

**Comment by Schnitzelvernichter** [comment]
you have to delete the user settings in the Graphic

ich hatte benutzer einstellungen drin ....einfach löschen auf standart

**Comment by zazabi** [comment]
Which graphic? sorry but I couldn't find it.

**Comment by Schnitzelvernichter** [comment]
in the operating system of the pc
