### ISSUE TITLE
Question: Using the bot to scan a spawn point

### ISSUE THREAD

**Issue by YellowTomato** [Ar1i/PokemonGo-Bot#3941]
Basicly I want to know if a specific pokemon is in an area, how often and when. I have heard about a park where Lickitung is supposed to spawn, but never when I was there physically. I want to use the bot to walk the park, or even just to stand at a specific point for 10-20 hours and get some data on that point.

How do I do that? Asking to pause, pauses the bot at a pokestop – too far away. Setting walk speed to 0 km/h make it walk extremely slow – but away from the point. Setting the area size to 50 meters make the bot unhappy as there are no pokestop within.

I am aware that I am trying to use it for something it was not designed for. Maybe you guys know a better tool?

Any suggestions?

Background: I want to fill my main (non-bot) account's pokedex and I am missing some of those  rare ones like Porygon, Lickitung and Snorlax.

**Comment by MTK4355** [comment]
Hrm. Don't think there is any way to configure that behavior right now, and I'm not sure how useful it would be to add as a feature... Put it in the #suggestions channel on Discord and see if you can get some support from the community. If enough people want it I'll take the time to add, but I have other things I'm focused on presently. 

Do you know how to code? Wouldn't be too tough to add your own override to the pause walking feature, but more work to make it a generally available function.

MK

**Comment by Adj1e** [comment]
@YellowTomato Lickitung in Taman Mini Indonesia Indah.

**Comment by YellowTomato** [comment]
My main goal is to fill my real/not-bot account. Going to Indonesia for that is a little excessive.
