### ISSUE TITLE
Max pokemon's capture

### ISSUE THREAD

**Issue by Zodice** [Ar1i/PokemonGo-Bot#3950]
Hi,

i'm now lvl 30, i understood the way to max the gain of experience.
But my aim is now to capture a maximum of pokemons, but i don't really have a trick. I put "great trhows" and "excellent throws" at 50% both, i checked the "use raspberry when" and i put 20%, i will maybe put it to 30%, but after that i don't have any ideas for maxing the capture.

So if anyone can help me, that's very cool.

Thank you for reading.

**Comment by MTK4355** [comment]
Please use discord link in README file for general discussion. Thanks!
