### ISSUE TITLE
Buddy Update

### ISSUE THREAD

**Issue by Croc0008** [Ar1i/PokemonGo-Bot#3954]
Hey!

Wird das Buddy Update jetzt eigentlich irgendwann zum Bot hinzugefügt?
Oder bleibt der Bot immer auf einer älteren Version.
Wollte nur nachfragen, da warscheinlich ziemlich viele, die den Bot benutzen sich aus Versehen schon ma das Buddy Update heruntergeladen haben...

Und würde der Bot nicht theoretisch ohne Ban klappen, wenn man seinen Buddy einfach entfernen würde?
Dann gäbe es ja auch keine Probleme mit den Bonbons sammeln usw.

LG 
~Croc0008

**Comment by Schnitzelvernichter** [comment]
Hi , ne die neue Version auf den Handy sendet einige Daten anders ...wenn du dann den Bot benützt  bekommt der Server falsche Daten ...zack bann ....war bei den Versionen früher auch so . 
Ich hoffe da sitzen schon einige kluge Köpfe dran :-)
