### ISSUE TITLE
Fail to transfer pokemon

### ISSUE THREAD

**Issue by chiu0602** [Ar1i/PokemonGo-Bot#3957]
transfer pokemon routine is not called so that I have to transfer pokemon manually, otherwise "Error catching Pokemon: PokemonInventoryFull" appears, but it is strange that this message appear even when my pokemon bag is not yet full (according to the title bar of the app)

**Comment by terence1016** [comment]
9 Eggs are also counted in your PokemonInventory lol

**Comment by chiu0602** [comment]
thanks terence1016, you are right
