### ISSUE TITLE
Hey all, why i cant see any pokestop, the bot said probably is server problem. Is that true? or my account have been banned? 

### ISSUE THREAD

**Issue by Mingshiaw** [Ar1i/PokemonGo-Bot#3958]

**Comment by Mingshiaw** [comment]
![14407615_1093830453985714_115280227_n](https://cloud.githubusercontent.com/assets/22276993/18617180/52984ad6-7dfc-11e6-95f6-2419d5ffeb3a.png)

**Comment by nasierache** [comment]
maybe perm ban

**Comment by Mingshiaw** [comment]
Does anyone having the same issue ?

**Comment by blackwing182** [comment]
can you login on the app?

**Comment by Zestiria00** [comment]
either you are perma ban,your ip is perma ban or softban. try to log in on the app with mobile data or use proxy

**Comment by Mingshiaw** [comment]
i used the older veraion bot stil can run, that means my account still can
use. i cant use the latest version pokemon go in my phone. but i wonder why
the latest bot suddenly cannot run
