### ISSUE TITLE
Still uses ultra ball although i set it not to use it if it is less than 70 

### ISSUE THREAD

**Issue by s3if** [Ar1i/PokemonGo-Bot#3963]
My ultraball was still 15 and still the bot keeps using it and wasted 7 ultra balls on a freakin dodrio 😂 Even if set it to zero or even set it not use it if it is less than 70, am i the only one having that problem?

**Comment by suljo94** [comment]
You set that it has to recycle when he had more than xx ultraballs you can't actually set to not use it when under xx so it you don't change that 0 back to 70 he will trow them all away
