### ISSUE TITLE
Bot Errors

### ISSUE THREAD

**Issue by LoffeNcs** [Ar1i/PokemonGo-Bot#397]
I have been running the bot 24/7 since you released it on mpgh. I have just found some errors taht apear and are sometimes irritating to deal with. 

#1 Bot Crashes and starts again and gives me this message 
https://gyazo.com/a9969f8b481b6847c074b595314f79a7

#2 Bot Crashes and tells me that the next pokestop is Xxxxxxxxxxxxxxxx.x meters away it will take 10000000.0 seconds to get there.

Those two errors disapear awhile when i update the but but they come back and i have to make a fresh map again. Thanks.

**Comment by jackrose01** [comment]
change the location bro...
the default location has no pokestop ( may be ).

work after i change the location :D

**Comment by iOwner** [comment]
Delete all folders and download the latest update.

**Comment by LoffeNcs** [comment]
@jackrose01 I did that. I also get a "Error at reqeust PostProtoPayLoad" error

**Comment by Ceiridge** [comment]
@LoffeNcs I had the same bug and all you have to do is setting your location ~1.8 km away.
As example:
I had the default starter position set and after I read this I tried setting the starter position to the north(er)  Central Park.

**Comment by LoffeNcs** [comment]
Why close it?

**Comment by Ar1i** [comment]
Cause the problem already posted often here. Change location.
