### ISSUE TITLE
Farm Items.

### ISSUE THREAD

**Issue by marci2oo9** [Ar1i/PokemonGo-Bot#3971]
Hey habe das Problem das ich eingestellt habe wie viele Items er behalten soll und naja das Problem ist das er iwie nicht die anzahl der Items beibehält oder sammelt ... er sammelt iwie wie er gerade möchte kann mir dabei Helfen ?
Ich habe alles hier durchsucht ob wer diesen Fehler auch schon hat jedoch nichts gefunden :/ hoffe das ich Deutsch schreibe ist okey.

I have problems  with the recycled and the items ... i set the Pokeball to 15 and the Greatball to 65 but i have now 45 Pokeballs and 10 Greatballs :/

**Comment by pwnjke** [comment]
bei mir ist auch so. am Anfang ist alles in Ordnung, aber nach 4-5 Stunden schaltet plötzlich der Bot die "Catch Pokemon" Funktion aus, obwohl er noch viele Pokebälle hat, und fängt an jeden Scheiss zu sammeln und recycelt nicht mehr. Ich denke er schaltet irgendwann die Catch-Funktion wieder, weil ich ihn einmal morgen früh mit 0 Pokebälle gefunden. Aber 350 Potions und Revives, die bei mir auf "0" eingestellt sind, hat er doch gelassen

**Comment by Persada7** [comment]
i got nothing when farming items at pokestop

**Comment by gothsk8er** [comment]
i have the same problem. i do not get any items when farming pokestops, only xp.. pls help !

**Comment by marci2oo9** [comment]
i am update the newest version and it will not work :/
when i look on my items great ball and super ball : 0 ....
