### ISSUE TITLE
Bot always crashes at evolving pokemons

### ISSUE THREAD

**Issue by Buddhasama** [Ar1i/PokemonGo-Bot#3972]
It keeps crashing whenever it stops to evolve pokemons. I tried restarting, changing settings , it keeps doing it. 

![evolving](https://cloud.githubusercontent.com/assets/20898364/18642074/f2bd2a80-7ea7-11e6-8f89-b701eb3f0056.PNG)

**Comment by Buddhasama** [comment]
I also tried completely removing the old config folder and it still does that.

**Comment by jackcrowz** [comment]
Same here

**Comment by BOYSA** [comment]
[19:47:58] Found 1 catchable Pokemon(s): Caterpie
[19:47:58] Exception: System.NullReferenceException: La rÃ©fÃ©rence d'objet n'est pas dÃ©finie Ã  une instance d'un objet.
   Ã  PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__51.MoveNext() dans C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 1221
--- Fin de la trace de la pile Ã  partir de l'emplacement prÃ©cÃ©dent au niveau duquel l'exception a Ã©tÃ© levÃ©e ---
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Ã  PokemonGo.RocketAPI.Logic.Logic.<fncPokeStop>d__41.MoveNext() dans C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 821
--- Fin de la trace de la pile Ã  partir de l'emplacement prÃ©cÃ©dent au niveau duquel l'exception a Ã©tÃ© levÃ©e ---
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Ã  PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext() dans C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 640
--- Fin de la trace de la pile Ã  partir de l'emplacement prÃ©cÃ©dent au niveau duquel l'exception a Ã©tÃ© levÃ©e ---
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Ã  PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__32.MoveNext() dans C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 222
[19:47:58] Starting again in 60 seconds...

**Comment by Lumumba76** [comment]
Just delete complete Bot Folder and set up new with actual Version.
Had the same.

**Comment by MTK4355** [comment]
Fixed!
