### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by Spoonyi** [Ar1i/PokemonGo-Bot#3975]
Is there a way to create a google map route and then import it so the bot will follow that route?

**Comment by Spoonyi** [comment]
![map](https://cloud.githubusercontent.com/assets/22220916/18648717/c4bc7990-7eb3-11e6-9704-ddd6391d74fd.png)

I have created this map as an example, is there any way to make the bot follow this path? as opposed to wandering round looking for pokestops?

**Comment by MTK4355** [comment]
I was working on that, but got bored. I'll get back on it soon. 

Do you know any c# I can tell you where to set it in the code....
