### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by lepriape** [Ar1i/PokemonGo-Bot#3976]
Good evening, unable to connect, I try all my different accounts.
![capture](https://cloud.githubusercontent.com/assets/22306773/18650031/29afcaaa-7ec3-11e6-8847-7ede920c2eff.JPG)

**Comment by MTK4355** [comment]
Do you have encryption enabled on your password?

**Comment by lepriape** [comment]
I'm not banned. I can play with my phone

**Comment by lepriape** [comment]
Yes it is enabled

**Comment by lepriape** [comment]
thanks MTK4355
