### ISSUE TITLE
Eggs Tab Reload button missing

### ISSUE THREAD

**Issue by thejundguy** [Ar1i/PokemonGo-Bot#3977]
![image](https://cloud.githubusercontent.com/assets/21860778/18654365/1b6e3fe4-7f13-11e6-911e-f4b722ab851e.png)

Hi, I wonder if I have a wrong setting, I think there's a Reload button for yesterday's build.

**Comment by spinning149** [comment]
Same with item tab..no reload button. Thank you in advance.

**Comment by erickrisnarinjaya** [comment]
@MTK4355 @Logxn @Ar1i Thanks.

**Comment by thejundguy** [comment]
this is solved. many thanks!
