### ISSUE TITLE
request older version

### ISSUE THREAD

**Issue by vinsiong** [Ar1i/PokemonGo-Bot#3983]
hello! ive been out for 2 weeks because i am working and i just updated the bot but it say 0.3.7 is too risky ..and it says the version 0.3.5 is better can i request the version 0.3.5 sir?

**Comment by Lumumba76** [comment]
Please read...
If you opened your account with Pokemon Go android version 0.3.7 (or updated version for iphone. dont know which it is) you should NOT use the bot anymore.
If you never opened with actual iphone or android version everything should be fine.

**Comment by mcferson** [comment]
So may be it's time to adapt the bot for the 0.3.7

**Comment by alexandrer0x** [comment]
"So may be it's time to adapt the bot for the 0.3.7"

Simple like that! It's just change one variable...
¬¬

**Comment by alexandrer0x** [comment]
@mcferson 
"So may be it's time to adapt the bot for the 0.3.7"

Simple like that! It's just change one variable...
¬¬

**Comment by MTK4355** [comment]
What.... The API calls being made by the 0.37 version are encrypted. We don't yet know what Niantic is sending to their servers in the latest app. It is not "time to adapt the bot" because we have no idea what needs to be adapted. 

Trust me, when we know what needs to change we will update it.

**Comment by MTK4355** [comment]
Just change one variable. lol. Which variable is that exactly? :)

**Comment by alexandrer0x** [comment]
That was sarcasm... because of mcferson's comment
