### ISSUE TITLE
Min CP GreatBall or UltraBall + Refresh

### ISSUE THREAD

**Issue by SkolgeaR** [Ar1i/PokemonGo-Bot#3985]
Hi. In latest version
Min CP use in GreatBall and UltraBalls config, not rules in bot.
And Refresh button in Eggs and Item, dissapear.

Thx for your work !

**Comment by SkolgeaR** [comment]
Missed Throws MAX, neither work.

:-)

**Comment by thejundguy** [comment]
![capture001](https://cloud.githubusercontent.com/assets/21860778/18697609/6c300a7e-7ff5-11e6-8ca3-4235f803f26e.JPG)
![capture002](https://cloud.githubusercontent.com/assets/21860778/18697610/70e4fdc2-7ff5-11e6-8591-cd393723700c.JPG)

same here. min cp and min stock both not working

**Comment by MTK4355** [comment]
Fixed!
