### ISSUE TITLE
Can anyone tell me what it this?

### ISSUE THREAD

**Issue by Persada7** [Ar1i/PokemonGo-Bot#3986]
![untitled](https://cloud.githubusercontent.com/assets/20898517/18667740/0d31a314-7f5c-11e6-9d14-873c9da01212.png)

I don't why this error or somethin can happened to me, when i try to used newest version but, TADA..!!!

**Comment by jmo93** [comment]
use 1.1.6.1 version

**Comment by Persada7** [comment]
i found the solution, the limit cannot be 0 (zero), and must be have some nominal like 100 or 1000

**Comment by Adj1e** [comment]
I agree with @jmo93 1.1.6.1 the best version. I use 100% exellent throw. but in new bot 100% exellent not  allow.
