### ISSUE TITLE
Idea: Route via TXT file

### ISSUE THREAD

**Issue by Schnitzelvernichter** [Ar1i/PokemonGo-Bot#3989]
The user creates even a TXT file ... about as :
![route1](https://cloud.githubusercontent.com/assets/22030029/18672413/60f29012-7f48-11e6-9e06-318d9aa11f55.jpg)

The bot is simply 1 - xx , and then starts again at 1

If the bot detects a Pokestop he farmt

would still be easy to implement it?

**Comment by MTK4355** [comment]
Maybe. Let me finish with bug fixes from my last round of changes and I'll make something like that work
