### ISSUE TITLE
Catching Pokemon Disabled in Client Settings - Skipping all Pokemon

### ISSUE THREAD

**Issue by blasterzhs** [Ar1i/PokemonGo-Bot#3990]
Can't understand why this issue is on, since i already checked the catch option in the settings, and it is marked yet!!! Help!!
![screenshot_60](https://cloud.githubusercontent.com/assets/22324326/18675234/08d17880-7f52-11e6-9230-6211f3aa5ffc.png)

**Comment by spinning149** [comment]
Check if you didn't check the Catch Pokemon box.

**Comment by blasterzhs** [comment]
as i said in the title, the catch pokemon box is already marked. So i dont know what to do in order to fix this issue :/

**Comment by blasterzhs** [comment]
![screenshot_61](https://cloud.githubusercontent.com/assets/22324326/18675794/cebe4446-7f53-11e6-990d-c33f552f1624.png)

**Comment by Buddhasama** [comment]
It happened to me as well, what i did was unmark the "Catch Pokemon" box and then mark it again and it started catching again. But this is an issue that needs to be resolved. It happens after you are left without any pokeballs.

**Comment by blasterzhs** [comment]
yeah, it started to me as well once the pokeballs were finished, thanks for the feedback guys

**Comment by MTK4355** [comment]
Noted. Will be fixed in next build.

**Comment by blasterzhs** [comment]
thanks a lot
