### ISSUE TITLE
Doesn't spin pokestops when stop catch pokemon

### ISSUE THREAD

**Issue by kyros123** [Ar1i/PokemonGo-Bot#3993]
when all pokeball out of stock, bot will auto stop catch pokemons, 
Then the bot did farm pokestop, but didn't spin pokestop, so don't get any pokeball to restore the pokeball, please to check it, thanks.

**Comment by StavrosHacker** [comment]
maybe you are softbanned ?

**Comment by dreamboatcap** [comment]
no it goes like this when all pokeball is out of stock, bot will auto stop to catch pokemons but never recycle items. so your inv is full of with useless crap. when you try to farm any pokestop with full inv, you will get nothing from those pokestops. so you have to manually restart the bot.
