### ISSUE TITLE
Not an issue: Thank you!

### ISSUE THREAD

**Issue by YellowTomato** [Ar1i/PokemonGo-Bot#3998]
I just want to tell you guys you are doing an excellent job. The new interface is a wonder. In many ways it is so much better than the app.  Just look at the IV! I have just gone trough the painful process of sorting out Magikarps on my real (non-bot)  account. Half an hours annoying work. Wast of time. With the bot it is just looking at be numbers and done – less than a minute.

One look overview of candy and sort on evolvable or not. Great! So much better than the app.

And it just got better! Number of upgrades and battles lost and won. I don't know what to use it for but definitely nice to have.

Thank you!

BTW the template says “DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!”  Ok? Where do you want question/suggestion then?

**Comment by MTK4355** [comment]
There is a link to the Discord community on README file. Please direct everything except issues to that forum. 

Thanks!
