### ISSUE TITLE
please help, how customize route between pokestop

### ISSUE THREAD

**Issue by Guazzett** [Ar1i/PokemonGo-Bot#3999]
Hi all, 
please can you help my, How i can customize route between pokestop, 
bot walking beeline across the river and buildings. Its possible make custom route for walking on road?

Thx

**Comment by YellowTomato** [comment]
Try the ”Use google Maps Routing” and it will wake on road/bridges (and even go by boat now and then).

I very much doubt that beeline routing is a ban-problem. Did you ever see the route created in real life by smart phones and tablets with bad GPSs? They jump around a lot, trough buildings and such and it is hard to see the difference and even harder to write a ban algorithm that uses that difference.

Personally I let the bot walk in beeline (but at max 10 km/h).
