### ISSUE TITLE
german names everywhere

### ISSUE THREAD

**Issue by ballbo8** [Ar1i/PokemonGo-Bot#40]
is it possible that everytime, the name of a pokemon is written, the german name is written, and not just when it is caught

**Comment by crss** [comment]
yes, 

edit logic.cs in PokemonGo.RocketAPI.Logic

search for  "{pokemon.PokemonId}" add  ({StringUtils.getPokemonNameGer(pokemon.PokemonId)})

search for {duplicatePokemon.PokemonId} add ({StringUtils.getPokemonNameGer(duplicatePokemon.PokemonId)})

**Comment by sandmann42** [comment]
implemented a kind of "multilanguage". It will maybe be live in the new version.
