### ISSUE TITLE
Request - Keep pokemons to evolve not working properly

### ISSUE THREAD

**Issue by HaydarOzturk** [Ar1i/PokemonGo-Bot#400]
Correct me if I am wrong but I want to give you an example about this. Imagine I have 150 charmender candy. I want to hold 3 charmender but program holds more then 3 and doesn't transfer them. Mybe program works partly I don't know but I encounter too much of this stiuation. If you could make this work, I suppose it would be great.

**Comment by TMaddox** [comment]
same here
