### ISSUE TITLE
Log events

### ISSUE THREAD

**Issue by mcferson** [Ar1i/PokemonGo-Bot#4000]
Hi there.
Logging events seem to crash the application because of value format passed to the Tick parameter.
This occurs only while encouter a pokemon to catch.

**Comment by mcferson** [comment]
Correction : i deactivated all logs and problem occurs. here a screen
![image](https://cloud.githubusercontent.com/assets/22058610/18706768/96351604-7ff3-11e6-9f02-7f5c68930fac.png)

**Comment by SkolgeaR** [comment]
Same here

**Comment by MTK4355** [comment]
Trapped this exception to prevent logic failure
