### ISSUE TITLE
Bot doesnt farm any Items

### ISSUE THREAD

**Issue by AlpaEZPZ** [Ar1i/PokemonGo-Bot#4002]
Hey guys :)

i got a question, since last week i have a problem with the bot.
My bot doesnt loot any items at pokestops, seems like he is getting exp but ye no items means no pokeballs means noch catchable pokemon :D

i give u a screen in the attached files. maybe one of u can tell me what happened, and just for information i switched the location from USA to germany but waited at least 8hours.

![21-09-2016 13-49-14](https://cloud.githubusercontent.com/assets/20835995/18709890/a6bdc778-8002-11e6-9627-b1c8755b073d.jpg)

**Comment by AlpaEZPZ** [comment]
got it XD see it on my own screenshot, items are 350/350

**Comment by drjack6** [comment]
I just had the same thing happen. Never had to do it before but I needed to manually recycle my iutems. Weird

**Comment by Schnitzelvernichter** [comment]
please close , thx
