### ISSUE TITLE
profiles repeats for catchPokemonSkipList,pokemonsToHold,pokemonsToEvolve

### ISSUE THREAD

**Issue by chifayeh** [Ar1i/PokemonGo-Bot#4003]
I found the profiles will repeat add the above values when save the profiles, 
so it is impossible to delete the old IDs.

I think you should clear the "Globals.doEvolve",,"Globals.noCatch","Globals.noTransfer" before you use ADD to save them.

**Comment by MTK4355** [comment]
Fixed!
