### ISSUE TITLE
Ball choice funktioniert nicht

### ISSUE THREAD

**Issue by pwnjke** [Ar1i/PokemonGo-Bot#4005]
![3](https://cloud.githubusercontent.com/assets/20947780/18713309/21609d5c-8012-11e6-959e-76004d7ee3d1.png)
![1](https://cloud.githubusercontent.com/assets/20947780/18713403/80bbab7a-8012-11e6-9597-6fd25beb7f75.png)

Great balls und Ultra balls werden auch nicht bis 75 gesammelt

**Comment by Schnitzelvernichter** [comment]
Ist bei mir auch so , seit 2 Wochen , egal welche Version .
Wenn du die Standart Monster zum Fangen sperrst werden die Bälle mehr , fängst halt weniger .

**Comment by MTK4355** [comment]
Fixed

**Comment by pwnjke** [comment]
sorry, Jungs. das bin ich wieder
![untitled](https://cloud.githubusercontent.com/assets/20947780/18811429/2810eacc-82af-11e6-8033-54599ac15c73.png)

**Comment by Ar1i** [comment]
Mach ein neues issue auf das hier ist schon zuweit nach hinten gerutscht.
