### ISSUE TITLE
Nbug what is this?

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#4006]
![image](https://cloud.githubusercontent.com/assets/22138908/18715016/05ef0bb4-805b-11e6-8562-8db7bb68f524.png) I was trying to evolve 3 weedle then alot of msgs came out saying sending something to the developers then after i tried to bot again this came then after 10 tries finally it let me use bot again

**Comment by MTK4355** [comment]
Bug reporting platform. Not fully implemented yet, but not likely the issue causing the crashing\.
