### ISSUE TITLE
newest version problem ?

### ISSUE THREAD

**Issue by Gooozzz** [Ar1i/PokemonGo-Bot#4010]
hi anybody having the same issue ?

![capture](https://cloud.githubusercontent.com/assets/22350615/18719226/7c6417ce-7ff4-11e6-81be-273a1ed64e2e.PNG)

![2](https://cloud.githubusercontent.com/assets/22350615/18719233/84b9e822-7ff4-11e6-9846-f3b02fdbb9c8.PNG)

**Comment by MTK4355** [comment]
Uncheck Encrypt password and re-enter it
