### ISSUE TITLE
[BUG] GUI seems a bit laggy sometimes

### ISSUE THREAD

**Issue by cyb0rg01** [Ar1i/PokemonGo-Bot#4012]
Hey folks,

since the latest two updates, the GUI seems to be a bit laggy. Sometimes it needs some time to switch between tabs and sometimes it needs also a bit to move in the same window.

I can reproduce this behavior: Version 1.1.6.8 is laggy in GUI and 1.1.6.5 is not.

My system has enough power (real workstation with Xeon 8 Core CPU and 64GB of RAM).

For this kind of issue, I can't provide any screenshots.

**Comment by FenrirXx34** [comment]
i don't have lag ^^

**Comment by drjack6** [comment]
Same exact issue here. Last two updates laggy pokemon list

**Comment by cyb0rg01** [comment]
@FenrirXx34 Play a bit around with the GUI and you will see. I switched to a different machine (actually a virtual one running on my ESXi Farm) and I got the same issue.

**Comment by vincent0817** [comment]
Same exact issue here. Last two updates laggy pokemon list

**Comment by Xelwon** [comment]
that problem is used to there is more tabs, each new tab need do a call to pokemon server to extract information so is like do in the game a pass for all options.
Now pokemon list windows is slower but more versatile.

**Comment by drjack6** [comment]
If thats the case, ithink they should at least kill player info tab since thats already listed in cmd

**Comment by cyb0rg01** [comment]
@Xelwon Thanks for your reply buddy. If thats the case, then there is no further actions needed anymore.

#close
