### ISSUE TITLE
Adding Easter-Egg nickname for Eevee

### ISSUE THREAD

**Issue by AireAyquaza** [Ar1i/PokemonGo-Bot#4013]
I need to control the evolution of my Eevees, can you add the possibility to rename Eevee with the different names : Sparky, Rainer and Pyro ?

**Comment by cicklow** [comment]
select Eevee->right button->IVs to nickname->Pyro, etc...
![sin titulo](https://cloud.githubusercontent.com/assets/933689/18732433/8ce24982-8039-11e6-9ffa-6fd660c1ea3d.png)
