### ISSUE TITLE
EncounterNotFound

### ISSUE THREAD

**Issue by Benjamous** [Ar1i/PokemonGo-Bot#4014]
Hey, each time that the bot go near a boosted Pokestop it normaly found a pokemon but there is a bug ... 
:D ty for the very good bot !
![pokebug](https://cloud.githubusercontent.com/assets/22354808/18727065/5adfc8c0-8047-11e6-8db5-ff323b6daa64.PNG)

**Comment by spinning149** [comment]
same here..
