### ISSUE TITLE
Region Locked Pockemon (1.1.6.9)

### ISSUE THREAD

**Issue by amsagain** [Ar1i/PokemonGo-Bot#4015]
Catching MrMime in Paris was possible in previous version, but now it isn't, even though I am farming in Paris with correct setting (not sniping, region locked off)
![image](https://cloud.githubusercontent.com/assets/22350890/18727200/6fb2c7fc-7ffc-11e6-8120-5a5faff34e2f.png)
![image](https://cloud.githubusercontent.com/assets/22350890/18727355/10338d7e-7ffd-11e6-9a5f-71fa2e50376f.png)

**Comment by MTK4355** [comment]
Setting must not be updating right on launch. Defaults to checked and looks like it's still being treated as "checked". Thanks for the feedback!

**Comment by MTK4355** [comment]
Found it. Will be fixed in next build. Please confirm and close bug when you can.
