### ISSUE TITLE
Memory leak in newest build?

### ISSUE THREAD

**Issue by suljo94** [Ar1i/PokemonGo-Bot#4019]
after you input touch(a few times short after each other)the gui(pokemon list) becomes unresponsive for a second

**Comment by JerungC** [comment]
experience that also little bit laggy on new release

**Comment by MTK4355** [comment]
I think it's the embedded map. Something about loading the pokemon. Doesn't look like a memory leak, but definitely a long running process. I'm looking at it. :)
