### ISSUE TITLE
[BUG] Pokestops not coming up at startup, but ok on retry (NOT A SOFTBAN) (1.1.7.1)

### ISSUE THREAD

**Issue by amsagain** [Ar1i/PokemonGo-Bot#4020]
Every time I start a program from scratch, I get this:
![image](https://cloud.githubusercontent.com/assets/22350890/18732267/c42e774e-8016-11e6-82e0-be74a0ac71ca.png)

It's definitely not a softban, after 60 seconds it gets me the list; also if I use Catchem bot, the stops show up straight away, no problem.

**Comment by MTK4355** [comment]
This only happens after sniping right?

Still working out kinks there.

**Comment by amsagain** [comment]
No, I had sniping unchecked the whole time.

**Comment by amsagain** [comment]
Seems to work ok in 1.1.7.2
