### ISSUE TITLE
Sniper works on startup but never re-looks for pokemon

### ISSUE THREAD

**Issue by drjack6** [Ar1i/PokemonGo-Bot#4022]
Problem is in the title.
Is that a bug or just me?
When I restart bot, sniper immediately finds lots of new poekmon but not while bot is still running.

**Comment by MTK4355** [comment]
Yeah, it doesn't repeat yet. @clicklow's implementation looks like it wasn't really intended to run WHILE the bot was running. It looked to be more of a "either or" implementation to me. Trying to work out a suitable interval.
