### ISSUE TITLE
[BUG] Set New Location does not seem to work

### ISSUE THREAD

**Issue by amsagain** [Ar1i/PokemonGo-Bot#4024]
Version 1.1.7.1.

Here's the config I am having issue with:

![image](https://cloud.githubusercontent.com/assets/22350890/18738162/0374e30c-804e-11e6-9fd0-e876caa256dd.png)

I set it, hit "Set New Location", and get back:
Default Location Set will navigate after next pokestop

I wait for the little dude to get to poke stop, and the action does not happen, it just lists next pokestop and moves to it (on the bottom):

![image](https://cloud.githubusercontent.com/assets/22350890/18738202/6009d51e-804e-11e6-94df-0a5cb4238af5.png)

What my expectation was, that after getting to pokestop, the dude will move to requested location at specified speed, and upon arriving there will pull a list of pokestops at that new destination, like it does at the start, and start farming those. Or does it work differently?

**Comment by MTK4355** [comment]
It works differently at the moment! 

That is, it does not work at all the way it should! Thanks for the feedback. Fix will be in the next update.
