### ISSUE TITLE
Json parse error when snipping is enabled

### ISSUE THREAD

**Issue by Fatal-Errol** [Ar1i/PokemonGo-Bot#4026]
![image](https://cloud.githubusercontent.com/assets/6903866/18739592/46a9279e-80d7-11e6-80bf-79bb460170b8.png)

Error appears on start and makes the app unusable. This only occurs when the snipping option is enabled. It was working this morning, using the latest version. No new updates so I think the bot was receiving an invalid json file for the pokemon coordinates to use in snipping.

**Comment by Fatal-Errol** [comment]
I don't understand why this was closed? I have the latest version and the error is still appearing. No particular commit that references a fix. Thanks

**Comment by llxkkxll** [comment]
How I use sniper function?

Em 23 de set de 2016 00:04, "Errol A. Zuñiga Jr." <notifications@github.com>
escreveu:
