### ISSUE TITLE
manual arena function?

### ISSUE THREAD

**Issue by MrJur1** [Ar1i/PokemonGo-Bot#4027]
Is there a chance to implement a manual arena function? Not automated sothat there will no advantage over other/normal players! Due to we cannot use the app atm and i would to like to use this function and i think a lot of other players too!
Thanks! :)

**Comment by MTK4355** [comment]
Way too much work, and I remember Ar1i stating at some point that there would never be gym battles in the bot, so I'm going with that... Mostly because I have too much other stuff I want to do to make the bot better at going undetected. 

:)
