### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by negiboss** [Ar1i/PokemonGo-Bot#4028]
after changing nickname i am not sure if nickname was really changed or not can show the changed nickname instead of real name or just add a new tab for changed nickname.??

**Comment by thejundguy** [comment]
has been trying with the nickname feature but it doesn't seem working.
but this is not a big deal :)

**Comment by Xelwon** [comment]
The nickname is shown in the tooltip of the list. 
You only need keep the mouse over the icon of the pokemon a moment.
