### ISSUE TITLE
Missing the reload button in newest build

### ISSUE THREAD

**Issue by john-hardesky** [Ar1i/PokemonGo-Bot#4031]
Newest build (1.1.7.3) is missing the reload button for items and eggs again. 
Also the reload button for Pokemon should be inside the menu underneath the list and not floating above the scroll bar.

**Comment by MTK4355** [comment]
How do you know it isn't supposed to be floating? ;) Maybe disembodied user controls are a thing these days? Sorry for the recurring bug with the reload button. Blame it on Microsoft and Win Forms.

**Comment by john-hardesky** [comment]
Hahaha :D 

I get it, that's why I use Gtk or Electron for my stuff.

**Comment by jdunnet** [comment]
This is fixed now I think. 1.1.7.4

**Comment by jdunnet** [comment]
Defo fixed in 1.1.7.6
