### ISSUE TITLE
Profile not loading

### ISSUE THREAD

**Issue by TxShack** [Ar1i/PokemonGo-Bot#4033]
When opening new bot since 1.1.6.3, my profile fails to load as a message appears telling me it couldn't load it. Newest build does the same.

P.S.: Using a new separated folder does the same.

**Comment by llxkkxll** [comment]
How can I use sniper function?

Em 23 de set de 2016 00:03, "TxShack" <notifications@github.com> escreveu:

**Comment by TxShack** [comment]
@llxkkxll Please erase your comment/question out of my post and go ahead and open yours. Thanks and read rules.
