### ISSUE TITLE
Sniping Problem

### ISSUE THREAD

**Issue by jake109913** [Ar1i/PokemonGo-Bot#4037]
The Pokemon was in Sniping list but its write the pokemon not in the list.Please check it.Thanks 
![exeu f v unker mn 2b](https://cloud.githubusercontent.com/assets/22091986/18782889/4f34c32a-81bb-11e6-8f22-e0ab568cb7b0.png)
![c r7vaskor gakodzt0b6cv](https://cloud.githubusercontent.com/assets/22091986/18782893/53e5b582-81bb-11e6-9845-71889fbf5f05.png)

**Comment by jake109913** [comment]
Pokemon sniping list have problem.It will automatically generate more pokemon list in the sniping list.

**Comment by suljo94** [comment]
@MTK4355 it actually doesn't snipe anything 
trying to snipe xx
Then it skips and tries to snipe something else which it skips again see above image
