### ISSUE TITLE
Size of location map window 

### ISSUE THREAD

**Issue by depeco** [Ar1i/PokemonGo-Bot#4040]
I have the problem of inputing longitude and latitude in the LOCATION Window below the map, just like the following picture. This problem was discovered when GET POINT function.

I already read The #3939 but don't understand how to resolve this problem can you help me please

**Comment by terence1016** [comment]
If your computer resolution is 1920x1080, u might get this problem XDXD
Try to change the resolution of your windows setting....

**Comment by depeco** [comment]
I change The résolution already but don't resolve The problem

**Comment by Xelwon** [comment]
may be used to font dpi, try to change it to 92

**Comment by depeco** [comment]
Resolve thx for your help !
