### ISSUE TITLE
loading config failed

### ISSUE THREAD

**Issue by stes60623** [Ar1i/PokemonGo-Bot#4042]
Everytime I restarted the bot (the latest version), my setting was gone. It can't save my setting all the time. Please helping me to solve the problem, thank u so much. 
![poke](https://cloud.githubusercontent.com/assets/22401711/18797110/edd4b506-81fe-11e6-9885-bbfc0ca0900c.png)
![poke2](https://cloud.githubusercontent.com/assets/22401711/18797477/affa8c36-8200-11e6-9cba-5a6ef1dfadef.png)

**Comment by king2010116** [comment]
LOOK FOR ACCOUNT TYPE

**Comment by stes60623** [comment]
I used google account, and I chose google too.
Today, using the 1.1.7.6 version still has same problem.

**Comment by pahadiboy** [comment]
If you are giving a profile name then go to account profile and select your profile. Then make sure to click on default profile and then save. Hope it works for you
