### ISSUE TITLE
Did anyone fix Error: GPSOAuthSharp?

### ISSUE THREAD

**Issue by Karimoto** [Ar1i/PokemonGo-Bot#405]
From yesterday i was trying to fix this error(GPSOAuthSharp) by making my account less safer. For example I turned off 2-steps verification, made app password, turn on mode for less safer application and add new access from strange location/new device. Still bot doesnt work. Email and password are fine. What else can I try? 
If I type wrong password it's like when i type right password. Sorry for launguage.

**Comment by Ar1i** [comment]
Screenshot of error?

**Comment by Karimoto** [comment]
![image](https://cloud.githubusercontent.com/assets/11833738/17271216/5a4f7248-5676-11e6-8358-89506882ea34.png)

**Comment by Karimoto** [comment]
trainer club is running 4sure

**Comment by glabella** [comment]
i have this error too with PTC account

**Comment by Logxn** [comment]
Isnt this a 2FA error?

**Comment by Karimoto** [comment]
I turned it off still doesnt work, (tried also to app password).

**Comment by glabella** [comment]
mine looks like this
![error](https://cloud.githubusercontent.com/assets/19846525/17271260/880c701a-567f-11e6-89bf-a79e2d2db4ba.png)

**Comment by Karimoto** [comment]
The older version of this app (then i need to type code to http://google.com/devices) works fine. (now isnt working)

**Comment by glabella** [comment]
Fak sorry im dumb...my account is a google account and i tried to log in with PTC ...sry again facepalm

**Comment by Ar1i** [comment]
OMQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ you did it today hahaha

**Comment by Karimoto** [comment]
?

**Comment by Ar1i** [comment]
Wups read wrong lol

**Comment by Ar1i** [comment]
But i dont know a fix atm and the /devices is not longer working cause of PokemonGo
