### ISSUE TITLE
Manual Sniping not working in 1.1.7.4

### ISSUE THREAD

**Issue by WsTs** [Ar1i/PokemonGo-Bot#4053]
Hi Developers,

Thank you for the bot but i want to report a problem.

I was trying the Manual Sniping feature but it is not working. But when i try with another sniper tool it is work. 

I am not soft-banned because i can capture pokemon in the map, just the manual snipping feature not works after few successful snipe.

**Comment by suljo94** [comment]
#4047

**Comment by suljo94** [comment]
#4047

**Comment by MTK4355** [comment]
Known issue. Working on a fix. Sit tight!

**Comment by WsTs** [comment]
@MTK4355 Thanks, you all are the best !!!!
