### ISSUE TITLE
manual sniping does not work

### ISSUE THREAD

**Issue by lepriape** [Ar1i/PokemonGo-Bot#4055]
Hello, the manual sniping does not work. "Snipe me" is grayed out. Maybe I use wrong coordinates. is can we have an example? Thanks all

![capture3](https://cloud.githubusercontent.com/assets/22306773/18806799/75f6f196-8237-11e6-98b2-faf128d585f7.JPG)

**Comment by MTK4355** [comment]
On Change of the Latitude and Longitude field the code attempts to parse the location string into numerical format. If this is successful the Snipe Me button will be enabled. Are you never able to click the Snipe Me button

**Comment by lepriape** [comment]
Hello, thank you for the answer,  I change the coordinates. but I still can not use the  Snipe Me button.

**Comment by YoBii** [comment]
Yes, I have the same problem. Again a EU/GER thing with decimals?

**Comment by DiieH** [comment]
anyone knows whats that?
weiss jemand wieso der bot bei mir sowas anzeigt?
![image](https://cloud.githubusercontent.com/assets/22412419/18808018/b6d87a76-8256-11e6-83f5-04a76a156346.png)

**Comment by YoBii** [comment]
Seems like the decimals are lost in those steps:
var lat = double.Parse(array[0].Trim());
var lng = double.Parse(array[1].Trim());

[13:49:52] ---DEBUG START---
[13:49:52] Input String: 30.123456, -97.123456
[13:49:52] Latitude: 30123456
[13:49:52] Longitude: -97123456
[13:49:52] ---DEBUG END---

**Comment by titilim** [comment]
Same problem for me i've tryed tones of latitude longitude nothing works
