### ISSUE TITLE
Snping not work

### ISSUE THREAD

**Issue by king2010116** [Ar1i/PokemonGo-Bot#4056]
I try many time to snping

But Auto Snipe and Manual Snipe not work

just show me like this PIC

https://drive.google.com/file/d/0BwOi9AWyO0FxTU9TbDZtVG1lR2M/view

https://drive.google.com/file/d/0BwOi9AWyO0FxTXBzSXZyd3pqaUE/view

https://drive.google.com/file/d/0BwOi9AWyO0Fxa2VSa3BremRrdGs/view

**Comment by Spoonyi** [comment]
That isnt the sniping failing, it just means the pokemon isnt there anymore as it disappeared/despawned, if you try again it will work with the auto sniping function
![pokecapture](https://cloud.githubusercontent.com/assets/22220916/18808371/29f92220-8258-11e6-81f0-5dfc71b555ea.png)

**Comment by JakeKate** [comment]
same here, none snip pokemon are caught
