### ISSUE TITLE
Fatal errors with the new verson !!!!

### ISSUE THREAD

**Issue by DiieH** [Ar1i/PokemonGo-Bot#4059]
Hello,

when i start the bot then i get errors.

i have downloaded and extracted and then by builds i hve start the bot and configured.
i get always errors.

![image](https://cloud.githubusercontent.com/assets/22412419/18807914/2316ac92-8254-11e6-9980-6d97f1e9ed38.png)

**Comment by Spoonyi** [comment]
Check to see if you're softbanned and make sure the login details are correct

**Comment by DiieH** [comment]
Hey thx for answer.

im not softbanned and im sure the login details are correct.

**Comment by Spoonyi** [comment]
Try deleting all of the files for the bot and redownloading the client

**Comment by DiieH** [comment]
ok w8

**Comment by DiieH** [comment]
lol now working *-*
puh :D so easy xD
but i have downloaded 30x and i had ever that problem ^^

ok now working thx i love you :*

**Comment by DiieH** [comment]
but now im softbanned idk why -.-

**Comment by Shai-hulud357** [comment]
I got the same message but it appears it is not blocking. The bot is operationnal after restart, to me
