### ISSUE TITLE
Transfer and some evolving options, no pokestops.

### ISSUE THREAD

**Issue by Kendama165** [Ar1i/PokemonGo-Bot#406]
The tool doesn't always transfer Pokemons and doesn't find PokeStops doesn't matter where I put it and if I put it in 5000000 radius.

And in addition to me first ticket, can you link me or explain me before closing it ? cuz I found no forum and no fix.

**Comment by Ar1i** [comment]
Edit your location. Central Park is down/lagging

**Comment by Kendama165** [comment]
I'm telling you doesn't matter where, the same location works on another bot but not this one, and I like this one.
