### ISSUE TITLE
Incense not working? and About pokemon sniping :)

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#4062]
Hi!!

Does anyone experiencing this issue? I already checked the "Use Incense every 30min" but nothing happens... I still have in my bag the 3 incense.. 

Thanks!! :)

for pokemon sniping, can there be a future feature wherein we can select which region to snipe? Like example i am from Asia so i am NOT allowed to catch taurus, mr.mime and ONLY farfetch'd.. But since the location for sniping is in new york at this moment.. so hopefully in the future there will be a feature for that.. haha.. but if not, it is still very ok!! as long as we can bot, right? haha!! :)

**Comment by Xelwon** [comment]
Bot uses http://pokesnipers.com API to optain which pokemons snipes. So is not only new york. Is what page pokenspers put in that.

Bot currenly have option to do not capture pokemons that appears only in a specific region (option avoid region locked pokemons)
