### ISSUE TITLE
BOT DONT WORK.

### ISSUE THREAD

**Issue by DiieH** [Ar1i/PokemonGo-Bot#4064]
Hey ^^

anyone can help me & say me the steps for opening the new bot version?

i get always errors in the log ^^
idkwhat i make wrong.

**Comment by suljo94** [comment]
set it up from scratch

**Comment by Xelwon** [comment]
create new folder, copy only the .exe, execute it. configure it. run bot. 
Create screenshot showing the problem and paste here.
