### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by negiboss** [Ar1i/PokemonGo-Bot#4070]
Please add an option for more then 1 pokemon at a time

**Comment by shadowahs** [comment]
This would be unrealistic, and increases your chances of getting banned,

**Comment by negiboss** [comment]
i know i mean it will work like
user choose few pokemons that user wants to transfer
after that it will work by transferring those one by one  
to do that bot will store all the pokemons to be transfer in its own memory then do it as normal user do.

**Comment by shadowahs** [comment]
is this not what it does now.....
