### ISSUE TITLE
can't set location anymore

### ISSUE THREAD

**Issue by cesarmull** [Ar1i/PokemonGo-Bot#4071]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by SscSPs** [comment]
a workaround, navigate to the location you wish to set, click on altitude textbox and press the"tab" key on your keyboard and then press "space bar". this should set your location

**Comment by jdunnet** [comment]
Set location button on Location screen has disappeared from the starting menu where you set your location. SscSPs work round does work for me.
Can't screen shot easily sorry.

**Comment by SscSPs** [comment]
there is an app named "snipping tool" inbuilt in windows, use that to take screenshots if you wish to

**Comment by jdunnet** [comment]
Thanks will do when I restart the bot again. Running Windows Virtual Machine on a Mac so my brain froze :-)

**Comment by cesarmull** [comment]
it's been corrected thanks !

**Comment by Logxn** [comment]
fixed
