### ISSUE TITLE
No items when farming pokestops, only xp!

### ISSUE THREAD

**Issue by gothsk8er** [Ar1i/PokemonGo-Bot#4072]
Hi! I have 0 pokeballs, all have run out and i cant get any because the bot does not get items when farming pokestops!
![untitled](https://cloud.githubusercontent.com/assets/22418656/18810504/ec5c6028-82a0-11e6-8b58-f2608c5b9282.png)
 Please help me !

**Comment by negiboss** [comment]
look at your items its 350/350 remove potions and revive qty from your beg

**Comment by gothsk8er** [comment]
LOL
Ty alot :) , i will delete this
