### ISSUE TITLE
URI Service?

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#4075]
Hi Guys!! There is this new feature on our about.. The URI Service; what is this for? Sorry for the noob question.. but hopefully someone can explain this.. Thanks much!! :)

**Comment by cicklow** [comment]
1- activate URI
2- go to http://pokesnipers.com/ or http://pokezz.com/
3- click "Snipe Me" or "Poke Snipers" (this in sites)
4- the bot is open and capture this pokemon auto

**Comment by Logxn** [comment]
^
