### ISSUE TITLE
the walking way cross the sea

### ISSUE THREAD

**Issue by f2011k11ex** [Ar1i/PokemonGo-Bot#4076]
![snap1](https://cloud.githubusercontent.com/assets/22422533/18812659/03a49b84-830e-11e6-824e-234cb48448f0.png)
hi, everyone. just like the above pic. the walking way cross the sea. it's very strange in actual life.
please sovle the problem, thank you.

**Comment by cicklow** [comment]
use Google Routing, that solves your problem

**Comment by erickrisnarinjaya** [comment]
@cicklow how to find out the Google Routing API Key? And why it set Beta for this feature in the bot? Is it not done yet?

**Comment by cicklow** [comment]
@erickrisnarinjaya 
https://developers.google.com/maps/documentation/directions/start#get-a-key/
scroll down to 

> Click the button below to follow a process where you will:
> 
>     Create or select a project
>     Enable the API
>     Get an API key

**Comment by erickrisnarinjaya** [comment]
@cicklow thanks. bro can u give me the link of the previous version (1.1.7.4)? I think I need that.

**Comment by cicklow** [comment]
@erickrisnarinjaya go to https://github.com/Ar1i/PokemonGo-Bot/commits/master/Builds-Only
select a day->"Builds-Only/PokemonGo.RocketAPI.Console.exe"->view->download :P

**Comment by Adj1e** [comment]
@erickrisnarinjaya 1.1.7.5 best bro. I use it. 
@cicklow Thanks bro
