### ISSUE TITLE
I PREFER THE PREVIOUS VERSION

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#4077]
i think this newest version is too not as simple as previous version. If I can suggest, please make as previous version. Thanks.

**Comment by erickrisnarinjaya** [comment]
Or, just give me the download link of the previous version. Thanks.

**Comment by cicklow** [comment]
@erickrisnarinjaya go to https://github.com/Ar1i/PokemonGo-Bot/commits/master/Builds-Only
select a day->"Builds-Only/PokemonGo.RocketAPI.Console.exe"->view->download :P
