### ISSUE TITLE
Just got banned after using the newest version (presumably because of the autosnipe)

### ISSUE THREAD

**Issue by Guiseppe3** [Ar1i/PokemonGo-Bot#4080]
Hey guys. Correct me if im wrong but my Bot still opens the Pokemonlist tho it says that it cannot find any pokemons in the next 5000 meters. I also am not able to log into my account (phone with GPS disabled, it says it has server issues).

I started to bot using the newest version although I let the bot do the sniping automatically and only for certain pokemon. Prerry sure RIP..... The greed always gets me

**Comment by erickrisnarinjaya** [comment]
Dont snipe. Because you cant teleport yourself in the real life.

**Comment by Guiseppe3** [comment]
Well I assumed that the autosnipe means just that he ignores other pokemon and just goes straight to the one I want to snipe.

**Comment by SscSPs** [comment]
if your bot do catch pokemons with sniping, you are not permanent banned 
wait 24 hours till you can be sure

**Comment by Guiseppe3** [comment]
Ok Guys. Its weird. I was IP banned. But I only used 1 Bot. 
Still I wasnt able to connect via App

**Comment by SscSPs** [comment]
IP ban is actually IP of your wifi router. it doesn't really matter if you use 1 bot or 2, if you use a bot on other device on same wifi, or on your app, it gives out a trigger for IP ban

**Comment by Guiseppe3** [comment]
Makes Sense. Ty
