### ISSUE TITLE
Adding iPhones to the device list

### ISSUE THREAD

**Issue by BungaBungaParty** [Ar1i/PokemonGo-Bot#4081]
There are no iPhones in the device list. Can these be added?

**Comment by Xelwon** [comment]
¿Do you have this information about that devices?

 { "note3",
                new Dictionary<string, string>()
                {
                    { "AndroidBoardName", "MSM8974" },
                    { "AndroidBootloader", "N900PVPUEOK2" },
                    { "DeviceBrand", "samsung" },
                    { "DeviceId", "8525f5d8201f78b5" },
                    { "DeviceModel", "SM-N900P" },
                    { "DeviceModelBoot", "qcom" },
                    { "DeviceModelIdentifier", "cm_hltespr" },
                    { "FirmwareBrand", "cm_hltespr" },
                    { "FirmwareFingerprint", "samsung/hltespr/hltespr:5.0/LRX21V/N900PVPUEOH1:user/release-keys" },
                    { "FirmwareTags", "test-keys" },
                    { "FirmwareType", "user" },
                    { "HardwareManufacturer", "samsung" },
                    { "HardwareModel", "SM-N900P" }
                }
            },

**Comment by jdunnet** [comment]
How would I get it from the device?

**Comment by caraoge** [comment]
I think this has no sense because the bot emulates sensor data for an android device. If you would add an iDevice as hardware type it's easy for Niantic to identify you as an botuser.

Please correct me if i'm wrong.

**Comment by Ar1i** [comment]
^ thats true, ios requests are different

**Comment by BungaBungaParty** [comment]
OK. Thanks.
