### ISSUE TITLE
Pokemon Go Sniper option doesn't work.

### ISSUE THREAD

**Issue by halloaki** [Ar1i/PokemonGo-Bot#4089]
When the bot is running I try to open up the Pokemon snipe button so I can start a automated search, This sadly doesn't work anymore for some reason. When I try to open it [this error](http://i.imgur.com/MMatsaB.png) pops up. [Here](http://pastebin.com/6ng4UiYA) is what the error says in detail.

It worked this morning but then it suddenly stops working. When I click continue the pokeball doesn't show up anymore and the hud is broken. The bot still runs.

[After I click continue.](http://i.imgur.com/ZphFsQ2.png)

**Comment by Xelwon** [comment]
Was solved in last version
