### ISSUE TITLE
Path overide detected ....

### ISSUE THREAD

**Issue by BungaBungaParty** [Ar1i/PokemonGo-Bot#4091]
Continually posting 

Path overide detected .... 
![capture](https://cloud.githubusercontent.com/assets/22419391/18817555/1438fad8-835b-11e6-8f56-6341a9e66a17.PNG)

in log screen approx 20 times a second.
Probably after I have terminated a path just my shutting down app.
Pausing an restarting walking stops to erros for a short while after resuming walk.

A fresh install does not do it, so I am guessing there is a 'tag' in a log file somewhere.

**Comment by Xelwon** [comment]
Have you selected google routing

**Comment by MTK4355** [comment]
Ah, Hadn't thought about that. I'll try to Clear the defined route on bot start to prevent this. Thanks for the feedback!

**Comment by jdunnet** [comment]
@Xelwo. Yes, Google routing was selected.
BTW what is the benefot of supplying my own Google API key. (I have one.)
