### ISSUE TITLE
Razz Berry in Snipe POkemon

### ISSUE THREAD

**Issue by caiom1** [Ar1i/PokemonGo-Bot#4093]
so, i saw in snipe pokemon, just one razz berry was be used, have some way to use razz berry every time pokemon escaped? If not, why don't put this option? Every time pokemon escaped, put new razz berry, that's way, probability to catch pokemon is better

![image](https://cloud.githubusercontent.com/assets/21690941/18818723/63c29cca-8357-11e6-8b1e-4e63453243f8.png)

**Comment by MorganHuangPhx** [comment]
Dear Guys,
The issue have been fixed as the above, please help to update the main repository.

Thanks,
Morgan
