### ISSUE TITLE
problems in pokestops

### ISSUE THREAD

**Issue by paulinho775** [Ar1i/PokemonGo-Bot#4095]
I'm in trouble because the bot is not farm pokestops, it returns this error, and as you can see in the pokestop was not caught any items

![asdf](https://cloud.githubusercontent.com/assets/22435697/18818911/eb8c66a0-835b-11e6-9d7b-39e7be6693ee.png)

someone else is with this problem and could help me?

**Comment by elrsifc** [comment]
check your bag, maybe your bag is full

**Comment by caiom1** [comment]
this is because your bag are full

**Comment by paulinho775** [comment]
thanks for the reply, but is full the problem is that pharma or eggs leave running and when I see is with eggs 0
