### ISSUE TITLE
Turkish language option

### ISSUE THREAD

**Issue by abdulkadiraktas** [Ar1i/PokemonGo-Bot#410]
Hello,
I downloaded this program, which is open source really been very nice. Congratulations. However, in the language of the program interface language you can easy to change?

I am writing using Google translate :)

**Comment by Ar1i** [comment]
Uhm, no its not that easy current. But I will add a option for that later!

**Comment by HaydarOzturk** [comment]
Abdul kadir ben hali hazırda bunu önerdim ilerde gelicek merak etme. Böyle konular açmayıp pekte meşgul etmezsek programcıları güzel olur.

I add an explanation and said he shouldn't open threads like that because I already suggested. If you leave this thread hear @Ar1i the others won't open either.

**Comment by abdulkadiraktas** [comment]
I need to do it again, but with all that I can update myself a little bit. :(

http://prntscr.com/bzhju3

**Comment by abdulkadiraktas** [comment]
Bende programlada az buçuk bilgim var zaten ama her güncelleme ile tekrar oturup TR'ye çevirmek sıkıyor kendim bir eklenti eklesem bile bir sonra ki güncellemesinde o eklenti oladığı için sıfırdan çeviri yapmak zorunda kalıyorum : ) 


I have less than half the programs have information already but again sit down with each update to TR-add plug-in for an even bothers to turn myself I have to do the translation from scratch is possible for an add-on after the update it:)  ( Google Translate )

**Comment by HaydarOzturk** [comment]
Bende onu diyorum işte daha fazla yorum yapma zaten eklenecek translation ilerde. Böyle yorumlarla bu insanların vaktini almayalım diyorum anladın mı güzel kardeşim? Burası forummuş gibi davranmayalım yani. 

That is the thing I am talking about. It is going to be added in the FUTURE, so do not waste their time with more comment okay my brother? We shouldn't act like this is a forum.
