### ISSUE TITLE
PokemonGo updated latest version pokemon catching location display

### ISSUE THREAD

**Issue by jake109913** [Ar1i/PokemonGo-Bot#4105]
After the new version released now the pokemon go will display the location where you caught it....so how the sniping tools fix it?

![445903a44623d534733597f5ffb4ec34](https://cloud.githubusercontent.com/assets/22091986/18836288/eb80ce04-8431-11e6-8b57-9ddb31b50d6c.jpg)
Sniped at Egypt

![7f11b3913320a208a31b7a3579742b76](https://cloud.githubusercontent.com/assets/22091986/18836291/ee2369dc-8431-11e6-999e-5bd495a7e367.jpg)
Sniped at New York

**Comment by Bence98007** [comment]
Sniping tool is actually gets a pokemon's location, goes there to capture it. It can be everywhere in the world. (Even on the moon)
I have pokemons captured @Central Park, and my bot keeps playing here in Budapest.

**Comment by TxShack** [comment]
> Sniping tool is actually gets a pokemon's location, goes there to capture it. It can be everywhere in the world. (Even on the moon)
I have pokemons captured @Central Park, and my bot keeps playing here in Budapest.

And if I'm not wrong once it is on the location it goes into the animation of capturing it but then changes the location back to original and then actually throw the pokeball and capture it. At least thats how I did it for safety.
