### ISSUE TITLE
NEW ERROR GoogleOfflineException

### ISSUE THREAD

**Issue by ElementV2** [Ar1i/PokemonGo-Bot#411]
It was working 1 hour ago but now when i try to launch the soft i got this error ... http://puu.sh/qjNgj/da92893011.png

**Comment by Oguzcan13** [comment]
This is due to your user name and password

**Comment by Oguzcan13** [comment]
(String Username , String Password )

**Comment by ElementV2** [comment]
I got it i use a professional adress ... i dont know why its dont working anymore ! with my personal adress its working but im not playinbg with it and professional adress dont let me create an exception for this  !
