### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by ZarSvane** [Ar1i/PokemonGo-Bot#4111]
Hi,
i'd like to know how I can set auto-delete pokemon under 80% IV.
Thanks for helping

**Comment by awyong1214** [comment]
before u run the bot, at pokemon tab, under 'bot settings', set 'Max. IV to transfer' to 80.
default value is 90.

**Comment by ZarSvane** [comment]
I tried, but nothing happened. Have I check some square?

**Comment by SkolgeaR** [comment]
Max duplicate pokemons, and Max Cp to transfer.

**Comment by ZarSvane** [comment]
Now it works! Thank you guys.
