### ISSUE TITLE
How many can u bot a day? 

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#4113]
I just wanna know how many of u guy bot a day i usually do only 2 bots a day and i have 10 acc. If  i do more than 2 the proxy gets soft ban or spins pokestops but doesn't  get any loot.

**Comment by lifeofkuli** [comment]
did u use proxy?

**Comment by lifeofkuli** [comment]
can we bot now? As I heard someone said we better stop bot now till new version coming out?

**Comment by Buckrogers81** [comment]
2 Bots a Day and 10 Accounts??? What are you doing? Selling these Accs at Ebay?

**Comment by Zestiria00** [comment]
Yes i use proxy but still most proxies dont last an hour(maybe many people are using it for pogo too. i use those account to gym before the update but now i just lvl them up for now for future gym raiding.

**Comment by coffeexp** [comment]
There are some pages on facebook that selling pokemon accounts.. and 1 page selling a bot software.. though it is not Ar1i's bot but the fact that they are selling it to the innocent people who don't know that it is for free... geez...

**Comment by Zestiria00** [comment]
Well i dont need money and i wont be selling this accounts it got atleast 5 strong pokemons (3.5k-3.1k)each account because those 3.1k-3.5k are my line up for gym raiding. The amount of time and passion i poured in to it is just insane so yea no-uh!
