### ISSUE TITLE
is it safe to bot right now?

### ISSUE THREAD

**Issue by Matze827** [Ar1i/PokemonGo-Bot#4114]
read above

**Comment by NaTriiuM** [comment]
i hope ^^

**Comment by sizkix** [comment]
been offline since 26e, try botting this morning about 7h, no problem so long, started agen 1h ago still ok, but yea i still think u can be banned, so be carrryfullish

**Comment by SkolgeaR** [comment]
No.

**Comment by Adj1e** [comment]
I botting with acc lvl 30 and not get a ban. But Im not botting with main acount lvl 37 hehe.
