### ISSUE TITLE
Mass Evolving and Collecting Pokestops

### ISSUE THREAD

**Issue by xscias21** [Ar1i/PokemonGo-Bot#4116]
My question is since the force update by niantic the bot is stopped for a short span of time. 

-Now does mass evolution can trigger soft or permanent bans? does evolution also send encrypted data to niantic? 

-How about farming pokestops? is it safe to use bot as long as we are not catching pokemons?

**Comment by xuban** [comment]
Try it and if you tell you they ban us.

**Comment by sizkix** [comment]
been botting for around 7h for 3days now, still not banned, but is prob coming h0hiha

**Comment by xscias21** [comment]
there is a news that bot users will be eradicated soon enough. maybe as of now niantics are collecting information which accounts should be banned. so I havent tried to bot again yet. 😁
if my guess was right even evolving and collecting items send an encrypt data since 0.39.1 update. so using bot to do anything will result to a perma ban soon. thats why i am asking somebody knowledgable about the topic.
