### ISSUE TITLE
SUGESTION

### ISSUE THREAD

**Issue by paulinho775** [Ar1i/PokemonGo-Bot#4120]
good morning, have some way to put the bot attack gym and put Pokemon to defend the gym for the same team?

**Comment by coffeexp** [comment]
As for the moment.. that wont happen.. as Ar1i said, it will kill the fun for the real players.. and he's right, isn't he? :) so go bot to farm and go out to fight gym.. :)

**Comment by Blubb123** [comment]
In my opinion it would be okay, to take open arenas, or arenas which have an open slot.
