### ISSUE TITLE
Cracking.

### ISSUE THREAD

**Issue by NaTriiuM** [Ar1i/PokemonGo-Bot#4121]
Hey ^^

anyone knows how long needs to crack the new api? 

when u play pogo now with bot then u get to 99,99% a perma ban ^^

**Comment by xuban** [comment]
Yesterday. U dont have it?

**Comment by Abfall** [comment]
@xuban Do you have the new api ?

**Comment by xuban** [comment]
Yeah. I'm the only person in the world with the API.... (ironic)

**Comment by NaTriiuM** [comment]
pff ^^
