### ISSUE TITLE
My Dummy Account Is Banned!

### ISSUE THREAD

**Issue by coffeexp** [Ar1i/PokemonGo-Bot#4123]
as what the title says.. haha..
well it is not really safe to bot as of this moment guys.. :)
sad for my dummy it was level 26.. haha..

**Comment by Zestiria00** [comment]
what are your configs settings??did u bot and play it on the new pogo version???

**Comment by sofos1990** [comment]
both my accnts are banned now

**Comment by coffeexp** [comment]
@Zestiria00 opened app only once during introduction.. and the rest all bot.. account created before 0.37 updates.. walking speed to 10~15km.. :)

**Comment by coffeexp** [comment]
and my main account has been banned also.. :( i never opened it on the app.. never bot after 0.39 update.. :(

**Comment by Zestiria00** [comment]
that sucks... guess im lucky still have my accounts and my running setting is 30-50km in the latest bot version i must be very lucky!right now im botting lvl 31,30,29,27 and 3 new acc all lvl 20-25. All in 30-50km..

**Comment by Blubb123** [comment]
my lvl 27 still works and I only used Bot, I just logged in the first time in 0.39 to check it.

**Comment by M31860** [comment]
same here...
and i didnt open the app and bot since the last forced update...
good bye pokeshit:D

**Comment by ramigora** [comment]
same, sec acc got banned

**Comment by iNoobaS** [comment]
my account got banned too

**Comment by king2010116** [comment]
I see many people get the ban with other BOT

I don;t know when can use the BOT

**Comment by dieter90210** [comment]
¿Bot is dead? seems that niantic finally did it.

**Comment by Konageski** [comment]
I am testing the bot in my test account and i not be banned yet.
I am using two hours a day, i started on monday.
Don't evolve pokemons, using lure and luck egg.
Only catch and transfer pokemons.
I am lucky?

**Comment by ocuellar** [comment]
Stopped using the bot after 0.37 (autoupdated on the phone and used) and my account is still valid. 
Sad, I won´t make it to level 25 ever.
