### ISSUE TITLE
What Message.

### ISSUE THREAD

**Issue by ToeyKK** [Ar1i/PokemonGo-Bot#4124]
Your account has been suspended for violating the Terms of Service.  Please see the Help Center for additional information.

**Comment by KingSyah** [comment]
you got love letter from Niantic

**Comment by ToeyKK** [comment]
hahaha.

**Comment by coffeexp** [comment]
Wow Congrats!!!

**Comment by Mr4Net** [comment]
I wonder  it is a permanent ban or temporary ban?
