### ISSUE TITLE
Bot wont Start

### ISSUE THREAD

**Issue by Camarozbro23** [Ar1i/PokemonGo-Bot#4125]
![buags](https://cloud.githubusercontent.com/assets/22565233/19016369/539dbf7a-87dd-11e6-87e0-be8615a69ed7.PNG)
###### ################## RULES. READ BEFORE POSTING!

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment
###### 

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Camarozbro23** [comment]
Everytime i start the bot it shows this please help

**Comment by king2010116** [comment]
MAY BE YOU GET THE BANNED OR PASSWORD WRONG
