### ISSUE TITLE
bot dead?

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#4126]
![lol](https://cloud.githubusercontent.com/assets/22138908/19017917/301cfb28-8892-11e6-9c51-6542d484556f.png)
is it?

**Comment by BOYSA** [comment]
BANNED

**Comment by Zestiria00** [comment]
Lol not even banned.

**Comment by 16Barre** [comment]
I'm truly sad to confirm that you are banned. 
I've got the same error, try to play with bluestacks and I got the "failed to get data from server"
The strange thing is that I didn't get any email from Niantic

**Comment by atomirny** [comment]
you are not banned, check your IP.

**Comment by Zestiria00** [comment]
Hahahaha sucks on u im still not ban :P

**Comment by MrJackBR** [comment]
"THE BOT IS CURRENTLY DOWN DUE TO A FORCED UPDATE BY NIANTIC. PLEASE DO NOT CREATE ISSUES. SEE DISCORD LINK BELOW FOR UPDATES!" that's on the 1st page of this project...
