### ISSUE TITLE
Is Bot Broke? Wont Start!

### ISSUE THREAD

**Issue by Camarozbro23** [Ar1i/PokemonGo-Bot#4127]
###### ################## RULES. READ BEFORE POSTING!

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment
###### 

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Camarozbro23** [comment]
![buags](https://cloud.githubusercontent.com/assets/22565233/19018102/bcf9312e-881a-11e6-8793-01e0a7b638ab.PNG)

**Comment by Camarozbro23** [comment]
is it broke? p.s IM NOT BANNED AND PASSWORS IS CORRECT

**Comment by NaTriiuM** [comment]
delete that and make new ^^
