### ISSUE TITLE
I am confused about using my account on a mobile device?

### ISSUE THREAD

**Issue by DayumDude** [Ar1i/PokemonGo-Bot#4129]
Hey,
I've read alot about getting banned using the new version of Pokemon GO on my mobile device. 
So how exactly do i get banned? I've **never** used my account on a mobilphone (made it for that bot). So, if I just login in with my cheated account, do i instantly get banned? Or can i avoid it in any specific way?
Greetings and Thank you very much =)

**Comment by xscias21** [comment]
you have to wait for a week. niantic ban accounts on a weekly basis
