### ISSUE TITLE
[request] live tracking 

### ISSUE THREAD

**Issue by TheDarkClaw** [Ar1i/PokemonGo-Bot#413]
some way to live tracking the bot on a map to see where he is.
maybe some kind of live map.
would be very nice

thx a lot,
TheDarkClaw

**Comment by Bacon00** [comment]
yeah, i found that feature realy cool on the Pokebuddy

**Comment by guzdank** [comment]
great feature

**Comment by rlmrso** [comment]
I thinks you will see it spoof all over the place, is the bot using only roads ?

**Comment by Tochez** [comment]
There is already out

**Comment by Tochez** [comment]
use telegram

**Comment by Tochez** [comment]
#95

**Comment by TheDarkClaw** [comment]
@Tochez yes but it isn't a live map -.-
but thx

**Comment by StyX996** [comment]
Already requested #215
