### ISSUE TITLE
To everyone having an issue with the bot not starting. (NOT AN ISSUE, A STATEMENT)

### ISSUE THREAD

**Issue by xxKevinSniperxx** [Ar1i/PokemonGo-Bot#4130]
Currently the bots api is not updated, this makes it very easy for niantic to ban your account if you are using the bot, i suggest to everyone who still has their account, to take a break from using the bot until the api is fixed, and to everyone getting errors when using the bot, i'm sorry to inform you that your account is most likely banned, you'll be forced to start a new one.

**Comment by lifeofkuli** [comment]
any estimated timeline? btw thank you to the team for the fun in boting pogo :)
