### ISSUE TITLE
as of october 8,2016 Pokestops not in range? My account can be logged in and not banned but it cant find any pokestops in range? Is there a fix to this? :( 

### ISSUE THREAD

**Issue by kimoy0926** [Ar1i/PokemonGo-Bot#4133]
###### ################## RULES. READ BEFORE POSTING!

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment
###### 

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by MrJackBR** [comment]
"THE BOT IS CURRENTLY DOWN DUE TO A FORCED UPDATE BY NIANTIC. PLEASE DO NOT CREATE ISSUES. SEE DISCORD LINK BELOW FOR UPDATES!" that's on the 1st page of this project...

**Comment by Zestiria00** [comment]
Ur real IP ad is banned so u should stop botting or change ur ip lul.
