### ISSUE TITLE
BOT DEAD ??

### ISSUE THREAD

**Issue by miejf** [Ar1i/PokemonGo-Bot#4134]
![bandicam 2016-10-08 17-51-52-029](https://cloud.githubusercontent.com/assets/15524794/19212258/13d04860-8d80-11e6-9a19-0b3dff2aaa87.jpg)

**Comment by miejf** [comment]
![bandicam 2016-10-08 17-55-30-077](https://cloud.githubusercontent.com/assets/15524794/19212278/6ad869da-8d80-11e6-9b95-15b2e7e265eb.jpg)

**Comment by MrJackBR** [comment]
"THE BOT IS CURRENTLY DOWN DUE TO A FORCED UPDATE BY NIANTIC. PLEASE DO NOT CREATE ISSUES. SEE DISCORD LINK BELOW FOR UPDATES!" that's on the 1st page of this project...

**Comment by miejf** [comment]
PokeSnipers TO.. 


![Uploading bandicam 2016-10-08 18-12-55-052.jpg…]()
![Uploading bandicam 2016-10-08 18-12-55-052.jpg…]()

**Comment by miejf** [comment]
![Uploading bandicam 2016-10-08 18-12-55-052.jpg…]()

**Comment by miejf** [comment]
THANKS FOR INFORMATION..
