### ISSUE TITLE
Neue Pokemon Go Rocket API

### ISSUE THREAD

**Issue by Croc0008** [Ar1i/PokemonGo-Bot#4136]
Hey!
Wann kommt das Update des Bot jetzt eig? Ich habe schon aus mehreren Quellen (z.B. YouTube) erfahren, dass die neue Pokemon Go API bereits gecracked worden ist, und es gibt ja auch schon Bots, die die neue API mit Buddy Update bereits besitzen :c

**Comment by iNoobaS** [comment]
keine ahnung...

**Comment by NaTriiuM** [comment]
wie welche bots denn? wie heissen die?

**Comment by Croc0008** [comment]
@NaTriiuM 
Also ich bin mir nicht sicher, aber Pokefarmer hat glaube ich schon das Buddy Update drinne und auf YouTube habe ich einen Bot gesehen, wo man seinen Buddy auswählen konnte...
Allerdings habe ich  mir den nicht gedownloadet da ich nur Ar1i vertraue, also das er nicht infected.

**Comment by NaTriiuM** [comment]
ahso okay und wieso macht arli nix neues?

**Comment by AiVo7z** [comment]
Naja also ne Anwendung zu programmieren wo alle knöpfe da sind die man möchte ist nicht schwer, könnte ein fake sein für Aufmerksamkeit. ob nun die bots da überhaupt schon laufen is so ne Sache "hab ich auf YouTube gesehen" ist eigtl. die aussage: steht im Internet, also muss es stimmen.

**Comment by Logxn** [comment]
Wir haben nen discord dafür.
