### ISSUE TITLE
HAS DEVELOPMENT OF THE BOT STOPPED?

### ISSUE THREAD

**Issue by Slayer013** [Ar1i/PokemonGo-Bot#4137]
i know niantic has tighten their security...
i just want to know if there are still activities regarding the development of the bot..
i missed using it so much.. T_T

anyways, Good luck guys!

**Comment by Shai-hulud357** [comment]
Hi, FPM has announced today that Niantic API had been cracked few hours ago. I suppose that Bot dev should start again pretty soon ... I know from Ar1i via twitter that he always has an eye on bot dev ...

**Comment by SscSPs** [comment]
Just a notification, the work on this has started again!
