### ISSUE TITLE
Bot doesnt work

### ISSUE THREAD

**Issue by Zestiria00** [Ar1i/PokemonGo-Bot#4139]
This always comes up. I already tried on other new bot with new api and the account works fine with them ..
![20161110_014051](https://cloud.githubusercontent.com/assets/22138908/20143961/c2be98ca-a6e6-11e6-910b-ca54bda1a0f9.jpg)

**Comment by Croc0008** [comment]
too.

**Comment by peterMfrj** [comment]
Maybe because 
THE BOT IS CURRENTLY DOWN DUE TO A FORCED UPDATE BY NIANTIC. PLEASE DO NOT CREATE ISSUES. SEE DISCORD LINK BELOW FOR UPDATES!

**Comment by Logxn** [comment]
Its updated again. 
Have fun

(btw. it was not working when you tried it, cuz niantic changed their api)
