### ISSUE TITLE
[Request] Add an option to catch specific pokemons via pokevision

### ISSUE THREAD

**Issue by pikaiskawai** [Ar1i/PokemonGo-Bot#414]
You could add an option to catch specific pokemons via pokevision map that would be an awesome add !

**Comment by rlmrso** [comment]
Implementing this is nice, but will not work when pokevision is not working

**Comment by StyX996** [comment]
Since the newest update you can select wich pokemon will not be caught via Pokevision in settings (don't catch pokemon)
