### ISSUE TITLE
Playerstats Error

### ISSUE THREAD

**Issue by InZaNeSkIl1zZ** [Ar1i/PokemonGo-Bot#4140]
The playerstats do not show up in the current version. May you could fix it with a new update.
Screenshots and code below.
Thanks guys

![unbenannt](https://cloud.githubusercontent.com/assets/21690506/20244599/f888b07c-a988-11e6-83e9-db88311e9391.PNG)

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() in C:\Users\nrgne\Documents\GitHub\New Version\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:Zeile 286.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Console.PlayerPanel.<updatePlayerInfoLabels>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly-Version: 1.1.8.1.
    Win32-Version: 1.1.8.1.
    CodeBase: file:///C:/Users/Richard/Desktop/PokemonGo-Bot/Builds-Only/PokemonGo.RocketAPI.Console.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Pokemon.Go.Rocket.API
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.1.8.1.
    CodeBase: file:///C:/Users/Richard/Desktop/PokemonGo-Bot/Builds-Only/PokemonGo.RocketAPI.Console.exe.
----------------------------------------

**Comment by Logxn** [comment]
Fixed
