### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by ko2i4s** [Ar1i/PokemonGo-Bot#4145]
Hi, 

I was using the bot before the Niantic Update, so i just downladed the new version seeing Ar1i message on twitter, but i constantly have the : "Your account should be banned" red message.

So i made a new google account (assuming the old one was banned), and  same problem but this time i have the GUI who's open.

I thought to an Ip ban ? (i dont think because i don't have static IP)

Any ideas ?

screenshot : https://gyazo.com/dd1876837dedbf237859766179cbb612

config : 

`[{"ProfileName":"DefaultProfile","IsDefault":true,"RunOrder":0,"SettingsJSON":"{\"SessionHash\":null,\"ProfileName\":\"DefaultProfile\",\"IsDefault\":true,\"AuthType\":0,\"PtcUsername\":\"MAILADRESS\",\"PtcPassword\":\"PASSWORD\",\"GoogleUsername\":\"MAILADRESS\",\"GooglePassword\":\"PASSWORD\",\"GoogleRefreshToken\":\"\",\"DefaultLatitude\":40.7929538298151,\"DefaultLongitude\":-73.9571285247803,\"DefaultAltitude\":28.0162410736084,\"UseLastCords\":true,\"WalkBackToDefaultLocation\":true,\"RelocateDefaultLocationTravelSpeed\":0.0,\"RelocateDefaultLocation\":false,\"MaxWalkingRadiusInMeters\":5000,\"FarmPokestops\":true,\"CatchPokemon\":true,\"WalkingSpeedInKilometerPerHour\":9.0,\"MinWalkSpeed\":3,\"TransferDoublePokemons\":true,\"HoldMaxDoublePokemons\":3,\"EvolvePokemonsIfEnoughCandy\":true,\"DontTransferWithCPOver\":999,\"Pb_Excellent\":35,\"Pb_Great\":25,\"Pb_Nice\":25,\"Pb_Ordinary\":15,\"MaxPokeballs\":100,\"MaxGreatballs\":100,\"MaxUltraballs\":100,\"MaxRevives\":100,\"MaxTopRevives\":100,\"MaxPotions\":100,\"MaxSuperPotions\":100,\"MaxHyperPotions\":100,\"MaxTopPotions\":100,\"MaxBerries\":100,\"UseIncense\":true,\"TelegramLiveStatsDelay\":5000,\"sleepatpokemons\":true,\"ivmaxpercent\":90,\"MinCPforGreatBall\":500,\"MinCPtoCatch\":0,\"MinIVtoCatch\":0,\"MinCPforUltraBall\":1000,\"TelegramAPIToken\":\"\",\"TelegramName\":\"\",\"AvoidRegionLock\":true,\"navigation_option\":1,\"UseLuckyEgg\":true,\"UseRazzBerry\":true,\"razzberry_chance\":0.35,\"keepPokemonsThatCanEvolve\":true,\"TransferFirstLowIV\":false,\"UseBasicIncubators\":false,\"pokevision\":false,\"AutoIncubate\":true,\"UseLuckyEggIfNotRunning\":false,\"SnipePokemon\":false,\"Espiral\":false,\"MapLoaded\":true,\"SelectedLanguage\":\"en\",\"UseProxyHost\":\"\",\"UseProxyPort\":0,\"UseProxyUsername\":\"\",\"UseProxyPassword\":\"\",\"UseProxyVerified\":false,\"UseProxyAuthentication\":false,\"catchPokemonSkipList\":[],\"pokemonsToHold\":[],\"pokemonsToEvolve\":[],\"NotToSnipe\":[],\"itemRecycleFilter\":[{\"Key\":1,\"Value\":100},{\"Key\":2,\"Value\":100},{\"Key\":3,\"Value\":100},{\"Key\":201,\"Value\":100},{\"Key\":101,\"Value\":100},{\"Key\":102,\"Value\":100},{\"Key\":103,\"Value\":100},{\"Key\":701,\"Value\":100},{\"Key\":104,\"Value\":100},{\"Key\":202,\"Value\":100}],\"pauseAtPokeStop\":false,\"BreakAtLure\":false,\"UseAnimationTimes\":true,\"UseLureAtBreak\":true,\"UseGoogleMapsAPI\":false,\"GoogleMapsAPIKey\":\"\",\"RandomReduceSpeed\":true,\"TimeToRun\":300.0,\"PokemonCatchLimit\":955,\"PokestopFarmLimit\":1595,\"XPFarmedLimit\":149550,\"BreakInterval\":55,\"BreakLength\":5,\"UseBreakFields\":true,\"NextDestinationOverride\":[],\"RouteToRepeat\":[],\"RepeatUserRoute\":false,\"UseLureGUIClick\":false,\"UseLuckyEggGUIClick\":false,\"UseIncenseGUIClick\":false,\"LimitPokeballUse\":true,\"LimitGreatballUse\":true,\"LimitUltraballUse\":true,\"Max_Missed_throws\":3,\"LogPokemon\":false,\"LogTransfer\":false,\"LogEvolve\":false,\"LogEggs\":false,\"AutoUpdate\":true,\"CheckWhileRunning\":true,\"InventoryBasePokeball\":10,\"InventoryBaseGreatball\":15,\"InventoryBaseUltraball\":20,\"UsePwdEncryption\":false,\"pauseAtEvolve\":true,\"EnablePokeList\":true,\"ForceSnipe\":false,\"ManualSnipePokemonID\":null,\"ManualSnipePokemonLocation\":null,\"NextBestBallOnEscape\":true,\"simulatedPGO\":false}"}]`

Sorry for english, and thanks

**Comment by Logxn** [comment]
I assume this is a fresh created account.
To fix this go ahead and log in on your phone.
Accept the ToS, and play the Pokemon Tutorial until the Professor stops talking.

Then retry
