### ISSUE TITLE
Egglist error

### ISSUE THREAD

**Issue by Tr1n0va** [Ar1i/PokemonGo-Bot#4148]
![987654321](https://cloud.githubusercontent.com/assets/20892427/20310449/4a46784e-ab4c-11e6-9903-fb75e99e9443.png)

**Comment by ThomasWDonnelly** [comment]
Has this bug been looked into by the contributors? @Tr1n0va, can you provide steps to reproduce?

**Comment by Tr1n0va** [comment]
I only tryed to Open the egglist... nothing else.

**Comment by vikask77** [comment]
This bug and all other bugs that we run into when parallel operations are performed should get resolved with my latest pull request.

**Comment by Logxn** [comment]
Fixed
