### ISSUE TITLE
No pokeballs?

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#416]
I feel like i'm softbanned and without pokeballs, but i think the system only tells if you're softbanned by pokemon running away, not sure though, but i've been running for about 5 mins and no pokemon have been caught due to no pokeballs

**Comment by plowzey** [comment]
![image](https://cloud.githubusercontent.com/assets/20713579/17271438/5fd161ca-5673-11e6-8723-73b729051027.png)

**Comment by plowzey** [comment]
How to fix?

**Comment by plowzey** [comment]
The problem fixed itself over time sorry /close/

**Comment by Oguzcan13** [comment]
You dont have the Pokeballs
