### ISSUE TITLE
Check for Force-Updates

### ISSUE THREAD

**Issue by Viper2k4** [Ar1i/PokemonGo-Bot#4165]
Heho,

so now we have a force-Update sometimes. Should we maybe add a check (all 30min or so) on:

https://pgorelease.nianticlabs.com/plfe/version

to prevents running the bot with the old API again the new forces version? Today i stopped my Bot at ~6:30 but it seems like he is running with many errors for some hours. And i think this could be very dangerous for the account :)

Greetings

**Comment by Logxn** [comment]
Already added

**Comment by Viper2k4** [comment]
at what point? i dont find it.

**Comment by Logxn** [comment]
I added it, you will see it once the Bot is back online again
