### ISSUE TITLE
Auto Reload Pokemon Inventory

### ISSUE THREAD

**Issue by skexxgo** [Ar1i/PokemonGo-Bot#417]
Every time it auto reloads it doubles the pokemon you have

**Comment by guzdank** [comment]
not happening to me

**Comment by Ar1i** [comment]
use updated version, i dont have that problem

**Comment by skexxgo** [comment]
I've been updating all the time. It fixed on my pc only on this version, till now I had that problem, but oh well, it's fixed now :)
