### ISSUE TITLE
Exception: Newtonsoft.Json

### ISSUE THREAD

**Issue by Tek12345** [Ar1i/PokemonGo-Bot#4178]
[21:35:53] Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à PokemonGo.RocketAPI.Logic.Utils.PokeSnipers.<CapturarPokemon>d__4.MoveNext() dans D:\workspaces\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Utils\PokeSnipers.cs:ligne 38
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__51.MoveNext() dans D:\workspaces\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 897
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   à PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__42.MoveNext() dans D:\workspaces\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:ligne 346
[21:35:53] Restarting in 60 [Seconds.

[http://prnt.sc/dt3vjd](url)

**Comment by esbiete** [comment]
Following Discord conversation between @Tek12345 and @Xelwon , it was solved by creating a new configuration.

**Comment by Logxn** [comment]
Closed
