### ISSUE TITLE
{Request} Add language box

### ISSUE THREAD

**Issue by Oguzcan13** [Ar1i/PokemonGo-Bot#422]
For example, a framework for choosing any language

**Comment by Oguzcan13** [comment]
For example, a framework for choosing any language

**Comment by Oguzcan13** [comment]
"TranslationStrings": [
    {
     "Key": "pokeball",
      "Value": "PokeBall"
    },
    {

**Comment by Dejamelofiao** [comment]
i can traslate to spanish

**Comment by lostsailor** [comment]
I can translate to Turkish

**Comment by 13XxM1CHA3lxX37** [comment]
I can translate to Russian

**Comment by tomypc88** [comment]
i can translate to french if needed

**Comment by cinek19** [comment]
I can help to translate to spanish too

**Comment by Kurimatzu** [comment]
I can translate to Portuguese/Brazil.
