### ISSUE TITLE
Pokemon list doesn't reload.

### ISSUE THREAD

**Issue by hendek95** [Ar1i/PokemonGo-Bot#423]
I can use everything but can't use Pokemon list. Just waiting "reloading pokemon list" and didn't open.

**Comment by Ar1i** [comment]
Uhm for me its working.. Update to newest Version..

**Comment by hendek95** [comment]
one of my friends he can use. but me and other friend cant use :(

**Comment by hendek95** [comment]
![poke list](https://cloud.githubusercontent.com/assets/20742246/17271533/3f114b6c-5687-11e6-9bf7-43d55bd06b81.png)

**Comment by Ceiridge** [comment]
This looks like an old version >:D

**Comment by hendek95** [comment]
same error. i m using now https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only is that true?

**Comment by Ceiridge** [comment]
Okay. How long have you waited?
I had the same problem and I just waited ~5 minutes

**Comment by hendek95** [comment]
i am waiting 2 or 3 hours :D

**Comment by Ceiridge** [comment]
:D - Okay that's really long.
Have you tried restarting the bot XD?

**Comment by hendek95** [comment]
:D i tried restart, delete coords, delete Profile_Nickname_PokemonList ext :dancers:

**Comment by hendek95** [comment]
still reloading :( 
![pokelist2](https://cloud.githubusercontent.com/assets/20742246/17271687/f3f97556-568a-11e6-9183-62886c89199b.png)

**Comment by Ceiridge** [comment]
Well, I can't help you but you can access your Pokemon Go Account later on your phone or bluestacks and then watch your pokemons

**Comment by hendek95** [comment]
hmm that s bad :( pokelist is very usefull. i m already use nox for watching statue but your pokelist is better than nox :D
