### ISSUE TITLE
Pokevision plugin dont work and traslate spanish

### ISSUE THREAD

**Issue by Dejamelofiao** [Ar1i/PokemonGo-Bot#426]
Hello pokevision dont work, correctly localize a pkmn but dont catch, and please insert language for bot, Español, frances, aleman... i am spanish if you want Ar1i I can traslate to spanish

thanks for work

**Comment by Bacon00** [comment]
Pokevision work for me!

**Comment by rlmrso** [comment]
Be alert, in some cities pokevision does not work like in mine...
