### ISSUE TITLE
changing countries

### ISSUE THREAD

**Issue by skalomenia** [Ar1i/PokemonGo-Bot#429]
Hello all
When i want to change country in the bot, it says more than 200hours to wait (maximum raduis..)
Is there any sollution to change it fastly ? 
Thx

**Comment by TMaddox** [comment]
delete the config file where the last coordinates are stored (lastcords.txt) and make sure that the .exe which you use isn´t already active (in case you got multiple accs you will have to make one folder for each account)

**Comment by skalomenia** [comment]
Yeah ok thx for help
