### ISSUE TITLE
Program gets stuck when running on mono

### ISSUE THREAD

**Issue by realChesta** [Ar1i/PokemonGo-Bot#430]
Everything works fine when using .NET to run the thing, but when using mono, the program gets stuck on posting a request.
I was able to trace it down to the following stack:

```
Program.cs:256 -->
Logic.cs:71 -->
Logic.cs:128 -->
Inventory.cs:181 --> 
Inventory.cs:81 -->
Inventory.cs:285 -->
Client.cs:485 -->
HttpClientExtensions.cs:23 -->
HttpClientExtensions.cs:58
```
(each line is one call deeper)

So it appearantly stops when trying to request the inventory in `ExportPokemonToCSV(...).
I think it has to do with an await call not finishing from earlier on, but I don't have enough experience with await calls to be sure.
In addition to this, the fact that this only occurs when running on mono makes it very hard to debug for me.

It is an important thing to make this mono-compatible, as most servers and some users do not run Windows and thus **need** mono to run this.
It would allow for a wider range of applications.

To anyone trying to run this with mono: insert this into the `Main` void before everything else:
```
ServicePointManager.ServerCertificateValidationCallback = delegate (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
            {
                bool isOk = true;
                // If there are errors in the certificate chain, look at each error to determine the cause.
                if (sslPolicyErrors != SslPolicyErrors.None)
                {
                    for (int i = 0; i < chain.ChainStatus.Length; i++)
                    {
                        if (chain.ChainStatus[i].Status != X509ChainStatusFlags.RevocationStatusUnknown)
                        {
                            chain.ChainPolicy.RevocationFlag = X509RevocationFlag.EntireChain;
                            chain.ChainPolicy.RevocationMode = X509RevocationMode.Online;
                            chain.ChainPolicy.UrlRetrievalTimeout = new TimeSpan(0, 1, 0);
                            chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllFlags;
                            bool chainIsValid = chain.Build((X509Certificate2)certificate);
                            if (!chainIsValid)
                            {
                                isOk = false;
                            }
                        }
                    }
                }
                return isOk;
            };

```
(Mono has its own certificate store and pokemon has not bought one - you will run into WebExceptions without this line)

**Comment by Ar1i** [comment]
Nice work, uhm just disable the execl thing for mono then? :p Cause i dont think you need that on a Server!

**Comment by realChesta** [comment]
Disabling that line basically doesn't change anything - the program stops responding after the next http-post-request,this time in `StatsLog(...)`

**Comment by Ar1i** [comment]
mhhh k..
