### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by TehVipRz** [Ar1i/PokemonGo-Bot#433]
How do I get Telegram working???

**Comment by Ceiridge** [comment]
He has made a tutoial for that: https://www.youtube.com/watch?v=m5cZEh4-ZSE
It is in German but I think you can follow his steps

**Comment by meuphilim** [comment]
Meuphilim, [30.07.16 15:08]
/stats

Pokebot, [30.07.16 15:08]
I dont hear at you!

**Comment by Ceiridge** [comment]
You have to type in YOUR username in the bot.
Field: Telegram Username
