### ISSUE TITLE
Discussion - FAST EXP

### ISSUE THREAD

**Issue by ObsessedHacker** [Ar1i/PokemonGo-Bot#434]
How do you guys make Fast EXP?
Here are my settings:
http://i.imgur.com/8MWyHHq.png

**Comment by Ceiridge** [comment]
I think you can get softbanned with that easily.
My speed is: 13 km/h
Why? - Eggs

**Comment by TMaddox** [comment]
move radius much smaller i got it like 1500m (you will walk out of good areas)

speed is ok up to 200km/h (eggs will hatch in the speeding down phase, and the bot doesn´t incubate automatically, so...)

you should calculate how much space is in your inventory and dont overfill it (your settings say 200 each, maby your inv is that big, mine isn´t)

dont evolve pokemon if enough cany, save evolvable pokemon until your inv is full and then evolve with lucky egg

**Comment by Ceiridge** [comment]
I always use a lucky egg before evolving but why should I wait until my inventory is full? :D

**Comment by Logxn** [comment]
Issues are not for discussions.
Please use the highminded thread for discussions.

#PleaseClose
