### ISSUE TITLE
In Which area you farm most EXP ?

### ISSUE THREAD

**Issue by Kelendris** [Ar1i/PokemonGo-Bot#436]
![untitled](https://cloud.githubusercontent.com/assets/20727621/17271668/10cd5ade-5682-11e6-8501-da4019ec341e.png)

**Comment by Tochez** [comment]
usually San Francisco
![capture](https://cloud.githubusercontent.com/assets/20713623/17271731/cd58520c-5651-11e6-8696-0d63de8b90ed.PNG)

**Comment by HaydarOzturk** [comment]
This thread will be closed because it is not a forum you can't make posts like that. That's just wrong man

**Comment by Dejamelofiao** [comment]
dont close please i want know hot places, for farm xp and stardust

**Comment by Ar1i** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/ use the forum
