### ISSUE TITLE
Pokemon Not Transfering

### ISSUE THREAD

**Issue by Loofy101** [Ar1i/PokemonGo-Bot#444]
I have transfer on, with 2 max pulicates and default 999CP 90% and have selected a few not to transfer and the bot doesn't transfer a single pokemon and I come back later with it saying Pokemon Inventory full and all of the rattatas, pidgeys etc still in my inventory. A fix when possible would be highly appreciated.

**Comment by 13XxM1CHA3lxX37** [comment]
Look at their IV (hover over the Pokémon in the GUI list).
 I'm pretty sure their IV is >= 90% and they won't transfer because of that
