### ISSUE TITLE
PokemonInventoryFull Exception at 240/250 pokemon

### ISSUE THREAD

**Issue by illTyped** [Ar1i/PokemonGo-Bot#452]
I have been seeing this happen on two different accounts for a couple days now (I have updated the bot regularly, and still see this happen). When the pokemon count reaches 240/250 or 241/250 pokemon, I start seeing PokemonInventoryFull exceptions after it finds catchable pokemon. The bot keeps trying and failing to catch that pokemon until I manually transfer some pokemon to make room.

I have looked at the .csv export, and it only shows 240 or 241 pokemon, so I suspect the bot is losing track of a few pokemon, somehow. Either that, or it is incorrectly throwing the exception. I have also restarted the bot, and it still shows the same count, but keeps throwing the exception.

Edit: Added screenshot
![capture](https://cloud.githubusercontent.com/assets/1933055/17272448/81374ff0-5664-11e6-839b-82c980d3c8ee.PNG)

**Comment by Ar1i** [comment]
Uhm the Inventory is cached. Probably your Inv is full but in the cached inventory it isnt.

**Comment by FrancYescO** [comment]
@Ar1i i think need to be reopened it's an issue... me too having 250/250 but bot showing 241/250
