### ISSUE TITLE
Can the program a Soft Ban deal?

### ISSUE THREAD

**Issue by LikeAFisch** [Ar1i/PokemonGo-Bot#453]
http://prntscr.com/bzjieq xD The Bot give a fuck.

**Comment by TMCloaker** [comment]
If you made the Pokemon Go account using your real location and then opened the bot in a location very far away you're most likely gonna get soft banned. I would suggest a location in driving distance from you.
1: Don't use the default location. 2: Don't set your movement speed to high, I do 50-100kph.
