### ISSUE TITLE
Bot Suggestions and Pokevision Suggestion

### ISSUE THREAD

**Issue by increaseeffiency** [Ar1i/PokemonGo-Bot#456]
Using the new update, to me it seems as if pokevision finds a target and then it changes priority to fast before dealing with the older target. Maybe extend delay depending on the distance to allow adequate time to capture all pokemon.

Also similar with pokestops even though the bot finds pokemon it reprioritizes to frequently and leaves behind many.

1. Spend more time scanning/rescanning poke stops before moving on.
2. Pathing seems slow to me so I just use radius I would like more customization as radius shape and a visible way to see it.
3. If can detect lured pokestops only focus on them
Thank you

**Comment by rlmrso** [comment]
-Let the bot take a look first at if you really want that kind of pokemon, instead of using pokevision first to find one and going to that place when its going to be skipped. This is spoofing/moving and lost time for no reason. I dont know if this can be fixed thanks !

**Comment by yy4cmm** [comment]
can also implement a better sniping with the api of this http://pokesnipers.com so every x pokestops it snipes at those listed there
