### ISSUE TITLE
Ban for Speed

### ISSUE THREAD

**Issue by DemonBytes** [Ar1i/PokemonGo-Bot#458]
I have 4 bots running at the same time. 3 on 10 km/h and 1 on 50 km/h. All never were getting banned. But sometimes all 4 gets a soft ban at the same time. I don't know why. Is that normal?

And i see multiple times the error: Error at Request  PostProtoPayload GetPlayerResponse retryinge 1/3 .. 2/3 .. 3/3 whats that?

And what about letting it run on 50km/h. Isn't that too dangerous because it would be detected easily, or doesn't it matter?

**Comment by TMaddox** [comment]
thats a server problem (causes bug in the bot, the bot thinks you got banned), dont worry i always have 200km/hr and this is no problem

wait 5 min and it should be normal again

**Comment by DemonBytes** [comment]
But isn't 200 kmh very risky to get perma banned? isnt that too obvious?

**Comment by TMaddox** [comment]
no i think not, some do 300km/h

wouldnt it be bad if you would get banned on the highway ?

**Comment by DemonBytes** [comment]
True... Well. We will see. Thanks for your help buddy
