### ISSUE TITLE
logic

### ISSUE THREAD

**Issue by cinwie** [Ar1i/PokemonGo-Bot#46]
hi..
what wrong this?

2>C:\Users\xxx\Desktop\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Utils\GeoUtils.cs(41,26,41,27): warning CS0219: The variable 'R' is assigned but its value is never used
2>C:\Users\xxx\Desktop\PokemonGo-Bot-master\PokemonGo.RocketAPI.Logic\Navigation.cs(248,53,248,55): warning CS0162: Unreachable code detected

ty

**Comment by Ar1i** [comment]
You can ignore that, its only a warning!
