### ISSUE TITLE
Issue at evolving

### ISSUE THREAD

**Issue by VirtusB** [Ar1i/PokemonGo-Bot#464]
If you can't evolve a pokémon, it will keep trying;

Error at Request PostProtoPayload EvolvePokemonOut retrying 1/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 2/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 3/3   <--- Now it should stop, but it resets
Error at Request PostProtoPayload EvolvePokemonOut retrying 1/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 2/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 3/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 1/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 2/3
Error at Request PostProtoPayload EvolvePokemonOut retrying 3/3

Goes on forever

**Comment by ReeViiS69** [comment]
same!
