### ISSUE TITLE
NoTransfer near Perfect Pokemon

### ISSUE THREAD

**Issue by nulp3** [Ar1i/PokemonGo-Bot#47]
Wär es möglich die Transfer liste so zu verändern das er zB bei 3 Pokemon nicht zwingend die highest CP alleine beachtet sondern zb als GUI Menupunkt Perfect Pokemon [ZahlX %] (zb 90%) auch im Fokus hat.  (Also nicht nur Count(x) macht mit High CP sondern Perfect Pokemon [+- 15% des Last-HighestCP Pokemon] höher Counted als nur die Besten(x) CP Pokemon)

Beispiel bei 3 Best now:
Golbat (Golbat)  |  CP: 1268 (78% perfect) [würde atm Bleiben da Top 3CP]
Golbat (Golbat)  |  CP: 1257 (82% perfect) [würde atm Bleiben da Top 3CP]
Golbat (Golbat)  |  CP: 1247 (73% perfect) [würde atm Bleiben da Top 3CP]
Golbat (Golbat)  |  CP: 1148 (90% perfect) [würde atm Gelöscht da nicht Top 3CP aber wär Technisch besser als das 1247CP Pokemon von den Base Werten]

PS:
Wenn ich das System der PerfectPokemon-BaseStats missverstanden habe Closen.
War mir nur aufgefallen das wenn ein Pokemon gefangen wurde was Schlechter als meine Top 3 war (aber halt unter der Behalte alles ab XXX CP) und nahe zu Perfekt war dennoch Getrashed wurde als dann ein Höher CP zu nehmen mit weniger % auf Perfekt.

**Comment by Ar1i** [comment]
Ja baue das Perfect System morgen noch ein bisschen besser ein.

**Comment by Caddyrn** [comment]
Diese Funktion wünsche ich mir auch. Nicht das er auf die CP schaut sondern wie perfect das Pokemon ist, das man per Funktion aktiviert, nur 90% perfecte Pokemon behalten der rest alles weg.
