### ISSUE TITLE
API POKESNIPERS

### ISSUE THREAD

**Issue by Dejamelofiao** [Ar1i/PokemonGo-Bot#470]
I do not understand you want to include the API pokesniper when the bot is " teleported " to the coordinates where this rare pokemon, they ban you so that you can not capture the pokemon . I think if you first take the bot to a "close " area and wait for the bot will remove the ban , then you can restart the bot with the exact location of rare pokemon, someone correct me if there is any way easier and fast to do it, the Ar1i ​​own could tell us whether you can use the API pokesniper and how.

Thanks for all

**Comment by yy4cmm** [comment]
The pokesniper works like this: it teleports to the pokemon destination, enters the capture mode and teleports back in a fraction of second, so you actually catch it in your current location, once you enter the catch mode it doesnt matter how far you are from it, thats what i understand of how it works, and that is why you dont get softbanned, ive tried it myself and it actually works.

**Comment by Dejamelofiao** [comment]
wow it is really interesting the way that you speak of , how could use it myself?
I can not find any tutorial on how to do

**Comment by Dejamelofiao** [comment]
please can you learn me?

**Comment by Juiche** [comment]
here 
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566079-pokesniper2-pokemon-sniper-catch-any-pokemon-no-matter-where-you.html
