### ISSUE TITLE
Pokemon

### ISSUE THREAD

**Issue by Kelendris** [Ar1i/PokemonGo-Bot#471]
Alle pokemons entwischen mir und kann keine spots mehr einnehmen was kann ich tun ? :(

**Comment by Logxn** [comment]
Warten und die 1337 unban methode ihre arbeit machen lassen.

**Comment by Kelendris** [comment]
die 1337 unban kommt ja nicht er versucht die ganze Zeit pokemons zu fangen aber die entwischen
