### ISSUE TITLE
About the guy coping Ar1i's work

### ISSUE THREAD

**Issue by Bence98007** [Ar1i/PokemonGo-Bot#476]
Hey there!

As you can see, there's a site which copies Ar1i's work. Please, help Ar1i with reporting that little f*cktard's youtube channel. On his site you can view all his videos, just report all of it as spam.

I hope we can get his site down.

**Comment by TMaddox** [comment]
i think the youtube channel doesnt belong to him

**Comment by TMaddox** [comment]
abuse@resellercamp.com
Report him here (this is where he hosts the site)

**Comment by Euskater2** [comment]
look hier ! the site https://www.pokecrot.com/

**Comment by TMaddox** [comment]
if anyone is into spamming this is his email:
vipspuc3ngine@yahoo.com

**Comment by Juiche** [comment]
done. that guy from indonesia, as an indonesian im feel ashamed.

**Comment by TMaddox** [comment]
His download page at the moment: https://www.pokecrot.com/dl/
Hope he got problems :D

**Comment by TMaddox** [comment]
anybody thought about downvoting his vids on youtube ?
i did

**Comment by ShutUpPvP** [comment]
So, i can safely use the bot still? I mean, the dragonite is gone unfortunately.. but yea its safe rite?
Also im going to fuck this bitch over that copies ur stuff, suck a fucking idiot!
And i think its time to say thanks for the constant updates that we get!
