### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by projectcagla** [Ar1i/PokemonGo-Bot#477]
This have a virus?

**Comment by Ar1i** [comment]
Its cause i put Enigma on it. You can google it, so the guy cant steal my source code!

**Comment by projectcagla** [comment]
No problem for the users?

**Comment by Ar1i** [comment]
Uhm what do you mean?

**Comment by projectcagla** [comment]
I close my virus scanner. Is there another way? I also thank you for your answers.

**Comment by Ar1i** [comment]
Yeah, i will update it so it wont get false positives

**Comment by lailaps** [comment]
Last build only 1/54 detection rate.
So it's secure and a good result even with protected source code!

Good job!
