### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by cinwie** [Ar1i/PokemonGo-Bot#48]
hi...
i cant build new version.

![capture](https://cloud.githubusercontent.com/assets/4066191/17114058/898803ec-52d7-11e6-82d2-d310e242762c.PNG)

ty bro....

**Comment by Ar1i** [comment]
STRG + F5

**Comment by cinwie** [comment]
sorry error too...

![capture](https://cloud.githubusercontent.com/assets/4066191/17114470/48b6eb4c-52d9-11e6-9f36-7c151ca24288.PNG)

**Comment by cinwie** [comment]
u packages folder is gone...

![capture](https://cloud.githubusercontent.com/assets/4066191/17115270/c8ef82bc-52dc-11e6-8e16-6a67a69b330d.PNG)
