### ISSUE TITLE
Use AppFuscator to prevent detections and deobfuscation

### ISSUE THREAD

**Issue by realChesta** [Ar1i/PokemonGo-Bot#485]
In my experience, AppFuscator has proven to be the best obfuscator I know.
You may consider using that one as it causes less detections and obfuscates your code in a way most deobfuscators don't detect.

**Comment by Ar1i** [comment]
Thanks!

**Comment by Ar1i** [comment]
Cost money tho, dont have that.. trying to search something free and good

**Comment by realChesta** [comment]
The AppFuscator Demo does the job completely fine - I used it many times.
