### ISSUE TITLE
How can we help you?

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#487]
Guys, it's time we do something back for the publisher of all these builds, as you might of heard someone is stealing his work. So what i wanted to know is how can we help to fight back (Other than donating) Because we owe you something back.

**Comment by Ar1i** [comment]
Try to get it down

**Comment by plowzey** [comment]
How can we do that sir?

**Comment by OGcpalm** [comment]
Yeah if you give me a link I'll fill out what ever you need your bot is amazing bro

**Comment by ShutUpPvP** [comment]
Just post a nice comment on his discussion wall on youtube, and report for something :)

https://www.youtube.com/channel/UCJY3oyxQnT-XC8SXk56XSaw/discussion

**Comment by plowzey** [comment]
I feel like reporting his youtube won't help much.

**Comment by ShutUpPvP** [comment]
Yea... probably

**Comment by juanpedrolopez220** [comment]
i know how to get it down,

**Comment by plowzey** [comment]
Share?

**Comment by TMaddox** [comment]
#476 ive posted a few suggestions here

**Comment by juanpedrolopez220** [comment]
I found his ip, i think... So we go to our CMD in the computer and put:
ping 104.24.111.87 -t -l 1000

**Comment by ShutUpPvP** [comment]
Is there a way to stop a ip from downloading the files?

**Comment by juanpedrolopez220** [comment]
idk

**Comment by ShutUpPvP** [comment]
okay, ure one step ahead haha

**Comment by juanpedrolopez220** [comment]
so if four or five of us ping it, i think it could be down

**Comment by juanpedrolopez220** [comment]
One time i do it, but now i dont know

**Comment by ShutUpPvP** [comment]
For how long? probably not for ever right?

**Comment by TMaddox** [comment]
unfortunately he bought ddos protection but you can comlain at his serverhost:
abuse@resellercamp.com

**Comment by ShutUpPvP** [comment]
Also, do we have 5 ppl?

**Comment by plowzey** [comment]
Well, he has protection on his website, but pinging him is only temporary though,

**Comment by juanpedrolopez220** [comment]
only a few minutes, but is true that is host is cloudfare and i dont know if he cant do it

**Comment by TMaddox** [comment]
pinging him will do nothing, sry but thats the truth, even if he hadn´t ddos protection you would need some tools

**Comment by ShutUpPvP** [comment]
we just need to make him unable to download the files somehow

**Comment by juanpedrolopez220** [comment]
yes, but i dont know how... xd

**Comment by plowzey** [comment]
Nah, these are temporary solutions guys give up on the whole ddosing him.

**Comment by juanpedrolopez220** [comment]
so how can we do it

**Comment by TMaddox** [comment]
trace and visit ;)

**Comment by lailaps** [comment]
Guys, he is behind Cloudflare, to protect his IP.
You have nothing to attack.
even Cloudflare IP Resolver doesn't work properly.

**I think the only way is that Ar1i protect the Source Code and he should contact Paypal!
The guy is asking for donations via Paypal for a project he doesn't own.**

That's the only chance, because almost no one will donate via. Bitcoin or Paysafe.

There is no other chance in this case, I am sorry.

**Comment by ShutUpPvP** [comment]
Well, a possible thing would be a private download where only some ppl have acess to right?  but there would be problems like a whole lo of ppl not be able to download, and maybe the "thief" is under us if u know what i mean

**Comment by TMaddox** [comment]
@lailaps if you get his domain deactivated for wrong use it wold help:
write to: abuse@resellercamp.com this is where he rents domain and server

**Comment by juanpedrolopez220** [comment]
but he can use the bot bc de build are aviable or not?

**Comment by ShutUpPvP** [comment]
Guess so

**Comment by lailaps** [comment]
**@TMaddox** Yeah, that's a good idea too! Hope they care, but he will just make another service who doesn't care about something like this.

**Comment by ShutUpPvP** [comment]
Well, new build is working atleast. Hope this guy gets removed :P

**Comment by TMaddox** [comment]
@lailaps the only one i got up to now if we stay legal

**Comment by TMaddox** [comment]
ah and dislike all (3) of his vids on youtube

**Comment by lailaps** [comment]
**@juanpedrolopez220**

Please read something about Cloudflare, before posting!
...and btw. you would need many thousand people to ping that website ^^.
Forget about old YouTube videos you may have seen in the past!

**Comment by juanpedrolopez220** [comment]
one question that is not related to this topic, which level are you in pokemon go?
And sorry of my english bc im spanish

**Comment by lailaps** [comment]
Maybe the idea to contact YouTube isn't as bad.
They are very strict about copyright issues!

**Comment by TMaddox** [comment]
good idea but that should be done by @Ar1i, because he is the owner and so on

**Comment by djdomrep** [comment]
already reported his channel to youtube. i think would be helpful if many people report him.
so he could get banned not only because of copyright issues also because of the mass of people he is insulting

**Comment by skillize** [comment]
Ar1 should make encrypt CRC check. BUT at this point no one could improve The bot
