### ISSUE TITLE
some pokemon wont autotransfered

### ISSUE THREAD

**Issue by Juiche** [Ar1i/PokemonGo-Bot#489]
magikarp
goldeen

wartortle
...

**Comment by crxvtec** [comment]
true i dont know why...i have to much pidgeys

**Comment by lailaps** [comment]
**@crxvtec**

Yes, me too and  many many Zubat!
If I come back after some hours my Pokemon Inventory is always full. :-(

**Comment by crxvtec** [comment]
@lailaps 

Do u resolve that? i dont know where the prob is... :( lol

**Comment by Ar1i** [comment]
Disable hold pokemons to evolve

**Comment by Juiche** [comment]
i double checked it, no checked on "not transfer list" except for pikachu, since i wont transfer my starter

**Comment by Juiche** [comment]
yes i leave that option unchecked, still, got doubled pokemon. 
yes i leave 1 on max duplicate pokemawns

**Comment by crxvtec** [comment]
the console says i have 1xx's pokemons to envolve and i dont have any sellected on settings

**Comment by crxvtec** [comment]
@Juiche  

same problem...i dont know what is it

**Comment by Juiche** [comment]
go download the latest version, there some fix about iv, that maybe affect and fix problem.

**Comment by SlightlyNoobish** [comment]
doesn't work, i tried 85% and only 100CP everything unchecked and i still collect randoms

**Comment by lailaps** [comment]
Yep, tried it too with latest version.
After maybe 2 hours my inventory is full with Zubat, Weedle, Caterpie and terrible Pidgey.
They never get transferred automatically, even if I only want to have 2 of them.

Is it maybe a problem, that I checked the box for german names and in the inventar window are always the english Pokemon names?

**Comment by Juiche** [comment]
yeah me too.
