### ISSUE TITLE
Pokevision Problem

### ISSUE THREAD

**Issue by Brojo67** [Ar1i/PokemonGo-Bot#490]
I've noticed when the bot uses pokevision it sometimes skips the pokemon without actually catching it. For instance, the bot will say Pokevision: A (blank) pokemon has been spotted. Trying to catch. And then right after that it will go onto something like moving to another pokemon without catching that pokemon or moving to a pokestop. Is there anyway I can prioritize pokevision encounters, especially for rare pokemon like dratini, electabuzz, etc?

**Comment by Juiche** [comment]
yeah, it moved onto next pokevision location, before get to current one, as soon as pokevision detect new location of pokemon in area.

**Comment by tarek1652** [comment]
same

**Comment by LoffeNcs** [comment]
Yeah i think this is a common issue since i think everyone is experienceing it.

**Comment by ShutUpPvP** [comment]
Yes, i saw that too. Sometimes it works tho.

Btw, so... i mostly use the speed to get around quickly, like i saw a Dragonite spawning, made my speed 300kmh and ran there like a mad man, but he is too fast than, means he just runs 1km farther than he needed to and blaaaa.
What im trying to say is, is there a command that makes me adjust my speed while in the console?

**Comment by Juiche** [comment]
```
Google
mail@gmail.com
password
-1,276544
116,833972
0
**100**  <---try changing this?
5000
True
True
1
False
499
```


5000
1
False
False
False
89
True
False
True
`

**Comment by ShutUpPvP** [comment]
need to try taht later, anyone else got a error "pokemonbox full" or something like that, even if i only have 240/250

**Comment by Juiche** [comment]
90/250 ..not yet
