### ISSUE TITLE
Max IV to transfer?

### ISSUE THREAD

**Issue by ShutUpPvP** [Ar1i/PokemonGo-Bot#494]
So, i was wondering since quiet some time now what the Max IV to transfer means, and if it even works properly.
Its 90% for me, but the bot keeps all percentages, not just all above 90%
Bug or me being stupid? xD

**Comment by Ar1i** [comment]
Probably the CP is higher then 999?

**Comment by kevinf100** [comment]
It something along of lines of this its set to.
`If (CP >= CPKeepAmount || IV >= IVKeepAmount || sameAmount > keepSameAmount)`
Set the CP to a higher amount if you want less to keep.
It will only start to transfer when you hit you max dupe cap as well.
Any pokemon that meets the Max CP or IV will not be transfer even if you hit the cap you set it.

**Comment by ShutUpPvP** [comment]
ahhh, okay thanks :)

**Comment by SlightlyNoobish** [comment]
I set CP to 100, IV to 85 and 1 extra pokemon, but it doesn't work

please look into it
