### ISSUE TITLE
old pokemon list layout

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#496]
any way we could get the old layout back much cleaner and easier to see/read? or an option that shows the detailed verison "new layout" or basic layout "old layout"

**Comment by Ar1i** [comment]
Uhm, what do you cant read/see in the list?

**Comment by OGcpalm** [comment]
hmm I don't know how to explain I think its just I'm used to old layout I'm sure I can get used to this one

**Comment by plowzey** [comment]
The new one is better has lots more detail.

**Comment by Ar1i** [comment]
^this, thinking that too

**Comment by FrancYescO** [comment]
@Ar1i setting 
                listView1.View = View.LargeIcon;
with a combobox probably is enought to get the old layout 
also idk if you noticed but you need to replace "{3}-{2}-{3}" to  "{1}-{2}-{3}" was my mistake
