### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by DemonBytes** [Ar1i/PokemonGo-Bot#497]
The last SVN Update brought some errors... What is that?

**Comment by Ar1i** [comment]
Source removed, cause a guy i copying my code, and is giving it out as his own... so build only for some days..

**Comment by DemonBytes** [comment]
so where can we get latest updates then? :/

**Comment by ShutUpPvP** [comment]
Whats the difference?

**Comment by Ar1i** [comment]
https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only

I wont put Source Updates online for some days.

**Comment by ShutUpPvP** [comment]
So, im a scrub at that. What does the source do?

**Comment by DemonBytes** [comment]
Well thats actually pretty sad. Can i contact you somehow privately?

**Comment by DemonBytes** [comment]
or you cantact me in skype at: disruptor88
i could make you an offer i guess..

**Comment by DemonBytes** [comment]
or at least email me at galeph@live.de .. rly need to talk...
