### ISSUE TITLE
Console.exe cant be unpacked

### ISSUE THREAD

**Issue by Synthek** [Ar1i/PokemonGo-Bot#499]
C:\Users\Florian\Downloads\Latest Build - 31.7 01.15.rar: Konnte C:\Users\Florian\Desktop\Neuer Ordner\PokemonGo.RocketAPI.Console.exe nicht erstellen.
!   Zugriff verweigert
Pls help me

**Comment by Ar1i** [comment]
Uhm, something is blocking it probably

**Comment by Synthek** [comment]
i used the older version and all was fine now i cant use anything cause this console cant be unpacked

**Comment by Synthek** [comment]
you have an idea to get this console?^^

**Comment by Ar1i** [comment]
Using Windows Defender? Try to disable it..

**Comment by Synthek** [comment]
no i have avira

**Comment by Ar1i** [comment]
Try to restart your pc :p

**Comment by Synthek** [comment]
i will try it5 min i will be back

**Comment by Kelendris** [comment]
Arli ich glaube dem gehört die pokecrot seite https://www.facebook.com/NiXoN.II.2012/

**Comment by Synthek** [comment]
ich habe gerade eben erst erfahren das es sowas wie das hier überhaupt gibt also quatsch nicht Kelendris

**Comment by Synthek** [comment]
oh du meinst wen ander sry^^

**Comment by Synthek** [comment]
Arli ich habe das aus probiert das funzt immer noch nicht

**Comment by Ar1i** [comment]
Lad mal die neuste Version runter, wenn es nicht geht.. liegt es wohl oder übel an dir ://

**Comment by OGcpalm** [comment]
honestly avira is not the best anti virus software false flags a lot of stuff and even with exceptions added it will cause problems I highly recommend eset & malwarebytes combo

**Comment by Synthek** [comment]
mein pc sagt das der zugriff verboten wird wie kann ich das umgehen hab den neusten bot gerade geladen

**Comment by Synthek** [comment]
der vorherige funktionierte ja auch

**Comment by Synthek** [comment]
XD lol funzt wieder scheiß pc der will mich wohl veräppeln danke und geile sache
