### ISSUE TITLE
Wegfindung

### ISSUE THREAD

**Issue by Skeec** [Ar1i/PokemonGo-Bot#50]
Hey Ar1i

wie hast du die Wegfindung implementiert?
Habe derzeit das Problem, dass der Bot sich immer eine ungünstige Route auswählt.
Eventuell können wir das optimieren würde dir meine Hilfe anbieten.

Liebe Grüße
Skeec

**Comment by Ar1i** [comment]
Schau dir die Navigation.cs an :)!

**Comment by Skeec** [comment]
Aii
