### ISSUE TITLE
PTC servers

### ISSUE THREAD

**Issue by plowzey** [Ar1i/PokemonGo-Bot#500]
Is it just me that is having problems with PTC servers?

**Comment by lailaps** [comment]
I only have PTC-accounts and they are working/farming with ~ 32.000 EXP/Hour.

**Comment by Draken1212** [comment]
No me too

**Comment by Draken1212** [comment]
At my mobile Phone i can login but the Bot can't

**Comment by OGcpalm** [comment]
Logging in fine on phone and bot

**Comment by Draken1212** [comment]
with Google or PTC?

**Comment by LoffeNcs** [comment]
I am running 5 bots both PTC and Google, they have been working fine for the last 48 hours straight

**Comment by Draken1212** [comment]
so what is the Problem by us :D

**Comment by plowzey** [comment]
My google acc works but ptc doensn't i'm in the UK

**Comment by Draken1212** [comment]
Germany

**Comment by lailaps** [comment]
My PTC works well in Germany.
But I am not collecting in New York.
New York seems to be more unstable!

**Comment by ShutUpPvP** [comment]
Collecting in NYC and its working fine besides the pokemon box glitch

**Comment by Draken1212** [comment]
Now it works :D

**Comment by plowzey** [comment]
Yeah guys if you have this problem change your farming location - it worked for me.
