### ISSUE TITLE
"ErrorPokemonInventoryFull"

### ISSUE THREAD

**Issue by ShutUpPvP** [Ar1i/PokemonGo-Bot#501]
even with 240/250 i get this error

**Comment by FrancYescO** [comment]
are you sure your list is reloaded and update?

**Comment by lailaps** [comment]
I have the same problem, some Pokemons are not transferred automatically, even if they should.
I have to do manually after some hours.

**Comment by crxvtec** [comment]
and mine wont transfer some weak pokemons...i have to much pidgeys, weedles, zumbats... i wont cheked nothing to keep, and have check transfer option and keep only 1 pokemon.

**Comment by lailaps** [comment]
**@crxvtec**
Yes, I have 100% the same small problem!

**Comment by ShutUpPvP** [comment]
So, i have a box with 241/250 pokemon, reloaded it and stuff, i send one pokemon away, i can catch another one again, so it may just be a visual glitch

And if we mean the same here, the setting where u can set a %perfection and a max lvl, its kinda hard to understand :)
Should be Minimum lvl to keep and minimum perfection in % to keep
Also it doesnt work properly right now :)

**Comment by lailaps** [comment]
My inventory is always full with 241/250.
Just checked it on some accounts.

**Comment by Ar1i** [comment]
Will take a look, if you open the handy app its full there?

**Comment by crxvtec** [comment]
yes for me

**Comment by Ar1i** [comment]
Then its a stats bug will take alook later

**Comment by ShutUpPvP** [comment]
@Ar1i Any idea why its not showing the amout of pokemon in the box yet ar1i?

**Comment by vrenzz** [comment]
@Ar1i im sorry but this is not fixed with the new update right ?? or it already fixed ??
