### ISSUE TITLE
Req: Rename pokemon w/ high IV

### ISSUE THREAD

**Issue by elijahstone** [Ar1i/PokemonGo-Bot#502]
I was using other bots and had them set to rename my pokemon like a 98% IV Arcanine to "Arcanine_98" so that you could see the pokemons IV at all times in-game or in the bot.

**Comment by Ar1i** [comment]
thats a good idea, will put that in tomorrow going to sleep now!

**Comment by yusuf541** [comment]
have nice dream ^^
btw its nice if we can sort pokemon by IV in List GUI  :)

**Comment by stormlolz** [comment]
Good idea ! I make this

So maybe use a random separator to be more safe, or ask the separator which the user want use ?

- / _ | / \ # % $ £ * [] ()
