### ISSUE TITLE
100% IVs not obeying sorting rule

### ISSUE THREAD

**Issue by UserWest** [Ar1i/PokemonGo-Bot#505]
![100](https://cloud.githubusercontent.com/assets/20710512/17273858/ce0897a6-5693-11e6-8555-59a2f2e8f18b.png)
Pokemon with perfect ivs appear at the bottom of the list when sorting good ivs to the top. It probably seems like not a big deal but when i clear out my pokemon I select everything below a certain percentage and don't bother looking at what they are.

**Comment by Ar1i** [comment]
Will take a look at it tomorrow

**Comment by guzdank** [comment]
its not a bug, just click wher it saids, <IV A-D-S and it will be fine from less to highest

**Comment by UserWest** [comment]
Guzdank, it automatically sorts ivs of 100 to where 10 would be when sorting by IVs. If you sort good ivs to the top then 100 will appear at the bottom and if you sort good ivs to the bottom then 100 will appear at the top. This is why i included Screenshot evidence to prove that they were being sorted in a proper method, if you notice in the picture provided the pokemon are being sorted by IV percentage descending, you would need a 100% IV pokemon to replicate this because up to 99 works in the correct fashion.

**Comment by guzdank** [comment]
ok

**Comment by southparkkids** [comment]
Just curious, how do you get your gui to look like that UserWest?

**Comment by yoyos** [comment]
Just change your windows theme and all default skins will be changed @southparkkids

**Comment by UserWest** [comment]
Yoyo is correct, I use a custom theme that I made myself, if you'd like to try it out I'd suggest you start by looking into 3rd party themes and learn from there.
