### ISSUE TITLE
Erorr While starting bot

### ISSUE THREAD

**Issue by squv** [Ar1i/PokemonGo-Bot#512]
![help] (https://i.gyazo.com/2392cc6f4e04d4d0adfde7ca1bccc866.png)

happens when i login

**Comment by abdellahaski** [comment]
I'm getting the same thing now

**Comment by ShutUpPvP** [comment]
Probably fixed until now? So #closed?

**Comment by Ar1i** [comment]
Should be fixed. If not open a new Issue
