### ISSUE TITLE
the fake site

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#515]
i have tried all possible means to bring down his site it seems it has worked and his site is down now. If you can start adding source codes again it will be great for ur fellow followers. thanks in advance.

**Comment by NWExKraken** [comment]
its back up again

**Comment by NWExKraken** [comment]
isn't it also illegal? if there's anything i can do to help protect the bot let me know.

**Comment by lailaps** [comment]
If the website is hosted by OVH (Canada) it would be very easy to take it down, **BUT** it's illegal.
Doing illegal things to stop illegal activity is always a bad idea!

We are the good guys, even if we could be bad!

**Comment by arcestia** [comment]
i hate this people they still other source too
hopely help to beat this guy https://www.facebook.com/NewMessa.Harianto

**Comment by Ar1i** [comment]
#530 one thread is enough tho! :p But thanks for this awesome support!
