### ISSUE TITLE
Himmihbeere

### ISSUE THREAD

**Issue by Kelendris** [Ar1i/PokemonGo-Bot#516]
Can you make the hack to use himmihbeere only for rare pokemons ? alltime i have nothing.

**Comment by ShutUpPvP** [comment]
I'd set the bot to 5km range with 60-80 kmh for 20minutes and let him farm central park pokestops.
Set the bot like this:
-"Pokemons to not catch, just click the "select all" button
-60-80kmh with 2km range
-Set max amount of resberrys to 100 or more
Than just let him run for 20 minutes and u should be fine.

**Comment by Ar1i** [comment]
^this.
