### ISSUE TITLE
New serverstatus message in latest update:

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#517]
Can't get serverstatus from: https://go.joas.com/status

I only get this message with the latest version, what is it?

**Your connection is not secure
The owner of go.joas.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.**

Why does the bot tries to connect to that site?

**Comment by rlmrso** [comment]
Same here

**Comment by cirnolp** [comment]
That site is used to get the online status of the Pokemon GO servers.

**Comment by Ar1i** [comment]
Will remove it yesterday, the Status worked great lol

**Comment by ShutUpPvP** [comment]
Could be niantic, http://www.techinsider.io/creator-of-pokemon-go-on-pokevision-cheating-in-the-game-2016-7

Even if its working fine for me here.
