### ISSUE TITLE
[BUG] Pokemons got duplicated (Latest version)

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#518]
I don't know, where I clicked inside the window, but all Pokemons got duplicated a few times.

I had to reload manually to switch back to correct view.

Btw. is it possible, that we can change the window size, like before?

**Edit: Reason for this is, if you click: Reload every 60 sec. ==> Auto reload function!
Instead of correct reloading, everything is duplicated!**

So the auto reload function is not working properly, manual reload works!

**Comment by SpectraOne** [comment]
Bug confirmed. I have the same problem.

**Comment by hauj12123** [comment]
me2

**Comment by stormlolz** [comment]
confirm when you click auto reload

**Comment by Ar1i** [comment]
Fixing that later.
