### ISSUE TITLE
Additional functions (enhancement)

### ISSUE THREAD

**Issue by SpectraOne** [Ar1i/PokemonGo-Bot#519]
Hello,
thanks for your work. Maybe you can add this functions.

An GUI where the inventory can be changed during runtime (number Pokéballs, razzberry, ...).

And please show the inventory items in the log (all 2 mins or in one Row to save space in the log console):

Pokeballs:
Great Ball:
Ultra Ball:
LuckyEgg:
RazzBerry:
Potions:
...

**Comment by Steve12341** [comment]
I really like this idea. My Inventory is always full so it would be nice to be able to  change it as it goes
