### ISSUE TITLE
GUI Title

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#522]
We can't have all informations of the GUI title

![image](https://cloud.githubusercontent.com/assets/20703341/17275168/a0378128-56fe-11e6-8d73-6f7f12e8ffd7.png)

Propose to change that : 
Level xx -> lvlxx
Exp/Hour -> xp/h
Exp -> DELETE
Delete space in the xp progression
Delete some space

Maybe like this we can see pokemon/hour? 17 char gain

So:

Name lvlXX-(20000/30000|84%)| Stardust: xxxxx| xp/h: xxxxx| pokemon/h: xxxx

**Comment by DevPXL** [comment]
Yea i see that Problem i will Fixed That

**Comment by Ar1i** [comment]
Fixing right now, pushing the update then

**Comment by stormlolz** [comment]
Don't work

1.0.4.6

![image](https://cloud.githubusercontent.com/assets/20703341/17276616/71739efa-572e-11e6-8c5a-2e6899cd3ba1.png)
