### ISSUE TITLE
Where is the forum?

### ISSUE THREAD

**Issue by Rijadez** [Ar1i/PokemonGo-Bot#524]
Sorry, but I m a little bit stupid in the morning, you have written that I should look in the forum, but where is it?

**Comment by wegweisen** [comment]
I think he means Reddit maybe?

**Comment by Rijadez** [comment]
and where is this, can you post a link pls?

**Comment by Logxn** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
