### ISSUE TITLE
PTC server offline

### ISSUE THREAD

**Issue by ondrej12345** [Ar1i/PokemonGo-Bot#526]
Are you facing also this issue ? I can login via phone. It was working 6 hours before for me.

![ssss](https://cloud.githubusercontent.com/assets/20751491/17275548/4ef3fbe4-570c-11e6-800a-5c73feef5b02.JPG)

**Comment by alexhart123** [comment]
i'm getting the same problem although google servers are still up

**Comment by ShutUpPvP** [comment]
No, working fine here (Germany) bot in NYC Central Park.

**Comment by alexhart123** [comment]
^is your login a google or a PTC?

**Comment by ondrej12345** [comment]
Google also works for me, PTC is down.
