### ISSUE TITLE
problem with number of pokemons

### ISSUE THREAD

**Issue by Meowrouane** [Ar1i/PokemonGo-Bot#527]
Hello

i dont know it is how it works around here, just created the account to contact you

the bot start showing "full pokemon inventory" error at 246/250 pokemons

thank you

**Comment by ShutUpPvP** [comment]
Its a bug, already listed.
It just shows u a wrong amount of pokemon in ur inventory, its full not 241/250.
Just delete some pokemon manually. :)

**Comment by Meowrouane** [comment]
thank you sir

another question (that all newbies ask) is there any "best" configuration? or is it all about luck ?

I mean hearing people talking about 130K/h of experience and having a 23K/h actually is a good enough reason to ask

**Comment by ShutUpPvP** [comment]
So, i experienced setting the range of the bot to 2000m with 70kmh on a VERY populated area like the central park is pretty good, 200+k per hour for me.

**Comment by Meowrouane** [comment]
So my decision of setting the range to 50km in Sidney was not that wise, thank you sir

by the way, where is that park located at ?

**Comment by ShutUpPvP** [comment]
So, "normally" the bot WALKS to the new location.
I would suggest u just farming where u are right now, if u have big pokemon spawns there, but idk since pokevsion got downed by niantic.
The park is set as the default start.
Coords: 40.767445685,-73.970697559

**Comment by ShutUpPvP** [comment]
Since even after the potential "nerfs" to Vaporeon/Aquana i'd still call it "Rainer" and let it evolve it to one.

**Comment by Ar1i** [comment]
Couldnt find the Bug atm, will look deeper in it!
