### ISSUE TITLE
it only spawns electabuzzes

### ISSUE THREAD

**Issue by mastersweg** [Ar1i/PokemonGo-Bot#529]
i have version 1.0.3.2 i im correct and it caught a lot of electabuzzes already so i checked pokemon not to catch i checked electabuzz and now the only pokemon hes spawning are electabuzzes

**Comment by ShutUpPvP** [comment]
U sure u didnt just check only catch electrobuzz?

**Comment by yoyos** [comment]
https://twitter.com/yoamei/status/759056516146077696
