### ISSUE TITLE
Stops Transferring of lows + Bugs inventory

### ISSUE THREAD

**Issue by FrozGR** [Ar1i/PokemonGo-Bot#53]
It stops transferring the lower pokemons and it bugs .. inventory goes full.

![gelaw](https://cloud.githubusercontent.com/assets/12578906/17120504/69675cc2-52d5-11e6-8abd-90378094d711.png)

I had to open an older version, in order to activate transfer to pokemon i had more than 4 times.. it was so bugged it would even keep more than 80 x 10CP ~ 350CP pokemons..

After i loaded an earlier version... :8ball: 
![a75465d3c95e61f1c0df8e60dd466f5f](https://cloud.githubusercontent.com/assets/12578906/17120831/a1ba989e-52d7-11e6-89a9-3a046ee85505.png)

**Comment by Ar1i** [comment]
Edit the Settings, that would help.

**Comment by FrozGR** [comment]
No it does not. With the same settings on previous versions it transfering normally.. with the new version it keeps 10CP pokemon. :/

Tested it with many changes.
