### ISSUE TITLE
i want to know a couple of thimgs 

### ISSUE THREAD

**Issue by Bikkstar123HD** [Ar1i/PokemonGo-Bot#533]
how can i change the default location in the bot 

and also what are the perfect speed and distance to have high XP gain and also not get soft banned 

i signed up just for u guys keep up the good work u are helping alot of people thanks and have  a great day

**Comment by ShutUpPvP** [comment]
Change location: 
-Click "Set Location" and set it where u want it to be, than set it to 30kmh and 15m range and it will go there you NEED to set the bot to "not catch pokemon (all)" or it will waste all ur pokeballs and the pokemon will run away.
Close it when the bot is there and start him again with farming settings.
Means, normal speed 50-70 kmh
2-5km range
all pokemon or the pokemon u want to catch, 2km range with 70kmh and auto evolve with xp boost is around 200-300k xp/h

**Comment by Ar1i** [comment]
^this. Next time use the Forum please! :)
