### ISSUE TITLE
did not visit pokestop to get pokeball

### ISSUE THREAD

**Issue by hklkf200553** [Ar1i/PokemonGo-Bot#534]
the pokeball are empty afte centain of catch , and it dont refill by visit poke stop 

already is the newest build 

or i am wrong on setting ? (all item setting i was unchange ) 

thank you

**Comment by Ar1i** [comment]
Uhm probably your Settings are wrong, make a screenshot of it please

**Comment by hklkf200553** [comment]
![error](https://cloud.githubusercontent.com/assets/20752594/17276038/ec62ac9e-574e-11e6-902d-6d9c36a6eb70.png)

password / account information removed , try to adjust item amount but seems not work

it found pokestop nearby and also show distance towards it ,but visit pokestop and receive item action are missing

**Comment by hklkf200553** [comment]
or the speed was too high ?

i got other similar bot will reduce speed while near the pokestop (not sure just showing fake text or it does reduce speed ) and that one work. actually i like this one better for managing pokemons i got  already

**Comment by bigwarboy** [comment]
I have the same problem :/ ^^

**Comment by ShutUpPvP** [comment]
Let the bot farm for some time, make a tick in the box that says
Pokemons to not catch "select all"

**Comment by ShutUpPvP** [comment]
also i would set the range down to 2-5km

**Comment by hklkf200553** [comment]
enabled not catch all 
range = 5000m , 10 km/h 

now it keep skiping pokemon but still no poke stop information or visit pokestop  @_@

**Comment by bigwarboy** [comment]
jop i think we have to wait for a update or fix :DD i have the same problem and it doesnt work O.o

**Comment by Ar1i** [comment]
Change the Location! Tokyo Disneyland : 35.633511709084274,139.87992525100708

**Comment by bigwarboy** [comment]
i am in Tokyo Disneyland but it doesnt work .. hmm

**Comment by bigwarboy** [comment]
it works Thx! ^^
