### ISSUE TITLE
[Suggestion] Minimum lvl/%perfection to keep pokemon

### ISSUE THREAD

**Issue by ShutUpPvP** [Ar1i/PokemonGo-Bot#535]
Is it possible to make a cap for pokemon lvl and %tages.
For example: The bot caught a lvl 20 pidgy with 12% perfection, could u make a setting that automaticaly sends away pokemon below a threshold.

**Comment by Ar1i** [comment]
It already sends away if its under % perfection?

**Comment by ShutUpPvP** [comment]
Unfortunately no, or my settings are wrong (well its default ones)

It keeps 11% Pokemon with lvl 64

**Comment by yoyos** [comment]
lvl 64 ! You farmed like hell !

**Comment by ShutUpPvP** [comment]
Yea... well, as long it doesnt send away my 2 2k vaporeon and arcanine :3

**Comment by ShutUpPvP** [comment]
Yes it does @Ar1i BUT, it starts at 3 pokemon means i always have 3 low lvl pokemon that take up space in the inventory.
