### ISSUE TITLE
One last thing for the pokemon list

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#537]
Really, when I saw the new Pokemon List I was in love.
It's great and the IV % and all other date is just awesome and incredible. Thank you for that.

Maybe a last add on: 
Be able to change the name.
For example I have an eeve of 98%. 
I would love to let this pokemon evolve, but I want a specific one. 
This means I have to change the name -> it would be great if the bot could do that (and I fill in what name it should have).

Thanks for developing this great bot!!!

**Comment by ShutUpPvP** [comment]
You can also just log in with the gps turned off and rename it :)

**Comment by Ar1i** [comment]
That wont work everytime with Eeve, so thats probably useless.. rename it by yourself!
