### ISSUE TITLE
is it possible to add manually poke catch commands feature in console?

### ISSUE THREAD

**Issue by captainting** [Ar1i/PokemonGo-Bot#539]
like for an example of typing 41.9139634197,-87.6627752991 <porygon> , teleporting catch and back to where it was farming at,etc, its because pokevision downs and nowdays its getting harder to hunt perfect pokemons, thank you if you are reading this creator

**Comment by Ar1i** [comment]
Uhm not planned atm.. need to fix bugs first.

**Comment by captainting** [comment]
wow, thats fast =D
