### ISSUE TITLE
When you want change the position point always show new york.

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#542]
When you want change the position point always show new york instead of last selected point.
So you must have very careful because you can start the bot in new york getting a ban aacount :'(.

**Comment by Bikkstar123HD** [comment]
yeah same here always sets to central park not sure why AR1 keep up the great work u are doing great with tweaks

**Comment by Ar1i** [comment]
Uhm changing that, thanks for the report

**Comment by Xelwon** [comment]
Thanks :).
