### ISSUE TITLE
new tab of sorting in the 'pokemon list'

### ISSUE THREAD

**Issue by d4nlo3008** [Ar1i/PokemonGo-Bot#544]
@Ar1i  hey there,

a new tab in the pokemon list with "**last catch/last update/newest pokémon**" to sort, which pokemon is the newest would be great.

greetings

**Comment by Reefers** [comment]
I'd like to see sorting by their Pokedex Number too, to see a 'family' together for easier evolving via the bot

**Comment by pokerave** [comment]
There is a way to sort it see the one I circled in black? click those it will arrange Name(a-z-, z-a) CP(low-high) etc.
![evolve](https://cloud.githubusercontent.com/assets/20603254/17276204/81fe819e-572a-11e6-9ff6-224541de21a9.jpg)

**Comment by Reefers** [comment]
Yes, I'm saying it would be nice to have Pokedex # as one of the columns.

**Comment by d4nlo3008** [comment]
@pokerave naaah... not this type of sorting. I mean, a sort of the "newest pokemon". Which you catch at least.

**Comment by Reefers** [comment]
sorry if I derailed, just seemed an appropriate thread to add the suggestion based on title instead of a new thread.
