### ISSUE TITLE
new update bug  not collecting pokestops

### ISSUE THREAD

**Issue by Bikkstar123HD** [Ar1i/PokemonGo-Bot#545]
the pokestops run by but the console isnt collecting it .  it sayd next pokestop and moves on to other one and other one but doesnt collect anything from there

**Comment by Ar1i** [comment]
Probably a softban wait some minutes

**Comment by Bikkstar123HD** [comment]
okay let me wait for like 30 mins to restart the console then thanks for the quick reply u the best

**Comment by hklkf200553** [comment]
i remove the old copy and extract a new one , only input account information and now it show up amount of pokestop near by  in yellow letter , and start to collect from pokestop 

work really good and it seems it was the fastest one compare to others i was trying 

also new function are welcome =D 

thumb up for the work

**Comment by Bikkstar123HD** [comment]
thanks for the help but can u elobarate cause the thing u just said is a bit confusing to me thanks anyways and in advance

**Comment by ShutUpPvP** [comment]
This can be closed if its just a softban i guess.

**Comment by Bikkstar123HD** [comment]
yes can be closed it was just a soft ban thanks for the tips and keep up
