### ISSUE TITLE
Pokecrot publisher founded (Plagiarism)

### ISSUE THREAD

**Issue by suabahasa** [Ar1i/PokemonGo-Bot#546]
I have found people who copy Ar1i/PokemonGo-Bot.
His name is Messa Harianto Oktavian https://www.facebook.com/NewMessa.Harianto
And now, he delete all his post about his pokecrot. [spuc3ngine](https://www.facebook.com/Spuc3ngineNetwork/photos/a.938611816170917.1073741828.936931259672306/1205187352846694/?type=3)

I have seen his account from past month, and he make a sense by selling DOTA2 (steam) cheat, actually it deceiving other people

**Comment by Bikkstar123HD** [comment]
great work

**Comment by Oguzcan13** [comment]
https://www.pokecrot.com/

**Comment by Oguzcan13** [comment]
non c'est Ar1i qui copie les autres

**Comment by StyX996** [comment]
Or write him E-Mails. You'll find his E-Mail adress:
http://www.whois.com/whois/pokecrot.com
