### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by blahblah1227** [Ar1i/PokemonGo-Bot#547]
when evolving, it doesn't use a lucky egg. i do have the box checked to use lucky egg when evolving

**Comment by pokerave** [comment]
maybe you don't have lucky egg?

**Comment by Ar1i** [comment]
^this

**Comment by blahblah1227** [comment]
i have 27 of them

**Comment by pokerave** [comment]
Wow 27?. Anyway my bot uses egg when i have them i just used the last one this morning when i evolved.

**Comment by blahblah1227** [comment]
weird. i dunno why mines not working. i manually evolve tho. do you have yours set to auto evolve?

**Comment by pokerave** [comment]
Yes. I have it on auto evolve.

**Comment by blahblah1227** [comment]
maybe thats why yours works. hmmm. so maybe the bug has to do with manually evolving doesn't activate lucky egg but auto evolve does..
