### ISSUE TITLE
can u add egg incubator/hacther ?  (Eier Ausbrüten, automatisch?

### ISSUE THREAD

**Issue by Cloud20xx** [Ar1i/PokemonGo-Bot#549]
Ist das machbar???
Es wäre echt eine Hammer Erweiterung für den bot! :)

Sonst gute Arbeit, mach weiter so, und vielen dank für den Bot. ^^

LG.

**Comment by Titus1987** [comment]
hey Cloud kannst du mir das mit dem update erklären ich weis nicht wo ich Dateien hin packen muss.
und hast du vielleicht auch das Problem das du nicht mehr in Arenen kämpfen kannst und keine pokestops mehr einnehmen kann ? muss ich da irgendwas umschreiben ?

**Comment by Cloud20xx** [comment]
Hey,
also bei mir funktioniert alles einwandfrei.

Lade hier die komplette Zip Datei entpacke es, geh Build Ordner, entpacke den standalone Ordner. und fertig ;´))

Arenen war ich gestern, da hatte ich das Problem auch kurz das du hier schilderst, (dachte erst wäre ein Softban) dem war aber nicht so.

Bin einfach zu nächsten Arena und es ging wieder ^^

nur das Eier Ausbrüten, wenn das automatisiert würde, könnte mach um einiges mehr EP durch den bot Ernten ^^

Hoffe da tut sich was.
lg hoffe hat dir geholfen.

**Comment by Titus1987** [comment]
also muss ich nur den build ordner ändern ?

**Comment by Titus1987** [comment]
was genau ist dieser "stand alone" ordner?

**Comment by Cloud20xx** [comment]
der latest build ordner ^^"
