### ISSUE TITLE
GUI mit Karte / Statusfenster o.ä.

### ISSUE THREAD

**Issue by altobee** [Ar1i/PokemonGo-Bot#55]
Es kam ja schon ein paar mal der Wunsch nach einer Visualisierung des Bots. Vielleicht wäre es den GUI Experten möglich eine Art Frontend für den Bot zu entwickeln in dem man einen Kartenausschnitt mit den Stops sieht und den Bot halt laufen + ein Status Fenster ähnlich dem des CMD's 

Sicherlich nicht 100% nötig aber dennoch irgendwie schöner um nachzuvollziehen wie und wo der gerade herumläuft. Insbesondere wenn man sich mittels Pokevision o.ä. anschauen will wohin man noch müsste / könnte / wollte. 

Ich hab leider keine Ahnung wie hoch der Aufwand hierfür wäre, wenn's zu krass ist Sorry

**Comment by crss** [comment]
Habe dazu den /stats Befehl in der TelegramUtil.cs erweitert. Dadurch gibt /stats mir nun 2 Links aus. Einen maps.google und einen Pokevision. Zumindest ein Anfang ;)

`                if (message.Text.StartsWith("/stats")) // send inline keyboard
                {

                    var usage = "";
                    var inventory = await _client.GetInventory();
                    var profil = await _client.GetProfile();
                    var stats = inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData.PlayerStats).ToArray();
                    foreach (var c in stats)
                    {
                        if (c != null)
                        {
                            int l = c.Level;

                            var expneeded = ((c.NextLevelXp - c.PrevLevelXp) - StringUtils.getExpDiff(c.Level));
                            var curexp = ((c.Experience - c.PrevLevelXp) - StringUtils.getExpDiff(c.Level));
                            var curexppercent = (Convert.ToDouble(curexp) / Convert.ToDouble(expneeded)) * 100;
                            string curloc = _client.CurrentLat + "%20" + _client.CurrentLng;
                            curloc = curloc.Replace(",", ".");
                            string curlochtml = "https://www.google.de/maps/search/" + curloc + "/";
                            string pokevis = _client.CurrentLat + ";" + _client.CurrentLng;
                            pokevis = pokevis.Replace(",", ".").Replace(";", ",");
                            string pokevishtml = "https://pokevision.com/#/@" + pokevis;

                            usage += "\nNickname: " + profil.Profile.Username +
                                "\nLevel: " + c.Level
                                + "\nEXP Needed: " + ((c.NextLevelXp - c.PrevLevelXp) - StringUtils.getExpDiff(c.Level))
                                + $"\nCurrent EXP: {curexp} ({Math.Round(curexppercent)}%)"
                                + "\nEXP to Level up: " + ((c.NextLevelXp) - (c.Experience))
                                + "\nKM walked: " + c.KmWalked
                                + "\nPokeStops visited: " + c.PokeStopVisits
                                + "\nStardust: " + profil.Profile.Currency.ToArray()[1].Amount
                                + "\nCurentLocation: " + curlochtml
                                + "\nPokevision: " + pokevishtml;
                        }
                    }
                    await _telegram.SendTextMessageAsync(message.Chat.Id, usage,
                        replyMarkup: new ReplyKeyboardHide());
                }`

**Comment by altobee** [comment]
das ist schon mal ganz geil :) Danke
