### ISSUE TITLE
No more arena and pokestops without hack ? 

### ISSUE THREAD

**Issue by Titus1987** [Ar1i/PokemonGo-Bot#552]
hey guys ,
i habe Problem that i dont can fight in Arena and took pokestops it is normal? sry for my bad english iam german .

greets

**Comment by pokerave** [comment]
Softban maybe. Wait 30 mins to 2hrs.

**Comment by Titus1987** [comment]
i dont can catch pokemon to :( one try and then they leave

**Comment by guzdank** [comment]
GO NEAR A POKESTOP and spin it and exit it like 30 or 40 times quickly and after you get your objects all done

**Comment by pokerave** [comment]
Yes soft ban. Wait 30 mins to 2hours.

**Comment by ShutUpPvP** [comment]
softbanned yup, dont tp and drive at the same time :P xd

**Comment by pokerave** [comment]
Dont jump country to country or state to state it will get you soft bans.

I do it usually by streets or 1 block so not to get ban.

**Comment by Titus1987** [comment]
ok i try it in 3 hours?

**Comment by pokerave** [comment]
Yup. It should be ok by then.

**Comment by Ar1i** [comment]
Softban try later
