### ISSUE TITLE
Transfer problem 2

### ISSUE THREAD

**Issue by alperemre** [Ar1i/PokemonGo-Bot#555]
Program still no transfer any pokemon

**Comment by ShutUpPvP** [comment]
You need to put a tick in the box for which pokemon u wanna transfer

**Comment by HSMatheus** [comment]
ShutUpPvP what box you mean? pokemons not to catch? I'm having the same problem here

**Comment by alperemre** [comment]
@ShutUpPvP which box ?

**Comment by Ar1i** [comment]
Screen of your Config please

**Comment by ShutUpPvP** [comment]
oh, mb missread that.


Maybe untick the box that says "Keep pokemon which can be evolved"

**Comment by HSMatheus** [comment]
@Ar1i  ![image](https://cloud.githubusercontent.com/assets/15190187/17276701/5b92f328-5707-11e6-8972-bacd66973531.png)

**Comment by alperemre** [comment]
![1111](https://cloud.githubusercontent.com/assets/20747873/17276758/4c452510-573b-11e6-9bc4-7f5752362bef.jpg)
