### ISSUE TITLE
Transfering item Bug

### ISSUE THREAD

**Issue by ElementV2** [Ar1i/PokemonGo-Bot#557]
Im 355/350 and its not transfering any item ;) plz correct this bug

**Comment by ShutUpPvP** [comment]
U sure u didnt just tell the bot to keep x amount of each item?

**Comment by ElementV2** [comment]
nop i let the default things for the item but it seems to be ok now i dont know for a few minutes all the pokestop didnt get me any item just XP ^^

**Comment by ShutUpPvP** [comment]
weird.. well, as long it works again :)

**Comment by Ar1i** [comment]
Hmm probably Server error closing this then
