### ISSUE TITLE
Restart Bot nach 30 Minuten ohne Pokestop

### ISSUE THREAD

**Issue by crss** [Ar1i/PokemonGo-Bot#56]
Habe den Bot von Berlin nach New York fliegen lassen. Dabei ist aufgefallen, dass er alle 30 Minuten folgende Exceptions liefert und sich dann neu startet.
![mstsc_2016-07-26_11-00-07](https://cloud.githubusercontent.com/assets/19149356/17132006/2b820fce-5320-11e6-9e93-2eaa100e4603.png)

**Comment by Ar1i** [comment]
Einfach ignorieren voerst, und du willst den bot echt 23.000 sekunden laufen lassen? ^^

**Comment by crss** [comment]
ja, möchte ja den flug nach NY simulieren ;D
