### ISSUE TITLE
NEW FEATURE CHOOSE IV OVER CP (TRANSFERING)

### ISSUE THREAD

**Issue by KingTarek** [Ar1i/PokemonGo-Bot#562]
Can you please put in a filter where you can choose IV over CP!!!!!!!

**Comment by ElementV2** [comment]
U just have to put on CP to transfer 0 and IV to transfer 90 or +

**Comment by KingTarek** [comment]
@ElementV2 are you sure that this will help? because I am scared that more Pokemons will be transfered

**Comment by ElementV2** [comment]
thats what i do and i have like 5 Eevee low CP but 90%+

**Comment by KingTarek** [comment]
okay thx

**Comment by rokuon** [comment]
@ElementV2 that doesnt transfer any pokemon at all with ur setting
