### ISSUE TITLE
[Error] 

### ISSUE THREAD

**Issue by Kurimatzu** [Ar1i/PokemonGo-Bot#565]
![9b07d8393d3c444c804204110659ec5e](https://cloud.githubusercontent.com/assets/9270074/17276414/4cf1adb2-56ff-11e6-8e88-a7ba372ebb7d.png)

**Comment by 12348766754** [comment]
At the moment I have the same error(s)

**Comment by pokerave** [comment]
there was a thread like this before.

**Comment by 12348766754** [comment]
@pokerave  able to link me to it? I could not find it :(

**Comment by Ar1i** [comment]
Will take a look later, probably to much requests for the Server..
