### ISSUE TITLE
force unban by hand

### ISSUE THREAD

**Issue by phipsy** [Ar1i/PokemonGo-Bot#566]
hi there.

sometimes I know that I will be softbanned the moment that I start the software, for example when I switch from new york to tokyo. Maybe you can add a button in the gui that does all the stuff I have to do when I make such a switch.

Meaning a checkbox like "Force Unban/Coordination change" that
a) Automatically deletes the LastCoords.txt
b) Starts the 1337 unban method (btw, you miss-spelled "method" here, you have an extra E at the end) at the first pokestops it visits

**Comment by guzdank** [comment]
nice

**Comment by Ar1i** [comment]
Yeah can add a checkbox to auto start it

**Comment by jay-2-rome** [comment]
Definitiv eine gute Idee. Des öfteren wenn ich die Location wechsle fang ich mir nen Ban ein und natürlich tauchen da die geilsten Pokémon auf. Sehr frustrierend :/

**Comment by Meowrouane** [comment]
I got softbanned and I closed the program by error

now I cannot start it 

adding that would be cool
