### ISSUE TITLE
How can I change the location?

### ISSUE THREAD

**Issue by cinek19** [Ar1i/PokemonGo-Bot#568]
If I change the default location the bot starts to walk to the default location, how can I change it?

**Comment by uaeb** [comment]
http://i.imgur.com/vNzNe0c.png

uncheck that checkbox on the gui

**Comment by Ar1i** [comment]
Delete LastCords.txt

**Comment by Ar1i** [comment]
Delete LastCords.txt

**Comment by cinek19** [comment]
Ty guys!
