### ISSUE TITLE
Infinite loop.

### ISSUE THREAD

**Issue by Kurimatzu** [Ar1i/PokemonGo-Bot#569]
![3dfeac84c95f4ad994bf93610ce74c2d](https://cloud.githubusercontent.com/assets/9270074/17276515/574fdbe6-5702-11e6-8a3b-6d877747a94a.png)

Even increasing the moves, continues this infinite loop.

**Comment by guzdank** [comment]
same hapening

**Comment by guzdank** [comment]
try in changing your location

**Comment by ShutUpPvP** [comment]
Probably softbanned, or can u acess pokestops with ur phone/nox

**Comment by Ar1i** [comment]
Change location that is the Problem

**Comment by Kurimatzu** [comment]
@Ar1i 

You could add the function, by giving this error, change the location automatically? (Set the latitude + 50) (longitude + 30)?
