### ISSUE TITLE
MY POKEMON DONT TRANSFER

### ISSUE THREAD

**Issue by KingTarek** [Ar1i/PokemonGo-Bot#571]
MY POKEMONS DON´T TRANSFER MY SETTINGS: CP:0 IV:90

**Comment by 12348766754** [comment]
And how much duplicates?
It's default settings is 3 I think.

**Comment by yoyos** [comment]
It's normal if you put CP MAX to transfert: 0 it will transfert nothing

**Comment by KingTarek** [comment]
@yoyos I want that IV is more important then CP hpw can I do this @Ar1i

**Comment by yoyos** [comment]
put 9999 on CP MAX
