### ISSUE TITLE
new bot package wont work anymore :/

### ISSUE THREAD

**Issue by Euskater2** [Ar1i/PokemonGo-Bot#573]
dont know why

**Comment by Euskater2** [comment]
usersetting is missind, somethjing with is also missing, says the register all the time for 2 ours now while i was trying to fix it xD

**Comment by Meowrouane** [comment]
download back the packet, make sure your antivirus doesn't delete files

**Comment by Euskater2** [comment]
oh this is I think the solution ! thanks bra

**Comment by Meowrouane** [comment]
just create a file call it bot and put all tools there then add it to your exeption list
and even for other games, if and only if the source is trusted, put them there

**Comment by Euskater2** [comment]
still dosnt work http://puu.sh/qkMF3/095911f66b.png

**Comment by Euskater2** [comment]
okei I´ll try. hope this works @Meowrouane

**Comment by Euskater2** [comment]
nothing works .. those two files still missing :/ @Meowrouane
