### ISSUE TITLE
Suggestion: make custom route

### ISSUE THREAD

**Issue by Xelwon** [Ar1i/PokemonGo-Bot#576]
The idea was 
Instead of select one unique location point, can select multiple points ( an array) and do the bot goes for those points in ascending order  and descendig order after. Simulating a more real exit to home and back to it. :). And repeat it every given time. 
Or even do a infinte look joining last point with first.

**Comment by guzdank** [comment]
great idea

**Comment by guzdank** [comment]
if they could do that PokeSniper could be better if added
