### ISSUE TITLE
AFTER I LOGIN?

### ISSUE THREAD

**Issue by squv** [Ar1i/PokemonGo-Bot#579]
![help] (https://i.gyazo.com/2392cc6f4e04d4d0adfde7ca1bccc866.png)

happens when i login

**Comment by monoxacc** [comment]
same here, InvalidProtocolBufferException: http://imgur.com/iWKqog9
Der tag ist an der stelle im Code immer 60, er geht bei MergeFrom() ins default weil 60 nicht definiert ist in der switch und wirft die Exception.
Passiert auch nur auf meinem Win Server, lokal läuft alles. IP ban villeicht?
