### ISSUE TITLE
Question: Will full powerup ban the account?

### ISSUE THREAD

**Issue by Stavtastic** [Ar1i/PokemonGo-Bot#580]
I read somewhere that the powerup from the bot exceeds the limit and bans accounts. Is there any truth to this or can I just max some pokemon?

How does it work?

**Comment by Meowrouane** [comment]
using the bot may bann the account at all

power up by hand, wont you ?

**Comment by Stavtastic** [comment]
that is the choice I want to research.

**Comment by Meowrouane** [comment]
just choose a location with lot of pokemons, bot for 1 week and take 1 day rest then start usnig yur account normally

**Comment by Juiche** [comment]
it would be great if not exceeds limit then.
