### ISSUE TITLE
no appconfig file 

### ISSUE THREAD

**Issue by megaDrummerxxl** [Ar1i/PokemonGo-Bot#584]
there's no appconfig file in the rocket API console. so visual studio can't compile it.

**Comment by Euskater2** [comment]
yeah same problerm here !! :D and usersettings file missing too xD

**Comment by Ar1i** [comment]
Uhm probably forgot i 1 sec

**Comment by Euskater2** [comment]
@Ar1i  ist here where it is missing http://puu.sh/qkPMM/0592771543.png

**Comment by Ar1i** [comment]
fixed
