### ISSUE TITLE
Bot no longer works with ptc accounts

### ISSUE THREAD

**Issue by saahilz** [Ar1i/PokemonGo-Bot#585]
the bot has stopped working with ptc accounts, while it still works ok with google accounts

**Comment by guzdank** [comment]
for me is working

**Comment by guzdank** [comment]
send the error

**Comment by github89023148902** [comment]
I just noticed two of my botting accounts that have been running for about 2 hours got banned.

**Comment by guzdank** [comment]
really?

**Comment by saahilz** [comment]
i am getting this message 
starting Execute on login server: Ptc
PTC server Offline. trying to restart in 20 Seconds

but google accounts works fine

**Comment by guzdank** [comment]
that means the PTC servers are offline try in putting another location and delete the config file

**Comment by saahilz** [comment]
i have checked PTC servers for Europe are online and on my phone i can login on pc account which is weird issue

**Comment by guzdank** [comment]
yes kind off

**Comment by saahilz** [comment]
but great work, one of the best i used till date 
thanks for all the work
