### ISSUE TITLE
IV calculations?

### ISSUE THREAD

**Issue by github89023148902** [Ar1i/PokemonGo-Bot#586]
It seems that the bot, when compared to https://pokeassistant.com/main/ivcalculator is calculating ivs way off, by up to 20% ive noticed.

Can you confirm?

**Comment by yoyos** [comment]
Didn't undestand anything.

Do you have an example ?

**Comment by guzdank** [comment]
you mean that the IV given in the GUI is way off more 20% more or less?

**Comment by yoyos** [comment]
Didn't see any difference on my side, maybe you mis interpreted results from pokeassistant.
