### ISSUE TITLE
[Another suggestion]: Softban unban.

### ISSUE THREAD

**Issue by Kurimatzu** [Ar1i/PokemonGo-Bot#587]
Could add a button that removes the softban?
Currently giving:

![screenshot_1](https://cloud.githubusercontent.com/assets/9270074/17276873/6c843b52-570b-11e6-9ced-5715ac0dfcfc.png)

**Comment by Meowrouane** [comment]
have the same error

Ar1i told us he would add a force to unban check at the beginning, waiting for his new update
