### ISSUE TITLE
Many, many, many , many Suggestions.

### ISSUE THREAD

**Issue by Kurimatzu** [Ar1i/PokemonGo-Bot#589]
Suggestions:
-

- https://github.com/Ar1i/PokemonGo-Bot/issues/587
- https://github.com/Ar1i/PokemonGo-Bot/issues/532
- Egg handling.
- Remove PokeVision support (probably, the pokevision project was canceled.)
- Rename Pokemon
- Choose evolution of Eeeve pokemon.
- Map to legendary pokemons.
- Option to only get Pokemon that you don't have.
- When it doesn't find any near pokeStop, add + 50 latitude/longitude

Bugs:
-
- Fix Eeeve duplicates.
- Fix Pokemons GUI (introduces lag)

Priority:
-
- Option to "force" Disabling the SoftBan.
- When changing location, if it is far away, set the speed to -1 (maximum) to teleport to there, to avoid "Will take 451356464 seconds".
- Fix "got away" (to give that message, automatically the softban is removed.)

Team PokemonGO Bot:
-

- @Ar1i

**Comment by Kurimatzu** [comment]
Update:

-When it doesn't find any near pokeStop, add + 50 latitude/longitude
-Fix "got away" (to give that message, automatically the softban is removed.)
-Fix Eeeve duplicates.

**Comment by guzdank** [comment]
love it

**Comment by Kurimatzu** [comment]
Topic edited for best viewing.

**Comment by mobile46** [comment]
güzel
