### ISSUE TITLE
IV% discrepancy 

### ISSUE THREAD

**Issue by Mouserat1016** [Ar1i/PokemonGo-Bot#597]
I noticed this difference in the IV% this morning.

![pokemongo rocketapi console_2016-07-31_09-22-08](https://cloud.githubusercontent.com/assets/20755356/17277129/40956fca-5701-11e6-97f5-9af6d782dbc8.png)
![pokemongo rocketapi console_2016-07-31_09-21-59](https://cloud.githubusercontent.com/assets/20755356/17277130/4098f1ea-5701-11e6-9b0f-25a9dc9ec118.png)

**Comment by Ar1i** [comment]
Uhm yeah, cause of the update yesterday, before IV was wrong some times..
