### ISSUE TITLE
Move radius problem 

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#599]
Hi,
I think that there are some problems with the move radius it's not accurate I'm using a 50000 meter move radius and it's just going to 2 nearby pokestops (max: 2km away) and it's returning back the default location and I am sure that there are many pokestope 5 km away 12 km away there are approximately 20 pokestop 
here is a screenshot if it could help.

![snip_20160731154748](https://cloud.githubusercontent.com/assets/10819089/17277260/564320f8-5736-11e6-963b-5bacba6befea.png)

**Comment by Ar1i** [comment]
Choose a different location

**Comment by abdellahaski** [comment]
the same thing with a low pokestop density location
