### ISSUE TITLE
Problem beim starten mit script

### ISSUE THREAD

**Issue by magiccube007** [Ar1i/PokemonGo-Bot#60]
Ich hab folgendes problem um die neuste Version per restart script zustarten muss man ja durch das 
-nogui das gui überspringen. Wenn ich das ganze so mache will er sich bei mir über pct einloggen, jedoch benutze ich einen google account. wenn ich das ganze dann ohne das -nogui also mit dem gui starten lass wählt er vorher schon automtisch google aus und nach dem ich dann im gui auf save gedrückt habe geht auch alles, jedoch kann ich ja schlecht nachts immer jede Stunde den save button drücken.
Ihrgendwelche fixes?

**Comment by Ar1i** [comment]
Ja kommt gleich neue Verison.

**Comment by magiccube007** [comment]
danke :D

**Comment by magiccube007** [comment]
wann kommt sie denn?
