### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by rynhrd** [Ar1i/PokemonGo-Bot#601]
I have the same problem when logging in using a Google account. and this applies in all cases bot I used. before Pokemon Go update to version 0.31.0.

![bot](https://cloud.githubusercontent.com/assets/20755620/17277271/fb25f06e-5768-11e6-9d92-2752dffc695a.png)

**Comment by wonderland1995** [comment]
This is the guy that stole the code!!! Look at the user  "messa"

**Comment by rynhrd** [comment]
No, I use a bot pokecrot, the log that is in command!!
![bot](https://cloud.githubusercontent.com/assets/20755620/17277401/27e9e080-576c-11e6-9cb5-47a8347036b9.png)
