### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by 4ndr0id19** [Ar1i/PokemonGo-Bot#602]
When i try to build and run the API in VS 2015 i get an error saying "Source file 'C:\Users\XXXXXXXXX\Desktop\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\UserSettings.Designer.cs' could not be found."  
EDIT: this was directly after getting the update.

**Comment by 3210x** [comment]
You can download missing file here https://www.dropbox.com/s/lqj0z0m1i13ykdi/husos.rar?dl=0
The 2 files goes here 'C:\Users\XXXXXXXXX\Desktop\PokemonGo-Bot-master\PokemonGo.RocketAPI.Console\'
