### ISSUE TITLE
Pokemon List GUI Bug

### ISSUE THREAD

**Issue by guzdank** [Ar1i/PokemonGo-Bot#605]
Maybe its not me but my Pokemon GUI list everytime i click reaload it Bugs or lags and sont reload back and this error code Pops Out 
![error list](https://cloud.githubusercontent.com/assets/20705893/17277454/305c157c-5711-11e6-8c32-72a20e64fe2c.png)

**Comment by Ar1i** [comment]
Cause Pokemon Limits Request, it retrys then! So everything should be okay! :p

**Comment by guzdank** [comment]
ok
