### ISSUE TITLE
2-9 and 100% IVs do not obey sorting rules.

### ISSUE THREAD

**Issue by UserWest** [Ar1i/PokemonGo-Bot#607]
Pokemon with perfect IVs and those with IVs 2-9 do not sort properly when sorting by IVs. 100% will appear lumped in with the tens, 2% will appear lumped in with the twenties, 3% will appear lumped in with the thirties, etc. It occurs to me that the simplest fix would be to change everything to a 3 digit number so that 5% would become 005% and 92% would become 092%.
![100](https://cloud.githubusercontent.com/assets/20710512/17277512/b55c524a-5712-11e6-9fb3-7c2421574753.png)
That is evidence of the sorting not functioning properly, note that IVs are being sorted in descending order and 100% is at the bottom of the list.

**Comment by yoyos** [comment]
It's a sort based on STRING

16 is greater than 10

**Comment by Dexter13425** [comment]
How you can have the black GUI ?

**Comment by UserWest** [comment]
It's a custom windows theme

**Comment by Dexter13425** [comment]
ok great :D

**Comment by Ar1i** [comment]
should be fixed
