### ISSUE TITLE
Pokemon List Deutsch

### ISSUE THREAD

**Issue by EvilBlood** [Ar1i/PokemonGo-Bot#609]
Leider werden die  Pokemon in der Pokemon List auf englisch angezeigt obwohl man die Funktion Pokemon Namen in Deutsch aktiviert hat.

**Comment by jay-2-rome** [comment]
Die werden aber in der Konsole auf Deutsch angezeigt...

Allerdings werden die aber auf Englisch angezeigt wenn man Pokémons bei "not to catch" anhakt...

**Comment by Ar1i** [comment]
should be fixed

**Comment by EvilBlood** [comment]
Leider werden die Pokemon weiterhin in Englisch angezeigt.
