### ISSUE TITLE
GUI writes nonselected Pokemon in Evolve/noCatch/noTransfer.ini at next start

### ISSUE THREAD

**Issue by stpdlsr** [Ar1i/PokemonGo-Bot#61]
Pokemon selected for one of these lists, Evolve/noCatch/noTransfer, are selected for other lists as well when starting/restarting the .exe again. 
At first start: http://i.imgur.com/GEVOIyS.png
At next start: http://i.imgur.com/YbV4tfL.png

**Comment by petravic** [comment]
Fixed in new pull request.
