### ISSUE TITLE
Issue while connecting

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#610]
That problem isn't yest resolved when I try to connect I get some errors here is the logs:

![snip_20160731165402](https://cloud.githubusercontent.com/assets/10819089/17277634/851f05c8-573f-11e6-9046-3e00ccf1f17c.png)

**Comment by UltraVLT** [comment]
Up-to-date version?

**Comment by abdellahaski** [comment]
Yeap

**Comment by UltraVLT** [comment]
Well awkward,are you using PTC or google login?

**Comment by abdellahaski** [comment]
PTC

**Comment by abdellahaski** [comment]
I'm using it in a vps is that a problem?

**Comment by UltraVLT** [comment]
PTC login is unstable atm,that may be causing the problem.Have patience

**Comment by abdellahaski** [comment]
But It's working on my pc right now with another ptc account

**Comment by abdellahaski** [comment]
the vps is US based as i'm usin a Us location

**Comment by Ar1i** [comment]
should be fixed
