### ISSUE TITLE
.vs folder

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#611]
who i must put the .vs folder?

**Comment by Ar1i** [comment]
Same Felder

**Comment by stickmick12** [comment]
i doesent have the folder before. Can u make a screenshot who the folder musst se right?

**Comment by stickmick12** [comment]
kannst deutsch schreiben xD dachte wärst engländer

**Comment by Ar1i** [comment]
ist unsichtbar, kannst eig auch ignorieren
