### ISSUE TITLE
Program is keylogging me

### ISSUE THREAD

**Issue by chrisjan123** [Ar1i/PokemonGo-Bot#612]
So when i log on to the bot with my gmail I instantly get keylogged by it

**Comment by Bikkstar123HD** [comment]
woah u sure ???

**Comment by Bikkstar123HD** [comment]
how can u tell that it is being keylogged ???

**Comment by chrisjan123** [comment]
well my oldschool runescape account got hacked this day. strange thing is it happened right after i logged into the bot

**Comment by Ar1i** [comment]
Look at the source wtf why should i share a Virus on github?!
