### ISSUE TITLE
unable to change location 

### ISSUE THREAD

**Issue by saahilz** [Ar1i/PokemonGo-Bot#615]
i am using the latest but is stuck in one location , i have restarted selected a different location but it still defaults back to one location for some reason have no idea why

**Comment by ShutUpPvP** [comment]
u unchecked the box that says something with "Walk back to default location"?

**Comment by Bikkstar123HD** [comment]
and also i m getting quicker soft bans at 25km speed and 3000m range i got soft banned twice after this new update to bot can anyone clear this thanks in advance

**Comment by saahilz** [comment]
how do you know if you are soft banned ?

**Comment by Bikkstar123HD** [comment]
it detects automaticaly

**Comment by saahilz** [comment]
am having no luck with changing location at all, it just goes back to some weird location, and not using the location i am selecting

**Comment by Juiche** [comment]
yes it happens, 

but u can change your lastcoords.txt file in config folder
change the coordinats there with ur current coordinate.

idk why but this works.

**Comment by madpada** [comment]
If you are having problems changing your location, delete the following file in the Configs folder before you want to change locations: LastCoords.txt

**Comment by Ar1i** [comment]
^this
