### ISSUE TITLE
FREE VERSION 

### ISSUE THREAD

**Issue by nickzheng998** [Ar1i/PokemonGo-Bot#616]
Thank you for updating daily. You did great job on this. SAVING MY GAS MONEY A LOT !
I make a donatation for our team. but I still in the free ware. How can i change it from the free one to the full verision software.
	6JK98241MD275891D    cn number for the paypal.

**Comment by Whitely1** [comment]
There is no "full version" its all free, donations are just for the awesome programmers.

**Comment by Ar1i** [comment]
^ this. If you want your money back no problem just tell me!

**Comment by nickzheng998** [comment]
NOPE JUST FOR YOU.

**Comment by nickzheng998** [comment]
NO PROBLEM FRIEND

**Comment by nickzheng998** [comment]
U earned what you did. thank you again

**Comment by nickzheng998** [comment]
you will be back my country soon. but in my china, we have to using vpn to play this game. do i need open vpn to run this software.

**Comment by nickzheng998** [comment]
I  will be back my country soon. but in my china, we have to using vpn to play this game. do i need open vpn to run this software.

**Comment by Ar1i** [comment]
Thank you man! Really much!
