### ISSUE TITLE
Pokevision, has been removed, creators are respecting "Niantic and Nintendo's wishes."

### ISSUE THREAD

**Issue by Whitely1** [Ar1i/PokemonGo-Bot#617]
From the tweet RIP 
Hey guys. We wish we had some news for you

At this moment, we are respecting Niantic and Nintendo's wishes. 

Will keep you guys posted

<3

**Comment by Ar1i** [comment]
Already got a alternative site probably which i can Support

**Comment by Whitely1** [comment]
Alright, Just making sure :)
Thanks.
