### ISSUE TITLE
Error at Request PostProtoPayLoad

### ISSUE THREAD

**Issue by Arkrant** [Ar1i/PokemonGo-Bot#618]
Hey ! 

Nice work ! Sometimes i got some error appears ! 
Here, my error is > Error at Request PostProtoPayload GetPlayerResponse Retrying
![capture d ecran 2016-07-31 a 18 35 17](https://cloud.githubusercontent.com/assets/15823346/17277906/bed182e6-574e-11e6-92e5-80994f51f481.png)

If you can fix it, it's would be nice !

Thanks

**Comment by Arkrant** [comment]
yes this error don't do anything i just write for fix it ! and do a clear log on the console :)

**Comment by Ar1i** [comment]
ignore it
