### ISSUE TITLE
Telegram bot problem

### ISSUE THREAD

**Issue by Thenatdead** [Ar1i/PokemonGo-Bot#619]
Hi 
I have set token and name bot and when i start pokemon go bot i said : To Activate Informations with Telegram, write the Bot a message for more Informations

And on my telegram bot i have no message and when i write on bot i say : No power here 
 Thinks for help me

**Comment by UltraVLT** [comment]
Did you write under the API Token box the name of your account who write from to the bot or your botname? ._.

**Comment by Juiche** [comment]
what teleggram bot do tho? for what?

**Comment by hancooo** [comment]
Hello, great work on this working epic!. Few problems:
Do you have a list of commands for the Telagram bot?
Also the command to turn on live information (Pokemon Caught, etc)

When I send anything (I have tried /stats and /top 10) I just get back the same thing every time: 
"I don't hear at you!"

See attachments

![pokeboterror1](https://cloud.githubusercontent.com/assets/20757683/17278103/619282b2-574c-11e6-92d3-496b162e016f.png)
![pokeboterror2](https://cloud.githubusercontent.com/assets/20757683/17278104/63a853b0-574c-11e6-9160-85aca3b6929f.png)

**Comment by UltraVLT** [comment]
did you wrote in the settings your telegram name under the api token box? @hancooo

**Comment by hancooo** [comment]
Yes, I have put the Telegram Bot Name under the name section.

**Comment by UltraVLT** [comment]
So you put "PokeBotUpdate" in there? @.@

**Comment by hancooo** [comment]
I have tried both the bot username "PokeUpdateBot" and also the bot name "PokeBotUpdate"

**Comment by UltraVLT** [comment]
Both of them are wrong,you have to put in your telegram name so you are like the "admin" of the bot.

**Comment by hancooo** [comment]
Sorry, I am lost. What other names are there?

**Comment by UltraVLT** [comment]
When you click on settings at the Telegram app there should be a text given informations about like your phone number.There should be your username too with @name.This is the name you have to type in that box but without the "@".

**Comment by hancooo** [comment]
PERFECT!
Thanks. I did try that, but I did not realize it was case sensitive. 

Thanks again.

**Comment by hancooo** [comment]
Can I request a feature that in the next release there is an option to turn on Live Pokemon Catches?

**Comment by Thenatdead** [comment]
Thanks i fixed that its done ;)

**Comment by Thenatdead** [comment]
What is a best spot for leveling ? but now Pokevision is closed rip

**Comment by martinjamesl** [comment]
Thanks for the information, I'll try it soon
