### ISSUE TITLE
Transferring?

### ISSUE THREAD

**Issue by RileyMcGee** [Ar1i/PokemonGo-Bot#620]
Having issues with transferring, set it to keep only 1 copy, no duplicates. Also set threshold for max CP at 900, and max IV at 85%. However I see it keeping pokemon with ~400 cp and like 40% iv? It actually filled my entire inventory overnight because it would not transfer them. 

Have I configured settings incorrectly?

**Comment by UltraVLT** [comment]
The settings should be right.Sometimes they bug on my acc too,but I wake up in time intervalls and transfer them manually. :S

**Comment by HSMatheus** [comment]
same problem ...

**Comment by wegweisen** [comment]
The bot automatically unbans you. 
http://fs5.directupload.net/images/160731/9flo9nsy.png

**Comment by UltraVLT** [comment]
@wegweisen wrong # answered? xD

**Comment by Ar1i** [comment]
should be fixed
