### ISSUE TITLE
Many Pokemons didn't Transfered Resulting Error " PokemonInventoryFull 241/250 " 

### ISSUE THREAD

**Issue by vrenzz** [Ar1i/PokemonGo-Bot#621]
i think someone posted it already but i want to be very through about this ... 
my setting is 1000 CP and 85% IV 
![transfer](https://cloud.githubusercontent.com/assets/20753039/17277962/515cbbb6-5782-11e6-8559-a62c0b5392d4.jpg)

and if the fix takes time to check .. please ADD sort (name/number/CP/IV) at Pokemon GUI List ... it will help alot while we waiting :+1:  :)

**Comment by mauxak** [comment]
Please download latest version
