### ISSUE TITLE
Lured Pokestops are ignored?

### ISSUE THREAD

**Issue by madpada** [Ar1i/PokemonGo-Bot#623]
A couple of times I've been at a real location on my device... standing next to 5 overlapping pokestops that were all lured.  I could see that there were currently at least 8 pokemon sitting there on the pokestops.  I quit Pokemon Go on my iPad and then set that location as my GPS location for the bot as I am starting it up (ensuring that Config\LastCoords.txt was deleted first).  When it launched, it was only able to find 1 pokemon in that area and quickly moved on.  Its as though its not seeing the pokemon that spawned from the lured pokestop.

Are these pokemon detected in a different way than the standard wild pokemon that are roaming around?

**Comment by K0zY** [comment]
where is that config folder???

**Comment by UltraVLT** [comment]
@K0zY it's in the main folder when you start the bot the first time.
@madpada The bot moves from pokestop to pokestop,he doesn't detects lures and waits there.

**Comment by madpada** [comment]
@UltraVLT i am fine with him not detecting the lures but its like he doesn't even see the pokemon that spawned from a lure. :/

**Comment by UltraVLT** [comment]
Hm,you could try to lower the move radius so the bot just walks around in the radius of these lures and watch if he detects them then.

**Comment by Ar1i** [comment]
new api will fix that atm i cant do anything
