### ISSUE TITLE
Running multiple Bots simultaneously

### ISSUE THREAD

**Issue by madpada** [Ar1i/PokemonGo-Bot#625]
With earlier versions of the Bot I was able to run up to 9 bots at the same (never tried more) but it seems like around the time PokeVision support was added (not sure this is the cause)... It no longer allows me to do that.  Has anyone else had this problem?

**Comment by UltraVLT** [comment]
Still botting 5 bots at the same time,but I am using the vers of yesterday.What problem is showing up when you start the other instances of the bot?

**Comment by madpada** [comment]
It starts throwing errors about being to far too away from pokemon to catch them.
