### ISSUE TITLE
location help plz

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#628]
http://prntscr.com/bzvfj7

i want get out of newyork xD and i cant can someone help me??? pllzz

**Comment by hazmad** [comment]
When you first open it up, Look for the location settings (right under your account info). Choose the "Set Location" and choose when you want to go. 

be careful of jumping around too quickly

**Comment by madpada** [comment]
delete your file called lastCoords.txt in the Configs folder.  The Configs folder is in the same folder where your EXE is that you use to start up the Bot.  Then when you launch the EXE you can use the "SET LOCATION" button to set your new location and it will have COMPLETELY forgotten about your old location.

**Comment by K0zY** [comment]
i dont have that folder configs
http://prntscr.com/bzvkzl

**Comment by hazmad** [comment]
once you open it up and choose "save configuration" (bottom right), it'll generate this folder and files

**Comment by K0zY** [comment]
@hazmad i did that and no folder bro :S

**Comment by madpada** [comment]
What version are you running?

**Comment by K0zY** [comment]
last one and i already fix it thnx all
