### ISSUE TITLE
AutoUpdater

### ISSUE THREAD

**Issue by DerRaiin** [Ar1i/PokemonGo-Bot#629]
Can i write for you a perfect auto updater ?(C#)
Here some examples for a mmorpg https://www.youtube.com/user/jubox1999/videos
Skype: justin12999

**Comment by Euskater2** [comment]
auto updater ! good idea :)

**Comment by rlmrso** [comment]
Great idea !

**Comment by madpada** [comment]
I wouldn't use auto update feature if it was added.

**Comment by RayVermilion** [comment]
This Place only for issues.
Request please in this forum: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Ar1i said that in the first post!

**Comment by Ar1i** [comment]
Wouldnt add, cause its in the forum forbidden aannnnd auto updaters are bad
