### ISSUE TITLE
Virus ?!

### ISSUE THREAD

**Issue by Dexter13425** [Ar1i/PokemonGo-Bot#632]
Yo I have scanned the zip and virustotal found a Ikarus backdoor !

How it's possible or it's an error ?

https://www.virustotal.com/fr/file/d8a456221dcef11a40be69e0381350d5078b9ed72b824df63a4f3bee9a82529b/analysis/

SHA256:	d8a456221dcef11a40be69e0381350d5078b9ed72b824df63a4f3bee9a82529b
Nom du fichier :	PokemonGo-Bot-master.zip
Ratio de détection :	1 / 55
Date d'analyse :	2016-07-31 17:10:40 UTC (il y a 29 minutes)

**Comment by Ar1i** [comment]
ZIP Scanning is always bad just saying, build your own then. You see the source.
