### ISSUE TITLE
transfer pokemons

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#635]
hello again xD 
i have alot of pokemons with 10cp 30 iv 
how to config the bot  to transfer auto that pokemons under 400 cp and under 80 iv??

my configs is max 300cp and max 80iv

**Comment by madpada** [comment]
Set duplicates to 2. iv to 90%.  Cp to 1500.  And turn off keeping Pokemon that can be evolved.  And set it to auto evolve cater pies, weedles, pidgeys, and rattatas.  Note: it will always keep your 2 strongest of any Pokemon and anything over cp 1500 or iv of 90 or greater.

**Comment by alperemre** [comment]
Still same problem x 3 uptade

**Comment by jordanpillefernandez** [comment]
Yeah completly same ... these pokemon with 15 cp and 20% IV stack on my bag ^^

**Comment by Ar1i** [comment]
disable keeppokemontoevolve
