### ISSUE TITLE
Telegram bot

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#636]
what Telegram bot does????

**Comment by toniy0** [comment]
As Telegram is like whatsapp, you can get live updates regarding your pokemon, XP, lvl and so on while you are not on your computer.

**Comment by ahmedtsadek** [comment]
it helps you watch the bot while you are away
you need a telegram account
create a bot look for tutorial online
copy paste the api key and enter your telegram user name to the bot and start chatting with the bot

**Comment by K0zY** [comment]
nice thnx for the help
