### ISSUE TITLE
We don't own Pokeballs

### ISSUE THREAD

**Issue by nicatmanaf** [Ar1i/PokemonGo-Bot#639]
How to fix this situation i tried turn off Pokevision but not helps 
![screenshot_1](https://cloud.githubusercontent.com/assets/10788471/17278347/85572cc8-576c-11e6-8872-b11b67586db0.png)

**Comment by Titus1987** [comment]
same!

**Comment by kerkael** [comment]
what if you have used all your pokeballs ? Then find a pokestop to refill.
what if you have been soft banned ? Then you need to throw 40 pokeballs to be able to catch pokemon or use pokestop
what if you have been soft banned and don't have 40 pokeballs left ???? well ..... maybe you wait 24h to be unbanned, or go to the shop and buy some pokeballs :)

**Comment by nicatmanaf** [comment]
@kerkael That means Bot can not get Pokeballs ?

**Comment by nicatmanaf** [comment]
Fix is like that. Disable lucky egg and Pokevision. And go on. U have to just wait
