### ISSUE TITLE
[Request] Mehrere Verbesserungen

### ISSUE THREAD

**Issue by Caddyrn** [Ar1i/PokemonGo-Bot#64]
Hallo Ihr lieben,

folgende Verbesserungen würde ich gerne Vorschlagen:

Verbesserung von Telegram, Bot Start und Stop Funktion in Telegram
Alle Pokemon mit einem % Wert von 90% Perfekt sollten im TElegram Chat kurz bei Information aufgeführt werden.

Das er Rauch benutzt und vllt Lock Module und dann an einem guten Eck wartet.

Eventuelle PokeVision Integration, Bot Checkt Seltene Pokemons und läuft dorthin falls in der MAX-Range liegent.

Bug Meldungen mach ich in einem anderen Thread

**Comment by Caddyrn** [comment]
Ebenso ist mir gerade eingefallen:

Er soll automatisch die Eier ausbrüten, oder eine Funktion in Telegram, das er von dort aus automatisch das ausbrüten startet.

**Comment by c0rrre** [comment]
Eier ausbrüten wäre auf jeden Fall auch noch geil

**Comment by Caddyrn** [comment]
Und wie man Updates des Bots durchführt ohne jedes Mal im GUI alles neu zu konfigurieren

**Comment by InvisibleTouch** [comment]
Yes incubate eggs would be nice....

**Comment by niikooartz** [comment]
Die settings bzw configs kannst du behalten indem du sie alle in den Configs ordner packst und dann einfach den configs ordner in den neu entpackten updgedateten bot ordner ziehst :D

Hoffe habe mich verständlich ausgedrückt xD
