### ISSUE TITLE
add a feature where the program looksonly forthe selected Pokemon

### ISSUE THREAD

**Issue by xxhamsterxx** [Ar1i/PokemonGo-Bot#640]
The program should teleport you to a Pokemon which was selected before.
I know that you might get asoftban but after that time you can catch it easy. 
Maybe you can combine it with Pokevision and the other pages?
I hope you know what I mean.

**Comment by Caddyrn** [comment]
Pokevision is down.  Your idea is very detectable.

**Comment by xxhamsterxx** [comment]
I know that pokevision is down but there are other great sites.
I know that they will softban you but after 2 minutes the bot will have unbanned you and the program has time to catch the pokemon,

**Comment by Caddyrn** [comment]
If you use a Move to GPS Data Function, you cant get a softban so fast. Teleport is very detectable.

**Comment by RayVermilion** [comment]
This Place only for issues.
Request please in this forum: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Ar1i said that in the first post!

And also everything which highers the risk for a softban is crap!
