### ISSUE TITLE
[Request] No-GUI-Version

### ISSUE THREAD

**Issue by Nestade** [Ar1i/PokemonGo-Bot#641]
Hello,

I'd like to run the bot on my VPS and I'd like to put it into the autostart.
Could you release a version without GUI or add something to autostart the bot?

Regards,
Nestade

EDIT: Autoupdate would be sick too :)

**Comment by RayVermilion** [comment]
This Place only for issues.
Request please in this forum: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Ar1i said that in the first post!

**Comment by Nestade** [comment]
Well, sorry - closed
