### ISSUE TITLE
[Request] Jenkins

### ISSUE THREAD

**Issue by Kurimatzu** [Ar1i/PokemonGo-Bot#642]
Could add Jenkins for automatic construction of the project? (I see you by modifying the source, however the folder "Builds Only" takes too long to be refreshed) with Jenkins, it's all automatic.

**Comment by RayVermilion** [comment]
This Place only for issues.
Request please in this forum: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Ar1i said that in the first post!

**Comment by Kurimatzu** [comment]
@RayVermilion I know that, but I think I'd better comment here, (Besides, it's a simple suggestion, you don't need to post on a forum)

**Comment by Kurimatzu** [comment]
@Ar1i 
Please, please, when you create a build, add a ChangeLog.
You make many changes, not to follow what has been modified.
