### ISSUE TITLE
Pokemon List Reload

### ISSUE THREAD

**Issue by EvilBlood** [Ar1i/PokemonGo-Bot#643]
Wenn die Funktion "Reload every X s" aktiv ist wird beim Neuladen die Funktion "Show only Pokemons that can evolve"

**Comment by UltraVLT** [comment]
ehm was genau ist dein problem? :O xd

**Comment by EvilBlood** [comment]
![reload](https://cloud.githubusercontent.com/assets/92166/17278645/0709a800-5762-11e6-80c1-cbf23e6af888.PNG)

Wenn beide Harken Aktiv sind werden alle Pokemon nach den Reload wieder angezeigt, aber der Harken bei "Show only Pokemons that can evolve" aktiv bleibt ohne das der Filter noch greift.

**Comment by Ar1i** [comment]
uhm, ist auf der liste
