### ISSUE TITLE
Telegram Bot Error

### ISSUE THREAD

**Issue by BalanceBreaker** [Ar1i/PokemonGo-Bot#646]
When the Bot is running for like 3 hours and i try to use /stats the Bot recognizes the command but then an error occurs:
"Error at Request PostProtoPayload GetPlayerResponse...".
I can only avoid the Problem if i restart the Bot every 3 hours.

BTW it would be cool if there would be a command like /capture that would also message me when the Bot captures a Pokemon :).

**Comment by Ar1i** [comment]
ignore that
