### ISSUE TITLE
Wait with evolutions until pokebox is nearly full

### ISSUE THREAD

**Issue by xhalfbakedguy** [Ar1i/PokemonGo-Bot#648]
I would love a feature where it waits with the evolutions until you have 240/250 so it doesnt burn through lucky eggs like mad

but keep in mind: if you stack up like 120 pidgey candy that there need to be 10 pidgeys

**Comment by 12348766754** [comment]
Just turn off the lucky eggs.. turn off the evolution..
Then.. wait till you have a lot of candies and put them both active?

**Comment by ShutUpPvP** [comment]
I just do it manually, u can evolve x amount of pokemon if u click Ctrm and click the pokemon, than click evolve, there u go.

**Comment by xhalfbakedguy** [comment]
ye i do turn off evolutions and luckyeggs but i only use the bot while im sleeping and working so i cant always keep an eye on it

**Comment by Quickbowjob** [comment]
Is it me or are the amount of candy's gone from GUI in ''Latest Build - 31.7 21.38'' ?
