### ISSUE TITLE
DRAGONITE!!!!!!!!!! sorry i know its for issues :3

### ISSUE THREAD

**Issue by ShutUpPvP** [Ar1i/PokemonGo-Bot#651]
Dragonite
40.880521148,-73.9003874774
Dragonite
40.880521148,-73.9003874774
Dragonite
40.880521148,-73.9003874774

**Comment by TMaddox** [comment]
a single one or nest ?

**Comment by ShutUpPvP** [comment]
LOL single one xD but a fkin Dragoran/Dragonire

**Comment by IDonated** [comment]
Woa what? I got softbanned for instatravelling gg

**Comment by xhalfbakedguy** [comment]
how do i snipe it?

**Comment by ShutUpPvP** [comment]
set the range to 3000m 50 kmh, get unbanned from the bot
BUT u need to set a tick that it doesnt try to catch dragoran

**Comment by ShutUpPvP** [comment]
than after u got unbanned set it to 30m range and enjoy the free dragoran

**Comment by IDonated** [comment]
will try, wish me luck

**Comment by xhalfbakedguy** [comment]
how do i see i got unbanned?

**Comment by IDonated** [comment]
Dragonite seems not to be there anymore Y__Y

**Comment by monoxacc** [comment]
is there no forum for this sh*t ?

**Comment by IDonated** [comment]
http://www.pokesnipers.com/

**Comment by ShutUpPvP** [comment]
So, i gna explain how i do it, its very easy since the latest patch of the bot.
U go to http://www.pokesnipers.com/
U now need to delete the "LastCoords" file in your config folder. (Bot needs to be closed)
Now u type in the coordinates that pokesnipers shows u.
It will teleport u there, before u click "Save Config." u need to set the range to 3000m and u need tocheck the box for Dragonite in the "Pokemons to not catch" box.
Log on, wait until it tells u u got banned and it will unban u.
Immideately close the bot, u probably already saw it saw xx pokemon and ignored it.
Now u change the range to 30m-100m and click select all so it unchecks all pokemon (so it catches all again)
Than u log in and u got what u want. :)

**Comment by ShutUpPvP** [comment]
haha, tried my best, before the patch it was super hard since u had to type coords in again and again
Holy cow!! gz man lucky you

**Comment by ShutUpPvP** [comment]
So, ill just close this i guess :)
