### ISSUE TITLE
Best coordinates to put in the bot.

### ISSUE THREAD

**Issue by leoozinn02** [Ar1i/PokemonGo-Bot#653]
# Why u don't put this site coordinates (http://spawns.sebastienvercammen.be/) in your bot, like pokevision, but this site have a lot of good pokemons.

**Comment by DargQ** [comment]
Is this a Ripoff pokesnipers?

**Comment by DargQ** [comment]
This page is for Issues go to https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ for suggestions.

**Comment by ShutUpPvP** [comment]
Wondering too, but its not as good as pokesnipers, since i cant see the despawn time
