### ISSUE TITLE
Application window too large, cannot click run

### ISSUE THREAD

**Issue by Joesilvpb4** [Ar1i/PokemonGo-Bot#654]
Problem:  Application window is too large, I cannot click the button to run and some settings are below screen.  Any suggetions?

**Comment by monoxacc** [comment]
Screenshot maybe? Which Windows do u have?

**Comment by NoticeMeSenpaiPLS** [comment]
Got the same Problem on my Ultrabook :/ for little screens its just to large :(

**Comment by Joesilvpb4** [comment]
![image](https://cloud.githubusercontent.com/assets/16861397/17279030/3394261c-5720-11e6-9411-9cba7aa31357.png)

Windows 10

**Comment by Joesilvpb4** [comment]
Would it be possible to adjust the application dimensions in whichever file holds the code?

**Comment by DargQ** [comment]
Just use Older build for now.

**Comment by IceQ1337** [comment]
I think it's because i changed the layout of the gui before.
I adjusted the settings in the next pull-request to make the gui sizable and scrollable.

**Comment by Joesilvpb4** [comment]
Thanks Ice!

**Comment by madpada** [comment]
increase your resolution in Windows... right click desktop and click Display Settings... stop running at such a low resolution.
