### ISSUE TITLE
Can't Find PokeStops

### ISSUE THREAD

**Issue by ObsessedHacker** [Ar1i/PokemonGo-Bot#656]
http://imgur.com/CUiXqBM

**Comment by ObsessedHacker** [comment]
Never mind it solved

**Comment by darklightchaos** [comment]
I am having this problem on two accounts.

**Comment by xash32** [comment]
I am having this problem +1

**Comment by mastersweg** [comment]
how did you solve i tried changing the range and it worked and now i increased that range to 100000m and it shows up the message id be thankful if you tell me how did you fix it

**Comment by Ar1i** [comment]
change location fixes that
