### ISSUE TITLE
Softban

### ISSUE THREAD

**Issue by DargQ** [Ar1i/PokemonGo-Bot#658]
Bot cannot notice softban without pokestops my bot got a targer distance within 70000 Seconds And bot  has run into like 15 pokemons they all get away and bot still cannot notice softban.

**Comment by ShutUpPvP** [comment]
i always restart the bot with 3000m range 50kmh and after max 2mins he is unbanning ,e

**Comment by DargQ** [comment]
Im running my bot with 300Km/h 5000m it doesnt get banned but i teleported and that coused the ban.

**Comment by DargQ** [comment]
My bot just runed into a pokestop and notices softban its ok now.

**Comment by ShutUpPvP** [comment]
make him slower, thats the problem, he has a hard time even acessing pokestops
