### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by am3yar0ra** [Ar1i/PokemonGo-Bot#659]
If possible can you please add the IV % besides the CP of the best pokemon while transferring.

[02:17:03] Transfer Rattata with 189 CP (58 % perfect) (Best: 328 CP / **??? IV**)

**Comment by DargQ** [comment]
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by jordanpillefernandez** [comment]
yes please
