### ISSUE TITLE
Catched.txt ;)

### ISSUE THREAD

**Issue by infslash** [Ar1i/PokemonGo-Bot#66]
@Logic.cs 357: 
File.AppendAllText(Environment.CurrentDirectory + "\\Catched.csv", StringUtils.getPokemonNameByLanguage(_clientSettings, pokemon.PokemonId) + ";" + encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp + "\r\n");

Edit: Die Idee kam von @par0noid ursprünglich, nur leicht abgeändert^^

Fände ich halt cool, dann hat man ne CSV ähnliche Datei für Excel ;)
Funktioniert bei mir. Ist nur ein Vorschlag.

Liebe Grüße
infslash aus HM

**Comment by Caddyrn** [comment]
Das man vllt diese Werte dann auch per TElegram abrufen kann wäre der Hammer. Das er die mit der besten %perfect werten die ersten 5 aufzählt oder so.

**Comment by par0noid** [comment]
@infslash mach ein .xls draus und im Excel sieht es schön aus :)

**Comment by infslash** [comment]
@par0noid edit done :) ty

**Comment by altobee** [comment]
Wird der Schnipsel noch übernommen ? Bei mir hat das leider nicht funktioniert mit dem rein editieren :-/

**Comment by bitrape** [comment]
Wäre nur nice, wenn die korrekte Vergangenheitsform benutzt wird.
Will kein Grammer Nazi sein, aber zu viele sprachliche Fehler lassen ein Programm unprofessionell aussehen, auch wenn der Code dahinter gut ist.

Catch, caught, caught.
-> caught.txt
