### ISSUE TITLE
pokevision out

### ISSUE THREAD

**Issue by lfaveur** [Ar1i/PokemonGo-Bot#660]
Hi is is planned for future to add an alternative for pokevision ? this website https://skiplagged.com/pokemon/# can be one alternative no ?

**Comment by DargQ** [comment]
Please suggest it at https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by DargQ** [comment]
This place is for Issues

**Comment by IceQ1337** [comment]
It was already added, but then it got removed with the next branch

**Comment by Quickbowjob** [comment]
Did try to link that on the forum yesterday but it still says: _(You have insufficient privileges to reply here.)_

**Comment by Ar1i** [comment]
using something other.. but we are currently writing the bot with the newest api.
