### ISSUE TITLE
We have no Pokeballs?

### ISSUE THREAD

**Issue by TouchTheSkies** [Ar1i/PokemonGo-Bot#661]
Do you need to already have the items on the account to use them? And why am I unable to find any Pokestops when I know they're well within range? These may not be real issues, but I thought I'd ask.

**Comment by DargQ** [comment]
I runed into this issue alot try to restart you bot or wait it might be softban.

**Comment by TouchTheSkies** [comment]
I've waited/restarted numerous times. It either says that, or it can't find any Pokemon in the area at all.

**Comment by DargQ** [comment]
Then try to use older build thats what i did and wait for newer one later.

**Comment by DargQ** [comment]
And it could be a problem with Pokemon go server.

**Comment by TouchTheSkies** [comment]
I've tried just about everything x.x

**Comment by TouchTheSkies** [comment]
Solved itself eventually, once I changed location.
