### ISSUE TITLE
pokemon list "evolvable?" description

### ISSUE THREAD

**Issue by Juiche** [Ar1i/PokemonGo-Bot#662]
some pokemon that can evolve, describe as "N" (can't evolve)

<img src="http://image.prntscr.com/image/87437842b4d244609e89a5a20a0e1e3f.png"></img>

-------
updated

because not enuf candy

**Comment by UltraVLT** [comment]
N because you don't have enough candy (16/100) to evolve ._.

**Comment by Juiche** [comment]
its not showing my current candy for each pokemon anymore.

**Comment by ShutUpPvP** [comment]
(16/100)

**Comment by UltraVLT** [comment]
Sure it does,just like on your screenshot lol

**Comment by Juiche** [comment]
but if a pokemon meet the requirement for evolve
its not showing my current candy for that pokemon anymore.

**Comment by ShutUpPvP** [comment]
Its Y and (400) then, well, we learned it at school xD u can write 400/400 but its not needed ya know

**Comment by ShutUpPvP** [comment]
But its simple, if it says Y u can, if not u cant. done.

**Comment by UltraVLT** [comment]
That's normal,never has shown the amount of candies. E.g when u want to evolve an eevee it only shows Y(25),because it only cares about if u can evolve or not.If you want to see your full amount,log in.

**Comment by Juiche** [comment]
previous version show our total ammount of candy

so i know how much candy left after power up a pokemon, 
lets say i want to power up 2 times before, without worry lacking of candy  for the evolve.

**Comment by Quickbowjob** [comment]
Yeah the candy tab is gone.. :<

**Comment by yoyos** [comment]
We love the total of candies :'(

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/681

**Comment by Ar1i** [comment]
doing that
