### ISSUE TITLE
New Location

### ISSUE THREAD

**Issue by Tenderlol** [Ar1i/PokemonGo-Bot#663]
If i move to a new location the bot needs to walk ... any way to fix that ?
I tryed it with the box beneath ticked and not ticked and it didnt make a difference.

**Comment by toniy0** [comment]
Delete the text in Configs\LastCoords.txt

**Comment by ShutUpPvP** [comment]
Delete the "LastCoords" file in the "Config Folder
Then just uncheck the box that says soemthing with default location

**Comment by Tenderlol** [comment]
did not work :/
