### ISSUE TITLE
should add back candy in pokemonlist its really useful

### ISSUE THREAD

**Issue by glabella** [Ar1i/PokemonGo-Bot#664]

**Comment by yoyos** [comment]
I'm for it too.
Is Evolvable and Candies are two separate things.

Instead, You could remove Height and Weight, those are shit
You can add HP too !

**Comment by yoyos** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/662

**Comment by FrancYescO** [comment]
#681

**Comment by Ar1i** [comment]
should be in now
