### ISSUE TITLE
Doesnt Transfer / Auto Snipe Req

### ISSUE THREAD

**Issue by jayomu** [Ar1i/PokemonGo-Bot#665]
I have duplicates 1, check transfer, min cp 1000, min iv 90, uncheck keep pokemon to evolve, uncheck evolve pokes with enf candy. 
The bot still stacks up all the catches. and it becomes useless if we keep it on for a few hours. cuz the pokemon box gets full. 
it should go like catch and transfer. but it catches x and transfers y, while x still meeting the transfer criteria.
Also, add a auto snipe function. :+1: 
And how do we help you to shut that site down?

**Comment by glabella** [comment]
maybe check the list on right "pokemons to not transfer " if they are checked there wont transfer

**Comment by jayomu** [comment]
> maybe check the list on right "pokemons to not transfer " if they are checked there wont transfer
i have like 20 on not to transfer. which dont mean anything cuz 10 are mew mewtwo etc which i dont have.

**Comment by jordanpillefernandez** [comment]
Same thing here. I dont want all these ratata...

**Comment by Emmi911** [comment]
It seems like a bug. The developer will probably fix it once he got time and notices it. Got the same
