### ISSUE TITLE
cant use multiple bots

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#668]
it says that the file lastcord is being used by another user, i already deleted it, changed the location and so, but i can only open one bot or it'll display the error, if SS needed please tell me

**Comment by gnzl0o** [comment]
ill try to insist if the problem persists ill send the Screen

**Comment by inurbad** [comment]
im currently runniny 10 bots and it works fine

**Comment by am3yar0ra** [comment]
1. Configs > config.txt => Edit and change your chords there.
2. Configs > LastCoords.txt => Edit your chords here also.

This will fix your issue.
