### ISSUE TITLE
Lowest IV is 100% ?

### ISSUE THREAD

**Issue by yusuf541** [Ar1i/PokemonGo-Bot#669]
just minor bug ^^
http://image.prntscr.com/image/7e1d9fc5a23b447e9dea46535daf9be9.png

**Comment by DokiTeeX** [comment]
Yes me2 with my magikarp.

**Comment by ShutUpPvP** [comment]
Yea, its just the "format" i think.
he needs to make it 001 010 100 and it should work fine

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/692

**Comment by Ar1i** [comment]
fixed
