### ISSUE TITLE
Error at request postprotopayload getPlayerresponse retrying

### ISSUE THREAD

**Issue by Synthek** [Ar1i/PokemonGo-Bot#671]
der mist kommt in einer tour was soll ich machen?

**Comment by ShutUpPvP** [comment]
Bei mir gings in ner früheren version durch neustarten weg, aber die meldung macht nix böses, einfach ignorieren.

**Comment by Synthek** [comment]
bekomme dadurch in einer tour softbann

**Comment by Ar1i** [comment]
ignorieren einfach
