### ISSUE TITLE
Doesn't transfer pokemons anymore.

### ISSUE THREAD

**Issue by Emmi911** [Ar1i/PokemonGo-Bot#673]
Worked like a charm for days but it seems that transfering doesnt work anymore. It says full inventory and is unable to catch new pokemons. Didnt change any settings.

**Comment by glabella** [comment]
it is working
![transfer](https://cloud.githubusercontent.com/assets/19846525/17279768/e17bf182-5785-11e6-86b7-3570e099947f.png)

**Comment by IceQ1337** [comment]
Leave a screen with your settings or ask for support at high-minded.com

**Comment by ShutUpPvP** [comment]
Its a bug, if u log in with ur phone u have a full inventory, just delete some pokemons manually

**Comment by alperemre** [comment]
same problem @glabella please config screen here

**Comment by Emmi911** [comment]
https://s31.postimg.org/pqvsj3eyz/error.jpg

**Comment by Emmi911** [comment]
None marks set on not transfer

**Comment by IceQ1337** [comment]
Maybe its because you "keep pokemon which can be evolved".
Try to uncheck it and tell us if that was the case please.

**Comment by Emmi911** [comment]
Testing that now. The error came again but it transfered pokemon (those who can be evolved). Lets see how it goes. Thanks so ar

**Comment by vrenzz** [comment]
@IceQ1337  thanks dude.. it works XD fiuuhhhhh :D

**Comment by HSMatheus** [comment]
someone pls leave a screen with the settings here, it's never transfering here :|

**Comment by IceQ1337** [comment]
@HSMatheus In the bottom-centered-box there is the option "keep pokemon which can be evolved".
Try to uncheck it.
