### ISSUE TITLE
Prioritize IVs over CP?

### ISSUE THREAD

**Issue by RemixDeluxe** [Ar1i/PokemonGo-Bot#674]
I'm still losing 90%+ pokemon because their CP is too low. Is this being looked into?

Maybe its me and I have a bad setup.

**Comment by ShutUpPvP** [comment]
#670 
So setting the CP value LOWER should work. didnt try it yet. im scared

**Comment by ShutUpPvP** [comment]
So i may found the problem.
The factor of CP and IV only applies after u have "3" pokemon of the same type
Means if u have 3 dragonir and 3 of them are lvl 200 50 iv, it will keep all 3 of them even if u only want 90% and 999+

**Comment by RemixDeluxe** [comment]
So what should I do then? Keep the IV at 90% but CP to 0?

I tried that and it just doesnt transfer anything at all.

**Comment by ShutUpPvP** [comment]
Also i may found the problem that some of us are facing.
The factor of CP and IV only applies after u have a certain amount of pokemon "Default it's 3".
Means if u have 3 times Pokemon XXX, and 3 of them are lvl 200 with 50% IV, it will keep all 3 of them even if u only want 90% IV and 999+ CP
So a fix could be setting max dublicate to 1?

**Comment by RemixDeluxe** [comment]
I do have the max duplicate to 1, I've never set it to anything else.

I also have my IV set to 90 and CP to 1200. Because some pokemon have higher CP than others the lower ones will get tossed out despite having higher IVs. I'm just hoping the devs are noticing this.
