### ISSUE TITLE
Updating to 1.0.4.9 bad idea ?

### ISSUE THREAD

**Issue by devidduma** [Ar1i/PokemonGo-Bot#675]
I heard that 1.0.4.9 is unstable, is this true? I have version 1.0.4.5 but want to upgrade, because i saw in the threads that the bot helps you get unbanned, when teleporting to catch pokemons using http://www.pokesnipers.com/

**Comment by Spartacusbr** [comment]
Same question here, I'm still on 1.0.3.8 would like to know what's the most stable bug-free (even if less features) version so far. Thanks.

**Comment by ShutUpPvP** [comment]
1.0.4.9 here, works like a charm for me

**Comment by am3yar0ra** [comment]
The latest version is bug free and is the best till now. There are no errors or bugs found yet.

**Comment by ShutUpPvP** [comment]
#678 @am3yar0ra?

**Comment by RogelioEV** [comment]
From my experience its way better than last update
