### ISSUE TITLE
autotransfer certain PK, UI suggestions, and possible lead for hatching

### ISSUE THREAD

**Issue by Parry1217** [Ar1i/PokemonGo-Bot#676]
Hi, love the work you all are doing on this, sincerely, thank you.

1) could we add an option for pokemon to catch and always transfer?  I sure could use the stardust from catching and transferring all these pidgies. ratatas and weedles... there are so many around here and they all get ignored when that could be 210 stardust each!

2)  I know it has been mentioned numerous times for hatching eggs.  And i know its not in the API.  there is another bot by jabbink written in Koltin that has egg hatching via the API.  perhaps they found a new function in the API??

3) Great job, who ever does the UI...with the advent of more widescreen computers, perhaps a more horizontal layout would be advantageous.

4) the Pokemon UI is awesome.  I liked it better when it could resize.. if you would anchor the listbox to the form differently, it could be resizable.  I sometimes have 15-20 magikarps at one time, it hard to tell which ones to transfer without scrolling up and down.

5) an additional tab in the PokemonUI for items.  I use the bot to farm in another country, so logging on to see how many pokeballs i have is not really possible.  

Great job all that work on this project!
Parry

**Comment by ShutUpPvP** [comment]
hey, please post suggestions here:
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

and nice ideas ;)

**Comment by Tochez** [comment]
@Ar1i #close
