### ISSUE TITLE
CP/IV to Transfer "BUG?"

### ISSUE THREAD

**Issue by ShutUpPvP** [Ar1i/PokemonGo-Bot#678]
So i may found the problem that some of us are facing.
The factor of CP and IV only applies after u have a certain amount of pokemon "Default it's 3".
Means if u have 3 times Pokemon XXX, and 3 of them are lvl 200 with 50% IV, it will keep all 3 of them even if u only want 90% IV and 999+ CP

**Comment by HSMatheus** [comment]
@ShutUpPvP  So, If I have like 3 Pikachus random Cp and IV , and duplicate pokemons is set to 3, the bot will keep them but the next Pikachus will be transfered if CP < 999 or IV < 90% right?

**Comment by HSMatheus** [comment]
but if I set duplicate to 1, having 3 pikachu, 2 of then will be transfered?

**Comment by ShutUpPvP** [comment]
Yes, tested it too yesterday, just didn't update it here, sorry. :)
So it's an error on dev's side.
The actual count of pokemom doesnt change even if its set to 1.
