### ISSUE TITLE
Idea ! :)

### ISSUE THREAD

**Issue by Euskater2** [Ar1i/PokemonGo-Bot#679]
Maybe an option, that tells the Machine that it only should Evolve a Pokemon with the highest CP ?

**Comment by tomypc88** [comment]
This Place only for issues.
Request please in this forum: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Ar1i said that in the first post!

**Comment by Tochez** [comment]
@Ar1i #close
