### ISSUE TITLE
[17:47:47] Error Catching Pokemon: EncounterNotInRange

### ISSUE THREAD

**Issue by madpada** [Ar1i/PokemonGo-Bot#683]
I created a new folder and added the contents of the Latest build and fired up the EXE.  In the GUI I filled everything out and hit save config.
The bot logs in just fine but whenever it tries to catch a pokemon, it gives this error:
[17:47:47] Error Catching Pokemon: EncounterNotInRange

Anyone else having this issue?

**Comment by myhvac** [comment]
Same Issue

**Comment by Sininenjuusto** [comment]
Unable To Catch Pokemons here

**Comment by madpada** [comment]
Didn't list my version but its 31.7 22.34 also

**Comment by madpada** [comment]
I just went back to an older version and it all works fine for me.... i guess i Will hold off from updating for now :(

**Comment by Sininenjuusto** [comment]
@madpada What Version You Went Back To?

**Comment by myhvac** [comment]
I went back to my old version 31.7 12.26 and had the same issue

**Comment by madpada** [comment]
i went really far back... 1.0.2.4 is the version number of my EXE file

**Comment by myhvac** [comment]
Strange, I went back to many backups and didn't work. I kept going back to Build 1.5 - 29.07 14.28 with exe version 1.0.2.9 and it worked.

**Comment by RogelioEV** [comment]
I had the same issue, what it causing it for me was that I download the last build and only overwrite the files form last ver, then I delete everything and reconfig again. After that works perfect

**Comment by madpada** [comment]
@RogelioEV i had tried that as well but didn't work for me :(

**Comment by RogelioEV** [comment]
@madpada no softban?
