### ISSUE TITLE
transfer pokemon

### ISSUE THREAD

**Issue by gnzl0o** [Ar1i/PokemonGo-Bot#685]
the bot is working perfectly but since the last actualization of pokemon go i cant transfer any pokemons(in game), is it because the location is way too far (NY)?

**Comment by CP02A** [comment]
Maybe its because of a soft ban... I just know because of a softban you cant get pokemon nor do anything

**Comment by IceQ1337** [comment]
Do you "keep pokemon which can be evolved" ? This might be the reason.
