### ISSUE TITLE
PokeBall-less (solved)

### ISSUE THREAD

**Issue by JunoBotboy** [Ar1i/PokemonGo-Bot#686]
I ran out of pokeballs!

And theres no pokestops in even 20million METERS !!

![pijds](https://cloud.githubusercontent.com/assets/20761289/17280282/7a084832-575a-11e6-9a8d-72a0ed1e5f31.png)

**Comment by Sininenjuusto** [comment]
Go To Config and delete LastCors Txt File and Try Again Should Work!
![screenshot 2016-08-01 03 09 56](https://cloud.githubusercontent.com/assets/20760993/17280303/80245f72-5795-11e6-8419-31dc17a96c25.png)

**Comment by JunoBotboy** [comment]
nope, didnt work

it says the same thing.

**Comment by rlmrso** [comment]
Softban just let it go it wil use 1337 unban methode and put max radius to around 5000 dont use standard location

**Comment by IceQ1337** [comment]
Laggy servers can also be responsible for this error. Try again later and tell us if the problem still exists.

**Comment by JunoBotboy** [comment]
dont worry i fixed it

It was still set on the same corrdinates

**Comment by JunoBotboy** [comment]
Hi, Ice!

Thanks for the App!!! i love pokemon

**Comment by IceQ1337** [comment]
@JunoBotboy 
I'm glad you like it, but it's actually not my work.
Thank Ar1i and the community-contributors (like me) instead! :D
