### ISSUE TITLE
"Max cp to transfer" is not working!

### ISSUE THREAD

**Issue by TueND** [Ar1i/PokemonGo-Bot#687]
"Max cp to transfer" is not working! Fix it please!

**Comment by IceQ1337** [comment]
It is working for me. What does your problem exactly look like?

**Comment by CP02A** [comment]
Mine works too
Maybe you put the pokemon on the "do not transfer" list?

**Comment by RogelioEV** [comment]
Works for me

**Comment by TueND** [comment]
My setting is:
 - Max CP to transfer: 650
 - Max IV to trasfer: 90
- Pkm to not transfer: i just tick some of the main Pokemon
The problem is : it retains almost all pokemon caught
Sorry, I'm not so good at English

**Comment by RogelioEV** [comment]
Hace you tried changing some of The configs?

**Comment by IceQ1337** [comment]
What's your plan for keeping pokemon?
With those settings you will keep:
1. every pokemon with 90%+ IVs
2. every pokemon with 651+ CP
