### ISSUE TITLE
pokecrop? you mean Pokecrot!

### ISSUE THREAD

**Issue by CP02A** [Ar1i/PokemonGo-Bot#689]
I saw the word pokecrop in the GUI and I saw this in the descibtion:

"HELP NEEDED

So there is a guy, which copys 1:1 my source and puts it online.
Help me to get his Site + copied Bot removed.
His site is: https://www.pokecrot.com/
Until that is done, i only publish builds. No Source."

So it is Pokecrop?? I Googled it and nothing came

**Comment by IceQ1337** [comment]
PR submitted. Should be fixed tomorrow.

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/691
