### ISSUE TITLE
Not Sure About The Issue

### ISSUE THREAD

**Issue by am3yar0ra** [Ar1i/PokemonGo-Bot#692]
![image](https://cloud.githubusercontent.com/assets/1933816/17280415/ff6a5b44-57ac-11e6-8a7b-d49fb522dc36.png)

What the heck !!!
What is bulbasaur doing there :octopus:

**Comment by guzdank** [comment]
thats a 90

**Comment by guzdank** [comment]
BTW what cords are u using to get high IV

**Comment by am3yar0ra** [comment]
@guzdank I'm using different bots. For sniping I use Necro and for farming this one.

**Comment by guzdank** [comment]
can you send best sniping setting for the necro bot?

**Comment by FrancYescO** [comment]
Confirming issue, unfortunately order in this column is done alphabetically

**Comment by FrancYescO** [comment]
Fixed in #681
