### ISSUE TITLE
Pokemons Keeps Getting Away!!

### ISSUE THREAD

**Issue by Sininenjuusto** [Ar1i/PokemonGo-Bot#693]
Even Cp10 Pokemons Keeps Getting Away i Was Using Latest Build Without Problems Then Suddenly couldnt catch pokemons anymore, and i tried to to downgrade almost all Builds And Still Cant Catch Pokemons. Fix Anyone?!

**Comment by IceQ1337** [comment]
Maybe you got softbanned or you don't have any pokeballs left.
Do you still get XP from pokestops?

**Comment by Sininenjuusto** [comment]
@IceQ1337 yes i am getting xp and i have pokeballs left

**Comment by Quickbowjob** [comment]
What speed Km/h you have set?

**Comment by Sininenjuusto** [comment]
@Quickbowjob 20km/h have had it for 4-5 builds now and never been a problem

**Comment by IceQ1337** [comment]
Do all pokemon keep getting away or just "a lot". Then the last app update would be the reason.
It is much more likely for pokemon to escape now.

**Comment by am3yar0ra** [comment]
Change your location. This will help you fix the issue.

**Comment by Sininenjuusto** [comment]
@am3yar0ra done it multiple times dont work

**Comment by IceQ1337** [comment]
Are you able to test it on multiple accounts?

**Comment by Sininenjuusto** [comment]
@IceQ1337 over 30 pokemons have gotten away and most of them are lower than 100cp so i dont think its about the app patch

**Comment by Sininenjuusto** [comment]
@IceQ1337 yes tested on my other account and i can catch pokemons so what is wrong with my other account then cus i aint banned everything still works but cant catch pokemons ?

**Comment by IceQ1337** [comment]
@Sininenjuusto A softban means you are not able to catch pokemon, fight in gyms and so on..
The rest would work "totally" fine.

**Comment by Sininenjuusto** [comment]
@IceQ1337 fck

**Comment by IceQ1337** [comment]
@Sininenjuusto Don't panic, it wouldn't last long.

**Comment by Sininenjuusto** [comment]
@IceQ1337 softban so i am banned forever?

**Comment by IceQ1337** [comment]
@Sininenjuusto No. It is 10 minutes up to a few hours or a day long.

**Comment by Quickbowjob** [comment]
Here is an easy un-ban tool that i tested today and works great, http://www.mediafire.com/download/e7f3xnd314mcwse/QuickSpin_1.2.zip

just make sure you get the coordinates right.
or do it manually in game by spinning a PokeStore for 40-50 times (5mins)

**Comment by IceQ1337** [comment]
@Sininenjuusto @Quickbowjob The bot will acutally detect a softban itself and will start the unban-method of it.

**Comment by Sininenjuusto** [comment]
@IceQ1337 @Quickbowjob should i use the bot?

**Comment by Sininenjuusto** [comment]
@IceQ1337 @Quickbowjob actually i got unbanned already

**Comment by CP02A** [comment]
I got the same problem but the bot doesn't do anything about it... And I didn't get banned while I was on the bot!
