### ISSUE TITLE
location bug

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#694]
http://prntscr.com/c00opc
the file in configs inst there and the last location is bug xD i didnt change anything

i downloaded the last version but now dont have config folder

**Comment by CP02A** [comment]
Now I know where you live ;)
Ok thats creepy
Well I have a "LastCoords" File in the config folder... You dont?

**Comment by K0zY** [comment]
at last update she disappear xD

**Comment by CP02A** [comment]
What?...

**Comment by K0zY** [comment]
http://prntscr.com/c00x2h

**Comment by CP02A** [comment]
Theres not even a config folder... Maybe you used the one inside the "Latest Build"?
