### ISSUE TITLE
Pokemon Features

### ISSUE THREAD

**Issue by CP02A** [Ar1i/PokemonGo-Bot#695]
Can you please make it that when you evolve an Eevee that it shows an option for the 3 Evolutions...
Also can you make it that you can star and nickname pokemons?

**Comment by madpada** [comment]
The Eevee Evolution doesn't work... and I believe the other requests are already implemented.

**Comment by CP02A** [comment]
Yes it does!

Names:
Sparky
Rainer
Pyro

If it doesnt work just restart your game and check if the name is still there because sometimes the servers dont catch up!

**Comment by CP02A** [comment]
Plus they confirmed it
@madpada

**Comment by FrancYescO** [comment]
nickname and stars are in tooltip text,

**Comment by CP02A** [comment]
@FrancYescO But I mean RENAMING them not just look at what the nicknames are
