### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by NWExKraken** [Ar1i/PokemonGo-Bot#696]
Whats the fastest speed you can go now and have it still capture pokemon and be safe from bans?

**Comment by NWExKraken** [comment]
i feel like thats too fast

**Comment by samueleycw** [comment]
you can try to fast farm and the soft-ban is not often appear also Ar1i make a great unban system so dont worry

**Comment by samueleycw** [comment]
10/kmh - 30/kmh is a safe speed
