### ISSUE TITLE
Version 1.0.4.9 Missing Candies from Pokemon List

### ISSUE THREAD

**Issue by southparkkids** [Ar1i/PokemonGo-Bot#697]
I like to see how many candies I have to decide what to evolve.

**Comment by NWExKraken** [comment]
should be the number next to the part where it says if its evolveable or not

**Comment by RogelioEV** [comment]
Yeah, the column says if its evolveable or not. if not showa sonethin like (25/50). If it is actally evolveable just sohs how much candies takes (50), bout it was cool to be like "Y (253/50)"

**Comment by samueleycw** [comment]
Yup! candy list is very useful for us to monitor, hope it can add back

**Comment by FrancYescO** [comment]
w8 for this pull https://github.com/Ar1i/PokemonGo-Bot/pull/681
