### ISSUE TITLE
Telegram Benachrichtigungen

### ISSUE THREAD

**Issue by altobee** [Ar1i/PokemonGo-Bot#7]
Derzeit gibt es ja nur über Stufenaufstieg sowie die Stats eine Benachrichtigung. Vielleicht könnte man dies um Status der Brutmaschienen erweitern und dies im UserSettings wählbar machen. 

Würde enorm die Geschichte mit den Eiern vereinfachen. Zudem eine Meldung wenn der Server down ist, bzw. man Probleme im Bot hat.

**Comment by nulp3** [comment]
Was auch nett wäre zb die "Top 10 Pokemon" / "Die letzten 10 Gefangen" anzeigen.
zb /top 10
Taupsi: 100 CP
Glurak: 69 CP etc.. 
(um Telegram ein wenig mehr sinn zu geben, um sich up2date zu halten)

**Comment by MikeUNtested** [comment]
Ich finde die Idee mit den Eiern auch sehr gut,  gerade da diese noch nicht automatisiert sind

**Comment by nulp3** [comment]
Spontan Idee:
Force Evolve via Telegram (wenn Automatisches Evolven zb aus ist)
Use Exp Boost (if ex-item >0)
Start Evolving All

**Comment by nulp3** [comment]
Zusatz Idee noch zu dem Top x:
Vielleicht noch Top X je Typ so das er nur das beste Pokemon davon anzeigt (das zb nicht 3 Ibitaks in der Liste sind sonder nur das beste davon)
