### ISSUE TITLE
pokemon list keep reloading doesnt show pokemon

### ISSUE THREAD

**Issue by roynarddd** [Ar1i/PokemonGo-Bot#702]
bot running normaly but pokemon list doesnt show anything it keep reloading, and before it happens my pokemon list error pokemon image duplicate and lag. i already delete and download newest but it still happens, sprites folder are empty too

**Comment by Tochez** [comment]
sometimes its not the bot problem. Its ur computer :/ @ @roynarddd

**Comment by roynarddd** [comment]
@Tochez yea the maybe the problem on my netframework because theres an alert it said my netframework running in another program, u know how to fix this sir?

**Comment by FrancYescO** [comment]
w8 this pull probably you will get more infos about error in console https://github.com/Ar1i/PokemonGo-Bot/pull/681

**Comment by hendek95** [comment]
same problem. my friends which i send pokebot they can use but i cant use :(
