### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by CP02A** [Ar1i/PokemonGo-Bot#704]
Will there ever be a Linux version so I can run it on my server in my basement?

**Comment by hazmad** [comment]
maybe try wine? it might work

**Comment by setyongr** [comment]
maybe you can try this
https://github.com/PokemonGoF/PokemonGo-Bot
its built using python so you can run that on linux

**Comment by pobyzaarif** [comment]
try wine

**Comment by FrancYescO** [comment]
use mono.

**Comment by CP02A** [comment]
https://www.winehq.org/
Thanks
