### ISSUE TITLE
Can add snipe tool to capture rare pokemon as necrobot use pokefeeder?

### ISSUE THREAD

**Issue by KHANGMIN** [Ar1i/PokemonGo-Bot#708]
Now i'm using Necrobot with pokefeeder because i want to capture rare pokemon. But i prefer using PokemonGo-Bot to using Necrobot
Can admin add snipe tool to capture rare pokemon?
Thanks

**Comment by Cepted** [comment]
I was thinking about the same thing! I'm sure a lot of other people would agree that they would love having this added!

**Comment by durnevo** [comment]
Yep, something like this:

How about have a bot that starts in 1 location, teleports to the co ordinates of a known rare pokemon, catches it without moving then return to the original location to avoid softban, it could grab the coordinates live from http://pokesnipers.com http://pokesnipers.com/api/v1/pokemon.json
