### ISSUE TITLE
FIX NAME

### ISSUE THREAD

**Issue by fourmansyah** [Ar1i/PokemonGo-Bot#711]
hello,
sorry about this but you Wrong Write :
GUI Note : "Pokecrop" The True Word is Pokecrot
check Out This Web www.Pokecrot.com
Thanks :+1:

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/691

**Comment by fourmansyah** [comment]
i talk about this ..
<a href="http://imgur.com/aIrwdxK"><img src="http://i.imgur.com/aIrwdxK.jpg" title="source: imgur.com" /></a>

**Comment by FrancYescO** [comment]
Fixed in #691.

**Comment by Ar1i** [comment]
fixed
