### ISSUE TITLE
got a issue

### ISSUE THREAD

**Issue by audota000** [Ar1i/PokemonGo-Bot#713]
![untitled](https://cloud.githubusercontent.com/assets/20767527/17288093/8a5eb1be-5816-11e6-8560-54d300bf8438.jpg)
help..anyone?
thanks.

**Comment by roberrrt-s** [comment]
Are you running the latest version?

**Comment by audota000** [comment]
yes, it is the latest version.

**Comment by Logxn** [comment]
Dont worry, it will get fixed with the next update I guess.
Nothing you guys did wrong

**Comment by roberrrt-s** [comment]
It's odd. My version, although immediately softbanning my character, returns no error like this.

Invalid response probably means one of your configuration settings is sending an invalid request to the PG servers.

**Comment by audota000** [comment]
and after this it just start over again with no problems....no idea what is going on.

**Comment by audota000** [comment]
is this means dangerous to continue?

**Comment by Ar1i** [comment]
ignore it
