### ISSUE TITLE
Pls return

### ISSUE THREAD

**Issue by DarkEXRaVen** [Ar1i/PokemonGo-Bot#715]
Please return in Pokémon parameter table that shows how much candy for the species you have everything. And you can somehow at the same table to do to display how much of one type of Pokemon I have? Manually considered long at times, when you have more than 60 pidgey inventory.

Thank you very much for your work.

**Comment by FrancYescO** [comment]
you can see candys in evolvable column.

**Comment by yoyos** [comment]
No you can't see them when you can evolve it

**Comment by DarkEXRaVen** [comment]
No. In evolable column only, example 12\50 or just 50 and say YES. I need to how much candy for one type I have.

**Comment by FrancYescO** [comment]
you will see candy also if Y after #681

**Comment by elenex23** [comment]
If was helpful when we could see the total candy for the creature.

**Comment by DarkEXRaVen** [comment]
Yes, column total candy more help

**Comment by FrancYescO** [comment]
I think Useless. Ordering with evolvable will be pretty the same

**Comment by Ar1i** [comment]
fixed
