### ISSUE TITLE
cant find any pokestops

### ISSUE THREAD

**Issue by ayatoo** [Ar1i/PokemonGo-Bot#716]
Hey 

when a strat the console i have 2 sentence.

We cant find any pokestops in a range of 1000m
we cant find any pokestope, which are unused ! Probably server unstable, or you visted them all. retrying ...

yesterday i had 0 problem  and today  have this problem  can you help me please ?

**Comment by Bikkstar123HD** [comment]
yup many are facing this issue

**Comment by ayatoo** [comment]
ok thank you

**Comment by stormlolz** [comment]
you have changed your position ?
send your last cordinates ?
try to set location and moove a little to change the 3 value and restart the bot ?

**Comment by ayatoo** [comment]
Ok i move a little and it work  thank you !

**Comment by Bikkstar123HD** [comment]
thank you soo much it helped me tooo

**Comment by DargQ** [comment]
I think its pokemon go server problem.....

**Comment by Ar1i** [comment]
change location
