### ISSUE TITLE
EncounterNotInRange

### ISSUE THREAD

**Issue by rihanboo** [Ar1i/PokemonGo-Bot#721]
Error catching Pokemon: EncounterNotInRange

Hey guys, i get this error message after the update. if i go back to the build 1.7-29.071914, everything is fine. every build after this one gives me that same  error. so ive been using this old one for a few days but I really want to use the new builds for its added features and bug fixes etc. any tips? tried fresh install, restart. It does not catch any pokemon or visit any pokestops thanks in advance

**Comment by ShutUpPvP** [comment]
Teleport away and its working again

**Comment by rihanboo** [comment]
unfortunately did not work, it seems to find the stops, but doesnt activate  them for poke balls etc and now no pokemon are being found at all to replicate the error msg i had earlier
![poke](https://cloud.githubusercontent.com/assets/20771150/17296122/db5c394c-57bc-11e6-8a95-5f78fd34c485.png)

**Comment by ShutUpPvP** [comment]
Softbanned because u tped, just let the bot run fpr 2-4 mins and he will unban you
