### ISSUE TITLE
Transfer Pokemon by IV

### ISSUE THREAD

**Issue by maksmar** [Ar1i/PokemonGo-Bot#722]
When the same Pokemon is catched multiple times, the Pokemon with the lowest CP is transferd.
It would be great to transfer the Pokemon with the lowest IV instead.

**Comment by UltraVLT** [comment]
Suggestions at https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by elenex23** [comment]
This seriously needs to happen. It is an issue that needs solve, and more important then these logo and language fixes.

**Comment by JustPlaysDE** [comment]
^
