### ISSUE TITLE
Pokemon list not working / Pokemon Liste lädt nicht 

### ISSUE THREAD

**Issue by whymk92** [Ar1i/PokemonGo-Bot#723]
Pokemon list is not working

any suggestions?

Der bot funktioniert ganz normal aber die Pokemonliste lädt nicht.

Kann mir da jemand helfen?

**Comment by hendek95** [comment]
same problem. i can enable gui list and show pokelist page but didn't reload.

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/709

**Comment by Ar1i** [comment]
update should be fixed
