### ISSUE TITLE
Suggest Manual force unban  soft-ban

### ISSUE THREAD

**Issue by samueleycw** [Ar1i/PokemonGo-Bot#725]
Sometime i get soft-ban about 5mins than the PokemonGo-Bot auto detect system is start to try unabn, so it is not sensitive so far , as you can hope add the Manual force unban button. Thanks!

**Comment by Bikkstar123HD** [comment]
right it doesnt unban youi have been trying it lately lot of times

**Comment by hazmad** [comment]
It works for me when I'm sniping. But yes, sometimes it can take a while to detect a soft-ban. This would be useful.
