### ISSUE TITLE
PTC offline for 2 of 4 accounts

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#727]
2 of my 4 accounts says PTC sever is OFFLINE..

Anyone have the same problem ?

![zefkljnelfize niefz](https://cloud.githubusercontent.com/assets/20703341/17294677/7fa96f34-57f8-11e6-9f51-40b66c0b62f0.png)

**Comment by audota000** [comment]
wait, u can let 2 accounts run at the same time on the same computer?

**Comment by stormlolz** [comment]
Yes
just copy tour folder
and i rename the exe :+1:  (don't know if needed)
ex : 
PokemonGo.RocketAPI.Console.exe
PokemonGo.RocketAPI.Console2.exe
PokemonGo.RocketAPI.Console3.exe
etc..

its running but i don't know if it's safe

**Comment by audota000** [comment]
is that means it is ok to exist 2 fake gps running in different programs on one IP address?
they are not intereacting each other?
i should try it. thx man.

**Comment by Ar1i** [comment]
thats cause ptc is unstable not a issue from my side
