### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by infslash** [Ar1i/PokemonGo-Bot#73]
> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
>    bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    bei PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) in D:\PokemonGo-Master\PokemonGo.RocketAPI.Console\GUI.cs:Zeile 251.
>    bei System.Windows.Forms.Form.OnLoad(EventArgs e)
>    bei System.Windows.Forms.Form.OnCreateControl()
>    bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    bei System.Windows.Forms.Control.CreateControl()
>    bei System.Windows.Forms.Control.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    bei System.Windows.Forms.Form.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Form.WndProc(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Kriege diesen Fehler beim Starten.
Fehler verschwindet sobald die Config.txt gelöscht ist. Vermutlich ist das Parsing an einer Stelle schief gegangen. Script läuft nach dem schließen vom Fehler Fenster trotzdem weiter, bzw. ich muss einiges neu einstellen und die Checkbox-Liste muss man auch neu anhaken.

**Comment by Ar1i** [comment]
Gucke mal rein

**Comment by Ar1i** [comment]
fixed
