### ISSUE TITLE
[BUG] Pokemon Count not corrent 

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#730]
Full pokemon at 241/250 because the bot count eggs ?

**Comment by Ar1i** [comment]
^this. I am not understanding that too tho

**Comment by stormlolz** [comment]
The bot consider I have the maximum pokemon 241/250 .
I have 9 eggs to hatch , it would not be bad account of those who pose this problem ?

**Comment by Werser** [comment]
This is the same behaviour as in the game. The eggs count as pokemon.

**Comment by stormlolz** [comment]
Ahh so i'ts just an error in the information of the nb ok pokemon

**Comment by joeykyubi** [comment]
I have the same issue.  i loggin in to the pokemon app and it showed i have 250 pokemon not 240. its some kind of bug.

**Comment by supertx2** [comment]
I configure the bot to  keep 1 pokemon each, but some times it keeps 2, 3... you guys have same issue?

**Comment by joeykyubi** [comment]
yeah it does on mine as well

**Comment by Ar1i** [comment]
@supertx2 @joeykyubi probably cause your cp/iv setup is wrong. Or you got keepPokemonToEvolve checked!

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/pull/911

**Comment by JustPlaysDE** [comment]
fixed
