### ISSUE TITLE
update does not fix pokemon list...

### ISSUE THREAD

**Issue by whymk92** [Ar1i/PokemonGo-Bot#735]

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/709

**Comment by hazmad** [comment]
Are you using home or work computer?

**Comment by whymk92** [comment]
home computer

**Comment by hazmad** [comment]
have you tried running it as admin?

**Comment by whymk92** [comment]
yes i have

**Comment by hazmad** [comment]
What OS?

**Comment by Snean1** [comment]
![er](https://cloud.githubusercontent.com/assets/12184212/17297848/5656f276-57ff-11e6-8ded-a4e4bdc3e862.png)

i get this Exception

**Comment by whymk92** [comment]
yesterday the pokemon list worked just fine

windows 10

**Comment by whymk92** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20772407/17297922/0e6ff9b8-5808-11e6-9b7f-b20c67ccedf3.png)

**Comment by hazmad** [comment]
Ok, I'm using google account on win 10. might be a ptc issue then.

**Comment by whymk92** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20772407/17298014/8601abd4-5808-11e6-882a-b79e0fb4754a.png)

**Comment by Snean1** [comment]
yesterday the servers were offline but loading the list worked.
Since the last update, it do not load.

**Comment by whymk92** [comment]
not a ptc issue because im using google acc

**Comment by Ar1i** [comment]
try restarting, for me its working

**Comment by Snean1** [comment]
restart/rebuild do not work. 
I restore every time my config!

**Comment by FrancYescO** [comment]
@whymk92 the screen is not from the latest build.

**Comment by whymk92** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20772407/17298805/ca35bb94-580b-11e6-929d-5466f5dd6fb4.png)

got the latest update now and it says "error reloading pokemon list"

restarted pc as well

**Comment by ToxicTear** [comment]
I got it aswell but just delete everything in the folder and then reinstall it.

**Comment by whymk92** [comment]
which folder? is it working for you?

**Comment by ToxicTear** [comment]
![ss 2016-08-01 at 05 30 55](https://cloud.githubusercontent.com/assets/20775867/17299227/be8873b6-580d-11e6-8ebc-050bbd048542.png)
I just deleted everything here and now its working fine.

**Comment by whymk92** [comment]
nope, not working for me

**Comment by hendek95** [comment]
i search. it is about microsoft problem i guess. 403 is mistake code. i tried setup hotfix but didn't work. i guess our pc s blocking server for pokemonlist pls help!

**Comment by whymk92** [comment]
ok..let me know if you find something

**Comment by hendek95** [comment]
can't find and open new issue #760 problem is about that.

**Comment by roynarddd** [comment]
i have the same problem but now it works by uncheck netframework 4.5 in program and feature.

**Comment by whymk92** [comment]
how can i uncheck netframework?
