### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Synthek** [Ar1i/PokemonGo-Bot#736]
i have updatet the programm an it says that a uprgade is available but i have you latest version

**Comment by bigwarboy** [comment]
same problem :D

**Comment by stickmick12** [comment]
I am to xD

**Comment by Synthek** [comment]
its funny^^

**Comment by bigwarboy** [comment]
Lets wait a minute ^^ start the bot and chill

**Comment by hazmad** [comment]
Sometimes there's small patches that don't change the version number. I just re-download and no more update message

**Comment by Synthek** [comment]
i re downloaded it but same problem

**Comment by fav0urite** [comment]
also redownloaded it.. doesnt change anything :D btw can someone tell me where i can get the most exp.. i am at the central park and i thing 17k-22k exp/h is a litte bit to few :D

**Comment by Synthek** [comment]
im there too^^
i doo 60k/h

**Comment by fav0urite** [comment]
@Synthek where do you farm or which settings do you use ? :P

**Comment by Synthek** [comment]
walk 200kmh
5000m
and all klicked

**Comment by Ar1i** [comment]
fixed

**Comment by Synthek** [comment]
thx^^
