### ISSUE TITLE
Location Change

### ISSUE THREAD

**Issue by shuksieno123** [Ar1i/PokemonGo-Bot#737]
Maybe u would add after a location change he runs first to a pokestop so the chance is better to get the favorite pokemon :)

**Comment by 13XxM1CHA3lxX37** [comment]
It is already like this

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
