### ISSUE TITLE
Ar1i is this so right the folder?

### ISSUE THREAD

**Issue by stickmick12** [Ar1i/PokemonGo-Bot#738]
http://www.bilder-upload.eu/show.php?file=b31563-1470064086.png

**Comment by stickmick12** [comment]
i dont know how realy must see the folder

**Comment by 13XxM1CHA3lxX37** [comment]
Lad dir lieber den fertigen Build runter und entpack den in einzelne Ordner

**Comment by stickmick12** [comment]
ja aber für was sind die anderen Ordner da das check ich nicht weischt

**Comment by Euskater2** [comment]
übrigens @stickmick12  der Ordner sieht etwa so aus http://puu.sh/qm7CH/76143fc7ee.png. :)

**Comment by stickmick12** [comment]
wenn das auch ohne das geht?

**Comment by Euskater2** [comment]
ich mache es schon die ganze Zeit so und lief bis jetzt einwandfrei

**Comment by stickmick12** [comment]
was bringt es denn?

**Comment by Ar1i** [comment]
Benutz einfach Build Onlys! :)
