### ISSUE TITLE
Pokestops Are not finding any items

### ISSUE THREAD

**Issue by Flaykert** [Ar1i/PokemonGo-Bot#739]
When The bot is taking a pokestop its saying:

Farmed XP: 50, Gems: 0, Eggs: / Items: / <Noting in here>

**Comment by stickmick12** [comment]
its right whos the problem/is doch richtig so wo ist das problem?

**Comment by stickmick12** [comment]
he dont found ever time items

**Comment by Flaykert** [comment]
But its happening to me everytime
like every pokestop that the bot came to its just saying
Farmed XP: 50, Gems: 0, Eggs: / Items: /

**Comment by stickmick12** [comment]
witch lvl are u?

**Comment by Flaykert** [comment]
22

**Comment by stickmick12** [comment]
ah oke my highest account get to very very rare any items of stops but the low acc get mutch

**Comment by stickmick12** [comment]
lol u right my highest acc to doesnt get items but the other get

**Comment by samueleycw** [comment]
you are soft-banned since the Bot may got issue with detecting , hope it can improve the soft-ban sensitive

**Comment by abdellahaski** [comment]
this happen because you bag is full check the stat on the console you'll find how many items you have 

@samueleycw If he is soft banned he couldn't get the XPs

**Comment by Ar1i** [comment]
^
