### ISSUE TITLE
why i cant find any pokestop?

### ISSUE THREAD

**Issue by konservatif** [Ar1i/PokemonGo-Bot#740]
i put my location on place that have so many pokestop, but did not met any pokestop. the bot only farming for pokemon and ignoring pokestop for collecting items

-lvl 22
-range 3500 meters
-50 speed

need for advice and helps... thanks pals

**Comment by Tochez** [comment]
delete the lastcoords file

**Comment by stormlolz** [comment]
when you set location, try to moove a little on the map to change the 3 cords, and retry

**Comment by JustPlaysDE** [comment]
^
