### ISSUE TITLE
can't catch pokemons

### ISSUE THREAD

**Issue by Vanmola** [Ar1i/PokemonGo-Bot#741]
when find a pokemon says  : 
Error catching pokemon : Encounter not in range

what can i do ? 
![untitled](https://cloud.githubusercontent.com/assets/20775697/17298798/193eeb1a-57d1-11e6-9fd7-d5e892d25f6d.png)

**Comment by Vanmola** [comment]
don't even get any pokestop , help please. 
![untitled](https://cloud.githubusercontent.com/assets/20775697/17299291/5a983286-57d3-11e6-9048-4a58aeff1b4c.png)

**Comment by abdellahaski** [comment]
which speed are you using ?
this happened to me when I've used a high speed

**Comment by peterbsandor** [comment]
he is using 50kmph as i see

**Comment by Vanmola** [comment]
i was using 15 km/h still having this issue, i can't catch any pokemon or get any item frm the pokestops.

**Comment by Vanmola** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20775697/17307078/ee88bf22-57f8-11e6-949b-af0f4404dc21.png)

**Comment by HackerPide** [comment]
Did you try resetting your LastCoords.txt file in your Configs folder?

**Comment by Vanmola** [comment]
no, just delete it ?

**Comment by Vanmola** [comment]
it work it, but i cant do it in my country just in the USA ,  :(
