### ISSUE TITLE
Still having trouble connecting 

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#742]
Hi guys I'm still facing the same problem #610 with some new error messages see the screenshot.
I'm using the Latest Build - 01.08 16.59 on a vps based in US with windows server 2012 R2 if this could help
note that the bot is working on my PC (outside US) win 10

here is the screenshot:
![snip_20160801161800](https://cloud.githubusercontent.com/assets/10819089/17298982/3dfe279e-5804-11e6-87b1-3cf701f6a5d4.png)

**Comment by JustPlaysDE** [comment]
#856
