### ISSUE TITLE
Error reloading Pokemon list

### ISSUE THREAD

**Issue by erniberni1611** [Ar1i/PokemonGo-Bot#745]
I get a exception, called "PokemonGo.RocketAPI.Exceptions.PtcOfflineException".
Are the servers down or whats going on there?

**Comment by whymk92** [comment]
same

**Comment by Synthek** [comment]
same

**Comment by erniberni1611** [comment]
I logged in into my google-account, there it works without any problems....with PTC-account it shows everytime the same exception..
