### ISSUE TITLE
Request on Auto. Incubators

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#746]
Would be nice if You could implement this feature so all the eggs can pop.

**Comment by Yahook** [comment]
It would be great to add this feature.

**Comment by abdellahaski** [comment]
Yes it would be really great
but guys suggestion should be posted here [https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/](https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/)

as Ar1i mentioned here #604
