### ISSUE TITLE
softban -> no pokestops

### ISSUE THREAD

**Issue by fav0urite** [Ar1i/PokemonGo-Bot#748]
Sometimes i get a soft ban after 15 mins and then it cant find any pokestops for a long time.
i use 200km/h , 30000 km 

how can i avoid that ?

---
[17:50:02] We cant find any PokeStops in a range of 25000m!
[17:50:02] We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying..

i closed and restarted the bot after 5 mins with soft ban.

**Comment by Bikkstar123HD** [comment]
hmmm thats right happens and soft ban method 1337 doesnt work moost of times it never did to me

**Comment by VisualBoyAdv** [comment]
you could always get another program that manually unsoftbans you like quickspin

**Comment by Euskater2** [comment]
@fav0urite why the hell are you using more than 200kmh ? xD no wonder that it detects you easier. cauz it´s not normal that a human travels with such a speed These days for normal consumer. 

use such as 50kmh or less  :) i´m using 26 ;)

**Comment by Euskater2** [comment]
@VisualBoyAdv  where to get this Programm ? i mean @Ar1i has already one inside, but an extern one ? oO

**Comment by Bikkstar123HD** [comment]
my speed is 26km/hour and 3200m range i am getting soft banned left and right just today tho no idea why

**Comment by ShutUpPvP** [comment]
Niantic updatet theyr shit, since the "lets remove pokevision" patch i am getting banned more often

**Comment by Ar1i** [comment]
Change your location!
