### ISSUE TITLE
No Pokestops near

### ISSUE THREAD

**Issue by ezilas** [Ar1i/PokemonGo-Bot#749]
I use the Location in Cantral Park, but in 95% I always get the message that there are no Pokestops in range of 15000m.

**Comment by Bikkstar123HD** [comment]
yup same here 26km/our and 3200 range

**Comment by IKnockDadsOut** [comment]
The same things happening to me. And getting softbanned after running the bot for a short while.

**Comment by abdellahaski** [comment]
I think that it happen when there are no pokestop in a range of a specific distance like 1km or something

cuz I'm having this problem when I'm using it near my house It goes the 2 nearby pokestop and it return to the default location even if there are some pokestop 5 km away even if I'm setting 200KM as  radius range

@Ar1i Please If you could help or just explain this

**Comment by ezilas** [comment]
@abdellahaski can be , but I m having the problem in Central Park and there is every 20-50m a Pokestop.

**Comment by abdellahaski** [comment]
@ezilas Yes that's a big problem but it could be just on your side because I'm using it right now on a location where there are pokestops in 50-400 meter away and it working great right now

**Comment by Ar1i** [comment]
Choose your location!
