### ISSUE TITLE
Pokecrot

### ISSUE THREAD

**Issue by thewestination** [Ar1i/PokemonGo-Bot#750]
Just wanted to let you know, the people stealing your project and selling it are called Spuc3ngine Network. Here's a link to their facebook page: https://www.facebook.com/Spuc3ngineNetwork/. If we all got together and reported them to Facebook for unauthorized use of intellectual property or something, we could pressure them to stop marketing the bot as their own. Forgive the long link, but this is one of their posts regarding Pokecrot: https://www.facebook.com/Spuc3ngineNetwork/photos/a.938611816170917.1073741828.936931259672306/1205187352846694/?type=3&theater

**Comment by Yahook** [comment]
I suggest you to write complaigns to Paypal and other payment systems where they have accounts. Tell them that these guys are stealing your intellectual property.

Also send a copy of your DMCA complaigns to their domain registrator and their hosting company. It will be difficult for them to ignore these complaigns after that.

**Comment by xhalfbakedguy** [comment]
was a known issue and the dmca takedown was sent

**Comment by Ar1i** [comment]
^this. But thanks for your awesome support!
