### ISSUE TITLE
Exception, if Poke Club Login Server down

### ISSUE THREAD

**Issue by Dliang2k** [Ar1i/PokemonGo-Bot#751]
I get this Exception, if Poke Club Login Server down

........
[18:30:21] Starting again.. But waiting 10 Seconds..
[18:30:31] Exception: System.ArgumentNullException: Der Wert darf nicht NULL sei
n.
Parametername: value
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authT
oken, AuthType authType, Double lat, Double lng, Double altitude, Requests[] cus
tomRequests) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonG
o.RocketAPI\Helpers\RequestBuilder.cs:Zeile 19.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authT
oken, AuthType authType, Double lat, Double lng, Double altitude, RequestType[]
customRequestTypes) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\P
okemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 47.
   bei PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\Ari\De
sktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:Zeile 183
.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__11.MoveNext() in C:\
Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\L
ogic.cs:Zeile 133.
[18:30:31] Starting again.. But waiting 10 Seconds..
[18:30:41] Exception: System.ArgumentNullException: Der Wert darf nicht NULL sei
n.
Parametername: value
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authT
oken, AuthType authType, Double lat, Double lng, Double altitude, Requests[] cus
tomRequests) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonG
o.RocketAPI\Helpers\RequestBuilder.cs:Zeile 19.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authT
oken, AuthType authType, Double lat, Double lng, Double altitude, RequestType[]
customRequestTypes) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\P
okemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 47.
   bei PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\Ari\De
sktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:Zeile 183
.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__11.MoveNext() in C:\
Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\L
ogic.cs:Zeile 133.
........

**Comment by Ar1i** [comment]
Hmm, will take a look but you can ignore that!
