### ISSUE TITLE
The bot can not find the pokespot

### ISSUE THREAD

**Issue by mooNN100** [Ar1i/PokemonGo-Bot#752]
The bot can not find the pokestop do so more Pokeballs normal? And a nice improvement would be to incubate the eggs auto .. Thanks again for your bot!

**Comment by ShutUpPvP** [comment]
better explenation pls.
But sounds like softban

**Comment by mooNN100** [comment]
Le bot voit les pokémons, veut les capturer mais n'ayant plus de pokéballs ne sait pas les capturer. Mais il ne détecte aucun pokéspots et donc ne ramassent aucun items.

**Comment by mooNN100** [comment]
The bot sees Pokemon, like the capture but having no Pokeballs unclear capture them. But it does not detect pokéspots and therefore pick up any items.

**Comment by Ar1i** [comment]
Change the location!
