### ISSUE TITLE
Magikarp transfer problem

### ISSUE THREAD

**Issue by alperemre** [Ar1i/PokemonGo-Bot#753]
Program some pokemons not transfer ex. magikarp

**Comment by abdellahaski** [comment]
Yes I've noticed that and also pidget sometimes

**Comment by HackerPide** [comment]
You need to untick "Keep pokemon which can be evolved". It's ticked by default in the current version.

**Comment by alperemre** [comment]
herşeyi ayarladım diğer pokemonları transfer ediyor bazen magikarp bazen voltorpları transfer etmiyor bag doluyor sonra

**Comment by HackerPide** [comment]
For some reason the transfers mostly happens if the pokemon is to be transferred and the same type of pokemon is caught.

**Comment by Ar1i** [comment]
^

**Comment by alperemre** [comment]
ww
