### ISSUE TITLE
Perfection / IV % different from other calculations

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#759]
Hi there,

The bot gives other perfection/ IV % then for example https://pokeassistant.com/main/ivcalculator
Any way to fix this? Or is the bot right and the website wrong

**Comment by FrancYescO** [comment]
for what i have tested the list UI show the same IV ... CLI is using a different calculation methode

**Comment by jordanpillefernandez** [comment]
not it"s not the same the bot one is very random compare to the other one much more perfect

**Comment by FrancYescO** [comment]
the bot one = CLI ?
the other one = UI ?

**Comment by JustPlaysDE** [comment]
^
