### ISSUE TITLE
Latest update & Crashes.

### ISSUE THREAD

**Issue by FrozGR** [Ar1i/PokemonGo-Bot#76]
After today's update, i had this unhandled exception that made my bot crash:

![image](https://cloud.githubusercontent.com/assets/12578906/17187188/e508c552-5440-11e6-8979-05d7b3fdc15a.png)

**Comment by FrozGR** [comment]
Happened 2nd time in an hour..


![image](https://cloud.githubusercontent.com/assets/12578906/17188377/694a0750-5445-11e6-863c-a8775bdbd06d.png)

**Comment by bitrape** [comment]
Seems like a simple try/catch for web requests is missing. Noticed the issue as well.

**Comment by bitrape** [comment]
Btw: Using "ExeOnly 0.4"

**Comment by infslash** [comment]
can confirm too, seems like after 45 mins or so
