### ISSUE TITLE
Using too many ItemRazzBerry

### ISSUE THREAD

**Issue by lovakosh** [Ar1i/PokemonGo-Bot#761]
Using this item almost on every pokemon over 300cp without reason.

**Comment by FrancYescO** [comment]
RazzBerry are very easy to find so why not use for every pokemon >300 with low prbability?

**Comment by lovakosh** [comment]
I had over 100 now i going under 30. So if you use a few on Pidgey with 300 cp it's a waste.
Anyway I think it's started today after the new update. until then it was fine.

**Comment by FrancYescO** [comment]
btw idk how it's possible... mine never used a razzberry

**Comment by lovakosh** [comment]
Mine neither. it's started after the update.

**Comment by xJustx** [comment]
Is it working now?

**Comment by lovakosh** [comment]
I think it's better. But it's still using berrys on Pidgey with 350-400 cp. From my side it's a waste.
If there was an option on which one's to use berrys and which one no. or limit it from specific cp it would be nice.

**Comment by xJustx** [comment]
If you have a suggestion, please post it here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
