### ISSUE TITLE
Request for standalone List to check VI and manage Pokemon

### ISSUE THREAD

**Issue by navygino** [Ar1i/PokemonGo-Bot#762]
Thank you for the great Bot and UI. It is very user friendly to me.

My buddies do not want to play the game with Bot but he really needs your List to check IV and manage the Pokemons.

Please consider to make a standalone .exe for the list.

Thank you so much!

**Comment by Quickbowjob** [comment]
Hello, i found this Pokeadvisor yesterday it can sort your Pokemons and sort them by VI stats works great.
https://www.reddit.com/r/TheSilphRoad/comments/4vdm93/pokeadvisorcom_automatic_stats_calculator_and

Would had posted it on the forum but i am not allowed on my 3 days old account didn't look into it why that is. (You have insufficient privileges to reply here.)

Anyways hf! ;)

**Comment by HSMatheus** [comment]
@Quickbowjob Really nice site, thank you!

**Comment by navygino** [comment]
Cool site and I can do it with mobile!

Thank you very much!
