### ISSUE TITLE
[Request] Auto Eggs Incubation ?

### ISSUE THREAD

**Issue by amarinediary** [Ar1i/PokemonGo-Bot#763]
Hi @Ar1i , hope everthing is fine, mus be a lot of work for you, but we appreciate it :+1: 
I would like to know if it's possible to add the auto eggs incubation to the bot, i'm sure somebody else asked already, is it already in the to do list ?
-- Regards, amarinediary

**Comment by ShutUpPvP** [comment]
Please post suggestions here, thank you! :)
https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by ShutUpPvP** [comment]
And yes, it got requested a couple times today and yesterday :)
Its on his to do list
