### ISSUE TITLE
Reloading list in guy error & check box for evolvable pokemons comeback

### ISSUE THREAD

**Issue by N4mEL3sS** [Ar1i/PokemonGo-Bot#764]
So one of the current new issues that came with the latest update is that we are not able to reload the Pokemon List, it only reloads automatically if you evolve a pokemon but if you check the checkbox with the text "Reload every ...s" it does not works because of this error: "Error reloading Pokemon List".
It's not everytime but very often.

The seccond one I have is not really an issue, it's just a suggestion whether you could please include the checkbox back in which was filtering only evolvable pokemons. That thing was nice.

**Comment by ShutUpPvP** [comment]
No error here, for pokemon list reload. Maybe u need to redownload the files.



The box for only evolvable isnt needed, u can just sort by evolvable ;)

**Comment by roynarddd** [comment]
i have the same problem but now it works by uncheck netframework 4.5 in program and feature.

**Comment by filoh** [comment]
I'm getting this error too.
How did you uncheck netframework 4.5 ?
What exactly did you do?
