### ISSUE TITLE
Is it possible to have it hatch eggs as well?

### ISSUE THREAD

**Issue by Timmiller109** [Ar1i/PokemonGo-Bot#766]
Would love to see a feature where you could incubate and hatch eggs. If this is possible would love to donate.

**Comment by HackerPide** [comment]
Hatching is already done automatically by the bot.

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
