### ISSUE TITLE
Error (Only in the Pokemon Club)

### ISSUE THREAD

**Issue by Kaeryth** [Ar1i/PokemonGo-Bot#767]
[21:13:41] Starting Execute on login server: Ptc
[21:13:41] Error: Newtonsoft.Json
[21:13:41] Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   en Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   en Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   en PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\JsonHelper.cs:línea 14
   en PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\PtcLogin.cs:línea 28
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Client.<DoPtcLogin>d__27.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:línea 154
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() en C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:línea 55
[21:13:41] Trying to Restart.
[21:13:41] Restarting in 10 Seconds.

**Comment by durnevo** [comment]
me too, for the past 8 hours~

**Comment by JustPlaysDE** [comment]
fixed
