### ISSUE TITLE
XP farming

### ISSUE THREAD

**Issue by Dexter13425** [Ar1i/PokemonGo-Bot#768]
Hey First of all great job ! 

Can you add a "FASTXP" mode ? like 180k xp per hour (like Haxton bot but haxton is horrible to config)

**Comment by agumax** [comment]
Where can u take 180k exp per hour? Can u show me

**Comment by Dexter13425** [comment]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566778-gps-locations-collection-exp-farm-cords-160k-per-hour.html

**Comment by Ar1i** [comment]
Uhm taking a look at it.. probably not.. but i will try!
