### ISSUE TITLE
[Request] Ein paar Vorschläge

### ISSUE THREAD

**Issue by Moe1992** [Ar1i/PokemonGo-Bot#77]
Hey Ar1i,
du meintest, du möchtest Vorschläge hier gepostet bekommen? Ich hätte da ein paar ;)
1. Der Bot sollte erkenntlich machen, ob ich einen Softban habe. Bis jetzt erkenne ich das nicht. Ab und zu bekomme ich als Fehlermeldung einen Haufen weißen Text, aber danach macht er irgendwie weiter. Keine Ahnung ob das dann ein Softban war oder was anderes. Wär jedenfalls interessant zu wissen ob man einen hat, was mich zu Punkt 2 führt.
2. Im Forum wurde mehrfach schon erklärt, wie ein Softban umgangen werden kann. Ich weiß nicht ob das ein Troll ist, aber angeblich soll der Softban verschwinden, wenn man (in der App) an einem Pokestop  die Münze bis zu 40 Mal dreht. Evtl. wäre es möglich dieses Verhalten zu implementieren. Dazu ist dann nämlich auch die Info wichtig/interessant, wann man einen Softban bekommt und wann er wieder weg ist.
3. Sollte man, aus welchen Gründen auch immer (bspw. weil man einem Softban entgehen will), zu einer weit entfernten Location "wandern" wollen, sollte der Bot schon auf dem Weg dorthin die Möglichkeit bieten, Pokestop und/oder Pokemon einzufangen. Sonst ist er Stunden unterwegs ohne etwas zu schaffen...

Vielleicht wurde davon schon mal etwas vorgeschlagen, ich hab mir jetzt nicht alle Posts durchgelesen.
LG Moe

**Comment by Caddyrn** [comment]
Da kann ich meine Vorschläge auch nur mit anpinnen um etwas Übersicht zu halten :) 

https://github.com/Ar1i/PokemonGo-Bot/issues/64
