### ISSUE TITLE
Still having the "PtcOfflineException" error

### ISSUE THREAD

**Issue by Yamazarashi** [Ar1i/PokemonGo-Bot#771]
How can I fix this please ? I've checked the others issues posts but found nothing

**Comment by BuDz57** [comment]
I've the same. 
Always get that :
![bug bot pokemon go](https://cloud.githubusercontent.com/assets/20780141/17306846/6f6a3010-5832-11e6-9ec7-4572747606f6.png)

**Comment by Yamazarashi** [comment]
Same. Can someone help us please ? :(
It says that the PTC servers are offline but I still can connect to the server on the mobile app

**Comment by BuDz57** [comment]
You're lucky. 
I can't connect to the server on the mobile app, but it's working with my other account (google). The main (where the bug is) is a trainer club account

**Comment by IamJull** [comment]
Waiting ideas, 2ptc acc. stopping with same message & google acc. run without problem.....

**Comment by Ar1i** [comment]
Yeah sometimes it works with PTC and sometimes not.. idk its a luck game, but its not the bot fault!

**Comment by Yamazarashi** [comment]
I know it's not but that's still weird I hope it won't do this again :')
