### ISSUE TITLE
Pokemon stats

### ISSUE THREAD

**Issue by Str315** [Ar1i/PokemonGo-Bot#772]
There is more than 250 pokemon in the game and each of them has several skills.
It's hard to remember all skills. I offer to write in the columns "Attack" and
"Special Attack" the second line as skill damage.
It will be perfect to add dps in parenthesis.

For example:
Thunderbolt
Attack 100 (23 dps)

**Comment by jordanpillefernandez** [comment]
will be awsome

**Comment by Ar1i** [comment]
Uhm, thats a suggestion.. but i will leave that open here cause its good. Will take a look at it on how to read that.
