### ISSUE TITLE
Error ptc payload etc

### ISSUE THREAD

**Issue by eclam** [Ar1i/PokemonGo-Bot#778]
![untitled](https://cloud.githubusercontent.com/assets/9125675/17307990/98fdad80-57ec-11e6-911f-47254a49c507.png)

Hey guys, this error keeps popping up lately. Just a heads up that this might turn into a bigger problem.

**Comment by IceQ1337** [comment]
It's a server issue.

**Comment by IDonated** [comment]
Are you sure? It's happening to me since I downloaded last version :\, anyway it tries to reconnect but until I restart the bot it doesn't truly start again.

**Comment by eclam** [comment]
Alright. Thanks IceQ1337 . Just wanted to make sure.

**Comment by Ar1i** [comment]
Already posted, and a server issue.. Trying to take a deeper look on how to fix that up.
