### ISSUE TITLE
Catching a Pokemon does not provides now 210 XP Please Fix that

### ISSUE THREAD

**Issue by DragonAnant** [Ar1i/PokemonGo-Bot#779]
After the new update catching a Pokemon does not provides 210 XP. Why do we still get that?
Please fix it. As no additional XP is provided for nice,great or excellent throw

**Comment by HackerPide** [comment]
Can you provide screenshot(s) please?

**Comment by HSMatheus** [comment]
@HackerPide 
![image](https://cloud.githubusercontent.com/assets/15190187/17308593/37238ed4-5811-11e6-892b-c1acfaf04dbe.png)

**Comment by DragonAnant** [comment]
As HSMatheues showed we shouldn't be getting that extra XP as that will help the Pokemon GO Developers to track us down fast.

**Comment by blahblah1227** [comment]
it might show 210xp for us but we might be only receiving 200xp. Assuming that the amount of xp actually given is server sided

**Comment by HackerPide** [comment]
@HSMatheus It would normally be like this:
100 XP - For cathing pokemon
100 XP - For excellent throw
10 XP - For curved throw
I just tested if we actually still get 210 XP and I can confirm we do. I checked from Nox App Player and in the profile page 210 XP was added after succesfull catch.

**Comment by HSMatheus** [comment]
Oh nvm, I forgot the Curve Ball, my bad... thanks HackerPide

**Comment by DragonAnant** [comment]
Guys i have manually caught a Pokemon with great and nice throws, I havent got any extra XP not sure of excellenet will someone check it out manually. You can even check this out https://m.reddit.com/r/TheSilphRoad/comments/4vfh8v/nice_great_excellent_throws_not_giving_bonus/

**Comment by Ar1i** [comment]
^
