### ISSUE TITLE
Eggs incubating while using bot

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#780]
Hi, Im using the bot, but after a few hours I opened game in a mobile phone, and I put 2 eggs on incubator.
Is there any danger on this, I mean if using the bot and then the eggs become ready to crack how bot will know? What happens if bot walked 15km with some eggs on incubator.
Then if I open real game in mobile, eggs will crack 5km after its normal behavior.
Is this suspicious to NIA? What is the experience on this?
Thanks

**Comment by HackerPide** [comment]
You should have no problem with using the bot and the pokemon go app as the bot automatically hatches the eggs if enough distance is walked(even if it is walked by the bot). But you need to manually start incubating the eggs from your pokemon go app as the bot doesnt have automatic incubating feature at the moment.

**Comment by zzzz9999** [comment]
Thanks for reply!
Kind regards
