### ISSUE TITLE
EncounterNotInRange 2

### ISSUE THREAD

**Issue by rihanboo** [Ar1i/PokemonGo-Bot#781]
So I have an issue here that was not resolved although it seems to have been closed but Im still in need of help. my old post is https://github.com/Ar1i/PokemonGo-Bot/issues/721

anyway shutupPVP i let it run for half an hour and it STILL does not work, teleporting away does not work either. im NOT softbanned because as i said earlier i can load the old build just fine and it works flawlessly. i just want to run the new version for bug fixes and new features.

**Comment by Ar1i** [comment]
Uhm, whats your Speed Settings?

**Comment by rihanboo** [comment]
50 5000

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849

**Comment by rihanboo** [comment]
fixed https://github.com/Ar1i/PokemonGo-Bot/issues/849
