### ISSUE TITLE
Restart bot request.

### ISSUE THREAD

**Issue by IDonated** [Ar1i/PokemonGo-Bot#783]
Could you add an option to restart the bot enterely to prevent it to get in loop atempting to reconnect to the PTC server? Today it stuck enfinetly like that and the only solution was to restart the bot manualy, I don't know why it couldn't reconnect but it just couldn't until you reset it manualy.

![image](https://cloud.githubusercontent.com/assets/20728445/17308735/c836dd5c-583b-11e6-85a9-8c77a6c48cf8.png)
![image](https://cloud.githubusercontent.com/assets/20728445/17308753/d3802498-583b-11e6-9125-c47da82e45a4.png)

**Comment by Synthek** [comment]
got the same problem
-.-

**Comment by Ar1i** [comment]
Uhm, will take a look..

**Comment by lailaps** [comment]
Yeah, would be great.
I had the same problems, after restart it was running normal again!

**Comment by sargathus** [comment]
i have same problem here its cant catch pokemons anymore
