### ISSUE TITLE
Auto hatch Poke-Eggs ?

### ISSUE THREAD

**Issue by Sonyc88** [Ar1i/PokemonGo-Bot#784]
Is it in future possible to auto use and hatch poke-eggs ?

Sry for my english..

**Comment by alperemre** [comment]
Yeah I want too

**Comment by madpada** [comment]
I second that... It would be nice to incorporate that little extra bit of XP gain.

**Comment by Ar1i** [comment]
Only possible when we update to latest API, we will do that in some days!
