### ISSUE TITLE
Set both Last Position and Destination

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#785]
The GUI allows to graphicaly set the Destination but not the last position.
Would be good to have both.
Plus Default Location is not explicit (nor the "walk from default position" check box)

When starting the bot after POGO, the bot Last Position is false ... thus subject to soft ban.
When loging to POGO with smartphone after using the bot, we need to wait for a delay compatible with bot last position and GPS position .... or I ask the bot to drive me back to real pos (not funny)

Reg@rds

**Comment by Ar1i** [comment]
Will take a look at it, tomorrow!

**Comment by kerkael** [comment]
Inner Map (on pokemon list) shows destination coords  ; should instead show last coords (just to see where we are on the trip)
