### ISSUE TITLE
Question : does the bot walk through walls or follow the roads and paths ?

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#786]
If I make the bot go 100km from my real position (defined by editing LastCoords.txt) at 50km/h, and a radius of 10m to be sure it will walk back, can I expect it to use roads, from google maps, or will it go straight line to its destination ?

Thanks

**Comment by madpada** [comment]
Straight line.  Ignores buildings, roads, etc...

**Comment by kerkael** [comment]
Thx - too bad it can't simulate an itinerary. It's quite obvious niantic will track such behaviour soon ... running at 50km/h straight line through roads and buildings on several km will be identified as not human.
Even at a decent speed of 5-7 km/h, getting in straight line from one pokestop to another  will be recognised.
Let's hope we will only get softbanned before the bot is improved :)

good job, still.

**Comment by IceQ1337** [comment]
They wont track walking through buildings like.. ever... The only thing they could possibly track is walking through larger waters. For the speed, they already improved their gps tracking system with the last update and it still works fine.
