### ISSUE TITLE
I don't know if it's an error or a feature

### ISSUE THREAD

**Issue by cinek19** [Ar1i/PokemonGo-Bot#787]
I had a Pokemon on a gym and with the bot I can transfer it.

What do you think?

**Comment by madpada** [comment]
That is a bug on Niantic's side of things... They are checking in-game but not on the API.  Tsk tsk tsk

**Comment by cinek19** [comment]
Like softban, no?

**Comment by Ar1i** [comment]
Nah, just a bug from their side!
