### ISSUE TITLE
Pokémon transfer doesn't work!

### ISSUE THREAD

**Issue by KiLLFR3AK** [Ar1i/PokemonGo-Bot#788]
I saw in the app that I have several duplicate pokemon. I wanted that the bot automatically transfer the pokemon. There was only one pokemon transfer, none else ... And after catching a duplicate Pokemon ist won't transfered.

**Comment by IceQ1337** [comment]
Can you show me a screenshot of your settings in the GUI ??

**Comment by sneeze18** [comment]
yup transfering not working atm

**Comment by KiLLFR3AK** [comment]
![screenshot 77](https://cloud.githubusercontent.com/assets/20781648/17310575/97a758ba-5845-11e6-8cab-75fb63c29977.png)

**Comment by IceQ1337** [comment]
Try to uncheck "Keep Pokemons which can be evolved".

**Comment by KiLLFR3AK** [comment]
Ah know it works, thank you! Have this point until now never seen xD
