### ISSUE TITLE
Farmed Eggs - not clear

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#789]
Hey there, I got 2 different info when farming at pokestop :

[23:47:57] Farmed XP: 50, Gems: 0, **Eggs: /** Items: 1 x ItemPokeBall, 1 x ItemSuperPotion, 1 x ItemGreatBall
[23:48:28] Farmed XP: 50, Gems: 0, **Eggs: Egg 0** Items: 1 x ItemPokeBall, 2 x ItemRazzBerry

Is there a difference ? between hatchable eggs and lucky eggs, for example ?

**Comment by 12348766754** [comment]
Yes.. lucky eggs -> double EXP
eggs -> walk and get a pokemon

**Comment by Ar1i** [comment]
Yes

**Comment by kerkael** [comment]
Ok, i'm not that a noob. The question was regarding the 2 different log lines in pokebot. I know the difference between the type of eggs ... I wanted to know if the bot shows them differently.
