### ISSUE TITLE
Fastest pokemon go bot ! 300pkms/h

### ISSUE THREAD

**Issue by mfron** [Ar1i/PokemonGo-Bot#791]
![botinterface](https://cloud.githubusercontent.com/assets/11887274/17310584/a3dc6a58-5845-11e6-83d1-e7a208d41a45.png)

https://github.com/mfron/PokemonGo-Bot

**Comment by CP02A** [comment]
Hey!! do not advertise... ;/

**Comment by CP02A** [comment]
Plus I think this might be a scam because you are the only on contributing to it

**Comment by supertx2** [comment]
just close this

**Comment by Ar1i** [comment]
your faggot really, hope you get what you merit.
