### ISSUE TITLE
Outside of the defined max walking radius

### ISSUE THREAD

**Issue by WIPEOUT2197** [Ar1i/PokemonGo-Bot#792]
There is a problem with the "set location" option, when I choose a location, this message appeared : http://puu.sh/qmttr/4754cc1a53.png

**Comment by CP02A** [comment]
I think that that is intentionally made like that so you wont get soft banned?

**Comment by WIPEOUT2197** [comment]
I up the speed to 300km/h and now I am soft banned :(

**Comment by KiLLFR3AK** [comment]
Try to delete your coord files

**Comment by alperemre** [comment]
enter the game normally and out account and connect again

**Comment by jerinx88** [comment]
UNBANNED
http://www.mediafire.com/download/e7f3xnd314mcwse/QuickSpin_1.2.zip

**Comment by WIPEOUT2197** [comment]
Thanks you all, so the "Outside of the defined max walking radius" is normal?
When we set new location we walk in the game to the new location?

**Comment by WIPEOUT2197** [comment]
@jerinx88 how can I get lattitude/longitude from a pokestop?

**Comment by jerinx88** [comment]
lattitude/longitude from your city, not pokestop

**Comment by WIPEOUT2197** [comment]
Ok I think it's ok, thanks you all :)
