### ISSUE TITLE
Cant Login with PTC

### ISSUE THREAD

**Issue by momo0206** [Ar1i/PokemonGo-Bot#795]
Server online but cant Login. 
![20160802_010400](https://cloud.githubusercontent.com/assets/20726632/17311640/1c175968-584d-11e6-9195-695d815feb71.jpg)

**Comment by Timmiller109** [comment]
Im having the same problem

**Comment by momo0206** [comment]
With another PTC acc it works

**Comment by IDonated** [comment]
It's the server, I can't log it with PTC as well

**Comment by IDonated** [comment]
Definetly it's not the server, can log it in my PTC account with my phone with 0 problems but bot seems to not be able to do it 

![image](https://cloud.githubusercontent.com/assets/20728445/17312259/b4fb82d6-5851-11e6-9a50-482f3897de13.png)

**Comment by momo0206** [comment]
On my Phone i cant Login with PTC too.  With another PTC acc, it works and the bot too

**Comment by IDonated** [comment]
in my main PTC account I can log it just fine with my phone, but can't log it with the bot, no idea what's happening. Could we have been banned in any way :S?

**Comment by Yamazarashi** [comment]
Same for me
I hope we're not :(

**Comment by momo0206** [comment]
I think the bot has an "unbanner".

**Comment by Yamazarashi** [comment]
It has. But then why doesn't it work ? :(

**Comment by momo0206** [comment]
I`ve no idea:/

**Comment by kurdt94** [comment]
Aaaannnddd it's back :)

**Comment by momo0206** [comment]
I am back too! But why? Could we have been banned for hours?

**Comment by Yamazarashi** [comment]
IT WORKS OMG

**Comment by Yamazarashi** [comment]
Seems like it was not from us

**Comment by Ar1i** [comment]
^cant be a bot issue, probably server
