### ISSUE TITLE
Transfert - keep high IV Pokemon instead of high CP Pokemon

### ISSUE THREAD

**Issue by shibien** [Ar1i/PokemonGo-Bot#796]
Hi Ar1i, 

I noticed when transfering mons, your incredible tool keep high PC pokemon instead of high IVs.
Is there a way to choose between PC and IV in preferences for pokemons transferts ?

For exemple, when I set 2 max same Pokemon, let's say I have 3 Weedles :
1st) CP = 120 , IV = 80%
2nd) CP = 150, IV = 45%
3rd) CP = 55 , IV = 98%

Your tool will transfert the last one, with the greatest potential when recharging it later, even if it has the lowest CP. 

Keep up the good job ! :)

**Comment by shibien** [comment]
And in my case I would prefer to keep the 1st and 3rd one and having the 2nd one transferred even if it has the highest CP among the three Weedles !

**Comment by Ar1i** [comment]
Just use max iv to transfer option :p!

**Comment by shibien** [comment]
sorry but I don't get it :/
