### ISSUE TITLE
Error Realoading Pokemon List: Out Of Memory

### ISSUE THREAD

**Issue by Juiche** [Ar1i/PokemonGo-Bot#798]
<img src="http://image.prntscr.com/image/0dfd16b1e5c2483db7cdf7b53f892116.png"</img>

reload pokemon list option not checked

**Comment by Ar1i** [comment]
Out of memory, could it be that your ram is full?

**Comment by hazmad** [comment]
I got this error earlier today, and I'm running 32 GB RAM. I downloaded it again, copied my config folder over and it worked fine again

**Comment by ElectricTaco** [comment]
Not an out of memory issue. Went back to previous release, works.

**Comment by Ar1i** [comment]
Uhm, i dont got that error with the newest Version.. so i dont really understand why that happens! Btw follow this one here, cause we already got one.. #709
