### ISSUE TITLE
Koorrdinatenwechseloption - weitere Strecken zu anderem Farmspot

### ISSUE THREAD

**Issue by altobee** [Ar1i/PokemonGo-Bot#8]
Und Idee - wäre nicht sogar ein Koordinatenwechsel tool Dings machbar ? Das man quasi die max Reisegeschwindigkeit nutzt um von A nach B zu kommen ohne Softbann zu bekommen ?

 geht mir gerade durch den Kopf wegen der Kontinentalen Raum-Zeit-Krümmung. Ich farme in Santa Monica Beach rum, aber irgendwann ist ja an den Spots (Module etc) nicht mehr viel los da die ja irgendwann ins Bett wollen... könnten wir uns jetzt theoretisch mit der Zeit zu anderen beliebten Farmspots bewegen ohne einen Bann zu kassieren wäre das nicht schlecht. Zumal man so ja auch in andere Gegenden käme (ich hab irgendwo gelesen das ja auch unterschiedliche Pokemon je nach Areal gibt (Industriegebiet/Tankstellen/Wasser/Strom etc))

 Nur so 'ne wirre Idee - vielleicht ist's auch Murks.

**Comment by crss** [comment]
Machst den Bot einfach für x Stunden aus... und startest dann neu. Bswp. HH - Berlin 3h Reisezeit. :)

Ansonsten wäre so eine Option Cool. Das man über die TelegramAPI neue Coords + Reisegeschwindigkeit (ggf. auch fest hinterlegt / optional), so das der Bot dann bswp. von HH nach Berlin mit 150km fährt.
