### ISSUE TITLE
Suggestion: Use Google Auth to login

### ISSUE THREAD

**Issue by amuessig** [Ar1i/PokemonGo-Bot#802]
Why don't you use the login with an Google Auth key instead of typing the password in clear text? 
This would be a major increase in security.

Thanks

**Comment by Ar1i** [comment]
Yeah, we used that before.. but Niantic changed something

**Comment by Turtizzle** [comment]
The bot that is available for download from chip [1] is still authenticating without password.
[1] http://www.chip.de/downloads/Pok_mon-Go-Bot_97374997.html

**Comment by Ar1i** [comment]
Uhm you sure that it still works? Cause we used something like that..

**Comment by Turtizzle** [comment]
I've just run my (still existing) copy. It evolved a Pidgey without issues, so I'd say yes, it works.

**Comment by Ar1i** [comment]
Uhm okay, i will take a look at it then.. trying to it like that! thanks for the information.

**Comment by Turtizzle** [comment]
Yea, I'm just afraid I've got no idea where the Chip-Bot comes from, but the API looks the same, so I guess I'd mention it here. Good luck :)

**Comment by Ar1i** [comment]
But you can be sure, we only send the data to google and niantic (pokemongo) servers. :)

**Comment by Turtizzle** [comment]
Well I just tested the current version of the above download and it seems they've also changed a lot. Anyway, the old version that I have on my desktop still works, so I wonder where the issues have been :/

**Comment by Ar1i** [comment]
Mhhmm, will take a look at it, and try to get a way! But i close this here, cause this is for issues only, anyways thank you!
