### ISSUE TITLE
Error catching Pokemon: Encounter Pokeman Fled

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#806]
If I get this message in red, what does it mean?

**Error catching Pokemon: Encounter Pokeman Fled**

or: **Error catching Pokemon encounter not found.**

I am using **Build - 01.08 16.59**

**Comment by Euskater2** [comment]
same here

**Comment by lailaps** [comment]
This message is new, and happens after a Pokemon was found.
I does happen to accounts > level 30 and even to an account with level 5.

**Comment by Bikkstar123HD** [comment]
i just reached level 30 and it is happening like all the time i am scared is it an issue to be worried

**Comment by Quejicas** [comment]
To my giving me this error at this time

[04:28:52] Found 1 catchable Pokemon(s).
[04:28:53] Error Catching Pokemon: EncounterNotFound

**Comment by sargathus** [comment]
i got the same problem im 24 lvl

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849
