### ISSUE TITLE
Error: Encounter Not Found for wild pokemon

### ISSUE THREAD

**Issue by lordzxil** [Ar1i/PokemonGo-Bot#808]
After a while of running (about 10 mins) I keep getting this: 

> [21:35:37] Lucky Egg still running: 11m10s
[21:35:38] Recycled 2x ItemPokeBall
[21:35:39] Error Catching Pokemon: EncounterNotFound
[21:35:40] Error Catching Pokemon: EncounterNotFound

> 

It's only started happening in the last hour or so.

**Comment by Bikkstar123HD** [comment]
yeah same i am seeing the same issue i got scared as hell

**Comment by taufik123** [comment]
yess, i also seeing the same thing, but only on several account.. whats happening ?

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849
