### ISSUE TITLE
Error catching pokemon

### ISSUE THREAD

**Issue by Synthek** [Ar1i/PokemonGo-Bot#809]
error catching pokemon encounternot found

i cant catch any pokemon what can i do

**Comment by sunit1998** [comment]
i am getting same message please do something

**Comment by Bikkstar123HD** [comment]
same here

**Comment by mik3litoris** [comment]
same here with version 1.0.4.7 otherwise version 1.0.4.9 works well

**Comment by Synthek** [comment]
i have version 1.0.5.5

**Comment by Bikkstar123HD** [comment]
i have 1.0.5.5 aswell

**Comment by KiranHenrizqa** [comment]
i have the 02.08.03.05 version and still Error Catching Pokemon: EncounterNotFound

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849
