### ISSUE TITLE
[BUG] " Auto transfer double Pokemons " funktioniert nicht mehr

### ISSUE THREAD

**Issue by Avirox** [Ar1i/PokemonGo-Bot#81]
Die Funktion " Auto transfer double Pokemons " ( wie im Titelt steht :p ) funktioniert nicht mehr.
Mein " Max CP to transfer " ist auf 9999 und das Pokemon ( bei mir Traumato ) ist auch nicht in der " to not transfer " Liste, komisch.

**Comment by Ar1i** [comment]
fixed
