### ISSUE TITLE
Error Pokemon Inventory Full

### ISSUE THREAD

**Issue by ashenbrownfox** [Ar1i/PokemonGo-Bot#812]
Is there a way to deal with this other than buying more pokemon inventory slots?
Can you set to have 3 duplicates of this pokemon, and only 1 duplicate of this other pokemon?

I have a suggestion. Allow nicknaming in the Pokemon List.

**Comment by UltraVLT** [comment]
You could favorite the ones you want to keep,since they can't be transfered when they have a fav on them.Then set the duplicate max. 1

**Comment by JustPlaysDE** [comment]
^
