### ISSUE TITLE
Bot no clear pocemons 

### ISSUE THREAD

**Issue by Dryid466** [Ar1i/PokemonGo-Bot#817]
Ночи доброй) Пишу вам с сайта покекрот, хочу сказать на счет бота, почему то не работает очистка покемонов, которые не подходят под критерий perfect 80% и Cp 1200, не хочет очищать.. Хотя ранее такой проблемы не наблюдалось
-----
Good Night ) I write to you with pokekrot site , I want to say on the bot account, why it does not work cleaning Pokémon that do not fit the criteria for the ideal 80 % and Cp 1200, does not want to clean .. While previously there was no such problem

**Comment by CP02A** [comment]
Pokecrot? The Copycat? What do you mean with "I write to you with pokekrot site"?

**Comment by CP02A** [comment]
and its PoKemons a K in english ;F

**Comment by SerBlackfyre** [comment]
Russian alphabet doesnt have the letter K, C is used for K.

However, you will get no help here with a version compiled/hosted by Pokekrot. Use the files from this host only and they will work as intended. If not we will help.

**Comment by sixmoonth** [comment]
this fb page copicat pokecrot https://web.facebook.com/Spuc3ngineNetwork ,he's selling cheat hey says got rp 30bilion/month its = $3000/mon. there's also information address & phone number lets report that page together.

**Comment by Dryid466** [comment]
Ночи доброй) Пишу вам с сайта покекрот, хочу сказать на счет бота, почему то не работает очистка покемонов, которые не подходят под критерий perfect 80% и Cp 1200, не хочет очищать.. Хотя ранее такой проблемы не наблюдалось
-----
Good Night ) I write to you with pokekrot site , I want to say on the bot account, why it does not work cleaning Pokémon that do not fit the criteria for the ideal 80 % and Cp 1200, does not want to clean .. While previously there was no such problem
