### ISSUE TITLE
How can I add a third language file?

### ISSUE THREAD

**Issue by HaydarOzturk** [Ar1i/PokemonGo-Bot#818]
I was waiting for this. So How can I add third language file into gui and for others?

**Comment by CP02A** [comment]
Make a pull request of course...

**Comment by CP02A** [comment]
well you need to know how to program for that but thats how ;)

**Comment by CP02A** [comment]
Actually spanish is already pull requested ( https://github.com/Ar1i/PokemonGo-Bot/pull/811 )

**Comment by HaydarOzturk** [comment]
I have some programming skills but I am only the begginer. If you want to help me I would be greatfull.

**Comment by CP02A** [comment]
I dont even know what programming language this is written in...
Plus I consider me as a beginner too xD

**Comment by HaydarOzturk** [comment]
It's java. I don't think it would be hard but I don't know wich files should I edit and I haven't done any pull request :D

**Comment by CP02A** [comment]
me neither so...

**Comment by HaydarOzturk** [comment]
I think I am on it. We will see when I finish this :)

**Comment by CP02A** [comment]
Good Luck ;D

**Comment by JustPlaysDE** [comment]
^
