### ISSUE TITLE
German: Kann es sein, dass der Bot nicht 100% richtig läuft?

### ISSUE THREAD

**Issue by LikeAFisch** [Ar1i/PokemonGo-Bot#819]
Sorry aber ich habe immer Pokemon mit 10-1699WP obwohl ich eingestellt habe, dass er nur Pokemon behalten soll mit mehr WP und 97% IV, doch er behält einfach irgendwelche Random Pokemon.
Davon abgesehen habe ich eingestellt, dass er auch nur bestimmte nicht versenden soll, aber diese sind dort 100% nicht dabei.
So habe ich alle 2-6h 250/250 Pokemon. Und muss sie manuell verschicken.

**Comment by CP02A** [comment]
vielleicht hast du Max duplicate falsch
Bei mir geht alles...
Meine Einstellungen:
http://imgur.com/a/OHMkS

**Comment by LikeAFisch** [comment]
Max duplicate habe ich 1 http://prntscr.com/c0h7tz

**Comment by CP02A** [comment]
keine ahnung was los ist...
sry

**Comment by UltraVLT** [comment]
hast du möglicherweise das Behalten von evolvable an?

**Comment by JustPlaysDE** [comment]
^
