### ISSUE TITLE
[Request] Add the ability to use Lucky Egg every 30 minutes instead of only when evolving

### ISSUE THREAD

**Issue by setoy** [Ar1i/PokemonGo-Bot#82]

**Comment by Ar1i** [comment]
Uhm what do mean exactly?

**Comment by setoy** [comment]
Well, currently it uses a Luck Egg only when there are evolvable pokemon. I want to use it basically all the time (every 30 minutes) to get double EP for spinning pokestops and for all other actions.

**Comment by setoy** [comment]
Implemented or discarded?
