### ISSUE TITLE
Thank and suggest

### ISSUE THREAD

**Issue by viajero1485** [Ar1i/PokemonGo-Bot#820]
Thank you very much for your work.
excellent suggestion would be like if in future updates in the list of pokemon, was ordered by id Pokemon, which would help to see what would have evolved and evolve optimal.
Again thank you very much and I hope you take into account my suggestion.
Excellent work friend!

**Comment by Ar1i** [comment]
Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
