### ISSUE TITLE
Datatables Sorting for pokemon list & Item List

### ISSUE THREAD

**Issue by copslacs** [Ar1i/PokemonGo-Bot#821]
Can you make something like multiple sorting at pokemon list form?
So, i can search pokemon with low cp and low IV. And keypad delete for transfer pokemon?
Also please add feature for list item and move item to trash.
Thanks

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
