### ISSUE TITLE
 Error Catching Pokemon: EncounterNotFound

### ISSUE THREAD

**Issue by spectrek1453** [Ar1i/PokemonGo-Bot#822]
I get this error.In the current version

**Comment by Bikkstar123HD** [comment]
hmmm if you are above level 30 u might encounter it because after level 30 catching low cp pokemons becomes harder

**Comment by Bikkstar123HD** [comment]
they fly away which gives u that message that encounter not found

**Comment by howcanihelp** [comment]
No, it's not that. If you login with you phone at the same area and try to click on a pokemon to catch him, he will disappear, that's what is giving this message. Don't really know why this is happening though

**Comment by KiranHenrizqa** [comment]
im at lvl 28 now and i have a problem with cathing pokemons to it says 
Error catching Pokemon: Encounter Pokeman Fled

or: Error catching Pokemon encounter not found.

**Comment by spectrek1453** [comment]
evet,aynı anda telefondan da girdiğim içinmiş..no problem

**Comment by howcanihelp** [comment]
This isn't the same as throwing a pokeball and it running away.
wonder if this also happens to a "regular" account...

**Comment by KiranHenrizqa** [comment]
it happens to both of my PTC and Google account

**Comment by hank621** [comment]
i have the same problem with ptc + google, lvl 20

**Comment by howcanihelp** [comment]
but you guys bot with them or just play on your phone?

**Comment by hank621** [comment]
we talk about the bot...

**Comment by howcanihelp** [comment]
Just saw a few guys mention it on other subreddit, so its not niantic's brand new antibot

**Comment by CowMadness** [comment]
Might just be a bug with the bot because I have 2 different account I use the bot with and It seems that I keep having:
[23:22:39] Error Catching Pokemon: EncounterPokemonFled
on my account which is 22.
But, I aint having any issues on my real account which is 16.
Not sure yet if it's a level issue thing or if its a bug from bot or if its a fix from Niantic.

**Comment by hank621** [comment]
For me i have two account simultaneously, lvl 20, and it's the same bug for two

**Comment by HSMatheus** [comment]
Not all but most pokemon the bot found is getting this error too here :/

**Comment by duyphuc1610** [comment]
I have same issue :( 
![untitled](https://cloud.githubusercontent.com/assets/20725565/17316145/a6d06f3c-58b0-11e6-9434-fb8c2939da66.png)

**Comment by SerBlackfyre** [comment]
@duyphuc1610 
 You should blur out your username, they can ban you by your username by watching hacking/boting forums.

**Comment by duyphuc1610** [comment]
@@ thank for that, i just delete it

**Comment by sammode** [comment]
same here out of three the bot is catching only one and i get this error. and gui is not working i cant see the pokemon list

**Comment by joeisme90** [comment]
Guys, i already try many build and the latest one has problem and not stable yet (Encounter Pokemon Fled), my advice is use the older one as i can use it without problem.

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849
