### ISSUE TITLE
error pokemon list : the remote server return an error

### ISSUE THREAD

**Issue by asawele** [Ar1i/PokemonGo-Bot#823]
![untitled](https://cloud.githubusercontent.com/assets/20785399/17315664/37da3fe6-58a0-11e6-9ecb-ccbabbd45879.png)
pls help me, i cant see my pokemon list. the bot always say the remote server return an error

**Comment by youverena** [comment]
try moving from sidney to us or uk

**Comment by asawele** [comment]
im at us now, california

**Comment by JustPlaysDE** [comment]
should be fixed
