### ISSUE TITLE
Cannot catch pokemon in new version.

### ISSUE THREAD

**Issue by SerBlackfyre** [Ar1i/PokemonGo-Bot#824]
I have been using version 1.0.2.4 for a couple days now and it works wonderfully. You know what they say if something isn't broken then don't fix it, well it kept prompting me to try the new version so I tried version 1.0.5.5.

Instantly, I was not able to catch pokemon, I kept getting the  error, "Error catching Pokemon encounter not in range" I left it run for a few minutes hoping it would iron itself out and it gave me a soft ban.

I waited the time out and went back to 1.0.2.4 and it works great. I want to use the pokemon GUI feature though. 

When will this bug be fixed? What changed in the capture coding that all of a sudden it doesnt work?

**Comment by SerBlackfyre** [comment]
edit: Wrong error: Its actually "Encounter not in range"

Its for every single pokemon. I tried version 1.0.5.5 again and again after a minute or two I got Soft Banned.

**Comment by Ar1i** [comment]
Fixed in Update probably, and please post here :) #849
