### ISSUE TITLE
Softban

### ISSUE THREAD

**Issue by CowMadness** [Ar1i/PokemonGo-Bot#825]
I was wondering something.. How many softbans can you possibly have before being banned for ever ?
Because it seems that when I use my bot (even in my town) and then use my phone to play. I get a softban. So, I was wondering if I should just stop botting on my real account.

Thanks for answering.

**Comment by SerBlackfyre** [comment]
So far niantic hasnt started perma banning but they also havent mentioned that when they do if it will be retroactive. 

If its obvious you have been cheating they might ban you permanently when they start the practice again.

I suggest whenever you bot though that you leave it for several hours before using your phone. Niantic basically watches when you login if you could realistically travel to that point between logins. If not you get a soft ban.

**Comment by Ar1i** [comment]
^
