### ISSUE TITLE
Won't catch pokemon

### ISSUE THREAD

**Issue by Burrito159** [Ar1i/PokemonGo-Bot#833]
I'm getting an error when the bot is trying to catch a pokemon. It says:

"Found 1 catchable Pokemon(s)."
"Error Catching Pokemon: EncounterNotInRange

Any ideas?

**Comment by Burrito159** [comment]
So I did some research, found out the deleting the lastcoord file doesn't work. My speed is also set to 11 khm/h

**Comment by Burrito159** [comment]
Alright, well I tried build 1.5-29.07 and it seems to be working. Collecting from pokestops as well as catching pokemon. I'll wait till it gets updated again.

Thank you for all of your work Ar1i and everyone who has helped.

**Comment by sidd1993** [comment]
can i get the link to download 1.5 -29.07 version

**Comment by Burrito159** [comment]
@sidd1993 https://github.com/Ar1i/PokemonGo-Bot/blob/a2635ef4384750b21153b5824c024b05684016a9/Builds%20Only/Build%201.5%20-%2029.07%2014.28.rar
