### ISSUE TITLE
cannot set new location?

### ISSUE THREAD

**Issue by sixmoonth** [Ar1i/PokemonGo-Bot#834]
I'm using new version and i want change to new location, previously my location in beach and i want change to middle town. after i set new location and start bot it always says "you're a outside of the define max walking radius, walking back" 
its walking back from middle town to the beach. how i can change to new location? 
i already check or unchecked start walk from default location but result always same,

**Comment by SerBlackfyre** [comment]
delete your last coordinates file in the config folder.

**Comment by sixmoonth** [comment]
ok fixed, now i can start from new location. thanks you very much

**Comment by Ar1i** [comment]
^
