### ISSUE TITLE
Please Evolves

### ISSUE THREAD

**Issue by WLMaNiaC** [Ar1i/PokemonGo-Bot#835]
Please put the button to see only the evolves avalibles... thank you on the pokemon list

**Comment by OGcpalm** [comment]
+1 was an amazing feature

**Comment by immoempe** [comment]
well you can sort them clicking Evolvable? column too

**Comment by WLMaNiaC** [comment]
u r rigth ty on the column but the button was amazing :)

**Comment by OGcpalm** [comment]
button is much better cause then you can sort by CP as well

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
