### ISSUE TITLE
Still having trouble connecting

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#836]
Guys need help here please #742

**Comment by moops44** [comment]
@abdellahaski  did you use google?
then do this 
go to close the bot, go to [https://security.google.com/settings/security/activity](url)
click on Android, delete this one, and then open the bot again, this will fix your error

**Comment by abdellahaski** [comment]
thanks but I'm using a PTC account

**Comment by xJustx** [comment]
opened again - sorry
