### ISSUE TITLE
ERROR lines

### ISSUE THREAD

**Issue by senakek** [Ar1i/PokemonGo-Bot#837]
Constantly seeing:
"Error Catching Pokemon:  EncounterPokemonFled" and
"Error Catching Pokemon:  EncounterNotFound"

Any help? This account hasn't used a bot before, no way it could be softbanned already.

**Comment by wonderland1995** [comment]
Im seeing this too.

**Comment by Bikkstar123HD** [comment]
yup i am seeing that thing too from today morning dont know whats the issue with it

**Comment by senakek** [comment]
Apparently I read in another thread/forum (can't remember) to temporarily fix this you have to change your location, but it would be nice to go back to your original area since there's a lot more Pokemon to catch in these areas.

**Comment by senakek** [comment]
Update, changed my location and had it running for about 30 mins and it started happening again

**Comment by Bikkstar123HD** [comment]
just let them run after 3-4 mins it will start ctching again the rest let us wait for AR1

**Comment by joeisme90** [comment]
Guys, i already try many build and the latest one has problem and not stable yet (Encounter Pokemon Fled), my advice is use the older one, i can use it without problem.
