### ISSUE TITLE
Error with the pokemon list for one account but not the other?

### ISSUE THREAD

**Issue by theblackmarmoset** [Ar1i/PokemonGo-Bot#839]
So when I start a bot with one of my accounts I get this error: http://prntscr.com/c0iapu

When I start a bot with another account I don't get that error.  Also on the account that I get the error the list of pokemon where you can evolve and everything seems to keep reloading.  I've tried restarting it a lot of times.  Does anyone know a fix?

**Comment by stormlolz** [comment]
Your account with the bug is on PTC and the other without bug on google ?

**Comment by IDonated** [comment]
It works fine with google, but in PTC you just get:

![image](https://cloud.githubusercontent.com/assets/20728445/17320377/93e2425a-5893-11e6-9e0e-31b3de10ebea.png)

Everytime you try to reload

**Comment by theblackmarmoset** [comment]
I get the error when I start the program.  Both accounts are on google btw.

**Comment by hendek95** [comment]
+1 i fixed framework but now taking "out of memory "

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/709
