### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by joeisme90** [Ar1i/PokemonGo-Bot#847]
Guys can i know the best speed setting and how many experience/h can you get from it?

**Comment by elenex23** [comment]
I use 48 and 1500ish meters. In a good location i typically get 60-45k xp/h. I am currently searching for a better spot in paris if someone could help me out.

**Comment by stormlolz** [comment]
Can you tell me your spot in Paris ?
Merci :)

**Comment by elenex23** [comment]
decided to settle on testing effiel tower. will post update in an hour

**Comment by Ar1i** [comment]
This is not an issue..
