### ISSUE TITLE
[BUG] Google Authentication isnt working anymore

### ISSUE THREAD

**Issue by absoluttechno** [Ar1i/PokemonGo-Bot#85]
Could you fix that?

**Comment by Otegh28** [comment]
yeah i got this problem too

**Comment by Caddyrn** [comment]
Please Chill. G-Authentification Server are down. Please wait.

**Comment by Caddyrn** [comment]
Use the older Version with authentifaction from Google. Is Worked

**Comment by par0noid** [comment]
Also got:

[12:49:51] Starting Execute on login server: Google
[12:49:52] Please visit  and enter
[12:49:52] PokemonGo Servers probably Offline?
[12:49:52] Cause we cant get a Device Code.

Version 1.0.16 works fine instead of 1.0.17

**Comment by Jordywillems** [comment]
Got the same issue, is there no way to fill in our own API key somewhere to bypass this?

**Comment by FrozGR** [comment]
They are right.

![image](https://cloud.githubusercontent.com/assets/12578906/17210860/3856d7fc-54ce-11e6-8da6-552234da22ae.png)

It's connecting if you try via your Mobile, it's failing on the bots.. it just doesn't work anymore.

**Comment by yukimorizuki** [comment]
maybe we should wait and use the older version one XD

**Comment by Jordywillems** [comment]
Older version redirects me to google's authentication page but the bot does not give me the code, would I need an even older version?

**Comment by absoluttechno** [comment]
other botcreators have already fixed that, why you dont do it ?

**Comment by Ar1i** [comment]
Which bot creator fixed that? I dont saw anyone. In the next minutes i will push an update.

**Comment by MarvinSCR** [comment]
how to install updates ??????

**Comment by MarvinSCR** [comment]
how to install the updates ??

**Comment by Ar1i** [comment]
dont be a fcking retard. Thanks Marvin. Btw its something bigger from google, need to take a deeper look.

**Comment by BerkanYildiz** [comment]
Hey, got the same issue :)

**Comment by Ar1i** [comment]
Temp fix added in newest Commit.

**Comment by Shad86** [comment]
you committed it clean? because it says there is a new version out with 1.0.1.8 but when i download i only get the highest version with 1.0,1.7

**Comment by BerkanYildiz** [comment]
![image](https://cloud.githubusercontent.com/assets/15068742/17217403/8a09a76c-54e4-11e6-97b7-fb6af186a239.png)

**Comment by itsjustnelis** [comment]
Cant even find the 1.0.1.8 download

**Comment by Ar1i** [comment]
Download the Source Build it yourself. In Client.cs you find on Line 128 the thing where you need to put in the Google Login Data.

**Comment by Shad86** [comment]
as i was reading in a forum that doesnt work if you have multiple profiles on that account

**Comment by itsjustnelis** [comment]
idk how this edit thing works well rip need to find someone who can do that for me :c

**Comment by itsjustnelis** [comment]
can someone give me the exe download cuz i cant use source idk how ....

**Comment by Cryxon** [comment]
@Ar1i Funktioniert, danke! 
Top Bot :+1:

**Comment by Kentongan** [comment]
Thanks a lot, It was very helpful 😄
