### ISSUE TITLE
PokemonInventoryFull

### ISSUE THREAD

**Issue by mazbron** [Ar1i/PokemonGo-Bot#851]
![Uploading 2016-08-01_172839.png…]()
PokemonInventoryFull, Help me -_-
Poke not transferred so I can't catch Pokemon again -_-

**Comment by stormlolz** [comment]
Restart you bot, configure it to make free space in your pokemon inventory with these options : 

Set like you want any fiels

![efzzefezzeffzezefzef2](https://cloud.githubusercontent.com/assets/20703341/17319858/d963fdda-5890-11e6-977e-de71783f1a0a.png)


Or make this option UP

![ezfaazaafaa3](https://cloud.githubusercontent.com/assets/20703341/17319873/f059b3a4-5890-11e6-9229-fb2be2c5bd15.PNG)

And transfer yourself your pokemon

**Comment by mazbron** [comment]
Already set like that mate

**Comment by thepeople03** [comment]
yeah same here im confused those options are also set for me and it still full bag? can u maybe explain more wat each options mean? every so often it would transfer 2 pf the same pokemons idk why help please?

**Comment by stormlolz** [comment]
can you send your export xls of your pokemon and your settings ?

**Comment by Ar1i** [comment]
Disable keep pokemon that can be evolved
