### ISSUE TITLE
can some pls explain that percentage thing?

### ISSUE THREAD

**Issue by sargathus** [Ar1i/PokemonGo-Bot#852]
i really dont that percentage think ? is it about evolve or power up or what is mean ?

**Comment by stormlolz** [comment]
It's the % of perfection of your pokemon

Every pokemon have different stats

Individual Values
Three values 0-15
Defensive/offensive/stamina

A pokemon 100% was perfect 15/15/15

You can have a pokemon with higt CP, but low IV.. it's not optimize
Priorize to up in CP pokemon with HIGT IV (90% +), your pokemon become most powered

I can't explain that with more precision with my bad english, tell to google

**Comment by Ar1i** [comment]
^
