### ISSUE TITLE
Save Selected Language in Config.txt

### ISSUE THREAD

**Issue by subix** [Ar1i/PokemonGo-Bot#853]
Please Save the selected Language in Config txt
On restart the same language should be loaded!

**Comment by HaydarOzturk** [comment]
I don't think it's really neccasry. There are flags with just one click but it's Ar1i's decision :)

**Comment by subix** [comment]
But it aint very hard work to do add this feature ;)

**Comment by subix** [comment]
If other languages will be added soon it would be helpful

**Comment by HaydarOzturk** [comment]
Yes I didn't think bigger as you do at first but you are right.

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
