### ISSUE TITLE
Pokemon List 

### ISSUE THREAD

**Issue by Ckoltuk** [Ar1i/PokemonGo-Bot#855]
I have an error when i open up bot. It works perfect but pokemon list isnt. It gives me the error code 403. 
Error reloading Pokemon list : Server returns an error: (403) Forbidden

**Comment by lailaps** [comment]
Try again, after 2 or 3 times it should work.

**Comment by hendek95** [comment]
it shouldn't work. i have same error. i guess about microsoft or connection you can look #760

**Comment by Ar1i** [comment]
^
