### ISSUE TITLE
NO Issue, but a Fix for Connection Error [ GOOGLE ONLY ]

### ISSUE THREAD

**Issue by moops44** [Ar1i/PokemonGo-Bot#856]
If you have an error like this with your GOOGLE account
![error](https://cloud.githubusercontent.com/assets/10819089/17298982/3dfe279e-5804-11e6-87b1-3cf701f6a5d4.png)

close the bot, go to https://security.google.com/settings/security/activity , login to your account
click on Android, delete this one 
![delete](https://cloud.githubusercontent.com/assets/20789896/17321573/8cb5acf0-5899-11e6-8f47-84e8d91ef770.PNG)
, and then open the bot again, this will fix your error

**Comment by sufficey** [comment]
Didn't work for me.

**Comment by mathiaas** [comment]
What @sufficey said.
