### ISSUE TITLE
what should I download?

### ISSUE THREAD

**Issue by emilie253** [Ar1i/PokemonGo-Bot#857]
Hello, when i see "Ar1i/PokemonGo-Bot", i see a lof of folder : 

- .vs
- Builds Only
- PokemonGo.RocketAPI.Console
- PokemonGo.RocketAPI.Logic
- PokemonGo.RocketAPI

i use  " Builds Only" and it works, but other folders, what is it???

thank you :)

**Comment by Ar1i** [comment]
That source, you dont need that!

**Comment by emilie253** [comment]
Ok ty :)

you know why i have "error pokemon list, insufissante memory?"??
