### ISSUE TITLE
Snipe

### ISSUE THREAD

**Issue by Doberok** [Ar1i/PokemonGo-Bot#858]
whether it is possible to add in the GUI interface to something that potodibii http://spawns.sebastienvercammen.be/ pokesnipe and below the line for catching Pokémon , it would be cool

**Comment by durnevo** [comment]
@Ar1i  should use pokesnipers.com/api/v1/pokemon.json  and make the bot teleport to them, catch them without moving, then teleport back to original position to avoid the softban.

**Comment by Excruciator23** [comment]
Yeah sounds real awesome, would be mad if that could be implemented !

**Comment by Ar1i** [comment]
Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
