### ISSUE TITLE
Need a clear answer about transfer priority iv>cp

### ISSUE THREAD

**Issue by elenex23** [Ar1i/PokemonGo-Bot#859]
I need to make sure I am transferring pokemon with the lowest iv and not even calculate cp when transferring. I stare at the scripts a lot but can't find a clear sign that satisfies me. Please advise and thank you Ari for amazingness. Can we please rename pokemon from GUI?

**Comment by Ar1i** [comment]
Yeah, just put CP on like 3000k and IV like 90% everything under 90% iv and 3000cp will be transfered

Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
