### ISSUE TITLE
[Request] When discart a pokemon you control the IVs??

### ISSUE THREAD

**Issue by ciabo18** [Ar1i/PokemonGo-Bot#86]
The IVs of the pokemon is very important. One charmender with 200CP and 100% IVs is better then one with 600CP and 70% IVs. Can the bot control that stat before discart a pokemon?

**Comment by par0noid** [comment]
I'm sorry but can you explain IV? I don't know what it is

**Comment by ciabo18** [comment]
IV=individual values  divided into three categories attack/defense/speed. Max at 15/15/15 is 100%. The CP don't consider this stats

**Comment by par0noid** [comment]
Oh, i never mind something like individual values

**Comment by ciabo18** [comment]
There is some "IV Checker" for pokemon go on github if you want to see how IVs work

**Comment by Ar1i** [comment]
Will put that in after Google works again.

**Comment by Ar1i** [comment]
#143
