### ISSUE TITLE
Suggestion : sort options for pokemon lists & join the 3 scroll bars

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#860]
Hi, in the GUI I'm looking for ages for the pokemon names ... especially 'cause I play in french and I don't know'em all names in english.
_In the initial window_ (not in the GUI):
- Would be great to sort the pokemon by name (plus index#).
- Would be great to have the not-to-transfer / not-to-catch / to evolve scroll together (or propose a unique list with 3 checkboxes)
Reg@rds

**Comment by IceQ1337** [comment]
Sorting by name is allready possible? Just click on the table head.

**Comment by kerkael** [comment]
I'm talking about the launch & settings window, not about the GUI once the bot is launched.
Where I can specify which pokemons can be skipped / transfered / not captured ....

**Comment by IceQ1337** [comment]
Ah, got it now :/
I will probably take a look at this later.

**Comment by Ar1i** [comment]
Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
