### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by DarkEXRaVen** [Ar1i/PokemonGo-Bot#862]
Function that would be very useful to add a button stop bot existing coordinates, so you can say, look through the list of Pokémon and make easy transfers, if I wish to say to do it manually, and then click to continue, so he did not start completely anew, and I began where it left off

**Comment by IDonated** [comment]
That would be trully nice

**Comment by Ar1i** [comment]
Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
