### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#863]
I think there should be a new function to incubate the eggs. its too hard to open the game after every 15-30 mins and add new egg to incubate so i request to add the egg incubate feature if u can

**Comment by Excruciator23** [comment]
Yeah I also wuld love that - and of course a notification in a new color in the log, wich Pokemon hatched and its stats !

**Comment by Ar1i** [comment]
Please post that here, cause its not an Issue :S https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
