### ISSUE TITLE
AR1 the new version u just put up crashes instantly  no config file shown (BUG CONFIRMED )

### ISSUE THREAD

**Issue by Bikkstar123HD** [Ar1i/PokemonGo-Bot#864]
not responding on start

**Comment by Ar1i** [comment]
Not crashing for me.. so it must be your fault

**Comment by sunit1998** [comment]
delete the files and extract again and restart ur pc worked for me

**Comment by Bikkstar123HD** [comment]
wait let me show u 
![proof](https://cloud.githubusercontent.com/assets/20752330/17324951/a4bc1172-58c6-11e6-8fd9-4f59bb9e8ba2.png)

**Comment by Ar1i** [comment]
Try to delete the Configs

**Comment by Euskater2** [comment]
same here http://puu.sh/qn1Fe/60288f3d8e.png

**Comment by Bikkstar123HD** [comment]
okay let me try the fix again 
 thanks i will post u the result in a minute

**Comment by Bikkstar123HD** [comment]
well i dont even get a config file because it crashes as i pop up the exe

**Comment by Synthek** [comment]
same too

**Comment by kazantip151** [comment]
Me too, i have sam crash... no config file. Extracted 3 times

**Comment by Rolzy2** [comment]
same here it doesn't start... looks like there's an issue with the file ari\desktop something

**Comment by coreAIM** [comment]
same , dont even get the config folder

**Comment by Ar1i** [comment]
Uploading a Update!

**Comment by Rolzy2** [comment]
thank you for your work, it's nice

**Comment by Bikkstar123HD** [comment]
thanks AR1 its very great how u respond evrything soo fast u the best

**Comment by brian13mtz** [comment]
thanks

**Comment by Ar1i** [comment]
Should be fixed! Redownload.

**Comment by sammode** [comment]
no its not fixed

**Comment by Bikkstar123HD** [comment]
let me check imma post u with an update on this

**Comment by Euskater2** [comment]
it´s fixed for me now :)

**Comment by Bikkstar123HD** [comment]
yes it is fixed AR1 thabks for ur quick response clap clap clap

**Comment by Ar1i** [comment]
Good!
