### ISSUE TITLE
whats wrong with new update

### ISSUE THREAD

**Issue by Tracynew** [Ar1i/PokemonGo-Bot#866]
i was updated  my bot

but 
![screenshot_3](https://cloud.githubusercontent.com/assets/20121285/17324988/09b9b9a8-585e-11e6-8b7b-85194b7c29f6.png)

can you help me??

**Comment by Tracynew** [comment]
i still use older version

![screenshot_1](https://cloud.githubusercontent.com/assets/20121285/17325054/56c9a424-585e-11e6-8c78-ec4d49b3e5d6.png)

**Comment by Ar1i** [comment]
Updating, fixing that then

**Comment by Bikkstar123HD** [comment]
thanks AR1 peace take your time

**Comment by sammode** [comment]
same prob

**Comment by Ar1i** [comment]
Redownload, should be fixed.
