### ISSUE TITLE
Add password encryption

### ISSUE THREAD

**Issue by Dickhead0** [Ar1i/PokemonGo-Bot#867]
Please use password encryption and decryption.
My Gmail account password is shown in config file and i don't see it as a secure means of storing such sensitive data.

Here is a text encryption and decryption using AES method.  It is in VB.Net though so you must convert it into C#. 
Please use it to encrypt passwords while storing them and decrypting them when needed.
And please provide a link from where i can contact you. 
I tried to edit your code but it shows 40+ errors while compiling.
I even used Nuget in VS2013 to install missing packages but the problem remains the same.
 
---------------------------Code------------------------------------------

Public Function AES_Encrypt(ByVal input As String, ByVal pass As String) As String
        Dim AES As New System.Security.Cryptography.RijndaelManaged
        Dim Hash_AES As New System.Security.Cryptography.MD5CryptoServiceProvider
        Dim encrypted As String = ""
        Try
            Dim hash(31) As Byte
            Dim temp As Byte() = Hash_AES.ComputeHash(System.Text.ASCIIEncoding.ASCII.GetBytes(pass))
            Array.Copy(temp, 0, hash, 0, 20)
            Array.Copy(temp, 0, hash, 19, 20)
            AES.Key = hash
            AES.Mode = Security.Cryptography.CipherMode.ECB
            Dim DESEncrypter As System.Security.Cryptography.ICryptoTransform = AES.CreateEncryptor
            Dim Buffer As Byte() = System.Text.ASCIIEncoding.ASCII.GetBytes(input)
            encrypted = Convert.ToBase64String(DESEncrypter.TransformFinalBlock(Buffer, 0, Buffer.Length))
            Return encrypted
        Catch ex As Exception
        End Try
    End Function

    Public Function AES_Decrypt(ByVal input As String, ByVal pass As String) As String
        Dim AES As New System.Security.Cryptography.RijndaelManaged
        Dim Hash_AES As New System.Security.Cryptography.MD5CryptoServiceProvider
        Dim decrypted As String = ""
        Try
            Dim hash(31) As Byte
            Dim temp As Byte() = Hash_AES.ComputeHash(System.Text.ASCIIEncoding.ASCII.GetBytes(pass))
            Array.Copy(temp, 0, hash, 0, 20)
            Array.Copy(temp, 0, hash, 19, 20)
            AES.Key = hash
            AES.Mode = Security.Cryptography.CipherMode.ECB
            Dim DESDecrypter As System.Security.Cryptography.ICryptoTransform = AES.CreateDecryptor
            Dim Buffer As Byte() = Convert.FromBase64String(input)
            decrypted = System.Text.ASCIIEncoding.ASCII.GetString(DESDecrypter.TransformFinalBlock(Buffer, 0, Buffer.Length))
            Return decrypted
        Catch ex As Exception
        End Try
    End Function

**Comment by Ar1i** [comment]
Hmm its pretty useless, if you can read the code directly from the source.. but yeah your right not the best with plaintext password. editing that.

**Comment by Dickhead0** [comment]
you can modify the 
Array.Copy(temp, 0, hash, 0, 20)
 Array.Copy(temp, 0, hash, 19, 20)

19 and 20
from the code to make the encryption anonymus.

**Comment by Dickhead0** [comment]
But you have to modify the decrypt code too(In the same place.)

**Comment by Logxn** [comment]
You need to modify the whole freakin code.
Its written in C# not Visual Basic :D

**Comment by Ar1i** [comment]
Btw you need Visual Studio 2015 then you wont get that errors

**Comment by Dickhead0** [comment]
I will convert it for you then

**Comment by Logxn** [comment]
nanana, you better wont use an online converter!

**Comment by Dickhead0** [comment]
public string AES_Encrypt(string input, string pass)
{
	System.Security.Cryptography.RijndaelManaged AES = new System.Security.Cryptography.RijndaelManaged();
	System.Security.Cryptography.MD5CryptoServiceProvider Hash_AES = new System.Security.Cryptography.MD5CryptoServiceProvider();
	string encrypted = "";
	try {
		byte[] hash = new byte[32];
		byte[] temp = Hash_AES.ComputeHash(System.Text.ASCIIEncoding.ASCII.GetBytes(pass));
		Array.Copy(temp, 0, hash, 0, 20);
		Array.Copy(temp, 0, hash, 19, 20);
		AES.Key = hash;
		AES.Mode = Security.Cryptography.CipherMode.ECB;
		System.Security.Cryptography.ICryptoTransform DESEncrypter = AES.CreateEncryptor;
		byte[] Buffer = System.Text.ASCIIEncoding.ASCII.GetBytes(input);
		encrypted = Convert.ToBase64String(DESEncrypter.TransformFinalBlock(Buffer, 0, Buffer.Length));
		return encrypted;
	} catch (Exception ex) {
	}
}

public string AES_Decrypt(string input, string pass)
{
	System.Security.Cryptography.RijndaelManaged AES = new System.Security.Cryptography.RijndaelManaged();
	System.Security.Cryptography.MD5CryptoServiceProvider Hash_AES = new System.Security.Cryptography.MD5CryptoServiceProvider();
	string decrypted = "";
	try {
		byte[] hash = new byte[32];
		byte[] temp = Hash_AES.ComputeHash(System.Text.ASCIIEncoding.ASCII.GetBytes(pass));
		Array.Copy(temp, 0, hash, 0, 20);
		Array.Copy(temp, 0, hash, 19, 20);
		AES.Key = hash;
		AES.Mode = Security.Cryptography.CipherMode.ECB;
		System.Security.Cryptography.ICryptoTransform DESDecrypter = AES.CreateDecryptor;
		byte[] Buffer = Convert.FromBase64String(input);
		decrypted = System.Text.ASCIIEncoding.ASCII.GetString(DESDecrypter.TransformFinalBlock(Buffer, 0, Buffer.Length));
		return decrypted;
	} catch (Exception ex) {
	}
}

**Comment by Dickhead0** [comment]
Did it with online converter

**Comment by Logxn** [comment]
I SAID NO!

**Comment by Dickhead0** [comment]
i used http://converter.telerik.com/ to convert it

**Comment by Logxn** [comment]
No!

**Comment by Dickhead0** [comment]
OK

**Comment by Dickhead0** [comment]
Shall i delete the above codes?

**Comment by Ar1i** [comment]
everything is fine men haha

**Comment by Logxn** [comment]
This is clean code.

  static void AES_Decrypt(string pass, string input, string decrypted)
        {
            RijndaelManaged aes = new RijndaelManaged();
            MD5CryptoServiceProvider hash_aes = new MD5CryptoServiceProvider();
            ICryptoTransform DESDecrypter = aes.CreateDecryptor();
            byte[] buffer = Convert.FromBase64String(input);

            decrypted = "";

            try
            {
                byte[] hash = new byte[31];
                byte[] temp = hash_aes.ComputeHash(ASCIIEncoding.ASCII.GetBytes(pass));

                Array.Copy(temp, 0, hash, 0, 20);
                Array.Copy(temp, 0, hash, 19, 20);

                aes.Key = hash;
                aes.Mode = CipherMode.ECB;

                decrypted = ASCIIEncoding.ASCII.GetString(DESDecrypter.TransformFinalBlock(buffer, 0, buffer.Length));
            }
            catch (Exception ex)
            {
                Console.WriteLine("Fag error: " + ex.Message);
                Console.Read();
            }
        }

**Comment by Dickhead0** [comment]
Thanks for providing it.

**Comment by Logxn** [comment]
No problem man c:
