### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by zipippino** [Ar1i/PokemonGo-Bot#868]
Hi, smone can explain me about "telegram" zone on the bot. What should it do?

**Comment by IDonated** [comment]
It should let you see your live stats, stats, etc. on telegram (a chat application). If you want to see it right into action I'd reccomend you this video:
https://www.youtube.com/watch?v=FO-M9cTARGU
It's on german but you will understand it anyway, hope it helps.

**Comment by zipippino** [comment]
Ok thanks

Sent by Francesco Buccoliero's iPhone 

**Comment by JustPlaysDE** [comment]
^
