### ISSUE TITLE
forbidden error reloading pokemon list

### ISSUE THREAD

**Issue by sammode** [Ar1i/PokemonGo-Bot#869]
i cant see any pokemon in the gui

**Comment by Ar1i** [comment]
Could you add a screenshot?

**Comment by devilexclonz22** [comment]
this is arl1 ...
![1](https://cloud.githubusercontent.com/assets/20783162/17325553/657a40f0-58d6-11e6-92b6-c834c6a1b1e9.jpg)

**Comment by Ar1i** [comment]
Hmm got an Idea probably, testing it and updating a new version. Gimme 5~ minutes.

**Comment by Bikkstar123HD** [comment]
no issue like that for me

**Comment by devilexclonz22** [comment]
okee goodluck for you arli :+1:

**Comment by UgaBugaBoo** [comment]
"Error reloading Pokemon list: The remote server returned an error: (403) Forbidden."

**Comment by Ar1i** [comment]
@devilexclonz22 @UgaBugaBoo @sammode try to download the newest build and give me a response if it works or not!

**Comment by IDonated** [comment]
@Ar1i I got this error everytime I try to get my poke list: (in on a PTC account):

![image](https://cloud.githubusercontent.com/assets/20728445/17325809/fe8fd5ee-58ad-11e6-9798-ac40fd4fda68.png)

**Comment by UgaBugaBoo** [comment]
@Ar1i  Works fine for me now

**Comment by devilexclonz22** [comment]
@Ar1i works .. thanks ^_^

**Comment by Ar1i** [comment]
@IDonated your ram is full?

**Comment by devilexclonz22** [comment]
@Ar1i always show the command , ar1i ... why ? hmm
![2](https://cloud.githubusercontent.com/assets/20783162/17326078/4135adb2-58d9-11e6-97e4-84039e19e967.jpg)

**Comment by Ar1i** [comment]
Uhm taking a look at it, 1 sec is my server probably.

**Comment by IDonated** [comment]
@Ar1i my ram? nope, it's not, at least I think so, how could I know?

**Comment by Ar1i** [comment]
@IDonated open task manager

**Comment by IDonated** [comment]
@Ar1i it says more than 50% of my ram is available (Total: 8121, in cache: 3,4k, available, 4844, free: 1.475) odd

**Comment by UgaBugaBoo** [comment]
Now this is happening [http://i.imgur.com/IEDxvKp.png](url)

**Comment by UgaBugaBoo** [comment]
This keep happening 
![vncviewerplus_2016-08-02_17-04-01](https://cloud.githubusercontent.com/assets/7885525/17326450/4fda8bd6-58d3-11e6-9523-fef6a0dd7eae.png)

**Comment by Ar1i** [comment]
@UgaBugaBoo should be fixed, downloading all images to my server.. needs some time tho!

**Comment by IDonated** [comment]
@Ar1i I don't know if this would help but I'd post it anyway:

![image](https://cloud.githubusercontent.com/assets/20728445/17326619/c19e81e4-58b2-11e6-877f-87bab8ed0c86.png)

**Comment by Elmander31** [comment]
Hello, 

Can I help you to translate the program in french ? 
Can you tell me how do to it ?

**Comment by sammode** [comment]
It worked thanks a lot

**Comment by PuertaOscura** [comment]
It didnt work

**Comment by Ar1i** [comment]
Closing this here, trying to fix the memory leak error

**Comment by John6011** [comment]
![capture](https://cloud.githubusercontent.com/assets/20890501/17463989/74007e9e-5d06-11e6-9c1f-3a9223bc5082.PNG)
What is the problem?
