### ISSUE TITLE
Version 1.0.1.8

### ISSUE THREAD

**Issue by Lukipow** [Ar1i/PokemonGo-Bot#87]
Sorry Guys, I think I am kinda blind, how do I get Version 1.0.1.8 I have 1.0.1.7 and it always says me I should update, maybe you could link me the version

**Comment by RicochetT** [comment]
I think the update is supposed to be here: https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only

But he hasn't updated in 3 hours.

**Comment by Lukipow** [comment]
ye, but when I download the Exe-Only, I still have 1.0.1.7 somehow

**Comment by Lukipow** [comment]
but thanks anyways

**Comment by WGuage** [comment]
i have 1.0.1.8 and its working

**Comment by Ar1i** [comment]
Exe Only is not always up2date.

**Comment by Lukipow** [comment]
where do I get the update then?

**Comment by TMaddox** [comment]
compile it
