### ISSUE TITLE
Your Google Account uses 2FA ?

### ISSUE THREAD

**Issue by Shikar257** [Ar1i/PokemonGo-Bot#871]
I cant login into my Google account and I need to make an app password but I dont know how

**Comment by Bikkstar123HD** [comment]
it wwill automatically take u there make an app password and replace it in bot in the password folder

**Comment by Shikar257** [comment]
For which App should I make the app password ?

**Comment by Bikkstar123HD** [comment]
none just name it anything i mean choose other and click generate password it will give u a 16 digit code replce it in password columnin the exe console

**Comment by markheumueller** [comment]
Hello,
I have the same problem. 2FA is disabled on my google account (dont want to activate it). But he always shows me the message. Any idea?

**Comment by markheumueller** [comment]
ok was apparently an error by google . I've enabled 2FA and disabled it later , then it worked .
