### ISSUE TITLE
Pokeball Issue 

### ISSUE THREAD

**Issue by Excruciator23** [Ar1i/PokemonGo-Bot#872]
@Ar1i 
I have set my inventory count for pokeballs to 0, but when the bot encounters a pokestop and a Pokemon right after he sometimes has not thrown away the pokeball yet and tries catching the pokemon with it - which always results in the pokemon fleeing because the sucess chance is so low - could you sharpen the throw away function so it always works or add a "use ball type x only" Function in the Guy under the items section ?

That would be awesome, thanks !

**Comment by Coded1337** [comment]
I have the same issue, I know the bot uses certain balls for certain pokemon, but should also use another ball if out of a certain ball.

**Comment by Ar1i** [comment]
Hmm will take a look at it, gimme a minute.

**Comment by Ar1i** [comment]
fixed in the update. if not open a new issue please!
