### ISSUE TITLE
Socket Error exception

### ISSUE THREAD

**Issue by Dickhead0** [Ar1i/PokemonGo-Bot#873]
I get this error very often. can you fix this. or display a simple red message in console explaining it.
rather than showing the whole bunch of error lines.

https://cloud.githubusercontent.com/assets/20767591/17325537/dcdaaf14-58cb-11e6-887c-db1e129cc1cb.png

**Comment by Logxn** [comment]
Means the Servers are down.

**Comment by Ar1i** [comment]
you can ignore that
