### ISSUE TITLE
French languages

### ISSUE THREAD

**Issue by 4lex42** [Ar1i/PokemonGo-Bot#874]
Can you add the french language please

**Comment by emilie253** [comment]
bof tu n'en as pas vraiment besoin pour un petit bot ainsi ^^

**Comment by Ar1i** [comment]
i cant speak french, so i cant add it

**Comment by emilie253** [comment]
you make like us when we need to speak french : google traduction :D. But i think most important is auto eggs, dont worry for french langage x) ^^

**Comment by Elmander31** [comment]
If you want, i can translate in french. 

I just need to know which files to translate.

**Comment by stormlolz** [comment]
Send the list of words to translate, and I do the french translate

for pokemon I have already post : 

https://github.com/Ar1i/PokemonGo-Bot/issues/89

**Comment by Ayrom** [comment]
Power Up / Full Power Up / Move Radius 


That's it for me

**Comment by stormlolz** [comment]
Power Up : "Recharger"
Full Power Up : "Recharger complètement"
Move Radius : "Rayon de mouvement"

**Comment by Dexter13425** [comment]
I have translate one .json how I can send it ?

**Comment by stormlolz** [comment]
Merci ! joli travail

petite rectification:

"infoline1":"Ce Bot est totalement gratuit et Open-Source! Si vous avez pay**é**, annulez le payement.",

**Comment by Gunjha** [comment]
merci Storm j'arrivais pas a faire une phrase correcte :)

**Comment by Ar1i** [comment]
So what now? which translation is correct? haha

**Comment by Dexter13425** [comment]
"accountType":"Type de compte:",
"username":"Nom d'utilisateur:",
"password":"Mot de passe:",
"locationSettings":"Paramètres de Localisation",
"speed":"Vitesse:",
"moveRadius":"Périmètre:",
"meters":"Metres",
"startFromDefaultLocation":"Commencer à marcher de la position initiale",
"botSettings":"Paramètres du Bot",
"autoTransferDoublePokemon":"Transfert automatique des doublons",
"maxDupPokemon":"Max. de doublons Pokemon",
"maxCPtransfer":"Max. PC à transférer:",
"maxIVtransfer":"Max. IV à transférer:",
"telegramSettings":"Paramètres du Telegram",
"infoline1":"Ce Bot est totalement gratuit et Open-Source! Si vous avez payé, annulez le payement.",
"infoline2":"Si vous avez un soucis en rapport avec 'Pokecrot', dites leur que le Bot a été volé.",
"maxPokeballs":"Max. Poké Ball:",
"maxGreatballs":"Max. Super Ball:",
"maxUltraballs":"Max. Hyper Ball:",
"maxMasterballs":"Max. Master Ball:",
"maxRevives":"Max. Rappel:",
"maxTopRevives":"Max. Rappel-Max:",
"maxPotions":"Max. Potion:",
"maxSuperpotions":"Max. Super Potion:",
"maxHyperpotions":"Max. Hyper Potion:",
"maxToppotions":"Max. Potion Max:",
"maxRazzberrys":"Max. Baie Framby:",
"totalCount":"Total:",
"pokemonNotToTransfer":"Pokemon - A ne pas transférer",
"selectAll":"Selectionner tout",
"pokemonNotToCatch":"Pokemons - A ne pas attraper",
"pokemonNotToEvolve":"Pokemons - A ne pas évoluer",
"saveConfig":"Sauvegarder la configuration / Démarrer le Bot",
"otherSettings":"Autres paramètres",
"useLuckyeggAtEvolve":"Utiliser oeuf chance pour les évolutions",
"germanPokemonNames":"Noms allemands pour les Pokémons",
"useIncese":"Utiliser un encens toutes les 30min",
"evolvePokemonIfEnoughCandy":"Evoluer les Pokémons si assez de bonbons",
"enablePokemonListGUI":"Activer Liste GUI Pokémon",
"keepPokemonWhichCanBeEvolved":"Conserver les Pokémons pouvant évoluer"
}

that's the good :D

**Comment by Gunjha** [comment]
And for the pokemon list interface :+1: 
Reload = Actualiser
Evolve = Evoluer
PowerUp = Recharger
Full-PowerUp = Recharger à fond
Transfer = Transférer

do you want the french list for the pokemon's names ?
https://github.com/Ar1i/PokemonGo-Bot/issues/89

**Comment by Ar1i** [comment]
Adding first the normal GUI Language, closing that. We will put an Update out then you can translate more :p

**Comment by Dexter13425** [comment]
French -->Eng
001 Bulbizarre Bulbasaur	
002	Herbizarre Ivysaur	
003	Florizarre	Venusaur	
004	004	Salamèche	Charmander	
005	005	Reptincel	Charmeleon	
006	006	Dracaufeu	Charizard
007	007	Carapuce	Squirtle	
008	008	Carabaffe	Wartortle	
009	009	Tortank	Blastoise	
010	010	Chenipan	Caterpie	
011	011	Chrysacier	Metapod	
012	012	Papilusion	Butterfree
013	013	Aspicot	Weedle		
014	014	Coconfort	Kakuna	
015	015	Dardargnan	Beedrill	
016	016	Roucool	Pidgey		
017	017	Roucoups	Pidgeotto
018	018	Roucarnage	Pidgeot	
019	019	Rattata	Rattata	
020	020	Rattatac	Raticate	
021	021	Piafabec	Spearow	
022	022	Rapasdepic	Fearow	
023	023	Abo	Ekans	
024	024	Arbok	Arbok	
025	025	Pikachu	Pikachu	
026	026	Raichu	Raichu	
027	027	Sabelette	Sandshrew	
028	028	Sablaireau	Sandslash	
029	029	Nidoran♀	
030	030	Nidorina	
031	031	Nidoqueen	
032	032	Nidoran♂
033	033	Nidorino	
034	034	Nidoking	
035	035	Mélofée	Clefairy	
036	036	Mélodelfe	Clefable	
037	037	Goupix	Vulpix	
038	038	Feunard	Ninetales	n
039	039	Rondoudou	Jigglypuff	
040	040	Grodoudou	Wigglytuff	
041	041	Nosferapti	Zubat	
042	042	Nosferalto	Golbat	
043	043	Mystherbe	Oddish	
044	044	Ortide	Gloom	
045	045	Rafflesia	Vileplume	
046	046	Paras	Paras	
047	047	Parasect	Parasect	
048	048	Mimitoss	Venonat	
049	049	Aéromite	Venomoth	
050	050	Taupiqueur	Diglett	
051	051	Triopikeur	Dugtrio	


052	052	Miaouss	Meowth	
053	053	Persian	Persian	
054	054	Psykokwak	Psyduck	
055	055	Akwakwak	Golduck	
056	056	Férosinge	Mankey	
057	057	Colossinge	Primeape	
058	058	Caninos	Growlithe	
059	059	Arcanin	Arcanine	
060	060	Ptitard	Poliwag	
061	061	Têtarte	Poliwhirl	
062	062	Tartard	Poliwrath	
063 Abra Abra
064	064	Kadabra	Kadabra
065	065	Alakazam	Alakazam	
066	066	Machoc	Machop	
067	067	Machopeur	Machoke	
068	068	Mackogneur	Machamp	
069	069	Chétiflor	Bellsprout	
070	070	Boustiflor	Weepinbell	
071	071	Empiflor	Victreebel	
072	072	Tentacool	Tentacool	
073	073	Tentacruel	Tentacruel	
074	074	Racaillou	Geodude	
075	075	Gravalanch	Graveler	
076	076	Grolem	Golem	
077	077	Ponyta	Ponyta	
078	078	Galopa	Rapidash	
079	079	Ramoloss	Slowpoke	
080	080	Flagadoss 	Slowbro	
081	081	Magnéti	Magnemite	
082	082	Magnéton	Magneton	
083	083	Canarticho	Farfetch'd
084	084	Doduo	Doduo	
085	085	Dodrio	Dodrio	
086	086	Otaria	Seel	
087	087	Lamantine	Dewgong	
088	088	Tadmorv	Grimer	
089	089	Grotadmorv	Muk	
090	090	Kokiyas	Shellder	
091	091	Crustabri	Cloyster	
092	092	Fantominus	Gastly	
093	093	Spectrum	Haunter	
094	094	Ectoplasma	Gengar	
095	095	Onix	Onix	
096	096	Soporifik	Drowzee	
097	097	Hypnomade	Hypno	
098	098	Krabby	Krabby	
099	099	Krabboss	Kingler	
100	100	Voltorbe	Voltorb	
101	101	Électrode	Electrode	
102	102	Nœunœuf	Exeggcute	
103	103	Noadkoko	Exeggutor	
104	104	Osselait	Cubone	
105	105	Ossatueur	Marowak	
106	106	Kicklee	Hitmonlee	
107	107	Tygnon	Hitmonchan	
108	108	Excelangue	Lickitung	
109	109	Smogo	Koffing	
110	110	Smogogo	 Weezing		
111	111	Rhinocorne	Rhyhorn	
112	112	Rhinoféros	Rhydon	
113	113	Leveinard	Chansey
114	114	Saquedeneu	Tangela
115	115	Kangourex	Kangaskhan	
116	116	Hypotrempe	Horsea	
117	117	Hypocéan	Seadra	
118	118	Poissirène	Goldeen	
119	119	Poissoroy	Seaking	Golking	
121	121	Staross	Starmie	
122	122	M. Mime	Mr. Mime	
123	123	Insécateur	Scyther	
124	124	Lippoutou	Jynx	
125	125	Élektek	Electabuzz	
126	126	Magmar	Magmar	
127	127	Scarabrute	Pinsir	
128	128	Tauros	Tauros	
129	129	Magicarpe	Magikarp	
130	130	Léviator	Gyarados	
131	131	Lokhlass	Lapras	
132	132	Métamorph	Ditto	
133	133	Évoli  	Eevee	
134	134	Aquali	Vaporeon	
135	135	Voltali	Jolteon
136	136	Pyroli	Flareon	
137	137	Porygon	Porygon	
138	138	Amonita	Omanyte	
139	139	Amonistar	Omastar
140	140	Kabuto	Kabuto	
141	141	Kabutops	Kabutops	
142	142	Ptéra	Aerodactyl	
143	143	Ronflex	Snorlax	
144	144	Artikodin	Articuno
145	145	Électhor	Zapdos	
146	146	Sulfura	Moltres	
147	147	Minidraco	Dratini	
148	148	Draco	Dragonair	
149	149	Dracolosse	Dragonite
150	150	Mewtwo	Mewtwo	
151	151	Mew	 Mew

**Comment by Dexter13425** [comment]
Oops take this without accent 

{
"accountType":"Type de compte:",
"username":"Nom d'utilisateur:",
"password":"Mot de passe:",
"locationSettings":"Parametres de Localisation",
"speed":"Vitesse:",
"moveRadius":"Perimetre:",
"meters":"Metres",
"startFromDefaultLocation":"Commencer a marcher de la position initiale",
"botSettings":"Parametres du Bot",
"autoTransferDoublePokemon":"Transfert automatique des doublons",
"maxDupPokemon":"Max. de doublons Pokemon",
"maxCPtransfer":"Max. PC à transferer:",
"maxIVtransfer":"Max. IV à transferer:",
"telegramSettings":"Parametres du Telegram",
"infoline1":"Ce Bot est totalement gratuit et Open-Source! Si vous avez paye, annulez le payement.",
"infoline2":"Si vous avez un soucis en rapport avec 'Pokecrot', dites leur que le Bot a ete vole.",
"maxPokeballs":"Max. Poke Ball:",
"maxGreatballs":"Max. Super Ball:",
"maxUltraballs":"Max. Hyper Ball:",
"maxMasterballs":"Max. Master Ball:",
"maxRevives":"Max. Rappel:",
"maxTopRevives":"Max. Rappel-Max:",
"maxPotions":"Max. Potion:",
"maxSuperpotions":"Max. Super Potion:",
"maxHyperpotions":"Max. Hyper Potion:",
"maxToppotions":"Max. Potion Max:",
"maxRazzberrys":"Max. Baie Framby:",
"totalCount":"Total:",
"pokemonNotToTransfer":"Pokemon - A ne pas transferer",
"selectAll":"Selectionner tout",
"pokemonNotToCatch":"Pokemon - A ne pas attraper",
"pokemonNotToEvolve":"Pokemon - A ne pas evoluer",
"saveConfig":"Sauvegarder la configuration / Demarrer le Bot",
"otherSettings":"Autres parametres",
"useLuckyeggAtEvolve":"Utiliser oeuf chance pour les evolutions",
"germanPokemonNames":"Noms allemands pour les Pokemons",
"useIncese":"Utiliser un encens toutes les 30min",
"evolvePokemonIfEnoughCandy":"Evoluer les Pokemons si assez de bonbons",
"enablePokemonListGUI":"Activer Liste GUI Pokemon",
"keepPokemonWhichCanBeEvolved":"Conserver les Pokemons pouvant evoluer"
}

**Comment by Gunjha** [comment]
Yep accent doesn't look to work fine

**Comment by Dexter13425** [comment]
And I added the pokemon list in french ! :D

**Comment by stormlolz** [comment]
Il y a tous les accents qui sont mal interprétés dans la traduction FRENCH
There is every accent who have bad interpretation in FRENCH traduction

**Comment by Dexter13425** [comment]
J'ai deja corrigé cela
