### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by badmage789** [Ar1i/PokemonGo-Bot#875]
what should i do?
![adsiz](https://cloud.githubusercontent.com/assets/20792795/17325835/7efbf7dc-58b6-11e6-88fa-8f8af54cb150.png)

**Comment by Ar1i** [comment]
Read, and you could already solve it by yourself

**Comment by Bikkstar123HD** [comment]
your authentication is wrong

**Comment by Bikkstar123HD** [comment]
hahha right AR1 lol

**Comment by badmage789** [comment]
i tried 3231 times the wrong password. iam an idiot thanks
