### ISSUE TITLE
@ aR1i dutch translations

### ISSUE THREAD

**Issue by rlmrso** [Ar1i/PokemonGo-Bot#876]
Just made changes to Gui.cs you said there is another file that needed to be changed for dutch translation let met know.

**Comment by Ar1i** [comment]
Pokemons.cs

**Comment by KanekiiVII** [comment]
Ar1i, 
Is it possible to contact u via Skype ?

**Comment by rlmrso** [comment]
Where to upload them @Ar1i ?
