### ISSUE TITLE
New Function : Auto download update

### ISSUE THREAD

**Issue by Dickhead0** [Ar1i/PokemonGo-Bot#878]
can you please add a feature to auto download an update .zip file and notify the user after downloading it.

**Comment by emilie253** [comment]
no because if you have bug, you cant use bot :p ^^

**Comment by Dickhead0** [comment]
even the manually downloaded bot contains the errors.

**Comment by emilie253** [comment]
yes but if you have bug, you can use old version. If you have auto update, you can't

**Comment by Ar1i** [comment]
will not add an auto update sorry.

**Comment by Dickhead0** [comment]
i mean just download the zip file in downloads file and notify the user that it ha downloaded the new version(But without extracting it.)
