### ISSUE TITLE
PTC account: Error reloading Pokemon List.

### ISSUE THREAD

**Issue by IDonated** [Ar1i/PokemonGo-Bot#879]
Everytime I try to get my poke list I got this enfinetly:

![image](https://cloud.githubusercontent.com/assets/20728445/17326125/8cdeff4a-58af-11e6-83c4-80f8b40ac9cb.png)

I don't know if it's a problem with PTC accounts (since my google account works fine), if it's a problem of mine, a problem with the server or what. Could anyone give me a confirmation?

**Comment by Doberok** [comment]
+

**Comment by IDonated** [comment]
@Doberok you have this problem too man?

**Comment by Ar1i** [comment]
Trying to fix that

**Comment by IDonated** [comment]
As I told you man already solved it, just deleted the sprites folder, and it magicaly solved.
Thanks for all your effors and patience man, really appreciate it!

**Comment by GhostSamurai** [comment]
@Ar1i 
Hello Ar1i i was, past tense, was working with the guys of pokecrot.com and i have some information.

Please get back to me ASAP!

I only use telegram to talk at GhostSamuraiX or find me in Discord app https://discord.gg/XsXuRJY
