### ISSUE TITLE
Why no fix?

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#886]
why you guys dont fix that bug, no transfer pokemons ??
that would be nice :)

**Comment by Ar1i** [comment]
Cause there is no Bug, your settings are wrong.

**Comment by K0zY** [comment]
ihave max cp 400 and iv 80%
and no sell pokemons bro :(

**Comment by K0zY** [comment]
http://prntscr.com/c0meb1
how i have it ?
should be selled right?

**Comment by yoyos** [comment]
No because you put "KEEP MAX DUPLICATE" to 1
So it will always keep 1 pokemon of each type

**Comment by K0zY** [comment]
yoyo i have keep 2

**Comment by rlmrso** [comment]
Close i think !?

**Comment by K0zY** [comment]
noo xD

**Comment by K0zY** [comment]
why some pokemons dont sell ??? now i have cp max 600 he sell more than b4 but not efective

**Comment by yoyos** [comment]
You just a fucktard, I explained it to you

**Comment by K0zY** [comment]
yoyo be calm

**Comment by K0zY** [comment]
so i have 2 of each one and if i catch one better he sells the worst?

**Comment by yoyos** [comment]
Put KEEP MAX DUPLICATE to 0
Then only CP and IV rules will apply

**Comment by K0zY** [comment]
http://prntscr.com/c0mxnd
i did it man and no sell
http://prntscr.com/c0mxyp

**Comment by K0zY** [comment]
rules cv 600 iv 75

**Comment by yoyos** [comment]
Can you give a screenshot with your settings interface too with rules ?

**Comment by K0zY** [comment]
my fail xD it works now

**Comment by K0zY** [comment]
yoyo u are greatest suportter :P

**Comment by yoyos** [comment]
Please stop posting anything here.

**Comment by K0zY** [comment]
dont be a badass dude 
thnx for help

**Comment by FrancYescO** [comment]
keep evolvable selected?

**Comment by Ar1i** [comment]
^
