### ISSUE TITLE
Use of Pokeballs/Great/Ultra/Master and Berries.

### ISSUE THREAD

**Issue by rlmrso** [Ar1i/PokemonGo-Bot#887]
Perhaps an good idea.. Make some settings in the bot where people can change wich Pokeball is being used depending on the CP or IV from the specific pokemon you trying to catch. 

Use Pokeball above:    ____ CP/IV
Use Greatball above:   ____ CP/IV
Use Ultraball above:    ____ CP/IV
Use Masterball above: ____ CP/IV

Also the use of berries depending on CP / IV is nice.

If Pokemon above ____ CP use berry.
or 
If pokemon above ____ IV use berry.

**Comment by sunit1998** [comment]
if u set that that will drop the rate of the pokemon getting caught

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
