### ISSUE TITLE
Pokemon List not responding

### ISSUE THREAD

**Issue by 12348766754** [Ar1i/PokemonGo-Bot#888]
Hi there, I was going to upgrade my eggexcute or something, but now the pokelist is not responding anymore (it were many power ups).

**Comment by 12348766754** [comment]
Oh, the bot itself in the log screen is running correctly. So it's just the pokemon list

**Comment by Xinrave** [comment]
lol, mine working just fine after the update.. got the same problem with prev version tho

**Comment by rlmrso** [comment]
CLOSE
