### ISSUE TITLE
Idea; Only Use lucky egg when you have +30 to evolve.

### ISSUE THREAD

**Issue by rlmrso** [Ar1i/PokemonGo-Bot#889]
The title say enough i think.. maybe add an additional option for this !?

**Comment by UltraVLT** [comment]
Would be great.but please post suggestions at https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/ . To make it easier for Ar1i.

**Comment by glabella** [comment]
i only use lucky egg when i have 140 to evolve (pidgey,caterpie and weedle, with 2 phones)

**Comment by JustPlaysDE** [comment]
^
