### ISSUE TITLE
[Request] French Translate

### ISSUE THREAD

**Issue by stormlolz** [Ar1i/PokemonGo-Bot#89]
Hello,

Have you planned a translation in French , at least for the names of Pokemon ?

It would be much more convenient for French users , and that would impact more users.

Thank you (sorry for my english)
Thank you for your work

I can help you for all Tradutions English-> French

A list to help

num/french/eglish
1/Bulbizarre/Bulbasaur
2/Herbizarre/Ivysaur
3/Florizarre/Venusaur
4/Salamèche/Charmander
5/Reptincel/Charmeleon
6/Dracaufeu/Charizard
7/Carapuce/Squirtle
8/Carabaffe/Wartortle
9/Tortank/Blastoise
10/Chenipan/Caterpie
11/Chrysacier/Metapod
12/Papilusion/Butterfree
13/Aspicot/Weedle
14/Coconfort/Kakuna
15/Dardargnan/Beedrill
16/Roucool/Pidgey
17/Roucoups/Pidgeotto
18/Roucarnage/Pidgeot
19/Rattata/Rattata
20/Rattatac/Raticate
21/Piafabec/Spearow
22/Rapasdepic/Fearow
23/Abo/Ekans
24/Arbok/Arbok
25/Pikachu/Pikachu
26/Raichu/Raichu
27/Sabelette/Sandshrew
28/Sablaireau/Sandslash
29/Nidoran/Nidoran-F
30/Nidorina/Nidorina
31/Nidoqueen/Nidoqueen
32/Nidoran/Nidoran-M
33/Nidorino/Nidorino
34/Nidoking/Nidoking
35/Mélofée/Clefairy
36/Mélodelfe/Clefable
37/Goupix/Vulpix
38/Feunard/Ninetales
39/Rondoudou/Jigglypuff
40/Grodoudou/Wigglytuff
41/Nosferapti/Zubat
42/Nosferalto/Golbat
43/Mystherbe/Oddish
44/Ortide/Gloom
45/Rafflesia/Vileplume
46/Paras/Paras
47/Parasect/Parasect
48/Mimitoss/Venonat
49/Aéromite/Venomoth
50/Taupiqueur/Diglett
51/Triopikeur/Dugtrio
52/Miaouss/Meowth
53/Persian/Persian
54/Psykokwak/Psyduck
55/Akwakwak/Golduck
56/Férosinge/Mankey
57/Colossinge/Primeape
58/Caninos/Growlithe
59/Arcanin/Arcanine
60/Ptitard/Poliwag
61/Tétarte/Poliwhirl
62/Tartard/Poliwrath
63/Abra/Abra
64/Kadabra/Kadabra
65/Alakazam/Alakazam
66/Machoc/Machop
67/Machopeur/Machoke
68/Mackogneur/Machamp
69/Chétiflor/Bellsprout
70/Boustiflor/Weepinbell
71/Empiflor/Victreebel
72/Tentacool/Tentacool
73/Tentacruel/Tentacruel
74/Racaillou/Geodude
75/Gravalanch/Graveler
76/Grolem/Golem
77/Ponyta/Ponyta
78/Galopa/Rapidash
79/Ramoloss/Slowpoke
80/Flagadoss/Slowbro
81/Magneti/Magnemite
82/Magneton/Magneton
83/Canarticho/Farfetch'd
84/Doduo/Doduo
85/Dodrio/Dodrio
86/Otaria/Seel
87/Lamantine/Dewgong
88/Tadmorv/Grimer
89/Grotadmorv/Muk
90/Kokiyas/Shellder
91/Crustabri/Cloyster
92/Fantominus/Gastly
93/Spectrum/Haunter
94/Ectoplasma/Gengar
95/Onix/Onix
96/Soporifik/Drowzee
97/Hypnomade/Hypno
98/Krabby/Krabby
99/Krabboss/Kingler
100/Voltorbe/Voltorb
101/Electrode/Electrode
102/Noeunoeuf/Exeggcute
103/Noadkoko/Exeggutor
104/Osselait/Cubone
105/Ossatueur/Marowak
106/Kicklee/Hitmonlee
107/Tygnon/Hitmonchan
108/Excelangue/Lickitung
109/Smogo/Koffing
110/Smogogo/Weezing
111/Rhinocorne/Rhyhorn
112/Rhinoféros/Rhydon
113/Leveinard/Chansey
114/Saquedeneu/Tangela
115/Kangourex/Kangaskhan
116/Hypotrempe/Horsea
117/Hypocéan/Seadra
118/Poissirène/Goldeen
119/Poissoroy/Seaking
120/Stari/Staryu
121/Staross/Starmie
122/Mr.Mime/Mr. Mime
123/Insécateur/Scyther
124/Lippoutou/Jynx
125/Elektek/Electabuzz
126/Magmar/Magmar
127/Scarabrute/Pinsir
128/Tauros/Tauros
129/Magicarpe/Magikarp
130/Léviator/Gyarados
131/Lokhlass/Lapras
132/Métamorph/Ditto
133/Evoli/Eevee
134/Aquali/Vaporeon
135/Voltali/Jolteon
136/Pyroli/Flareon
137/Porygon/Porygon
138/Amonita/Omanyte
139/Amonistar/Omastar
140/Kabuto/Kabuto
141/Kabutops/Kabutops
142/Ptéra/Aerodactyl
143/Ronflex/Snorlax
144/Artikodin/Articuno
145/Electhor/Zapdos
146/Sulfura/Moltres
147/Minidraco/Dratini
148/Draco/Dragonair
149/Dracolosse/Dragonite
150/Mewtwo/Mewtwo
151/Mew/Mew

**Comment by 3210x** [comment]
J'ai réussi a faire la translate
https://mega.nz/#!7dJkUJoS
