### ISSUE TITLE
RazzBerry problems

### ISSUE THREAD

**Issue by Ted0504** [Ar1i/PokemonGo-Bot#890]
After several updates, my RazzBerries are always 0. Why is that?
![razzberry](https://cloud.githubusercontent.com/assets/20794116/17327674/40a67e82-586e-11e6-951d-8afb321fcf88.jpg)

**Comment by rlmrso** [comment]
They are busy implementing razzberries .

**Comment by sunit1998** [comment]
depends where ur farming.
if u want to use razz berry this is location-   40.765076, -73.972846
with least consumption of razz berry this is the location-    -33.868965, 151.209038

**Comment by Logxn** [comment]
^ that is the worst awnser I have seen so far.

Check your Inventory in the App, do you realyl have 0 RazzBerrys?
If yes, then its fucking obvious why it cant use razzberrys :D
