### ISSUE TITLE
avast warning

### ISSUE THREAD

**Issue by fumoffu80** [Ar1i/PokemonGo-Bot#892]
Avast found Win32:Malware-gen in Latest Build - 02.08 12.35 on the GoogleMapsApi.dll

**Comment by 13XxM1CHA3lxX37** [comment]
Avast is crap

**Comment by IDonated** [comment]
Probably a false positive, anyway, if you don't feel safe I encourage you to not to use it. There are other bots you could always use but this is the best one I've found :smiley:

**Comment by IceQ1337** [comment]
@fumoffu80  It's obviously a false positive.
@13XxM1CHA3lxX37 Avast is one of the best Anti-Virus Systems.

**Comment by Ar1i** [comment]
^
