### ISSUE TITLE
Error GMap.NET.WindowsForms.GMapControl and Reloading Pokemon List

### ISSUE THREAD

**Issue by filoh** [Ar1i/PokemonGo-Bot#896]
I'm getting this two erros.
First say this when click on the Set Location: "GMap.NET.WindowsForms.GMapControl threw an exception "
Second is the error saying Reloading Pokemon List.

Already uncheck netframework 4.5 and tryed again, no lucky, same error always.

**Comment by Ar1i** [comment]
Can you post a Screenshot of it? Would help me to find the error

**Comment by filoh** [comment]
Here it is the two errors.
![pokemon list error](https://cloud.githubusercontent.com/assets/20794024/17338054/0b14fbba-58bc-11e6-833e-dccb18e67c10.jpg)
![set location error](https://cloud.githubusercontent.com/assets/20794024/17338055/0b4cd6b6-58bc-11e6-97a3-4502fd14715f.jpg)
