### ISSUE TITLE
How to Install Video (Turkish)

### ISSUE THREAD

**Issue by mertcemq** [Ar1i/PokemonGo-Bot#897]
I realized that in YouTube, there is many videos about your bot in Turkish. But none of them uses your GitHub Link. If you want, I can make a video that explains how to download, install and telegram setup. Then you can use it in your thread (https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/) so you will have more Turkish users.

**Comment by hendek95** [comment]
kardeş boşver sen onu :D uzak sunucu hata döndürdü (403) yasak hatası alıyorum framework microsoft ya da ağ ile ilgili bir sıkıntı bilgin var mı? #760

**Comment by mertcemq** [comment]
Bende hata yok çalışıyor şuan :D

**Comment by HaydarOzturk** [comment]
Kardeşim youtube da zaten tanıtım olarak ben kullandım. Kimse kullanmıyor kısmını değiştirirsen sevinirim.

**Comment by HaydarOzturk** [comment]
Ayrıca bunu yetkililerlede konuştum ekleyeceklerini söylediler o sayfaya ancak ekleme yapmadılar sanırım sayfayı almanca ve ingilizce tutmak ıstıyorlar.

**Comment by mertcemq** [comment]
Kusura bakma kardeşim, YouTubeda Pokecrot falan diye kullanmışlar ilklerde. Konuda da göremeyince yok sandım.
