### ISSUE TITLE
We cant find any pokestops

### ISSUE THREAD

**Issue by 0x92** [Ar1i/PokemonGo-Bot#899]
I did not change my config or anything elsed just updated to the latest build and now its broken

**Comment by 0x92** [comment]
![1](https://cloud.githubusercontent.com/assets/6593435/17328806/f96a4cae-58bf-11e6-8f73-8db2b0149d97.png)

**Comment by Sashen1991** [comment]
me too.pls fix

**Comment by Bikkstar123HD** [comment]
same but it means you are soft banned wait for a while and you will be good

**Comment by 0x92** [comment]
@Bikkstar123HD it did not detect that i am banned ...

**Comment by Bikkstar123HD** [comment]
0x92 if u restart the bot it will say u are soft banned it will detect in a while

**Comment by 0x92** [comment]
I did this and it didnt helped

**Comment by Shikkaku** [comment]
seems that the bots are not working? the old version cant find any pokestaps either

**Comment by Bikkstar123HD** [comment]
yeah i think the same 
it says no pokestops found from last 30-40 mins straight

**Comment by Sashen1991** [comment]
what can we do?

**Comment by Bikkstar123HD** [comment]
dont know if its with the servers from niantic or may be its the bot we cant confirm it as pokevision isnt working

**Comment by proruxHD** [comment]
do u guys think that they will fix it?

**Comment by Bikkstar123HD** [comment]
its not an error SIMPLE TRICK  delete your last cordinates file from config and set locatioon to a different pace it will start woking asap as far as i think it is

**Comment by stormlolz** [comment]
yes delete last cords and set location, next moove a little with your mousse on the map to moove the 3 cords and run the bot

**Comment by Ar1i** [comment]
Change location. And it should work.
