### ISSUE TITLE
Use branching for dev version

### ISSUE THREAD

**Issue by chrisoro** [Ar1i/PokemonGo-Bot#9]
This way you don't need to 'release' a new version as an archive.

Just create a dev branch for active development and a release branch for each major release

**Comment by Ar1i** [comment]
Uhm, its my first time doing this with Github, so i dont really know how that works.

**Comment by chrisoro** [comment]
Well I'm a software developer myself.

Usually you have different 'paths' a software can take and you want each path to have its purpose and advantages. Thats why you use a version control like git or svn.

https://en.wikipedia.org/wiki/Branching_(version_control)

If you want I can help you set it up!
