### ISSUE TITLE
What to do when he detect a softban ?

### ISSUE THREAD

**Issue by ayatoo** [Ar1i/PokemonGo-Bot#900]
What i have to do when he detect a softban ?

**Comment by hazmad** [comment]
let it run, it'll fix it for you. wait for the "probably unbanned" message

**Comment by ayatoo** [comment]
Ok but he   detect  and unbanned every 2minutes  it's normal ?

**Comment by 0x92** [comment]
Do you log into ur account while botting?

**Comment by hazmad** [comment]
If it detects that your location moving to far it'll soft-ban you. you should only run the bot, if you play on the app, it'll keep soft-banning you

**Comment by ayatoo** [comment]
no i dont play on the app

**Comment by Greenryder** [comment]
You need to delete the "LastCoord.txt" in the Configs folder if you change your location.

**Comment by ayatoo** [comment]
Oh ok nice ! thank you

**Comment by Greenryder** [comment]
You're welcome

**Comment by JustPlaysDE** [comment]
^
