### ISSUE TITLE
how to update the client?

### ISSUE THREAD

**Issue by PTArtiss** [Ar1i/PokemonGo-Bot#904]
pretty self explanatory question.

**Comment by 0x92** [comment]
Go to github download zip  unzip build archive copy and overwrite finished

**Comment by K0zY** [comment]
before i had config folder now i dont :O

**Comment by FAymYs19** [comment]
For me I just keep "Config" and "Sprites" and delete everything else.
Then i open "Build.rar" and extract to that folder.

**Comment by hazmad** [comment]
extract the new download. copy (or move) the entire Config folder from the old build to the new build folder. optional: delete the old build folder

**Comment by Ar1i** [comment]
Just replace it done. Your Config file etc should be safed, if you use Latest Build
