### ISSUE TITLE
config folder

### ISSUE THREAD

**Issue by K0zY** [Ar1i/PokemonGo-Bot#906]
i dont have config folder to delete lastcoord file
before someone told me i had to set location to get the folder but it isnt working
can someone help me?

**Comment by UltraVLT** [comment]
Did you started the bot after you were done with ur settings? Normally he saves all the sets in the config folder after that.If it's still not popping up in ur folder,redownload the "clean/fresh" rar and set it up from new.

**Comment by K0zY** [comment]
look im running bot rigth now and no config folder

http://prntscr.com/c0nrfr

**Comment by K0zY** [comment]
i think im doing rigth can u suport by teamviwer?

**Comment by UltraVLT** [comment]
Do you have a Sprites folder tho? @.@ Can't support,I am at my business pc. xd

**Comment by K0zY** [comment]
what is that?:O

**Comment by UltraVLT** [comment]
Folder with all the pokemon as png for the pokemon gui list. :S

**Comment by K0zY** [comment]
no i dont have but my list works

**Comment by UltraVLT** [comment]
hm awkward,how about you'll redownload the rar in a fresh folder and try again if anything is being created.And another question,can you transfer etc at your GUI even tho you have no CSV of your pokemonlist? Oo

**Comment by K0zY** [comment]
yeah i can use the list well
i already did alot of downloads xD alot of trys
seems like invisible idk why

**Comment by UltraVLT** [comment]
Well then,idk why it doesn't work,sorry m8 :/

**Comment by hazmad** [comment]
Where is the Bot folder located on your computer? 
example: "C:\Users\someguy\Downloads\Latest Build - 02.08 12.35"

**Comment by Logxn** [comment]
When you first run the program, a Configs folder will be created.
When you first save your config in the gui, it will create "lastCoords.txt" in the Configs folders.

If you want to switch locations, you need to delete lastCoords.txt

**Comment by K0zY** [comment]
C:\PokemonGo-Bot-master\Builds Only
hazmad


logxp
it doesnt appear, that folder..

**Comment by Logxn** [comment]
then build it yourself, or redownload

**Comment by K0zY** [comment]
but if i donwload new one with clean configs he save my configs but no folder :O

**Comment by K0zY** [comment]
can someone send me a new one config folder? xD

**Comment by hazmad** [comment]
try moving the whole folder to your user directory, see if you still having the problem

anywhere under C:\Users\username\

**Comment by K0zY** [comment]
i tested on desktop and is the same

**Comment by hazmad** [comment]
OK, I try this. I sanitized my info. extract these folders into your build folder, fill in the config info manually and then give it a try. 
[http://www.mediafire.com/download/0u8067gucgbq7l4/bot-folders.7z](#bot-folders)

**Comment by K0zY** [comment]
epic... i did that but...
my settings have been saved but in config folder is everyting cleen :o

**Comment by hazmad** [comment]
Everything Clean? what do you mean?

**Comment by K0zY** [comment]
i mean new one not used
