### ISSUE TITLE
may be bots not working  or potentially niantic servers are having an issue

### ISSUE THREAD

**Issue by Bikkstar123HD** [Ar1i/PokemonGo-Bot#908]
no pokestops found frm past 30-40 minutes straight no matter how much gap i give before restarting it 
potentially bug or anything else 
the rest who have issues like this post it here so that we can all see if its for all or just some of us

**Comment by Shikkaku** [comment]
if the old bots dont works to then i think poke go server problems or niantic did something. old and new version dont work for me

**Comment by stormlolz** [comment]
Screen the cmd box ? and your positions? what version?

**Comment by Shikkaku** [comment]
default position at central park > the newest version and 1.0.4.9

**Comment by rlmrso** [comment]
Dont use default locations ! .

**Comment by K0zY** [comment]
working here

**Comment by Shikkaku** [comment]
i always start from there and there was no problems

**Comment by Bikkstar123HD** [comment]
i never use default location

**Comment by rlmrso** [comment]
@Bikkstar123HD Try to use another location .

**Comment by Bikkstar123HD** [comment]
mm let me try it and imma reply u the result @rlmrso

**Comment by Bikkstar123HD** [comment]
@rlmrso it started working thanks for the tip the nianctic servers sometimes remove pokestops from central park just move like 1000 mts and re start the bot it started working now so may be all must try this and see thanks in advance and thanks to @rlmrso
