### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#909]
after this latest update i m getting the error that directory not found.
![screenshot_1](https://cloud.githubusercontent.com/assets/20731094/17330243/b401d9d8-58e3-11e6-870a-cb52629a0582.jpg)

please look into this matter

**Comment by globsch** [comment]
fix here:
https://github.com/Ar1i/PokemonGo-Bot/pull/910

**Comment by Logxn** [comment]
Go update

**Comment by Ar1i** [comment]
Update and it should work.
