### ISSUE TITLE
Login Error with Google

### ISSUE THREAD

**Issue by NerdisDev** [Ar1i/PokemonGo-Bot#91]
<img width="1444" alt="un123benannt" src="https://cloud.githubusercontent.com/assets/13067978/17217200/cbbb2a1a-54e3-11e6-954b-eb597f8ccfc6.PNG">

This bug appears everytime when i start the Bot. I use Google to Login. Version 1.0.1.8

**Comment by bitrape** [comment]
Please check other issues before opening another...
Problem is known and already worked at. 
See issue #85

**Comment by itsjustnelis** [comment]
How did u even got 1.0.1.8 ????

**Comment by PinkmanHD** [comment]
yes where can i download it with a exe to run?

**Comment by NerdisDev** [comment]
... you cant download it. The Google Auth API Key Changed so the .exe dont work anymore.

**Comment by Ar1i** [comment]
There is already a post #85, use source and build it.
