### ISSUE TITLE
Not working, only spam and spam (PTC)

### ISSUE THREAD

**Issue by crazyhoorse961** [Ar1i/PokemonGo-Bot#913]
It doesn't load, i configurate it, open it but gives this weird error:
http://pastebin.com/8xvzkVaJ

**Comment by stormlolz** [comment]
error in your account connection

try your log on google
or on pokemon website

**Comment by Logxn** [comment]
ACCOUNT NOT VERIFIED

Do I need to say anymore?

**Comment by crazyhoorse961** [comment]
I've tried creating another one, and nothing! (I've verified my account!!)

**Comment by stormlolz** [comment]
When you loggin here 

https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin

what happened

**Comment by UltraVLT** [comment]
Do you start the account from zero?

**Comment by stormlolz** [comment]
warning login is case sensitive

**Comment by Ar1i** [comment]
Read, verify it again.
