### ISSUE TITLE
Cant use Location

### ISSUE THREAD

**Issue by Abbasoo** [Ar1i/PokemonGo-Bot#917]
When i try to select the location it always show this to me:

![untitled](https://cloud.githubusercontent.com/assets/20796710/17331869/71ecc0f2-58d5-11e6-9c33-a74c734ec288.jpg)

Need help!

**Comment by PinkmanHD** [comment]
try to zoom in

**Comment by Logxn** [comment]
You need to zoom in, you somehow managed to zoom out to much.
Either way if you add the location manually, it will work just fine.

This is not a bug of the program itself :)

**Comment by JustPlaysDE** [comment]
^
