### ISSUE TITLE
Pokemon inventory full, although 241/250 Pokemons

### ISSUE THREAD

**Issue by Scanda85** [Ar1i/PokemonGo-Bot#918]
Hi...
i got the error text that my pokemon inventory is full.
But the pokemon list at the program shows 241/250.

If i enter the game by app, there i will see 250 / 250.
There is a problem with the pokemon list with the PokemonGoBot.

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/730

Fixed in last build.
