### ISSUE TITLE
SoftBan

### ISSUE THREAD

**Issue by Shoier** [Ar1i/PokemonGo-Bot#919]
I use app when bot is playing. Is it possible to unbanned acc with softban ?

**Comment by glabella** [comment]
spin a pokestop 40 times to remove softban

**Comment by Bikkstar123HD** [comment]
first it has its own unsoftban feature let it run and it will unsoftban you  or else

yes it is just delete last cordinates from the config folder and set some other location and try to run the console works fine

**Comment by Shoier** [comment]
The it works. It unbanned me when it works. But I can t play on my phone. I must spin 40 Times pokestop after closed bot ?

**Comment by JustPlaysDE** [comment]
Yes - you changed your location so you are softbanned.
