### ISSUE TITLE
IDEA: chronological sort, last cords, renaming of pokemon with stars

### ISSUE THREAD

**Issue by BurningHAM18** [Ar1i/PokemonGo-Bot#920]
chronological sort: in the pokemon list, we can sort them by name, cp, etc but not by capture time. can be useful expecially for those who manually transfer pokemon

renaming: in the same list can be useful rename (expecially for eevee) or star a pokemon, maybe to see in-game which pokemon has the bigger IV

last cords: in the GUI can be added a textbox to modify the lastcords file

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
