### ISSUE TITLE
PokemonGo.pocketAPI.Console.exe

### ISSUE THREAD

**Issue by petrpan1782** [Ar1i/PokemonGo-Bot#921]
PokemonGo.pocketAPI.Console.exe always deleted when unziped.. why ?:O some ideas ?

**Comment by stormlolz** [comment]
your antivirus ?

**Comment by petrpan1782** [comment]
about 3y - Bitdefend.

**Comment by GhostSamurai** [comment]
false positives

**Comment by JustPlaysDE** [comment]
Disable your antivirus or add it to the whitelist.
