### ISSUE TITLE
Catching very few Pokemon

### ISSUE THREAD

**Issue by ColdF0rest** [Ar1i/PokemonGo-Bot#924]
Hi,
am I doing something wrong or why do I not catch so many Pokemon? It seems like the bot is just running from one Pokestop to another without actually caring about Pokemon.

Normally,if you wait at a Pokestop for about 5-10 secs you can catch at least 2 Pokemon whereas it  just happens that the bot is running to the Pokestops for 30min without catching even 1 Pokemon.

**Comment by JustPlaysDE** [comment]
You have to change your location. 
So you can get up to 160 pokemon per hour.

**Comment by ColdF0rest** [comment]
Wouldn´t it be very noticeable if I would change my location from one to another?

**Comment by xJustx** [comment]
No that's no problem.
You will get softbanned but the bot will unban you automatically.
