### ISSUE TITLE
How do i update to new version

### ISSUE THREAD

**Issue by guzdank** [Ar1i/PokemonGo-Bot#93]
i dont know how to update to new version need help. no tutorials?

**Comment by BerkanYildiz** [comment]
This is a real question ?

**Comment by Supershady** [comment]
Thers no instruction how to update the bot just saying you need to update ....

**Comment by BerkanYildiz** [comment]
Ok
- Install Visual Studio 2015  Community
- Download the Source
- Compile the Source using VS15
- Done

**Comment by Ar1i** [comment]
Download newest and replace? @BerkanYildiz thanks. Closing this.
