### ISSUE TITLE
PokemonGo.RocketAPI.Console.exe is virus Gen:Variant.MSILPerseus.44388 ????

### ISSUE THREAD

**Issue by xlmnt** [Ar1i/PokemonGo-Bot#932]
bitdefender detect virüs PokemonGo.RocketAPI.Console.exe Gen:Variant.MSILPerseus.44388

**Comment by Logxn** [comment]
Virüüüüüüüs xD

**Comment by sirltgenamb** [comment]
yeah same here using bit defender

**Comment by Ar1i** [comment]
Compile it yourself, i dont know why its showing virus. But if you google it you see False Positive!
