### ISSUE TITLE
question:Pokestops

### ISSUE THREAD

**Issue by glabella** [Ar1i/PokemonGo-Bot#933]
i placed my bot in middle of Disneyland in Tokyo and it only finds  50-77 pokestops when there are a lot more(at least 200). i tried with diffrent speeds and diffrent move radius but no inprovements on finding more of those pokestops. Any suggestions?
![disneyland](https://cloud.githubusercontent.com/assets/19846525/17334106/a297a03e-58dd-11e6-8353-535bb99cdbca.png)

**Comment by chom00** [comment]
Increase radius?

**Comment by glabella** [comment]
i tried from 2000 to 11000 and no more then 70

**Comment by Ar1i** [comment]
cause the bot only sees what the app would see
