### ISSUE TITLE
Request to link with the sniper function feeded with Pokevision, Trackmon, Spawns.mazbron, etc...

### ISSUE THREAD

**Issue by navygino** [Ar1i/PokemonGo-Bot#935]
Is it possible?

http://www.trackemon.com/
https://pokevision.com/
http://spawns.mazbron.net/
https://github.com/sebastienvercammen/Pokemon-Go-Coords

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
