### ISSUE TITLE
Just hunt pokemon, No Spinning of pokestops

### ISSUE THREAD

**Issue by chom00** [Ar1i/PokemonGo-Bot#936]
Dear Devs,

Is it possible to disable spinning of pokestops. Basically just pure Hunting of Pokemons. I think i''m leveling too fast(even with just going through  pokestops) and not getting much needed desired Pokemons.

Thanks and Great work!

**Comment by Logxn** [comment]
Then Walk slower. 1kmh

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
