### ISSUE TITLE
Telegramm

### ISSUE THREAD

**Issue by damster87** [Ar1i/PokemonGo-Bot#938]
Telegramm

Why it does not work anymore ?

**Comment by Ar1i** [comment]
It works, if you setup correctly

**Comment by damster87** [comment]
I have not changed anything. 
it is the answer that i have no power more with ugly pitcure.

**Comment by Ar1i** [comment]
Haha, your name is wrong in the gui then

**Comment by damster87** [comment]
where should I change it in den gui ?

**Comment by Logxn** [comment]
Probably where it says name?

**Comment by darklordor** [comment]
what is that telegram thing about?
