### ISSUE TITLE
PokemonInventory Full 291/300

### ISSUE THREAD

**Issue by Snean1** [Ar1i/PokemonGo-Bot#940]
![pkm](https://cloud.githubusercontent.com/assets/12184212/17334692/16b330c8-58cf-11e6-949d-d1b22028d2fc.png)

I have only 291/300 Pokemon and i get the error "PokemonInventory Full".

**Comment by JustPlaysDE** [comment]
Please update your bot.

**Comment by juliencouraud** [comment]
I am on the latest and it seems the bot doesn't transfer any pokemon too...

**Comment by roflnoob** [comment]
It's because of eggs.
