### ISSUE TITLE
I found an issue!

### ISSUE THREAD

**Issue by ferobeatz** [Ar1i/PokemonGo-Bot#941]
Everytime i fill in my login id and password and start the bot i just see: 
 xxxx/badauthetication. 

I checked if i write my email address or password wrong but i I have not misspelled!
my email address is xxx@HOTMAIL.com i guess the program cant handle email addesses with "hotmail".

so i tried it out and create a new "xxx@gmail.com" accout and now the bot is working. can you guys pls fix this issue so i can use the bot for my "xxx@hotmail.com" account. 

sorry for my english.

**Comment by Bikkstar123HD** [comment]
it wont work because pokemon go only accepts two types of logins either PTC or google so use google if u want to play

**Comment by ferobeatz** [comment]
> it wont work because pokemon go only accepts two types of logins either PTC or google so use google if u want to play

wrong! i played 2 week with my xxx@hotmail.com account !

**Comment by Nils044** [comment]
Create a google account like everyone else, pls !

**Comment by madpada** [comment]
i have a google account with a yahoo email and the Bot runs it just fine.
