### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by mugikhan** [Ar1i/PokemonGo-Bot#944]
App doesn't connect to remote server when starting up and displays no settings. The live map also doesn't work

**Comment by Ar1i** [comment]
http://pokemon-go.ar1i.xyz/lang/get.php what happens if you open it?

**Comment by Ar1i** [comment]
post a screenshot please

**Comment by mugikhan** [comment]
Atta
![error1](https://cloud.githubusercontent.com/assets/20798643/17336754/e0a1259c-58df-11e6-99d0-0c9b58124129.jpg)
![error2](https://cloud.githubusercontent.com/assets/20798643/17336756/e0d72e26-58df-11e6-87b5-b4b32ac158bb.jpg)

ched

**Comment by Ar1i** [comment]
@mugikhan http://pokemon-go.ar1i.xyz/lang/get.php what happens if you open it?

**Comment by mugikhan** [comment]
tr.json spain.json ptBR.json ru.json france.json de.json

**Comment by Ar1i** [comment]
uhm then you can connect to the server.. try to restart the bot

**Comment by mugikhan** [comment]
I get the above error every time i try to start the bot

**Comment by Ar1i** [comment]
can you post the content of the messagebox?

**Comment by mugikhan** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 104.27.189.101:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\GUI.cs:line 82
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly Version: 1.0.5.9
    Win32 Version: 1.0.5.9
    CodeBase: file:///C:/Users/mugik/Desktop/PokemonGo-Bot-master/Builds%20Only/PokemonGo.RocketAPI.Console.exe
----------------------------------------
Pokemon Go Rocket API
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Users/mugik/Desktop/PokemonGo-Bot-master/Builds%20Only/Pokemon%20Go%20Rocket%20API.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PokemonGo.RocketAPI.Logic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mugik/Desktop/PokemonGo-Bot-master/Builds%20Only/PokemonGo.RocketAPI.Logic.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Ar1i** [comment]
where do you live? could probably because something is blocking that..

**Comment by mugikhan** [comment]
South Africa, but it used to work on older version now doesn't work anymore :(

**Comment by Ar1i** [comment]
Could you try it again please?

**Comment by mugikhan** [comment]
Tried again still unable to connect error

**Comment by Ar1i** [comment]
Hmm putting it then, directly into the tool. Gimme a hour orso.

**Comment by pokerave** [comment]
if he's using from a school or work IT probably blocked it.

System.Net.Sockets.SocketException: An attempt was made to access **_a socket in a way forbidden by its access permissions_** 104.27.189.101:80
