### ISSUE TITLE
Transalations French

### ISSUE THREAD

**Issue by WeRz34** [Ar1i/PokemonGo-Bot#945]
Hi, 
I'm French if you need some help, I can hlep you to translate the bot.
Because I see some wrong words in French.
Thanks you for read me.

Best regards,

WeRz.

**Comment by Ar1i** [comment]
Then help us :p 

> {
"accountType":"Type de compte:",
"username":"Nom d'utilisateur:",
"password":"Mot de passe:",
"locationSettings":"Paramètres de Localisation",
"speed":"Vitesse:",
"moveRadius":"Périmètre:",
"meters":"Metres",
"startFromDefaultLocation":"Commencer à marcher de la position initiale",
"botSettings":"Paramètres du Bot",
"autoTransferDoublePokemon":"Transfert automatique des doublons",
"maxDupPokemon":"Max. de doublons Pokemon",
"maxCPtransfer":"Max. PC à transférer:",
"maxIVtransfer":"Max. IV à transférer:",
"telegramSettings":"Paramètres du Telegram",
"infoline1":"Ce Bot est totalement gratuit et Open-Source! Si vous avez payé, annulez le payement.",
"infoline2":"Si vous avez un soucis en rapport avec Pokecrot, dites leur que le Bot a été volé.",
"maxPokeballs":"Max. Poké Ball:",
"maxGreatballs":"Max. Super Ball:",
"maxUltraballs":"Max. Hyper Ball:",
"maxMasterballs":"Max. Master Ball:",
"maxRevives":"Max. Rappel:",
"maxTopRevives":"Max. Rappel-Max:",
"maxPotions":"Max. Potion:",
"maxSuperpotions":"Max. Super Potion:",
"maxHyperpotions":"Max. Hyper Potion:",
"maxToppotions":"Max. Potion Max:",
"maxRazzberrys":"Max. Baie Framby:",
"totalCount":"Total:",
"pokemonNotToTransfer":"Pokemon - A ne pas transférer",
"selectAll":"Selectionner tout",
"pokemonNotToCatch":"Pokemons - A ne pas attraper",
"pokemonNotToEvolve":"Pokemons - A ne pas évoluer",
"saveConfig":"Sauvegarder la configuration / Démarrer le Bot",
"otherSettings":"Autres paramètres",
"useLuckyeggAtEvolve":"Utiliser oeuf chance pour les évolutions",
"germanPokemonNames":"Noms allemands pour les Pokémons",
"useIncese":"Utiliser un encens toutes les 30min",
"evolvePokemonIfEnoughCandy":"Evoluer les Pokémons si assez de bonbons",
"enablePokemonListGUI":"Activer Liste GUI Pokémon",
"keepPokemonWhichCanBeEvolved":"Conserver les Pokémons pouvant évoluer"
}

**Comment by xJustx** [comment]
After translating it, you can do a pull request.
