### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by JackTheRipper94** [Ar1i/PokemonGo-Bot#946]
Hello everyone, thank you for the wonderful work you are doing.

I wanted to help out. I translated in my language the GUI of the bot.
Not being a developer, I created a file "ita.json"

DOWNLOAD: https://mega.nz/#!ApVUgSLC!YzdlRCikPqzzZ2PCS6kNgXp70LzCREijN_YAwa5TX28

I hope you can add it in the final build!

See you soon, Jack.

**Comment by Ar1i** [comment]
will use that, thanks!
