### ISSUE TITLE
False +

### ISSUE THREAD

**Issue by adman9031** [Ar1i/PokemonGo-Bot#947]
So im pretty sure this issue has been addressed but if not, the console shows my account gaining xp but its not actually gaining anything. is this an issue with ptc accounts only? my gmail seems fine

**Comment by FrancYescO** [comment]
Gaining exp but no item = inventory full

**Comment by adman9031** [comment]
the bot is literally doing nothing to ptc accounts... the inventory is no even remotely close to full

**Comment by adman9031** [comment]
it shows that its working in console but if you go to check your account on your phone, it hasnt done anything
