### ISSUE TITLE
Evolving Bug.

### ISSUE THREAD

**Issue by FAymYs19** [Ar1i/PokemonGo-Bot#950]
If you try to evolve a Pokemon without having enough candy, the bot will consistently retry to evolve it.

This only happened once to me.
After i tried to force the bug to display for a screenshot, i just got a pop-up error.

**Comment by Ar1i** [comment]
Uhm i need a screenshot to get the exact error, this wont help much.. :s

**Comment by elenex23** [comment]
I do know if you try to evolve a mon and don't have enough candy, it will freeze the gui

**Comment by FAymYs19** [comment]
if i get the bug i send u a screenshot. :)

**Comment by Ar1i** [comment]
K closing until, just open a new issue then please!
