### ISSUE TITLE
[Request] Pokemon transfer list

### ISSUE THREAD

**Issue by pokemongouser** [Ar1i/PokemonGo-Bot#953]
Would it be possible to add a list (just like the one which allows us to choose which Pokemons not to catch) for Pokemon that should be transferred after they have been caught. For example when a rattata is caught the bot should automatically transfer it. This allows for the user to gain XP for catching but keeps the inventory usage low.

**Comment by jordanpillefernandez** [comment]
+1

**Comment by xJustx** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
