### ISSUE TITLE
Got banned for long usage

### ISSUE THREAD

**Issue by idkwateva** [Ar1i/PokemonGo-Bot#956]
Hi,

I mostly got banned if I walk more than 3 hours for one account with speed 5km/h distance 1000m. It probably can solved by adding multiple account array features i.e 2 hours account A and the next 3 hours account B or C and they switch automatically so the bot can run 24/7.

Or maybe use the distance as switcher.... After account A walk 5km it switch to account B.

Thanks

**Comment by Gunjha** [comment]
got no ban 
i tryed it all night long 2 days ago

and today it's ON from 1pm to now (6 hours already)

**Comment by idkwateva** [comment]
what's your walk speed and distance settings?
I've got 2 of my acc soft banned.

**Comment by ahya93** [comment]
use quickspin unbanner bro, input ur coordinate u want to jump..

**Comment by idkwateva** [comment]
Quickspin not working... quickspin said no pokestop nearby no matter where i put the coordinate.

**Comment by Mystery7** [comment]
botting 3days straight, 16km/h - 1500m no ban yet.

**Comment by HSMatheus** [comment]
I got banned to ... I opened on nox , no pokestop/Pokémon appears... I let my pc on to see if when I come back to home will back to normal... My other account with exact same settings is normal tho :/

**Comment by amuessig** [comment]
I also got soft banned banned with default configuration several times. Like 5 times within 15 minutes.. 
It ran all day long.

**Comment by Gunjha** [comment]
tryed different speed usualy  20km/h
today i tryed 35km/h

radius : 2000

**Comment by durnevo** [comment]
I bot for 4 days, 50km 1000 radius, no bans. Maybe you are logged in on your phone too?

**Comment by MrProblematic** [comment]
Im botting for 3 days interrupts... only thing weird is happening is that> 

> When i found some pokemon like, Rare or Very Rare, the game "crash" saying: 'Encounter not found'.
> -> So i stopped the bot to check the coordenates on my phone, to see what the fck was happening:
> The bot founded a Haunter (Rare), and when i touch it to try to capture, he just vanish for a few seconds, then re-appear..
> Any guess what is happening? Some kind of new ban?

**Comment by gummyruler** [comment]
Used the bots for 2 weeks now no ban. My speed is 1200 and my range is 2500.

**Comment by MrProblematic** [comment]
I think i've figured out what was happening to me...
While the bot was running, i used the "trackemon" to just take a look in the area.. probably niantic have madded some kind of little IP ban for snipping pkms and use the game..
I'll test Tor to snip..

**Comment by idkwateva** [comment]
@durnevo nope... never logged in anywhere... it's a new account.

**Comment by sammode** [comment]
i  ran the  bot at  50kms 100000  for 2 days no bans
