### ISSUE TITLE
Error reloading Pokemon list: Not enough RAM.

### ISSUE THREAD

**Issue by Greenryder** [Ar1i/PokemonGo-Bot#957]
Got the Error shown in the Screenshots. I've got 16gb of RAM so this shouldn't be the problem.

![memory error](https://cloud.githubusercontent.com/assets/20795884/17337237/09dacc04-58e2-11e6-8e8d-c3ef350ca619.PNG)
![memory](https://cloud.githubusercontent.com/assets/20795884/17337236/09d797aa-58e2-11e6-97d4-8d870fa6c90c.PNG)

**Comment by Ar1i** [comment]
Yeah, already on my list. Idk why that happens atm.

**Comment by Greenryder** [comment]
Alright, thank you :)

**Comment by poketlaban** [comment]
Im running 3bots, 2works perfectly fine and one get "Error reloading Pokemon list: Out of memory".
Not sure it's related but the only thing that is diffrent for the account that gets the errors is uppgraded bagspace to 400 and max pokemon to 350.

**Comment by Greenryder** [comment]
I upgraded bagspace and pokemon too. Maby thats the issue.

**Comment by hendek95** [comment]
i ll try delete pokemon and bag
