### ISSUE TITLE
* READ * Telegram Group

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#958]
Hey,
I decided to start a Telegram Group. There you can ask ppl or just share Settings and more. Please dont Spam that much.

Group Link to join: https://telegram.me/joinchat/DHcpCAi6HrQdbj5QagLIxA

**Comment by evanescentotaku** [comment]
hey ar thx for creating that group but that page wont load on me any suggestions it says The address wasn't understood

**Comment by Nuke11Proof** [comment]
Can´t add to telegram :(

**Comment by NevilleNg** [comment]
good idea~!~ start on your own group 1st:)
