### ISSUE TITLE
I Know not for suggestions, but

### ISSUE THREAD

**Issue by Garadoss** [Ar1i/PokemonGo-Bot#959]
I have some ideas to improve the Bot.

1. Autohatch - As already said it would be a cool function to Autohatch the Eggs.

2. A function that makes it depending on the IV and not the CP of a Pokemon which one have to leave the Team 
This could look like this in the settings:

_[**x**]Auto-Leave in case you got more than XX Pokemon of one kind depending on:
|->Highest CP[    ]
|->Highest IV[**x**]_

So a Tauros with 10CP and 98%IV will be kept and not a Tauros with 1000CP but 20%IV. 
In my Opinion its better to feed/level a Pokemon with an High IV up to an high CP, than having an high CP Pokemon. This high CP-Pokemon would be underpowered if you compare it to an high IV Pokemon which is leveled up to the same Level.

3. That in mind leads me to the 3 suggestion.
Autoevolve depending on the IV. That the Highest IV Pokemon will be evolved if you got enough candy could be a solution. But far better would be an evolve that is depending on the exact IV of an Pokemon. For example: you got enough candys (400!!!) to evolve a Magikarp (GER:Kapador) to a Gyarados (GER:Garados) but the highest IV of one of yours Magikarp is only 67% in this Situation. 
Lets say you could choose in the settings only to evolve Pokemon that IV is higher then 85%, you would keep the Magikarpcandys as long as you caught one Magicarp that IV is higher than 85% and evolve this one to an Gyrados no matter what CP it got.

This could look like this in the settings:

_[**x**]Auto-Evolve Pokemon if they got an higher IV then [**85%**]_

Far better would be a seperately option for every evolvable Pokemon (maybe a box on one Side of the Pokemons name in the "Pokemon to Evolve"-Chart), but i think this would be to much work.

Like and appreciate your work and love you for what you are doing,
Cheers

**Comment by Ar1i** [comment]
Please post it here, cause this is for issues only :( https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/unread
