### ISSUE TITLE
help anyone?

### ISSUE THREAD

**Issue by jusawatcher** [Ar1i/PokemonGo-Bot#960]
![untitled](https://cloud.githubusercontent.com/assets/20791379/17337598/033437a8-5916-11e6-838f-7d9ffd5db037.png)

anyone please? stuck here.

**Comment by elenex23** [comment]
Have to give us some more details. You for sure have all the settings correct? username/pw correct? Have you logged into the account or is it brandnew fresh?

**Comment by Ar1i** [comment]
Read the Red Error message.
