### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by sufficey** [Ar1i/PokemonGo-Bot#961]
This has been happening for 2 days: http://prntscr.com/c0qugr
I've been patient, re-trying it every few hours, using the newest version, still doesn't work. Any ideas?

**Comment by elenex23** [comment]
your last coordinates and current location are matching?

**Comment by sufficey** [comment]
Default location check, coordinates matching, search range 5000

**Comment by sufficey** [comment]
help :/
