### ISSUE TITLE
Sniping Pokemons?

### ISSUE THREAD

**Issue by Sininenjuusto** [Ar1i/PokemonGo-Bot#965]
everytime i change the location to catch some rare pokemons i get softbanned? or something even to i have 90-100 propability to catch these pokemons they seem to get away is there way to snipe pokemons without this problem, and yes i dont know what i am doing i am new to this thing!

**Comment by MrProblematic** [comment]
When i found some pokemon like, Rare or Very Rare, the game "crash" saying: 'Ecounter not found'.
-> So i stopped the bot to check the coordenates on my phone, to see what the was happening:
The bot founded a Haunter (Rare), and when i touch it to try to capture, he just vanish for a few seconds, then re-appear..
Any guess what is happening? Some kind of new ban?

**Comment by ShutUpPvP** [comment]
Probably just human incompetence :P 
For me sniping with the bot is working fine.

**Comment by JustPlaysDE** [comment]
If you change your location you will get a softban.
