### ISSUE TITLE
Italian translation JSON file [Better]

### ISSUE THREAD

**Issue by AcolyteIT** [Ar1i/PokemonGo-Bot#968]
[italian.zip](https://github.com/Ar1i/PokemonGo-Bot/files/397806/italian.zip)

**Comment by IceQ1337** [comment]
Added.

**Comment by AcolyteIT** [comment]
One last question, how can I translate the pokemon list HUD? is there an easy way like this one or not?

**Comment by IceQ1337** [comment]
The Pokemon List GUI does not have the new translation feature yet.
We will not hardcode translations as before in this GUI so just wait for an update there.

**Comment by Ar1i** [comment]
^this :) Added already to the Server. Just binding it now. Thanks!
