### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Finalssuse** [Ar1i/PokemonGo-Bot#969]
hello
I got a lil prbomem.
I used the bot, but i cant reset my location to my orignal location. pls need help!

**Comment by AcolyteIT** [comment]
just remove it and reinstall, that's how i fixed this

**Comment by Finalssuse** [comment]
oh thx u, i will try it

**Comment by JustPlaysDE** [comment]
If you change your location you have to delete the lastcords.txt in your config folder.
