### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by Mystery7** [Ar1i/PokemonGo-Bot#971]
i have no idea why it won't allow me to upload zip but any i uploaded it as txt simply rename it to .json.
[ar.txt](https://github.com/Ar1i/PokemonGo-Bot/files/397738/ar.txt)

**Comment by Abbasoo** [comment]
Need to improve.

**Comment by Mystery7** [comment]
Instead of saying it needs, go ahead and do it, its not that easy coming up with a translation for something that doesnt exist in your languages dictionary.

**Comment by IceQ1337** [comment]
I am not sure if this would actually work so i wait for @Ar1i to look over it.

**Comment by xJustx** [comment]
Please do a pull request.
