### ISSUE TITLE
New issue with the bot

### ISSUE THREAD

**Issue by Abbasoo** [Ar1i/PokemonGo-Bot#973]
Any help?

![untitled](https://cloud.githubusercontent.com/assets/20796710/17339093/fdd46fb2-58f2-11e6-9a81-3f3eaf44819c.jpg)

**Comment by devilexclonz22** [comment]
hello @Ar1i , somethhing wrong in new update for IV .. 
this is my picture .. hehe
![4](https://cloud.githubusercontent.com/assets/20783162/17339211/1ddbf164-5915-11e6-9c6a-a7714cf1c9ec.jpg)

**Comment by oltabaile** [comment]
I'm having the same issue. I tried a couple things, but they didnt work for me. Might work for you?

https://github.com/Ar1i/PokemonGo-Bot/issues/948

**Comment by zyf911** [comment]
the same issue happens to me

**Comment by hendek95** [comment]
i fixed  first error from https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ef0f1c39-fc92-4cde-9920-597a8d6981f9/403-error-the-remote-server-returned-an-error-403-forbidden?forum=sqlreportingservices
but after taking out of memory

**Comment by Abbasoo** [comment]
#948 @ @Ar1i @oltabaile @zyf911 @hendek95 It worked by running as Admin

**Comment by Ar1i** [comment]
Ahhh good to know!

**Comment by Abbasoo** [comment]
@Ar1i After restarting the bot the problem started again :( !

**Comment by hendek95** [comment]
@Abbasoo that link should help you because same error. pls read carefully which framework is a problem fix its access

**Comment by Abbasoo** [comment]
@hendek95 Thanks, it helped me.

**Comment by zyf911** [comment]
tried change permission for .NET, also run console as admi, no luck. @Abbasoo what did you do to make it work?

**Comment by hendek95** [comment]
@zyf911 mate it should. because error in first page about framework. pls read your error again and edit framework version
