### ISSUE TITLE
next time with new bot....

### ISSUE THREAD

**Issue by Titus1987** [Ar1i/PokemonGo-Bot#976]
np pokeballs but why?

**Comment by Titus1987** [comment]
he dont stop at the pokestops and catch items sry 4 my bad english

**Comment by ShutUpPvP** [comment]
Softbanned.

**Comment by FrancYescO** [comment]
items full? how many pokestop found in your location?

**Comment by Titus1987** [comment]
items 186/300 i dont se how much pokestops

**Comment by ShutUpPvP** [comment]
Whats ur location?

**Comment by FrancYescO** [comment]
will show how many pokestop on start

**Comment by Titus1987** [comment]
central park

**Comment by ShutUpPvP** [comment]
Than ure softbanned, or maybe a but, reinstall the folder. But i think its a softban.

**Comment by FrancYescO** [comment]
The bot will show you a warning if softbanned.

**Comment by ShutUpPvP** [comment]
But it sometimes takes about 2-4 minutes @FrancYescO 
And most ppl close the bot instantly.

**Comment by ShutUpPvP** [comment]
Btw. are u a dev @FrancYescO, if yes. Do u know if setting the Lifestat delaylower to detect a softban quicker?

**Comment by Titus1987** [comment]
ist dont a soft ban he´s catching pokemons but not the spots

**Comment by ShutUpPvP** [comment]
Send us a screenshot pls

**Comment by lailaps** [comment]
Close your bot and change settings.
Remove count for Top. - or Hyper Potions for example.
Restart the bot, once you have restarted the bot, it will recycle those items and get new Pokeballs @next Pokestops.

Easy as that!

**Comment by Titus1987** [comment]
but my Inventar dont is full ?

**Comment by ShutUpPvP** [comment]
A screenshot still would be helpful.

**Comment by Titus1987** [comment]
http://www.bilder-upload.eu/show.php?file=1f71be-1470164155.png

**Comment by Titus1987** [comment]
i have 3 bots at the same time 
at all 3 he dont catch the stops 
at once he catch no pokemon an no stops
and at the other 2 he dont catches stops 

its the same when 1 bot run

**Comment by ShutUpPvP** [comment]
Outside of the max walking range, so he is running back where he last detectet ur char, maybe u went online with ur phone with gps turned on.
So he will walk 90000 km to ur location and then he starte collecting again.

**Comment by ShutUpPvP** [comment]
How to fix that:
Delete the "LastCoords" file in ur "config" folder -> open the bot and set a new location -> uncheck the box that says "Walk from default location" -> now ure softbanned, the bot will unban u after 2-4 minutes.
Enjoy.

**Comment by Titus1987** [comment]
okay i try it

**Comment by ShutUpPvP** [comment]
Also, do u use 3 bots for the same account?
Would explain it too.

**Comment by Titus1987** [comment]
no its 3 other accounts can you help me ?`where find i the config or the last coords Folder? sry :x

**Comment by ShutUpPvP** [comment]
In the folder u saved the winrar file that u unpacked.

**Comment by Titus1987** [comment]
http://www.bilder-upload.eu/show.php?file=e5c93d-1470164692.png

**Comment by Titus1987** [comment]
dont find it  =/

**Comment by lailaps** [comment]
@Titus1987 
Only 2 Pokemons got away on your Screenshot... ^^
The rest was caught...

**Comment by ShutUpPvP** [comment]
Click on the builds only folder

**Comment by ShutUpPvP** [comment]
No @Titus1987 Its 3 different accounts.

**Comment by Titus1987** [comment]
there 6 rar Folder in it

**Comment by ShutUpPvP** [comment]
names?

**Comment by FrancYescO** [comment]
@ShutUpPvP Lifestat delay??

i think the best way to detect a softban is already here = pokestop give 0 exp

**Comment by Titus1987** [comment]
http://www.bilder-upload.eu/show.php?file=aee636-1470164908.png

**Comment by ShutUpPvP** [comment]
Yes @FrancYescO 
I mean if the bot will detect it faster, i know it in the second i read something like that, but the bot takes quiet some time to detect it.

**Comment by ShutUpPvP** [comment]
@Titus1987 Its the most recent build, open it, Should be called "Latest Build - 02.08 20.14"
There u should see the "config" folder with a "LastCoords" file in it, delete that.

**Comment by Titus1987** [comment]
http://www.bilder-upload.eu/show.php?file=3a14e7-1470165964.png

 i dont se him :D

**Comment by Titus1987** [comment]
okay it works the Problem wars ..... ihave the new bot copy in the old Folder now i have complete reinstall it short soft bann and now it works ! THANKS MAN !

**Comment by ShutUpPvP** [comment]
Ahhh good.
Yeah, i always downlaod the new bot version manually, so i didnt know hot the master version does that :)

But good that it fixed ur issue! and no probs.

Please close this issue report so the devs dont need to do it :)
There should be a "close" button somewhere on the bottom right of the comment box :)
