### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by PokemonGoer** [Ar1i/PokemonGo-Bot#977]
I can't load up my bot and it shows this message http://puu.sh/qnqQK/41ba0a4c28.png

**Comment by Ar1i** [comment]
You need all files, of the Latest Build Rar!

**Comment by PokemonGoer** [comment]
Could you send me the link please?

**Comment by danielalvenstrand** [comment]
[Here](https://github.com/Ar1i/PokemonGo-Bot/blob/master/Builds%20Only/Latest%20Build%20-%2002.08%2020.14.zip)

**Comment by PokemonGoer** [comment]
Thanks for the help :)

**Comment by Ar1i** [comment]
Good :p If the error still happens open a new issue please!
