### ISSUE TITLE
Issue where all pokéstops within 5000m disappeared but can still catch pokémon.

### ISSUE THREAD

**Issue by danielalvenstrand** [Ar1i/PokemonGo-Bot#980]
Hi!

I'm currently not experiencing this issue but I was before.
The bot was walking around and suddenly lost the ability to find any pokéstops for a while. It was still catching pokémon as before, none was running away. I tried to change location further away and the issue persisted. It kinda resolved on its own after a while walking around.

I've experienced being softbanned before and this wasn't it. It was walking around at 50km/h and didn't have full inventory.

Have anyone else experienced this issue?

I will try to document it if it happens again.

**Comment by ShutUpPvP** [comment]
Yes, i had the error couple times, u can just delete ur "LastCoords" folder, set a new position somewhere else and he will detect pokestops again.
U will get softbanned but the bot will unban u after 2-4minutes max.

**Comment by Ar1i** [comment]
This happens sometimes, cause the location is down where you've been. Just switch location then or wait some time!
