### ISSUE TITLE
.Net Framework error (.xyz domain blocked by network at work)

### ISSUE THREAD

**Issue by zyf911** [Ar1i/PokemonGo-Bot#981]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: An exception occurred during a WebClient request. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\GUI.cs:line 86
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly Version: 1.0.5.9
    Win32 Version: 1.0.5.9
    CodeBase: file:///C:/Users/Yufan/Desktop/PokemonGo-Bot-master%203/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/PokemonGo.RocketAPI.Console.exe
----------------------------------------
Pokemon Go Rocket API
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Users/Yufan/Desktop/PokemonGo-Bot-master%203/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/Pokemon%20Go%20Rocket%20API.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PokemonGo.RocketAPI.Logic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Yufan/Desktop/PokemonGo-Bot-master%203/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/PokemonGo.RocketAPI.Logic.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by filoh** [comment]
same here

**Comment by hendek95** [comment]
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ef0f1c39-fc92-4cde-9920-597a8d6981f9/403-error-the-remote-server-returned-an-error-403-forbidden?forum=sqlreportingservices go that link and try solve i fixed. but after that i have "out of memory"

**Comment by zyf911** [comment]
the error message said "Illegal characters in path", I think it's not related to network service, maybe it's something wrong with the script?
I have tried add write permission to network service of .NET

**Comment by FrancYescO** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by Ar1i** [comment]
Or try to move the files in another folder

**Comment by hendek95** [comment]
Guys! i didn't download 4.5 but after last update i can use thanks! 02.08 20.14

**Comment by zyf911** [comment]
I am using 02.08 20.14 version now, tried moving to another folder, didn't work. I have .NET 4.6 now, I will try to change it to .NET 4.5

**Comment by zyf911** [comment]
using .NET 4.5 now, no help. same error again

**Comment by oltabaile** [comment]
I'm having the same issue. Tried downgrading from .NET 4.5.2 to 4.5. Tried adjusting the permissions, running as administrator.

Something changed between yesterdays build and todays to cause the issue, I believe. It worked great last night and this morning.

**Comment by zyf911** [comment]
@oltabaile same here, tried everything, nothing worked. I am running windows 7 using VirtualBox on my macbook pro now. I was wondering will that cause a problem? What kind of windows are you using?

**Comment by oltabaile** [comment]
Windows 7 on a PC.

**Comment by FrancYescO** [comment]
try opening this url http://pokemon-go.ar1i.xyz/lang/get.php

**Comment by zyf911** [comment]
@FrancYescO  I can't open that url, it's blocked by my network at work. will that cause the problem?

**Comment by FrancYescO** [comment]
@zyf911  yeah, Thats why.

@Ar1i You need to put json files locally, its better.  some networks hate .xyz domains.

**Comment by zyf911** [comment]
@FrancYescO I will try it later when I am home. Is this files on .xyz a new thing today? The bot worked fine when I am at work yesterday~

**Comment by zyf911** [comment]
@FrancYescO I will try it later when I am home. Is this files on .xyz a new thing today? The bot worked fine when I was at work yesterday~

**Comment by FrancYescO** [comment]
yep, @Ar1i added download language from this domain today with https://github.com/Ar1i/PokemonGo-Bot/commit/4026f79ebe57e85790778dfd54802465e93a44dc

**Comment by zyf911** [comment]
Tried again at home, worked perfectly! Thanks @FrancYescO I will keep this issue open until the problem is solved completely. (.xyz domain blocked by network at work)

**Comment by xJustx** [comment]
^

**Comment by Ar1i** [comment]
Reopened until fix
