### ISSUE TITLE
Pokecrot.com 

### ISSUE THREAD

**Issue by whateverpop** [Ar1i/PokemonGo-Bot#983]
Not sure if this is already known, but apparently the owner is from Jakarta, Indonesia.

Cited from http://pokecrot.com.ipaddress.com/ :

"
messa harianto
N/A
Jakarta
Jakarta, Ja 11730
IN
Telephone: 6285769809023
Email: vipspuc3ngine@yahoo.com
                                                          "

This also explains the owner's crappy English ;)

Keep up the good work Ar1i!

**Comment by ShutUpPvP** [comment]
Yes, someone even found his ip and shit already ^^

**Comment by jief78** [comment]
abuse@resellercamp.com
this is his registar abuse contact may they can help us?
