### ISSUE TITLE
Asking for Administrator rights ??

### ISSUE THREAD

**Issue by yoyos** [Ar1i/PokemonGo-Bot#985]
Why does it ask for administrator rights. It wasn't the case before no ? What could justify this ? Please remove it ...

**Comment by Ar1i** [comment]
Cause of the WebClient, some ppl sayd that, that fixed it for them. Why should we remove it? Most applications uses that. If you dont want it remove it by youself, in the manifest.

**Comment by yoyos** [comment]
@Ar1i It's just it could let someone use high privilege code aiming at our system.
Even if you read/filter/validate all the code, it could be possible someone hide it in a pull request and you didn't see it.
