### ISSUE TITLE
help me translate pokemon list please

### ISSUE THREAD

**Issue by jief78** [Ar1i/PokemonGo-Bot#986]
hello I'm sorry i don't really know where to ask my question.

I would like to help translate pokemon list to french but i can't find any of the other translation to start from.

**Comment by BreAk95420** [comment]
copie .json and translate it for acceuil french ! Pokemon list i dont now

**Comment by jief78** [comment]
thank's acceuil is done already but i can't found pokemon list .json for translation

**Comment by xJustx** [comment]
Currently you can't translte the pokemon list.

**Comment by jief78** [comment]
please can explain?
i don't understand! their is a german translation already didn't it?

**Comment by xJustx** [comment]
Yep. But currently you can't translate it into other languages. Sorry!

**Comment by jief78** [comment]
@xJustx hello as you can see on an other issue i posted today #1140 
i did found the german translation and translated it to french; I created a method for it but,
what i need now is someone to create the checkbox calling my new method.
Can you give me a name ( other than @Ar1i since he is probably busy doing more important things ). 
thanks
