### ISSUE TITLE
Transfer problem vol 465845134564

### ISSUE THREAD

**Issue by alperemre** [Ar1i/PokemonGo-Bot#987]
My config auto transfer double pokemons enable maxd.p. : 1 max cp 600 max IV 65

program is not transfer some pokemons fix it please
![adsiz](https://cloud.githubusercontent.com/assets/20747873/17341079/9bd47718-58fb-11e6-87bf-60409df7c5fb.jpg)

**Comment by mazbron** [comment]
Same problem hahaha

**Comment by Skreetex** [comment]
same issue :/

**Comment by Ar1i** [comment]
Cmon guys, already wrote that like 10000 times.. Disable at the GUI: Keep Pokemon Which Can Be Evolved. Should fix that.

**Comment by Skreetex** [comment]
sorry habs nicht gesehen

**Comment by lordzxil** [comment]
^You the god.

**Comment by lordzxil** [comment]
^^Seriously I love you, transferring like 200 pokemon now haha

**Comment by alperemre** [comment]
Please look my config any tick Keep Pokemon Which Can Be Evolved ?

Bot is troubled vol 54687816135

**Comment by sargathus** [comment]
bot still keeping a lot of pokemen which is need to transfer but after i disable gui keep evolve pokemons thing its helps a alot

**Comment by mazbron** [comment]
Still not transfer even I disable: Keep Pokemon Which Can Be Evolved
![pokemon](https://cloud.githubusercontent.com/assets/9880408/17356518/208492dc-5982-11e6-8709-66446e17c16a.gif)
