### ISSUE TITLE
Using my all berries

### ISSUE THREAD

**Issue by KeePoFF** [Ar1i/PokemonGo-Bot#988]
[21:54:59] Used ItemRazzBerry. Remaining: 0. . Even for the lower pokemon is using razzberry. Is there way to make razzberry not to use? 

P.C. sorry for my bad english.

**Comment by UltraVLT** [comment]
There isn't yet.

**Comment by coolio818** [comment]
Please add it so you can disable the use of RazzBerrys because all mine go too... It's annoying so that when I actually go out and a decent Pokemon appears I can't use them :(

**Comment by elenex23** [comment]
set your inventory settings better then. Keep 30 razz only.
