### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by lanziii97** [Ar1i/PokemonGo-Bot#989]
The program needs net framework 4.5 but i have windows xp that supports only 4, what can i do? Is there another version?

**Comment by KeePoFF** [comment]
Just install windows above 7.. is there still ppl that use xp o.O

**Comment by lanziii97** [comment]
I only have an old computer

**Comment by danielalvenstrand** [comment]
I bet win10 would run on it though, but since winxp->win10 isn't a free upgrade I would recommend buying a new pc that already has win10 installed. You could buy one close to what win10 would cost and it would be better than what you have now it yours can't run win10. My recommendations.

**Comment by Ar1i** [comment]
Mhm, it will not work with 4.0 i am sorry..!
