### ISSUE TITLE
I need help ! 

### ISSUE THREAD

**Issue by Supershady** [Ar1i/PokemonGo-Bot#99]
How i get the Bot on the latest version .How do i compile the old version with the latest using VS15

**Comment by BerkanYildiz** [comment]
Hello,

- Download the bot [https://github.com/Ar1i/PokemonGo-Bot/archive/master.zip](here).
- Unzip it and open the project, using VS 15
![image](https://cloud.githubusercontent.com/assets/15068742/17221174/fbb3ec7a-54f2-11e6-9cf8-5ca4eafa201e.png)
- Build it by clicking on the "Start" button, at the top. ( Toolbar )
![image](https://cloud.githubusercontent.com/assets/15068742/17221228/45fac2b8-54f3-11e6-8d10-bb2262666b6f.png)
