### ISSUE TITLE
Cant catch anything. 

### ISSUE THREAD

**Issue by PokeDudeAlf** [Ar1i/PokemonGo-Bot#992]
I keep getting this issue but when I log in on my phone everything is fine
![whatswrong](https://cloud.githubusercontent.com/assets/20801636/17341954/a8873764-58bc-11e6-8fa4-1b10e92148d7.png)

[https://s31.postimg.org/987muja8r/whatswrong.png](url)

**Comment by JustPlaysDE** [comment]
Not our bot - download newest version: https://github.com/Ar1i/PokemonGo-Bot

**Comment by PokeDudeAlf** [comment]
This is the newest version from the link you shared.
