### ISSUE TITLE
no pokeballs? NOT soft banned

### ISSUE THREAD

**Issue by OGcpalm** [Ar1i/PokemonGo-Bot#993]
I am still farming pokestops and getting exp from them but can't catch any pokemon it says no pokeballs

**Comment by FrancYescO** [comment]
.... and do you have pokeballs ?

**Comment by OGcpalm** [comment]
if it is going to pokestops and farming them why shouldn't I ?

**Comment by gltzrsckchn** [comment]
Well, I got the same problems, but I've got 51 pokeballs.

**Comment by FrancYescO** [comment]
post screens to show logs

**Comment by jief78** [comment]
you're maybe full of other things so you can't get any pokeballs

**Comment by OGcpalm** [comment]
is there anyway to delete them? without logging in on my phone, cause I'm assuming that if I log in on my phone [ I live in canada ] and I'm farming in london I'll get softbanned?

**Comment by FrancYescO** [comment]
just set the max items in the guid when you start the bot.

**Comment by OGcpalm** [comment]
I just did that it didn't delete any items and is still not getting items from pokestops only exp

**Comment by FrancYescO** [comment]
so probably your item count < what have you set in the ui

**Comment by OGcpalm** [comment]
what do you recommend so I do not run into this problem

**Comment by jief78** [comment]
can you give us your items settings please

**Comment by OGcpalm** [comment]
50
50
50
125
0
0
125
50
20
50
125

**Comment by jief78** [comment]
maybe your problem is with the 125 potions!
i don't keep any potion or super potion only hyper

**Comment by OGcpalm** [comment]
potion and super potion are set to 0

**Comment by jief78** [comment]
sorry can you screenshot your config interface please because the file is confusing to me

**Comment by OGcpalm** [comment]
I just changed my config inside the GUI 3times but every time I re open the config [item file] nothing is changing.. but anyway here is the screenshot 
[img]https://i.gyazo.com/d4a2fe5e8e05c5745a9361c1f2563646.png[/img]

**Comment by jief78** [comment]
are you sure you saved it?
maybe try to hard change it in the file
lower both of your 125 and see

**Comment by OGcpalm** [comment]
just tried that as well, after opening the bot again the and starting it and re opening the config file it just getting reset back to
50
50
50
125
0
0
125
50
20
50
125

**Comment by FrancYescO** [comment]
cause we cannot know for sure if you have or not pokeballs, redefine values to match a max of 250

**Comment by OGcpalm** [comment]
nope still not working

**Comment by jief78** [comment]
sorry i don't know what is your problem because every thing works well with me.
was the bot opened when you changed the file. are you sure you saved and closed it?

**Comment by OGcpalm** [comment]
yes sir I did save and close

**Comment by jief78** [comment]
try deleting it and setting it again with the gui

**Comment by OGcpalm** [comment]
nope no luck

**Comment by FrancYescO** [comment]
the only way to understand more is to login with the app and get the list of items, if you wan't get softbanned wait some time...

**Comment by OGcpalm** [comment]
I really don't want to risk it this account is level 32 :(

**Comment by RevoP3** [comment]
just don't use gps so it couldn't know were you are

**Comment by OGcpalm** [comment]
how do I do this?

**Comment by FrancYescO** [comment]
disable it before opening pokemon go :P

**Comment by OGcpalm** [comment]
so logged into it on my phone and it says I have 22 pokeballs but still saying no pokeballs

**Comment by FrancYescO** [comment]
normal pokeball? post a screenshot of encountered pokemon and no pokeball message

**Comment by OGcpalm** [comment]
I just deleted the folder and re downloaded seems to be working so far

**Comment by elenex23** [comment]
see if you can close this issue OGcpalm. Also i suggest keeping only 10 and 10 and 150 of the pokeballs. 5 revive, 20 max revive, 30 hyper potion, 30 razz. I've kept low numbers and never have an issue. I visit way more pokestops then pokemon
