### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by d0ct0r87** [Ar1i/PokemonGo-Bot#996]
how do you use the latest build after update, I see that someone has stolen your code at the bottom and your only going to post the latest build and no source, so how do I launch the program now?

**Comment by UltraVLT** [comment]
Download the builds only folder with the rar included.That's all you need.

**Comment by d0ct0r87** [comment]
do i just drop the rar into the old folder?

**Comment by ShutUpPvP** [comment]
drop the rar into a new folder, unpack it, open the folder start the "PokemonGo.RocketAPI.Console"
And you're set.

**Comment by d0ct0r87** [comment]
I don't see any application file in there so how would i run it?

**Comment by JustPlaysDE** [comment]
Download Builds Only: https://github.com/Ar1i/PokemonGo-Bot/tree/master/Builds%20Only
.. and start the "PokemonGo.RocketAPI.Console.exe"

**Comment by d0ct0r87** [comment]
Cool that worked ty
