### ISSUE TITLE
New destination on the map

### ISSUE THREAD

**Issue by Lovassz** [Ar1i/PokemonGo-Bot#997]
Hi Ar1i!

Your app is awesome, I only miss one feature.
Can you add an option to set a new destination on the map?
Like it, we could use it to catch rare Pokemons nearby, found on other Pokemon tracker sites.
Thank you for your awesome bot, we love your great project.

**Comment by OGcpalm** [comment]
this is a suggestion no issue please post suggestions on high minded forums

**Comment by JustPlaysDE** [comment]
This is only for issues. Please post your suggestion here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/

**Comment by Lovassz** [comment]
Thank you for the link, I will write here.
